batch/batch/worker/worker.py
hail/python/hailtop/auth/tokens.py
hail/python/hailtop/tls.py
hail/src/main/scala/is/hail/services/tls/package.scala
tls/create_certs.py

Now the `HAIL_SSL_CONFIG_DIR` environment variable can point to any absolute path. It must contain a `ssl-config.json` file that contains relative paths to `HAIL_SSL_CONFIG_DIR` for the rest of the ssl config files.
Also allows `HAIL_TOKENS_FILE` in python, which was already implemented in Scala.

[tls] Make ssl configs use a relative path

---

ci/ci/build.py
ci/ci/ci.py
ci/ci/github.py
hail/python/hailtop/hailctl/dev/deploy/cli.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

Potential footgun but specifically limited to dev deploys. This allows you to explicitly exclude build steps when dev deploying. For example, `hailctl dev deploy -b … -s deploy_query --excluded_steps deploy_batch` would make sure that `deploy_batch` and any jobs only in the `deploy_batch` subtree are not run.
Thoughts?

[ci] allow dev deploy to forcibly exclude build steps

---

batch/batch/worker/worker.py

`get_log` wasn't an async function.

[batch] Fix extra await in JVM job get_log

---

hail/python/hail/expr/types.py
hail/python/hail/typecheck/check.py
hail/python/test/hail/expr/test_ndarrays.py

Was testing that we could run with newer pythons, encountered some warnings to clean up.
- We aren't supposed to use `collections.Sequence` anymore. It's `collections.abc.Sequence`. They said this wouldn't work in 3.9, but they decided to delay removal again to 3.10.
- `np.bool` is just the same as `bool`, so numpy has deprecated `np.bool`. 
- We deprecatd `hl.null` in favor of `hl.missing` a little while ago.

[query] Address some warnings

---

notebook/deployment.yaml
notebook/nginx.conf

The `notebook` and `workshop` services were incorrectly pointing to the python notebook app instead of its nginx proxy, which handles proxying to notebook workers. In #10250 I added back https to the notebook python app and accidentally changed the nginx -> notebook worker connection `https`, where it should not be. These combined meant that notebook was unable to proxy to notebook workers. I deployed this into default and verified that I can get to jupyter, and also run scale tests.

[notebook] fix notebook service to expose nginx and use http with workers

---

batch/batch/driver/main.py
batch/batch/front_end/front_end.py
batch/batch/worker/worker.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py
memory/memory/memory.py
query/query/query.py

Right now the query service is taking a long time to terminate and it seems it's waiting on a single task. We saw a similar thing happen with a zombie worker but found it difficult to attach a debugger into the process. This way if we ssh into the pod and send a `SIGUSR1` we can hopefully get some good information out.

[batch,query,memory] add signal handler to dump task stacktraces

---

ci/ci/ci.py
ci/ci/templates/batch.html

Batches that have a `pr` attribute now link back to the corresponding PR page. Also fixed a latent bug where we were only loading batches for a PR based on the PR number, so if we had multiple watched branches you could display batches for PRs of the same number across branches.

[ci] add link back to PR in batch view

---

hail/src/main/scala/is/hail/types/physical/PCanonicalDict.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalSet.scala

Rahul reported this failing on the following gnomad pipeline:
```
from gnomad.utils.vep import process_consequences
from gnomad.resources.grch37 import gnomad
gnomad_v2_exomes = gnomad.public_release("exomes")
ht_exomes = gnomad_v2_exomes.ht()
ht_exomes_proc = process_consequences(ht_exomes)
ht_exomes_proc._force_count()
```
No test case included, but this kind of error will be impossible soon
(when requiredness exists on EmitType, not SType/PType).

[query] Fix assertions in PCDict/PCSet constructors

---

hail/python/hail/docs/tutorials-landing.rst
website/website/website.py

The fix for Safari will take effect the next time the docs are deployed. In the meantime,
the docs are indeed downloaded, but Safari tells you there was a problem. If users navigate
to the Downloads directory, the file should indeed be present.

[website] minimal changes to enable downloading the tutorials.tar.gz

---

docker/Dockerfile.base
hail/python/dev-requirements.txt

This avoids confusing Docker cache behavior by baking the verison number into
the RUN command string.

[docker] use versioned URL for gcloud sdk

---

docker/requirements.txt
hail/python/requirements.txt

There is some version incompatibility issue waiting to hit us as soon as someone
triggers a rebuild of the base image (gcs does not properly pin fsspec).

[docker][query] use newest gcsfs

---

docker/hail-ubuntu/controller.sh
query/deployment.yaml
shuffler/deployment.yaml

I also fixed controller.sh to properly handle arguments with space. This syntax
is the Bash array syntax, AFAIK, it is the only way to properly save a command string.

[shuffler][query] dump hs_err_pid file on segfault

---

hail/python/hail/matrixtable.py

This mirrors other methods like `show`.

[query] prefer n_rows to n in MT.head

---

batch/batch/driver/gce.py

If instance name isn't active, look to see whether it existed in the database before printing an error message about an unknown instance.

[batch] cleanup error message for unknown instance

---

hail/python/test/hail/expr/test_ndarrays.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala

The old error message for matmul was impossible to read. This is much clearer.

[query] NDArray Matmul Better Error Message

---

hail/src/main/scala/is/hail/io/fs/HadoopFS.scala

This reduced the time to run `hl.hadoop_ls` on a glob that matches 1000 files in a GCS bucket from ~55s to ~10s. Still not as good as `gsutil ls -l`, which takes ~3s.
Related to #9895

[query] Parallelize HadoopFS.listStatus

---

hail/python/hail/docs/datasets/schemas/gnomad_annotation_pext.rst
hail/python/hail/experimental/datasets.json

Adds fixed gnomAD annotation-level pext Hail Table (see #9955) to datasets.

[datasets] add fixed gnomAD pext Hail Table

---

hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py

The new `.run` usage doesn't actually print the stdout/stderr stream when it fails.
I used this change to find the requirements.txt bug earlier today.

[hailctl] Don't parameterize safe_call on python version

---

hail/src/main/scala/is/hail/utils/Cache.scala

Avoid query-service races when looking at the cache.

[query] synchronize the code cache

---

hail/python/hailtop/batch/batch_pool_executor.py

While trying to fix some weird errors, I realized this was more complicated than necessary and, I
think, broken.
In the new implementation, a BatchPoolFuture is a thin wrapper around an asyncio.Future. Instead of
tracking the value and any exceptions manually, the BatchPoolFuture relies on asyncio.Future.
I think the diff is not very helpful, just look at the new, simpler implementation.
I also forgot to close the ServiceBackend, I now do that in the cleanup method that happens after all future complete.

[hailtop.batch] simplify BPE implementation

---

hail/python/test/hailtop/batch/test_batch_pool_executor.py

It seems that referencing a global function serializes a module named `test` which
does not exist on the worker.

[hailtop.batch] avoid serializing whole module in tests

---

hail/python/hailtop/utils/utils.py
hail/src/main/scala/is/hail/services/DeployConfig.scala
hail/src/main/scala/is/hail/services/package.scala

- google.api_core.exceptions.ServiceUnavailable is just 503 in an unnecessary new class
- Teach DeployConfig.socket to use retryTransientErrors.
- Also retry NoRouteToHostException (the host should *eventually* come into existence).

[services] more transient errors

---

batch/batch/worker/worker.py
hail/python/hailtop/batch/backend.py
hail/python/hailtop/batch_client/parse.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py
hail/python/test/hailtop/utils/test_utils.py

Tags and digests have no affect on whether an image is one of the hailgenetics
images that are stored in both GCR and DockerHub. This change ignores the tag and
digest when checking if we should warn about using DockerHub.
In doing this, I consolidated and made more robust our Docker-image-reference parsing.

[hailtop][batch] Fix DockerHub

---

libhail/src/hail/allocators.cpp
libhail/src/hail/format.cpp
libhail/src/hail/main.cpp
libhail/src/hail/query/backend/compile.cpp
libhail/src/hail/query/backend/compile.hpp
libhail/src/hail/query/backend/jit.cpp
libhail/src/hail/query/backend/jit.hpp
libhail/src/hail/query/backend/stype.cpp
libhail/src/hail/query/backend/stype.hpp
libhail/src/hail/query/backend/svalue.cpp
libhail/src/hail/query/backend/svalue.hpp
libhail/src/hail/query/ir.cpp
libhail/src/hail/query/ir.hpp
libhail/src/hail/query/ir_type.cpp
libhail/src/hail/query/ir_type.hpp
libhail/src/hail/runtime/runtime.cpp
libhail/src/hail/test.cpp
libhail/src/hail/test.hpp
libhail/src/hail/test_format.cpp
libhail/src/hail/test_value.cpp
libhail/src/hail/type.cpp
libhail/src/hail/type.hpp
libhail/src/hail/value.cpp
libhail/src/hail/value.hpp
libhail/src/hail/vtype.cpp
libhail/src/hail/vtype.hpp

Includes are grouped by source (system, LLVM, internal), the groups
themselves are then ordered stdlib, dependencies, internal. Ordering
within groups is alphabetical.
Also switch internal include style from #include <> to #include ""

[libhail] restyle includes

---

hail/python/hailtop/hailctl/dataproc/start.py

This is useful for falling back to Dataproc clusters in Batch pipelines, until Query is feature-complete.

[hailctl] add a `--service-account` parameter to `hailctl dataproc start`

---

docker/hail-ubuntu/Dockerfile

We can directly download the key and specify the repository. I used these instructions:
- https://wiki.debian.org/DebianRepository/UseThirdParty
- https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa
This builds in like 2 minutes rather than 4.
The frontend part avoids issues in downstream docker files where the installer might try to interact with the user. I noticed that some package was updated and now pulls in `tzdata` which asks you to select a timezone at install-time (if Debian frontend is interactive).

[hail-ubuntu] avoid software-properties-common, a huge package

---

hail/python/hail/docs/_static/annotationdb/annotationdb.html
hail/python/hail/docs/_static/annotationdb/annotationdb.js
hail/python/hail/docs/_static/datasets/datasets.html
hail/python/hail/docs/_static/datasets/datasets.js

Existing tables and matrix tables that we don't own/didn't create but are accessible via the datasets API are not always available on both GCS and S3 (e.g. pan UKB datasets are only on AWS S3), or are not available in an `eu` bucket on GCS (e.g. gnomAD datasets). 
This just adds a column `cloud: [regions]` to the tables on the datasets API and annotation DB docs pages to be more explicit about what datasets/versions are available on which cloud platform. 
So, for example, if a version of a dataset is in `gs://hail-datasets-us`, `gs://hail-datasets-eu`, and `s3://hail-datasets-us-east-1`, then under `cloud: [regions]` we would see `gcp: [eu,us], aws: [us]`.

[datasets] [annotationdb] add column for cloud/regions to tables in docs

---

hail/python/test/hail/experimental/test_annotation_db.py

The test was lacking asserts, so it didn't fail even though it wasn't right. The tables were missing keys.

[query] fix annotation db test

---

website/website/templates/base-foot.html
website/website/templates/base-head.html
website/website/templates/base.html
website/website/templates/dynamic-base.html

@nawatts points out that the docs are missing the font-awesome icons. This new website
stuff is confusing! Here is how to think about it going forward:
This PR is the *long-term fix*. It will not resolve the current production issue. The easiest fix
for that is to release a new version of Hail, which will generate a new version of the docs. That
new version will be compatible with the currently released `website`.
We have two phases: docs-generation-time and serve-time. Importantly, we always need to support the
*previously released documentation* with the current `main` `website`.
This PR makes things work like this:
At docs-generation-time (which happens every time we release a new version of the Hail package to
PyPI), Sphinx uses `dynamic-base.html` to build the docs website. Those …

[website] fix for issues raised in #10277

---

hail/python/hail/experimental/datasets.json
hail/python/hail/experimental/db.py

This just adds the appropriate `"annotation_db": {"key_properties": [...]}` entry to datasets.json for various Hail tables that were missing it.

[annotationdb] add missing key_properties for tables

---

hail/python/hailtop/hailctl/dataproc/start.py

`max-idle` and `max-age` have been available since 258 https://cloud.google.com/sdk/docs/release-notes#25800_2019-08-13
We already require >=285 https://github.com/hail-is/hail/blob/main/hail/python/hailtop/hailctl/dataproc/cli.py#L16

[hailctl] fix dataproc

---

hail/python/hailtop/aiotools/fs.py

The `//io/...` example you found now gives this:
```
ValueError: invalid file URL: //io/hail-ubuntu/Dockerfile.out, invalid netloc: expected localhost or empty, got io
```

[fs] LocalAsyncFS: validate file URL

---

hail/python/test/hail/expr/test_ndarrays.py

`exc` is a pytest exception holder. `exc.value` is the actual exception.
If pytest has to call `__str__(self)` on an object, pytest will automatically
truncate the result. However, pytest does not truncate `str` objects, that is
why I added a message to the assert and ensured that the message is already a
`str` before pytest sees it.

[query] provide a better error message in test_ndarray_solve

---

batch/batch/worker/worker.py
build.yaml
hail/python/hailtop/tls.py
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/backend/service/Worker.scala
hail/src/main/scala/is/hail/io/fs/FS.scala
hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
hail/src/main/scala/is/hail/io/fs/ServiceCacheableFS.scala
hail/src/main/scala/is/hail/services/Requester.scala
hail/src/main/scala/is/hail/services/Tokens.scala
hail/src/main/scala/is/hail/services/memory_client/MemoryClient.scala
memory/memory/client.py
memory/memory/memory.py
memory/test/test_memory.py
query/query/query.py
query/query/sockets.py

Reading function/contexts from GCS on query workers can contribute a significant portion of the runtime for small jobs. For a simple query like `hl.utils.range_table(10).collect()`, the jobs in the batch can range in time from 5-9 seconds depending on GCS latency.
This builds on #9484 to add write-through capability to `memory` and a `ServiceCacheableFS` in Scala. The cacheable FS reads/writes through `memory` and falls back to GCS, so in the good path the ServiceBackend writes the compiled function and contexts to `memory`, workers read inputs and write outputs exclusively from/to memory, from which the ServiceBackend reads the results. From small benchmarks in dev, this cuts down read times on the workers by ~30-40% compared to the worst case GCS latencies and roughly matches the …

[memory,query] Cache job function/context/outputs in memory service

---

hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh37.sh
hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh38.sh

Deleted the `gsutil cat` line, it wasn't doing anything because of that erroneous `/vep_data/Plugins.tar`. I don't think plugin needs to be included here, as it's in the docker image. 
Deleted the `gsutil cp`, as the file it referenced did not exist. Grabbed the 1var.vcf from the already copied loftee_data. 
It's not clear to me why we don't do the `1var.vcf` vep run stuff when using `GRCh38`.

[query] Vep Script Bugs

---

hail/python/hailtop/batch/batch.py
hail/python/hailtop/batch/docs/change_log.rst
hail/python/hailtop/batch/job.py

See https://hail.zulipchat.com/#narrow/stream/223457-Batch-support/topic/GOOGLE_APPLICATION_CREDENTIALS.20issue/near/235884329
This way we maintain some backwards compatibility where project doesn't have to be defined when using the Batch constructor unless you use the new functionality.

[batch] Make initializing GCS lazy when using PythonJob

---

hail/Makefile

I tried to do this with process substitution instead of xargs (which pays python/pip startup many times) but it's annoying to get that to work in makefiles.

[makefile] Fix install-on-cluster with requirements.txt dependencies

---

hail/python/hail/__init__.py

I do not fully understand why, but pytest sometimes imports Hail in threads
other than the main thread. Asyncio raises an error if you try to start an
event loop in a non-main thread.
This PR only runs nest_asyncio if there is already a running event loop. If
there is no running event loop, we do not need to run nest_asyncio anyway! If
there is a running event loop, we can modify it to be nest-able even from
a non-main thread.

[query] only run nest_asyncio if asyncio is in use

---

hail/python/test/hail/utils/test_utils.py

I have no idea how this ever worked. It should have triggered UTF-8 decoding errors.

[query] test utils needs to use binary I/O for binary data

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/lir/X.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

We will get errors about methods not being well formed if we don't define every label on an IEmitCode, so we have to consume each one even if we  don't do anything with it. 
I also moved `StreamLen` to `emitI`, because we were pointlessly switching back and forth from `EmitCode` to `IEmitCode`

[query]  StreamLen needs to consume elements

---

hail/python/test/hail/experimental/test_experimental.py
hail/python/test/hail/methods/test_pca.py
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala

Had to fix a bug where we were not binding global when lowering scans.

[query] Enable NDArray based PCA to run on local and service backend

---

ci/kaniko/Dockerfile

I do not know why but /etc triggers errors about:
```
archive/tar: write too long
```
Even though /etc is not very large (1.4MB). I suspect there is some symlink
or other nonsense which is breaking Kaniko.
The solution, after much trial and error, was simple: copy over directories that do not
cause issues and copy only the necessary files out of etc. A mix of speculation and
binary search lead me to the conclusion that /etc/ld.so.* are the only files necessary
from /etc for python to run correctly. These files tell the kernel how to link python3.7
to the various libraries on which it depends (which live in lib and lib64).
Anyway, I've tested that this image can build itself, so it should be good enough for
our purposes.

[ci] allow kaniko to build the kaniko image

---

ci/ci/build.py

Without `--cache-repo`, Kaniko uses `{image_name}/cache` (e.g. `gcr.io/hail-vdc/batch-worker/cache`). That works particularly poorly for all the test images which are `gcr.io/hail-vdc/ci-intermediate` and therefore don't share a cache with the default images.

[ci] all builds share the same cache repo

---

build.yaml
ci/test/resources/build.yaml

I think this was a red-herring caused by Kaniko blowing disk
trying to copy special files.
If this PR passes, then Kaniko is able to build itself with normal workers
and no extra disk, so there is no risk of another firedrill wherein
Kaniko is broken

[ci] remove Kaniko resource requirements

---

hail/python/test/hail/test_context.py
hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala

They're IR functions, not JVM functions

[query] Fix user function cleanup

---

hail/python/hail/ir/__init__.py
hail/python/hail/ir/ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/Compilable.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/linalg/GridPartitioner.scala

I mostly want this for debugging lowering on `LocalBackend`, but I added a SparkBackend implementation as well (goes through breeze and java literals, not going to be super performant).

[query] Add method to go from BlockMatrix to NDArray

---

benchmark/python/benchmark_hail/combine/combine.py
benchmark/python/benchmark_hail/compare/compare.py
benchmark/python/benchmark_hail/run/cli.py
benchmark/python/benchmark_hail/run/utils.py

This works by parsing log files for the message produced by TaskContext cleanup added in #10392.
A bit hacky, but it works!
```
Benchmark Name      Ratio     Time 1     Time 2   Mem Ratio   Mem 1 (MB)   Mem 2 (MB)
--------------      -----     ------     ------   ---------   ----------   ----------
union_p1000_p1000     116.0%     28.394     32.935      100.0%            1            1
union_p10_p100     114.8%     33.685     38.683      100.0%            1            1
compile_2k_merge     112.1%    253.023    283.740      100.0%            7            7
ndarray_matmul_int64_benchmark     110.1%      8.165      8.992      100.0%            1            1
shuffle_key_by_aggregate_bad_locality     108.9%    414.396    451.457      100.0%            4            4
shuffle_order_by_10m_int …
```

[benchmark] Add memory tracking to benchmarks

---

hail/python/hail/fs/google_fs.py
hail/python/hail/fs/local_fs.py
hail/python/test/hail/matrixtable/test_file_formats.py

I cannot enable these tests because both the local and service backend fail due to this error:
```
E               Java stack trace:
E               java.lang.AssertionError: assertion failed:
E                 ir key: [Ljava.lang.String;@28f4484b
E                 lowered key: WrappedArray()
E               	at scala.Predef$.assert(Predef.scala:223)
E               	at is.hail.expr.ir.lowering.LowerTableIR$.lower$1(LowerTableIR.scala:1101)
E               	at is.hail.expr.ir.lowering.LowerTableIR$.apply(LowerTableIR.scala:1118)
E               	at is.hail.expr.ir.lowering.LowerToCDA$.lower(LowerToCDA.scala:67)
E               	at is.hail.expr.ir.lowering.LowerToCDA$.lower(LowerToCDA.scala:36)
E               	at is.hail.expr.ir.lowering.LowerToCDA$.apply(LowerToCDA.scala:16)
E …
```

[query][fs] fix local and google fs, port test_backward_compatability

---

build.yaml

When we download files from GCS, they lose their permissions. Git complains and then the checkout fails.

[ci] fix make_pip_versioned_docs

---

batch/build-batch-worker-image-startup.sh

Tested this manually to make sure that the build-worker instance ran to completion (it fails on `apt-get update` currently)

[batch] update GPG key before apt-get update on build-worker instance

---

batch/test/test_batch.py
ci/ci/build.py
hail/python/hailtop/utils/utils.py

Multiplying by random number from 0 to 1 uniformly seems a bit too aggressive and harder for us, as
the programmers, to understand.
Consider that, one in a hundred uses of this function, we will get a sequence of random draws with
each number less than 0.1:
0.1, ..., 0.05, ..., 0.09
For that same sequence of draws, the sequence of delays, if started at 0.1, is this:
0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8, 25.6, 51.2
The next delay will be 60. Suppose the next draw is 1.0. We will have waited no more than ~5 seconds
[1], but our next delay is 60 seconds!
This PR proposes using
t = delay * random.uniform(0.9, 1.1)
which ensures that each delay is at least 90% of the expected delay. In the worst case scenario, by
the 11th attempt we have waited, in total, at least ~45 seconds.
I think this …

[utils] make sleep_and_backoff a bit more predictable

---

batch/batch/front_end/templates/batch.html
batch/batch/front_end/templates/batches.html
web_common/web_common/styles/main.scss

An onclick handler does not correctly handle command+click. Instead, we
convert the anchor to a block element (allowing it to have width and
height independent of its contents) and set the width and height to
100% of its container.

[batch] enable command-click on job id cell

---

hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala
hail/src/main/scala/is/hail/types/BlockMatrixType.scala

This was an easy one, since  we already  had `BlockMatrixBroadcast` lowered. All  `ValueToBlockMatrix` does is make a tiny 1x1 BlockMatrix that can later be broadcast. I kind  of think this is a weird  IR design and that we should actually have a  `BlockMatrixBroadcast`  that takes a value `IR` child instead of a `BlockMatrixIR`, but I'll experiment with that refactoring later. Trying to just get the current thing lowered.

[query] Lower BlockMatrix.fill

---

hail/src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala

now that `tcode` is gone/will be gone soon, we can also work on getting rid of `PCode.code`

[query] remove some registerCode/wrapArg calls

---

hail/python/hail/docs/_templates/layout.html

`curlylint` doesn't like logical blocks that produce incomplete html tags. This is the only instance in our codebase where we do that though. In either path of the if/else block we produce an open `a` tag and then close it out outside of the block. I reorganized it to avoid this and think it's actually more clear, and that creating open tags like this is a footgun to avoid since it's super easy not to close them (which we have had a lot).

[docs] rework layout template logic

---

hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/asm4s/package.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/test/scala/is/hail/lir/CompileTimeRequirednessSuite.scala

We need the negation folding as well due to the structure of how requiredness
is used in stypes/ptypes.

[query] Add compile-time constant bool analysis to generate requiredness

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/streams/EmitStream.scala

replace usages with toI.get instead

[query] Remove EmitCode.get

---

hail/src/main/scala/is/hail/types/physical/PArrayBackedContainer.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalArray.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SIndexablePointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SContainer.scala
hail/src/test/scala/is/hail/expr/ir/MemoryLeakSuite.scala

CHANGELOG: Fixed a memory leak triggered by `hl.literal(...).contains(...)
This bug is present elsewhere in the code generator, but the set
contains function is probably the worst place for it to happen.
This leads to a full copy of the set where the binary search
is executed.
The core problem was a bug in PArrayBackedContainer not casting
its codes properly, leading to the no-op coerce logic in PCanonicalArray
being bypassed in favor of the generic copy-the-world implementation of
`store`. The test I have added catches the memory leak, but now fails at
compile time at the assertion to `PCanonicalArray.store` instead.

[query] Fix bad memory leak triggered by set contains IR function

---

hail/python/hailtop/utils/utils.py

I think this should resolve the issues we were seeing with OnlineBoundedGather2.
Changes:
- cancelled tasks (those that raise CancelledError) are ignored (we don't propagate cancelled out of background tasks)
- Make sure all exceptions are either reraised or logged
- The first exception is raised out of exit, not call
- call raises PoolShutdownError if the pool is shutdown
- _shutdown doesn't signal _done_event until all cancelled tasks are complete
- call clears _done_event (not strictly necessary because exit checks pending, but seems safer)
- added copious docstrings

Clarify the behavior of OnlineBoundedGather2.

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala
hail/src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
hail/src/main/scala/is/hail/expr/ir/streams/EmitStream.scala
hail/src/main/scala/is/hail/types/TypeWithRequiredness.scala
hail/src/main/scala/is/hail/types/physical/stypes/SType.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SIndexablePointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SContainer.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
hail/src/test/scala/is/hail/expr/ir/GenotypeFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

EmitCodes and their EmitTypes, not ptypes, are to be the authoritative
source of requiredness information in the code generator.
This is the next step toward removing top-level requiredness from ptypes.

[query] Push through requiredness on EmitCodes

---

pyproject.toml

`pre-commit` passes changed files as arguments to `black`, which overrides its `exclude` flag. `force-exclude` excludes files even if they are passed explicitly as arguments.

[black] force-exclude excluded files to work with pre-commit

---

hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/RefEquality.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerToCDA.scala
hail/src/main/scala/is/hail/types/TypeWithRequiredness.scala

In this PR:
- I add `BlockMatrix.from_ndarray`. The implementation isn't great, it just basically just evals the ndarray and adds NDArray support to `ValueToBlockMatrix`. A better version wouldn't cross the Python / Java boundary at all, but I want something that works on all backends, so for now this will have to suffice. Any solution will at least need to communicate the shape of the ndarray back to python, since it's tracked in the block matrix type. 
- With this new method, I can now get many tests in `test_linalg.py` to run on the local / service backends. Most BM lowering was apparently untested before, so some bug fixes were necessary, including:
- Support requiredness analysis on BlockMatrix, even though the answer is always required. 
- Use `CompileAndEvaluate`  rather than …

[query] Create BlockMatrix from NDArray + Actually Running Lowering Tests

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/linalg/LinalgCodeUtils.scala

BLAS's DGEMM has an option for transposing input matrix, which is effectively just transposing. I've added support for this. It should save time and memory to not have to copy into column major format. 
Didn't end up making my linear regression benchmark much faster, maybe 3%. It's using a bit less memory too.

[query] NDArrayMatMul Emit Handles Row Major matrices without copying

---

hail/python/test/hail/methods/test_pca.py

I split it up into 5 separate tests, and I took away one of the 3 data sizes we test on, so it's faster and more easily split now. Let me know if you think there's other things we can remove/change without losing information.

[query] test_spectra was too slow

---

hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/asm4s/package.scala
hail/src/main/scala/is/hail/expr/ir/ArraySorter.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/SpecializedArrayBuilders.scala
hail/src/main/scala/is/hail/expr/ir/orderings/CodeOrdering.scala
hail/src/main/scala/is/hail/expr/ir/streams/StreamUtils.scala
hail/src/main/scala/is/hail/lir/X.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalDict.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalSet.scala
hail/src/main/scala/is/hail/types/physical/PCode.scala
hail/src/main/scala/is/hail/types/physical/stypes/SType.scala
hail/src/test/scala/is/hail/expr/ir/StagedBTreeSuite.scala

* push SingleCodeType through StagedArrayBuilder
* what was makeDependentSortingFunction, let's not do that anymore
* generate a staged quicksort instead of pass a virtual function
as a param and copying everything many times
* Break apart emitters for different IRs. They don't share that much.
Non-randomly assigning Chris because we talked about this design in the past.

[query] Renovate StagedArrayBuilder and sorting IR code generators

---

hail/src/main/scala/is/hail/asm4s/ClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/test/scala/is/hail/asm4s/ASM4SSuite.scala

[query] Remove DependentMethodBuilder

---

hail/python/setup.py

Make it easier to get to the change log from Hail's PyPI project page.

Add change log to project links section on PyPI

---

hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala

This PR lowers `BlockMatrixToTable`, which is the implementation of Hail's `BlockMatrix.entries`. It turns a `BlockMatrix` to a table of `(i, j, entry)` triplets.

[query] Lower BlockMatrix.entries

---

hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala

Before ndarrays, the two choices for children of `ValueToBlockMatrix` were array or float. This simplify rule hadn't been updated to reflect that ndarrays were now an option, so it was falling through to the float case when it saw an ndarray. 
By fixing this, I've gotten `test_paired_elementwise_ops` to work on lowered backends.

[query] Fixed BlockMatrixToValueApply simplify rule

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/MonoidAggregator.scala
hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
hail/src/main/scala/is/hail/types/physical/PCode.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SNDArrayPointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SSubsetStruct.scala
hail/src/test/scala/is/hail/expr/ir/StagedBTreeSuite.scala

There was basically nothing to do here after the latest changes.

[compiler] Remove PCode.code and EmitCode.v

---

benchmark/python/benchmark_hail/run/methods_benchmarks.py

I want to track performance of logistic  regression.  Currently, on my laptop these two benchmarks clock in at 11 seconds for Breeze and 62 seconds for ndarrays. Now that I have a metric I'll try and optimize.

[query] Added benchmarks for wald logistic regression

---

hail/Makefile

rsync -v prints every file that's being copied, which is way too much terminal noise. I feel like it didn't used to do this? Maybe mac update changed it.

Quieter rsync on make install

---

docker/requirements.txt
hail/python/requirements.txt

boto3 is the AWS Python client library.  This is for the upcoming S3AsyncFS.  FYI @tpoterba I also added it to the hail package requirements file because it will be exposed via `hailctl cp ...`, etc.

[docker] add Boto3 dependency

---

hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/functions/GetElement.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala

We had a lowering defined for `BlockMatrixSlice`, but it was barely tested and not correct. In this PR I rewrote it to be correct and enabled the python tests in `test_linalg` that check slicing behavior.

[query] Correctly lowered BlockMatrixSlice

---

hail/python/test/hail/helpers.py
hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala

We had an old   assert  that only  applies  to Spark, moved it  into the execute method.

Fixed arbitrary maps on BlockMatrix, added test

---

hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
hail/src/main/scala/is/hail/utils/richUtils/RichString.scala

Exceptional control flow is not great, but that's the rare
case here. This is faster than matching on the first few characters
instead of using exceptions.

[compiler] Fix bad performance in parseFloat{32, 64}

---

hail/python/hail/experimental/db.py

If a compatible annotation dataset can't be found in `index_compatible_version`, show the user the available versions and reference genome builds of the requested annotation dataset in the raised `ValueError`.

[annotationdb] more informative error when can't find compatible annotation dataset

---

datasets/extract/extract_1000_Genomes_30x_GRCh38_samples.sh
datasets/extract/extract_1000_Genomes_NYGC_30x_GRCh38.py
datasets/load/load_1000_Genomes_NYGC_30x_HighCov_samples.py
datasets/load/load_1000_Genomes_autosomes_NYGC_30x_HighCov_GRCh38.py
datasets/load/load_1000_Genomes_chrX_NYGC_30x_HighCov_GRCh38.py
datasets/load/load_1000_Genomes_chrY_NYGC_30x_HighCov_GRCh38.py
hail/python/hail/docs/datasets/schemas/1000_Genomes_HighCov_autosomes.rst
hail/python/hail/docs/datasets/schemas/1000_Genomes_HighCov_chrX.rst
hail/python/hail/docs/datasets/schemas/1000_Genomes_HighCov_chrY.rst
hail/python/hail/docs/datasets/schemas/1000_Genomes_Retracted_autosomes.rst
hail/python/hail/docs/datasets/schemas/1000_Genomes_Retracted_chrX.rst
hail/python/hail/docs/datasets/schemas/1000_Genomes_Retracted_chrY.rst
hail/python/hail/docs/datasets/schemas/1000_Genomes_autosomes.rst
hail/python/hail/docs/datasets/schemas/1000_Genomes_chrX.rst
hail/python/hail/docs/datasets/schemas/1000_Genomes_chrY.rst
hail/python/hail/experimental/datasets.json

Adds the [1000 Genomes NYGC 30x on GRCh38](https://www.internationalgenome.org/data-portal/data-collection/30x-grch38) autosomes, chrX, and chrY MatrixTables as `1000_Genomes_HighCov_autosomes`, `1000_Genomes_HighCov_chrX`, and `1000_Genomes_HighCov_chrY`. 
The `1000_Genomes_HighCov_autosomes` and `1000_Genomes_HighCov_chrX` datasets have phased calls. 
[Due to multiple issues](http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/GRCh38_positions/README_GRCh38_liftover_20170504.txt), the phase 3 GRCh38 versions of the current `1000_Genomes_autosomes`, `1000_Genomes_chrX`, and `1000_Genomes_chrY` datasets have been retracted. They have been renamed to `1000_Genomes_Retracted_autosomes`, `1000_Genomes_Retracted_chrX`,  and `1000_Genomes_Retracted_chrY`, respectively. The …

[datasets] add 1000 Genomes NYGC 30x on GRCh38

---

hail/python/hailtop/google_storage.py

CHANGELOG: Fixed writing files to GCS when the bucket name starts with a "g" or an "s"

[google_storage] Fix getting bucket name from uri

---

hail/python/hail/experimental/haplotype_freq_em.py

`hl.experimental.haplotype_freq_em` documents the order of input and output arrays in terms of A/a and B/b for reference and non-reference alleles for two variants.
https://github.com/hail-is/hail/blob/ff10ed660b3655c70204589b96e440115ed9063b/hail/python/hail/experimental/haplotype_freq_em.py#L13-L20
However, the underlying Scala code swaps A and B.
For example, the Python function's documentation says index 2 should represent AAbb but the Scala code treats index 2 as aaBB.
https://github.com/hail-is/hail/blob/1a861505c1fc2ea3c9d7b32a47be7af10d13907c/hail/src/main/scala/is/hail/experimental/package.scala#L50-L62
The currently documented order of outputs from the Python function seems to be based on the Scala code and thus does not match with the documented inputs.
@lfrancioli

Fix documentation for hl.experimental.haplotype_freq_em

---

build.yaml
hail/python/hailtop/aiogoogle/client/storage_client.py
hail/python/hailtop/aiotools/fs.py
hail/python/hailtop/aiotools/s3asyncfs.py
hail/python/hailtop/aiotools/stream.py
hail/python/test/hailtop/aiotools/test_copy.py
hail/python/test/hailtop/test_aiogoogle.py
hail/python/test/hailtop/test_fs.py

- Add S3AsyncFS which is implemented in terms of the AWS Python client library, boto3.  boto3 is sync (there is an in-progress async version but I decided not to use it to start).  The operations are nearly identical to GCS, except S3 supports explicit API requests for multi-part uploads (unlike GCS, where we implement it in terms of compose).
- The only tricky bit is `create`, which needs an async stream writer, but a synchronous stream reader that is passed to boto3.
- I split up test_aiogoogle.py.  The GCS specific tests stay there, and AsyncFS tests move to test_fs.py.
- Add S3 to the AsyncFS and copy tests.  I created an S3 bucket (hail-test-dy5rg) and test user credentials (added to K8s as test-aws-key).  I'm still trying to figure out how to give the rest of the …

[hailtop/fs] add S3AsyncFS

---

hail/python/MANIFEST.in

setup.py opens the requirements.txt file, because of this it must be in any source distribution.
This will become more relevant as we start distributing more (any) native code, reducing the number of platforms where `pip install hail` installs a binary distribution.
tested manually with:
```
make copy-py-files
cd build/deploy
python3 setup.py sdist
cd dist
tar xf hail-0.2.64.tar.gz
cd hail-0.2.64
python setup.py bdist_wheel
```

[hail] ensure source distributions (setup.py sdist) can build

---

hail/python/hail/__init__.py
hail/python/hail/docs/utils/index.rst
hail/python/hail/fs/fs.py
hail/python/hail/fs/google_fs.py
hail/python/hail/fs/hadoop_fs.py
hail/python/hail/fs/local_fs.py
hail/python/hail/utils/__init__.py
hail/python/hail/utils/hadoop_utils.py
hail/src/main/scala/is/hail/io/fs/HadoopFS.scala

Currently, the only way to check if Hail can read URLs with a given scheme (`gs`, `s3`, etc) is to attempt to read a URL with that scheme. However, the same exception type is thrown whether the scheme is not supported or the file doesn't exist or something else went wrong and the error message is the only way to determine what went wrong.
This adds a `hl.hadoop_scheme_supported` function, which returns a boolean indicating whether or not a URL scheme is supported.
Discussed on Zulip: https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/Get.20supported.20URL.20schemes
@johnc1231

Add hl.hadoop_scheme_supported function

---

hail/python/hailtop/aiotools/fs.py
hail/python/hailtop/utils/utils.py
hail/python/test/hailtop/aiotools/test_copy.py
hail/python/test/hailtop/test_aiogoogle.py
hail/python/test/hailtop/test_fs.py

This supresses "coroutines not awaited" messages in the case that a
bounded gather is cancelled before all subtasks have had a chance to
start.

[hailtop] bounded_gather2 takes partial functions

---

hail/src/main/scala/is/hail/types/physical/PType.scala
hail/src/test/scala/is/hail/annotations/StagedConstructorSuite.scala
hail/src/test/scala/is/hail/expr/ir/RequirednessSuite.scala

It's only used in tests, and is not something we wish to maintain as part of the ptype interface.

[compiler] Relegate PType.deepInnerRequired to tests

---

hail/src/main/scala/is/hail/expr/ir/Pretty.scala

Missed this when updating MatrixRead. Main goal
here is not to dump out JSON partition intervals
a bunch of times in the log files.

[compiler] Fix short printout for table readers

---

hail/build.gradle

See [discussion](https://hail.zulipchat.com/#narrow/stream/127527-team/topic/CI.20Deploy.20Failure/near/241944633). spring.io no
longer supports [direct, unauthenticated access to its repository](https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020).

[hail] remove repo.spring.io, which we was added to support hortonworks spark

---

hail/src/main/scala/is/hail/expr/ir/analyses/ComputeMethodSplits.scala
hail/src/main/scala/is/hail/types/physical/stypes/SingleCodeSCode.scala

Helps a little with benchmarks in whole stage codegen (which I'm working on in a different branch)

[compiler] Generate method splits at stream consumers

---

hail/python/test/hail/matrixtable/test_matrix_table.py
hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala

This change makes the `test_read_stored_cols` work via lowering.
I'm still unsure if we should support the cols/rows/entries subfolders
of a MT being valid tables themselves, but certainly it's incorrect
to describe the written cols table as having the same key as the MT
columns when it's unordered.
This change strips the col key off the tabletype generated in the
file, to reflect the ordering status.

[query] Fix table type of MT cols subfolder

---

batch/batch/driver/job.py
batch/batch/worker/worker.py
hail/python/hailtop/aiotools/tasks.py

Konrad ran into a problem where we started shutting down the worker because it was idle, but in between checking if there were any jobs still running and shutting down the site, a create job request came in. MJS was sent to the driver, but MJC was never sent because the worker shut down. The driver thought the job failed to schedule because the deactivate request was sent in before create job could return. The end result was Konrad's job still ran, but the database was left with an attempt that has a start time but no end time.

[batch] Don't create jobs while shutting down the worker

---

hail/src/main/scala/is/hail/asm4s/ClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SIntervalPointer.scala

This removes the single code requirement (st.nCodes == 1) for methods
returning SCodes.

[compiler] Use AsmTuple for multi-code SType return values

---

hail/src/main/scala/is/hail/expr/ir/agg/NDArraySumAggregator.scala
hail/src/main/scala/is/hail/linalg/LinalgCodeUtils.scala
hail/src/main/scala/is/hail/types/encoded/ENDArrayColumnMajor.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SNDArrayPointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SNDArray.scala

Add a codegen method `SNDArray.coiterate`, with signature
```
def coiterate(cb: EmitCodeBuilder, region: Value[Region], indexVars: IndexedSeq[String], arrays: IndexedSeq[(SNDArrayCode, IndexedSeq[Int], String)], body: IndexedSeq[SSettable] => Unit, deepCopy: Boolean): Unit
```
For example, the index expression `A[i, j] += B[j]` would be written
```
coiterate(cb, region, Seq("i", "j"), Seq((A, Seq(0, 1), "A"), (B, Seq(1), "B")), {
case Seq(a, b) => cb.assign(a, SCode.add(cb, a, b))
})
```
This generates a loop nest, with one loop per variable in `indexVars`. The inner loop is `indexVars(0)`, so that column major traversal is when index variables are increasing, as in `(A, Seq(0, 1), "A")`. Each index variable iterates over a dimension, with the size of the dimension inferred from its use. …

[query] tensor index expression code generator

---

build.yaml
hail/python/hailtop/aiogoogle/client/storage_client.py
hail/python/hailtop/batch/backend.py
hail/python/hailtop/batch/batch.py
hail/python/hailtop/batch/docs/api.rst
hail/python/hailtop/batch/docs/conf.py
hail/python/hailtop/batch/job.py
pylintrc

KC was experiencing extremely long batch creation times.
This change allows hailtop.batch to upload serialized python jobs 150-way parallel into GCS. I found that above 150-way parallelism, I didn't receive any further benefits. I can now upload KC's batch's jobs at about ~330 jobs per second. For 400k jobs, that will take ~20 minutes. I think the total batch submission should take less than an hour.
I lifted a few changes from the #10331. I had to put the AsyncFS on the backend though because the backend is the only object which has a close method.

[hailtop.batch] parallelize the upload of serialized functions

---

hail/python/hail/expr/functions.py
hail/python/test/hail/expr/test_expr.py

Currently, `hl.sorted` only accepts an array expression. If we want to sort a set or dict, we have to convert it to an array first.
```python
hl.eval(hl.sorted({1, 2, 3}))
hl.eval(hl.sorted(hl.array({1, 2, 3})))
```
Hail supports converting set and dict expressions to array expressions through [`hl.array`](https://hail.is/docs/0.2/functions/constructors.html#hail.expr.functions.array). This changes `hl.sorted` to also accept set and dict expressions and automatically convert them to array expressions.

[query] Allow hl.sorted to sort sets and dicts

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/test/hail/expr/test_expr.py

Currently, Hail cannot impute a Hail type for frozenset objects.
```python
hl.literal(frozenset(["foo"]))
```
This is an issue because frozenset is Hail's Python counterpart to SetExpression. Since Hail outputs frozensets from functions like `eval` and `collect`, users are likely to expect that Hail can also accept them as input.
```python
hl.eval(hl.set([1,2,3]))
hl.set([1,2,3]).collect()
```
One example use case where this issue pops up is annotating a table with all possible values of some field. Currently, the output of aggregating using `hl.agg.collect_as_set` cannot be directly used to annotate a table, it must be explicitly cast to a set.
```python
values = ds.aggregate(hl.agg.collect_as_set(ds.field))
ds.annotate_globals(values=values)
ds.annotate_globals(values=set(values))
```

[query] Impute Hail type for frozensets

---

hail/python/hail/utils/misc.py

Now get:
```
E           AttributeError: ArrayStructExpression instance has no field, method, or property 'select'
E               Did you mean:
E                   ArrayStructExpression inherited method: 'collect'
```
instead of
```
AttributeError: ArrayStructExpression instance has no field, method, or property 'select'
Did you mean:
ArrayStructExpression method: 'select'
ArrayStructExpression inherited method: 'collect'
```

[query] Fix magic collection struct errors

---

batch/batch/driver/instance_collection.py
batch/batch/driver/pool.py
batch/batch/utils.py
hail/python/hailtop/utils/utils.py

This PR fixes the problem where there were 3 free cores on an instance not in us-central. ci can not schedule jobs in other zones so ci could not progress.

[batch] Avoid CI deadlocks based on zone

---

hail/python/hailtop/utils/utils.py

```
body='{\\n \"error\": {\\n \"code\": 403,\\n \"message\": \"Quota exceeded for quota group \\'default\\' and limit \\'Queries per user per 100 seconds\\' of service \\'compute.googleapis.com\\' for consumer \\'project_number:859893752941\\'.\",\\n \"errors\": [\\n {\\n \"message\": \"Quota exceeded for quota group \\'default\\' and limit \\'Queries per user per 100 seconds\\' of service \\'compute.googleapis.com\\' for consumer \\'project_number:859893752941\\'.\",\\n \"domain\": \"usageLimits\",\\n \"reason\": \"rateLimitExceeded\"\\n }\\n ],\\n \"status\": \"PERMISSION_DENIED\"\\n }\\n}
```

[utils] Fix transient error for rateLimitExceeded

---

hail/python/hailtop/batch/job.py

CHANGELOG: Added the ability to unset batch-level default values and use the service defaults instead.

[hailtop.batch] Add ability to unset default resource values

---

atgu/atgu/atgu.py
auth/auth/auth.py
batch/batch/driver/main.py
batch/batch/front_end/front_end.py
ci/ci/ci.py
gear/gear/__init__.py
gear/gear/metrics.py
memory/memory/memory.py
notebook/notebook/notebook.py
query/query/query.py
website/website/website.py

We currently have a `@monitor_endpoint` decorator that we use to wrap aiohttp endpoints and produce prometheus metrics, but the same result can be achieved with fewer lines of code by using essentially the same wrapper as an aiohttp middleware. 
Separately, I fixed the wrapper to correctly catch and report on endpoints that raise exceptions, as well as keeping track of the number of concurrent connections.

[prometheus] make middleware function instead of per-route decorator

---

gear/gear/metrics.py

Non-existent routes have a `None` resource, so this was causing `500`s on requests that should have `404`'d

[prometheus] Dont 500 on bad URL

---

hail/python/hail/expr/functions.py

A user was getting an index out-of-bounds error on `cdf.values[idx]`. I can't reproduce it, but this should guarantee the index is in bounds, and is a simplification besides.

[query] fix _quantile_from_cdf bug

---

hail/python/test/hail/matrixtable/test_matrix_table.py
hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala
hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala

CHANGELOG: Fix crashes when writing/reading matrix tables with 0 partitions.

[query] Fix 0-partition matrix table writes.

---

batch/batch/driver/main.py
batch/batch/worker/worker.py

Whenever the batch driver shuts down we have some errors due to unclosed aiohttp `ClientSession`s. Deploying the driver in asyncio debug mode revealed that these sessions were in the `ComputeClient` and `LoggingClient`, which we don't call `close` on (and we don't use them as context managers). After this change I was able to delete my driver pod without any unclosed client session errors (though plenty of cancelled errors, which is a separate issue.

[batch] close compute and logging clients on shutdown

---

batch/Dockerfile.worker
batch/Makefile
batch/batch/driver/create_instance.py
batch/batch/worker/worker.py
batch/test/test_batch.py
build.yaml
ci/ci/build.py
ci/test/resources/build.yaml
dev-docs/batch-design.md
docker/.gitignore
docker/requirements.txt
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/process.py
hail/python/test/hailtop/batch/utils.py

This is the first step to removing batch workers' reliance on the docker daemon and docker in general, in favor of a lower level of abstraction that gives us finer control over resources on the worker like overlays and network namespaces, allowing us to shortcut and pre-configure some of the overhead that goes into running a job.
Currently, the high-level process for running a job involves communicating with the docker daemon to:
1. Pull an image for a job
2. Start a container from that image
3. Run the container
4. Delete the container and its associated resources
We offload some of these responsibilities into the worker code and onto [crun](https://github.com/containers/crun), a lightweight low-level runtime with the same API as `runc`, what docker uses to run containers. Once docker …

[batch] Run job containers with crun

---

hail/python/hailtop/hailctl/dataproc/start.py

A use case is to add the `cloud-platform` scope to allow accessing GCP secrets from within a dataproc script.

[hailctl] add `--scopes` parameter to `hailctl dataproc start`

---

hail/python/hail/docs/nd/index.rst
hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/expr/expressions/typed_expressions.py
hail/python/hail/ir/__init__.py
hail/python/hail/ir/ir.py
hail/python/hail/nd/__init__.py
hail/python/hail/nd/nd.py
hail/python/test/hail/expr/test_ndarrays.py

Added nd array map2 to correspond to existing scala nd array map2 ir. Also used map2 to facilitate writing user facing features hl.nd.maximum and hl.nd.minimum which echo np.maximum and np.minimum.

Ndarray map2

---

hail/python/hailtop/aiogoogle/client/compute_client.py

I think our default timeout of 5 seconds is why the disk operations are slow. The `wait` endpoint returns within 2 minutes. https://cloud.google.com/compute/docs/api/how-tos/api-requests-responses#handling_api_responses

[batch] Increase timeout for disk wait operation

---

hail/python/hail/expr/functions.py
hail/python/hail/utils/misc.py

We were getting warnings when tests ran that we were internally using deprecated methods still.

Removed uses of deprecated methods cond and null

---

hail/python/hailtop/aiogoogle/auth/credentials.py

This makes Hail Batch usable from a VM that's run under a service account, without requiring a JSON key.

[batch] add ability to fetch access tokens from instance metadata server

---

hail/python/hailtop/batch/job.py
hail/python/test/hailtop/batch/test_batch.py

CHANGELOG: Made failed Python Jobs have non-zero exit codes.

[hailtop.batch] Fix exit code for Python jobs

---

hail/python/test/hail/expr/test_ndarrays.py
hail/python/test/hail/methods/test_statgen.py
hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/linalg/BLAS.scala

Need to use dgemv when doing matrix vector multiplies. 
Makes `logistic_regression_rows_nd` ~12% faster

[query] Replace Matrix / Vector multiplies with DGEMV

---

hail/python/hail/expr/functions.py

Now that we have `starmap`, trivial to add `hl.map` over multiple lists, same way python map works.

[query] hl.map multiple lists

---

hail/python/hailtop/batch/backend.py

Prevents this output when no python jobs are present:
```
upload python functions: 0it [00:00, ?it/s]
```

[batch] Only print python job progress if there are python jobs

---

hail/python/hail/docs/functions/index.rst
hail/python/hail/docs/functions/numeric.rst
hail/python/hail/expr/__init__.py
hail/python/hail/expr/functions.py
hail/python/hail/methods/statgen.py
hail/python/test/hail/expr/test_math.py

A user reviewing the code pointed out that the branches of this function were backwards. Is there any easy way to construct a test that would catch this? Is `sigmoid` worth wrapping up into like `hl.math.sigmoid` or something? It seems like the name `sigmoid` refers to many things, maybe it should be `expit` like it apparently is in R and scipy?

[query] Fix the branches in logreg sigmoid

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_expr.py

It's possible to get a list of (key, value) tuples from DictExpression by casting it to an array.
```python
hl.eval(hl.array(hl.literal({"foo": 1, "bar": 2})))
```
This adds an `items` method to DictExpression that returns the same thing. This aligns with the `items` method of Python dicts and may be more intuitive/discoverable than casting to an array.
#assign compiler

[query] Add items method to DictExpression

---

hail/python/hail/methods/impex.py

Before
https://hail.is/docs/0.2/methods/impex.html#hail.methods.export_vcf
After
#assign compiler

Fix formatting for metadata parameter type in export_vcf docs

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_ndarrays.py

Summing ndarrays containing booleans along an axis is supposed to count how many booleans are in the answer. I just made this adjustment in python by mapping out of booleans.

[query] Support booleans when summing ndarrays

---

batch/batch/driver/create_instance.py
batch/batch/worker/worker.py

I dev deployed all *_image steps on a single worker running `main` and saw many fail with corrupted filesystems. I imagine this is because multiple jobs were extracting the same filesystem into the same place. The previous change to using a r/w lock for pulling and deleting images is correct, but we must lock on the image id when *extracting* the actual filesystem. With this change everything passed in my dev. The `BATCH_WORKER_IMAGE_ID` fix from before didn't actually work because of not properly escaping the `{` in the f-string.
I also moved the `docker rmi` step to be first in the image cleanup process because I imagine if docker refuses to remove an image we shouldn't remove it from our own cache either.

[batch] Only one pull image task should extract the root filesystem

---

batch/batch/worker/worker.py

Random hex strings, while valid, are a little dangerous to use as hostnames because some tools (Spark) could attempt to interpret an entirely numeric name as an IP address. This just avoids that danger entirely.

[batch] Prefix job hostnames with hostname_

---

batch/batch/worker/worker.py

Docker requires the `-f` tag to purge an image from its cache if multiple tags reference the same image ID. Checked to make sure that this couldn't accidentally disturb the worker container and added an assert because we should never even try to remove the worker image.

[batch] Use -f when removing Docker images

---

hail/python/cluster-tests/cluster-liftover-rg.py
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/io/reference/FASTAReader.scala
hail/src/main/scala/is/hail/io/reference/LiftOver.scala
hail/src/main/scala/is/hail/variant/ReferenceGenome.scala
hail/src/test/scala/is/hail/variant/ReferenceGenomeSuite.scala

[compiler] Lazily initialize reference genomes in generated code 

---

hail/build.gradle
hail/src/main/scala/is/hail/types/encoded/EArray.scala
hail/src/main/scala/is/hail/types/physical/PStruct.scala
hail/src/test/scala/is/hail/expr/ir/ETypeSuite.scala

The main change here is changing a 7 to an 8. I'm not sure how any lowered array anything ever worked. We should release after this goes in.

[query] Fix Array Encode

---

docker-build.sh

Right now if a `make ... deploy` step fails to build one of its images it continues (because the building now happens in `docker-build.sh`), which can result in running a service that expects an image not in GCR.

[docker] Make steps should fail if building an image fails

---

hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/package.scala

With StackStruct, now we don't allocate in the `MakeTuple` here.
Should deforest better, and be faster in general.

[query] Generate better code in lowering rule for MatrixAggregate

---

hail/python/hail/__init__.py
hail/python/hail/methods/qc.py
hail/python/hail/table.py
hail/python/hail/vds/__init__.py
hail/python/hail/vds/methods.py
hail/python/hail/vds/variant_dataset.py

Adds the split `VariantDataset` representation, where reference block data and variant data are contained in separate `MatrixTable` objects. Functions are accessible via the `hail.vds` submodule, e.g. `hl.vds.sample_qc(vds)`.

[svcr] add VariantDataset class and add functions to vds submodule

---

hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala

Before this change, all agg states for each intermediate aggregation phase are left in memory for the duration of the task.

[query] Fix memory management of tree aggregation intermediates

---

hail/python/test/hail/experimental/test_experimental.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala

Recur needs to emit its args into region 1, then copy them into region 2. Also the `emitI` result needs to emit into `loopRef.r1` before being copied into the main `region`.

[query] Fix loop memory management

---

hail/python/hail/expr/types.py
hail/python/test/hail/table/test_table.py

I verified the test failed with the same [error as KC's](https://discuss.hail.is/t/repartition-on-read/2148/2) before my change.

[query] fix read(..., _n_partitions) with missing keys

---

batch/batch/front_end/templates/job.html
batch/batch/front_end/validate.py
hail/python/hailtop/batch/backend.py
hail/python/hailtop/batch/globals.py
hail/python/hailtop/batch/job.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py

I made any command that is larger than 10KB is written to a file instead and is downloaded as an input file to be run (same as what we do for Python jobs). I also added a new field `user_code` that represents the user's code that they want to run versus the command we have Docker run. I formatted the `user_code` for Python jobs to show the actual function definition and the arguments used to call the function. It's probably not perfect (i.e. JobResourceFile), but better than nothing.

[hailtop.batch] Write out large commands to GCS for BashJobs

---

hail/python/hail/expr/functions.py
hail/python/hail/nd/nd.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/streams/StreamUtils.scala

Previously, we always made the stream into an array, then copied the array into the ndarray. Now we just insert the stream directly into the ndarray. This saves memory (~7% on the linear regression rows benchmark), and had no noticeable effect on speed in my experiments.

[query] Make ndarray from stream

---

batch/batch/worker/worker.py
batch/test/test_batch.py

The current implementation of piping into the worker's process and calling `readline` fails on log lines that are greater than 64KiB. This directs the container's stdout/stderr to a log file in their XFS project, so a job cannot blow up the worker with excessive logging. It then just calls `read` on the entire log file when requested, so there still is some issue of loading the log into memory, but no more so than currently exists.
The added test currently fails in default.

[batch] Write job logs to disk in user's XFS project

---

batch/batch/worker/worker.py

Follow-up on this zulip thread https://hail.zulipchat.com/#narrow/stream/219455-ServicesDev/topic/unexpected.20image.20cleanup.20err/near/247270652
If `extract_rootfs` creates the `rootfs_path` and then is cancelled while it's extracting the filesystem, following jobs will assume the rootfs is already extracted and run without a filesystem.. which isn't good.

[batch] Shield extracting the rootfs of an image

---

hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala

This will ensure a consistent order of reference genomes both in the
makeAddReferenceGenome and the addReferenceGenomes function that it
generates.

[compiler] Sort reference genomes by name in ModuleBuilder accessors

---

hail/python/test/hail/helpers.py

I changed this from 2=>1 in April of last year unintentionally while debugging
(it's easy to get interleaved prints/logs with 2 concurrent worker threads).
https://github.com/hail-is/hail/pull/8535/files#diff-bf51d09b286fddaa730b426824ccb12dac8b9032e0c88bde81882f3cb1423df8R14

[query] Increase test parallelism

---

batch/batch/driver/main.py

Right now, the label is showing up as `pool highmem` which is the str representation rather than the explicit name.

[batch] Cleanup prometheus instance collection labels

---

batch/batch/worker/worker.py

The current implementation of `Container.delete`,
```python
async def delete(self):
log.info(f'deleting {self}')
self.deleted_event.set()
await self.delete_container()
```
provokes a race between the `run` task and the `delete` task. The former sees the `deleted_event`, raises and jumps to `delete_container`, so both tasks might be trying to delete the container at the same time. This races here,
```python
if self.container_is_running():
try:
log.info(f'{self} container is still running, killing crun process')
self.process.terminate()
self.process = None
await check_exec_output('crun', 'kill', '--all', self.container_name, 'SIGTERM')
except asyncio.CancelledError:
raise
except Exception:
log.exception('while deleting container', exc_info=True)
```
where we might queue two `crun kill` …

[batch] Make Container.delete only set deleted_event

---

hail/python/hailtop/batch/batch_pool_executor.py
hail/python/hailtop/utils/utils.py

First error was we were not cancelling the batch on TimeoutErrors. I kept the interface to timeout on the client side rather than passing the timeout to the service spec. We can revisit this design at another point.
I also added another layer of tasks to make sure we were cancelling batches in the case that a submit failed. Some coroutines may have already succeeded and created a BatchPoolFuture, which we need to cancel. We need to use tasks instead of coroutines as the input to `gather` because on at least one failure we need to know if the submit task was completed successfully to extract the BatchPoolFuture to cancel it.

[hailtop.batch] Fix BatchPoolExecutor to cancel batches on errors

---

docker/requirements.txt
hail/python/hailtop/batch/batch_pool_executor.py

See https://github.com/erdewit/nest_asyncio/issues/11
Original error was this:
```
_________________ ServiceTests.test_single_task_resource_group _________________
self = <test.hailtop.batch.test_batch.ServiceTests testMethod=test_single_task_resource_group>
def test_single_task_resource_group(self):
b = self.batch()
j = b.new_job()
j.declare_resource_group(output={'foo': '{root}.foo'})
j.command(f'echo "hello" > {j.output.foo}')
>       res = b.run()
../test/hailtop/batch/test_batch.py:484: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
batch/batch.py:565: in run
run_result = self._backend._run(self, dry_run, verbose, delete_scratch_on_exit, **backend_kwargs)  # pylint: disable=assignment-from-no-return
batch/backend.py:475: in _run …
```

[docker] bump nest_asyncio version to fix transient error

---

prometheus/prometheus.yaml

The persistent volume is getting pretty full. We might need to expand it anyway if some of the new metrics are really big but we don't honestly benefit from long term retention so thought I'd try this first.

[prometheus] Set retention time to 15d

---

hail/src/main/scala/is/hail/expr/ir/Interpret.scala

It still thought it had `s`, an error message to print as a python traceback, rather than an error id like it has now.

[query] Fixed ArrayRef interpret rule

---

hail/python/hailtop/hailctl/dataproc/start.py

This should hopefully preserve stack traces for more exceptions during
execution.
See https://stackoverflow.com/questions/2411487/nullpointerexception-in-java-with-no-stacktrace
for more detail

[hailctl dataproc] Add OmitStackTraceInFastThrow to debug mode options

---

hail/src/main/scala/is/hail/expr/ir/PrimitiveTypeToIRIntermediateClassTag.scala
hail/src/main/scala/is/hail/types/virtual/TArray.scala
hail/src/main/scala/is/hail/types/virtual/TCall.scala
hail/src/main/scala/is/hail/types/virtual/TDict.scala
hail/src/main/scala/is/hail/types/virtual/TInterval.scala
hail/src/main/scala/is/hail/types/virtual/TLocus.scala
hail/src/main/scala/is/hail/types/virtual/TNDArray.scala
hail/src/main/scala/is/hail/types/virtual/TSet.scala
hail/src/main/scala/is/hail/types/virtual/TStream.scala
hail/src/main/scala/is/hail/types/virtual/TString.scala
hail/src/main/scala/is/hail/types/virtual/TStruct.scala
hail/src/main/scala/is/hail/types/virtual/TTuple.scala
hail/src/main/scala/is/hail/types/virtual/TUnion.scala
hail/src/main/scala/is/hail/types/virtual/Type.scala

This was unused, but was a performance nightmare -- the reconstruction of a single type triggered a full reallocation of the nested structure.

[compiler] Remove Type.fundamentalType

---

hail/src/main/scala/is/hail/asm4s/Code.scala

Leave old code commented out for debugging

[compiler] Stop calling `Thread.getStackTrace` in `cb.fatal`

---

hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/agg/NDArraySumAggregator.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala

`BlockMatrixAgg` is the IR node that sums along an axis. This PR lowers `BlockMatrixAgg`. It confusingly took different arguments from `NDArrayAgg`, in that it requested a list of axes you wanted to keep around, instead of a list of axes you want to sum out. Since the `sum` function in numpy, on hail ndarrays, and on hail `BlockMatrix` takes in a list of axes you want to sum out, I decided it would be better to make things consistent and changed the arguments to be consistent.

[query] Lower BlockMatrixAgg

---

hail/src/test/scala/is/hail/annotations/RegionSuite.scala

I don't know if this happens to you guys, but when I try to compile `RegionSuite.scala` I get Scala compiler warnings about how it's not cool to do `operations(3) == ("allocate", 64)`, since Scala can't tell if we mean:
`operations(3).==("allocate", 64)`
or 
`operations(3).==(("allocate", 64))`.
It was annoying me, so I added the extra parens so it would stop.

Added parens to address Scala warning

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/expr/expressions/typed_expressions.py

Previously, if you did:
```
x = hl.bool(True)
if x:
....
```
You'd get a message like: "Expressions do not have a static length", because in Python, truthiness is resolved by first checking if `__bool__` is defined, then checking if `__len__` is nonzero. This PR gives a better message suggesting that the user has in some way tried to coerce an `Expression` into a bool, and only shows the other error if someone does something that specifically needs the length.

Better warning about accidentally using Expression as a bool.

---

hail/src/main/scala/is/hail/expr/ir/GenericTableValue.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala

We want to make a `PartitionReader` that reads in lines of text, no notion of `PType` makes sense for this.
@tpoterba, does this make sense? I find the `Requiredness` stuff confusing, but I think this should do the same thing the old code did

[query] Partition reader no ptype

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/ir/streams/EmitStream.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala

The new tests in scala and python both catch this.

[compiler] Fix bug in streamJoinLeftDistinct with multiple key repeats.

---

hail/python/hailtop/batch/batch_pool_executor.py
hail/python/test/hailtop/batch/test_batch_pool_executor.py

A couple of fixes to batch pool executor to both get rid of orphaned running forever jobs and exception not retrieved errors:
- `asyncio.wait` does not retrieve results. I had to change waits to gathers with return_exceptions=True to get the behavior we want.
- A timeout error with `asyncio.wait_for` cancels the task automatically. Therefore, the previous code would never cancel the batch because the task was already "cancelled".
- I made `asyncio_cancel` idempotent and made sure we cancel the batch if the task has been cancelled to address the issue above. I added a check to see if the batch is running before cancelling. I'm ambivalent on whether this change is necessary.
- I added an explicit test now to make sure all batches are terminated. I think this is a good change, but the …

[hailtop.batch] More batch pool executor fixes

---

ci/ci/github.py

CI is updating a lot of PRs in its `update` loop that don't need to be updated. I've replicated and examined one such scenario in my own dev namespace but I feel like this visibility would be nice to have by default.

[ci] Add more visibility into the PR update cycle

---

hail/Makefile
hail/python/hail/docs/install/other-cluster.rst

Resolves #10747
I sshed into a VM and tried to do a clean install based on the issue raised above. As noted there, lz4 was missing from our cluster install docs. I also noticed `pip` returns a nonzero exit code if it tries to install something but doesn't find it, so I added some `|| true` to prevent a confusing error message. I also updated our examples to use Spark 3 by default.

More complete instructions for building hail on spark clusters

---

hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/streams/EmitStream.scala

The slight increase in complexity is worth it for the code improvement.
We now will clearly support early truncation when possible (and can
enable the inner join benchmark to go through whole stage codegen),
and will propagate requiredness correctly.

[compiler] Support all four join types in StreamJoinLeftDistinct

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala

This will make `TableHead` ~and `TableTail`~ lowered implementation performant enough to actually use.
EDIT: I was doing something wrong with `TableTail`, decided to just leave it for a follow up PR instead of having this sit.

[query] Better lowering for TableHead

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala
hail/src/main/scala/is/hail/expr/ir/MapIR.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala
hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
hail/src/main/scala/is/hail/lir/Blocks.scala
hail/src/main/scala/is/hail/lir/SplitMethod.scala
hail/src/main/scala/is/hail/types/TypeWithRequiredness.scala
hail/src/main/scala/is/hail/utils/package.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

Necessary for the big aggregate benchmark to pass (albeit more slowly) in benchmarks.

[compiler] Lots of compiler and code size performance improvements

---

ci/ci/github.py

There's a small CI feature where you can randomly assign someone from services and/or compiler team to review a PR by including a directive in the github PR body, e.g. #assign compiler. There's a slight bug where if the PR body is left blank, GitHub will report it as `None` instead of what I assumed would be "", which breaks the lines like `if ASSIGN_SERVICES in self.body` with the error that `None` is not iterable. This just inserts a guard against that.

[ci] Dont try to assign reviewers with empty PR body

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_expr.py

In python, `"hail" * 3` evaluates to `"hailhailhail"`. I've added support for this syntax to hail expressions by overriding `StringExpression.__mul__`, `StringExpression.__rmul__`, `Int32Expression.__mul__`, and `Int32Expression.__rmul__`. It was necessary to do all 4 in order to make sure all possible combinations of python values and hail expressions work.

[query] String multiplying

---

hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/functions/NDArrayFunctions.scala
hail/src/main/scala/is/hail/expr/ir/ndarrays/EmitNDArray.scala
hail/src/main/scala/is/hail/linalg/LinalgCodeUtils.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/types/physical/PNDArray.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SNDArrayPointer.scala

This adds a `constructUninitialized` constructor to `PCanonicalNDArray`. Now that we have interface methods that mutate an ndarray, there's no reason to force initialization of the data to happen inside the constructor. And there are plenty of uses, like out parameters for lapack methods, that just want an uninitialized ndarray.
Also, it seemed silly to be forced to memoize the new uninitialized ndarray before filling its data, when the constructor already had everything in locals, so I changed the ndarray constructors to return `SNDArrayValue`s.

[query] refactor PCNDArray constructors

---

batch/batch/utils.py

This PR eliminates this warning message:
```
This version of MySQL doesn't yet support 'sorting of non-scalar JSON values'
```
I tested this change in the SQL Fiddle and still got the correct answer. We could remove all non-varying fields from the group by, but decided to leave the other sortable fields as that is the SQL standard.

[batch] Don't use group by with a JSON array value

---

hail/python/hail/linalg/blockmatrix.py
hail/python/hail/table.py

Generate less code in to_matrix_table_row_major methods of table and BlockMatrix by using hl.map instead of python list comprehensions

[query] Prevent to_matrix_table_row_major IR from being linear in sample size

---

hail/python/hailtop/batch/backend.py

Not sure if this is unidiomatic but I always write little scripts that don't close the service backend and end with errors about unclosed sessions. This auto-closes a `ServiceBackend`.

[batch] Close service backend connections on deletion

---

hail/python/hail/methods/statgen.py

#10676 correctly points out a documentation error, which I am addressing.

[query] Fixed example in split_multi_hts warning

---

hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/linalg/BLAS.scala
hail/src/main/scala/is/hail/linalg/LAPACK.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SNDArray.scala

Adds support for using mkl, which is needed for some of the added lapack methods.
To use, install mkl, then set the environment variable `HAIL_MKL_PATH` to the directory containing the mkl dylib files. In particular, it should contain `libmkl_rt.dylib`.
On my laptop, I installed mkl through conda with `conda install -c intel mkl`, then set `HAIL_MKL_PATH=~/opt/miniconda3/envs/hail/lib/`.

[query] more lapack bindings, support using mkl

---

hail/python/hail/methods/statgen.py
hail/python/test/hail/methods/test_statgen.py

This PR adds support for using `"lst"` mode when lowering `logistic_regression_rows`

[query] Logistic Score Test support for lowered Logistic Regression

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_expr.py

Add operators for SetExpression, similar to those for [built-in sets](https://docs.python.org/3/library/stdtypes.html#set).
* `<=` subset
* `<` proper subset
* `>=` superset
* `>` proper superset
* `&` intersection
* `|` union
* `^` symmetric difference
#assign compilers

[query] Add set operators

---

batch/batch/worker/worker.py

Container overlays were previously only getting umounted when the container was deleted while running. This caused worker disk to fill up over time.

[batch] Always umount a container's overlay

---

hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/TableValue.scala
hail/src/test/scala/is/hail/expr/ir/LiftLiteralsSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

This is a trivial (non-semantic) refactor.

[compiler] TableIR.execute returns TableExecuteIntermediate

---

batch/batch/worker/worker.py

Scenario: A job is cancelled while its image is being pulled. The container overlay will never be made, so we should not try to unmount it in `delete_container`. This adds a flag to prevent that scenario.

[batch] Only umount a container's overlay if it was successfully created

---

infra/gsa_k8s_secret/main.tf
infra/gsa_k8s_secret/outputs.tf
infra/gsa_k8s_secret/variables.tf
infra/main.tf

This is an attempt to modularize / refactor our terraform code regarding google service accounts and kubernetes secrets. This doesn't add any new functionality.
Currently, our use of terraform is one flat file `main.tf` where we declare every `resource` in GCP that should exist. Examples of such resources are `google_service_account`, `google_service_account_key` and `kubernetes_secret`. For each of the accounts we create for various services, we end up creating these three resources (and sometimes IAM roles) in the same way. To abstract this, we can create a custom `module`, which is just a collection of resources, a set of inputs called `variables`, and a set of outputs. A module can then be "instantiated" using a `module` block in `main.tf`, providing it the source path of the module …

[terraform] Use a module for gsa and secret creation

---

hail/python/hailtop/batch/backend.py
hail/python/hailtop/batch/batch.py
hail/python/hailtop/batch/job.py
hail/python/hailtop/batch/resource.py
hail/python/test/hailtop/batch/test_batch.py

CHANGELOG: Fixes writing large commands to GCS
I made a couple of changes here:
1. Try and format a readable version of the code (including the user code) for the dry run mode
2. Fix `interpolate_command` was not idempotent. Thus large commands with resource files would fail.
3. Use paths directly in paths by doing a double interpolation. I'm worried about the speed of having to doubling parse the command with the regex, but I think the improvement in readability is a big win.

[hailtop.batch] Fix compile code and directly use resource paths in code

---

batch/batch/worker/disk.py
batch/batch/worker/worker.py

Sharing the worker's compute client can lead to prematurely closing the client session shared by the worker and disks. Just use compute clients instead.

[batch] Use separate ComputeClient per disk

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/agg/NDArraySumAggregator.scala
hail/src/main/scala/is/hail/expr/ir/functions/NDArrayFunctions.scala
hail/src/main/scala/is/hail/expr/ir/ndarrays/EmitNDArray.scala
hail/src/main/scala/is/hail/linalg/LinalgCodeUtils.scala
hail/src/main/scala/is/hail/types/encoded/EBlockMatrixNDArray.scala
hail/src/main/scala/is/hail/types/encoded/ENDArrayColumnMajor.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/types/physical/PNDArray.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SNDArrayPointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SNDArraySlice.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SUnreachable.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SNDArray.scala

~Stacked on #10770~
~Stacked on #10791~
This PR attempts to allow linear algebra codegen methods, like the LAPACK wrappers and the local whitening methods I'm working on, to defensively assert shape compatibility preconditions, without generating redundant runtime checks. (I always hate when we're pushed to avoid using code generation abstractions (in this case, just factoring code into smaller functions), because they generate worse code.)
The method is pretty simple. SNDArray shapes are now arrays of `SizeValue`, which is a sum type with cases `SizeValueDyn(Value[Long])` and `SizeValueStatic(Long)`. I don't think static sizes occur very often, but it was a simple addition.
`SizeValue`s can be compared statically with `==`, or at runtime with `ceq`: the former is true only if we can …

[query] Preserve static NDArray shape information

---

hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala

When I test this, I get
```
FatalError: IllegalFormatConversionException: d != java.lang.String
Java stack trace:
is.hail.utils.HailException: Encountered invalid type for format string %d: format specifier d does not accept type java.lang.String
at is.hail.utils.ErrorHandling.fatal(ErrorHandling.scala:15)
at is.hail.utils.ErrorHandling.fatal$(ErrorHandling.scala:15)
at is.hail.utils.package$.fatal(package.scala:78)
at is.hail.expr.ir.functions.UtilFunctions$.format(UtilFunctions.scala:168)
at __C12Compiled.__m15format(Emit.scala)
...
java.util.IllegalFormatConversionException: d != java.lang.String
at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793)
at …
```

[compiler] catch bad format exception

---

hail/python/hail/utils/java.py
hail/python/test/hail/expr/test_expr.py

My understanding of this now is that we have to backtick-escape any identifiers that aren't going to be valid java/python identifiers. That means we have to change the regex that identifies those to only accept things that start with a letter.

[query] Escaping field names that don't start with a letter

---

benchmark/Dockerfile

Also, removed deprecated 2020-resolver arguments. This was necessary to resolve `avro` dependencies as per: https://stackoverflow.com/questions/65233583/pip-install-cannot-resolve-the-version-from-artifactory

[benchmark] Upgrade setuptools to allow avro dependency

---

infra/gcs_bucket/main.tf
infra/gcs_bucket/outputs.tf
infra/gcs_bucket/variables.tf
infra/main.tf
infra/ukbb/main.tf

Yet Another Terraform Refactoring PR, this creates two simple modules:
- A gcs_bucket module to remove the redundancy of resources that we have across the batch-logs, query and test bucket
- A ukbb module which sets up the ukbb k8s resources. While this technically would allow us to reuse this, say in azure, it's more an attempt to tease it apart from the google-specific infrastructure so that we wouldn't have to. In short, it would be nice to organize things such that deploying hail with or without the ukbb site is as simple as choosing to include or omit a terraform module.

[terraform] Create modules for gcs_bucket and ukbb k8s resources

---

infra/README.md
infra/azure/README.md
infra/azure/main.tf
infra/azure/variables.tf

This adds the following terraform capabilities:
- A reserved public IP for the k8s gateway
- A container registry and pull access for the k8s cluster
- A [private link](https://azure.microsoft.com/en-us/services/private-link/) for the mysql database that makes it accessible on the k8s subnet. I haven't set up the config to use the database yet but ensured that the hostname for the database was resolvable from a pod on the cluster
I think this covers most of the azure specific resources that we need. Most of the rest of our terraform for gcp creating k8s secrets for the database config and various service accounts. I'd like to approach that in a single chunk to find out how best to abstract those into modules.

[infra] Add tf resources for gateways and container registry

---

gateway/gateway.nginx.conf

This is a pretty simple change, though the diff is a little bizarre. I don't want running a ukbb server to be a requirement of running a hail instance. Since the ukbb app is a special case in the way we deploy apps in k8s, we would render the gateway configuration server blocks with the logic:
- For each service, if it's not ukbb, render it the usual way
- Render the ukbb block
This is a very simple change to instead make the logic
- For each service, if it's ukbb render it the ukbb way, else render it the usual way
Together with the separation of the ukbb terraform into its own module in #10842, it should be easier to deploy hail without the ukbb app and simplify the bootstrap process.
This is currently running in hail-vdc.

[gateway] Include server block for ukbb if it is listed as subdomain

---

memory/deployment.yaml

See [the metrics explorer](https://console.cloud.google.com/monitoring/metrics-explorer?project=hail-vdc&pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22kubernetes.io%2Fcontainer%2Fcpu%2Frequest_utilization%5C%22%20resource.type%3D%5C%22k8s_container%5C%22%20metadata.user_labels.%5C%22app%5C%22%3D%5C%22memory%5C%22%22,%22minAlignmentPeriod%22:%2260s%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22crossSeriesReducer%22:%22REDUCE_SUM%22,%22groupByFields%22:%5B%22resource.label.%5C%22container_name%5C%22%22%5D%7D,%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22groupByFields%22:%5B%5D%7D%5D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLi …

[memory] substantially reduce cpu requests

---

memory/deployment.yaml

Memory's local storage is a simple cache, so it is safe for k8s to
evict it from the node if the node is underutilized.
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node

[memory] safe to evict

---

internal-gateway/deployment.yaml

It never uses more than 3% of its request.
https://console.cloud.google.com/monitoring/metrics-explorer?project=hail-vdc&pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22kubernetes.io%2Fcontainer%2Fcpu%2Frequest_utilization%5C%22%20resource.type%3D%5C%22k8s_container%5C%22%20metadata.user_labels.%5C%22app%5C%22%3D%5C%22internal-gateway%5C%22%22,%22minAlignmentPeriod%22:%2260s%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22crossSeriesReducer%22:%22REDUCE_SUM%22,%22groupByFields%22:%5B%22metadata.user_labels.%5C%22app%5C%22%22%5D%7D,%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22groupByFields%22:%5B%5D%7D%5D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLO …

[internal-gateway] reduce request for internal-gateway

---

hail/src/main/scala/is/hail/expr/ir/AbstractMatrixTableSpec.scala

Resolves #10843 
Now you'll see:
```
Hail version: 0.2.74-467a12fcbef9
Error summary: HailException: No file or directory found at gs://hail-datasets-us/annotations/THIS_PATH_DOES_NOT_EXIST
```
instead of the error about it not being a directory.

[query] Add a check that file exists before checking if it's a directory

---

build.yaml

I don't see any other mentions of this secret in the codebase.

[k8s] Remove unused hail-vdc-sa-key

---

hail/python/hailtop/aiotools/copy.py

This is needed to be able to bootstrap an Azure cluster.

[copy] Add AzureAsyncFS to the copy tool

---

batch/Dockerfile.worker
batch/Makefile
batch/batch/driver/create_instance.py
batch/batch/worker/worker.py
batch/build-batch-worker-image-startup.sh
docker/requirements.txt

This introduces a new version of the batch worker instance: one without `docker`. Instead we bring in `podman` to cover the functions of pulling images, extracting expanding filesystems from those images, and running the worker container. `podman` by default uses `crun` as its low-level runtime so we can get rid of the independent `crun` installation in the worker image. `podman` is daemonless and can be run rootless. For the most part you can't tell the difference, except this makes `podman` easy to run under multiple users with different caches per user. So if you ssh into a worker, be sure to `sudo` before any `podman` (or `crun`) command or else you might think nothing is running when in fact the worker is running under root's podman configuration. The podman/crun state directories …

[batch] Replace docker on the worker with podman

---

memory/Makefile

Removed the line to template `service-account-batch-pods.yaml` as it no longer exists and added the missing `default_ns.name` field to the jinja environment for the deployment template.

[memory] Remove unused template and fix jinja environment

---

auth/auth/driver/driver.py
auth/deployment.yaml

This removes unused google-specific environment variables from the auth modules.

[auth] Remove dead google config variables

---

hail/src/main/scala/is/hail/annotations/BroadcastValue.scala
hail/src/main/scala/is/hail/utils/ArrayOfByteArrayOutputStream.scala
hail/src/main/scala/is/hail/utils/prettyPrint/ArrayOfByteArrayInputStream.scala

I ran into issues when broadcasting a very large struct of ndarrays for a huge linear regression, where the the total size was more than `MAX_INT` bytes. To solve this, I've changed `SerializableRegionValue` to use `ArrayOfByteArrayOutputStream` and `ArrayOfByteInputStream`, which create nested arrays of bytes instead of just one array, removing any maximum length issues. 
PRing now for tests, also running benchmarks.

[query] Broadcast with array of array byte streams

---

hail/python/hail/vds/combiner/__init__.py
hail/python/hail/vds/combiner/variant_dataset_combiner.py
hail/python/hail/vds/variant_dataset.py
hail/python/test/hail/vds/test_combiner.py

Create a new class `VariantDatasetCombiner` that implements a simple state
machine for running a VariantDataset combiner pipeline from start to
finish.
The `VariantDatasetCombiner` structure contains pretty much everything the
old `experimental.vcf_combiner.run_combiner` method took as arguments:
`temp_path`, `output_path`, list of gvcf paths, etc.. What is new is the
addition of a `save_path` and `vds_paths`. The `save_path` is used as
a filesystem or object storage location to save the state of the
combiner so that it may be resumed. The vds paths implement the long
awaited mixed hail and gvcf inputs, that was never completed for the VCF
combiner. End users should not call `VariantDatasetCombiner.__init__`
instead preferring the free function new_combiner. The
`VariantDatasetCombiner` …

[vds] Implement resumable VariantDataset combiner state machine

---

ci/ci/build.py
ci/ci/environment.py
ci/deployment.yaml
ci/test/resources/deployment.yaml
ci/test/resources/statefulset.yaml

There are many global config fields that CI needs in order to template build.yaml jobs that are threaded through to CI with environment variables. However, these variables are never actually used by CI and they introduce some needless dependencies to run CI (you need a GCP_PROJECT, for example, even though CI doesn't care at all). Instead of setting specific environment variables for each field that build.yaml steps need, I instead mount the global-config (read-only) to the CI container and read in the whole thing. This does potentially expose more variables to the build.yaml environment than there were previously, but I argue that none of those should be sensitive anyway or maybe don't belong in the global-config (which shouldn't be sensitive). This in part makes the process of adding …

[ci] Mostly pass through global-config in CI instead of constructing from env variables

---

docker/genetics/Dockerfile

And they did not use a proper HTTP redirect.

[hailgenetics/genetics] KING is in a new place

---

batch/test/test_accounts.py
build.yaml

1. Delete the right tokens in build.yaml
2. Ensure all users of `get_billing_project_name`, including `test_deleted_open_batches_do_not_prevent_billing_project_closure` delete their billing projects, if they stil exist.
3. Be a bit more careful about try-finally in deletion.

[batch] ensure deletion of test billing projects

---

hail/python/hail/fs/google_fs.py

While working on Hail Query on Hail Batch, I frequently encountered transient
errors in rmtree when cleaning up temporary cloud directories. This change
ensures rmtree is resilient to such failures.

[hail.fs] make rmtree retry transient errors

---

build.yaml

This logic can happen at config time instead of runtime.

[build] Check cloud at config time in deploy config step

---

infra/azure/main.tf

I didn't test this yet -- do you want me to try the updated docs or should we wait until we redeploy the infrastructure next? Documentation is [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_security_group).

[infra] Add batch worker network security group

---

infra/azure/bootstrap.sh
infra/azure/main.tf

Since the batch workers will ultimately need to communicate with the database for CI jobs, it seems asymmetrical to put the private database connection in the k8s subnet. I've created a third small subnet just for the private database connection. Traffic across subnets is allowed by default so VMs in k8s and the batch workers should be able to access the database IP. This way we can put more restrictive rules in later (like batch workers should not be able to address VMs in the k8s subnet) without interfering with the database connection.
I've applied this change to the azure instance and verified that auth and the admin pod work with the new IP.

[infra] Put azure database in its own subnet

---

infra/gcp/README.md
infra/gcp/main.tf

The new terraform resource replaces the manual step in the README

[infra] Configure GCP peering routes in tf intsead of manually

---

ci/bootstrap.py
ci/ci/build.py
ci/ci/ci.py
ci/ci/environment.py
ci/ci/templates/pr.html
ci/deployment.yaml
infra/bootstrap_utils.sh

Another small effort toward getting `gs://` out of our code. I'll follow up with a PR that puts the prod CI bucket into terraform. The `test_storage_uri` field of the global config was introduced in #11014

[ci] Use storage uri for ci module

---

hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py

If stop raises a CancelledError or something, we should still retrieve exceptions
from the request task.

[aiogoogle] retrieve any exceptions from the request task

---

infra/gcp/README.md
infra/gcp/bootstrap.sh
infra/gcp/main.tf

This adds the oauth2 client secret as a terraform resource instead of uploading it by hand to k8s (though you still have to download it manually from the console. It also makes use of the `bootstrap_utils.sh` script that I introduced for azure for cloud-agnostic steps, trimming down the GCP instructions by a lot.

[infra] Make use of bootstrap scripts for GCP

---

build.yaml
ci/ci/build.py
infra/azure/outputs.tf
infra/gcp/main.tf
infra/k8s/main.tf
infra/k8s/variables.tf

#11005 Added support for the BuildImage job in build.py to work with `GOOGLE_APPLICATION_CREDENTIALS` or `AZURE_APPLICATION_CREDENTIALS`, but that doesn't mean that the backing secret behind those environment variables has to be different in each case. Ultimately, we would like the same k8s terraform to generate secrets for both clouds, so this changes both `gcr-push-service-account-key` and `acr-push-credentials` to just be `registry-push-credentials`. I have copied the `gcr-push-service-account-key` into a new secret with the appropriate name in `hail-vdc`.

[infra] Use the same name for azure and gcp registry push credentials

---

build.yaml

The terraform sets `gcp_project` in the global-config not `project`. A few weeks ago I did a manual copy & rename of `project -> gcp_project`, `zone -> gcp_zone` etc. This is the follow-through for that conversion.

[build.yaml] Rename global.project to global.gcp_project

---

hail/python/hail/docs/functions/stats.rst
hail/python/hail/expr/__init__.py
hail/python/hail/expr/functions.py
hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala
hail/src/main/scala/is/hail/stats/LinearMixedModel.scala
hail/src/main/scala/is/hail/stats/LogisticRegressionModel.scala
hail/src/main/scala/is/hail/stats/PoissonRegressionModel.scala
hail/src/main/scala/is/hail/stats/package.scala
hail/src/test/scala/is/hail/stats/StatsSuite.scala

This PR exposes the `lower_tail` and `log_p` parameters in `hl.pnorm`, `hl.qnorm`, `hl.pchisqtail`, and `hl.qchisqtail`, per this [feature request](https://hail.zulipchat.com/#narrow/stream/127634-Feature-Requests/topic/log_p.20option.20for.20pnorm.2Fpchisqtail). 
While I was at it I made a few other changes, including:
- Added `hl.dnorm` and `hl.dchisq` to allow for computation of normal and chi-squared probability densities.
- Exposed `mu` and `sigma` in `hl.dnorm`, `hl.pnorm`, and `hl.qnorm` so users can specify different mean/sd values if they wish. By default these functions will still use `mu=0` and `sigma=1` for standard normal densities/cumulative probabilities/quantiles if not otherwise specified by the user.
- Added `ncp` parameter to `hl.qchisqtail` to allow users to specify a …

[query] expose `lower_tail` and `log_p` parameters in normal and chi-squared statistical functions

---

hail/src/main/scala/is/hail/asm4s/ClassBuilder.scala
hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/asm4s/CodeBuilder.scala
hail/src/main/scala/is/hail/asm4s/GenericTypeInfo.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala
hail/src/main/scala/is/hail/expr/ir/Param.scala
hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala
hail/src/main/scala/is/hail/expr/ir/agg/AppendOnlyBTree.scala
hail/src/main/scala/is/hail/expr/ir/agg/ArrayElementLengthCheckAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/CallStatsAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/CollectAsSetAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/GroupedAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/StagedArrayBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/StagedBlockLinkedList.scala
hail/src/main/scala/is/hail/expr/ir/agg/TakeByAggregator.scala
hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/main/scala/is/hail/io/index/IndexWriter.scala
hail/src/main/scala/is/hail/types/encoded/EType.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala
hail/src/test/scala/is/hail/asm4s/ASM4SSuite.scala
hail/src/test/scala/is/hail/expr/ir/FunctionSuite.scala

~Stacked on #10906~
This PR refactors `MethodBuilder.invoke` and `EmitCodeBuilder.invoke(S)Code` to take/return values.
* `invoke` now takes a `CodeBuilderLike`. It is used in places where there is only access to a `CodeBuilder` (not an `EmitCodeBuilder`), so I had to use the generic interface, and had to move a couple methods on `EmitCodeBuilder` to `CodeBuilderLike`. I have never understood this Emit/non-Emit split; would be a great simplification if we could collapse it.
* This change pushed some (S)Code->(S)Value refactorings inside some aggregator implementations, which generate and invoke internal methods.
* I had to keep a version of `MethodBuilder.invoke` that doesn't take a CodeBuilder, for use in `ThisLazyFieldRef.get`. Will have to think more about how this should work when …

[compiler] (S)Code->(S)Value in invoke

---

hail/python/hailtop/auth/auth.py
hail/python/hailtop/auth/tokens.py
hail/python/hailtop/utils/utils.py

1. Lazily load the tokens on the end user machine because the first time someone logs in to the default namespace, they will have no tokens.
2. Teach `get_tokens_file` to default to the default end-user location.
3. Add a bunch of types which would have caught this error.

[auth] fix tokens

---

batch/test/test_batch.py
batch/test/test_dag.py
build.yaml
docker/requirements.txt
hail/python/hailtop/aiocloud/aiogoogle/session.py
hail/python/hailtop/batch/backend.py
hail/python/hailtop/batch/docs/service.rst
hail/python/hailtop/hailctl/config/cli.py
hail/python/test/hailtop/batch/test_batch.py
memory/test/test_memory.py

I did not fix the Hail version of the Service backend. I didn't quite understand where bucket was being used and it's not on the critical path for Azure.

[hailtop.batch] Deprecate bucket in favor of remote_tmpdir

---

hail/src/main/scala/is/hail/annotations/BroadcastValue.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/io/CodecSpec.scala
hail/src/test/scala/is/hail/expr/ir/EncodedLiteralSuite.scala

Support encoded values greater than 2GB.

[compiler] Refactor EncodedLiteral / TableLiteral to use multiple byte arrays

---

batch/batch/cloud/gcp/driver/create_instance.py
batch/batch/worker/worker.py

Currently we use the `10.0.0.0/15` range to assign local IPs to jobs on a worker. This is problematic if other resources in our infrastructure collide with this range. Since these are low address ranges it is quite likely that this could happen, and indeed has happened to me in a dev project where the database was assigned a `10.1.x.x` ip and CI jobs that require database access could not run. I don't have a particularly good reason to pick `10.150.0.0/15` as the new range other than I have not seen anything else use it.

[batch] Use higher subnet range for job subnets

---

build.yaml

Stacked on #11057. I tested the query string and made sure the list commands worked. However, I did not test the actual delete with xargs. This was copied almost verbatim from the gcp delete instances step. I'm pretty sure by not adding the `-x` flag at the top of the script, the password won't be printed to the command line output in the logs, but I'm not 100% sure.
Also, for this to work, the test-gsa-key needs to be able to delete VM and network resources. Do we have this in GCP as well? I guess we must in order for Batch to be able to remove its instances.

[build.yaml] Add delete azure instances build step

---

hail/python/hail/ir/base_ir.py

This can occur if stop is called before a garbage collection

[query] Do not attempt to remove vector references if there is no hail context

---

hail/build.gradle

#11016 Updated default hail version in Makefile, but build.gradle warns if you're not using 3.1.1. That's silly, everything should be 3.1.2 now.

Updated build.gradle to use Spark 3.1.2 as default version

---

hail/src/main/scala/is/hail/io/index/IndexReadIterator.scala
hail/src/main/scala/is/hail/io/index/IndexReader.scala
hail/src/main/scala/is/hail/io/index/MaybeIndexedReadZippedIterator.scala

To do this, expose the necessary methods to get the start and end bounds
of an interval queries position within the index. Then just add
a counter to the iterators.

[query] Use index counts rather than index iterator for reads

---

auth/auth/driver/driver.py
batch/batch/cloud/azure/driver/create_instance.py
batch/batch/cloud/azure/worker/instance_env.py
batch/batch/cloud/gcp/worker/instance_env.py
batch/batch/worker/instance_env.py
batch/batch/worker/worker.py
build.yaml

Mostly random bugs that didn't get flexed until trying to run CI jobs and batch tests within jobs.
- The IP addresses used for jobs immediately got out of sync with GCP and I needed to add an `internal.hail` entry to the worker and job's `/etc/hosts` so that default batch could submit to dev batch.
- GCP's metadata server and DNS nameserver are both 169.254.169.254. Azure has a separate IP address for the latter, so I added this configuration to the CloudWorkerAPI.
Something that's not addressed here is that I needed to comment out the resource requirements for build image jobs to make them run on standards. The common 2 vCPU / 10 Gi storage / 7.5 Gi Mem lands on standards in GCP but highcpu on azure, which doesn't have disks implemented yet. I'm not sure what the correct step forward on …

[batch] Fixes to get tests to start running on Azure

---

auth/auth/driver/driver.py

We put this in to remove auth's dependency on batch when batch couldn't run in azure and now this is no longer necessary.

[auth] Remove guard against creating trial projects in azure

---

hail/python/hail/experimental/write_multiple.py

I think this little change adds a lot of usability to the method.
You do not need to know how the names of the tables are constructed in the function.

Return paths from write_matrix_tables

---

hail/python/hailtop/aiocloud/aioaws/fs.py
hail/python/hailtop/aiotools/copy.py
hail/python/hailtop/aiotools/fs/copier.py
hail/python/requirements.txt

This brings the aggregate bandwidth from ~150MB/s to ~650MB/s. I'm still facing some issues with writing *to* AWS, but this eliminates a *ton* of TLS overhead. `uvloop` comes with a faster implementation of TLS.

[hailtop] substantially improve the performance of copy

---

build.yaml
ci/ci/ci.py
ci/ci/constants.py
ci/ci/environment.py
ci/ci/github.py
ci/deployment.yaml
infra/gcp/ci/main.tf
infra/gcp/ci/variables.tf
infra/gcp/main.tf
monitoring/monitoring/monitoring.py

This introduces the necessary pieces of infrastructure to run CI in GCP and a couple of small changes such that it can run as a secondary CI. This is currently failing because one of the secrets I introduce here in the terraform does not exist in hail-vdc. If you approve of the approach I can add it in manually. 
This adds a new CI terraform module that adds a CI bucket, sets some permissions for the CI service account and adds some K8s secrets like github tokens and the zulip config. This allows the terraform deployment to optionally include resources needed for CI. This was the best way I could think to introduce this infra with the least changes, but it's not what I want in the long term. Right now we have one monolithic root module that includes all the resources necessary to run …

[ci] Add CI infrastructure for testing outside hail-vdc

---

build.yaml

There might be more that we won't be able to run but saving for the gcs_bucket/gsutil steps, these are the steps that I found after a couple scans through that we can't expect to run currently on azure.

[build] Mark steps that cannot currently run on Azure as GCP only

---

batch/batch/batch_format_version.py
batch/batch/driver/job.py
batch/batch/front_end/front_end.py
batch/batch/worker/worker.py
batch/sql/change_azure_test_highcpu_pool.py
batch/test/billing_projects.py
batch/test/test_accounts.py
batch/test/test_batch.py
batch/test/utils.py
build.yaml
hail/python/hailtop/batch/backend.py

The coalesce is necessary right now because Azure has no resources so the result is None rather than 0. Since the cost is always 0, then the tests that test billing limits fail.
In addition, the tests that choose whether we select the cheapest machine won't work because all machines cost $0/hr right now due to no billing setup. Instead, we get the first pool alphabetically (highcpu). 
The reason for the database upgrade is because we're selecting the first pool alphabetically which is highcpu. The default settings don't leave enough disk space and thus require an external disk. To circumvent this, I just made the worker data disk size the same as in GCP -- 375Gi -- for the highcpu pool.

[batch] Make test_batch_* pass in Azure

---

notebook/deployment.yaml

This allows the notebook front end pod to be scheduled on an azure spot node.

[notebook] Tolerate spot instances on Azure

---

batch/Dockerfile.worker
batch/batch/worker/worker.py

Discovered in azure when it couldn't run the auth copy-paste token tests. We don't see this in google because we use Cloud DNS for resolving *.hail to internal gateway for private jobs (we use /etc/hosts and a public resolver for public jobs). In Azure I decided to forego azure dns and just use the /etc/hosts route for all of our jobs.

[batch] Add auth.hail to job /etc/hosts

---

build.yaml
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
infra/azure/main.tf
infra/azure/outputs.tf
infra/gcp/main.tf
infra/k8s/global_config.tf
infra/k8s/variables.tf
query/deployment.yaml

After this deploys and we re-run terraform, I can remove the deprecated entry.

[build.yaml] eliminate hail_query_gcs_path

---

build.yaml

Should fix this error:
```
azure.core.exceptions.HttpResponseError: The specified block list is invalid.
```

[build.yaml] Don't write to the same output location in test_java_*

---

ci/ci/ci.py
ci/ci/environment.py

This was the patch I had to apply to fix the 500s that we had yesterday in PR pages. The URI to URL rewrite enforced GCP which caused the 500. I removed the assertion but don't know yet the proper way to link to a **private** blob storage containers so I just return the URI. I looked at the [canonical URL for blob storage containers](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#resource-uri-syntax) but appears to only work for public containers. When I looked up how to get a URL for private containers, I get a lot of articles on SAS URLs that bake a token into the URL -- not what we want. We really just use this to link to the portal/console, but when I went to the portal the URL contains subscription-specific parameters …

[ci] Fix assertion that artifacts URI must be gs:// and fix deploy steps

---

build.yaml
ci/Makefile
ci/test/resources/build.yaml

- Allow ci-related secrets in azure
- remove `create_ci_test_repo.token` in `ci/Makefile` since that is not retrieved from the `ci-config` secret
- Use `standard` memory in the test build.yaml

[ci] Small fixes for non-default CI in azure

---

batch/test/test_batch.py
build.yaml
hail/python/hailtop/config/deploy_config.py
hail/python/hailtop/hailctl/config/cli.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

I added the capability for the deploy config to find the domain from setting it in the config.ini file. This way users only use `hailctl config set domain` rather than `hailctl dev config set domain`. In addition, we use this new capability to make a test in Batch work on Azure.
CC: @danking

[deploy_config] Add domain support to hailctl config

---

build.yaml

It depends on a number of GCS buckets that that we could transition to terraform/ABS in the future but thought it's not worth the time right now.

[benchmark-service] Mark as GCP only

---

ci/ci/build.py
hail/python/hailtop/utils/utils.py
infra/azure/ci/main.tf
infra/azure/ci/variables.tf
infra/azure/main.tf
infra/azure/outputs.tf

Implemented image untagging for image cleanup steps (like is done in GCR) for Azure. Since old layers still should be used for caching, this just removes the tag used for an image in a test build. We can then do something like [here](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auto-purge#run-in-an-on-demand-task) where you can purge untagged layers that are older than some number of weeks where we believe they're no longer relevant to the layer cache.
I also switched out the `registry-push-credentials` that CI uses to build images from the ACR admin login to CI's service principal and eliminated the admin login from the ACR terraform resource.
I dev deployed CI and manually verified after a deploy that a tag that was cleaned up no longer showed up in acr

[ci] Add image cleanup for PR runs in Azure

---

infra/bootstrap_utils.sh

Currently `docker/python-dill` images are untested and deployed manually, but used in tests and by our users. #11122 aims to both test and automatically publish those images on every release, but to move forward testing in Azure for now this pushes those images as part of the bootstrapping process.
Also removed the `export HAIL` line because operators should be able to define where their hail home is.

[bootstrap] Publish python-dill images to container registry

---

hail/python/hailtop/config/deploy_config.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

`config['domain']` is actually never None in `from_config` so I moved the fallback to the config.ini value of domain to the `from_config_file` function that currently hard-codes `hail.is` when there's no deploy config.

[batch] Fix defaulting to config.ini for domain

---

build.yaml

The `fails_in_azure` decorator uses the `HAIL_CLOUD` environment variable and it wasn't supplied to tests. The decorator itself looks fine.

[batch] Use cloud env var for hailtop tests

---

build.yaml

The whole point of my previous changes was to capture the exit code and
interpret it. I do not want to exit immediately when a command fails

[build.yaml] test_hail_fs: do not fail when java exists non-zero

---

auth/auth/driver/driver.py
build.yaml
ci/ci/ci.py
ci/ci/github.py
ci/create_initial_account.py
hail/python/hailtop/hailctl/dev/deploy/cli.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

These are the alterations that Jackie and I made to be able to add a developer account to a dev namespace. If the namespace isn't default then it grabs the credentials for the user from default instead of creating a new credential. I don't like that the extra config lives on the branch but this is how it is otherwise supported in bootstrap.py, and ultimately we should just use the auth account to hit the auth endpoint and delete the `create_initial_account` script entirely.

[auth] Support create_initial_user in dev deploy for dev namespaces

---

website/website/pages/index.html
website/website/styles/style.scss

I tried to achieve this within the CSS flex system, but I had trouble making the buttons equal-sized. The CSS grid system seemed more suited to our needs. The `grid-gap` property tells the browser to leave at least that much space between elements (the current code achieved that with this funky `a + a` rule). The key new rules are:
```css
grid-template-columns: repeat(auto-fit, minmax(130px, 1fr));
width: 100%;
```
The first rule tells the browser to put as many columns in the grid as possible, except that:
1. no column may be less than 130px (approximately the length of the phrase "Hail Query")
2. no column may occupy more than one "fraction" of the horizontal space (which is to say: each column gets an equal portion of the horizontal space)
The second rule tells the browser how much …

[website] fix mobile buttons

---

hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py

mistune 2.0.0 was released which breaks nbconvert. nbconvert 5.6.0 introduced
appropriate pinning. https://github.com/jupyter/nbconvert/commit/365683f40f85dc9304b6f1c23ca35eeb4d63b597.

[dataproc] fix notebooks

---

ci/create_initial_account.py

Argparse automatically transforms internal dashes of argument names into underscores for optional arguments, but [not for positional arguments](https://bugs.python.org/issue15125), so this currently breaks on line 87 with `args.login_id` not being a valid attribute. I tested that this change works with the minimal example:
```python
import argparse
def main():
parser = argparse.ArgumentParser(description='foo')
parser.add_argument('username', help='The username of the initial user.')
parser.add_argument('login_id', metavar='login-id', help='The login id of the initial user.')
args = parser.parse_args()
print(args.username, '\t', args.login_id)
main()
```

[bootstrap] Fix positional login-id argument

---

build.yaml
grafana/Makefile
grafana/deployment.yaml

The Makefile was hardcoded for GCP. Grafana is still currently able to be deployed through CI, this just changes the Makefile so it's not hardcoded to `gcp` and moves the gcp project from a Makefile-set value to one set through kubernetes so the Makefile is more cloud agnostic (doesn't reference a gcp project).

[grafana] Make deployable in Azure with Makefile

---

hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala

Not including a test since Patrick has an open PR that obviates this kind of error completely.

[query] Fix invalid string cast

---

batch/batch/driver/k8s_cache.py
ci/bootstrap.py

Importing from `batch_configuration` means that for this cache to be used you must define all environment variables that batch depends on. I severed this connection and fixed a use of the k8s cache in bootstrap.py

[batch] Remove K8sCache dependence on the batch environment

---

prometheus/prometheus.yaml

5G won't fit on our current AKS machine type. This doesn't lower the memory limit and basically ensures that prometheus will get its own node, and should be ok with that amount of memory.

[prometheus] Lower memory request to 4G

---

hail/python/requirements.txt

A user requested we loosen requirements on fsspec and tqdm. TQDM appears to
follow semver (https://github.com/tqdm/tqdm/issues/33). GCSFS is one of the
packages that specifically caused us versioning problems before. It does not
claim a versioning policy anywhere, but they do now pin fsspec versions, so
I think we can trust them to not break in that way, at least.

[hail] loosen requirements

---

docker/third-party/copy_images.sh

skopeo avoids downloading images that are already up-to-date, so it
is often a lot faster.

[infra] use skopeo for copying when its available

---

auth/auth/auth.py
infra/azure/modules/auth/main.tf

I can apply the terraform to azure after this merges and new auth pods are running.

[auth] Use client_secret instead of client_secret_v2

---

batch/batch/front_end/front_end.py
batch/test/test_accounts.py
batch/test/test_batch.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py
hail/python/test/hailtop/batch/test_batch.py
hail/src/main/scala/is/hail/services/batch_client/BatchClient.scala

This change allows batchces which fit in one bunch to be created in one
request instead of three. I found this saved a few hundred milliseconds
for batches with 1 job. This path is already well tested because most
of our test batches fit in one job.
To be clear: all the savings here is from avoiding two round-trips to front-end.

[batch] introduce create-fast

---

hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala

Had to fix this:
```
val base = Literal(TStruct("1" -> TInt32, "2" -> TInt32), Row(1,2))
val ir4 = InsertFields(InsertFields(base, Seq("3" -> I32(0), "4" -> I32(1)), None), Seq("3" -> I32(5)), None)
```
which was getting simplified to:
```
InsertFields(base, Seq("4" -> I32(1), "3" -> I32(5), None)
```
which changes the order of the fields. Now I explicitly construct a `fieldOrder` to remedy this.

[query] Fix insert fields simplify bug

---

batch/batch/cloud/azure/driver/resource_manager.py

Looking at the logs, I think these two new states are because we added the log analytics agent based on when the PR merged and the absence of these errors before December 10th.
```
Unknown azure statuses [{'code': 'ProvisioningState/updating', 'level': 'Info', 'displayStatus': 'Updating'}, {'code': 'PowerState/running', 'level': 'Info', 'displayStatus': 'VM running'}] for instance batch-worker-default-standard-166xu
```

[batch] Add updating provisioning state in Azure

---

gear/gear/clients.py
hail/python/hailtop/aiocloud/aioazure/__init__.py
hail/python/hailtop/aiocloud/aioazure/credentials.py
hail/python/hailtop/aiocloud/aioazure/fs.py
hail/python/hailtop/aiocloud/aiogoogle/__init__.py
hail/python/hailtop/aiocloud/aiogoogle/client/__init__.py
hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py
hail/python/hailtop/aiotools/fs/__init__.py
hail/python/hailtop/aiotools/fs/fs.py
memory/deployment.yaml
memory/memory/memory.py

I also added factories for Google and Azure so that we only
check the global-config cloud setting once, not repeatedly
every time we create an AsyncFS.

[memory] implement azure support

---

batch/test/test_accounts.py
hail/python/hailtop/batch_client/aioclient.py

Lines 381-390 had a real bug: we re-used the "b1" and "b2" variables for the rest of wait which is a dictionary, not a true handle to the batch. I went ahead and fixed all the mypy / pylons issues I found in this file.

[batch] address some pylint issues

---

ci/ci/build.py

I mistakenly assumed in #11159 that _all_ dependencies of a requested step should run, but in fact `run_if_requested` steps can be dependents of normal steps.

[ci] Dont add requested step dependencies that are run_if_requested

---

build.yaml
hail/Dockerfile.hail-pip-installed-python38

Python 3.6 is EOL: https://endoflife.date/python
Let's switch to checking against 3.7 and 3.8.

Stop checking against Python 3.6

---

gear/gear/clients.py
memory/memory/memory.py

1. I taught `get_or_add_user` to serialize loading of a single user's secrets
from kubernetes. The old code would issue multiple requests in parallel for
a user not yet in `users`.
2. The whole situation with the worker pool and the files in progress set did
not seem right to me. If a write comes in, we create a future corresponding
to the write and store the future in a dictionary. If a read comes in, we
first check redis, then we check if there is already a write or read of cloud
storage in progress. If there is no write nor read in progress, we initiate
a read. Before a read or write completes, it removes itself from the in-progress
files (future reads will now see the file in redis). Writes are permitted to
overwrite other writes that are already in progress.

[memory] several fixes

---

hail/python/hailtop/__init__.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/hailctl/dataproc/deploy_metadata.py
hail/python/hailtop/hailctl/dataproc/start.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/time.py
hail/python/hailtop/utils/tqdm.py

tqdm.notebook and pkg_resources take .55s and .37s to import, respectively. humanize imports pkg_resources which is why that is moved to. Moving these out of the top level improve cold-start time from 1.5s to .5s, and never even need to be imported for invocations such as `hailctl config list`, whose runtime is entirely import time.

[hailctl] Move slow imports out of the top level

---

hail/python/hail/docs/getting_started_developing.rst
hail/python/hail/docs/install/linux.rst
hail/python/hail/docs/install/macosx.rst
hail/python/hail/docs/install/other-cluster.rst
website/website/pages/index.html

I also fixed a reference to the JDK. Users do not need `javac` and friends, just a JRE (i.e. `java`).

[query] include JRE 11 as an acceptable Java version in the docs

---

ci/ci/github.py

What level of confidence do we need in this? Definitely not something our CI test suite supports.

[ci] Track all hail CI statuses and merge only when they all pass

---

ci/ci/github.py

CI is currently erroring on line 555 because when it starts up `last_known_github_status` is empty. Pre #11156, `last_known_github_status` initialized to `None` so using `get` here should have the same effect, and allow CI to post statuses to github.

[ci] Allow for last_known_github_status to be empty

---

hail/src/main/scala/is/hail/expr/Parser.scala
hail/src/main/scala/is/hail/utils/ParseTrieNode.scala
hail/src/main/scala/is/hail/variant/ReferenceGenome.scala

Improve the parse trie to use iteration instead of parser recursion.

[query] Fix performance of parse_locus_interval

---

ci/Makefile

I think this was missed when we pulled in buildkit to our own container registry.

[ci] Fix buildkit make target

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala
hail/src/main/scala/is/hail/expr/ir/streams/EmitStream.scala

Make sure result of `storeEmitParam` doesn't contain any references to the parameter, since it may be used in a different function due to method splitting.

[query] fix storeEmitParam

---

hail/python/hail/methods/qc.py
hail/python/hail/utils/__init__.py
hail/python/hail/utils/misc.py
hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py

Grace requested this for gnomAD purposes. In Azure, we can determine this
using the classpath or envionrment variables (the env var is only available
inside Jupyter). In GCP, I added an environment variable to our Spark env
/ Jupyter env.

[query] provide hail.utils.guess_cloud_spark_provider

---

hail/python/hailtop/hailctl/batch/batch_cli_utils.py
hail/python/hailtop/hailctl/batch/billing/list_billing_projects.py
hail/python/hailtop/hailctl/batch/list_batches.py

- Add make_formatter (in batch_cli_utils.py) options for csv, tsv, grid, and orgtbl
- Refactor list_batches.py to always use result of make_formatter
- Changed default format for `hailctl batch list` to grid

[hailctl] add support for table format for hailctl batch billing list

---

hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

Allow the default value to be controlled by a context flag.

[query] Make TableKeyByAndAggregate bufferSize parameter required

---

hail/python/hailtop/hailctl/dataproc/connect.py

gettempdir returns the system/Python temporary directory. If multiple
chromium processes are launched with the same user data directory, the
the process is reused. Because of this, new proxy settings won't be
picked up if the directory is reused. So we use a random identifier for
the chromium data directory.
Co-Authored-By: Dan King <daniel.zidan.king@gmail.com>

[hailctl] Use a unique temp dir for starting browser in connect

---

batch/batch/cloud/azure/driver/create_instance.py
batch/batch/cloud/gcp/driver/create_instance.py
batch/batch/worker/worker.py

This rule that we add per job network namespace
> iptables -w {IPTABLES_WAIT_TIMEOUT_SECS} --append FORWARD --out-interface {self.veth_host} --in-interface {self.internet_interface} --jump ACCEPT
is functionally equivalent to this single line 
> iptables --append FORWARD --in-interface $INTERNET_INTERFACE --destination 172.20.0.0/15 --jump ACCEPT
so better have 1 rule than O(slots) rules.
It would be nice to eliminate the one remaining rule that we append per-network namespace. Without that rule [this test](https://github.com/hail-is/hail/blob/9da1c759efe9fcbbd9ad02ee7c8bf725974270e9/batch/test/test_dag.py#L117) will fail because the iptables rules won't allow `curl $HAIL_BATCH_WORKER_IP:$HAIL_BATCH_WORKER_PORT` from inside the job container. The request leaves the job's network namespace …

[batch] Simplify iptables rules for worker network namespaces

---

hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

I had a brief worry that the key distinctness analysis didn't handle missing keys correctly, so I added some tests. It does seem to work so that's good.

Test missingness comparisons for distinctly keyed

---

hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/ComparisonOp.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitStreamDistribute.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerDistributedSort.scala
hail/src/main/scala/is/hail/expr/ir/orderings/CodeOrdering.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/lowering/LowerDistributedSortSuite.scala

This PR:
- Introduces `StructComparisonOp`, a subclass of `ComparisonOp` that is just for comparing structs. They have an array of sort fields for this purpose.
- Extends `StreamDistribute` to take in a `ComparisonOp`, so that it doesn't just assume data sorted in ascending order.
- Updates `LowerDistributedSort.scala` to actually use the `SortFields` that get passed into it, allowing for arbitrary sort orders.

[query] New Shuffler with Arbitrary Sort Order

---

build.yaml
hail/Makefile
hail/scripts/test-dataproc.sh

test-dataproc was taking over an hour, for two reasons:
1. Starting two vep clusters sequentially is slow.
2. A very small cluster was working on submits that sometimes had 10k partitions.
To solve this, I've:
1. Split test-dataproc into test-dataproc-37 and test-dataproc-38
2. Added a few preemptibles to cluster create script.

[build] Parallelize test-dataproc

---

build.yaml

Correcting an oversight from #11273 
Probably we should test that all build.yaml dependencies exist in the future (Services team seems to be replacing build.yaml with something new?)

[query] Update deploy to depend on new test dataprocs

---

hail/python/requirements.txt

Pandas 1.4 drops support for Python versions before 3.8.
As a user of python 3.10, having no pre-built pandas or pandas that did
not compile due to changes in the python c-api was very painful.

[query] upgrade pandas to >=1.3.0,<1.4.0

---

hail/python/hail/plot/plots.py

Struct fields are not mutable, so the log argument of hl.plot.histogram would never work. Also have to handle the case where there are 0s

[query] Fix old hl.plot.histogram log argument

---

hail/python/hail/docs/datasets/schemas/gnomad_chrM_sites.rst
hail/python/hail/experimental/datasets.json
hail/python/hailtop/hailctl/dataproc/start.py

I noticed that the gnomAD mitochondria datasets were pointing at the `gs://gnomad-public-requester-pays` bucket. The Google Cloud Public Datasets version should be up to date now.
Also updated the documented schema for chrM sites. Some information about those changes is available in the gnomAD change log: https://gnomad.broadinstitute.org/news/2021-08-rename-filter-in-mitochondria-dataset-and-minor-format-changes/.
And finally, since these were the only two datasets that reference `gnomad-public-requester-pays`, removed `gnomad-public-requester-pays` from the list of annotation DB buckets used by `hailctl dataproc`.

Update location and schema for gnomAD mitochondria datasets

---

hail/python/hailtop/hailctl/dataproc/start.py

CHANGELOG: hailctl dataproc now produces clusters which are not known to be vulnerable to log4j exploits as of 2022-01-22.
More details at https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-2.0.

[hailctl dataproc] Address the *third* log4j vulnerability

---

batch/batch/cloud/azure/driver/create_instance.py
devbin/functions.sh
infra/bootstrap_utils.sh

docker_prefix is not exactly the "registry name" in azure's definition, but it is `<registry_name>.azurecr.io` which `az acr login` accepts alternatively to just the registry name. Didn't seem worth adding a mostly redundant config field.

[azure] Dont assume resource_group is the name of the ACR

---

ci/ci/build.py
ci/test/resources/build.yaml

- Ignore missing secrets when they are optional. The test is a bit weak but hopefully enough to guard against crashing entirely.
- No longer need to support secrets as just string names in `createNamespace` steps

[ci] Support optional secrets in createNamespace steps

---

hail/python/hailtop/config/deploy_config.py

Python CLI tools like `hailctl` suffer from slow startup times, which infuriate me. This is in part because the first thing that happens is python has to recursively load all imported packages, since imports are traditionally done at the top-level. Very conveniently, setting the `PYTHONPROFILEIMPORTTIME` environment variable will cause python to emit a profile to stderr, which you can visualize with tools like [tuna](https://github.com/nschloe/tuna). So running
```
PYTHONPROFILEIMPORTTIME=1 hailctl dev config show 2> profile.log
tuna profile.log
```
gave me this
showing that importing `aiohttp` is responsible for half the time it takes me to run `hailctl dev config show`, which is literally just printing a local file!! There's no reason this shouldn't be instantaneous, but reducing it to …

[hailctl] Move aiohttp imports in deploy_config out of top level

---

batch/batch/driver/canceller.py

We were not accounting for jobs that could be in the Creating state before a job has been scheduled on an active instance.

[batch] Fix cancel orphaned attempts query

---

batch/batch/worker/worker.py

The `netns_pool_min_size` parameter was pretty pointless, we always want `4 * CORES` slots on a machine.

[batch] Reserve 4 times CORES network namespaces

---

infra/azure/create_bootstrap_vm.sh

In the unlikely change that the user already has a VM whose prefix is boostrap-vm, this will significantly reduce the likelihood of a name-clash.

[infra] teach create_bootstrap_vm.sh to use random names

---

hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

This adds a new IR pretty-printer that uses an mlir inspired printed form. It is currently not rigorously tested, so using the new format in logs is gated behind the flag `HAIL_USE_SSA_LOGS`.

[query] ssa style IR in logs

---

hail/src/main/scala/is/hail/expr/ir/lowering/LowerDistributedSort.scala

This PR makes the following changes:
1. For some reason, I forgot `CompileAndEvaluate` exists, and was separately calling `Compile`, applying it, then doing `SafeRow.read` in two places. Ripped those out in favor of `CompileAndEvaluate`.
2. When all segments are either already sorted or sufficiently small, I now sort and write out all the sufficiently small ones. Now I have a set of files that taken together fully represent the table, and I create a new `TableStage` by assembling those chunks into approximately evenly sized partitions.

[query] Shuffler Outputs Approximately Evenly Sized Partitions

---

benchmark/python/benchmark_hail/run/matrix_table_benchmarks.py
hail/src/main/scala/is/hail/expr/ir/TableIR.scala

Tested using code from [zulip].
After this change, the same pipeline went from 135 MiB peak usage per
partition, to 808 KiB.
[zulip]: https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query.200.2E2.20support/topic/Hail.20off-heap.20memory/near/270245855

[query] Clear TableKeyByAndAggregate context region in SeqOp

---

infra/gcp/README.md

The Makefile rules are prefixed with `gcp-`: https://github.com/hail-is/hail/blob/main/batch/Makefile#L47-L48, so reflecting it in the docs.
Though not sure how it generalises with Azure

infra: README fix 

---

infra/azure/README.md
infra/azure/bootstrap.sh

Resource groups are permitted to use dashes, underscores, uppercase letters,
and probably other characters not permitted in storage account names. This
PR cahanges `bootstrap.sh` to:
1. Ignore invalid characters in the resouce group.
2. Ensure (via randomness) that the generated name is unique.
3. Do not try to create a new storage account if `backend-config.tfvars` exists.
I lightly tested this. Here is an example of how it sanitizes a resource group name:
```
RESOURCE_GROUP=bu__ild-batch-worker-i32mage
possibly_invalid_storage_account_name="$(cat /dev/urandom | LC_ALL=C tr -dc 0-9 | head -c 4)${RESOURCE_GROUP}"
STORAGE_ACCOUNT_NAME=$(LC_ALL=C tr -dc a-z0-9 <<< "${possibly_invalid_storage_account_name}" | head -c 24)
echo $STORAGE_ACCOUNT_NAME
7241buildbatchworkeri32m
```

[infra] always use valid storage account names

---

hail/python/hail/ggplot/geoms.py
hail/python/hail/ggplot/ggplot.py
hail/python/hail/ggplot/scale.py
hail/python/hail/ggplot/stats.py
hail/python/hail/ggplot/utils.py
hail/python/test/hail/ggplot/test_ggplot.py

This PR:
1. Refactors `listify` to return pandas dataframes, and every geom to take in pandas dataframes. This significantly simplifies the code and should also speed things up.
2. Refactors the `apply_to_fig` method of most of the geoms to rely on a specification dict and then just loop over that. This simplifies adding a new argument / aesthethic. In the future, it may be best to just make all of the geoms take `**kwargs` so that arguments added to that dict will immediately be used for plotting, as right now I have to add something to `geom_bar`, `GeomBar.__init__`, and that dictionary for it to start showing up in plots. 
3. Adds `identity` as a bar position, which means to plot bars on top of each other. This is useful along with the `alpha` argument added to bars and histograms, …

[query] Refactor ggplot to use pandas, support alpha on histograms and bar charts

---

infra/gcp/ci/main.tf
infra/gcp/main.tf
infra/k8s/ci/main.tf

The only real bitrot in the GCP terraform was the leftover `gsuite_organization` variable. This fixes that and also makes the zuliprc secret and ukbb module optional. The extra `fileexists` in the data block for the zuliprc is janky, but functions such as `file` are evaluated before the creation of the resource, so terraform will complain that about the file not existing without that extra guard there. I don't love it but ultimately want these to come from a cloud secret vault so it might look different soon enough anyway.

[infra] Make zuliprc and ukbb terraform resources optional

---

infra/azure/modules/db/main.tf

We had a couple PRs fail because the database reached its [max connections](https://portal.azure.com/#@haildev.onmicrosoft.com/resource/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/haildev/providers/Microsoft.DBforMySQL/servers/db-393222c4/metrics). We should probably be resilient to this, but I figured we should be able to handle our normal PR load. I also checked GCP and their default is 4k. Azure sets its cap at 1250.
I haven't applied any terraform since you've made your changes. Is that safe to do?

[infra] Raise azure db max_connections to 1k

---

ci/ci/ci.py
ci/ci/github.py
hail/python/hailtop/batch_client/aioclient.py

This adds all WIP-labelled PRs to the Awaiting Action table on the CI's /me page. CI has automated testing in-so-far as we create a test repository on GitHub with some toy code in it and see that CI can deploy that code into Kubernetes. This stuff not so much, but I can for example put a CI in my namespace and make a PR to its test repository, add a wip tag, and see the table change at `internal.hail.is/dgoldste/ci/me`

[ci] Make WIP a PR that requires action

---

hail/python/hailtop/batch/backend.py

Fixes this error:
```
File "/Users/tpoterba/anaconda3/envs/hail/lib/python3.7/site-packages/hailtop/batch/backend.py", line 83, in __del__
File "/Users/tpoterba/anaconda3/envs/hail/lib/python3.7/site-packages/hailtop/batch/backend.py", line 79, in close
File "/Users/tpoterba/anaconda3/envs/hail/lib/python3.7/site-packages/hailtop/batch/backend.py", line 453, in _close
AttributeError: 'ServiceBackend' object has no attribute '_batch_client'
```

[hailtop.batch] Fix ServiceBackend close

---

batch/batch/driver/instance_collection/pool.py

I'm happy to see if I can replace this with a more efficient observability solution, but according to the profiler these lines combined can take up to 8% of the driver's overall CPU time, which just seems like something we shouldn't do. The `get_instance` logging will be especially bad with big clusters because it builds up a whole histogram which then needs to get formatted and printed.
I'm not sure how useful these log statements currently are. I never look at them but maybe others do.
cc: @danking

[batch] Don't do O(jobs) logging in scheduling loop when no machines found

---

hail/python/hail/ggplot/geoms.py
hail/python/test/hail/ggplot/test_ggplot.py

R uses `ymin` and `ymax`. This was added after last release so isn't a user exposed bug yet.

Changed y_min and y_max to ymin and ymax for geom_ribbon

---

batch/batch/driver/instance_collection/pool.py

After do_handshake, [schedule_loop_body](https://github.com/hail-is/hail/blob/2d019337114a972016ad843baabe76814dc8ad10/batch/batch/driver/instance_collection/pool.py#L371) is our biggest offender on the profiler. That in itself is not a bad thing, ideally we want the scheduling loop to be running as much as possible to give us the highest throughput, but the loop should still be efficient. All the queries in `user_runnable_jobs` show up the same on the profiler, since they are the same function call-stack just with different arguments. This should give us finer granularity into what's taking up our time.

[batch] Add metrics for scheduling loop queries

---

build.yaml

I believe this missing line basically erased all of the above `build_wheel_for_azure` step and the cloud optional changes I put our build system think a missing step is ok. If you look at the most recent deploy it doesn't include `build_wheel_for_azure` even though the `deploy` step depends on it. I'll separately make a fix for that

[build.yaml] Fix jvm entryway and wheel for azure steps

---

auth/auth/driver/driver.py
batch/batch/driver/main.py
ci/bootstrap.py
ci/bootstrap_create_accounts.py
ci/create_initial_account.py
devbin/rotate_keys.py
devbin/sync.py
memory/memory/memory.py
notebook/notebook/notebook.py

I use `pyright` as my LSP server and it gets mad at me with our old form of importing saying that `client is not a known member of kubernetes_asyncio`,  which as far as I can tell is because they don't actually use `__all__` and just import their submodules in their init? Anyway this seemed better to me and allows me to actually get the LSP hints for this library now, but let me know if this is just a Me thing or if I don't understand python modules

properly import submodules from kubernetes_asyncio

---

gear/gear/database.py

I was confused at how these could work because `self.conn.commit` and `self.conn.rollback` are async functions, but then I couldn't find any invocations of these methods.

[gear] Remove broken and unused Transaction functions

---

hail/src/main/scala/is/hail/asm4s/CodeBuilder.scala
hail/src/main/scala/is/hail/expr/ir/BinarySearch.scala

This ports and cleans up the binary search library methods in `RichIndexedSeq`. I very carefully documented general pre-/post-conditions and invariants, because binary search implementations are notorious for hiding bugs, and because these will be used in cases where both haystack and needle are intervals, where the typical formulation of binary search involving a well-behaved ordering doesn't apply.

[compiler] generic staged binary search utils

---

hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/io/plink/LoadPlink.scala

`lowerGlobals` is only used by `lowerTableIR`, we have to have the lowered globals at this point, not the matrix globals.

[query] Fix MatrixPlinkReader's `lowerGlobals`

---

devbin/functions.sh

I really do not think this should be necessary. The ADC is my *user* credentials. If I can
access the given project then I do not see why I need to regenerate my ADC creds.

[devbin] do not authenticate everytime I change projects

---

batch/batch/front_end/front_end.py
docker/requirements.txt

Closes hail-is/hail-production-issues#9
Details [here](https://github.com/hail-is/hail-production-issues/issues/9#issuecomment-1049356188).
This is my bad. One of the query service PRs allowed spec writing to happen in
parallel with DB insertion (which reduces latency a bit), but if the spec fails
to write or is cancelled, then the DB has a spec token that points at a
cloud object which does not necessarily exist.
I think we do not need the spec token, but removing it does not seem likely
to improve performance much. We still need to hit the DB to get the start_job_id.
There was some discussion about the necessity of the token [here](https://github.com/hail-is/hail/pull/7949#discussion_r370406517).
I think that discussion came to the wrong conclusion. GCS is atomic and globally …

[batch] db must rollback if spec write fails or is cancelled

---

batch/Makefile
benchmark/Makefile
bootstrap-gateway/Makefile
config.mk
gateway/Makefile
infra/bootstrap_utils.sh
internal-gateway/Makefile

I was hoping that a greater restructure would lead to a more elegant solution, but after so many footguns it just felt worth making this change. The main point is shelling out in the Makefiles to ask Kubernetes directly for what the global config values are instead of hard-coding them. Specifically, the changes are:
- `KUBERNETES_SERVER_URL` was simply not used anymore in the Makefiles so I deleted it.
- `DOCKER_ROOT_IMAGE`, `INTERNAL_IP`, `IP` and `CLOUD` were only used in a couple Makefiles so I moved the `kubectl` invocation into where they're used so that Makefiles that don't depend on those variables won't incur the cost of querying them
- `DOCKER_PREFIX` and `DOMAIN` were used pretty widely, so I kept them in config.mk because most Makefiles will need to query those values anyway. …

[infra] Remove hard-coded values from config.mk

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/expr/functions.py
hail/python/hail/expr/types.py
hail/python/hail/table.py
hail/python/test/hail/table/test_table.py

Pandas missingness is crazy. `pd.isna` tells you if something is "missing", which means either `NaN`, or a special `NA` sentinel value. For floats they use `NaN`, and specifically for the pandas special `Int64DType` and `Int32DType` and nothing else they use this `NA` value.
They don't have an easy way to distinguish between `NA` and `NaN`, so I first check if something `isna`, then check if it's a `float` to differentiate between the cases. 
They also don't have a way to test if something is a `Int32DType` for some reason. So I use `is_int64_dtype`, and if that fails I fall back to `is_integer_dtype`, which is true for both `Int64DType` and `Int32DType`.

[query] from_pandas needs to support Pandas missing types and support numpy nums better

---

batch/batch/driver/job.py
gear/gear/__init__.py

Closes hail-is/hail-production-issues#3
Details [here](https://github.com/hail-is/hail-production-issues/issues/3).
The high-level takeaway is that if the system is moving quite fast MJS
can happen *after* MJC. When MJC happens first, there are not yet any
resources. As a result, the state of a batch is observable as
`complete` *before* the resources are present. A lack of
resources implies an incorrect total cost for a batch. Linking
resource insertion with MJC ensures a batch may be complete if-and-only-if
the cost of the batch is accurate.

[batch] ensure cost is up-to-date when a batch is marked complete

---

hail/src/main/scala/is/hail/expr/ir/Analyses.scala
hail/src/main/scala/is/hail/expr/ir/DistinctlyKeyed.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerToCDA.scala
hail/src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala
hail/src/test/scala/is/hail/expr/ir/DistinctlyKeyedSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/lowering/LowerDistributedSortSuite.scala

Analysis pass to decide if tableIRs are uniquely keyed. Used by table join.

Distinct analysis

---

hail/Makefile
hail/build.gradle

This PR drastically simplifies the hail/elasticsearch story. We no longer require any special custom built JAR from google cloud (was necessary because there was a time when Spark 3 compatible ES wasn't on Maven). Also allow ES version 7 or 8 when on Spark 3, and don't require that it's Spark 3.1

[query] Simplify Elasticsearch Dependencies

---

hail/src/main/scala/is/hail/services/package.scala

See https://ci.hail.is/batches/532603/jobs/112.
We encounter a `is.hail.relocated.com.google.cloud.storage.StorageException` which is caused by a
`com.google.api.client.http.HttpResponseException`. The latter exception is not currently
considered a transient error. This PR changes isTransientError to recognize `HttpResponseException`
as a transient error.

[java-services] add new transient error

---

hail/python/test/hailtop/test_aiogoogle.py

We forgot to retry create part in a test. See, for example, copier.py, where we do retry create part.

[aiogoogle] retry create part in test

---

hail/python/test/hail/methods/test_impex.py
hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
hail/src/main/scala/is/hail/io/fs/FS.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SJavaArray.scala

To do this add an intermidiate abstract PartitionWriter,
SimplePartitionWriter, and extend it with TextTablePartitionWriter.
SimplePartitionWriter manages the output stream for its subclasses. The
subclasses need to implement consumeElement, and optionally preConsume
and postConsume.
TextTablePartitionWriter handles the delimiter delimited writing per
element item and the line delimited writing per element of the stream.
It will also optionally write the header if ExportType.PARALLEL_HEADER_IN_SHARD
has been requested.
TextTableFinalizer is the 'MetadataWriter' (name change pending), for
TextTableWriter. That's where the header is written for
PARALLEL_SEPARATE_HEADER and CONCATENATED, and files are merged for
CONCATENATED.
There are currently a few idosyncracies that don't replicate …

[query] Lower TextTableWriter

---

hail/python/hail/table.py
hail/python/test/hail/table/test_table.py

As far as I can tell, pandas integers and strings specifically can be this special pandas `NA` value, whereas floats use `NaN` for missing and `object` just uses `None`. Here I specifically watch out for these special pandas values and turn them into `None`s.

[query] Properly handling pandas strings which can be NA 

---

build.yaml

I'm honestly not sure how we managed to go so long without this fix.

[build.yaml] steps using database-server-config must depend on its creation

---

infra/install_bootstrap_dependencies.sh

Allows `skopeo` to be used instead of docker when copying third-party images, which should substantially speed up the bootstrap process.

[infra] Install skopeo on bootstrap vm

---

hail/python/hail/ggplot/geoms.py
hail/python/hail/ggplot/ggplot.py
hail/python/hail/ggplot/scale.py
hail/python/hail/ggplot/stats.py
hail/python/hail/ggplot/utils.py
hail/python/test/hail/ggplot/test_ggplot.py

Turns out pandas dataframes have an `.attrs` field to store "globals". So now I group by discrete values and collect them as globals, and I get one pandas dataframe per group of discrete values. This makes things a bit less complicated I think. 
As part of this change, I now create scales based on looking at all the collected data, not just one particular geom's data. This is more correct for things like continuous color, where if I have one geom that has points in color range 0 - .5, and another geom that has points in color range .5-1, there should be a continuous color gradient between 0 and 1, not two separate ones from 0 - .5 and .5 - 1. 
This will also allow me to support things like `scale_color_hue`, which is the default R way of picking discrete colors by choosing evenly spaced …

[query] ggplot redo scales and stores groups in Dataframe.attrs

---

ci/ci/ci.py
ci/ci/templates/pr-table.html

Currently if I visit `ci.hail.is` it shows the status of the build that CI ran in GCP. Now that we enforce all CI's pass, we can end up with situations on `ci.hail.is` where the PR is approved and the build was successful but it's not merging because the tests failed over on azure. This shows all the github statuses in addition to the cloud-local build information.

[ci] Show github statuses in addition to build status

---

batch/batch/driver/job.py

This is not a real error. It is not the fault of batch that the other
end of the connection did not respond. If batch is having general
network connectivity issues, I would expect to see many other
error log statements.

[batch] demote callback failure to info

---

batch/batch/driver/instance_collection/job_private.py
batch/batch/driver/instance_collection/pool.py

The return value of these functions indicates if the containing loop
should wait or if we should immediately re-call the function. This
is intended to be used to allow functions which *know* they have more
work to eagerly invoke themselves again.
The use of this variable seems to have been changed to basically always
eagerly re-run during the Azure work.
This change restores the original behavior:
1. Do not wait in job private if we saw 300 records (seems likely there were
301 or more records in the db).
2. Do not wait in pool scheduler if we exhaust a user's share. I do not
fully follow the pool scheduler's logic. There might be something
smarter we can do. I think we should really only re-call if we believe
the db contains more ready jobs and we have available cores.

[batch] wait unless we have more work

---

ci/ci/ci.py
ci/ci/templates/pr-table.html

The margins around the list are kind of annoying and make the table really big.
An example of how two row headers look:
```
<table>
<thead>
<tr>
<th rowspan="2">PR</th>
<th rowspan="2">Build State</th>
<th colspan="3">GitHub Statuses</th>
<th rowspan="2">Labels</th>
<th rowspan="2">Branch</th>
<th rowspan="2">Review State</th>
<th rowspan="2">Author</th>
</tr>
<tr>
<th>gcp ci</th>
<th>aws ci</th>
<th>azure ci</th>
</tr>
</thead>
<tbody>
<tr>
<td>123</td>
<td>failing</td>
<td>fail</td>
<td>success</td>
<td>fail</td>
<td></td>
<td>my-branch</td>
<td>approved</td>
<td>danking</td>
</tr>
</tbody>
</table>
```

[ci] use two-level header for more succinct table

---

infra/gcp/main.tf

I currently have a PR up to change the Azure database so I'll make the equivalent change there.
If you click into the link I included you'll see that the naming scheme we're currently using is now considered Legacy, and they're moving to a scheme that doesn't use machine type, instead just resource specs

[infra] Double cores and memory for GCP database

---

batch/test/test_accounts.py

This is still happening. I think particularly under heavy batch load it might take a while for this to propagate.
https://ci.azure.hail.is/batches/34523/jobs/102

[batch] further cost test mitigation

---

hail/python/hail/vds/methods.py

the actual expression for x/y ploidy is:
```python3
per_sample = coverage.transmute_cols(autosomal_mean_dp=auto_dp,
x_mean_dp=x_dp,
x_ploidy=2 * x_dp / auto_dp,
y_mean_dp=y_dp,
y_ploidy=2 * y_dp / auto_dp)
```

[vds] fix impute_sex_chromosome_ploidy docs

---

auth/auth/auth.py
auth/auth/exceptions.py
gear/gear/__init__.py
hail/python/hailtop/auth/__init__.py
hail/python/hailtop/auth/auth.py
hail/python/hailtop/hailctl/auth/cli.py
hail/python/hailtop/hailctl/auth/create_user.py
hail/python/hailtop/hailctl/auth/delete_user.py

I wanted to get this feature done quickly for Michael. But I do think we should think about having consistency in route names across services. Like when do we have `/delete` in the route name versus a 'DELETE' request or both?
Another question is whether to add the polling / waiting for the user to be created and if so, where should the polling go? I put it in the auth service for now rather than the CLI because I don't think we expose the state of the user in our API.
I tested this as much as I could in my namespace.
The most important thing is to make sure the decorators are correct and only developers can create / delete users. I want to add auth tests that make sure the routes are protected, but that's more work than I wanted to do in this PR.

[auth] Add rest endpoint and cli for create / delete users

---

gear/gear/database.py
gear/gear/metrics.py

Added a panel for it [here](https://grafana.hail.is/d/TVytxvb7z/batch-driver-performance?orgId=1&var-namespace=dgoldste&from=1646327460490&to=1646328244432). I was kind of surprised to see that we don't have a queue building up, but the back-pressure could be somewhere else. I can also bring up the rate limit now that the DB can handle it

[gear] Add metric for number of queries waiting on a connection

---

hail/python/test/hail/matrixtable/test_matrix_table.py
hail/python/test/hail/methods/test_misc.py
hail/python/test/hail/table/test_table.py
hail/python/test/hail/vds/test_vds.py
hail/src/main/scala/is/hail/expr/ir/lowering/CanLowerEfficiently.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala

Closes hail-is/hail-tasks#13
~Stacked on #11375~
Currently only supports `product = false`

[compiler] lowered TableIntervalJoin

---

docker/requirements.txt

This was used a very long time ago for authentication (e.g. see notebook2 in commit aa937bd3414481998e522832336ab618a8cf756d).

[docker] remove Authlib

---

ci/ci/github.py

I don't think this will be too much on the database, but even if it is I feel like mitigating that will be less effort than it is currently trying to nudge CI towards getting PRs in quickly.

[ci] Run five PRs simultaneously

---

dev-docs/kubernetes-operations.md

cc: @jigold
I am honestly not sure how this should interact with terraform. We do specify the
node pools there. I worry that using terraform to change the node pools would create
downtime.

[dev-docs] kubernetes operations: altering a node pool

---

batch/batch/worker/worker.py
batch/test/test_batch.py

Saw this in https://ci.azure.hail.is/batches/38760/jobs/99.
I think the log of a container is actually never None any more. It can
be empty if bash has started but the echo command has not yet run.

[batch] fix flaky test

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala

This fixes a bug in joins where:
* The join key is a prefix of the left key
* Values of the join key in the left table span multiple partitions
For example, say the left table is `{[(0, 0), (0, 1)], [(0, 2), (1, 0)]}`, where the two lists of tuples are the two partitions, and the key is the entire tuple, and the join key is just the first field.
Then in the old code
```
val loweredLeft = lower(left).strictify()
val leftKeyToRightKeyMap = left.typ.keyType.fieldNames.zip(right.typ.keyType.fieldNames).toMap
val newRightPartitioner = loweredLeft.partitioner.coarsen(commonKeyLength)
.rename(leftKeyToRightKeyMap)
val loweredRight = lower(right).repartitionNoShuffle(newRightPartitioner)
```
the left partitioner is coarsened to `[(0), (0)], [(0), (1)]` in the third line, and the …

[compiler] fix lowered join where join key is prefix of left key

---

build.yaml
hail/build.gradle
hail/python/cluster-tests/block_matrix_from_numpy.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/test/scala/is/hail/utils/RichIndexedRowMatrixSuite.scala

Spark 3.1 still relies on Breeze 1.0, which is very broken: https://github.com/scalanlp/breeze/issues/772
We can never allow use of Breeze 1.0. 
To fix, I have hard coded the insistence that we use Breeze 1.1, relocated it into our hail jar. In the process, I also made it so that we don't support building with Scala 2.11 anymore, but that doesn't preclude us from still building with Spark 2.4.8 for now. 
Our old "fix" in the build.gradle that said to change Spark 1.0 to 1.1 was actually making things more confusing. It was making it so that when we pulled down Spark and Breeze from Maven ourselves we'd switch out Breeze 1.0 for Breeze 1.1. However, it had no effect on what happened in dataproc, when breeze and Spark are provided on the classpath and we just use what's available. 
I also …

[query] Relocate Breeze

---

batch/batch/front_end/front_end.py

The endpoint was originally added into the Query service in https://github.com/hail-is/hail/pull/10085, but it disappeared after the Query service was removed. Re-adding it into Batch.
Let me know if it better belongs somewhere else. Our use case was to request the version of currently running Batch service, so adding it into Batch made sense.)

[batch] Add `/version` endpoint (originally in [query])

---

hail/scripts/deploy.sh

I could not get the `\d` to work for me on an Ubuntu machine. The `[0-9]`
range seems to work with extended regexps.

[deploy] fix sed for updating HAIL_VERSION

---

hail/src/main/scala/is/hail/expr/ir/EmitStreamDistribute.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerDistributedSort.scala
hail/src/main/scala/is/hail/types/physical/stypes/SCode.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SBaseStructPointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SCanonicalCall.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SIndexablePointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SJavaString.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SNDArrayPointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SStackStruct.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SStringPointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SUnreachable.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SBaseStruct.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SBinary.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SContainer.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SInterval.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SLocus.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SNDArray.scala
hail/src/main/scala/is/hail/types/physical/stypes/primitives/SBoolean.scala
hail/src/main/scala/is/hail/types/physical/stypes/primitives/SFloat32.scala
hail/src/main/scala/is/hail/types/physical/stypes/primitives/SFloat64.scala
hail/src/main/scala/is/hail/types/physical/stypes/primitives/SInt32.scala
hail/src/main/scala/is/hail/types/physical/stypes/primitives/SInt64.scala
hail/src/test/scala/is/hail/asm4s/CodeSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/lowering/LowerDistributedSortSuite.scala

With this, we should theoretically be able to arbitrarily sized rows.

[query] LowerDistributedSort cutoff based on bytes not rows

---

hail/src/main/scala/is/hail/utils/Py4jUtils.scala

This is a sane choice, and while I do not expect java to ever change the
toString of Date, it's better to have a consistent format across all
file systems and interfaces.

[query] Use RFC3339/ISO8601 for Py4jUtils.stat data

---

hail/python/hail/fs/__init__.py
hail/python/hail/fs/fs.py
hail/python/hail/fs/google_fs.py
hail/python/hail/fs/hadoop_fs.py
hail/python/hail/fs/local_fs.py
hail/python/hail/fs/router_fs.py
hail/python/hail/fs/stat_result.py
hail/python/hail/utils/hadoop_utils.py
hail/python/test/hail/matrixtable/test_file_formats.py
hail/src/main/scala/is/hail/io/fs/FS.scala
hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
hail/src/main/scala/is/hail/io/fs/HadoopFS.scala
hail/src/main/scala/is/hail/utils/Py4jUtils.scala

The new object, a StatResult (analogous to os.stat_result) is minimal
for now. Notably, it uses a fractional UNIX timestamp for modification
time. StatResult should be moderately extensible, but since it
subclasses NamedTuple, care may need to be taken to preserve field
order.

[query] Rework python FS.stat to return an object

---

hail/python/hail/backend/service_backend.py

It is not a property. We can clean up some async resources as well.

[query/service] properly implement Backend.stop for ServiceBackend

---

hail/src/main/scala/is/hail/expr/ir/Pretty.scala

Fixes a bug where identifiers for bound variables were not being printed by the sexpr style pretty printer.

[compiler] fix sexpr style IR printer

---

hail/python/hailtop/aiotools/fs/copier.py
hail/python/hailtop/utils/utils.py

I saw an error in a CI job that was copying in some files. To be clear,
this change would not restart a copy of the entire directory. It just
retries the directory listing. We currently use O(N_FILES) memory to
store the list of files in a directory *before* we start copying.
```
File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.7/dist-packages/hailtop/aiotools/copy.py", line 110, in <module>
asyncio.run(main())
File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
return loop.run_until_complete(main)
File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
File …
```

[copier] retry file listing if it fails

---

prometheus/prometheus.yaml

prometheus was on a crash loop in Azure because it was failing to `mmap` a 0-byte file that the previous pod had created before getting shut down. Turns out this bug was fixed in a more recent version of prometheus so a simple upgrade fixed the issue. This is the most recent release.

[prometheus] Update prometheus version

---

hail/python/hail/backend/service_backend.py

We do not send flags set to None, so we should not include them in the count of flags.
Yes, I agree, I should have used JSON for this. I will fix that post-haste after March 28th

[query/service] fix calculation of number of flags

---

ci/ci/github.py

Now that Azure's up and seems at least as good as it was before, plus we'll need this before the AzureScalaFS PR is ready.

Revert "[ci] Ignore follower (azure) ci statuses"

---

hail/python/hailtop/aiotools/copy.py
query/Makefile

When using GNU Make 4.3, the slashes in the json string in
query/Makefile were being passed unmodified as arguments to the python
copy process. In order to fix this, I had to put the json input on one
line. Furthermore, I converted all indents to tabs for consistency.
I also modified hailtop.aiotools.copy to read from standard input if '-'
or no 'files' argument is provided. I belive this will allow easier use
of the copy tool by end users, for example, using [jo], the copy
invocation looks like:
```make
jo -a \
$$(jo from=../hail/src/test/resources to=$(HAIL_TEST_RESOURCES_DIR)) \
$$(jo from=../hail/python/hail/docs/data to=$(HAIL_DOCTEST_DATA_DIR)) | \
python3 -m hailtop.aiotools.copy 'null'
```
[jo]: https://jpmens.net/2016/03/05/a-shell-command-to-create-json-jo/

[query] Improve Makefile Compatibility

---

hail/src/main/scala/is/hail/asm4s/ClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/Random.scala
hail/src/main/scala/is/hail/types/physical/stypes/SCode.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SRNGState.scala
hail/src/main/scala/is/hail/types/virtual/TRNGState.scala
hail/src/main/scala/is/hail/utils/Bitstring.scala
hail/src/test/scala/is/hail/expr/ir/RandomSuite.scala

This PR begins to implement the infrastructure needed for reproducible randomness.
The main components are:
* An implementation of the Threefish block cipher, reduced to 20 rounds as in Threefry [1], but keeping the tweak from Threefish (really just the first 64 bits, the second 64 bits are always 0). The specification for Threefish can be found in [2].
* An implementation of the `jdistlib.RandomEngine` interface using Threefish, so that we can continue using the `jdistlib` implementations of sampling from various distributions.
* This has some improvements over the standard Java RNG implementations of random floating point numbers, and of random integers from a specified interval. See comments in the code for details.
* The beginnings of a new type `(S/T)RNGState`. This implements a …

[compiler] First pieces of infrastructure for reproducible randomness

---

hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala

The old query service would cache user information. The new query service just
constructs a new FS for every query (its not too expensive). None of this code
is used currently.

[query/service] remove unused things from old query service

---

hail/python/hail/backend/local_backend.py
hail/python/hail/fs/local_fs.py
hail/python/hail/fs/router_fs.py
hail/python/hail/utils/hadoop_utils.py
hail/python/test/hail/methods/test_impex.py
hail/python/test/hail/methods/test_statgen.py
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/io/vcf/ExportVCF.scala

Re-implement export vcf in generated code.
There is a fair amount of 'duplicated' code here between table export
and vcf export, however, I belive this to be fine. We can always
refactor VCFPartitionWriter to be a subclass of SimplePartitionWriter,
but that would require a little special casing as VCF export needs
access to the column values and SimplePartitionWriter assumes such
a thing is not necessary.
As far as VCF export itself, we simply duplicate the logic present in
ExportVCF but with generated code.

[lowering] lower vcf export 

---

hail/python/hail/docs/ggplot/index.rst
hail/python/hail/ggplot/__init__.py
hail/python/hail/ggplot/ggplot.py
hail/python/hail/ggplot/scale.py
hail/python/hail/ggplot/utils.py
hail/python/test/hail/ggplot/test_ggplot.py

Prior to this PR, when someone specified they'd like to color a plot by a discrete variable, we used a predetermined list of 10 colors to assign colors. If something used more than 10 colors, it'd wrap around. 
This PR changes `scale_color_discrete` to be an alias for `scale_color_hue`, as it is in ggplot. `scale_color_hue` works by sampling evenly spaced points around a color wheel to create a set of maximally distant colors. 
The old behavior is now achievable by using `scale_color_manual`, which takes in a list of colors and assigns colors based on that list.

[query] Generate infinite discrete colors

---

hail/python/hail/fs/local_fs.py
hail/python/test/hail/utils/test_utils.py

This test tests a lot of functionality. Two different things were failing, both of which are fixed here:
1. When you list a file (as opposed to a directory) you should get a size one list containing the stat for that file. Previously, `LocalFS.ls` would raise a NotADirectoryError.
2. `LocalFS.ls` does not support the globbing that `HadoopFS` supports. I fixed that.

[query/fs] fix LocalFS when given a single file to list & when globbing

---

batch/batch/driver/job.py
batch/batch/front_end/front_end.py

We time most of our stored SQL procedures (anything with a `CALL`). I'd like to time these two as well, the `mark_job_creating` should hopefully inform the deadlock situation.

[batch] Time mark job creating and close batch

---

ci/ci/build.py

@johnc1231 Had this idea for dealing with registry flakiness. I was hesitant at first because really I want buildkit to retry more transient errors, but maybe with its local cache it would be quick?

[ci] Retry image builds

---

docker/Dockerfile.base
docker/hail-ubuntu/curlrc
hail/Dockerfile.hail-run-tests

We have configured curl to retry so we should always prefer it to wget. I also
fixed that long-standing mistake I made when I added retry-all-errors before
it was supported in our version of curl.

[docker] fix curl options, use curl in more places

---

dev-docs/kubernetes-operations.md
infra/azure/main.tf
infra/azure/modules/batch/main.tf
infra/azure/modules/ci/main.tf
infra/azure/modules/vdc/main.tf
infra/azure/modules/vdc/variables.tf
infra/azure/variables.tf
infra/gcp/main.tf

There's a few things happening here:
I extended the node pool update documentation with how to deal with terraform-managed node pools. This is what I did on Azure and worked fine. The only real change in terraform other than changing the machine type is making the node pool name configurable to adhere to the naming guidelines and allow us to do a rolling migration.
I updated the azurerm provider without thinking much about it and even though it's a minor version had some breaking changes that after a half-successful `apply` made it hard to downgrade. So I decided just to appease the breaking change and leave us at the new version, which is what all the `blob_properties` changes are for. They are in no way related to the node pools.
I added a section for a bug that I've seen a couple of …

[infra] Update k8s to 8-core nodes

---

hail/python/hail/ggplot/geoms.py
hail/python/hail/ggplot/stats.py
hail/python/test/hail/ggplot/test_ggplot.py

Added support for a weight aesthetic in geom_bar. Also made small fix to geom_tile's color.

Geom bar weight

---

hail/python/hailtop/batch/backend.py

Otherwise, "batch-in-batch" will print the internal (`batch.hail`) domain.

Print external URL in batch submission log

---

batch/Dockerfile.driver-nginx
batch/Makefile
batch/batch/driver/instance_collection/pool.py
batch/batch/driver/job.py
batch/batch/driver/main.py
batch/batch/spec_writer.py
batch/deployment.yaml
batch/driver-nginx.conf
build.yaml
gear/gear/database.py
gear/gear/metrics.py
hail/python/hailtop/utils/utils.py
internal-gateway/internal-gateway.nginx.conf
tls/config.yaml

This change adds an nginx sidecar to the batch-driver pod for terminating TLS. TLS negotiation has proven a major bottleneck to scheduling performance, as the batch-driver currently spends up to 60% of its CPU time in handshakes with workers. Moving TLS termination into a sidecar that can leverage additional cores both reduced CPU pressure on the driver and allowed for a 3-4x increase in job-scheduling throughput.
Below are before-and-after profiles of the same benchmark (30,000 1s jobs) under the proposed higher rate limit, showing CPU time:
Looking at Wall time, the before profile is nearly identical because at the current rate limit the driver uses 100% of its CPU shares under this benchmark. On this branch, CPU utilization drops to 40-60%, giving the following wall time profile:
So we …

[batch] Use nginx reverse proxy to terminate TLS for batch-driver

---

batch/batch/front_end/front_end.py
batch/batch/front_end/validate.py
batch/batch/worker/worker.py
batch/deployment.yaml
build.yaml
hail/.gitignore
hail/Makefile
hail/python/hail/__init__.py
hail/python/hail/backend/service_backend.py
hail/python/hail/context.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/setup.py
hail/src/main/scala/is/hail/backend/service/Main.scala
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/backend/service/Worker.scala
query/Makefile

Apologies, this spiraled into a big PR. Hopefully the large set of changes actually improves everyone's understanding of this.
---
The goal of this PR is to make this work:
```
HAIL_QUERY_BACKEND=service \
python3 -c 'import hail as hl; hl.utils.range_table(10).write("gs://foo/bar.t")`
```
In particular, a normal user should not need to know the location of a Hail Query JAR. Currently, you must specify two environment variables: `HAIL_SHA` and `HAIL_JAR_URL`.
This PR takes advantage of the well known location of a Hail Query JAR [1]. We use the newly introduced `hl.revision()` to determine the SHA-1 of the currently installed Hail. This PR includes the revision in the driver job spec. The front end has been modified to convert the revision into a cloud storage URL.
This PR also provides …

[query/service] automatically determine JAR url based on SHA

---

batch/batch/worker/worker.py
batch/test/test_batch.py
hail/python/hailtop/aiotools/copy.py

This PR splits the old Container class into an Image class, a Task class, and a Container class. The Image class has all the code necessary for pulling, localizing, and extracting images. There are two public methods `pull` and `prune`. The Container class has all the code for setting up networks, ports, overlays, and running the container. The two important public methods are `run` and `get_logs` which subclasses can overwrite. The Task class is a subclass of the Container class. In the future I will add `JVMContainer` which is also a subclass of a Container.
There is an open question about what the code is doing with `spec['network']` right now. The validator says it's an optional string, but our code allows booleans and doesn't handle the 'public' case.
The last thing to make sure of …

[batch] Refactor worker Container class into Image and Container

---

hail/python/hail/backend/backend.py
hail/python/hail/backend/py4j_backend.py
hail/python/hail/backend/service_backend.py
hail/python/test/hail/expr/test_expr.py
hail/python/test/hail/expr/test_ndarrays.py
hail/python/test/hail/linalg/test_linalg.py
hail/python/test/hail/methods/test_impex.py
hail/python/test/hail/methods/test_misc.py
hail/python/test/hail/utils/test_utils.py
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/backend/service/Worker.scala
hail/src/main/scala/is/hail/io/plink/LoadPlink.scala
hail/src/main/scala/is/hail/utils/ErrorHandling.scala
hail/src/main/scala/is/hail/utils/richUtils/RichContextRDD.scala

The main change is to the communication protocol between the client and
the driver and between the driver and the worker.
In main, both the driver and the client send messages back to the client
and driver (respectively) by writing to a file in cloud storage. In both
cases, the file (in main) has one of these two structures:
0x00                  # is_success (False)
UTF-8 encoded string  # the stack trace
0x01                  # is_success (True)
UTF-8 encoded string  # JSON message to send back to the client or driver
In this PR, the success case does not change. The failure case becomes:
0x00                  # is_sucess (False)
UTF-8 encoded string  # short message
UTF-8 encoded string  # expanded message
4-byte signed integer # error id
The Python client (in `service_backend.py`) and …

[query/service] use error id to raise user-friendly errors

---

hail/python/hail/backend/backend.py
hail/python/hail/backend/py4j_backend.py
hail/python/hail/backend/service_backend.py
hail/python/hail/expr/types.py
hail/python/test/hail/experimental/test_experimental.py
hail/python/test/hail/expr/test_expr.py
hail/python/test/hail/ggplot/test_ggplot.py
hail/python/test/hail/methods/test_family_methods.py
hail/python/test/hail/methods/test_impex.py
hail/python/test/hail/methods/test_misc.py
hail/python/test/hail/methods/test_pca.py
hail/python/test/hail/methods/test_qc.py
hail/python/test/hail/methods/test_statgen.py
hail/python/test/hail/table/test_table.py
hail/python/test/hail/test_context.py
hail/python/test/hail/vds/test_vds.py
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala

This PR keeps a list of registered function client-side. When we send
an execute operation, we also send all the functions with the IR-to-execute.
The bulk of the deletions are removing fails_service_backend markers.

[query/service] implement the function registry in the ServiceBackend

---

hail/python/hail/backend/backend.py
hail/python/hail/backend/service_backend.py
hail/python/hail/experimental/expressions.py
hail/python/hail/ir/matrix_ir.py
hail/python/hail/ir/table_ir.py
hail/python/hail/matrixtable.py
hail/python/hail/methods/impex.py
hail/python/hail/table.py
hail/python/hail/utils/misc.py

As much as possible, avoid network requests. In particular, we know the type of tables that are read in checkpoint and Expression.persist.

[query/service] fast path for checkpoint and persist

---

batch/batch/worker/worker.py

```
File "/usr/local/lib/python3.7/dist-packages/batch/worker/worker.py", line 525, in run_until_done_or_deleted
return step.result()
File "/usr/lib/python3.7/asyncio/futures.py", line 181, in result
raise self._exception
File "/usr/lib/python3.7/asyncio/tasks.py", line 249, in __step
result = coro.send(None)
File "/usr/local/lib/python3.7/dist-packages/batch/worker/worker.py", line 695, in _run
raise ContainerTimeoutError(f'timed out after {self.timeout}s')
ContainerTimeoutError: timed out after 5s
```
```
File "/usr/local/lib/python3.7/dist-packages/batch/worker/worker.py", line 2378, in run_job
await job.run()
File "/usr/local/lib/python3.7/dist-packages/batch/worker/worker.py", line 1695, in run
await …
```

[batch] Fix errors on the worker

---

hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/linalg/blockmatrix.py

[query] propagate type information when we have it in BlockMatrix

---

hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/backend/service/Worker.scala
hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala

1. Until we scale up the memory service's throughput, avoid use on the client
and the worker if there are more than 50 partitions.
2. On the driver, open no more than 100 concurrent connections to Google Cloud
Storage.
3. Set a timeout of five seconds to connect or read from Google Cloud Storage.

[query/service] fixes for large pipelines

---

batch/batch/worker/worker.py

```
File "/usr/local/lib/python3.7/dist-packages/batch/worker/worker.py", line 2148, in new_connection
return await asyncio.open_unix_connection(self.socket_file)
File "/usr/lib/python3.7/asyncio/streams.py", line 128, in open_unix_connection
lambda: protocol, path, **kwds)
File "/usr/lib/python3.7/asyncio/unix_events.py", line 232, in create_unix_connection
await self.sock_connect(sock, path)
File "/usr/lib/python3.7/asyncio/selector_events.py", line 473, in sock_connect
return await fut
File "/usr/lib/python3.7/asyncio/futures.py", line 266, in __await__
return self.result()  # May raise too.
File "/usr/lib/python3.7/asyncio/futures.py", line 181, in result
raise self._exception
File "/usr/lib/python3.7/asyncio/selector_events.py", line 478, in …
```

[batch] Remove existing JVM container before recreating

---

batch/Dockerfile.worker

Mainly bug fixes and criu support. I don't like that we're still building from source and hope to replace that soon, but Vedant will need this to start playing with checkpoint/restore.

[batch] Upgrade crun to 1.4.4

---

docker/requirements.txt
hail/python/dev/requirements.txt

Fixes a transitive dependency breaking issue. See [here](https://github.com/psf/black/issues/2964).

[black] Upgrade to 22.3.0

---

hail/python/hail/context.py

I dropped a bunch of args to spark and accidentally prepended every Hail QoB pipeline name with "Hail"

[query] fix init

---

hail/python/hailtop/hailctl/dataproc/connect.py

For example,
```
(base) # hailctl dataproc connect --ssh-key-file=/my/special/key dk notebook --dry-run
gcloud command:
compute ssh dking@dk-m --zone=us-central1-b \
'--ssh-flag=-D 10000' \
'--ssh-flag=-N' \
'--ssh-flag=-f' \
'--ssh-flag=-n' \
'--ssh-key-file=/my/special/key'
```

[hailctl] allow passthrough arguments to dataproc connect

---

hail/build.gradle

Needed to sub in commons-io, which we were getting transitively from lsmtree. I picked the version that hadoop/spark depend on at runtime. lsmtree depends on an older one but currently in `main` gradle upgrades it for the one requested by the runtime dependencies.

[query] Remove indeed lsmtree

---

batch/batch/worker/worker.py

`NetworkAllocator.reserve` creates a bunch of network namespaces on startup and adds them to an `asyncio.Queue`. There's no reason to wait for all of them before accepting jobs.

[batch] Dont block on all netns creation on startup

---

hail/python/test/hail/matrixtable/test_matrix_table.py
hail/src/main/scala/is/hail/expr/ir/ExtractIntervalFilters.scala

The new way:
```
In [6]: mt = hl.balding_nichols_model(3, 10, 100)
2022-03-28 10:30:08 Hail: INFO: balding_nichols_model: generating genotypes for 3 populations, 10 samples, and 100 variants...
In [7]: fmt = mt.filter_rows(mt.locus.contig == "chr1")
In [8]: fmt.rows()._force_count()
2022-03-28 10:30:13 Hail: WARN: Filtered with contig 'chr1', but 'chr1' is not a valid contig in reference genome GRCh37
2022-03-28 10:30:14 Hail: INFO: Coerced sorted dataset
2022-03-28 10:30:14 Hail: INFO: reading 0 of 8 data partitions
Out[8]: 0
```

[query] Fix bug with filtering against invalid contig

---

hail/python/hail/ggplot/__init__.py
hail/python/hail/ggplot/facets.py
hail/python/hail/ggplot/geoms.py
hail/python/hail/ggplot/ggplot.py
hail/python/hail/ggplot/stats.py
hail/python/test/hail/ggplot/test_ggplot.py

This PR introduces `facet_wrap`, which will allow creating plots based on a specified facet.
It also adds 
`     def _add_aesthetics_to_trace_args(self, trace_args, df):`
and
`     def _update_legend_trace_args(self, trace_args, legend_cache):`
two helper methods which let me clean up some of the redundant plotting work.
A `legend_cache` was introduced to make sure we put traces that should have the same legend point in a `legendgroup` together. Without it, if I draw one red line in each of 4 different subplots created by a facet, then 4 entries appear in the legend.

[query] Introducing Faceting with Plotting

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/test/hail/expr/test_expr.py

The test for keys has to be `is not None` to make sure falsey things like `Struct()` can be keys.

[query] Fix bug where dictionary literal couldn't have falsey key

---

hail/python/hail/docs/install/macosx.rst

`adoptopenjdk` has been deprecated.  `temurin` is now the official successor as of 2021-08-01 (Aug 01, 2021)
https://github.com/AdoptOpenJDK/homebrew-openjdk
https://formulae.brew.sh/cask/adoptopenjdk#default

Update installation commands for using homebrew

---

hail/src/main/scala/is/hail/asm4s/ClassBuilder.scala

According to the JVM specification, methods may only have 255 parameters
(including this).

[query] Add assertion that methods have fewer than 255 parameters

---

batch/batch/worker/worker.py

Shortly after this merged, we encountered issues where some workers shut down soon after starting up, but while they were running jobs. I think the `startup_tasks` idled out even though we activated, which caused us to return without shutting down the site. That meant we shut down while we were processing jobs and those workers spewed a bunch of errors before they finally killed themselves off.
I think it's wrong here to tie in the timing out trying to activate with other startup tasks that could potentially take a longer amount of time but will certainly finish and we should let them finish. We also don't need all of the network namespaces created in order to start accepting jobs.
For context, I think it takes just about MAX_IDLE_TIMEOUT_SECONDS to create all the network namespaces.

Revert "[batch] Dont block on all netns creation on startup"

---

batch/batch/driver/instance_collection/pool.py
batch/batch/driver/job.py

The `log.exception` in the wrapping try/except means we log anything that raises as an error, even things like 503's and 403's from the workers which we explicitly log as info. I think we're abusing exception handling here to catch a potentially non-exceptional failure mode which is "we couldn't schedule, we need to add back those cores". Didn't rework things though, just pushed the exception logging in to the only chunk of code that wasn't already in a nested try/except.

[batch] Don't double log exceptions in job scheduling

---

hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala

This feels like a bug in `java.net.URI`, but who am I to upend decades of software:
```
scala> import java.net.URI
import java.net.URI
scala> new URI("gs://nd_qc/preimp_qc/GWASpy/Preimp_QC/wave1_pilot_qced.mt").getAuthority
res0: String = nd_qc
scala> new URI("gs://nd_qc/preimp_qc/GWASpy/Preimp_QC/wave1_pilot_qced.mt").getHost
res1: String = null
scala> new URI("gs://nd_qc/preimp_qc/GWASpy/Preimp_QC/wave1_pilot_qced.mt").getPort
res2: Int = -1
scala> new URI("gs://nd_qc/preimp_qc/GWASpy/Preimp_QC/wave1_pilot_qced.mt").getUserInfo()
res3: String = null
```

[query/service] use authority, not host

---

hail/src/main/scala/is/hail/backend/service/Worker.scala

Ideally, a stream would be able to recover from a transient error by
seeking, but until we have that functionality, this avoids having
one failure out of 5000 (which I have now seen twice).
Example:  https://batch.hail.is/batches/1531518/jobs/2094.

[query/service] retry entire partition when we encounter transient errors in compiled code

---

letsencrypt/Makefile
letsencrypt/letsencrypt.sh
letsencrypt/service.yaml

1. Do not leak the private key for lets encrypt into the renewal container's stdout and consequently into the logs.
2. Do not revert the secret to an empty state before renewing the certificate. Doing so causes a failed renewal (e.g. 500s from lets encrypt) to destroy the extant keys.
---
Anyone using the Hail infrastructure should both regenerate their lets encrypt certificates with the changes in that PR. To do so they can execute the following from the root of the Hail repository:
make -C letsencrypt run
To take advantage of this vulnerability, someone would need access to the k8s container logs and the ability to redirect the relevant domain name to an IP they control. We have no evidence anyone has done this with Hail’s certs.

[letsencrypt] no secret logging and no blowing away secret

---

hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala

This retries all the basic RPC methods of GoogleStorageFS. I saw a transient
error arise from an `open` in generated code. These changes would have
retried the `open` and not failed the job (1 of 50,000 jobs :( ). However,
I am still not sure how to retry an error during actual writing (as opposed
to opening the OutputStream). I think we have to retry the whole partition.
See further discussion in Zulip.

[query/service] even more retries

---

infra/gcp/main.tf

Looks like this has been removed: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/v2-upgrade-guide#changes-in-v200

Remove obsolete load_config_file argument

---

notebook/Dockerfile.create-tables

Couldn't find any use of this Dockerfile anywhere nor could I find `create-notebook-tables.sql` so I'm assuming it's dead.

[notebook] Delete unused Dockerfile

---

ci/ci/github.py

Given our rate limit increases and turning on additional service tests, 5 concurrent PR batches is too much for the 4-core database to handle. This is a mitigation while we figure out the right way to maintain that load.

[ci] Bring max number of concurrent PRs down to three

---

hail/python/hail/vds/methods.py
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerDistributedSort.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

The `to_dense_mt` and `to_merged_sparse_representation` methods required
localizing into an array all of the split rows at each locus when the
variant data is on the right side of the join. We flip the order so that
the variant data are on the left and the reference data, known to be
locus-distinct, are on the right.
I also fix a few stream mis-parameterizations that led to a slightly
higher (but similarly scaling) memory usage.

[query] Fix high memory usage VDS converters after splitting multiallelics

---

ci/ci/github.py

This should make `merge_priority` consistent across all CIs so we shouldn't have deadlocks resulting from mismatched merge candidate.

[ci] take status on other CIs into account for merge candidate

---

hail/python/hailtop/aiotools/copy.py
hail/python/requirements.txt

For the `hail` python package, even if some things don't work great/at all, I think it would be nice if it at least installed on windows. `uvloop` is unsupported on windows, so I add a little logic to ensure that it's not requried on windows and the copy tool doesn't fail if it's not found.

Better windows support

---

hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py

IncompleteReadError is exported from asyncio and has been since python
3.6 (as far back as I checked). At some point (checked with python 3.10)
it stopped being accessible from asyncio.streams

[hailtop/aiogoogle] Fix import

---

hail/python/hail/fs/router_fs.py
hail/python/hailtop/aiocloud/aioaws/fs.py
hail/python/hailtop/aiocloud/aioazure/fs.py
hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py
hail/python/hailtop/aiotools/fs/__init__.py
hail/python/hailtop/aiotools/fs/fs.py
hail/python/hailtop/aiotools/local_fs.py
hail/python/hailtop/aiotools/router_fs.py
hail/python/test/hail/matrixtable/test_file_formats.py
hail/python/test/hail/utils/test_utils.py
hail/python/test/hailtop/test_aiogoogle.py

The `hadoop_ls` interface has traditionally supported globbing. This improves the service backend to also support Python-style globbing. The strategy is straightforward:
1. Break the object name into components (the bits between `/`s)
2. Find the components with glob patterns. Call these pattern-components.
3. For each pattern-component, list the files in its `dirname`. Find entries which match the pattern-component.
cc: @tpoterba @chrisvittal , y'all have a vested interest in the Query Python FS API.

[query/service] implement globbing for RouterFS

---

hail/python/hail/vds/methods.py
hail/python/test/hail/vds/test_vds.py

During testing of our gnomAD v4 exome dataset we determined that there was better separation of x-ploidy values by using only the variant dataset to determine the mean DP of chromosome X rather than the reference blocks.
This PR is my attempt to add an option to the the VDS `impute_sex_chromosome_ploidy` method that will only compute the ploidy estimates using the variant dataset instead of the default option of using the reference blocks.
The code should still filter to variants that fall within the `calling_intervals`.

[vds] Add option to VDS impute sex to use only the variant data

---

docker/hail/Dockerfile
hail/Dockerfile.hail-pip-installed
hail/Dockerfile.hail-pip-installed-python37
hail/Dockerfile.hail-pip-installed-python38

Putting the tar in its own `COPY` layer means we drag around the tar in the resultant image. This uses a read-only mount for the subsequent `RUN` command to extract the tar without adding it to the image. This should save close to 100MB on the image size.
Also realized that this happens in our pip-installed images.

[docker] Dont store the wheel tar in hailgenetics image

---

hail/python/hailtop/utils/utils.py

Two rare events is notable and probably indicates an error anyway. Let us prefer
to get information as soon as possible.

[hailtop] eagerly give transient error info and include delay

---

hail/python/hailtop/httpx.py

`httpx.ClientSession` did not include the logic to set up the timeout. I do
not recall why I had a factory function distinct from the class itself. That
was a mistake. I leave the factory function because it is used prevasively.
However, now, allocating the class itself is also OK.

[httpx] use timeouts and remove footgun

---

hail/src/main/scala/is/hail/expr/ir/lowering/LowerDistributedSort.scala

For example, a tiny table with one partition really ought not to use 64
branches. In the future, we should track the byte-size of partitions and
just use a local sort for one partition tables.

[query/shuffler] somewhat tune branching factor to dataset & log phases

---

docker/python-dill/push.sh
hail/python/hailtop/batch/docker.py

Follow up to previous PR that added 3.9 and 3.10 support.

[batch] Remove python 3.6 support for python jobs

---

docker/hail-ubuntu/Dockerfile

Apparently distutils isn't a core python package anymore. Here's an example where I tried to build the hail ubuntu image on main https://ci.hail.is/batches/2214931
```
#13 59.80 update-alternatives: using /usr/bin/python3.7 to provide /usr/bin/python3 (python3) in auto mode
#13 59.87 Traceback (most recent call last):
#13 59.87   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
#13 59.87     "__main__", mod_spec)
#13 59.87   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
#13 59.87     exec(code, run_globals)
#13 59.87   File "/usr/lib/python3/dist-packages/pip/__main__.py", line 16, in <module>
#13 59.87     from pip._internal.cli.main import main as _main  # isort:skip # noqa
#13 59.87   File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line …
```

[docker] Include distutils in hail ubuntu image

---

hail/python/hailtop/batch/docker.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/process.py

This adds support to optionally view the docker output in `build_python_image`. I'm not sure what our general strategy is for adding inputs to user-facing functions. I tried to maintain backwards compatibility, but it feels very weird and similarly wrong to put a normal parameter after an underscore parameter. I feel like it would be best to have `_tmp_dir` be keyword-only. That would also technically be breaking, but does the underscore prefix relinquish us from that responsibility?

[batch] Add option to show docker output when building images

---

hail/python/hail/plot/plots.py

This is a small change which allows `hl.plot.smoothed_pdf` to optionally take an existing figure to add the pdf plot to, rather than creating a new figure. As the old plotting interface should be deprecated soon, I'm not too worried about adding the option to the other plots as well.

[query] allow smoothed_pdf to add plot to existing figure

---

hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala

Just to be sure that we're committing all the data, in case there's
a poorly behaved output stream somewhere.

[query] Add flush to lowered text exporters

---

hail/src/main/scala/is/hail/expr/ir/agg/ArrayElementLengthCheckAggregator.scala

I spruced up the entire method, but the bug was in the original
L153. One of the Code=>Value changes in the last couple of months
added the memoize to eltOffset. This was a ticking time bomb --
the usage of eltOffset inside `seq` must be evaluated inline, since
the value of `idx` changes between iterations of the loop where the
code argument to `seq` is located.
I suspect this has worked until now because `idx` is 0 every time
this method is called in typical runtimes. It exploded for the
buffered aggregator PR, where we are calling the copy with a stale
value of `idx` presumably equal to the length of the array, so we're
reading memory off the end of the array allocation.

[query] Fix latent bug in ArrayElementAggregator copy

---

hail/python/hail/vds/methods.py
hail/python/test/hail/vds/test_vds.py

CHANGELOG: Fix incorrectly missing entries in to_dense_mt at the position of ref block END.

[vds] Fix behavior of to_dense_mt and off-by-one END comparison

---

batch/batch/worker/worker.py

Since `jvm.kill` is an async function it needs an `AsyncExitStack`. `ExitStack` doesn't `await` its callbacks.

[batch] Use AsyncExitStack for jvm.kill cleanup

---

hail/src/main/scala/is/hail/expr/ir/lowering/LowerDistributedSort.scala

For each large segment in each loop iteration, we pick a branch factor
based on the size of the chunks in each segment.
Future work includes choosing a branch factor even for the first loop
iteration, which we currently cannot do without knowing the byte sizes
of the incoming data (not something comupted at present)

[query] Add adaptive branching to LowerDistributedSort

---

hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py
hail/python/hailtop/aiocloud/common/session.py
hail/python/hailtop/auth/auth.py
hail/python/hailtop/httpx.py
hail/python/hailtop/utils/utils.py

cc: @daniel-goldstein, this is a tricky asyncio situation which you should also keep in mind
OK, there were two problems:
1. A timeout of 5s appears to be now too short for Google Cloud Storage. I am not sure why but we
timeout substantially more frequently. I have observed this myself on my laptop. Just this
morning I saw it happen to Daniel.
2. When using an `aiohttp.AsyncIterablePayload`, it is *critical* to always check if the coroutine
which actually writes to GCS (which is stashed in the variable `request_task`) is still
alive. In the current `main`, we do not do this which causes hangs (in particular the timeout
exceptions are never thrown ergo we never retry).
To understand the second problem, you must first recall how writing works in aiogoogle. There are
two Tasks and an …

[copy] fix the TimeoutError and ServerDisconnected issues in copy

---

hail/python/hailtop/aiocloud/aioaws/fs.py
hail/python/hailtop/aiocloud/aioazure/fs.py
hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py
hail/python/hailtop/aiotools/fs/__init__.py
hail/python/hailtop/aiotools/fs/copier.py
hail/python/hailtop/aiotools/fs/fs.py
hail/python/hailtop/aiotools/fs/stream.py
hail/python/hailtop/aiotools/local_fs.py
hail/python/hailtop/aiotools/router_fs.py
hail/python/hailtop/httpx.py
hail/python/test/hailtop/inter_cloud/test_fs.py

No changelog because the copy tool is not properly public, though
maybe it can be public now.
The main problem was that we were saturating our network bandwidth
with data we did not need. Why? As far as I can tell, `release` on
an `aiohttp.ClientResponse` is insufficient to stop the receipt of
more bytes.
I realized one proper fix was to simply tell the cloud storage vendors
how much data we wanted to receive. That is the change to `open_from`
which I have made pervasively to all clouds.
I also changed `release` to `close` because that seems more correct.
I do not understand why we only `release`d it before.

[copy] finally eliminate all stalls from the copy tool

---

hail/python/hail/expr/functions.py

CHANGELOG: `hl.rand_unif` now has default arguments of 0.0 and 1.0

[query] default rand_unif to [0, 1]

---

hail/python/hailtop/hail_logging.py

Python 3.8 [added a validate parameter](https://docs.python.org/3/library/logging.html#logging.Formatter) to the stdlib Formatter which is on by default and doesn't like our format strings, which I guess python 3.7 is just too lenient about? Anyway I updated the format string to match the docs' recommendation.

[hailtop] Use python3.8-compatible format string for json logger

---

ci/Dockerfile.ci-utils
hail/scripts/deploy.sh

Skopeo was yanked from the Kubic repository and there's not an obvious place to retrieve it for 20.04 yet. Removing it as a dependency to unblock current PRs until the issue is resolved.

[ci] Dont depend on Skopeo

---

hail/python/hailtop/aiocloud/aioazure/fs.py
hail/python/test/hailtop/inter_cloud/test_fs.py

[This test](https://github.com/hail-is/hail/blob/9ad2e64bd7570199ebdb64304b6ca6599749b260/hail/python/test/hail/utils/test_utils.py#L88) suggests that `fs.open` should fail immediately if the desired blob does not already exist. This is true of the hadoop and the aiogoogle FS implementations. The azure implementation varies slightly in that `open` will succeed if the blob does not exist but *read* will throw an exception. The current async fs test for a nonexistent file does both open and read so the subtle distinction is flying under the radar. The azure sdk intentionally allows you to create a blob client for a blob that doesn't exist, so we have to do an existence check ourselves.

[aiotools] Make Azure fs.open raise a FileNotFoundError if blob does not exist

---

build.yaml

We no longer have a service with the identity of Query, so no longer have a `query-gsa-key`. This was left over from an incomplete deletion, and since Batch now owns the query jar bucket, we should use its identity to upload jars to it.

[query] Fully rip out query-gsa-key

---

build.yaml

Those env variables most have been copy-pasted from another step because they're neither correct nor necessary. I tried downloading the batch-gsa-key and running `upload-query-jar` with it as the credentials and it succeeded.

[ci] Fix upload_query_jar azure credentials

---

hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala

We probably should have better retry logic, but hopefully this will alleviate some of the errors in the short term.

[hail] Set AzureFS timeout to 30s

---

hail/python/hail/docs/Makefile

Currently none of the figures are copied with the notebook into the docs.

[docs] preserve iframe_figure directory during build

---

hail/python/hail/methods/statgen.py

Fixes #11229.
The `a_index` field is added by split_multi and should be present
on the non-split table as well.

[query] fix docs for split_multi

---

batch/batch/worker/worker.py

This reduced the number of logs in "worker.log" by over 80% from 515K lines to 77K for an hour with some load.
https://console.cloud.google.com/logs/query;query=resource.type%3D%22gce_instance%22%0AlogName:%22worker%22%0ANOT%20labels.namespace%3D%22default%22%0ANOT%20%22crun%20process%22%20AND%20NOT%20%22crun%20run%20process%22%20AND%20NOT%20%22marking%20complete%22%20AND%20NOT%20%22initializing%22%20AND%20NOT%20%22running%20input%22%20AND%20NOT%20%22input:%22%20AND%20NOT%20%22running%20main%22%20AND%20NOT%20%22main:%22%20AND%20NOT%20%22running%20output%22%20AND%20NOT%20%22output:%22%20AND%20NOT%20%22cleaning%20up%22%20AND%20NOT%20%22downloading%20JAR%22%20AND%20NOT%20%22running%20jvm%20process%22%20AND%20NOT%20%22uploading%20log%22%20and%20NOT%20%22Obtained%20writer%22%20AND%20NOT%20%22fi …

[batch] Cleanup worker logs

---

hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py

The docs say we should use at a minimum 8 MB chunks. With 50 way parallelism that's 400 MB in memory which should be fine.

[aiogoogle] Increase chunk size when copying files to GCS

---

hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala

We do not make guarantees about the exact contents of a folder after
a parallel export. We do guarantee that all data is in the folder
however, so we must make it speculation safe. We do so by adding a UUID
to each part file we write for in lowered text export.

[query] Fix text export part file overwrite due to speculation

---

hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/io/vcf/ExportVCF.scala

Fixes #9782.
We need to escape VCF descriptions when exporting.

[query] escape VCF descriptions

---

hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala

Consider the case where there are 100 states. We will attempt
three combines because (100 + 50) / 50 is 3. In that case the
third context will be an empty slice. This will trigger the
errror reported by Wenhan [here](https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/HailException.3A.20array.20index.20out.20of.20bounds/near/286347013).

[query] nCombines calculation in tree aggregate

---

hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala

Issue the [rewrite] request. To save on reading and writing entire
blobs, as well as transferring data to the machine running the copy
rather than letting google storage move the data.
This operation should be effectively free when copying from one location
in a bucket to a different location in the same bucket, as the linked
docs say, when source and destination have the same location and storage
class, the blob is copied in a single request and returns immediately.
[rewrite]: https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite

[query] Specialize GoogleStorageFS.copy

---

hail/python/hail/fs/router_fs.py
hail/python/test/hail/utils/test_utils.py

Currently, if we have a file structure like:
a/
b/
aa/
bb/
A glob pattern like `*/b` will raise FileNotFoundError beacuse
we try to list the file or folder named "b" inside `aa`. We should
not error. We should return `['a/b']`.
It is insufficient to avoid FileNotFoundError altogether because
the Hadoop API treats paths without globs differently. In particular,
listing the path `aa/b` should raise an error.
This change fixes behavior in the first case and treats the second
case explicitly.

[fs] not FileNotFoundError for glob patterns

---

hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala

We frequently use head(1) in the linear algebra stuff and it triggers four partitions
even though in almost all cases the first row is in the first partition.

[query] head(1) & tail(1) optimistically look at one partition

---

hail/python/test/hail/matrixtable/test_file_formats.py

Pytest sometimes uses a background thread to collect tests. That interacts badly
with asyncio. We avoid this by explicitly managing the event loop.

[query] avoid rare test collection bug

---

hail/python/hail/backend/service_backend.py
hail/python/hail/builtin_references.py

The tests use multiple threads which can race to download the references. This is a bit
of a blunt fix. In particular, this is not an asyncio-friendly lock (because I need
thread safety, which asyncio.Lock does not provide). In general, users should not try
to initialize hail multiple times in different coroutines in the same thread.

[QoB] protect reference download with a lock

---

datasets/extract/extract_gencode_v35_annotation_gtf.sh
datasets/notebooks/GENCODE.ipynb
hail/python/hail/docs/datasets/schemas/gencode.rst
hail/python/hail/experimental/datasets.json

Fixes #11899 .
To make [GENCODE v35](https://www.gencodegenes.org/human/release_35.html) available via the datasets API, as requested in issue https://github.com/hail-is/hail/issues/11899. 
The Hail Table was created from the [comprehensive gene annotation (on the reference chromosomes only) GTF file](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_35/gencode.v35.annotation.gtf.gz).

[datasets] add GENCODE v35

---

hail/python/hail/backend/local_backend.py
hail/python/hail/backend/py4j_backend.py
hail/python/hail/backend/service_backend.py
hail/python/hail/backend/spark_backend.py
hail/python/hail/experimental/vcf_combiner/vcf_combiner.py
hail/python/hail/expr/aggregators/aggregators.py
hail/python/hail/expr/expressions/typed_expressions.py
hail/python/hail/expr/functions.py
hail/python/hail/expr/types.py
hail/python/hail/ir/__init__.py
hail/python/hail/ir/base_ir.py
hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/ir/ir.py
hail/python/hail/ir/matrix_ir.py
hail/python/hail/ir/renderer.py
hail/python/hail/ir/table_ir.py
hail/python/hail/ir/utils.py
hail/python/hail/matrixtable.py
hail/python/hail/methods/qc.py
hail/python/hail/table.py
hail/python/hail/vds/combiner/combine.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
hail/src/main/scala/is/hail/expr/ir/Optimize.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/rvd/RVD.scala

High level design:
* `ApplySeeded` takes a child of type `trngstate`. It is always constructed as a free reference `__rng_state`, which must be defined by a parent, who has the responsibility to ensure the seeded function is given a distinct rng state on each invocation.
* Any node with a child which may be executed more than once (e.g. `TailLoop`, stream nodes, table nodes) must use `Let('__rng_state', RNGSplit(Ref('__rng_state'), uid), child)`, where `uid` is a long or tuple of longs which is guaranteed to be distinct on every execution of `child`.
* Uids are typically created at the leaves of pipelines (`TableRead`, `StreamRange`, etc.), and propagated upwards.
There was a phase-ordering conflict that had to be worked around:
* IRs must be given explict rng state and uid semantics as …

[query] python side infrastructure for deterministic rngs

---

hail/python/test/hail/matrixtable/test_matrix_table.py
hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala

Can lead to keys being pruned upstream, producing invalid scans.
CHANGELOG: Fixed correctness bug in scan order for `Table.annotate` and `MatrixTable.annotate_rows` in certain circumstances.

[query] Fix key pruning bug with respect to table/matrix row scans.

---

hail/python/hailtop/utils/utils.py

This way the second error will be "caused by" the original retry once error. I think
this is worthwhile because otherwise we will never know what the first error was.

[hailtop] improve stack traces for retry once errors

---

ci/ci/constants.py

They all have broad emails now, which is what I used for their Batch usernames.

[ci] allow core AUS devs to see CI pages

---

hail/python/hailtop/batch/batch_pool_executor.py
hail/python/hailtop/batch/job.py
hail/python/test/hailtop/batch/test_batch.py
hail/python/test/hailtop/batch/test_batch_pool_executor.py

CHANGELOG: `hb.BatchPoolExecutor` and Python jobs both now also support async functions.

[batch] allow async functions in BPE and PythonJob

---

hail/python/hail/experimental/vcf_combiner/vcf_combiner.py

We were not properly handling cases where there were exactly 10 or 100
files to write. We would handle all other cases correctly.
Closes #11891

[vcf combiner] Fix error in determining intermidiate file names

---

batch/batch/driver/job.py
batch/sql/estimated-current.sql
batch/sql/minimize-deadlock-errors.sql
build.yaml

There were two sources of deadlocks:
1. The attempt resources were not inserted in the same order in the aggregated_*_resources tabes between the two triggers `attempt_resources_after_insert` and `attempts_after_update`. One had jobs -> batches -> billing projects and the other had billing_projects -> batches -> jobs. We also were inserting the resources in a different order in the two triggers. I solved the ordering issue by making sure we `INSERT MANY` the resources in alphabetical order.
2. Once I fixed (1), then the next set of errors were in `add_attempt`. We were locking the `instances_free_cores_mcpu` table only if the attempt didn't already exist. This was causing cryptic deadlock errors like this:
```
------------------------
LATEST DETECTED DEADLOCK
------------------------ …
```

[batch] Fix deadlock errors when inserting attempts and attempt resources

---

hail/src/main/scala/is/hail/services/package.scala

The invalid grant error below this line is wrapped in a `StorageException`. We want to open up these wrapping exceptions to see if there's a true error underneath.

[query] Inspect error causes in isRetryOnceError

---

build.yaml
hail/python/hail/docs/change_log.md

There must be a blank line after three dashes, otherwise you get this error:
```
[WARNING] Could not parse YAML metadata at line 64 column 1: :8:0: Unexpected '-'
```

[website] fix change_log.md & treat pandoc warnings as errors

---

internal-gateway/nginx.conf

We still have the error log. This produces a lot of logs and I have never used it for debugging purposes.

[internal-gateway] disable access log

---

hail/python/hail/backend/service_backend.py
hail/python/hail/context.py
hail/python/hailtop/config/user_config.py
hail/python/test/hail/backend/test_service_backend.py
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
query/.gitignore

CHANGELOG: `hl.init` now supports `worker_cores` and `worker_memory` options when using Hail Batch backend.

[query] Add worker_cores and worker_memory options to hl.init when using batch

---

hail/python/hail/backend/service_backend.py
hail/python/test/hail/methods/test_qc.py
hail/python/test/hail/methods/test_statgen.py

I am not sure what persist should mean in the service backend. For some linear
algebra work, persist appears to be used to store the results of an expensive
query. In that setting, we should clearly checkpoint the dataset.
cc: @tpoterba

[query] persist is checkpoint

---

batch/batch/worker/worker.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

1. Treat any 500 from Docker as a retryable error.
2. Move DockerError transiency to is_transient_errors and use retry_transient_errors instead of a hand rolled transient wrapper.
The first change also makes us robust to changes in error messages on the GCR side. In particular, we started seeing this error message:
```
Head https://gcr.io/v2/hail-vdc/ubuntu/manifests/18.04: Get https://gcr.io/v2/token?account=_json_key&scope=repository%3Ahail-vdc%2Fubuntu%3Apull&service=gcr.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
which is slightly different from the extant messages we check for.

[hailtop][batch] unify & simplify docker transient error handling

---

infra/azure/variables.tf
infra/gcp/main.tf

I need to get GKE costs down further. The driver is now 3 CPU anyway.
@daniel-goldstein, I am not sure how to modify the Azure terraform. It appears this
is controlled by a variable which is already set to a 4 core machine?

[gke] optimize utilization autoscaling and shrink nodes

---

batch/download-gcs-connector.py
docker/Dockerfile.base-with-spark-3-2
docker/Dockerfile.service-java-run-base
docker/hail/Dockerfile
hail/Dockerfile.hail-run
hail/python/test/hail/utils/test_utils.py
hail/scripts/install-gcs-connector.sh

Modern Spark versions including 3.1.2 [include up-to-date hadoop versions](https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.12/3.1.2).

[many] update gcs connector to recent version

---

batch/driver-nginx.conf

The improvement here was really remarkable. Went from a shaky ~80 jobs per second to ~120 and NGINX max CPU use from 100% to 73%.

[batch] Dont use worker_processes auto in nginx sidecar

---

hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala

This should be configurable, but that was harder than I expected.
This should cut down on the number of class A operations we do a bit. It is quite high right now.

[QOB] reduce default parallelism

---

hail/python/hail/backend/service_backend.py

This slipped in with QoB. We need to cleanup the iodir when we are done with it.

[QoB] remove debugging cruft

---

batch/deployment.yaml

This is unused and the same as `INTERNAL_GATEWAY_IP` a few variables down

[batch] Remove redundant env variable for internal gateway ip

---

hail/Makefile

Discovered because I accidentally had an old build directory in $HAIL/hail/python that was sneakily being rsync'd into the build/deploy directory and then silently picked up by bdist_wheel as a build cache.

[query] Clear the bdist build cache before building the wheel

---

batch/deployment.yaml

Again, [looking at utilization](https://console.cloud.google.com/monitoring/dashboards/builder/982ec67a-4b20-4901-a0aa-af418813a9c4?project=hail-vdc&dashboardBuilderState=%257B%2522editModeEnabled%2522:false%257D&timeDomain=1m&f.rlabel.namespace_name=default&f.umlabel.app=batch-driver), the driver is generally not using its full request. The Python spikes are maybe 35% of utilization and the nginx spikes are maybe 15%. I set the requests to around the top of these spikes. That should ensure that normal daily load is handled without scale up, but during low periods we can pack much better.
cc: @jigold

[batch-driver] reduce requests

---

ci/ci/build.py

Based off of discussion in #11907, this aims to avoid separate PRs from clobbering the image cache tag and sets up PR-specific cache tags per image. Note that using `ci-intermediate` was also detrimental to the image cache and I don't think different images sharing layers under the common name holds much value. I think we should ultimately get rid of `ci-intermediate` entirely and explicitly name our images so that they don't ruin each other's caches. I tested this in my namespace's CI. Here's the image build times from two consecutive dev deploys:
Before         |  After
:-------------------------:|:-------------------------:
I don't personally see the need for adding more SHAs to the cache as mentioned in #11907, a per-PR cache seems like exactly what you would want. The one drawback I …

[ci] Use image and PR-specific cache tags for image builds

---

grafana/deployment.yaml

The emptyDir is only used to communicate from the initcontainer to the
main container. The autoscaler can safely evict and reschedule Grafana
and the initcontainer will run again and generate the token as necessary.

[grafana] allow grafana to be evicted by autoscaler

---

hail/src/main/scala/is/hail/linalg/BlockMatrix.scala

When `hl.king` is called on a mt with only 2 samples, the result has an empty partition. It probably shouldn't, but regardless I don't think we should be assuming non-empty partitions.

allow empty partition in BlockMatrixReadRowBlockedRDD

---

batch/batch/spec_writer.py

The capacity on the cache is pretty arbitrary, but given that bunches are going to get churned through very quickly and then never used again, it seemed nice to have the assertion that every layer of the cache is always small and shouldn't be an issue to search through in a blocking manner. I tested this with a dev-deployed load-test and observed the number of `get_token_start_id` queries drop from O(jobs) to ~4 per second at max throughput. No difference in profiling, this is just an attempt to reduce the number of queries we're hitting the database with.

[batch] Cache tokens for job bunches on the driver to avoid db queries

---

hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala

This seems unlikely to be causing Lindo's issue, but does seem like a good change?

[query] Interval shuffle memory management

---

gear/gear/auth.py

`_web_unauthorized` should really be `_web_unauthenticated`, since it only makes sense to send someone through an auth flow if they are not logged in. If they are logged in but don't have the right credentials, e.g. in `web_authenticated_developers_only`, this will result in an infinite loop of auth redirects. As such, this also jumps straight to the point in `web_authenticated_developers_only` and raises Unauthorized if the session belongs to a user that is not a dev.

[gear] Dont redirect to auth flow if authenticated but not authorized

---

batch/batch/front_end/front_end.py

The old query plan is here:
```
+----+-------------+-----------------------------------+------------+--------+---------------------------------------------------------------------------------------------------------------+-------------------------------+---------+---------------------------------------------+------+----------+-----------------------------------------------------------+
| id | select_type | table                             | partitions | type   | possible_keys                                                                                                 | key                           | key_len | ref                                         | rows | filtered | Extra                                                     | …
```

[batch] Explicitly use index in get_batches query

---

infra/bootstrap_utils.sh

Hadn't tested bootstrapping since a recent PR made `NAMESPACE` required for any make steps that push images.

[infra] Provide namespace variable to bootstrap uses of make deploy

---

ci/ci/build.py

This is to ensure when we're getting the offsets of the chunks that we don't run out of memory on the client.

[ci] Use 4 cores for db migration jobs in deploys

---

batch/batch/driver/job.py
batch/batch/driver/main.py
batch/sql/add-resource-ids.sql
batch/sql/add_resource_ids.py
batch/sql/delete-batch-tables.sql
batch/sql/estimated-current.sql
build.yaml

This PR adds a new column to the `resources` table (resource_id) as well as to the `attempt_resources` table. The `resource_id` represents the mapping from the string resource name to an integer identifier. To make this migration work, we first need to add the new columns to the corresponding tables along with a new trigger. The trigger makes sure any writes that occur after we start populating the older values will have the new resource_ids filled into the `attempt_resources` table. I decided to not convert the `attempt_{batch, job,billing_project}_resources` tables to have the resource_id because we'll drop them anyways in the future and it was adding 75% more time to the migration. My original script had the updates happening to all tables, hence why there's overkill for the way it's …

[batch] Add resource ids to the attempt resources table

---

infra/gcp/main.tf

Follow-up to https://github.com/hail-is/hail/pull/12025. Without this setting, the Terraform cluster upgrade will fail eventually.
These are cluster-wide limits. I picked rather generous limits, but I'm not sure how many dev deployments you have or whether you generally need a lot of nodes (the current node pool max is 200 nodes).

[batch] Add resource_limits to enable new autoscaling_policy

---

batch/batch/driver/job.py
batch/sql/estimated-current.sql
batch/sql/modify-resource-id-trigger.sql
build.yaml

Stacked on #12028
This PR just does some reconfiguring to enable us to remove the `resource` column in the `attempt_resources` table in the next PR with an online migration.

[batch] Modify attempt resources trigger to prepare for future migrations

---

gear/gear/database.py

To avoid `pymysql` packet sequence errors on long-running pods. See https://hail.zulipchat.com/#narrow/stream/300487-Hail-Batch-Dev/topic/PyMysql.20packet.20sequence.20errors/near/289668489 for context.

[batch] Add pool_recycle parameter to database creation to avoid stale connections

---

batch/batch/driver/main.py
batch/sql/estimated-current.sql
batch/sql/rm-resource-foreign-keys.py
batch/sql/rm-resource-names-agg-resources.sql
build.yaml

Stacked on #12029. This is basically the same as #12030, but I separated dropping the final trigger and the resource column of the table from this PR so we can double check everything looks good and do that last dangerous step separately.
I think this will take about an hour, but I haven't looked timed it recently.
@danking Can you double check none of the SQL operations are blocking. If they are, I think we just have to live with it.

[batch] Switch attempt resources primary keys and triggers to use resource ids

---

hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala

When cleaning up a text export, we delete all files that our successful
tasks didn't produce. We weren't adding tabix files to this set, and so
were deleting tabix files that were created during vcf export. Now, we
explicitly add tabix files to our 'to keep' list.

[query] Fix accidental deletion of tabix files

---

batch/sql/delete-batch-tables.sql
batch/sql/estimated-current.sql
batch/sql/rm-resource-names-agg-resources-pt-2.sql
build.yaml

Stacked on #12029 
This PR rips out the `resource` column from the `attempt_resources` table and used the `resource_id` instead. Notice that the triggers need to use the `resource` and not the `resource_id` because we didn't convert the column in the `aggregated_{batch, jobs,billing_project}_resources` tables.

[batch] Remove resource names from the attempt resources table

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala

The RNGSplit emitter assumed the components of `dynBitstring` were always inferred to be required, but it seems to be impossible to construct the bitstrings in a way that the requiredness inference can always see that.
This first makes the type of `dynBitstring` more constrained to simplify the emitter. Before it was allowed to be a single long, or an arbitrarily nested tuple all of whose leaves are longs. But I believe only flat tuples are actually being generated, so this makes that the enforced type.
Then the emitter asserts all fields are present at runtime.

[compiler] Fix RNGSplit tuple requiredness

---

batch/batch/instance_config.py
batch/sql/add-att-resources-format-version-lt-3.sql
batch/sql/estimated-current.sql
batch/sql/insert_attempt_resources_format_version_lt_3.py
build.yaml

cc: @danking 
Here is the first major database migration. The goal is to add all attempt resources into the database for any attempt with batch format version less than 3. The node configuration was the same for all attempts back then with standard instances, 16 cores, and a 100GB boot disk. I figured out what the quantity for each resource should be by looking at how we compute quantities for resources in `batch/batch/resources.py`. I checked the inserted quantities are identical to the attempts that already exist in the database right after we converted the billing over to using resources.
Once we have all resources for all attempts, the next step (future PR) is to do a scan and repopulate the new aggregated billing tables **by date**. In this PR, I don't try and add the usage to the …

[batch] Add attempts with format version < 3 into attempt_resources

---

batch/sql/estimated-current.sql
batch/sql/revert-attempt-resources-trigger-back-compat.sql
build.yaml

To make future modifications to the `attempt_resources_after_insert` trigger easier to follow, I have this PR which reverts the change to ignore any updates for batch format_version < 3.
Stacked on #11990

[batch] Undo trigger change to ignore updates for format_version < 3

---

hail/python/hail/backend/py4j_backend.py
hail/python/hail/experimental/codec.py
hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala

Reduces the size of the payload sent back to the client with each query

[query] don't send timing info if not requested

---

hail/python/test/hail/experimental/test_experimental.py
hail/python/test/hail/methods/test_impex.py
hail/python/test/hail/methods/test_king.py

Reverts hail-is/hail#11987
Now that the FS seek bug is fixed these shouldn’t run up huge GCS charges

Revert "[QoB] disable import_plink using tests"

---

batch/batch/driver/main.py
batch/sql/add-agg-billing-by-date.sql
batch/sql/delete-batch-tables.sql
batch/sql/estimated-current.sql
batch/sql/populate_agg_billing_by_date.py
build.yaml

Stacked on #11995 
This PR creates all of the new `aggregated_*_resources_by_date` tables that will be used for real time billing and making our billing queries fast and also populates them! It will probably run for ~7-8 hours (online migration) and add an estimated 200 GB to the database. It will take around 5-6 hours to populate the tables and the remainder of the time is doing an audit.
I think we should whiteboard what is going on in person, but the general idea is as follows:
1. Revert any previous work and set the trigger back to the original state (idempotent)
2. Find the latest complete or open batch id. We know that a complete batch will not have updates to the attempts table. This is extremely important because the next steps can be done in parallel rather than serially.
3. Find …

[batch] Add billing tables partitioned by date

---

hail/python/hailtop/aiocloud/aioazure/client/pricing_client.py

pricing.azure.com just changed their certificates to use an internal certificate authority that is not widely trusted. This caused the batch-driver to fail to start. They might fix this, but since we're just getting public information and we're not sending any data, we just use http instead.

[batch] Dont use tls for Azure pricing API

---

batch/sql/estimated-current.sql
batch/sql/revert-temp-agg-by-date-infra.sql
build.yaml

Stacked on #11996. This change gets rid of the extra dummy variable and temp table used for bookkeeping the previous migration to populate the aggregated billing tables.

[batch] Revert infrastructure for populating agg-by-date tables

---

ci/ci/build.py

Error message was this:
```
+ kubectl -n pr-12053-default-chqnmsebv8fq scale deployment batch-driver --replicas=0
Error from server (Forbidden): deployments.apps "batch-driver" is forbidden: User "system:serviceaccount:pr-12053-default-chqnmsebv8fq:admin" cannot get resource "deployments" in API group "apps" in the namespace "pr-12053-default-chqnmsebv8fq"
```

[ci] Fix missing api groups in pr namespace admin role

---

hail/src/main/scala/is/hail/methods/LocalLDPrune.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/methods/LocalLDPruneSuite.scala

This simplifies the code and means that region bookeeping for the prune
queue is unnecessary.

[query] Rewrite ld prune to use java objects for filtering

---

hail/python/hail/matrixtable.py

Otherwise you get an error from the compiler on IR construction/typechecking

[query] Good error for `localize_entries` to existing field name

---

ci/ci/build.py

We were missing permissions for "deployments/scale" to be able to set the number of replicas of the batch driver to 0 in the cleanup instances step.

[build.py] Add missing sa privilege for deployments/scale

---

hail/python/hail/docs/datasets/schemas/panukb_meta_analysis_all_ancestries.rst
hail/python/hail/docs/datasets/schemas/panukb_meta_analysis_high_quality.rst
hail/python/hail/docs/datasets/schemas/panukb_summary_stats.rst
hail/python/hail/experimental/datasets.json

Currently, the Hail datasets API only has the pan-UKB datasets available via the Amazon S3 bucket. This PR makes the pan-UKB datasets available via GCS as well (from the `gs://ukb-diverse-pops-public` bucket), and updates the summary statistics and meta-analysis MatrixTables to reflect the most up-to-date release.

[datasets] update pan-UKB datasets and make available via GCS

---

hail/python/hail/context.py
hail/python/hail/expr/functions.py

CHANGELOG: Fix bug where hl.init could silently overwrite the global random seed.

[query] fix global seed initialization and enable doctests

---

batch/batch/batch.py
batch/batch/batch_format_version.py
batch/batch/driver/job.py
batch/batch/driver/main.py
batch/batch/front_end/front_end.py
batch/batch/utils.py

Stacked on #12006 
This PR actually uses the new tables within the client application. The billing page should now load quickly. Note that the old aggregated billing tables are still in the database and being populated.
The key thing to note is I switched how we are computing the cost. First, I aggregate the usage by resource before multiplying by the resource rate and summing. Therefore, the old and new numbers should be close, but not identical in the UI.
The reviewer should double check that there are no references to `aggregated_*_resources$` tables (the ones that do not have the date interval) within the application code.

[batch] Use the new aggregated by date billing tables

---

hail/src/main/scala/is/hail/expr/ir/lowering/LowerDistributedSort.scala
hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/main/scala/is/hail/utils/package.scala

Number of rows per partition still limited at MAXINT, with check.

[query] Fix limitation to 2^32 rows for new shuffle algorithm.

---

build.yaml

This step uses `set -e` so a failed clone fails the whole step. I fixed this using `retry` but also use a fresh temporary directory for each clones so if a clone fails part of the way through it doesn't reuse the broken directory.

[ci] Fix retryable cloning of ci test repo

---

batch/batch/driver/main.py
batch/batch/worker/worker.py
batch/sql/add-real-time-billing.sql
batch/sql/estimated-current.sql
build.yaml

Stacked on #11997
This PR enables real-time billing. It should be relatively straightforward. It uses the MySQL v8 instant add of a column. Therefore, we need to switch the Azure infrastructure to use V8.0 before this PR merges. I'm not sure how long this update will lock the attempts table, but hopefully it's not too long. I can test it out on my test database next week. This is an online migration.
The key thing to double check is I got the trigger updates to use the new `rollup_time` correctly and am not missing any updates to the attempts where the rollup time needs to be updated as well.

[batch] Add real time billing!

---

infra/gcp/main.tf

Node auto-provisioning (turned on by the `enabled` flag) doesn't mix well with manually-provisioned pools like we do here with terraform. TL;DR, the auto-provisioning autoscaler will not direct manually-provisioned node pools to autoscale. This does not impact the scheduler, so applying this terraform to a cluster that already has the nodes that it needs can silently work, but without this fix a new cluster will fail to scale up from 0 nodes.

[infra] Disable GKE node auto-provisioning

---

infra/gcp/gsa_k8s_secret/main.tf
infra/gcp/gsa_k8s_secret/variables.tf
infra/gcp/main.tf

The real change here is changing the preemptible pool config from `preemptible = true` to `spot = true`, but the `spot` config was only available in the new provider which involved a major version upgrade. The only incompatibility was the addition of an explicit `project` input to `google_project_iam_member`, as opposed to picking it up from the provider configuration.
Tested just now in my own project.
If one wants to apply this change without incurring downtime for preemptible deployments, they should follow the instructions outlined in the [migrating node pools dev-docs](https://github.com/hail-is/hail/blob/main/dev-docs/kubernetes-operations.md#when-using-terraform).

[infra] Move GCP preemptible pool to spot

---

hail/python/hailtop/hailctl/dataproc/start.py

This is helpful for running Dataproc with a service account without access to all buckets in a GCP project.

[hailctl] Allow overriding the temp bucket for Dataproc

---

infra/k8s/ci/main.tf

These are present in GCP and required to run CI in Azure. Must have been a manual fix that didn't make it into PR when we set up Azure CI.

[infra] Give Azure batch the same clusterrole it has in GCP

---

hail/python/hail/docs/functions/index.rst
hail/python/hail/docs/functions/random.rst
hail/python/hail/expr/__init__.py
hail/python/hail/expr/functions.py
hail/python/hail/ir/register_functions.py
hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/expr/ir/functions/RandomSeededFunctions.scala

CHANGELOG: Add `rand_int32` and `rand_int64` for generating random 32-bit and 64-bit integers, respectively.

[query] add rand_int32 and rand_int64

---

batch/batch/worker/worker.py
batch/test/test_batch.py
hail/python/hailtop/utils/utils.py

Weirdly, GCR returns a 500 for an invalid repository name instead of a 404, so we retry it endlessly. We need to special-case our transient errors to treat 500s with "Invalid repository name" messages as *not* transient errors, and then give the user the error message that their image repository is invalid. This follows the same pattern that we use for invalid image names.

[batch] Do not retry pulling images from invalid repositories

---

hail/python/hail/ggplot/ggplot.py
hail/python/hail/ggplot/scale.py
hail/python/hail/ggplot/stats.py
hail/python/hail/ggplot/utils.py

The identity color scale (which treats the values of the "color" aesthetic mapping as literal hex color codes) was grouping by the color values, because their type "tstr" is normally a discrete type. This had the effect of reordering data unnecessarily, and creating a pointless noisy legend for the trivial color scale.
This changes the identity color scale to be continuous. It also modifies the grouping logic to group by aesthetics with discrete scales, not with "discrete types". Now the identity color scale doesn't group or create a legend.

[ggplot] make identity color scale continuous

---

hail/src/main/scala/is/hail/services/package.scala

Because HttpResponseException is a subclass of IOException, the match clause for HttpResponseException in isRetryOnceError is unreachable. As a result, account-not-found errors for Google Cloud Storage are not handled correctly. This change reorders the match clauses accordingly.

[query] handle retry once errors in the correct order

---

batch/test/failure_injecting_client_session.py
batch/test/test_accounts.py
batch/test/test_batch.py

Basically all naming, rids these test files of linting errors. We do a lot of reassigning a `BatchBuilder` variable to a `Batch` and so I consolidated around `bb` and `b`. A couple instances where I remove debug_info from an assert statement is because the associated `Batch` object would not exist, since that assert is triggered by an error that's raised before the `Batch` object is created.

[batch] Remove lint errors from test_batch and test_accounts

---

hail/python/hail/ir/matrix_ir.py
hail/python/test/hail/matrixtable/test_matrix_table.py

CHANGELOG: Fixed crash in `collect_cols_by_key` with preceding random functions

[query] Fix handle_randomness for `collect_cols_by_key`

---

hail/Makefile
hail/build.gradle
hail/src/main/scala/is/hail/asm4s/ClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala

Between Java 8 and Java 11, the `.newInstance()` method and the `-Xlint:-sunapi` compiler flag were deprecated, which prevents hail from being built with the Java 11 JDK, despite [the docs](https://hail.is/docs/0.2/getting_started_developing.html) suggesting otherwise. This change replaces usages of `.newInstance()` with [`.getDeclaredConstructor().newinstance()`](https://stackoverflow.com/questions/56079042/fix-to-java-newinstance-deprecated) and of `-Xlint:-sunapi` with [`-XDignore.symbol.file`](https://stackoverflow.com/questions/13855700/suppress-javac-warning-is-internal-proprietary-api-and-may-be-removed-in-a-f).

[query] remove incompatibilities with java 11

---

hail/python/hailtop/utils/utils.py

We have to mirror a lot of our utilities across python and scala. Looks like this error never made it to python and we just hadn't encountered it in our python client until a user hit it yesterday.

[utils] Add invalid grant to python retry-once errors

---

hail/python/test/hail/matrixtable/test_matrix_table.py
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/LowerOrInterpretNonCompilable.scala
hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPass.scala

This is a bad change to a worse problem. The right solution is to redesign the IR
so that implicit init eval scopes don't exist -- but the right solution is hard to justify
going off to do right now.
This change patches the Extract.scala lowering logic to track the variables bound inside a
lowered IR and find the highest node that provides all necessary free variables. This change
still makes assumptions about the structure of the IR -- namely, it is still invalid to write
an IR like:
```
MakeTuple
Let
initBinding1
<something>
ApplyAggOp with ref to initBinding1
Let
initBinding2
<something2>
ApplyAggOp with ref to initbinding2
```
However, this fix resolves the case where init args reference a high single binding chain, as
in the test added.

[query] Fix lowering of aggs to preserve free variables in init args

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/ir/Simplify.scala

We do not guarantee that the intervals are ordered and appropriately unioned on the node.
CHANGELOG: Fix incorrect composition of interval filters with unordered interval lists that could lead to over- or under-filtering

[query] Fix FilterIntervals simplify rule

---

batch/batch/driver/instance.py

We were getting lots of exceptions when an instance was no longer reachable because it had either been preempted or idled out. The driver could have been offline or the monitor instances / health check loop ran before the activity log monitor was able to process the delete instance events. This PR attempts to tone down the exceptions such that we only get errors for instances that are likely to be zombies (no contact for 5 minutes) rather than normally disappearing instances. However, I do think we should have a separate Grafana alert for when we have lots of instances being deactivated because they couldn't contact the driver as that's a sign of a bigger problem.

[batch] Tone down healthcheck exception

---

batch/batch/spec_writer.py

We keep an in-memory cache on the driver for which job ranges correspond to which job spec token. Currently, we cache the open range [N, None) which corresponds to the last bunch in the batch. This is fine when the batch is all submitted at once, but can become stale if there are updates to the batch. Here, we just use the range [N, n_jobs), which even if the number of jobs in the batch changes should still be correct.
Ultimately, I think we should just add the end id to the batch_bunches table instead of doing this subquery and join against the batches table. This is a bit of a hack.

[batch] Dont include open-ended job ranges in token cache

---

hail/src/main/scala/is/hail/io/fs/FS.scala
hail/src/test/scala/is/hail/fs/FSSuite.scala

This assert is here because the buffer we use in the FS is a Java array and can't be longer than MAX_INT, but clearly the position in the blob can be more than that. This currently breaks range reads into indexes on data that's more than 2GiB.

[query] Allow seeks more than MAX_INT bytes away

---

batch/batch/front_end/front_end.py
batch/sql/add-batch-updates.sql
batch/sql/delete-batch-tables.sql
batch/sql/estimated-current.sql
batch/sql/populate_batch_updates.py
build.yaml

Stacked on #11998. This PR adds a new `batch_updates` table as well as propagates update_ids to the batch_inst_coll_staging and batches_cancellable_resources tables. The tricky part is making sure that old/currently running batches are migrated properly while new batches are created properly between when the migration has occurred but before batch is redeployed.

[batch] Add infrastructure for updates

---

batch/sql/cleanup-add-batch-updates.sql
batch/sql/estimated-current.sql
build.yaml

Replacement for #12120. Stacked on #12117. 
The `foreign_key_checks=0` is necessary in order to avoid locking the entire table while copying the whole thing.

[batch] Cleanup adding update id infrastructure

---

batch/batch/front_end/templates/billing.html

Currently, the label for the end field on the billing page is `End:`.
This change clarifies how the field is used by updating that label to `End (inclusive):`.

[batch][UI] update billing end field label

---

ci/buildkit/convert-cloud-credentials-to-docker-auth-config

This adds support for authenticating with multiple docker registries inside a `BuildImage` CI step instead of just one. This will be necessary for switching to Artifact Registry as we will temporarily be pushing images to both registries during the migration.

[ci] Accept multiple registries in the docker auth script

---

hail/python/hailtop/batch/backend.py

Noticed this while running a local "Hello World" batch. It prints the transfer summary (copied 0 bytes) which would be surprising to a new user that has not specified any output files. This fixes that and makes it consistent with the check that we do with the `input_transfer_dicts`

[batch] Dont transfer outputs in the local backend if there arent any

---

hail/Makefile

CHANGELOG: Fix bug that caused make install-on-cluster to fail with a message about sys_platform.
Co-authored-by: ryerobinson <39314627+ryerobinson@users.noreply.github.com>

[query] fix install-on-cluster to handle lines with spaces

---

.github/dependabot.yml

Curious to hear your reaction to this, Daniel, as you've effectively become the dependency czar. For this, we might need to pull in @chrisvittal or @tpoterba to resolve dependency issues.

[dependabot] also monitor hail/build.gradle

---

batch/batch/front_end/front_end.py

This will stuck any clients try to use the token-based idempotency, e.g. QoB

[batch] Return the start_job_id from _create_job_update when the update exists

---

batch/batch/front_end/front_end.py

This isn't used / breaking anything but I noticed that `update-fast` returns the batch id not the update id. The update id makes more sense and aligns with the create-fast endpoint where it returns the id of the thing that it made.

[batch] Return update-id from update-fast endpoint not batch id

---

docker/linux-pinned-requirements.txt
docker/requirements.txt
hail/python/dev/pinned-requirements.txt
hail/python/dev/requirements.txt
hail/python/pinned-requirements.txt
hail/python/requirements.txt

The search bar for the batch docs is broken and just says `Searching…` forever. Tracked it down to a bug in the `sphinx_rtd_theme` dependency that was fixed in a later release. The important files to look at are the `requirements.txt` files not the `pinned-requirements.txt` files as the latter bulk updated a bunch of patch releases when I regenerated them. 
In the mess of version conflicts that updating a dependency appears to do here, I also removed `google-cloud-logging` as it appears to be an unused dependency and `pre-commit` because it is optional for developers and had a hard requirement on a `importlib-metadata` version that made it incompatible with other important libraries that we use. I also explicitly pinned `protobuf` as a major version upgrade that wasn't restricted by some …

[pip] Update dependencies and fix batch docs search

---

hail/python/hail/table.py
hail/python/test/hail/table/test_table.py

CHANGELOG: Support missing values in primitive columns in `Table.to_pandas`.

[query] Support missing values in primitive columns in `Table.to_pandas`

---

hail/python/hail/backend/service_backend.py
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/backend/service/Worker.scala
hail/src/main/scala/is/hail/services/BatchConfig.scala
hail/src/main/scala/is/hail/services/batch_client/BatchClient.scala

This leverages open batches to submit all QoB stages as updates to the same batch the Query Driver is running in. Most of this implementation feels uncontroversial, but there is a backwards-incompatible change to the JVMJob that I don't love. I needed to let the Query Driver know which batch it's running in and did so by adding that as another argument to main. I initially wanted this as an environment variable, but considering that these containers are long-lived I wasn't quite sure how to do that.
I didn't stack this on open batches so this won't work until that goes in but the changes are entirely disjoint

[qob] Add capability for worker jobs to go in the same batch as the driver job

---

hail/python/hail/ggplot/geoms.py

This change makes the labels for groups of points on scatterplots created through `geom_point` configurable by the user.
Consider the following sample code:
```python
from hail.ggplot import ggplot, aes, geom_point
ht = ht.annotate(squared=ht.idx ** 2)
ht = ht.annotate(even=hl.if_else(ht.idx % 2 == 0, "yes", "no"))
ht = ht.annotate(threeven=hl.if_else(ht.idx % 3 == 0, "good", "bad"))
fig = (
ggplot(ht, aes(x=ht.idx, y=ht.squared, color=ht.even, shape=ht.threeven))
+ geom_point()
)
fig.show()
```
Before this change, this code generates the following legend for the plot:
After this change, the legend looks like this (`×` is now the default group name separator):
If `legend_format` is passed to `geom_point`, like so:
```python
...
+ …
```

[query/ggplot] Adds configurable legend format to point geom

---

hail/python/hailtop/batch/backend.py
hail/python/hailtop/batch/batch_pool_executor.py

CHANGELOG: Users running python 3.9 and 3.10 no longer have to specify a `default_python_image` for PythonJobs when using the default image.

[batch] Allow python 3.9 and 3.10 in python jobs without specifying an image

---

docker/third-party/images.txt

I figure we should keep this up to date with our supported python images. AFAIK, we currently only use the mirror of python:3.7. We don't expose any of them as publicly available images, but perhaps we should due to dockerhub rate limits? I suppose that's a question for another day.
We probably want to base our python-dill images on these so that docker hub can't just force push a new version of a tag and break our builds.

[docker] add new python third-party images

---

batch/batch/worker/worker.py
build.yaml
hail/python/hailtop/utils/utils.py
hail/python/test/hailtop/batch/test_batch.py
hail/python/test/hailtop/batch/test_batch_pool_executor.py

For some reason either artifact registry or aiodocker returns a 500 instead of a 403 when a service account does not have access to pull an image. Had to add another special case for handling this error.
https://console.cloud.google.com/logs/query;query=%22ys6od%22;pinnedLogId=2022-10-03T13:09:09.430766581Z%2Fyw46w2divo5eqk0vv;cursorTimestamp=2022-10-03T13:09:09.430766581Z?project=hail-vdc

[batch] Add special-casing for Artifact Registry access denied message

---

hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala

Based on [this comment](https://github.com/hail-is/hail/pull/12185#discussion_r985974224)

[lowering] Remove uses of RVDToTableStage in matrix writers

---

hail/python/hail/vds/variant_dataset.py

CHANGELOG: `VariantDataset` now implemented `union_rows` for combining datasets with the same samples but disjoint variants.

[query] add VDS.union_rows

---

hail/src/main/scala/is/hail/expr/ir/BinarySearch.scala
hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/GenericTableValue.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/SpecializedArrayBuilders.scala
hail/src/main/scala/is/hail/expr/ir/StringTableReader.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/agg/AppendOnlyBTree.scala
hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/GroupedAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/NDArrayMultiplyAddAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/NDArraySumAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/StagedBlockLinkedList.scala
hail/src/main/scala/is/hail/expr/ir/agg/TakeByAggregator.scala
hail/src/main/scala/is/hail/expr/ir/orderings/CodeOrdering.scala
hail/src/main/scala/is/hail/expr/ir/streams/EmitStream.scala
hail/src/main/scala/is/hail/io/avro/AvroPartitionReader.scala
hail/src/main/scala/is/hail/types/physical/stypes/SingleCodeSCode.scala

This means we don't need out Emit params to take a region as arg to load, which was super messy.

[compiler] Redesign streams to take outer region as init param.

---

hail/src/main/scala/is/hail/io/index/StagedIndexReader.scala

CHANGELOG: Fixed bug in reading tables/matrixtables with partition intervals that led to error or segfault.

[query] Correctly return first key in index if query compares less

---

hail/python/hail/ggplot/__init__.py
hail/python/hail/ggplot/geoms.py
hail/python/hail/ggplot/ggplot.py
hail/python/hail/ggplot/labels.py

Currently, `hail.ggplot.geom_point` generates cross-product-style legends when the `shape` and `color` aesthetics each have multiple groups. This change makes that behavior consistent with `ggplot2`'s implementation, producing legends where the groups are factored out. Because the strategy used to accomplish this does not preserve the interactive features of the legends, such as toggling groups' visibility, this change also makes all plots generated via `hail.ggplot.geom_point` [static](https://plotly.com/python/configuration-options/#making-a-static-chart).
For example, before this change, this code:
```python
from hail.ggplot import ggplot, aes, geom_point
ht = ht.annotate(squared=ht.idx ** 2)
ht = ht.annotate(even=hl.if_else(ht.idx % 2 == …
```

[query/ggplot] Replaces cross-product legends with grouped ones

---

hail/python/hail/expr/functions.py
hail/python/hail/ir/ir.py
hail/python/hail/ir/matrix_ir.py
hail/python/hail/ir/table_ir.py
hail/python/hail/utils/jsonx.py
hail/python/hail/utils/misc.py
hail/python/test/hail/table/test_table.py

CHANGELOG: Fix bug made more likely by 0.2.101 in which Hail errors when interacting with a NumPy integer or floating point type.

[query] teach query to JSON encode numpy types correctly

---

hail/python/hailtop/batch/backend.py
hail/python/hailtop/batch/batch.py
hail/python/hailtop/batch/job.py

Currently, for each function call that a Python job has, it serializes the entire function definition to a file, to be deserialized and called when the job is run. This change moves the serialization to the batch level, so if the same job calls the same function multiple times, or if multiple jobs within a single batch all call the same function, it will only have its definition serialized once.

[batch] serialize user-defined python functions once per batch

---

hail/python/hail/docs/tutorials/09-ggplot.ipynb

Ignore the missing `[-]` icon; this is a local build of the docs, and I suspect I'm missing a font that it expects me to have installed.

[query/ggplot/docs] fix the tutorials TOC by adding a page title

---

batch/batch/front_end/front_end.py
batch/batch/worker/worker.py
hail/python/hail/context.py

This is useful for tuning resource consumption of large QoB jobs.

[batch] Allow finer granularity for JVM memory settings

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/io/index/StagedIndexReader.scala

CHANGELOG: fixed a bug when reading tables with partition intervals having exclusive left endpoints

[compiler] fix staged index reader

---

build.yaml
ci/ci/build.py
ci/test/resources/build.yaml

I think this is what was wrong with the `git_make_bash_image` taking a minute each time. Since every image without a `publishAs` uses `ci-intermediate`, the `ci-intermediate:cache-PR-X` tag is left pointing to whichever anonymous image built last in the PR run. This is certainly never `git_make_bash_image`, so every time it gets rebuilt, the cache-from that it is using points to an an image whose layers do not include a layer that is `RUN apt-get update && apt-get install -y git make bash`. If this PR runs twice, hopefully we'll see the first step go super quick.

[ci] Require publishAs to preserve per-image caching

---

hail/python/hail/ir/matrix_ir.py
hail/python/hail/matrixtable.py
hail/python/test/hail/matrixtable/test_matrix_table.py
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

Needed for row uid propagation for randomness.

[query] union_cols can keep right row fields

---

docker/third-party/images.txt
grafana/Makefile
grafana/deployment.yaml

Also added it to third-party images so we're not pulling from DockerHub. Turns out the \ufeff bug we were seeing is hitting a lot of people and is addressed in this release. I put this up in my namespace to see that I can load it without error (though didn't try copying over dashboards and such).

[grafana] Update to 9.1.4

---

docker/hailgenetics/hail/Dockerfile

Installing hail from the whl is going to break this cache every time so we end up installing the gcloud sdk on every build, which takes 40 seconds. It'd be nice to also move the extra pip packages further up the image but I think they're ordered this way so that pip gives us hail-compatible versions. I think the best fix would be to track these packages in a requirements.txt that is pinned and constrained on the hail package's requirements.

[docker] Reorder hailgenetics hail docker image layers

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/HailFeatureFlags.scala
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
hail/src/main/scala/is/hail/io/index/IndexWriter.scala
hail/src/main/scala/is/hail/io/index/StagedIndexReader.scala

CHANGELOG: Fixes a rare crash reading tables/matrixtables with _intervals

[query] Redesign staged index reading to compute index then query by index

---

hail/python/hail/backend/local_backend.py
hail/python/hail/backend/spark_backend.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/expr/ir/Binds.scala
hail/src/main/scala/is/hail/expr/ir/Env.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
hail/src/main/scala/is/hail/utils/Graph.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

This refactors the parser to use `BindingEnv`, which tracks the separate eval, agg, scan, and relational environments. This was motivated by the new randomness work, which needs to be able to rebind row and col references in both eval and agg scopes, which was breaking the parser.
I don't like duplicating the (rather complicated) binding behavior of the nodes, but I couldn't find a way to avoid it without a much larger refactoring of the IR. So I tried to make the binding logic in the parser be as direct a copy of what is encoded in `Binds.scala` as possible. For example, relational nodes always pass `env.onlyRelational` to their children, which isn't necessary if we ensure that only relational bindings exist in environments passed to relational nodes, but it matches the logic in `Binds`.

[compiler] use BindingEnv in parser

---

hail/python/hail/matrixtable.py

Horrifying! Lowering supports naive_coalesce, has for some time...

[query] Don't write/read for naive_coalesce in service backend

---

batch/batch/front_end/front_end.py

This can happen when a job-private instance fails to activate. We want to retain that attempt so we have a record of the instances that we tried to create for the job.

[batch] Use the end-time in the UI atttempt-ordering if start_time is None

---

build.yaml

We don't need to fetch to grab the tags off the remote, and we were using the origin instead of the newly-added remote.

[ci] Use correct remote name in pip versioned docs

---

hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala

Making the change we talked about last week in a fresh PR so PCA is faster on the service.

[query] Don't tree aggregate unnecessarily

---

.pre-commit-config.yaml
build.yaml
ci/ci/build.py
ci/ci/ci.py
ci/ci/github.py
ci/ci/templates/namespaces.html
ci/ci/utils.py
ci/sql/active-namespaces.sql
ci/sql/delete-ci-tables.sql
web_common/web_common/templates/header.html

Adds functionality for CI to track which namespaces in the cluster are currently active and which services they are running. See #12095 for more context on the motivation for this change.
As an added bonus, this is one step toward more flexible internal namespace management, i.e. automatic cleanup of dev namespaces or keeping PR namespaces open for X days.

[ci] Track active namespaces in CI database

---

hail/python/hail/matrixtable.py
hail/python/hail/table.py
hail/python/test/hail/matrixtable/test_matrix_table.py
hail/python/test/hail/table/test_table.py

CHANGELOG: semi/anti join methods will now properly accept tables with a shorter but compatible key.

[query] Add good error messages for semi/anti join, fix semantics

---

hail/python/hail/ggplot/geoms.py

Buried in [the documentation for `add_scatter`](https://plotly.com/python-api-reference/generated/plotly.graph_objects.Figure.html\#plotly.graph_objects.Figure.add_scatter) is a little note that says you must set `hoverinfo` to `"text"` *in addition to* setting the hovertext. :shrug:

[ggplot] make tooltip work on geom_point

---

hail/src/main/scala/is/hail/asm4s/ClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala

No multithreading issues here -- these are intended to be used in a read-only way.

[compiler] Move serialized object array to module, instead of class

---

hail/python/hail/ggplot/geoms.py

I do not fully understand why, but I was getting errors about df.columns not accepting string indexes:
```
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
I think `df.columns` is not intended to let us get the Series for a column from the DataFrame. I think we are supposed to use `df` directly for this purpose, which is what I do here.
I also noticed an unfortunate issue where `''` is false-y so it is overlooked by the `or` in favor of the default value. It would be nice to have some kind of lazy `None` coalescing operator in Python :/.

[ggplot] avoid weird dataframe error

---

hail/python/test/hail/methods/test_qc.py
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala

Fix TableAggregate tree aggregation on a table with 0 partitions, by making the last layer of aggregation initialize the agg states using the initializers, rather than the head of the results array, just as we do in non-tree aggregate.

[compiler] fix tree aggregation on empty table

---

batch/batch/driver/instance_collection/pool.py
batch/sql/estimated-current.sql
batch/sql/faster-regions-pool-scheduler.sql
build.yaml

I tried benchmarking this change and didn't see much of a difference in timings in my contrived high throughput example. However, I do think this index is better because I believe MySQL does the order by first and then filters records.
@danking Can you take a look at this and make sure the index is actually an improvement.
The speed of the query is linearly related to the number of records in the limit. So I think if we need to get the query speed back to under 10ms then we revert back to pulling a smaller number of records rather than 1000. I think 300 is fine and gets us to 10ms. I just didn't want to pull 10 jobs and then none of them are schedulable but the 100th one is. We can revisit this if the scheduler becomes the bottleneck after your changes to the gateway.

[batch] Add indices for faster pool scheduling

---

auth/auth/auth.py
auth/deployment.yaml
batch/batch/front_end/front_end.py
batch/deployment.yaml
gateway/gateway.nginx.conf
grafana/nginx.conf
prometheus/nginx.conf

Moves multi-pod deployments over to using Headless Services, which enables client-side load-balancing to the underlying pods. See #12095 for more context.
The reason I put this in its own PR is that Kubernetes won't let me apply the `clusterIP: None` changes to existing `Services`, and I must delete the `Service` resources first. I can manually delete and apply new headless services in a way that is compatible with what is currently on main and with just a few seconds of downtime, but I should do this manually just before this PR merges.

[k8s] Move to headless services and make pods listen on 443

---

batch/batch/front_end/front_end.py

Should help a bit to speed up the the create-fast and update-fast endpoints if the user doesn't have to wait on this request to the driver.

[batch] Send batch-driver push notification out of task of commit update

---

hail/python/hail/expr/blockmatrix_type.py
hail/python/hail/expr/matrix_type.py
hail/python/hail/expr/table_type.py
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/types/MatrixType.scala

This makes the keys we produce in serialized representation the same as the field names in the python objects.

[query] Update JSON serialized relational type names

---

gateway/gateway.nginx.conf
grafana/nginx.conf
prometheus/nginx.conf
prometheus/prometheus.yaml

After the change for headless services, for some reason nginx require the full in-cluster domain name for resolving services. It could have something to do with the explicit resolver directive, but this is all imminently getting replaced with envoy anyway so this is just a fix to get internal.hail.is and grafana/prometheus working again.

[nginx] Fully specify in-cluster domain

---

hail/src/main/resources/log4j.properties
hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/services/JSONLogLayout.scala

It was the change to `HailContext.scala` that finally affected the output for QoB jobs, but I tried to stay consistent.

[query] Add milliseconds to log output

---

hail/python/hail/expr/blockmatrix_type.py
hail/python/hail/expr/matrix_type.py
hail/python/hail/expr/table_type.py

Add `__slots__` to prevent assignment bugs and a `_to_json` method for `ttable`, `tmatrix`, and `tblockmatrix`.

[query] More utilities for relational types

---

hail/python/hail/vds/combiner/variant_dataset_combiner.py

I've found that these days, 10k gvcfs merging at one time is generally too many.

[vds combiner] reduce default batch size

---

Makefile
build.yaml

I'm guessing that these steps are just here for historical reasons. Notebook was already getting checked in `check_services` so I just had to add `check_monitoring`.

[ci] Consolidate check services steps

---

hail/python/hail/ggplot/geoms.py
hail/python/hail/ggplot/ggplot.py

I love simpler solutions that leverage mutation, but in this case, `ggplot.py` and `geom.py` are circularly dependent if we want to use `GGPlot` in `geom.py`. I return a Boolean indicating if this geom makes the plot static. I do not love it because there is little indication of what that return value means, but I do not see another simple solution.

[ggplot] avoid circularity in types

---

hail/python/hail/ggplot/ggplot.py
hail/python/test/hail/ggplot/test_ggplot.py

Currently, `ggplot` expects a `Table` to be passed in as its data, and errors if passed a `MatrixTable`. With this change, the following code:
```python
mt = hl.utils.range_matrix_table(10, 10)
mt = mt.annotate_entries(entry_idx = mt.row_idx + mt.col_idx)
mt.show()
```
Which produces a `MatrixTable` that looks like this:
```
+---------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+
| row_idx | 0.entry_idx | 1.entry_idx | 2.entry_idx | 3.entry_idx | 4.entry_idx | 5.entry_idx | 6.entry_idx | 7.entry_idx |
+---------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+
|   int32 |       int32 |       int32 |       int32 |       int32 |       int32 | …
```

[query/ggplot] add support for MatrixTables

---

batch/batch/cloud/gcp/worker/worker_api.py
batch/batch/worker/worker.py
hail/python/test/hailtop/batch/test_batch.py

CHANGELOG: `Job.cloudfuse` now supports requester-pays buckets in GCP. The billing project specified in `hb.Batch(requester_pays_project=…)` is used to bill against.

[batch] Enable use of requester-pays buckets with gcsfuse

---

batch/batch/cloud/gcp/driver/create_instance.py
batch/batch/driver/main.py
memory/memory/memory.py

FYI @danking 
We needed to reduce logging output again. The memory service was printing logs for every request so I got rid of that. We were missing a new endpoint in the batch driver that didn't need to be logged. Finally, a lot of logs looked like syslog from the worker so I made sure to turn off the syslog Fluentd logging as the first thing we do on the worker. Not sure if it will help, but worth a try.

[memory,batch] Reduce logging output

---

batch/sql/add-batch-state-index.sql
batch/sql/estimated-current.sql
build.yaml

Should improve queries like [this one](https://console.cloud.google.com/sql/instances/db-jcaq4/insights;database=batch;duration=PT1H;trace=2a8c32c1dc3084ef49937289a31cffb5;span=16a6210f0941d4dd;norm_query_id=SELECT%20%60jobs%60%20.%20*%20,%20%60batches%60%20.%20%60format_version%60%20,%20%60batches%60%20.%20%60userdata%60%20,%20%60batches%60%20.%20%60user%60%20,%20%60attempts%60%20.%20%60instance_name%60%20FROM%20%60batches%60%20INNER%20JOIN%20%60jobs%60%20ON%20%60batches%60%20.%20%60id%60%20%3D%20%60jobs%60%20.%20%60batch_id%60%20LEFT%20JOIN%20%60attempts%60%20ON%20%60jobs%60%20.%20%60batch_id%60%20%3D%20%60attempts%60%20.%20%60batch_id%60%20AND%20%60jobs%60%20.%20%60job_id%60%20%3D%20%60attempts%60%20.%20%60job_id%60%20LEFT%20JOIN%20%60instances%60%20ON%20%60attempts%60%20.%20%60instance …

[batch] Add index on batches.state

---

hail/python/hailtop/utils/utils.py
hail/src/main/scala/is/hail/services/package.scala

Envoy uses [429](https://http.cat/429) for rate-limiting whereas nginx uses [503](https://http.cat/503). Looks like I'd only added it to Python and not Scala

[qob] Add 429 to retryable status codes

---

hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala

CHANGELOG: Fixed a bug that turned off tree aggregation for aggregation and scans
The alligator eats the bigger number

[query] Fix bug that turned off tree aggregation for scans and aggs

---

hail/python/hail/ir/matrix_reader.py
hail/python/hail/methods/impex.py
hail/python/test/hail/methods/test_impex.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/GenericLines.scala
hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
hail/src/test/scala/is/hail/TestUtils.scala

This does, what I believe to be the minimum necessary to get Tabix reading working in a standard VCF reader.
* Add GenericLines readTabix
* Harmonize import_gvcfs arguments and MatrixVCFReader parameters, as such, it is now possible to directly override the sample ids.
* Remove the undocumented (and until this change, dead) _partitions argument to import_vcf

[query] Finally get tabix vcf reading working

---

batch/test/test_batch.py
ci/ci/ci.py
ci/ci/envoy.py

- Using the full domain name instead of the shorthand `<service>.<namespace>` isn't strictly necessary but just made me nervous and I opted for the full unambiguous domain for in-cluster services (what if we had a namespace named `com`?? I feel like that would break some things)
- I got the configuration wrong on how to tell envoy *not* to worry about certs of internal namespaces (I'd recommend using the `split` view for the diff because otherwise it's pretty hard to read)
- For internal namespaces, using the `prefix` parameter for matching a route allowed `/foo/batch` to match a route like `/foo/batch-driver` which is obviously not great. the `path_separated_prefix` parameter actually does what we want
- Fixed the batch tests not to look at the HTTP 1.1 reason phrase and instead look at …

Fixes for envoy

---

batch/batch/worker/worker.py
hail/python/hailtop/aiotools/__init__.py
hail/python/hailtop/aiotools/tasks.py

This should fix the issue where we were trying to use a nonexistent GoogleAsyncFS when a worker is killed in the UI. I tested this in my namespace.

[batch] Kill any remaining jobs on worker shutdown

---

auth/auth/driver/driver.py
batch/test/test_accounts.py
build.yaml

for error responses coming from our services.
I think I got all occurrences of this by searching for `e.message` across the codebase. The only instances I see left of this are error-handling withing `front_end.py` (which isn't a problem because this is an issue of the reason phrase not making it between server -> client) and exceptions from aiodocker which is not within our control.

[httpx] Replace inspection of e.message with e.body 

---

ci/ci/envoy.py
ci/ci/github.py

- CI needs to account not only for the services that it is deploying but the services that the test-ci might later deploy into that same namespace
- I had earlier applied batch-driver's rate limit to everything and soon found that it is a bit too restrictive w.r.t. many simultaneous client submissions to the batch front end. With nginx we just didn't have rate limits on anything else, which seems less good than setting high rate limits. I'll admit that 200 was incredibly arbitrary (let's call it optimistic) and I'm happy to take more precise suggestions.

[envoy] Set higher rate limits for most services and add test_ci services

---

batch/test/test_batch.py

This test could run forever if batch is temporarily down between starting the job and the job completing. I'm not entirely sure what to do in this scenario, failing doesn't seem too bad because we weren't actually able to verify the test, but it seems better than potentially having the job hang.

[batch] Dont allow log test to possibly run forever

---

hail/python/hail/__init__.py

As of [nest_asyncio 1.5.2](https://github.com/erdewit/nest_asyncio/commit/1856573ac86954d15b0f617c97c02844bcbc7ea4), we can initialize nest_asyncio inside running loops (e.g. Jupyter). If nest_asyncio is initialized after even one task is created, [users receive inscrutable errors](https://github.com/erdewit/nest_asyncio/issues/22\#issuecomment-874710264). This error happened during the QoB workshop I ran. This change takes advantage of nest_asyncio 1.5.2 to initialize nest_asyncio before *everything*, thus ensuring it can completely patch the event loop.
You can reproduce the error yourself by running `python3 -c "import hail as hl; hl.init(billing_project=\"not-a-real-billing-project\")"` repeatedly in a terminal. I encounter the error ~50% of the time. With this change, I did not see …

[qob] fix use of nest_asycnio

---

batch/batch/worker/worker.py

Docker jobs were cleaning up after themselves by including the entire directory for that job which removed the old container files. This PR makes it so `Container.remove()` removes the directory for the container.
Before we merge this, I want to check the logs for this PR and make sure there aren't error messages that don't show up in tests.

[batch] Fix JVM file exists error

---

auth/auth/auth.py

If we cannot authenticate the user, we should send them to a publicly accessible page where the error message can be presented.

[auth] avoid redirect loop on failed login

---

build.yaml
docker/hailgenetics/hail/Dockerfile
hail/Dockerfile.hail-pip-installed
hail/Dockerfile.hail-pip-installed-python37
hail/Dockerfile.hail-pip-installed-python38

This installs our fully-pinned requirements deep in the docker image and then installs the hail wheel without dependencies on top. This will be a lot more consistent (and docker cache friendly) than the current approach, which will install all dependencies with the wheel and possibly upgrade some of them.
Also did the same to the hail-pip-installed images used for testing.

[hailgenetics] Use fully-pinned requirements in hailgenetics/hail

---

hail/python/hail/methods/pca.py
hail/python/test/hail/experimental/test_experimental.py
hail/python/test/hail/matrixtable/test_matrix_table.py
hail/python/test/hail/methods/test_pca.py

CHANGELOG: pca and hwe_normalized_pca now supported in Query-on-Batch

[query] use native pca on service, better default params

---

batch/batch/driver/job.py
batch/batch/driver/main.py
batch/batch/worker/worker.py

Tested in a dev deploy'd load test that # of add_attempt_resources queries == # of jobs instead of double as you can currently observe in default.

[batch] Avoid calling add_attempt_resources in MJC if MJS succeeded

---

batch/batch/front_end/validate.py
batch/batch/worker/worker.py
hail/python/hailtop/batch/backend.py
hail/python/hailtop/batch/job.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py
hail/python/test/hailtop/batch/test_batch.py

CHANGE_LOG: 
- Added ``Job.always_copy_output`` when using the ``ServiceBackend``. The default behavior is `False` which
is a breaking change from the previous behavior to always copy output files irregardless of the job's
completion state.
Thoughts on introducing this "breaking" change? I think it's okay and we will announce the change on Zulip. I think the benefits of getting rid of this not so intuitive behavior where we copy files despite the main container's completion state outweighs possibly breaking someone's pipeline that relied on files being there when the copy step could have failed as well.

[batch] Add always_copy_output option

---

hail/python/hailtop/aiocloud/aioazure/session.py

Azure seems to have pervasively higher latency than GCP. This should reduce the amount of warning logs we receive.

[batch][azure] increase timeout for Azure

---

build.yaml

This didn't fail the PR because this step does not have the test scope.

[ci] Use correct hailgenetics_hailtop image step in deploy

---

batch/test/test_accounts.py
hail/python/hailtop/batch_client/aioclient.py

`_delete` retries transient errors. The `.../delete` endpoints return 404 for batches that do not exist, which, I suppose, is reasonable. On the client-side, we need to ignore 404s to ensure idempotency.

[batch] make Batch.delete idempotent

---

hail/python/hail/backend/backend.py
hail/python/hail/backend/py4j_backend.py
hail/python/hail/backend/service_backend.py
hail/python/hail/utils/java.py
hail/python/hailtop/yamlx.py
hail/python/test/hailtop/test_yamlx.py

The root issue here was that sometimes exc.args[0] was a string and sometimes it was a dict. When it was a string the `in` condition worked fine. When it was a dict, it was looking at the keys of the dict and not finding the error message (which is buried under a few layers).
The code was unnecessarily complex. I reworked the yaml printer to be simpler and work for any multiline string. I removed the regular expression that was used to discover the worker batch when the worker jobs were in a different batch from the driver jobs. I remove all specialized debugging information in favor of the general `debug_info` methods on `Batch` and `ServiceBackend`. I also have two clear error cases: if the driver does not write its output file, then something went horribly wrong. We dump all the debug …

[query][qob] simplify QoB error handling and fix flaky test

---

hail/Makefile

I renamed HAIL_DIR to HAIL_HAIL_DIR to better convey to which directory it refers.

[query] use python:3.7 for pip-compile in hail

---

hail/python/hail/backend/service_backend.py
hail/python/hailtop/utils/utils.py

KeyboardInterrupt inherits from BaseException and not Exception so we couldn't kill waiting on batches etc. in the terminal. I decided to not catch BaseException and instead add the separate handler case because I wasn't sure we want to actually catch BaseException rather than Exception.

[hailtop.utils] Add exception handling for KeyboardInterrupt

---

hail/python/hail/backend/service_backend.py

Now the worker job names look like this instead of the worker jobs also having the batch name as the prefix:

[qob] Dont include the batch name in the worker name anymore

---

batch/test/test_time_limited_max_size_cache.py
build.yaml
docker/Dockerfile.base
docker/Dockerfile.service-base
hail/Dockerfile.hail-build
hail/Dockerfile.hail-run
hail/Dockerfile.hail-run-tests

Wonder what your thoughts are on this. I think that we have too deep an image hierarchy and that it's only stalling our time-to-test in CI. I propose here getting rid of the run-tests image and just putting plink in the hail-run image. I also remove the dependency on service-base and just install hailtop in the hail-run image -- I don't think anything hail/hail should depend on services code. This change actually revealed an accidental dependency where there was a gear (services) test in the hail/python tests. I moved that over to the batch suite as batch is the primary user of that class and we don't have a gear suite atm.
Ultimately, I think we should have a pretty flat docker image hierarchy. Each of our Dockerfiles does a decent job of following the docker mantra of dependencies …

[test] hail-run image should depend on base not service base

---

hail/python/hail/ggplot/facets.py
hail/python/hail/ggplot/geoms.py
hail/python/hail/ggplot/ggplot.py
hail/python/hail/ggplot/stats.py
hail/python/hail/ggplot/utils.py

This change brings the `facet_wrap` interface more in line with [the `ggplot2` implementation](https://ggplot2-book.org/facet.html#facet-wrap) by defaulting to show axes (with tick marks) for all facets, as well as providing `scales`, `nrow` and `ncol` arguments that the user can use to specify whether the scales should be the same across facets and how many rows or columns to use.
It also updates the faceting code to avoid duplicating legend entries when [grouped legends](https://github.com/hail-is/hail/pull/12254) are used, and to disable interactivity accordingly.
With this update, running this code:
```python
from hail.ggplot import aes, facet_wrap, geom_point, ggplot, vars
ht = ht.annotate(squared=ht.idx ** 2)
ht = …
```

[query/ggplot] Updates faceting to respect legend grouping

---

hail/python/hail/backend/service_backend.py

Not sure this is the right fix, but I believe we can't update a batch once it's been cancelled still.

[qob] Invalidate batch cache on error

---

hail/Makefile
hail/python/test/hail/methods/test_impex.py

The environment variables should be affecting `pytest`, not `cd`.
`test_import_bed` just needs to use an `open` that can speak `gs://`.

[query] Fix pytest-qob and fix test_import_bed

---

hail/python/dev/pinned-requirements.txt
hail/python/dev/requirements.txt
hail/python/hailtop/pinned-requirements.txt

The FS tests were accidentally disabled because pytest-asyncio was never included in dev/requirements.txt (as it should have been). As a result, all the `async def` tests were (silently) ignored by pytest.

[query] enable fs tests

---

hail/src/main/scala/is/hail/expr/ir/LiftRelationalValues.scala

Not a long-term solution, but we do hacky dedups like this elsewhere in the compiler and it can clean up simple duplicated IRs. Not chained duplicated IRs, as you've noticed.

[query] deduplicate identical LiftMeOut nodes

---

hail/python/hailtop/aiocloud/aioazure/fs.py
hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py
hail/python/hailtop/aiotools/utils.py

If we hit an exception and exit the iterator early, then we are no longer iterating. We need to record that fact so that we can retry transient errors.

[hailtop] safely use chunks

---

query/.clang-tidy

From local timing results using `clang-tidy -enable-check-profile`, I'm pretty sure `misc-confusable-identifiers` is quadratic. It was taking about a quarter of the time on `hail-opt`

[native compiler] disable expensive clang-tidy check

---

batch/batch/driver/instance_collection/base.py

The driver will regularly update the VM state from the azure API so including the update time can block the driver from deleting runaway instances, which can subsequently halt the system.

[batch] Dont consider update time when deleting broken instances

---

hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala

In order to track partition bounds and distinctness, we report the first and last seen keys when writing (matrix) tables. Previously we were copying the last seen key into the partition region. This is incorrect as the partition region has a lifetime of the entire partition and cannot be cleared, leaking memory. Fix this by giving the last seen key its own region that can be cleared before a new last seen key is saved.
Tested manually.
See the following zulip thread for initial report.
https://hail.zulipchat.com/#narrow/stream/123011-Hail-Query-Dev/topic/memory.20usage.20by.20range.20-.3E.20write/near/316404073

[query] Fix memory leak of relational keys in native writers

---

hail/python/hail/ir/table_ir.py
hail/python/test/hail/test_randomness.py

CHANGELOG: Fix a bug that prevented exploding on a field of a Table whose value is a random value.

[query] fix bug that prevents exploding a random field

---

hail/python/hail/matrixtable.py
hail/python/hail/table.py
hail/python/test/hail/expr/test_show.py

CHANGELOG: Fix bug where matrix tables with duplicate col keys do not show properly. Also fix bug where tables and matrix tables with HTML unsafe column headers are rendered wrong in Jupyter.

[query] fix show when col keys are not unique & escape table headers

---

build.yaml
website/deployment.yaml

I noticed in #12526 that you added `scope` to the website Makefile but I don't think it's needed as using `deploy` is a little cleaner.

[website] Clean up use of scope instead of deploy

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/test/hail/expr/test_expr.py

Fixes the col_key.show() issue Dan unearthed.

[query] Fix _to_relational for col_key

---

hail/python/hail/ggplot/geoms.py
hail/python/hail/ggplot/ggplot.py

CHANGELOG: `hail.ggplot`s that have more than one legend group or facet are now interactive. If such a plot has enough legend entries that the legend would be taller than the plot, the legend will now be scrollable. Legend entries for such plots can be clicked to show/hide traces on the plot, but this does not work and is a known issue that will only be addressed if `hail.ggplot` is migrated off of plotly.
Currently, scatter plots with more than one legend group and plots with multiple facets are static. This is because both these types of plot leverage empty traces in order to produce legends that match R's ggplot2's legends more closely than the ones plotly generates by default. As a result, the interactive elements of the legends for these types of plot, specifically the ability to …

[query/ggplot] re-enables interactivity for plots that use dummy traces

---

batch/batch/worker/worker.py

Docker just always returns 500s for images that don't exist and has a slightly different error message for each thing that could go wrong (project / repository / image / tag don't exist) and that message varies across registries.

[batch] Treat any 500 from pulling with unknown in the message as a 404

---

hail/build.gradle
hail/python/hail/ir/matrix_writer.py
hail/python/hail/methods/impex.py
hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/SpecializedArrayBuilders.scala
hail/src/main/scala/is/hail/io/bgen/BgenRDD.scala
hail/src/main/scala/is/hail/io/bgen/BgenRDDPartitions.scala
hail/src/main/scala/is/hail/io/bgen/IndexBgen.scala
hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala
hail/src/main/scala/is/hail/io/gen/ExportBGEN.scala
hail/src/main/scala/is/hail/utils/CompressionUtils.scala
hail/src/main/scala/is/hail/utils/package.scala

CHANGELOG: `hl.import_bgen` and `hl.export_bgen` now support compression with Zstd.

[query] Support zstd compression in BGEN files

---

batch/batch/front_end/front_end.py
batch/batch/front_end/templates/batch.html

This is a feature Bob asked for to be able to search by job id in the UI. I added new functionality where if the "q" query string changes, we reset the last_job_id. Otherwise, something like "job_id=100" followed by "job_id=5" wouldn't work.

[batch] Add job_id to UI search

---

hail/python/hail/methods/impex.py
hail/python/hail/vds/combiner/variant_dataset_combiner.py
hail/python/hail/vds/variant_dataset.py
hail/python/test/hail/vds/test_combiner.py

The dataset type should not change with each stage in the combiner, so
we are able to assert the type of the combiner datasets at each stage
and prevent round trips to the backend during reading. As such, we can
remove a call to read_multiple_matrix_tables which requires spark.
This sets up more changes so that we can switch on the backend and run
the combiner in query on batch.

[vds combiner] Save dataset type in combiner state 

---

batch/batch/driver/main.py
batch/batch/front_end/front_end.py
batch/deployment.yaml

For terra I currently have the front-end and driver running in the same pod, so I can't have the front-end listening on port 443 since it's in use by something else in the pod. Seemed like a reasonable enough change on its own. There will be an entirely separate `deployment.yaml` for terra so better to expose small options like these there than in the python code.

[batch] Specify web server port through env variable

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/issue_template.md

I discovered [issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) the other day and thought it might be helpful for directing users to the discussion forum / Zulip chatroom.
With this configuration, when someone opens an issue, they'll be presented with some options:
If they choose to report a bug, they'll be presented with a form prompting for Hail version and log output.

Replace issue template with form

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/test_indices_aggregations.py
hail/python/test/hail/test_ir.py

CHANGELOG: Improve error message when combining incompatibly indexed fields in certain operations including array indexing.
See test cases for straightforward examples. In main, none of the test code triggers errors. You have to execute the table to actually trigger an error in IR serialization which will reference `"sa"` which is totally meaningless to the user (let alone many Hail engineers).

[query] add a small & incomplete test suite for good index errors

---

ci/ci/build.py
ci/ci/github.py

Currently you can't do a dev deploy that only builds an image, because the `deployed_services` method breaks if there are no `deploy_*` steps in the config. This change allows a dev deploy to work with just steps that don't transitively depend on the create namespace step.

[ci] Dont require a deploy step for a dev deploy

---

hail/Makefile

depending on implementation, cat and tr will report broken pipes adding noise to the output of make.

[query] quiet makefile

---

batch/batch/cloud/azure/worker/disk.py
batch/batch/cloud/azure/worker/worker_api.py
batch/batch/cloud/gcp/worker/disk.py
batch/batch/cloud/gcp/worker/worker_api.py
batch/batch/driver/main.py
batch/batch/front_end/front_end.py
batch/batch/worker/disk.py
batch/batch/worker/worker.py
batch/batch/worker/worker_api.py
gear/gear/clients.py
hail/python/hailtop/aiocloud/aiogoogle/credentials.py

- Use the worker VMs credentials for the FS and compute client instead of requesting credentials from the batch driver
- This allows creating the FS before worker activation, meaning that same FS can be passed to JVMContainers, instead of needing to create a new LocalAsyncFS for JVM objects
- Thread the task_manager through more of worker.py so the worker can properly cancel all tasks on shutdown

[batch] Dont use Batch identity on workers

---

ci/ci/ci.py

It's just a string so `json.loads` fails on it. Not sure why I did that anyway.
This has been broken on CI for a bit now. CI still manages fine because it checks everything on an interval but the callback helps it respond immediately to when batches finish for a PR test or deploy.

[ci] Dont try to json.loads the namespace string

---

hail/python/test/hail/methods/test_statgen.py

Compare to a deploy job wherein the string "test_statgen.py" does not appear: https://ci.hail.is/batches/6942543/jobs/58 .

[query] re-enable the statgen tests

---

hail/python/hail/nd/nd.py
hail/python/test/hail/expr/test_ndarrays.py

1. ndarray methods now properly propagate indices or aggregations.
2. `hl.nd.qr` has some extra documentation about the properties of those matrices.
3. Examples are always first, parameters use our standard style, return values are only named when there are more than one of them.

[query] various nd array fixes

---

hail/python/hailtop/aiotools/fs/stream.py

It's not supported on macOS, despite the python documentation. This fix makes `make check-hail` pass for me on my laptop.

[fs] Only use posix_fadvise on linux

---

infra/gcp/main.tf

In azure the worker has the Contributor role which should give it all the CRUD permissions.

[batch] Batch worker gets object admin on batch bucket

---

hail/python/hail/fs/router_fs.py
hail/python/hail/fs/stat_result.py
hail/python/hailtop/aiocloud/aioaws/fs.py
hail/python/hailtop/aiocloud/aioazure/fs.py
hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py
hail/python/hailtop/aiotools/fs/fs.py
hail/python/hailtop/aiotools/local_fs.py
hail/python/hailtop/timex.py
hail/python/test/hailtop/inter_cloud/test_fs.py
hail/python/test/hailtop/test_timex.py

Fixes #12540.
CHANGELOG: When using Query-on-Batch, hl.hadoop* methods now properly support creation and modification time.
Creation time is supported by modern Linuxes but only through a new statx API which is not exposed by the Python standard library. There is a 0.1 version library from 2021 which exposes statx including the "birth time". I chose to raise an exception for now.
Each cloud does support a "modification time" but it generally refers to changes to metadata or is just the creation time:
- https://cloud.google.com/storage/docs/json_api/v1/objects#resource (see updated)
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_ResponseSyntax ("Last-Modified", is always creation time)
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html# …

[query][qob][hailtop/fs] Expose modification and creation time.
