hail-is/hail

- hail/src/main/scala/is/hail/expr/ir/BinarySearch.scala
- hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala
- hail/src/main/scala/is/hail/expr/ir/orderings/IntervalOrdering.scala
- hail/src/main/scala/is/hail/io/index/StagedIndexReader.scala
- hail/src/main/scala/is/hail/types/physical/PCanonicalInterval.scala
- hail/src/main/scala/is/hail/types/physical/stypes/concrete/SIntervalPointer.scala
- hail/src/main/scala/is/hail/types/physical/stypes/concrete/SStackInterval.scala
- hail/src/main/scala/is/hail/types/physical/stypes/concrete/SStackStruct.scala
- hail/src/main/scala/is/hail/types/physical/stypes/concrete/SUnreachable.scala
- hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SBaseStruct.scala
- hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SInterval.scala
~Stacked on #12376~
Reworks the staged index reader query algorithm. Before, `queryInterval` did three traversals from root to leaf: one each for the start and end of the interval, and one to find the first record. Now it always does a single traversal, visiting one or two nodes at each level (two if the paths for the start and end keys diverge), and doing a single binary search at each visited node.
This is probably not a significant performance improvement when doing a single query per partition, but could be beneficial when using the new `query_table` per row.
> [query] improved index search algorithm

- hail/python/hail/methods/impex.py
- hail/python/test/hail/methods/test_impex.py
- hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
could use a second look here -- am I crazy? 
If GP is missing from the MT and no expression is passed, there's no GP in the MT passed into the writer.
And if there's no GP in the writer, we export a file worth of nulls.
https://github.com/hail-is/hail/blob/eee0924c119d8aa2ba1cdaf4f30a4f2be4ba347f/hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala#L1123-L1149
> [query] Stop silently exporting null bgens if no GP field exists

- auth/deployment.yaml
- ci/deployment.yaml
Starving auth of the cycles to complete authentication requests causes cascading failures in the system.
> [k8s] Give auth and CI more CPU shares

- hail/python/dev/pinned-requirements.txt
- hail/python/hailtop/pinned-requirements.txt
- hail/python/pinned-requirements.txt
> Revert "Bump cryptography from 38.0.4 to 39.0.1 in /hail/python"

- hail/python/hail/ir/blockmatrix_ir.py
- hail/python/hail/methods/relatedness/identity_by_descent.py
- hail/python/test/hail/methods/relatedness/test_identity_by_descent.py
Patrick -- can you give this a careful look over? Once we're happy with it, I'll redo the benchmarking as a last sanity check.
> [query] IBD implemented in terms of block matrices

- hail/python/hailtop/requirements.txt
`>=` is not compatible with wildcards:
```
cd build/deploy; rm -rf build; python3 setup.py -q sdist bdist_wheel
/usr/local/lib/python3.7/dist-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
SetuptoolsDeprecationWarning,
error in hail setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
google-cloud-storage>=1.25.*
~~~~~~^
make: *** [Makefile:248: build/deploy/dist/hail-0.2.109-py3-none-any.whl] Error 1
```
I'm not sure why this hasn't shown up before, but we couldn't deploy 0.2.109 without this fix.
> [batch] Fix google-cloud-storage version requirement

- batch/batch/worker/worker.py
This is needed for Siwei's recursive pipeline to work.
> [batch] Add environment variable for batch id in worker

- hail/python/hailtop/batch/batch.py
CHANGELOG: :class:`.PythonJob` now correctly uses the default region when a specific region for the job is not given.
I noticed this was missing when I was looking at Siwei's pipeline.
> [batch] Use default regions in python jobs

- hail/Makefile
`gsutil` is one of the most user hostile tools I have ever used. Here are some examples of why. I think what I now have committed is the only way to achieve the behavior we want without assuming anything about which objects are present at the target.
```
$ gsutil -m cp -r baz gs://danking/baz/
$ gsutil ls gs://danking/baz/
gs://danking/baz/baz/
```
```
$ gsutil rm -rf gs://danking/baz
$ gsutil -m cp -r baz/ gs://danking/baz/
$ gsutil ls gs://danking/baz/
gs://danking/baz/baz/
```
```
$ gsutil rm -rf gs://danking/baz
$ gsutil -m cp -r baz gs://danking/baz
$ gsutil ls gs://danking/baz/
gs://danking/baz/1
gs://danking/baz/2
```
```
$ gsutil rm -rf gs://danking/baz
$ touch foo
$ gsutil cp foo gs://danking/baz/foo
$ gsutil -m cp -r baz gs://danking/baz
$ gsutil ls gs://danking/baz …
```
> [query] fix gsutil cp invocation

- batch/batch/driver/billing_manager.py
I left out the cloud specific check and just make it so we don't have this problem again on any cloud.
> [batch] Mitigate too many resources with same prices

- hail/src/main/scala/is/hail/backend/HailTaskContext.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/io/index/StagedIndexReader.scala
- hail/src/main/scala/is/hail/utils/Cache.scala
Add finalizers to HailTaskContext to clean up open indices.
> [query] Make caching in PartitionNativeIntervalReader more aggressive

- hail/python/hail/expr/types.py
- hail/python/hail/ir/__init__.py
- hail/python/hail/ir/table_ir.py
- hail/python/hail/methods/statgen.py
- hail/python/hail/utils/__init__.py
- hail/python/hail/utils/genomic_range_table.py
- hail/python/test/hail/expr/test_types.py
- hail/python/test/hail/utils/test_genomic_range_table.py
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/expr/ir/lowering/CanLowerEfficiently.scala
- hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
- hail/src/main/scala/is/hail/types/virtual/TLocus.scala
CHANGELOG: In Query on Batch, `hl.balding_nichols_model` is slightly faster. Also added `hl.utils.genomic_range_table` to quickly create a table keyed by locus.
It has grated on me for a while that `hl.balding_nichols_models` requires a whole pass to verify it is sorted even though it is plainly so. This change introduces the necessary infrastructure to convince Hail of that fact.
> [query] add `hl.utils.genomic_range_table`

- batch/Dockerfile.worker
- build.yaml
- hail/Makefile
- hail/build.gradle
- hail/python/dev/pinned-requirements.txt
- hail/python/hail/backend/local_backend.py
- hail/python/hail/backend/spark_backend.py
- hail/python/hailtop/aiotools/fs/fs.py
- hail/python/hailtop/batch/docker.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/hailctl/auth/create_user.py
- hail/python/hailtop/hailctl/auth/delete_user.py
- hail/python/hailtop/hailctl/dataproc/start.py
- hail/python/hailtop/hailctl/describe.py
- hail/python/hailtop/pinned-requirements.txt
- hail/python/hailtop/timex.py
- hail/python/pinned-requirements.txt
- hail/python/requirements.txt
CHANGELOG: Query on Spark now officially supports Spark 3.3.0 and Dataproc 2.1.x
Tested on dataproc via `make -C hail test-dataproc-37`. Updating the dependencies introduced a few new linting checks that I fixed here. Updating pyspark necessitated a couple of changes, namely a different py4j jar and they removed `SparkSession._wrapped` (but maybe we didn't need that anyway? not sure). Most importantly, the newer spark version brings with it a newer jackson version which is sufficient for the azure-storage-blob dependency, meaning we don't need to build against two different spark versions for spark and batch.
> [query] Upgrade spark to 3.3.0 and dataproc to 2.1

- hail/python/hail/docs/methods/genetics.rst
- hail/python/hail/methods/__init__.py
- hail/python/hail/methods/statgen.py
- hail/python/test/hail/methods/test_skat.py
CHANGELOG: `hl.skat(..., logistic=True)` now supported in the Batch backend.
> [query] lower logistic SKAT

- hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
Not all IOExceptions have a cause.
> [query] fix NPE introduced in #12555

- batch/batch/file_store.py
- batch/batch/front_end/front_end.py
- batch/batch/worker/worker.py
- batch/test/test_batch.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/batch_client/client.py
- hail/python/hailtop/hailctl/batch/log.py
The crux of this PR is the 9 line change in `file_store.py` -- we shouldn't decode job logs to `str` before uploading because we can't trust jobs to output only valid UTF-8 to stdout. The FS can take bytes anyway so it is an unnecessary conversion. The rest of the complexity of this PR is figuring out how to communicate those logs over the Batch API in a backwards-compatible and straight-forward way. What makes that tricky is that when we say "job log" in the code we mostly talk about a dictionary or JSON object of container to log string. Valid JSON must be UTF-8, so JSON starts to make less and less sense for sending log files. Log files are easy to send though if we just want one, so I added an endpoint to request the log for a specific container in a job and we can easily fulfill that …
> [batch] Support job logs that are not UTF-8 compatible

- hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
- hail/src/main/scala/is/hail/backend/service/Worker.scala
- hail/src/main/scala/is/hail/io/fs/FS.scala
- hail/src/main/scala/is/hail/io/fs/ServiceCacheableFS.scala
- hail/src/main/scala/is/hail/io/fs/package.scala
- hail/src/main/scala/is/hail/services/memory_client/MemoryClient.scala
Currently, the memory client buffers the entire output in memory which is likely to cause OOMs. For reasons that are not entirely clear to me, sometimes these OOMs get muffled by our system and instead lead to non-termination. I vaguely remember this happening before with `using`. I suspect there is something somewhat subtle wrong with that method, but I am not certain.
Anyway, there are four big changes here:
1. Do not buffer the entire request body in memory when writing to memory.
2. Because of (1) we have to pull retry behavior all the way up to the top-level where we know how to recreate the body.
3. Because of (2) it is easier to provide a `write(url)(writerFunction)` style API, which I do here.
4. Again, because of (2), and because I want to preserve the file-object-like interface, …
> [query] improve the memory client

- build.yaml
The local backend tests only use 1 core, so this dedicates the same resources for much more parallelism.
> [ci] Run the local backend tests much more in parallel

- hail/python/hail/backend/backend.py
- hail/python/hail/backend/local_backend.py
- hail/python/hail/backend/service_backend.py
- hail/python/hail/backend/spark_backend.py
- hail/python/hailtop/config/user_config.py
- hail/python/test/hail/test_context.py
- hail/src/main/scala/is/hail/HailFeatureFlags.scala
Flags now use the same user configuration machinery we use for Batch and QoB. I am not certain this is the right choice. Feedback very welcome. The configuration_of function lets us uniformly treat any configuration by checking, in order: explicit argument, envvar, config file, or a fallback.
I added a bit of code to allow us to support the envvars which do not conform to the new envvar scheme.
I also removed a few flags that are no longer used.
I kind of think these flags should actually be under a new section like "query_compiler" or something.
@tpoterba, thoughts?
> [query] rework flags and fix QoB flags

- batch/batch/worker/worker.py
- devbin/sync.py
- gear/gear/database.py
- hail/python/hailtop/aiotools/tasks.py
- hail/python/hailtop/utils/utils.py
The asyncio event loop only keeps weak references to tasks, so wherever we call `asyncio.create_task` we need to ensure that we keep a strong reference to its result. Specifically, `BackgroundTaskManager` needs to keep strong references not weak references to the tasks it creates. This is easy to do without accumulating garbage by using a done callback on the task to remove itself from the set. However, this felt iffy with the threadsafe futures, which were only used in sync.py anyway, so I pushed that functionality directly into sync.py and removed it from the `BackgroundTaskManager`.
To simplify the ownership story for tasks, this changes `BackgroundTaskManager` to *not* return the task and instead hold onto strong references. If a client wants a reference to the task it creates, it …
> [hailtop] Keep strong references to tasks

- batch/batch/worker/worker.py
Error messages from GCR and AR are different, and sometimes it looks like this from GCR:
```
"unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials
```
> [batch] Treat unauthorized in docker error message as permission denied

- docker/Dockerfile.base-with-spark-3-2
Missed this when deleting all the Spark 3.2 related stuff when upgrading to 3.3.0
> [ci] Remove unused Spark 3.2 base image

- hail/python/hail/plot/plots.py
- hail/python/test/hail/plot/test_plot.py
1. `hl.plot.cdf`, `hl.plot.histogram`: `values` is a method on `hl.Struct`s (because they are `Mapping`), use `["values"]` to get the `values` field of a struct.
2. `hl.plot.pdf`: Do not error if there are no compactions, just set error to zero.
3. *: Add return type annotations to improve IDE hints.
4. `hl.plot.joint_plot`: I think a bokeh upgrade completely broke this; the first argument is the grid of figures.
5. `hl.plot.qq`: Kill unnecessary persists with fire.
6. `hl.plot.visualize_missingness`: Informative error message when row key is not "windowable".
7. `hl.plot.visualize_missingness`: When row key is a one-field struct, use the one field instead of the struct as the windowable value.
> [query] fix `hl.plot.*` and add tests to ensure correctness

- hail/python/hailtop/batch/job.py
- hail/python/test/hailtop/batch/test_batch.py
CHANGELOG: `PythonJob.call` now immediately errors when supplied arguments are incompatible with the called function instead of erroring only when the job is run.
inspect.Signature allows you to inspect the signature of some function, and [inspect.Signature.bind](https://docs.python.org/3/library/inspect.html#inspect.Signature.binds) takes arguments to the function and maps those arguments to method parameters. If the invocation is invalid, i.e. would raise a TypeError when *actually* invoking the function with those arguments, this method raises a similar error. This can help a user immediately catch something like not passing the correct number of arguments to a PythonJob call without having to submit and run it.
> [batch] Error if PythonJob functions are called with incompatible signature

- batch/batch/resource_usage.py
Removes this error from the logs:
```
--
File "/usr/local/lib/python3.7/dist-packages/batch/resource_usage.py", line 220, in periodically_measure
await self.measure()
File "/usr/local/lib/python3.7/dist-packages/batch/resource_usage.py", line 187, in measure
memory_usage_bytes = self.memory_usage_bytes()
File "/usr/local/lib/python3.7/dist-packages/batch/resource_usage.py", line 126, in memory_usage_bytes
return int(f.read().rstrip())
OSError: [Errno 19] No such device
```
> [batch] Ignore device not found errors in resource usage code

- hail/python/hail/table.py
- hail/python/test/hail/table/test_table.py
This PR fixes #11738. Now users can specify arbitrary type conversation between Hail and Pandas dtypes via:
```
ht.to_pandas(types={"col1": "int32", "col2": np.float64, hl.tstring: "object"})
```
This maps `col1` and `col2` to `int32` and `np.float64`, respectively, and all `hl.tstring` fields to `object`.
One design question might be whether to have separate arguments for column name and Hail type specifications or not. Any thoughts? cc: @danking 
Also, I don't think the current type check would work for `np.float64`-like numpy dtype specifications...
> [query] Add to_pandas(types={}) argument to specify user-supplied pandas dtypes

- ci/create_database.py
This is part of a minor bug-fix for how CI tracks active namespaces in development environments. #12093 added a table in CI's database that tracks the namespaces that CI is currently aware exists and that it manages. Non-production CIs don't really use this table (dev CIs don't update gateway routing or anything), but it's useful in development to see that CI is properly updating its database tables as it would in prod. In #12093, the migration that adds the `active_namespaces` table explicitly adds entries for the `default` namespace. However, I'm now realizing that this is a mistake, because a CI in the `dgoldste` namespace shouldn't have an entry for `default`, it should instead have an entry for `dgoldste`. That migration should have been parametrized by the  namespace the migration …
> [db] Add namespace to migrations environment

- batch/batch/worker/worker.py
- hail/python/hailtop/utils/utils.py
This PR tries to address the error we saw last Friday on Azure where there was a stuck worker that could not pull ubuntu:20.04 from Dockerhub. The error message in the worker logs was
```
DockerError(500, 'Head \"https://haildev.azurecr.io/v2/ubuntu/manifests/20.04\": denied: retrieving permissions failed')
```
I looked at the system logs and the actual error message was this:
```
Mar 03 16:56:12 batch-worker-default-standard-nj0qy dockerd[4066]: time="2023-03-03T16:56:12.112691249Z" level=info msg="Attempting next endpoint for pull after error: Head \"https://haildev.azurecr.io/v2/ubuntu/manifests/20.04\": denied: retrieving permissions failed"
```
Higher up in the logs was:
```
Mar 03 16:54:50 batch-worker-default-standard-nj0qy dockerd[4066]: time="2023-03-03T16:54:50.520878176Z" …
```
> [batch] Mitigate possible corrupt containerd image cache

- build.yaml
- ci/sql/fix-default-namespace.py
Stacked on #12755, this shouldn't have an impact on production, but is just meant to replace `default` in test CI databases with the actual name of the namespace that the CI is in. Should mimic [the prior migration](https://github.com/hail-is/hail/blob/main/ci/sql/active-namespaces.sql) just parametrized by namespace.
> [ci] Fix default namespace record for dev namespaces

- hail/python/requirements.txt
CHANGELOG: Update parsimonious to a verison that supports Python 3.11.
Fixes #12759.
> [query] relax parsimonious pin

- hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
The old jgscm used a version incompatible with PEP 440. NB: it was the version in setup.py that was wrong, the tag was fine.
> [query] update jgscm in init_notebook

- batch/batch/driver/instance_collection/pool.py
- batch/batch/driver/main.py
- batch/batch/driver/templates/pool.html
- batch/batch/inst_coll_config.py
- batch/sql/config-pool-min-instances.sql
- batch/sql/estimated-current.sql
- build.yaml
I added the configuration option for the minimum number of workers that should be present at any time. I tested this in my namespace. I'd like you to double check the logic is correct for the number of workers needed as I derived it by working through examples:
```python3
n_live_instances = self.n_instances_by_state['pending'] + self.n_instances_by_state['active']
n_standing_instances_needed = max(0, self.min_instances - self.n_instances)
n_standing_instances_needed = min(
n_standing_instances_needed,
self.max_live_instances - n_live_instances,
self.max_instances - self.n_instances,
remaining_instances_per_autoscaler_loop,
300,
)
```
> [batch] Allow more than one standing worker

- build.yaml
- hail/python/hail/__init__.py
- hail/python/hail/backend/service_backend.py
- hail/python/hail/context.py
- hail/python/hail/docs/utils/index.rst
- hail/python/hail/utils/__init__.py
- hail/python/hail/utils/misc.py
- hail/python/test/hail/backend/test_service_backend.py
- hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
CHANGELOG: Added the regions parameter to `hl.init()` for specifying which regions Query on Batch jobs should run in.
> [qob] Add regions parameter

- hail/python/hailtop/batch/backend.py
- hail/python/hailtop/batch/batch.py
- hail/python/hailtop/batch/job.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/batch_client/client.py
- hail/python/test/hailtop/batch/test_batch.py
CHANGELOG: Added the ability to update an existing batch with additional jobs by calling `Batch.run()` more than once.
I wrote this quite awhile ago, so I don't remember if there were any issues as to why I didn't make a PR sooner or if I'm missing some complexity here.
> [hailtop.batch] Add ability to update a batch

- hail/python/test/hailtop/batch/test_batch.py
Different splits (`test_hailtop_batch_0`, `test_hailtop_batch_1`, …) can clobber each other's tmpdir.
> [batch] Unique remote tmpdir path for each split

- hail/python/hailtop/batch/backend.py
Looks like the `get_remote_tmpdir` function was made when the Query ServiceBackend needed this config and didn't want to copy code directly from the batch ServiceBackend. Howevr, the batch ServiceBackend was never changed to use the new functions so got left behind. Aside from deleting a lot of duplicate code, the only change is that now the batch ServiceBackend will pick up the following environment variables `HAIL_BATCH_REMOTE_TMPDIR` and `HAIL_BATCH_BILLING_PROJECT`
> [batch] Make ServiceBackend respect environment variable configuration

- hail/python/hail/expr/functions.py
- hail/python/hail/methods/statgen.py
- hail/python/test/hail/expr/test_ndarrays.py
- hail/python/test/hail/methods/test_statgen.py
cc @tpoterba 
My apologies. I made several changes to lowered logistic regression as well.
All the generalized linear model methods share the same fit result. I abstracted this into one datatype at the top of `statgen.py`: `numerical_regression_fit_dtype`.
---
You'll notice I moved the cases such that we check for convergence *before* checking if we are at the maximum iteration. It seemed to me that:
- `max_iter == 0` means do not even attempt to fit.
- `max_iter == 1` means take one gradient step, if you've converged, then return successfully, otherwise fail.
- etc. The `main` branch currently always fails if you set `max_iter == 1`, even if the first step lands on the true maximum likelihood fit.
I substantially refactored logistic regression. There were dead code paths (e.g. the …
> [query] lower poisson regression

- hail/python/test/hail/linalg/test_linalg.py
- hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
- hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
Using changePartitionerNoRepartition with a partitioner with a different
number of partitions cannot be correct and will result in dropped data.
Just construct the new partitioner (based on row index, so it will
comply with invariants) directly.
> [lowering] Fix MatrixBlockMatrixWriter lowering when some partitions are empty

- hail/python/test/hail/helpers.py
I sometimes iterate quickly with `pytest -k testname` from the `hail/python` directory. I cannot do that if the test directory is hard coded.
> [query] better local testing experience

- hail/python/hail/expr/expressions/typed_expressions.py
- hail/python/hail/expr/types.py
The compiler still catches this at runtime, but it is hard to understand because it lacks a meaningful stacktrace.
> [query] tndarray equality includes number of dimensions

- hail/python/test/hail/expr/test_ndarrays.py
- hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SNDArray.scala
CHANGELOG: Raise an error instead of silently returning bad results when using a negative index with an `hl.nd.array`.
In practice, I always saw this return a positive value very close to zero. We should fix this to just support Python-style indexing, but I wanted to fix ASAP given the severity.
> [query] fix read from undefined memory

- batch/test/test_batch.py
- batch/test/test_invariants.py
- ci/test/test_ci.py
- gear/gear/auth.py
- hail/python/hailtop/aiocloud/common/session.py
- hail/python/hailtop/auth/__init__.py
- hail/python/hailtop/auth/auth.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/hailctl/auth/login.py
- hail/python/hailtop/hailctl/auth/logout.py
- hail/python/hailtop/hailctl/curl.py
- hail/python/hailtop/hailctl/dev/deploy/cli.py
- memory/memory/client.py
- memory/test/test_memory.py
- monitoring/test/test_monitoring.py
- notebook/scale-test.py
My motivation here is that in Terra we aren't going to be using hail authentication tokens, rather an authentication from gcloud or az. So I want our batch client to be able to use a `CloudCredentials` just as easily as it uses the hail auth token that we store on the user's machine. So I introduce HailCredentials which subclasses CloudCredentials but the behavior is the same. It also lets us re-use some of the retry logic that we have baked into `aiocloud.common.Session`.
> [auth] Make HailCredentials for refreshable auth tokens

- hail/python/hail/expr/aggregators/__init__.py
- hail/python/hail/expr/aggregators/aggregators.py
- hail/python/hail/ir/register_aggregators.py
- hail/python/test/hail/expr/test_expr.py
- hail/src/main/scala/is/hail/expr/ir/AggOp.scala
- hail/src/main/scala/is/hail/expr/ir/Exists.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
- hail/src/main/scala/is/hail/expr/ir/agg/ReservoirSampleAggregator.scala
- hail/src/main/scala/is/hail/expr/ir/agg/StagedArrayBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
CHANGELOG: Fixed bug where Table/MT._calculate_new_partitions returned unbalanced intervals with whole-stage code generation runtime.
> [query] Add reservoir sample aggregator

- hail/python/hail/ir/renderer.py
- hail/python/test/hail/test_ir.py
The deleted assertion says that a node can't both be lifted to a let, and be the destination of lets being lifted from below. When I added it, I figured any lets being lifted from below should be able to lift all the way to the destination of this node, and I hadn't thought carefully through what would happen if that assumption weren't true.
The example that breaks that assumption is when some expression `x` is used as the top level of a branch of an if, or any other spot that prevents lets from being lifted any higher, while also being used >1 times elsewhere, and `x` also contains a repeated subexpression. The other uses of `x` will be lifted out somewhere above, so `x` gets marked as being lifted. The use in the if cannot be lifted, and moreover is the destination of the lifted …
> [compiler] fix overly strict CSE bug

- hail/Makefile
- hail/scripts/upload_qob_jar.sh
OK, three issues:
1. The TOKEN envvar needs to be defined.
2. If statement indentation a bit confusing.
3. Hail Batch in the default namespace rejects JAR URLs that are not under `$QUERY_STORAGE_URI/jars`, ergo we need to use QUERY_STORAGE_URI in the default namespace branch. The official JARs have a retention policy and are at the top level (rather than under a `/$(whoami)/`), so there is little risk of corrupting them.
> [query] fix Makefile & upload_qob_jar.sh

- infra/gcp/main.tf
Both of these were noted by Bernick as a part of his security review.
1. `local_infile`: if this is on, a client could in theory read any file on the instance by loading it into a table.
2. `skip_show_database`: this disables `SHOW DATABASES` by default; we can still grant certain users (e.g. the admin-pod) the `SHOW DATABASES` privilege. A bit of security by obscurity, IMO, but it does not bother me much. I can always see the list of databases via the GCP console.
> [db] encode our three database flags in TF & add two more

- benchmark/scripts/benchmark_in_batch.py
> [benchmark] actually set the env vars

- hail/python/hailtop/batch/backend.py
CHANGELOG: The Batch LocalBackend now sets the working directory for dockerized jobs to the root directory instead of the temp directory
Tested with the following:
```
In [1]: import hailtop.batch as hb
...: b = hb.Batch(backend=hb.LocalBackend())
...: j = b.new_job()
...: j.image('ubuntu:20.04')
...: j.command('pwd')
...: b.run()
...:
...:
/
Batch completed successfully!
```
> [batch] Use the root directory for the working directory in dockerized local backend jobs

- hail/python/hail/methods/misc.py
- hail/python/hail/methods/qc.py
- hail/python/test/hail/methods/test_qc.py
CHANGELOG: `hl.variant_qc` no longer requires a `locus` field.
Fixes #12844.
> [query] relax requirements of variant_qc

- benchmark/Makefile
I develop accross a couple of OSes and my username isn't always the same. I'd like to expose this make variable so that I can push images to the same location.
> [benchmark] Allow configuration of `BENCHMARK_DOCKER_TAG`

- hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
- hail/src/main/scala/is/hail/io/fs/FS.scala
- hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
- hail/src/main/scala/is/hail/io/fs/RouterFS.scala
CHANGELOG: In Query-on-Batch, simple pipelines with large numbers of partitions should be substantially faster.
:facepalm:
> [qob] Read results files 20x faster by not using Scala parallel collections

- hail/python/hail/backend/backend.py
- hail/python/hail/backend/local_backend.py
- hail/python/hail/backend/service_backend.py
- hail/python/hail/backend/spark_backend.py
- hail/python/hail/experimental/function.py
- hail/python/hail/experimental/vcf_combiner/vcf_combiner.py
- hail/python/hail/vds/combiner/combine.py
- hail/python/test/hail/fs/test_worker_driver_fs.py
- hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
CHANGELOG: In Query-on-Batch, allow writing to requester pays buckets, which was broken before this release.
> [qob] allow writing to requester pays buckets

- hail/python/hail/backend/service_backend.py
- hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
Merge of https://github.com/hail-is/hail/pull/12868 and https://github.com/hail-is/hail/pull/12867 because I expect each is likely to fail due to the other's error.
---
[qob] retry `storage.writer` and `storage.reader`
I do not think we frequently get errors in `storage.reader`, but I think `storage.writer` was
always flaky and we were protected by the `retryTransientErrors` on `createNoCompression`. My
change to fix requester pays delayed the error until either the first `write` or the `close`
which do not have a `retryTransientErrors` (and it is not obvious to me that it is safe to retry
a `flush`).
---
[qob] retry transient errors reading the results file
---
> [qob] Fix new transiencies

- hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
- hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPass.scala
This fixes a bug Mike W was hitting with a gnomAD pipeline. I wasn't able to replicate with a trivial example, and would prefer not to spend another half-day poring through that huge IR to try to minimize. Verified that this fixes the problem, though.
https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/.E2.9C.94.20Summing.20number.20of.20entries.20meeting.20criteria.20.20by.20group
> [compiler] Don't generate IRs with reference sharing during agg lowering

- Makefile
- build.yaml
- ci/Dockerfile.ci-utils
- ci/test/resources/build.yaml
the `test_dataproc` steps need what is in ci-utils but also the tools in base_image to build hail. Tested with a dev deploy of `test_dataproc-37`
> [ci] Put ci-utils on top of base image

- batch/batch/driver/job.py
- batch/sql/add-deduped-resource-ids-to-attempt-resources.sql
- batch/sql/estimated-current.sql
- build.yaml
This is now the first PR in the deduping resource ids stack. I decided that we should directly write the new "deduped_resource_id" value rather than in a trigger to make things simpler to reason about later when dropping unused columns. The implication of this is this PR must now be fully deployed before #12757. We need to announce this on Zulip once this PR merges.
> [batch] Add deduped resource id column to attempt resources table

- batch/test/test_accounts.py
- batch/test/test_aioclient.py
- batch/test/test_batch.py
- batch/test/test_dag.py
- batch/test/test_scale.py
- batch/test/utils.py
- hail/python/test/hailtop/batch/test_batch.py
very helpful when executing tests locally. Most of the lines here are noise because I added a function that wraps `client.create_batch` so needed to replace usages everywhere.
> [batch] Default to using the test method name for the name of the batch

- hail/python/hail/docs/vds/index.rst
- hail/python/hail/vds/__init__.py
- hail/python/hail/vds/combiner/combine.py
- hail/python/hail/vds/methods.py
- hail/python/hail/vds/variant_dataset.py
- hail/python/test/hail/vds/test_vds.py
CHANGELOG: Added `hl.vds.store_ref_block_max_len` to patch old VDSes to make interval filtering faster.
> [vds] Add function to patch old VDSes to store max reference block length

- hail/python/hailtop/utils/utils.py
`google.api_core.exceptions` imports `pkg_resources` on import which is horrendously slow. Moving these imports out of the top level yields a 60% (almost half a second) improvement in startup time for `hailctl`.
> [hailctl] Improve startup time by removing big top-level imports

- dev-docs/development_process.md
- hail/Makefile
- hail/python/hail/docs/getting_started_developing.rst
I made recent changes such that all targets for anything hail are now in sync and installable in one go (earlier we had separate requirements files between query and batch that could accidentally diverge and were possibly not installable together). Forgot to update the docs
> [docs] Update instructions for installing dev python requirements

- hail/python/hailtop/aiocloud/aioazure/fs.py
- hail/python/hailtop/test_utils.py
- hail/python/test/hail/fs/test_worker_driver_fs.py
- hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
CHANGELOG: Reading data from public blobs is now supported in Azure
On current main, the following test fails:
```python
def test_can_access_public_blobs():
public_mt = 'hail-az://azureopendatastorage/gnomad/release/3.1/mt/genomes/gnomad.genomes.v3.1.hgdp_1kg_subset.mt'
assert hl.hadoop_exists(public_mt)
mt = hl.read_matrix_table(public_mt)
mt.describe()
```
The `hadoop_exists` fails in the python fs with a `ClientAuthenticationError` and the QoB pipeline fails on the Query Driver with a 401. See [zulip](https://hail.zulipchat.com/#narrow/stream/300487-Hail-Batch-Dev/topic/Azure.20public.20blobs/near/284186815) for additional context. I contemplated whether we should have a public container in our infrastructure for running tests, but the lack of requester pays makes that feel not great. …
> [fs] Support reading from public containers in azure

- hail/python/hail/backend/backend.py
- hail/python/hail/linalg/blockmatrix.py
- hail/python/hail/matrixtable.py
- hail/python/hail/table.py
- hail/python/test/hail/test_ir.py
- There is now one persist method that accepts any of a Table,
MatrixTable, or BlockMatrix.
- Backend.unpersist was incorrect with respect to unpersist docs, it was
not accepting the persisted dataset, or returning the unpersisted
dataset, or doing nothing if the dataset wasn't persisted.
> [query] Refactor and fix Backend's persist and unpersist 

- hail/python/hail/backend/service_backend.py
CHANGELOG: An interactive hail session is no longer unusable after hitting CTRL-C during a batch execution in Query-on-Batch.
> [qob] Allow a hail session to be reused after ctrl-c

- hail/python/hail/docs/_templates/req_unphased_diploid_gt.rst
- hail/python/hail/docs/overview/expressions.rst
- hail/python/hail/docs/types.rst
https://hail.is/docs/0.2/overview/expressions.html#missingness says:
> In Hail, all expressions can be missing. An expression representing a missing value of a given type can be generated with the [`null()`](https://hail.is/docs/0.2/functions/core.html#hail.expr.functions.null) function, which takes the type as its single argument.
It then proceeds to show a number of examples, all of which use `missing()` rather than `null()`, which is confusing.
PR #9936 added `hl.missing`, which supersedes `hl.null`, and replaced instances of `null(...)` invocations in the documentation. However `:func:'.null'` instances in the surrounding documentation text were missed.
> [docs, minor] Prefer missing() rather than deprecated null()

- hail/python/hail/ggplot/geoms.py
CHANGELOG: Fixed bug in `hail.ggplot` where all legend entries would have the same text if one column had exactly one value for all rows and was mapped to either the `shape` or the `color` aesthetic for `geom_point`.
This change fixes [an edge case that was encountered](https://hail.zulipchat.com/#narrow/stream/123000-general/topic/plotting.20legend.20bug/near/340198585) where, if the user creates a scatter plot and assigns one column with multiple values in it to the `color` aesthetic and one column with exactly one value in it to the `shape` aesthetic (or vice versa), the plot has a legend which contains the correct visual entries, but they are all labelled with the value from the single-value column, instead of the labels from the other column.
For a concrete example, this code: …
> [query/ggplot] fixes legend behavior for single-category columns

- build.yaml
- ci/Dockerfile.ci-utils
I should have checked quay.io for 1.12.0, which doesn't exist: https://quay.io/repository/skopeo/stable?tab=tags&tag=v1.12.0
Even though 1.12.0 was released two weeks ago https://github.com/containers/skopeo/releases
> [query] revert to skopeo 1.11.2

- infra/gcp-broad/main.tf
NB, this is a stacked PR. To see just these changes see [this commit](https://github.com/hail-is/hail/pull/12883/commits/ae51e0a9af12e4c89a44e7ce3235f3f665ff4830)
---
[VPC Flow Logs](https://cloud.google.com/vpc/docs/flow-logs):
> VPC Flow Logs records a sample of network flows sent from and received by VM instances, including
> instances used as Google Kubernetes Engine nodes. These logs can be used for network monitoring,
> forensics, real-time security analysis, and expense optimization
I found the collection process the most elucidating part of the documentation. My summary of that
process follows:
1. Packets are sampled on the network interface of a VM. Google claims an average sampling rate of
1/30. This rate reduces if the VM is under load. This rate is immutable to us.
2. Within …
> [terraform] enable VPC Flow logs in all our US subnets

- batch/batch/worker/worker.py
- build.yaml
We always ensure that `cleanup` is run, but in order to ensure that `post_job_complete` is run we need to ensure we get through any computation in cleanup and `mark_complete` that could potentially hang. So we add timeouts to any yield points in those functions and broadly catch exceptions so we always continue in the cleanup/mark_complete process regardless of failure.
> [batch] Add timeouts to ensure that post_job_complete is reached

- batch/sql/estimated-current.sql
- batch/sql/mitigate-bad-attempt-resources-trigger.sql
- build.yaml
There was an extra check in the where statement for the token matching on the jobs billing table. The jobs billing table is the only one not parameterized with a token.
> [batch] Fix bad insert attempt resources trigger

- hail/python/hail/table.py
- hail/python/hail/utils/struct.py
CHANGELOG: `hl.Struct` now has a correct and useful implementation of pprint.
For structs with keys that were not identifiers, we produced incorrect `repr` output. For `pprint`, we just `pprint`'ed a dictionary (so you cannot even tell that the object was an `hl.Struct`). This PR:
1. Fixes `hl.Struct.__str__` to use the kwargs or dictionary representation based on whether the keys are Python identifiers.
2. Teaches `StructPrettyPrinter` to first try to `repr` the struct (this is what the default pretty printer does)
3. Teaches `StructPrettyPrinter` to properly pretty print a struct as an `hl.Struct` preferring the kwarg representation when appropriate.
4. Teaches `_same` to use pretty printing when showing differing records.
> [query] fix & improve pprint for hl.Struct

- infra/gcp-broad/main.tf
The old bucket did not use uniform access control and also was multi-regional (us). I created a new bucket using the random suffix ger0g which has uniform access control. I also switched the location to us-central1 (not pictured here because that is a variable).
I copied all the JARs from `gs://hail-query/jars` to `gs://hail-query-ger0g/jars` using a GCE VM.
Again, global-config is not present in our terraform, so I'll have to manually edit that to reflect this new location: `gs://hail-query-ger0g`.
The deployment process is:
1. Edit global-config to reflect new bucket.
2. Delete batch and batch-driver pods.
3. Delete old workers.
The rollback process (if necessary) is the same.
Since this requires wiping the workers, I'll wait for a time when no one is on the cluster to do it.
Any users …
> [qob] use a regional bucket with uniform access control

- batch/batch/worker/worker.py
Applies the most restrictive bind and event propagation settings to job container mounts. While user jobs do not have the capabilities to create mount points, overlapping mount points in the container config can inadvertently trigger mount propagation back to the host which we just never want.
> [batch] Restrict mount propagation for job container mounts

- hail/python/test/hail/fs/test_worker_driver_fs.py
- hail/python/test/hailtop/batch/test_batch.py
- infra/gcp-broad/main.tf
I updated terraform but
1. GCP Terraform state is still local on my laptop.
2. GCP Terraform appears to not configure global-config. As such, I cannot thread the name of the bucket through to the tests the way we do with TEST_STORAGE_URI. For now, I've hardcoded the name (which is what we were doing previously). When we eventually get to testing recreation of GCP in a new project we'll have to address the global config then.
> [batch] use regional bucket for requester pays tests

- build.yaml
- hail/Dockerfile.hail-pip-installed-python38
- hail/Dockerfile.hail-pip-installed-python39
Because the python version in hail-ubuntu changed from 3.7 to 3.8, both of the `hail-pip-installed` dockerfiles were running 3.8. I changed the old 3.7 dockerfile to try to use 3.9
> [ci] Test pip-installed lints against python 3.9

- batch/test/test_batch.py
Skipping these for the timebeing because they currently only pass for 16-core worker VMs and not for 8-core worker VMs.
> [batch] Skip currently incorrect tests after Azure price change

- batch/batch/worker/worker.py
I think this change is better than #12975
> [batch] Don't rmtree if any errors occur while unmounting

- hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
Attempting to install hail on dataproc using the `init_notebook.py` script errors out because hail depends on a more recent version of `jinja2` than the version of `notebook` pinned in the script allows for. This change upgrades the pinned version of `notebook` in the script to be compatible with hail's pinned `jinja2` version.
Fixes #12926.
> [hailctl/dataproc] upgrades `notebook` to version 6.0.*

- .gitignore
These show up because I use metals and bloop for Emacs code completion.
> [git] ignore .metals and .bloop

- build.yaml
- ci/ci/build.py
- ci/test/resources/build.yaml
Currently a change to `create_database.py` will only be tested once the change is in production, as opposed to in the PR where it was changed. This should fix that.
> [ci] Use the ci-utils image from the new branch for db creation

- batch/batch/front_end/validate.py
- batch/test/test_batch.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/batch_client/client.py
- hail/src/test/scala/is/hail/services/batch_client/BatchClientSuite.scala
This has been unused for a long time and I wanted to rid the world of it. This changes the client to no longer send the `mount_docker_socket` field, updates the validator so it's ok for that field to be missing, and explicitly rejects any requests where `mount_docker_socket` is set to true. The reason I couldn't remove `mount_docker_socket` entirely from the codebase is older clients would break if it was not at least optional in the validator spec, which is kind of annoying.
Dev deployed this and successfully submitted jobs using the client from this branch and the client from main.
> [batch] Delete old unused docker socket field in job spec

- batch/batch/cloud/gcp/driver/create_instance.py
This bug was introduced by https://github.com/hail-is/hail/pull/13016 .
> [batch] without auto-create subnetworks, you must specify a subnet

- hail/python/test/hail/methods/test_impex.py
- hail/python/test/hail/table/test_table.py
- hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
- hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
Parallel export modes now write a manifest file, "shard-manifest.txt" to the folder where generated shards live. These manifest files are text files with one filename per line, containing name of each shard written successfully to the directory. These filenames are relative to the export directory.
If a header is written, that is the first filename in the shard manifest.
> [query] Add manifest files with parallel export

- build.yaml
These tests spin up a lot of non-preemptible Query Driver jobs. This makes these tests feel not really preemptible safe, as a preemption of the test job will end up submitting duplicate Query Drivers.
> [ci] Run service backend tests on non-preemptibles

- hail/src/main/scala/is/hail/expr/ir/BlockMatrixWriter.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/main/scala/is/hail/expr/ir/ValueWriter.scala
- hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
- hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/RequirednessSuite.scala
WriteValue has always been a weird bit of functionality. It takes a path and writes a single value to that path. This change does not change that quirk, however this change expands the possibilities of hail value serialization through the introduction of ValueWriter, analogous to PartitionWriter.
ValueWriters serialize hail values and are responsible for the allocation and cleanup of any resources required to do that.
One ValueWriter has been implemented as part of this change. The ETypeFileValueWriter, the minimum necessary functionality for ensuring WriteValue still works exactly as it used to.
The short term here is to implement the BlockMatrixRectanglesWriter with a value writer that dumps an NDArray in either binary or text. The longer term is to develop more faculties within the IR …
> [query] Expand WriteValue beyond hail EType serialization

- hail/python/hailtop/utils/__init__.py
- hail/python/hailtop/utils/utils.py
- hail/src/main/scala/is/hail/services/package.scala
CHANGELOG: In Query-on-Batch, retries of certain errors has been increased from once to five times. This should reduce the occurrence of transient errors such as "Connection reset" and `SocketException`.
---
The old approach doesn't work because it doesn't have the retry logic around the invocation. Moreover, the old approach wouldn't retry transient errors encountered after a retry once error. The new approach address both.
> [services] retry five times instead of once

- hail/build.gradle
- hail/scripts/upload_qob_jar.sh
- hail/settings.gradle
- hail/shadedazure/build.gradle
- hail/src/main/resources/META-INF.services/com.azure.core.http.HttpClientProvider
- hail/src/main/resources/META-INF.services/is.hail.shadedazure.com.azure.core.http.HttpClientProvider
- hail/src/main/resources/META-INF/services/com.azure.core.http.HttpClientProvider
- hail/src/main/resources/META-INF/services/com.ctc.wstx.shaded.msv.relaxng_datatype.DatatypeLibraryFactory
- hail/src/main/resources/META-INF/services/com.ctc.wstx.stax.WstxInputFactory
- hail/src/main/resources/META-INF/services/com.fasterxml.jackson.core.JsonFactory
- hail/src/main/resources/META-INF/services/com.fasterxml.jackson.core.ObjectCodec
- hail/src/main/resources/META-INF/services/com.fasterxml.jackson.databind.Module
- hail/src/main/resources/META-INF/services/io.micrometer.context.ContextAccessor
- hail/src/main/resources/META-INF/services/is.hail.shadedazure.com.azure.core.http.HttpClientProvider
- hail/src/main/resources/META-INF/services/javax.xml.stream.XMLEventFactory
- hail/src/main/resources/META-INF/services/javax.xml.stream.XMLInputFactory
- hail/src/main/resources/META-INF/services/javax.xml.stream.XMLOutputFactory
- hail/src/main/resources/META-INF/services/org.codehaus.stax2.validation.XMLValidationSchemaFactory
- hail/src/main/resources/META-INF/services/org.codehaus.stax2.validation.XMLValidationSchemaFactory.dtd
- hail/src/main/resources/META-INF/services/org.codehaus.stax2.validation.XMLValidationSchemaFactory.relaxng
- hail/src/main/resources/META-INF/services/org.codehaus.stax2.validation.XMLValidationSchemaFactory.w3c
- hail/src/main/resources/META-INF/services/reactor.blockhound.integration.BlockHoundIntegration
- hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
- hail/src/main/scala/is/hail/services/package.scala
Fixes #12976
I do not fully understand the Azure git tagging scheme, but [this commit](https://github.com/Azure/azure-sdk-for-java/commit/054df3fb74098f4ee30eeb1df70df1e40438d169) appears to have made `close` idempotent. It was merged in June of 2022. That commit resolved [an issue](https://github.com/Azure/azure-sdk-for-java/issues/24782) reporting an error very similar to our own.
All the azure version changes update the Azure packages to their latest versions as of 2023-05-09 1713 ET.
Unfortunately, newer Azure versions and Spark 3.3.0 have inconsistent `io.netty` requirements. Spark is stuck back in February 2022. Spark 3.4.0 does support a compatible version of `io.netty`, but we're months from seeing that in Dataproc.
This change packages up Azure and all its dependencies into one …
> [services] update azure-storage-blob 12.22.0 to mitigate "Stream is already closed"

- infra/gcp-broad/main.tf
ACLs apply to an entire bucket, per-object ACLs are banned. We never used the latter anyway.
> [infra] use uniform bucket level access

- infra/gcp-broad/main.tf
This allows us to fully control subnet parameters. In particular, we want VPC flow logs enabled on all subnets. I already made this change in the console and deleted the asia, europe, me, northamerica, and southamerica subnets which were not in use and which lacked VPC flow logs.
> [infra] create subnetworks manually

- hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
- hail/src/main/scala/is/hail/services/package.scala
Fixes #12983
---
After an `FSSeekableInputStream` method (successfully) returns, `getPosition` always represents theintended location within the object. We can entirely eliminate `lazyPosition` because it tracks the
same value as `getPosition` when `reader == null`.
For retryable reads, we just seek back to the known correct location of the stream before attempting to read again.
> [qob] maybe retry GSFS reads

- batch/test/pytest.ini
- hail/python/test/hail/table/test_table.py
- hail/python/test/pytest.ini
I noticed this while xfail-ing a different test. It is possible this test now passes. We will see!
> [query] xfail should always be strict

- benchmark/Dockerfile
- benchmark/Makefile
Related: https://github.com/hail-is/hail/pull/12963
Remember to add your service account to the new respository policy bindings: 
```
$ gcloud artifacts repositories add-iam-policy-binding 'hail-benchmarks' \
--member='serviceAccount:YOUR_SERVICE_ACCOUNT' \
--role='roles/artifactregistry.repoAdmin' \
--location='us' \
--project='broad-ctsa'
```
> [benchmark] Make benchmarks run in Google Artifact Repository

- hail/src/main/scala/is/hail/methods/LocalLDPrune.scala
> [query] Better message for LocalLDPrune only taking diploid calls

- hail/python/hail/backend/service_backend.py
- hail/python/hail/expr/expressions/expression_utils.py
- hail/python/test/hail/backend/test_service_backend.py
The service backend is shared among all the threads which means we were changing the resource requests of random other tests. This substantially delays certain tests when, say, 16 quick partitions require 8 highmem cores each.
> [qob] only use highmem for one test

- infra/gcp-broad/main.tf
Without this I get a diff because it wants to set workload_pool to null.
> [infra] fix workload_identity_config

- hail/python/hail/table.py
CHANGELOG: In Query-on-Batch, `naive_coalsce` no longer performs a full write/read of the dataset. It now operates identically to the Query-on-Spark implementation.
> [qob] actually do a naive_coalsece

- build.yaml
- ci/ci/build.py
- ci/create_database.py
- ci/create_initial_account.py
- ci/test/resources/build.yaml
- docker/mysql/db.yaml
- gear/gear/__init__.py
- gear/gear/database.py
- hail/python/hailtop/auth/sql_config.py
- tls/Dockerfile
- tls/create_test_db_config.sh
This change creates mysql pods for test and dev namespaces, instead of sharing the CloudSQL database server. The areas of change are as follows:
The current approach in main does a little trick. Since the current `createDatabase` step uses the `database-server-config` from default to generate admin/user sql configs, the CI pipeline creates a dummy database `test-database-instance` to create a `sql-test-instance-admin-config` that inherits the credentials from the production `database-server-config`, and then copies that within the test namespace to `database-server-config`.
In this change, since we are creating the server ourselves, we can just replace these with a step that creates a `database-server-config` from scratch, and then uses that for the DB pod.
Overall making these changes …
> [ci] Create a test MySQL server in test and dev namespaces

- batch/batch/cloud/azure/worker/worker_api.py
- batch/batch/cloud/gcp/worker/credentials.py
- batch/batch/cloud/gcp/worker/worker_api.py
- batch/batch/worker/credentials.py
- batch/batch/worker/worker.py
- batch/batch/worker/worker_api.py
Just some more shoving of implementation details into `CloudWorkerAPI` so that credential objects are more of a black box to `worker.py`. Can e.g. change up certain implementations to use oauth2tokens for users.
> [batch] Give cloud-specific API implementations more control over container registry credentials

- hail/src/main/resources/META-INF.services/com.azure.core.http.HttpClientProvider
- hail/src/main/resources/META-INF.services/is.hail.shadedazure.com.azure.core.http.HttpClientProvider
This appears unnecessary. I was mislead by a website about the correct path at which to store Serivce Provider Interface implementations.
> [query] eliminate irrelevant META-INF.services

- hail/python/hail/docs/change_log.md
For posterity, update the date in the change log to reflect when PR #12987 was merged and the release made.
Very minor, and probably already less important than it was last week, but for future readers it's useful for these to be aligned…
> Correct the 0.2.116 release date [very minor]

- hail/python/hailtop/hailctl/config/cli.py
Validation code was not updated when adding azure https support. Made this check a bit more robust and tested locally.
Resolves #13049
> [hailctl] Fix validation for remote_tmpdir to allow azure https scheme

- hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/BlockMatrixWriter.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/main/scala/is/hail/expr/ir/ValueReader.scala
- hail/src/main/scala/is/hail/expr/ir/ValueWriter.scala
- hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
- hail/src/main/scala/is/hail/types/encoded/ENumpyBinaryNDArray.scala
- hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/RequirednessSuite.scala
This represents a small redesign of ValueWriter as well.
Add deserializers, subclasses of ValueReader and have ReadValue use them. A ValueReader deserializes a single hail value from an input stream.
This change also alters the semantics of ValueWriters. Both readers and writers no longer manage their own I/O resources. It is the responsibility of 'callers' to do so instead. However programmers must be careful as we need to create input/output buffers to perform native serialization/deserialization. For InputBuffers in particular, the underlying stream may be left in an unusable state.
> [query] Expand ReadValue beyond hail EType deserialization

- infra/azure/main.tf
- infra/azure/modules/batch/main.tf
- infra/azure/modules/batch/variables.tf
- infra/azure/modules/ci/main.tf
- infra/azure/modules/ci/variables.tf
- infra/azure/modules/db/main.tf
- infra/azure/variables.tf
We've had to do a redeploy of our hail batch instance on Azure. This PR resolves/clarifies two issues we encountered.
1) Storage Account Name Uniqueness
Due to Azure's restrictions on storage account naming (mainly that names must be globally unique) the redeploy did not succeed.
This is because the resource group name (we chose to reuse hail) is possible under a new subscription, but the generated storage account names were therefore identical to our previous stack.
I've added in an argument called `storage_account_suffix` to account for this issue. It can be set to any arbitrary string that complies with Azure's storage account naming scheme in order to avoid naming conflicts in the future.
While the option remains to simply choose a novel resource group name this is not enforced by …
> Azure-redeploy-fixes-upstream

- batch/deployment.yaml
- batch/sql/set-test-and-dev-pools-to-16-core-max-3.py
- batch/test/test_batch.py
- build.yaml
- ci/ci/github.py
Now that test databases are hosted on their own servers instead of the single cloud-hosted MySQL, we can ramp up the parallelism both in our tests and in the number of PRs that we run at once. I recall that even before we had this DB bottleneck we still restricted the number of PRs running at once for cost reasons, but if that's not the case we could remove that restriction entirely.
> [batch] Use same size VMs in dev and PR as we use in prod

- hail/python/hail/nd/nd.py
See supported operators of KaTeX [here](https://katex.org/docs/supported.html#relations). See that the docs currently do not render [here](https://hail.is/docs/0.2/nd/index.html#hail.nd.qr).
> [nd] docs should use \ge not \gte

- batch/jvm-entryway/src/main/resources/log4j2.properties
- batch/jvm-entryway/src/main/scala/is/hail/QoBAppender.scala
CHANGELOG: In Query-on-Batch, driver and worker logs no longer buffer so messages should arrive in the UI after a fixed delay rather than proportional to the frequency of log messages.
> [qob] immediateFlush=true for QoB logger

- docker/hail-ubuntu/Dockerfile
It seems that the latest version of Ubuntu doesn't have rsync installed. I need this for developing on Batch to get the sync.py script to work.
> [docker] Add rsync to hail-ubuntu image

- batch/batch/driver/instance_collection/base.py
- hail/python/dev/pinned-requirements.txt
- hail/python/dev/requirements.txt
- hail/python/hailtop/fs/router_fs.py
- hail/python/hailtop/httpx.py
- hail/python/test/hail/table/test_table.py
- hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
- hail/src/main/scala/is/hail/io/fs/FS.scala
CHANGELOG: In Azure Query-on-Batch, fix a resource leak that prevented running pipelines with >500 partitions and created flakiness with >250 partitions.
fixes: https://github.com/hail-is/hail/issues/13061
> [qob] remove resource leak in readNoCompression

- hail/python/hail/docs/install/macosx.rst
`orjson` is a perennial issue. We could (and probably should) set an upper limit pin that is compatible with most Broad-issued Macbooks. In the meantime, hopefully this doc improvement will help users avoid the issue themselves.
> [query] suggest --only-binary=:all: if pip fails to build from source

- infra/azure/modules/vdc/main.tf
- infra/gcp-broad/main.tf
This pod is constantly blocking scale down.
There are two of them running anyway, there is no reason not to take one down to allow scale down:
```
(base) dking@wm28c-761 hail % k get pods -n kube-system -l k8s-app=kube-dns
NAME                        READY   STATUS    RESTARTS   AGE
kube-dns-7d44cdb5d5-twvfd   4/4     Running   0          14d
kube-dns-7d44cdb5d5-xjq25   4/4     Running   0          14d
```
> [infra] apply a PDB to kube-dns

- hail/python/hailtop/aiocloud/aioazure/fs.py
`asyncio.wait()` can only be used for tasks and not coroutines.
> [aiotools] Properly close azure storage clients

- batch/batch/cloud/azure/worker/worker_api.py
- batch/batch/cloud/gcp/worker/worker_api.py
- batch/batch/worker/worker.py
- batch/batch/worker/worker_api.py
worker.py requests the compute client from the worker API just so it can close it at the end. Having a close method instead on the worker API means we don't need to create a compute client in environments that don't support disks (azure and azure-terra).
> [batch] Remove unnecessary get_compute_client method on CloudWorkerAPI

- hail/python/hailtop/hailctl/dataproc/start.py
`hailctl` allows the user to define a `network` for a new dataproc cluster, but not a `subnet`. The `network` flag in `gcloud` only works for `auto` and `legacy` project networks. If a Google Project has a custom network, the `subnet` must be supplied manually.
This PR adds that functionality to `hailctl`. Its a very simple passthrough, so not much effort was required.
> CHANGELOG Allow subnet to be passed through to gcloud in hailctl

- hail/python/hail/ggplot/geoms.py
CHANGELOG: `hail.ggplot.geom_point` now displays a legend group for a column even when it has only one value in it.
Currently, if a column with only one value in it is passed to either the `color` or the `shape` aesthetic for `geom_point`, the generated legend will not include a group with a single entry for that aesthetic. However, R's ggplot2 library in the same situation includes such a legend group.
This change brings our ggplot implementation into line with R's ggplot2 in that regard.
For example, this code:
```python
from hail.ggplot import ggplot, aes, geom_point
ht = ht.annotate(squared=ht.idx ** 2)
ht = ht.annotate(even=hl.if_else(ht.idx % 2 == 0, "yes", "no"))
ht = ht.annotate(threeven="good")
fig = (
ggplot(ht, aes(x=ht.idx, …
```
> [query/ggplot] Shows legend group for single-value columns

- hail/python/hailtop/hailctl/dataproc/start.py
I'm surprised that no one has complained about this. Is this setting not used much? Should we alert people that they might have garbage in places they wouldn't expect?
> [hailctl] Fix wrong temp-bucket setting in hailctl dataproc start

- auth/deployment.yaml
In particular, start with a few copies, no autoscaling, and no disruption budget
> [auth] mirror the batch settings for non-deploy

- hail/python/hail/backend/service_backend.py
Alright, I snagged the PR namespace from the CI:
```
pr-13135-default-u5tt5011yt5w
```
Then I went to the Azure [Log Analytics workspace haildev-logs](https://portal.azure.com/#@haildev.onmicrosoft.com/resource/subscriptions/22cd45fe-f996-4c51-af67-ef329d977519/resourceGroups/haildev/providers/Microsoft.OperationalInsights/workspaces/haildev-logs/logs).
I went to "Queries", selected "DK's AKS Pod Logs", modified the namespace to the aforementioned one, and added a filter for "hail-az://".
```
let startTimestamp = ago(2h);
KubePodInventory
| where TimeGenerated > startTimestamp
| extend PodName=Name
| where Namespace == "pr-13135-default-u5tt5011yt5w" and PodName startswith "batch-driver"
| distinct ContainerID, PodName, Namespace
| join (
ContainerLog
| where TimeGenerated > …
```
> [qob] more debugging information on UnexpectedEOFError in Azure

- infra/azure/bootstrap.sh
Unclear to me exactly why (perhaps a terraform update on my machine) but running terraform against azure was complaining that it didn't know the resource group that the terraform state storage account lives in. Unclear to me why this is necessary because the storage account is globally unique but it was easy enough to add and fixed my problem *shrug*. Let me know if you'd like me to look into this further.
> [infra] Add resource group to azure terraform state remote config

- auth/pinned-requirements.txt
- batch/pinned-requirements.txt
- ci/pinned-requirements.txt
- gear/pinned-requirements.txt
- hail/python/dev/pinned-requirements.txt
- hail/python/hailtop/pinned-requirements.txt
- hail/python/pinned-requirements.txt
- web_common/pinned-requirements.txt
> [ci][gear][auth][query][hailtop] upgrade requests and cryptography

- build.yaml
Was getting tired of having to manually delete my root cert every so often and redeploy. This will recreate the root cert in dev and test namespaces if it is already expired. Deleting an expired root cert won't break communication that isn't already now broken.
> [ci] Automatically recreate expired root cert in dev and test namespaces

- hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
A test timed out with this in the logs. This is some driver job. It just hangs for 2 minutes trying to talk to Azure Blob Storage presumably? Let us get some more information:
```
2023-06-08 20:22:28.209 JVMEntryway: INFO: Yielding control to the QoB Job.
2023-06-08 20:22:28.210 Tokens: INFO: tokens found for namespaces {pr-12991-default-ei61x1qrplk9}
2023-06-08 20:22:28.210 tls: INFO: ssl config file found at /batch/240df6ec091b49d8a6062b781e6700d3/secrets/ssl-config/ssl-config.json
2023-06-08 20:24:30.873 : INFO: RegionPool: initialized for thread 10: pool-2-thread-2
2023-06-08 20:24:31.016 ServiceBackend$: INFO: executing: iaU8w3QX6Y6hRrB9jczJds ArrayBuffer((), is.hail.utils.SerializableHadoopConfiguration@5ad5cde6)
2023-06-08 20:24:31.153 : INFO: JSON: …
```
> [qob] noisier ServiceBackend startup

- hail/python/hail/table.py
This both avoids an extra pass to find the failing rows as well as avoiding a an extra pass if the globals depend on non-global data. In particular, this pipeline would run the column aggregations four times (IMO, at most twice is OK):
```
mt = hl.utils.range_matrix_table(2,2)
mt = mt.annotate_entries(x = mt.row_idx * mt.col_idx)
mt = mt.annotate_cols(mean_x = hl.agg.mean(mt.x))
mt = mt.annotate_entries(x = mt.x - mt.mean_x)
mt._same(mt)
```
> [query] Improve _same to make exactly one pass over the data

- hail/python/hailtop/hailctl/dev/cli.py
The `--extra-config` short option used to be `-c` and I accidentally made it `-e`, which likely shadows the previous option. This broke using `-e` for `--excluded_steps`.
> [ci] Fix dev deploy options

- tls/create_test_db_config.sh
These are intended to ultimately be pretty short lived anyway so the expiration is more annoying than useful, but the default of 30 days is a little tight.
> [db] Make the test and dev DB certs last a year

- bootstrap-gateway/Makefile
- build.yaml
- grafana/Makefile
- grafana/deployment.yaml
- notebook/Makefile
- website/Makefile
Manual image building for these three images was broken because they weren't fully converted to use the new image targets in the top-level Makefile. I manually ran the build targets for these images. I also changed Grafana to use hail-ubuntu because it has everything it needs now. I ripgrepped the codebase for `image-ref` and `$(MAKE) -C ../docker` after this change and can find no more matches.
> [boostrap-gateway|notebook|grafana] Fix broken references to images in Makefiles

- batch/sql/dedup_billing_project_users_v2.py
- build.yaml
I'm sorry I had to duplicate everything :(
Here's the diff from the old migration script. I fixed the SQL and also only throw an exception after all bad records have been found:
```diff
diff --git a/batch/sql/dedup_billing_project_users.py b/batch/sql/dedup_billing_project_users_v2.py
index 5533e63e5e..b840a30e17 100644
--- a/batch/sql/dedup_billing_project_users.py
+++ b/batch/sql/dedup_billing_project_users_v2.py
@@ -96,6 +96,8 @@ async def audit_changes(db):
chunk_offsets.append(offset)
chunk_offsets = list(zip(chunk_offsets[:-1], chunk_offsets[1:]))
+    failing_bp_users = []
+
if chunk_offsets != [(None, None)]:
for offsets in chunk_offsets:
start, end = offsets
@@ -130,25 +132,25 @@ FROM (
LOCK IN SHARE MODE
) AS old
LEFT JOIN (
-  SELECT billing_project, `user`, resource_id, …
```
> [batch] Fix audit for the deduping bp user resources migration

- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
- hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIRHelpers.scala
- hail/src/main/scala/is/hail/rvd/RVD.scala
- hail/src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala
Provides an example and template for doing the rest.
> [query] Remove old implementation of TableJoin

- build.yaml
- hail/python/hailtop/aiocloud/aioazure/fs.py
- hail/python/test/hail/fs/test_worker_driver_fs.py
- hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
- hail/src/main/scala/is/hail/io/fs/FS.scala
- hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
- hail/src/main/scala/is/hail/io/fs/HadoopFS.scala
- hail/src/main/scala/is/hail/io/fs/RouterFS.scala
This PR adds support for Azure SAS tokens in QoB. A SAS token is basically a blob storage URI with a short-lived credential to access that resource appended as a URL query string. In such a scenario where the FS receives a blob URI with a SAS token, that token should be used instead of the latent credentials on the system. Most of the changes to the `AzureStorageFS.scala` are to parse out a SAS token from blob names.
This change brings with it a couple caveats. Unfortunately it is not possible to truly disambiguate a SAS token from a glob pattern, or even just a normal blob filename. So we take what is probably a safe assumption and look to see if there exists a query-parameter style key-value pair after the last `?` in the blob name. If this is the case, we treat everything after the …
> [fs] Add support for SAS tokens in Scala AzureStorageFS

- build.yaml
- hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
- hail/src/main/scala/is/hail/backend/service/Worker.scala
- hail/src/main/scala/is/hail/services/tls/package.scala
- tls/config.yaml
Pretty sure this is all dead code because we don't currently speak TLS between the worker and internal gateway. I think what's ultimately the right approach here is to start sending the hail root cert to workers and have them mount that at a well known location to all containers, not have it be part of the job spec. Then we should be able to talk https to internal gateway.
I'm not exactly sure what to do in this PR specifically. I want to get rid of this hard dependency on the ssl-config because
1. Doesn't exist in terra as everything goes through the relay listener
2. These ssl configs aren't used anyway
but I'd need to put in a bit more work to start sending the root cert to workers and add https to internal-gateway
> [tls] make internal cert config optional

- infra/gcp-broad/main.tf
Currently hail-vdc uses the GSA for the test user as the GSA for the test-dev user. We should be using different identities. This is done correctly in the other terraform so the following steps only apply to `hail-vdc`. After this change is applied and a new identity for test-dev is created, I will:
- Create a key for the new service account and update `test-dev-gsa-key` with that key
- Update the auth database to set the `hail_identity` for test-dev to the new identity
> [infra] Add test-dev GSA to gcp-broad

- hail/python/hail/vds/methods.py
- hail/python/test/hail/vds/test_vds.py
> [query/vds] Don't densify past the end of contigs

- hail/python/hail/expr/aggregators/__init__.py
- hail/python/hail/expr/aggregators/aggregators.py
- hail/python/hail/expr/expressions/typed_expressions.py
- hail/python/hail/ir/__init__.py
- hail/python/hail/ir/ir.py
- hail/python/test/hail/expr/test_expr.py
This method is useful for accessing functionality that exists in the aggregator library but not the basic expression library, for instance, `call_stats`.
> [query] Enable use of aggregators on array expressions

- batch/batch/cloud/azure/driver/create_instance.py
- batch/batch/cloud/gcp/driver/create_instance.py
- batch/batch/worker/worker.py
The goal of this PR is to have all of the JVM container logs available where all the worker logs are. I tagged the entries with "worker.log" so they show up with the other worker log entries. However, it's plain text with no timestamp. We can improve the formatting as a separate project. Notice the two entries with "*" on the left instead of the normal "I".
The design choice I made is to have the JVM containers write to a location that is static. We cannot easily change the fluentd configuration dynamically. It requires restarting the daemon which takes 1.5 seconds. Furthermore, the configuration for fluentd is on /etc/ on the host which the batch worker container cannot access. Hence, why I took the approach of specifying it in the startup script at known locations. 
Before we merge …
> [batch] JVM container logs streamed with fluentd

- hail/python/hail/ir/__init__.py
- hail/python/hail/ir/ir.py
- hail/python/hail/nd/__init__.py
- hail/python/hail/nd/nd.py
- hail/python/test/hail/expr/test_ndarrays.py
- hail/src/main/scala/is/hail/asm4s/Code.scala
- hail/src/main/scala/is/hail/expr/ir/Children.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/main/scala/is/hail/linalg/LAPACK.scala
- hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SNDArray.scala
Add an `eigh` ndarray method, for finding eigenvalues of symmetric matrices ("h" is for Hermitian, the complex analogue of symmetric). This just dispatches to an [LAPACK method](https://netlib.org/lapack/explore-html/d2/d8a/group__double_s_yeigen_gaeed8a131adf56eaa2a9e5b1e0cce5718.html). The interface is compatible with [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eigh.html#scipy.linalg.eigh).
> [query] add eigh method

- batch/batch/utils.py
This query is the slowest one we have right now and is making the billing projects pages to be slow. I saw substantial speed improvements using lateral joins.
- For querying all open billing projects for a given user, it went from 1.8 seconds to 0.87 seconds.
- For querying all open billing projects (i.e. billing projects page), it went from 5.5 seconds to 2.6 seconds.
The speed of the queries should go down further once the aggregated billing project user resources table has been deduped and further improvements after compaction.
> [batch] Fix billing projects query to be fast with lateral joins

- infra/gcp-broad/main.tf
This was misconfigured and is currently breaking grafana which uses the GCE metadata server to connect to the google datasource.
> [infra] Revert GKE metadata workload identity config

- hail/python/hailtop/hailctl/__main__.py
- hail/python/hailtop/hailctl/auth/cli.py
- hail/python/hailtop/hailctl/batch/billing/cli.py
- hail/python/hailtop/hailctl/batch/cli.py
- hail/python/hailtop/hailctl/config/cli.py
- hail/python/hailtop/hailctl/dataproc/cli.py
- hail/python/hailtop/hailctl/dev/cli.py
- hail/python/hailtop/hailctl/hdinsight/cli.py
`rich` stacktraces will by default show the local variables at each level of scope, which is nice for debugging but can leak things like tokens. Best not to have that show up in logs or accidentally pasted into zulip
> [hailctl] Dont show local variables in stacktraces

- batch/batch/front_end/front_end.py
- batch/batch/front_end/templates/billing_limits.html
Fixes #13205 
Possible billing project states are defined in the database schema:
```mysql
CREATE TABLE IF NOT EXISTS `billing_projects` (
`name` VARCHAR(100) NOT NULL,
`name_cs` VARCHAR(100) NOT NULL COLLATE utf8mb4_0900_as_cs,
`status` ENUM('open', 'closed', 'deleted') NOT NULL DEFAULT 'open',
`limit` DOUBLE DEFAULT NULL,
`msec_mcpu` BIGINT DEFAULT 0,
PRIMARY KEY (`name`)
) ENGINE = InnoDB;
CREATE INDEX `billing_project_status` ON `billing_projects` (`status`);
CREATE UNIQUE INDEX `billing_project_name_cs` ON `billing_projects` (`name_cs`);
CREATE INDEX `billing_project_name_cs_status` ON `billing_projects` (`name_cs`, `status`);
```
> [batch] Separate closed and open projects on billing limits page

- auth/auth/driver/driver.py
- auth/sql/add-hail-identity-uid.sql
- auth/sql/estimated-current.sql
- build.yaml
- gear/gear/clients.py
- hail/python/hailtop/aiocloud/aioazure/client/graph_client.py
In order to start using Google or AAD access tokens instead of hail-minted tokens, we need to be able to identify a service account in the system by its UID at their identity provider. In Google, this UID is the `uniqueId` field of the Service Account. In AAD, it is the Service Principal Object ID. In an upcoming change, we'll update the user creation process to add this ID upon user creation, at which point we will be able to safely remove this code that updates existing records.
I've marked this PR as `full-deploy` so the AUS folks can roll this commit out specifically before this column is relied on. This way we can safely remove the loop in a follow-up PR and know they will have run this code to populate the column.
> [auth] Add internal hail identity UIDs to the users table

- batch/batch/driver/instance_collection/job_private.py
- batch/batch/driver/instance_collection/pool.py
- batch/batch/driver/job.py
- batch/batch/driver/main.py
- batch/batch/front_end/front_end.py
- batch/batch/utils.py
- batch/batch/worker/worker.py
- batch/sql/add-jobs-ready-time.sql
- batch/sql/estimated-current.sql
- build.yaml
- hail/python/hailtop/hail_logging.py
I realize this looks like a lot of code changes, but it's mostly copying and pasting two SQL procedures and changing one line in each.
This adds 4 bits of metadata to requests that then can be queried as extra metadata:
- batch_id
- job_id
- batch_operation
- job_queue_time
Should be self-explanatory except job_queue time is the time in which the job is first set to ready to when it was scheduled on the worker (exact moment is when the job config is made to send to the worker).
Example logging query. Note that the search on "batch_id" is not optimized so you definitely want to add some kind of time limit that's short on the window to search. I can add my Python script that scrapes these logs and makes a Plotly figure in a separate PR once this goes in.
```
( …
```
> [batch] Add identifying metadata to Batch requests

- hail/src/main/scala/is/hail/expr/ir/NestingDepth.scala
- hail/src/test/scala/is/hail/expr/ir/ForwardLetsSuite.scala
CHANGELOG: Fixed bug causing poor performance and memory leaks for Matrix.annotate_rows aggregations
> [query] Fix BAD loop deoptimization with StreamAgg

- auth/auth/driver/driver.py
For deleted users the request to look up the AAD application can fail with a 404, and we don't need to gather this information for deleted users anyway.
> [auth] Only resolve the identity UID for active users

- hail/python/hailtop/hailctl/dataproc/cli.py
This got dropped in the move to typer.
> [hailctl] Restore pkgs alias for dataproc start packages option

- batch/batch/cloud/azure/worker/worker_api.py
- hail/python/hailtop/aiocloud/aioazure/credentials.py
Azure default credentials will use the metadata server when available so we can just use those instead of manually reaching out to the metadata server.
> [batch] Reuse AzureCredentials on the worker

- hail/python/hail/expr/functions.py
- hail/python/hail/genetics/call.py
- hail/python/hail/genetics/locus.py
- hail/python/hail/utils/interval.py
- hail/python/hail/utils/linkedlist.py
- hail/python/hail/utils/struct.py
- hail/python/test/hail/expr/test_functions.py
- hail/python/test/hail/genetics/test_call.py
- hail/python/test/hail/genetics/test_locus.py
- hail/python/test/hail/utils/test_utils.py
RR: https://github.com/hail-is/hail/issues/13045
RR: https://github.com/hail-is/hail/issues/13046 
Support symmetric comparison of structs and struct expressions.
Provide better error messages when attempting to construct literals from expressions with free variables.
> Fix #13045 - Comparison of Structs and Struct Exprs

- batch/batch/front_end/front_end.py
- batch/test/test_batch.py
The test that lists batches timed out. The main problem is the limit in the aioclient used by the test_batch tests was passing a string rather than an integer. I assumed downstream the function was passing an integer. Therefore, we were doing this:
batch_id < "137"
and not batch_id < 137.
So the query was running forever and scanning all batches from the test user.
I also was missing a tag annotation on the queries, but that was not causing the timeout.
> [batch] Fix list batches query and test

- ci/ci/ci.py
- ci/ci/templates/batch.html
- ci/ci/templates/filtered-jobs.html
- ci/ci/templates/pr.html
Currently, when the user views the jobs for a CI pipeline, either on the `pr.html` page or the `batch.html` page, they are displayed all together in a big table, like so:
This change filters the jobs out into smaller tables, with any failed jobs displayed first, followed by any jobs that are currently running, then any pending jobs, then the rest.
Example with failed job:
Example with running/pending jobs:
> [ci/ui] filters jobs by status

- hail/python/hailtop/fs/router_fs.py
Qin He reported that listing a folder containing around 50k files took 1h15. This new code takes ~16 seconds which is about how long it takes `gcloud storage ls`.
There are two improvements:
1. Use `bounded_gather2`. The use of a semaphore in `bounded_gather2`, which is missing from `bounded_gather`, allows it to be used recursively. In particular, suppose we had a semaphore of
50. The outer `bounded_gather2` might need 20 slots to run its 20 paths in parallel. That leaves 30 slots of parallelism left over for its children. By passing the semaphore down, we let our children optimistically use some of that excess parallelism.
2. If we happen to have the `StatResult` for a particular object, we should never again look it up. In particular, getting the `StatResult` for every file in a …
> [hailtop.fs] use parallelism to list directories

- hail/python/hailtop/batch/backend.py
`hailtop.batch.ServiceBackend` uses `get_user_config().get` to read the `HAIL_BATCH_REGIONS` environment variable, when it should use `configuration_of`. This change fixes that.
> [batch] reads `HAIL_BATCH_REGIONS` environment variable correctly

- batch/batch/driver/main.py
- batch/batch/driver/templates/index.html
- batch/sql/add-feature-flags.sql
- batch/sql/add-feature-switches.sql
- batch/sql/delete-batch-tables.sql
- batch/sql/estimated-current.sql
- build.yaml
Let me know if you think this is good and whether I need to test the UI with dev deploy.
> [batch] Add feature switches

- hail/python/test/hail/methods/test_pca.py
Replaces https://github.com/hail-is/hail/pull/13260.
- `test_spectral_moments` times out in a PR: (QoB) https://hail.zulipchat.com/#narrow/stream/127527-team/topic/timeouts/near/376698259, (spark) https://ci.hail.is/batches/7653376/jobs/74, (spark) https://ci.hail.is/batches/7653376/jobs/72, (spark) https://ci.hail.is/batches/7653376/jobs/62
I also backed local off to 4m even though it has no evidence of time outs. Seems simpler for Spark and local to be the same.
> [query] back off spectral moments timeout for local, spark, and batch

- batch/sql/increase_test_max_idle_time.py
- build.yaml
I observed a cluster with it set to the default idle time of 30 seconds in Azure and the workers were continuously thrashing leading up to 49 instances being created over the course of a PR. With an idle time of 120 seconds, there was no thrashing and 28 instances were created over the course of the PR (16 standard + job private etc.). The cluster nicely scaled down at the end of the PR. It looked like a couple of times the `standard-np` pool scaled up and then scaled down so I assume the `standard` pool wasn't at full capacity while that was happening. It might be worth configuring the `standard-np` pool to be 4 or 5 standing instances with 16 cores and see what happens -- that might help as well.
> [batch] Increase max worker idle time to 2 mins in test and dev

- hail/python/test/hail/methods/test_impex.py
- hail/src/main/scala/is/hail/rvd/RVD.scala
On the current release (0.2.119), `is.hail.rvd.RVD.localSort` attempts to serialize an entire `is.hail.rvd.RVD` object when called, which causes some operations, like reading a set of VCF files, to fail. That particular operation no longer fails due to some combination of the changes made to reading VCF files in https://github.com/hail-is/hail/pull/13206 and https://github.com/hail-is/hail/pull/13229, but the serialization could still cause issues if `is.hail.rvd.RVD.localSort` is called in another context. 
See https://hail.zulipchat.com/#narrow/stream/123011-Hail-Query-Dev/topic/Possible.20bug.20in.20Hail.200.2E2.2E119/near/378610151 for more information.
> [query] removes unnecessary serialization in is.hail.rvd.RVD.localSort

- auth/auth/auth.py
- batch/batch/batch.py
- batch/batch/driver/billing_manager.py
- batch/batch/driver/instance.py
- batch/batch/driver/main.py
- batch/batch/front_end/front_end.py
- ci/bootstrap_create_accounts.py
- gear/gear/database.py
- monitoring/monitoring/monitoring.py
- pylintrc
Adding this signature appeases `pyright` in my editor. Unfortunately, `pylint` still [gets confused](https://github.com/pylint-dev/pylint/issues/259) so I disabled this particular check. I made sure that `mypy` still errors when forgetting to provide a required parameter to a function call.
> [gear] Add typing to the transaction decorator

- hail/python/hail/docs/cloud/query_on_batch.rst
The config flag batch/tmp_dir is now batch/remote_tmpdir
> update query on batch tmp config flag

- config.mk
The values of the global config are the same across namespaces, but it does feel more correct to use the `global-config` from the namespace you're targeting than the one in production. This should also enable `make` deploying into a dev namespace without having any permissions for `default`.
> [k8s] Dont require access to default secrets when make deploying

- devbin/rotate_keys.py
A job running for five days *could* cause an issue here, so the operator should still be cognizant of that. The
move to access tokens will eliminate that concern anyway.
We should not consider system-managed keys because those are managed by Google and not even visible in the
UI. We are not obligated to rotate them (nor are we able, afaik).
There are two special secrets which do not conform to the `key.json` naming scheme for their
secret files. I added them as special cases.
> [security] delete after 5 days, ignore system managed, consider two special secrets

- hail/python/hailtop/aiocloud/aioazure/fs.py
- hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
I hope this helps. The regular `timeout` parameter on the Python methods like `stage_block` is for the server-side timeout of the operation. We want the client side timeout to be shorter. I picked 5 seconds, but that was arbitrary. I'm not sure I implemented the Scala code correctly, but that's along the right lines of what needs to happen.
> [azure] Add connection timeouts for Azure FS in both Python and Scala

- build.yaml
For added context see: https://github.com/hail-is/hail/issues/13351
cc: @patrick-schultz @chrisvittal @daniel-goldstein @ehigham @iris-garden 
I actually don't think we need to notify anyone because we'll still get errors if something goes wrong in default. If main starts failing, we have the slightly annoying situation of needing to run tests in a one-off manner to verify and we might need to block a release until we can revert.
> [qob] disable QoB PR tests (keep deploy and dev)

- hail/python/hail/utils/hadoop_utils.py
the local_path_uri function simply prepends 'file://' to the path provided. This leads to an odd situation were a relative path is transformed into 'file://relative/path/to/log', which parses as:
SCHEME: file
HOST  : relative
PATH  : path/to/log
To fix this, compute the real path of the log file and use that as the path for the local_path_uri
> [query] Fix copy_log when log path is relative.

- auth/auth/auth.py
- batch/batch/driver/main.py
- batch/batch/front_end/front_end.py
- ci/ci/ci.py
- gear/gear/__init__.py
- gear/gear/auth.py
- gear/gear/auth_utils.py
- web_common/web_common/web_common.py
Post-vacation brain is mushy so I squashed some poor typing that my nvim lsp has been mad at me about for ages. Specifically, added sufficient type signatures to our aiohttp handler decorators, removed some unnecessary pylint ignore directives, and added a bit of typing to the `userdata` dict. There should be no changes in functionality.
> [lint] Add aiohttp handler types and remove some pylint disable directives

- build.yaml
- ci/test/resources/build.yaml
- hail/src/main/scala/is/hail/services/DeployConfig.scala
Since #13211, all jobs by default have a deploy config mounted into the container. The `worker-deploy-config` secret is no longer necessary, so long as we properly configure the namespace that CI jobs need to talk to.
> [ci] Remove unnecessary worker-deploy-config secret

- hail/python/test/hail/utils/test_hl_hadoop_and_hail_fs.py
See https://github.com/hail-is/hail/issues/13361 for details. Something goes wrong when cleaning up after this test.
> [fs] add debugging information to flaky test_hadoop_methods_3

- hail/python/hail/methods/impex.py
- hail/python/test/hail/vds/test_combiner.py
PGT is a call field by default for import_vcf, the now former import_gvcfs (old combiner start point). Make import_gvcf_interval also treat PGT as a call field.
> [query/combiner] Fix import_gvcf_interval's default PGT handling

- hail/python/test/hail/extract_intervals/test_key_prefix.py
- hail/src/main/scala/is/hail/expr/ir/ExtractIntervalFilters.scala
E.g. when the row key, and/or the row itself, in a predicate is hidden behind Refs, MakeStructs, SelectFields. For example, before matching the first key field "kf" only worked for exactly `GetField(Ref("row", ...), "kf")`. Now the following all work (meaning the analysis recognizes these all as being the first key field):
```
Let("foo",
SelectFields(Ref("row"), [..., "kf", ...]),
GetField(Ref("foo"), "kf"))
Let("foo",
Ref("row"),
Let("bar",
MakeStruct("baz" -> GetField(Ref("foo"), "kf"), ...)
GetField(Ref("bar"), "baz")))
```
Edit:
A note on how serious the issue was in practice: Any filter that uses more than one field (or the same field twice) was broken, where broken means it does no interval filter and reads all the data. E.g. `ht.filter((ht.locus >= hl.locus('20', 1)) & (ht.locus < …
> [query] allow inteval filters to work with indirect row key

- auth/auth/auth.py
Came across this while doing #13307. The `AuthClient` decorators are used by services like Batch and CI to protect endpoints behind an authentication/authorization check. Those decorators might make a network request to the auth service to see who the user is and whether they're a developer. I realized that these decorators are also used to protect some endpoints on the auth service too, which albeit uniform felt silly to me (make a network request back to yourself instead of just making a function call). Creating new decorators to use within the auth service is a bit more code, but I personally think it's a much easier code path to follow.
Only the last commit is this PR, as it's stacked.
> [auth] Dont use the auth client for authz in the auth service

- batch/deployment.yaml
`kubectl` commands like `exec` that deal with containers in pods will generally default to the first container in the pod. The `batch-driver` deployment has two containers, the envoy sidecar and the batch-driver python app. Since the `envoy` container is listed first, `kssh` and `sync.py` default to that container, but we basically always intend `batch-driver`. Instead of switching up the order, or adding a bunch of explicit container specification, this annotates `batch-driver` as the default container in the pod, so `kssh` and `sync.py` work with the batch driver.
> [batch] Specify batch-driver as the default container in the batch-driver pod

- dev-docs/creating-a-developer-account.md
As part of the security POAMs, we'll follow up on this with instructions of making operator devs viewers + ability to assign themselves roles. This is just what I did for Sophie to give access just to the dev namespace.
> [devdocs] Add instructions on giving a dev admin access to their dev namespace

- build.yaml
- hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
I think this change will help the number of operations we're making substantially. My Scala skills are not great, so I don't know if this is written correctly.
Basically, we were making a call to list the blobs recursively to test if the path was a directory which was streaming through the first 5000 records. I made the page size equal to 1 record as we don't care about all records. The next thing I did was to just get the blob properties rather than calling exists + get blob properties. So that will cut the number of HTTP calls by half for every blob. Lastly, listing items in a directory which is used for globbing was making a call to get the metadata for each file and then it was making the 3 API calls above to check whether it's a directory, whether it exists, and what the blob …
> [azure] Optimize file status operations

- auth/auth/auth.py
- build.yaml
- ci/ci/ci.py
- ci/ci/github.py
- ci/test/resources/build.yaml
I broke my previous PR into littler pieces some of which has already merged. This PR adds developers from production to test namespaces (only programmatic access, browser OAuth flow does not work yet for test namespaces) and makes it easier to add developers to dev namespaces.
> [ci] Add easier way to add all production developers to a dev namespace

- hail/python/hail/vds/combiner/combine.py
- hail/python/hail/vds/combiner/variant_dataset_combiner.py
- hail/python/test/hail/vds/test_combiner.py
Add the call_fields argument.
Much like refrence entries, when passing a VDS to the combiner, we check it's call fields to ensure that there is a match between the passed argument and the VDS's call fields.
> [vds/combiner] Teach VDS combiner how to handle custom call fields

- batch/batch/spec_writer.py
Before open batches, the `n_jobs` of a batch was a constant known before any jobs were added. Moreover, we did not start scheduling jobs until all the jobs were added to the database. Therefore, it was always safe to assume that the final "bunch" of jobs in the database was the last "bunch" ergo it spanned from its `start_job_id` to the job with id `n_jobs` (nb: job ids are 1-indexed).
When open batches were added, the `n_jobs` became a mutable value. Moreover, `n_jobs` includes jobs in bunches *which have not yet been added to the database*. In particular, suppose two clients are each submitting a bunch of size 10. Each client independently "reserves" 10 job slots by atomically incrementing `n_jobs` by ten. `n_jobs` is now 20. Further suppose that the first bunch is added to the database …
> [batch] Mitigate siwei bug by removing cache

- hail/python/hailtop/config/user_config.py
- hail/python/test/hailtop/hailctl/config/conftest.py
- hail/python/test/hailtop/hailctl/config/test_cli.py
- hail/scripts/test_requester_pays_parsing.py
This is pretty bare bones but I thought this might help a lot with the testing of all your upcoming `hailctl config` changes rather than having to manually test various possible combinations.
Run by just invoking pytest: `pytest hail/python/test/hailtop/hailctl/config`
> [hailctl] Add basic tests for hailctl config

- batch/batch/worker/worker.py
A mitigation, but not resolution, for #13402, this errors a job after 10 seconds of waiting on a network namespace, as it should never take that long to create one.
> [batch] Dont wait on a network namespace forever

- batch/utils/stress.py
- hail/python/hailtop/batch/batch.py
- hail/python/hailtop/batch/job.py
- hail/python/test/hailtop/batch/test_batch.py
Folks need this when preemption rates are too high for their jobs.
cc: @daniel-goldstein
> [batch] expose Job.spot

- build.yaml
`ci-agent` is the actual cluster admin service account that CI can use for batch jobs. `ci-admin` does not exist.
> [ci] Use ci-agent not ci-admin for cron

- batch/batch/driver/main.py
For example, see error messages when batch-driver shuts down: https://cloudlogging.app.goo.gl/kKgJdv34s3a6Vd8n6.
> [batch] ignore aiomysql warnings about batch.billing_projects.name

- build.yaml
Alright! I stopped being lazy and actually tested all this.
I copied the code from the step into a file and removed the left-hand indentation. I called that file `/tmp/foo.sh`. I ran this:
```
python3 ~/projects/hail/ci/jinja2_render.py '{"code":{"developers":[{"username":"cchurch"},{"username":"dking"},{"username":"jigold"},{"username":"dgoldste"}, {"username":"irademac"},{"username":"parsa"},{"username":"test-dev"},{"username":"cseed"},{"username":"cvittal"},{"username":"ehigham"},{"username":"gsmith"},{"username":"jwander"},{"username":"nwatts"},{"username":"pschultz"}]}}' \
/tmp/foo.sh \
/tmp/foo.sh.out
sh /tmp/foo.sh.out
```
And it correctly skipped test-dev entirely, it printed "Skipping cchurch because they have no namespace." and it created the appropriate cronjobs for everyone …
> [build.yaml] finally fix up the namespace autoscaler

- hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py
- hail/python/test/hailtop/test_aiogoogle.py
This code was broken if the URL only had a bucket name like `gs://foo`. It truncated the last character of the bucket because the `find` operation returned -1 for not being able to find another `/` in the URL after `gs://`.
> [aiogoogle] Fix bucket name parsing

- auth/auth/auth.py
- batch/batch/driver/main.py
- batch/batch/front_end/front_end.py
- ci/ci/ci.py
- gear/gear/auth.py
- hail/python/hailtop/config/deploy_config.py
- notebook/notebook/notebook.py
Returning HTTP status objects that subclass `Exception` [is deprecated](https://docs.aiohttp.org/en/stable/web_quickstart.html#exceptions) and will at some point block an upgrade to a higher version of aiohttp.
> [batch] Raise instead of returning aiohttp objects that subclass Exception

- hail/python/test/hail/table/test_table.py
- hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
fixes #13407
CHANGELOG: Resolves #13407 in which uses of `union_rows` could reduce parallelism to one partition resulting in severely degraded performance.
TableUnion was always collapsing to a single partition when the key was empty. This adds a special case handling, which just concatenates partitions.
The body of the resulting TableStage is a little hacky: it does a StreamMultiMerge, but where exactly one input stream is non-empty. I think that should have fine performance, and I didn’t see any simpler ways to do it.
> [compiler] fix TableUnion lowering

- build.yaml
GCP k8s crons are in UTC apparently. We could instead specify a timezone here, LMK which you prefer.
> [ci] Make dev namespace scaling cron in UTC

- hail/python/hail/ir/ir.py
- hail/python/hail/matrixtable.py
- hail/python/test/hail/matrixtable/test_matrix_table.py
CHANGELOG: MatrixTable.aggregate_cols no longer forces a distributed computation. This should be what you want in the majority of cases. In case you know the aggregation is very slow and should be parallelized, use mt.cols().aggregate instead.
Most of the time, `aggregate_cols` will be much faster performing the aggregation locally. Currently, we generate a `TableAggregate` over a `TableParallelize` of the columns. We shouldn't try to optimize that to a local computation during compilation; `TableParallelize` should express the intent that the computation is expensive and really should be parallelized. This should be considered part of the semantics the compiler must preserve.
This PR changes `aggregate_cols` to explicitly generate a local computation using `StreamAgg` (which was only …
> [query] force `aggregate_cols` to be local

- hail/python/hailtop/config/user_config.py
- hail/python/test/hailtop/hailctl/config/conftest.py
- hail/python/test/hailtop/hailctl/config/test_cli.py
Sorry missed this in the initial PR. `os.environ` is global to the whole python session so setting it directly could inadvertently affect the environment for unrelated tests. There seems to be safe ways to do this using `monkeypatch` and whatever `CliRunner` is doing, but I decided just not to set it.
> [hailctl] Dont change the current python environment in test fixture

- hail/python/hailtop/hailctl/batch/cli.py
- hail/python/hailtop/hailctl/dataproc/cli.py
- hail/python/hailtop/hailctl/hdinsight/cli.py
CHANGELOG: Resolves #13446. In all three submit commands (batch, dataproc, and hdinsight), Hail now allows and encourages the use of -- to separate arguments meant for the user script from those meant for hailctl. In hailctl batch submit, option-like arguments, for example "--foo", are now supported before "--" if and only if they do not conflict with a hailctl option.
> [hailctl] clarify suggested use of -- and allow it in hailctl batch submit

- hail/testng.xml
TestNG (appears to) allocates every class in the classpath matching the package glob. I assume this is to check if any of these are `instanceof` `TestNGSuite`.
The Azure SDK depends on `rector-netty-core` which includes some classes which reference interfaces *not included in its required dependencies*. These classes are meant to be used only when those optional dependencies are present. They should not be willy-nilly allocated, but, of course, we told TestNG to go willy-nilly allocating everything.
> [query] fix ./gradlew test

- batch/test/test_accounts.py
- batch/test/test_aioclient.py
- batch/test/test_batch.py
- batch/test/test_dag.py
- batch/test/test_scale.py
- batch/test/utils.py
- ci/ci/github.py
- hail/python/hail/backend/service_backend.py
- hail/python/hail/methods/qc.py
- hail/python/hailtop/batch/backend.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/batch_client/client.py
- hail/python/test/hailtop/batch/test_batch.py
This PR refactors the aioclient to merge the functionality of Batch and BatchBuilder into just a single Batch object. The reason for making this change is to make adding job groups simpler. I will follow up with a change to Jobs after this merges. I apologize for the number of line changes. Most are just renaming `bb -> b` in the tests.
> [batch_client.aioclient] Get rid of BatchBuilder

- batch/batch/worker/worker.py
- dev-docs/batch-container-design.md
In the world of low-level container runtimes there exists the term "bundle", which basically means the pair of a root filesystem and a `config.json` file containing all of the other necessary information to run the container. If you invoke `crun` or `runc` with `--bundle /path/to/bundle`, the runtime assumes the following:
- The configuration file for the container is located at `/path/to/bundle/config.json`
- That `config.json` contains a field [`root.path`](https://github.com/opencontainers/runtime-spec/blob/main/config.md#root) that specifies the location of the root filesystem, most commonly as a path relative to `/path/to/bundle`.
`crun` offers a way to explicitly reference the location of `config.json` through its `--config` flag. This seems fairly innocuous, but specifying a custom …
> [batch] Move config.json into the container bundle

- ci/ci/ci.py
- ci/ci/github.py
- ci/ci/templates/batch.html
- ci/ci/templates/filtered-jobs.html
- ci/ci/templates/pr.html
This change sorts the jobs for a PR correctly in the UI, so that all jobs are placed under a header with the correct state (see screenshot). Because jobs are split into separate tables by their state, `focusOnSlash` has been removed from the relevant CI pages, since it is unknown which tables will exist on the page until it is rendered. It also fixes the error that was causing the server to return a 500 when there were no jobs yet (e.g. when a retry had just been requested), which was caused by an assumption in the original job filtering code that there would always be at least one job to display. It also passes the list of developers through to the underlying `PR` object that a `WatchedBranch` has, which was missed in https://github.com/hail-is/hail/pull/13398 but is required for CI to …
> [ci/ui] fixes 500 when there are no jobs to display

- hail/python/hailtop/hail_frozenlist.py
CHANGELOG: Hail `frozenlist` now has an eval-able `repr`.
`hailtop.hail_frozenlist.frozenlist` previously inherited the `repr` of the `frozenlist` library:
> frozenlist([1, 2, 3])
<FrozenList(frozen=True, [1, 2, 3])>
With this change, I both use the fact that `frozen=True` for Hail frozenlists and use a printed form that is actually eval-able:
> frozenlist([1, 2, 3])
frozenlist([1, 2, 3])
> eval(repr(frozenlist([1, 2, 3])))
frozenlist([1, 2, 3])
> [query] frozenlist.__repr__ should be eval-able

- hail/python/test/hail/vds/test_vds_functions.py
- hail/src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala
Make sure that all local alleles are less than the n_total_alleles parameter passed to the function.
This error will often occur if a vds is split with regular split_multi rather than vds.split_multi
Closes #13479
> [query] Add bounds checks to local_to_global

- batch/batch/driver/__main__.py
We get a lot of spurious Grafana alerts because batch-driver has unclosed `aiohttp.ClientSession` objects. `aiohttp` can [report the creation location](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L242-L247), but only when aysncio is in debug mode.
I am hesitant to enable debug mode because I suspect it will slow down everything by grabbing stack traces for every coroutine (so that it can report an error later).
I adapted the code from the linked asyncio code and tested it as follows:
```
In [1]: import aiohttp
...: import traceback
...: import sys
...:
...: oldinit = aiohttp.ClientSession.__init__
...: def newinit(self, *args, **kwargs):
...:      oldinit(self, *args, **kwargs)
...:      self._source_traceback: Optional[
...:                 traceback.StackSummary …
```
> [batch] report unclosed ClientSession alloc location in batch-driver

- .github/ISSUE_TEMPLATE/bug-report.yml
I also suggested gist.github.com for large logs.
This will allow us to quickly see new issues from users. We might want other forms / to generalize this form if we want support requests to go to GitHub too.
cc: @jigold
> [github] apply needs-triage label to each bug report

- hail/src/main/scala/is/hail/io/bgen/StagedBGENReader.scala
- hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
- hail/src/main/scala/is/hail/io/fs/FS.scala
- hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
- hail/src/main/scala/is/hail/io/fs/HadoopFS.scala
- hail/src/main/scala/is/hail/io/fs/RouterFS.scala
- hail/src/test/scala/is/hail/fs/FSSuite.scala
This was added in https://github.com/hail-is/hail/pull/12421 to help debug errors in `testSeekMoreThanMaxInt`. We have not seen that transient error in a while and I think the switch to https://github.com/hail-is/hail/pull/12590 might have fixed some underlying misuse of `AppendBlobClient` (by not using it).
> [fs] remove Azure _debug parameters

- hail/python/hailtop/batch/docs/advanced_search_help.rst
I presume this was meant to be normal double quotes.
> [batch] remove use of smart quotes in docs

- hail/python/hailtop/batch/docs/advanced_search_help.rst
Captions render haphazardly, at least on my browser.
> [batch] use headings instead of captions

- hail/python/hail/__init__.py
- hail/python/hail/experimental/function.py
- hail/python/hail/expr/expressions/base_expression.py
- hail/python/hail/ir/ir.py
- hail/python/hail/table.py
- hail/python/hail/typecheck/check.py
- hail/python/hailtop/hail_decorator.py
- hail/python/test/hail/helpers.py
Without these changes, my IDE cannot deduce that the return value of, say, `select` is a `Table` which prevents jump-to-definition on subsequent method calls.
I also received an error about `Table.collect` returning an `ArrayExpression` which it will only do when `_localize=False`. `overload` teaches this fact to the type system.
I didn't use the specific expression in `base_expression.py` because that would require an import circularity.
> [query] improve type hinting for tables

- auth/auth/auth.py
I must have broken this during a recent refactor of the decorators. When making requests to an internal namespace, the default namespace's auth token is set in the `X-Hail-Internal-Authorization` header and the dev namespace's token is in the `Authorization` header. The dev namespace needs to know *not* to pick up the `X-Hail-Internal-Authorization` header.
> [auth] Fix the auth rest API for developers

- batch/batch/cloud/gcp/driver/create_instance.py
- batch/batch/worker/worker.py
In a previous PR we added exception logging when tasks on a `BackgroundTaskManager` fail. I'm not seeing any of those messages in the worker logs, suggesting that for some reason the Tasks to free a network namespace when a job is finished are not getting created in the first place. I don't see how in the code we could somehow *not* free the network namespace, but I'm hoping that some of these diagnostics shed some light. Also open to suggestions for where else might be a good spot to add more logging.
> [batch] More debugging information for network namespace errors

- batch/batch/cloud/azure/driver/create_instance.py
- batch/batch/cloud/gcp/driver/create_instance.py
Super tiny quality of life change, so one can `docker exec worker …` instead of copy/pasting the container id
> [batch] Name the batch worker container

- batch/batch/front_end/templates/table_search.html
Without this my browser keeps trying to put periods everywhere.
> [batch] treat search field as plaintext: no spellcheck, no autocorrect

- hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
- hail/src/main/scala/is/hail/backend/service/Worker.scala
This will ensure proper freeing of resources, no matter what.
> [query] All non-spark task context use in using blocks

- hail/python/hail/utils/struct.py
- hail/python/test/hail/utils/test_pickle.py
CHANGELOG: `hl.Struct` is now pickle-able.
> [query] fix pickling of hl.Struct

- batch/batch/batch.py
- batch/batch/driver/job.py
- batch/batch/front_end/front_end.py
- batch/batch/front_end/query/query_v1.py
- batch/batch/front_end/query/query_v2.py
- batch/batch/front_end/templates/batch.html
- batch/batch/front_end/templates/job.html
- batch/test/test_dag.py
- hail/python/hailtop/utils/utils.py
> [batch] Show cost breakdown in the UI

- docker/hailgenetics/mirror_images.sh
This inspect command prevents us from updating a tag, for example, if we need to replace an image with a security problem or if there is a bug like the one fixed by https://github.com/hail-is/hail/pull/13536.
> [docker] copy even if the tag already exists

- batch/batch/cloud/gcp/instance_config.py
I am having trouble determining the effect of this mistake, but it seems like we would be substantially undercharging for the serivce fee if it was really being charged by worker_fraction_in_1024ths instead of core-hours.
> [batch] fix misnamed resources

- hail/python/test/hail/table/test_table.py
- hail/src/main/scala/is/hail/utils/package.scala
Not a correctness bug because we raise an assertion error in the partition function.
> [query] avoid signed integer overlow in partition function

- hail/src/main/scala/is/hail/lir/PST.scala
- hail/src/main/scala/is/hail/lir/SplitMethod.scala
Remove the code computing loop regions in lir. They aren't currently being used, and the recursive function is causing stack overflows.
> [compiler, lir] don’t compute unused loop regions

- hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh37.sh
- hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh38.sh
This appers to have been lost in #8268. There is no explicit mention of it and it was inconsistently removed (e.g. loftee in GRCh38 still has the `&`). I assume it was a mistake.
> [dataproc] restore parallel fetching of resources

- build.yaml
- hail/python/hail/docs/change_log.md
- hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh37.sh
- hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh38.sh
Consider, for example, this deploy: https://ci.hail.is/batches/7956812. `test-dataproc-37` succeeded but `test-dataproc-38` failed (it timed out b/c the master failed to come online).
You can see the error logs for the cluster here: https://cloudlogging.app.goo.gl/t1ux8oqy11Ba2dih7
It states a certain file either did not exist or we did not have permission to access it.
[`test_dataproc-37`](https://batch.hail.is/batches/7956812/jobs/193) and [`test_dataproc-38`](https://batch.hail.is/batches/7956812/jobs/194) started around the same time and both uploaded four files into:
gs://hail-30-day/hailctl/dataproc/ci_test_dataproc/0.2.121-7343e9c368dc/
And then set it to public read/write. The public read/write means that permissions are not the issue.
Instead, the issue is that there must be some …
> [test-dataproc] make test-dataproc-37 and -38 not race

- build.yaml
All this `HAIL_AZURE_OAUTH_SCOPE` and `HAIL_IDENTITY_PROVIDER_JSON` are now injected by batch workers by default so we don't need to specify them explicitly in `build.yaml`.
Unrelatedly, I don't think `create_dummy_oauth2_client_secret` does anything as `auth-oauth2-client-secret` already exists inside new namespaces.
> [ci] Clean up temporary config for OAuth changes

- hail/python/dev/pinned-requirements.txt
- hail/python/pinned-requirements.txt
- hail/python/requirements.txt
Supersedes https://github.com/hail-is/hail/pull/13228 . Resolves [CVE-2023-25399](https://nvd.nist.gov/vuln/detail/CVE-2023-25399).
> [security] update scipy pin to 1.11.1

- hail/python/hail/expr/aggregators/aggregators.py
- hail/python/hail/expr/expressions/typed_expressions.py
- hail/python/hail/expr/functions.py
- hail/python/test/hail/expr/test_expr.py
In particular, struct field names which clash with methods on `StructExpression`.
close #13495
CHANGELOG: Fix a bug where field names can shadow methods on the StructExpression class, e.g. "items", "keys", "values". Now the only way to access such fields is through the getitem syntax, e.g. "some_struct['items']". It's possible this could break existing code that uses such field names.
> [query] fix shadowing of field names by methods

- ci/ci/ci.py
#13331 moved the initialization of the `WatchedBranch`s out of the top level in `ci.py` and into the end of `on_startup`. Notice that this new location is both after `app['task_manager'].ensure_future(update_loop(app))` is run *and* after an `await`-point. It's quite likely that the first time `update_loop` is run is *before* there are any watched branches. This loop then sleeps for five minutes before it runs again. I believe this is why sometimes on startup it can take multiple minutes before CI loads PR information.
> [ci] Start update loop after watched branches are initialized

- hail/src/main/scala/is/hail/expr/ir/Emit.scala
> [query] unswap print_(ir / inputs)_on_worker flags

- hail/python/hail/fs/hadoop_fs.py
- hail/python/hailtop/fs/fs.py
- hail/python/hailtop/fs/fs_utils.py
- hail/python/hailtop/fs/router_fs.py
- hail/python/hailtop/fs/stat_result.py
- hail/src/main/scala/is/hail/expr/ir/GenericLines.scala
- hail/src/main/scala/is/hail/expr/ir/StringTableReader.scala
- hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala
- hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
- hail/src/main/scala/is/hail/io/fs/FS.scala
- hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
- hail/src/main/scala/is/hail/io/fs/HadoopFS.scala
- hail/src/main/scala/is/hail/io/fs/RouterFS.scala
- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
- hail/src/main/scala/is/hail/methods/MatrixExportEntriesByCol.scala
- hail/src/main/scala/is/hail/utils/Py4jUtils.scala
- hail/src/main/scala/is/hail/variant/ReferenceGenome.scala
- hail/src/test/scala/is/hail/fs/FSSuite.scala
- hail/src/test/scala/is/hail/io/compress/BGzipCodecSuite.scala
- hail/src/test/scala/is/hail/utils/UtilsSuite.scala
In our asyncio FSes, we use the term FileListEntry for the package of information you receive from a cloud object store list operation. We reserve the term FileStatus for the metadata you get about a blob without a list operation. A major difference is that FLEs know if they refer to files or folders. In contrast, a FileStatus knows that it is a file *but does not know if a directory with the same name exists*.
> [fs] consistent use of the term FileListEntry

- hail/python/hail/ggplot/utils.py
CHANGELOG: Fixed a bug in `hail.ggplot.scale_color_continuous` that sometimes caused errors by generating invalid colors.
For example, this code:
```python
from hail.ggplot import ggplot, aes, geom_point
t = hl.utils.range_table(10)
t = t.annotate(x=hl.rand_unif(), y=hl.rand_unif(), z=hl.rand_unif(1, 10))
fig = ggplot(t, aes(x=t.x, y=t.y, color=t.z)) + geom_point()
fig.show()
```
Produces an error like this:
```
ValueError:
Invalid element(s) received for the 'color' property of scatter.marker
Invalid elements include: ['rgb(-84, -187, 123)', 'rgb(-116, -227, 131)', 'rgb(-29, -120, 109)', 'rgb(-33, -125, 110)', 'rgb(15, -65, 97)', 'rgb(10, -71, 99)', 'rgb(-112, -223, 130)', 'rgb(-63, -162, 117)', 'rgb(-81, -185, 122)', 'rgb(31, -45, 93)']
```
But after this change is …
> [query/ggplot] fixes math for continuous color scales

- hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py
We retry the request method in `hailtop.aiocloud.common.session.Session` but that does us no good when we read the body with `.json`.
Seen here: https://batch.hail.is/batches/7973546/jobs/157
> [query] retry page iterator get requests

- hail/python/hailtop/auth/auth.py
- hail/python/hailtop/auth/flow.py
Tested the following in GCP and Azure:
1. `hailctl auth login` on the current release (pre-OAuth2) and `hailctl auth logout` on `main`
2. Both login/logout on `main`.
> [hailctl] Update hailctl auth logout to support OAuth2 credentials

- auth/deployment.yaml
- batch/batch/cloud/azure/driver/driver.py
- batch/batch/cloud/driver.py
- batch/batch/cloud/gcp/driver/billing_manager.py
- batch/batch/cloud/gcp/driver/driver.py
- batch/batch/driver/main.py
- batch/deployment.yaml
- build.yaml
- ci/bootstrap_create_accounts.py
- datasets/extract/extract_CADD.py
- datasets/extract/extract_dbSNP.py
- gear/gear/clients.py
- hail/python/hailtop/aiocloud/aiogoogle/credentials.py
- hail/python/hailtop/batch/docs/service.rst
This is mostly cleanup reducing the amount of the codebase that depends on GSA key files (which are not available in terra or a future keyless hail-vdc). The core bit is instead of threading `credentials_file="/gsa-key/key.json` through the batch and auth codebase we set `GOOGLE_APPLICATION_CREDENTIALS` in their deployments. I can't think of a scenario where `auth` or `batch` would need to use multiple identities so better to remove their ability to do so and always use the default credentials.
I also did a bit of tidying up, using `$GOOGLE_APPLICATION_CREDENTIALS` instead of the hard-coded path and removing the credentials endpoints on the batch-driver which have been unused by workers for many months now.
> [auth|batch|aiogoogle] Favor latent credentials over specifying /gsa-key/key.json in application code

- infra/gcp/main.tf
`hail_test_gcs_bucket` is an instantiation of a `gcs_bucket` module not a `google_storage_bucket` resource.
> [infra] Fix bad reference to test bucket module in GCP terraform

- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
CHANGELOG: On some pipelines, since at least 0.2.58 (commit 23813afd5b), Hail could use essentially unbounded amounts of memory. This change removes "optimization" rules that accidentally caused that.
Closes #13606
> [query] eliminate optimization that can blow RAM

- ci/deployment.yaml
I accidentally copy pasted the line. If you look a few lines down you can see the actual name/value pair for that environment variable.
> [ci] Fix errant line in environment variable spec

- hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
CHANGELOG: fix a bug which caused jobs with a large number of partitions (close to 100k) to run out of memory on the driver after all partitions finish.
Cap number of threads allocated when reading results of a cda on the driver.
~Still waiting on a test to confirm this fixes the bad scaling with number of partitions.~
We were reading cda results with a threadpool containing one thread per partition, but kept all but 1000 threads blocked. This changes to use a threadpool of 1000 threads.
We still use a surprising amount of memory when reading results, but this change will likely allow jobs with ~100k partitions to complete.
fixes #13533
> [qob] don’t use unbounded threads reading results

- build.yaml
- hail/python/hail/docs/tutorials/08-plotting.ipynb
- hail/python/hail/docs/tutorials/09-ggplot.ipynb
- hail/python/hail/ggplot/__init__.py
- hail/python/hail/plot/__init__.py
- hail/python/hailtop/__init__.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/utils/rich_progress_bar.py
CHANGELOG: Additional setup is no longer required when using `hail.plot` or `hail.ggplot` in a Jupyter notebook (calling `bokeh.io.output_notebook` or `hail.plot.output_notebook` and/or setting `plotly.io.renderers.default = 'iframe'` is no longer necessary).
I double-checked locally that `import hail as hl` and `from hail.ggplot import ggplot` both cause the added code to run, and that running them in a notebook does the setup we expect it to, but running it in iPython or the Python interpreter does not.
> [query/ggplot] runs plotting notebook setup on import

- .gitignore
- hail/Makefile
- hail/build.gradle
- hail/python/hail/backend/backend.py
- hail/python/hail/backend/local_backend.py
- hail/python/hail/backend/spark_backend.py
- hail/python/hail/context.py
- hail/python/hail/experimental/compile.py
- hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
Apparently, creating a zip file of all our dependencies and the Hail code takes ~30s. This change skips the shadow JAR for local development. We still need a shadow JAR to produce a shareable wheel file; however, when doing local development, we can simply tell Py4J (and the JVM) where to find our dependencies class files.
Also notice that I made install-editable non-PHONY. It need not be PHONY as long as we can reliably determine if `hail/python` is the pip-installed version. To do so, we simply check if the `__init__.py` at the root of the pip package is newer than when we last installed. If its newer, then either:
1. We edited `__init__.py`, or
2. The pip location of Hail has changed since we last ran install-editable
I also deleted eggs because nobody uses eggs.
> [query] non-shadow-jar for pytest, doctest, and install-editable

- batch/batch/driver/main.py
- batch/batch/front_end/front_end.py
- batch/batch/utils.py
- batch/deployment.yaml
- batch/sql/estimated-current.sql
- ci/bootstrap_create_accounts.py
In the spirit of getting everyone talking with the same authentication mechanism. The communication between batch and batch-driver isn't really a big deal, but we are basically storing a password as plaintext with this `internal_token`.
> [batch] Use normal credentials instead of internal_token for communicating between batch and batch-driver

- hail/build.gradle
- hail/gradle/wrapper/gradle-wrapper.properties
It is possible this addresses #12950 for two reasons:
1. In 2.25.0, they rewrote the BlobWriteChannel entirely. [commit](https://github.com/googleapis/java-storage/commit/1b52a1053130620011515060787bada10c324c0b).
2. Also in 2.25.0, after the rewrite, they fixed in issue with tracking offsets after incremental flushes. Maybe the issue existed in the old code too?. [commit](https://github.com/googleapis/java-storage/commit/c099a2f4f8ea9afa6953270876653916b021fd9f).
3. In 2.22.4 they modified the BlobWriteChannel to use a different retry method. [commit](https://github.com/googleapis/java-storage/commit/1b52a1053130620011515060787bada10c324c0b).
Anyway, all circumstantial.
> [query] update to latest google storage APIs

- gear/gear/session.py
Typically, a CSRF attack can occur when `evil.com` tricks a user into requesting a state-changing URL at `batch.hail.is`. We use CSRF tokens to protect against such attacks, but there is an additional defense-in-depth cookie attribute that we can use called [SameSite](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#samesite-cookie-attribute). The possible values for this attribute are:
- None => browser always sends this cookie in cross-site requests
- Strict => browser never sends this cookie in cross-site requests
- Lax => browser only sends this cookie in cross-site requests that use "safe" HTTP methods (GET, HEAD, OPTIONS)
Both Lax and Strict protect against the most primitive forms of CSRF (a form on evil.com submitting a POST to …
> [gear] Set SameSite=Lax on the session cookie

- build.yaml
- docker/hailgenetics/hail/Dockerfile
- hail/python/hailtop/batch/backend.py
- hail/python/hailtop/batch/batch.py
- hail/python/hailtop/batch/batch_pool_executor.py
- hail/python/hailtop/batch/hail_genetics_images.py
- hail/scripts/deploy.sh
- infra/gcp-broad/gcp-ar-cleanup-policy.txt
CHANGELOG: Python jobs in Hail Batch that use the default image now support all supported python versions and include the `hail` python package.
The `-py3.X` tag suffix is copied from dask's DockerHub images. Resolves #13558
> [docker] Build hailgenetics/hail images with all supported python versions

- hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
- hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala
- hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
- hail/src/main/scala/is/hail/io/fs/FS.scala
- hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
- hail/src/main/scala/is/hail/io/fs/HadoopFS.scala
- hail/src/main/scala/is/hail/io/fs/RouterFS.scala
- hail/src/main/scala/is/hail/utils/Py4jUtils.scala
- hail/src/main/scala/is/hail/variant/ReferenceGenome.scala
- hail/src/test/scala/is/hail/io/fs/FSSuite.scala
- hail/src/test/scala/is/hail/io/fs/FakeFS.scala
The "status" in `listStatus` referred to `FileStatus`, a Hadoop abstraction of a Linux `stat` object. In my last PR, I split that concept into `FileStatus` and `FileListEntry` where the former is only for files and the latter is for the contents of a directory (in the latter case, cloud providers usually definitively tell you if a path is an object, an object and a prefix [aka directory], or a prefix).
This method is really about listing (a la `ls`) directories, so I have changed its name to reflect that.
I specifically choose not to name it `ls` or `list` because I do not want it confused with `ls` because `ls` typically supports "listing" a specific file. This method is only for listing the contents of a directory.
> [jvm-fs] rename listStatus to listDirectory

- .gitignore
- hail/python/hail/ggplot/__init__.py
- hail/python/hail/plot/__init__.py
- hail/python/hailtop/__init__.py
- hail/python/hailtop/batch_client/aioclient.py
https://github.com/hail-is/hail/pull/13610 added the setup for bokeh and plotly into `hailtop/__init__.py`, which causes `IPython` to be imported when invoking `hailctl`, adding unnecessary startup time to it (observed between 0.210s and 0.400s). This change moves the setup into the `__init__.py` files for the plotting modules, with the resulting state stored in a global variable in `hailtop/__init__.py`. The plotting setup is still run upon invoking `import hail`, as this imports all submodules of hail as well, but the `IPython` import no longer happens when invoking `hailctl`.
> [query/ggplot] makes plotting setup lazy

- hail/python/test/hail/methods/test_statgen.py
It's cutting it too close and sometimes timing out when jobs land on cold JVMs.
> [query] Give test_ld_prune more time on the batch backend

- ci/ci/ci.py
- hail/python/hailtop/hailctl/__main__.py
- hail/python/hailtop/hailctl/dev/ci_client.py
If you dev deploy right now you'll likely see warnings like this:
```
(hail) dgoldste@wmce3-cb7 hail % hailctl dev deploy -b hail-is/hail:main -s merge_code
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb64d58f1f0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fb64d5a1520>, 1.908669784)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fb64d579040>
Created deploy batch, see https://ci.hail.is/batches/7992015
(hail) dgoldste@wmce3-cb7 hail %
```
`HailCredentials` recently changed such that now they contain resources (GCP or Azure credentials) that require closing, so `hail_credentials()` needs to be used as a context manager or you get those unclosed errors on exit.
> [hailtop] Properly close HailCredentials

- gear/gear/database.py
This is only called once on `Database` creation so I don't think the caching here is used anymore.
> [gear] Dont cache the db ssl context in a global

- hail/scripts/deploy.sh
#13643 just totally mixed up the hailtop and hail 3.11 images. `$HAIL_GENETICS_HAILTOP_IMAGE_PY_3_11` does not exist.
> [deploy] Fix deploy script to correctly push 3.11 image and hailtop image

- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/utils/rich_progress_bar.py
I think this was inadvertantly broken. The `Progress.disable` property needs to be set *before* you start the progress bar, otherwise it has no effect. Clients of all these progress bars should not touch their `Progress` instance, that is an implementation detail. I have changed rich_progress_bar.py to use `_progress` to clearly communicate this.
Unrelatedly, it seems that `add_task` accepts varargs which become arbitrary additional metadata for the task. There is no `disable` keyword, that is just added as additional metadata. Instead, we must use the `visible` keyword to enable/disable the task.
I verified this looks right now:
```python3
In [1]: import hailtop.batch_client.aioclient as ac
...: try:
...:     client = await ac.BatchClient.create('hail')
...:     b = client.create_batch() …
```
> [batch] disable bunch submission progress bar when fewer than 100

- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
Blocks containing only a single `Ref` node weren't being handled correctly, and we were adding empty lines in some cases.
Examples:
sexpr:
```
(Let __iruid_2
(I32 2)
(Let __iruid_1
(I32 1)
(Let __iruid_0
(True)
(If
(Ref __iruid_0)
(ApplyUnaryPrimOp Negate (Ref __iruid_1))
(Ref __iruid_2)))))
```
ssa before:
```
%c2 = I32 [2]
%c1 = I32 [1]
%true = True
If %true then {
ApplyUnaryPrimOp(%c1) [Negate]
} else {
Ref [__iruid_2]
}
```
ssa after:
```
%c2 = I32 [2]
%c1 = I32 [1]
%true = True
If %true then {
ApplyUnaryPrimOp(%c1) [Negate]
} else { %c2 }
```
sexpr:
```
(StreamMap __iruid_3
(StreamRange -1 False (I32 0) (I32 5) (I32 1))
(Ref __iruid_3))
```
ssa before:
```
!c0 = I32 [0] 
!c5 = I32 [5] 
!c1 = I32 [1]
!s = StreamRange(!c0, !c5, !c1) [-1, False]
StreamMap(!s) { (%elt) =>
Ref [__iruid_3] …
```
> [compiler] a couple bugfixes in ssa pretty-printer

- hail/python/hail/expr/functions.py
- hail/python/hail/ggplot/geoms.py
- hail/python/hail/ggplot/stats.py
- hail/python/hail/plot/plots.py
… and make the default
Examples
Histogram without setting min/max. Requires two passes over data, has low resolution over interesting part of the distribution:
Histogram with manual min/max. Most accurate, but different choices of number of bins cause different artifacts. Requires knowledge of distribution beforehand.
Smoothed `approx_cdf` based pdf (old default). Smoothing causes large distortion.
New unsmoothed `approx_cdf_ based pdf. Single pass, works well for any distribution, needs no tuning or foreknowledge of distribution.
> [query] add less biased unsmoothed pdf to ggplot

- batch/batch/batch.py
- batch/batch/front_end/front_end.py
- batch/test/test_dag.py
Having a numerical value is helpful in the API if I'm trying to do any analytics with the the result of fetching batches.
> [batch] Report duration ms in batch and job records

- batch/jvm-entryway/src/main/scala/is/hail/QoBAppender.scala
Recent log demonstrating the failure: https://cloudlogging.app.goo.gl/ayiTFRnkLdrSzY2j7
In retrospect this seems kind of obvious. Consider `JVMEntryway`. The first `log` statement occurs on line 98 (the line after we set the filename). I think, in my head, the Appender would be created when we initialized the Logger on line 17. That's apparently incorrect. The Appender is lazily created when some internal buffer fills and the logger flushes that buffer.
That internal buffer is most likely to fill on the `log.error` lines because they dump a (large) stack trace to the log. That's why we always see the error there.
The fix is simple: we track the currently desired output filename and, if we happen to create an appender *after* someone has called `changeFileInAllAppenders`, we initialize …
> [qob] fix QoBAppender for real this time

- batch/sql/set-test-pools-to-known-parameters.py
- build.yaml
The biggest benefit of this PR is that I declare most of the pool state in one file so that we have one place to look to figure out what the tests are doing.
We pay about 2 USD per PR test, which is not very high but still higher than I would like. I investigated why and looked at eight recent PR tests (all after Daniel's QoB test reduction):
1. https://grafana.hail.is/d/8Kldmmynk/job-analytics?from=1695065243258&to=1695070128973&var-namespace=pr-13643-default-w484n4ke6oeg&orgId=1
2. https://grafana.hail.is/d/8Kldmmynk/job-analytics?from=1694628837271&to=1694632585473&var-namespace=pr-12468-default-y8okmle5k65x&orgId=1
3. https://grafana.hail.is/d/8Kldmmynk/job-analytics?from=1695078157872&to=1695080578446&var-namespace=pr-13644-default-phtb7scq3qln&orgId=1
4. …
> [batch] substantially reduce PR test costs

- hail/python/hail/ir/table_ir.py
- hail/python/test/hail/table/test_table.py
> [query] don’t drop poduct flag on TableIntervalJoin

- hail/python/test/hail/methods/test_misc.py
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
We special case array<str>, converting it before calling unwrapReturn, which for array<str> expects a SJavaArrayString for the return type and an Array[String] for the value.
Fixes #13633
> [query] Allow maximal_independent_set to accept strings as node names

- batch/batch/cloud/azure/driver/billing_manager.py
- batch/batch/cloud/azure/driver/pricing.py
- batch/batch/cloud/gcp/driver/billing_manager.py
- batch/batch/cloud/gcp/driver/pricing.py
- batch/batch/driver/billing_manager.py
- batch/batch/driver/pricing.py
- batch/batch/inst_coll_config.py
- batch/sql/add-product-sku.sql
- batch/sql/estimated-current.sql
- build.yaml
This change is to ensure that the SKU we think is associated with a product doesn't change in case the human readable name changes to a different SKU. This was raised as a good safety feature by #13430
> [batch] Add SKU to latest_product_versions

- batch/batch/worker/worker.py
Ben came across an image in the wild with a null `Env` field in the manifest, which caused the following error:
```
Error
File "/usr/local/lib/python3.9/dist-packages/batch/worker/worker.py", line 868, in _run
timed_out = await self._run_until_done_or_deleted(self._run_container)
File "/usr/local/lib/python3.9/dist-packages/batch/worker/worker.py", line 1010, in _run_until_done_or_deleted
return await run_until_done_or_deleted(self.deleted_event, f, *args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/batch/worker/worker.py", line 680, in run_until_done_or_deleted
return step.result()
File "/usr/local/lib/python3.9/dist-packages/batch/worker/worker.py", line 1066, in _run_container
await self._write_container_config()
File …
```
> [batch] Allow image Env to be None

- build.yaml
See #13554. This is the first fix that needs to happen such that the service account has permissions to delete VMs and disks. Note that the correct service account was already being used in Azure.
> [build.yaml] Give delete_gcp_batch_instances job the proper service account

- Makefile
- batch/Dockerfile.worker
- batch/build-batch-worker-image-startup-gcp.sh
- ci/create_database.py
- ci/create_local_database.py
- dev-docs/development-process.md
- docker/mysql/compose.yaml
- gear/gear/database.py
- hail/python/hailtop/auth/sql_config.py
I picked this refactor off of my terra branch and took it the last ten yards such that now you can run `make batch-db` and get a full local instance of the batch database that you can access through `mysql -h 127.0.0.1 -u root -ppw` or
```ipython
(hail) dgoldste@wmce3-cb7 hail % HAIL_SQL_DATABASE=local-batch ipython
Python 3.9.17 (main, Jul  5 2023, 16:17:03)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.15.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from gear import Database
...: db = Database()
...: await db.async_init()
...: await db.select_and_fetchone('SELECT * FROM globals')
...:
...:
Out[1]:
{'instance_id': 'XXXXXXXX',
'internal_token': 'XXXXXXX',
'n_tokens': 200,
'frozen': 0}
```
If you add a migration, just run `make batch-db` again.
> [devbin] Add a script for running a database locally

- batch/batch/cloud/gcp/driver/create_instance.py
The environment variable was getting assigned after we setup the fluentd log parameters.
> [batch] Fix GCP fluentd log labels

- hail/src/main/scala/is/hail/services/package.scala
CHANGELOG: Fixes #13704, in which Hail could encounter an IllegalArgumentException if there are too many transient errors.
I need to do the multiplication in 64-bits so that it does not wrap around to a large negative value. Then I can use `math.min` with the maxDelayMs to get us back into 32-bits.
I'm just pushing through a bunch of bugs to get Wenhan unblocked today.
> [query] fix backoff code

- batch/batch/worker/worker.py
I'm not sure this is the only reason why we're getting worker log errors when a user deletes jobs, but this code is definitely wrong in the case a container hasn't been started. I'm conflicted on whether we should do nothing or write empty files though.
> [batch] Only write logs and resource usage for started containers

- batch/jvm-entryway/src/main/java/is/hail/JVMEntryway.java
Fixes #13716
This finally block is currently located after `gather.take()` but *before* we cancel (aka shutdown) all threads. As a result, it is possible for us to shudown the logging (thus flushing, closing, and destorying old appenders) then restart logging (thus opening the file in overwrite mode) and blow away whatever was there.
I have verified in my namespace across 10s of thosuands of JVM Jobs that this never blows away the log.
> [qob] prevent race to write to log file

- hail/src/main/scala/is/hail/io/fs/FS.scala
- hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
CHANGELOG: Fix #13356 and fix #13409. In QoB pipelines with 10K or more partitions, transient "Corrupted block detected" errors were common. This was caused by incorrect retry logic. That logic has been fixed.
I now assume we cannot reuse a ReadChannel after any exception occurs during read. We also do not assume that the ReadChannel "atomically", in some sense, modifies the ByteBuffer. In particular, if we encounter any error, we blow away the ByteBuffer and restart our read entirely.
As I described in [this comment to #13409](https://github.com/hail-is/hail/issues/13409#issuecomment-1737926184), I have a 10K partition pipeline which was reliably producing this error but now reliably *does not* produce this error (it produces another one, #13721, fix forthcoming for that too).
> [qob] In GCS, recreate the ReadChannel if a transient error occurs

- hail/build.gradle
CHANGELOG: Fix #13721 which manifested with the message "Missing Range header in response". The root cause was a bug in the Google Cloud Storage SDK on which we rely. The fix is to update to a version without this bug. The buggy version of GCS SDK was introduced in 0.2.123.
The details are not particularly important, but the GCS client library was unable to parse a certain kind of exceptional server condition. This updates us to the latest GCS version.
> [qob] update GCS client lib to 2.27.1 to fix #13721

- batch/batch/worker/worker.py
- batch/test/utils.py
I started to debug #13599 and found this feature of knowing which job spun off the test batch would have been helpful for debugging purposes.
> [batch] Add client job id to test batch attributes for debugging

- batch/test/test_dag.py
I think the `client_job` attribute is doing its intended job but we need to ignore uncontrollable attributes in this test in particular.
> [batch] Ignore client_job attribute in test_callback test

- hail/Makefile
This should help us avoid more confusing errors down the line since our workers are all running JDK 8 and cannot use JDK 11+ bytecode.
> [qob] install-for-qob errors if javac is not 1.8

- batch/test/test_batch.py
It definitely looks like "ZONE_RESOURCE_POOL_EXHAUSTED" is the cause of these GPU test failures. In this case it looks like it took ~4 minutes to successfully get a VM (after two exhaustion errors) & schedule the job. By then, our uniform 6 minute timeout per test left us with just two minutes. It looks like the job actually did succeed in the worker (seems to have taken ~2 minutes, seems long, does testing for CUDA do some kind of initialization work?). Looks like backing that off to 10 minutes might be just enough to eventually get us a GPU. Might be worth pulling that into its own build.yaml test job so that it does not block the queue of other tests.
> [batch] back off gpu timeout to 10 minutes

- hail/python/hail/docs/tutorials/08-plotting.ipynb
- hail/python/hail/plot/plots.py
- hail/python/test/hail/plot/test_plot.py
Fixes #13696.
`n_divisions` is a downsampling factor. It conflicts with `collect_all` when `collect_all=True` is specified.
Deprecate `collect_all` and issue warning when users supply a non-`None` `collect_all` argument.
Use `n_divisions=None` to not downsample (implies `collect_all=True`).
Throw when `collect_all=True` and `n_divisions` is not `None` - this is a conflict.
> [query] Deprecate `collect_all` in `hail.plots.*` (use `n_divisions` instead)

- batch/batch/resource_usage.py
For the first 5 seconds, we sample every 100ms rather than using the underlying `delay_ms_for_try` in order to have enough data for short jobs.
> [batch] Sample resource usage more frequently at start

- hail/python/test/hail/conftest.py
#13564 forgot to change this condition (which was based on the old `None` means not-submitted logic).
> [qob] only try to cancel a test batch if it was submitted

- hail/build.gradle
Fixes #13706. When I reworked `build.gradle` to be simpler and conform with modern gradle standards, I forgot to dump all of our dependencies into our test runtime classpath.
This PR ensures that the test runtime classpath is the same as our runtime classpath in QoB and in QoS.
> [query] Fix 13706: enable Java tests to work again

- hail/python/hail/backend/service_backend.py
- hail/python/hail/context.py
- hail/python/test/hail/conftest.py
Stopping and re-initing is cheap and easy with QoB (compared to spark) and is a cleaner way to reset service backend state. Also note that we pass in the test name as `app_name` in init so batches are guaranteed to be created with the name of the test.
> [pytest] Stop and reinitialize hail between QoB tests

- hail/build.gradle
closes https://github.com/hail-is/hail/issues/13690.
to test that this works, i've been running these commands from the root of my clone of the hail repo:
```bash
make -C hail install-editable
make -C hail install-hailctl
hailctl dataproc start notebook-slowdown-repro --region us-central1
hailctl dataproc connect notebook-slowdown-repro notebook
```
and then running this minimal example in the notebook:
```python
import hail
hail.utils.range_table(10).show()
```
and making sure it outputs a visual of the table, instead of getting stuck displaying `Stage 0:> (0+X)/Y` and not progressing.
> [query] fixes hail jar for dataproc notebooks

- hail/src/main/scala/is/hail/io/InputBuffers.scala
- hail/src/main/scala/is/hail/io/OutputBuffers.scala
In the end, this did not seem to have any significant effect on decoding, but it does show up in the profiler as a hotspot.
> [query] do not reinitialize zstd repeatedly

- hail/src/main/scala/is/hail/lir/X.scala
This has no discernable effect on latency but it makes the LIR much easier to read because, for example, `IfX IFNE L1 L2 ...` will have `L1` (in printed LIR and JVM bytecode) immediately after it rather than `L2`. The labels also tend to appear in sequential order, which I find helps me navigate the LIR.
> [query] emit LIR instructions in order (instead of reverse order)

- Makefile
- build.yaml
- check-sql.sh
- ci/test/resources/build.yaml
I really borked our SQL linting. This PR is short but it catches a few critical problems.
1. The point of `check-sql.sh` is to detect modifications or deletions of SQL files in PRs and fail if such a change occurs. Currently on `main` it does not detect modifications. In #13456, I removed the `delete-<service>-tables.sql` files (intentionally), so added the `^D` to the `grep` regex to indicate that it is OK to have a deletion. What I inadvertently did though is change the rule from "It's ok to have Additions of any file OR  Modifications of estimated-current.sql / delete-<service>-tables.sql" to "It's ok to have Additions OR Modifications OR Deletions of estimated-current.sql / delete-<service>-tables.sql". Really this should have been "It's ok to have Additions OR Modifications of …
> [linting] Catch unintended errors in check-sql.sh

- hail/src/main/scala/is/hail/backend/Backend.scala
`f` is a thunk so it is currently being evaluated thrice before inserted into the code cache. The `compiledFunction` variable was unused so I think this is what was originally intended.
> [query] Dont compile code cache function three times

- hail/python/test/hail/expr/test_ndarrays.py
- hail/src/main/scala/is/hail/expr/ir/ndarrays/EmitNDArray.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
ndarray concat was broken when the first input has size 0 along the concat axis. For example
```
In [3]: hl.eval(hl.nd.hstack([hl.nd.zeros((2, 0)), hl.nd.array([[1.0, 2.0], [3.0, 4.0]])]))
Out[3]:
array([[0., 2.],
[0., 4.]])
```
The zeros matrix is 2 by 0, so horizontal concatenation should just return the other matrix.
(I once saw the first column filled with random numbers, presumably from a buffer overflow)
I did some cleaning up in the concat implementation, but the functional change is to record the index of the first input which is non-empty along the concat axis, and when resetting to the start of the axis, reset to that non-empty index. Other size 0 inputs are correctly handled when incrementing the index, the problem was that the first read happens before an increment.
> [query] fix ndarray concat with size 0 dims

- hail/python/hailtop/utils/utils.py
CHANGELOG: Mitigate new transient error from Google Cloud Storage which manifests as `aiohttp.client_exceptions.ClientOSError: [Errno 1] [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2548)`.
As of around 1500 ET 2023-10-16, this exception happens whenever we issue a lot of requests to GCS.
See [Zulip thread](https://hail.zulipchat.com/#narrow/stream/300487-Hail-Batch-Dev/topic/cluster.20size/near/396777320).
> [hailtop] yet another transient error

- ci/ci/templates/pr.html
The `logging_queries` variable is always *defined* but sometimes `None`.
> [ci] fix Azure CI PR page

- hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
- hail/src/main/scala/is/hail/backend/service/Worker.scala
- hail/src/main/scala/is/hail/utils/ErrorHandling.scala
CHANGELOG: Fixes #13697, a long standing issue with QoB, in which a failing partition job or driver job is not failed in the Batch UI.
I am not sure why we did not do this this way in the first place. If a JVMJob raises an exception, Batch will mark the job as failed. Ergo, we should raise an exception when a driver or a worker fails!
Here's an example: I used a simple pipeline that write to a bucket to which I have read-only access. You can see an example Batch (where every partition fails): https://batch.hail.is/batches/8046901. [1]
```python3
hl.utils.range_table(3, n_partitions=3).write('gs://neale-bge/foo.ht')
```
NB: I removed the `log.error` in `handleForPython` because that log is never necessary. That function converts a stack of exceptions into a triplet of the …
> [query] if worker or driver raise an exception, fail the Batch job

- hail/src/main/scala/is/hail/annotations/RegionValueBuilder.scala
- hail/src/main/scala/is/hail/annotations/UnsafeUtils.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/agg/StagedArrayBuilder.scala
- hail/src/main/scala/is/hail/types/encoded/EArray.scala
- hail/src/main/scala/is/hail/types/physical/PArrayBackedContainer.scala
- hail/src/main/scala/is/hail/types/physical/PCanonicalArray.scala
- hail/src/main/scala/is/hail/types/physical/PContainer.scala
- hail/src/main/scala/is/hail/types/physical/stypes/concrete/SIndexablePointer.scala
- hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SContainer.scala
- hail/src/test/scala/is/hail/asm4s/CodeSuite.scala
- hail/src/test/scala/is/hail/types/physical/PContainerTest.scala
Picking up where #13776 left off.
CHANGELOG: improved speed of reading hail format datasets from disk
This PR speeds up decoding arrays in two main ways:
* instead of calling `arrayType.isElementDefined(array, i)` on every single array element, which expands to
```scala
val b = aoff + lengthHeaderBytes + (i >> 3)
!((Memory.loadByte(b) & (1 << (i & 7).toInt)) != 0)
```
process elements in groups of 64, and load the corresponding long of missing bits once
* once we have a whole long of missing bits, we can be smarter than branching on each bit. After flipping to get `presentBits`, we use the following psuedocode to extract the positions of the set bits, with time proportional to the number of set bits:
```
while (presentBits != 0) {
val idx = …
```
> [query] faster array decoder

- hail/python/hailtop/aiotools/fs/copier.py
1. File rate is more interesting for small files.
2. The source_report controls the progress bar. By updating it eagerly while we are listing a directory, the progress bar is more accurate sooner. We currently wait until we get a semaphore for a particular file to update the progress bar.
> [copier] minor clean up to copier

- hail/python/hail/vds/combiner/combine.py
> [vds/combiner] use get_lgt for PGT handling as well

- hail/src/main/scala/is/hail/annotations/RegionMemory.scala
Consider this:
```scala
class Foo {
def bar(): (Long, Long) = (3, 4)
def destructure(): Unit = {
val (x, y) = bar()
}
def accessors(): Unit = {
val zz = bar()
val x = zz._1
val y = zz._2
}
}
```
These should be exactly equivalent, right? There's no way Scala would compile the match into something horrible. Right? Right?
```
public void destructure();
Code:
0: aload_0
1: invokevirtual #27                 // Method bar:()Lscala/Tuple2;
4: astore_3
5: aload_3
6: ifnull        35
9: aload_3
10: invokevirtual #33                 // Method scala/Tuple2._1$mcJ$sp:()J
13: lstore        4
15: aload_3
16: invokevirtual #36                 // Method scala/Tuple2._2$mcJ$sp:()J
19: lstore        6
21: new           #13                 // class scala/Tuple2$mcJJ$sp
24: dup
25: lload         4
27: lload …
```
> [query] no unnecessary object allocations in RegionMemory.allocate

- hail/python/hail/experimental/pca.py
- hail/python/hail/experimental/table_ndarray_utils.py
- hail/python/hail/expr/__init__.py
- hail/python/hail/expr/expressions/__init__.py
- hail/python/hail/expr/expressions/expression_utils.py
- hail/python/hail/linalg/blockmatrix.py
- hail/python/hail/linalg/utils/misc.py
- hail/python/hail/methods/pca.py
- hail/python/hail/methods/statgen.py
- hail/python/hail/plot/plots.py
- hail/python/test/hail/methods/test_statgen.py
Fixes #13788:
- Add `raise_unless_column_indexed` guard and apply to all column-indexed parameters in `statgen.py`.
- Rename `check_row_indexed` and `check_entry_indexed` as I'm allergic to functions called "check" - now it's clearer what they do.
> Verify `logistic_regression_rows` `y` param is column-indexed

- hail/python/hailtop/aiotools/copy.py
This is the result of some experimentation. With ten-way parallelism, the copier very rarely gets rate-limited. With 75-way parallelism (the default), we almost always experience a tens of transient errors. If we start at ten and back off as in this PR, I can get to 75 with just a handful of transient errors.
cc: @jigold
> [fs] rate limit our use of parallelism in copy

- batch/batch/worker/worker.py
Containers get deleted when a job is cancelled. This is not exceptional behavior.
Example: https://cloudlogging.app.goo.gl/punCSPauoM1ZEqZ27
> [batch] no logs on container deleted

- hail/python/hailtop/hailctl/dataproc/submit.py
> [hailctl] Expand username in dataproc submit

- hail/python/hailtop/utils/utils.py
Besides the types and some transient exceptions, I think I fixed our task exception handling in several spots. Two things:
1. We do not need to wait on a cancelled task. If it was not done, then it could not possibly have an exception to retrieve. Moreover, now that it is cancelled, there is nothing else to do. Cancellation is immediate.
2. If a task is done, we *must* always retrieve the exception, otherwise we might not see an exception.
> [hailtop] types, new exceptions, better task exception handling

- hail/python/hail/matrixtable.py
- hail/python/hail/table.py
Rori encountered some confusing output. _same is private, but this is good both for GVS/AoU and also for us.
Things are indented properly, it uses as much terminal width as is available, the names are slightly less confusing, and we see both globals & row failures if both fail.
```python3
Table._same: rows differ:
Row mismatch at key=Struct(locus=Locus(contig=1, position=1, reference_genome=GRCh37), alleles=['A', 'C']):
Left:
[Struct(ancestral_af=0.381520365258488,
af=[0.6482459117152142],
__uid_entries_85=[Struct(GT=Call(alleles=[1, 1], phased=False)), Struct(GT=Call(alleles=[1, 1], phased=False))])]
Right:
[Struct(ancestral_af=0.381520365258488,
af=[0.2510276144176496],
__uid_entries_85=[Struct(GT=Call(alleles=[0, 0], phased=False)), Struct(GT=Call(alleles=[0, 1], phased=False))])]
Row …
```
> [query] improve field names and output of _same

- hail/python/hail/backend/service_backend.py
- hail/python/test/hail/conftest.py
1. If a job errors rather than fails, we still want to see its logs in the debug info.
2. The backend from before `hl_stop_for_test` is broken. In particular, it does not have an open ClientSession, so it cannot make HTTP requests.
> [qob] minor fixes to service backend

- ci/ci/ci.py
- ci/ci/utils.py
DEFAULT_NAMESPACE will always point to `default` for the production CI deployment.
> [ci] Fix namespace used for logging queries on PR page

- hail/Makefile
- website/website/website.py
I also fixed local/dev docs building. You need Hail installed for the docs build to work because it tries to `import` the classes for which you're building docs.
> [website] add docs/latest/ (which currently redirects to 0.2)

- ci/ci/build.py
I wanted to be safe rather than sorry for #13487 to make sure we have enough memory to fit all of the 100 row chunk endpoints in memory. We can switch it back to 4 cores after that PR is merged.
> [ci] Bump number of cores to 16 for db deployment jobs

- hail/python/hail/context.py
CHANGELOG: hl.default_reference can now be passed an argument to change the default reference genome.
Now, when hl.default_reference is passed a reference genome argument, it sets the default reference to that reference genome and returns None.
> [query] Teach hl.default_reference to set the default reference genome

- hail/python/hailtop/hailctl/describe.py
Fix the overriding of the gcs_requester_pays/project config variable through using 'hailctl describe -u'.
Closes #13793
> [hailctl] fix hailctl describe requester pays argument handling

- ci/ci/build.py
The largest migration took 6.2 GB of memory. I think we'll be fine for awhile with 15 GB of memory (4 cores).
> [ci] Set database creation jobs back to 4 cores

- Makefile
- auth/Makefile
- batch/Makefile
- ci/Makefile
- config.mk
- docker-build.sh
- infra/bootstrap_utils.sh
- monitoring/Makefile
- website/Makefile
This came to mind yesterday during our pairing. This PR introduces the following properties that our image building targets do not currently have:
1. If your intention is only to build images, you shouldn't need `kubectl`. When `DOCKER_PREFIX` is used as a docker build arg it is because we mirror some dockerhub images inside our registry (for reliability/rate limiting reasons). But for local building there's no reason you can't use the dockerhub image. Also, other people should be able to build the hail image if they want to!
2. One should *only* need to use `kubectl` if they are intending to use an image in a kubernetes deployment. In other words, you should only need the private registry `DOCKER_PREFIX` for pushing images.
3. One should not need to endure image pushing if the only goal …
> [make] Separate image building from image pushing

- batch/Dockerfile.worker
Let's see if this "just works".
> [batch] Update gcsfuse version to 1.2.0

- hail/build.gradle
CHANGELOG: Fixes #13837 in which Hail could break a Spark installation if the Hail JAR appears on the classpath before the Scala JARs.
We and several dependencies of ours are exposing an old version of scala-reflect (rude of us and them). If our JAR appears on the classpath before the scala JARs and the sub-versions of Scala differ, Spark is likely to have incompatible bytecode.
See https://github.com/hail-is/hail/issues/13837 .
In this PR, this command,
```
make shadowJar && \
jar tf build/libs/hail-all-spark.jar | grep scala/reflect | wc -l && \
jar tf build/libs/hail-all-spark.jar | grep 'MutableSettings'
```
prints:
```
0
```
On main (`5d7dc2cab7`) it prints:
```
1417
scala/reflect/internal/settings/MutableSettings$.class
scala/reflect/internal/settings/MutableSettings$SettingValue.cla …
```
> [gradle] exclude scala-reflect

- build.yaml
- hail/python/hail/context.py
- hail/python/hailtop/batch/backend.py
- hail/python/hailtop/batch/batch_pool_executor.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/cleanup_gcr/__main__.py
- hail/python/hailtop/fs/router_fs.py
- hail/python/hailtop/hail_event_loop.py
- hail/python/hailtop/hailctl/batch/cli.py
- hail/python/hailtop/hailctl/describe.py
- hail/python/hailtop/requirements.txt
- hail/python/hailtop/utils/utils.py
- hail/python/test/hail/conftest.py
- hail/python/test/hail/helpers.py
- hail/python/test/hail/test_hail_in_notebook.ipynb
- hail/python/test/hail/test_hail_in_notebook.py
- hail/python/test/hailtop/inter_cloud/generate_copy_test_specs.py
CHANGELOG: Fix `RuntimeError: This event loop is already running` error when running hail in a Jupyter Notebook.
Man this is really complicated.
OK, so, things I learned:
1. [asyncio will not create a new event loop if `set_event_loop` has been called even if `set_event_loop(None)` has since been called.](https://github.com/python/cpython/blob/main/Lib/asyncio/events.py#L676)
2. [asyncio will not create a new event loop in a thread other than the main thread.](https://github.com/python/cpython/blob/main/Lib/asyncio/events.py#L677)
3. `aiohttp.ClientSession` stashes a copy of the event loop present when it starts. This can cause all manner of extremely confusing behavior if you later change the event loop or use that session from a different thread.
The fix, in the end, wasn't that …
> [query] ensure nest_asyncio is applied, but only when necessary

- hail/src/main/scala/is/hail/expr/ir/analyses/SemanticHash.scala
- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
- hail/src/test/scala/is/hail/expr/ir/analyses/SemanticHashSuite.scala
Fixes #13915
`MatrixVCFReader` accepts glob patterns (wildcards in glob names). This bamboozled `SemanticHash` which had assumed all files had been resolved. This change fixes this by adding explicit `FileNotFoundException` handling to `SemanticHash` and replacing the `params.files` object of `MatrixVCFReader` with the resolved paths.
> Make `SemanticHash` Resilient to `FileNotFoundExceptions`

- hail/python/hail/docs/change_log.md
- hail/python/hailtop/utils/utils.py
- hail/python/test/hail/conftest.py
- hail/src/main/scala/is/hail/backend/BackendServer.scala
Non-daemon threads [keep a JVM alive](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html):
> When a Java Virtual Machine starts up, there is usually a single non-daemon thread (which typically calls the method named main of some designated class). The Java Virtual Machine continues to execute threads until either of the following occurs:
>
> The exit method of class Runtime has been called and the security manager has permitted the exit operation to take place.
>
> All threads that are not daemon threads have died, either by returning from the call to the run method or by throwing an exception that propagates beyond the run method.
Spark appears to wait for the JVM to terminate before it considers a job complete.
> [query] avoid hanging the JVM in Dataproc

- batch/test/test_batch.py
- build.yaml
Trying to rely on our private registry instead of dockerhub where we can.
> [ci] Use private base image for GPU testing image

- hail/python/test/hail/expr/test_ndarrays.py
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
Really bad example:
```python
In [2]: a = hl.nd.array(2)
In [3]: empty = np.array([], np.int32).reshape((0, 2, 2))
In [4]: empty = hl.nd.array(empty)
In [5]: hl.eval(empty)
Out[5]: array([], shape=(0, 2, 2), dtype=int32)
In [6]: hl.eval(a + empty)
Out[6]:
array([[[       2, 55622722],
[       2,        3]]], dtype=int32)
```
Result of sum of shape `()` with shape `(0, 2, 2)` should be shape `(0, 2, 2)` by standard numpy broadcasting rules. Instead, we try to produce a result with shape `(1, 2, 2)`, which contains garbage data.
> [compiler] fix ndarray broadcasting with 0 sizes

- hail/python/hailtop/aiotools/copy.py
- hail/python/hailtop/aiotools/delete.py
- hail/python/hailtop/aiotools/diff.py
- hail/python/hailtop/batch/backend.py
- hail/python/hailtop/utils/rich_progress_bar.py
I renamed RichProgressBar and SimpleRichProgressBar to ...CopyToolProgressBar because that is more accurate. I enhanced both to now include a count and a rate with the right units based on the description. It is a bit flaky because I need the descriptions to be exactly "files" or exactly "bytes" to pick the right units, but this seems fine for the specific case of th CopyToolProgressBar.
There is probably a better way to build these UIs. I am sure we will start to figure that out as we use rich more.
Before:
After:
> [fs] improve copy tool progress bars

- Makefile
- build.yaml
- docker/hailgenetics/hail/Dockerfile
IIUC the reason we `tar` the hail wheel to move it between jobs in the CI pipeline is because the wheel name must contain the pip version and that is not known statically in `build.yaml`. However, it would be just as effective to copy the wheel around inside a directory, and then we don't have to do all this tar'ing and untar'ing.
cc @ehigham I'm happy to hold off on this if it would bork your branch
> [ci] Dont tar the hail wheel in CI pipelines

- batch/batch/driver/job.py
- batch/batch/driver/main.py
- batch/batch/front_end/front_end.py
- batch/batch/front_end/query/query_v1.py
- batch/batch/front_end/query/query_v2.py
This PR switches all usages of v2 billing tables on the batch and batch-driver server code to use the v3 tables instead. Stacked on #12849.
> [batch] Switch to using v3 tables for batches and jobs billing

- hail/python/hail/genetics/reference_genome.py
Add a section on managing the default reference using the `default_reference` method.
> [query] Update ReferenceGenome docs

- hail/python/hail/expr/aggregators/aggregators.py
- hail/python/hail/expr/functions.py
- hail/python/hail/ir/register_aggregators.py
- hail/python/test/hail/expr/test_expr.py
- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/agg/ApproxCDFAggregator.scala
- hail/src/main/scala/is/hail/expr/ir/agg/ApproxCDFStateManager.scala
- hail/src/main/scala/is/hail/expr/ir/functions/ApproxCDFFunctions.scala
- hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
- hail/src/main/scala/is/hail/types/physical/stypes/primitives/SInt64.scala
- hail/src/test/scala/is/hail/annotations/ApproxCDFAggregatorSuite.scala
This PR enables users to combine results from multiple independent approx_cdf aggregators, for instance to allow updating quantile summaries when adding new samples.
In more detail:
* Change the result type of the internal aggregator to be a lossless representation of the internal state.
* Add a registered function which expose the CombOp of the aggregator.
* Move the function which computes the old result type from the internal state to python.
* Add a flag `_raw` to `approx_cdf` which produces the internal result type, which supports combining; otherwise convert to the old result type.
> [query] refactor approx_cdf to support manual combining

- hail/src/main/scala/is/hail/expr/ir/analyses/SemanticHash.scala
- hail/src/test/scala/is/hail/expr/ir/analyses/SemanticHashSuite.scala
Namely, TableKeyByAndAggregate and TableAggregateByKey
> [query] Add semhash support for Table-to-Table Aggregations

- hail/python/hailtop/auth/auth.py
- hail/python/hailtop/auth/tokens.py
- hail/python/hailtop/config/deploy_config.py
- hail/python/hailtop/hailctl/auth/cli.py
- hail/python/test/hailtop/config/test_deploy_config.py
The `DeployConfig.service_ns` doesn't really do anything, we always use the `_default_namespace`. This is maybe from an earlier age where some services might live in different namespaces.
> [hailtop] Remove service_ns method in DeployConfig

- hail/src/main/scala/is/hail/expr/ir/Children.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/ExtractIntervalFilters.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/InTailPosition.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
- hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/main/scala/is/hail/expr/ir/add-ir-checklist.txt
- hail/src/main/scala/is/hail/expr/ir/analyses/SemanticHash.scala
- hail/src/main/scala/is/hail/expr/ir/lowering/CanLowerEfficiently.scala
- hail/src/test/scala/is/hail/expr/ir/ExtractIntervalFiltersSuite.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
- hail/src/test/scala/is/hail/expr/ir/RequirednessSuite.scala
- hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala
We have no high-level IR analogue to `CodeBuilderLike.switch`. Such a node is useful for flattening the IR in deeply-nested `If` nodes, predicated on integer equality.
This partially addresses the stack-overflow error on the `matrix_muluti_write_nothing` benchmark, which currently has a stack-overflow error when computing the type of the CDA.
> [compiler] Add `Switch` to `IR`

- build.yaml
- ci/ci/build.py
- ci/deployment.yaml
- ci/test/resources/build.yaml
- `CreateNamespaceStep.public` was entirely unused
- `adminServiceAccount` is not used in `build.yaml` so `CreateNamespaceStep.admin_service_account` is always `None` meaning it has no effect.
- The three environment variables that I deleted from the `deployment.yaml` are as far as I can tell entirely unused (they are now grabbed from the global config)
> [ci] Remove dead code from CI configs

- batch/batch/cloud/gcp/worker/disk.py
This is a fix for an error Ben found.
```
File "/usr/local/lib/python3.9/dist-packages/batch/worker/worker.py", line 1907, in run
await self.setup_io()
File "/usr/local/lib/python3.9/dist-packages/batch/worker/worker.py", line 1848, in setup_io
await self.disk.create(labels=labels)
File "/usr/local/lib/python3.9/dist-packages/batch/cloud/gcp/worker/disk.py", line 47, in create
await self._attach()
File "/usr/local/lib/python3.9/dist-packages/batch/cloud/gcp/worker/disk.py", line 112, in _attach
self.last_response = await self.compute_client.attach_disk(
File "/usr/local/lib/python3.9/dist-packages/hailtop/aiocloud/aiogoogle/client/compute_client.py", line 83, in attach_disk
return await self._request_with_zonal_operations_response(self.post, path, …
```
> [batch] Make GCP disk attachment idempotent

- batch/batch/cloud/azure/driver/driver.py
- batch/batch/cloud/driver.py
- batch/batch/cloud/gcp/driver/driver.py
- batch/batch/driver/canceller.py
- batch/batch/driver/main.py
- batch/batch/front_end/front_end.py
- batch/batch/worker/worker.py
- hail/python/hailtop/aiotools/tasks.py
- hail/python/hailtop/utils/utils.py
I couldn't find the best issue for this. Should fix #13908, but I thought there was another issue about reducing noisy grafana alerts which this PR also addresses.
> [batch] Fix async exit stacks

- batch/sql/populate_job_groups.py
- build.yaml
This PR just populates the records for older batch into the `job_groups` and `job_group_self_and_ancestors` tables.
Stacked on #13475
> [batch] Populate job groups in database

- batch/sql/estimated-current.sql
- batch/sql/fix-job-groups-state-enum.sql
- build.yaml
I forgot that "open" was a valid batches state when I created the job groups table state column as an enum. This should fix the failed migration from #13487
> [batch] Fix enum column state in job groups table

- website/website/styles/navbar.scss
- website/website/templates/nav-top.html
The CSS for the website is a real mess. I initially tried to clean it up, but that became a time sink. We should eventually do that, but for now I made the minimal edits to get a reasonable looking layout.
With the navbar open, in mobile, it looks the same as the non-docs pages.
> [website] add a link to the community feedback survey to website

- Makefile
- batch/pinned-requirements.txt
- benchmark/python/pinned-requirements.txt
- ci/pinned-requirements.txt
- gear/pinned-requirements.txt
- hail/python/dev/pinned-requirements.txt
- hail/python/hailtop/config/deploy_config.py
- hail/python/hailtop/pinned-requirements.txt
- hail/python/pinned-requirements.txt
- hail/python/requirements.txt
- web_common/pinned-requirements.txt
`asyncinit` is unused AFAICT and the `frozenlist` requirement is already inherited from hailtop (though it is not used in `hailtop` only in query code, so am also happy to move it out of hailtop fully and into query).
> [query] Remove unused and redundant requirements

- hail/src/main/scala/is/hail/expr/ir/ExtractIntervalFilters.scala
- hail/src/test/scala/is/hail/expr/ir/ExtractIntervalFiltersSuite.scala
Fix bug where relational IR inside the condition of a TableFilter or MatrixFilter causes a ClassCastException. This can happen if, for example, there's a TableAggregate inside the condition.
> [compiler] allow relational IR in ExtractIntervals

- hail/python/hail/plot/plots.py
> [query/plot] removes "chr" prefix for manhattan plot x-axis labels

- hail/build.gradle
CHANGELOG: Fix #13937 caused by faulty library code in the Google Cloud Storage API Java client library.
> [query] fix #13937 which manifests as Google throwing an NPE

- hail/python/test/hail/fs/test_worker_driver_fs.py
A very small PR but here's the background and context behind this change. When talking to either GCP or Azure, hail chooses credentials in the following order from highest priority to lowest priority:
1. An explicit `credential_file` argument passed to the relevant credentials class
2. An environment variable containing the path to the credentials (`GOOGLE_APPLICATION_CREDENTIALS` or `AZURE_APPLICATION_CREDENTIALS`) (from this you can see why the code that was here is totally redundant)
3. The latent credentials present on the machine. This might be `gcloud` or `az` credentials, or the metadata server if you're on a cloud VM.
I'm trying to rid the codebase of most explicit providing of credentials file paths, for two reasons:
- Quality of life. I'm already signed into the cloud with …
> [batch] Use default credentials for the Azure SAS token test

- hail/python/test/hail/experimental/test_local_whitening.py
It’s a random test, and it seems the current tolerance still allows rare sporadic failures.
> [query] relax tolerance in local whitening test

- hail/python/test/hail/expr/test_expr.py
We observed some sporadic failures, but the error was always less than .011. This raises the tolerance to .015, which should be a comfortable margin.
> [query] increase tolerance in approx_cdf tests

- hail/build.gradle
Spark depends on a very old verison of SLF4J. We cannot upgrade. We added this dependency ages ago to fix some undocumented issue with logging and SLF4J. It seems reasonable to me that we should just accept whatever version of SLF4J that Spark provides.
This removes this message:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/usr/lib/spark/jars/log4j-slf4j-impl-2.17.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```
Which, IMO, really should be a …
> [query] restore Spark logs to the Hail log file

- pylintrc
We only have `make` commands for running `pylint` on subdirectories that have been kept up to date with its rules, but the `pylintrc` doesn't actually contain any indication of which subdirectories should be ignored when running `pylint`. This makes the use of language servers that run `pylint` on the file that's open frustrating, as files in the ignored subdirectories will often be full of `pylint` suggestions. This change adds the relevant subdirectories to the `pylintrc` file. Note that this does not necessarily enable us to run `pylint` directly on those subdirectories with the equivalent `make` commands to the ones that already exist, because there is no way that I've found to make `pylint` ignore the `__init__.py` file of whatever module it's being run on, so running it on …
> [tooling] adds non-hailtop subdirs to pylint ignore

- Makefile
- letsencrypt/Makefile
- letsencrypt/subdomains.txt
This wasn't updated when I separated out building and pushing so the `build` target wasn't pushing the image. When I fixed that the cert generation failed because `memory` is no longer available. These changes got everything working again.
> [letsencrypt] Update make targets to be compatible with new docker-build.sh

- hail/python/hailtop/hailctl/dataproc/cli.py
- hail/python/hailtop/hailctl/dataproc/start.py
CHANGELOG: Since 0.2.110, `hailctl dataproc` set the heap size of the driver JVM dangerously high. It is now set to an appropriate level. This issue manifests in a variety of inscrutable ways including RemoteDisconnectedError and socket closed. See issue #13960 for details.
In Dataproc versions 1.5.74, 2.0.48, and 2.1.0, Dataproc introduced ["memory protection"](https://cloud.google.com/dataproc/docs/support/troubleshoot-oom-errors#memory_protection) which is a euphemism for a newly aggressive OOMKiller. When the OOMKiller kills the JVM driver process, there is no hs_err_pid...log file, no exceptional log statements, and no clean shutdown of any sockets. The process is simply SIGTERM'ed and then SIGKILL'ed.
From Hail 0.2.83 through Hail 0.2.109 (released February 2023), Hail was pinned to …
> [query] prevent sudden unceremonious death of driver JVM

- auth/auth/auth.py
`aiohttp` 3.9 introduced `AppKey` which allows `Application.__getitem__` to convey a return type based on its input. So we can do things like `db = app[AppKeys.DB]` and `db` is known to be of type `Database`. This should help a great deal with static type checking and in-editor type hints.
> [auth] Use aiohttp AppKeys for typed Application storage

- batch/test/test_batch.py
- hail/python/hail/backend/service_backend.py
- hail/python/hailtop/batch/backend.py
Jobs that are configured with `mount_tokens=True` will have their Hail tokens mounted into the main container. However, now that we are using access tokens from cloud identities, the tokens are no longer used. This removes the default behavior of mounting the `tokens.json` files since they aren't used by our codebase anyway.
> [batch|qob] Dont request hail tokens in the batch client

- hail/build.gradle
CHANGELOG: Fix #13979, affecting Query-on-Batch and manifesting most frequently as "com.github.luben.zstd.ZstdException: Corrupted block detected".
This PR upgrades google-cloud-storage from 2.29.1 to 2.30.1. The google-cloud-storage java library has a bug present at least since 2.29.0 in which simply incorrect data was returned. https://github.com/googleapis/java-storage/issues/2301 . The issue seems related to their use of multiple intremediate ByteBuffers. As far as I can tell, this is what could happen:
1. If there's no channel, open a new channel with the current position.
2. Read *some* data from the input ByteChannel into an intermediate ByteBuffer.
3. While attempting to read more data into a subsequent intermediate ByteBuffer, an retryable exception occurs.
4. The exception …
> [query] update past a broken google cloud storage java library

- hail/build.gradle
The Zstandard version is not changing. The zstd-jni library, which wraps Zstandard and provides some interoperation with java.nio, has released 9 times since 1.5.5-2. They do not publish a changelog, but I scanned through their commits. There were some potentially relevant bug fixes:
1. When using array-backed ByteBuffers, zstd-jni reads the wrong data if the arrayOffset is not zero. https://github.com/luben/zstd-jni/commit/355b8511a2967d097a619047a579930cac2ccd9d
2. Perhaps a slightly faster path for array-backed ByteBuffers. https://github.com/luben/zstd-jni/commit/100c434dfcec17a865ca2c2b844afe1046ce1b10
3. Possibly faster buffer pool. https://github.com/luben/zstd-jni/commit/2b6c3b75012dec44f8fd2dd56dd97eea0d62f19c
4. Removed a double free during compression. …
> [query] update zstd-jni to 1.5.5-11

- hail/python/hailtop/aiocloud/aioazure/credentials.py
- hail/python/hailtop/aiocloud/aiogoogle/credentials.py
- hail/python/hailtop/aiocloud/common/credentials.py
- hail/python/hailtop/aiocloud/common/session.py
- hail/python/hailtop/auth/auth.py
- hail/python/hailtop/auth/tokens.py
- hail/python/hailtop/batch_client/aioclient.py
We need to retry 401s until we get a 401 from credentials we know to be invalid.
> [aiocloud] refresh access tokens after transient errors

- hail/python/hailtop/hailctl/dataproc/connect.py
- hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
- hail/python/test/hailtop/hailctl/dataproc/test_connect.py
CHANGELOG: Fix #14089, which makes `hailctl dataproc connect` work in Windows Subsystem for Linux.
1. Non 64-bit Windows uses "Program Files" not "Program Files (x86)"
2. Windows Subsystem for Linux looks like GNU/Linux but will not have chromium on its path.
3. The removed arguments are no longer supported. They produce a warning message in my version of Chrome and appear to not work in the version of Chrome that this user was using. Instead, I bind to 0.0.0.0 and access the Notebook using the machine DNS name. This is how Google recommend accessing the Spark UI anyway.
> [hailctl] make hailctl work on windows

- hail/python/hail/vds/combiner/variant_dataset_combiner.py
* Add assertion to `load_combiner` and `new_combiner` to fail if the output vds exists
* Remove assertion that disallows empty `gvcfs` and `vdses` in `VariantDatasetCombiner.__init__`
Resolves #14079
> [query/vds combiner] Change sanity checks on combiner construction

- hail/src/main/scala/is/hail/services/package.scala
Wenhan observed this error after I gave her a branch using google cloud storage 2.30.1. I've reported this new transient error to the client API repo, but I doubt it will be fixed. https://github.com/googleapis/java-storage/issues/2337
SSL errors seem like the kind of thing we should not retry forever since they could indicate a bad actor.
> [query] retry Tag mismatch a limited number of times

- build.yaml
- hail/python/hailtop/auth/auth.py
- hail/python/hailtop/hailctl/__main__.py
- hail/python/hailtop/hailctl/auth/cli.py
- hail/python/hailtop/hailctl/auth/create_user.py
- hail/python/hailtop/hailctl/auth/delete_user.py
- hail/python/hailtop/hailctl/auth/login.py
- hail/python/hailtop/hailctl/batch/utils.py
I'm trying to move our codebase away from relying on the notion of a K8s namespace for routing because this model does not hold in alternative deployment environments such as Terra. Further, having a `-n` option in `hailctl auth` commands is awkward because it can only be used for dev environments yet is visible to users in the help menu. As such, this is a breaking change only for developers. The functionality is not really gone though because you can replace any `hailctl auth … -n dgoldste` with `HAIL_DEFAULT_NAMESPACE=dgoldste hailctl auth …`.
> [hailtop] Remove namespace options in hailctl auth commands

- hail/src/main/scala/is/hail/backend/Backend.scala
- hail/src/main/scala/is/hail/backend/BackendUtils.scala
- hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
- hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
- hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
- hail/src/main/scala/is/hail/services/package.scala
- hail/src/main/scala/is/hail/utils/package.scala
- hail/src/test/scala/is/hail/expr/ir/table/TableGenSuite.scala
The original goal of this PR was avoiding `Try` when we are not using the restartability provided by semantic hashing because I strongly suspect it is related to the loss of stacktraces in exceptions.
Unrelatedly, we realized the semantic hash PR changed the semantics of Query-on-Spark even when semantic hash is disabled: previously we would abort RDD writing on the first exception. In Hail 0.2.123 through 0.2.126, the semantics were changed to only crash *after* we already ran every other partition. Two bad scenarios of which I can think:
1. Suppose the first partition fails due to OOM. We now waste time/money on the rest of the partitions even though we cannot possibly get a valid output.
2. Suppose every partition hits a permission error. Users should get that feedback after paying for …
> [query] cleave Backend paths into normal parallelize and parallelize returning errors

- hail/python/hailtop/hailctl/hdinsight/start.py
CHANGELOG: Fix `hailctl hdinsight start`, which has been broken since 0.2.118.
The shift to typer/click accidentally converted this parameter from a string to an int.
> [hailctl] fix parsing in hailctl hdinsight start

- hail/python/hailtop/auth/flow.py
This would seem to violate this [statement about `hd`](https://developers.google.com/identity/openid-connect/openid-connect#id_token-hd):
> The absence of this claim indicates that the account does not belong to a Google hosted domain.
but alas, that's the truth. They elide `hd` for iam.gserviceaccount.com accounts.
> [auth] hd is not present for iam.gserviceaccount.com

- .pre-commit-config.yaml
We do not yet have pyright running on the Hail python package nor the tests. Without this change, I get failures on push.
> [precommit] ignore hail/python/(hail|test) from pyright

- batch/test/test_batch.py
- build.yaml
- hail/python/hailtop/config/deploy_config.py
- hail/python/test/hailtop/config/test_deploy_config.py
Currently, the k8s namespace field is used both for routing internal requests inside kubernetes but also external requests over the internet. It also has special logic based on whether the namespace indicates a production or dev environment. For example, if `namespace == 'default'`, then we route external `batch` requests to `batch.<domain>/path`, but if `namespace == foo_dev`, we route external `batch` requests to `internal.<domain>/foo_dev/path`.
This PR decouples the namespace field from routing. Aside from being overall more straightforward in my opinion, this is necessary for batch on azure terra where batch is served out of a subpath it does not control and is unrelated to whatever namespace it might reside in. The guiding principle for routing is then as follows: If the config has …
> [hailtop] Add subpath to deploy config

- hail/python/hailtop/hailctl/dataproc/start.py
Here's a diff of `hailctl dataproc start foo --dry-run` on main and on this branch. Notice that the properties and metadata arguments gain a leading and trailing single quote. This ensure that things like `sys_platform!="win32"` are properly transmitted.
In `start.py` we just use exec-style invocation, so there's no equivalent issue.
```
7c7
<     --properties=^|||^spark:spark.task.maxFailures=20|||spark:spark.driver.extraJavaOptions=-Xss4M|||spark:spark.executor.extraJavaOptions=-Xss4M|||spark:spark.speculation=true|||hdfs:dfs.replication=1|||dataproc:dataproc.logging.stackdriver.enable=false|||dataproc:dataproc.monitoring.stackdriver.enable=false|||spark:spark.driver.memory=36g|||yarn:yarn.nodemanager.resource.memory-mb=29184|||yarn:yarn.scheduler.maximum-allocation-mb=14592|||spark:spar …
```
> [hailctl] make the output of dry-run copy-pasteable

- build.yaml
- hail/python/hailtop/aiocloud/aioazure/fs.py
- hail/python/hailtop/hailctl/batch/cli.py
- hail/python/hailtop/hailctl/batch/submit.py
- hail/python/test/hailtop/hailctl/batch/test_submit.py
The bug in #13785 was that we used a `relpath`, but the files that were to be included was the parent directory of the current working directory of the script. To solve this, I added a new option `--mounts` that uses the Docker syntax for `-v src:dest` to specify where the contents of the source should be mounted into the container.
Fixes #13785
> [hailctl] Fix uploading files from parent directories of cwd

- hail/python/hailtop/aiocloud/aioaws/fs.py
- hail/python/hailtop/aiocloud/aioazure/fs.py
- hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py
- hail/python/hailtop/aiotools/fs/fs.py
- hail/python/hailtop/aiotools/local_fs.py
- hail/python/test/hailtop/inter_cloud/test_fs.py
The term `name` has long been ambiguous and, indeed, our Azure implementation differed from S3 and Google. Now both FileStatus and FileListEntry use the term `basename`. Azure has been changed to have the same semantics as S3 and Google.
> [aiotools] add basename to FileStatus; rename name in FileListEntry

- hail/python/test/hailtop/hailctl/batch/test_submit.py
This provides useful feedback we can use to understand why `test_file_in_current_dir` keeps failing.
> [batch] provide sufficient information to debug transient errors

- hail/Makefile
- hail/python/hailtop/aiocloud/aioaws/fs.py
- hail/python/hailtop/aiocloud/aioazure/fs.py
- hail/python/hailtop/aiotools/copy.py
- hail/python/hailtop/httpx.py
- hail/scripts/upload_qob_jar.sh
We have long had trouble with copying on flaky Internet connections. AFAIK, this is due to our very aggressive timeouts. This change permits the CLI to override the default timeout in `hailtop.aiotools.copy`. Setting this back to 600s should work on most flaky Internet connections. It works on my particularly bad home WiFi.
The upload-docs target was old and broken so I deleted it. I did not change the upload-artifacts target because that is Google Cloud specific anyway.
Main benefit is that these targets work in Azure now.
> [httpx][Makefile][copier] add --timeout to copier; use in Makefile

- batch/batch/driver/instance.py
- batch/batch/driver/job.py
- batch/batch/driver/main.py
- batch/batch/front_end/front_end.py
- ci/ci/ci.py
- ci/ci/github.py
- gear/gear/__init__.py
- gear/gear/auth.py
- monitoring/monitoring/monitoring.py
- website/website/website.py
Uses aiohttp [AppKeys](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.AppKey) to statically type `Application` storage. Also more explicitly pass additional parameters to methods in the `github.py` module instead of using `app` to ship around state.
> [ci] Use appkeys instead of strings for application storage.

- ci/ci/ci.py
The current `on_cleanup` code carefully attempts to close resources in the correct order (if B depends on A, we should close B before we close A). Doing so is pretty error prone though and we have messed it up in the past, leading to noisy error logs when pods are shut down. If we instead push `.close` methods onto a stack immediately after they are initialized, the exit stack cannot be executed in the wrong order.
> [ci] Push cleanup methods in on_startup to ensure proper execution order

- auth/deployment.yaml
- batch/deployment.yaml
- ci/ci/envoy.py
- ci/deployment.yaml
- ci/test/resources/deployment.yaml
- ci/test/resources/statefulset.yaml
- gateway/Makefile
- gear/gear/session.py
- monitoring/deployment.yaml
- web_common/web_common/web_common.py
As of #14056, there is ambiguity when referring to the configuration value `domain`.
- In the `global-config`, this is the root domain of the entire hail system. This is the same across all namespaces.
- In the `deploy-config` of a namespace N, this refers to the root domain served by applications of that namespace. In production (namespace `default`), this is `hail.is`, the same as the root domain of the entire system. In other namespaces, this is `internal.hail.is`.
Setting the `HAIL_DOMAIN` environment variable in the k8s deployments from the `global-config` overrides what should be `internal.hail.is` to `hail.is`, breaking any form of redirection. There's really no need to set this environment variable at all, as its value can be derived from the `deploy-config`. This PR removes that …
> [services] Fix domain configuration in dev namespaces

- hail/python/hailtop/hailctl/dev/config.py
- hail/python/test/hailtop/hailctl/dev/conftest.py
- hail/python/test/hailtop/hailctl/dev/test_config.py
#14056 added a new optional field to the deploy config, `base_path` which is intended to phase out `default_namespace`. But for backwards compatibility reasons we cannot yet remove `default_namespace`. This should all work fine without breaking any workflows like switching back and forth between namespaces so long as `base_path` is not explicitly set in a developer's deploy config.
But `hailctl dev config set <property> <value>` does not just set a single property, it loads the deploy config, sets the property, and then writes the whole deploy config back. If the deploy config does anything with default values, which it now does with `base_path`, this round trip does not work.
Another simpler example is that currently in main, the following will make two changes to a deploy config not …
> [hailctl] Dev config set should only change one property

- devbin/dev_proxy.py
- monitoring/monitoring/monitoring.py
Forgive my throwing the dev proxy change in here too, but this gets us static typechecking on stuff stored in `app` across the codebase except for `batch`. That's a beast that will be a lot of changes to port to `AppKey`s and I don't want to mess with the current in flight PRs.
> [monitoring] Use aiohttp.AppKey to add static typing to Application storage

- batch/batch/cloud/gcp/driver/create_instance.py
Currently the Ops Agent does not do any parsing of the log message, so the log entry in Google Logging looks like:
```
jsonPayload: {
message: "{"severity":"INFO","levelname":"INFO","asctime":"2024-01-22 16:10:45,748","filename":"worker.py","funcNameAndLine":"<module>:3461","message":"closed","hail_log":1}"
}
```
The `parse_json` processor extracts the json fields from the message into fields on the `jsonPayload` so it looks like this
```
jsonPayload: {
asctime: "2024-01-22 16:14:06,098"
filename: "worker.py"
funcNameAndLine: "<module>:180"
hail_log: 1
levelname: "INFO"
message: "CLOUD gcp"
}
```
and only the new `message` field is displayed in the Google Logging row instead of the whole json.
This also adds a `severity` field on the log entry so filters such as `SEVERITY!=INFO` work as …
> [batch] Add json parsing and severity to GCP Ops Agent config

- devbin/dev_proxy.py
- web_common/web_common/web_common.py
Currently, the `_csrf` cookie is made available to all subdomains of `.hail.is`. This means that if I first visit `batch.hail.is` I get a `_csrf` cookie set for `.hail.is`. That cookie is then reused if I visit `ci.hail.is`. Even more awkward, the same value of the cookie will get reused if I then visit `batch.azure.hail.is`. This isn't that big of a deal, these can all be considered part of the same application that the hail team delivers and secures, but it is very little work to set stricter bounds on where this cookie is sent. By removing the `domain` attribute and using `samesite='strict'`, the cookie's domain will be set by the browser to the domain of the request whose response included the `Set-Cookie` header, e.g. `batch.hail.is` or `internal.hail.is`. `Strict` mode then ensures …
> [gear] Make csrf cookie samesite=strict

- batch/sql/estimated-current.sql
- batch/sql/remove-v2-billing-writes.sql
- build.yaml
This PR modifies the billing triggers to stop writing to the v2 billing tables as well as remove the check for whether the equivalent v2 rows have been "migrated" when writing to the v3 tables. Stacked on #13891.
> [batch] Stop writing to v2 billing tables

- devbin/rotate_keys.py
Rotation has a non-interactive mode for when you are rotating keys in an expected state. I added the same behavior for the bulk delete mode.
> [rotate_keys.py] make deletion non-interactive as well

- hail/python/hailtop/config/variables.py
- hail/python/hailtop/hailctl/config/config_variables.py
- hail/python/hailtop/httpx.py
Until we have a mechanism to infer the correct timeout based on network conditions, this provides an escape hatch for users on flaky network connections such as wifi.
> [hailtop] allow configuration of default HTTP timeout

- hail/python/hail/vds/combiner/variant_dataset_combiner.py
- hail/python/hail/vds/variant_dataset.py
Use the patch in place function of `store_ref_block_max_length` to compute `ref_block_max_length` rather than computing it on a zip join pipeline, causing that zip join pipeline to be executed twice.
> [vds/combiner] Better calculation of ref_block_max_length

- hail/src/main/scala/is/hail/services/DeployConfig.scala
I forgot to include the changes in #14056 to the scala code as well. This favors using `basePath` in the Scala deploy config over the `defaultNamespace`.
> [qob] Update scala deploy config to use new base_path field

- batch/batch/cloud/gcp/instance_config.py
- batch/batch/cloud/gcp/resources.py
- batch/sql/update-ip-fee-resource.py
- build.yaml
- hail/python/hailtop/batch/docs/service.rst
Fixes #13784 
Here's the GCP documentation:
https://cloud.google.com/vpc/pricing-announce-external-ips
We were previously billing the same IP-Fee for both spot and regular instances. I changed it so we're billing for each instance type accordingly.
Following #13542, I hard coded the new resource rates.
> [batch] Update IP Fee pricing for February 2024 price increase

- hail/python/hailtop/batch/backend.py
- hail/python/hailtop/batch/batch.py
- hail/python/hailtop/batch/docs/service.rst
- hail/python/test/hailtop/batch/test_batch_service_backend.py
`hb.Batch` now supports `default_regions` which completes the natural hierarchy of: config, envvar, backend, batch, job. I went a little hog wild with examples. I think we should have more examples everywhere!
The ServiceBackend doc page also had several basic formatting issues which I addressed.
> [hailtop.batch] add default_regions to hb.Batch, improve docs

- batch/batch/worker/worker.py
`oldwarn` is somehow `None` which spams us with instance log errors. We can revisit the warning level in a PR if this is really important.
https://cloudlogging.app.goo.gl/VmUohrJSNo6EjsK56
> [batch] silence instance logs

- hail/python/test/hail/table/test_table.py
- hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
CHANGELOG: Fix a bug, introduced in 0.2.114, in which `Table.multi_way_zip_join` and `Table.aggregate_by_key` could throw "NoSuchElementException: Ref with name `__iruid_...`" when one or more of the tables had a number of partitions substantially different from the desired number of output partitions.
Fixes https://github.com/hail-is/hail/issues/14245.
In both MultiWayZipJoin and TableAggregateByKey, we repartition the child but neglect to use the new globals `Ref` from the repartitioned child. As long as `repartitionNoShuffle` does not create a new TableStage with new globals, this is fine, but that is not, in general, true. It seems that recently, in lowered backends, when the repartition cost is deemed "high" we generate a fresh TableStage with a fresh globals ref.
> [query] Use valid globals reference in MWZJ and TABK

- hail/src/main/scala/is/hail/expr/AnnotationImpex.scala
- hail/src/test/scala/is/hail/methods/ExprSuite.scala
@patrick-schultz I'm not sure if this makes sense or not, but I observed it while working on something else. It seems weird but acceptable to import an empty dictionary as any struct. Does this seem reasonable to you? How have we avoided this bug for so long?
I'm not familiar enough with this code to know how to simply reproduce the bug and add a corresponding test. Thoughts?
> [query] support importing empty JSON objects

- hail/python/hail/docs/tutorials/07-matrixtable.ipynb
In this pull request, I fix an error in the MatrixTable tutorial. The tutorial shows some genotype data and erroneously states that all the genotypes that are shown are homozygous reference (0/0). In fact, there are also some heterozygous (0/1) and homozygous alternate (1/1) genotypes in the displayed data. In this pull request, I remove the erroneous statement.
I ran the notebook to confirm that the notebook displays a mix of genotypes, not just homozygous reference. You can view the erroneous version of the tutorial [here](https://hail.is/docs/0.2/tutorials/07-matrixtable.html#MatrixTable-operations).
> Fix an error in the MatrixTable tutorial

- batch/batch/worker/worker.py
The current lack of this guard means we log exceptions when users submit jobs with images that don't exist or when users cancel their jobs (`ContainerDeletedError`). We do this check elsewhere but looks like this line slipped through.
> [batch] Do not log user errors as exceptions

- gear/gear/database.py
As discussed in #14240, we emit warnings on database deadlocks, which there are enough of to trigger noisy alerts. Since there's nothing to be done operationally (and there's no current work underway to get rid of them), these alerts only contribute to alert fatigue and hide potential problems in the system that could be addressed. This demotes a deadlock to the `info` level so we can still see how often they occur but are not alerted by them. In the future when we resolve the current deadlock we can re-escalate this error so that we can catch new deadlocks that are introduced.
> [gear] Change deadlock logs from warning to info

- batch/batch/cloud/azure/driver/create_instance.py
- batch/batch/cloud/gcp/driver/create_instance.py
Fixes #14262
Ever since starting to control job network namespaces ourselves, we run the worker container with `--network host`. But running with the host's network namespace means there's no need (nor meaning) to use port forwarding rules with `-p`. Docker safely ignores this redundant setting but emit some log messages like:
```
WARNING: Published ports are discarded when using host network mode
```
The solution here is to just remove the old port publishing settings.
> [batch] Drop redunant port mapping on worker container run

- build.yaml
- infra/gcp-broad/ci/main.tf
- infra/gcp-broad/gcs_bucket/main.tf
- infra/gcp-broad/main.tf
If CI jobs are to apply cleanup policies to the Artifact Registry, CI needs to have the permissions on the AR to do so. Prior to this change, CI only had viewer on the AR and used a different service account named `gcr-push` to push images to the registry. I don't see the point in having this second service account and think that CI should have these permissions (because it basically does already if it can submit jobs with the `gcr-push` service account). So the main point of this PR is to give CI admin on the AR, and then we can follow up by deleting the `gcr-push` service account.
Separately:
Not sure how this ever worked, but I needed to update the google terraform provider to get `cleanup_policy_dry_run = false`. That upgrade now made the DNS zone description mandatory so I added one. …
> [infra] Make CI an admin of the artifact registry

- hail/scripts/release.sh
cloudtools is an ancient name for hailctl dataproc. This is not the docs SHA. The docs are copied into a Docker image by the `website_image` build step. The only special file is gs://hail-common/builds/0.1/docs/hail-0.1-docs-5a6778710097.tar.gz which was the last 0.1 docs. It is the one that we host on the website for posterity.
> [release] remove unused old stuff

- hail/src/main/scala/is/hail/io/avro/AvroTableReader.scala
We need a valid HailStateManager when generating the partitioner for AvroPartitionReader. Instead of calculating the partitioner on the AvroTableReader, make the partitioner computation a method that takes an HailStateManager.
Closes #14249
> [query] Fix NullPointerException in Avro import

- website/website/pages/search.html
For some reason, the old application, identified by BH4D9OD16A has been disabled. This updates us to the new one which is still valid.
> [algolia] update to current "application"

- website/website/templates/nav-bottom.html
Apparently the last change I made only updated the search on the home page. Grep for `d2dee24912091336c40033044c9bac58` now returns no results on our repo.
> [algolia] also update the search bar on the docs page

- hail/python/hail/docs/tutorials/07-matrixtable.ipynb
This is hard to keep valid without automatically verifiying our tutorials do not have broken links.
> [tutorials] fix broken link to joins tutorial

- hail/python/cluster-tests/cluster-vep-check-GRCh37.py
- hail/python/cluster-tests/cluster-vep-check-GRCh38.py
- hail/python/hail/docs/_static/annotationdb/annotationdb.html
- hail/python/hail/docs/_static/annotationdb/annotationdb.js
- hail/python/hail/docs/annotation_database_ui.rst
- hail/python/hail/docs/cloud/azure.rst
- hail/python/hail/docs/datasets.rst
- hail/python/hail/experimental/datasets.json
- hail/python/hail/experimental/datasets.py
- hail/python/hail/experimental/db.py
- hail/python/hail/methods/qc.py
- hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh37.sh
- hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh38.sh
- hail/python/hailtop/hailctl/dataproc/start.py
- hail/python/test/hail/experimental/test_annotation_db.py
- hail/scripts/test-dataproc.sh
CHANGELOG: In GCP, the Hail Annotation DB and Datasets API have moved from multi-regional US and EU buckets to regional US-CENTRAL1 and EUROPE-WEST1 buckets. These buckets are requester pays which means unless your cluster is in the US-CENTRAL1 or EUROPE-WEST1 region, you will pay a per-gigabyte rate to read from the Annotation DB or Datasets API. We must make this change because [reading from a multi-regional bucket into a regional VM is no longer free](https://cloud.google.com/storage/pricing-announce#network). Unfortunately, cost constraints require us to choose only one region per continent and we have chosen US-CENTRAL1 and EUROPE-WEST1.
This is a disruptive change.
Due to the introduction of egress costs from multi-regional buckets, we decided to move all the datasets in the …
> [annotationdb][datasets] regional buckets

- auth/auth/auth.py
- monitoring/monitoring/monitoring.py
This change makes it harder to get the order of `on_cleanup` wrong. An extension of #14172 to `auth` and `monitoring`.
> [auth|monitoring] Push exit stack callbacks on initialization

- infra/azure/modules/batch/outputs.tf
- infra/azure/modules/ci/main.tf
If this looks good I will apply it before merging. Once this is in we can fully drop support for `hail-az`.
> [infra] Use https instead of hail-az in service configs

- hail/python/hailtop/aiocloud/aioazure/fs.py
- hail/python/hailtop/config/user_config.py
- hail/python/test/hail/fs/test_worker_driver_fs.py
- hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
Closes #14116. This has been deprecated for some time and we have received confirmation from relevant parties that they are off this scheme.
> [fs] Drop support for the deprecated hail-az scheme

- gear/pinned-requirements.txt
- gear/requirements.txt
- hail/python/hailtop/pinned-requirements.txt
- hail/python/hailtop/requirements.txt
- hail/python/pinned-requirements.txt
CHANGELOG: Require `orjson<3.9.12` to avoid a segfault introduced in orjson 3.9.12.
See https://github.com/hail-is/hail/issues/14299 for details.
> [query] avoid orjson-caused segfault in py4j_backend.py

- Makefile
- build.yaml
- ci/ci/build.py
- ci/test/resources/build.yaml
`network=private` is an escape hatch for CI so certain jobs can talk to internal endpoints on our network that we do not permit user jobs to reach. In `main`, all CI jobs are hard-coded to use `private` in `build.py`, but few jobs in the CI pipeline actually require these heightened privileges. The steps in the CI pipeline are of the following types:
- `BuildImageStep`: These do not need to use the private network and have now all been made to use the public network namespaces
- `CreateDatabaseStep`: These *do* need to use `network='private'` because all our DBs only have private IPs on our internal network
- `RunImageStep`: Those steps that contact the DB need the private network. This PR makes the network configurable for these steps but default to public, so steps that need DB access …
> [ci] Use the public networks where possible

- infra/gcp/main.tf
#14266 only added these changes to `gcp-broad`, I neglected to make them to our generic terraform as well.
> [infra] Apply same CI admin role as gcp-broad in normal gcp terraform

- build.yaml
- ci/ci/build.py
- infra/gcp-broad/main.tf
- infra/gcp/main.tf
CI owns the internal container registry, so there's no reason to have an additional service account that CI impersonates in order to push images. This removes uses of `registry-push-credentials` in favor of using the CI identity that already exists in the batch jobs that interact with the container registry. I've marked this as `full-deploy` because you want to roll out this change before a subsequent PR that I will make to delete the `gcr-push` identity.
> [ci] Use CI's credentials for image pushing instead of gcr-push

- build.yaml
- hail/python/hail/docs/change_log.md
#14198 removed the GAR-related parameters to release.sh but they were still passed in in build.yaml so it refused to run.
> [ci] Remove unused arguments to release script

- gear/gear/database.py
`create_database_pool` does not actually make a connection, rather it sets up a `_PoolContextManager`. We need to make sure this line
```python
self.pool = await self.async_exit_stack.enter_async_context(x)
```
is covered by transient error handling.
> [gear] Retry transient errors on database pool creation

- hail/python/hailtop/batch/docs/service.rst
With the introduction of the metadata server, users no longer need to explicitly activate a service account with `gcloud` and this line of code will stop working when we remove key files.
> [batch] Remove GOOGLE_APPLICATION_CREDENTIALS from the batch docs

- build.yaml
Since recently adding metadata server support for batch jobs in GCP, `gcloud` should now "Just Work" using the CI service account in CI jobs without explicitly configuring it with a key file, so we no longer need this line. I tested that this succeeds with a dev deploy.
> [ci] Remove unnecessary GSA activation for GAR policy step

- batch/batch/utils.py
`monitor_billing_updates` occasionally fails due to deadlocks on this query, but as it's read-only it should be fine to retry. Changing to `select_and_fetchall` uses read-only transactions and retries those transient errors.
> [batch] Use select instead of execute for retryable billing project queries

- hail/python/hailtop/utils/rich_progress_bar.py
Calling `int` truncates the value, rates below 1 units/second, appear as "0". This preserves the floating point value and displays it with two precision digits. This does mean that numbers like "123.45" are now displayed like that rather than as "123" :shrug:.
> [rich_progress_bar] show two sigfigs when rate <1

- hail/python/hailtop/utils/utils.py
Suppose there are 10,000 tasks competing for the semaphore. If any one of them rasises an exception while the `WithoutSempahore` context manager is active, then the probability that the `WithoutSemaphore.__aexit__` wins the semaphore is 1/10,000 aka unlikely. In practice, this means we need to process through most of the tasks to get the first exception. If, for a real world example, there is a permission issue, you will wait many minutes for all 10,000 tasks to fail, all with the same exception, and then you will finally receive the first exception plus a *litany* of log messages about other tasks which were not properly cleaned up (due to the implementation of `bounded_gather2_raise_exceptions`).
> [hailtop] in WithoutSemaphore, optionally do not acquire the semaphore when raising

- devbin/rotate_keys.py
- infra/azure/modules/batch/main.tf
- infra/gcp/main.tf
#14301 Switched image building steps in the CI pipeline over to just using CI's own credentials instead of this special `registry-push-credentials` secret. `registry-push-credentials` is now unused in the codebase and can be removed. Will run this when the PR is approved, then merge.
> [infra] Remove unused registry-push-credentials secret

- build.yaml
I don't have great evidence but 15 seconds might not be very much if we get big preemptions in k8s and our auth pods need to be redeployed on new nodes. I've been seeing more timeouts in Azure CI in this step and thought we should retry a little longer. If this issue persists I'll devote some time to digging deeper on it.
> [ci] Retry more for auth copy paste logins

- hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py
Alright, so.
1. If you `await`, call `exception`, or call `result` on a cancelled task, you receive a `CancelledError`.
2. A cancelled task is not necessarily done. The task could catch the `CancelledError` and do something, including raise a different exception (e.g. because a resource close failed).
3. Nested try-finally sucks.
This PR adds `_cleanup_future` which:
1. Cancels the future.
2. Waits for the future to receive its cancellation and then terminate.
3. Checks if the future is cleanly cancelled (in which case there is nothing more for us to do).
4. Retrieves any present exceptions from a not-cancelled (but done!) future.
We then use this function, in combination with exit stacks, to simply and cleanly manage exceptions.
I also added some missing retry_transient_errors …
> [aiogoogle] clean up storage client Task management

- hail/python/hailtop/aiotools/fs/fs.py
In particular, this allows `async with RouterAsyncFS(...) as fs` to give a tight type to `fs`.
> [aiotools.fs] tighter type on AsyncFS.__aenter__

- batch/batch/driver/main.py
I assessed three query options, but keep in mind that the database is currently at nearly 100% CPU so these timings are high variance. I'm honestly pretty surprised that the first one isn't the fastest. It seems to me like the obvious SQL query and yet it does not perform as well as those using lateral joins.
Option 2 and Option 3 both use lateral joins. Option 2 uses a LEFT JOIN followed by a `WHERE ... IS NOT NULL` which is definitionally an `INNER JOIN`. For that reason, I also explored Option 3, directly using `INNER JOIN`, which appears to be very slightly faster and lower variance.
| Option | Timing (mean + stddev, in seconds) |
|--------|------------------------------------|
| 1      | 9.92 +- 2.02                       |
| 2      | 5.35 +- 1.87                       |
| 3      | …
> [batch] reduce CPU use of delete_prev_..._resource_records

- batch/batch/driver/job.py
Surfaced because sometimes k8s secrets 404 for CI pipelines and we got FK constraint failures because there is no batch 0. No danger of bad data being written, just noise and unnecessary database load. Thank you foreign key checks!
> [batch] Correct ordering of batch_id and job_group_id in mark_job_errored

- hail/build.sc
This will hopefully make it harder to accidentally build in debug mode when doing performance testing.
> [query] make mill print debug/release mode

- hail/python/hail/ir/base_ir.py
- hail/python/hail/ir/table_ir.py
- hail/python/test/hail/matrixtable/test_matrix_table.py
MatrixEntriesTable didn't define `uid_field_name` in `_handle_randomness`. Downstream operations failed to fetch the field and inserted a NA into `RNGSplit`. Assert that TableIRs define `uid_field_name` when provided to `handle_randomness`.
Fixes: #14303
> [query] Fix #14303 - missing when sampling MatrixTable entries

- batch/batch/front_end/front_end.py
As written there are at least two issues:
1. This function is not idempotent. If we retry the request while the first is still running, the second request will receive nothing from the first query and attempt to insert records into that empty space.
2. Intentionally concurrent updates will try to use the same update id because we do not take a FOR UPDATE lock on the gap after the last row. We should verify that what I have written here takes that gap lock.
> [batch] ensure exactly one request creates each update

- ci/ci/envoy.py
This might be an overcorrection, but as it is we are not scheduling more than 30j/s with the database at max capacity. With 3 replicas of internal-gateway this will let 30rps reach the batch driver. This should give us a clear indication of whether rate limiting more aggressively will help with the database currently being overloaded. See [this thread](https://hail.zulipchat.com/#narrow/stream/300487-Hail-Batch-Dev/topic/trying.20to.20mark.20batch.200.20complete/near/423839864) for more details.
> [internal-gateway] Greatly reduce rate limit for batch-driver requests from workers

- batch/batch/front_end/query/query_v1.py
- batch/batch/front_end/query/query_v2.py
I started with a random slow query I observed in the database. I confirmed, by running it on the database, that it was longer than a few seconds. I never waiting long enough for it to complete.
Starting with `select * from job_groups limit 51;`, I iteratively added clauses until the query was slow. I got through every clause except the `ORDER BY batches.id DESC` with queries that took fractions of a second. Around the same time @jigold commented:
> Is the order by statement the issue. Would have thought that should be on job groups table
I think she's exactly right.
This is the query:
```
SELECT
batches.*,
cancelled_t.cancelled IS NOT NULL AS cancelled,
job_groups_n_jobs_in_complete_states.n_completed,
job_groups_n_jobs_in_complete_states.n_succeeded, …
```
> [batch] reduce runtime of listing batches and job groups

- hail/python/test/hail/methods/test_impex.py
- hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
> [query] Don't error on VCF export when haploid call is unphased

- batch/sql/estimated-current.sql
- batch/sql/fix-mark-job-complete-deadlocks.sql
- build.yaml
By joining against the `batches` row in the insert `FOR UPDATE`, these queries try to grab an exclusive lock on the row in the `batches` table. This is a problem if the transaction already has a shared lock on that row, like it does in `mark_job_complete`. In that case any two concurrent MJCs from the same batch will deadlock.
> [batch] Dont grab an X lock on the batches table in attempts after update

- ci/ci/envoy.py
Reverts hail-is/hail#14374. #14373, #14377 and #14379 appear to have restored Batch's throughput.
> Revert "[internal-gateway] Greatly reduce rate limit for batch-driver requests from workers"

- hail/python/hail/matrixtable.py
Related Record: #14362
Operations following `make_table` fail with `ClassTooLargeException` when
one tries to make a `Table` from a `MatrixTable` with more than a modest
number of columns.
Users should use `localize_entries` for a more efficient means of creating
tables from matrixtables.
> [query] deprecate `MatrixTable.make_table`

- infra/gcp-broad/hail-is/ci_config.enc.json
- infra/gcp/README.md
I created @hail-ci-robot, created a personal access token with the "resource owner" set to "hail-is". It has permission to read and write pull requests and statuses. The token expires in just under a year. I created a calendar event on Hail General Calendar to remind us to rotate it.
> [ci] switch to a new personal access token

- hail/python/hailtop/batch/job.py
- hail/python/hailtop/batch/resource.py
We recently had a debugging odyssey due to the following code:
```python
import hailtop.batch as hb
def make_job(batch):
job = batch.new_job(name='test')
return job  # Oops, forgot to also return the output resource
batch = hb.Batch(name='test')
my_job, my_output = make_job(batch)
```
This lead to the following error message:
```
File "…/borkscript.py", line 8, in <module>
my_job, my_output = make_job(batch)
File "…/site-packages/hailtop/batch/job.py", line 125, in __getitem__
return self._get_resource(item)
File "…/site-packages/hailtop/batch/job.py", line 118, in _get_resource
r = self._batch._new_job_resource_file(self, value=item)
File "…/site-packages/hailtop/batch/batch.py", line 405, in _new_job_resource_file
jrf = _resource.JobResourceFile(value, …
```
> Prevent iteration of Job and ResourceGroup objects

- infra/azure/main.tf
- infra/azure/modules/batch/main.tf
- infra/azure/modules/ci/main.tf
- infra/azure/modules/vdc/main.tf
The major version upgrade of the azure provider changed some defaults, so in order to keep our infrastructure the same I explicitly set these changed fields back to their previous v2.99.0 values. The `min_tls_version` now defaults to 1.2, which *should* be fine as I presume all our services are using TLS 1.3, but we should independently verify that before making that change. I will make an issue accordingly.
> [infra] Update Azure provider 3.93.0

- batch/pinned-requirements.txt
- benchmark/python/pinned-requirements.txt
- ci/pinned-requirements.txt
- gear/pinned-requirements.txt
- gear/requirements.txt
- hail/python/dev/pinned-requirements.txt
- hail/python/hailtop/pinned-requirements.txt
- hail/python/hailtop/requirements.txt
- hail/python/pinned-requirements.txt
- hail/python/requirements.txt
`protobuf` was pinned not because it is a direct dependency of `hail` but because the version of `google-cloud-profiler` that we use is incompatible with greater versions of protobuf despite not putting an upper bound on its pin. However, the current solution of pinning it in `hailtop/requirements.txt` and `python/requirements.txt` is problematic in three ways:
1. Users of the `hail` pip package cannot use a newer version of protobuf if they want to
2. The `protobuf` version is only a problem for `google-cloud-profiler`, which we only use in the batch/ci/auth services, not the hail package
3. `protobuf` no longer a transitive dependency of anything in `hailtop`/`hail`, so why include it (and why include it twice?)
This is all fixable by moving the `protobuf` pin "up" to …
> [pip] Move protobuf pin from query to gear

- batch/batch/front_end/front_end.py
- batch/test/test_batch.py
> [batch] 400 on bad job group specs instead of 500

- batch/batch/cloud/terra/azure/driver/driver.py
This was basically a debugging assertion that slipped into `main`. We run our clusters in Azure's `eastus` region, but other than this line there's nothing stopping anyone from running clusters elsewhere.
> [batch] Remove hardcoded eastus assert

- hail/src/main/scala/is/hail/asm4s/package.scala
- hail/src/main/scala/is/hail/types/encoded/EBaseStruct.scala
> [query] Load each missing byte once during struct decoding.

- hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
This flag was once used when we used custom hail tokens for authenticating with Batch. Now, we use GCP or Azure access tokens to auth requests so this flag is no longer necessary.
> [qob] Remove mount_tokens job spec parameter for worker jobs

- Makefile
`requirements.txt` was removed in 30d69b6f2
> Remove `auth` from `check-pip-requirements` make target

- batch/batch/cloud/gcp/worker/worker_api.py
- batch/batch/worker/worker.py
When workers shut down, we get warning logs about unclosed client sessions, as seen in #14261. While it can be difficult to derive the source of the client session, I think it's the one held by the `GCPWorkerAPI`. I've added an exit stack and added the session's close method to it.
I also made a small change to `Worker`. I find it can be difficult to determine whether or not a particular class should close a client session because it's not always clear who owns it. Without a clear way to communicate this in python, I think we should just never transfer ownership of a `ClientSession` and always assume that if an object's constructor takes a client session, it should be assumed a borrow and not close the session when the object is closed. As such, I moved the call to `client_session()` into …
> [batch] Close the aiohttp client session used by the gcp WorkerAPI

- hail/src/main/scala/is/hail/services/package.scala
I run into this ~1/20,000 QoB just when writing result files. I'm going to make a separate issue with the ABS client repo but I suspect this might be difficult to track down and fix.
Example stack trace:
```
RuntimeException: java.lang.IllegalStateException: Faulted stream due to underlying sink write failure	Gjava.lang.RuntimeException: java.lang.IllegalStateException: Faulted stream due to underlying sink write failure
at is.hail.shadedazure.com.azure.storage.common.StorageOutputStream.checkStreamState(StorageOutputStream.java:92)
at is.hail.shadedazure.com.azure.storage.common.StorageOutputStream.flush(StorageOutputStream.java:102)
at is.hail.io.fs.AzureStorageFS$$anon$3.close(AzureStorageFS.scala:308)
at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
at …
```
> [fs] Add sink write failure in ABS to transient errors

- build.yaml
I'm guessing this was a Make-ism that spilled over into the bash script.
> [release] Fix EV syntax in release job for WHEEL variable

- batch/batch/utils.py
Decided to tackle this as it was causing noise in the logs. There is no reason this read-only select query should lock any rows.
> [batch] Do not lock when querying billing projects

- batch/batch/front_end/templates/billing.html
I sometimes find the term "Cost" on this page confusing, and I think its inferred meaning differs depending on who's reading the page. This page shows what users are spending on the Batch service, not what it is *costing* operators to run the service (since we charge a service fee).
> [batch] Use spend instead of cost on the billing page

- hail/python/hail/backend/spark_backend.py
- hail/python/hail/context.py
- hail/python/test/hail/backend/test_spark_backend.py
Adds `copy_spark_log_on_error` init configuration option. When true, driver logs are copied to the remote tmpdir if an error occurs. This is useful in support cases where users cannot copy logs off the dataproc server themselves as it has already shut down.
> [query] Copy spark driver log to remote tmpdir on error

- build.yaml
In a89d64a, I modified `build.yaml` to release the wheel we had already built and tested. Unbeknownst to me was that we rebuild the wheel with a different version of `hail/python/hailtop/hailctl/deploy.yaml` and releasing the version used for testing borked `hailctl dataproc` commands.
To fix this, we'll rebuild the wheel but use the `jar` we've already built and tested. This is safe to do as far as I know because we don't bundle any information into the jar that depends on the make flag `DEPLOY_REMOTE`.
Fixes: #14452
> [release] build release wheel with correct `deploy.yaml`

- build.yaml
- hail/python/hail/backend/local_backend.py
- hail/python/hail/context.py
- hail/python/test/hail/fs/test_worker_driver_fs.py
- hail/src/main/scala/is/hail/HailFeatureFlags.scala
- hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
- hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
- hail/src/main/scala/is/hail/backend/service/Worker.scala
- hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
- hail/src/main/scala/is/hail/io/fs/FS.scala
- hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
A long-standing fixme in the LocalBackend was to not rely on HadoopFS, which we use with the SparkBackend for compatibility with dataproc and hdfs urls.
By default, the HadoopFS doesn't understand gs urls. Users need to install the gcs-hadoop-connector (preinstalled in dataproc) to communicate with google cloud storage. Spark handles supplying credentials to the connector.
Issue #13904 is caused by failing to properly supply the gcs-hadoop-connector with credentials in the LocalBackend. In the absence of config, the connector hangs while trying to fetch a token form a non-existant metadata server.
The LocalBackend was designed to be a testing ground for lowered and compiled code that would eventually be run on batch, where we use the RouterFS. I propose a pragmatic fix for #13904 that …
> [query] Use RouterFS With LocalBackend

- ci/ci/ci.py
We can always revert this if there are issues, but the polling CI does to refresh its understanding of PRs and batches is pretty light, and I think every minute is still quite reasonable.
> [ci] Poll for batch and github changes every 1 minute instead of 5

- batch/batch/utils.py
I missed that #14443 only got one of several `LOCK IN SHARE MODE` lines in the billing projects query. This gets the rest in the two `query_billing_projects` functions that do readonly selects
> [batch] Remove remaining locks in read-only billing project queries

- ci/ci/ci.py
Reverts hail-is/hail#14461. We're hitting [github rate limits](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.container_name%3D%22ci%22%0A--%20severity%3DERROR%20OR%20WARNING;pinnedLogId=2024-04-18T15:42:12.920462831Z%2Fvdlhscspn377olu0;cursorTimestamp=2024-04-18T15:42:14.785330871Z;duration=P1D?project=hail-vdc) which is preventing actions like dev deploys. The limit is apparently [5,000 requests/hour](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-authenticated-users). This feels excessive to me, and I feel like we most be using the API poorly, but I want to just revert this before investigating further so …
> Revert "[ci] Poll for batch and github changes every 1 minute instead of 5"

- hail/python/hail/expr/types.py
- hail/python/test/hail/expr/test_expr.py
Our call representation effectively uses unsigned integers. We have to make sure that we are converting between signed and unsigned when encoding/decoding them to/from the backend.
> [query] Correct python encoding/decoding of diploid calls

- build.yaml
- infra/gcp-broad/gcp-ar-cleanup-policy.txt
`curl` is already installed in `hail_ubuntu_image`, on which `curl_image` is based.
> [ci] hail_curl_image is redundant. kill it.

- batch/batch/cloud/terra/azure/worker/worker_api.py
- batch/pinned-requirements.txt
- benchmark/python/pinned-requirements.txt
- ci/pinned-requirements.txt
- gear/pinned-requirements.txt
- gear/requirements.txt
- hail/python/dev/pinned-requirements.txt
- hail/python/hailtop/aiocloud/aiogoogle/client/bigquery_client.py
- hail/python/hailtop/auth/flow.py
- hail/python/hailtop/pinned-requirements.txt
- hail/python/hailtop/requirements.txt
- hail/python/pinned-requirements.txt
- hail/python/requirements.txt
- web_common/pinned-requirements.txt
`orjson` 3.9.15 fixed the rare segfault that we saw in `3.9.11`. Besides just updating to latest patch and minor versions:
- Removed a redundant requirement of `orjson` in `gear/requirements.txt` -- it inherits `orjson` from hailtop
- Bokeh `3.4` made a breaking change w.r.t. the `circle` method on figures. I have restricted the bounds for `bokeh` to avoid this breaking change but will follow up with a PR that changes our usage of bokeh to follow the deprecation/upgrade advice and undo the bounds restriction
> [pip] Update orjson and transitive dependencies

- docker/Dockerfile.base
- hail/Makefile
- hail/python/dev/pinned-requirements.txt
- hail/python/dev/requirements.txt
- hail/python/hailtop/pinned-requirements.txt
- hail/python/pinned-requirements.txt
setup.py complains awfully when you invoke it directly. Apparently this sort of thing is unacceptable and the recommended workflow for building wheels is to use build. See the link below for more information. https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
> [query] Build Hail Wheel With Python build

- hail/src/main/scala/is/hail/backend/Backend.scala
- hail/src/main/scala/is/hail/backend/BackendUtils.scala
- hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
- hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
- hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
- hail/src/main/scala/is/hail/utils/package.scala
- hail/src/test/scala/is/hail/utils/UtilsSuite.scala
https://github.com/hail-is/hail/pull/14085 fixed a change in semantics for `parallelizeAndComputeWithIndex` didn't fail early anymore.
It also noted that the `SparkTaskContext.partitionId` could be wrong when used with call caching, but left the fix to another change.
This change takes inspiration from `SparkContext.runJob` in its `partitions` optional argument.
By supplying this, we can limit the number of partitions that we compute (useful for call caching) without doing dodgy things that breaks the `partitionId`.
This change also reduces code duplication wile preserving semantics - `parallelizeAndComputeWithIndex` still fails early for the local and spark backends.
> [query] Cleanup Code-Duplication around `parallelizeAndComputeWithIndex`

- batch/batch/cloud/gcp/resource_utils.py
- batch/batch/cloud/resource_utils.py
This function is an unused relic of the first version of our billing system, that just computed the cost of a slot on a Batch VM per mcpu milliseconds based on some hard-coded prices. We long ago migrated to a system where we track GCP SKUs and price changes through their API and properly itemize usage by SKU in the database.
> [batch] Remove unused cost_from_msec_mcpu code

- hail/src/main/scala/is/hail/expr/ir/Binds.scala
- hail/src/main/scala/is/hail/expr/ir/Env.scala
Follows up on #14475 by deleting the old implementation of `Bindings` in favor of the new one, which has now been checked by CI to not change the behavior.
> [compiler] delete old binds implementation

- hail/src/main/scala/is/hail/expr/ir/BaseIR.scala
- hail/src/main/scala/is/hail/expr/ir/Binds.scala
- hail/src/main/scala/is/hail/expr/ir/ComputeUsesAndDefs.scala
- hail/src/main/scala/is/hail/expr/ir/Env.scala
- hail/src/main/scala/is/hail/expr/ir/ForwardLets.scala
- hail/src/main/scala/is/hail/expr/ir/FreeVariables.scala
- hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala
- hail/src/main/scala/is/hail/expr/ir/Subst.scala
- hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
Refactors `Bindings` to return an object encoding the change to the environment (any new bindings, whether the agg/scan env is promoted, etc). This allows the deletion of `SegregatedBindingEnv`. Follow up work will use this to replace the other specializations of `GenericBindingEnv`, and to greatly simplify compiler passes, such as `NormalizeNames` and `PruneDeadFields`, which currently need to redundantly encode the binding structure of every node.
> [compiler] declarative `Bindings`

- hail/python/hailtop/batch/batch.py
These docstrings weren't updated since the GCP multi-regional egress changes. It is no longer free to egress from/to multi-regional buckets, so the best thing to do would be to put your storage and compute into the same region.
> [docs] Change input/output bucket warning to recommend regional buckets

- docker/hail-ubuntu/Dockerfile
pip is very permissive and just treats `>=21<22` as `>=21`. The release candidate `24.1b1` for pip dropped yesterday and something about its name normalization broke extras with underscores in them. Since we were previously using `23`, I've pinned above `23` and below this broken release candidate.
> [docker] Fix pip pin

- hail/python/hail/table.py
- hail/python/test/hail/table/test_table.py
> [query] Ensure Table group_by + aggregate can't clobber global fields

- hail/python/hailtop/utils/utils.py
The treatment of `ClientPayloadError` as a sometimes transient error was originally made in response to [an existing issue](https://github.com/aio-libs/aiohttp/issues/4581) in aiohttp that can cause transient errors on the client that are difficult to distinguish from a real broken server. What's in `main` matched exactly on the error message, but that error message has [since changed](https://github.com/aio-libs/aiohttp/commit/dc38630b168a169139974617d75e176530c91696) to include more information, breaking our transient error handling. This change relaxes the requirement of the error response string to fix transient error handling for our current version of `aiohttp`.
I wish I had a better approach. `ClientPayloadError` can also be thrown in the case of malformed data, so I am reticent to …
> [hailtop] Dont assume exact error message match for ClientPayloadError retrying

- build.yaml
- ci/ci/ci.py
- ci/ci/envoy.py
- ci/deployment.yaml
- ci/test/envoy/test_gateway_cds_response.yaml
- ci/test/envoy/test_gateway_rds_response.yaml
- ci/test/envoy/test_internal_gateway_cds_response.yaml
- ci/test/envoy/test_internal_gateway_rds_response.yaml
- ci/test/test_ci.py
- ci/test/test_envoy.py
- gateway/Makefile
This adds simple unit tests to the CI functionality that generates the configs for `gateway` and `internal-gateway`. It also adds a developer-only endpoint to CI for easier inspection of what configs CI is currently generating in production. These configs do not contain any sensitive information.
> [ci] Add tests for generating envoy xds configs

- ci/ci/ci.py
The refactor in #14524, ironically to add more testing, accidentally dropped the query arguments when production CI filters by live namespaces. I'll follow up with more testing but CI is currently borked without this
> [ci] Fix query for deployed services when filtering to live namespaces

- hail/python/test/hail/linalg/test_linalg.py
Disables the test `test_tree_matmul_splits`, which seems to be leaking memory, and causing tests run after it to timeout. Disabling to allow CI to make progress on other PRs, but we do need to diagnose the actual issue here.
> [query] disable test_tree_matmul_splits

- batch/batch/driver/canceller.py
`self.async_worker_pool` is not owned by the `Canceller`, just borrowed, so it should not close it. `app['async_worker_pool']` is already closed in the aiohttp app lifecycle.
> [batch] Prevent double close of the async worker pool by the canceller

- hail/src/main/scala/is/hail/expr/ir/Binds.scala
- hail/src/main/scala/is/hail/expr/ir/Env.scala
- hail/src/main/scala/is/hail/expr/ir/FreeVariables.scala
- hail/src/main/scala/is/hail/types/MatrixType.scala
- hail/src/main/scala/is/hail/types/TableType.scala
Slightly tweak the `Bindings` class to store a single array of (name, type) pairs, with the various environments referring back to that array. This simplifies passes that want to create a single mutable state for each binding, even those that are bound in multiple environments (e.g. eval and agg).
> [compiler] refactor types in bindings

- hail/src/main/scala/is/hail/types/encoded/EArray.scala
- hail/src/main/scala/is/hail/types/encoded/EStructOfArrays.scala
- hail/src/main/scala/is/hail/types/physical/PArrayBackedContainer.scala
- hail/src/main/scala/is/hail/types/physical/PCanonicalArray.scala
- hail/src/main/scala/is/hail/types/physical/PCanonicalDict.scala
- hail/src/main/scala/is/hail/types/physical/PCanonicalSet.scala
This catches a few things missed in https://github.com/hail-is/hail/pull/14521 and adds `PCanonicalArrayBackedContainer` as an extension trait to `PArrayBackedContainer`, ensuring that types implementing this trait are specifically backed by `PCanonicalArray`.
>  [query] Cleanup following 'PArray implements PArrayBackedContainer' 

- build.yaml
- hail/build.sc
- hail/python/dev/pinned-requirements.txt
- hail/python/dev/requirements.txt
- hail/python/hail/context.py
- hail/python/hail/utils/java.py
- hail/python/test/hail/backend/test_service_backend.py
- hail/python/test/hail/conftest.py
- hail/python/test/hail/helpers.py
- hail/python/test/hail/methods/test_qc.py
- hail/python/test/pytest.ini
- hail/src/main/scala/is/hail/HailFeatureFlags.scala
- hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
- hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
- hail/src/main/scala/is/hail/backend/service/Worker.scala
- hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
- hail/src/main/scala/is/hail/io/fs/FS.scala
- hail/src/main/scala/is/hail/utils/package.scala
- hail/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- hail/src/test/scala/is/hail/backend/ServiceBackendSuite.scala
- hail/src/test/scala/is/hail/services/batch_client/BatchClientSuite.scala
Python integration tests often fail waiting to allocate highmem instances for worker jobs.
Since we control both APIs, it seems reasonable to move the testing burdon for vm allocation onto batch and use contract testing on the query driver side.
These contract tests cover:
- uploading the the ServiceBackendRPConfig to remote storage in python
- reading that config and forwarding the relevant sections to the batch service in scala
Admittedly these are fairly busy tests and make bare a lot of lower-level implementation details. While I believe these tests are good to have, they perhaps don't warrant the time investment to properly refactor for cleaner mocking. Should details of the main implementation change, these will likely break.
I've made tweaks to the python unittest annotations for …
> [query] Batch Backend Job Creation Contract Tests

- hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala
- hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala
> [query] fix lowered blockmatrix densify

- batch/batch/cloud/gcp/driver/pricing.py
- batch/batch/cloud/gcp/resource_utils.py
- batch/batch/cloud/resource_utils.py
- batch/test/test_utils.py
This PR adds the a2 machine family into batch as job private instance machines. These machines have much more powerful gpus than the g2 family of machines currently in batch.
> add a2 machine into batch

- hail/src/main/scala/is/hail/expr/ir/BaseIR.scala
- hail/src/main/scala/is/hail/expr/ir/Binds.scala
- hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/Compile.scala
- hail/src/main/scala/is/hail/expr/ir/ForwardLets.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala
- hail/src/main/scala/is/hail/expr/ir/Optimize.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/main/scala/is/hail/expr/ir/analyses/SemanticHash.scala
- hail/src/test/scala/is/hail/expr/ir/ForwardLetsSuite.scala
- hail/src/test/scala/is/hail/expr/ir/analyses/SemanticHashSuite.scala
Greatly simplifies the `NormalizeNames` pass to be logically independent of the binding structure. This leaves the old implementation, and asserts that they agree. Will delete the old implementation in a follow up.
> [compiler] simplify NormalizeNames

- batch/batch/front_end/front_end.py
- batch/test/test_batch.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/batch_client/client.py
Hi! 
I know this is out of the blue, but we would like the ability to fetch resource_usage data from an endpoint programmatically to evaluate our job performance. I thought it might be worth suggesting this upstream to see if it's something you'd like too :)
This PR:
1. Use the internal method to fetch the dataframes for a job
2. Transform the data frame to dictionary with `orient='split'`
And FWIW, here's how to convert it back into a dataframe:
```python
import pandas as pd
response = {} # response from Hail Batch
dataframes = {
key: pd.DataFrame(data=values['data'], columns=values['columns'])
for key, values in response.items()
}
```
I tested this in on a dev deploy and it worked pretty well, but happy to add testing if you can direct me to a place to add it.
> [batch] Add resource_usage endpoint for jobs

- hail/src/main/scala/is/hail/expr/ir/BaseIR.scala
- hail/src/main/scala/is/hail/expr/ir/Binds.scala
- hail/src/main/scala/is/hail/expr/ir/DeprecatedIRBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/test/scala/is/hail/expr/ir/FakeTableReader.scala
- hail/src/test/scala/is/hail/expr/ir/MatrixIRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
- hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala
- hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
Makes some further progress on simplifying the `PruneDeadFields` pass, with the primary goal of decoupling it from the details of the binding structure.
The primary change is to `memoizeValueIR`. Before, it passed in only the requested type of the node, and returned and environment containing all free variables and their requested types. Any bound variables would then need to be removed, and the environments of all children then merged. This low-level manipulation of environments made it closely tied to the binding structure, essentially redundantly encoding everything in `Binds.scala`.
Now we pass an environment down into the children, which maps variables to a mutable state tracking the requested type. Each `Ref` node unions the requested type at the reference with the state in the …
> [compiler] simplify PruneDeadFields

- internal-gateway/Makefile
#14524 changed the argv for `envoy.py` and I missed the invocation in the bootstrapping process for `internal-gateway`. A grep for `envoy.py` shows both usages now using the correct arguments
> [internal-gateway] Fix bootstrap invocation

- hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
When trying to create a dataproc cluster using the results of `make -C hail install-editable` and `make -C hail install-hailctl`, the Jupyter server can't be connected to because it runs into the error described [here](https://stackoverflow.com/questions/77549493/modulenotfounderror-no-module-named-jupyter-server-contents). This change bumps the version of `notebook` that we use in the `init_notebook.py` script in order to make that work again.
> [dataproc] bumps version of notebook

- hail/src/main/scala/is/hail/services/package.scala
Additional transient errors from GCS
> [query] Add more transient error handling

- infra/gcp-broad/main.tf
I manually changed the Cloud SQL automated backups storage from the `us` multi-region to `us-central1`. There's no reason to store it in a multi-region and it's more expensive. What I didn't realize is that this configuration is actually owned by the terraform that we have managing the lifecycle of the database and other infra, so we need to update the terraform to reflect the desired (and current) state.
> [infra] Update GCP DB terraform to reflect backup region change

- hail/python/hail/vds/combiner/combine.py
- hail/python/hail/vds/combiner/variant_dataset_combiner.py
- hail/python/hail/vds/methods.py
- hail/python/test/hail/vds/test_combiner.py
CHANGELOG: The gvcf import stage of the VDS combiner now preserves the GT of reference blocks. Some datasets have haploid calls on sex chromosomes, and the fact that the reference was haploid should be preserved.
> [vds/combiner] Stop dropping GT in reference data during gvcf import

- hail/python/hail/expr/functions.py
- hail/python/test/hail/expr/test_ndarrays.py
Fixes: #14559
`hl.nd.array`s constructed from stream pipelines can cause out of memory exceptions owing to a limitation in the python CSE algorithm that does not eliminate partially redundant expressions in if-expressions. Explicitly `let`-binding the input collection prevents it from being evaluated twice: once for the flattened data stream and once for the original shape.
> [query] Let-Bind Input Collection Parameter In `hl.nd.array`.

- build.yaml
Fixes paths missed by https://github.com/hail-is/hail/pull/14565
> [ci] fix mount paths for `start_hail_benchmark` task

- hail/python/hail/vds/combiner/combine.py
`make_variants_matrix_table` and `make_variant_stream`, shared a function for processing entries. As did `make_reference_matrix_table` and `make_reference_stream`. This deduplicates that functionality by lifting out the internal functions to top level definitions.
> [vds/combiner] Deduplicate functions in combiner internals

- hail/python/hail/backend/local_backend.py
- hail/python/hail/backend/service_backend.py
- hail/python/hail/backend/spark_backend.py
- hail/python/hailtop/aiotools/validators.py
- hail/python/hailtop/batch/backend.py
- hail/python/hailtop/batch/batch.py
We use `nest_asyncio` to allow synchronous blocking on a coroutine execution inside an async context. For example, if a user is using the synchronous interface of hail inside a jupyter cell (which runs an event loop). `nest_asyncio` achieves this by patching the `asyncio` event loop to make it reentrant, and with that there are footguns. This allows us to do things like create 100 tasks that all concurrently invoke `run_until_complete`, each of which will add stack frames to the event loop stack that can pile up and trigger a cryptic `RecursionError`.
But internally we never *need* to make concurrent calls to `run_until_complete`, and more broadly we should never have `async / sync / async` inside hail code. This change exposes an asynchronous `validate_file` so that asynchronous methods …
> [hailtop] Prevent event loop RecursionError during highly concurrent file uploads

- batch/batch/front_end/query/query_v1.py
- batch/batch/front_end/query/query_v2.py
These queries are responsible for getting the paginated list of jobs in the batch UI. I believe this missing order by went unnoticed because the queries were naturally getting returned in order based on the jobs primary key, but we've recently seen a couple page loads of jumbled or missing jobs. Seems like something around the query stats changed and the database adjusted its plan slightly. Regardless, we want this order by explicit.
> [batch] Sort jobs by job id in the UI

- hail/build.sc
- hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
> [query] Remove string length restriction in jackson

- batch/batch/front_end/templates/batch.html
- batch/batch/front_end/templates/batches.html
- batch/batch/front_end/templates/billing_limits.html
- batch/batch/front_end/templates/job.html
The original UI redesign was intended to make it easier to navigate and focus on important information. I received very positive feedback on some aspects like this, for example having the different job steps in separate tabs. There was also feedback though that there was a lot of dead space. This is an attempt to find a good middle ground where the UI is not overwhelmingly cluttered but is more compact and makes better use of screen real estate
> [batch] Adjust Batch UI to have less dead space

- hail/python/hail/backend/backend.py
- hail/src/main/scala/is/hail/HailFeatureFlags.scala
- hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
We seem to be running into spark/yarn scheduling limitations causing stages to often fail with a large number of partitions. Here, we implement a very simple chunking strategy to run spark jobs with a limited number of partitions at a time.
The maximum parallelism is controlled by a new `spark_max_stage_parallelism` feature flag, which defaults to MAXINT until we can figure out a good default.
Also, this change corrects a small error in logic for partition indices for call caching. The `resultHandler` argument of [`runJob`] is called with the job's partition index, not the index of the partition within the RDD. So we need to index into the `partitions` sequence when populating the results buffer.
CHANGELOG: Add 'spark_max_stage_parallelism' flag to allow users to run pipelines with a …
> [query] Chunk spark backend execution

- hail/python/test/hail/vds/test_vds.py
#14560 updated `to_dense_mt` to take into account reference the existence of reference GT fields. However, it was untested. I take our old `test_to_dense_mt` test, and add a haploid `LGT` field to the reference, and check to make sure that the haploid reference is present in the result.
> [vds] add haploid to_dense_mt test

- hail/python/hailtop/batch/job.py
See #14576 for full details, this is another instance of the batch client improperly blocking on coroutines from within our own async code.
> [batch] Async _compile should use async read_input

- batch/batch/cloud/gcp/driver/disks.py
- batch/batch/cloud/gcp/driver/zones.py
- hail/python/hailtop/aiocloud/aiogoogle/client/compute_client.py
Workers can dynamically attach disks to themselves to accommodate jobs that request storage that the VM cannot accommodate. In certain circumstances like preemption, the VM can disappear before it is able to delete its own disks, so the Batch Driver scans for disks that are no longer attached (orphaned) and deletes them. It looks like our disk cleanup loop was broken due to inadvertent mutation that leads to an assertion error if the same `params` argument is used in multiple invocations of `GoogleComputeClient.list`. This is preventing orphaned disks from being deleted, costing us money. Additional details are in #14613.
Fixes #14613
> [batch] Fix accidental mutation in GoogleComputeClient.list that broke disk cleanup

- auth/Dockerfile
Auth's css is broken because the css isn't compiled in the docker image (something that the local dev server does not test). I deployed this into my namespace to make sure that the css inside the docker image works.
> [auth] Add compiled tailwind css to docker image

- build.yaml
- ci/ci/ci.py
- ci/ci/envoy.py
- ci/ci/templates/namespaces.html
- ci/sql/add-service-rate-limits.sql
- ci/sql/estimated-current.sql
- ci/test/envoy/test_gateway_rds_response.yaml
- ci/test/envoy/test_internal_gateway_rds_response.yaml
- ci/test/test_envoy.py
- dev-docs/services/gateways.md
This adds a control to CI where an operator can adjust the rate limit on a particular service in a particular namespace. CI stores and propagates that information when it generates the Envoy configs for `gateway` and `internal-gateway`. This enables operators to shield an overwhelmed batch driver by decreasing its rate limit without needing to push a code change. Increasing the rate limit can increase throughput if workers are being rate limited but the batch driver is not fully utilized.
> [ci] Add operator knob to adjust rate limits

- ci/ci/envoy.py
- ci/test/envoy/test_gateway_cds_response.yaml
- ci/test/envoy/test_gateway_rds_response.yaml
- ci/test/envoy/test_internal_gateway_cds_response.yaml
- ci/test/envoy/test_internal_gateway_rds_response.yaml
- ci/test/test_envoy.py
#14609 broke the routing for https://hail.is. The `domains` variable here indicates to `gateway` which domains in incoming requests should be routed to the given service. Since #14609 changed the `service` parameter from `str` to `Service`, it silently broke this branch.
This wasn't covered by the envoy config generation tests because we didn't have a `www` service in the test configuration. I've added it so that this branch is covered.
Fixes #14616
> [gateway] Fix top level domain for website

- hail/python/hailtop/auth/flow.py
Fixes #14634. Always prompt for which google account to use during login. Avoids confusion over whether logout succeeded or not (especially considering #14635)
> [Auth] Always select user during login prompt

- hail/python/hailtop/hailctl/dataproc/cli.py
- hail/python/hailtop/hailctl/dataproc/submit.py
Closes https://github.com/hail-is/hail/issues/14647.
> [dataproc] adds project to args for submit

- batch/batch/front_end/query/query.py
- batch/batch/front_end/query/query_v2.py
This reverts commit 21ad23a70a804d6424319b61d9c741f89d4db9ae.
(partially) Resolves #14599
> Revert "[batch] make batches query go brrrrrrr (#14629)"

- admin-pod/Makefile
The `admin-pod-image` target just builds the docker image locally, so just using that results in the pod failing to pull an image that does not exist where the cluster does. We want to push the image, hence `pushed-private-admin-pod-image`, and then use that pushed image name in the pod manifest.
Fixes #14642
> [admin-pod] Fix admin-pod Makefile to push pod image

- auth/auth/templates/user.html
- web_common/web_common/templates/new_header.html
Fixes #14635. Logout is only possible from `auth` pages due to per-subdomain CRSF tokens. Security/design thought process as documented in a comment on the issue: https://github.com/hail-is/hail/issues/14635#issuecomment-2253086187
> [UI] Remove broken Log out; provide another option

- batch/batch/front_end/query/query_v2.py
#14629 improved the speed of listing a user's batches but introduced a large
regression for listing all batches readble by that user. This change fixes that
regression by making use index hints and `STRAIGHT_JOIN`s.
The index hint tells MySQL to never consider the index `batches_deleted` as it
has very low cardinality. In some forms of this query, the planner tries to use
it to its peril.
A problem in query 0 with #14629 (see below) was that fewer filters on batches
made the optimiser consider joins in a suboptimal order - it did a table scan 
on `job_groups` first then sorted the results by to `batches.id DESC` instead
of doing an index scan on `batches` in reverse.
Using `STRAIGHT_JOIN`s instead of `INNER JOIN` mades the optimiser start from
`batches` and read its index in reverse …
> [batch] make batches query go brrrrrrr (for realsies)

- hail/python/hailtop/hailctl/dataproc/cli.py
- hail/python/hailtop/hailctl/dataproc/start.py
Closes https://github.com/hail-is/hail/issues/14652.
See https://github.com/populationgenomics/hail/pull/346. Thanks for the contribution @illusional!
Gives Dataproc clusters started via `hailctl dataproc start` internet access by default, since we need it to install some of our dependencies, per the error message in the linked issue.
> Passes `--public-ip-address` to `hailctl dataproc start`

- batch/batch/front_end/templates/batch.html
- batch/batch/front_end/templates/batches.html
- web_common/input.css
- web_common/web_common/templates/utils.html
Screenshots should give the main overview of the changes
Questions for reviewers.
Technical:
UX:
- to help with layout within the batch-name box
- to put it in a reliable place (ie not moving around based on how long the name is)
(layout and columns)
(Renaming confusing 'Pending' field)
Fixes #14628. Adds and shuffles content on the new Batches table
> [UI] Batches UI Improvements

- ci/ci/github.py
Fixes #14660 by using the graphQL API to query github directly. Replaces our current parallel interpretation of reviews into a review decision, which is brittle if we ever change review requirements in github again.
Tested by manually updating the live CI to use the test batch generated image. Results:
- Review decisions correctly fetched from github, not based on CI's parallel interpretation of individual reviews:
- No merge candidate was being incorrectly nominated (in particular, #14645 is now considered pending, rather than approved, which is what we are currently, incorrectly, calculating)
> [CI] Use github's graphQL to query review state directly

- dev-docs/development-process.md
Based on the discussions [here](https://hail.zulipchat.com/#narrow/stream/300487-Hail-Batch-Dev/topic/create.20initial.20account/near/268756206).
It seems that this is not the most desirable **_eventual_** state, but for now, it seems better to document this than ignore it.
> [Docs, Batch] Document need for copying keys in developer namespaces

- ci/ci/envoy.py
See https://github.com/hail-is/hail/pull/14617. This change applies the same fix to the routing for the `ukbb-rg` subdomain.
> [services/ukbb-rg] fixes routing

- build.yaml
- ci/ci/build.py
The `delete_azure_batch_instances` step is failing on various PRs with the error `jq: command not found`. This appears to be because we do not pin the version for the `mcr.microsoft.com/azure-cli` image, and while that image was previously based on the Alpine image, [now it is based on the Azure Linux image](https://learn.microsoft.com/en-us/cli/azure/run-azure-cli-docker), and does not appear to have `jq` (or `kubectl`) preinstalled on it.
This change updates the commands run in the `azure-cli` container for this CI step to install `jq` and `kubectl` via `curl` before running the relevant commands. The `curl` commands were tested locally by running `docker run -it mcr.microsoft.com/azure-cli` and trying them out in the image's shell.
This change also adds the installation commands in the …
> [ci/azure] installs dependencies for azure-cli image

- hail/python/hail/backend/py4j_backend.py
Contains dangeling reference to `pyIndexBgen`, deleted since 92e4776
> [query] delete stale `Py4JBackend/index_bgen`

- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
There was a typo in the `Interpret` rule for `TableAggregate` which had it refer to the row instead of the globals inside the init op.
I tried to add a test for this, but it's frustratingly difficult to force the compiler to go through this code path. Even when using an `InterpretOnly` compilation, the lowering pipeline often lifts `TableAggregate` to a `RelationalLet`, and then evaluates it, using the compiler not the interpreter. This is a deeper issue we should address, but a user is currently blocked on this bug so I don't want to hold it up.
> [query, bugfix] TableAggregate interpret supports globals in init op

- hail/python/hail/vds/methods.py
- hail/python/test/hail/vds/test_vds.py
After split_multi, LGT is dropped from the variant data of a VDS. After PR #14560, LGT is added to datasets after creation via the combiner. After #14675 the same is true for `from_merged_representation`. We should keep the GT/LGT field consistent across ref and var data. This change does so for split_multi.
Resolves #14694
> [vds] Unify GT/LGT after split_multi for reference data

- .github/ISSUE_TEMPLATE/change-request.yml
- .github/pull_request_template.md
For feedback - a couple of potential templates for capturing security impacts at either the issue or PR level.
> [Github] Security impact field in templates

- dev-docs/services/services-development-faq.md
Adding devserver instructions to the developer FAQ to avoid having to search zulip history for this command in future (and also document a little about how it works)
> [Docs] devserver documentation

- ci/ci/constants.py
Seems like only yesterday that we had #14668
Also removes @illusional as I believe he's no longer in a contributing role (... but please shout out if you disagree! And cc @jmarshall)
Removes entries from the allow-list of contributors and recommended reviewers.
> [CI] Remove Iris and M Franklin from authorized users and teams lists

- ci/Dockerfile.ci-utils
- docker/hail-ubuntu/Dockerfile
See https://cloud.google.com/sdk/docs/install#deb
> [ci-utils] Use google's apt repo to install gcloud and kubectl

- hail/python/hail/vds/combiner/combine.py
- hail/python/hail/vds/combiner/variant_dataset_combiner.py
- hail/python/hail/vds/variant_dataset.py
- hail/python/test/hail/vds/test_combiner.py
- hail/python/test/hail/vds/test_vds.py
This is the beginning of a series of changes to support export of VDS to VCF 4.5, the version of VCF that contains the standardized form of our work that culminated in SVCR/VDS.
Reference blocks were standardized with a LEN rather than an END. So, now, by default, add LEN to all VDS reads and drop END in favor of LEN on all VDS writes. Our optimizer will be able to take care of pruning away the dead field in pipelines that don't use it.
We make sure that all VDS creation (other than the combiner), such as read_vds and from_merged_representation, contains both LEN and END preserving user code that depends on the presence of the END field.
Furthermore, this change contains necessary combiner updates to prefer LEN over END, and to use LEN in the combiner itself.
>  [query/vds] Add LEN field to VDS 

- build.yaml
- hail/Makefile
Jobs within our CI pipeline often invoke `mill` indirectly through `Makefile` prerequisites.
By staging mill's build area to and from `/derived/{release/debug}/hail/out`, mill will not rebuild artefacts from previous steps.
Exposing `MILLOPTS` in `hail/Makefile` allows us to build in CI without a compilation server. 
Using a compilation server may have been why we experienced intermittent failures between building the jar and copying to its final destination.
Note that the `--no-server` option must be the first argument to `millw`.
Only derived files from the mill + python build process are staged and unstaged.
No secrets or otherwise sensitive information are contained therein.
(Reviewers: please confirm the security impact …
> [ci] preserve mill + python build area between ci stages

- build.yaml
The `letsencrypt` inputs to `batch_worker_image` are duplicated (though
the second time were localised to an unreachable location). 
These files were unreachable from the ci job.
> [ci] remove unused inputs to `batch_worker_image`

- build.yaml
- hail/python/test/hailtop/test_aiogoogle.py
In [09437c5](https://github.com/hail-is/hail/commit/09437c531b47c9af2faa196817c6edeaba17fced), I moved `pytest.ini` up a directory but didn't update the artefacts built in ci.
As a consequence, test stages like `test_unchecked_allocator` have not run since.
> [ci] test artefacts missing pytest.ini

- hail/python/hail/vds/methods.py
- hail/python/test/hail/vds/test_vds.py
- Use LEN for `to_dense_mt`. We still need to calculate a global position for the end of a reference block, but this version is cleaner.
- Update `truncate_reference_blocks`.
>  [vds] More updates for preferring LEN over END

- hail/python/hail/docs/cloud/amazon_web_services.rst
AWS no longer maintains the Hail on AWS quickstart.
This PR removes the reference to this now-broken documentation.
This PR removes broken documentation. There is no end user impact.
> Update Hail on AWS documentation

- hail/python/hail/vds/functions.py
- hail/src/main/scala/is/hail/expr/ir/functions/CallFunctions.scala
Noticed these during other work.
- For `local_to_global`, we already check for number being `A`, `G`, or `R` in typecheck, and it's not good python style to have an else clause after a return. 
- For `lgt_to_gt`, the case type matching is cleaner than the explicit conversion methods.
Query only changes that have identical functionality to previous code
> [query] code cleanup

- hail/python/hail/docs/install/dataproc.rst
This PR updates the tutorial instructions for running Hail on Dataproc to clarify that the Google Cloud SDK must be installed and configured before Hail can be run.
I made this change to prevent future users from also needing to Google these setup instructions.
This change only updates documentation and has no immediate end user impact.
The updated documentation does not leak any proprietary / confidential / sensitive information about Hail or any related systems.
> Improve documentation for Hail on Dataproc

- Makefile
- dev-docs/services/letsencrypt.md
Add section on authenticating to GKS+GAR and AKS+ACR and then setting the kubectl context to the appropriate cluster.
Note that the one should clean the letsencrypt image files created by make.
Only documentation changes.
> [dev-docs] More detailed certificate rotation instructions

- .github/ISSUE_TEMPLATE/new-developer.yml
This change has no security impact as it modifies githib issue templates.
> [github] include granting iam roles for new developers in issue template

- dev-docs/development-process.md
- devbin/rotate_keys.py
Corrects our gsa-key copying instructions (from #14664) to copy the key contents, not the entire secret metadata.
The batch service seems resilient to these badly formed secrets, but the rotate_keys.py script was not.
- Not a production change
- Does not add any new information to the secrets, only formats them a useable way. 
- Only in dev namespaces
> [Dev processes] Fixup gsa-key copying instructions, add debug line to rotate_keys.py

- hail/python/hail/methods/impex.py
'may or may not' is redundant phrasing. The word 'may' is sufficient to indicate the optional nature of glob expressions in the `path` argument to `import_vcf`
Docs only
> [query] Clarify import_vcf docs

- batch/pinned-requirements.txt
- ci/pinned-requirements.txt
- dev-docs/development-process.md
- gear/pinned-requirements.txt
- hail/python/dev/pinned-requirements.txt
- hail/python/dev/requirements.txt
- hail/python/hailtop/pinned-requirements.txt
- hail/python/pinned-requirements.txt
- web_common/pinned-requirements.txt
Replacing pyright with pyright[nodejs] in /dev/requirements.txt, allowing for installation of necessary node.js binaries to run pyright when one installs dev requirements.
As per https://pypi.org/project/pyright/, pyright needs node to run, but pip installing pyright doesn't also install node. Pyright acknowledges this, and they have a separate pip installation command that will also give you the necessary node binaries to run pyright. We now specify that proper pyright+node install in our requirements.txt.
Updating old pyright installation in /dev/requirements.txt, no impact on security-sensitive systems.
> [Dev processes] Replacing pyright with pyright[nodejs] in /dev/requirements.txt

- hail/python/hail/vds/__init__.py
- hail/python/hail/vds/impex.py
- hail/python/test/hail/vds/test_vds.py
Usage and notes in the documentation for the new methods.
Part of  #14655.
Does not increase attack surface. New methods only call into old ones.
> [query] Teach hail to export a VDS to an SVCR-VCF

- hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
It is no longer the case that VCF does not support phased haploid calls. Make a note of this in the code.
Change error messages only.
> [query] Update ExportVCF error messages

- batch/batch/cloud/gcp/driver/pricing.py
Stop importing prices for reserved resources. They cause clashes with our database primary keys and can never be part of user billing. (By definition, we can't be running jobs on reservations of future resources)
We are doing a simple string match and then choosing not to import something that we otherwise might have into our database. 
> [Batch Driver] Stop importing reserved resource prices

- hail/python/test/hail/test_ir.py
- hail/src/main/scala/is/hail/backend/service/Main.scala
resolves #14749
Leave the override in Backend as well to avoid duplication. Future enhancements may enable us to construct a ServiceBackend from argv alone, allowing this to be reverted.
This change restores known good functionality.
> [QoB] Set StreamReadConstraints maxStringLength as early as possible

- batch/batch/front_end/templates/batch.html
From @jmarshall on [zulip].
[zulip]: https://hail.zulipchat.com/#narrow/channel/223457-Hail-Batch-support/topic/Batch.20UI.20Previous.20Page.20button.20causing.20500.20Server.20Errors/near/481042141
Tiny change in logic in a template that doesn't add any new information to view/exploit.
> [batch] Check that batch jobs is nonempty in Previous Page button

- hail/Makefile
This change prevents packaging benchmark code in the hail wheel by updating the rsync exclude patterns in `hail/Makefile` to exclude `benchmark/`.
Low-level build configuration change that only affects which directories are excluded during file copying operations.
> [query] Exclude `benchmark/` from hail wheel

- hail/python/test/hail/expr/test_expr.py
- hail/src/main/scala/is/hail/expr/ir/agg/ApproxCDFStateManager.scala
Fixes a bug which was reported in https://discuss.hail.is/t/arrayindexoutofboundsexception-using-cdf-combine/4008/6.
The bug was caused by an unenforced invariant in the ApproxCDF aggregator state. Roughly, the state consists of a number of "levels" (stored flattened into a single array), where each level contains a number of samples from the data. There is also a notion of the "capacity" of each level. The data structure assumes that whenever the array containing the flattened levels becomes full, there must be at least one level which is above capacity, and can therefore be compacted to free space. In other words, the size of the array must be at least the sum of the capacities of the present levels.
In #13935, we changed the ApproxCDF aggregator to return the raw internal state, and …
> ApproxCDF bugfix

- build.yaml
We publish release artifacts independently of tests passing in the release pipeline. Flaky tests were causing the benchmarks to not run. This change takes the pragmatic view that if publishing does not depend on tests, then neither should starting the benchmark batch.
> [query] Run benchmarks after wheel is published to PyPI

- hail/src/test/scala/is/hail/HailSuite.scala
- hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/io/TabixSuite.scala
- hail/src/test/scala/is/hail/io/compress/BGzipCodecSuite.scala
- hail/src/test/scala/is/hail/utils/UtilsSuite.scala
- hail/src/test/scala/is/hail/variant/ReferenceGenomeSuite.scala
Factor out the location of the test resources directory in the scala tests, so we only need to change one place when we rearrange the directory structure.
Tests only
> don't hardcode paths to test resources

- auth/auth/auth.py
Updates the handling of the `next` query parameters on various auth URLs to only accept absolute paths within the same domain as the auth service or its equivalent batch service. Prevents a potential class of attacks exploiting unvalidated redirects.
For medium/high impact: provide a description of the impact and the mitigations in place.
Changes how an auth API works, but in a way that reduces its overall functional surface. Defends against inappropriate redirections following login.
> [auth] Validate next page urls

- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/MatrixIRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala
- hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
- hail/src/test/scala/is/hail/io/compress/BGzipCodecSuite.scala
- hail/src/test/scala/is/hail/methods/LocalLDPruneSuite.scala
- hail/src/test/scala/is/hail/variant/ReferenceGenomeSuite.scala
#14775 missed some places in the scala tests where the test resources directory is hardcoded. This fixes the remaining cases.
Tests-only change
> [query] don't hardcode paths to test resources, cont'd

- .gitignore
Removes `*.out` from our `.gitignore`. There are files in our test resources directory with a `.out` extension.
Only affects commit creation
> [query] remove *.out from .gitignore

- hail/python/hail/backend/py4j_backend.py
- hail/python/hail/ir/ir.py
- hail/python/hail/ir/table_ir.py
- hail/python/test/hail/genetics/test_reference_genome.py
- hail/src/main/scala/is/hail/backend/Backend.scala
- hail/src/main/scala/is/hail/backend/BackendServer.scala
- hail/src/main/scala/is/hail/backend/ExecuteContext.scala
- hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
- hail/src/main/scala/is/hail/backend/py4j/Py4JBackendExtensions.scala
- hail/src/main/scala/is/hail/backend/service/Main.scala
- hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
- hail/src/main/scala/is/hail/backend/service/Worker.scala
- hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
- hail/src/main/scala/is/hail/variant/ReferenceGenome.scala
- hail/src/test/scala/is/hail/HailSuite.scala
- hail/src/test/scala/is/hail/backend/ServiceBackendSuite.scala
- hail/src/test/scala/is/hail/expr/ir/StagedMinHeapSuite.scala
- hail/src/test/scala/is/hail/expr/ir/lowering/LowerDistributedSortSuite.scala
Refactors backend code to improve separation of concerns by extracting Python-specific functionality into a new `Py4JBackendExtensions` trait. This change consolidates Python interface methods that were previously scattered across different backend implementations into a single shared trait.
The change also improves reference genome handling by making the references map mutable and passing it explicitly through constructors rather than modifying it after creation.
Low-level refactoring of internal backend code that moves functionality between classes without changing behavior. No changes to external interfaces or security boundaries.
> [query] Extract Backend Methods called from Python into `Py4JBackendExtensions`

- build.yaml
The `check_hail` CI job is failing routinely. 
Resource usage plots show that the jobs are hitting their 4G memory limit. 
Downloading more ram should help.
> [ci] download more ram for `check_hail`

- auth/auth/auth.py
Addresses a bug introduced in #14776 which didn't allow `ci` or `monitoring` as valid "next" urls
Additional `next_url`s are allowed, but they are still tightly constrained to the standard set of hail services.
> [auth] Allow ci and monitoring as valid next_urls in auth flows

- hail/hail/src/is/hail/types/virtual/TArray.scala
- hail/hail/src/is/hail/types/virtual/TBaseStruct.scala
- hail/hail/src/is/hail/types/virtual/TBinary.scala
- hail/hail/src/is/hail/types/virtual/TBoolean.scala
- hail/hail/src/is/hail/types/virtual/TCall.scala
- hail/hail/src/is/hail/types/virtual/TDict.scala
- hail/hail/src/is/hail/types/virtual/TFloat32.scala
- hail/hail/src/is/hail/types/virtual/TFloat64.scala
- hail/hail/src/is/hail/types/virtual/TInt32.scala
- hail/hail/src/is/hail/types/virtual/TInt64.scala
- hail/hail/src/is/hail/types/virtual/TInterval.scala
- hail/hail/src/is/hail/types/virtual/TLocus.scala
- hail/hail/src/is/hail/types/virtual/TNDArray.scala
- hail/hail/src/is/hail/types/virtual/TRNGState.scala
- hail/hail/src/is/hail/types/virtual/TSet.scala
- hail/hail/src/is/hail/types/virtual/TStream.scala
- hail/hail/src/is/hail/types/virtual/TString.scala
- hail/hail/src/is/hail/types/virtual/TUnion.scala
- hail/hail/src/is/hail/types/virtual/TVariable.scala
- hail/hail/src/is/hail/types/virtual/TVoid.scala
- hail/hail/src/is/hail/types/virtual/Type.scala
A project-wide search showed no uses.
> [query] remove unused `scalaClassTag` method on `Type`

- .gitignore
Restore *.out to .gitignore, with an exclusion in resource directories
Only changes gitignore rules
> restore *.out to .gitignore, except in resources

- auth/auth/auth.py
- auth/auth/templates/user.html
- gear/gear/auth.py
- web_common/web_common/templates/header.html
- web_common/web_common/templates/new_header.html
Changes login flow in the UI to go via the user page, which gives us a chance to show (and require acceptance of) the terms of service:
Notes to reviewers:
- It should not be possible to log in via the UI except via the `/user` page (ignoring direct url-surfing to the `/login` url)
- The next_url mechanism should continue to work as before (ie navigate to `/batches` > prompted to login > login success > should end up on the batches page)
Moves the login button and updates some redirects, but does not fundamentally alter anything about the login flow.
> [auth] Require tos acceptance on UI login

- hail/hail/src/is/hail/HailFeatureFlags.scala
- hail/hail/src/is/hail/backend/Backend.scala
- hail/hail/src/is/hail/backend/ExecuteContext.scala
- hail/hail/src/is/hail/backend/local/LocalBackend.scala
- hail/hail/src/is/hail/backend/py4j/Py4JBackendExtensions.scala
- hail/hail/src/is/hail/backend/service/ServiceBackend.scala
- hail/hail/src/is/hail/backend/spark/SparkBackend.scala
- hail/hail/src/is/hail/expr/ir/EmitClassBuilder.scala
- hail/hail/src/is/hail/expr/ir/ExtractIntervalFilters.scala
- hail/hail/src/is/hail/expr/ir/MatrixValue.scala
- hail/hail/src/is/hail/io/plink/LoadPlink.scala
- hail/hail/src/is/hail/io/reference/FastaSequenceIndex.scala
- hail/hail/src/is/hail/io/reference/IndexedFastaSequenceFile.scala
- hail/hail/src/is/hail/io/reference/LiftOver.scala
- hail/hail/src/is/hail/io/vcf/LoadVCF.scala
- hail/hail/src/is/hail/variant/ReferenceGenome.scala
- hail/hail/test/src/is/hail/HailSuite.scala
- hail/hail/test/src/is/hail/annotations/UnsafeSuite.scala
- hail/hail/test/src/is/hail/expr/ir/ExtractIntervalFiltersSuite.scala
- hail/hail/test/src/is/hail/expr/ir/IRSuite.scala
- hail/hail/test/src/is/hail/expr/ir/LocusFunctionsSuite.scala
- hail/hail/test/src/is/hail/expr/ir/RequirednessSuite.scala
- hail/hail/test/src/is/hail/expr/ir/StagedMinHeapSuite.scala
- hail/hail/test/src/is/hail/expr/ir/lowering/LowerDistributedSortSuite.scala
- hail/hail/test/src/is/hail/utils/FlipbookIteratorSuite.scala
- hail/hail/test/src/is/hail/variant/LocusIntervalSuite.scala
- hail/hail/test/src/is/hail/variant/ReferenceGenomeSuite.scala
This change is split out from a larger refactoring effort on the various Backend 
implementations. The goals of this effort are to provide query-level 
configuration to the backend that's currently tied to the lifetime of a backend,
reduce code duplication and reduce state duplication.
In this change, I'm restoring references to the execute context [1] and 
decoupling them from the backend. In a future change, they'll be lifted out of 
the backend implementations altogether. This is to reduce the surface area of 
the Backend interface to the details that are actually different.
Both the Local and Spark backend have state that's manipulated from python via 
various py methods. These pollute the Backend interface [2] and so have been 
extracted into the trait Py4JBackendExtensions. In …
> [query] Expose references via `ExecuteContext`

- hail/python/hailtop/batch/batch.py
- hail/python/hailtop/utils/__init__.py
- hail/python/hailtop/utils/utils.py
- pylintrc
Extends PR #14544 which did this for read_input()/read_input_group().
Refactor type coercion previously added to _new_input_resource_file()
into a new hailtop.utils.path_str() utility routine, and also invoke
it from Batch.write_output().
- This change has low security impact
Client side change only. Standard function call on a standard library class. Analogous to existing calls for similar functionality.
> Allow os.PathLike paths for Batch.write_output()

- hail/python/hail/vds/combiner/variant_dataset_combiner.py
> [vds/docs] Fix erroneous gvcf_batch_size description

- auth/auth/auth.py
- auth/auth/exceptions.py
Moves validation of usernames to the front-end, so invalid username requests never get into the database and block driver processing of new user requests.
Low because we are removing a path to a possible error state.
> [auth] Validate usernames upfront

- hail/hail/src/is/hail/backend/service/ServiceBackend.scala
- hail/hail/src/is/hail/services/BatchClient.scala
- hail/hail/test/src/is/hail/services/BatchClientSuite.scala
Fixes #14597
cancel_after_n_failures = 1; cancels whole job group if one partition fails.
Unit tests and no interaction on anything secure.
> [qob] cancel stage if any partitions fail.

- hail/python/hail/expr/expressions/typed_expressions.py
- hail/python/test/hail/expr/test_expr.py
Either set construction from an iterator or set difference is not order preserving. If we iterate through the struct fields in order, then our select inside of rename will preserve order for existing fields.
Brief description and justification of what this PR is doing.
Query only. Simply causes a single iteration to happen in a different order.
> [query] Preserve field order in StructExpression.rename

- hail/hail/src/is/hail/expr/ir/TableIR.scala
- hail/hail/src/is/hail/io/bgen/BgenRDDPartitions.scala
- hail/hail/src/is/hail/io/bgen/BgenSettings.scala
- hail/hail/src/is/hail/io/bgen/LoadBgen.scala
- hail/hail/src/is/hail/io/bgen/StagedBGENReader.scala
- hail/hail/src/is/hail/io/index/StagedIndexReader.scala
For legacy reasons, the data contained by an index leaf node includes a field called `offset` and another called `annotation`. The `offset` is always an int64, and `annotation` contains arbitrary data. When writing a matrix table, we use a field in `annotation` called `entries_offset`. In the index spec, we make a note of if there is a different offset than `offset`.
This means, that if we have an index spec, we can't assume that the offset field is always `offset`, and so, add a helper method that takes a leaf node, and give us the offset the index spec is expecting.
Code generated is identical to previous version.
> [query] StagedIndexReader now requires an index spec

- batch/batch/cloud/gcp/driver/billing_manager.py
- batch/batch/cloud/gcp/driver/pricing.py
Allows the system to start up even if price refreshing fails. This is temporary until we can stop the latest set of SKU collisions 
Ignore parsing / interpretation errors .
> [batch] Allow startup if price-refreshing fails

- gear/gear/auth.py
Currently: when a user's session times out or becomes invalid for any reason, they are redirected to a login page which (because of the existing but stale session cookie) just returns 401: Unauthorized.
With this change: we allow users with invalid or stale session cookies to access the user page and re-login
Allow access to pages that previously would have failed when a user's session was invalid. 
However: 
- The pages in question are accessible for unauthorized users
- We treat the page access as though the user were unauthorized
So this is essentially equivalent to the user clearing out their cookie cache before attempting to access the page.
> [auth] Allow re-login after session timeout

- batch/batch/driver/billing_manager.py
Allows the system to start up even if price refreshing fails. This is temporary until we can stop the latest set of SKU collisions 
Ignore parsing / interpretation errors .
> [batch] Allow startup if price-refreshing fails 

- hail/hail/src/is/hail/backend/Backend.scala
- hail/hail/src/is/hail/backend/ExecuteContext.scala
- hail/hail/src/is/hail/backend/local/LocalBackend.scala
- hail/hail/src/is/hail/backend/service/ServiceBackend.scala
- hail/hail/src/is/hail/backend/spark/SparkBackend.scala
- hail/hail/src/is/hail/expr/ir/Compile.scala
- hail/hail/src/is/hail/expr/ir/CompileAndEvaluate.scala
- hail/hail/src/is/hail/expr/ir/Emit.scala
- hail/hail/src/is/hail/expr/ir/Interpret.scala
- hail/hail/src/is/hail/expr/ir/TableIR.scala
- hail/hail/src/is/hail/expr/ir/agg/Extract.scala
- hail/hail/src/is/hail/expr/ir/lowering/LowerDistributedSort.scala
- hail/hail/src/is/hail/expr/ir/lowering/RVDToTableStage.scala
- hail/hail/src/is/hail/utils/Cache.scala
- hail/hail/test/src/is/hail/TestUtils.scala
- hail/hail/test/src/is/hail/expr/ir/Aggregators2Suite.scala
- hail/hail/test/src/is/hail/expr/ir/EmitStreamSuite.scala
In the spirit of shrinking the `Backend` functionality to a core set of functions, move code cache access via execute context.
> [query] Remove `lookupOrCompileCachedFunction` from `Backend` interface

- hail/hail/src/is/hail/backend/service/ServiceBackend.scala
- hail/hail/src/is/hail/backend/service/Worker.scala
- hail/hail/src/is/hail/services/BatchClient.scala
- hail/hail/src/is/hail/utils/ErrorHandling.scala
- hail/hail/test/src/is/hail/backend/ServiceBackendSuite.scala
- hail/hail/test/src/is/hail/services/BatchClientSuite.scala
-  Added ability to check job status in individual jobs in a JobGroup
- Cancel JobGroup if any jobs in the partition fail
- Added test functionality for detecting cancelled, failed jobs
- Query batch for which jobs have failed within a JobGroup, rather than go through every job in the group.
Mainly just code for testing, nothing security related
> [query] Improve error handling and job tracking in ServiceBackend

- batch/batch/worker/worker.py
Currently, the available shared memory (/dev/shm) in a Docker image is capped at 64M by default. On a regular machine, this is instead capped at half the machine's available RAM. While there exists a flag you can specify during `docker run` that can increase your `/dev/shm`, this change modifies the default shared memory in a container to now be half the available memory.
Memory usage comparison allocating 512M to `/dev/shm`:
Prior to this change, allocation capped at 64M:
```
free -m
df -h
dd if=/dev/zero of=/dev/shm/file bs=512M count=1
total        used        free      shared  buff/cache   available
Mem:           60262        5407       48518           2        7017       54855
Swap:              0           0           0
Filesystem      Size  Used Avail Use% Mounted on
overlay …
```
> [batch] increase shared memory in a container to be up to half the actual memory

- build.yaml
- hail/Makefile
This allows the test-dataproc steps to use these artifacts.
Minor change to build steps.
>  [ci] Upload hailctl artifacts after building the release mode jar/wheel 

- hail/python/hail/ir/ir.py
`uses_agg_randomness` is a method, not a property, so we need to call it in the StreamAgg `__init__`, otherwise, we're just passing the bound method object or using it as a boolean.
Internal API change
> [query] Fix randomness handling in StreamAgg

- hail/hail/src/is/hail/backend/Backend.scala
- hail/hail/src/is/hail/backend/ExecuteContext.scala
- hail/hail/src/is/hail/backend/local/LocalBackend.scala
- hail/hail/src/is/hail/backend/service/ServiceBackend.scala
- hail/hail/src/is/hail/backend/spark/SparkBackend.scala
- hail/hail/src/is/hail/expr/ir/GenericTableValue.scala
- hail/hail/src/is/hail/expr/ir/TableIR.scala
Refactored table reader coercion and caching mechanism.
- Removed `shouldCacheQueryInfo` method from `Backend` class
- Introduced `CoercerCache` in `ExecuteContext`
- Refactored `LoweredTableReader.makeCoercer` to return a function instead of a class
- Removed local caching in `GenericTableValue` and `LoweredTableReader`
This change aims to optimize table reader coercion by:
- Centralizing caching logic in `ExecuteContext`
- Allowing more flexible caching strategies across different backend implementations
> [query] Move LoweredTableReaderCoercer into ExecuteContext

- auth/auth/auth.py
- auth/auth/auth_utils.py
- auth/test/test_auth_utils.py
Addresses #14840 by allowing well-placed hyphens in usernames again. Not required for the Broad deployment but is perfectly safe to do, and was blocking external collaborators whose usernames frequently require hyphens.
Modifies the set of usernames allowed, but only by allowing well-placed individual hyphens, which will still produce "url valid" downstream resource names.
> [auth] Allow (non-adjacent) hyphens in usernames

- hail/python/pinned-requirements.txt
- hail/python/requirements.txt
It seems to have been erroneously re-added in #14158
Fixes problem reported on Zulip.
Removal of unnecessary dependency.
> [pip] Re-remove hail's protobuf dependency.

- hail/hail/src/is/hail/expr/ir/Copy.scala
- hail/hail/src/is/hail/expr/ir/IR.scala
- hail/hail/src/is/hail/expr/ir/Requiredness.scala
- hail/hail/src/is/hail/expr/ir/functions/Functions.scala
- hail/hail/src/is/hail/expr/ir/functions/ReferenceGenomeFunctions.scala
- hail/hail/src/is/hail/expr/ir/package.scala
- hail/hail/test/src/is/hail/expr/ir/FunctionSuite.scala
This PR refactors the `ApplyIR` node to behave more consistently with the rest of the IR nodes. In particular, before this change it had mutable fields `conversion` and `inline` which were not set in the constructor (instead being set after construction by the function registry), but were copied by the `Copy` implementation.
The primary changes are as follows:
* Functions can be registered with polymorphic types. We previously supported also looking up functions with polymorphic signatures. However, I noticed that we only ever look up concrete signatures. This allowed me to make several simplifications.
* Instead of caching the implementation in the `ApplyIR` node, and preserving the cached implementation across copies, I now simply re-lookup the implementation in the function registry as …
> [compiler] refactor ApplyIR

- hail/hail/src/is/hail/expr/ir/NormalizeNames.scala
- hail/hail/src/is/hail/expr/ir/package.scala
Fixes a bug that was reported in [zulip](https://hail.zulipchat.com/#narrow/channel/123010-Hail-Query-0.2E2-support/topic/Type.20error.20with.20ht.2Eshow.28.29).
Background: we use a function `freshName` to generate names to use in the IR which are guaranteed to not already be in use in the IR. We do that by maintaining a global variable counting the number of fresh names ever generated, and `freshName` returns the string `s"__iruid_$i"`. `NormalizeNames` changes all the names used in the IR such that any name is defined at most once in the IR. It is also currently required to be deterministic, so that two IRs which are equal up to the choice of variable names (they are alpha equivalent) will be strictly equal after normalizing names. It does this by maintaining a local counter of how …
> [compiler] fix a bug in NormalizeNames

- build.yaml
- hail/python/hail/backend/py4j_backend.py
- hail/python/pytest.ini
- hail/python/test/hail/backend/test_spark_backend.py
- hail/python/test/hail/conftest.py
- hail/python/test/hail/fs/test_worker_driver_fs.py
- hail/python/test/hail/helpers.py
- hail/python/test/hail/test_context.py
A number of tests require hail be unitialised and call `hail.stop`. This change
- provides a mechanism to do that automatically
- separates running tests in test/hailtop from test/hail as pytest was mixing `conftest.py`
in non-obvious ways. 
This change affects test code only and thus has low security impact.
> [query] Add `unitialized` pytest marker to initialisation tests

- hail/python/hail/backend/service_backend.py
- hail/python/hail/context.py
- hail/python/test/hail/backend/test_service_backend.py
- hail/python/test/hail/experimental/test_annotation_db.py
- hail/python/test/hailtop/batch/test_batch_service_backend.py
The goal of this change is to be able to group QoB queries together to allow for
easier visibility of how much a pipeline costs as well as make the batches page
less cluttered so it's easier to tell what is running.
Adds `batch_id` parameter to `hl.init` that, when used with the `'batch'` backend, 
allows users to add query-on-batch jobs to an existing batch. Note that racing two
or more QoB jobs concurrently in the same batch will likely fail. Instead, users
should add dependences between query jobs so that they're scheduled consecutively.
This change has low security impact as it only modifies client code: users cannot
attach to batches that they do not already have access to.
> [qob] Add ability to attach to existing batch

- hail/hail/src/is/hail/expr/ir/Casts.scala
- hail/hail/src/is/hail/expr/ir/Simplify.scala
- hail/hail/test/src/is/hail/expr/ir/SimplifySuite.scala
Fixes #14868
Marks some casts as being lossless, and only allows simplifying a t1->t2->t1 cast when the t1->t2 cast is lossless.
Only changes the behavior of arithmetic in query.
> [compiler] fix overeager cast simplification

- hail/hail/test/src/is/hail/annotations/UnsafeSuite.scala
- hail/hail/test/src/is/hail/scalacheck/ArbitraryPTypeInstances.scala
- hail/hail/test/src/is/hail/scalacheck/GenVal.scala
Remove uses of `if` or `suchThat` in comprehensions over `Gen` to prevent sporadic errors like the following in scalacheck-driven tests 
```scala
Exception:
org.scalatest.exceptions.GeneratorDrivenPropertyCheckFailedException: Gave up after 9 successful property evaluations. 51 evaluations were discarded.
```
> [tests] prevent genVal for PInterval exceeding num retries

- .gitignore
- auth/auth/templates/user.html
- batch/batch/front_end/front_end.py
- batch/batch/front_end/templates/privacy.html
- batch/batch/front_end/templates/tos.html
- web_common/web_common/templates/utils.html
Require on login that users accept the ToS and Privacy Policy
Requires infosec approval:
- Adds two new endpoints, however they both serve only static content.
- Adds some script functionality to the auth users page, to allow enabling/disabling of login/sign up buttons based on checkbox state. These scripts are entirely self contained and only serve to enable or disable pre-existing content.
Before logging in (ToS not accepted):
Before logging in (ToS accepted):
After logging in:
> [auth] Login UI requires ToS acceptance

- .github/workflows/create-release-pr.yml
Fetches the last tag from `origin` so we can generate the changelog.
Neeed to set `user.name` and `user.email` to commit. 
> [github] update release action to fetch last tag + set git config

- hail/hail/src/is/hail/backend/spark/SparkBackend.scala
- hail/hail/src/is/hail/expr/ir/Interpret.scala
- hail/hail/src/is/hail/expr/ir/TableIR.scala
- hail/hail/src/is/hail/expr/ir/TableValue.scala
- hail/hail/src/is/hail/expr/ir/lowering/ExecuteRelational.scala
- hail/hail/src/is/hail/types/virtual/TStruct.scala
- hail/hail/src/is/hail/types/virtual/Type.scala
- hail/hail/test/src/is/hail/expr/ir/LiftLiteralsSuite.scala
- hail/hail/test/src/is/hail/expr/ir/PruneSuite.scala
- hail/hail/test/src/is/hail/expr/ir/TableIRSuite.scala
Refactor the `TableIR` class to move the `execute` method out of the class, into a free function. Besides just being a better organization, this is also a step towards codegenerating the `TableIR` nodes.
Working through this, I had to stop myself from trying to rewrite some `execute` methods to use the lowered implementation (as `TableLeftJoinRightDistinct` has for some time). But this is a big enough change, I wanted to keep it a pure refactoring. And when we start replacing some RVD-based execute cases with lowering-based ones, we should closely monitor the performance impact.
Non-functional change to the query compiler
> [compiler] move TableIR execute methods out of class

- hail/python/test/hail/methods/test_impex.py
This test is very sensitive to cloud noise and can require repeated retries in ci.
Worth stating that our benchmarks handle identifying regressions while tests such
as these handle correctness.
> [tests] increase `VCFTests::test_combiner_works` timeout

- .github/workflows/create-release-pr.yml
Updates the release action to:
- fetch history for `main` up to the last release tag
- use `contents: write` to push to the repo
- use `bash -ex` as the default interpreter
> [github] fetch tag and history in release action

- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/utils/rich_progress_bar.py
Adds cost information to the progress bar
Client-side change only
> [qob,batch] Add cost to BatchProgressBar

- auth/auth/templates/user.html
UI change only. Moves the "Sign Up" button lower so that it's less easy to click on "Sign Up" when the intended action is "Log in". This has become even more easy to do now that we have the "I have reviewed the ToS" checkbox.
Too easy to click "Sign up" right after accepting the ToS even if the intended action is to log in.
The "easiest flow" is now to click on Log in, which is the most likely action for existing users.
This is a change which impacts Hail Batch. Appsec approval is required:
Moving UI elements around, no functional changes.
> [auth / ui] Make Sign Up button less prominent

- hail/python/hailtop/hailctl/batch/initialize.py
- hail/python/hailtop/hailctl/batch/utils.py
We ran into a problem where soft-delete is automatically enabled for new buckets. This caused a ton of unexpected costs as my mental model was that Batch temp buckets should have no retention policy on them. This change makes it such that all new batch remote temporary directories are set up correctly both with regards to retention and regions.
Only impacts hailctl and no backend code.
> [hailctl] Initialize buckets without soft delete on

- hail/python/hail/vds/combiner/combine.py
As of #14675, we are automatically adding a `LEN` field to VDS on read, while also dropping the `END` field on write. For older VDS, this puts the `LEN` field at the end of the reference entry struct. PR #14675 puts `LEN` as the first item in the entry struct when creating new reference data from a GVCF. This leads to an incompatibility when running the combiner on a mixture of old and new datasets. The solution here can be very simple. Just put `LEN` at the end of the entry struct on GVCF import as well.
> [query/vds] Reorder LEN field to end of new ref entry struct

- hail/python/hailtop/batch/backend.py
Fixes bug where `remove_tmpdir` Batch jobs were not run in the regions the user specified.
Only changes the hailtop.batch client library.
- For medium/high impact: provide a description of the impact and the mitigations in place.
> [hailtop.batch] remove_tmpdir jobs run in correct region

- hail/hail/src/is/hail/backend/service/ServiceBackend.scala
We were serializing and then throwing away the serialized data.
QoB relies on serializing broadcast values into the partition functions, it will be sufficient to diagnose pipeline bugs via those serialization errors, we don't need to do extra work.
> [qob] Remove unnecessary serialization in ServiceBackend broadcast

- batch/batch/worker/worker.py
When many JVM-requiring jobs are starting at once, many requests will be queued up on _waiting_for_jvm_with_n_cores. There may in fact be more pending requests than max_jvms, so the excess requests should simply wait for an existing JVM to become available rather than try to create another -- which would fail.
Prevents _jvm_initializer_task from aborting when it receives very many not-immediately-satisfiable borrow_jvm() requests. No new behaviour otherwise.
> Create requested JVM only when there aren't already enough

- hail/python/hail/vds/combiner/variant_dataset_combiner.py
It may be confusing for users to wait for computing the defined reference entries, so we add logging when we compute those fields.
> [vds/combiner] Add extra logging to new_combiner

- hail/hail/src/is/hail/expr/ir/Requiredness.scala
- hail/hail/src/is/hail/types/TypeWithRequiredness.scala
- hail/hail/test/src/is/hail/expr/ir/DictFunctionsSuite.scala
Fixes an apparently long standing bug. The issue is that `RDict` was a subclass of the concrete class `RIterable`, and assumed that all `TypeWithRequirement`s corresponding to a dict are explicitly constructed as the `RDict` subclass. However, `SContainer._typeWithRequiredness` always constructs an `RIterable`, even though it may be a dict type.
To fix, I eliminated the questionable use of inheritance. `RIterable` is now final, `RDict` is deleted in favor of being a special case of `RIterable`, and `RNDArray` (which was also a subclass of `RIterable`, even though `TNDArray` is not a `TIterable`) no longer inherits from `RIterable`.
> [compiler] fix RIterable

- hail/python/hailtop/config/__init__.py
- hail/python/hailtop/config/user_config.py
- hail/python/hailtop/config/variables.py
- hail/python/hailtop/hailctl/batch/initialize.py
- hail/python/hailtop/hailctl/config/cli.py
- hail/python/hailtop/hailctl/config/config_variables.py
- hail/python/test/hailtop/hailctl/config/test_cli.py
Fixes #14894 
This PR allows multiple simultaneous Hail configuration profiles to customize settings for different projects, especially batch/remote_tmpdir and batch/billing_project
Only impacts "hailctl" -- the Hail CLI running on the user's computer.
---
The design of this PR is that we have `config.ini` in `~/.config/hail/` that contains the default values. We load this config first. Then we update any overlapping values and add new ones from `my-profile.ini`. To find available configs, we look for any `.ini` files that are not `config.ini`. To delete a profile, we remove `~/.config/hail/my-profile.ini`.
Important! -- to …
> [hailctl] Add support for multiple configuration profiles

- hail/hail/src/is/hail/io/plink/LoadPlink.scala
PLINK bim records are not huge, but we were observing issues when broadcasting very large numbers of variants leading to unexpected failures in serialization.
We attempt to fix this by serializing each partition's variants to a separate file that is decoded at the beginning of a pipeline.
> [query] Serialize plink variants per partition

- hail/python/hailtop/hailctl/batch/initialize.py
Cleans up the bucket naming in `hailctl batch init` and sets the default lifecycle to 7 days.
Necessary to try and reduce storage costs while making it clear to users the underlying bucket configuration.
---
```
(hail-cost-progress) jigold@wm349-8c4 hail % hailctl batch init
You are currently logged in to Hail at domain hail.is.
Do you want to create a new bucket for temporary files generated by Hail? [y/n]: y
Which google project should the bucket be created in? This project will incur costs for storing your Hail generated data. (my-project): my-project2
Which region does your data reside in? (us-central1): 
Do you want to set a lifecycle policy (automatically …
```
> [hailctl] Change hailctl batch init defaults

- batch/batch/worker/worker.py
- batch/sql/119-is-job-cancelled.sql
- build.yaml
The following sql triggers and procedures were not updated to reflect
changes to job cancellation when job groups merged: 
- `jobs_after_update`
- `cancel_batch`
- `schedule_job`
- `mark_job_creating`
- `mark_job_started` 
These error if there's more than 1 cancelled job group in the batch,
preventing jobs being marked complete even if they had been executed
sucessfully.
This change drops and re-creates these entities with updated job 
cancellation logic. 
Fixes #14864
This change impacts the Hail Batch instance as deployed by Broad Institute in GCP.
This change has a medium security impact, affecting
- the stored SQL procedures in the batch database, and
- error handling in the batch worker.
This change does not expose new functionality that could be exploited.
> [batch] Fix job_group cancellation logic in SQL procedures

- build.yaml
- docker/hailgenetics/vep/grch37/85/Dockerfile
- docker/hailgenetics/vep/grch38/95/Dockerfile
We'd like vep results to remain consistent. I've noticed in #14927 when upgrading hail-ubuntu to 24.04, some results changed, and I'm not sure why. I'd like to upgrade our images to the newer version. So, I've pinned our VEP containers to be based on ubuntu:22.04.
Also here is some minor reorganization to how we group dependencies, a harmonization of samtools installation across both the 85 and 95 images, and an upgrade to the latest version of samtools.
> [query] Pin VEP base image os version

- hail/python/hailtop/batch/job.py
Job names are unlimited in length; avoid ENAMETOOLONG by truncating the name when it is used as part of the job's working directory.
One-liner to truncate the existing text of a directory name.
> [hailctl|batch] Truncate job name when used as a directory name under /io

- admin-pod/Dockerfile
- batch/Dockerfile.worker
- batch/build-batch-worker-image-startup-gcp.sh
- batch/gcp-create-worker-image.sh
- batch/terra-chart/Dockerfile.batch
- batch/terra-chart/templates/config.yaml
- batch/test/utils.py
- build.yaml
- ci/Dockerfile.ci-utils
- docker/Dockerfile.base
- docker/hail-ubuntu/Dockerfile
- docker/third-party/images.txt
- hail/hail/test/src/is/hail/services/BatchClientSuite.scala
- hail/python/hailtop/batch/backend.py
- hail/python/hailtop/batch/docs/cookbook/clumping.rst
- hail/python/hailtop/batch/docs/cookbook/files/batch_clumping.py
- hail/python/hailtop/batch/docs/docker_resources.rst
- hail/python/hailtop/batch/job.py
- hail/python/test/hailtop/batch/test_batch_local_backend.py
- hail/python/test/hailtop/batch/utils.py
- infra/azure/modules/batch/main.tf
- infra/gcp-broad/main.tf
- infra/gcp/README.md
- infra/gcp/main.tf
- infra/k8s/global_config/main.tf
In #14859 and #14918, I was getting segfaults in libsass, that went away when I upgraded to ubuntu 24.04. This change separates out the upgrade as there should be no issues running python3.9 on ubuntu 24.04 until we upgrade our default version of python.
Core OS image upgrade.
> [auth|batch|ci|monitoring] Upgrade all default images to ubuntu:24.04

- batch/Dockerfile.worker
We have not updated crun since 2022.
Dependency upgrade.
> [batch] Upgrade crun

- hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
Have parity with our pinned requirements.
Also remove strict requirements on lxml and mkl. They haven't been updated since they were added and I have no idea _why_ they're there, which is why I didn't remove them.
> [query] Update init_notebook dependency versions

- hail/hail/src/is/hail/expr/ir/BlockMatrixIR.scala
- hail/hail/src/is/hail/expr/ir/MatrixIR.scala
- hail/hail/src/is/hail/expr/ir/TableIR.scala
- hail/hail/src/is/hail/expr/ir/TypeCheck.scala
- hail/hail/test/src/is/hail/expr/ir/table/TableGenSuite.scala
This is a simple relocation of the typecheck methods on relational IR classes to the `Typecheck` function. This removes one of the arbitrary differences between relational and value IR classes, and prepares the way to codegenerating relational IR.
> [compiler] move relational IR typecheck methods out of class

- batch/batch/driver/instance_collection/pool.py
The query to get the head of the job queue for a given batch was building a temp table containing all jobs in the batch. In a batch with millions of jobs, this was taking >30s, and the scheduler couldn't schedule jobs fast enough to keep worker instances alive.
Credit to Bram Gorissen for the optimized query. It does change the order we schedule jobs, and we may want to revisit that ordering, but we urgently need to remove this bottleneck to complete a running large batch.
Only affects the order the batch scheduler considers ready jobs.
> [batch] fix to slow scheduler query

- build.yaml
> [ci] Remove deleted python_3_11 image references

- gear/gear/auth.py
- hail/python/hailtop/hail_logging.py
Adds to our API call logs:
- The user_agent
- Whether the API call required authentication or developer privilege 
From a sample payloadJson, after calling a non-developer page:
```json
{
"authenticated_users_only": true,
"developers_only": false,
"is_developer": 1,
"message": "https GET /chrisl/batch/batches done in 0.24499999999989086s: 200",
"response_status": 200,
"user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X ...) AppleWebKit/... (KHTML, like Gecko) Chrome/... Safari/..."
}
```
And from a developer-only page:
```json
{
"authenticated_users_only": true,
"developers_only": true,
"is_developer": 1,
"message": "https GET /chrisl/batch/batches done in 0.07899999999995089s: 200",
"response_status": 200,
"user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X ...) AppleWebKit/... …
```
> [services] Add user agent and auth-level metadata to API logs

- .github/workflows/create-release-pr.yml
> [github] run release action if repo is hail-is/hail

- hail/hail/src/is/hail/expr/ir/MatrixWriter.scala
- hail/python/test/hail/linalg/test_linalg.py
`MatrixBlockMatrixWriter` writes 0 columns in the final block 
when block size evenly divides the number of columms.
> [query] Fix `MatrixBlockMatrixWriter` for when `n_cols mod block_size == 0`

- hail/scripts/release.sh
> Update release script for dropping support for python 3.9

- hail/python/hailtop/hailctl/dataproc/cli.py
- hail/python/hailtop/hailctl/dataproc/submit.py
The `--dry-run` option was not outputing the `cluster` argument, and the docs were using a confusing `--image-name` argument that doesn't mean anything in the context of dataproc.
> [hailctl] Fix dry-run and docs for `dataproc submit`

- hail/Makefile
`hail/Makefile` fails with an inscrutable error when using a gmake version prior to 3.82. Mac OS by default comes with 3.81 installed, so this is a common encounter for people first setting up a hail dev environment. This adds a version check to the makefile, to provide a clear error message. Note that `MAKE_VERSION` still assumes gmake, so running this with non-gnu make might still fail in a confusing way. I don't think that's a serious issue, but let me know if anyone disagrees.
On my mac:
```
❯ /usr/bin/make foo
makefile:2: *** requires gmake version at least 3.82.  Stop.
```
> [query] make make error on unsupported make version

- hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
- hail/python/hailtop/hailctl/dataproc/start.py
We haven't updated this value since February of 2024.
> [hailctl] Update dataproc image version to 2.2.60

- hail/hail/src/is/hail/expr/ir/IRBuilder.scala
- hail/hail/src/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala
Fixes the BlockMatrix lowering rule for extracting the diagonal of a blockmatrix. Before it was inlining the parent BM's block IR inside a loop to read out the diagonal elements. So the parent block was being allocated and recomputed once for each diagonal element, without freeing allocations from previous iterations. Fixed by changing `BlockMatrixStage2.collectBlocks` to provide the block IR as a reference.
> [query] fix memory leak in lowered blockmatrix diagonal

- hail/hail/src/is/hail/backend/local/LocalBackend.scala
- hail/hail/src/is/hail/backend/service/ServiceBackend.scala
- hail/hail/src/is/hail/backend/spark/SparkBackend.scala
- hail/hail/src/is/hail/expr/ir/CompileAndEvaluate.scala
- hail/hail/src/is/hail/expr/ir/Parser.scala
- hail/hail/src/is/hail/expr/ir/lowering/LoweringPipeline.scala
- hail/hail/test/src/is/hail/expr/ir/RequirednessSuite.scala
- hail/hail/test/src/is/hail/linalg/BlockMatrixSuite.scala
Before this change, `CompileAndEvaluate` always invoked the `relationalLowerer` lowering pipeline, despite the fact that this is often called *after* lowering, sometimes on many fragments of a larger IR. So not only is the lowering pipeline not needed, I believe this is at least one of the causes of our logs being polluted with so many IRs in so many stages of lowering it's hard to keep track of what's happening.
As a step towards untangling the compilation process, this instead makes `CompileAndEvaluate` take a lowering pipeline as an argument, with a default of a trivial no-op pipeline. This also allowed the cleanup of some code duplication.
> [query] don't lower inside CompileAndEvaluate

- .github/workflows/create-release-pr.yml
- hail/scripts/update-changelog
Moves the shell commands that update the hail and batch changelogs into
callable scripts and updates them to work with bsd sed.
This change has no security impact and does not impact the hail batch
service managed by Broad Institute in GCP.
> [release] script-ify change log generation

- hail/hail/test/src/is/hail/expr/ir/OrderingSuite.scala
This test was flaky, as scalacheck was discarding the test case whenever the generated value was not an element of the generated set. Since the empty set is likely to be generated, this failed often, causing the test to fail with a "too many discarded cases" error.
There was some logic in the assertion that was clearly intended to test the behavior in the case that the element is not contained in the set. But as that logic was never exercised, it was no longer correct.
I've rewritten the assertion to never discard a test case, and to correctly verify the post-conditions of the binary search method in all cases. As a side benefit, on my computer, the test has gone from sometimes taking 30-60s, to <2s.
> [compiler] fix testBinarySearchOnSet

- dev-docs/compiler-team/development_tools.md
Update development_tools.md to recommend `uv` instead of conda, and python 3.11 instead of 3.9
> Update development_tools.md to recommend `uv` instead of conda

- hail/hail/src/is/hail/asm4s/CodeBuilder.scala
While running in QoB, I encoutered this strange error:
```
Caused by: java.lang.IllegalAccessError: class __C2828stream_to_iter tried to access private method 'void java.lang.AssertionError.<init>(java.lang.String)' (__C2828stream_to_iter is in unnamed module of loader is.hail.asm4s.HailClassLoader @4319052; java.lang.AssertionError is in module java.base of loader 'bootstrap')
```
I have _no idea_ why this is ocurring. However, the public constructors of [AssertionError], does not include `AssertionError(String message)`, so, we attempt to correct this by using the `AssertionError(Object)` constructor instead.
[AssertionError]: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/AssertionError.html
- This change cannot impact the Hail Batch instance as deployed by …
> [query] Fix AssertionError signature

- hail/build.mill
> [query] Upgrade google-cloud-storage to 2.55.0

- hail/python/hailtop/hailctl/auth/cli.py
Adds links to cli login for new Privacy Policy and Terms of Service. Prompts users to review and agree to both before logging in. As before, login cannot occur without explicitly agreeing to both documents.
Though related to login, this functionality was already in place; this PR simply updates the user prompt to include links to the new ToS and privacy statement.
> [batch/auth] Updated CLI login with ToS and privacy policy links

- hail/hail/src/is/hail/backend/service/Worker.scala
I've seen this odd error in QoB on occasion, and I have no idea why. Does it have to do with a process being reused for a JVM job?
```
2025-08-19 06:09:59.177 JVMEntryway: ERROR: QoB Job threw an exception.
java.lang.reflect.InvocationTargetException: null
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at is.hail.JVMEntryway$1.run(JVMEntryway.java:119) [jvm-entryway.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
at …
```
> [qob] Use getOrCreate to ensure HailContext initialization

- hail/hail/ir-gen/src/Main.scala
- hail/hail/src/is/hail/expr/ir/AggOp.scala
- hail/hail/src/is/hail/expr/ir/DeprecatedIRBuilder.scala
- hail/hail/src/is/hail/expr/ir/Exists.scala
- hail/hail/src/is/hail/expr/ir/IR.scala
- hail/hail/src/is/hail/expr/ir/InferType.scala
- hail/hail/src/is/hail/expr/ir/Parser.scala
- hail/hail/src/is/hail/expr/ir/Pretty.scala
- hail/hail/src/is/hail/expr/ir/PruneDeadFields.scala
- hail/hail/src/is/hail/expr/ir/Requiredness.scala
- hail/hail/src/is/hail/expr/ir/Simplify.scala
- hail/hail/src/is/hail/expr/ir/TableIR.scala
- hail/hail/src/is/hail/expr/ir/TypeCheck.scala
- hail/hail/src/is/hail/expr/ir/agg/Extract.scala
- hail/hail/src/is/hail/expr/ir/analyses/SemanticHash.scala
- hail/hail/src/is/hail/expr/ir/lowering/LowerTableIR.scala
- hail/hail/test/src/is/hail/expr/ir/Aggregators2Suite.scala
- hail/hail/test/src/is/hail/expr/ir/AggregatorsSuite.scala
- hail/hail/test/src/is/hail/expr/ir/EmitStreamSuite.scala
- hail/hail/test/src/is/hail/expr/ir/ExtractIntervalFiltersSuite.scala
- hail/hail/test/src/is/hail/expr/ir/ForwardLetsSuite.scala
- hail/hail/test/src/is/hail/expr/ir/IRSuite.scala
- hail/hail/test/src/is/hail/expr/ir/PruneSuite.scala
- hail/hail/test/src/is/hail/expr/ir/SimplifySuite.scala
- hail/hail/test/src/is/hail/expr/ir/TableIRSuite.scala
- hail/hail/test/src/is/hail/expr/ir/TestUtils.scala
`AggSignature`, which groups an `AggOp` together with the types of the init op and seq op arguments, was not contributing any value, and needing to keep the types in sync with the arguments of `ApplyAggOp` created complexity.
> [compiler] remove AggSignature

- infra/gcp-broad/main.tf
- infra/gcp/main.tf
Closes https://github.com/hail-is/hail-security/issues/49
Closes https://github.com/hail-is/hail-security/issues/51
Adds "OS Login" and "Block project-wide SSH keys" compute metadata at a project level. Will impact new instances.
Note:
```
gcloud compute project-info add-metadata \
--metadata enable-oslogin=TRUE,block-project-ssh-keys=TRUE
```
- The Impact Rating, Impact Description, and Appsec Review sections are required
- The Impact Rating, Impact Description, and Appsec Review sections can be deleted
- This change has a medium …
> [terraform] Add VM metadata for OS Login and Block project-wide SSH

- hail/python/hail/methods/qc.py
It is possible for the count of transversions to be 0, so we need to check before dividing by it. In the display code for the variant summary, use NaN as that works with float formatting. For `summarize_variants(..., show=False)` use `None` rather than NaN.
> [query] Fix division by zero in summarize_variants

- batch/batch/worker/worker.py
Also, set the java heap limit to 90% of machine memory.
The intention here was to give nicer error messages for when hail was using too much memory. Unfortunately, this drastically reduces the jobs that will succeed, as we partition the heap into a JVM portion and a native portion. And so, the job may hit a memory limit while the machine still has ample memory.
- This change has low security impact
This is a change to the environment of our java containers, where we run Query on Batch jobs. As this is simply a change to how a container is set up, this has low to no impact on the service as a whole.
> [qob] Don't set hail off heap memory limits in QoB

- infra/gcp-broad/main.tf
- infra/gcp/main.tf
Closes https://github.com/hail-is/hail-security/issues/46
Enabled network policies in our k8s cluster in GCP.
Note: This is a terraform change, which will need to be manually applied to the GCP infrastructure after approval.
This change potentially impacts the Hail Batch instance as deployed by Broad Institute in GCP
Enables a setting recommended by the CIS scan
> [terraform] Add network policy support to k8s in gcp and gcp-broad infra

- infra/gcp-broad/main.tf
- infra/gcp/main.tf
Partially resolves https://github.com/hail-is/hail-security/issues/55
Replaces very broad admin grants to the `auth` service with more specific required permissions.
Replaces two admin level role grants with 5 specific permissions
> [terraform] Replace excess auth admin roles with custom role

- ci/Dockerfile.ci-utils
It's been almost seven years. Some transient dependency upgrade broke it. Upgrading it allowed me to manually upload the release to PyPI.
> [release] Upgrade twine

- hail/hail/src/is/hail/HailContext.scala
- hail/hail/src/is/hail/HailFeatureFlags.scala
- hail/hail/src/is/hail/expr/ir/agg/package.scala
- hail/hail/src/is/hail/expr/ir/lowering/LowerTableIR.scala
- hail/hail/src/is/hail/rvd/RVD.scala
- hail/python/hail/backend/backend.py
- hail/python/hail/backend/local_backend.py
- hail/python/hail/backend/service_backend.py
- hail/python/hail/backend/spark_backend.py
- hail/python/hail/context.py
Refactored the branching factor parameter to be controlled through feature flags instead of being passed directly to the HailContext constructor. This change:
1. Removes the branching factor parameter from HailContext constructor and methods
2. Adds a new feature flag "branching_factor" with a default value of 50
3. Creates a new `agg` package with utility functions to retrieve the branch factor from context
4. Modifies Python backends to pass branching factor through flags rather than constructor parameters
This approach provides a more consistent way to configure the branching factor through environment variables or programmatic flags, aligning with how other Hail parameters are managed.
> [query] remove `branchingFactor` from `HailContext`

- CODEOWNERS
Makes sure appsec is approving PRs that might impact production, even if the PR gets two other positive reviews first.
> [github] Add codeowners file to avoid accidental merging

- ci/ci/constants.py
From the monthly userlist scan. These users have not created testable PRs in over 60 days. We can re-add them later if required.
Removes inactive users from authorized users list in CI
> [CI] Tidy authorized users list

- ci/ci/github.py
I believe this probably fixes https://github.com/hail-is/hail/issues/15058
Adds another exception type to the guard around github status updating, so that the main loop doesn't crash if we run out of allowed status updates in github.
See follow up #15092 to actually fix the problem.
Adds resilience to CI code, otherwise no changes to running workloads. The only new information being logged if the exception throws is the API URL we were attempting to call, which is already public on github
> [CI] Catch type errors from status updater so that the main loop doesn't crash

- infra/gcp-broad/gsa/main.tf
- infra/gcp-broad/main.tf
- infra/gcp/gsa_k8s_secret/main.tf
- infra/gcp/main.tf
Relates to 
Fixes the role references. Previously we were using custom roles as though they were presets, but in fact they need to be project-qualified
Impact is that the custom roles we previously created should now be applied correctly
> [terraform] Fix role references for new custom roles

- hail/hail/src/is/hail/HailContext.scala
- hail/hail/src/is/hail/rvd/RVD.scala
- hail/hail/test/src/is/hail/HailSuite.scala
As part of my sacred quest to kill `HailContext`, this change moves `checkRVDKeys` out of `HailContext`​.  
> [query] implement `HailContext.checkRVDKeys` via flags

- infra/gcp-broad/main.tf
- infra/gcp/main.tf
Fixes https://github.com/hail-is/hail-security/issues/47
Enables secure boot and shielded nodes for node pools and vdc cluster.
Note:
Enables secure boot and shielded nodes. Makes sure the kernels being loaded in are properly protected
> [terraform] enable secure boot in k8s node pools

- docker/mysql/db.yaml
Makes test DBs schedulable by reducing their required CPU to 1.25 (from 1.5), because of all the new ~cruft~ security apparatus processes that have been added to node pool VMs
DB pods are only used in test and developer namespaces, not for the main production services. This change reduces their bare minimum required CPU declaration from 1.5 to 1.25 to accommodate the new processes taking up small CPU segments on all the node pool VMs
> [CI] Resize test dbs

- infra/gcp-broad/main.tf
- infra/gcp/main.tf
Fixes https://github.com/hail-is/hail-security/issues/44
Sets the k8s secrets database with a user-managed key so that the secrets are encrypted at rest, with a key managed in the standard cloud KMS system
> [terraform] Encrypt k8s secrets DB at rest

- batch/test/test_batch.py
Attempts to make our current GPU test more reliable by:
- Only requiring us to roll the dice of "will we get a GPU allocated to us" once, not twice
- Allowing up to 4 retries before giving up
Brief description and justification of what this PR is doing.
Internal test shuffling to improve reliability. Should be no functional change.
> [CI] Attempt to make gpu testing more reliable

- batch/test/test_batch.py
Temporarily disable the GPU tests. They fail far too frequently with ZONE EXHAUSTION errors that are nothing to do with the code itself and just an artifact of clouds not being infinite all the time.
Just a test, no production impact
> [CI] Disable overly flaky GPU test

- hail/hail/src/is/hail/HailContext.scala
- hail/hail/src/is/hail/backend/local/LocalBackend.scala
- hail/hail/src/is/hail/backend/spark/SparkBackend.scala
- hail/hail/src/is/hail/utils/Logging.scala
- hail/hail/src/is/hail/utils/Py4jUtils.scala
- hail/hail/src/is/hail/utils/package.scala
- hail/hail/test/src/is/hail/HailSuite.scala
- hail/python/hail/backend/py4j_backend.py
`HailContext` jihad:
-  moves logging configuration from `HailContext` to a dedicated `Logging` object.
- removes references to `HailContext.version`​
> [query] move `configureLogging` and `version` out of `HailContext`

- hail/Makefile
Enable workflows where `hail/mill-build/config/scala-version` is set to something other than `SCALA_VERSION` in `hail/Makefile`.
This change does not impact the hail batch deployment in GCP.
> [query] invoke mill using `SCALA_VERSION` env var in Makefile

- hail/python/hailtop/batch/docker.py
Fixes #15082
Currently, `build_python_image` fails for some users if they want to include dependencies that aren't compatible with the underlying Docker image used by `build_python_image` (that is, the image we specify in the `docker build -t...` step). Our default image is always the `slim` version of one of our `hailgenetics/python:dill` images and is rather bare-bones compared to a regular, non-slim image version. There is currently no way for users to specify otherwise.
This change adds a `slim` argument to `build_python_image` (default True), allowing users to specify `False` if the they want to use the standard base image rather than the `slim` version.
- This change has a medium security …
> [batch] parameterizing `build_python_image` to build from non-slim images

- hail/hail/src/is/hail/HailContext.scala
- hail/hail/src/is/hail/backend/Backend.scala
- hail/hail/src/is/hail/backend/BackendUtils.scala
- hail/hail/src/is/hail/backend/ExecuteContext.scala
- hail/hail/src/is/hail/backend/driver/BatchQueryDriver.scala
- hail/hail/src/is/hail/backend/driver/Py4JQueryDriver.scala
- hail/hail/src/is/hail/backend/service/Worker.scala
- hail/hail/test/src/is/hail/HailSuite.scala
- hail/python/hail/backend/local_backend.py
- hail/python/hail/backend/spark_backend.py
Changes the HailContext and Backend relationship by:
1. Removing the direct dependency of HailContext on Backend by:
- Removing the backend parameter from HailContext constructor
- Introducing a static Backend.get/set mechanism to access the current backend
2. Ensures proper backend lifecycle management:
- Moves backend.close() calls to appropriate locations
- Sets up Backend.set(null) after operations to prevent leaks
> [query] remove `Backend` from `HailContext`

- hail/generate_splits.py
Why shell out when there are perfectly acceptable library functions?
Tested manually by asserting old and new methods of generating the file list produce the same output.
> [query] Use pure python for test class finding in generate_splits.py

- hail/hail/src/is/hail/HailContext.scala
- hail/hail/src/is/hail/backend/driver/BatchQueryDriver.scala
- hail/hail/src/is/hail/backend/driver/Py4JQueryDriver.scala
- hail/hail/src/is/hail/backend/local/LocalBackend.scala
- hail/hail/src/is/hail/backend/service/Main.scala
- hail/hail/src/is/hail/backend/service/Worker.scala
- hail/hail/src/is/hail/backend/spark/SparkBackend.scala
- hail/hail/src/is/hail/linalg/package.scala
- hail/hail/test/src/is/hail/HailSuite.scala
Removes creation of a `HailContext` for QoB.  `HailContext.apply` previously registered a dense matrix operation. For compatibility, this has been moved to a `lazy val` in the newly added `linalg` package object (so that it's registered at most once). Each backend initialises that `lazy val` in a similar way to the `StreamReadConstraints` business.
Fixes #15072
> [query] `HailContext` is not required in batch
