hail-is/hail

changes.md, docs/Annotations.md, docs/ExportTSV.md, docs/ExportVCF.md, docs/ProgrammaticAnnotation.md, docs/QC.md, docs/Representation.md, src/main/scala/org/broadinstitute/hail/driver/VariantQC.scala, src/test/resources/exportTest.columns, src/test/scala/org/broadinstitute/hail/PipelineSuite.scala, src/test/scala/org/broadinstitute/hail/methods/AggregatorSuite.scala, src/test/scala/org/broadinstitute/hail/methods/AnnotateGlobalSuite.scala, src/test/scala/org/broadinstitute/hail/methods/ExportSuite.scala, src/test/scala/org/broadinstitute/hail/utils/TestRDDBuilder.scala
=> Tp docs and renames

docs/ExportTSV.md, src/main/scala/org/broadinstitute/hail/Utils.scala, src/main/scala/org/broadinstitute/hail/driver/AnnotateVariantsJSON.scala, src/main/scala/org/broadinstitute/hail/driver/ExportGenotypes.scala, src/main/scala/org/broadinstitute/hail/driver/ExportSamples.scala, src/main/scala/org/broadinstitute/hail/driver/ExportVariants.scala, src/main/scala/org/broadinstitute/hail/expr/Parser.scala, src/main/scala/org/broadinstitute/hail/expr/Type.scala, src/main/scala/org/broadinstitute/hail/methods/ExportTSV.scala, src/test/scala/org/broadinstitute/hail/methods/ExportSuite.scala
optionally export a one-line types file
=> Tp export columns

build.gradle, src/main/scala/org/broadinstitute/hail/driver/ExportVariantsSolr.scala, src/main/scala/org/broadinstitute/hail/variant/GenotypeStream.scala
=> Treat warnings as errors.

docs/HailExpressionLanguage.md, src/main/scala/org/broadinstitute/hail/Utils.scala, src/main/scala/org/broadinstitute/hail/expr/AST.scala, src/test/scala/org/broadinstitute/hail/methods/ExprSuite.scala
Once this is in, I'll add a straight-up sort, and perhaps also options for descending rather than ascending order.
I"m still thinking about whether null should be at the beginning or the end, but we'll start with it at the beginning.
=> Jb expr sortby

src/main/scala/org/broadinstitute/hail/driver/ExportVCF.scala
Also remove undocumented fileDate header entry in exportvcf.
=> Remove Java 8 dependency.

docs/HailExpressionLanguage.md, src/main/scala/org/broadinstitute/hail/Utils.scala, src/main/scala/org/broadinstitute/hail/expr/AST.scala, src/test/scala/org/broadinstitute/hail/methods/ExprSuite.scala
- added sort on Arrays in expr
- extended sort and sortBy to take an optional Boolean parameter for ascending
- modifed behavior to always place null values at the end
- updated HailExpressionLanguage.md
- added tests for sort and sortBy to ExprSuite
=> added sort, added ascending parameter to sortBy

docs/commands/ImportAnnotations.md
=> Updated 'importannotations table' docs

Jenkinsfile
=> use Jenkins pipelines

src/main/scala/org/broadinstitute/hail/methods/MendelErrors.scala, src/main/scala/org/broadinstitute/hail/methods/Pedigree.scala, src/test/scala/org/broadinstitute/hail/methods/PedigreeSuite.scala
- changed Pedigree from a case class to a class
- changed member from Array[Trio] to IndexedSeq[Trio]
=> Changed Pedigree to class with IndexSeq[Trio]

src/main/scala/org/broadinstitute/hail/driver/Count.scala, src/main/scala/org/broadinstitute/hail/driver/ExportPlink.scala, src/main/scala/org/broadinstitute/hail/driver/ExportVCF.scala, src/main/scala/org/broadinstitute/hail/driver/ExportVariants.scala, src/main/scala/org/broadinstitute/hail/driver/ExportVariantsCass.scala, src/main/scala/org/broadinstitute/hail/driver/ExportVariantsSolr.scala, src/main/scala/org/broadinstitute/hail/driver/FilterVariantsList.scala, src/main/scala/org/broadinstitute/hail/driver/GQHist.scala, src/main/scala/org/broadinstitute/hail/driver/ImportAnnotations.scala, src/main/scala/org/broadinstitute/hail/driver/LinearRegressionCommand.scala, src/main/scala/org/broadinstitute/hail/driver/SampleQC.scala, src/main/scala/org/broadinstitute/hail/driver/SplitMulti.scala, src/main/scala/org/broadinstitute/hail/driver/VEP.scala, src/main/scala/org/broadinstitute/hail/driver/VariantQC.scala, src/main/scala/org/broadinstitute/hail/methods/Aggregators.scala, src/main/scala/org/broadinstitute/hail/methods/ToStandardizedIndexedRowMatrix.scala, src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala, src/main/scala/org/broadinstitute/hail/vcf/HtsjdkRecordReader.scala, src/test/scala/org/broadinstitute/hail/methods/AggregatorSuite.scala, src/test/scala/org/broadinstitute/hail/methods/ImportAnnotationsSuite.scala, src/test/scala/org/broadinstitute/hail/methods/ImportVCFSuite.scala, src/test/scala/org/broadinstitute/hail/methods/ImputeSexSuite.scala, src/test/scala/org/broadinstitute/hail/utils/TestRDDBuilder.scala, src/test/scala/org/broadinstitute/hail/variant/vsm/VSMSuite.scala
Refactored RDD[(Variant, Annotation, Iterable[Genotype])] to
RDD[(Variant, (Annotation, Iterable[Genotype]))]
=> Made VSM rdd a PairRDD

src/main/scala/org/broadinstitute/hail/driver/GRM.scala
Fixes: https://github.com/broadinstitute/hail/issues/321.  I just tested it on the Cray against 20K exomes.  Took ~6m, worked like a charm.
=> Use block matrix multipy in grm.

style-guide.md
Turn off Align when multiline.
=> Updated style guide.

src/main/scala/org/broadinstitute/hail/check/Gen.scala, src/main/scala/org/broadinstitute/hail/expr/Type.scala, src/main/scala/org/broadinstitute/hail/variant/Genotype.scala, src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala
Resolves #571 by randomly choosing rectangle dimensions to use for the matrix dimensions.
=> Resolve Issue 571

src/test/scala/org/broadinstitute/hail/variant/vsm/VSMSuite.scala
also, relax linearity requirement
=> Use the global RDG in vsm linearity test

docs/HailExpressionLanguage.md, src/main/scala/org/broadinstitute/hail/expr/AST.scala, src/test/scala/org/broadinstitute/hail/methods/ExprSuite.scala
consistent with sortBy, isEmpty, flatMap, etc
=> changed mapvalues to mapValues in expr language

changes.md
Resolves https://github.com/broadinstitute/hail/issues/580.
=> Fixed broken link in changes.md.

src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala
isDosage defaults to false if:
- wrong JType in metadata JSON
- not found in metadata JSON
=> Made read back-compatible.

docs/HailExpressionLanguage.md, src/main/scala/org/broadinstitute/hail/Utils.scala, src/main/scala/org/broadinstitute/hail/expr/AST.scala, src/test/scala/org/broadinstitute/hail/methods/ExprSuite.scala
- added methods to AST for Array and Set
- added docs in HailExpressionLangauge.md
- added tests to ExprSuite
- addresses Issue #556
=> added flatMap and flatten to expr language

docs/index.html, docs/style.css
Fixed broken link.
Style code in links as code.
=> Simplified, increased contrast of link styling.

docs/style.css
Style pre > code as block, line height 1.1.
Treat pre.synopsys similarly.
=> More css tweaks.

src/main/scala/org/broadinstitute/hail/driver/SeqrServer.scala
Support more list/set element types.
Make queries async.
Standardize on chrom/start.
=> Cassandra fixes and improvements.

src/main/scala/org/broadinstitute/hail/driver/Coalesce.scala, src/main/scala/org/broadinstitute/hail/sparkextras/OrderedRDD.scala, src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala
Moved main code from VSM.coalesce to OrderedRDD.
Handle dependencies and preferred locations.
In non-shuffle case, interpret requested partitions as maximum.
=> Improved coalesce.

src/main/scala/org/broadinstitute/hail/driver/VEP.scala
I think this should fix the issue with running VEP on large site files with a small number of partitions.
=> Fixed bug in VEP blocking.

src/main/scala/org/broadinstitute/hail/driver/SplitMulti.scala
Depends on pull request #696. Merge that first to get a simpler diff.
=> Split multi flat map monotonic

docs/buildDocs.js
Awesome or Terrible?
@cseed @tpoterba
=> add an edit link

src/main/scala/org/broadinstitute/hail/io/plink/PlinkBlockReader.scala
=> Convert seek computation to Long

src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala
The serialization changed briefly, still load VDSes written with that verison.
=> Ignore partitioner on InvalidClassException.

docs/HailObjectProperties.md
Resolves https://github.com/hail-is/hail/issues/730
=> Removed nMismatch from AltAllele docs.

src/main/scala/org/broadinstitute/hail/expr/AST.scala, src/main/scala/org/broadinstitute/hail/expr/Type.scala, src/test/scala/org/broadinstitute/hail/methods/ExprSuite.scala
=> Revert "Fixes #705: if doesn't do numeric promotion"

docs/commands/filteralleles.md, src/main/scala/org/broadinstitute/hail/Utils.scala, src/main/scala/org/broadinstitute/hail/driver/Command.scala, src/main/scala/org/broadinstitute/hail/driver/FilterAlleles.scala, src/main/scala/org/broadinstitute/hail/variant/Genotype.scala, src/test/scala/org/broadinstitute/hail/driver/FilterAllelesSuite.scala
=> add the filteralleles command

build.gradle, src/main/scala/org/broadinstitute/hail/Utils.scala, src/main/scala/org/broadinstitute/hail/expr/Type.scala, src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala, src/test/scala/org/broadinstitute/hail/SparkSuite.scala, src/test/scala/org/broadinstitute/hail/driver/GRMSuite.scala, src/test/scala/org/broadinstitute/hail/io/ExportPlinkSuite.scala, src/test/scala/org/broadinstitute/hail/io/ImportPlinkSuite.scala, src/test/scala/org/broadinstitute/hail/io/ImportVCFSuite.scala, src/test/scala/org/broadinstitute/hail/io/LoadBgenSuite.scala, src/test/scala/org/broadinstitute/hail/methods/ExportSuite.scala, src/test/scala/org/broadinstitute/hail/methods/ImputeSexSuite.scala, src/test/scala/org/broadinstitute/hail/methods/PedigreeSuite.scala, src/test/scala/org/broadinstitute/hail/utils/TextTableSuite.scala
Workflow:
```
$ hdfs dfs -rm -r src/test/resources
$ hdfs dfs -put src/test/resources src/test
$ ./gradlew shadowTestJar
$ SPARK_CLASSPATH=./build/libs/hail-all-spark-test.jar spark-submit --total-executor-cores 2 --class org.testng.TestNG ./build/libs/hail-all-spark-test.jar ./testng.xml
```
=> get tests running against Cray cluster

src/main/scala/org/broadinstitute/hail/driver/Command.scala, src/main/scala/org/broadinstitute/hail/driver/Filtermulti.scala
filters multi-allelic sites  returns a VDS with waSplit = true
=> Added filtermulti command 

src/main/scala/org/broadinstitute/hail/driver/ExportVariantsSolr.scala
Also, close connection when done.
=> Commit Solr after creating fields.

src/main/scala/org/broadinstitute/hail/driver/ExportVariantsSolr.scala, src/main/scala/org/broadinstitute/hail/expr/Parser.scala
Check response in solr queries.
User specified properties in add field query.
=> Solr improvements.

src/main/scala/org/broadinstitute/hail/driver/AnnotateVariantsLoci.scala, src/main/scala/org/broadinstitute/hail/driver/AnnotateVariantsTable.scala, src/main/scala/org/broadinstitute/hail/driver/Coalesce.scala, src/main/scala/org/broadinstitute/hail/driver/FilterVariantsList.scala, src/main/scala/org/broadinstitute/hail/driver/ImportAnnotations.scala, src/main/scala/org/broadinstitute/hail/driver/ImportBGEN.scala, src/main/scala/org/broadinstitute/hail/driver/ImportGEN.scala, src/main/scala/org/broadinstitute/hail/driver/LinearRegressionCommand.scala, src/main/scala/org/broadinstitute/hail/driver/SplitMulti.scala, src/main/scala/org/broadinstitute/hail/driver/VEP.scala, src/main/scala/org/broadinstitute/hail/driver/VariantQC.scala, src/main/scala/org/broadinstitute/hail/io/plink/PlinkLoader.scala, src/main/scala/org/broadinstitute/hail/io/vcf/LoadVCF.scala, src/main/scala/org/broadinstitute/hail/sparkextras/BlockedRDD.scala, src/main/scala/org/broadinstitute/hail/sparkextras/OrderedLeftJoinRDD.scala, src/main/scala/org/broadinstitute/hail/sparkextras/OrderedPartitioner.scala, src/main/scala/org/broadinstitute/hail/sparkextras/OrderedRDD.scala, src/main/scala/org/broadinstitute/hail/sparkextras/PartitionKeyInfo.scala, src/main/scala/org/broadinstitute/hail/sparkextras/ReorderedPartitionsRDD.scala, src/main/scala/org/broadinstitute/hail/utils/richUtils/RichPairRDD.scala, src/main/scala/org/broadinstitute/hail/utils/richUtils/RichRDD.scala, src/main/scala/org/broadinstitute/hail/utils/richUtils/RichSQLContext.scala, src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala, src/test/scala/org/broadinstitute/hail/methods/ImputeSexSuite.scala, src/test/scala/org/broadinstitute/hail/utils/OrderedRDDSuite.scala, src/test/scala/org/broadinstitute/hail/utils/TestRDDBuilder.scala, src/test/scala/org/broadinstitute/hail/variant/vsm/VSMSuite.scala
This allows us to coerce as sorted 'files.chr*.vcf',
no matter the order of the files in globbing.
=> Add ReorderedPartitionsRDD

src/main/scala/org/broadinstitute/hail/methods/ImputeSexPlink.scala
=> Address type mismatch in ImputeSexPlink

src/main/scala/org/apache/spark/sql/SparkExport.scala, src/main/scala/org/broadinstitute/hail/utils/richUtils/RichSQLContext.scala, src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala, src/test/scala/org/broadinstitute/hail/utils/OrderedRDDSuite.scala
Reorder partitions based on ParquetInputSplit path.
Tests pass on GCP.
=> Fix sortedParquetRead on Dataproc.

src/main/scala/org/broadinstitute/hail/expr/AST.scala, src/test/scala/org/broadinstitute/hail/methods/ExprSuite.scala
It also fixes numeric promotion of TInt to TLong, which threw an
assertion error before.
=> Fixes #705: if doesn't do numeric promotion

docs/commands/importvcf.md
not sure if this is worth documenting here, but I had this question, and did some tests to figure out the answer.
=> document behavior if VCF(s) contain multiple

src/main/scala/org/broadinstitute/hail/sparkextras/AdjustedPartitionsRDD.scala, src/main/scala/org/broadinstitute/hail/sparkextras/OrderedRDD.scala, src/test/scala/org/broadinstitute/hail/utils/OrderedRDDSuite.scala
This permits shuffle-free load of files where
multiallelics are split across partitions.
=> Add AdjustedPartitionsRDD

build.gradle, docs/FAQStyleGuide.md, docs/faq/Annotations.md, docs/faq/DataRepresentation.md, docs/faq/DevTools.md, docs/faq/ErrorMessages.md, docs/faq/ExportingData.md, docs/faq/ExpressionLanguage.md, docs/faq/FilteringData.md, docs/faq/General.md, docs/faq/ImportingData.md, docs/faq/Installation.md, docs/faq/Methods.md, docs/faq/OptimizePipeline.md, docs/faq/Representation.md, docs/html/faqTemplate.html, docs/javascript/compileDocsNode.js, docs/javascript/compileFaqNode.js
- Markdown files by category in `docs/faq` directory
- Uses NodeJS to compile markdown files into single page `build/docs/faq.html`
- See the style guide `docs/FAQStyleGuide.md`
- Modified Gradle `createDocs` task
=> Added FAQ to Documentation

src/test/scala/org/broadinstitute/hail/variant/vsm/VSMSuite.scala
=> Add test for VDS with no partitioner

docs/javascript/buildDocs.js
"<" and ">" in the synopsis need to be replaced by html codes
=> Resolves #842

src/main/scala/org/broadinstitute/hail/driver/FilterVariantsExpr.scala, src/main/scala/org/broadinstitute/hail/driver/FilterVariantsList.scala, src/main/scala/org/broadinstitute/hail/variant/Variant.scala, src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala
to facilitate calling these functions from elsewhere in Hail without changing vds in state, which I need for linear mixed models
=> pulled out FilterVariants Expr and List functions

docs/commands/ibd.md, src/main/scala/org/broadinstitute/hail/driver/IBDCommand.scala
=> Concatenate files in ibd

docs/commands/sampleqc.md, src/main/scala/org/broadinstitute/hail/driver/SampleQC.scala, src/test/scala/org/broadinstitute/hail/methods/ExportSuite.scala
Updated calculation
Fixes #764
Branch name is numbered incorrectly, issue reference here is correct.
=> Refactor rDeletionInsertion to rInsertionDeletion

docs/commands/filteralleles.md, src/main/scala/org/broadinstitute/hail/driver/FilterAlleles.scala, src/test/scala/org/broadinstitute/hail/driver/FilterAllelesSuite.scala
Related to issue: https://github.com/hail-is/hail/issues/551#issuecomment-240823343
=> Added subset and filterAlteredGenotypes options to filteralleles

src/main/scala/org/broadinstitute/hail/driver/ExportVariantsSolr.scala
delete, recreate collection before exporting variants
added --drop otion
added option to export missing genotypes
=> exportvariantssolr improvements.

docs/commands/importannotations_table.md, src/main/scala/org/broadinstitute/hail/utils/TextTableReader.scala, src/test/scala/org/broadinstitute/hail/utils/TextTableSuite.scala
=> Fully read file in TextTableReader.imputeTypes

src/main/scala/org/broadinstitute/hail/sparkextras/AdjustedPartitionsRDD.scala, src/main/scala/org/broadinstitute/hail/sparkextras/BlockedRDD.scala, src/main/scala/org/broadinstitute/hail/sparkextras/ReorderedPartitionsRDD.scala
Build off @tpoterba's rdd_cleanup PR.
=> Rdd cleanup2

src/main/scala/org/broadinstitute/hail/driver/ImportPlink.scala, src/main/scala/org/broadinstitute/hail/io/plink/PlinkLoader.scala
=> Better fam file error messages

src/main/scala/org/broadinstitute/hail/stats/eigSymD.scala, src/test/scala/org/broadinstitute/hail/stats/eigSymDSuite.scala
-added symEigD and symEigR in stats on Breeze matrices
-added unit test and speed test
=> added LAPACK dsyevd and dsyevr for symEig

README.md
=> Fix Docs Link on README

docs/tutorial/Tutorial.md
=> Update wget link for ipython notebook

src/main/scala/org/broadinstitute/hail/io/vcf/HtsjdkRecordReader.scala, src/main/scala/org/broadinstitute/hail/utils/Context.scala
=> Update Context to catch throwables rather than exceptions

src/main/scala/org/broadinstitute/hail/driver/Clear.scala, src/main/scala/org/broadinstitute/hail/driver/Command.scala, src/main/scala/org/broadinstitute/hail/driver/Get.scala, src/main/scala/org/broadinstitute/hail/driver/Join.scala, src/main/scala/org/broadinstitute/hail/driver/Put.scala, src/test/scala/org/broadinstitute/hail/driver/JoinSuite.scala
Added set, get and clear commands.
join works against environment.
=> Added VDS environment to state.

src/main/scala/org/broadinstitute/hail/methods/SamplePCA.scala
=> Fix pca bug

src/main/scala/org/broadinstitute/hail/driver/ExportVariantsCass.scala, src/main/scala/org/broadinstitute/hail/driver/SeqrServer.scala
Added --export-missing, escape sample names in exportvariantscass.
Support sample_ids, unescape sample names in seqrserver Cassandra mode.
Let exportvariantscass accept multiallelics.
=> Update Cassandra support to match Solr.

README.md
which will look better on the homepage
=> Update README.md with line break

docs/reference/HailExpressionLanguage.md, src/main/scala/org/broadinstitute/hail/expr/FunctionRegistry.scala, src/test/scala/org/broadinstitute/hail/methods/ExprSuite.scala
- added to expr doc
- added tests
=> added runif and rnorm to function registry

docs/commands/linreg.md, src/main/scala/org/broadinstitute/hail/driver/LinearRegressionCommand.scala, src/main/scala/org/broadinstitute/hail/methods/LinearRegression.scala, src/test/scala/org/broadinstitute/hail/methods/LinearRegressionSuite.scala
- added filters to LinearRegressionCommand
- added minAC to LinearRegression
- added tests to LinearRegressionSuite
- documented in linreg.md
=> added -maf and -mac filters to linreg

src/main/java/org/broadinstitute/hail/io/compress/BGzipInputStream.java, src/main/scala/org/broadinstitute/hail/driver/Command.scala, src/main/scala/org/broadinstitute/hail/driver/CountBytes.scala, src/main/scala/org/broadinstitute/hail/driver/Main.scala
=> Added hidden command countbytes.

docs/commands/exportsamples.md, docs/commands/exportvariants.md, src/main/scala/org/broadinstitute/hail/driver/AggregateIntervals.scala, src/main/scala/org/broadinstitute/hail/driver/Command.scala, src/main/scala/org/broadinstitute/hail/driver/ExportGenotypes.scala, src/main/scala/org/broadinstitute/hail/driver/ExportSamples.scala, src/main/scala/org/broadinstitute/hail/driver/ExportVariants.scala, src/main/scala/org/broadinstitute/hail/driver/ExportVariantsCass.scala, src/main/scala/org/broadinstitute/hail/expr/AST.scala, src/main/scala/org/broadinstitute/hail/expr/Parser.scala, src/main/scala/org/broadinstitute/hail/expr/Type.scala, src/main/scala/org/broadinstitute/hail/utils/richUtils/RichStringBuilder.scala, src/test/scala/org/broadinstitute/hail/annotations/SplatSuite.scala, src/test/scala/org/broadinstitute/hail/methods/ExportSuite.scala
Able to export variantqc output with:
```
exportvariants -c 'Variant = v, va.qc.*'
```
=> Export splatting

src/main/scala/org/broadinstitute/hail/driver/VEP.scala
Not for integrating in the current state.
=> added csq option to vep

README.md
=> Revert "ashg"

docs/reference/GettingStarted.md
=> fix getting started doc

src/main/scala/org/broadinstitute/hail/expr/Type.scala, src/main/scala/org/broadinstitute/hail/utils/package.scala, src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala, src/test/scala/org/broadinstitute/hail/TestUtils.scala, src/test/scala/org/broadinstitute/hail/TestUtilsSuite.scala
- added these to TestUtils
- added tests in TestUtilsSuite
=> adding assertVectorEqualityDouble and assertMatrixEqualityDouble

src/main/scala/org/broadinstitute/hail/driver/Command.scala, src/main/scala/org/broadinstitute/hail/driver/SparkInfo.scala, src/main/scala/org/broadinstitute/hail/sparkextras/StorageLevelString.scala, src/main/scala/org/broadinstitute/hail/utils/richUtils/Implicits.scala, src/main/scala/org/broadinstitute/hail/utils/richUtils/RichStorageLevel.scala, src/test/scala/org/broadinstitute/hail/utils/UtilsSuite.scala
- number of partitions and storage level are logged for each command that requires vds
=> added sparkinfo command and logging

docs/commands/annotatesamples_vds.md, docs/commands/clear.md, docs/commands/deduplicate.md, docs/commands/get.md, docs/commands/join.md, docs/commands/put.md, docs/commands/sparkinfo.md, docs/javascript/buildDocs.js
Fixes bug that the edit link to github does not exist.
=> require markdown file for all commands

docs/commands/baldingnichols.md, src/main/scala/org/broadinstitute/hail/driver/BaldingNicholsModelCommand.scala, src/main/scala/org/broadinstitute/hail/driver/Command.scala, src/main/scala/org/broadinstitute/hail/expr/Parser.scala, src/main/scala/org/broadinstitute/hail/stats/BaldingNicholsModel.scala, src/main/scala/org/broadinstitute/hail/stats/package.scala, src/main/scala/org/broadinstitute/hail/variant/VariantMetadata.scala, src/test/scala/org/broadinstitute/hail/TestUtils.scala, src/test/scala/org/broadinstitute/hail/TestUtilsSuite.scala, src/test/scala/org/broadinstitute/hail/stats/BaldingNicholsModelSuite.scala, src/test/scala/org/broadinstitute/hail/stats/StatsSuite.scala
- created BaldingNicholsCommand, and registered command, currently hidden
- created BaldingNicholsModel to generate model and convert to annotated vds
- created BaldingNicholsSuite to test that seed is working properly
- started baldingnichols.md
- added parseCommaDelimitedDoubles and comma_delimited_doubles to Parser
- moved vdsFromMatrix from TestUtils to stats package, set wasSplit=true, added optional samplesIds parameter
- moved vdsFromMatrixTest from TestUtilsSuite to StatsSuite
- added VariantMetadata constructor with wasSplit option
=> added Balding-Nichols model

docs/commands/imputesex.md, src/main/scala/org/broadinstitute/hail/methods/ImputeSexPlink.scala, src/test/scala/org/broadinstitute/hail/methods/ImputeSexSuite.scala
Added Write to test to make sure annotation types are correct.
=> fixes bug with imputesex types

src/main/scala/org/broadinstitute/hail/io/vcf/HtsjdkRecordReader.scala
'Fix' for https://github.com/hail-is/hail/issues/1065
=> Added support for "nan" float values in INFO fields.

build.gradle
=> Fix cats runtime dependency

build.gradle
@tpoterba I think I've finally resolved it. Final tests are running now on the Cray.
=> fix gradle uber JAR asm dependency

src/main/scala/org/broadinstitute/hail/driver/VEP.scala
=> Fixed bug causing type mismatch when using --csq on a VDS 

docs/faq/ExpressionLanguage.md, docs/reference/HailExpressionLanguage.md, src/main/scala/org/broadinstitute/hail/expr/FunctionRegistry.scala, src/main/scala/org/broadinstitute/hail/stats/package.scala, src/test/scala/org/broadinstitute/hail/methods/ExprSuite.scala, src/test/scala/org/broadinstitute/hail/stats/StatsSuite.scala
- added pnorm, qnorm, inverseChiSquaredTailOneDF to stats package
- added tests to StatsSuite
- added pnorm, qnorm, pchisq1tail, qchisq1tail to function registry
- added tests to ExprSuite
- added docs to HailExpressionLanguage.md
=> Added statistical functions useful for meta-analysis, genomic control lambda

src/main/scala/org/broadinstitute/hail/driver/package.scala
Needed to get pyhail going on the Cray again.
=> Set Spark properties from envvar.

docs/commands/annotatealleles_expr.md, docs/commands/splitmulti.md, python/pyhail/dataset.py, src/main/scala/org/broadinstitute/hail/driver/AnnotateAlleles.scala, src/main/scala/org/broadinstitute/hail/driver/AnnotateAllelesExpr.scala, src/main/scala/org/broadinstitute/hail/driver/Command.scala, src/main/scala/org/broadinstitute/hail/driver/SplitMulti.scala, src/test/scala/org/broadinstitute/hail/methods/AnnotateAllelesSuite.scala
- added option to keep * alleles in SplitMulti
- changed va.aIndex from 0 to 1 for bi-allelic sites (consistent with multi-allelic sites) in SplitMulti
=> Added annotatealleles command

src/main/scala/org/broadinstitute/hail/driver/package.scala
=> Fix configuration

src/main/scala/org/broadinstitute/hail/driver/package.scala
=> Fix partition split for large parquet files.

src/main/scala/org/broadinstitute/hail/expr/AST.scala, src/main/scala/org/broadinstitute/hail/expr/FunctionRegistry.scala, src/test/scala/org/broadinstitute/hail/methods/ExprSuite.scala
Ensure that all values produced in exprSuite are serializable.
Fixes #1179
=> Fix two serialization issues in expr language.

src/main/scala/org/broadinstitute/hail/expr/FunctionRegistry.scala, src/test/scala/org/broadinstitute/hail/methods/ExprSuite.scala
=> fix registerNumeric boxed return type

build.gradle, python/pyhail/keytable.py, src/main/scala/org/broadinstitute/hail/driver/package.scala
This is branched off improvekt, that should get checked in first.
=> Exportmongo

src/main/scala/org/broadinstitute/hail/driver/AnnotateGlobalExpr.scala, src/main/scala/org/broadinstitute/hail/expr/AST.scala, src/main/scala/org/broadinstitute/hail/expr/Fun.scala, src/main/scala/org/broadinstitute/hail/expr/FunctionRegistry.scala, src/main/scala/org/broadinstitute/hail/expr/Parser.scala, src/main/scala/org/broadinstitute/hail/expr/package.scala, src/main/scala/org/broadinstitute/hail/methods/Aggregators.scala, src/test/scala/org/broadinstitute/hail/methods/AggregatorSuite.scala
=> fix aggregators

src/main/scala/org/broadinstitute/hail/methods/Aggregators.scala, src/test/scala/org/broadinstitute/hail/methods/AggregatorSuite.scala
=> Iterator fix

python/pyhail/dataset.py, python/pyhail/tests.py
- List of str inputs for condition are modified such that each condition is wrapped in parentheses and multiple conditions are separated by `&&`. Previous was conditions were comma separated.
=> Bug fix for filter commands with list of conditions

python/pyhail/context.py, python/pyhail/dataset.py
repartition.md
filtergenotypes.md
tdt.md
filtersamples_expr.md
exportgen.md
filtervariants_expr.md
persist.md
importplink.md
vep.md
write.md
annotatevariants_expr.md
=> Convert documentation to Python

docs/tutorial/Tutorial.md, python/pyhail/docs/getting_started.rst
- removed getting started stuff from tutorial
=> Updated tutorial and getting started to reflect Spark 2, etc.

python/hail/context.py, src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/test/scala/is/hail/variant/vsm/VSMSuite.scala
Require partitioner.json.gz in VSM.read.
Added hc.write_partitioning to update legacy VDSes.
=> Require partitioner.json.gz in VSM.read.

python/hail/context.py, python/hail/dataset.py, python/hail/keytable.py, python/hail/tests.py, src/main/scala/is/hail/keytable/KeyTable.scala
Improved VariantDataset.variants_keytable docs.
Added KeyTable.printSchema (Scala) and KeyTable.print_schema (Python).
=> Added HailContext.dataframe_to_keytable.

src/main/scala/is/hail/methods/LinearRegression.scala, src/main/scala/is/hail/methods/LogisticRegression.scala
Now that these are Python based, we need to check.
Later I will convert to use nAltAlleles and change documentation.
=> added checks for wasSplit on linreg and logreg

src/main/scala/is/hail/driver/Count.scala, src/main/scala/is/hail/utils/ByteIterator.scala, src/main/scala/is/hail/utils/IntIterator.scala, src/main/scala/is/hail/utils/IteratorInt.scala, src/main/scala/is/hail/utils/richUtils/Implicits.scala, src/main/scala/is/hail/utils/richUtils/RichIterableGenotype.scala, src/main/scala/is/hail/variant/Genotype.scala, src/main/scala/is/hail/variant/GenotypeStream.scala, src/test/scala/is/hail/variant/GenotypeStreamSuite.scala
- added skipLEB128 to byte iterator
- modifed test in GenotypeStreamSuite
Before merging, we should run a larger number of generated examples through the test. @cseed any advise?
=> added hardcallIterater to GenotypeStream

python/hail/context.py, python/hail/stats.py, src/main/scala/is/hail/stats/BaldingNicholsModel.scala, src/main/scala/is/hail/stats/Distributions.scala, src/test/scala/is/hail/stats/BaldingNicholsModelSuite.scala
-Created distribution objects in python hail.stats
-Created corresponding scala objects in Distributions.scala
-Implemented TruncatedBeta Distributions.
=> Added ability to specify distributions for balding nichols

python/hail/dataset.py, src/main/scala/is/hail/driver/SplitMulti.scala, src/main/scala/is/hail/variant/Variant.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/test/scala/is/hail/driver/MinRepSuite.scala, src/test/scala/is/hail/io/SplitSuite.scala
* Supports multi-allelics
* Modified SplitMulti to use the same code
=> Added MinRep

docs/tutorial/Tutorial.md
=> Update Tutorial link to 1000 genomes sample data

python/hail/context.py, src/main/scala/is/hail/stats/BaldingNicholsModel.scala, src/test/scala/is/hail/methods/LinearMixedRegressionSuite.scala, src/test/scala/is/hail/stats/BaldingNicholsModelSuite.scala, src/test/scala/is/hail/stats/ComputeRRMSuite.scala
=> Removed root from Balding-nichols, fixed distribution type string

src/main/scala/is/hail/methods/MendelErrors.scala
This one actually bit me, I was pretty confused until I looked at the source code.
=> fix wrong error message

python/hail/context.py
Literally 4 character change to close issue #1282
=> Changed block_size to min_block_size

python/hail/context.py, python/hail/dataset.py, python/hail/docs/representation/index.rst, python/hail/keytable.py
Primarily fixes a dozen or so formatting issues in docs, but also ported documentation for annotate_alleles_expr function.
=> Fixed formatting issues in docs

python/hail/keytable.py, src/main/scala/is/hail/annotations/Annotation.scala, src/main/scala/is/hail/keytable/KeyTable.scala
=> Fix TDict expansion bug in Annotation.expandTypes.

build.gradle
@cseed @tpoterba Is this a good thing? I now have seen two users who used public channels to get support wrt our change to Spark 2.x .
=> check spark version

docs/reference/HailExpressionLanguage.md, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/test/scala/is/hail/methods/ExprSuite.scala
Also scalatest has the worst matching infrastructure, ever.
cc @lfrancioli @konradjk
=> add groupBy

src/main/scala/is/hail/driver/package.scala
=> add spark ui web url to log output

python/hail/docs/style-guide.txt
=> updated style guide

python/hail/dataset.py, python/hail/docs/tutorial.ipynb, src/main/scala/is/hail/methods/LinearMixedRegression.scala, src/main/scala/is/hail/methods/LinearRegression.scala, src/main/scala/is/hail/methods/LogisticRegression.scala, src/main/scala/is/hail/stats/LogisticRegressionModel.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/test/scala/is/hail/methods/LogisticRegressionSuite.scala
- e.g., now va.logreg.wald.beta is just va.logreg.beta
- changed docs and tests accordingly
=> improved logreg annotation schema

src/main/scala/is/hail/expr/Type.scala
Add random generation of missingness to Type.genValue
=> Fix bug preventing write if `va == NA`

python/hail/docs/_static/rtd_modifications.css
this one makes the blue background go to the top
=> sticky sidebar

python/hail/context.py, python/hail/dataset.py, src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/io/bgen/BgenBlockReader.scala, src/main/scala/is/hail/io/bgen/BgenLoader.scala, src/main/scala/is/hail/io/gen/GenLoader.scala, src/main/scala/is/hail/io/plink/ExportBedBimFam.scala, src/main/scala/is/hail/io/plink/PlinkBlockReader.scala, src/main/scala/is/hail/io/vcf/HtsjdkRecordReader.scala, src/main/scala/is/hail/io/vcf/LoadVCF.scala, src/main/scala/is/hail/methods/SplitMulti.scala, src/main/scala/is/hail/utils/ByteArrayBuilder.scala, src/main/scala/is/hail/utils/richUtils/Implicits.scala, src/main/scala/is/hail/utils/richUtils/RichByteArrayBuilder.scala, src/main/scala/is/hail/variant/Genotype.scala, src/main/scala/is/hail/variant/GenotypeStream.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/main/scala/is/hail/variant/package.scala, src/test/scala/is/hail/utils/LEB128Suite.scala, src/test/scala/is/hail/variant/GenotypeSuite.scala, src/test/scala/is/hail/variant/vsm/VSMSuite.scala
Use Parquet compression.
snappy Parquet compression by default.
Added ByteArrayBuilder.
=> Axed genotype compression.

python/hail/dataset.py
Mostly just adding impute_sex documentation from the markdown, but also fixed two small typos in other locations.
=> Johnc imputesex docsfixes

README.md
=> Removed "Hail" from "Interactive Hail Tutorial"

src/main/scala/is/hail/expr/Fun.scala, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/expr/HailRep.scala, src/main/scala/is/hail/keytable/KeyTable.scala, src/main/scala/is/hail/methods/Filter.scala, src/main/scala/is/hail/methods/IBD.scala, src/main/scala/is/hail/utils/package.scala, src/main/scala/is/hail/variant/Genotype.scala, src/main/scala/is/hail/variant/VariantDataset.scala
=> Added fully unboxed interface to Genotype.

python/hail/dataset.py, src/main/scala/is/hail/methods/VEP.scala
Makes it possible to run on versions other than 81.
=> Added required hail.vep.fasta VEP configuration property.

src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/variant/GenericDataset.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/main/scala/is/hail/variant/package.scala, src/test/scala/is/hail/variant/GenericDatasetSuite.scala, src/test/scala/is/hail/variant/vsm/VSMSuite.scala
- `GenericDataset = VariantSampleMatrix[Annotation]`
- `readGDS` method to `HailContext`
- `GenericDatasetFunctions` with implicit conversion
- Moved read/write `isGenericGenotype` functionality to `GenericDataset`
- Added methods `toGDS` to VDS and `toVDS` to GDS
- Added `GenericDatasetSuite`
=> Added GenericDataset

python/hail/context.py
=> Fix index_bgen doc

python/hail/docs/sql.rst
Following @cseed's work in https://github.com/hail-is/hail/pull/1421.
=> Document how to query genotype information using SQL.

build.gradle, python/hail/docs/conf.py
@tpoterba : Can you test? Use the gradle command `createDocsNoTest`.
=> fixes #1472

python/hail/context.py
The intent of this was mostly docs fixes, but I also fixed a bug with default value of import_gen and import_bgen not being the same.
=> Johnc import bgen docs

src/main/scala/is/hail/expr/FunctionRegistry.scala, src/test/scala/is/hail/methods/ExprSuite.scala
- Array: append, extend
- Set: add, union, difference, intersection, issubset
=> Added new functions on Array and Set

python/hail/dataset.py
=> query_variants doc typo

src/main/scala/is/hail/asm4s/Code.scala, src/main/scala/is/hail/expr/FunctionRegistry.scala
Make invoke search superclasses, use in [].
=> Minor compiler cleanup.

src/main/scala/is/hail/expr/FunctionRegistry.scala
=> remove TBoxed

src/main/scala/is/hail/expr/CM.scala, src/main/scala/is/hail/expr/FunctionRegistry.scala
should merge cleanly after PR #1533 lands
=> Remove more unnecessarily complicated invokes

python/hail/dataset.py, src/main/scala/is/hail/methods/IBD.scala, src/main/scala/is/hail/methods/MaximalIndependentSet.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/test/scala/is/hail/methods/MaximalIndependentSetSuite.scala
Added IBD prune functionality to VDS's.
=> Johnc ibdprune

src/main/scala/is/hail/asm4s/FunctionBuilder.scala, src/main/scala/is/hail/utils/LoggerOutputStream.scala
Should merge cleanly after #1254 merges.
=> print compiled byte code if an error arises from it

src/main/scala/is/hail/io/bgen/BgenBlockReader.scala, src/main/scala/is/hail/io/bgen/BgenLoader.scala, src/main/scala/is/hail/variant/Genotype.scala
Added DosageGenotype.
Directly decode BGEN blocks instead of converting to GenotypeStreams.
Fixed possible bug in BGEN inflation.
=> Optimized BGEN import.

python/hail/dataset.py, src/main/scala/is/hail/methods/Aggregators.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala
Other pull requests will take care of filter functions etc.
=> Moved AnnotateSamplesExpr and AnnotateVariantsExpr to VSM

python/hail/dataset.py, src/main/scala/is/hail/variant/VariantDataset.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala
=> Moved filterVariantsExpr, filterSamplesExpr, aggregateByKey to VSM

python/hail/dataset.py
These tables aren't showing up on website right now because right side of table is messed up. Escape characters end up making it look weird in the code, but these render correctly with these changes.
=> Fixed the tables in lmmreg

python/hail/representation/__init__.py, python/hail/representation/genotype.py, python/hail/tests.py, python/hail/type.py
I purposefully did not add the Call type to the documentation. Will do this in later PR.
=> Added Call type and object in python

python/hail/dataset.py
Also accounted for different `write` signature between GDS and VDS.
=> Added requireTGenotype decorator and _is_generic_genotype to dataset.py

src/main/scala/is/hail/stats/ComputeRRM.scala, src/main/scala/is/hail/utils/richUtils/RichIndexedRowMatrix.scala, src/test/scala/is/hail/utils/RichIndexedRowMatrixSuite.scala
Changes:
-Added RichIndexedRowMatrix with new method .toBlockMatrixDense()
-Added tests for new method 
-Changed ComputeRRM to use new method
=> Rewrote IndexedRowMatrix.toBlockMatrix()

python/hail/dataset.py, python/hail/java.py, src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/expr/AST.scala, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/expr/Parser.scala, src/main/scala/is/hail/io/CassandraConnector.scala, src/main/scala/is/hail/io/SolrConnector.scala, src/main/scala/is/hail/io/annotators/BedAnnotator.scala, src/main/scala/is/hail/io/annotators/IntervalListAnnotator.scala, src/main/scala/is/hail/keytable/KeyTable.scala, src/main/scala/is/hail/methods/GRM.scala, src/main/scala/is/hail/methods/IBD.scala, src/main/scala/is/hail/methods/Pedigree.scala, src/main/scala/is/hail/package.scala, src/main/scala/is/hail/stats/BaldingNicholsModel.scala, src/main/scala/is/hail/stats/RegressionUtils.scala, src/main/scala/is/hail/utils/Context.scala, src/main/scala/is/hail/utils/ErrorHandling.scala, src/main/scala/is/hail/utils/TextTableReader.scala, src/main/scala/is/hail/utils/package.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/test/scala/is/hail/TestUtils.scala, src/test/scala/is/hail/io/ImportVCFSuite.scala, src/test/scala/is/hail/methods/ExprSuite.scala, src/test/scala/is/hail/methods/KeyTableSuite.scala, src/test/scala/is/hail/methods/RenameSamplesSuite.scala, src/test/scala/is/hail/variant/GenericDatasetSuite.scala
This PR breaks "fatal" out into two functions, "fatal" and "abort".  Fatal is for unexpected error handling, and produces a python stacktrace, but 'abort' is for handled, expected errors (like invalid method inputs) and does not generate a stack trace in python.
=> Py stacktrace

python/hail/dataset.py, src/main/scala/is/hail/methods/IBD.scala, src/main/scala/is/hail/methods/MaximalIndependentSet.scala, src/main/scala/is/hail/utils/package.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/test/scala/is/hail/methods/IBDSuite.scala, src/test/scala/is/hail/methods/MaximalIndependentSetSuite.scala, src/test/scala/is/hail/utils/UtilsSuite.scala
Added the ability to specify a tie breaking function to ibd_prune. This allows the user to do things like choosing to keep a case over a control if two people have the same number of relatives.
=> Johnc ibdprune tie breaking

src/main/scala/is/hail/io/annotators/BedAnnotator.scala
=> Fixed bed annotator to be more flexible

src/main/scala/is/hail/expr/AST.scala, src/test/scala/is/hail/methods/FilterSuite.scala
=> Better catch-all error message for weird out-of-place exprs

python/hail/dataset.py, src/main/scala/is/hail/methods/SampleQC.scala, src/main/scala/is/hail/methods/VariantQC.scala, src/main/scala/is/hail/variant/VariantDataset.scala
=> Add root to QC methods

src/main/scala/is/hail/keytable/KeyTable.scala
=> Fixed keytable explode NPE.

python/hail/tests.py, src/main/scala/is/hail/io/vcf/LoadVCF.scala, src/main/scala/is/hail/utils/richUtils/RichRDD.scala, src/test/scala/is/hail/io/ExportVcfSuite.scala, src/test/scala/is/hail/vds/BiallelicMethodsSuite.scala
=> Check for multiallelics in vcf import

src/main/scala/is/hail/variant/Variant.scala, src/test/scala/is/hail/variant/AltAlleleSuite.scala
* Added a quick check in minRep to avoid copmuting things if ref is already minimal
=> Fixed isInsertion and minRep for * (and empty) altAlleles

src/main/scala/is/hail/keytable/KeyTable.scala, src/test/scala/is/hail/methods/KeyTableSuite.scala
oops, thought I PRed this yesterday
=> Fix key table join

python/hail/expr.py, python/hail/keytable.py, python/hail/representation/annotations.py, python/hail/tests.py, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/expr/Type.scala, src/main/scala/is/hail/keytable/KeyTable.scala, src/main/scala/is/hail/keytable/package.scala, src/main/scala/is/hail/utils/IntervalTree.scala, src/main/scala/is/hail/utils/package.scala, src/main/scala/is/hail/variant/Genotype.scala, src/main/scala/is/hail/variant/Variant.scala, src/test/scala/is/hail/methods/ExprSuite.scala
Added Type.ordering.
Added KeyTable.from_py.
=> Added KeyTable.order_by

gradle/wrapper/gradle-wrapper.properties, python/hail/context.py, src/main/scala/is/hail/io/vcf/HtsjdkRecordReader.scala
=> Update docs for import_vcf about filters and pass

python/hail/kinshipMatrix.py, src/main/scala/is/hail/methods/KinshipMatrix.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/test/scala/is/hail/methods/KinshipMatrixSuite.scala
Made it easy to export KinshipMatrix to a tsv file.
=> Implemented tsv export on KinshipMatrix

build.gradle, src/main/scala/is/hail/expr/CompilationHelp.scala, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/expr/HailRep.scala
This gets us back to the ~65s total time referenced in [here](https://github.com/hail-is/hail/pull/1254#issuecomment-274951875), but [ultimately not achieved](https://github.com/hail-is/hail/pull/1254#issuecomment-284071915) by the final PR. In that time, `master`'s speed on that benchmark decreased ~10s.
This PR + [the compiler PR](https://github.com/hail-is/hail/pull/1254) yield about a total 30% reduction in time on that benchmark.
=> Convert some functions to Code

python/hail/dataset.py, src/main/scala/is/hail/methods/SampleQC.scala, src/main/scala/is/hail/variant/Variant.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/test/scala/is/hail/methods/gqDpStatsSuite.scala, src/test/scala/is/hail/variant/AltAlleleSuite.scala, src/test/scala/is/hail/vds/MinRepSuite.scala
* Added test for deletion at multi-allelic site
* Added test for minrep *
=> Fixed isDeletion and added keep_star option to sampleqc

src/test/scala/is/hail/methods/LinearRegressionBurdenSuite.scala
@danking this addresses your comment.
=> removed potential for NPE in linreg burden suite

python/hail/docs/_templates/layout.html, python/hail/docs/conf.py
- See https://github.com/rtfd/sphinx_rtd_theme/pull/346 for description of issue and solution
- Required for search to work with Sphinx v1.5.4+
=> Fix searchbar on website

src/main/scala/is/hail/keytable/KeyTable.scala, src/test/scala/is/hail/methods/KeyTableSuite.scala
=> Fixed bug with key table join.

src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/stats/package.scala, src/test/scala/is/hail/methods/ExprSuite.scala, src/test/scala/is/hail/stats/StatsSuite.scala
=> Add Poisson functions to FunctionRegistry

src/main/scala/is/hail/expr/FunctionRegistry.scala, src/test/scala/is/hail/methods/ExprSuite.scala
=> Implement string splicing

src/main/scala/is/hail/methods/LinearRegressionBurden.scala, src/main/scala/is/hail/stats/RegressionUtils.scala, src/test/scala/is/hail/methods/LinearRegressionBurdenSuite.scala
changed denseStats to statsKeyedRow
=> added interceptFatal tests to linregBurden

build.gradle
testAll triggers testHail and test. test no longer triggers testHail.
**WARNING:** the CI server will not run `testHail` on this branch nor will it run `testHail` after this branch is merged; we must manually edit the
=> add testAll

src/main/scala/is/hail/methods/TDT.scala
=> Fixed integer division bug in TDT.

python/hail/context.py, python/hail/dataset.py, python/hail/docs/tutorial.ipynb, python/hail/keytable.py, python/hail/tests.py, src/main/scala/is/hail/HailContext.scala
HailContext:
- read_keytable -> read_table
VariantDataset:
- from_keytable -> from_table
- variants_keytable -> variants_table
- samples_keytable -> samples_table
- genotypes_keytable -> genotypes_table
KeyTable:
- column_names -> columns
=> More method / param renames, doc fixes.

python/hail/representation/annotations.py, python/hail/representation/genotype.py, python/hail/representation/interval.py, python/hail/representation/variant.py
- genotype.py
- variant.py
- interval.py
- annotations.py
=> added typechecks

src/main/scala/is/hail/io/vcf/ExportVCF.scala, src/test/scala/is/hail/io/ExportVcfSuite.scala
- better error message for invalid export type
- don't support nested collections (bugfix)
=> Better exportvcf behavior

python/hail/dataset.py, python/hail/tests/tests.py, src/main/scala/is/hail/variant/VariantDataset.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala
=> Added unpersist to VDS

src/main/scala/is/hail/expr/FunctionRegistry.scala, src/test/scala/is/hail/methods/ExprSuite.scala
=> Fix dosage bug

python/hail/keytable.py, src/main/scala/is/hail/keytable/KeyTable.scala
=> Added unpersist to Keytable

python/hail/keytable.py, python/hail/tests/tests.py, src/main/scala/is/hail/keytable/KeyTable.scala
=> Added KeyTable range() and indexed()

python/hail/representation/pedigree.py
Annotate a few methods in `pedigree.py` with `@handle_py4j`.
=> Handlepy4j pedigree

python/hail/representation/pedigree.py
Merge #1868 first
Resolves #1831
=> Typecheck pedigree

python/hail/keytable.py
=> added typecheck for keytable

src/main/resources/reference/human_g1k_v37.json, src/main/scala/is/hail/expr/AnnotationImpex.scala, src/main/scala/is/hail/package.scala, src/main/scala/is/hail/utils/package.scala, src/main/scala/is/hail/variant/GenomeReference.scala, src/main/scala/is/hail/variant/Variant.scala, src/test/scala/is/hail/variant/GenomeReferenceSuite.scala
This is a prototype for just build 37. My plan is to add other genome builds, expose as variable in HailContext, and add support for reading JSON from a file not in the Java resources in subsequent PRs.
=> Added GenomeReference and Contig classes

src/main/scala/is/hail/check/Gen.scala, src/main/scala/is/hail/distributedmatrix/BlockMatrixIsDistributedMatrix.scala, src/main/scala/is/hail/distributedmatrix/DistributedMatrix.scala, src/main/scala/is/hail/utils/GridPartitioner.scala, src/main/scala/is/hail/utils/richUtils/RichIndexedRowMatrix.scala, src/test/scala/is/hail/distributedmatrix/BlockMatrixIsDistributedMatrixSuite.scala
@cseed I'd like your thoughts on this interface and implementation. I added this to make implementing PCRelate a little bit easier because many of the operations I wanted on matrices didn't exist on Spark's matrices.
=> implement DistributedMatrix[_]

python/hail/context.py, python/hail/typecheck/__init__.py, python/hail/typecheck/check.py, src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/utils/TextTableReader.scala, src/test/scala/is/hail/utils/TextTableSuite.scala
Needed for UKBB phenotype import.
=> Added quote to import_table.

python/hail/dataset.py, python/hail/keytable.py, src/main/scala/is/hail/keytable/KeyTable.scala, src/main/scala/is/hail/variant/GenericDataset.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala
- VariantDataset.export_variants
- VariantDataset.export_genotypes
- Keytable.export
=> Added parallel export option

python/hail/dataset.py, python/hail/tests/tests.py, src/main/scala/is/hail/distributedmatrix/BlockMatrixIsDistributedMatrix.scala, src/main/scala/is/hail/methods/LDMatrix.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/test/scala/is/hail/distributedmatrix/BlockMatrixIsDistributedMatrixSuite.scala, src/test/scala/is/hail/methods/LDMatrixSuite.scala
Allows for local computation of ld matrix when the matrix is relatively small to improve performance.
=> Johnc ld matrix local

www/style.css
@jbloom22 Here's the parameters you need to change the size of the banner.
=> change size of jobs banner

src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/test/scala/is/hail/io/LoadBgenSuite.scala
=> Resolves #1950

python/hail/dataset.py
Was missing a new line resulting in python code not rendering properly.
=> Fixed Filter Samples Table docs 

src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/methods/Aggregators.scala, src/test/scala/is/hail/methods/AggregatorSuite.scala
I want to use them to answer this bioinformatics.SE question:
https://bioinformatics.stackexchange.com/questions/974/selecting-sites-from-vcf-which-have-an-alt-ad-10
```
from hail import *
hc = HailContext()
(hc.import_vcf('test.vcf')
.filter_variants_expr('gs.exists(g => g.ad[1:].exists(d => d > 10))')
.count())
```
=> Added forall, exists aggregators.

python/hail/docs/overview.rst
(Hi, I found a small typo while randomly reading code/docs. Thanks!)
s/hierarchial/hierarchical/
=> Fix a minor type in python/hail/docs/overview.rst

src/main/scala/is/hail/distributedmatrix/BlockMatrixIsDistributedMatrix.scala
This is a placeholder PR so I don't forget about this bug. I still need to devise a test case that triggers it. I saw it happen on the Broad on-prem cluster.
=> Fix diagonal bug

src/main/scala/is/hail/expr/Type.scala
Found this while working on unsafe stuff.
=> Fix bug in TDict ordering

src/main/scala/is/hail/variant/VariantSampleMatrix.scala
Avoid creating List (!) of genotypes.
=> Use iterator join in VSM.join.

python/hail/dataset.py, python/hail/keytable.py, python/hail/representation/interval.py, python/hail/tests/tests.py, python/hail/typecheck/__init__.py, python/hail/typecheck/check.py, python/hail/typecheck/tests.py
Can check self-type with lazily set checkers.
=> Updated typecheck

src/main/scala/is/hail/expr/Type.scala
Fixes https://github.com/hail-is/hail/issues/2006
=> Fix canCompare on TIterable.

src/main/scala/is/hail/expr/Parser.scala, src/test/scala/is/hail/methods/ExprSuite.scala
Resolves https://github.com/hail-is/hail/issues/1877
=> Added single-quote strings to expr language.

python/hail/dataset.py, python/hail/keytable.py, python/hail/representation/variant.py
=> Add documentation to static methods.

python/hail/dataset.py
=> Link to filter_variants_table in filter_intervals.

python/hail/dataset.py, python/hail/docs/data/sample_mapping.txt
=> Added example of loading dict from file for rename_samples

python/hail/dataset.py, python/hail/keytable.py, python/hail/representation/annotations.py
=> Added pprint to the docs in schema functions and Struct.

src/main/c/Makefile, src/main/scala/is/hail/methods/IBSFFI.scala
This should make it easier to include new C files into Hail.
=> Better makefile

python/hail/docs/_templates/layout.html
Need to make sure that the docs look correct on the artifact from CI.
=> Fix annotation DB docs

python/hail/context.py, python/hail/docs/operators.rst
=> added links to java 8 regex doc and improved example

python/hail/dataset.py, src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/io/bgen/BgenLoader.scala, src/main/scala/is/hail/io/bgen/BgenRecord.scala, src/main/scala/is/hail/io/gen/GenLoader.scala, src/main/scala/is/hail/io/plink/PlinkBlockReader.scala, src/main/scala/is/hail/io/plink/PlinkLoader.scala, src/main/scala/is/hail/methods/Aggregators.scala, src/main/scala/is/hail/stats/InfoScoreCombiner.scala, src/main/scala/is/hail/stats/RegressionUtils.scala, src/main/scala/is/hail/variant/Genotype.scala, src/test/scala/is/hail/io/ExportPlinkSuite.scala, src/test/scala/is/hail/io/ImportPlinkSuite.scala, src/test/scala/is/hail/io/LoadBgenSuite.scala, src/test/scala/is/hail/io/LoadGenSuite.scala, src/test/scala/is/hail/methods/LinearMixedRegressionSuite.scala, src/test/scala/is/hail/methods/LinearRegressionSuite.scala, src/test/scala/is/hail/methods/LogisticRegressionSuite.scala, src/test/scala/is/hail/stats/InfoScoreSuite.scala, src/test/scala/is/hail/variant/GenericDatasetSuite.scala
import_plink, import_bgen return GDS.
Builds on https://github.com/hail-is/hail/pull/2047
=> Towards full generic 2

python/hail/context.py, python/hail/dataset.py, src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/io/vcf/ExportVCF.scala, src/main/scala/is/hail/io/vcf/HtsjdkRecordReader.scala, src/main/scala/is/hail/io/vcf/LoadVCF.scala, src/main/scala/is/hail/variant/Genotype.scala, src/main/scala/is/hail/variant/VariantKeyDatasetFunctions.scala, src/test/scala/is/hail/io/ExportVcfSuite.scala, src/test/scala/is/hail/io/ImportVCFSuite.scala
Builds on part 2: https://github.com/hail-is/hail/pull/2048
=> Towards full generic 3: nuked Gentoype-based VCF import

src/main/scala/is/hail/methods/LDMatrix.scala
Cherry picked commit 7146786ebaba0317cc72aa73cb5ad66f2488d68b from 0.1 branch.
=> Clean up / increase efficiency of LD Matrix method (#2040)

src/main/scala/is/hail/expr/Parser.scala, src/main/scala/is/hail/keytable/KeyTable.scala, src/main/scala/is/hail/variant/Variant.scala, src/test/scala/is/hail/variant/GenomeReferenceSuite.scala
- Added methods to `Variant` that take a `GenomeReference` object
- Reconfigured VariantSubgen to take a Gen[Contig]
- Added a Gen[Contig] from a GenomeReference object
=> Reference Genome #2

src/main/scala/is/hail/annotations/MemoryBlock.scala, src/main/scala/is/hail/annotations/UnsafeRow.scala, src/main/scala/is/hail/expr/Type.scala, src/main/scala/is/hail/io/vcf/LoadVCF.scala, src/test/scala/is/hail/SparkSuite.scala, src/test/scala/is/hail/annotations/UnsafeSuite.scala
Builds on: https://github.com/hail-is/hail/pull/2074
Added optimized unsafe row add to region value builder.  Tests are faster than toward_fullgeneric_4, 0.1 (8m2s vs 9m18s, 0.1: 8m20s).
=> Towards fullgeneric 5

src/test/scala/is/hail/io/ImportVCFSuite.scala
@cseed I can't trigger any bugs, even at higher sizes and counts.
=> random impex tests for VCFs

src/main/scala/is/hail/annotations/MemoryBlock.scala, src/main/scala/is/hail/expr/Type.scala
Made types final.
@tpoterba I think you should rebase GenotypeView on this and use the new accessors there.
We shouldn't be trying to optimize the traversal of types or the field access code now.  The way to optimize these things is to make the types compile-time objects (as they should be) and these accessors will become code generators that turn lookups into things like `byteOffsets` into a compile-time constant.
At some point I think we should go "full unsafe" by using off-heap allocation and change the (region, offset) pair into a Long.  However, this makes error checking harder.  I'll think about when to do that.  I still think getting rid of the triple in VSM is the right next step.
=> Added region value accessors to types.

build.gradle, python/hail/dataset.py, python/hail/docs/experimental.rst, src/main/scala/is/hail/distributedmatrix/BlockMatrixIsDistributedMatrix.scala, src/main/scala/is/hail/methods/PCRelate.scala, src/main/scala/is/hail/methods/SamplePCA.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/main/scala/org/apache/spark/mllib/linalg/distributed/BetterBlockMatrix.scala, src/test/resources/is/hail/methods/runPcRelate.R, src/test/resources/is/hail/methods/runPcRelateOnTrivialExample.R, src/test/scala/is/hail/methods/PCRelateReferenceImplementation.scala, src/test/scala/is/hail/methods/PCRelateSuite.scala
=> PC Relate (#2054)

src/main/scala/is/hail/annotations/ReadRowsRDD.scala, src/test/scala/is/hail/annotations/UnsafeSuite.scala, src/test/scala/is/hail/io/ExportPlinkSuite.scala
Reopening.  Needed by https://github.com/hail-is/hail/pull/2097.  Will address performance once Row is gone and we're full unsafe.
=> Encode/decode values in rowstore.

src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala
This simplifies many of our methods with a `using` primitive for handling `Closeable` objects.
=> Refactor resource usage

src/main/scala/is/hail/sparkextras/OrderedRDD.scala
=> Fixed typo in coalesce

python/hail/keytable.py, python/hail/tests/tests.py
=> Fix up KeyTable.from_py

src/main/scala/is/hail/io/gen/GenLoader.scala, src/main/scala/is/hail/io/vcf/HtsjdkRecordReader.scala, src/main/scala/is/hail/methods/SplitMulti.scala, src/main/scala/is/hail/variant/Genotype.scala, src/main/scala/is/hail/variant/package.scala, src/test/scala/is/hail/io/LoadBgenSuite.scala
Also fixes https://github.com/hail-is/hail/issues/1976
=> Fixed failure on bgen import/hardcalls/write [0.1]

python/hail/dataset.py
=> update to mendel docs

src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala
=> Fix mistakenly committed access modifier change

src/main/scala/is/hail/distributedmatrix/BlockMatrixIsDistributedMatrix.scala, src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala, src/test/scala/is/hail/distributedmatrix/BlockMatrixIsDistributedMatrixSuite.scala
* works
* use hadoop
* fix inputstream reader and uris
* fix bug
* using existing interfaces
* fix comments
=> Read/Write Block Matrix (#2071) for 0.1

python/hail/docs/conf.py, python/hail/ldMatrix.py, python/hail/tests/tests.py, src/main/scala/is/hail/methods/LDMatrix.scala, src/main/scala/is/hail/utils/package.scala, src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala, src/test/scala/is/hail/methods/LDMatrixSuite.scala
* works?
* address PR comments
* optimize imports
* use existing interfaces
* fix imports
* fix syntax error
* remove bad import
* add LDMatrix import
* fix tests for ldmatrix
* fix tests
* clean paths before writing
=> Read/Write LD Matrix (#2073) for 0.1

src/main/java/is/hail/io/compress/BGzipInputStream.java
=> Added more informative message to bgz ZipException

src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala, src/main/scala/is/hail/utils/richUtils/RichRDD.scala, src/main/scala/is/hail/utils/richUtils/RichRDDByteArray.scala
=> Adding checks on header and numPartFiles in copyMerge

src/main/scala/is/hail/io/vcf/ExportVCF.scala, src/test/scala/is/hail/io/ExportVcfSuite.scala
=> [0.1] Fix ExportVCF issue with info field + semicolons

src/main/scala/is/hail/io/vcf/ExportVCF.scala, src/test/scala/is/hail/io/ExportVcfSuite.scala
=> Fix ExportVCF issue with info field + semicolons

src/main/scala/is/hail/io/vcf/LoadVCF.scala, src/test/scala/is/hail/io/ImportVCFSuite.scala
=> Improve performance of VCF Header Check

scripts/test-gcp.sh
=> add test-gcp

src/test/scala/is/hail/utils/BinaryHeapSuite.scala
This takes ~15 minutes right now
=> speed up sameAsReferenceImplementation

src/main/scala/is/hail/utils/BinaryHeap.scala
=> Fix error message

src/test/scala/is/hail/variant/GenotypeSuite.scala
=> Handle null Genotypes in types

python/hail/dataset.py, python/hail/tests/tests.py, src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/test/scala/is/hail/variant/vsm/VSMSuite.scala
=> Reorder samples in VSM

python/hail/keytable.py, src/main/scala/is/hail/keytable/KeyTable.scala, src/main/scala/is/hail/utils/BinaryHeap.scala, src/main/scala/is/hail/utils/Graph.scala, src/test/scala/is/hail/utils/GraphSuite.scala
Merge after #2147 Priority queue.
=> Local Maximal Independent Set

python/hail/keytable.py
=> [0.1] Add docs to KeyTable.collect

python/hail/keytable.py
=> Add docs to KeyTable.collect

src/main/scala/is/hail/expr/AST.scala, src/test/scala/is/hail/methods/ExprSuite.scala
=> condition of if must be Boolean-typed

src/main/scala/is/hail/annotations/MemoryBlock.scala
=> Added ValueVisitor.

src/main/scala/is/hail/annotations/MemoryBlock.scala, src/main/scala/is/hail/stats/package.scala, src/main/scala/is/hail/utils/ArrayBuilder.scala, src/main/scala/is/hail/utils/ArrayStack.scala, src/test/scala/is/hail/utils/ArrayBuilderSuite.scala, src/test/scala/is/hail/utils/ArrayStackSuite.scala
=> Added ArrayStack.

src/main/scala/is/hail/expr/FunctionRegistry.scala, src/test/scala/is/hail/methods/AggregatorSuite.scala
=> fix flatmap when NA is returned

python/hail/docs/getting_started.rst
=> Fix getting started git commands

python/hail/dataset.py, python/hail/keytable.py, python/hail/tests/tests.py, src/main/scala/is/hail/keytable/KeyTable.scala, src/main/scala/is/hail/sparkextras/OrderedRDD.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/test/scala/is/hail/utils/RichRDDSuite.scala
=> Added head methods to KeyTable and VDS

build.gradle, generate-dist-links.sh
resolves #2216 (I already changed the CI server)
=> Issue 2216

src/main/scala/is/hail/keytable/KeyTable.scala, src/test/scala/is/hail/methods/KeyTableSuite.scala
=> add issue2231 test & fix

src/main/scala/is/hail/utils/BinaryHeap.scala, src/test/scala/is/hail/utils/BinaryHeapSuite.scala
I will need this for a forthcoming PR that include tie breaking for maximal independent set.
=> tie breaking heap

python/hail/context.py, python/hail/tests/tests.py, src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/io/plink/PlinkBlockReader.scala, src/main/scala/is/hail/io/plink/PlinkLoader.scala, src/test/scala/is/hail/io/ImportPlinkSuite.scala
=> Add support for A1 as reference allele with PLINK import

python/hail/dataset.py, python/hail/tests/tests.py, src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/test/scala/is/hail/variant/IntervalSuite.scala
I want this for interface purposes, but it's really not usable due to performance. It takes 2 minutes to collect sample.vcf.
I think that py4j is the main culprit, but the history stuff also slows it down a ton.
=> Added VariantDataset.collect

python/hail/keytable.py, src/main/scala/is/hail/keytable/KeyTable.scala, src/main/scala/is/hail/utils/BinaryHeap.scala, src/main/scala/is/hail/utils/Graph.scala, src/test/scala/is/hail/utils/BinaryHeapSuite.scala, src/test/scala/is/hail/utils/GraphSuite.scala
=> Local Maximal Independent Set (#2148)

python/hail/dataset.py, src/main/scala/is/hail/distributedmatrix/BlockMatrixIsDistributedMatrix.scala, src/main/scala/is/hail/methods/PCRelate.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/test/scala/is/hail/methods/PCRelateSuite.scala
Fuse filtering into the PCRelate computation. This prevents realization of a huge kinship matrix.
=> PC Relate unified kinship filtering [PCRI-1]

python/hail/keytable.py, src/main/scala/is/hail/keytable/KeyTable.scala, src/main/scala/is/hail/utils/BinaryHeap.scala, src/main/scala/is/hail/utils/Graph.scala, src/test/scala/is/hail/utils/BinaryHeapSuite.scala
=> Fix bug in MIS that jon found in #2148

python/hail/docs/getting_started_developing.rst
@jbloom22 the PR Scorecard is a classic example of randomness that feels non-random to me. The dice keeps coming up Jon.
=> Include SKAT in required R packages for developers

src/test/scala/is/hail/methods/PCRelateSuite.scala
Our users will interact with a KeyTable so the tests should too.
=> improve pc-relate testing by going through keytable

python/hail/dataset.py, src/main/scala/is/hail/distributedmatrix/BlockMatrixIsDistributedMatrix.scala, src/main/scala/is/hail/methods/PCRelate.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/test/scala/is/hail/methods/PCRelateSuite.scala
=> PC Relate unified kinship filtering [PCRI-1] (#2238) for Master

src/test/scala/is/hail/methods/PCRelateSuite.scala
This test currently takes 3 minutes. I reduce the number of parameters we check.
=> reduce pc relate test time

src/main/scala/is/hail/expr/AST.scala, src/main/scala/is/hail/expr/Fun.scala, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/expr/Type.scala
A `DependentFunCode` is a function that additionally depends on the particular type of its arguments, even if it is otherwise generic. This likely provides a path towards refactoring `TNumeric` as well.
cc: @cseed @jigold
=> Type aware bindings

src/main/scala/is/hail/utils/TempDir.scala, src/main/scala/is/hail/utils/richUtils/RichRDDByteArray.scala, src/test/scala/is/hail/utils/RichRDDSuite.scala
Needed to address #2245 and for export bgen (future PR).
=> Parallel write option for RichRDDByteArray.saveFromByteArrays

build.gradle
That I've seen on some machines.
=> Fix for lmmLargeExampleTest stack overflow.

src/main/scala/is/hail/variant/VariantDataset.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/test/scala/is/hail/io/HardCallsSuite.scala
Otherwise the type and the values in the RDD are (momentarily)
inconsistent.
=> Update type in VSM.mapValues.

src/main/scala/is/hail/variant/HTSGenotypeView.scala
Expose gIsDefined, isLinearScale.
Expose PX for TGenotypeView.
Fixed some offset bugs.
=> Fixes/enhancements to HTSGenotypeView.

src/main/scala/is/hail/methods/LDMatrix.scala, src/test/scala/is/hail/methods/LDMatrixSuite.scala
=> LD matrix improvements [0.2]

src/main/scala/is/hail/methods/LogisticRegression.scala, src/main/scala/is/hail/methods/TDT.scala
Otherwise type and RDD values will (momentarily) disagree.
=> Update RDD and types simultaneously in linreg.

src/main/scala/is/hail/variant/VariantSampleMatrix.scala
This should play well with [the optimizer](https://github.com/hail-is/hail/blob/master/src/main/scala/is/hail/expr/Relational.scala#L189-L192)
=> dropSamples plays well with optimizer

python/hail/dataset.py, python/hail/typecheck/__init__.py, python/hail/typecheck/check.py, src/main/scala/is/hail/methods/PCRelate.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/test/scala/is/hail/methods/PCRelateSuite.scala
=>  PC Relate: Add a desired output flag [PCRI-2] (#2249) for master

src/main/scala/is/hail/annotations/MemoryBlock.scala, src/main/scala/is/hail/check/Gen.scala, src/main/scala/is/hail/check/Prop.scala, src/main/scala/is/hail/expr/Type.scala, src/test/scala/is/hail/annotations/UnsafeSuite.scala
Builds on: https://github.com/hail-is/hail/pull/2298
You might want to wait for that to go in to review.
=> Improvervb

python/hail/dataset.py, python/hail/tests/tests.py, src/main/scala/is/hail/annotations/MemoryBlock.scala, src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/expr/Type.scala, src/main/scala/is/hail/io/vcf/HtsjdkRecordReader.scala, src/main/scala/is/hail/io/vcf/LoadGDB.scala, src/main/scala/is/hail/io/vcf/LoadVCF.scala, src/main/scala/is/hail/methods/Aggregators.scala, src/main/scala/is/hail/methods/SampleQC.scala, src/main/scala/is/hail/methods/VariantQC.scala, src/main/scala/is/hail/sparkextras/OrderedRDD2.scala, src/main/scala/is/hail/variant/Genotype.scala, src/main/scala/is/hail/variant/HTSGenotypeView.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/test/scala/is/hail/utils/UtilsSuite.scala, src/test/scala/is/hail/variant/vsm/VSMSuite.scala
Builds on: https://github.com/hail-is/hail/pull/2302
Last "major" OrderedRDD2 change.  Still need to use it/RegionValue throughout.
=> Integrate OrderedRDD2 in VSM.

src/main/scala/is/hail/expr/Type.scala
I agree with this comment: https://stackoverflow.com/a/17329465/431282
> Lazy val is *not* free (or even cheap). Use it only if you absolutely need laziness for correctness, not for optimization.
I think we should avoid lazy val.  This was borne out when profiling `RegionValue` stuff.
=> Don't use lazy val in Type.

src/main/scala/is/hail/utils/richUtils/RichIndexedRowMatrix.scala, src/test/scala/is/hail/utils/RichIndexedRowMatrixSuite.scala
=> Better RichIndexedRowMatrix.toHailBlockMatrix

python/hail/dataset.py, python/hail/docs/tutorials/expression-language-part-2.ipynb, python/hail/docs/tutorials/hail-overview.ipynb, python/hail/tests/tests.py, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/methods/LinearRegression.scala, src/main/scala/is/hail/stats/RegressionUtils.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/test/scala/is/hail/methods/LinearRegressionSuite.scala, src/test/scala/is/hail/vds/BiallelicMethodsSuite.scala
Other regressions will be forthcoming.
=> Made linreg completely generic.

src/main/scala/is/hail/asm4s/FunctionBuilder.scala
Better error handling:
Attempt to verify correctness of byte code using automatically computed maxes and stack frames. 
- If that prints no messages and throws no exceptions, then everything worked fine.
- If that throws no exception, but prints a message, then verification failed. Print the verification failure message and throw an exception.
- If that throws an exception, then it is likely that auto-computing stack frames failed, so let's try to verify again without the stack frames
- If that prints no messages, then something weird happened, rethrow the original verification exception.
- If that prints a message, then verification failed. Print the verification failure message and throw an exception.
- I've never seen the max-only verifier throw an exception.
I also added a bit that …
=> better fb error handling

python/hail/keytable.py, src/main/scala/is/hail/keytable/KeyTable.scala, src/main/scala/is/hail/utils/Graph.scala, src/test/scala/is/hail/methods/KeyTableSuite.scala, src/test/scala/is/hail/utils/GraphSuite.scala
cc: @konradjk, do you need this in 0.1?
=> teach MIS how to break ties

src/main/scala/is/hail/expr/AST.scala, src/main/scala/is/hail/expr/Fun.scala, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/test/scala/is/hail/methods/ExprSuite.scala
@jigold I'm giving this to you because you looked into uniroot before.  If you prefer I spin the magic wheel, I can do that, too.
This requires a special typecheck method, because other places we have lambdas, we assume they are methods on containers and the lambda argument type is the container element type.
=> Added uniroot.

src/main/scala/is/hail/methods/ImputeSexPlink.scala
=> Changed impute sex to use reference genome and filter intervals

src/main/scala/is/hail/annotations/UnsafeRow.scala, src/main/scala/is/hail/expr/Type.scala, src/main/scala/is/hail/methods/VariantQC.scala, src/main/scala/is/hail/sparkextras/OrderedRDD2.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala
Two go full native, we still need:
- support for region values in expr language,
- support for efficiently inserting multiple values simultaneously.
=> Semi-native annotateVariantsExpr.

python/hail/dataset.py, python/hail/tests/tests.py, src/main/scala/is/hail/sparkextras/OrderedRDD.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala
A bunch of people have been asking for this. Once this is in, I'll rebase it against 0.1 and submit another PR. I'll also follow up with a second PR to remove the multiple-VDS-file-reading from `hc.read`.
=> Added VDS union

src/main/scala/is/hail/annotations/UnsafeRow.scala, src/main/scala/is/hail/annotations/package.scala, src/main/scala/is/hail/expr/Type.scala, src/main/scala/is/hail/methods/VariantQC.scala, src/main/scala/is/hail/sparkextras/OrderedRDD2.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala
@danking @tpoterba Reopening https://github.com/hail-is/hail/pull/2317 from hail-is/hail so stacked PRs show up here.
=> Full native VariantQC.

src/main/scala/is/hail/annotations/MemoryBlock.scala, src/main/scala/is/hail/annotations/UnsafeUtils.scala, src/main/scala/is/hail/asm4s/Code.scala, src/main/scala/is/hail/expr/Type.scala, src/main/scala/is/hail/utils/richUtils/RichCodeMemoryBuffer.scala
A few minor things:
- teach `Code.apply` method to handle arbitrary length sequences of `Code[_]`
- remove unnecessary implicit parameter on `newArray`
- improve `whileLoop` ergonomics by allowing many body instructions
- Add xor and bitwise-negate on Longs and Ints
- fix type of unsigned right shift [JLS 6.5](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-6.html) LUSHR, requires its second argument is an int.
=> code improvements

src/main/scala/is/hail/methods/PCRelate.scala
Dramatically improves performance of PC Relate. Some prior discussion at #2280 .
=> PC Relate with persist annotations

src/main/scala/is/hail/methods/PCRelate.scala
* all the caches!
* two caches and a fix
* space between methods
* cache comments
=> PC Relate with persist annotations (#2365) for Master

python/hail/keytable.py
=> Fix Doc bug in MIS

src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/expr/Type.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala
Added BaseType.
NewAST => BaseIR, MatrixAST => MatrixIR, etc.
=> Cleanup for coming IR.

src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/distributedmatrix/BlockMatrix.scala, src/main/scala/is/hail/distributedmatrix/GridPartitioner.scala, src/main/scala/is/hail/utils/package.scala, src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala, src/main/scala/is/hail/utils/richUtils/RichIndexedRowMatrix.scala, src/main/scala/is/hail/utils/richUtils/RichRDD.scala, src/test/scala/is/hail/distributedmatrix/BlockMatrixSuite.scala, src/test/scala/is/hail/distributedmatrix/GridPartitionerSuite.scala, src/test/scala/is/hail/variant/vsm/VSMSuite.scala
Diff from #2367 diff:
I don't broadcast the serialized Hadoop context.
The only application is to BlockMatrix (there's no RowStore)
=> partitioned read/write for BlockMatrix, 0.1

src/main/scala/is/hail/utils/richUtils/RichIndexedRowMatrix.scala, src/test/scala/is/hail/utils/RichIndexedRowMatrixSuite.scala
This has already landed in 0.1, bringing it over to master now.
=> Better RichIndexedRowMatrix.toHailBlockMatrix (#2297) for Master

src/main/scala/is/hail/expr/Type.scala, src/main/scala/is/hail/utils/richUtils/RichCodeMemoryBuffer.scala
=> fix TStruct.setFieldMissing (fieldIdx shouldn't be Code[Int])

src/main/scala/is/hail/asm4s/Code.scala, src/main/scala/is/hail/expr/Type.scala, src/main/scala/is/hail/expr/ir/BinaryOp.scala, src/main/scala/is/hail/expr/ir/Casts.scala, src/main/scala/is/hail/expr/ir/Children.scala, src/main/scala/is/hail/expr/ir/Compile.scala, src/main/scala/is/hail/expr/ir/Copy.scala, src/main/scala/is/hail/expr/ir/Env.scala, src/main/scala/is/hail/expr/ir/IR.scala, src/main/scala/is/hail/expr/ir/Infer.scala, src/main/scala/is/hail/expr/ir/UnaryOp.scala, src/main/scala/is/hail/expr/ir/package.scala, src/main/scala/is/hail/utils/richUtils/RichCodeMemoryBuffer.scala, src/test/scala/is/hail/expr/ir/CompileSuite.scala
This encapsulates the type dispatch necessary to load and store
annotations.
=> (append|store)Annotation

src/main/scala/is/hail/asm4s/AsmFunction.scala, src/main/scala/is/hail/asm4s/Code.scala, src/main/scala/is/hail/asm4s/FunctionBuilder.scala, src/main/scala/is/hail/expr/Type.scala, src/main/scala/is/hail/expr/ir/BinaryOp.scala, src/main/scala/is/hail/expr/ir/Casts.scala, src/main/scala/is/hail/expr/ir/Children.scala, src/main/scala/is/hail/expr/ir/Compile.scala, src/main/scala/is/hail/expr/ir/Copy.scala, src/main/scala/is/hail/expr/ir/Env.scala, src/main/scala/is/hail/expr/ir/IR.scala, src/main/scala/is/hail/expr/ir/Infer.scala, src/main/scala/is/hail/expr/ir/UnaryOp.scala, src/main/scala/is/hail/expr/ir/package.scala, src/main/scala/is/hail/utils/richUtils/RichCodeMemoryBuffer.scala, src/test/scala/is/hail/asm4s/ASM4SSuite.scala, src/test/scala/is/hail/expr/ir/CompileSuite.scala
This weakens the requirements for using them, obviating the
need for a FunctionBuilder
=> move getStatic and putStatic to Code

python/hail/keytable.py, python/hail/tests/tests.py
=> Implement KeyTable.from_pandas

src/main/scala/is/hail/expr/Type.scala, src/main/scala/is/hail/io/RowStore.scala
@cseed I'm going to assign these all to you in case you want them in over the weekend; otherwise, I'll spin the RNGesus wheel on Monday and reassign?
=> don't store missing bits when elementType is required for containers

python/hail/dataset.py, src/main/scala/is/hail/methods/SplitMulti.scala, src/main/scala/is/hail/sparkextras/OrderedRDD2.scala, src/main/scala/is/hail/variant/VariantKeyDatasetFunctions.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala
Copy new architecture of `split_multi`.
Added `left_aligned` option, removed `max_shift`.
Moved routine to VariantSampleMatrix, require row key is `Variant`.
=> improved minrep

python/hail/dataset.py, src/main/scala/is/hail/methods/SampleQC.scala, src/main/scala/is/hail/methods/VariantQC.scala, src/main/scala/is/hail/variant/HTSGenotypeView.scala, src/main/scala/is/hail/variant/VariantDataset.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/test/scala/is/hail/vds/BiallelicMethodsSuite.scala
And removed the out of date biallelic requirement on variant_qc.
=> Made qc commands fully generic.

src/main/scala/is/hail/io/RowStore.scala
Don't split variable-length encoded ints across compression blocks.  Save a comparison in the inner loop.  As usual, has seemingly negligible effect on performance.  I'm sure it would be significant on the C side.
I don't encode as signed yet.  It makes the termination condition more complicated and I want to think on it a bit more.
=> Avoid end of block checks in int/long en/decoding.

src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/io/vcf/LoadVCF.scala, src/test/scala/is/hail/io/ImportGDBSuite.scala, src/test/scala/is/hail/io/ImportVCFSuite.scala
Let me know if you were envisioning a different behavior. Right now, nothing is checked because I think that's what you wanted. However, I think it's a good idea to check the sample ids.
=> No error checking on LoadVCF if user-provided header file

src/main/scala/is/hail/expr/AST.scala, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/expr/Parser.scala, src/test/scala/is/hail/variant/GenomeReferenceSuite.scala
=> Genome dependent constructors in func registry

python/hail/ldMatrix.py, src/main/scala/is/hail/methods/ExportableMatrix.scala, src/main/scala/is/hail/methods/KinshipMatrix.scala, src/main/scala/is/hail/methods/LDMatrix.scala, src/test/scala/is/hail/methods/LDMatrixSuite.scala
=> rudimentary matrix export as text facilities

src/main/scala/is/hail/expr/AST.scala, src/main/scala/is/hail/expr/Type.scala, src/main/scala/is/hail/io/LoadMatrix.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/test/scala/is/hail/io/ImportMatrixSuite.scala, src/test/scala/is/hail/vds/GRMSuite.scala
Was throwing exception failures.  Return optional by default.  Handle
TInt32 since there can be two TInt32, required and optional.
=> Fix promoteNumeric in light of required/optional types.

python/hail/typ.py
Allows creating TStruct from a list of Field in python (keeping attributes)
=> Added TStruct.from_fields

src/main/scala/is/hail/sparkextras/OrderedRDD2.scala
Fixes problem in LDPruneSuite with one variant per partition.
=> Fix PartitionKeyInfo2

src/main/scala/is/hail/stats/RegressionUtils.scala
Removed deprecated functions and consolidated getPhenoCovCompleteSamples with getPheno[s]CovCompleteSamples. The latter will be overhauled as annotations go away.
=> Trim regression utils

src/main/scala/is/hail/annotations/Annotation.scala, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/utils/ArrayBuilder.scala, src/main/scala/is/hail/utils/TruncatedArrayIndexedSeq.scala, src/test/scala/is/hail/methods/ExprSuite.scala
Minor, maybe, but, with along with some other changes, made a
significant speedup to a pipline of Konrad's.
=> Minor expr optimizations.

python/hail/context.py, python/hail/history.py, python/hail/ldMatrix.py, python/hail/representation/annotations.py, python/hail/representation/genomeref.py, python/hail/representation/genotype.py, python/hail/representation/interval.py, python/hail/representation/pedigree.py, python/hail/representation/variant.py, python/hail/tests/tests.py, python/hail/typ.py, src/main/scala/is/hail/methods/LDMatrix.scala, src/main/scala/is/hail/variant/GenomeReference.scala, src/main/scala/is/hail/variant/Locus.scala, src/test/scala/is/hail/methods/LDMatrixSuite.scala
=> More Python changes for Genome Reference

python/hail/representation/interval.py, python/hail/representation/variant.py, src/main/scala/is/hail/io/vcf/ExportVCF.scala, src/main/scala/is/hail/methods/MendelErrors.scala, src/main/scala/is/hail/variant/Variant.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/test/scala/is/hail/methods/IBDSuite.scala, src/test/scala/is/hail/stats/InbreedingCoefficientSuite.scala, src/test/scala/is/hail/variant/GenomeReferenceSuite.scala
=> Require Genome Reference for Variant methods

src/main/scala/is/hail/io/IndexedBinaryBlockReader.scala, src/main/scala/is/hail/io/bgen/BgenLoader.scala, src/main/scala/is/hail/io/bgen/BgenRecord.scala, src/main/scala/is/hail/io/plink/PlinkBlockReader.scala, src/main/scala/is/hail/io/plink/PlinkLoader.scala
This is for @astheeggeggs.  I assume @tpoterba is going to yell at me for opening too many PRs.
Directly create region values in import_bgen, import_plink.  This should vastly speed up importing UKB in 0.2.
=> Read into region value in PLINK, BGEN import.

python/hail2/expr/column.py, python/hail2/tests.py, src/test/scala/is/hail/variant/GenomeReferenceSuite.scala
@tpoterba If this is too hard to rebase, I can make these same changes on top of your changes. I just wanted a record of what needed to be modified to make the genome reference functionality work.
=> hail2 -- reference genome support

src/main/scala/is/hail/io/bgen/BgenRecord.scala, src/test/scala/is/hail/io/LoadBgenSuite.scala
=> Special case UKB format in BGEN loader.

src/main/scala/is/hail/keytable/KeyTable.scala
=> Add back compatibility to key table on-disk representation

src/main/scala/is/hail/expr/ir/Children.scala, src/main/scala/is/hail/expr/ir/Copy.scala
I somehow forgot to add these cases of the match
=> Implement Children and Copy for Cast

python/hail/dataset.py, python/hail/docs/tutorials/hail-overview.ipynb, python/hail/tests/tests.py, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/test/scala/is/hail/methods/PCASuite.scala
- changed normalized_genotype_pca to pca_normalized_genotypes
- improved doc of nGenotypes
=> simplified python normalization logic in pca

src/main/scala/is/hail/annotations/Memory.java, src/main/scala/is/hail/distributedmatrix/BlockMatrix.scala, src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala, src/test/scala/is/hail/distributedmatrix/BlockMatrixSuite.scala
- used in read/write of breeze dense matrix
=> added unsafe memcpy bytes to/from double

python/hail/linalg/__init__.py, python/hail/linalg/matrix.py, src/main/scala/is/hail/distributedmatrix/BlockMatrix.scala, src/main/scala/is/hail/distributedmatrix/GridPartitioner.scala, src/main/scala/is/hail/utils/richUtils/RichIndexedRowMatrix.scala, src/test/scala/is/hail/distributedmatrix/GridPartitionerSuite.scala
Not intending this to be used yet (e.g. no documentation) but thought this might be useful.  Tried to use it to time matmul on my home computer, but it wasn't using BLAS (and the instructions in the docs didn't work!)  I'll time tomorrow.
=> Added BlockMatrix to Python

src/main/scala/is/hail/methods/PCA.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala
I'm experimenting with this operation independent of its use in PCA and think VSM is the natural home.
=> moved doubleMatrixFromVSM in PCA to toIndexedRowMatrix on VSM

src/main/scala/is/hail/asm4s/Code.scala, src/main/scala/is/hail/expr/ir/BinaryOp.scala
Some operators in anticipation of AST to IR.
=> define <, <=, >=, >, ==, and !=

python/hail/tests/tests.py
- Added assert to tests with `kt1.same(kt2)`
=> Python test fix

python/hail/representation/genomeref.py, src/main/scala/is/hail/variant/GenomeReference.scala
=> Make python GenomeReference lazy

src/main/scala/is/hail/utils/richUtils/RichIndexedRowMatrix.scala
It's now consistent with other recent changes to BlockMatrix and GridPartitioner. I also tried to improve the names.
=> simplified IRM toHailBlockMatrix

src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/test/scala/is/hail/annotations/AnnotationsSuite.scala, src/test/scala/is/hail/io/ExportVCFSuite.scala, src/test/scala/is/hail/io/ImportVCFSuite.scala, src/test/scala/is/hail/io/LoadBgenSuite.scala, src/test/scala/is/hail/io/LoadGenSuite.scala, src/test/scala/is/hail/io/SplitSuite.scala, src/test/scala/is/hail/methods/AggregatorSuite.scala, src/test/scala/is/hail/methods/AnnotateGlobalSuite.scala, src/test/scala/is/hail/methods/AnnotateSuite.scala, src/test/scala/is/hail/methods/ConcordanceSuite.scala, src/test/scala/is/hail/methods/ExportSuite.scala, src/test/scala/is/hail/methods/FilterSuite.scala, src/test/scala/is/hail/methods/ImputeSexSuite.scala, src/test/scala/is/hail/methods/ProgrammaticAnnotationsSuite.scala, src/test/scala/is/hail/methods/SkatSuite.scala, src/test/scala/is/hail/stats/InbreedingCoefficientSuite.scala, src/test/scala/is/hail/testUtils/package.scala, src/test/scala/is/hail/utils/RichVariantSampleMatrix.scala, src/test/scala/is/hail/variant/GenericDatasetSuite.scala, src/test/scala/is/hail/variant/vsm/VSMSuite.scala
Move functions only used in tests to RichVariantSampleMatrix defined
in src/test.
=> Removed unused functions from VSM.

src/main/scala/is/hail/expr/ir/Infer.scala
Forgot to push these up with the previous PRs
=> A couple things missing in infer

python/hail/api2/matrixtable.py, python/hail/api2/table.py, python/hail/expr/expression.py, python/hail/expr/functions.py
depends on #2548 (not a stacked PR because I don't want them to have to go in together)
=> Fix up expression construction

src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala, src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/expr/ir/Compile.scala, src/main/scala/is/hail/utils/richUtils/RichCodeMemoryBuffer.scala
Builds on: https://github.com/hail-is/hail/pull/2563.  Didn't stack (yet).
Had to remove the requiredness on gs since I can't produce it in the IR (minor).
Fixed two bugs along the way: wrong TypeInfo in ArrayMap and loadPrimitive wasn't loading the array address.
=> FilterSamples IR

src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala, src/main/scala/is/hail/expr/Type.scala, src/main/scala/is/hail/utils/richUtils/RichCodeMemoryBuffer.scala, src/test/scala/is/hail/annotations/StagedRegionValueSuite.scala
Mostly making sure staged/unstaged method names match.
=> Some small SRVB cleanups.

src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/keytable/KeyTable.scala, src/main/scala/is/hail/methods/Aggregators.scala, src/test/scala/is/hail/expr/KeyTableIRSuite.scala, src/test/scala/is/hail/methods/KeyTableSuite.scala
@cseed once #2573 I'll probably change this to use that stuff.
=> Keytable filter

src/main/scala/is/hail/asm4s/FunctionBuilder.scala, src/test/scala/is/hail/asm4s/ASM4SSuite.scala, src/test/scala/is/hail/expr/ir/CompileSuite.scala
@danking @cseed I'm not super sure how to handle the types in the method arguments. Right now they're not being checked.
=> add MethodBuilder and tests

src/main/scala/is/hail/distributedmatrix/BlockMatrix.scala, src/main/scala/is/hail/stats/RegressionUtils.scala, src/main/scala/is/hail/utils/richUtils/RichIndexedRowMatrix.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala, src/test/scala/is/hail/utils/RichIndexedRowMatrixSuite.scala, src/test/scala/is/hail/variant/vsm/VSMSuite.scala
I'll add more tests, and I'm still considering whether to rip out or integrate WriteBlocksRDD for IRM. But given how similar this is to the latter, I'm ready for feedback on the new code.
=> VSM writeBlockMatrix

src/main/scala/is/hail/annotations/Region.scala, src/main/scala/is/hail/annotations/RegionValueBuilder.scala, src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala, src/main/scala/is/hail/expr/Type.scala, src/main/scala/is/hail/io/RowStore.scala, src/main/scala/is/hail/utils/richUtils/RichCodeMemoryBuffer.scala, src/test/scala/is/hail/annotations/UnsafeSuite.scala
There is now just public allocate that takes an alignment and a size.  Then update client code.
=> Clean up Region allocate/align interface.

python/hail/api1/context.py, src/main/scala/is/hail/utils/TextTableReader.scala, src/test/scala/is/hail/utils/TextTableSuite.scala
=> Fix TextTableReader delim problem

src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/keytable/KeyTable.scala, src/main/scala/is/hail/rvd/ConcreteRVD.scala, src/main/scala/is/hail/rvd/RVD.scala, src/main/scala/is/hail/variant/VariantSampleMatrix.scala
Implements reading of KeyTable as IR.
=> Keytable read

src/main/scala/is/hail/HailContext.scala
=> Fix forceBGZ behavior [0.1]

src/main/scala/is/hail/HailContext.scala
=> Fix forceBGZ behavior

src/main/scala/is/hail/distributedmatrix/BlockMatrix.scala
@cseed we didn't catch that the OneToOneDependency (by the identity map) is no longer correct after the changes I made to transpose.
=> fixed dependencies on BlockMatrixTransposeRDD

python/hail/expr/functions.py
=> Add binomTest

python/hail/api1/dataset.py, python/hail/api1/tests.py, src/main/scala/is/hail/methods/PCRelate.scala, src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/methods/PCRelateSuite.scala
Added test to invoke PCRelate on BN sample data (runs in ~3s).
=> Moved PCRelate to method object.

build.gradle, python/hail/methods/tests.py
Somewhat stubby.
Dependent on #2578
=> Add package tests to hail.methods

src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala, src/main/scala/is/hail/utils/richUtils/RichRDD.scala, src/test/scala/is/hail/utils/RichRDDSuite.scala
=> Fix writeTable with parallel separate headers to include newline

python/hail/api1/dataset.py, python/hail/api1/tests.py, src/main/scala/is/hail/methods/PCA.scala, src/main/scala/is/hail/variant/MatrixTable.scala
Added test to make sure python is calling the JVM correctly.
=> moved PCA to method object

python/hail/docs/expr/expression.rst, python/hail/expr/expression.py, python/hail/genetics/variant.py, src/main/scala/is/hail/expr/FunctionRegistry.scala
Sorry @catoverdrive, the RNG really likes you recently.
Despite being 1700 lines of changes, I don't think this is a huge commitment to review.
(only a couple of non-doc changes, which I'll point out)
=> Added a pile of docs to expression.py

src/main/scala/is/hail/methods/Skat.scala
This is better than using MatrixTable.rdd becuase (1) we want to get
rid of it and, (2) it copies but that isn't necessary here.
=> Use rdd2 in Skat.

python/hail/methods/statgen.py
@tpoterba I brought back the context of the model as discussed, have a look see. Note that samples is a generic term in this context.
=> Fixed up linreg docs

python/hail/expr/ast.py, python/hail/expr/tests.py
=> Wrap conditional HQL in parens.

build.gradle, python/hail/api1/keytable.py
passes all tests, builds package locally
ripped out (now unused) mongo dependencies
=> added spark 2.2.0 build support

src/main/scala/is/hail/distributedmatrix/RowMatrix.scala, src/test/scala/is/hail/distributedmatrix/RowMatrixSuite.scala
This is en route to removing IndexedRowMatrix and ExportableMatrix
=> added RowMatrix and adapted ExportableMatrix functionality

python/hail/api2/table.py, python/hail/docs/data/explode_example.tsv
Don't know I forgot this in the last round!
=> Add table.explode

python/hail/expr/aggregators.py, python/hail/expr/tests.py
=> Fix fraction aggregator bug

scripts/setup_env
Seems like what Spark 2.2 wants us to do.
=> update setup_env script

python/hail/api2/table.py
Made a few fixes while I was reading.
=> Minor hail2 doc fixes

python/hail/api1/context.py, python/hail/utils/__init__.py, python/hail/utils/misc.py, src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala
@cseed I think this should clean up the entire temp directory when we exit, although I will do some testing. Anything we create in that temp directory (or using create_temp_file) should get cleaned up automatically.
=> temp file support

python/hail/api1/dataset.py, python/hail/docs/methods/index.rst, python/hail/methods/__init__.py, python/hail/methods/family_methods.py, python/hail/methods/tests.py, src/main/scala/is/hail/methods/MendelErrors.scala
=> Ported mendel_errors

src/main/scala/is/hail/variant/MatrixTable.scala
=> appease the type system

src/main/scala/is/hail/variant/MatrixTable.scala
=> rv-ify annotation samples

src/main/scala/is/hail/io/plink/ExportBedBimFam.scala, src/main/scala/is/hail/variant/HTSGenotypeView.scala, src/main/scala/is/hail/variant/MatrixTable.scala
removed mapValuesWithAll
This region value stuff is really some verbose shit.
=> rv-ified filterGenotypes and annotateGenotypesExpr

python/hail/api2/context.py, python/hail/docs/methods/index.rst, python/hail/methods/__init__.py, python/hail/methods/io.py, python/hail/methods/tests.py
@tpoterba I'll comment this back in once #2726 is in (or if this goes in first, you can in that PR):
```
>>> dataset = dataset.annotate_rows(info = dataset.info.annotate(AC=dataset.variant_qc.AC))
```
=> port export_vcf

python/hail/expr/tests.py, src/main/scala/is/hail/expr/Parser.scala, src/test/scala/is/hail/methods/ExprSuite.scala
=> Fix floating point parsing

python/hail/api1/keytable.py, python/hail/api2/table.py, src/main/scala/is/hail/table/Table.scala
=> Fix Table.show to not print enormous lines

python/hail/docs/methods/index.rst, python/hail/methods/__init__.py, python/hail/methods/qc.py, python/hail/methods/tests.py
@lfrancioli -- here's the 0.2 version of concordance
I wasn't sure how to handle describing the requirements for the entry schema. Will it assume there is an entry field "GT" with type Call? For now, I left it the same documentation as `dataset.py`.
=> Port concordance to 0.2

python/hail/docs/methods/index.rst, python/hail/methods/__init__.py, python/hail/methods/io.py
Includes changes from porting export_vcf #2728
=> port export_gen, export_cassandra, export_solr

src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala, src/main/scala/is/hail/expr/Parser.scala, src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/expr/ir/Children.scala, src/main/scala/is/hail/expr/ir/Compile.scala, src/main/scala/is/hail/expr/ir/Emit.scala, src/main/scala/is/hail/expr/ir/IR.scala, src/main/scala/is/hail/expr/ir/Infer.scala, src/main/scala/is/hail/expr/ir/Recur.scala, src/main/scala/is/hail/expr/ir/Subst.scala, src/main/scala/is/hail/table/Table.scala, src/test/scala/is/hail/expr/TableIRSuite.scala, src/test/scala/is/hail/expr/ir/CompileSuite.scala
@cseed @danking I tried to do annotate but I think it's pretty messy right now.
=> first pass at TableAnnotate IR

python/hail/api1/dataset.py, python/hail/api1/tests.py, python/hail/expr/types.py, python/hail/methods/statgen.py, python/hail/methods/tests.py, python/hail/utils/__init__.py
=> Add check for HTS Genotype schema to split_multi_hts

src/main/scala/is/hail/rvd/OrderedRVD.scala, src/main/scala/is/hail/variant/MatrixTable.scala
Builds on: https://github.com/hail-is/hail/pull/2711 (genericintervals7)
You probably want to wait until that goes in to review (hopefully soon)
=> rv-ified filterVariants{Table, List}

python/hail/expr/expression.py
=> Better error message for Expression.__nonzero__

src/main/scala/is/hail/methods/LinearMixedRegression.scala, src/main/scala/is/hail/methods/LinearRegression.scala, src/main/scala/is/hail/methods/LogisticRegression.scala, src/main/scala/is/hail/methods/Skat.scala
=> improve info messages on regressions

python/hail/docs/expr/functions.rst
=> Added missing constructor functions to rst

src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/variant/vsm/VSMSuite.scala
=> writeKeyedBlockMatrix on MatrixTable

src/main/scala/is/hail/expr/AST.scala, src/main/scala/is/hail/expr/CM.scala, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/expr/Parser.scala
=> respect indexes in the EC

src/main/scala/is/hail/methods/PCRelate.scala
So as to keep my forthcoming PR clean.
=> remove unnecessary whitespace

python/hail/api2/context.py, python/hail/api2/table.py, python/hail/methods/misc.py, src/main/scala/is/hail/annotations/Region.scala, src/main/scala/is/hail/table/Table.scala, src/test/scala/is/hail/methods/TableSuite.scala
cc @cseed 
I still need to have it be able to take a list of column keys.
=> Sparse to dense

python/hail/api2/tests.py, src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/variant/MatrixTable.scala
Fixes https://github.com/hail-is/hail/issues/2763
=> Fixed bug in join

python/hail/api1/dataset.py, python/hail/api1/tests.py, python/hail/api2/table.py, src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/methods/AnnotateSuite.scala, src/test/scala/is/hail/methods/ExportSuite.scala, src/test/scala/is/hail/methods/SkatSuite.scala, src/test/scala/is/hail/utils/TextTableSuite.scala, src/test/scala/is/hail/variant/IntervalSuite.scala, src/test/scala/is/hail/variant/vsm/GroupBySuite.scala, src/test/scala/is/hail/variant/vsm/VSMSuite.scala
will do annotateSamplesTable separately.
=> made anntoateVariantsTable consistent in type/value behavior

python/hail/api1/dataset.py, python/hail/api2/tests.py
I did the rebase/push by hand (because, as far as I know, there's no way to pull a rebase with our current github setup) and messed things up.  This fixes it.  Other stuff going into breaking will fail until this goes in.  Oops!
=> fix breaking

python/hail/api2/matrixtable.py, python/hail/api2/table.py, python/hail/api2/tests.py, python/hail/docs/_templates/experimental.rst, python/hail/docs/hail2_tutorials/hail2-overview.ipynb, python/hail/methods/__init__.py, python/hail/methods/qc.py, python/hail/methods/summarize.py, python/hail/methods/tests.py
Once this goes in I will make a second PR (to breaking) that that removes api1, integrates api2, etc.
=> Remove dependence on api1 in api2 (except for HailContext).

python/hail/api2/matrixtable.py, python/hail/api2/tests.py, src/main/scala/is/hail/variant/MatrixTable.scala
This has been useful in the past and @konradjk and Alicia had recent use for it (don't ask)
=> added MT._filter_partitions

python/hail/api1/context.py, python/hail/methods/impex.py, python/hail/methods/statgen.py, src/main/scala/is/hail/HailContext.scala
also includes full get_vcf_metadata.
=> don't call HC methods in methods (ahem)

src/main/scala/is/hail/methods/LogisticRegression.scala, src/test/scala/is/hail/methods/LogisticRegressionSuite.scala, src/test/scala/is/hail/stats/LogisticRegressionModelSuite.scala
=> allow Firth to bypass non-converged MLE, 0.2

build.sbt, project/Build.scala, project/Dependencies.scala, project/build.properties, project/plugins.sbt
cc: @catoverdrive 
See inline commentary on choices made.
=> Add basic sbt support

src/main/scala/is/hail/HailContext.scala
This was the most confusing error I've seen in a while! 😅
=> Fix error message when no files found

python/hail/docs/conf.py, python/hail/docs/expr/functions.rst, python/hail/docs/expr/index.rst, python/hail/docs/expr/utils.rst, python/hail/expr/expression.py, python/hail/expr/functions.py, python/hail/expr/tests.py, python/hail/expr/utils.py
(not a random reviewer assignment, assigned you because of our discussion on Sat.)
=> Added case and switch to expr

src/main/scala/is/hail/utils/richUtils/RichIndexedRowMatrix.scala
block of zeroes needs the correct dimensions (may not be blocksize x blocksize).
=> bug fix in irm.to_block_matrix

src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/io/ImportMatrixSuite.scala, src/test/scala/is/hail/variant/vsm/GroupBySuite.scala
two tests were broken but have been fixed in another branch.
disabling for now.
=> fixed MT.same

python/hail/methods/impex.py
=> add index_bgen docs

build.gradle, python/hail/docs/api.rst, python/hail/matrixtable.py
=> fix missing docs

python/hail/expr/expression.py, python/hail/expr/functions.py, python/hail/matrixtable.py, python/hail/table.py
```
ds = ds.annotate_cols(**table[ds.s])
```
=> Prevent multiple joins from happening if you do this:

src/main/scala/is/hail/annotations/RegionValueBuilder.scala, src/main/scala/is/hail/annotations/UnsafeRow.scala, src/main/scala/is/hail/expr/AnnotationImpex.scala, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/expr/Parser.scala, src/main/scala/is/hail/expr/types/TInterval.scala, src/main/scala/is/hail/io/annotators/BedAnnotator.scala, src/main/scala/is/hail/io/annotators/IntervalList.scala, src/main/scala/is/hail/methods/FilterIntervals.scala, src/main/scala/is/hail/rvd/OrderedRVD.scala, src/main/scala/is/hail/utils/IntervalTree.scala, src/main/scala/is/hail/variant/GenomeReference.scala, src/main/scala/is/hail/variant/Locus.scala, src/test/scala/is/hail/io/ExportVCFSuite.scala, src/test/scala/is/hail/methods/ExprSuite.scala, src/test/scala/is/hail/variant/IntervalSuite.scala
allow specification of whether or not to include endpoints in an interval
=> Interval endpoints

src/main/scala/is/hail/expr/CM.scala
=> improve sequence to not blow stacks

python/hail/expr/expression.py, python/hail/matrixtable.py, python/hail/table.py, python/hail/utils/misc.py, python/hail/utils/struct.py
=> Fix struct errors

scripts/setup_env
Fixes a bug @uqrmaie1 ran into where the hail scripts failed if there was a space in the HAIL_HOME path.
=> handle space in HAIL_HOME path

src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/io/LoadMatrix.scala, src/main/scala/is/hail/rvd/OrderedRVDPartitioner.scala, src/main/scala/is/hail/utils/IntervalTree.scala, src/test/scala/is/hail/io/ImportMatrixSuite.scala
@konradjk some minor tweaks to existing defaults, but otherwise the arguments are the same, plus the no_header flag.
=> [master] add default no-key option to import_matrix, as well as no_header and force_bgz flags.

python/hail/methods/tests.py, src/main/scala/is/hail/methods/FilterIntervals.scala
use the correct type for merging intervals into an interval tree
=> fix filter_intervals

python/hail/docs/expr/expression.rst, python/hail/expr/expression.py, python/hail/expr/tests.py
=> Add array negation.

python/hail/matrixtable.py, python/hail/tests.py, src/main/scala/is/hail/rvd/OrderedRVDPartitioner.scala, src/main/scala/is/hail/variant/MatrixTable.scala
for renaming fields in an otherwise-unchanged MatrixTable.
=> added MatrixTable.rename

python/hail/expr/ast.py, python/hail/matrixtable.py, python/hail/table.py, src/main/scala/is/hail/expr/AST.scala, src/main/scala/is/hail/expr/Parser.scala, src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/expr/ir/Compile.scala, src/main/scala/is/hail/expr/types/TStruct.scala, src/main/scala/is/hail/expr/types/TableType.scala, src/main/scala/is/hail/table/Table.scala, src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/expr/ParserSuite.scala, src/test/scala/is/hail/expr/TableIRSuite.scala, src/test/scala/is/hail/io/ImportMatrixSuite.scala, src/test/scala/is/hail/io/ImportPlinkSuite.scala, src/test/scala/is/hail/io/LoadBgenSuite.scala, src/test/scala/is/hail/io/SplitSuite.scala, src/test/scala/is/hail/methods/AggregatorSuite.scala, src/test/scala/is/hail/methods/AnnotateSuite.scala, src/test/scala/is/hail/methods/ExportSuite.scala, src/test/scala/is/hail/methods/FilterSuite.scala, src/test/scala/is/hail/methods/PCASuite.scala, src/test/scala/is/hail/methods/SelectSuite.scala, src/test/scala/is/hail/methods/TableSuite.scala, src/test/scala/is/hail/methods/gqDpStatsSuite.scala, src/test/scala/is/hail/stats/HWESuite.scala, src/test/scala/is/hail/variant/GenomeReferenceSuite.scala, src/test/scala/is/hail/variant/IntervalSuite.scala, src/test/scala/is/hail/variant/vsm/GroupBySuite.scala, src/test/scala/is/hail/variant/vsm/VSMSuite.scala
added row / global as top-level structs.
=> Table scala expr redesign

python/hail/methods/tests.py, src/main/scala/is/hail/rvd/OrderedRVD.scala, src/test/scala/is/hail/variant/IntervalSuite.scala
Fixes #2949.
I'm going to add some more comprehensive tests also so that these cases get tested.
=> fix filter intervals

build.gradle, python/hail/docs/_templates/navbar_hail.html, www/navbar.html
Just trying to freak you out @tpoterba
=> make devel docs public in website

python/hail/docs/methods/index.rst, python/hail/docs/methods/misc.rst, python/hail/methods/impex.py, python/hail/methods/misc.py
=> docs for grep + filter_intervals

python/hail/docs/utils/index.rst, python/hail/expr/functions.py, python/hail/expr/tests.py, python/hail/methods/tests.py, python/hail/table.py, python/hail/tests.py, python/hail/utils/__init__.py, python/hail/utils/misc.py, src/main/scala/is/hail/variant/MatrixTable.scala
Move Table.range to hl.utils.range_table
=> Add hl.utils.range_matrixtable.

src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/methods/SelectSuite.scala
=> Fix bug in selectRows

python/hail/docs/expr/aggregators.rst, python/hail/expr/aggregators.py, python/hail/expr/ast.py, python/hail/expr/tests.py
=> Add agg.any and agg.all

python/hail/docs/tutorials/hail-overview.ipynb, scripts/hail, scripts/ihail
call (i)python3 in scripts
I also write example as 4 partitions and added overwrite=True otherwise the write can fail if data/1kg_annotations.txt is missing.
=> fixed (api2) links in tutorial

src/main/scala/is/hail/rvd/OrderedRVD.scala, src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala
The hintPartitioner wasn't being handled correctly in OrderedRVD.apply.
=> fix shuffle bug

python/hail/expr/expression.py, python/hail/matrixtable.py, python/hail/table.py
Let's get weird with it, guys.
=> Add show, take, and collect methods on Expression.

python/hail/expr/expression.py, python/hail/expr/tests.py, src/main/scala/is/hail/expr/FunctionRegistry.scala
=> Add default argument to dict.get

python/hail/context.py
Not especially fleshed-out, but at least now there's something there.
=> Add mangy documentation to hl.init

python/hail/context.py, python/hail/expr/expression.py, python/hail/genetics/call.py, python/hail/genetics/interval.py, python/hail/genetics/kinshipMatrix.py, python/hail/genetics/locus.py, python/hail/genetics/pedigree.py, python/hail/genetics/reference_genome.py, python/hail/linalg/matrix.py, python/hail/matrixtable.py, python/hail/methods/family_methods.py, python/hail/methods/impex.py, python/hail/methods/misc.py, python/hail/methods/qc.py, python/hail/methods/statgen.py, python/hail/table.py, python/hail/utils/hadoop_utils.py, python/hail/utils/java.py, python/hail/utils/misc.py, python/hail/utils/tests.py
monkey patch py4j with an exception handler.
=> Removed handle_py4j 

python/hail/expr/expression.py, python/hail/matrixtable.py, python/hail/methods/misc.py, python/hail/methods/tests.py, python/hail/table.py
Also allow `StructExpression.__getitem__` to take an int index.
In the end, pretty easy.
=> make Table.key, MT.{row_key, col_key, partition_key} structs.

python/hail/__init__.py, python/hail/context.py, python/hail/docs/api.rst
=> Expose spark context

python/hail/methods/statgen.py
=> Fix split multi hts

python/hail/matrixtable.py, python/hail/table.py
=> Add error on matrixtable iter

python/hail/matrixtable.py, python/hail/tests.py, src/main/scala/is/hail/methods/Aggregators.scala, src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/variant/vsm/GroupBySuite.scala
@tpoterba I still need to add some tests for GroupedMatrixTable, but what do you think about this?
=> update group_rows_by, GroupedMatrixTable

python/hail/expr/expression.py
=> search aggregations for fields

python/hail/expr/expression.py, python/hail/expr/functions.py, python/hail/expr/tests.py, python/hail/matrixtable.py, python/hail/table.py, python/hail/utils/misc.py, python/hail/utils/struct.py
The top_level=True fixes the join-inside-aggregation behavior
=> Add expression.describe

python/hail/expr/expression.py, python/hail/matrixtable.py, python/hail/table.py, python/hail/tests.py
Table.view_join_rows => Table.index
renamed index_rows => add_row_index, etc.
=> renamed view_join_* => index_*, etc.

python/hail/docs/types.rst, python/hail/expr/expression.py, python/hail/expr/functions.py, python/hail/expr/types.py, python/hail/matrixtable.py, python/hail/table.py, python/hail/tests.py
@konradjk this might break some of your stuff.
make tstruct a str -> Type mapping (and int -> Type mapping since tstructs are ordered).  tstruct.fields is still a tuple of fields, so to get the ith field, use t.fields[i].
=> Made tstruct a str -> Type mapping

python/hail/matrixtable.py, python/hail/table.py, python/hail/tests.py, src/main/scala/is/hail/table/Table.scala, src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/io/ImportPlinkSuite.scala, src/test/scala/is/hail/methods/TableSuite.scala
Also, small bug in matrix table rename.
=> Fix Table 'rename'

python/hail/tests/test_api.py, src/main/scala/is/hail/variant/MatrixTable.scala
=> Fix drop0entries

src/main/scala/is/hail/io/vcf/LoadVCF.scala
=> Fix VCF error message

src/main/scala/is/hail/rvd/OrderedRVD.scala, src/main/scala/is/hail/rvd/OrderedRVDPartitioner.scala, src/main/scala/is/hail/sparkextras/OrderedRDD2.scala, src/main/scala/is/hail/utils/IntervalTree.scala, src/test/scala/is/hail/utils/IntervalSuite.scala
=> Fix partitioner interval check

python/hail/methods/impex.py, python/hail/tests/test_methods.py, src/main/scala/is/hail/io/LoadMatrix.scala, src/test/scala/is/hail/io/ImportMatrixSuite.scala
=> import_matrix_table error on bad keys, also default to int col_ids

python/hail/tests/test_api.py, src/main/scala/is/hail/variant/MatrixTable.scala
=> Fix filter_entries bugs (2!)

python/hail/linalg/blockmatrix.py, src/main/scala/is/hail/linalg/BlockMatrix.scala, src/test/scala/is/hail/linalg/BlockMatrixSuite.scala
Meredith needs the former and I need the latter. I'll add Python tests of all block matrix functionality in subsequent broadcasting PR.
=> element-wise pow and sqrt on BlockMatrix

python/hail/expr/types.py
The hardcoded True and False are fixed in #3054
=> fix tinterval json

src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/variant/vsm/VSMSuite.scala
The modified test catches it. I'll be updating the test further tomorrow as I make changes to BlockMatrix.from_expr and MatrixTable.writeBlockMatrix
=> select_entries bug fix

src/main/scala/is/hail/utils/Py4jUtils.scala, src/main/scala/is/hail/variant/MatrixTable.scala
cleaned/killed a bad import and an unused variable
=> remove bad import

src/main/scala/is/hail/methods/Nirvana.scala, src/main/scala/is/hail/methods/VEP.scala
=> Fix VEP/Nirvana

python/hail/docs/aggregators.rst, python/hail/docs/conf.py, python/hail/docs/functions/index.rst, python/hail/docs/index.rst, python/hail/docs/overview.rst, python/hail/expr/expressions/base_expression.py, python/hail/table.py
This is a rough, first draft. Examples are out of date as well.
=> new overview

build.gradle, python/hail/environment.yml, python/hail/setup.cfg, python/hail/tests/test_methods.py, python/hail/tests/utils.py, src/main/scala/is/hail/HailContext.scala
=> Use nosetests in gradle

python/hail/methods/qc.py, src/main/scala/is/hail/methods/Nirvana.scala
Can you also test this?  As far as I know you're the only one who knows how.
=> remove Variant from Nirvana

src/main/scala/is/hail/methods/VEP.scala, src/main/scala/is/hail/variant/Variant.scala
continue to filter * alleles but remove allele index fixup.  Konrad said it was OK.
I still need to test by hand.
=> rip variant out of VEP

python/hail/context.py, src/main/scala/is/hail/HailContext.scala
=> Add back progress bar

src/main/scala/is/hail/table/Table.scala, src/main/scala/is/hail/variant/MatrixTable.scala
=> Better errors for read

python/hail/tests/test_methods.py, python/hail/tests/utils.py
=> Ported trio_matrix test to 0.2

src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/expr/ir/Compile.scala, src/main/scala/is/hail/methods/SplitMulti.scala
=> simplified compiler interface

python/hail/table.py, src/main/scala/is/hail/table/Table.scala, src/test/scala/is/hail/io/ImportPlinkSuite.scala, src/test/scala/is/hail/methods/PCASuite.scala, src/test/scala/is/hail/testUtils/RichTable.scala, src/test/scala/is/hail/testUtils/package.scala, src/test/scala/is/hail/variant/ReferenceGenomeSuite.scala
move Table.{exists, forall} to test section in Scala
=> implement Table.{any, all} in terms of aggregate

src/main/scala/is/hail/expr/types/Type.scala
Found an unrelated bug while reviewing your join PR
=> Fix isOfType for TTuple

python/hail/expr/aggregators.py, python/hail/expr/expressions/__init__.py, python/hail/expr/expressions/base_expression.py, python/hail/expr/expressions/expression_typecheck.py, python/hail/expr/expressions/typed_expressions.py, python/hail/expr/functions.py, python/hail/expr/types.py, python/hail/matrixtable.py, python/hail/methods/family_methods.py, python/hail/methods/misc.py, python/hail/methods/statgen.py, python/hail/table.py, python/hail/tests/test_expr.py, python/hail/typecheck/check.py
Produces better error messages, and allows for deeply nested
conversion if we want to do that.
=> Add coercion capability to expr typecheckers.

python/hail/__init__.py, python/hail/docs/utils/index.rst, python/hail/tests/test_methods.py, python/hail/tests/test_utils.py, python/hail/typecheck/check.py, python/hail/utils/__init__.py, python/hail/utils/hadoop_utils.py
=> Replace hadoop_read/write/binary with a single hadoop_open method

build.sbt
build.gradle was changed previously
=> update samtools verison in build.sbt

python/hail/expr/aggregators.py, python/hail/expr/expressions/base_expression.py, python/hail/expr/expressions/expression_typecheck.py, python/hail/expr/expressions/typed_expressions.py, python/hail/expr/types.py, python/hail/tests/test_expr.py, python/hail/typecheck/__init__.py, python/hail/typecheck/check.py
Also involves a streamlining of the aggregator typechecking.
=> Teach bools how to math.

src/main/scala/is/hail/annotations/UnsafeRow.scala, src/main/scala/is/hail/rvd/OrderedRVD.scala, src/main/scala/is/hail/rvd/OrderedRVDPartitioner.scala, src/main/scala/is/hail/sparkextras/RepartitionedOrderedRDD.scala
Builds on #3213. I'll rebase this when that goes in.
=> remove Serializable/Partitioner from OrderedRVDPartitioner

src/main/scala/is/hail/expr/ir/Copy.scala
I forgot to add it the first time around. :(
=> add ArrayFlatMap to Copy

python/hail/expr/expressions/typed_expressions.py, python/hail/tests/test_expr.py, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
=> Add StringExpression.startswith and endswith

src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/expr/ir/package.scala
Missed this when I made ir.InsertFields.
=> replace ir.insertStruct with InsertFields node

src/main/scala/is/hail/table/Table.scala, src/main/scala/is/hail/variant/MatrixTable.scala
until we can figure out a better solution :-/
=> don't take IR path on select if more than 500 fields in resulting struct

python/hail/tests/test_api.py, src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/variant/MatrixTable.scala
@danking @tpoterba 
Fixes #3173.
=> fix requiredness erasing in FilterCols IRs

python/hail/expr/aggregators.py, python/hail/expr/functions.py, python/hail/expr/types.py, python/hail/methods/family_methods.py, python/hail/methods/misc.py, python/hail/methods/qc.py, python/hail/methods/statgen.py
Notably, I skipped a bunch where one of multiple types might be output, wasn't sure how you wanted to handle that.
=> Add return typehints in most places

python/hail/matrixtable.py
=> Add example of filtering with a local list to filter_cols

src/main/scala/is/hail/variant/MatrixTable.scala
=> check if keys are preserved in AST for select_rows

python/hail/matrixtable.py, python/hail/table.py
=> Fix filter typechecking

src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/linalg/BlockMatrix.scala, src/main/scala/is/hail/rvd/RVD.scala, src/main/scala/is/hail/utils/ByteTrackingInputStream.scala, src/main/scala/org/apache/spark/ExposedMetrics.scala
=> Add metrics to Hail readRows

python/hail/docs/tutorials-landing.rst, python/hail/docs/tutorials/01-genome-wide-association-study.ipynb, python/hail/docs/tutorials/02-types.ipynb, python/hail/docs/tutorials/03-expressions.ipynb, python/hail/docs/tutorials/04-missingness.ipynb, python/hail/docs/tutorials/05-tables.ipynb, python/hail/docs/tutorials/06-aggregation.ipynb, python/hail/docs/tutorials/07-filter-annotate.ipynb, python/hail/docs/tutorials/08-joins.ipynb, python/hail/docs/tutorials/09-matrixtable.ipynb, python/hail/docs/utils/index.rst, python/hail/expr/expressions/base_expression.py, python/hail/utils/__init__.py, python/hail/utils/tutorial.py, src/main/scala/is/hail/utils/Py4jUtils.scala
also add module functions to download and import 1KG and Movie Lens data
=> Add oxford tutorials to repository

README.md
Building on @maccum 's great changes.
=> Homepage edit

python/hail/tests/test_api.py, src/main/scala/is/hail/variant/MatrixTable.scala
=> Fix aggregate_entries index issue

src/main/scala/is/hail/annotations/UnsafeRow.scala, src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/methods/Skat.scala, src/main/scala/is/hail/rvd/RVD.scala, src/main/scala/is/hail/variant/MatrixTable.scala
still following what we did for TableMapRows and MapEntries
=> MapRows IR

python/hail/expr.py, python/hail/tests/tests.py
requested on gitter by a couple folks
=> add traverse_fields

src/main/scala/is/hail/expr/ir/BinaryOp.scala, src/main/scala/is/hail/expr/ir/Emit.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/test/scala/is/hail/expr/ir/InterpretSuite.scala
Looking for some feedback and advice on what tests to build.
=> Basic shell of interpret

src/main/scala/is/hail/methods/PCA.scala, src/main/scala/is/hail/variant/MatrixTable.scala
Now IndexRowMatrix is properly quarantined inside PCA. Plan is for RowMatrix to subsume uses of IRM everywhere else.
=> replace MatrixTable.toIndexedRowMatrix with toRowMatrix

python/hail/docs/getting_started_developing.rst, python/hail/tests/test_methods.py
=> Include pc relate dependencies in developer getting started

src/main/scala/is/hail/expr/ir/Interpret.scala, src/main/scala/is/hail/expr/ir/Pretty.scala, src/main/scala/is/hail/table/Table.scala, src/main/scala/is/hail/variant/MatrixTable.scala
log.info IR when executing or interpreting.
Example output:
```
2018-04-07 16:57:01 root: INFO: in MatrixTable.value: execute:
(MapEntries
(MatrixLiteral)
(InsertFields
(Ref g)
(x
(ApplyBinaryPrimOp Add
(GetField row_idx
(Ref va))
(GetField col_idx
(Ref sa)))))
```
=> Added ir.Pretty.

python/hail/expr/types.py
It looks like master is somehow broken, last commit didn't build.  This should fix it (missing Python export)
=> fix missing export

python/hail/table.py, src/main/scala/is/hail/rvd/OrderedRVD.scala, src/main/scala/is/hail/rvd/RVD.scala, src/main/scala/is/hail/table/Table.scala
=> Remove some deprecated uses of rdd, copy in Table.

src/main/scala/is/hail/expr/ir/Children.scala, src/main/scala/is/hail/expr/ir/Copy.scala, src/main/scala/is/hail/expr/ir/Emit.scala, src/main/scala/is/hail/expr/ir/IR.scala, src/main/scala/is/hail/expr/ir/Infer.scala, src/main/scala/is/hail/expr/ir/Recur.scala, src/main/scala/is/hail/expr/ir/Subst.scala, src/test/scala/is/hail/expr/ir/CompileSuite.scala
remove *Missingness nodes and MapNA (just use let, if)
=> clean up ir

python/hail/matrixtable.py, src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/methods/AggregatorSuite.scala, src/test/scala/is/hail/methods/KinshipMatrixSuite.scala, src/test/scala/is/hail/methods/LinearMixedRegressionSuite.scala, src/test/scala/is/hail/methods/PCRelateSuite.scala, src/test/scala/is/hail/methods/SelectSuite.scala, src/test/scala/is/hail/methods/SkatSuite.scala, src/test/scala/is/hail/stats/FisherExactTestSuite.scala, src/test/scala/is/hail/stats/InbreedingCoefficientSuite.scala, src/test/scala/is/hail/testUtils/RichMatrixTable.scala, src/test/scala/is/hail/variant/vsm/ExplodeSuite.scala, src/test/scala/is/hail/variant/vsm/GroupBySuite.scala
rewrite select/annotate/drop to go through `_select_cols` in Python
=> MatrixTable column operations all go through select

src/main/scala/is/hail/HailContext.scala
=> Relax Spark version checking.

python/hail/tests/test_methods.py, src/main/scala/is/hail/io/vcf/LoadVCF.scala, src/test/resources/floating_point_array.vcf
=> Fix numeric arrays in import_vcf

python/hail/table.py
=> Check key in python for table join

python/hail/expr/expressions/base_expression.py, python/hail/expr/expressions/expression_utils.py, python/hail/table.py
=> Fix bad error message

src/main/scala/is/hail/annotations/CodeOrdering.scala, src/main/scala/is/hail/asm4s/Code.scala, src/main/scala/is/hail/asm4s/FunctionBuilder.scala, src/main/scala/is/hail/asm4s/package.scala, src/main/scala/is/hail/expr/ir/Compile.scala, src/main/scala/is/hail/expr/ir/Emit.scala, src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala, src/main/scala/is/hail/expr/ir/ExtractAggregators.scala, src/main/scala/is/hail/expr/types/TBinary.scala, src/main/scala/is/hail/expr/types/TInterval.scala, src/main/scala/is/hail/utils/richUtils/RichCodeRegion.scala, src/main/scala/is/hail/variant/ReferenceGenome.scala, src/test/scala/is/hail/asm4s/ASM4SSuite.scala, src/test/scala/is/hail/expr/ir/CompileSuite.scala, src/test/scala/is/hail/expr/ir/ExtractAggregatorsSuite.scala, src/test/scala/is/hail/expr/ir/FunctionSuite.scala, src/test/scala/is/hail/expr/ir/OrderingSuite.scala, src/test/scala/is/hail/variant/ReferenceGenomeSuite.scala
Currently not used anywhere, but I wrote a test for it.
=> CodeOrdering generates code for region value comparison

python/hail/tests/test_utils.py, src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/rvd/OrderedRVDPartitioner.scala
=> Fixed range_matrix_table when n_rows < n_partitions

python/hail/methods/statgen.py
=> Impute sex uses filter_intervals

src/main/scala/is/hail/rvd/RVDContext.scala, src/main/scala/is/hail/sparkextras/ResettableContext.scala
This was a mistake. See https://github.com/hail-is/hail/pull/3365
=> Remove ResettableContext

src/main/scala/is/hail/expr/ir/Interpret.scala
We must control the memory of all Regions with `using`. Currently,
all Regions are on-heap, but this is part of the work to get
them off-heap.
cc: @tpoterba, since you've been working in here.
=> Use Region.scoped in Interpret

python/hail/table.py
=> Typecheck Table.union

python/hail/table.py
@tpoterba interested in your thoughts on this interface-wise
=> Add name option to Table.explode.

src/main/scala/is/hail/annotations/RegionValueBuilder.scala, src/main/scala/is/hail/annotations/WritableRegionValue.scala, src/main/scala/is/hail/expr/types/TStruct.scala
Mostly a convenience function for subsetting a struct on RVB.
=> Add RVB.selectRegionValue

src/main/scala/is/hail/expr/ir/FoldConstants.scala, src/main/scala/is/hail/expr/ir/IR.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/main/scala/is/hail/expr/ir/IsScalarConstant.scala, src/main/scala/is/hail/expr/ir/Optimize.scala, src/main/scala/is/hail/expr/ir/RewriteBottomUp.scala, src/main/scala/is/hail/expr/ir/Simplify.scala, src/main/scala/is/hail/utils/package.scala, src/test/scala/is/hail/methods/AggregatorSuite.scala
builds on (the largish): https://github.com/hail-is/hail/pull/3332
=> fold constants

src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala, src/main/scala/is/hail/asm4s/Code.scala, src/main/scala/is/hail/expr/AST.scala, src/main/scala/is/hail/expr/ir/Children.scala, src/main/scala/is/hail/expr/ir/Copy.scala, src/main/scala/is/hail/expr/ir/Emit.scala, src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala, src/main/scala/is/hail/expr/ir/FoldConstants.scala, src/main/scala/is/hail/expr/ir/IR.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/main/scala/is/hail/expr/ir/Pretty.scala, src/main/scala/is/hail/expr/ir/Recur.scala, src/main/scala/is/hail/expr/ir/TypeCheck.scala, src/main/scala/is/hail/expr/ir/TypeToIRIntermediateClassTag.scala, src/main/scala/is/hail/expr/ir/functions/CallFunctions.scala, src/main/scala/is/hail/expr/ir/functions/Functions.scala, src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala, src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala, src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala, src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala, src/main/scala/is/hail/expr/ir/package.scala, src/main/scala/is/hail/table/Table.scala, src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/expr/ir/CompileSuite.scala, src/test/scala/is/hail/expr/ir/FunctionSuite.scala
@jbloom22 I'm giving this back to you because it's just the changes from #3388 minus the comparison ops.
=> add string constant IR

src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/expr/ir/Simplify.scala, src/main/scala/is/hail/table/Table.scala
added flatten union simplify rule
=> added TableUnion IR node

src/main/scala/is/hail/expr/ir/FoldConstants.scala, src/main/scala/is/hail/expr/ir/IR.scala, src/main/scala/is/hail/expr/ir/functions/CallFunctions.scala, src/main/scala/is/hail/expr/ir/functions/Functions.scala, src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala, src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala, src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
the `isDeterministic` flag tells us whether we can expect a fixed output given a fixed input. It is checked when folding constants to preserve randomness.
@jbloom22, I'm giving this to you because I'm not super sure on which math functions need to have this flag turned off.
=> add isDeterministic flag to IRFunction to help with optimization

python/hail/expr/functions.py, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala, src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala, src/main/scala/is/hail/stats/package.scala, src/test/scala/is/hail/stats/StatsSuite.scala
binomTest refactored to use integer enum instead of string.
=> add binomTest and array / scalar for floating points to IR

src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/variant/MatrixTable.scala
=> localizeEntries bugfix

python/hail/__init__.py
Probably fixes the problem mentioned by @gounir on gitter
=> Fix for weird python inconsistency

src/main/scala/is/hail/asm4s/FunctionBuilder.scala
Based on: https://stackoverflow.com/questions/6963544/search-a-codebase-for-large-methods
Not sure if this is the exact bytecode size, but it is probably a good ballpark estimate.
=> log generated method bytecode size

build.gradle
verified this successfully loads natives on linux and osx
@jbloom22 FYI
=> add netlib dependencies to shadow{Test}Jar

python/hail/methods/family_methods.py, src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/utils/TextTableReader.scala, src/test/scala/is/hail/utils/TextTableSuite.scala
work in progress to add use_cols parameter to table imports
=> add use_cols parameter to TableImport

src/main/scala/is/hail/io/RowStore.scala, src/main/scala/is/hail/rvd/RVD.scala
I tested this on a cluster on a bit of code that @konradjk provided. not super sure if we can actually write a test for this for our test suite.
Fixes #3446
=> fix the thing where we're generating code on executors

src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/table/Table.scala
This was probably the root of the problem from #3493.
Fixes #3492.
=> make TableRange produce OrderedRVD

python/hail/methods/impex.py, python/hail/tests/test_methods.py, src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/io/vcf/HtsjdkRecordReader.scala, src/main/scala/is/hail/io/vcf/LoadVCF.scala, src/main/scala/is/hail/utils/MissingArrayBuilder.scala, src/test/resources/missingFormatArray.vcf, src/test/scala/is/hail/io/ImportVCFSuite.scala
=> Expose 'array_elements_required' in 'import_vcf'

python/hail/methods/misc.py
@konradjk Does this change address #3257?
=> Fix #3257: MIS docs clarification

src/main/scala/is/hail/io/RowStore.scala
=> fix not clearing per item

src/main/scala/is/hail/io/RowStore.scala, src/main/scala/is/hail/rvd/RVD.scala, src/main/scala/is/hail/sparkextras/ContextRDD.scala, src/test/scala/is/hail/sparkextras/ContextRDDSuite.scala
I realized I was missing some region clears from aggregate methods on ContextRDD.
=> Add some missing clears to aggregations

python/hail/__init__.py, python/hail/linalg/blockmatrix.py, src/main/scala/is/hail/linalg/BlockMatrix.scala, src/main/scala/is/hail/linalg/RowMatrix.scala, src/test/scala/is/hail/linalg/BlockMatrixSuite.scala, src/test/scala/is/hail/linalg/RowMatrixSuite.scala
- add index_row option to export
- add more examples to docs
- flip default on random to normal
- partition_size defaults to block_size
=> Add export to BlockMatrix

src/test/scala/is/hail/methods/AggregatorSuite.scala, src/test/scala/is/hail/methods/AnnotateGlobalSuite.scala
=> Speed up AnnotateGlobalSuite.test. Also move it to aggregator suite

src/main/scala/is/hail/io/vcf/LoadGDB.scala, src/main/scala/is/hail/rvd/OrderedRVD.scala
=> build encoder and decoder on master node

src/main/scala/is/hail/asm4s/FunctionBuilder.scala
ham fisted copy-paste on my part.
=> Fix error message when Code[T] emission happens on worker

src/main/scala/is/hail/variant/MatrixTable.scala
I did this and then realized unfilterEntries is only used in a test.  @tpoterba, did you intend to expose this in Python?
=> implement unfilterEntries with IR

src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/expr/ir/Pretty.scala, src/main/scala/is/hail/expr/ir/Simplify.scala, src/main/scala/is/hail/variant/MatrixTable.scala
@cseed @tpoterba Is this what you had in mind? I'm guessing the functions I moved from the IR nodes to MatrixTable will have to end up somewhere else eventually.
=> Consolidate IR: MatrixRead

src/main/scala/is/hail/expr/Relational.scala
`Table.explode` was unconditionally producing `UnpartitionedRVD` backed tables.
=> fix explode

python/hail/tests/test_expr.py, src/main/scala/is/hail/annotations/aggregators/RegionValueMaxIntAggregator.scala, src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
Also added max aggregator to IR function registry.
=> Fix bug in RV Max Aggregator

python/hail/tests/test_expr.py, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala, src/main/scala/is/hail/expr/ir/functions/Functions.scala, src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala, src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala, src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala, src/test/scala/is/hail/methods/ExprSuite.scala, src/test/scala/is/hail/methods/TableSuite.scala
builds on #3519; will rebase when that goes in.
Also moved array function from `UtilFunctions` into it's own file.
=> Add some more functions to IR registry (mostly array ops, casts)

python/hail/table.py, python/hail/tests/test_api.py
=> Add table.transmute_globals

src/main/scala/is/hail/annotations/RegionValue.scala, src/main/scala/is/hail/annotations/UnsafeRow.scala, src/main/scala/is/hail/rvd/OrderedRVD.scala, src/main/scala/is/hail/rvd/OrderedRVDPartitioner.scala, src/main/scala/is/hail/sparkextras/ContextPairRDDFunctions.scala, src/main/scala/is/hail/variant/MatrixTable.scala
@danking this is where I was at. I think I got most of the stuff that the scala tests caught, not sure about python.
=> unkryoserializable region values

src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/table/Table.scala
Also removes local sort code path, because local sort is unreliable.
=> move keyBy to IR

src/main/scala/is/hail/expr/ir/Simplify.scala
=> Add a few more simplification rules

src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/io/RowStore.scala, src/main/scala/is/hail/utils/ByteTrackingInputStream.scala, src/main/scala/is/hail/utils/richUtils/ByteTrackingOutputStream.scala, src/main/scala/org/apache/spark/ExposedMetrics.scala
And improved reporting of input metrics.  Now read/count report identical numbers are match exactly the total on-disk file size.
=> generate output metrics

src/main/scala/is/hail/expr/Relational.scala
cc: @tpoterba 
Some greek yogurt to cool off that spicy meatball.
Large filters, or filters with large globals will clutter up the region unnecessarily. This fix adds clears to the two matrix row filters and the table filter.
=> Fix for Beryl

python/hail/methods/statgen.py
Per conversation with @konradjk @danking regarding user confusion, this PR emphasizes that ld_prune returns a table of pruned variants rather than pruning the matrix table itself. Also corrected but about parallelism.
@danking I could go farther and change the method name to `ld_pruned_variants`, but I'd rather leave whatever interface changes seem optimal for when you add your planned version that actually does the pruning.
=> improve ld_prune docs

python/hail/expr/aggregators.py, python/hail/tests/test_api.py, src/main/scala/is/hail/stats/CallStatsCombiner.scala
=> Remove ploidy requirement for call_stats

src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/expr/ir/Compile.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/test/scala/is/hail/TestUtils.scala
I tested this on #3562 and `test_call_stats` passes now.
=> Fixed InitOp in MatrixMapCols

src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/expr/ir/Simplify.scala, src/main/scala/is/hail/variant/MatrixTable.scala
I also added a small optimization that doesn't copy the column annotations into the row unless we're aggregating. I did this for both `filter_rows` and `annotate_rows`. cc: @cseed
=> teach matrix filter to aggregate

python/hail/tests/test_methods.py, src/main/scala/is/hail/annotations/aggregators/RegionValueCallStatsAggregator.scala, src/main/scala/is/hail/annotations/aggregators/RegionValueStatisticsAggregator.scala, src/main/scala/is/hail/expr/AST.scala, src/main/scala/is/hail/expr/ir/Children.scala, src/main/scala/is/hail/expr/ir/Copy.scala, src/main/scala/is/hail/expr/ir/Emit.scala, src/main/scala/is/hail/expr/ir/IR.scala, src/main/scala/is/hail/expr/ir/Infer.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/main/scala/is/hail/expr/ir/TypeCheck.scala, src/test/scala/is/hail/expr/ir/CompileSuite.scala
and IR node for `SelectFields`.
=> add IR conversion for "drop"

src/main/scala/is/hail/expr/AST.scala
=> Irfraction

python/hail/linalg/blockmatrix.py, python/hail/tests/test_linalg.py, src/main/scala/is/hail/linalg/BlockMatrix.scala
=> Add block matrix indexing and slicing

python/hail/methods/impex.py, python/hail/tests/test_methods.py, src/main/scala/is/hail/io/plink/ExportPlink.scala, src/main/scala/is/hail/io/plink/LoadPlink.scala, src/test/scala/is/hail/TestUtils.scala
I'll add to the log of breaking changes.
I've also updated the name from `position_morgan` to `cm_position`, as Plink 2.0 has settled on centimorgans: https://www.cog-genomics.org/plink/2.0/formats#bim
With this change, I can again import 1kg plink files.
=> Fix/update PLINK centimorgan impex as Float64

src/main/scala/is/hail/expr/Relational.scala
This seems to save like 20 to 30 seconds out of a 2.5 minute pipeline, so like 1/6 to 1/5 saved.
I'm testing this PR and the SplitMulti one (both separately and with changes combined) with:
```
In [1]: import hail as hl
In [2]: hl.init()
In [3]: %%time 
...: hl.split_multi_hts(hl.read_matrix_table('/Users/dking/projects/hail-data/profile.mt').select_entries('GT', 'AD', 'DP', 'GQ', 'PL'))._force_count_rows()
```
=> MatrixMapEntries: copy globals and cols from a partition region

src/main/scala/is/hail/annotations/aggregators/RegionValueArraySumAggregator.scala, src/test/scala/is/hail/methods/AggregatorSuite.scala
=> fix bug in region value array sum aggregators

src/main/scala/is/hail/utils/FlipbookIterator.scala
Scala's reflective access warning refers to referencing a member of an anonymous class that is not also a member of the implemented int.rface / super-class. Because there is no concrete, non-anonymous type that contains that member, there is no normal means to access / call that member. Scala hacks around this issue by inserting a use of Java's reflection library to look up the member at run-time.
The solution is simple: make the class named / non-anonymous/
=> remove reflective access in FlipbookIterator

src/main/scala/is/hail/asm4s/Code.scala, src/main/scala/is/hail/asm4s/FunctionBuilder.scala, src/main/scala/is/hail/expr/AST.scala, src/main/scala/is/hail/expr/ir/Children.scala, src/main/scala/is/hail/expr/ir/Copy.scala, src/main/scala/is/hail/expr/ir/Emit.scala, src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala, src/main/scala/is/hail/expr/ir/IR.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/main/scala/is/hail/expr/ir/TypeCheck.scala, src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala, src/test/scala/is/hail/expr/ir/CompileSuite.scala, src/test/scala/is/hail/expr/ir/MathFunctionsSuite.scala
Builds on #3631.
cc @danking 
(rebased)
=> add uniroot function to IR

src/main/scala/is/hail/expr/ir/Emit.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/test/scala/is/hail/expr/ir/CompileSuite.scala, src/test/scala/is/hail/expr/ir/IRSuite.scala, src/test/scala/is/hail/expr/ir/InterpretSuite.scala
=> fix IR range for start < stop; add some more tests

src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/variant/MatrixTable.scala
=> use array map instead of dict in groupColsBy

src/main/scala/is/hail/expr/ir/Children.scala, src/main/scala/is/hail/expr/ir/Compilable.scala, src/main/scala/is/hail/expr/ir/Copy.scala, src/main/scala/is/hail/expr/ir/Emit.scala, src/main/scala/is/hail/expr/ir/IR.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/main/scala/is/hail/expr/ir/Simplify.scala, src/main/scala/is/hail/expr/ir/TypeCheck.scala, src/main/scala/is/hail/utils/package.scala, src/test/scala/is/hail/TestUtils.scala, src/test/scala/is/hail/expr/ir/IRSuite.scala
=> added additional IR tests

python/hail/tests/test_api.py, src/main/scala/is/hail/variant/MatrixTable.scala
Fixes https://github.com/hail-is/hail/issues/3668
=> fromRowsTable failed if there were globals

python/hail/methods/family_methods.py
=> Fix de_novo docs

python/hail/utils/misc.py
=> Better errors for hl.utils.range_table / range_matrix_table

src/main/scala/is/hail/rvd/KeyedOrderedRVD.scala
=> enlargeToRange bugfix

python/hail/expr/functions.py
- removed `.. doctest::` since these are no longer used
- changed all `hl.eval_expr(x)` to `x.value`
Will do the same for other files in different PRs.
=> Removed doctest directives from functions.py

python/hail/expr/builders.py, python/hail/expr/expressions/base_expression.py, python/hail/expr/expressions/expression_utils.py, python/hail/expr/expressions/typed_expressions.py, python/hail/expr/types.py, python/hail/genetics/call.py, python/hail/matrixtable.py, python/hail/table.py, python/hail/utils/hadoop_utils.py, python/hail/utils/interval.py, python/hail/utils/misc.py
- removed `.. doctest::` since these are no longer used
- changed all hl.eval_expr(x) to x.value
=> remove doctest directive from other files

src/main/scala/is/hail/expr/ir/Casts.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/main/scala/is/hail/expr/ir/functions/CallFunctions.scala, src/main/scala/is/hail/expr/ir/functions/Functions.scala, src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala, src/main/scala/is/hail/variant/Call.scala, src/test/scala/is/hail/expr/ir/CallFunctionsSuite.scala, src/test/scala/is/hail/expr/ir/TestUtils.scala
Call(str):call
Call(array<int32>,bool):call
Call(int32,int32,bool):call
Call(int32,bool):call
Call(bool):call
ploidy(call):int32
[](call,int32):int32
oneHotAlleles(call,array<str>):array<int32>
unphasedDiploidGtIndex(call):int32
=> IR Call Functions

python/hail/tests/test_api.py, python/hail/tests/test_expr.py, src/main/scala/is/hail/expr/Relational.scala
Fixed the following things:
1. initOp was in wrong place for AggregateRows
2. no clearing of rv aggregators between groups in AggregateRows
3. The post-agg function wasn't being used in AggregateCols.
I added more tests in Python.
=> Fix MatrixAggregateColsByKey and MatrixAggregateRowsByKey

python/hail/tests/utils.py, src/main/scala/is/hail/asm4s/Code.scala, src/main/scala/is/hail/expr/AST.scala, src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala, src/main/scala/is/hail/expr/ir/functions/ReferenceGenomeFunctions.scala, src/main/scala/is/hail/io/reference/FASTAReader.scala, src/main/scala/is/hail/io/reference/LiftOver.scala, src/main/scala/is/hail/utils/SerializableHadoopConfiguration.scala, src/main/scala/is/hail/variant/ReferenceGenome.scala, src/test/scala/is/hail/variant/ReferenceGenomeSuite.scala
checked that the python liftover tests pass on a cluster, too.
=> add liftover and reference sequence functions to IR

src/test/scala/is/hail/methods/TableSuite.scala, src/test/scala/is/hail/testUtils/RichTable.scala
it uses the deprecated AST interface
=> Remove RichTable.annotateGlobalExpr.

src/test/scala/is/hail/methods/TableSuite.scala
don't use deprecated AST interface
=> use Table interface in RichTable.{forall, exists}

python/hail/tests/test_api.py, src/main/scala/is/hail/expr/Relational.scala
=> fix partition key bug

src/main/scala/is/hail/expr/ir/BinarySearch.scala, src/main/scala/is/hail/expr/ir/Children.scala, src/main/scala/is/hail/expr/ir/Copy.scala, src/main/scala/is/hail/expr/ir/Emit.scala, src/main/scala/is/hail/expr/ir/IR.scala, src/main/scala/is/hail/expr/ir/Infer.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/main/scala/is/hail/expr/ir/TypeCheck.scala, src/main/scala/is/hail/expr/ir/functions/DictFunctions.scala, src/main/scala/is/hail/expr/ir/functions/Functions.scala, src/main/scala/is/hail/expr/ir/functions/SetFunctions.scala, src/test/scala/is/hail/expr/ir/IRSuite.scala, src/test/scala/is/hail/expr/ir/OrderingSuite.scala
replaced with a single node that does the search on the ordered collection and returns the closest index.
=> remove SetContains, DictContains, DictGet nodes

python/hail/table.py, python/hail/tests/test_api.py, python/hail/tests/test_expr.py, python/hail/tests/test_methods.py, src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/table/Table.scala, src/test/scala/is/hail/methods/AggregatorSuite.scala, src/test/scala/is/hail/methods/TableSuite.scala
Builds on @jigold 's fixes in #3724 
I tested the new AST branch before I added the IR branch as well as in notebook using still-un-IRed functions (like `signum`), but I'm not sure the best way to force that branch to be continue to be tested.
=> IR for aggregate on GroupedTable

src/main/scala/is/hail/expr/ir/package.scala
This quiets some warnings about this file.
=> Import implicit conversions feature

src/main/scala/is/hail/annotations/aggregators/RegionValueInbreedingAggregator.scala, src/main/scala/is/hail/expr/AST.scala, src/main/scala/is/hail/expr/Relational.scala, src/main/scala/is/hail/expr/ir/AggOp.scala, src/main/scala/is/hail/expr/ir/Children.scala, src/main/scala/is/hail/expr/ir/CodeAggregator.scala, src/main/scala/is/hail/expr/ir/Copy.scala, src/main/scala/is/hail/expr/ir/Emit.scala, src/main/scala/is/hail/expr/ir/ExtractAggregators.scala, src/main/scala/is/hail/expr/ir/IR.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/main/scala/is/hail/expr/ir/Pretty.scala, src/main/scala/is/hail/expr/ir/TypeCheck.scala, src/main/scala/is/hail/methods/Aggregators.scala, src/main/scala/is/hail/stats/InbreedingCombiner.scala, src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala, src/test/scala/is/hail/expr/ir/FunctionSuite.scala, src/test/scala/is/hail/expr/ir/InterpretSuite.scala
@cseed I had to add some new Aggregator infrastructure to make this work (multiple SeqOp arguments). Feel free to take a look.
=> RV Aggregator: Inbreeding

src/main/scala/is/hail/annotations/aggregators/RegionValueInbreedingAggregator.scala
We decided to go with copy being a brand new instance for aggregators.
=> Fix copy in inbreeding aggregator

python/hail/methods/impex.py
This is exactly what `enumeration` is for.
=> simplify type checking of entry_fields

python/hail/matrixtable.py, python/hail/tests/test_api.py, src/main/scala/is/hail/expr/Relational.scala
=> Fix bugs in TableAggregateByKey and MatrixAggregateRowsByKey

python/hail/expr/types.py, python/hail/tests/test_expr.py
=> Fix integer typechecking with None

src/main/scala/is/hail/io/IndexBTree.scala, src/test/scala/is/hail/io/IndexBTreeSuite.scala
I need this so I can add another row_field that is the index in the file for the given variant.
=> Teach the btree how to also return the index of the element

src/main/scala/is/hail/annotations/aggregators/RegionValueCounterAggregator.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/test/scala/is/hail/TestUtils.scala
to ensure that combOps are being tested somewhere.
=> use combOps in ir.TestUtils.eval

src/main/scala/is/hail/io/IndexBTree.scala, src/test/scala/is/hail/io/IndexBTreeSuite.scala
`OnDiskBTreeIndexToValue` can index the elements at the base of a BTree.
The BGen BTree is a BTree on the byte-offsets of variants in the BGen file. In a following PR, I will use this class to filter the BGen file to a subset of variants, specified by their index. This kind of filtering happens at the level of bytes, it permits me to avoid decoding/decompressing any variants I don't need.
Ideally, the index would also include the variant keys themselves. That would be a really nice extension of this work and would enable a more natural file-level filtering user experience.
Aside: `IndexBTree` could use some TLC. I'm sort of making the minimal changes to get Caitlin cooking. Last night, I slipped into a rewrite and it's just too big a task to get right before Friday because I don't have …
=> Facility to View BTree as On-Disk Array

src/main/scala/is/hail/annotations/aggregators/RegionValueCollectAsSetAggregator.scala
This was based on feedback Cotton gave me in the Counter PR. I couldn't figure out how to get a nicer count of the number of elements for `result`.
=> refactor collect as set bool

src/main/scala/is/hail/asm4s/FunctionBuilder.scala
@catoverdrive @cseed Is this the line that should be commented in function builder? Must have been a bad rebase somewhere.
=> Comment out verify in function builder

python/hail/table.py
=> Fix docs bugs in row_value

src/main/scala/is/hail/expr/Relational.scala
Doesn't fix the open issue #3814, but will help debug.
=> Add requirement to TableMapRows constructor. 

src/main/scala/is/hail/expr/ir/functions/Functions.scala, src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala, src/test/scala/is/hail/expr/ir/StringFunctionsSuite.scala, src/test/scala/is/hail/testUtils/RichTable.scala
Since Amanda is out, fixed test failure, replacing: https://github.com/hail-is/hail/pull/3817
@catoverdrive wrote it and I already reviewed it.  Last commit is my fix, mostly unrelated to this change.
=> add str and json

python/hail/matrixtable.py
=> Fix MT._annotate_all by removing calls to analyze

python/hail/tests/test_utils.py, src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala
to return False if the path does not exist
Fixes #3725
=> Fix hadoop_is_file and hadoop_is_dir 

src/main/scala/is/hail/expr/Relational.scala
=> Fix TableUnion checks to match Python

src/main/scala/is/hail/methods/VEP.scala
=> Fix VEP CSQ mode

python/hail/matrixtable.py, src/main/scala/is/hail/expr/ir/MatrixIR.scala, src/test/scala/is/hail/methods/LocalLDPruneSuite.scala
=> move aggregations in filter_rows to python

python/hail/matrixtable.py, python/hail/table.py, python/hail/tests/test_api.py, src/main/scala/is/hail/variant/MatrixTable.scala
=> Throw error if user tries to explode a key field

src/main/scala/is/hail/HailContext.scala
=> Better error message for spark.serializer unset

python/hail/__init__.py, python/hail/docs/api.rst, python/hail/docs/experimental.rst, python/hail/experimental/__init__.py, python/hail/tests/test_experimental.py
=> Add experimental module

python/hail/expr/expressions/base_expression.py
=> Fix entry.show()

python/hail/expr/aggregators.py, python/hail/expr/functions.py, python/hail/methods/qc.py, python/hail/methods/statgen.py
These are doc corrections/improvements I'd made in #3825 but then removed from #3833, except for the name changes that would break interface. I'd like to get feedback on those at check-in.
=> Updates to ctt, chisq, fet, hwe docs, retaining interface

python/hail/expr/expressions/typed_expressions.py, python/hail/expr/functions.py
Improvements for locus global position docs. Clarify that global positions start at 0, and include better examples.
=> correct global position docs

python/hail/expr/functions.py
Requested by Jonathan Keebler.
=> add docs for calculation of pl dosage

src/main/scala/is/hail/expr/ir/TableValue.scala
Fixes #3692. I also factored out some of the TableKeyBy logic and tweaked it. If a table is already backed by an OrderedRVD with key ("a", "b", "c") and partition key ("a"), and we do a keyBy(["a", "b"], ["a", "b"]), then no work needs to be done, but we want the OrderedRVDType of the underlying OrderedRVD to remember the stronger invariants it satisfies. That way if we later keyBy(["a", "b", "c"], ["a"]), we don't have to do any work.
=> sort on TableWrite

python/hail/table.py, src/main/scala/is/hail/expr/ir/Simplify.scala, src/main/scala/is/hail/expr/types/MatrixType.scala
=> More simplify rules

python/hail/methods/statgen.py
`_f` has been rendering as subscript `f`
=> fix is_female latex

python/hail/docs/methods/stats.rst, python/hail/linalg/__init__.py, python/hail/linalg/blockmatrix.py, python/hail/methods/__init__.py, python/hail/methods/linear_mixed_model.py, python/test/test_hail/methods/test_statgen.py, src/main/scala/is/hail/io/DoubleInputBuffer.scala, src/main/scala/is/hail/linalg/RowMatrix.scala, src/main/scala/is/hail/methods/LinearMixedRegression.scala, src/main/scala/is/hail/stats/LinearMixedModel.scala
Adds the core LinearMixedModel class
=> LinearMixedModel 0.2

style-guide.md
Code style document wasn't displaying properly.
=> fix markdown indenting

python/hail/docs/aggregators.rst, python/hail/expr/aggregators.py, python/hail/expr/expressions/base_expression.py, python/test/test_hail/expr/test_expr.py, src/main/scala/is/hail/annotations/aggregators/RegionValueLinearRegressionAggregator.scala, src/main/scala/is/hail/expr/AST.scala, src/main/scala/is/hail/expr/FunctionRegistry.scala, src/main/scala/is/hail/expr/ir/AggOp.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/main/scala/is/hail/methods/Aggregators.scala, src/main/scala/is/hail/stats/LinearRegressionCombiner.scala, src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala, src/test/scala/is/hail/methods/AggregatorSuite.scala
I decided not to add the multiple R^2 because I couldn't get it to work and it's something that can be added later. Also, can you review the docs as is? I don't want to write more substantial documentation for this right now.
=> Linear Regression Aggregator

python/hail/ir/ir.py, src/main/scala/is/hail/expr/ir/Children.scala, src/main/scala/is/hail/expr/ir/Compilable.scala, src/main/scala/is/hail/expr/ir/Copy.scala, src/main/scala/is/hail/expr/ir/IR.scala, src/main/scala/is/hail/expr/ir/Infer.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/main/scala/is/hail/expr/ir/PruneDeadFields.scala, src/main/scala/is/hail/expr/ir/TypeCheck.scala, src/main/scala/is/hail/rvd/RVD.scala, src/main/scala/is/hail/sparkextras/ContextRDD.scala, src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/expr/ir/PruneSuite.scala
should fix one of Liam's slowdowns
=> Add MatrixAggregate IR node

python/hail/expr/functions.py, python/test/test_hail/expr/test_expr.py, src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala, src/test/scala/is/hail/expr/ir/GenotypeFunctionsSuite.scala
=> Move plDosage implementation to Python

python/hail/expr/types.py
have java types be preserved on python types where possible
=> preserve jtypes in python

src/main/scala/is/hail/annotations/aggregators/KeyedRegionValueAggregator.scala, src/main/scala/is/hail/asm4s/FunctionBuilder.scala, src/main/scala/is/hail/expr/Parser.scala, src/main/scala/is/hail/expr/ir/AggOp.scala, src/main/scala/is/hail/expr/ir/CodeAggregator.scala, src/main/scala/is/hail/expr/ir/Emit.scala, src/main/scala/is/hail/expr/ir/ExtractAggregators.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/main/scala/is/hail/expr/ir/Pretty.scala, src/main/scala/is/hail/methods/Aggregators.scala, src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala, src/test/scala/is/hail/expr/ir/IRSuite.scala
- Keyed AggOp
- KeyedRegionValueAggregator
- KeyedCodeAggregator
- IR Parser support
- tests
=> Keyed Aggregations

python/hail/docs/methods/genetics.rst, python/hail/docs/methods/index.rst, python/hail/linalg/blockmatrix.py, python/hail/linalg/utils/misc.py, python/hail/methods/__init__.py, python/hail/methods/statgen.py, python/test/test_hail/methods/test_statgen.py
=> ld_matrix method

src/main/scala/is/hail/expr/ir/MatrixValue.scala
assigning you again because I want to be sure I'm using the context correctly.
=> Optimize MatrixValue.entriesRVD

src/main/scala/is/hail/asm4s/FunctionBuilder.scala
Let's just delete this line, since it accidentally keeps getting into master uncommented.
=> Remove debugging line

src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/variant/vsm/VSMSuite.scala
The two deleted tests are covered by Python tests.
=> Clean up a few pieces of MatrixTable.

python/hail/linalg/__init__.py, python/hail/linalg/blockmatrix.py, python/test/test_hail/linalg/test_linalg.py
Factoring out this piece of LMM 0.2 pipeline as a broadly useful SVD method on BlockMatrix
=> reduced SVD on BlockMatrix via local gramian

src/main/scala/is/hail/expr/ir/add-ir-checklist.txt
I'm open to debate about where this should live.
FYI @chrisvittal
=> added IR checklist

python/hail/ir/matrix_ir.py, python/hail/matrixtable.py, python/hail/methods/impex.py, python/test/test_hail/methods/test_impex.py, src/main/scala/is/hail/HailContext.scala, src/main/scala/is/hail/expr/ir/MatrixIR.scala, src/main/scala/is/hail/expr/ir/Pretty.scala, src/main/scala/is/hail/io/bgen/BgenRDD.scala, src/main/scala/is/hail/io/bgen/BgenRDDPartitions.scala, src/main/scala/is/hail/io/bgen/LoadBgen.scala, src/main/scala/is/hail/rvd/OrderedRVD.scala, src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/expr/ir/IRSuite.scala
Builds on: https://github.com/hail-is/hail/pull/3945
=> Add MatrixBGENReader

python/hail/table.py, python/test/test_hail/table/test_table.py, src/main/scala/is/hail/rvd/OrderedRVD.scala, src/main/scala/is/hail/rvd/RVD.scala, src/main/scala/is/hail/rvd/UnpartitionedRVD.scala, src/main/scala/is/hail/table/Table.scala
Fixes https://github.com/hail-is/hail/issues/3619
FYI @konradjk
=> added Table._filter_partitions

src/main/scala/is/hail/expr/ir/TableIR.scala
avoid scan logic if not used
don't rv-ify globals if not needed
The following pipeline was sped up ~7%:
```
t1 = hl.utils.range_table(100 * 1000 * 1000)
t2 = t1.annotate(x = hl.rand_unif(0, 1))
t2.write('t2.ht', overwrite=True)
```
=> improve table map rows

python/hail/docs/functions/index.rst, python/hail/docs/functions/numeric.rst
I think this finally resolves https://github.com/hail-is/hail/issues/1717
=> add uniroot to docs

python/hail/ir/matrix_ir.py, python/hail/matrixtable.py, python/test/hail/test_ir.py, src/main/scala/is/hail/annotations/BroadcastValue.scala, src/main/scala/is/hail/expr/Parser.scala, src/main/scala/is/hail/expr/ir/MatrixIR.scala, src/main/scala/is/hail/expr/ir/PruneDeadFields.scala, src/main/scala/is/hail/expr/ir/Simplify.scala, src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/expr/ir/IRSuite.scala, src/test/scala/is/hail/expr/ir/PruneSuite.scala
keeps the behavior of MatrixTable.unionRows for now; this PR just moves it into IR.
=> add MatrixUnionRows IR node

src/test/scala/is/hail/TestUtilsSuite.scala
This should fail until #3948 goes in.
=> Fixes #3951 - DataProvider bug

src/main/scala/is/hail/expr/ir/functions/DictFunctions.scala, src/main/scala/is/hail/expr/ir/functions/SetFunctions.scala, src/test/scala/is/hail/expr/ir/DictFunctionsSuite.scala, src/test/scala/is/hail/expr/ir/SetFunctionsSuite.scala
fixes #3937 (and related bugs calling contains on empty sets and dicts).
=> fix get and contains on empty set/dict

src/main/scala/is/hail/annotations/OrderedRVIterator.scala, src/main/scala/is/hail/expr/ir/PruneDeadFields.scala, src/main/scala/is/hail/expr/ir/TableIR.scala, src/main/scala/is/hail/rvd/OrderedRVD.scala
=> Fix bug in OrderedRVIterator and PruneDeadFields

python/hail/expr/expressions/base_expression.py, python/hail/expr/expressions/expression_utils.py, python/hail/utils/misc.py
=> Fix bad error message, make 'analyze' errors better

README.md, generate-dist-links.sh, python/hail/docs/index.rst, python/hail/docs/installation.rst, python/hail/docs/soft_dev_instructions.rst
A few small changes to installation and developer docs. I changed how the topics were nested in the installation page and added a section on Contributing to the 'For Software Developers' page.
=> edit getting started docs and developer docs

python/hail/ir/table_ir.py, python/hail/table.py, python/test/hail/table/test_table.py, python/test/hail/test_ir.py, src/main/scala/is/hail/expr/Parser.scala, src/main/scala/is/hail/expr/ir/Pretty.scala, src/main/scala/is/hail/expr/ir/PruneDeadFields.scala, src/main/scala/is/hail/expr/ir/Simplify.scala, src/main/scala/is/hail/expr/ir/TableIR.scala, src/main/scala/is/hail/table/Table.scala, src/main/scala/is/hail/utils/BufferedAggregatorIterator.scala, src/test/scala/is/hail/expr/ir/IRSuite.scala, src/test/scala/is/hail/expr/ir/PruneSuite.scala, src/test/scala/is/hail/utils/BufferedAggregatorIteratorSuite.scala
=> Add TableKeyByAndAggregate node.

src/main/scala/is/hail/io/ElasticsearchConnector.scala
=> Fix elastic search py4j

python/hail/linalg/blockmatrix.py, python/test/hail/linalg/test_linalg.py
Updates behavior and docs so that when SVD is computed via gramian, singular values for negative eigenvalues are set to 0.
=> svd update

src/main/scala/is/hail/expr/ir/Compile.scala, src/main/scala/is/hail/expr/ir/Optimize.scala
This makes the logs MUCH more readable.
=> Make Optimize less noisy when coming from Compile.

python/hail/docs/methods/index.rst, python/hail/docs/methods/stats.rst, python/hail/linalg/blockmatrix.py, python/hail/linalg/utils/__init__.py, python/hail/linalg/utils/misc.py, python/hail/methods/linear_mixed_model.py, python/test/hail/methods/test_statgen.py
Adds LMM constructors `from_mixed_effects` and `from_kinship` and improves lmm math documentation and testing.
=> more lmm2 infrastructure

python/test/hail/table/test_table.py, src/main/scala/is/hail/expr/ir/TableIR.scala
=> Bugfix in TableAggregateByKey

src/main/scala/is/hail/annotations/ExtendedOrdering.scala, src/main/scala/is/hail/annotations/OrderedRVIterator.scala, src/main/scala/is/hail/expr/ir/IR.scala, src/main/scala/is/hail/expr/ir/functions/DictFunctions.scala, src/main/scala/is/hail/expr/types/TBaseStruct.scala, src/main/scala/is/hail/expr/types/TStruct.scala, src/main/scala/is/hail/io/LoadMatrix.scala, src/main/scala/is/hail/rvd/OrderedRVD.scala, src/main/scala/is/hail/rvd/OrderedRVDPartitioner.scala, src/main/scala/is/hail/sparkextras/RepartitionedOrderedRDD.scala, src/main/scala/is/hail/utils/IntervalTree.scala, src/test/scala/is/hail/utils/IntervalSuite.scala, src/test/scala/is/hail/utils/RowIntervalSuite.scala
First step in RVD changes. Rewrites `Interval` to support endpoints that are `Row`s of different lengths. Hopefully comments and test suite are enough to make the semantics clear. If not, let me know what is unclear and I'll add documentation and/or test cases.
=> [RVD1] Interval

python/hail/table.py, python/test/hail/table/test_table.py
=> Fix table.union with key = None

python/hail/expr/aggregators/aggregators.py, python/test/hail/matrixtable/test_matrix_table.py, python/test/hail/table/test_table.py
=> Fix bug with _agg_func producing Indices with source=None

python/hail/expr/expressions/base_expression.py, python/test/hail/expr/test_expr.py
fixes #4081
or comes as close as we can do without a ton of work
=> Slightly improves error message for Expression.__iter__

python/hail/docs/aggregators.rst, python/hail/expr/aggregators/__init__.py, python/hail/expr/aggregators/aggregators.py, python/hail/ir/aggsig.py, python/hail/ir/base_ir.py, python/test/hail/expr/test_expr.py
Depends on #3992.
Resolves https://github.com/hail-is/hail/issues/878.
@tpoterba @catoverdrive Could you please double check I handled the joins, indices, and aggregations properly? Everything I tried besides just copying the indices and aggregations from `agg_expr` resulted in an index mismatch error. My current code generates the right output. I'm just skeptical whether it is robust to other faulty inputs.
=> Expose group_by aggregator in Python

python/hail/methods/misc.py, python/hail/methods/qc.py, src/main/scala/is/hail/methods/Nirvana.scala, src/main/scala/is/hail/methods/VEP.scala
assigning Cotton because we need to make sure we test this and the other VEP PR.
=> Rework VEP and Nirvana to cooperate with IR

python/hail/docs/getting_started.rst
Reported by Theodore Wang [on Zulip](https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/subject/failure.20running.20recent.20builds.20of.20Hail.200.2E2).
=> Include `--jars` in getting started running on a cluster docs

python/hail/expr/expressions/base_expression.py, python/hail/expr/functions.py, python/hail/expr/types.py, python/test/hail/expr/test_expr.py
=> Permit expressions inside literal

python/hail/ir/matrix_ir.py, src/main/scala/is/hail/expr/Parser.scala, src/main/scala/is/hail/expr/ir/MatrixIR.scala, src/main/scala/is/hail/expr/ir/Pretty.scala, src/main/scala/is/hail/expr/ir/PruneDeadFields.scala, src/main/scala/is/hail/expr/ir/TableValue.scala, src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/expr/ir/IRSuite.scala
=> Matrix annotate cols table

python/hail/expr/aggregators/aggregators.py, python/test/hail/expr/test_expr.py
=> Fix agg.mean

python/hail/table.py
=> Add analyze to GroupedTable.aggregate

python/hail/expr/types.py
Can load 5000 cols in 5 seconds
Previously 250 cols took 3 minutes
fixes #4153
=> Fix wide table problem.

src/main/scala/is/hail/variant/RegionValueVariant.scala
=> Fix error message with null values for export vcf

python/hail/docs/functions/index.rst, python/hail/docs/functions/string.rst, python/hail/expr/__init__.py, python/hail/expr/functions.py, python/test/hail/expr/test_expr.py, src/main/scala/is/hail/annotations/UnsafeRow.scala, src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
Calls the Java String.format function https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#format-java.lang.String-java.lang.Object...-
=> Added format function

README.md
these links appear to have been swapped
=> fix swapped links

python/hail/docs/plot.rst, python/hail/plot/plots.py
fixes http://discuss.hail.is/t/skat-table-qq-plot/612
=> fix qq plot on Table source

python/hail/expr/expressions/base_expression.py
=> Better error on "if expression"

python/hail/experimental/ldscore.py, python/test/hail/experimental/test_experimental.py
@jbloom22 Updated `ld_score()` function to use new `locus_windows()` function
=> updated to use locus_windows() function

src/main/scala/is/hail/io/index/IndexReader.scala, src/main/scala/is/hail/io/index/IndexUtils.scala, src/main/scala/is/hail/io/index/IndexWriter.scala, src/main/scala/is/hail/io/index/InternalNodeBuilder.scala, src/main/scala/is/hail/io/index/LeafNodeBuilder.scala, src/test/scala/is/hail/io/IndexSuite.scala
Still to do:
- What should the index file look like for 0 keys? I think it should be 0 bytes and the reader needs to look at the nKeys in the metadata first.
- Incorporate into LoadBGEN
=> Index Writer/Reader

python/test/hail/expr/test_expr.py, src/main/scala/is/hail/stats/package.scala
=> fix chi sq overflow

src/main/scala/is/hail/io/index/IndexReader.scala, src/main/scala/is/hail/io/index/IndexWriter.scala, src/main/scala/is/hail/io/index/InternalNodeBuilder.scala, src/test/scala/is/hail/io/IndexSuite.scala
I broke this separate from #4121 (queryByKey) so the BGEN changes can be done in parallel.
=> Added last key to index file format

src/main/scala/is/hail/rvd/OrderedRVDPartitioner.scala, src/main/scala/is/hail/rvd/OrderedRVPartitionInfo.scala
=> Log unsorted

python/test/hail/table/test_table.py, src/main/scala/is/hail/expr/ir/MatrixIR.scala, src/test/scala/is/hail/methods/TableSuite.scala
=> Table to matrix table bug

python/hail/ir/matrix_ir.py, python/hail/ir/table_ir.py, python/test/hail/test_ir.py, src/main/scala/is/hail/expr/Parser.scala, src/main/scala/is/hail/expr/ir/LiftLiterals.scala, src/main/scala/is/hail/expr/ir/MatrixIR.scala, src/main/scala/is/hail/expr/ir/Pretty.scala, src/main/scala/is/hail/expr/ir/PruneDeadFields.scala, src/main/scala/is/hail/expr/ir/Simplify.scala, src/main/scala/is/hail/expr/ir/TableIR.scala, src/main/scala/is/hail/table/Table.scala, src/main/scala/is/hail/variant/MatrixTable.scala, src/test/scala/is/hail/expr/ir/IRSuite.scala, src/test/scala/is/hail/expr/ir/PruneSuite.scala
The new Literal IR node completely satisfies this functionality.
=> Remove the 'value' argument from TableMapGlobals and MatrixMapGlobals

python/hail/expr/types.py, python/hail/utils/misc.py, python/test/hail/expr/test_expr.py, src/main/scala/is/hail/expr/AnnotationImpex.scala
=> Fix serialization of nan / inf / -inf

python/hail/docs/functions/index.rst, python/hail/docs/functions/numeric.rst, python/hail/expr/__init__.py, python/hail/expr/functions.py, python/test/hail/expr/test_expr.py, src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala, src/main/scala/is/hail/expr/types/TFloat32.scala, src/main/scala/is/hail/expr/types/TFloat64.scala, src/test/scala/is/hail/expr/ir/MathFunctionsSuite.scala
@catoverdrive Could you please double check the registerCodeWithMissingness implementation?
=> Added approx_equal function

python/test/hail/table/test_table.py, src/main/scala/is/hail/expr/ir/TableIR.scala
=>  Fix copy in LocalizeEntries IR node 

src/main/scala/is/hail/sparkextras/RepartitionedOrderedRDD2.scala
:( 
(see https://hail.zulipchat.com/#narrow/stream/123011-Hail-Dev/subject/shuffle.20-.3E.20join.20memory.20leak)
=> replace takeWhile with filter in RepartitionedOrderedRDD2

build.gradle
=> Elasticsearch v6.3

src/main/scala/is/hail/stats/LinearMixedModel.scala
I'm verifying this now, so don't approve yet
=> fix low rank lmm too

src/main/scala/is/hail/HailContext.scala, src/test/scala/is/hail/SparkSuite.scala, src/test/scala/is/hail/expr/ir/TableIRSuite.scala
also added test for this change:
https://github.com/hail-is/hail/pull/4228
made sure that it errored without that change
=> have Scala tests error if memory leak is detected

hail-ci-deploy.sh
Sister PR: https://github.com/hail-is/hail/pull/4220
=> Hail CI Deploy for 0.1

python/test/hail/expr/test_expr.py, src/main/scala/is/hail/annotations/aggregators/RegionValueDownsampleAggregator.scala, src/main/scala/is/hail/stats/DownsampleCombiner.scala, src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala
downsample aggregator throws null pointer exception for empty table
=> handle empty case for downsample

python/test/hail/expr/test_expr.py, src/main/scala/is/hail/annotations/aggregators/RegionValueArraySumAggregator.scala, src/main/scala/is/hail/annotations/aggregators/RegionValueInfoScoreAggregator.scala, src/main/scala/is/hail/annotations/aggregators/RegionValueLinearRegressionAggregator.scala, src/main/scala/is/hail/expr/Parser.scala, src/main/scala/is/hail/expr/ir/AggOp.scala, src/main/scala/is/hail/expr/ir/ExtractAggregators.scala, src/main/scala/is/hail/expr/ir/Interpret.scala, src/main/scala/is/hail/expr/ir/MatrixIR.scala, src/main/scala/is/hail/methods/Aggregators.scala, src/main/scala/is/hail/stats/InfoScoreCombiner.scala, src/main/scala/is/hail/stats/LinearRegressionCombiner.scala, src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala
- Fixed InfoScore, LinearRegression, Sum (Arrays) to work with required types
- Fixed the AggSignature Parser to strip requiredness from the types
=> Fix Aggregator Types

src/main/scala/is/hail/io/index/IndexReader.scala, src/main/scala/is/hail/io/index/IndexWriter.scala, src/main/scala/is/hail/io/index/InternalNodeBuilder.scala, src/test/scala/is/hail/io/IndexSuite.scala
Builds on #4121 
These are the changes based on today's meeting:
- Change default branching factor to 4096
- Removed last key (no longer needed)
- Moved first index into children
=> Index changes

create_config_file.py, hail-ci-deploy.sh
see cloudtools pr: https://github.com/Nealelab/cloudtools/pull/77
=> update deploy script to generate some cloudtools configs

hail-ci-deploy.sh
I ham fingered the name of the credentials. Unfortunately, PR tests do not test the deployment script.
=> Fix Deployment

hail-ci-deploy.sh
Forgot to authorize with gcloud so that I could copy JARs to GCS.
=> Fix 0.1 deployment

src/main/scala/is/hail/io/ElasticsearchConnector.scala
=> backport export_elasticsearch implementation from 0.2 to support nested objects

src/main/scala/is/hail/variant/MatrixTable.scala
=> improve import vcf error message

hail-ci-deploy.sh
see https://github.com/Nealelab/cloudtools/pull/90
=> change latest hash location

python/hail/ir/base_ir.py, python/hail/ir/ir.py, python/hail/ir/matrix_ir.py, python/hail/ir/renderer.py, python/hail/ir/table_ir.py, src/main/scala/is/hail/expr/Parser.scala, src/test/scala/is/hail/expr/ir/IRSuite.scala
`BaseIR.__str__` uses render.
Render tracks Java IR.
Added JavaTable, JavaMatrix IR nodes.
Next I will add ir to Python Table/MatrixTable.
=> Added BaseIR.render.

hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
the test case that I added was failing before this fix.
=> fix arrayscan/fold handling of missingness; add arrayfold tests

hail/python/test/hail/helpers.py
Don't leave the hail subdirectory
=> Adjust the 'resource' discovery logic

hail/python/hail/matrixtable.py, hail/python/test/hail/matrixtable/test_matrix_table.py
=> Fix matrix entry join

hail/python/hail/context.py, hail/python/hail/matrixtable.py
=> warn once on reorder for cols() and entries()

hail/build.gradle
=> Fix deployedSparkVersions in build.gradle

hail-ci-build-image, hail/Makefile, hail/python/hail/dev-environment.yml, hail/python/hail/environment.yml
I updated all packages in conda, ran all python tests, and then updated/added the versions.
=> include versions in .yml files

hail/src/main/scala/is/hail/stats/InbreedingCombiner.scala
=> Inbreeding errors out on multiallelic GTs

hail/python/hail/methods/qc.py
@konradjk this is a copy of vep85-loftee-gcloud.json
=> update vep doc example properties file

hail/src/main/scala/is/hail/stats/CallStatsCombiner.scala
=> Add better error message for call_stats error mode

hail/hail-ci-deploy.sh
I have a partial setup of the website in k8s, will poll for a new hash and update the docs.
=> deploy docs

hail/src/main/scala/is/hail/expr/Parser.scala, hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala, hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala, hail/src/main/scala/is/hail/expr/ir/TableIR.scala, hail/src/main/scala/is/hail/expr/types/MatrixType.scala, hail/src/main/scala/is/hail/expr/types/TableType.scala, hail/src/main/scala/is/hail/io/bgen/IndexBgen.scala, hail/src/main/scala/is/hail/methods/LinearRegression.scala, hail/src/main/scala/is/hail/methods/LocalLDPrune.scala, hail/src/main/scala/is/hail/methods/LogisticRegression.scala, hail/src/main/scala/is/hail/rvd/KeyedOrderedRVD.scala, hail/src/main/scala/is/hail/rvd/OrderedRVD.scala, hail/src/main/scala/is/hail/rvd/OrderedRVDType.scala, hail/src/main/scala/is/hail/stats/LinearMixedModel.scala, hail/src/main/scala/is/hail/table/Table.scala, hail/src/main/scala/is/hail/utils/richUtils/RichContextRDD.scala, hail/src/main/scala/is/hail/variant/MatrixTable.scala
see commit descriptions for details
=> Refactoring RVD interface, pt. 1

hail/src/main/scala/is/hail/rvd/OrderedRVD.scala
purely a rearangement, plus section headings
=> Refactoring RVD interface, pt. 2

Dockerfile.pr-builder, hail-ci-build-image, hail-ci-build.sh, hail/hail-ci-deploy.sh, project-changed.py
Apply the deploy logic to testing.  `TARGET_BRANCH` is set by the ci, see: https://github.com/hail-is/ci/blob/master/pr-build-script.  Renamed needs-redeploy.py => project-changed.py.
=> Only test if changed

hail/src/main/scala/is/hail/annotations/OrderedRVIterator.scala, hail/src/main/scala/is/hail/rvd/OrderedRVD.scala
Move `localKeySort` to `OrderedRVIterator`. Previously, its only dependence on the `producerRegion` parameter was to clear the region as it consumed the producer iterator. That's now handled in `localSort` by a `boundary`.
=> Refactoring RVD interface, pt. 5

hail/src/main/scala/is/hail/rvd/OrderedRVD.scala, hail/src/main/scala/is/hail/sparkextras/ContextPairRDDFunctions.scala, hail/src/main/scala/is/hail/variant/MatrixTable.scala
Okay, last one before the big rename. This is just a bit of cleaning up, and fixing what I think were memory leaks.
Thanks for going through all of these.
=> Refactoring RVD interface, pt. 6

site/hail.nginx.conf
I think this does what we want, but I'm really not sure. It shouldn't harm anything else. I'd like to merge and experiment a bit with it
=> Maybe Redirect to Hail CI PR test pods

ci/ci/prs.py, ci/deployment.yaml
no longer watch batch (integrated with monorepo)
reopening
=> add hail secret

hail/python/hail/methods/statgen.py
=> Clean up old-style phrasing in statgen.py

hail/src/main/scala/is/hail/expr/ir/TableIR.scala
now shuffle the same way we do in keyBy
=> make TableOrderBy not use SafeRow

ci/Dockerfile, ci/Makefile, ci/ci/environment.py, ci/deployment.yaml
I already deployed this because CI is can't deploy anything until this lands. We're currently running rather old CI code (because we neglected to rebuild & deploy CI image when we changed it)
=> fix building ci docker

batch/batch/client.py, ci/ci/prs.py
The mounted docker has gid 412:
```
$ kubectl logs docker-test
srw-rw---- 1 root 412 0 Jul  1 17:49 /var/run/docker.sock
```
I tested by had this fixes it.
=> add fsGroup: 412

hail/hail-ci-build.sh, hail/src/test/scala/is/hail/methods/LocalLDPruneSuite.scala
here we go
please have your SIGKILL at the ready
=> CI build script experiments

batch/batch/server.py
This was somehow lost in the monorepo-ization, was merged into batch as https://github.com/hail-is/batch/pull/55
=> Add UUID to batch jobs

site/hail.nginx.conf
cc: @cseed, this is how we can do dynamic proxying in k8s
=> fix DNS resolution for CI test pods

hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
=> GetTupleElement and GetField IRSuite Tests

hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
=> ApplyBinaryPrimOp and ApplyUnaryPrimOp IRSuite Tests

site/Makefile
This will get site updating with a short downtime while get a proper fix in place for https://github.com/hail-is/hail/issues/4463.
=> site: delete/create instead of apply

hail/python/hail/docs/makeDocs.sh, hail/www/landing.md, hail/www/readme-to-index.xslt
I made a few small changes, but will wait until after this goes in (if the rest of you think it's a good idea) to start making meaningful changes on either side.
=> Fork the website homepage and GitHub README.

hail/python/test/hail/expr/test_expr.py, hail/src/main/scala/is/hail/expr/ir/BinarySearch.scala, hail/src/main/scala/is/hail/expr/ir/functions/DictFunctions.scala, hail/src/test/scala/is/hail/expr/ir/DictFunctionsSuite.scala, hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala
=> Fixes dict get with null key

hail/python/hail/docs/_templates/layout.html
resolves #4486
i have literally no idea if this will work, but we'll see when the pr build finishes.
=> maybe make keyboard shortcut for search docs

hail/src/main/scala/is/hail/annotations/aggregators/RegionValuePearsonCorrelationAggregator.scala, hail/src/main/scala/is/hail/expr/ir/AggOp.scala, hail/src/main/scala/is/hail/expr/ir/Interpret.scala, hail/src/main/scala/is/hail/methods/Aggregators.scala, hail/src/main/scala/is/hail/stats/PearsonCorrelationCombiner.scala, hail/src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala
PRs to follow will add to Python, and add array correlation function.
=> Add Pearson correlation aggregator to Scala

hail/src/main/scala/is/hail/asm4s/Code.scala
I tested this works on a debugging branch.
=> Add println to Code

hail/python/hail/expr/expressions/__init__.py, hail/python/hail/expr/expressions/typed_expressions.py, hail/python/hail/expr/functions.py, hail/python/test/hail/test_ir.py, hail/src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala, hail/src/main/scala/is/hail/expr/ir/functions/DictFunctions.scala, hail/src/main/scala/is/hail/expr/ir/functions/SetFunctions.scala, hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala, hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala, hail/src/test/scala/is/hail/expr/ir/ArrayFunctionsSuite.scala, hail/src/test/scala/is/hail/expr/ir/DictFunctionsSuite.scala, hail/src/test/scala/is/hail/expr/ir/FunctionSuite.scala, hail/src/test/scala/is/hail/expr/ir/IRSuite.scala, hail/src/test/scala/is/hail/expr/ir/SetFunctionsSuite.scala, hail/src/test/scala/is/hail/expr/ir/StringFunctionsSuite.scala, hail/src/test/scala/is/hail/expr/ir/StringLengthSuite.scala
improves optimization and opportunities for deforestation
=> prefer IR over ApplyIR for simple functions

batch/hail-ci-build.sh
=> Shutdown batch after testing

ci/ci/ci.py, ci/deploy-index.html, ci/index.html, ci/pr-build-script, hail/hail-ci-build.sh
This was driving me fucking crazy. Change the logs to end in '.log', set the content-type on .log artifacts to text/plain.
=> set content-type: text/plain on uploaded logs

ci/setup-endpoints.sh, ci/test-locally.sh, hail/install-gcs-connector.sh
`-i` includes the response headers on stdout
`-v` includes a lot of information (include request headers, which sometimes include sensitive information).
=> better curl output

hail/python/hail/methods/__init__.py, hail/python/hail/methods/statgen.py, hail/python/test/hail/methods/test_statgen.py, hail/src/main/scala/is/hail/methods/LogisticRegression.scala, hail/src/main/scala/is/hail/methods/PoissonRegression.scala, hail/src/main/scala/is/hail/stats/LogisticRegressionModel.scala, hail/src/main/scala/is/hail/stats/PoissonRegressionModel.scala, hail/src/test/resources/regressionPoisson.pheno, hail/src/test/scala/is/hail/stats/LogisticRegressionModelSuite.scala
to solve Duncan's problems in time for conference, still needs docs and tests but I think the math is right. PRing now so @danking and I can hack on it tomorrow
=> poisson regression

README.md
=> Delete ASHG info from github readme

hail/python/hail/pylintrc, hail/python/hail/setup.cfg
cc: @tpoterba
pylint and flake8 will automatically look for these files in these places when run on python files in `hail/python/hail`.
=> checker configs

hail/www/landing.md, hail/www/navbar.html
I'm update the readme separately. And we can discuss updating the links later.
=> update 0.1/0.2 in landing and navbar

batch/deployment.yaml.in, ci/deployment.yaml.in, scorecard/deployment.yaml.in, site/site-deployment.yaml.in, upload/deployment.yaml.in
cc: @cseed 
This is what you were observing.
=> fix label, prevent incessant redeploys

python/hail/docs/_templates/layout.html
navbar was in two places, this fixes the second one.  think this might be the last one.
=> fix docs navbar

hail-ci-deploy.sh
Don't attempt to connect to old ci/web server.
=> [0.1] fix deploy

batch/deployment.yaml.in, ci/deployment.yaml.in, scorecard/deployment.yaml.in, site/site-deployment.yaml.in, upload/deployment.yaml.in
Otherwise all numeric SHAs will be treated as numbers which breaks k8s input validation
=> Quote SHAs in yaml files

hail/create_config_file.py
not sure if this fixes deploy
cc: @cseed
=> I think this fixes deploy

hail/www/landing.md
=> add GWASbot link

README.md
and not just recapitulate the homepage. @tpoterba I'm not sure if this is exactly what you had in mind, but I think it's definitely an improvement.
=> rewrite README to focus more on software dev

hail/python/hail/methods/statgen.py, hail/python/test/hail/methods/test_statgen.py, hail/src/main/scala/is/hail/methods/LinearRegression.scala
Supports UKBB / multiple GWAS activities.
To do:
- Add an option for extra table fields on all regression methods
- Add How-To for chained linear regression, extra table fields
=> Added chained linear regression

hail/hail-ci-build.sh
and reduce max-idle (althought it seems that's being ignored?)
Just trying to reduce testing costs.
=> use a smaller test cluster

hail/src/main/scala/is/hail/expr/types/TBaseStruct.scala, hail/src/main/scala/is/hail/expr/types/TContainer.scala
Clean up unused functions related to RV construction
found on TBaseStruct and TContainer
=> PTypes 19: GC

hail/python/hail-apiserver/hail-apiserver.py, hail/python/hail/backend/__init__.py, hail/python/hail/backend/backend.py, hail/python/hail/context.py
Builds on @jigold's PR: https://github.com/hail-is/hail/pull/4582
First pipeline executed via API!
Start the server:
```
$ hail hail/python/hail-apiserver/hail-apiserver.py
Welcome to
__  __     <>__
/ /_/ /__  __/ /
/ __  / _ `/ / /
/_/ /_/\_,_/_/_/   version 0.2-cc8ca5cfae35
* Serving Flask app "hail-apiserver" (lazy loading)
* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```
Run a hail pipeline:
```
$ hail
>>> import hail as hl
>>> hl.init(_backend=hl.backend.ServiceBackend('localhost', 5000))
Welcome to
__  __     <>__
/ /_/ /__  __/ /
/ __  / _ `/ / /
/_/ /_/\_,_/_/_/   version 0.2-cc8ca5cfae35
>>> t = hl.Table.parallelize([hl.struct(a=1), hl.struct(a=5)])
>>> t.count()
2
>>> 
```
and on the server logs:
```
2018-10-19 22:36:18 Hail: INFO: execute: (TableCount …
```
=> HaaS lives!

hail/python/hail/methods/statgen.py, hail/python/hail/stats/linear_mixed_model.py, hail/python/test/hail/methods/test_statgen.py, hail/python/test/hail/stats/test_linear_mixed_model.py, hail/src/main/scala/is/hail/methods/LogisticRegression.scala, hail/src/main/scala/is/hail/methods/PoissonRegression.scala
- Logistic regression
- Poisson regression
- Linear mixed regression
=> Add pass through fields to other regression methods.

hail/src/main/scala/is/hail/annotations/Region.scala, hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala, hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala, hail/src/main/scala/is/hail/expr/types/TContainer.scala, hail/src/main/scala/is/hail/io/vcf/ExportVCF.scala, hail/src/main/scala/is/hail/variant/MatrixTable.scala, hail/src/test/scala/is/hail/annotations/StagedRegionValueSuite.scala
=> PTypes 24: TContainer is fully virtual!

hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala, hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala, hail/src/main/scala/is/hail/expr/types/TBaseStruct.scala, hail/src/main/scala/is/hail/io/vcf/ExportVCF.scala, hail/src/main/scala/is/hail/linalg/BlockMatrix.scala, hail/src/main/scala/is/hail/methods/IBD.scala, hail/src/main/scala/is/hail/rvd/RVDType.scala, hail/src/main/scala/is/hail/variant/MatrixTable.scala, hail/src/test/scala/is/hail/expr/ir/FunctionSuite.scala, hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala
=> PTypes 28: TStruct is fully virtual!

hail/python/hail/genetics/reference_genome.py
=> Buff up ReferenceGenome docs

hail/src/main/scala/is/hail/annotations/Region.scala, hail/src/main/scala/is/hail/annotations/UnsafeUtils.scala, hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala, hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala, hail/src/main/scala/is/hail/expr/types/ComplexType.scala, hail/src/main/scala/is/hail/expr/types/TArray.scala, hail/src/main/scala/is/hail/expr/types/TBaseStruct.scala, hail/src/main/scala/is/hail/expr/types/TBinary.scala, hail/src/main/scala/is/hail/expr/types/TBoolean.scala, hail/src/main/scala/is/hail/expr/types/TContainer.scala, hail/src/main/scala/is/hail/expr/types/TDict.scala, hail/src/main/scala/is/hail/expr/types/TFloat32.scala, hail/src/main/scala/is/hail/expr/types/TFloat64.scala, hail/src/main/scala/is/hail/expr/types/TInt32.scala, hail/src/main/scala/is/hail/expr/types/TInt64.scala, hail/src/main/scala/is/hail/expr/types/TSet.scala, hail/src/main/scala/is/hail/expr/types/TString.scala, hail/src/main/scala/is/hail/expr/types/TStruct.scala, hail/src/main/scala/is/hail/expr/types/TTuple.scala, hail/src/main/scala/is/hail/expr/types/Type.scala, hail/src/main/scala/is/hail/io/gen/ExportGen.scala, hail/src/main/scala/is/hail/io/plink/ExportPlink.scala, hail/src/main/scala/is/hail/io/vcf/ExportVCF.scala, hail/src/main/scala/is/hail/methods/IBD.scala, hail/src/test/scala/is/hail/annotations/StagedRegionValueSuite.scala
=> PTypes 29: Type is fully virtual!

hail/src/main/scala/is/hail/expr/Parser.scala, hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/Env.scala, hail/src/main/scala/is/hail/expr/ir/IR.scala, hail/src/main/scala/is/hail/expr/ir/Interpret.scala, hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala, hail/src/main/scala/is/hail/expr/types/TStruct.scala, hail/src/test/scala/is/hail/TestUtils.scala, hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
to mirror MakeArray
typecheck in evalsEqualTo
add If asserts in constructor, Emit
=> added If.unify

ci/Makefile, ci/ci/ci.py, ci/ci/prs.py, ci/ci/static/style.css, ci/ci/templates/index.html
1. Fixed Makefile for same reasons as in https://github.com/hail-is/hail/pull/4659
2. Added the most basic CI UI
=> Basic ci ui

batch/Makefile
#4659 removed this dependency.
=> [CI][Batch] Do not redeploy CI when batch is deployed

hail/python/hail/plot/plots.py, hail/src/main/scala/is/hail/stats/HistogramCombiner.scala
=> fix a few issues with hl.plot.histogram

batch/batch/api.py, batch/batch/client.py, ci/ci/environment.py
This should prevent CI from getting killed by health checks if batch fails to respond in a timely manner.
=> add batch client timeouts, set timeout in ci

hail/build.gradle
Add testCppCodegen to testAll
Remove trailing whitespace
=> Remove the dependency of testCppCodegen from test
