hail-is/hail

- notebook/notebook/notebook.py
Also, when you `GET /new`, we delete your old pod if it exists
> [notebook] redirect to a wait page after a new form submit

- notebook/notebook/notebook.py
If I can GET the URL I'm about to redirect to, then the only point of failure
remaining is the gateway nginx, and I trust that to work.
> [notebook] redirect only after service endpoint succeeds

- hail/python/hail/plot/plots.py
I broke this in the last few days.
> Fix manhattan plot downsampling

- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
> fix TableKeyByAndAggregate simp rule

- ci/index.html
So it's visible while we figure out the right solution
> Increase size of embedded artifacts HTML

- hail/src/main/scala/is/hail/sparkextras/MultiWayJoinRDD.scala
- hail/src/main/scala/is/hail/sparkextras/MultiWayZipRDD.scala
This is the underpinning for most of the multi way join work
> Add MultiWayJoinRDD

- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
Master:
> Wall time: 17min 33s
PR:
> Wall time: 4min 46s
> Load VCFs faster

- batch/hail-ci-deploy.sh
> fix batch deploy script

- hail-ci-build-image
- hail/build.gradle
- hail/hail-ci-build.sh
- hail/python/hail/dev-environment-py3.7.yml
- hail/python/hail/dev-environment.yml
Makes it easy to see failing tests, stack traces, and timings.
> Add pytest HTML report to artifacts

- notebook/hail-ci-deploy.sh
This will hopefully fix deploy.
> auth docker in notebook deploy script

- notebook/Dockerfile
> fixed notebook Docker build

- image-fetcher/Makefile
> Deploy image fetcher in default

- hail/python/hail/expr/expressions/typed_expressions.py
- hail/src/main/scala/is/hail/cxx/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala
- hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
This should be a big performance boost.
> Fix argument evaluation pattern of ApplyIR node.

- hail/python/hail/experimental/__init__.py
- hail/python/hail/experimental/haplotype_freq_em.py
- hail/src/main/scala/is/hail/experimental/ExperimentalFunctions.scala
- hail/src/main/scala/is/hail/experimental/package.scala
- hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
Note: Had to add Array[Double] in `RegistryFunctions.unwrapReturn`
> Added experimental function for haplotype counts with EM

- hail/python/hail/ir/table_ir.py
- hail/python/hail/table.py
- hail/python/test/hail/table/test_table.py
- hail/python/test/hail/test_ir.py
- hail/src/main/scala/is/hail/annotations/OrderedRVIterator.scala
- hail/src/main/scala/is/hail/expr/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/sparkextras/ContextRDD.scala
- hail/src/main/scala/is/hail/table/Table.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
- hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
> Add TableMultiWayZipJoin (take 2)

- hail/src/main/scala/is/hail/HailContext.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/expr/ir/TableValue.scala
- hail/src/main/scala/is/hail/expr/types/MatrixType.scala
- hail/src/main/scala/is/hail/io/RowStore.scala
- hail/src/main/scala/is/hail/io/index/IndexReader.scala
- hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala
- hail/src/main/scala/is/hail/rvd/RVD.scala
- hail/src/main/scala/is/hail/variant/MatrixTable.scala
Reopened and rebased on `ptypes-33`
> PTypes 36: ReadRows uses PType

- ci/index.html
@tpoterba any reason we don't just make this the full width of the window?
> [ci] make artifacts iframe bigger

- batch/Dockerfile
- batch/Dockerfile.test
- batch/Makefile
- batch/batch/client.py
- batch/batch/server.py
- batch/hail-ci-build.sh
- batch/test-locally.sh
Future enhancements to batch will necessitate the proper use of modules.
> [batch][dag2] Switch to Python Modules

- batch/batch/server/globals.py
- batch/batch/server/server.py
I couldn't get `_counter` to work from `server.py`. Wrapping it in a function restored the functionality.
> [batch][dag7] pull globals out to a file

- batch/batch/server/globals.py
- batch/batch/server/server.py
Also pull up the constants, reorganize them, and print POD_NAMESPACE
> [batch][dag9] move constants into globals

- batch/batch/server/globals.py
- batch/batch/server/kubernetes.py
- batch/batch/server/log.py
- batch/batch/server/server.py
Pull these out in preparation for pulling out `Job` and `Batch`.
No code changes were made here.
> [batch][dag8] pull out kubernetes and log

- Dockerfile.pr-builder
- batch/batch/__init__.py
- batch/batch/api.py
- batch/batch/client.py
- batch/batch/pylintrc
- batch/batch/server.py
- batch/environment.yml
- batch/hail-ci-build.sh
- batch/ignored-pylint-errors
- batch/setup.cfg
- hail-ci-build-image
I also added `batch/ignored-pylint-errors` which we diff the output of pylint against. If pylint differs from the `ignored-pylint-errors`, then either we fixed an ignored error or we added a new unignored error. In either case, the developer should address the issue by changing the code or the `ignored-pylint-errors` file.
> [batch][dag 4] Require pylint and flake8 success for all PRs

- hail/python/hail/ir/matrix_ir.py
- hail/python/test/hail/test_ir.py
- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/variant/MatrixTable.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
Assigned @patrick-schultz non-randomly because this should go in before the bugfix for #4833 to lessen the change
> Add IR node for MatrixDistinctByRow

- hail/hail-ci-build.sh
- hail/src/main/scala/is/hail/cxx/PackDecoder.scala
- hail/src/main/scala/is/hail/cxx/StagedContainerBuilder.scala
- hail/src/main/scala/is/hail/expr/types/physical/PContainer.scala
Fixes #4816.
I pulled this out of the other PR, since it's still failing the CI tests, so I'll remove this part there.
> fix c++ codegen, run testCppCodegen in build

- Dockerfile.pr-builder
- hail-ci-build-image
- hail/build.gradle
- hail/hail-ci-build.sh
- hail/src/main/c/Makefile
- hail/src/main/c/testutils/style.css
- hail/src/main/c/testutils/test-reporter.xslt
- hail/src/main/c/testutils/unit-tests.cpp
@patrick-schultz I've assigned this to you because I wanted your feedback, but I'm happy to spin the wheel if you'd prefer.
cc @cseed
> infrastructure for c++ unit testing

- notebook/deployment.yaml.in
- vdc/k8s-config.yaml
cc: @cseed 
Hopefully this gets notebook working again.
> maybe fix deployment

- gateway/hail.nginx.conf.in
- notebook/deployment.yaml.in
- notebook/notebook/notebook.py
- vdc/k8s-config.yaml
> Workshop fixes

- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
fixes #4754 
ಠ_ಠ
cc @konradjk @lfrancioli
> Fix If type unification in PruneDeadFields

- hail/build.sbt
Missed this when updating htsjdk earlier.
> Update htsjdk version in build.sbt

- hail/src/main/resources/include/hail/Utils.h
- hail/src/main/scala/is/hail/cxx/Emit.scala
- hail/src/main/scala/is/hail/expr/types/physical/PContainer.scala
- hail/src/test/scala/is/hail/expr/ir/InterpretSuite.scala
Another in the (ordering) series
> move native array impl (mostly) to c++

- hail/src/main/scala/is/hail/HailContext.scala
> Require exactly java 8

- scorecard/scorecard/scorecard.py
- scorecard/scorecard/templates/index.html
> add high priority issues to scorecard

- env-setup.sh
create wants the short name not the full name 🤷‍♀️
> Fix env-setup.sh

- hail/www/jobs.md
- hail/www/navbar.html
- hail/www/readme-to-index.xslt
> remove jobs information from website

- hail/python/test/hail/table/test_table.py
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
> Fix TableKeyByAndAggregate simplify bug

- hail/src/main/scala/is/hail/expr/ir/Optimize.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
> Do not print JSON literal values in the log

- hail/python/hail/ir/__init__.py
- hail/python/hail/ir/matrix_ir.py
- hail/python/hail/ir/matrix_reader.py
- hail/python/hail/methods/impex.py
- hail/python/hail/utils/misc.py
- hail/python/test/hail/test_ir.py
- hail/src/main/scala/is/hail/HailContext.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala
- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
- hail/src/test/scala/is/hail/TestUtils.scala
- hail/src/test/scala/is/hail/annotations/AnnotationsSuite.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/MatrixIRSuite.scala
- hail/src/test/scala/is/hail/io/ExportVCFSuite.scala
- hail/src/test/scala/is/hail/io/ImportVCFSuite.scala
- hail/src/test/scala/is/hail/methods/IBDSuite.scala
- hail/src/test/scala/is/hail/methods/LocalLDPruneSuite.scala
- hail/src/test/scala/is/hail/methods/PedigreeSuite.scala
- hail/src/test/scala/is/hail/methods/TableSuite.scala
- hail/src/test/scala/is/hail/utils/RichRDDSuite.scala
- hail/src/test/scala/is/hail/variant/vsm/VSMSuite.scala
- used by read_matrix_table, range_matrix_table, import_vcf, import_bgen
> Refactor Python MatrixRead

- hail/www/404.xslt
- hail/www/template.xslt
> revert xslt changes

- hail/python/hail/methods/misc.py
- hail/python/test/hail/methods/test_misc.py
> Fix maximal independent set bug

- hail/www/404.xslt
- hail/www/template.xslt
I misunderstood what `//` and `/` meant. `//` is used for things like `//google.com/index.html` which resolves to `https://google.com/index.html` when served by `https` and `http://google.com/index.html` when served by `http`. `/` is the same but for local URLs. For example, `/index.html` resolves to `https://hail.is/index.html` on our website but `http://localhost:8080/index.html` if I'm testing locally.
> [hail][site] fix 404 page

- notebook/Makefile
- notebook/images/ccg-workshop/Dockerfile
- notebook/images/ccg-workshop/ccg_workshop_2018_python3.ipynb
I also reduced the layers and size of the notebook a bit. It's still ~8GB. I added `time` to the make command for curiosity's sake.
> [notebook] add a ipynb for cog

- hail/python/hail/matrixtable.py
- hail/python/hail/methods/impex.py
- hail/python/hail/methods/statgen.py
- hail/python/test/hail/methods/test_impex.py
- hail/python/test/hail/methods/test_statgen.py
> Fix MatrixTable._select_all to address atomicity constraint

- ci/ci/ci.py
- ci/ci/templates/index.html
- ci/ci/templates/job-log.html
> Ci deploy ui

- hail/get-deployed-sha.sh
Should actually figure out how to unify all these variables in one file since they're at least used in both hail-ci-deploy.sh and get-deployed-sha.sh right now
> [hail] fix get-deployed-sha.sh

- hail/src/main/scala/is/hail/expr/types/physical/PType.scala
When we remove requiredness from virtual types, requiredness will
live on in both encoded types and physical types. This will require
us to use these types to generate the canonical physical type without
extra missing bits. We will need to use this pattern in, for instance,
TableKeyBy, which may need to encode/decode to shuffle, and will
produce a constructable physical type to decode from.
> PTypes 50: Add PType.canonical constructors

- hail/python/hail/context.py
> Add short doc note to hl.init

- hail/src/main/scala/is/hail/expr/ir/IRBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
> Lower MatrixColsTable

- hail/python/hail/ir/ir.py
- hail/python/hail/table.py
- hail/python/test/hail/test_ir.py
- hail/src/main/scala/is/hail/expr/ir/Children.scala
- hail/src/main/scala/is/hail/expr/ir/Compilable.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/Infer.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/LiftLiterals.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
- hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
> Add TableCollect IR node

- Dockerfile.pr-builder
- hail-ci-build-image
- hail/python/hail/dev-environment-py3.7.yml
- hail/python/hail/dev-environment.yml
- hail/python/hail/docs/Makefile
- hail/python/hail/docs/genetics/index.rst
Also had to switch PLINK hosting.
> Fix Sphinx builds with Sphinx versions != 1.7.5

- batch/batch/server/server.py
404 NOT FOUND is inappropriate in this situation.
> [batch] validation errors should be 400 BAD REQUEST

- notebook/images/ccg-workshop/runAnalysis.1.8.sh
@jbloom22 I suspect this is why the website isn't deployed.
We were missing this file so the ccg-workshop image couldn't be built.
> fix ccg workshop build & deploy thus fixing deployment

- hail/src/main/resources/include/hail/Ordering.h
- hail/src/main/scala/is/hail/cxx/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/ComparisonOp.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/Infer.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/main/scala/is/hail/expr/ir/add-ir-checklist.txt
- hail/src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala
i.e. `ApplyComparisonOp(Compare(), ir1, ir2)`.
> add 'Compare' ComparisonOp to IR

- hail/src/main/scala/is/hail/compatibility/UnpartitionedRVDSpec.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/rvd/RVD.scala
- hail/src/main/scala/is/hail/rvd/RVDType.scala
Does not depend on PTypes 53, despite the name.
> PTypes 54: PType inference for TableKeyBy

- hail/python/hail/docs/tutorials/01-genome-wide-association-study.ipynb
> fix rendering of tutorial docs

- hail/python/hail/methods/statgen.py
see comment: 
https://github.com/hail-is/hail/issues/3706#issuecomment-395118375
> Simplify ld_prune tie breaker

- hail/python/hail/ir/ir.py
- hail/python/hail/matrixtable.py
- hail/python/hail/table.py
- hail/python/test/hail/test_ir.py
- hail/src/main/scala/is/hail/expr/ir/Children.scala
- hail/src/main/scala/is/hail/expr/ir/Compilable.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/InferPType.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/LiftLiterals.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/main/scala/is/hail/expr/ir/functions/RelationalFunctions.scala
- hail/src/main/scala/is/hail/methods/ForceCount.scala
- hail/src/main/scala/is/hail/table/Table.scala
- hail/src/main/scala/is/hail/variant/MatrixTable.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
Use for ForceCountTable and ForceCountMatrixTable  
stacked on #5038
> Add nodes for relational => value functions

- scorecard/scorecard/scorecard.py
Added myself to the scorecard random user list. resolves #5087
> Added daniel-goldstein to users

- hail/python/hail/docs/getting_started_developing.rst
Fixed outdated info in the dev environment setup
> Updated dev setup docs

- hail/python/hail/backend/__init__.py
- hail/python/hail/backend/backend.py
- hail/src/main/scala/is/hail/backend/Binding.scala
- hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
- hail/src/main/scala/is/hail/backend/local/LowerTableIR.scala
- hail/src/main/scala/is/hail/backend/spark/LowerTableIR.scala
- hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/Optimize.scala
More like a pile of bones, maybe not as much here as you'd hoped for.
> added Spark, Local backends in Scala, currently unused

- hail/python/hail/experimental/vcf_combiner.py
- hail/python/test/hail/methods/test_impex.py
- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
Also fixup the combiner to work properly with the new keys.
> Key by ['locus', 'alleles'] in import_vcfs

- hail/python/hail/matrixtable.py
- hail/python/test/hail/matrixtable/test_matrix_table.py
Cotton broke this when he converted make_table to Python
> Fix make_table separator issue

- batch/batch/server/server.py
- batch/test/test_dag.py
> [batch] also return parent ids in get

- hail/python/hail/methods/impex.py
- hail/src/main/scala/is/hail/table/Table.scala
Table is going away and the data is small (local) anyway
> make importFam return JSON instead of Table

- batch/batch/client.py
- batch/batch/schemas.py
- batch/batch/server/server.py
- batch/test/diamond_dag.yml
- batch/test/test_dag.py
Ready for review. Defines a file format for describing batch job dags. See for example https://github.com/hail-is/hail/pull/5031/files#diff-c477bbaab53cc034eccad65bae5c58e9 which defines a diamond shaped DAG.
> [batch] DAG file format

- hail/python/hail/backend/backend.py
- hail/python/hail/matrixtable.py
- hail/python/hail/table.py
Default persist (used by ServiceBackend) currently does nothing.  As we've discussed, there's more work to flesh out a cache/persist strategy in the new setting.
> route (un)persist through Backend

- hail/python/hail/ir/__init__.py
- hail/python/hail/ir/table_ir.py
- hail/python/hail/ir/table_reader.py
- hail/python/hail/methods/impex.py
- hail/python/test/hail/test_ir.py
- hail/src/main/scala/is/hail/HailContext.scala
- hail/src/main/scala/is/hail/cxx/TableEmit.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
- hail/src/main/scala/is/hail/utils/TextTableReader.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
- hail/src/test/scala/is/hail/methods/IBDSuite.scala
- hail/src/test/scala/is/hail/utils/TextTableSuite.scala
convert TableImport into TextTableReader
> parameterize TableRead with a TableReader

- hail/python/hail/methods/statgen.py
https://hail.is/docs/0.2/methods/stats.html#hail.methods.logistic_regression_rows
> Fix doc syntax

- hail/src/main/scala/is/hail/expr/ir/IRBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
> Lower MatrixExplodeCols

- hail/python/hail/methods/impex.py
- hail/src/main/scala/is/hail/HailContext.scala
> don't use _convert_to_j in call to indexBgen

- hail/python/hail/ir/ir.py
- hail/python/hail/linalg/blockmatrix.py
- hail/python/hail/matrixtable.py
- hail/src/main/scala/is/hail/expr/ir/functions/MatrixWriteBlockMatrix.scala
- hail/src/main/scala/is/hail/expr/ir/functions/RelationalFunctions.scala
- hail/src/main/scala/is/hail/variant/MatrixTable.scala
I made this a relational function, but it could also be a void-valued IR.  I'm not sure if there is any real difference.  Thoughts, @tpoterba?
>  add write block matrix relational function

- hail/src/main/scala/is/hail/rvd/RVD.scala
> Fix TableRepartition when unkeyed

- hail/python/hail/table.py
- hail/python/test/hail/table/test_table.py
> Fix show for empty tables

- hail/python/hail/expr/matrix_type.py
- hail/python/hail/ir/matrix_ir.py
- hail/python/hail/matrixtable.py
- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/variant/MatrixTable.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/io/ImportMatrixSuite.scala
> added MatrixRename IR

- hail/python/hail/ir/table_ir.py
- hail/python/hail/methods/statgen.py
- hail/src/main/scala/is/hail/expr/ir/TableValue.scala
- hail/src/main/scala/is/hail/expr/ir/functions/RelationalFunctions.scala
- hail/src/main/scala/is/hail/methods/PoissonRegression.scala
- hail/src/main/scala/is/hail/methods/Skat.scala
- hail/src/main/scala/is/hail/stats/RegressionUtils.scala
Should be analogous to the logistic regression change
> convert PoissonRegression, Skat to relational functions

- batch/batch/client.py
- batch/batch/server/server.py
- batch/test/test_batch.py
For my pipeline code, I need a way to iterate through the list of jobs submitted and collect their error codes to determine if a pipeline failed and if so print out the log.
> add jobs to Batch in client.py

- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/IRBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
Please don't approve yet.
Some initial experiments are showing that the performance here is pretty terrible - probably related to more interpreter usage.
> Lower MatrixAnnotateColsTable

- hail/python/hail/matrixtable.py
- hail/python/test/hail/matrixtable/test_matrix_table.py
> Fix make_table to preserve row fields

- hail/python/hail/table.py
> Fix show() to respect 'types' argument

- notebook/Dockerfile
FYI @tpoterba.
See https://github.com/pypa/pip/issues/6197 and proposed fix PR https://github.com/pypa/pip/pull/6219.
This resolves the deploy issue.
> [notebook] workaround for pip error

- hail/python/hail/matrixtable.py
- hail/python/test/hail/matrixtable/test_matrix_table.py
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
> add check to union_rows

- hail/python/hail/matrixtable.py
They were all broken.
Fixes #5235
> Fix error messages in union_cols

- hail/python/hail/expr/expressions/typed_expressions.py
> Add more docs to CallExpression methods

- hail/python/hail/matrixtable.py
cc: @tpoterba 
As my sailing instructor says: "The rules of sailing are: do it right and look good doing it".
Trailing spaces burns my eyes (via an editor setting).
> [hail] remove trailing whitespace

- hail/python/hail/table.py
- hail/python/test/hail/table/test_table.py
> Fix truncation in Table.show

- hail/python/hail/context.py
- hail/python/test/hail/test_no_context.py
> make get_reference ensure hail context is initialized

- hail/python/hail/ir/ir.py
> Fix TableExport writing a types file called "None"

- hail/python/hail/ir/table_ir.py
- hail/python/test/hail/table/test_table.py
> Fix order_by parsing

- hail/python/hail/experimental/vcf_combiner.py
This performs the operations described in the `NOTE` at the end of `vcf_combiner.py`
The only thing that I feel may be confusing is that we recompute the `DP` info fields as the sum of the `DP` entry fields. We do this as `densify` (currently a placeholder) may populate a previously missing entry.
> Add summarize function to combiner

- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/utils/TextTableReader.scala
- hail/src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala
> [hail][bad error message] Improve errors when trying to import dirs

- hail/python/hail/table.py
> Fix Table.join key rename warning

- notebook/.gitignore
see the Makefile. We generate a file with a plural name. I also eliminated a blank line.
> [notebook] fix gitignore

- hail/python/cluster-tests/cluster-vep-check.py
This should fix the fact that every PR is failing.
> Point vep check to new config and reference files

- hail/python/hail/experimental/vcf_combiner.py
Update summarize in response to Laura's feedback. Also add a helper method to compute the 'real' GT from Local GT and Local Alleles.
> Combiner summarize 2

- hail/python/hail/matrixtable.py
- hail/python/hail/table.py
Improve verbiage for the notes in all filter docs.
> Fix the filter_cols and filter_entries docs

- hail/src/main/scala/is/hail/cxx/TableEmit.scala
- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/RefEquality.scala
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/variant/MatrixTable.scala
Add TableZipUnchecked IR node (used to zip rows and entries).
> Lower MatrixNativeReader into manipulations of TableReads

- hail/python/hail/docs/guides/genetics.rst
- hail/python/hail/expr/functions.py
@jigold - the wheel picked you, it must have known...
> Adding how to guide for liftover

- apiserver/apiserver/apiserver.py
- hail/python/hail/backend/backend.py
- hail/python/hail/genetics/reference_genome.py
- hail/python/test/hail/genetics/test_reference_genome.py
> Fix add_sequence

- hail/python/hail/experimental/vcf_combiner.py
> Rename fields to indicate locality

- hail/python/hail/expr/expressions/typed_expressions.py
Still can't write the thing we want.  :-(  Loop gets closer, but it needs to play nicely with array deforestation which isn't trivial.  ArrayFold with explicit recur like loop might be the thing.
> rewrote CollectionExpression.find in terms of ArrayFold.

- hail/python/hail/experimental/vcf_combiner.py
We were already doing it for combining.
> Use elementwise sum for initial SB aggregation

- scorecard/scorecard/scorecard.py
- scorecard/scorecard/templates/index.html
Add components and list of reviewers for those components to the index.html page.  It looks like this:
The order of the names is random each time the page is loaded.  Idea is to take the first name for the component you're reviewing when creating PRs.
@danking I removed you from Hail front-end.  Now everyone appears on 2-3 components.
@akotlar FYI, I ripped out the JSON endpoints since I'm happy with the Flask implementation.
> Scorecard components and reviewers

- auth-gateway/package-lock.json
- auth-gateway/package.json
The lock file is auto-generated. There isn't any need to review its contents; it matches the dependency tree for the packages/versions specified in package.json.
Committing it allows all future users to follow the same dependency graph during installation.
Ref: https://docs.npmjs.com/files/package-lock.json , https://stackoverflow.com/questions/44297803/package-lock-json-role
- Counter-argument: https://github.com/npm/npm/issues/20603
We can accept this PR first, to make the dependent PR small.
> Auth gateway: simply adds project deps

- projects.txt
I realized after I approved that we forgot to add this new project to projects.txt
> add auth-gateway to projects.txt

- hail/python/hail/genetics/reference_genome.py
This seems not confusing and helpful.
> [hail] make add_sequence more convenient

- hail/python/hail/expr/__init__.py
- hail/python/hail/expr/functions.py
- hail/python/hail/ir/ir.py
- hail/python/test/hail/expr/test_expr.py
- hail/python/test/hail/test_ir.py
- hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/ArraySorter.scala
- hail/src/main/scala/is/hail/expr/ir/Binds.scala
- hail/src/main/scala/is/hail/expr/ir/Children.scala
- hail/src/main/scala/is/hail/expr/ir/ComparisonOp.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/InferPType.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
- hail/src/main/scala/is/hail/expr/ir/SpecializedArrayBuilders.scala
- hail/src/main/scala/is/hail/expr/ir/Subst.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala
- hail/src/test/scala/is/hail/expr/ir/ArrayFunctionsSuite.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
the former `ascending` and `onKey` parameters are just rewrites of the comparison expression.
> refactor ArraySort IR to take comparison expression

- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/test/scala/is/hail/expr/ir/MatrixIRSuite.scala
> Lower matrix range reader

- batch/batch/api.py
- batch/batch/client.py
- batch/batch/server/server.py
- batch/test/test_batch.py
First attempt to modify Batch :)
> [batch] add scratch_bucket parameter

- batch/batch/api.py
- batch/batch/client.py
- batch/batch/server/server.py
- batch/test/test_batch.py
Be clear we need a scratch folder not a scratch bucket.
> [batch] scratch folder

- hail/python/hail/experimental/vcf_combiner.py
Obtaining the allele for `LGT[i]` for all `i` is more straightforward:
```
allele = alleles[LA[LGT[i]]]
```
Before we needed to do a `LGT[i] == 0` check.
> Include index of REF in Local Alleles

- hail/python/hail/backend/backend.py
- hail/python/hail/matrixtable.py
- hail/python/hail/methods/impex.py
- hail/python/hail/methods/qc.py
- hail/python/hail/methods/statgen.py
- hail/python/test/hail/methods/test_impex.py
- hail/src/main/scala/is/hail/HailContext.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala
- hail/src/main/scala/is/hail/expr/types/MatrixType.scala
- hail/src/main/scala/is/hail/io/LoadMatrix.scala
- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
- hail/src/main/scala/is/hail/methods/CalculateConcordance.scala
- hail/src/main/scala/is/hail/methods/IBD.scala
- hail/src/test/scala/is/hail/io/ImportMatrixSuite.scala
- hail/src/test/scala/is/hail/methods/IBDSuite.scala
Stacked on: https://github.com/hail-is/hail/pull/5382
>  eliminate uses of Scala MatrixTable from Python

- hail/src/main/scala/is/hail/sparkextras/ContextRDD.scala
This makes ContextRDD.aggregate deterministic (aggregators are folded in partition-order).
treeAggregate and reduce (at least) also need to be fixed.
This shouldn't be much slower, but will increase memory usage on the master.  Better than a wrong answer.  Longer-term, we should aggregate commutative aggregators on the fly, and merge adjacent non-commutative aggregators on the fly instead of collecting all of them.
> Make ContextRDD.aggregate deterministic.

- hail/python/hail/experimental/vcf_combiner.py
This joins the output of the combiner with the output some of of GATK's
post joint-calling tools. It is intended that this function be run with some
combiner output, the rows of the combiner output run through `summarize`, 
and GATKs output from a sites only VCF produced from that `summarize` output.
It also adds a little documentation.
> Add reannotate function to combiner

- gateway/hail.nginx.conf.in
- letsencrypt/domains.txt
- notebook2/.gitignore
- notebook2/Dockerfile
- notebook2/Makefile
- notebook2/SECRETS.md
- notebook2/deployment.yaml.in
- notebook2/environment.yml
- notebook2/get-deployed-sha.sh
- notebook2/hail-ci-deploy.sh
- notebook2/images/hail/Dockerfile
- notebook2/images/hail/resources/Hail-Workshop-Notebook.ipynb
- notebook2/notebook/notebook.py
- notebook2/notebook/static/centering.css
- notebook2/notebook/static/style.css
- notebook2/notebook/templates/admin-login.html
- notebook2/notebook/templates/index.html
- notebook2/notebook/templates/wait.html
- notebook2/notebook/templates/workers.html
- notebook2/worker/Dockerfile
- notebook2/worker/resources/Hail-Workshop-Notebook.ipynb
- projects.txt
Only changes are as we discussed: rename/add notebook2 labels where appropriate. Tested in cluster, appears to work although the deployment is stuck in Desired == 1, so I may have missed one of the notebook labels, or maybe `make deploy` not enough (I find the makefile a bit confusing still). Describe shows `ReplicaFailure   True    FailedCreate`, will figure out tomorrow
cc @cseed
> notebook2 as a notebook copy

- hail/python/hail/expr/aggregators/aggregators.py
- hail/python/test/hail/expr/test_expr.py
> Fix _prev_nonnull to work with primitive types

- hail/python/hail/experimental/vcf_combiner.py
This passes the requireness issue upstream to the consumer of the
library. Add docs to explain this.
> [combiner] remove array copy in transform one

- hail/src/main/scala/is/hail/expr/ir/Optimize.scala
> Fix IR size printed in log statement after optimize

- hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala
- hail/src/main/scala/is/hail/expr/ir/TableValue.scala
- hail/src/main/scala/is/hail/utils/package.scala
> Add README.txt to written native Table/MatrixTable files

- hail/python/hail/expr/functions.py
- hail/python/hail/methods/impex.py
- hail/python/hail/methods/statgen.py
> [docs] Fix examples of usages with RG defaults to explicitly pass RG

- hail/python/hail/ir/blockmatrix_ir.py
- hail/python/hail/linalg/blockmatrix.py
- hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
Implemented BlockMatrix.random, which creates a matrix of random entries, as the broadcast of a seed value into a 2D matrix, and then a map with the RNG.
> Implement BlockMatrix.random in terms of the IR

- hail/python/hail/experimental/vcf_combiner.py
Also don't rekey if unnecessary.
> [combiner] check keys in input tables to reannotate

- hail/python/hail/ir/table_reader.py
- hail/python/hail/methods/impex.py
- hail/python/test/hail/methods/test_impex.py
- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
- hail/src/main/scala/is/hail/utils/TextTableReader.scala
- hail/src/main/scala/is/hail/utils/package.scala
Add 'force' argument to import_table
> [bugfix] Add globbing support back to hl.import_table

- hail/python/hail/experimental/vcf_combiner.py
Before we were using min_rep to create unique alleles for combining, and
then padding to create the appropriate REF/ALT after combining. Now we
do this padding after joining the combiner inputs.
> [combiner] pad alleles during combine instead of after

- hail/python/hail/experimental/__init__.py
- hail/python/hail/experimental/function.py
- hail/python/hail/ir/base_ir.py
- hail/python/test/hail/experimental/test_experimental.py
- hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
@chrisvittal your functions, sir:
```
f = hl.experimental.define_function(
lambda a, b: (a + 7) * b, hl.tint32, hl.tint32)
self.assertEqual(hl.eval(f(1, 3)), 24)
```
> prototype experimental.define_function

- hail/src/main/scala/is/hail/backend/spark/LowerTableIR.scala
- hail/src/main/scala/is/hail/cxx/Compile.scala
Does not/should not change current behavior; I'm just refactoring some code in anticipation of future changes needing the individual pieces instead of the whole.
> [c++] tidy up Compile, break out and generalize the part that makes the function

- pipeline/pipeline/backend.py
- pipeline/pipeline/pipeline.py
- pipeline/pipeline/resource.py
- pipeline/pipeline/task.py
- pipeline/test/test_pipeline.py
> [pipeline] Added support for file extensions

- pipeline/Makefile
- pipeline/pipeline/backend.py
- pipeline/pipeline/resource.py
- pipeline/test/test_pipeline.py
Also...
- fix inheriting from str so `join` will work
- fix Makefile for checking whether Batch files have been updated
- fix copying same input multiple times in LocalBackend
> [pipeline] Change directory structure

- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/io/RowStore.scala
Should hopefully fix our memory issues.
> [hail] Use context's region in writeRowsSplit and TableMultiWayZipJoin

- hail/python/test/hail/expr/test_expr.py
- hail/src/main/scala/is/hail/utils/MissingFloatArrayBuilder.scala
> [bugfix] Fix collect for float32 values

- hail/python/scripts/run_combiner.py
This is intended to be used with spark cluster job submission like `cluster submit`.
Developing this has gone on long enough without version control.
> [combiner] add python script for driving combiner

- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/io/bgen/BgenRDDPartitions.scala
- hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala
- hail/src/main/scala/is/hail/io/gen/LoadGen.scala
- hail/src/main/scala/is/hail/io/plink/LoadPlink.scala
- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
- hail/src/main/scala/is/hail/variant/MatrixTable.scala
- hail/src/test/scala/is/hail/TestUtils.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
- hail/src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala
> Lower other matrix reads

- apiserver/apiserver/apiserver.py
- hail/python/hail/backend/backend.py
- hail/python/hail/expr/functions.py
- hail/src/main/scala/is/hail/expr/ir/CompileAndEvaluate.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/InterpretNonCompilable.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
To be followed by a PR cleaning up some dead scala code (hooray!)
> Run compiler instead of interpreter in Backend.execute()

- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
> warn when .vcf missing

- hail/python/hail/experimental/vcf_combiner.py
We're going to be running the joint caller on 100,000+ samples. Assuming
we batch merges in groups of 100 samples, we would build the post join
IR around 1000 times. Two orders of magnitude less than transform one,
but still probably worth it.
> [combiner] use functions in combiner methods

- hail/python/hail/methods/family_methods.py
- hail/python/test/hail/methods/test_family_methods.py
It was totally broken in the default case.
> [bugfix] Fix trio matrix

- notebook2/notebook/notebook.py
- notebook2/notebook/static/styles/pages/login.scss
- notebook2/notebook/templates/login.html
- notebook2/notebook/templates/notebook-form.html
Tim, like we discussed, thanks for the suggestion. No login for workshop users, we skip auth0 altogether. Not quite as safe, but probably not a big deal provided https, a long-enough password. 
I also removed the image picker, because it's I think more implementation detail than workshop users need (and it's not particularly styled)
and uses ibg2019
cc @danking @cseed
> [notebook2] don't make workshop users log in 

- hail/python/hail/docs/getting_started.rst
- hail/python/hail/docs/getting_started_developing.rst
cc: @catoverdrive 
I think this is a bit easier to follow.
> [hail] improve getting started

- batch/test/test_dag.py
Trying to catch up to @tpoterba in PR count.
> [batch] remove unused variable in test

- hail/python/hail/plot/plots.py
> [feature] add 'log' parameter to hl.plot.histogram

- hail/python/hail/expr/aggregators/aggregators.py
> fix in hl.agg.hist docs

- apiserver/apiserver/apiserver.py
- hail/python/hail/backend/backend.py
- hail/src/main/scala/is/hail/backend/spark/LowerTableIR.scala
- hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
- hail/src/main/scala/is/hail/expr/ir/CompileAndEvaluate.scala
- hail/src/test/scala/is/hail/TestUtils.scala
This is independent of #5469, but I don't know if we wanted to wait on that to land before this happens.
> [c++] use SparkBackend if cpp flag is turned on

- scorecard/scorecard/scorecard.py
> add cloudtools to scorecard, start with tpoterba, danking

- hail/python/hail/expr/functions.py
- hail/python/test/hail/expr/test_expr.py
cc: @tpoterba 
This seems like the correct semantics for these expressions.
> [hail] make coalesce and or_else evaluate each argument once

- hail/python/cluster-tests/test-skat.py
- hail/src/main/scala/is/hail/methods/Skat.scala
> fix native call in Skat

- hail/src/main/resources/include/hail/SparkUtils.h
- hail/src/main/scala/is/hail/backend/spark/LowerTableIR.scala
- hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
- hail/src/main/scala/is/hail/cxx/Compile.scala
- hail/src/main/scala/is/hail/cxx/Emit.scala
- hail/src/main/scala/is/hail/cxx/SparkUtils.scala
- hail/src/main/scala/is/hail/cxx/package.scala
> [c++] implement CollectDistributedArray computation from c++, use in lowering.

- ci/Makefile
- loadconda
Also add my extremely specific conda installation location to `loadconda`
> [ci] fixup some makefile issues

- apiserver/environment.yml
> [apiserver] fix jupyter incompatible implicit tornado>=6 dep

- hail/python/hail/methods/impex.py
- hail/src/main/scala/is/hail/io/ElasticsearchConnector.scala
> Fix export_elasticsearch

- apiserver/apiserver/apiserver.py
- hail/src/main/scala/is/hail/HailContext.scala
- hail/src/main/scala/is/hail/expr/AnnotationImpex.scala
- hail/src/main/scala/is/hail/expr/HailRep.scala
- hail/src/main/scala/is/hail/expr/types/MatrixType.scala
- hail/src/main/scala/is/hail/expr/types/physical/PLocus.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TLocus.scala
- hail/src/main/scala/is/hail/io/bgen/BgenRDD.scala
- hail/src/main/scala/is/hail/io/bgen/BgenRDDPartitions.scala
- hail/src/main/scala/is/hail/io/bgen/IndexBgen.scala
- hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala
- hail/src/main/scala/is/hail/io/gen/LoadGen.scala
- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
- hail/src/main/scala/is/hail/rvd/RVDPartitioner.scala
- hail/src/main/scala/is/hail/variant/Locus.scala
- hail/src/main/scala/is/hail/variant/ReferenceGenome.scala
- hail/src/test/scala/is/hail/SparkSuite.scala
- hail/src/test/scala/is/hail/TestUtils.scala
- hail/src/test/scala/is/hail/expr/ir/ArrayDeforestationSuite.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/LocusFunctionsSuite.scala
- hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala
- hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
- hail/src/test/scala/is/hail/io/ImportMatrixSuite.scala
- hail/src/test/scala/is/hail/variant/LocusIntervalSuite.scala
- hail/src/test/scala/is/hail/variant/ReferenceGenomeSuite.scala
Stacked on: https://github.com/hail-is/hail/pull/5509
Broadcast once and reuse the same broadcast where.  Never serialize (except via broadcast).  Same pattern as RVDPartitioner and Hadoop configuration.
> broadcast ReferenceGenome

- hail/python/hail/experimental/__init__.py
- hail/python/hail/experimental/ldscsim.py
ldscsim is a simulation framework for testing LD score regression
> add ldscsim

- project-changed.py
I need transitive dependencies for the forthcoming hailjwt library.
fyi @akotlar
> transitive dependencies

- hail/src/main/scala/is/hail/expr/AnnotationImpex.scala
> [bugfix] use map for decoding intervals from json

- hail/src/main/resources/include/hail/SparkUtils.h
- hail/src/main/scala/is/hail/backend/spark/LowerTableIR.scala
- hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
- hail/src/main/scala/is/hail/cxx/Compile.scala
- hail/src/main/scala/is/hail/cxx/Emit.scala
- hail/src/main/scala/is/hail/cxx/SparkUtils.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
Maybe not the ideal implementation, but this currently just threads through all of the literals we need and passes them into the function as an encoded Array[Byte].
>  [c++] implement Str and Literal in Emit

- hail/python/hail/matrixtable.py
- hail/python/hail/table.py
> adding _read_if_exists to checkpoint

- hail/python/hail/docs/tutorials-landing.rst
- hail/python/hail/docs/tutorials/05-tables.ipynb
- hail/python/hail/docs/tutorials/06-aggregation.ipynb
- hail/python/hail/docs/tutorials/07-filter-annotate.ipynb
- hail/python/hail/docs/tutorials/08-joins.ipynb
> Revert "disable tutorials that depend on movie lens"

- hail/python/cluster-tests/cluster-sanity-check.py
- hail/src/main/scala/is/hail/io/index/IndexReader.scala
> Fix ImportBGEN RG serialization

- hail/python/hail/linalg/blockmatrix.py
- hail/python/test/hail/linalg/test_linalg.py
> rename blockmatrix to-matrix-table field to element

- hailjwt/.gitignore
- hailjwt/Makefile
- hailjwt/hail-ci-build.sh
- hailjwt/hailjwt/__init__.py
- hailjwt/hailjwt/hailjwt.py
- hailjwt/setup.py
- hailjwt/test/test_jwt.py
- projects.yaml
cc: @akotlar @jigold @cseed 
Is everyone OK with this? You can run `python setup.py install` to install this project.
I want to use this in the cookies batch PR.
> [jwt] create jwt subproject

- hail/python/hail/experimental/ld_score_regression.py
Localizing matrix table to a table, scanning entries, then unlocalizing back to a matrix table -- previously was collecting entry fields in matrix table row annotations, scanning the row annotations, then re-annotating entries.
> rewrote block calculations in ld_score_regression

- hail/python/hail/methods/statgen.py
- hail/python/test/hail/methods/test_statgen.py
> [bugfix] Fix PCA loadings containing extra fields

- hail/python/hail/experimental/vcf_combiner.py
Now that we have moved all of the gVCF INFO field into entries, group everything but END into a struct.
> [combiner] group moved info into one field

- hail/python/hail/ir/table_reader.py
- hail/python/test/hail/table/test_table.py
> [bugfix] Fix table min_partitions

- hail/python/hail/plot/plots.py
I need to add this plot to the plotting tutorial notebook so that these are caught!
> Fixed marginal density plot in `joint_plot`

- hail/python/hail/context.py
Do you remember if there's a reason it's 1? I don't want Big Brother telling me how many blocks to use, and I doubt our users do either!
> Change min_block_size default value

- hail/python/cluster-tests/cluster-sanity-check.py
- hail/python/hail/linalg/blockmatrix.py
the uri got dropped in refactoring on PR that just went in #5686. Reverted the change and added a test to cluster sanity check.
> [fix] tofile needs local uri

- hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala
> [bugfix] Optimize optional variantsTable IR in import_bgen

- hail/src/main/scala/is/hail/cxx/Emit.scala
- hail/src/main/scala/is/hail/cxx/EmitTriplet.scala
- hail/src/main/scala/is/hail/expr/ir/Binds.scala
- hail/src/main/scala/is/hail/expr/ir/Children.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/InferPType.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
Backend IR and emit for NDArrayMap2
> [c++] NDArrayMap2 Scala IR and Emit

- hail/python/hail/methods/impex.py
- hail/python/hail/table.py
> [docs] Add warnings to export and export_vcf

- notebook2/notebook/notebook.py
- notebook2/notebook/static/styles/pages/user.scss
- notebook2/notebook/templates/header.html
- notebook2/notebook/templates/user.html
Simply adds a /user page
Assigned to dan, but he's sick, should I assign someone else?
cc @cseed, @danking @jigold
> [notebook2] add user profile with google bucket, service account

- hail/python/hail/expr/aggregators/__init__.py
- hail/python/hail/expr/aggregators/aggregators.py
- hail/python/hail/expr/functions.py
- hail/python/hail/ir/ir.py
- hail/python/hail/plot/__init__.py
- hail/python/hail/plot/plots.py
* `approx_quantiles` aggregator wrapping `approx_cdf`
* cdf and pdf plots
* Allow the histogram plot to take the result of the `approx_cdf` aggregator
* Add interactivity to the histogram and pdf plots
> add approx_cdf methods

- hail/python/test/hail/expr/test_expr.py
- hail/src/main/scala/is/hail/expr/ir/ExtractAggregators.scala
- hail/src/main/scala/is/hail/expr/ir/StagedExtractAggregators.scala
> [bugfix] Fix array_agg in annotate_rows

- image-fetcher/.gitignore
- image-fetcher/Makefile
- image-fetcher/fetch-image.sh.in
I'll follow up with another PR to pull the tagged base image instead of latest (although they should always be the same)
> fetch notebook2 image, base (latest)

- image-fetcher/Makefile
- notebook2/notebook/notebook.py
> worker_image shouldn't require auth

- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
- hail/src/main/scala/is/hail/expr/ir/TableValue.scala
> Lower MatrixWrite

- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/TableValue.scala
There is currently some code duplication with CastTableToMatrix,
which will go away when Matrix lowering is done.
> Add conversion from TableValue to MatrixValue

- hail/python/hail/__init__.py
- hail/python/hail/utils/java.py
I'm somewhat surprised it was able to run before.
> Fix backend spark_backend function to be static

- batch/batch/server/database.py
- batch/batch/server/server.py
- batch/test-locally.sh
- batch/test/test_database.py
> [batch] sql temporary tables

- batch/batch/api.py
- batch/batch/client.py
- batch/batch/server/server.py
- batch/test/test_batch.py
You can filter on complete (Job.is_complete), success (completed with exit status 0) and key/value attributes.
> [batch] added list_jobs filter parameters

- batch/batch/pylintrc
- batch/batch/server/database.py
- batch/test/test_database.py
> [batch] Expose and test SQL table operations

- batch/batch/__init__.py
- batch/batch/aioclient.py
- batch/batch/api.py
- batch/batch/client.py
- batch/test/test_aioclient.py
mostly copied from client.py, minimally tested
I changed is_complete to update the state if the job is not already complete, removed cached_status.
> add batch aioclient

- ci/Makefile
- ci/test-in-cluster.sh
- ci/test-locally.sh
- cloud-sql.mk
Just spin up a local batch instead of using a proxy. Also delete some make targets that I suspect no one uses.
Stacks on no conda https://github.com/hail-is/hail/pull/5800
> [ci] simplify local tests

- hail/python/hail/matrixtable.py
- hail/python/test/hail/matrixtable/test_matrix_table.py
- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
> [bugfix] Fix entries() with col key and no row key

- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/expr/ir/functions/RelationalFunctions.scala
- hail/src/main/scala/is/hail/expr/types/MatrixType.scala
- hail/src/main/scala/is/hail/methods/FilterIntervals.scala
- hail/src/main/scala/is/hail/methods/FilterPartitions.scala
- hail/src/main/scala/is/hail/methods/ForceCount.scala
- hail/src/main/scala/is/hail/methods/NPartitions.scala
> Lower MatrixToMatrix and MatrixToTable functions

- batch/batch/aioclient.py
- batch/batch/api.py
- batch/batch/client.py
- batch/batch/requests_helper.py
- batch/batch/server/server.py
- batch/test/test_aioclient.py
- batch/test/test_batch.py
stacked on: https://github.com/hail-is/hail/pull/5812 (which should hopefully go in soon?)
simplified aioclient (added HTTP verb helper methods)
changed cancel and close to PATCH endpoints
client side Batch object carries attributes
> improve batch support: added batch cancel, list

- hail/src/main/scala/is/hail/expr/ir/functions/RelationalFunctions.scala
Fixes #5830
Jon, can you test this?
> [bugfix] Fix Nirvana again

- hail/python/hail/matrixtable.py
Fixes #5832
I also changed the pluralization because I think "showing the first 1 columns" sounds better than "showing the first 1 column".
> [hail] fix show

- hail/src/main/scala/is/hail/expr/ir/Env.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
Can't reopen the old one since I force-pushed onto the branch?
> Fix prune rebuild

- hail/src/main/scala/is/hail/expr/ir/functions/MatrixWriteBlockMatrix.scala
- hail/src/main/scala/is/hail/methods/FilterIntervals.scala
- hail/src/main/scala/is/hail/methods/FilterPartitions.scala
- hail/src/main/scala/is/hail/methods/LinearRegression.scala
- hail/src/main/scala/is/hail/methods/LogisticRegression.scala
- hail/src/main/scala/is/hail/methods/PoissonRegression.scala
- hail/src/main/scala/is/hail/methods/Skat.scala
- hail/src/main/scala/is/hail/methods/VEP.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/MatrixIRSuite.scala
> Add tests for relational function serialization roundtrips

- docker/Dockerfile.base
- hail/build.sbt
- hail/get-deployed-sha.sh
- site/poll-0.2.sh
@danking I think you may be the only one using the sbt file?
> Update missed files to spark 2.4

- pipeline/pipeline/backend.py
- pipeline/test-locally.sh
- pipeline/test/test_pipeline.py
> [pipeline] fix local backend write resource groups

- batch/test/test_batch.py
- batch/test/test_dag.py
> [batch] fix flaky callback test

- apiserver/Makefile
- apiserver/apiserver/apiserver.py
- apiserver/setup.cfg
Fix a bunch of pylint and flake things
> [apiserver] fix?

- hail/python/hail/__init__.py
- hail/python/hail/backend/backend.py
- hail/python/hail/fs/__init__.py
- hail/python/hail/fs/fs.py
- hail/python/hail/utils/hadoop_utils.py
- hail/python/hail/utils/java.py
Basic filesystem class, currently only implements Hadoop calls. Tests pass.
Not sure what we'd like to do with the docstring, so left it
All apparently random formatting changes are to force compliance with pep8
> [backend, hail_utils]: add fs class

- hail/python/test/hail/table/test_table.py
- hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala
> [bugfix] Fix physical key pruning issue

- hail/python/hail/linalg/blockmatrix.py
- hail/python/hail/methods/statgen.py
- hail/python/test/hail/linalg/test_linalg.py
- hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
- hail/src/main/scala/is/hail/linalg/BlockMatrix.scala
> [bugfix] Fix BlockMatrix interaction with filtered entries

- batch/batch/aioclient.py
- batch/batch/client.py
- batch/batch/server/database.py
- batch/batch/server/server.py
- batch/test/test_batch.py
@cseed I think this is what you asked for. Please confirm.
> [batch] Add Ready state

- ci/ci/constants.py
- ci/ci/pr.py
Needed so #5866 will pass tests.
> [ci] Expose batch user volumes

- hail/python/hail/context.py
- hail/src/main/scala/is/hail/HailContext.scala
- hail/src/main/scala/is/hail/expr/ir/Optimize.scala
> Iterate on optimization

- hail/diagnose.sh
- hail/python/hail/__init__.py
- hail/python/hail/context.py
- hail/python/test/hail/test_context.py
@cseed @tpoterba thoughts?
Once this is merged, we can just tell people to run
```bash
curl -LO https://raw.githubusercontent.com/hail-is/hail/master/hail/diagnose.sh | bash
```
and send us the output. We can include all sorts of useful diagnostics here. 
I only upload the log and core files to a pastebin if you pass an argument to the script a la:
```bash
curl -LO https://raw.githubusercontent.com/hail-is/hail/master/hail/diagnose.sh | bash -s foo
```
> [hail] diagnose.sh

- README.md
- hail/python/hail/__init__.py
- hail/python/hail/context.py
> update citation section

- ci2/Makefile
fix Makefile typo
This caused the deploy to fail.
> [ci2] fix deploy

- ci2/Makefile
- ci2/deployment.yaml.in
> add missing envvars in ci2 deploy

- hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala
- hail/src/main/scala/is/hail/expr/ir/TableValue.scala
- hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala
- hail/src/main/scala/is/hail/variant/MatrixTable.scala
- hail/src/main/scala/is/hail/variant/ReferenceGenome.scala
- hail/src/test/scala/is/hail/variant/ReferenceGenomeSuite.scala
This should help in parallelizing multi write.
> Update many `write` methods to take hadoop conf

- hail/www/index.md
While we fight over the index page lets at least fix the 404
> fix overview link

- hail/www/index.md
@cseed @jbloom22 
I had forgotten the website's index.html is different from the root README.md. I just copied over the README.md to here. Is there anything from the current website we want to keep? At the very least the overview link was broken.
> fix website

- batch/batch/aioclient.py
- batch/batch/client.py
Save the bucket name in `BatchClient.bucket`
> [batch] get bucket

- ci/Dockerfile
ci needs hailjwt.
this PR https://github.com/hail-is/hail/pull/5941 added a hailjwt dependency to batch client which broke CI.
> [ci] fix ci image

- batch/batch/database.py
- batch/batch/server/database.py
- batch/batch/server/globals.py
- batch/batch/server/google_storage.py
- batch/batch/server/server.py
- batch/test/test_database.py
- pylintrc
Reassigning to @danking since he looked at an earlier version of this.
cc: @cseed 
Stacked on #5866
> [batch] Add SQL persistence to Batch

- hail/python/hail/expr/expressions/typed_expressions.py
- hail/python/hail/ir/ir.py
- hail/python/test/hail/expr/test_expr.py
- hail/src/main/resources/include/hail/NDArray.h
- hail/src/main/scala/is/hail/cxx/EncodeNDArray.scala
- hail/src/main/scala/is/hail/cxx/PackEncoder.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- encoding for .npy format and NDArray `save` method
> [c++][feature] Save NDArrays as .npy

- batch/batch/server/server.py
I already updated the test namespace secret.
> fix private key file name

- hail/python/test/hail/matrixtable/test_matrix_table.py
These actually all pass, much to my surprise, because we're
doing great IR sanitization in Python. I have some changes in
another branch that introduced bugs that tests like this will
make easier to debug.
It's quite satisfying to add a PR with only tests and no code changes.
> Add more tests of globals and literals in MT world.

- hail/src/main/scala/is/hail/expr/ir/Binds.scala
- hail/src/main/scala/is/hail/expr/ir/Children.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/ExtractAggregators.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/InferPType.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/StagedExtractAggregators.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
We need this to lower MatrixMapCols.
Yes, the name is terrible. No, I don't have anything better.
> Add ArrayAggScan node.

- batch/batch/server/server.py
- ci2/Dockerfile.ci-utils
- ci2/Makefile
- ci2/ci/build.py
- ci2/ci/ci.py
- ci2/ci/environment.py
- ci2/ci/github.py
- ci2/ci/templates/index.html
- ci2/deployment.yaml.in
- ci2/jinja2_render.py
- pylintrc
- but don't enable
- add back deployable to watched branches
- add deploy flag to build configuration
- added Code option that represents a version of code (but not quite a sha, because it might do a merge that produces a new sha) and can check itself out
I think this gets us pretty close.  Working on ci2 tests now.
> [ci2] add support for deploy

- .dockerignore
- .gitignore
- batch/.gitignore
- batch/batch/database.py
- batch/batch/server/server.py
- ci2/ci/ci.py
- ci2/ci/templates/batch.html
- ci2/ci/templates/batches.html
> [ci2] fix ui

- batch/batch/server/server.py
Gonna have to force merge this one, batch is DOA.
> [batch] fix duration calculation

- batch/create-batch-tables-pod.yaml
- build.yaml
- ci2/ci/github.py
create batch tables twice to test idempotency
> [ci2] fix merge

- batch/batch/server/database.py
- batch/batch/server/server.py
- batch/create-batch-tables.sql
- batch/test-locally.sh
- pipeline/test-locally.sh
Also changed other helper methods to be only on jobs or batch tables rather than the helper tables jobs-parents and batch-jobs.
> [batch] fix get_jobs performance issue

- hail/build.gradle
This is a temporary workaround to enable easy local testing to continue
> Use new environment parameters in gradle test target

- batch/batch/aioclient.py
- batch/batch/client.py
- batch/batch/server/server.py
- batch/create-batch-tables.sql
- batch/test/test_batch.py
- pipeline/pipeline/backend.py
Not sure why the diff for this is so horrible...
> [batch] Require jobs in a batch

- hail/python/hail/expr/expressions/base_expression.py
- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/expr/types/TableType.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
This is a pretty mega PR, but it would be very difficult to break it up.
> Extend PruneDeadFields to prune key fields (woohoo!)

- batch/batch/server/server.py
- batch/deployment.yaml
- ci2/deployment.yaml
- gateway/deployment.yaml.in
- scorecard/deployment.yaml
@cseed
Step in the right direction. Does not fix all the pod specs already stored in the database.
> [batch][ci2][gateway][scorecard] min cpu

- batch/batch/server/server.py
oops. I was requiring 500,000,000 CPU for every job.
> fix resource requirements

- hail/src/main/scala/is/hail/cxx/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/Children.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/IRBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/main/scala/is/hail/expr/types/virtual/Type.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
> Add CastRename IR node, use to lower MatrixRename

- hail/python/hail/expr/functions.py
- hail/python/hail/ir/ir.py
- hail/python/hail/ir/utils.py
- hail/python/test/hail/test_ir.py
- hail/src/main/scala/is/hail/cxx/Code.scala
- hail/src/main/scala/is/hail/cxx/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/Children.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/main/scala/is/hail/utils/richUtils/RichIterator.scala
- hail/src/test/scala/is/hail/TestUtils.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
This node encapsulates a pattern we use in several places, and lets us generate IR that we can optimize more effectively.
> Add Coalesce IR node

- ci2/ci/github.py
> prioritize merge candidate

- batch/batch-pods-deployment.yaml
- batch/deployment.yaml
- build.yaml
Also increase the limit to 300 distinct pvcs.
> [batch] add pvc limits to deployment.yaml

- ci2/ci/github.py
prefer passing > unknown > failing merge candidates
> split batch update and heal

- ci2/ci/templates/pr.html
cc: @tpoterba @konradjk 
Include the words success and failure and some color, but preserve the exit code.
Also, banish tabs.
> [ci2] loud failure

- hail/python/hail/methods/qc.py
- hail/python/hail/methods/statgen.py
> [hail] nicer error msg for ibd

- ci2/ci/templates/pr.html
- hail/python/test/hail/expr/test_expr.py
> [ci2] watched_branches is not a URL

- hail/python/hail/matrixtable.py
Also remove a bunch of trailing whitespace
> [hail] improve localize entries docs with MT.show

- ci2/ci/ci.py
- ci2/ci/github.py
- ci2/ci/templates/pr.html
github status should be pending if success but build out of date
protect entire build/deploy with try/catch
build_state: merge_failure => error
report build error in pr page
don't merge/deploy if target sha is None
Not showing deploy error yet.
> ci improvments

- batch/batch/aioclient.py
- batch/batch/api.py
- batch/batch/client.py
- batch/batch/database.py
- batch/batch/server/database.py
- batch/batch/server/globals.py
- batch/batch/server/server.py
- batch/create-batch-tables.sql
- batch/test/test_batch.py
- batch/test/test_dag.py
- build.yaml
- ci2/ci/ci.py
- ci2/ci/github.py
- ci2/ci/utils.py
- hail/python/hail/expr/expressions/typed_expressions.py
- pipeline/pipeline/backend.py
@cseed I have a question about batch state when n_jobs == 0. Should this be `ready`? Should `complete` be True or False? I think this will be obsolete once all jobs are submitted with a batch.
- Added triggers to update the Batch state on Job insert, state update
- Got rid of delete and cancel on Job and list_jobs
- Added foreign keys to database with delete cascade
- Misc naming changes for clarity: get_record -> get_records
- Changed list_batches to not include individual jobs but batches/N still returns the jobs
> [batch] SQL and Interface improvements

- build.yaml
> wait 900s for pipeline test

- hail/src/main/scala/is/hail/cxx/Emit.scala
- Don't materialize the result of some NDArray computation when retrieving an element.
- The whole array is still materialized for a `MakeNDArray` but this will fully get rid of intermediates from element-wise operations.
> [c++] Deforest NDArrayRef

- hail/python/hail/docs/tutorials-landing.rst
- hail/python/hail/docs/tutorials/01-genome-wide-association-study.ipynb
- hail/python/hail/docs/tutorials/02-expressions.ipynb
- hail/python/hail/docs/tutorials/03-tables.ipynb
- hail/python/hail/docs/tutorials/04-aggregation.ipynb
- hail/python/hail/docs/tutorials/05-filter-annotate.ipynb
- hail/python/hail/docs/tutorials/06-joins.ipynb
- hail/python/hail/docs/tutorials/07-matrixtable.ipynb
- hail/python/hail/docs/tutorials/08-plotting.ipynb
Also rename tutorial files to be consistent.
Fixes #5739
Assigning Jackie because she has good ideas about tutorials.
> [bugfix] Fix global call rate calculation in GWAS tutorial.

- hail/python/hail/methods/impex.py
Also drop these ignored fields, letting us prune them.
> Warn about ignored fields in `export_vcf`.

- build.yaml
- ci2/ci/build.py
I think this is sufficient for our purposes
> [ci2] add a log option to deploy steps

- ci2/ci/build.py
> [ci2] wait can be none

- hail/src/main/scala/is/hail/expr/ir/Exists.scala
> [hail] Fix Exists.inIR

- hail/python/hail/plot/plots.py
Apparently we're supposed to use collection.defaultdict now.
> [hail] fix plot

- hailctl/python/hailctl/__init__.py
- hailctl/python/hailctl/__main__.py
- hailctl/python/hailctl/dataproc/__init__.py
- hailctl/python/hailctl/dataproc/cli.py
- hailctl/python/hailctl/dataproc/cluster_config.py
- hailctl/python/hailctl/dataproc/connect.py
- hailctl/python/hailctl/dataproc/describe.py
- hailctl/python/hailctl/dataproc/diagnose.py
- hailctl/python/hailctl/dataproc/latest.py
- hailctl/python/hailctl/dataproc/list_clusters.py
- hailctl/python/hailctl/dataproc/modify.py
- hailctl/python/hailctl/dataproc/resources/init_notebook.py
- hailctl/python/hailctl/dataproc/safe_call.py
- hailctl/python/hailctl/dataproc/start.py
- hailctl/python/hailctl/dataproc/stop.py
- hailctl/python/hailctl/dataproc/submit.py
- hailctl/python/hailctl/dataproc/utils.py
- hailctl/python/setup.py
Add `hailctl` as a top-level project. Mostly a copy of cloudtools,
with some additional plumbing on top.
> [hailctl] Initial hailctl commit

- batch/batch/server/server.py
- ci2/ci/ci.py
- ci2/ci/constants.py
- ci2/ci/github.py
- ci2/deployment.yaml
- hailjwt/hailjwt/__init__.py
- hailjwt/hailjwt/hailjwt.py
whitelist PR authorized, ignore the rest
require authorized users
move authenticated_users_only batch => hailjwt
> lock down ci

- hail/src/main/scala/is/hail/cxx/Emit.scala
Create the new shape in one go in the emitted code instead of one-by-one since we have all the info we need at compile-time.
> [c++] simplify deforesting for NDArrayReindex

- ci2/ci/github.py
Resolves #6120.
CI is the authority on PR status. Before attempting a merge we should
tell GitHub what we know. We need only update it on the one status
we want to merge, but this code already exists for updating everyone
and it only makes network requests for out of date statuses. This seems
simple and correct.
> [ci2] update status before attempting merge

- hail/python/hail/expr/aggregators/aggregators.py
- hail/python/hail/expr/functions.py
- hail/python/hail/plot/__init__.py
- hail/python/hail/plot/plots.py
- hail/python/test/hail/expr/test_expr.py
Add an a postiori error estimate for the approximate cdf aggregator. Use in new pdf plotting method than makes no assumption about the smoothness of the true distribution.
> Error estimates for approx quantiles, better PDF plots.

- batch/batch/server/database.py
- batch/batch/server/server.py
- batch/create-batch-tables.sql
- batch/test/test_aioclient.py
- batch/test/test_batch.py
- batch/test/test_dag.py
- ci2/ci/templates/batch.html
- pipeline/pipeline/backend.py
@cseed Feel free to assign to someone else. I just wanted to make sure this change is what we discussed. For ci exit_code display, I just took the max of all of the exit codes.
> [batch] change how exit codes are stored

- apiserver/apiserver/apiserver.py
- apiserver/deployment.yaml
- apiserver/test-apiserver-pod.yaml
- batch/deployment.yaml
- batch/test-batch-pod.yaml
- build.yaml
- ci2/ci/build.py
- ci2/deployment.yaml
- hailjwt/hailjwt/hailjwt.py
- notebook2/deployment.yaml
- notebook2/notebook/notebook.py
- pipeline/test-pipeline-pod.yaml
stacked on: https://github.com/hail-is/hail/pull/6139
create test jwt-secret-key secret and corresponding Hail service accounts.
> Test jwt signing key

- hail/python/hail/methods/statgen.py
For Duncan
FYI @tpoterba (keeper of breaking changes)
> [hail] [breaking] split_multi_hts: take previous GQ if PL is missing

- build.yaml
Deploy failed, I was missing dependencies.
> [hail] add missing dependencies to deploy_hail step

- batch/batch/aioclient.py
- batch/batch/client.py
- batch/batch/server/server.py
- ci2/ci/ci.py
- ci2/ci/templates/batch.html
- ci2/ci/templates/pr.html
- fixes problem where dictionaries may not be sorted
- compare to none in jinja
> [ci] fix exit_code template again

- build.yaml
> fix stupid typo

- hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
- hail/src/main/scala/is/hail/expr/ir/Binds.scala
- hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/Children.scala
- hail/src/main/scala/is/hail/expr/ir/Compilable.scala
- hail/src/main/scala/is/hail/expr/ir/CompileAndEvaluate.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/EvaluateRelationalLets.scala
- hail/src/main/scala/is/hail/expr/ir/FoldConstants.scala
- hail/src/main/scala/is/hail/expr/ir/ForwardLets.scala
- hail/src/main/scala/is/hail/expr/ir/ForwardRelationalLets.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/MapIR.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala
- hail/src/main/scala/is/hail/expr/ir/Optimize.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/Scope.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
> Add relational let nodes

- hailctl/python/hailctl/dataproc/resources/init_notebook.py
- hailctl/python/hailctl/dataproc/start.py
(this is your PR updated against hailctl)
> [hailctl] Don't reinstall conda

- letsencrypt/domains.txt
- router/router.nginx.conf.in
Also removed unused domain names (test, dev1) and added internal for future use to route to internal namespaces.
> expose batch

- hail/src/main/scala/is/hail/expr/ir/Children.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
Assigned high priority since this is a pretty small PR that's now blocking a larger one.
> [hail] Lowered MatrixMultiWrite node

- batch/batch/server/server.py
Necessary for the templating to work.
> batch: initialize jinja

- gateway/Makefile
- router-resolver/Makefile
Some fixes to my recent resiliency changes.  These weren't caught because gateway and router-resolver are part of infrastructure that isn't automated by ci yet.  I needed to make these changes to deploy them by hand (which I did successfully).
> some fixes to gateway, router-resolver Makefile

- batch/batch/server/server.py
- batch/test/test_batch.py
Another attempt at getting the batch ui up.  Add ui tests (just verify successful status code) to hopefully reduce the iteration time.
> [batch] jinja template can't be web response

- hail/src/main/scala/is/hail/expr/ir/functions/DictFunctions.scala
> [hail][feature] Improve DictExpression.__getitem__ error message.

- batch/batch/server/server.py
- batch/batch/templates/batch.html
- batch/batch/templates/batches.html
- batch/batch/templates/job_log.html
- batch/test/test_batch.py
- pipeline/pipeline/backend.py
Use name attribute for label in pipeline, this matches the ci convention.  Display the name attribute.
> port features from ci ui to batch

- build.yaml
- ci/ci/build.py
The changes to build.yaml won't kick in until ci redeploys with these changes.
> add resources to runImage step

- hail/python/hail/expr/functions.py
- hail/python/hail/ir/register_functions.py
- hail/python/hail/methods/impex.py
- hail/python/test/hail/expr/test_expr.py
- hail/python/test/hail/methods/test_impex.py
- hail/src/main/scala/is/hail/asm4s/Code.scala
- hail/src/main/scala/is/hail/expr/AnnotationImpex.scala
- hail/src/main/scala/is/hail/expr/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/functions/ReferenceGenomeFunctions.scala
- hail/src/main/scala/is/hail/io/reference/LiftOver.scala
- hail/src/main/scala/is/hail/variant/Locus.scala
- hail/src/main/scala/is/hail/variant/ReferenceGenome.scala
- hail/src/test/resources/example2.bed
- pipeline/pipeline/utils.py
Hopefully, third time is the charm for this...
Same PR as #5935 #5355
> [hail] Fix import_bed interval length = 0

- hail/python/hail/matrixtable.py
- hail/python/test/hail/matrixtable/test_matrix_table.py
- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
> [hail][bugfix] Add distincting to MatrixTable.union_rows

- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
> [hail][bugfix] make sure to lower children of BlockMatrixIR

- hail/python/hail/plot/plots.py
Somehow a logger object was getting imported (maybe from bokeh?)
and overwriting `log`.
`import *` is very bad style when we we're not sure what we're doing.
> [hail] fix plotting imports

- hail/python/hail/expr/expressions/typed_expressions.py
- hail/python/hail/ir/ir.py
- hail/python/test/hail/expr/test_expr.py
- hail/src/main/scala/is/hail/cxx/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/Children.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
Left to do:
- error checking on bounds of slices. This could either be done in the emitted code for slice or in the IR with Die and what not. Open to advice on which is better.
- bind shape in the python iR generation so it doesn't get repeated a bunch of times. This would go along with the bounds checking in python
> [c++]Ndarray slice

- hail/python/hail/matrixtable.py
- hail/python/test/hail/matrixtable/test_matrix_table.py
I must have broke this in march -- I changed that line
> [hail][bugfix] Fix filter_cols aggregations

- hail/src/main/scala/is/hail/cxx/EncodeNDArray.scala
> [c++] Clean up repeated code in NDArray encoding

- hail/src/main/scala/is/hail/expr/ir/ExtractIntervalFilters.scala
- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/expr/ir/TableValue.scala
- hail/src/main/scala/is/hail/expr/ir/functions/RelationalFunctions.scala
- hail/src/main/scala/is/hail/expr/types/MatrixType.scala
- hail/src/main/scala/is/hail/io/LoadMatrix.scala
- hail/src/main/scala/is/hail/io/bgen/BgenRDD.scala
- hail/src/main/scala/is/hail/io/bgen/BgenRDDPartitions.scala
- hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala
- hail/src/main/scala/is/hail/io/gen/ExportGen.scala
- hail/src/main/scala/is/hail/io/plink/ExportPlink.scala
- hail/src/main/scala/is/hail/io/vcf/ExportVCF.scala
- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
- hail/src/main/scala/is/hail/methods/IBD.scala
- hail/src/main/scala/is/hail/methods/LocalLDPrune.scala
- hail/src/main/scala/is/hail/methods/LogisticRegression.scala
- hail/src/main/scala/is/hail/methods/PCA.scala
- hail/src/main/scala/is/hail/methods/PCRelate.scala
- hail/src/main/scala/is/hail/methods/PoissonRegression.scala
- hail/src/main/scala/is/hail/methods/Skat.scala
- hail/src/main/scala/is/hail/variant/MatrixTable.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/MatrixIRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
- hail/src/test/scala/is/hail/testUtils/RichMatrixTable.scala
- hail/src/test/scala/is/hail/vds/JoinSuite.scala
> [hail] MatrixType.rvRowType dies a timely death

- batch/batch/server/server.py
@cseed I think this will be an improvement and doesn't require a database change.
> [batch] Add failure reason to logs

- ci/ci/constants.py
@cseed can you confirm that this is the only place I need to add Brandon for him to get merging into master?
> Add Brandon Franco to dev list

- apiserver/Dockerfile.hail-jupyter
> add --allow-root to jupyter

- batch/batch/aioclient.py
- batch/batch/client.py
Didn't realize the attributes was being used by ci.
> [batch] fix missing attributes in batch builder

- notebook2/notebook/notebook.py
> [notebook] fix for k8s vulnerability

- pipeline/pipeline/backend.py
- Added `gsa_key_file` which will mount a specified file to `/gsa-key/privateData`. Also looks at `HAIL_PIPELINE_GSA_KEY_FILE` if `gsa_key_file` is not specified.
- Added `extra_docker_run_flags`. Also looks at `HAIL_PIPELINE_EXTRA_DOCKER_RUN_FLAGS` if `extra_docker_run_flags` is not specified.
I tested this by hand on my local computer.
FYI: @cseed and @konradjk
> [pipeline] add extra local backend options

- hail/build.gradle
> [hail] remove ./gradlew pipInstall

- batch/batch/aioclient.py
- batch/batch/globals.py
- batch/batch/server/database.py
- batch/batch/server/server.py
- batch/create-batch-tables.sql
- batch/test/test_aioclient.py
- batch/test/test_batch.py
- batch/test/test_dag.py
- pipeline/pipeline/backend.py
Old State Diagram:
Created -> Ready -> Complete
Cancelled
New State Diagram:
Pending -> Ready -> (Error, Running -> (Failed, Success))
Cancelled
> [batch] change Job state diagram

- hail/build.sbt
- hail/src/main/scala/is/hail/HailContext.scala
- hail/src/main/scala/is/hail/nativecode/NativeCode.java
I'm building hail things again, SBT complained about these things.
> [hail] fix some compile issues

- build.yaml
there aren't any scorecard tests, and running it in tests is blowing
out Github request limits.
FYI @tpoterba
> [scorecard] don't test scorecard

- hail/src/main/scala/is/hail/expr/ir/ExtractIntervalFilters.scala
I saw an adversarial example in some of Christina's code.
> [hail] Cap size of literals extracted as FilterIntervals nodes

- hail/Makefile
Not sure where in my brain the previous code came from, it
was totally wrong.
> [hail] Fix pypi-deploy rule

- ci/ci/github.py
> [ci] Track all labels on PR, don't merge stacked PRs

- hail/src/main/scala/is/hail/HailContext.scala
- hail/src/main/scala/is/hail/backend/Backend.scala
- hail/src/test/scala/is/hail/SparkSuite.scala
This should definitely be disabled until we fix the region thing, oops.
> turn off lowered compile except for tests

- hail/src/main/scala/is/hail/cxx/Emit.scala
Very few actual code changes. Instead of calling `emit` on child to realize a NDArray in memory, use the deforested emitter of the child.
> [c++] deforest NDArray aggs

- hail/.gitignore
- hail/Makefile
- Expand variables at definition
- Fix pip definition, allow it to be overwritten
- Copy hail_version and hail_pip_version into hailctl to not break
local PYTHON_PATH settings.
> Makefile cleanup

- hail/python/scripts/drive_combiner.py
Want it in source control for reproducibility
> Add another combiner driver script.

- hail/Makefile
- hail/python/hail/docs/getting_started_developing.rst
Adds a new target to make file that installs all dependencies and developer dependencies.
> Added install-deps target to Makefile

- hail/Makefile
Discussed here: 
https://github.com/hail-is/hail/pull/6318#issuecomment-501313676
> Fixed Makefile so it would not always attempt to cat pypi creds

- hail/src/main/scala/is/hail/expr/ir/IR.scala
I have yet to figure out why this is so expensive, but it's got to
goo off until I do.
> [hail] [high-prio] Don't optimize in ApplyIR

- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/types/MatrixType.scala
- hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala
- hail/src/main/scala/is/hail/io/gen/LoadGen.scala
- hail/src/main/scala/is/hail/io/plink/LoadPlink.scala
- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
- hail/src/main/scala/is/hail/methods/WindowByLocus.scala
- hail/src/main/scala/is/hail/variant/MatrixTable.scala
- hail/src/test/scala/is/hail/TestUtils.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
Now same as the constructor, copy.
> [hail] cleanup: remove MatrixType.{fromParts, copyParts}

- hail/src/main/resources/include/hail/Ordering.h
> [hail] no tabs

- batch/batch/server/server.py
Instead of having an explicit state in the database (added complexity), just return 'Running' to the user in `to_dict` if the state is Ready and there is a pod assigned to it.
Stacked on #6341
> [batch] get rid of running state in server code

- batch/batch/aioclient.py
- batch/batch/server/server.py
- batch/batch/templates/batches.html
- batch/test/test_batch.py
- ci/ci/ci.py
- ci/ci/github.py
@cseed I didn't know what to do with healthcheck. I think we either need two routes or keep it at `/healthcheck`
> [batch] rename routes

- batch/batch/server/server.py
This can probably be better optimized, but it is part of a larger problem with the notify children not happening atomically. Working on a better fix, but that will take some time. Figured this is an improvement.
> [batch] update state with ec, log atomically

- ci/ci/github.py
- ci/ci/templates/index.html
> [ci] Add out-of-date indicator to CI UI

- hail/src/main/scala/is/hail/scheduler/Client.scala
also fixes completed task accounting with callback exceptions
> [scheduler] add some logging to scheduler client

- batch/batch/aioclient.py
- batch/batch/database.py
- batch/batch/server/database.py
- batch/batch/server/server.py
- batch/test/test_batch.py
- batch/test/test_dag.py
> [batch] create batch atomically

- batch/batch/server/server.py
@konradjk Hopefully this will fix it until I can get a streaming based solution in. Default value is 1024**2
> [batch] increase client_max_size for requests

- ci/ci/ci.py
Need to update the GitHub web hook once this goes in.
> [ci] change route name to github_callback

- ci/ci/ci.py
- ci/ci/github.py
- ci/ci/templates/index.html
> [ci] Add age to CI deploy/build statuses

- hail/python/test/hail/table/test_table.py
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
> [hail][bugfix] Fix TableFilterIntervals/TableMapRows rewrite

- hail/python/hail/ir/blockmatrix_ir.py
- hail/python/hail/ir/blockmatrix_reader.py
- hail/python/hail/ir/blockmatrix_writer.py
- hail/python/hail/ir/ir.py
- hail/python/hail/ir/matrix_ir.py
- hail/python/hail/ir/matrix_reader.py
- hail/python/hail/ir/matrix_writer.py
- hail/python/hail/ir/table_ir.py
- hail/python/hail/ir/table_reader.py
- hail/python/hail/ir/table_writer.py
- hail/python/hail/matrixtable.py
- hail/python/hail/utils/java.py
- hail/python/hail/utils/misc.py
- hail/python/test/hail/utils/test_utils.py
- hail/src/main/scala/is/hail/utils/Py4jUtils.scala
Crazy to call out to JVM for the sake of escaping strings.
> Johnc Removing JVM from Escaping Strings

- hailjwt/hailjwt/csrf.py
https://stackoverflow.com/questions/42043226/using-a-coroutine-as-decorator
> [hailjwt,ci] fix authorized sha csrf

- hail/src/main/scala/is/hail/scheduler/Client.scala
- hail/src/main/scala/is/hail/scheduler/package.scala
- hail/src/test/scala/is/hail/TestUtils.scala
- scheduler/scheduler/scheduler.py
- scheduler/templates/index.html
Adds a job token to track jobs submitted by a client. I think this *should* fix the hanging issue we've been seeing on the ci with the distributed backend test.
> [scheduler][bugfix-ish] add more logging, job tokens

- hail/.gitignore
- hail/Makefile
- hail/python/hailtop/hailctl/__main__.py
- hail/python/hailtop/hailctl/dataproc/start.py
- hail/python/setup.py
* Hailtop wasn't a module.
* The import paths were fucked.
* There was a syntax error in setup.py
* No dirty trees after builds
> [hailtop][bugfix] Fix hailtop everything

- batch/batch/server/server.py
- build.yaml
- gear/gear/__init__.py
- gear/gear/logging.py
- router-resolver/router-resolver/router-resolver.py
- scheduler/Dockerfile
- scheduler/MANIFEST.in
- scheduler/scheduler/__init__.py
- scheduler/scheduler/__main__.py
- scheduler/scheduler/scheduler.py
- scheduler/setup.py
stacked on: https://github.com/hail-is/hail/pull/6424
> Gear logging

- scorecard/scorecard/scorecard.py
I'd like to get on the scorecard random reviewers selector.
> Add johnc to scorecard random reviewers

- batch/batch/templates/batches.html
Copied from ci -- index.html
FYI @konradjk
> [batch] search bar for batches.html

- batch/batch-pods-deployment.yaml
See discussion on Zulip https://hail.zulipchat.com/#narrow/stream/127527-team/topic/batch
Our worst case monthly cost moves from 40 USD to 4000 USD. However, PVCs seem to be rather reliably cleaned up now, so I am not overly concerned about this. We also have monitoring on PVC storage capacity.
> [batch] increase storage limit to 100Ti / 100000

- hail/src/main/scala/is/hail/expr/ir/TableValue.scala
- hail/src/main/scala/is/hail/methods/IBD.scala
- hail/src/main/scala/is/hail/table/Table.scala
Does not extend into modifying TableValue, as this affects the IR, relates to the boundary you spoke of I believe, and will affect much more besides IBD. Happy to start digging into that in this PR or the next PR if desired.
cc @cseed
> [hail] IBD Type

- batch/batch/batch.py
> [batch] add error information to debug message

- notebook2/notebook/static/styles/pages/user.scss
- notebook2/notebook/templates/layout.html
viewport meta tag, left align name on user page
> [notebook2] viewport meta tag, left align name on user page

- hail/python/hail/table.py
> Fix truncation in html

- hail/python/hail/table.py
> [hail][bugfix] Fix Table.show collecting data twice

- batch/batch/batch.py
- batch/batch/queue.py
- batch/test/test_dag.py
> [batch] add start jobs queue

- batch/batch/batch.py
> [batch] easy performance improvements

- scorecard/scorecard/scorecard.py
> bringing it full circle

- hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
- hail/src/main/scala/is/hail/expr/types/physical/PContainer.scala
- hail/src/test/scala/is/hail/annotations/StagedRegionValueSuite.scala
(Changes from #6480)
No tests for this right now, although I can write some---they get exercised through the staged region value aggregator stuff.
> implement deep copy in SRVB

- ci/ci/github.py
Fixes #6324
I'm not sure I got all of the places this can happen, but hopefully this will unstick ci.
> [ci] fix deadlock if unauthorized PR is merge candidate

- batch/batch/batch.py
- batch/batch/database.py
- batch/batch/k8s.py
- batch/batch/templates/batch.html
- batch/batch/templates/pod_status.html
- batch/create-batch-tables.sql
- batch/test/test_batch.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/batch_client/client.py
- hail/python/hailtop/hailctl/batch/cli.py
- hail/python/hailtop/hailctl/batch/pod_status.py
@danking Feel free to reassign if you have too much to do.
Requires a database change. I realize there's a lot of code duplication here with how we get/show the logs. It might be worth generalizing this in the future if there's a third thing that follows this pattern.
> [batch] save pod status

- batch/batch/batch.py
> [batch] fix mark_unscheduled if log exists in db

- batch/batch/batch.py
I thought I had this fixed in my PR that merged...
> [batch] fix polling loop with mysql

- batch/batch/batch.py
- docker/requirements.txt
Seeing if I can get any batch logging going in Prometheus without personal batch working.
> Johnc batch logging Experiment

- hail/python/hailtop/hailctl/dev/benchmark/__init__.py
- hail/python/hailtop/hailctl/dev/benchmark/cli.py
- hail/python/hailtop/hailctl/dev/benchmark/utils.py
> [benchmark] Add argument to filter simple patterns

- hail/python/hailtop/hailctl/dev/benchmark/table_benchmarks.py
> [benchmark] Add simple range_table write benchmarks

- hail/src/main/scala/is/hail/expr/ir/AggOp.scala
- hail/src/main/scala/is/hail/expr/ir/Compile.scala
- hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
This is the first broken off piece of @catoverdrive's PR #6518. Staged on #6501 (only look at last commit).
> Staged aggs 1

- ci/ci/github.py
Wasn't sure if this should raise an error or just continue.
> [ci] log batch id that raises an exception

- batch/batch/database.py
> [batch] add retry query logic for new_record and update_record

- batch/batch/batch.py
- batch/batch/database.py
> [batch] use compare and swap when updating a record

- monitoring/monitoring.yaml
Addresses #6495 
Insane Prometheus incantation sourced from here: https://blog.freshtracks.io/a-deep-dive-into-kubernetes-metrics-part-4-the-kubernetes-api-server-72f1e1210770
Stacked on #6413
> Kubernetes apiserver logs

- hail/src/main/scala/is/hail/expr/ir/Compile.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
Second piece of #6518; staged on #6530. Changes in Emit to enable staged aggregators.
> Staged aggs 2

- batch/batch/batch.py
A bunch of untested code to time batch endpoints. Will also want to do database calls but little bit at a time.
> Batch timing: HTTP Requests

- hail/python/hailtop/hailctl/dataproc/start.py
> [hailctl] Fix package management for dataproc

- batch/batch/batch.py
- batch/deployment.yaml
Gives the metric a reasonable name, adds a necessary label.
> Johnc prometheus batch timings

- hail/python/hail/__init__.py
- hail/python/hail/context.py
@tpoterba I think we need this until 0.3
> [hail] restore backwards compatibility

- hail/python/hailtop/hailctl/dev/benchmark/__init__.py
- hail/python/hailtop/hailctl/dev/benchmark/cli.py
- hail/python/hailtop/hailctl/dev/benchmark/utils.py
Default format is now a table.
> [benchmark] Parameterize output formats, files, verbosity.

- batch/batch/batch.py
- batch/batch/database.py
- batch/create-batch-tables.sql
Same PR as #5990, but I rebased it on current master and I'll debug it. FYI: @danking
> [batch] batch attributes table

- hail/python/hailtop/hailctl/dataproc/start.py
> [hailctl] Add pass-through args to `hailctl dataproc start`

- hail/python/hail/genetics/reference_genome.py
- hail/python/hail/plot/plots.py
> [hail][bugfix] Fix reference genome compatibility in plot.manhattan

- ci/ci/constants.py
- scorecard/scorecard/scorecard.py
Add me to the scorecard so I can be picked for reviewing
> Add iitalics to scorecard

- ci/ci/build.py
Ci is currently failing because this variable is not defined.
> Missed renaming this instance of 'deploy' varable to 'scope'

- ci/ci/ci.py
- hail/python/hailtop/hailctl/dev/deploy/cli.py
Forgot to authorize when I did dev deploy.
> Dev Deploy Auth Correction

- ci/ci/ci.py
- ci/ci/constants.py
- hail/python/hailtop/hailctl/dev/deploy/cli.py
Part 1 of improving dev deploy usability. This PR:
- Moves definition of profiles out of CI so that new build steps can be added as part of development.
> Dev Deploy profiles live on client side

- scorecard/deployment.yaml
> Scorecard Readiness Probe

- image-fetcher/fetch-image.sh
> [notebook] add worker-image for notebook

- README.md
- hail/www/index.md
- hail/www/references.md
@tpoterba @jbloom22 
1) New page with list of references
2) Link from index.md and README.md
> List of references

- batch/deployment.yaml
- ci/deployment.yaml
We've designed them to not have state
> [batch][ci] tolerate preemptibles

- notebook/Makefile
- notebook/images/hands-on-with-hail/resources/Hands-on Genomics with Hail.ipynb
- notebook/notebook/notebook.py
Yeah that shell find is totally broken. I'll fix it properly later. The k8s API changed since we last deployed. I'm hand deploying this now anyway.
> [notebook] fix bugs.

- batch/batch/k8s.py
Start tracking time to create a pod and a pvc.
> [batch] Monitoring

- hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
- hail/src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala
- hail/src/main/scala/is/hail/expr/ir/functions/ReferenceGenomeFunctions.scala
- hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
> [hail] (PTypes) make `Functions.unwrapReturn` use physical type

- batch/batch/batch.py
- batch/batch/database.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/batch_client/client.py
- provide a default session
- made cancel not wait for all jobs to be cancelled before returning
- some log statements
- fix error catching in retry function
- add retry to batch client create jobs
- add cancel if batch is not submitted successfully
> [batch] miscellaneous usability improvements

- batch/batch/batch.py
- batch/batch/database.py
- batch/batch/queue.py
- batch/test/test_batch.py
- batch/test/test_dag.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/batch_client/client.py
I added support for order by as well, but didn't expose it yet. We can get to that later when we add sorting to tables.
> [batch] add support for pagination in server

- batch/batch/batch.py
I missed the `pod_status` thing in the rebase. The container log is just a mistake on my part.
> [batch] two small fixes

- hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala
> Revert "[testing] Enable un-decorated tests in OrderingSuite"

- ci/ci/ci.py
Without this I cannot see my dev deploy batches.
> [ci] fix batch page

- router/deployment.yaml
This resolves the router CrashLoopBackOff issue
> [ci] fix bug in router/deployment.yaml

- README.md
> Updated readme with Community section

- hail/src/main/scala/is/hail/backend/Backend.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
> [hail][bugfix] Fix parsing and array element required types

- ci/ci/build.py
> Remove Sink Job from build.py

- ci/ci/build.py
This reverts commit 3ed684c64c9e4d80a2c2531cc745a05a25cd4637.
> Revert "Remove Sink Job from build.py (#6764)"

- batch/batch/batch.py
The risk is that a container image will eventually be pushed
to the container registry allowing this container to proceed.
We do not rely on this behavior (modulo the eventual consistency
of GCR).
> [batch] image pull back off means container failure

- hail/python/hail/methods/statgen.py
- hail/python/test/hail/methods/test_misc.py
Tests are approximate but should be safe.
> [hail][bugfix] Fix lambda_gc method

- hail/.gitignore
- hail/Makefile
- hail/python/setup.py
It was broken, trying to read a file that didn't exist.
> fix `hailctl version`

- hail/src/main/scala/is/hail/expr/ir/agg/AppendOnlyBTree.scala
- hail/src/test/scala/is/hail/expr/ir/StagedBTreeSuite.scala
Tests against a scala mutable.Set and a random batch of inserts.
> StagedBTree (append-only) implementation + test

- batch/batch/batch.py
This was a recently committed mistake of mine.
Whoops.
As written, nothing happens.
> [batch] need to await mark_complete

- hail/build.gradle
- hail/src/main/scala/is/hail/linalg/BlockMatrix.scala
- hail/src/main/scala/is/hail/linalg/GridPartitioner.scala
- hail/src/test/scala/is/hail/linalg/BlockMatrixSuite.scala
This allows filtering sparse matrices without densifying.
> Sparse Matrix Filter

- hail/python/test/hail/expr/test_expr.py
- hail/src/main/scala/is/hail/expr/ir/agg/TakeAggregator.scala
array_agg is broken for take, too :(
Can't release until we fix this bug.
> [hail] Add failing test for array_agg with take

- hail/python/hailtop/hailctl/dev/benchmark/compare/compare.py
The json output now has "config" and "benchmarks" top level fields
> [benchmark] Update compare logic to process new schema

- hail/python/hail/docs/_static/rtd_modifications.css
- hail/python/hail/docs/api.rst
- hail/python/hail/docs/experimental/index.rst
- hail/python/hail/docs/experimental/ldscsim.rst
- hail/www/references.xslt
Fixes:
* increase docs width to 1200px to tutorials render OK
* add xslt file for references
* add folder for experimental stuff
* add ldscsim file
> [docs] Docs fixes

- hail/python/hail/context.py
Shows you how much they were being used :)
> [hail] fix citation

- hail/src/main/scala/is/hail/annotations/aggregators/ArrayElementsAggregator.scala
- hail/src/main/scala/is/hail/annotations/aggregators/KeyedRegionValueAggregator.scala
- hail/src/main/scala/is/hail/annotations/aggregators/RegionValueAggregator.scala
- hail/src/main/scala/is/hail/annotations/aggregators/RegionValueCollectAggregator.scala
- hail/src/main/scala/is/hail/annotations/aggregators/RegionValuePrevNonnullAnnotationAggregator.scala
- hail/src/main/scala/is/hail/annotations/aggregators/RegionValueTakeAggregator.scala
- hail/src/main/scala/is/hail/annotations/aggregators/RegionValueTakeByAggregator.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
- hail/src/main/scala/is/hail/rvd/RVD.scala
- hail/src/main/scala/is/hail/sparkextras/ContextRDD.scala
> [hail] Add commutative combiner to reduce aggregation memory pressure

- notebook/Dockerfile
- notebook/notebook/notebook.py
- notebook/notebook/templates/wait.html
- notebook/scale_test.py
There is more work to do to get this unified with the modern hail deployment (note that I copied the logging setup here). Nevertheless, this brings asyncio to notebook leader, which enables it to handle a helluva lot more simultaneous users.
Next steps are to get this regularly deployed again and to get it on to a normal hail docker image.
> [notebook] aiohttp notebook leader

- batch/Dockerfile.check
- batch/Dockerfile.test
- batch/batch/batch.py
- batch/batch/database.py
- batch/batch/datetime_json.py
- batch/batch/k8s.py
- batch/batch/log_store.py
- batch/batch/throttler.py
- build.yaml
Batch PRs now require flake8 and pylint to pass.
I also pinned the pytest-instafail version we use in test_batch.
> [batch] enforce checkers

- batch/batch/batch.py
🐎 💨 
I tested this pretty heavily during my scale testing.
> [batch] more concurrency in refresh loop

- batch/batch/batch.py
apparently gather runs things in the background even if
you do not await the gather task, which is different from
other awaitables (which simply do nothing), the result was
that batch nondeterministically succeeds, depending on
whether the tasks execute in the order of the program or not.
> [batch] hotfix we have to await awaitable things

- ci/ci/build.py
Please verbally tell me when you're going to approve this, I'd like to be ready in case it breaks ci, since last time I made a change like this I had to revert it to go home.
> No sink, attempt 2

- hail/python/test/hail/expr/test_expr.py
- hail/src/main/scala/is/hail/expr/ir/agg/StagedArrayBuilder.scala
fixes #6860 
i also need this for my PR #6742 to stop segfaulting
> [hail] [bugfix] Fix Take aggregator's handling of pointers

- hail/Makefile
- hail/python/hailtop/hailctl/batch/cli.py
I needed this when running PR tests. It is also useful for dev deploys.
I also fixed a minor bug in install-editable
> [batch] make master url configurable

- batch/batch/batch.py
we used the wrong key for the copy. I don't even know what the other key is for. It's removed by my forthcoming batch changes.
> [ci] fix bad key

- batch/batch/throttler.py
> [batch] one fix

- batch/batch/__main__.py
> [batch] configure logging

- docker/requirements.txt
I'm hoping adding these packages to current master will make my batch2 dev builds faster!
> [batch2] add packages to base image

- ci/ci/ci.py
This is a regression from a recent batch change
> [ci] use humanize on durations

- hail/python/hailtop/hailctl/dataproc/cli.py
- hail/python/hailtop/hailctl/dataproc/modify.py
- hail/python/hailtop/hailctl/dataproc/start.py
- hail/python/hailtop/hailctl/dataproc/stop.py
Also `max-idle` and similar are no longer beta commands.
> Add --beta argument to force gcloud beta

- monitoring/monitoring.yaml
> Requesting lots of memory for Prometheus

- hail/python/hail/methods/family_methods.py
Fixes #6888
Also simplify code to remove redundant checks.
> [docs] Fix `de_novo` docs

- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
> [hail] Simplify BGEN row count

- hail/python/hail/experimental/sparse_split_multi.py
Updating some docs since I found spots that were out of date and I got really confused trying to refresh myself on what it did just now.
Also, I think the hom_ref case needs to update the GQ if the PL is recalculated, so I did that.
> fix docs for sparse_split_multi, update GQ

- hail/python/hail/experimental/sparse_split_multi.py
In the raw gnomAD v3 data, there are exactly 4 samples each with one variant
that changes loci after min_rep. It has the effect of removing the problematic
variants from the output, without removing anything else, so ref-blocks and
other variants are preserved.
> [hail] add ability to filter variants that change loci from split output

- ci/Makefile
- ci/ci/ci.py
- docker/Makefile
Fixed some minor regressions introduced by: https://github.com/hail-is/hail/pull/6915
> [ci] fix ci regressions

- hail/python/hail/experimental/import_gtf.py
> [hail] fixing specification of reference genome in experimental.get_gene_intervals

- docker/requirements.txt
- router/deployment.yaml
- router/router.nginx.conf.in
plus some router config fixes.
Mainly I'm PR'ing this so I can use the cached base image when testing.
> [auth] auth preliminaries

- hail/python/hail/experimental/densify.py
On a test of 1-2 partitions with 5000 samples, this takes the second stage of a densify from 2 minutes down to 1.4 minutes (only loading GT).
> [hail] store contig as index in densify

- hail/python/hail/linalg/blockmatrix.py
Adding checkpointing as a quality of life improvement for block matrices.
> Support checkpoint on BlockMatrix

- hail/python/hailtop/hailctl/dev/benchmark/run/matrix_table_benchmarks.py
- hail/python/hailtop/hailctl/dev/benchmark/run/utils.py
- hail/src/main/scala/is/hail/io/gen/ExportBGEN.scala
* add simulated BGEN file based on distributions in real data
* add import, info score, filter benchmarks
* fix bad error message in `export_bgen`
> [benchmark] Add BGEN benchmarks

- hail/python/hail/ir/ir.py
- hail/python/test/hail/test_ir.py
This caused problems in struct annotate deduplication.
> [hail][bugfix] Fix IR hashing issues

- hail/Makefile
- hail/python/hail/docs/Makefile
- hail/python/hail/docs/tutorials-landing.rst
Also fix make targets.
Fixes #6520
> [docs] Add a download link for a .tar.gz with tutorials

- hail/python/hail/genetics/call.py
- hail/python/hail/genetics/locus.py
- hail/python/hail/utils/interval.py
- hail/python/hail/utils/struct.py
* Struct
* Locus
* Call
* interval
> [docs] Clarify local objects and link to expressions/functions

- build.yaml
- hail/Makefile
- hail/python/hail/docs/Makefile
Also clean up tutorials directory, and set retentions.
> [docs] Add make target to build and deploy docs

- hail/Makefile
Fixed version.
We should get this in, or something else, today, so that visitors see non-broken docs.
> [www] cache bust css

- batch/batch/batch.py
We might need to force deploy this, but let's see if it just works first.
> [batch] Fix missing await in read failed logs

- notebook/notebook/notebook.py
Found these today. need to convert to string and correctly specify the query parameters
> [notebook] fix bugs

- hail/python/hailtop/hailctl/dataproc/stop.py
hailctl dataproc stop now supports passthrough, dry-run
Resolves #7014
> hailctl dataproc stop now supports passthrough, dry-run

- hail/python/hail/linalg/blockmatrix.py
This documentation is out of date as of #6723
> Reflect updates to block matrix filtering in docs

- hail/benchmark/Dockerfile
> [benchmark] pip install aiomysql

- hail/src/main/scala/is/hail/io/RowStore.scala
> [hail] Remove NativePackEncoder/NativePackDecoder

- hail/src/main/scala/is/hail/io/index/IndexReader.scala
- hail/src/main/scala/is/hail/io/index/IndexWriter.scala
Fixes #7044. (tested on cluster)
> [hail][bugfix] don't extract types on workers in IndexReader

- auth/create-accounts-pod.yaml
- batch/batch/batch.py
- notebook2/notebook/notebook.py
- notebook2/notebook/templates/header.html
Changes:
- add link to batch to notebook2 header
- and links to ci, scorecard for developers
- make create_accounts idemopotent
Next, I'm going to add the notebook2 styling to batch, ci and scorecard to give at least a somewhat unified experience to the collection of services.
> [notebook2] expand header

- hail/src/main/scala/is/hail/backend/Backend.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/TableValue.scala
- hail/src/main/scala/is/hail/expr/types/physical/PStruct.scala
- hail/src/main/scala/is/hail/io/TextMatrixReader.scala
- hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala
- hail/src/main/scala/is/hail/methods/Nirvana.scala
- hail/src/main/scala/is/hail/methods/PCA.scala
- hail/src/main/scala/is/hail/methods/Skat.scala
- hail/src/main/scala/is/hail/utils/richUtils/RichContextRDDRow.scala
- hail/src/test/scala/is/hail/TestUtils.scala
- hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala
- hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
I think this the last of them outside of:
* aggregators
* encoding/indexes
> [hail] (PTypes) Remove usages of physicalType

- hail/Makefile
- hail/python/hail/docs/change_log.md
Add change log for release 0.2.22
> [hail] release 0.2.22

- hail/python/hail/docs/hail_on_the_cloud.rst
- hail/python/hailtop/hailctl/dataproc/cli.py
- hail/python/hailtop/hailctl/dataproc/submit.py
Someone had asked how to pass args to their python script on dataproc submit, and it I realized it was no documented, so I added it to the website and to the command line help info. Happy to make changes to wording for clarity. 
Addresses #6899
> Document passing args to dataproc submit

- hail/src/main/scala/is/hail/expr/ir/agg/StagedBlockLinkedList.scala
- hail/src/main/scala/is/hail/expr/types/physical/PContainer.scala
- hail/src/main/scala/is/hail/expr/types/physical/PStruct.scala
- hail/src/main/scala/is/hail/io/RowStore.scala
- hail/src/test/scala/is/hail/expr/ir/agg/StagedBlockLinkedListSuite.scala
implements a growable linked list of buffers, for O(1) append and small space overhead
> [hail] Linked-list-of-blocks (staged) data structure

- notebook/images/isia/Dockerfile
Added more files for the instructors. I expect no more changes
> [notebook] update lima image

- hail/src/main/scala/is/hail/annotations/RegionPool.scala
- hail/src/test/scala/is/hail/annotations/RegionSuite.scala
> [hail] Use thread-local storage for regions

- hail/src/main/scala/is/hail/annotations/RegionPool.scala
> [hail] RegionPool echoes at a doubling size threshold

- hail/python/hailtop/hailctl/dev/benchmark/run/table_benchmarks.py
- hail/python/test/hail/expr/test_expr.py
- hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
- hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala
- hail/src/main/scala/is/hail/expr/ir/agg/CallStatsAggregator.scala
- hail/src/main/scala/is/hail/expr/ir/agg/CollectAsSetAggregator.scala
- hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
- hail/src/main/scala/is/hail/expr/ir/agg/GroupedAggregator.scala
- hail/src/main/scala/is/hail/expr/ir/agg/PrevNonNullAggregator.scala
- hail/src/main/scala/is/hail/expr/ir/agg/StagedArrayBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/agg/TakeByAggregator.scala
- hail/src/main/scala/is/hail/utils/richUtils/RichCodeRegion.scala
- hail/src/test/scala/is/hail/annotations/StagedRegionValueSuite.scala
- hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
- hail/src/test/scala/is/hail/expr/ir/TakeByAggregatorSuite.scala
Spicy meatball. This will be hard to review, and I realize that. I've included quite comprehensive tests to help make that easier.
> [hail] Move TakeBy to aggregators2

- notebook/scale_test.py
I added a newline because pylint wants two blank lines between functions.
The diff sucks, but all I did was add a finally that ensures we GET `/new` which destroys the associated pod and service in k8s.
> [notebook] clean up after a scale test

- hail/src/main/scala/is/hail/expr/ir/agg/CollectAggregator.scala
- hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
- hail/src/main/scala/is/hail/expr/ir/agg/StagedBlockLinkedList.scala
- hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
- hail/src/test/scala/is/hail/expr/ir/agg/StagedBlockLinkedListSuite.scala
implements CollectAggregator using the StagedBlockLinkedList from that PR
> [hail] CollectAggregator w/ block linked list

- notebook/images/isia/Dockerfile
> [notebook] update isia image

- hail/python/hail/linalg/blockmatrix.py
- hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/linalg/BlockMatrix.scala
> BlockMatrix.random seed should not always be zero

- benchmark/Dockerfile
- benchmark/Makefile
* don't require HAIL_WHEEL to install
* version doesn't actually mean version benchmarked, so that's now a param
* Fix pip in install target
> [benchmark] Various fixes to makefile

- hail/src/test/scala/is/hail/expr/ir/StagedBTreeSuite.scala
I left a parameter on the StagedBTree implementation to be able to adjust the number of elements a node can hold, but we were never testing this (we currently never use anything except the default).
I'm modifying the BTree test to run on trees of size 2, 3, 5, 6, and 22; 2 is the default, and 22 is the check for when the max number of possible elements doesn't exceed half the size of the node. The others are mainly just to check that both even and odd numbers work correctly for a size that we'd conceivably want to use.
> [hail] add tests for BTree implementation with different maxElements

- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
> fix ArrayScan on empty arrays

- hail/src/main/scala/is/hail/compatibility/LegacyEncodedTypeParser.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
We'll use this to build the back-compatible spec deserializers.
> [hail] Add legacy encoded type parser

- web_common/web_common/styles/main.scss
- web_common/web_common/templates/header.html
FYI @tpoterba you can see this in action in my namespace (for the moment)
@akotlar and I agree this is not ideal, but it is done and better than nothing.  I will continue to play with alternatives and make a PR when I have something better.
Remaining tasks:
- make notebook like non-clickable until ready
- write up test playbook
@akotlar let me know if/when you get tired of these, I'll send them to Dan or Jackie.  Probably good for them to engage with this stuff, too.
> [notebook] Add notebook dropdown menu to workshop admin page for developers

- notebook/test-playbook.txt
FYI @tpoterba
I have a few pending PRs now.  I will run through this when they are all in.  If anything else changes, we should probably do it again a couple days before the workshop and fix issues.
Remaining workshop todo items:
- My error handling is too aggressive and frozen pod (2.B) won't work right now
- Still need to add memory/CPU settings to the workshop
> added notebook/test-playbook.txt

- notebook/create-notebook-tables.sql
- notebook/notebook/notebook.py
- notebook/notebook/templates/workshop-admin.html
- web_common/web_common/templates/header.html
- web_common/web_common/web_common.py
Changes:
- add cpu/memory field to workshops
- simplified workshop login logic a bit: workshops_session is just workshop name, token and guest user id, userdata for workshops is id and workshop, workshop auth decorator verifies workshop is valid to before creating userdata,
- make sure to check active everywhere,
> [notebook] add cpu and memory, code fixes and improvements

- notebook/notebook/notebook.py
Error page was too aggressive: it would delete any pod even if there was just a temporary network hiccup.
Error page means a connection to the notebook failed.  That means the state isn't Ready anymore, it is at most initializing (but maybe the pod is gone).  In that case, probe k8s to figure out the current state, but don't probe the notebook, let /notebook call /wait to poll for the notebook to come back up (or report whatever state is there)
> [notebook] Fix error page

- hail/python/hail/docs/tutorials/04-aggregation.ipynb
- Added examples of compound filters
> [docs] Small additions to Aggregation tutorial

- batch/batch/batch.py
- ci/ci/ci.py
Use set_message in CI and Batch to give users feedback after performing POST operations.
I added set_message while working on notebook.  Any message set will show up at the top of the next page loaded styled according to the message type.
> use set_message in CI, Batch

- hail/python/hail/docs/tutorials-landing.rst
> [docs] Add information about running tutorials locally

- hail/python/hail/expr/expressions/typed_expressions.py
- hail/python/test/hail/expr/test_expr.py
> [hail][feature] Add `window` method to `LocusExpression`

- hail/src/main/scala/is/hail/expr/ir/Emit.scala
This addresses one of your specific comments on #7069 that wasn't actually relevant to that PR. So let's just fix it here, merge it in, and I'll rebase when I fix the other things.
> Don't reuse shapet.value in MakeNDArray

- ci/ci/constants.py
> [hail] update authorized users

- notebook/scale-test.py
Update notebook scale test to reflect new location of workshop service (moved notebook.hail.is/workshop => workshop.hail.is)
Just ran it with 10 notebooks against production and it worked fine.
> [notebook] fix scale test

- hail/src/main/scala/is/hail/annotations/RegionPool.scala
> [hail] Fix region reporting.

- hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
- hail/python/requirements.txt
> [hailctl] Fix cluster creation

- hail/python/scripts/drive_combiner.py
Some members of DSP are starting to try to use this script. Add at least a little bit about what these functions do.
> [combiner] Document combiner driver

- notebook/notebook/notebook.py
As per previous code review.  These are implied because we're querying on a primary key.
> [notebook] add asserts

- hail/python/test/hail/methods/test_impex.py
- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
- hail/src/test/resources/noglgp.vcf
We were not checking if floats or doubles were missing leading to very
confusing results.
> [bugfix][hail] Check for missingness in VCF FORMAT arrays

- ukbb-rg/Dockerfile.browser
- ukbb-rg/Makefile
- ukbb-rg/README
- ukbb-rg/deployment.yaml
switch storage class to ssd for a bit of a speed bump
update to R 3.5+ for file format compat
added README with rough instructions for updating the browser
This is deployed running against updated data from Duncan.
> [ukbb-rg] update ukbb-rg

- hail/src/main/scala/is/hail/expr/ir/BinarySearch.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala
- hail/src/main/scala/is/hail/expr/ir/package.scala
- hail/src/test/scala/is/hail/expr/ir/IntervalSuite.scala
- hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala
> [hail] Introduce better TableFilterIntervals optimization

- batch2/Dockerfile.check
- batch2/Makefile
- batch2/batch/batch.py
- batch2/batch/blocking_to_async.py
- batch2/batch/database.py
- batch2/batch/driver.py
- batch2/batch/google_compute.py
- batch2/batch/google_storage.py
- batch2/batch/instance.py
- batch2/batch/instance_pool.py
- batch2/batch/k8s.py
- batch2/batch/utils.py
- batch2/batch/worker.py
- build.yaml
Added batch2_check step in build, fixed lint errors.
> [batch2] add batch2 check, delint

- auth/create-accounts-pod.yaml
- batch2/Makefile
- batch2/batch/main.py
- batch2/deployment.yaml
Changes:
- created batch2 Hail service account with the correct google permissions
- fixed "make deploy"
- updated UI code to be compatible with latest changes
Hand deployed to verify it is all working.
> [batch2] deploy fixes

- scorecard/scorecard/scorecard.py
> [scorecard] no more C++

- hail/www/index.md
- hail/www/navbar.css
- hail/www/navbar.html
- hail/www/style.css
> [www] workshop callout

- hail/Makefile
I don't know what happened to this
> [hail] add make clean

- notebook/notebook/notebook.py
Don't say the notebook wasn't found if it is there.  Try to connect again if it is ready.
> [notebook] fix notebook error message

- hail/python/hail/experimental/interact.py
Holdover from the initial design of something that could aggregate.
This just forces evaluation in a bad way.
> [hail] Do not cache in interactive describe.

- hail/python/hail/docs/plot.rst
Since we use it in the ashg notebook we should document it
> [plot] documented output_notebook

- hail/python/test/hail/expr/test_ndarrays.py
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/types/physical/PNDArray.scala
This PR adds the ability to index into hail NDArrays (not slicing, just individual elements).
> NDArray Ref

- build.yaml
Fixes https://github.com/hail-is/hail/issues/7166
> deploy_ci depends on deploy_batch

- hail/python/hail/plot/plots.py
* print lambda-GC on the plot
* add p value to hover
Fixes #5567
> [hail] Improvements to qq-plot

- hail/python/hail/docs/_static/rtd_modifications.css
The portions I committed after your initial approval weren't merged. That almost seems like a CI bug.
edit: those additional changes apparently didn't get pushed. This fixes.
This expands on the work that you approved, by adding the remaining sections. There are still only 2 style groups, unfortunately split between 6 classes.
fyi @cseed (styling)
> [www/docs] add classmethods,staticmethod,data,attribute,function,class explicitly

- batch2/batch/driver/driver.py
- batch2/batch/driver/instance.py
- batch2/batch/driver/instance_pool.py
- batch2/batch/utils.py
- batch2/batch/worker.py
- batch2/create-batch-tables.sql
Fixes a problem where floating point number imprecision was causing new instances to be created even though the number of ready cores should have been 0.
> [batch2] fix cores calculation

- hail/python/requirements.txt
In response to #7299. It would be nice to get to a more automated way of doing this, but for now we should just update this assuming it passes all tests.
> Updated pandas to version 0.25 in requirements

- auth/deployment.yaml
- batch/deployment.yaml
- batch2/batch/front_end/front_end.py
- batch2/deployment.yaml
- ci/deployment.yaml
- monitoring/monitoring.yaml
- router-resolver/deployment.yaml
- router/deployment.yaml
- scorecard/deployment.yaml
- vdc/priority-classes.yaml
Copy pattern from other services: tolerate preemptibles, min 3 replicas, auto-scale up to 10.
> [batch2] autoscale front-end deployment

- batch2/Dockerfile.worker
- batch2/batch/driver/instance_pool.py
- batch2/run-worker.sh
- build.yaml
This is for debugging only right now!
> [batch2] fix worker logs not being uploaded

- notebook/notebook/notebook.py
Subtle type bug!  `userdata['id']` for normal users is an integer (coming from the users.user_data table). Guest users in workshop get a string user_id:
> user_id = secrets.token_hex(16)
`get_user_notebook` makes the following query:
> execute('SELECT * FROM notebooks WHERE user_id = %s;', user_id)
`notebooks.user_id` is a string (varchar).  MySQL `string = int` works by converting the string to an integer, and a if the string has a number prefix like `72af...` it is converted to 72.  So although notebooks.user_id is a primary key (and therefore unique column), this query can return multiple values if they have the same integer prefixes!
My solution is to consistently convert `userdata['id']` to a string inside notebook.
> [notebook] make user_id a string everywhere

- hail/python/hailtop/batch_client/validate.py
on pod not container
Scheduling will be a bit messed up until this goes in (I had deployed to hopefully speed up the testing).
> fix toleration when building pod spec

- batch/deployment.yaml
- batch2/deployment.yaml
- hail/python/hailtop/batch_client/validate.py
job_spec_to_k8s_pod_spec is used in batch and batch2.front_end.
> [batch+] reduce job default memory in tests

- hail/python/test/hail/table/test_table.py
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
> [hail][bugfix] Fix TableHead prune behavior w.r.t keys

- hail/python/hail/docs/experimental/index.rst
- hail/python/hail/docs/experimental/ldscsim.rst
- hail/python/hail/docs/experimental/vcf_combiner.rst
- hail/python/hail/docs/methods/impex.rst
- hail/python/hail/docs/methods/index.rst
- hail/python/hail/experimental/vcf_combiner.py
- hail/python/hail/methods/impex.py
Still needs work, but it's something.
> [hail][combiner] expose vcf_combiner documentation

- router/deployment.yaml
Add missing batch2-driver to router-services
> add batch2-driver to router services

- hail/python/hail/expr/aggregators/aggregators.py
Look at the current docs, code is not rendered correctly. 
Fixes #7345
> [docs] Fix approx_quantiles docs

- ci/ci/build.py
- gear/gear/logging.py
FYI @cseed 
I tested this locally, but we may have to merge it and see if it works.
> [ci] Format logs in a readable format

- benchmark/python/benchmark_hail/run/cli.py
- benchmark/python/benchmark_hail/run/table_benchmarks.py
- benchmark/python/benchmark_hail/run/utils.py
- hail/src/main/scala/is/hail/annotations/Region.scala
- hail/src/main/scala/is/hail/annotations/RegionPool.scala
- hail/src/main/scala/is/hail/expr/ir/agg/AppendOnlyBTree.scala
- hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala
- hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
- hail/src/main/scala/is/hail/expr/ir/agg/StagedArrayBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/agg/TakeAggregator.scala
- hail/src/main/scala/is/hail/expr/ir/agg/TakeByAggregator.scala
- hail/src/main/scala/is/hail/expr/types/encoded/EArray.scala
- hail/src/main/scala/is/hail/expr/types/encoded/EBaseStruct.scala
- hail/src/main/scala/is/hail/expr/types/encoded/EType.scala
- hail/src/main/scala/is/hail/expr/types/physical/PStruct.scala
- hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
- hail/src/test/scala/is/hail/expr/ir/agg/DownsampleSuite.scala
I need to write another scala test, but it's working as expected in
large test cases in benchmarks.
```
table_aggregate_downsample_worst_case      57.8%    57.617    33.278
table_aggregate_downsample_dense      30.0%   127.079    38.119
Geometric mean: 41.6%
Simple mean: 43.9%
Median:  43.9%
```
> [hail] Implement staged downsample aggregator

- batch2/batch/batch.py
- batch2/batch/database.py
- batch2/batch/driver/driver.py
- batch2/batch/driver/k8s.py
- batch2/batch/driver/main.py
- batch2/batch/front_end/front_end.py
- batch2/batch/google_storage.py
- batch2/batch/log_store.py
- batch2/batch/worker.py
- batch2/create-batch-tables.sql
- batch2/test/test_batch.py
- hail/python/hailtop/utils/utils.py
- pylintrc
Apologies for the size, this PR got a bit out of hand.  Let me know if you want me to try to break it up.
Changes:
- Use custom status for pods, stored in pod and job tables as json.  See Pod.status and Container.status in worker.py for the format.  Example at the end.  Note, "container_statuses" items have a field "container_status", because container is used in two ways: as a substep of a pod/job, and as docker container.  My last renaming proposal got shot down, but we clearly need to improve this in a later PR.
- Heavily reworked worker.py.  I believe this fixes https://github.com/hail-is/hail/issues/7350.  The main design idea is to having all state creation and cleanup in Pod.run and Container.run.
- worker: Just support pods/status and pods/log, not container level status or logs. …
> [batch2] custom status

- hail/python/hail/docs/tutorials/05-filter-annotate.ipynb
Problem introduced in my last PR.
> [docs] Fixing header level of Global Fields in F&A tutorial.

- hail/Makefile
It was dumb luck that this worked. Oops.
> [hail][bugfix] tr accepts ranges, not regexes

- hail/python/hail/utils/misc.py
- hail/python/test/hail/matrixtable/test_matrix_table.py
It's all in the title.
Resolves #7243
> [hail] allow empty range matrix table

- hail/python/hail/utils/misc.py
- hail/python/test/hail/table/test_table.py
> [hail] allow empty range_table

- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/utils/__init__.py
- hail/python/hailtop/utils/utils.py
> [hailtop] Added gather and modified AsyncWorkerPool

- hail/python/test/hail/expr/test_ndarrays.py
- hail/src/main/scala/is/hail/asm4s/Code.scala
- hail/src/main/scala/is/hail/expr/AnnotationImpex.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/main/scala/is/hail/expr/types/physical/PFloat32.scala
- hail/src/main/scala/is/hail/expr/types/physical/PFloat64.scala
- hail/src/main/scala/is/hail/expr/types/physical/PInt32.scala
- hail/src/main/scala/is/hail/expr/types/physical/PInt64.scala
- hail/src/main/scala/is/hail/expr/types/physical/PIntegral.scala
- hail/src/main/scala/is/hail/expr/types/physical/PNDArray.scala
- hail/src/main/scala/is/hail/expr/types/physical/PNumeric.scala
This PR introduces matrix multiplication to `NDArrayNumericExpression`s.
> NDArray Matmul

- ci/ci/build.py
> [ci] tweak wait commands for Service using a StatefulSet

- hail/python/hail/matrixtable.py
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
> [hail][bugfix] Fix column key pruning in MatrixMapCols

- ci/ci/build.py
- ci/wait-for.py
> [ci] allow custom endpoint for wait-for.py instead of always using /healthcheck

- ci/ci/build.py
- ci/wait-for.py
> [ci] allow wait to specify custom request headers

- monitoring/monitoring.yaml
- monitoring/router.yaml
- router/deployment.yaml
- add priority class infrastructure throughout
- all pod specs have resource requests and limits
- make es tolerate preemptibles
- make monitoring router tolerate preemptibles
Deployed.
> [monitoring] Monitoring resource tweaks

- scheduler/executors.yaml
Trying to minimize stuff that requires non-preemptibles.
> [scheduler] Preemptible executors

- blog/deployment.yaml
- image-fetcher/deployment.yaml
- notebook/deployment.yaml
Straightforward as notebook is stateless.
Also, add resource limits on blog and reduce memory (it is currently using 87Mi).
> [notebook, blog] schedule notebook on preemptibles

- batch2/batch/batch.py
- batch2/batch/driver/instance.py
- batch2/batch/driver/instance_pool.py
- batch2/batch/driver/main.py
- batch2/create-batch-tables.sql
Changes:
- Added back instance monitoring loop.  Don't track instance health yet.
- Added time_created and last_updated to instances table in UNIX time.
Add to last of things to rename: Instance => Worker.  Instance is a GCE instance.  Worker is a process running on a instance that executes jobs.
> [batch2] added instance monitoring loop

- batch2/batch/driver/instance_pool.py
- batch2/batch/worker.py
> [batch2] fix batch2 cleanup, copy worker logs

- hail/python/hail/expr/expressions/typed_expressions.py
- hail/python/test/hail/expr/test_ndarrays.py
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
Fixes #7221. Pretty minimal changes, a lot of them are just renames
> NDArrayEmitter carries throught missingness Information

- hail/python/dev-requirements.txt
- hail/python/hail/docs/_static/goto.js
- hail/python/hail/docs/_templates/layout.html
- hail/python/hail/docs/conf.py
Implements Katex. Changes to goto.js (and its position on the page) has to do with Firefox's apparently broken history.scrollRestoration = 'manual' handling on page refresh (in that it still automatically restores scroll position).
Tested in Chrome, Firefox (latest), Safari 13.0.1, Microsoft Edge (Mac Beta 78.0.276.20). Edge should mostly behave like Chrome, runs now on Chromium.
> [www/docs] katex

- hail/src/main/scala/is/hail/backend/LowerTableIR.scala
- hail/src/main/scala/is/hail/backend/local/LowerTableIR.scala
- hail/src/main/scala/is/hail/expr/ir/Compile.scala
- hail/src/main/scala/is/hail/expr/ir/CompileAndEvaluate.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/FoldConstants.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/Optimize.scala
- hail/src/test/scala/is/hail/expr/ir/FoldConstantsSuite.scala
> [hail] Remove logic preventing literal generation in FoldConstants

- auth/create-accounts-pod.yaml
- build.yaml
- ci/Dockerfile.test
- ci/ci-agent-role.yaml
- ci/ci-agent-sa.yaml
- ci/ci/build.py
- ci/ci/environment.py
- ci/ci/templates/batch.html
- ci/ci/templates/batches.html
- ci/ci/templates/index.html
- ci/ci/templates/pr.html
- ci/deployment.yaml
- ci/test-ci-pod.yaml
- ci/test/resources/Dockerfile
- ci/test/resources/build.yaml
- ci/test/resources/deployment.yaml
- ci/test/resources/hello.py
- ci/test/test_ci.py
The last test for making sure PRs get merged is still a work in progress.
> [ci] Add tests for CI

- hail/src/main/scala/is/hail/expr/ir/Exists.scala
- hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala
I believe this will solve a bug Alicia is hitting, but I am having
trouble replicating it without the ability to run her pipeline.
> [hail] Strengthen containsAgg and containsScan.

- hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
Includes auto-minimization on job completion.
> [hailctl] Update to latest spark monitor

- ci/Makefile
- ci/ci/build.py
- ci/ci/environment.py
- ci/deployment.yaml
> [ci] Add kubernetes server url to global variables

- build.yaml
Set secrets namespace in runImage steps.
> [build.yaml] fix batch2 secrets part 2

- batch2/batch/driver/instance_pool.py
Also add explicit asserts at the top of adjust_for_{add, remove}.  We got it for free for remove (since .remove throws if missing) but for add.
> [batch2] fix negative n_deleted issue

- auth/deployment.yaml
- batch2/deployment.yaml
- build.yaml
- gateway/deployment.yaml
- internal-gateway/deployment.yaml
- notebook/deployment.yaml
- router-resolver/deployment.yaml
- router/deployment.yaml
- site/deployment.yaml
preemptible no affinity for preemptible pods
fix empty scopes yaml
> deploy fixes

- ci/ci/templates/job_log.html
I forgot to switch this in PR #7488
> [ci] fix logs ui page

- hail/python/test/hail/table/test_table.py
This is currently too slow (110s!) to be a part of CI.
We can bump it back up when we've made things faster.
> [hail] Reduce max scale test width

- batch2/batch/batch.py
- batch2/batch/worker.py
> [batch2] add start, finish time to worker timing

- letsencrypt/Makefile
- letsencrypt/domains.txt
- letsencrypt/run-letsencrypt.sh
And explicitly specify default namespace.
> [batch2] add batch2-driver to letsencrypt

- hail/src/main/scala/is/hail/HailContext.scala
- hail/src/main/scala/is/hail/sparkextras/IndexReadRDD.scala
Try to not serialize partFile or interval arrays to the workers.
> [hail] Add IndexReadRDD class

- hail/python/hail/expr/aggregators/aggregators.py
- hail/python/test/hail/expr/test_expr.py
- hail/src/main/scala/is/hail/annotations/aggregators/RegionValueApproxCDFAggregator.scala
- hail/src/main/scala/is/hail/expr/ir/AggOp.scala
- hail/src/test/scala/is/hail/annotations/ApproxCDFAggregatorSuite.scala
This makes staging much easier.
> [hail] Support only doubles in ApproxCDFCombiner.

- batch2/Dockerfile.test
- batch2/batch/front_end/front_end.py
- batch2/batch/worker.py
- batch2/test/test_batch.py
- batch2/test/test_dag.py
- hail/python/hailtop/batch_client/aioclient.py
Stacked on: https://github.com/hail-is/hail/pull/7530
> [batch2] only run input or output if needed

- benchmark/python/benchmark_hail/run/cli.py
- benchmark/python/benchmark_hail/run/linalg_benchmarks.py
- benchmark/python/benchmark_hail/run/matrix_table_benchmarks.py
- benchmark/python/benchmark_hail/run/methods_benchmarks.py
- benchmark/python/benchmark_hail/run/resources.py
- benchmark/python/benchmark_hail/run/shuffle_benchmarks.py
- benchmark/python/benchmark_hail/run/table_benchmarks.py
- benchmark/python/benchmark_hail/run/utils.py
Big diff but almost all mechanical. Take a look at the `resources.py` to comment on design, though, please!
next step is using this to build better batch structures that transmit only necessary data, not a huge tar of all resources all the time.
> [benchmark] Add resource groups to benchmarks.

- hail/src/main/scala/is/hail/HailContext.scala
- hail/src/main/scala/is/hail/backend/Backend.scala
- hail/src/main/scala/is/hail/expr/ir/Compile.scala
- hail/src/main/scala/is/hail/expr/ir/CompileAndEvaluate.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/Optimize.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
- hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPipeline.scala
- hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala
- hail/src/main/scala/is/hail/utils/Graph.scala
- hail/src/test/scala/is/hail/TestUtils.scala
- hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
> [hail] Thread ExecuteContext through Compile

- hail/src/main/scala/is/hail/io/fs/HadoopFS.scala
cc @konradjk 
Say that ten times fast
> [hail] Log globs

- ci/ci/build.py
Expand the namespace in runImage step service account so we can use valueFrom (in fact, so we must use valueFrom).
> [ci] expand service account namespace

- hail/python/hail/__init__.py
- hail/python/hail/context.py
e.g.
```
In [3]: hl.version()                                                                                                                                                                                                
Out[3]: '0.2.27-6c82057ece64'
```
cc: @tpoterba since you're the pyczar
> [hail] hl.version()

- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
- hail/src/main/scala/is/hail/utils/SemanticVersion.scala
> [hail][bugfix] Don't push down intervals into old files

- benchmark/python/benchmark_hail/create_resources/create_resources.py
- benchmark/python/benchmark_hail/run/resources.py
- benchmark/python/benchmark_hail/run/utils.py
Also allow incremental file creation.
Necessary for forthcoming work that reconfigures the dependency structure of the pipeline benchmarks.
> [benchmark] Restructure benchmark resources directory

- hail/python/hail/docs/change_log.md
CC @tpoterba 
I don't know how to explain what was going on with those two bugs. I wasn't involved in fixing them and the descriptions of the problems on the PRs are unclear / nonexistent.
> Release Change log 0.2.28

- hail/Makefile
> 0.2.28 Release Change patch number

- hail/src/main/scala/is/hail/expr/ir/Compile.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/ExtractAggregators.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/Optimize.scala
- hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
- hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPipeline.scala
> [hail] All calls to optimize are tracked with ExecuteContext

- batch2/batch/worker.py
- hail/python/hailtop/utils/utils.py
- pylintrc
Once jobs are delisted, the worker will quit after the max idle time.
> [batch2] delist jobs after 3m or half run duration

- hail/src/main/scala/is/hail/annotations/CodeOrdering.scala
- hail/src/main/scala/is/hail/expr/ir/AbstractMatrixTableSpec.scala
- hail/src/main/scala/is/hail/expr/ir/AbstractTableSpec.scala
- hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/expr/ir/TableValue.scala
- hail/src/main/scala/is/hail/expr/types/physical/PBaseStruct.scala
- hail/src/main/scala/is/hail/expr/types/physical/PStruct.scala
- hail/src/main/scala/is/hail/expr/types/physical/PTuple.scala
- hail/src/main/scala/is/hail/expr/types/physical/PType.scala
- hail/src/main/scala/is/hail/table/package.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
- hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala
> [hail] Rename `Table.scala` and move into `is.hail.expr.ir`

- hail/python/test/hail/experimental/test_experimental.py
- hail/src/main/scala/is/hail/linalg/BlockMatrix.scala
Just let the user give it whatever extension.
> Don't madate tsv when specifying custom names

- batch2/batch/batch.py
- batch2/batch/driver/instance.py
- batch2/batch/driver/instance_pool.py
- batch2/batch/driver/main.py
- batch2/batch/driver/scheduler.py
- batch2/batch/front_end/front_end.py
- batch2/batch/front_end/templates/batch.html
- batch2/batch/front_end/templates/batches.html
- batch2/batch/globals.py
- batch2/batch/google_compute.py
- batch2/batch/utils.py
- batch2/batch/worker.py
- batch2/create-batch-tables.sql
- batch2/delete-batch-tables.sql
- batch2/test/test_dag.py
I added the columns to the batches table for the real-time cost estimate even though that will be v2 to avoid having to reset the database twice. Although, we may need to do that anyways so the fields are properly interpreted.
> [batch2] billing v1

- batch2/Makefile
add missing project and zone to globals
> [batch2] fix deploy

- build.yaml
- ci/Dockerfile.test
- ci/ci/build.py
- ci/ci/ci.py
- ci/ci/environment.py
- ci/ci/github.py
- ci/deployment.yaml
- ci/test/resources/build.yaml
- ci/test/resources/deployment.yaml
- ci/test/test_ci.py
- gear/gear/auth_utils.py
Permit the Dockerfile to be specified inline:
```yaml
- kind: buildImage
name: inline_image
dockerFile:
inline: |
FROM ubuntu:18.04
RUN apt-get update && apt-get install git
contextPath: .
```
> [ci] inline docker images

- ci/ci/ci.py
- ci/ci/templates/pr.html
- hail/python/hailtop/utils/utils.py
> [ci] add cost to pr page

- hail/src/main/scala/is/hail/asm4s/Code.scala
- hail/src/test/scala/is/hail/annotations/CodeSuite.scala
- hail/src/test/scala/is/hail/asm4s/CodeSuite.scala
Happy to hear suggestions as to better ways to do this, but I've made too many emitter typos with while loops. I keep either doing something like
```
i := 0,
j := 0,
Code.whileLoop(i < M,
Code.whileLoop(j < N, 
???,
j := j + 1
)
i := i + 1
)
```
(j should be inside the outer whileLoop),
forgetting one of the increments, or forgetting to set the variables to 0 at the beginning. `Code.forLoop` is to force me to include all parts.
> Added Code.forLoop

- batch2/batch/driver/scheduler.py
I saw a case where this loop was spinning generating $$$ logs.
> [batch2] back off in scheduler loop

- batch2/batch/front_end/front_end.py
- hail/python/hailtop/batch_client/aioclient.py
Sorry, code movement made the diff a bit messy.  Basically: support the same search and pagination interface in the batch/jobs API endpoint as we do now in the batch UI page.
> [batch2] batch jobs api supports queries and pagination

- batch2/batch/batch.py
- batch2/batch/front_end/front_end.py
- batch2/batch/front_end/templates/batches.html
- batch2/test/test_batch.py
- ci/ci/ci.py
- ci/ci/github.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/batch_client/client.py
- hail/python/hailtop/pipeline/backend.py
- hail/python/hailtop/utils/utils.py
For attributes, same as /jobs, and state queries: open, closed, running, success, failure, cancelled, and complete.
Also added an `open` batch state.
> [batch2] query and pagination in /batches

- batch2/batch/driver/scheduler.py
- batch2/batch/front_end/front_end.py
- batch2/create-batch-tables.sql
- batch2/delete-batch-tables.sql
@cseed I had this branch almost finished when I saw your design document. This should be fairly similar to what you proposed. I'm sure the SQL queries need to be fixed. Let me know how you want to proceed.
> [batch2] Fair share scheduler prototype

- Makefile
- batch2/Dockerfile.tables
- batch2/batch/front_end/front_end.py
- batch2/batch/front_end/schemas.py
- batch2/create-batch-tables-pod.yaml
- batch2/create-batch-tables.sql
- batch2/create-billing-projects.sql
- batch2/delete-batch-tables.sql
- batch2/test/test_aioclient.py
- batch2/test/test_batch.py
- batch2/test/test_dag.py
- batch2/test/test_scale.py
- ci/ci/ci.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/batch_client/client.py
- hail/python/hailtop/hailctl/batch/cli.py
- hail/python/hailtop/pipeline/backend.py
- pipeline/test/test_pipeline.py
Add billing projects.  Billing projects are validated once in /batches/create.
> [batch2] add billing project

- batch2/batch/worker.py
I thought this was the simplest way of solving this. I could also have checked the container name in Container.run and selected the right semaphore there.
> [batch2] use null semaphore for input, output steps

- batch2/deployment.yaml
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
> [batch2] recreate deployment

- hail/python/hail/methods/qc.py
- hail/python/test/hail/experimental/test_experimental.py
- hail/python/test/hail/methods/test_qc.py
> [hail][bugfix] Fix bug in correctness of n_discordant

- hail/python/hail/methods/impex.py
`Height` and `Age` were the examples from `import_table`
> Fixed import_matrix_table docs 

- ci/ci/ci.py
- ci/ci/templates/pr.html
Make things a little easier if you've got a few PRs going.
> [ci] add the pr title to the pr page header

- ci/ci/ci.py
Recent jobs change introduced a bug in CI.
> [ci] fix incorrect jobs reference

- ci/test/test_ci.py
- docker/Dockerfile.base
> Add liblapack3 to base image

- hail/python/hail/docs/data/table_with_json.tsv
- hail/python/hail/methods/impex.py
> Add an example of importing a table with JSON entries

- batch/batch/driver/main.py
- batch/batch/driver/scheduler.py
- batch/batch/driver/templates/user_resources.html
- batch/create-batch-tables.sql
- batch2/batch/driver/templates/user_resources.html
- web_common/web_common/templates/header.html
I also fixed the user_resources index. Not sure if I should wait to put that in for another PR. If you have a database change PR, maybe you can add it to that?
> [batch2] add user resources ui page

- ci/create_database.py
Unfortunately this is hard to test in the current setup because the tests never get the root config file (which has no database set).
> sql migrations using the wrong config file

- ci/create_database.py
One more feature I needed to switch to migrations.
> [ci] make scope available to migrations

- batch/batch/driver/scheduler.py
> [batch] fix scheduler error if allocated_cores not found

- hail/python/hail/expr/__init__.py
- hail/python/hail/expr/functions.py
- hail/python/hail/ir/register_functions.py
- hail/python/hail/table.py
- hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TArray.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TBaseStruct.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TDict.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TFloat32.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TFloat64.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TSet.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TString.scala
- hail/src/main/scala/is/hail/expr/types/virtual/Type.scala
This *should*, in conjunction with #7720 and #7719, fix #7638.
> [hail] register scala function for Table.show

- hail/build.sbt
#7506 left build.sbt behind again, this fixes it
> [hail] update htsjdk version in build.sbt

- hail/src/main/scala/is/hail/expr/ir/Exists.scala
> [hail] Remove unused Extract object.

- hail/Makefile
- hail/python/hail/docs/change_log.md
Change log for release 0.2.29. Currently I have the date set for tomorrow since i didn't know if it would make it in today. Could always change it.
> Release 0.2.29

- hail/src/main/scala/is/hail/expr/ir/AggOp.scala
- hail/src/main/scala/is/hail/expr/ir/Compile.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/IRBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
- hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
- hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
- hail/src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala
- hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
- hail/src/test/scala/is/hail/expr/ir/ForwardLetsSuite.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
- hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala
- hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/TestUtils.scala
Stacked on #7697
Sorry to assign you to all of these, but the context should mean that the most recent 3-4 PRs should be reviewable in under 60 seconds.
> [hail] Rename AggSignature2 => AggSignature

- hail/src/main/scala/is/hail/annotations/UnsafeRow.scala
- hail/src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala
- hail/src/main/scala/is/hail/expr/types/physical/PCanonicalLocus.scala
- hail/src/main/scala/is/hail/expr/types/physical/PLocus.scala
> [hail/ptypes] PLocus: add contigType, positionType

- hail/src/main/scala/is/hail/expr/ir/IR.scala
Could be recomputed many times!
> [hail] make IR.size a lazy val.

- batch/batch/front_end/front_end.py
> [batch] fix message

- hail/python/hail/experimental/loop.py
- hail/python/test/hail/experimental/test_experimental.py
- hail/src/main/scala/is/hail/expr/ir/InTailPosition.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
> [hail] calling recur from tail position in nested loop is allowed

- benchmark/python/benchmark_hail/run/matrix_table_benchmarks.py
- hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
They were quadratic. Bad bad bad bad bad.
Benchmark now takes ~7s, compared to roughly the amount of time it
would take for my laptop to naturally sublimate.
> [hail] Fix EXTREME performance regression in column scans.

- hail/Makefile
- hail/python/hail/docs/change_log.md
> Release 0.2.30

- hail/python/hail/ir/ir.py
- hail/python/test/hail/experimental/test_experimental.py
- hail/python/test/hail/expr/test_expr.py
- hail/python/test/hail/test_ir.py
- hail/src/main/scala/is/hail/expr/ir/Binds.scala
- hail/src/main/scala/is/hail/expr/ir/Children.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/InferPType.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/MathFunctionsSuite.scala
Moved the relevant Scala tests into python.
> [hail] remove (unused) Uniroot IR node

- batch/batch/front_end/front_end.py
- batch/batch/front_end/templates/billing_projects.html
- batch/batch/worker.py
- web_common/web_common/templates/header.html
Added simple UI for billing projects, create, add and remove users.  Hand-tested with dev deploy.
> [batch] billing project ui

- batch/batch/worker.py
- batch/test/test_batch.py
- ci/ci/build.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/batch_client/client.py
- hail/python/hailtop/batch_client/validate.py
This is for the batch callback test, so I can make test_batch a direct pod.
> [batch] allow jobs to request a port

- auth/Makefile
- ci/Makefile
Some of the templating in the Makefiles were out of date.
> [auth, ci] fix deploys

- build.yaml
- ci/ci/build.py
If the yaml sets the step to `runIfRequired: true`, this change should only run the step if specifically asked for when dev deploying.
> [ci] Add runIfRequested option

- hail/python/hail/methods/statgen.py
> [hail] fix pruning in `hl.skat` by using select instead of annotate

- hail/src/main/scala/is/hail/expr/ir/InferPType.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
As discussed before, I believe we need a deep union of the branches, and will leave upcasting to Emit. Once this and the copy PR go in I will implement the necessary changes to the emitter.
Related to: https://github.com/hail-is/hail/issues/6952
> [hail/ptypes] infer If node

- hail/python/test/hail/table/test_table.py
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
> [hail] Push TableIntervalJoin into both sides of a TableJoin

- hail/python/hail/docs/getting_started.rst
> [hail] Fix Docs

- hail/src/main/scala/is/hail/utils/TextTableReader.scala
Instead print summary.
I am tired of scrolling past the 5k-field table output in the CI test logs.
> [hail] Don't print per-field types for wide tables

- gear/gear/database.py
I couldn't figure out how to consolidate this more.
> [gear] add retry on deadlock errors

- ci/ci/constants.py
- scorecard/scorecard/scorecard.py
> Removing old users

- batch/test/test_batch.py
don't rely on defaults in cost test
> [batch] fix batch tests in deploy

- hail/src/main/scala/is/hail/expr/types/physical/PBaseStruct.scala
Uses the existent Region.setMemory function, and checks requiredeness before setting/clearing missing bits.
> [hail/ptypes] simplify clearMissingBits, setAllMissing

- hail/python/test/hail/expr/test_expr.py
Closes #4922 . I don't really see the problem with having them in two separate test methods though.
> Combining hl agg group_by tests

- batch/batch/front_end/front_end.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/config/deploy_config.py
`client_max_size` was being ignored, I fixed that. I also increased it to 8MB. Increasing further requires changes to routers and gateways, so for now I ignore that.
> [batch] parallelism on insert

- batch/test/test_batch.py
I think this should work. 60 Gi > 60 GB which is what we are using for the amount of memory.
> [batch] fix invalid resource test to account for 16 core machines

- batch/batch/batch.py
- batch/batch/driver/instance_pool.py
- batch/batch/driver/k8s_cache.py
- batch/batch/driver/main.py
- batch/sql/delete-batch-tables.sql
- hail/python/hailtop/utils/__init__.py
- hail/python/hailtop/utils/utils.py
> [batch] Add k8s secret/sa cache and retry transient errors

- build.yaml
Preparing to remove createDatabase(1).
> [build] test-instance use createDatabase2 step

- hail/python/hailtop/auth/auth.py
- router-resolver/deployment.yaml
- router-resolver/router_resolver/router_resolver.py
which will retry transient errors
router-resolver is part of the infrastructure, so I will hand-deploy once you're happy with this.
> [router-resolver] use async_get_userinfo

- batch/batch/batch.py
- batch/batch/driver/main.py
- batch/batch/front_end/front_end.py
- batch/batch/utils.py
- batch/sql/insert_globals.py
As a sanity check, we've halved the amount of disk per worker. CPU is $0.01 core hour. So 0.003 / 2 = 0.0015
> [batch] update billing cost with 100 GB disk, 16 cores

- build.yaml
- ci/ci/build.py
- ci/create_database.py
- ci/test/resources/build.yaml
shutdowns in createDatabase2 is a list of deployments to shut down before applying any migrations.
> [ci] add shutdowns option to createDatabase2 step

- hail/python/hail/experimental/time.py
- hail/python/test/hail/experimental/test_time.py
Add a sentence to strptime docs to explain useful information about rounding. Add a test with negative timestamp.
> Updated time docs with recommendation for strptime

- dbuf/Makefile
> [dbuf] fix dbuf makefile

- hail/src/main/scala/is/hail/expr/ir/InferPType.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
Matching the If node inference, as described and requested here: https://github.com/hail-is/hail/pull/6912/files#r317671912
> [hail/ptypes] Die should perform deepInnerRequired

- hail/src/main/scala/is/hail/expr/ir/AggOp.scala
- hail/src/main/scala/is/hail/expr/ir/Compile.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/IRBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/Simplify.scala
- hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala
- hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
- hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
Stacked on #7698
This is the last stacked PR I'm assigning to you this week, I promise!
> [hail] Introduce proper ptype management to aggregators

- hail/src/main/scala/is/hail/expr/ir/InferPType.scala
- hail/src/main/scala/is/hail/expr/types/virtual/Type.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
> [hail/ptypes] infer Coalesce PType

- hail/python/hail/expr/types.py
- hail/python/test/hail/expr/test_ndarrays.py
- hail/src/main/scala/is/hail/asm4s/Code.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/linalg/BLAS.scala
- hail/src/main/scala/is/hail/linalg/LAPACK.scala
- hail/src/main/scala/is/hail/linalg/LinalgCodeUtils.scala
- hail/src/main/scala/is/hail/utils/TryAll.scala
This PR adds an optimization where a two dimensional matrix multiply of matrices containing float32 or float64s will be performed by SGEMM or DGEMM respectively. In the future, we should use this during tensor multiplies as well.
> DGEMM and SGEMM

- batch/batch/driver/main.py
- batch/batch/front_end/front_end.py
- batch/batch/globals.py
- batch/batch/worker.py
- batch/test/test_batch.py
> [batch] fix client max size

- benchmark/python/benchmark_hail/cli.py
- benchmark/python/benchmark_hail/compare/compare.py
- benchmark/python/benchmark_hail/run/methods_benchmarks.py
- benchmark/python/benchmark_hail/run/resources.py
- benchmark/python/benchmark_hail/run/utils.py
- benchmark/python/benchmark_hail/summarize/summarize.py
- benchmark/scripts/benchmark_in_pipeline.py
one more I had been using before break but forgot to PR...
> [benchmark] Fix errors in running and analyzing benchmarks

- build.yaml
- ci/test/resources/build.yaml
Everywhere isn't very many places.
> [build] createDatabase2 => createDatabase everywhere

- batch/batch/driver/scheduler.py
- run cancels in parallel with scheduling
- handle errors asap rather than serially after all jobs have finished
> [batch] parallel cancel

- hail/src/main/scala/is/hail/expr/ir/Children.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
Currently unused in main control flow, need to figure out how to fit
it in.
> [hail] Add RunAgg IR node

- batch/batch/front_end/front_end.py
- batch/batch/front_end/templates/batches.html
> [batch] add delete button to ui

- hail/src/main/scala/is/hail/expr/types/virtual/TArray.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TBaseStruct.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TBinary.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TBoolean.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TCall.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TContainer.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TDict.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TFloat32.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TFloat64.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TFunction.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TInt32.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TInt64.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TInterval.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TIterable.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TLocus.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TNDArray.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TSet.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TStream.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TString.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TStruct.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TTuple.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TUnion.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TVariable.scala
- hail/src/main/scala/is/hail/expr/types/virtual/TVoid.scala
- hail/src/main/scala/is/hail/expr/types/virtual/Type.scala
- hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
> [hail] Remove Type.physicalType (!)

- batch/batch/front_end/front_end.py
- gear/gear/__init__.py
- gear/gear/database.py
cc: @cseed 
It's not the nicest thing, but it's OK. I only updated `front_end.py`. If y'all like this solution, I can go carefully fix up the rest, but you gotta be careful with this about global state.
> [gear][batch] Retry-able Transactions

- build.yaml
- ci/ci/build.py
- ci/ci/github.py
- ci/ci/globals.py
- ci/deployment.yaml
- ci/sql/delete-ci-tables.sql
- docker/requirements.txt
Also added `delete_ci_tables`.
> [ci] add zulip notification of failed deploy state

- batch/batch/driver/main.py
- batch/batch/driver/scheduler.py
- batch/batch/front_end/front_end.py
- hail/python/hailtop/utils/__init__.py
- hail/python/hailtop/utils/utils.py
This should put the issue of non-responsive cancels to rest.
> [batch] fix user cancel/delete request blocking if driver down

- batch/batch/front_end/front_end.py
- batch/batch/front_end/templates/job.html
We should probably include the attempts in the REST API endpoint, too.  I'll leave that for a TODO.
> [batch] include attempts in job UI page

- batch/batch/front_end/front_end.py
Minor, I know, but it pains me and I can't help myself.
> [batch] minimize transaction size in front_end

- hail/src/main/scala/is/hail/expr/ir/functions/RandomSeededFunctions.scala
god this was so fucking slow
(it boxes)
> [hail] no scala allowed

- hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/Children.scala
- hail/src/main/scala/is/hail/expr/ir/Copy.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/Exists.scala
- hail/src/main/scala/is/hail/expr/ir/IR.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
- hail/src/main/scala/is/hail/expr/ir/Parser.scala
- hail/src/main/scala/is/hail/expr/ir/Pretty.scala
- hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
- hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala
- hail/src/main/scala/is/hail/io/InputBuffers.scala
- hail/src/main/scala/is/hail/io/MemoryBuffer.scala
- hail/src/main/scala/is/hail/io/OutputBuffers.scala
- hail/src/main/scala/is/hail/utils/MemoryBufferWrapper.scala
- hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
> [hail] Add CombOpValue and AggStateValue nodes for agg lowering

- hail/python/hailtop/hailctl/batch/list_batches.py
Tested on my laptop, works now.
> [batch] fix hailctl batch list 

- hail/python/hailtop/pipeline/task.py
Not sure if you wanted to change the name or anything, but I presume this is the interface you were thinking?
> [pipeline] adding Task.always_run

- hail/python/hail/methods/qc.py
- hail/python/test/hail/methods/test_qc.py
> [hail][bugfix] Fix divide by zero error in `hl.concordance`

- batch/batch/batch.py
- batch/test/conftest.py
- build.yaml
- hail/python/hailtop/batch_client/aioclient.py
Also increase the logging in the batch tests: set the log format, log when tests start/end.
> [batch] fix cancellation notification error

- ci/ci/ci.py
- ci/ci/templates/batch.html
FYI, I tested this with a deploy.
> [ci] fix: attributes are already stored in the status

- hail/python/hailtop/batch_client/aioclient.py
> [batch] remove stray debugging statements from client

- batch/batch/globals.py
I ran my migration test.  Worked perfectly.  I say this is ready to go.
> [batch] switch to batch format v2

- batch/batch/batch.py
- batch/batch/front_end/front_end.py
- batch/batch/front_end/templates/batch.html
- ci/ci/templates/batch.html
- ci/ci/templates/pr.html
> [batch] add name to job json

- hail/python/hail/docs/tutorials/01-genome-wide-association-study.ipynb
> [docs] Fix broken link to Expression docs in tutorial

- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/expr/ir/TableValue.scala
- hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala
Also refactor BGEN ptype logic.
stacked on #7941
> [hail/ptypes] Delete dead references to `tt.canonicalRVDType`

- batch/batch/front_end/templates/batch.html
- batch/batch/front_end/templates/batches.html
Apologies, should have caught this. I think we can improve the UI testing picture. In particular, would be useful to have a staging area (we may already entirely have this with dev namespace, I would like to have a shared space for the reviewer (and myself) to play with the implementation issued in the PR, maybe a link in CI to the deployed web app?), test data (so we can see the table filled), and a local dev strategy with hot reloading (make a change, script recompiles and reloads your browser).
I also need to be more familiar with developing behind dev namespaces.
Before:
After:
> [batch] table width fix

- hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
> [hail/ptypes] Rework ptype rules in importVCF

- hail/src/main/scala/is/hail/expr/ir/InferPType.scala
Remove unnecessary brackets, add helper function
> [hail/ptypes] Style updates to InferPType

- batch/batch/utils.py
add 0.004/instance-hr external IP cost
add 0.01/core-hr service charge
also reorganized the code a little bit.
Corresponds to ~$0.021704/core-hr for the current setup.
FYI @konradjk
> [batch] update cost calculation

- hail/python/hailtop/hailctl/batch/batch_cli_utils.py
- hail/python/hailtop/hailctl/batch/cli.py
- hail/python/hailtop/hailctl/batch/get.py
- hail/python/hailtop/hailctl/batch/job.py
- hail/python/hailtop/hailctl/batch/log.py
- Rename pod_status to job.
- Fix job to work with new batch.
- Fix get to work with new batch.
- Fix log to work with new batch.
- Unify formatting options across job, get, and log.
> [batch] clean up the batch cli

- hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
- hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
> [hail][bugfix] Fix optimizer bug in PruneDeadFields for MatrixUnionRows

- benchmark/python/benchmark_hail/compare/compare.py
Fix up formatting, add harmonic mean.
> [benchmark] Minor tweaks to `hail-bench compare`

- hail/python/hailtop/utils/utils.py
> [utils] treat 500 as a transient error

- gateway/Makefile
Someone changed this at one point and did not update the makefile.
cc: @cseed
> [gateway] fix Makefile for new static IP

- pipeline/test/test_pipeline.py
Tests scale of commands, to some degree.
> [pipeline] Add test that looks like benchmark workflow.

- internal-gateway/service.yaml
See https://github.com/hail-is/hail/pull/8045.
> [internal-gateway] preserve source IPs

- hail/src/main/scala/is/hail/expr/ir/Compile.scala
> [hail] Add back InferPTypes to Compile

- benchmark/python/benchmark_hail/run/methods_benchmarks.py
- benchmark/python/benchmark_hail/run/resources.py
- benchmark/scripts/benchmark_in_pipeline.py
- hail/python/hail/context.py
We should start tracking the speed of this as we work to replace it with ndarray version.
> Added a benchmark for linear_regression_rows

- site/Dockerfile
- site/Makefile
- site/hail.nginx.conf
- site/nginx.conf
More details at #8058.
- Include the user's IP in the site logs.
- Fix out of date Makefile.
I recognize there's duplication of log format. Abstracting over that doesn't seem *that* valuable and requires putting the shared configuration into a file in the root of hail and then arranging for the shared config file to be in the docker context. It's all kind of annoying and seems low value.
> [site] log user IP

- benchmark/python/benchmark_hail/run/__init__.py
- benchmark/python/benchmark_hail/run/combiner_benchmarks.py
- benchmark/python/benchmark_hail/run/resources.py
Import empty gvcf, duplicate it 10k times, transform it, combine it 100
at a time, and attempt to multi_write the results.
Note: On my local machine this fails with a GC overhead exceeded, it may be too much for hail to handle right now. This should be fast.
> [bench] Add combiner compile benchmark.

- hail/python/hail/experimental/vcf_combiner.py
* Fix a bug in `calculate_new_intervals`, when the default reference does not match
`reference_genome`
* Make positional argument names valid python ids
* Update various argument help
* Add `--log` argument allowing the user to specify the logfile
* If `--overwrite` is not present, check that `out_file` exists
> [combiner] Miscellaneous combiner fixes and doc updates

- hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala
- hail/src/main/scala/is/hail/asm4s/joinpoint/JoinPoint.scala
- hail/src/main/scala/is/hail/asm4s/joinpoint/ParameterPack.scala
- hail/src/main/scala/is/hail/expr/ir/Streamify.scala
- hail/src/main/scala/is/hail/expr/ir/package.scala
- hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
Have a new test to target that will verify correct code generation.
Also refactor parameterpack a bit to be more traceable.
High prio because this is blocking ptypes work.
> [hail/streams] Disable If and NA stream emitters

- auth/Dockerfile
- auth/auth/auth.py
- auth/sql/delete-auth-tables.sql
- batch/batch/driver/main.py
- batch/batch/front_end/front_end.py
- batch/deployment.yaml
- ci/ci/ci.py
- dbuf/dbuf/dbuf.py
- gear/gear/__init__.py
- gear/gear/logging.py
- notebook/notebook/notebook.py
- scorecard/scorecard/scorecard.py
Add AccessLogger which standardizes access logging across our infrastructure and crucially prints the X-Real-IP header.
Also includes a fix for the google auth issue and two missing tables from delete_auth_tables.
> [batch][ci][scorecard][auth][notebook][dbuf] log real ips

- ci/ci/build.py
Addresses this transient error I just encountered.
```
+ docker push gcr.io/hail-vdc/ci-intermediate:tn05m3kr79i2
The push refers to repository [gcr.io/hail-vdc/ci-intermediate]
Get https://gcr.io/v2/: dial tcp: lookup gcr.io: Temporary failure in name resolution
```
> [ci] retry docker pull/push

- hail/src/main/scala/is/hail/annotations/RegionValueBuilder.scala
- hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
- hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/agg/AppendOnlyBTree.scala
- hail/src/main/scala/is/hail/expr/types/encoded/EBaseStruct.scala
- hail/src/main/scala/is/hail/expr/types/physical/ComplexPType.scala
- hail/src/main/scala/is/hail/expr/types/physical/PArrayBackedContainer.scala
- hail/src/main/scala/is/hail/expr/types/physical/PBaseStruct.scala
- hail/src/main/scala/is/hail/expr/types/physical/PCanonicalArray.scala
- hail/src/main/scala/is/hail/expr/types/physical/PCanonicalBaseStruct.scala
- hail/src/main/scala/is/hail/expr/types/physical/PCanonicalBinary.scala
- hail/src/main/scala/is/hail/expr/types/physical/PCanonicalNDArray.scala
- hail/src/main/scala/is/hail/expr/types/physical/PCanonicalString.scala
- hail/src/main/scala/is/hail/expr/types/physical/PCanonicalStruct.scala
- hail/src/main/scala/is/hail/expr/types/physical/PCanonicalTuple.scala
- hail/src/main/scala/is/hail/expr/types/physical/PPrimitive.scala
- hail/src/main/scala/is/hail/expr/types/physical/PStream.scala
- hail/src/main/scala/is/hail/expr/types/physical/PStruct.scala
- hail/src/main/scala/is/hail/expr/types/physical/PTuple.scala
- hail/src/main/scala/is/hail/expr/types/physical/PType.scala
- hail/src/main/scala/is/hail/expr/types/physical/PVoid.scala
- hail/src/test/scala/is/hail/annotations/StagedRegionValueSuite.scala
- hail/src/test/scala/is/hail/annotations/UnsafeSuite.scala
- hail/src/test/scala/is/hail/expr/types/physical/PhysicalTestUtils.scala
This lets RVB copy values of a different type. To do this, I needed to
delete all the logic in RVB and move it to PType. This also was an
opportunity to slightly simplify the existing copy code.
I realize this may be a challenge to review. Happy to walk through any part as necessary.
> [hail/ptypes] Rework ptype value copying for RVB

- hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
- hail/src/main/scala/is/hail/expr/types/encoded/EArray.scala
- hail/src/main/scala/is/hail/expr/types/encoded/EBaseStruct.scala
- hail/src/main/scala/is/hail/expr/types/encoded/EBinary.scala
- hail/src/main/scala/is/hail/expr/types/encoded/EBoolean.scala
- hail/src/main/scala/is/hail/expr/types/encoded/EFloat32.scala
- hail/src/main/scala/is/hail/expr/types/encoded/EFloat64.scala
- hail/src/main/scala/is/hail/expr/types/encoded/EInt32.scala
- hail/src/main/scala/is/hail/expr/types/encoded/EInt64.scala
- hail/src/main/scala/is/hail/expr/types/encoded/EType.scala
> [hail] Refactor getOrDefineMethod to be on FB, not EFB

- benchmark/scripts/benchmark_in_pipeline.py
> [benchmark] Include benchmark in name of batch job

- hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala
- hail/src/main/scala/is/hail/expr/types/physical/ComplexPType.scala
- hail/src/main/scala/is/hail/expr/types/physical/PBoolean.scala
- hail/src/main/scala/is/hail/expr/types/physical/PFloat32.scala
- hail/src/main/scala/is/hail/expr/types/physical/PFloat64.scala
- hail/src/main/scala/is/hail/expr/types/physical/PInt32.scala
- hail/src/main/scala/is/hail/expr/types/physical/PInt64.scala
- hail/src/main/scala/is/hail/expr/types/physical/PPrimitive.scala
- hail/src/main/scala/is/hail/expr/types/physical/PType.scala
- hail/src/test/scala/is/hail/annotations/StagedRegionValueSuite.scala
> [hail/ptypes] Rework SRVB to support ptype coercion

- hail/src/main/scala/is/hail/expr/ir/InferPType.scala
- hail/src/main/scala/is/hail/expr/types/physical/PStream.scala
https://github.com/hail-is/hail/issues/7924
> [hail/ptypes] don't assume canonical implementation in copyStreamable

- ci/ci/github.py
We got an error because a BatchBuilder has no id attribute
> [ci] fix ci when deploy batch is invalid

- ci/ci/build.py
> [ci] add one more missing docker retry

- ci/ci/github.py
- ci/test/resources/build.yaml
I think this will work, but I haven't tested it with dev deploy.
> [ci] add url to zulip failure notification

- docker/requirements.txt
https://pypi.org/project/aiodocker/0.17.0/
A few bug fixes were made since 0.14.0
> [batch] update aiodocker version

- batch/batch/front_end/validate.py
- batch/batch/worker.py
- batch/test/test_batch.py
- ci/ci/build.py
- ci/test/resources/build.yaml
- docker/requirements.txt
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/batch_client/client.py
The changes to build.yaml will be in a separate PR once this merges.
> [batch,ci] Add timeout parameter

- batch/batch/front_end/front_end.py
I think this is the correct fix. The batch in default needs to access service accounts in other namespaces.
> [batch] fix service accounts

- batch/test/test_batch.py
- hail/python/hailtop/batch_client/aioclient.py
- hail/python/hailtop/batch_client/client.py
> [batch] Add query parameter for listing jobs

- ci/ci/github.py
https://zulipchat.com/help/format-your-message-using-markdown#mentions
> [ci] fix zulip notification

- hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/expr/ir/TableValue.scala
cc: @tpoterba @chrisvittal, you two were on the PR that removed this. Do I misunderstand something?
> [hail] actually persist

- batch/batch/driver/instance_pool.py
- batch/batch/front_end/validate.py
Prefer us-central1 up to 50K cores, then strip across all regions based on quotas.
> [batch] stripe across regions

- hail/src/main/scala/is/hail/expr/ir/Emit.scala
> [hail] fix ndarrayconcat

- hail/src/main/scala/is/hail/expr/ir/Compile.scala
Don't want to release with this instability
> Removed InferPTypes

- hail/Makefile
- hail/python/hail/docs/change_log.md
Don't approve this yet, I have to turn off `InferPTypes`
> Release 0.2.33

- .gitignore
- batch/.gitignore
- ci/.gitignore
- remove some redundant project git ignores
- add a few more file types
> [hail] clean up git ignores

- build.yaml
Everyone else does VERB NOUN and we were doing NOUN VERB.
> [dbuf] harmonize dbuf build naming with other projects

- batch/batch/worker.py
> [batch] fix container process is already dead error

- benchmark/python/benchmark_hail/run/table_benchmarks.py
This is unacceptably slow, let's track it until it isn't.
> Add an array range force count benchmark

- build.yaml
- hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala
- hail/src/main/scala/is/hail/asm4s/joinpoint/ParameterPack.scala
- hail/src/main/scala/is/hail/expr/ir/Compile.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
- hail/src/main/scala/is/hail/expr/ir/InferType.scala
- hail/src/main/scala/is/hail/expr/ir/PValue.scala
- hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala
- hail/src/main/scala/is/hail/expr/ir/agg/StagedBlockLinkedList.scala
- hail/src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala
- hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
- hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala
- hail/src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala
- hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
- hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
- hail/src/main/scala/is/hail/expr/types/physical/PType.scala
- hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
- hail/src/test/scala/is/hail/expr/ir/agg/StagedBlockLinkedListSuite.scala
> [hail] Make EmitTriplet value a PValue

- hail/src/main/scala/is/hail/asm4s/Code.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/agg/TakeByAggregator.scala
- hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
- hail/src/main/scala/is/hail/expr/types/physical/PCanonicalArray.scala
- hail/src/test/scala/is/hail/asm4s/ASM4SSuite.scala
- hail/src/test/scala/is/hail/expr/ir/UtilFunctionsSuite.scala
I tried to rip it out of EmitStream2 also, but I got stuck at the boundary of EmitStream1.  If you know how to do it, that'd be awesome, otherwise we need to wait until EmitStream1 is ripped out.
> [query] Back off joinpoint

- hail/src/main/scala/is/hail/io/TypedCodecSpec.scala
> [hail] RowStore.scala -> TypedCodecSpec.scala

- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
> [query/streams] Port CDA to new streams, delete EmitArrayTriplet etc.

- batch/batch/driver/instance.py
This PR fixes a problem where the database state for the instance didn't match the in-memory state for the instance. For example, in-memory the state was 'inactive' while in the database it was 'deleted'. We're not sure why that happens yet. There are 4 possible states: pending, active, inactive, deleted.
Rather than failing when this happens (causing an infinite retry loop), we check the return code from the database and act accordingly. 
For `deactivate`, the return code will be non-zero only if the instance is inactive or deleted. I thought about making the in-memory state match the state in the database explicitly, but I think it's safer to keep the current behavior where the in-memory state is "inactive". The state will be fixed to deleted when the callers of deactivate eventually …
> [batch] fix instance loops when db and Python are inconsistent

- build.yaml
Want to know what's taking 10m. The compilation only takes 3.5...
> [ci] Add timings to build-hail

- hail/python/hailtop/pipeline/backend.py
- hail/python/hailtop/pipeline/pipeline.py
- hail/python/hailtop/pipeline/task.py
Please check whether you like the behavior I added where I raise a NotImplementedError if you try and use the local backend with `always_run` or `timeout`.
> [pipeline] add timeout option

- hail/src/main/scala/is/hail/annotations/UnsafeRow.scala
- hail/src/main/scala/is/hail/backend/Backend.scala
- hail/src/main/scala/is/hail/expr/ir/CompileAndEvaluate.scala
- hail/src/main/scala/is/hail/expr/ir/Interpret.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
- hail/src/main/scala/is/hail/io/RichContextRDDRegionValue.scala
- hail/src/main/scala/is/hail/rvd/RVD.scala
- hail/src/test/scala/is/hail/TestUtils.scala
- hail/src/test/scala/is/hail/annotations/StagedRegionValueSuite.scala
- hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
- hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
- hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala
- hail/src/test/scala/is/hail/expr/ir/TakeByAggregatorSuite.scala
- hail/src/test/scala/is/hail/expr/ir/agg/StagedBlockLinkedListSuite.scala
> [query] Remove region argument from SafeRow.read

- notebook/notebook/templates/workshop/resources.html
Double check the links work Kumar and I think this will be good to go.
> Add BroadE Workshop to Workshop Resources

- hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh37.sh
- hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh38.sh
- hail/python/hailtop/hailctl/dataproc/start.py
So far there is still only one bucket, but here's the proposed restructuring. I'll make a follow up PR and duplicate the data to EU (we are bound to have European veppers) and London (since we know Sanger wants to use it). 
Also fixes #8078
> [hailctl] Look up the bucket to get VEP data from

- hail/Makefile
- hail/python/hail/docs/change_log.md
I listed everything I'm aware of, though it's possible that some internal changes may have made performance impacts I don't know about.
> Release 0.2.34

- hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/InferPType.scala
- hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala
- hail/src/main/scala/is/hail/expr/types/physical/PCanonicalArray.scala
- hail/src/main/scala/is/hail/expr/types/physical/PCanonicalBaseStruct.scala
- hail/src/main/scala/is/hail/expr/types/physical/PType.scala
- hail/src/test/scala/is/hail/TestUtils.scala
- hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
> [query] test compiled, unoptimized

- hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
- hail/src/main/scala/is/hail/stats/package.scala
Also fix HWE and Hardy-Weinberg return types.
> [query] Appropriately set requiredness in `registerCode`

- hail/src/main/scala/is/hail/expr/ir/Emit.scala
- hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
- hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
- hail/src/main/scala/is/hail/expr/ir/InferPType.scala
Remove some (now) unnecessary local variable initializations.
newEmit{Local, Field}: don't store missingness variable for required types.
Split up zip cases assert same length and extend na.  Otherwise, the same length code ended up assigning a missing element to a required field.
> [query] some default initialization cleanup

- hail/src/main/scala/is/hail/expr/types/encoded/EArray.scala
- hail/src/main/scala/is/hail/expr/types/encoded/EContainer.scala
- hail/src/main/scala/is/hail/expr/types/encoded/EPackedIntArray.scala
EContainer is a superclass of EArray and EPackedInts that has an element
type.
> [query] Add EContainer

- hail/python/hailtop/hailctl/dataproc/start.py
Adds Australia to hailctl's vep list.
> Australian VEP region

- hail/python/hail/methods/qc.py
Based on feedback from Maryam, this helps users use VEP correctly.
> [hail][vep] add VEP installation note

- hail/src/main/scala/is/hail/lir/X.scala
I'm starting to look over the lir changes, and I caught this.
> fix infinite loop

- batch/batch/front_end/front_end.py
- batch/batch/front_end/templates/billing.html
- batch/sql/add-batches-time-created-index.sql
- batch/sql/estimated-current.txt
- build.yaml
- web_common/web_common/templates/header.html
I added a billing UI page. I thought about supporting search/filter on user and billing project, but it was too hard to get the formatting how I wanted and thought this was good enough for now.
@cseed Can you confirm you're okay with the query I added over batches? I also added an index on `time_created` on the batches table, so this will require a migration.
> [batch] Add billing UI page

- hail/python/hail/backend/backend.py
Scala counterpart removed a while ago
> [query] remove Python LocalBackend

- hail/python/hail/ir/register_functions.py
- hail/src/main/scala/is/hail/expr/ir/PCode.scala
- hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
- hail/src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala
- hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala
- hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
- hail/src/test/scala/is/hail/expr/ir/GenotypeFunctionsSuite.scala
This represents an incremental step that will allow functions to be ported to PCode over time.
> [query/pcode] Add registerPCode, begin moving a few registerCode functions to it.

- ci/ci/github.py
Error is rather obvious as is fix
> [ci] fix CI bug: dan cannot use 0-based indexing

- ci/ci/github.py
Four line change. Trying to spread the service review burden around a bit from Jackie.
> [ci] link to the batch triggering the status change

- ci/ci/ci.py
- ci/ci/templates/pr.html
I also fixed a mis-matched span close tag.
> [ci] link to GH PR from CI PR page

- hail/src/main/scala/is/hail/experimental/ExperimentalFunctions.scala
> [query/ptypes] experimental registered functions

- .dockerignore
tiny PRs to maximize our daily PR count 😉
> ignore log files in dockerignore

- hail/Makefile
- hail/python/hail/docs/change_log.md
WIP because we are waiting on #8418
> Release 0.2.35

- benchmark/python/benchmark_hail/cli.py
- benchmark/python/benchmark_hail/combine/combine.py
- benchmark/python/benchmark_hail/compare/cli.py
- benchmark/python/benchmark_hail/create_resources/create_resources.py
- benchmark/python/benchmark_hail/run/cli.py
- hail/python/hailtop/hailctl/dataproc/cli.py
Prints the default in the help message, way nicer.
> Use ArgumentDefaultsHelpFormatter as argparse formatter

- hail/src/main/scala/is/hail/expr/ir/CompileAndEvaluate.scala
- hail/src/main/scala/is/hail/expr/ir/TableIR.scala
rounds out my assigned todos for the week
> [query/ptypes] remove PType.canonical from TableParallelize

- batch/batch/worker.py
I wasn't quite sure how to structure this.
> [batch] retry docker image not found error

- benchmark/python/benchmark_hail/run/combiner_benchmarks.py
They had not been updated when the module structure changed.
> [benchmark] Fix combiner benchmarks
