apiserver/environment.yml
apiserver/hail-ci-deploy.sh
notebook2/Makefile
notebook2/notebook/notebook.py
notebook2/notebook/templates/notebook-form.html
projects.yaml

This adds apiserver to CI, and modifies notebook to use the hail-jupyter image that the former defines.
To ensure that it's using the appropriate image, notebook2's Makefile has been modified to read the ["hail-jupyter-image" label that the apiserver deployment defines](https://github.com/hail-is/hail/blob/master/apiserver/deployment.yaml.in#L74)
- the Makefile tests that we get a non-empty string from the kubectl command used to read this value before proceeding
Stacks on https://github.com/hail-is/hail/pull/5592, without which notebook2 wouldn't work when also defaulting to hail-jupyter.
I used the "dependencies" property in `projects.yaml` as well as presenting the proper order, but that doesn't look like it's actually used yet. Still, it seems like a good idea, so if that is planned …

[apiserver, notebook2] notebook2 depends on apiserver

---

hail/src/main/scala/is/hail/io/RowStore.scala

This might fix the bug you're seeing.  Capacity (which should have been tracked separately) wasn't getting updated correctly in copyFrom, so if you did two copyFrom's, the second one would truncate the data.

fix potential memory buffer bug

---

hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala

First step in fixing: https://github.com/hail-is/hail/issues/5358
@chrisvittal FYI this should improve the performance of multiple aggregations across samples in MatrixTable.anntoate_rows.

Fix lower mmr

---

hail/src/main/scala/is/hail/io/tabix/TabixReader.scala
hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala

Saves memory on the master but has an unfortunate side effect of
drastically multiplying the number of times a tabix file is read, as it
is read once per partition per vcf rather than once per vcf.
This change places tabix reading in a more critical path of the gVCF
merger, I would appreciate a more detailed performance audit of that
code, in addition to looking over this change.
From my measurements it looks like we pay a 20-30 second cost per partition of 100 gVCFs
cc: @cseed

Parse tabix during reading, not during import

---

apiserver/Makefile

Deploy is currently failing because deploy script tries to deploy in current namespace (batch-pods) and doesn't have permission.

deploy in default namespace

---

docker/Dockerfile.base
docker/Dockerfile.spark-base
docker/Makefile
docker/core-site.xml
docker/hail-ci-build.sh
docker/hail-ci-deploy.sh
projects.yaml
scorecard/Dockerfile
scorecard/Makefile
scorecard/environment.yml

FYI @danking @jigold @akotlar This might be contentious.  The wisdom is to make docker images small, but I think this will greatly improve our docker pull/build/push times.
Watching some recent builds and deploys, it seems insane, the time we spend and the number of images we build with (mostly) duplicate contents.  The goal here is to build a common base image for all containers in our cluster.  I built on Ubuntu instead of Debian because it has Python 3.6 by default.  It contains useful stuff I often find myself installing when debugging inside the cluster (htop, emacs, others should feel free to add tools they like), python3 and pip packages needed by any service (no conda, thank you very much), jvm and the google-cloud-sdk with kubectl.  I also build a spark-base (built on base) with …

[docker, scorecard] add docker base image, use in scorecard

---

ci/ci/pr.py

There's no reason for these tiny CI test jobs to use 3.7 cpus.

[ci] only give high resources to real hail PRs

---

hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

This is currently an IR that does nothing except take an IR of a container type and changes the wrapper type to TStream. In this PR, I've defined it in the usual (Scala) IR framework and in Emit (currently equivalent to ToArray, but that will change in the c++ emitter as the stream infrastructure goes in). It's otherwise not used yet (and will essentially continue to be a no-op in the JVM emitter), so I haven't written tests other than the parser test.
I intend to use this mostly to enforce non-instantiation of arrays in the c++ emitter, so that we don't inadvertently try to create e.g. an array of all the rows in a partition.

define ToStream IR (stub)

---

ci/ci/batch_helper.py
ci/ci/build_state.py
ci/ci/ci.py
ci/ci/pr.py
ci/ci/prs.py

I think this resolves a number of our issues actually wherein CI keeps hearing about jobs that it's already updated its internal state about.

[ci] delete a job after its information has been incorporated into internal state

---

hail/python/hail/ir/base_ir.py
hail/python/hail/ir/matrix_ir.py
hail/python/hail/methods/impex.py
hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/types/MatrixType.scala
hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

This should cut down on expensive py4j calls in import_vcfs, and the
infrastructure should also help us with complex java <=> python
interchanges, by passing the releavant information via primitive types
or strings in all cases.
Brief summary:
- Add vectorIrs map to HailContext to store lists of irs that may need
be referenced later
- Switch import_vcfs to returning a json string with the id of the IR
array that is now stored in the vectorIrs map, along with the size of
that array and its type, suitable to passed to tmatrix._from_json.
- Add JIRVectorReference to python, which is the deserialized version of
the returned json.
- Add JavaMatrixVectorRef, which represents a single IR contained in
some stored IR array.

[hail] Add map of ints to Arrays of IRs to context, use in import_vcfs

---

batch/Dockerfile

Deploy is still failing because batch build is failing.  The async stuff had new requirements that didn't install on alpine.  I migrated it to base.  I verified the build by hand.

fix batch build, migrate to base

---

hail/src/main/resources/include/hail/NDArray.h
hail/src/main/resources/include/hail/Utils.h
hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

- Implemented an NDArray as simply a struct with enough information to properly index but no knowledge of the data type, so no templating required.
- Convert child IRs from regions to `std::vector` so the NDArray logic is simpler and isn't coupled to regions. Maybe it doesn't need to be decoupled?
- Currently passing by value in the code-gen for simplicity and since the values are pretty small, but would appreciate feedback on memory-management strategies for non-region values like NDArray.
- Tests extract singular values since we can't translate these arrays back into Java.

[c++] Add NDArray in C++ and emit MakeNDArray and NDArrayRef

---

hail/src/main/scala/is/hail/expr/ir/Binds.scala

The constructors don't get a scope.

Fix Apply{Agg, Scan}Op binding rules

---

docker/Dockerfile.base

The ubuntu 18.04 docker default is ascii, which was causing batch to barf on logs that contained special characters.

set base image default language to C.UTF-8

---

hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala

Binary search changed to return the size of the keys if the given key was greater than all existing keys. The randomized tests weren't updated and would fail intermittently in this case. Added in a check for this case and asserted that the given key is in fact greater than the entire keyset.
Resolves #5630

[fix] test for bin-search on dict

---

hail/python/scripts/run_combiner.py

This will hopefully ensure that the import_vcfs IR is deleted after its only
use.

Add an explicit gc call in the combiner script

---

hail/python/hail/experimental/__init__.py
hail/python/hail/experimental/full_outer_join_mt.py
hail/python/hail/expr/functions.py
hail/python/test/hail/experimental/test_experimental.py

[experimental] Add full_outer_join_mt experimental function.

---

hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

If we're binding a variable and using it in an array expression, and then transforming that array expression, we should be able to deforest the entire thing.

[c++] support deforested Let in Emit

---

hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/main/scala/is/hail/expr/ir/Binds.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/types/physical/PArray.scala
hail/src/main/scala/is/hail/expr/types/physical/PIterable.scala
hail/src/main/scala/is/hail/expr/types/physical/PStream.scala
hail/src/main/scala/is/hail/expr/types/virtual/TArray.scala
hail/src/main/scala/is/hail/expr/types/virtual/TStream.scala
hail/src/main/scala/is/hail/variant/MatrixTable.scala
hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala

and correspondingly, TContainer -> TIterable.
This paves the way for more strict enforcement of stream types in deforested code generation in the lowerer. We assume that basically anywhere that expects an array in the current value IR, it could also be a stream. When streamable values are expected to have a physical layout/representation, we convert to PArray and treat as a PArray.
MakeArray, ArrayRange and ReadPartitions are also always a stream type. (MakeArray takes type Streamable to be consistent with python, but I could fix that.)
The next step from here is to add a streamifying pass during lowering that adds ToStream and ToArray everywhere, and then more strictly enforce that anything deforested in cxx.Emit is of type TStream, and anything not deforested is of type TArray.
EDIT: I …

TArray -> TStreamable within value IR typing

---

ci/ci/ci.py

after a job is deleted a recent change to batch client
means that all the properties of that job objcet
are lost.

partition jobs before theyre deleted

---

hail/build.gradle

So that I'll stop checking in crap.
I have no idea why the parentheses are necessary, but they are.

add PYTEST_ARGS env var to gradle

---

hail/python/hail/experimental/vcf_combiner.py

@lfrancioli and I were discussing the possibility of computing allele level statistics on the new
combiner output. This was the result.
No longer store any `info` field in the rows, preserving all relevant fields in the entries.
There is now a `quick_summary` function that creates all of the old info fields that we were
previously computing during `combine_gvcfs`

[combiner] Move all INFO fields to entries

---

hail/python/hail/plot/plots.py

The problem here is that `one_of` looks for the first successful match,
and a `Dict[str, Expression]` will always satisfy `expr_any` before
it reaches the dict checker.

Fix plotting label as dict

---

hail/src/main/scala/is/hail/rvd/RVDPartitioner.scala

Should hopefully save some allocations in TableMapRows and elsewhere.

[hail] do not create a new RVDPartitioner with unchanged key

---

hail/python/hail/backend/backend.py
hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/expr/functions.py
hail/python/hail/ir/base_ir.py
hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/ir/blockmatrix_reader.py
hail/python/hail/ir/blockmatrix_writer.py
hail/python/hail/ir/ir.py
hail/python/hail/ir/matrix_ir.py
hail/python/hail/ir/matrix_reader.py
hail/python/hail/ir/matrix_writer.py
hail/python/hail/ir/renderer.py
hail/python/hail/ir/table_ir.py
hail/python/hail/ir/table_reader.py
hail/python/hail/ir/utils.py
hail/python/hail/linalg/blockmatrix.py
hail/python/hail/table.py
hail/python/hail/utils/misc.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Contains one piece of a fix for #5262
This refactor was initially undertaken to resolve the above issue, which
manifested due to the nested stack frames created by the IR renderer.

Refactor Python IR to reduce code duplication and complexity

---

hail/hail-ci-build.sh
hail/hail-ci-deploy.sh
hail/src/main/c/Makefile

Developers should manually enable `-Werror` in their local `CXXFLAGS`

[hail] only -Werror on CI builds

---

hail/install-gcs-connector.sh

Need to get only the service account (there is now a `disabled` column that needs to be cut out)

gcs connector install fix

---

.github/issue_template.md

The current one splits text across lines and looks pretty bad in the editor mode.

Improve github issue template

---

hail/python/cluster-tests/cluster-sanity-check.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/linalg/test_linalg.py

`BlockMatrix.to_numpy` writes separate block files if the matrix size is too big to export in a single file on the leader. This caused a bug on the cluster because the workers were writing to their local filesystems and not Hadoop. This now actually writes and reads with a temp Hadoop path.
Added an underscore parameter to the `to_numpy` method to force writing the block matrix out in blocks and added a sanity check in the cluster tests.

use hadoop filesystem for reading rectangles to numpy

---

cloud-sql.mk

Default mysql port is 3306, should probably stick with that for default CLOUD_SQL_PORT, especially since google doesn't expose way to override the default

[batch] default port for mysql 3306

---

hail/python/hail/expr/expressions/expression_typecheck.py
hail/python/hail/expr/expressions/typed_expressions.py
hail/python/hail/expr/functions.py
hail/python/hail/ir/ir.py
hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

- Added `NDArrayMap` IR to python as well as `NDArrayExpression.map`
- Added `NDArrayNumericExpression` so NDArrays can be operated on using `hl.abs` and `hl.sign` etc. However, these native methods aren't supported currently in C++ so they are untested. Once Map2 goes in, arithmetic operations can be added to `NDArrayNumericExpression`.
Note:
- The `NDArrayCoercer` "works" in that it identifies objects that are already `NDArrayExpression`s, but is not meant to actually coerce other data types yet.

Py ndarray map

---

apiserver/Dockerfile.apiserver
apiserver/deployment.yaml.in
apiserver/start-worker.sh

Spark worker port (on spark-worker) 9000
Spark driver port (on apiserver) 9001
Block manager port (on apiserver and spark-worker) 9002
The apiserver was hanging trying to connect to the master (and therefore notebook2 notebooks trying to connect to it) without this.  Tested hand deploy and it fixed it.

fix various Spark ports, expose on pods

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/ir/TableIR.scala

Fix TableMultiWayZipJoin key behavior

---

hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/io/LoadMatrix.scala

 import_matrix_table can import matrix table with no cols

---

vdc/k8s-config.yaml

This fixes the notebook2 deployment permission issue that was resulting in CrashLoopBackoff (no permissions for the Table class to `read_namespaced_secret('get-users', 'default')`). Already tested, works (notebook2 back up).
It also fixes an apparent error in the master branch RoleBinding.
This diff looks slightly weird. I fixed the existing notebook  Roles/RoleBindings by deleting the `create-services` `Role` and `notebook-create-services` `RoleBinding`, and then fixing the broken `notebook-create-servivces-and-pods` `RoleBiding`, by correctly updating the `roleRef` to read `create-services-and-pods`.
When notebook1 totally goes away, we can probably remove the "services" permission.
Before:
```yaml
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
namespace: default …
```

[notebook, notebook2]: fix create-services-and-pods binding, add get-users permission

---

notebook2/notebook/table.py

Cotton requested this, to disambiguate the google service account secret name from other secret names, when, at some later date, we have that problem.
Will add the corresponding definition updates in the script PR (https://github.com/hail-is/hail/pull/5618)

[notebook2]: change secret_name -> gsa_key_secret_name

---

hail/src/main/scala/is/hail/expr/ir/Compile.scala

Needed to debug Laurent's pipeline. And we should be logging everything anyway -- this is the only way we get to see the post-extract-aggregators executed IR

Increase verbosity of Compile optimization

---

hail/python/hail/experimental/expressions.py

Can you double check the `analyze` syntax? I'm not sure that's 100% correct but I couldn't find an existing example of checking specifically for globals

add check for expression source in write_expression

---

notebook2/notebook/notebook.py

Allows the notebook container to have access to the user's gsa secret key, a necessary step in mounting the user's bucket.
I modified `delete_worker_pod` to exclude the  V1DeleteOptions, because the signature appears to have changed, and no options were actually provided.
```sh
File "notebook/notebook.py", line 443, in delete_worker_pod
kube.client.V1DeleteOptions())
TypeError: delete_namespaced_pod() takes 3 positional arguments but 4 were given
```
Will double check that I have necessary permissions: its the case when running on local, but I think I will need to update vdc to provide broad secret read access for notebook for this to work on the cluster. Checking now
cc @cseed, @danking, @jigold

[notebook2] mount gsa key secret

---

ci/ci/github.py

dismiss wasn't handled so CI incorrectly thought an approved, passing PR should be merged, which then failed.

recognized dismissed review

---

hail/python/hail/methods/misc.py

[bugfix] Fix duplicated nodes in maximal_independent_set output

---

hail/src/main/scala/is/hail/annotations/aggregators/RegionValueArraySumAggregator.scala
hail/src/main/scala/is/hail/annotations/aggregators/RegionValueHistogramAggregator.scala
hail/src/main/scala/is/hail/expr/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/io/bgen/BgenRDDPartitions.scala
hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala
hail/src/main/scala/is/hail/io/plink/LoadPlink.scala
hail/src/main/scala/is/hail/io/vcf/ExportVCF.scala
hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
hail/src/main/scala/is/hail/linalg/BlockMatrix.scala
hail/src/main/scala/is/hail/methods/Aggregators.scala
hail/src/main/scala/is/hail/methods/LocalLDPrune.scala
hail/src/main/scala/is/hail/methods/Nirvana.scala
hail/src/main/scala/is/hail/misc/BGZipBlocks.scala
hail/src/main/scala/is/hail/utils/ExportType.scala
hail/src/main/scala/is/hail/utils/StringEscapeUtils.scala
hail/src/main/scala/is/hail/utils/package.scala
hail/src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala
hail/src/main/scala/is/hail/variant/Call.scala
hail/src/main/scala/is/hail/variant/Locus.scala
hail/src/main/scala/is/hail/variant/MatrixTable.scala
hail/src/main/scala/is/hail/variant/ReferenceGenome.scala
hail/src/main/scala/is/hail/variant/VariantMethods.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/testUtils/Variant.scala
hail/src/test/scala/is/hail/variant/LocusIntervalSuite.scala
hail/src/test/scala/is/hail/variant/ReferenceGenomeSuite.scala

We mix the two right now, with most of the new code using quotes. I
feel that quotes are a better solution given the prevalence of markdown
editors (like Zulip) where copy-pasting an error message with backticks
leads to badly formatted renderings.
cc @cseed who I believe favored the use of the backtick style in the first place.

Fix error messages to be consistent about using quotes, not backticks.

---

hail/python/hail/expr/__init__.py
hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/expr/functions.py
hail/python/hail/ir/register_functions.py
hail/python/hail/linalg/utils/__init__.py
hail/python/hail/linalg/utils/misc.py
hail/python/hail/methods/statgen.py
hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala
hail/src/main/scala/is/hail/linalg/BlockMatrix.scala

leaving unassigned right now, since there's still some behavior change questions to be figured out.
cc @konradjk 
Fixes #5407.

[feature] add _localize flag to locus_windows to prevent serialization in ld_matrix

---

hail/python/hail/methods/qc.py
hail/python/test/hail/methods/test_qc.py

Fixes #5561
Also improved the implementation of sample and variant qc.

[bugfix] Fix call rate in sample_qc to divide by the total rows.

---

ci2/Dockerfile.ci2
ci2/Makefile
ci2/ci/ci.py
ci2/deployment.yaml.in
ci2/hail-ci-deploy.sh
gateway/hail.nginx.conf.in
projects.yaml

I'm forking ci => ci2 to address the existing ci issues.  I plan to steal lots of code from ci, this is just a skeleton to get started.  Along the way, I'm going to convert everything to async.
I already deployed the ci2 service, so the gateway change shouldn't break anything.

added ci2 skeleton

---

hail/src/main/scala/is/hail/expr/ir/FreeVariables.scala
hail/src/main/scala/is/hail/expr/ir/Mentions.scala

The CountMentions implementation was totally wrong -- it hadn't been updated to use the binding environment. I think most of the usages of Mentions were technically correct as implemented, but this is much safer.

Fix Mentions

---

ci/ci/prs.py

@cseed fyi
Not sure why I didn't always do it this way. `push` is the method that updates the internal state with knowledge of a new commit to a target branch (e.g. master, 0.1)

[ci] eagerly update statuses for all PRs targeting merged branch

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/hail/matrixtable.py
hail/python/hail/table.py
hail/python/test/hail/matrixtable/test_matrix_table.py

stacks on https://github.com/hail-is/hail/pull/5666
Teaches Matrix Tables how to HTML

[hail] Teach MatrixTable how to HTML

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_expr.py

[feature] Add ArrayExpression.index

---

batch/batch/__init__.py
batch/batch/server/server.py
batch/test/test_batch_server.py

`server.py` contains global variables that we really ought not to evaluate when running tests. This moves the minimal set of things out of `server.py` so that the tests do not evaluate `server.py`.

[batch] prevent test from evaluating server.py

---

ci/ci/pr.py

I think old repos still work, which is why CI is mostly fine, but I was seeing errors when testing locally.

[ci] use new GitHub raw content URLs

---

ci/test-locally.sh

This is intended to prevent the script from being terminated while it cleans up (c.f. people who spam ctrl-c to kill a local test). `set` is not the word for setting a `trap` though. Long standing bug 🤷‍♀️ .

[ci] fix trap syntax

---

hail/src/main/scala/is/hail/expr/ir/IRBuilder.scala
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/types/MatrixType.scala

Fixes #5777
Timing in master for benchmark/matrix_table_entries_table:
run 1 took 91.15s
run 2 took 86.58s
run 3 took 85.45s
Mean, Median: 87.73s, 86.58s
Timing on this branch:
run 1 took 20.33s
run 2 took 20.98s
run 3 took 21.28s
Mean, Median: 20.86s, 20.98s

Lower MatrixEntriesTable

---

ci/test/test-ci.py

There were some cases where GH or CI were a bit slow to respond to PR changes. This lets the tests wait a bit until CI is aware of a PR. I think some test flakiness came from this.
cc: @cseed

[ci] make ci tests resilient to slow ci

---

batch/.dockerignore

The language of a [`.dockerignore`](https://docs.docker.com/engine/reference/builder/#dockerignore-file) file is different from that of a `.gitignore` file. This changes batch's ignore file to do what the original author probably intended.

[batch] Fix dockerignore

---

notebook2/notebook/table.py

Fixes connection timeout after 8 hours. 
When we transition to aiomysql, will port well to a pooled connection version (`async with self.pool.acquire() as conn:`. Even now however, the time it takes to acquire a connection is not the bottleneck during login.
cc @danking assigned you as well in case you're on.

[notebook2]: acquire new connection per login

---

hail/src/main/resources/include/hail/NDArray.h
hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/main/scala/is/hail/cxx/EmitTriplet.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

- Implement `NDArrayReindex` IR node in Scala. This node specifies a surjective function onto the node's child's set of dimensions. In the case where this is a bijection, the reindex is a transpose and the dimensions are permuted. If it is not a bijection, you introduce new dimensions (a broadcast) that have no specified length. Therefore, broadcasts are impossible to realize and must be deforested (not implemented yet).
- Implement emit for top-level reindexing (must be a transpose).
- Storage format is completely encoded in strides so the `row_major` flag in `NDArray` is superfluous and doesn't make sense after arbitrary transposes. Removed it but kept the `flags` field of `NDArray` which will be used for other metadata.

[c++] NDArray transpose

---

hail/hail-ci-build.sh

This should reduce external cloud storage dependencies making
infrastructure changes easier.

[tests] use generated config and real sha for tests

---

batch/batch/client.py

YAML has an arbitrary extension mechanism. pyYAML defines a python extension that lets you create arbitrary python objets. This is clearly a huge security vulnerability. Apparently, pyYAML, by default, enables this extension (rather than just parsing vanilla YAML, 🤦‍♀️). `safe_load` loads vanilla YAML without the gaping security hole.
I was getting warnings about this when testing.

[batch] use safe load in batch client

---

batch/batch/api.py
batch/batch/client.py
ci/ci/environment.py

Get rid of default API and all these unnecessary api root-level methods. Add a cookies and headers parameter that can be used to send arbitrary cookies and headers along.

[batch] simplify batch api.py

---

batch/Makefile
batch/batch/database.py
batch/batch/pylintrc
batch/batch/server/database.py
batch/batch/server/server.py
batch/clean-db.sh
batch/hail-ci-deploy.sh
batch/test-locally.sh
batch/test/test_database.py
pipeline/test-locally.sh

This PR is almost done. I need to change one of the Makefile rules to include new targets from #5791 and make sure the database is cleaned and test the deploy works. My plan is to continually delete the production tables per deployment until we're happy with the schema and everything is working.
Once this is all in, then the next PR will add the actual data to the tables in `server.py` and get rid of the global dictionaries / application state. I might try and do this in 2 stages (jobs and batch), but I'm not sure it's possible.
Depends on #5781, #5784

[batch] Add BatchDatabase with corresponding tables

---

apiserver/Dockerfile.hail-base
apiserver/Dockerfile.spark-base
apiserver/start-master.sh
apiserver/start-worker.sh

Working in cluster. Fixes the below error, the origin of which I'm not quite sure: does it happen because wherever CI builds this has spark2.4 installed, or is spark2.4 pulled by gradlew shadowJar (I don't see where this happens, but I also haven't looked very carefully).
```
install-hail-locally:
rm -rf build
(cd ../hail && GRADLE_OPTS=-Xmx2048m ./gradlew shadowJar --gradle-user-home /gradle-cache)
mkdir -p build/hail/jars
mkdir -p build/hail/python
cp -a ../hail/build/libs/hail-all-spark.jar build/hail/jars
cp -a ../hail/python/hail build/hail/python
build-hail-base: build-spark-base install-hail-locally
```
Only issue I see is
"""
2019-04-10 18:00:59 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting …

[apiserver]: use spark2.4

---

ci/Makefile

I had a PR go in that changed the name of the target.

[ci] fix test-locally cloud-sql targets

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala

Assigning Cotton for context since he implemented ArrayAgg back in January.
It looks to me like this stuff was never actually getting optimized...

Optimize IR generated in ArrayAgg

---

docker/Dockerfile.base

For ci2.  We might prefer just the jre in the base, but the Hail build doesn't work if you install the jre and then the jdk, java.home still points to the jre and I haven't figured out a fix yet.

update base image

---

hail/python/hail/table.py
hail/python/test/hail/table/test_table.py

[feature] Add `unify` option to `Table.union`

---

apiserver/Dockerfile.apiserver
apiserver/deployment.yaml.in

I guess the Spark 2.4 upgrade broke apiserver, but honestly I don't know how this could have worked before.
Deployed by hand and verified it's working.
I'm talking in methods tomorrow, might try to demo this.  It would be nice if it is working.

set driver bind address, add apiserver service ports

---

hail/python/hail/methods/family_methods.py
hail/python/test/hail/methods/test_family_methods.py

New entry filtering semantics was removing children with no errors
leading to incorrect counts.
fixes #5786

[bugfix] restore proper mendel_errors behavior

---

hail/src/main/scala/is/hail/expr/ir/IRBuilder.scala

This is used in lowering `MatrixAnnotateColsTable`, and will allow
us to optimize away unnecessary keying shuffles that happen in column
annotation table manipulations.

[performance] Unkey table before collectAsDict

---

batch/batch/server/server.py
batch/test/test_dag.py

Here's the reference for the behavior of `gsutil cp` with directory naming. https://cloud.google.com/storage/docs/gsutil/commands/cp#how-names-are-constructed
Pipeline and CI will need to make sure the inputs to Batch actually produce what is intended.

[batch] add recursive copying of directories

---

hail/python/test/hail/matrixtable/test_matrix_table.py
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala

`va` needs to be available inside the aggregator init operations, so needs to be bound outside the arrayagg.

Fix MatrixAggregateColsByKey lowering

---

hail/python/test/hail/expr/test_types.py
hail/src/main/scala/is/hail/expr/AnnotationImpex.scala

When putting `tuple` in `dict` type, it will fail to convert spark dataframe. The issue could be reproduce by:
```
ht = ht.annotate(nested=hl.dict({"tup": hl.tuple([ht.idx])}))
ht.to_spark()
```
This PR fix this issue.

Fix tuple nested in dict type will fail when calling `to_spark()`

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/hail/ir/ir.py
hail/python/test/hail/test_ir.py
hail/src/main/resources/include/hail/NDArray.h
hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/main/scala/is/hail/cxx/EmitTriplet.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

- Changed NDArrayRef node to take a _sequence_ of IR for the indices as opposed to a single IR. This will make operations like slicing much easier, simplifies IR emission and allows us to typecheck that you have enough index variables
- Refactored `linearizeIndices`, a function that takes a Scala sequence of index variables for a ndarray and emits the single array index, so that it actually checks now that each index is within the shape length bounds of that dimension.

[c++] Make NDarrayRef take a sequence of index IR

---

ci2/deployment.yaml.in

Errant tabs in a yaml which kubectl (rightly) rejects.

convert tabs to spaces

---

hail/build.gradle
hail/python/hail/experimental/__init__.py
hail/python/hail/experimental/write_multiple.py
hail/python/hail/ir/blockmatrix_writer.py
hail/python/hail/ir/ir.py
hail/python/test/hail/experimental/test_experimental.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Compilable.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/linalg/BlockMatrix.scala
hail/src/main/scala/is/hail/utils/richUtils/RichArray.scala
hail/src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/utils/RichArraySuite.scala
hail/src/test/scala/is/hail/utils/RichDenseMatrixDoubleSuite.scala

added `export_block_matrices` and `block_matrices_tofiles` to `experimental`, parallel versions of `BlockMatrix.export` and `BlockMatrix.tofile`, in the style of `write_matrix_tables`.

add parallelized write block matrices functions

---

apiserver/Makefile

This will be easier to put right once we get rid of pr-builder and ci2 is building all the dependent images each time.

use cp instead of rsync to avoid updating pr-builder

---

hail/src/main/scala/is/hail/experimental/package.scala
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/methods/IBD.scala
hail/src/main/scala/is/hail/methods/VEP.scala
hail/src/test/scala/is/hail/annotations/AnnotationsSuite.scala
hail/src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala
hail/src/test/scala/is/hail/expr/ir/ArrayFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/DictFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/GenotypeFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/LocusFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/MatrixIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala
hail/src/test/scala/is/hail/expr/ir/StringSliceSuite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
hail/src/test/scala/is/hail/methods/ConcordanceSuite.scala
hail/src/test/scala/is/hail/methods/LocalLDPruneSuite.scala
hail/src/test/scala/is/hail/methods/TableSuite.scala
hail/src/test/scala/is/hail/rvd/RVDPartitionerSuite.scala
hail/src/test/scala/is/hail/stats/StatsSuite.scala
hail/src/test/scala/is/hail/utils/RowIntervalSuite.scala
hail/src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala

We must be vigilant against these intruders.

Banish hundreds of `scala.immutable.Vector` usages

---

ci2/ci/build.py
ci2/ci/ci.py
ci2/ci/github.py
ci2/ci/utils.py

- All subprocess calls are async.  The UI is much more responsive now.
- Make refresh (rather than heal) non-reentrant.  There was a race condition where we could update the Github state of a PR we were actively deploying.  This seemed error prone.
- We need to lock the repos until the build is fully deployed.  I now protect pr.heal.
- Set `batch_changed = True` whenever heal needs to be rerun becomes some of its inputs (build_state, source or target sha, collection of PRs) changed.
Next up: deploy.

[ci2] concurrency improvements

---

batch/batch/aioclient.py
batch/batch/api.py
batch/batch/client.py
batch/batch/server/database.py
batch/batch/server/server.py
batch/test/test_batch.py
ci/ci/pr.py
ci/ci/prs.py

Stacked on #5934. `scratch_folder` is not used anymore because we have the bucket_name from the jwt

[batch] remove scratch_folder

---

hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/stats/HistogramCombiner.scala

[bugfix] Use binarySearch for larger and smaller in HistogramCombiner

---

batch/batch/database.py
batch/batch/server/database.py
batch/batch/server/server.py

I added `user` and `userdata` to the jobs and batch table. I also added `user` as a secondary index, which @danking also did. 
I used the `ksa_name` in the jwt for now. @akotlar We should figure out what this should be instead. 
This does not check authentication for `get_recent_events`. I also am concerned about the case where we can't access jobs, batches easily as there's no support for a super user who can view everything.
Stacked on #5934

[batch] ownership checks

---

batch/batch/database.py

In new_index, trying to create the database if it doesn't exist, I'm seeing:
pymysql.err.InternalError: (1061, "Duplicate key name 'user'")

remove duplicate user

---

ci2/ci/github.py

Fixes this:
```
WARNING	| 2019-04-30 23:31:34,751 	| server.py 	| handler:818 | callback for batch 33, job 993 failed due to an error, I will not retry. Error: Invalid URL 'ci2/batch_callback': No schema supplied. Perhaps you meant http://ci2/batch_callback?
```

Fix batch callback

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/hail/ir/ir.py
hail/python/test/hail/expr/test_expr.py
hail/src/main/resources/include/hail/NDArray.h
hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/main/scala/is/hail/cxx/EmitTriplet.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

- Implement broadcasting of NDArrays. This essentially just gives NDArrays additional dimensions of length one, which changes the view onto the NDArray but not the underlying data. This allows us to promote smaller-dimensional NDArrays before a Map2 so both NDArrays have the same number of dimensions. The loops for the map will loop through the _unified shape_ of both child NDArrays with the same semantics as numpy (if corresponding dimensions are not equal, they are still compatible if one is 1 in which case you would take the larger one). Dimensions of length 1 have a stride of 0, so indexing into the array as if it were broadcast works and is totally free. The only additional benefit deforesting would actually give you is putting fewer loop variables into the calculation of the index. …

[c++] NDArray broadcast

---

hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala

Because `BlockMatrix` is strictly 2-D but the IR backing it represents 0, 1 and 2-D arrays, we have to track whether 1-D vectors are really row or column vectors, and convert back and forth to their "matrix shape". This caused a mismatch of the 2-D vs 1-D type when transposing a row vector to a column vector and trying to do col vector + row vector. We assert that dimensions that aren't being broadcasted to a larger length retain their original length. This uncovered a related bug in the conversion between 1-D vector length and 2-D matrix dimensions.

[bug-fix] Fix incorrect assert when transposing row vector

---

hail/src/main/scala/is/hail/cxx/EmitTriplet.scala

- I don't know why I was recomputing the whole output index instead of just moving forward one. The loops will always just iterate down the new data buffer. Also means I can use the normal array builder abstraction instead.

[c++] increment offset instead of computing it from the ndarray index

---

hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala

- Most of the code is actually the same, but I was intentionally not deforesting until now to get some benchmarks.
- Basically all you need to do is compose the `outputElement`s of your children (the body of the loops) and compute what the ultimate bounds (shape) of the nested loops should be.
- For Reindex, we statically reorder the loop variables used to index into the NDArray instead of permuting the shape/strides at runtime. Not a huge performance improvement but in the broadcasting case (adding dimensions) it's at least fewer multiplications at runtime in the loop body to compute the index.

[c++] Deforest NDArray element-wise operations

---

hail/src/main/scala/is/hail/annotations/aggregators/RegionValueApproxCDFAggregator.scala
hail/src/test/scala/is/hail/annotations/ApproxCDFAggregatorSuite.scala

Add `keep` parameter to `compactLevel`, which will keep the `keep` smallest and largest values in `level`, only compacting the middle.
Get rid of the messy special handling of the min and max values of the stream. Instead, always have `keep = 1` when compacting the bottom level, which guarantees the min and max will never get compacted away.

First step towards relative error approx cdf

---

hail/python/hail/methods/impex.py
hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala

This overrides each vcf's header with a user provided one, and
overrides the vcfs' samples' names with a user provided list of lists.
This is wildly unsafe. I don't like this code. However it seems that it
is the best way to proceed with data production for gnomAD v3.
cc @cseed

Add override options to import_vcfs

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_expr.py

Quality of life improvement, wrapper around saving an ndarray and loading through numpy. Most changes are in the tests which previously could only extract elements from ndarrays to assert the transformation worked.

[hail] implement to_numpy for ndarrays going through disk

---

hail/python/hail/plot/__init__.py
hail/python/hail/plot/plots.py

Adds log option to `plot.histogram2d`
Also adds `joint_plot` to plot init

Hist2d log

---

ci2/ci/build.py

I think tests of services are failing during deployment because wait-for Service (which probes /healthcheck) hits the old service, then the service goes down during (re)deployment.
Here is an example test failure: first few tests pass then the rest fail due to connection timeout: https://ci2.hail.is/jobs/1413/log.
This doesn't quite make sense, because batch and apiserver both have readiness checks, so the rollout should be have now downtime (although some of the tests could hit the old service which could fail if there were differences).
I think this is a good chance but I'm not totally confident.  Interested in your thoughts.  Also, I can't seem the find the different between `wait deployment` and `rollout status`.

wait for deployment before testing service

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/test/scala/is/hail/expr/ir/FunctionSuite.scala
hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala

Just cleaning up some old tests to use assertEvalsTo instead of manually constructing the functions.

clean up uses of Emit in tests

---

hail/python/hail/ir/matrix_ir.py
hail/python/hail/ir/table_ir.py
hail/python/hail/matrixtable.py
hail/python/hail/table.py
hail/python/test/hail/matrixtable/test_matrix_table.py
hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/annotations/OrderedRVIterator.scala
hail/src/main/scala/is/hail/annotations/WritableRegionValue.scala
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/types/physical/PInterval.scala
hail/src/main/scala/is/hail/rvd/KeyedRVD.scala
hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/main/scala/is/hail/rvd/RVDType.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
hail/src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala

Add `product` option to `Table.index`, and `MatrixTable.{index_rows, index_cols}`. Supports interval joins. Refactored the index methods to reduce code duplication, and make them more consistent with each other. Only case not supporting `product=True` is annotating columns of a matrix table with an interval keyed table.

[Hail][Feature] Add product option to index methods

---

hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
hail/src/main/scala/is/hail/expr/ir/ArraySorter.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
hail/src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/RandomSeededFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/ReferenceGenomeFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/RandomFunctionsSuite.scala

In this PR, I replaced the usage of EmitMethodBuilder with a shim class called EmitRegion basically wherever we expect to need to pull the region from the methodbuilder. EmitRegion currently just holds the methodbuilder and the region to use if we need to store values.
I have not yet changed any region behavior, so this PR should not affect the generated code.

(scala) don't assume region as first argument to generated function

---

hail/src/main/scala/is/hail/backend/spark/LowerTableIR.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala

since the lowering is not actually a C++ step.
(also pulled out the table lowering step into an explicit step so that I could add an optimization pass afterwards)

throw different error in SparkBackend

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/hail/ir/ir.py
hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/main/scala/is/hail/cxx/EmitTriplet.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Ideally, a reshape would just be a different view onto the same underlying data. This is not always possible given the way the data is ordered (e.g. after a transpose)  in which case it might have to copy the data and start fresh. This implementation is naive in that it always copies the data. Additional checks for compatibility of strides, etc. can be added to prevent copying and just make a new view with new shape/strides.

[c++] NDArray Reshape

---

build.yaml
ci2/ci/build.py

wait for 1h for resources to be scheduled
add timeouts for pods and services
set timeout to 2x average time from a dozen recent successful runs of the step

fix test timeouts

---

hail/src/main/scala/is/hail/rvd/RVDPartitioner.scala
hail/src/main/scala/is/hail/utils/Interval.scala
hail/src/main/scala/is/hail/utils/package.scala
hail/src/test/scala/is/hail/expr/ir/IntervalSuite.scala

[hail] Add interval reduction and intersection functions

---

docker/requirements.txt
hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_expr.py

First step towards treating `CollectionExpression`s exactly like non-distributed tables. Works for arrays and sets.
cc: @konradjk
```python
>>> a = [hl.struct(b=[hl.struct(inner=1),
...                   hl.struct(inner=2)]),
...      hl.struct(b=[hl.struct(inner=3)])]
>>> hl.eval(a.b)
[[hl.struct(inner=1), hl.struct(inner=2)], [hl.struct(inner=3)]]
>>> hl.eval(a.b.inner)
[[1, 2], [3]]
>>> hl.eval(hl.flatten(a.b).inner)
[1, 2, 3]
>>> hl.eval(hl.flatten(a.b.inner))
[1, 2, 3]
```

[hail][feature] Super array expression

---

build.yaml
pipeline/Dockerfile.test
pipeline/pipeline/backend.py
pipeline/pipeline/pipeline.py
pipeline/pipeline/pylintrc
pipeline/pipeline/resource.py
pipeline/pipeline/task.py
pipeline/pipeline/utils.py
pipeline/test-pipeline-pod.yaml
pipeline/test/test_pipeline.py

- Added idea of two types of outputs: internal and external. Internal outputs are copied between tasks and external outputs are user specified copies of files.
- Added `valid` and `mentioned` which are sets of resources tasks keep track of. `valid` checks whether the resources were properly declared. `mentioned` keeps a record of the resources used in the command for variables that need to be declared.
- Changed when outputs are copied for external outputs. TaskResourceFiles are copied when the task finishes rather than at the end of the pipeline. InputResourceFiles are copied at the beginning of the pipeline as one job.
- `inputs`, `internal_outputs`, and `external_outputs` only contain resource files (not resource groups) which simplified the code quite a bit!

[pipeline] Refactor backend code

---

site/deployment.yaml

This sets up auto-scaling for site.  Request 100m, min 2, max 10 for now (unlikely we'll exceed that any time soon), anti-affinity to get instances on different nodes.  With the replication, we could probably schedule them on preemptibles.

autoscale site

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/table.py
hail/python/test/hail/expr/test_show.py

Summary of Changes
- Preserve MT structure for entry fields
- Harmonize MT and T `show` interface in a backwards compatible way
- Simplify `Expression.show` code slightly
- A comprehensive, colocated set of `show` tests

[hail] Teach Expressions to HTML Show

---

ci2/ci/build.py

I'm seeing deploy failures where the tests start failing part way through because batch becomes unavailable, for example: https://ci2.hail.is/jobs/2886/log
However, this can't be the whole story, because batch has a readiness check and it isn't clear why it should go unavailable.  Either way, this seems safer because it makes sure you pick up the intended version.

use rollout status when waiting for deployments

---

hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala

Two small, related bug fixes here:
- Vectors were not being transposed correctly, the index expression is different than that of a matrix.
- In the edge cases where vector broadcasts/transposes had to be realized, there was an IOB exception because `to` is evil and I should've used `until`. I knew this would happen one day...

[fix] Fix IOB exception when broadcasting BlockMatrix vectors

---

hail/python/hail/docs/experimental.rst
hail/python/hail/experimental/__init__.py
hail/python/hail/experimental/tidyr.py

An initial attempt to replicate the `gather()`, `spread()`, and `separate()` functions of R's `tidyr` package.

tidyr functions

---

ci2/ci/github.py

Batch had a bug that left a batch in a bad state. To unstick CI, we deleted the bad batch manually, but CI could not handle a 404'ing batch. We change CI's logic to now handle 404'ing deploy batches.

[ci2] protect against missing batches

---

hail/src/main/scala/is/hail/expr/ir/ComparisonOp.scala
hail/src/main/scala/is/hail/expr/ir/ExtractIntervalFilters.scala
hail/src/main/scala/is/hail/expr/ir/ForwardLets.scala
hail/src/main/scala/is/hail/expr/ir/IsConstant.scala
hail/src/main/scala/is/hail/expr/ir/Optimize.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/functions/RelationalFunctions.scala
hail/src/main/scala/is/hail/methods/FilterIntervals.scala
hail/src/test/scala/is/hail/expr/ir/ExtractIntervalFiltersSuite.scala

This PR will not be merged as-is, but split along the 3 commits contained within: 
- Add `Coalesce` IR node
- Expose pruning on FilterIntervals relational functions. These should be promoted to full IR nodes, especially after this PR.
- Add `ExtractIntervalFilters` optimizer pass.
I also have yet to add tests for the last commit.
What does this PR do?
```python
In [2]: mt = hl.read_matrix_table('data/1kg.rep.mt')
In [3]: mt.filter_rows(mt.locus.contig == '16').count()
Hail: INFO: interval filter loaded 5 of 128 partitions
Out[3]: (384, 284)
In [4]: mt.filter_rows(mt.locus.contig == '16').count_rows()
Hail: INFO: interval filter loaded 5 of 128 partitions
Out[4]: 384
In [5]: mt.filter_rows((mt.locus.contig == '16') | (mt.locus.contig == '19')).count()
Hail: INFO: interval filter loaded 10 …
```

Add `ExtractIntervalFilters` optimizer pass.

---

hail/python/hail/expr/aggregators/aggregators.py
hail/python/hail/ir/register_aggregators.py
hail/src/main/scala/is/hail/annotations/aggregators/RegionValueApproxCDFAggregator.scala
hail/src/test/scala/is/hail/annotations/ApproxCDFAggregatorSuite.scala

Add a `keepRatio` parameter to the ApproxCDF aggregator. When compacting any level, always keep a fixed fraction of the smallest and largest values at that level.
Also keep counts of the number of times each level is compacted, for use in downstream error estimates.

add keepRatio param to cdf aggregator

---

hail/Makefile
hail/build.gradle
hail/gradle/wrapper/gradle-wrapper.properties
hail/python/hail/docs/getting_started.rst
hail/python/hail/docs/getting_started_developing.rst
hail/src/main/c/Makefile

Users who build from source are often confused by the native
library configuration. This adds a target that handles native
library configuration for the user. I also changed the docs to
encourage the use of this target. This means everyone building hail
from source will need to build the C libraries, but I think this
is for the best, since most people building from source need to
correctly handle native libraries anyway.
Resolves https://github.com/hail-is/hail/issues/6132

[hail] add releaseJar

---

ci2/ci/github.py

Fixes this assertion error in ci2 logs:
```
ERROR   | 2019-05-21 20:22:56,019       | ci.py         | update_loop:239 | hail-is/hail:master update failed due to exception: Traceback (most recent call last):
File "/ci/ci.py", line 235, in update_loop
await wb.update(app)
File "/ci/github.py", line 465, in update
await self._update(app)
File "/ci/github.py", line 481, in _update
await self._update_github(gh)
File "/ci/github.py", line 543, in _update_github
await pr._update_github_review_state(gh)
File "/ci/github.py", line 261, in _update_github_review_state
assert state in ('DISMISSED', 'COMMENTED'), state
AssertionError: PENDING
PENDING
```

[ci] fix github state

---

hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
hail/src/main/scala/is/hail/backend/spark/LowerTableIR.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackendUtils.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala
hail/src/main/scala/is/hail/expr/ir/SpecializedArrayBuilders.scala
hail/src/main/scala/is/hail/io/RowStore.scala
hail/src/main/scala/is/hail/utils/ExecutionTimer.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

there's also a small amount of refactoring that was necessary to send TableIRSuite.testRangeCount through the lowered, jvm-emitted path to test the CollectDistributedArray implementation.
cc @cseed

implement CollectDistributedArray in ir.Emit

---

hail/src/main/scala/is/hail/expr/ir/Parser.scala

This catch was masking a `org.json4s.package$MappingException: Parsed JSON values do not match with class constructor` as a `NullPointerException` on line 148. Exceptions always include their cause in the stack trace, I see no compelling reason to maintain this try-catch.

[hail] remove confusing try-catch

---

ci2/ci/templates/index.html

Even if there is no currently running build, there may be useful history.

[ci2] always link to the pr build page

---

apiserver/apiserver/apiserver.py
apiserver/create_key.py
batch/batch/server/database.py
batch/batch/server/server.py
batch/create_key.py
batch/deployment.yaml
batch/test/test_batch.py
batch/test/test_dag.py
build.yaml
ci2/Dockerfile.ci-utils
ci2/deployment.yaml
docker/Dockerfile.base
hailjwt/Makefile
hailjwt/hailjwt/hailjwt.py
notebook2/notebook/notebook.py

We should hand merge this when we roll over the new keys.  The newly generated jwt secret should be generated by hailjwt.JWTClient.generate_key (type bytes) and written binary when creating the new jwt-secret-key secret.

require the jwt-secret-key to be binary

---

build.yaml
ci2/ci/constants.py

This copies all the artifacts into place, but doesn't update the latest hash.  Once we verify the files look correct after one round of deploy, I'll comment in the code to update latest hash.
This script is basically copied exactly from the old hail/hail-ci-deploy.sh.

Prep deploy

---

batch/batch/server/server.py
batch/create-batch-tables.sql

@cseed This fixes a bug in cancel where a job that was created but not ready was never actually cancelled. I discovered it with my PR that creates the entire batch in one atomic call. I don't think this change requires us to reset the database (just deleted a field), but if so I should probably combine this with another database change.
Can you confirm that changing (state=Created, cancelled=True) -> Cancelled doesn't change the meaning of the 'Cancelled' state how you intended?

[batch] fix cancelled, created jobs

---

hail/python/hail/ir/ir.py
hail/src/main/scala/is/hail/annotations/aggregators/ArrayElementsAggregator.scala
hail/src/main/scala/is/hail/expr/ir/Binds.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/ExtractAggregators.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/IRBuilder.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala
hail/src/main/scala/is/hail/expr/ir/Optimize.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Scope.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

This is required to implement lowering for MatrixMapCols (coming after
a dependent PR goes in). We lower the per-column aggregations to an
`AggArrayPerElement`, but if there are no rows, the result would be
missing.
This PR will allow us to feed in the known number of columns as the
base case.

[hail] Extend AggArrayPerElement to support a "knownLength" argument.

---

hail/python/test/hail/expr/test_expr.py
hail/src/main/resources/include/hail/NDArray.h
hail/src/main/scala/is/hail/cxx/Code.scala
hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/main/scala/is/hail/cxx/EmitTriplet.scala

~~Stride for a dimension should be calculated based off the length * stride of the previous innermost dimension with length > 1. I was remembering to do that for the stride but just taking the length of the adjacent dimension.~~
~~Length-1 dimensions have stride 0 so broadcasting happens implicitly without the need for checks while indexing into the ndarray.~~
Broadcasting was previously handled implicitly by having 0 stride for dimensions of length 1. This doesn't actually work in all scenarios and conflates the concept of a multidimensional index with the underlying representation. Since we already compute the shapes of all intermediate NDArrays before doing any iteration, we can identify broadcasting "statically". Instead, loop variables associated with a braodcast are replaced with 0 …

[bugfix][c++] fix strides for length-1 dimensions

---

hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/Compilable.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

Basically, serializes all necessary literals onto the emitted function to be decoded and used on worker nodes.

allow Literals to be emitted in generated JVM code

---

hail/python/hail/experimental/__init__.py
hail/python/hail/experimental/function.py
hail/python/hail/expr/functions.py
hail/python/hail/ir/ir.py

The SNP manipulation functions are huge and get inlined a million
times in sample_qc. This will help keep IR size down.

[hail] Add experimental udf decorator, use to register big functions

---

batch/batch/server/server.py

I think this is a good change, but we should keep in eye out, it is going to increase preemptions and restarts, and will almost certainly expose issues.  Poor man's chaos.
I will add an option to the batch interface to disable this for longer-running jobs.

allow all batch jobs to be scheduled on preemptibles

---

pipeline/pipeline/__init__.py
pipeline/setup.py

This is a temporary fix for @konradjk. A consequence of having the synchronous BatchClient be implemented asynchronously is that the event loop conflicted with the jupyter notebook event loop. The correct solution is to reimplement the synchronous batch client with the requests library. Will make an issue for that.

[pipeline] temporary fix for event loop problem in jupyter

---

batch/batch/aioclient.py
batch/batch/client.py
batch/test/test_dag.py
ci/ci/build.py
pipeline/pipeline/backend.py

I think this interface is clearer and it will be a necessary change when atomic batch creation causes the batch_id to be None until the entire batch is submitted.

[batch,ci,pipeline] change client - parent_ids -> parents

---

ci/ci/build.py

and propagate resources to docker build command
Without this, we can overload the node by running a bunch of build image jobs which tiny cpu allocations that invoke docker build which run unconstrained docker builds.  This should resolve the docker timeout issue I saw.
I allocated 2G per build job, and pass 1.5G of that to the docker build.  Just guessing on that -- I'm not sure how to figure out how much memory a docker build required.

limit resources in build image step

---

ci/ci/build.py

kubectl logs defaults to 10 lines if a selector is used:
>       --tail=-1: Lines of recent log file to display. Defaults to -1 with no selector, showing all log lines otherwise
> 10, if a selector is provided.
Add `--tail=999999` in those cases.  `--tail=-1` doesn't seem to do anything (still only get 10 lines).
If there are multiple replicas, I find logs to border on useless.  I think longer term, we want to get logs (even for tests) into centralized logging in real-time and we can replace these logging steps to links to the logging infrastructure.

[ci] add --tail=999999 for kubectl logs calls with selectors

---

apiserver/apiserver/apiserver.py
ci/ci/ci.py
docker/Makefile
gateway/.gitignore
gateway/gateway.nginx.conf
hailjwt/hailjwt/__init__.py
hailjwt/hailjwt/hailjwt.py
monitoring/.gitignore
monitoring/Dockerfile
monitoring/Makefile
monitoring/grafana-cluster.json
monitoring/monitoring.yaml
monitoring/router.nginx.conf
monitoring/router.yaml
router-resolver/Dockerfile
router-resolver/Makefile
router-resolver/deployment.yaml
router-resolver/router-resolver/router-resolver.py
router/.gitignore

Changes:
- added monitoring setup (Prometheus, Grafana) to monitoring namespace
- I'm considering monitoring part of "infrastructure", no automated tests, gateway and router-resolver changes already deployed
- authenticated_users_only always passes userdata as second argument
- added authenticated_developers_only decorator to hailjwt, no userdata
- gateway forwards to internal namespaces: internal.hail.is/namespace proxies to router.namespace, so in general you'll go to internal.hail.is/namespace/service/the/real/url
- proxy only if namespace has router service and authorized developer
- add router to monitoring namespace that proxies for prometheus and grafana
- restrict ci to authorized developers
monitoring/grafana-cluster.json is an export of an initial Grafana monitoring dashboard …

Monitoring

---

batch/batch/aioclient.py
batch/batch/client.py
batch/batch/schemas.py
batch/batch/server/server.py
batch/create-batch-tables.sql
batch/test/test_aioclient.py
batch/test/test_batch.py
batch/test/test_dag.py
ci/ci/build.py
ci/ci/github.py
pipeline/pipeline/backend.py

- Removed `close`, `is_open`, and `ttl` on batches
- Changed `create_job` and `create_batch` to be synchronous (bunch of ci code changed as a result)
- Added `submit` to batches that actually submits to request to the server
- Server still inserts records not in one transaction (future PR)
- Added some tests of operations not allowed when the batch is being created
I'm not entirely happy with the client code. I'm open to suggestions!

[batch] Change client interface

---

hail/python/hail/docs/getting_started.rst

The greater than or equal to sign wouldn't allow Conda to create the Hail environment.

Fixed Getting Started

---

hail/python/hailctl/dataproc/connect.py

This is my original `which` patch from almost a year ago repurposed for hailctl. I have been running this locally for cloudtools. Uses `shutil.which` to find `chromium` or `chromium-browser`, falling back to the macOS default if they cannot be found.

[hailctl] Attempt to find chromium before defaulting to Chrome

---

hail/python/hail/table.py
hail/python/test/hail/expr/test_show.py

We had these semantics in our interface in the past, which was
lost in the Python reimplementation.
Fixes #6122

[hail] Showing a negative number prints the whole table.

---

hail/python/benchmark/matrix_table_benchmarks.py
hail/src/main/scala/is/hail/expr/ir/IRBuilder.scala
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/rvd/RVD.scala

This was causing out-of-order keys to exist and be used in #6223. This doesn't fix that issue specifically, but it will now throw the correct error (and prevent incorrect tables/matrix tables from being written out).

[bugfix] check key ordering when isSorted = true

---

hail/Makefile

This is the style of the GNU Make docs. I slightly prefer it because it visually distinguishes Make definitions from shell definitions.

[hail] makefiles traditionally have spaces around variable defs

---

docker/core-site.xml

The hail-vdc-sa-key was (temporarily) used by apiserver, which is no longer being deployed.  When it comes back, it should either have its own service account (mounted in the standard location) or, if @akotlar user isolation stuff is ready, not use the Hadoop connector.
FYI @konradjk when this goes I'll push a new version to Docker Hub.

[docker] use standard gsa key location for Hadoop gs connector

---

hail/Makefile
site/poll-0.2.sh

The website will get updated when we deploy a PyPI version. This seems
like the best approach for now -- we don't want new functions hanging
around that people can't use. That's caused trouble in the past.
Also, it seems that from ci to ci2, we've started deploying the docs
by full revision, rather than short revision. The makefile reflects
that.

[deployment] Make docs deployment logic consistent.

---

hail/src/main/scala/is/hail/expr/ir/ExtractIntervalFilters.scala
hail/src/test/scala/is/hail/expr/ir/ExtractIntervalFiltersSuite.scala

Example:
In [11] lit = hl.literal([hl.parse_variant('1:8960153:G:A')])
In [12]: mt.filter_rows(lit.contains(mt.row_key)).count()
2019-06-10 15:28:51 Hail: INFO: reading 1 of 128 data partitions
Out[12]: (1, 284)
stacked on #6298

[hail] Extend ExtractIntervalFilters to operate on key structs 

---

hail/src/main/scala/is/hail/backend/Backend.scala
hail/src/main/scala/is/hail/backend/BackendUtils.scala
hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
hail/src/main/scala/is/hail/backend/local/LowerTableIR.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/test/scala/is/hail/TestUtils.scala

This PR should not change any of the backend functionality; it just renames some things that shouldn't be spark-specific and moves some generally-applicable code into the Backend class.

refactor backend stuff in preparation for scheduler's backend

---

hail/python/test/hail/utils/test_utils.py

the `resource` directory is `src/test/resources`, not meant for output.

[hail] Fix copy_log test to not pollute working directory

---

build.yaml
ci/ci/ci.py
ci/ci/constants.py
ci/ci/github.py
ci/ci/templates/index.html
ci/create-ci-tables-pod.yaml
ci/deployment.yaml

- add ci database with 1 table: authorized_shas
- only start build if authorized author or source_sha is authorized
- form on main page to add authorized sha,
- unauthorized PRs are created, but not tested, and shown as unauthorized in UI

[ci] support authorized shas for external PRs

---

hail/Makefile

Ran into an issue in cluster creation due to `gs://bucket/path/to/a//file` being different than `gs://bucket/path/to/a/file`. Should be fixed now.

More makefile cleanup

---

hail/python/hail/experimental/ldscsim.py
hail/python/hail/genetics/reference_genome.py
hail/python/test/hail/expr/test_expr.py
hail/python/test/hail/expr/test_types.py
hail/python/test/hail/linalg/test_linalg.py
hail/python/test/hail/matrixtable/test_matrix_table.py
hail/python/test/hail/methods/test_impex.py
hail/python/test/hail/table/test_table.py

Most are deprecation warnings related to np.matrix, some are
about invalid escape characters and resolved by using r- (raw-)
strings.

[hail] Fix a bunch of warnings generated by the tests.

---

pipeline/pipeline/backend.py
pipeline/test/test_pipeline.py

Let me know if you need the context. I don't think it's necessary and will break my interface. I didn't want the job id to be available until the whole batch is submitted and the batch id is available.

Pipeline fix verbose

---

ci/ci/build.py

We need to deploy databases which don't exist. For example, there is a new ci database that needs to be created and secrets added before the create-tables script can run.
cc: @cseed

[ci] fix ci deploy

---

pipeline/pipeline/backend.py
pipeline/pipeline/pipeline.py
pipeline/pipeline/task.py
pipeline/test/test_pipeline.py

These will be helpful when we support searching based on attributes in the Batch UI. Maybe calling it attributes would be better than tags to be consistent with k8s and batch? Also, when making this PR, I don't love the redundancy of the name argument on init and the name method for Tasks. I propose getting rid of the name method. Thoughts? 
Stacked on #6277

[pipeline] add tags

---

batch/batch/server/server.py
ci/ci/ci.py

I decided that if a batch has been deleted, then there should not be callbacks from each job finishing after the deletion (ex: always_run jobs).

[batch,ci] minor fixes to callbacks

---

hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/linalg/BlockMatrix.scala

BlockMatrix dimensions can be `Long`s but each block's dimensions are `Int`s. Need to cast Long --> Int when collecting something we know to be small enough to fit into a Java Array. Added checks before casts and  changed the signature of `BlockMatrix.random` which had no need to restrict to `Int`.
Looking at the methods in `BlockMatrixIR` like broadcast{Row, Col}Vector, would these be better implemented on the `BlockMatrix` RDDs rather than collecting?
Resolves #6325

[fix] check casts from longs to ints

---

hail/build.sbt

I asked in an SO post how to make SBT work the right way but until then we should disable fatal `-Werror` on Javac (build.sbt didn't even have the right javac option, my bad).
Pending SO question asking for help: https://stackoverflow.com/questions/56495453/how-do-i-suppress-warnings-about-the-unsafe-api-when-compiling-with-sbt
Also fix two warnings I saw in SBT but not gradle.

[hail] fix some warnings, fix SBT

---

hail/Makefile

It was missed in the previous change

Fix twine username invocation

---

hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/cxx/Emit.scala

Batch eval for tests by putting expressions in a tuple and using `Begin` for write statements. This helps dramatically by avoiding the c++ compilation time on every assert.

Speed up ndarray tests

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/expr/functions.py
hail/python/hail/expr/types.py
hail/python/hail/utils/misc.py
hail/python/test/hail/expr/test_expr.py

Couples changes:
- Explicitly convert numpy types to hail types and don't only accept numpy floats. Apparently `np.array_equal` is very relaxed and will coerce between ints and booleans so the test that should have caught this now checks the types too.
- There was a subtle bug when extracting the numpy ndarray values into python. The values were always being extracted in row-major order, regardless of their previous layout in numpy. Changed it so now `row_major` can be `None`, in which case for numpy ndarrays it will use the existing ordering and will default to row major if just entering a python list.
Note: row and column major (or in numpy terms, C contiguous and F contiguous) aren't the only options. It can be strided in a bunch of different permutations, but in these cases we read it …

[hail] Fix converting numpy ndarrays to hail ndarrays

---

batch/batch/database.py
batch/batch/server/database.py
batch/batch/server/server.py
batch/create-batch-tables.sql

I implemented `cancelled` as a join from the batch table rather than storing redundant information for each job.
@akotlar The issue was that all jobs were getting set to cancelled at the same time (and thus notifying children), so always run jobs were all getting run at once neglecting the hierarchy of job dependencies. This is the purpose of having the `cancelled` flag as separate from the `Cancelled` state and is checked in `create_if_ready`.
@cseed Can you look and see if this solves the cancel problem we discussed earlier? The faulty PR was this one: https://github.com/hail-is/hail/pull/6128/files

[batch] fix cancelled

---

notebook2/notebook/notebook.py

To prevent session cookie from being invalidated when the notebook2 leader restarts
This isn't the actual key used, but the salt for derived key.
edit: key used is generated identically:
`python -c "import secrets; import base64; print(base64.urlsafe_b64encode(secrets.token_bytes(16)))"`

[notebook2]: consistent session signing key

---

hail/python/dev-requirements.txt

Search in Sphinx 2.0.0. is known to be broken with third party themes, such as RTD. https://github.com/sphinx-doc/sphinx/issues/6244 . Sphinx 2.0.1 resolves this https://github.com/sphinx-doc/sphinx/pull/6257 .

[hail] fix search on docs

---

hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala

This PR fixes an issue in which the `entry_float_type` flag in `import_vcf` affects all floating-point fields in a VCF, including fields defined in `INFO` headers. We should have restricted it to affect only fields defined in `FORMAT` headers.
This is a rehash of #6262 due to some forked repo damage on our end.

Fix behavior of entry_float_type flag in import_vcf

---

batch/batch/server/server.py

Addresses this error:
```
ERROR   | 2019-06-17 09:41:59,615       | web_protocol.py       | log_exception:355 | Error handling request
File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 418, in start
resp = await task
File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py", line 458, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_urldispatcher.py", line 157, in handler_wrapper
result = await result
File "/usr/local/lib/python3.6/dist-packages/batch/server/server.py", line 849, in create_batch
await create_job(batch.id, userdata, job_params)
File "/usr/local/lib/python3.6/dist-packages/batch/server/server.py", line 628, in create_job
pvc_size=pvc_size)
File …
```

[batch] fix assertion error in mark_job_task_complete

---

hail/python/hail/expr/aggregators/aggregators.py
hail/python/hail/expr/expressions/base_expression.py

I removed the two default arguments so they use the same automatic sizing technology as MT and T show. I'm calling this a bugfix because it's confusing that they were different. I also doubt anyone will be broken by this change.
This also adds `n_rows` and `n_cols` which is useful for `mt.GT.show` where you want to specify a number of columns.

[hail] harmonize Expression.show with other shows

---

monitoring/Makefile
monitoring/monitoring.yaml

This is the most recently deployed version of monitoring.yaml. I'm not sure the best way to test it solves the problem that deployments faced.
One thing to note is that StatefulSets don't guarantee that all of their constituent pods get deleted when the StatefulSet is deleted. To be sure the pods all get deleted, we'd have to either manually delete them or scale the StatefulSet size down to 0 before deleting it.

Changed Grafana Deployment to StatefulSet in monitoring.yaml

---

hail/python/hail/matrixtable.py

Previously the below would display `0.GT | 1.GT` (simply the index in the entries array).
```
In [2]: import hail as hl  
...: mt = hl.balding_nichols_model(3, 100, 100) 
...: mt = mt.key_cols_by(sample_id = 'sample-' + hl.str(mt.sample_idx)) 
...: mt.show(n_rows=10, n_cols=10)                                                                                                                                                                               
2019-06-19 16:20:33 Hail: INFO: balding_nichols_model: generating genotypes for 3 populations, 100 samples, and 100 variants...
+---------------+------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+
| locus         | alleles    | sample-0.GT | …
```

[hail] if an MT is string-column-keyed, use said strings in show

---

hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala

@tpoterba this is the FunctionBuilder fix I was talking about. If two threads are both using the resulting function at the same time, having them use the same function object will result in overwriting fields and nonsensical behavior.
The only place this was really broken should be in the Encoder/Decoder---all the IR codegen calls EmitFunctionBuilder.resultWithIndex(), which does the correct thing. I fixed the base FunctionBuilder.result() to do the same thing as EmitFunctionBuilder.resultWithIndex().

[bugfix] create a new instance of F every time we want a new function result

---

batch/batch/server/server.py
batch_client/batch_client/aioclient.py
ci/ci/ci.py
hailjwt/hailjwt/__init__.py
hailjwt/hailjwt/hailjwt.py

@cseed Can you take a look at the last commit and see if this is what you envisioned by securing the api calls with headers instead of cookies?
Stacked on #6288

[hailjwt,batch,ci] Use headers instead of cookies in api calls

---

monitoring/Makefile
monitoring/monitoring.yaml

Prometheus is now a StatefulSet, removing the need to delete a deployment and sleep in the monitoring Makefile. The storage has also been bumped up to 50Gi to prevent running out of storage in the future.

Prometheus Stateful Set and Storage Bump

---

hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Instead of realizing an intermediate NDArray and switching up the shape/strides, now just map the new indices into the NDArray after a reshape to the corresponding indices prior to the reshape. Do this by converting to/from the single scalar index of an element in the NDArray (NOTE: this indexes elements in the NDArray by the row major (C) convention, but _does not_ necessarily correlate, nor is it related, to the actual memory layout)

[c++] Deforest reshape

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/ir/ExtractIntervalFilters.scala
hail/src/test/scala/is/hail/expr/ir/ExtractIntervalFiltersSuite.scala

[hail][bugfix] Fix ExtractIntervalFilter comparisons

---

docker/requirements.txt
hail/python/hailtop/gear/logging.py
hail/python/requirements.txt

I just pulled in a library specifically for json log formatting that handles escaping nicely + makes it easy to add anything else we might want to do. I've obviously not run batch locally but I've tested this code locally by running 
```from hailtop.gear import configure_logging
import logging
configure_logging()
logging.info('"Foo"')
```
We are definitely going to want more than this eventually, but this should at least let us start to break up our logs in Kibana. And it's hard to test more complicated things without some way to run my own batch.

Use JSON formatting in logs

---

hail/python/hail/ir/matrix_writer.py
hail/python/hail/methods/__init__.py
hail/python/hail/methods/impex.py
hail/python/test/hail/helpers.py
hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/io/bgen/IndexBgen.scala
hail/src/main/scala/is/hail/io/gen/ExportBGEN.scala
hail/src/main/scala/is/hail/utils/package.scala
hail/src/main/scala/is/hail/variant/HardCallView.scala

Exports BGEN 1.2 with 8 bits per probability.
Needs docs and more tests, not quite ready yet.

add export_bgen

---

hail/python/hail/docs/methods/genetics.rst
hail/python/hail/docs/methods/index.rst
hail/python/hail/expr/expressions/__init__.py
hail/python/hail/expr/expressions/expression_utils.py
hail/python/hail/methods/__init__.py
hail/python/hail/methods/statgen.py

Also added `table_source` since I couldn't find it - let me know if I missed it

[hail] add lambda GC calculation

---

batch/batch/batch.py

The previous checks for `pod is None` were intended to catch this case. We're not sure why this happens. By including the pod in the message we hope to understand the cause of nameless pods.

[batch] sometimes pod metadata name is None

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/hail/ir/base_ir.py
hail/python/hail/ir/ir.py
hail/python/hail/matrixtable.py
hail/python/hailtop/hailctl/dev/benchmark/matrix_table_benchmarks.py

Benchmark:
```python
@benchmark
def per_row_stats_star_star():
mt = hl.read_matrix_table(resource('gnomad_dp_simulation.mt'))
mt.annotate_rows(**hl.agg.stats(mt.x))._force_count_rows()
```
This branch:
```
running per_row_stats_star_star...
run 1 took 14.53s
run 2 took 16.56s
run 3 took 15.05s
Mean, Median: 15.38s, 15.05s
```
Master:
```
running per_row_stats_star_star...
run 1 took 31.47s
run 2 took 37.34s
run 3 took 26.67s
Mean, Median: 31.83s, 31.47s
```

[hail][performance] Deduplicate inlined IRs in `annotate(**thing)`

---

hail/python/hailtop/hailctl/__init__.py
hail/python/hailtop/hailctl/dataproc/start.py

in hailctl dataproc start
allows other hailctl commands to be used without being installed
This way you can set PYHTONPATH=$HAIL_HOME/hail/python and use the development version instead of the installed version (except for `hailctl dataproc start`)

[hailctl] only load deploy metadata when needed

---

image-fetcher/fetch-image.sh

To avoid this:
```sh
+ sleep 360
+ true
+ curl -sSL http://notebook/worker-image
curl: (7) Failed to connect to notebook port 80: Connection refused
```
Since notebook is not currently running

[image-fetcher] remove notebook/worker-image prefetch

---

hail/www/Makefile
hail/www/template.xslt

Currently, on mobile browsers, the home page of [hail.is](https://hail.is/) is shrunk down to the point where it's difficult to read without zooming in. This adds a [viewport tag](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag) to improve that layout.

Add viewport tag to improve home page layout on mobile devices

---

hail/python/hail/experimental/vcf_combiner.py
hail/python/hail/table.py
hail/python/test/hail/table/test_table.py

[hail] Publicize and document Table.multi_way_zip_join

---

hail/python/hailtop/hailctl/dev/benchmark/matrix_table_benchmarks.py

Pretty horrible performance.
Most of the time is spent in the IR evaluation to annotate entries:
```
(Let __iruid_65
(InsertFields
(Ref row)
None
(`the entries! [877f12a8827e18f61222c6c8c5fb04a8]`
(ArrayMap __iruid_66
(ArrayRange
(I32 0)
(I32 10)
(I32 1))
(Literal Struct{} <literal value>))))
(InsertFields
(Ref __iruid_65)
None
(`the entries! [877f12a8827e18f61222c6c8c5fb04a8]`
(ArrayMap __iruid_67
(ArrayRange
(I32 0)
(ArrayLen
(GetField __cols
(Ref global)))
(I32 1))
(InsertFields
(ArrayRef
(GetField `the entries! [877f12a8827e18f61222c6c8c5fb04a8]`
(Ref __iruid_65))
(Ref __iruid_67))
None
(x
(ApplyBinaryPrimOp Add
(GetField col_idx
(ArrayRef
(GetField __cols
(Ref global))
(Ref __iruid_67)))
(GetField row_idx
(Ref __iruid_65)))))))))))
```

[benchmark] Add benchmark for range_matrix_table write

---

batch/batch/batch.py
batch/deployment.yaml

Did a local test of prometheus_async on a tiny aiohttp server, turns out the order of the decorators does matter. The timing decorator has to be on the bottom to actually time anything successfully. Does the order of any of the other decorators matter?

Reordered the decorators so timings actually work

---

letsencrypt/domains.txt
router/Makefile
router/get-deployed-sha.sh
router/router.nginx.conf.in
ukbb-rg/Dockerfile.browser
ukbb-rg/Dockerfile.static
ukbb-rg/Makefile
ukbb-rg/deployment.yaml
ukbb-rg/shiny-server.conf
ukbb-rg/static.nginx.conf

Hand deployed (currently running).  Only visible change is to router, add proxy rules from ukbb-hail.is to the ukbb-rg servers.  The web site has two parts: static HTML served by nginx and a interactive, data-driven Shiny site run by R/shiny/shiny server.  Servers run as stateful sets.  Static HTML and 
data for Shiny were hand-populated.
Currently giving them each one core.  Given how much state is involved here, it's not clear how to autoscale this like we do with the other services.

Add ukbb rg browser

---

hail/Makefile
hail/python/setup.py

This works better with my environment and it means that, e.g., Brandon, only needs Java and python set up correctly to run: `git clone ... && cd hail/hail && make pytest`. No environment variables, no packages to install.

[hail] add make install-editable and pytest

---

hail/python/hail/ir/ir.py
hail/python/hail/matrixtable.py
hail/src/main/scala/is/hail/expr/ir/functions/RelationalFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/TableCalculateNewPartitions.scala

Uses a similar method to RVD.coalesce to calculate the new bounds.
Requires a quick scan of the data but no shuffles.

Expose a range bounds calculator

---

hail/python/cluster-tests/cluster-vep-check.py

The new VEP results have some new ANC_ALLELE field not present in the
"truth" dataset.

[testing] Disable VEP cluster test until mismatch is resolved

---

batch/batch/batch.py

Also only start jobs once a batch is closed.

[batch] make create, delete, close not linear in jobs

---

hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/backend/Backend.scala
hail/src/main/scala/is/hail/backend/BackendUtils.scala
hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/CompileAndEvaluate.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/ExtractAggregators.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/TableValue.scala
hail/src/main/scala/is/hail/utils/Graph.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/annotations/StagedRegionValueSuite.scala
hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala
hail/src/test/scala/is/hail/variant/ReferenceGenomeSuite.scala

Cloud providers don't want you to know this one weird trick to save
thousands on your compute bill
This PR:
```
Running matrix_table_array_arithmetic...
run 1: 18.28
run 2: 15.26
run 3: 14.76
```
Master:
```
Running matrix_table_array_arithmetic...
(I waited 30 minutes and the first partition still hadn't finished...)
```
Lower bound: 900x faster

[hail][performance] Fix literals lazy decoding

---

ci/ci/build.py

I need this for the auth stuff.  Basically, in each namespace created by a createNamespace step, we create a service account called `admin` and give it the admin role for the namespace.

[ci] add admin account to created namespaces

---

hail/python/hailtop/hailctl/dev/benchmark/cli.py
hail/python/hailtop/hailctl/dev/benchmark/run/cli.py
hail/python/hailtop/hailctl/dev/benchmark/run/table_benchmarks.py
hail/python/hailtop/hailctl/dev/cli.py
hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala

When using indexed reads, we were creating a new partitioner for every
partiton in tmpPartitioner. It was not good.

[hail] use val for IndexedRVDSpec partitioner

---

ci/ci/build.py

I accidentally deleted this dividing line when I reorganized the namespace creation step.

Adding the missing divider to the generated yaml for namespace creation

---

batch/batch/batch.py

Made a mistake in #6569 . mark_deleted has to wait for cancel to finish. otherwise, the cleanup loop can delete a half cancelled batch.

[batch] fix delete

---

hail/src/main/scala/is/hail/io/RowStore.scala

It is currently possible to write a blocked index where the virtual file
offset is exactly ((REAL_FILE_OFFSET << 16) | BLOCK_SIZE). This is a bug
and leads to assertion errors when trying to seek to the appropriate row
because `off == end` for that index.

[hail] fix BlockInputBuffer seek assertion

---

ci/ci/build.py

I messed this up, forgot the namespace on the admin account, so they were all going into the current namespace (bach-pods).  Oops.

set namespace on admin account

---

hail/src/main/scala/is/hail/annotations/Region.scala

I've left all the instances of `region.loadX` untouched (and left the methods on the region object, but this should let us avoid piping through region objects when we just need to read something.
(Broken out from #6580)

move load/store methods onto Region object

---

hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Works pretty much like Read/Write, except serializes to/from a fixed number of byte array slots on the function object. Not *super* happy with this design, but I'm using it in the new TableMapRows implementation to avoid reading/writing all the aggregations to a file.
(Broken out from #6580)

implement SerializeAggs/DeserializeAggs

---

hail/src/main/scala/is/hail/methods/PCA.scala
hail/src/main/scala/is/hail/rvd/RVD.scala

fixes #6236
instead of calling `SafeRow` to manifest the entire row and then pick out the keys, create `UnsafeRow`s and then copy only the keys.
added `RVD.toUnsafeRows`

[hail] only convert row keys into Java objects in PCA

---

hail/python/hail/matrixtable.py
hail/python/hail/methods/statgen.py

When I timed the specific code block we hid behind the flag, it took
about 1.5 seconds on the benchmark dataset.
This check scales linearly with the number of samples, though, which is not great.

[hail] Parameterize check on union_rows. Don't check in `split_multi`

---

ci/ci/build.py
ci/ci/ci.py
ci/ci/github.py
hail/python/hailtop/hailctl/dev/deploy/cli.py

Currently, dev deploy always eventually returns a timeout in the terminal because it tries to wait for the entire batch deploy / tests to run before returning. Now it will just create the batch and return the batch number instead of waiting.

dev deploy dont wait for batch

---

notebook/notebook/notebook.py

CVE-2019-11245 is a vulnerability in k8s that causes some (all?)
containers without a runAsUser configuration to run
as user id 0, i.e. root. Jupyter refuses to start as root.
This change enables Jupyter to start successfully.

[notebook] mitigate CVE-2019-11245

---

hail/python/hail/utils/misc.py

One of our sillier calls to the JVM, plus reordering some imports so pylint stops complaining.

No more JVM for URI parsing

---

hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

(Last piece from #6580.)
Implements Extract and new path for TableMapRows, which is used by default but can be turned off. (This piece has not really fundamentally changed since the beginning.)

Extract staged aggregators

---

hail/python/hail/utils/misc.py

This PR fixes `_dump_partitions()` to transcribe the `includes_start` and `includes_end` flags in locus intervals specified through `import_vcfs()`. As the code stands, `_dump_partitions()` hard-codes `includes_end` to `False`, which eventually yields a "bounds must be inclusive" exception.

Fixed _dump_partitions to correctly transcribe includes* flags

---

hail/python/hail/expr/types.py
hail/python/test/hail/expr/test_types.py

I could also add checks to `_insert_field`, but currently it looks like the ability to overwrite an existing field is intended.
`tunion` already makes it impossible to overlap field names
fixes #6409

Verify field uniqueness when renaming fields of tstruct

---

hail/src/main/scala/is/hail/annotations/CodeOrdering.scala
hail/src/main/scala/is/hail/annotations/Region.scala
hail/src/main/scala/is/hail/expr/ir/BinarySearch.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala
hail/src/main/scala/is/hail/expr/types/physical/PBaseStruct.scala
hail/src/main/scala/is/hail/expr/types/physical/PBinary.scala
hail/src/main/scala/is/hail/expr/types/physical/PBoolean.scala
hail/src/main/scala/is/hail/expr/types/physical/PFloat32.scala
hail/src/main/scala/is/hail/expr/types/physical/PFloat64.scala
hail/src/main/scala/is/hail/expr/types/physical/PInt32.scala
hail/src/main/scala/is/hail/expr/types/physical/PInt64.scala
hail/src/main/scala/is/hail/expr/types/physical/PInterval.scala
hail/src/main/scala/is/hail/expr/types/physical/PLocus.scala
hail/src/main/scala/is/hail/expr/types/physical/PString.scala
hail/src/main/scala/is/hail/expr/types/virtual/TInt32.scala
hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala

Slowly getting rid of the regions being threading through non-allocating functions, part i + 1.
This changes the method signature of CodeOrdering method signatures from f(region1, v1, region2, v2) to f(v1, v2). Some other function signatures (e.g. PInterval.loadStart) were also updated as necessary. No functionality has been changed.

yoink regions out of CodeOrdering method signatures

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/agg/ArrayElementLengthCheckAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/CountAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
hail/src/main/scala/is/hail/expr/ir/agg/PrevNonNullAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/StagedAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/SumAggregator.scala
hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala

- rewrite ArrayElements.initOp to take nested initOps as arguments directly
- pass in EmitTriplet instead of RVAVariable; get rid of RVAVariable
- StagedRegionValueAggregator -> StagedAggregator, since doesn't always use RVs
- refactor tests to be more extensible for new aggregators

some cleanup to staged aggregators

---

batch/batch/sidecar.py

If we miss an event, the refresh loop won't find it because it errors.

[batch] minor problem in sidecar

---

hail/src/main/scala/is/hail/annotations/UnsafeRow.scala
hail/src/main/scala/is/hail/backend/LowerTableIR.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala
hail/src/main/scala/is/hail/expr/types/physical/PString.scala
hail/src/main/scala/is/hail/methods/VEP.scala
hail/src/main/scala/is/hail/methods/WindowByLocus.scala
hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/main/scala/is/hail/stats/LinearMixedModel.scala
hail/src/main/scala/is/hail/table/Table.scala
hail/src/main/scala/is/hail/utils/TextTableReader.scala
hail/src/main/scala/is/hail/variant/MatrixTable.scala

Usages of `physicalType` remain in four places:
- in/around aggregators
- tests
- a few stray TableIR nodes
- at the boundary of encoding/decoding

[hail] (PTypes) Remove more usages of `physicalType`

---

batch/batch/batch.py
batch/test/test_batch.py

Without this change, it is very annoying to copy and manipulate the result.

[batch] display pod statuses as JSON not python dict

---

hail/python/hail/matrixtable.py
hail/python/hail/table.py
hail/python/test/hail/matrixtable/test_matrix_table.py
hail/python/test/hail/table/test_table.py

also changes the error message to display `<<<empty key>>>` as the list of keys
fixes #6663

Fix error message when indexing into (Matrix)Tables without keys

---

hail/python/hail/expr/aggregators/aggregators.py
hail/python/test/hail/expr/test_expr.py

The sources for agg transformations weren't being recorded correctly for transformations of hl.agg.count(). This wasn't a problem for e.g. a single-level hl.agg.group_by(key, hl.agg.count()), but was throwing errors when that was nested within other transformations.

Fix aggregator source propagation for transformations of hl.agg.count

---

hail/src/main/scala/is/hail/expr/ir/agg/ArrayElementLengthCheckAggregator.scala
hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala

Nested array element aggregations weren't working. This fixes it and adds a test for nested ArrayAggs. Caught by test failures from #6698.

fix nested array aggregators

---

hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
hail/src/main/scala/is/hail/rvd/RVD.scala

Renamed agg->aggArgs in Interpret to avoid name collision.

lift TableAggregate to new aggregator path

---

hail/python/hail/docs/methods/index.rst

Only 3 of the 7 methods appear here: https://hail.is/docs/0.2/methods/index.html
Though they all appear here: https://hail.is/docs/0.2/methods/stats.html

add missing stats methods

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/ir/Simplify.scala

`hl.desc` sorts could be instead sorted ascending in some cases.

[hail] [bugfix] Fix correctness bug in Table.order_by optimization

---

hail/python/setup.py

This is required to run `setup bdist_wheel`, and is not in the standard
library.

[dev] Add `wheel` to setup dependencies

---

hail/python/hailtop/hailctl/dataproc/connect.py

Unfortunately, Google changed the way to connect to Spark UI, and now makes you either go through the YARN UI or use the Spark history page. This PR changes our Spark UI commands in `hailctl dataproc connect` to use the spark history page instead, since that works. The regular `spark-ui` command will show you running jobs, the `spark-history` command will show you finished jobs. I don't know what ui1 and ui2 were, but they're no longer usable so I removed them.

Fixed spark ui commands

---

hail/src/main/scala/is/hail/annotations/Region.scala
hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/types/physical/PBaseStruct.scala
hail/src/main/scala/is/hail/io/RowStore.scala
hail/src/test/scala/is/hail/annotations/UnsafeSuite.scala
hail/testng-cpp-codegen.xml

The Encoder/Decoder methods weren't handling non-struct values correctly (this is mostly fine from an Encoder/Decoder perspective, since they don't handle non-struct/array values). I fixed this in #6727 because I wanted to encode arbitrary values, and changed EmitPackDecoder/EmitPackEncoder to handle arbitrary values so that I could test this.
I also pulled out some more peripheral changes from that PR, mostly defining some (currently unused, untested) methods like `Code.orEmpty` and a version of `newMethod` that lets you give the method a real name for ease of debugging, as well as some more changes to move more load/store methods off of region instances and onto the Region object.

fix encode/decode of non-wrapped values, some other refactoring changes

---

hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala

argument order to `storeAddress` was reversed, which could cause a segfault

Fix SRVB.deepCopy(er, typ, src, dest)

---

ci/ci/build.py

None is an unfortunate default for a list of dependencies.

deps should be empty if there aren't any

---

hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala

This PR makes the BlockMatrixNativeReader's type a lazy val so that it doesn't keep going to disk. 
4800x speedup on my filtering and exporting 300 block matrices example.

Cache blockmatrix type

---

ci/ci/ci.py

This fixes an issue where we cannot retrieve old batches for a PR.
Addresses this error:
```
{"levelname": "ERROR", "asctime": "2019-08-01 15:59:17,119", "filename": "web_protocol.py", "funcNameAndLine": "log_exception:355", "message": "Error handling request", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py\", line 418, in start\n    resp = await task\n  File \"/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py\", line 458, in _handle\n    resp = await handler(request)\n  File \"/usr/local/lib/python3.6/dist-packages/aiohttp/web_urldispatcher.py\", line 157, in handler_wrapper\n    result = await result\n  File \"/usr/local/lib/python3.6/dist-packages/aiohttp_jinja2/__init__.py\", line 91, in wrapped\n …
```

[ci] filter out None

---

hail/python/hailtop/hailctl/dev/benchmark/run/matrix_table_benchmarks.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala
hail/src/main/scala/is/hail/expr/ir/agg/CountAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/SumAggregator.scala

This isn't needed any more, since setAggState() and newAggState() do the right thing when called.
At least on my laptop, this brings the one test down to 
```
Name	Mean	Median	StDev
matrix_table_many_aggs_col_wise	24.275	24.372	0.818
```
vs with the flag disabled, which is 
```
Name	Mean	Median	StDev
matrix_table_many_aggs_col_wise	30.147	29.706	1.868
```
(oops)

don't check if agg states are loaded

---

batch/batch/batch.py

I don't really understand how this happens, but it happens. The callees of this method already handle the case that the database has no job, so adding another `return None` is fine. It will result in this pod getting deleted, which seems reasonable since it is missing necessary labels.

[batch] handle missing labels

---

batch/batch/batch.py

We apparently did not exercise this code path much before I fixed batch to treat ImagePullBackOff as failure.
Really confusing error message because `write_gs_file` returns `None` which is not iterable so you get a type error on line 565. The real issue is that you're trying to deconstruct a pair as `uri, err` and you received `None`.

[batch] address latent bug

---

batch/batch/batch.py

Without this fix, we almost never release the semaphore

[batch] always use throttler to delete pods

---

batch/batch/batch.py
batch/batch/throttler.py

The separation makes that metric more accurate. Moreover, I check the queue before rescheduling. This saves a database call, a kubernetes call, and set churn (we remove then add back the job).

[batch] separate eviction from missing pod, check queue before rescheduling

---

batch/batch/batch.py

I do not know what these are, but they generally have broken schemas
which break assumptions elsewhere in the code. Just skip them.

[batch] skip ERROR events

---

ci/ci/ci.py

Before this change we got an array of strings rather than
several lines

[ci] improve formatting of build errors

---

hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

This is currently just dead code, although it could conceivably be useful in the future; I want to remove this for now as it's pretty simple to add back in at a later date (follows the pattern of Serialize/Deserialize Aggs pretty much exactly) and makes for less code to keep refactoring as we optimize the aggregator stuff.

remove Read/Write Aggs

---

ci/ci/build.py

Small amount of preliminary work #6673. I made a PR trying to address this issue already, but ended up reverting it because it broke CI and we don't test that well. To minimize frustration, I'm making some initial changes here first. 
Namely:
- Steps have an equality and hash method based solely on their name (I'm going to want to build a hash map of steps when coming up with dependencies for the cleanup jobs. 
- Cleanup now takes a list of parents, instead of just the sink job (useful for when there are more parents than just the sink job).

Cleanup Before Removing Sink

---

hail/python/hailtop/hailctl/dev/benchmark/run/table_benchmarks.py

This is segfaulting.
See #6793

[benchmark] Turn off read_with_index benchmark.

---

monitoring/monitoring.yaml

As discussed at team meeting today, filebeat needs a toleration to run on preemptibles.

filebeat should run on preemptibles

---

hail/src/main/scala/is/hail/expr/ir/agg/StagedArrayBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/TakeAggregator.scala
hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala

`builder.loadFields` just loads the offset of the data array, but it needs to do a deep copy otherwise all of the array aggragators will start off writing to (and overwriting) the same arraybuilder.

fix agg take

---

hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala
hail/src/main/scala/is/hail/expr/ir/agg/ArrayElementLengthCheckAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/CountAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/PrevNonNullAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/StagedAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/StagedArrayBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/SumAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/TakeAggregator.scala

no method wrapping, but this way we can start to/we stop passing around the wrong method everywhere.

mb -> fb in staged aggregators

---

hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/PrevNonNullAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/StagedArrayBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/TakeAggregator.scala

the way it worked previously seemed kind of counterintuitive because we were using the offset instead of the actual value, like the actual rvb stuff does.

have srvb.addWithDeepCopy take value instead of offset

---

hail/python/hail/docs/getting_started.rst
hail/python/hail/docs/getting_started_developing.rst

We should have documentation about our expectations about versions of C compiler. Plus, we don't need R for dev testing anymore.

Adding GCC/Clang Requirement to Docs, Removing R

---

notebook/notebook/notebook.py

- delete all workers never worked because it thought the objects were names, that's fixed.
- if we don't get a successful response (i.e. 502) we shouldn't break, we should loop and try again, the same as if we got an exception, in either case we should sleep briefly

[notebook] fix some simple problems

---

batch/batch/throttler.py

Two big changes.
Catch any errors and release the semaphore.
Restart failed workers in the concurrent worker pool.

[batch] more reslience in pod throttler

---

notebook/scale_test.py

You can run this as `python3 scale_test.py 120` to simulate 120 clients simultaneously creating notebooks. You have to delete the notebooks yourself using the admin account or manually killing them in k8s.
This isn't actually used anywhere (notebook isn't deployed by CI), but I want it in our repository. At some point we should productionize notebook.

[notebook] scale tester

---

hail/Makefile

This is a start at making more of the Makefile not phony.
$ make
./gradlew shadowJar
$ make
make: Nothing to be done for 'shadowJar'.

[hail][build] Make several targets not PHONY

---

hail/python/hailtop/hailctl/dev/benchmark/run/table_benchmarks.py
hail/src/main/scala/is/hail/io/index/IndexReader.scala

Was causing segfaults in the read_with_index_p1000 benchmark.
closes #6793

[bugfix] Remove region.close in IndexReader

---

batch/Dockerfile.test
build.yaml
docker/requirements.txt
pipeline/Dockerfile.test

> pytest-instafail is a plugin for py.test that shows failures and errors instantly instead of waiting until the end of test session.
https://github.com/pytest-dev/pytest-instafail/

[hail][pipeline][batch] add pytest-instafail to base-image and pervasively use it

---

hail/python/hail/matrixtable.py

They self-referenced instead of referencing the dual method.

[hail] fix docs for anti_joins_rows and _cols

---

ci/ci/github.py

Otherwise, everytime we refresh from batch, we think we have a
new state and the timestamps are useless
This is why most of our timestamps look the same.

[ci] only update timestamp if new state

---

batch/Dockerfile.test
batch/batch/batch.py
batch/batch/sidecar.py
batch/test/test_dag.py
docker/requirements.txt
pipeline/Dockerfile.test

It's a shame that we have to restart a whole job just because GCP's authentication servers hiccuped. This change retries the auth once if it fails after a random wait of [5, 10) seconds.

[batch] a little gcloud auth resilience

---

hail/.gitignore
hail/Makefile
hail/env_var.mk

Suppose you have two branches with the same base commit. Neither branch has Scala changes. Consider `make shadowJar` when switching between these branches: it thinks there's nothing to do because the Scala code hasn't changed.
This of course doesn't work because the python version *is* changing (note: make install-editable refreshes the version files) and Hail refuses to use an out of date jar.
This adds a tiny make macro that lets make targets depend on variables that depend on the latent environment, like git SHAs. To create a target for such a variable add this line: `$(eval $(call ENV_VAR,VARIABLE_NAME))`. Any rule that depends on the value of `VARIABLE_NAME` should depend on the target `env/VARIABLE_NAME`.
I also split `BUILD_INFO` into the scala parts and the python parts and moved …

Fix makefile

---

build.yaml

Spinning up a VM takes around two minutes. Downloading fresh container images
takes additional time, maybe a whole minute.
The cost of timing out is high: an otherwise passing PR test run may fail
demanding a bump and delaying merging of said PR by fifteen to twenty minutes.
The cost of waiting two more minutes is that a resource deadlock may last
two extra minutes. We address deadlocks by scaling up and limiting concurrent
PR tests to four.

[ci] wait for at least four minutes

---

hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala

@chrisvittal I don't know if this fixes Laurent's issue, since I haven't been able to reproduce it, but it seems like this is the desired behavior anyways.

[bugfix] read partion aggs in loop during scan

---

hail/python/hail/experimental/sparse_split_multi.py

Try to give the user information about the failure.
A follow up to this is to give a mode to ignore the error, and filter the variant.

Add better sparse split multi error message

---

hail/python/hail/expr/functions.py
hail/python/test/hail/expr/test_expr.py

If all data is missing, `approx_cdf` computes an empty `values` array. We just need to check that case, and return `NA` quantiles.

fix approx_quantiles on all-missing data

---

hail/python/test/hail/matrixtable/test_matrix_table.py
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala

The `MatrixEntriesTable` lowering rule was broken. It fails when the input `MatrixTable` has multiple key fields, which appear out of order in the row struct.
`MatrixEntriesTable` has to do an `TableAggregateByKey`, which makes a table with row type `Struct{keyFields..., aggResult}`. In particular, it rearranges the key fields to the key order. Then the later
```scala
mapRows('row.dropFields(toExplode).insertStruct('row (toExplode),
ordering = Some(x.typ.rowType.fieldNames.toFastIndexedSeq)))
```
fails, because it tries to put the key fields back in their original order.
I've fixed this by changing the above line to a `mapRows(makeStruct(...))`, but I don't see any good reason for the restriction that `InsertFields` must preserve the relative ordering of old fields.
Another fix, which I …

Fix MatrixEntriesTable lowering

---

hail/python/hail/ir/table_ir.py
hail/python/hail/methods/statgen.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/Compilable.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/functions/RelationalFunctions.scala
hail/src/main/scala/is/hail/methods/PCRelate.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/methods/PCRelateSuite.scala

- clean up PCRelate
- BlockMatrixToTableFunction
- BlockMatrixToTableApply

[hail] dedicated IR node for PCRelate

---

hail/Makefile

I like the != syntax but it is not supported by the Make shipped
with recent OS X versions, so I think we should avoid it.

[hail] avoid != in Makefile

---

batch/batch/batch.py

When we retrieve a live pod status, we recieve a V1Pod object from the k8s
API. The `json` library does not know how to convert that to a JSON object.
This change makes the return type of `Job._read_pod_statuses()` uniformly
`dict`.

[batch] convert V1Pod to dict before sending to json encoder

---

hail/python/hail/experimental/sparse_split_multi.py

This should hopefully save on computing things like downcasts for hom-refs.

Add hom-ref short circut to sparse_split_multi

---

batch/batch/cleanup_sidecar.py

Print the output of the cleanup sidecar when the exit code is non-zero.

[batch] better error message

---

hail/python/hail/expr/types.py
hail/python/hail/utils/linkedlist.py
hail/python/hail/utils/struct.py

We were getting warnings of the form:
`DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`
because Python has moved abstract collections like `Iterable` from `collections` to `collections.abc`. We still get some warnings from packages we depend on, but I've addressed all instances of this I saw warnings for in our hail python code.

Responded to deprecations of abcs in toplevel collections module

---

hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala

If we're using a TableKeyBy to go from e.g. `[locus, alleles]` to `[locus]`, the requested type of the child node shouldn't have an empty key---we should preserve the necessary keys since they already exist.
Would love a glance from @patrick-schultz and @tpoterba to double-check that this is correct.

preserve valid keys in TableKeyBy pruning

---

hail/python/hail/docs/getting_started.rst

Our releaseJar example should not use Spark version 2.3.0 when we don't actually want users to use that version

Update example releaseJar to use Spark 2.4.0

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/agg/AppendOnlyBTree.scala
hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
hail/src/main/scala/is/hail/expr/ir/agg/GroupedAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/TakeAggregator.scala
hail/src/main/scala/is/hail/expr/types/physical/PBaseStruct.scala
hail/src/main/scala/is/hail/io/RowStore.scala
hail/src/main/scala/is/hail/utils/richUtils/RichCodeOutputBuffer.scala
hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
hail/src/test/scala/is/hail/expr/ir/StagedBTreeSuite.scala

The way I ended up structuring this:
There's an AppendOnlyBTree type, which has keys of a certain type (BTreeKey). The BTree relies on this key type to know how to manage memory and what type to use for the comparison key. The BTree knows how to do three things:
- initialize an empty tree with one node
- get the address of a key corresponding to a certain comparison key, inserting and initializing an empty key if no matching key is found
- traverse the keys of the btree and do something with them
- deepCopy itself using the deepCopy defined by the BTreeKey.
The BTreeKey must know:
- the storage type within the BTree
- how to initialize itself, and whether or not it's empty
- the type of the comparison key
- a comparison function between two BTreeKeys 
- and one between a BTreeKey and a …

staged GroupBy aggregator

---

batch/test/test_batch.py
batch/test/test_dag.py
ci/ci/build.py
ci/ci/github.py

Dev deploy is currently broken, this should hopefully fix. Issue is that we were treating the name of a step like it was a step object. I am calling the argument `requested_step_names` now to help keep track of the distinction. 
@jigold @cseed

Requested step names -> Requested Steps

---

hail/python/hail/genetics/reference_genome.py
hail/python/test/hail/genetics/test_reference_genome.py

If we want to stop storing user-defined reference genome information on our global HailContext in Scala, we'll need to also track liftover and sequence information in Python.

[hail] keep sequence and liftover filenames in python

---

gateway/Makefile
gateway/deployment.yaml
gateway/gateway.nginx.conf
monitoring/router.nginx.conf
router/router.nginx.conf.in

OK, this should fix routing from internal.hail.is.  The gateway routes internal.hail.is/ns/svc to router.ns with Host: svc.internal so the ns router can dispatch to the right server block off the Host.  We could dispatch off the URL, but that would mean the default and private namespaces dispatch different, doubling the complexity of the router NGINX configuration.  Change the host back for grafana and prometheus which generate a redirect otherwise.
The monitoring and gateway changes are deployed and everything seems to be working.

fix routing from internal.hail.is

---

ci/ci/ci.py
ci/ci/templates/batch.html
ci/ci/templates/job_log.html
ci/ci/templates/job_pod_status.html
ci/ci/templates/pr.html

- add pod_status page and add link to all places we link the log
- make historical batches look the same (use emoji, colors, etc.) as the current batch for a pr
- link back to the batch from a job
- link to the GitHub PR page from the CI PR page
- banish tabs

[ci] UI improvements

---

hail/src/main/scala/is/hail/rvd/RVD.scala

Previously, we ignored the fast keys which required
reading all the data of the RVD to get the keys.
There does not appear to be any users of this method
other than `import_plink`.

[hail] improve performance of import_plink

---

hail/python/hail/methods/statgen.py

[docs] Fix reference to `Struct` in `split_multi_hts` docs

---

hail/python/hail/expr/aggregators/aggregators.py
hail/python/hail/ir/ir.py
hail/src/main/scala/is/hail/expr/ir/ExtractAggregators.scala
hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala

[hail] Fix performance problems in aggregators by binding arguments

---

hail/python/requirements.txt

In noticed this was missing when I tried to run the benchmarks, which use pipeline.

[hail] pin aiohttp, add aiohttp_session

---

batch/batch/batch.py

- introduce job logging methods that automatically include id, state, and pod name
- add `reap_job` state update logic into `new_state`, use `new_state` in `reap_job`
- remove unused function `refresh_parents_and_maybe_create`, which lead to more dead code which was also removed

[batch] improve logging, remove dead code, unify code

---

batch/batch/batch.py
batch/batch/batch_configuration.py

1. log should include job id not job
2. `client_session` is only used for k8s-internal requests to worker pods, so
use a very aggressive timeout of 10s
3. reduce refresh delay to two minutes

[batch] various improvements re: benchmark

---

hail/python/hail/expr/matrix_type.py
hail/python/hail/expr/table_type.py
hail/python/hail/ir/__init__.py
hail/python/hail/ir/base_ir.py
hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/ir/ir.py
hail/python/hail/ir/matrix_ir.py
hail/python/hail/ir/table_ir.py
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala

This is the stuff I had to add to the python IR hierarchy for the CSE pass. Some of it feels a bit hacky; I would welcome suggestions on ways to clean it up.

Python IR binding and environment infrastructure

---

hail/Makefile

Apparently Hail needs to be installed even to build the docs without tests? I don't know why but I ran into this today. Seems wrong that we need it installed to build the docs, but 🤷‍♂

[hail] fix make docs-no-test

---

auth/auth/auth.py
auth/create-accounts-pod.yaml
hail/python/hailtop/gear/__init__.py

Without this change, you cannot import hailtop on any non-
developer machine (i.e. a machine with the dev-requirements).

[gear] teach gear to not always depend on aiomysql

---

hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/types/physical/PNDArray.scala
hail/src/main/scala/is/hail/expr/types/physical/PStruct.scala

This PR:
- Introduces mapping over NDArrays in JVM emitter. 
- Introduces the `NDArrayEmitter` class, mimicking the cxx analogue. This class is used as the basis of our `NDArray` deforesting efforts (see `emitLoops`)
- Fixes a bug in `PStruct`'s load field function. 
- Introduces useful helper functions on `PNDArray`: `numElements` and `makeDefaultStrides`
Ready for review

NDArray Map

---

hail/src/main/scala/is/hail/annotations/Region.scala

Master:
```
2019-09-11 21:59:10,002: INFO: [1/1] Running split_multi_hts...
2019-09-11 21:59:44,299: INFO:     burn in: 34.29s
2019-09-11 22:00:15,875: INFO:     run 1: 31.57s
2019-09-11 22:00:47,900: INFO:     run 2: 32.02s
2019-09-11 22:01:19,140: INFO:     run 3: 31.24s
```
PR:
```
2019-09-11 21:56:22,833: INFO: [1/1] Running split_multi_hts...
2019-09-11 21:56:49,639: INFO:     burn in: 26.80s
2019-09-11 21:57:12,559: INFO:     run 1: 22.92s
2019-09-11 21:57:34,842: INFO:     run 2: 22.28s
2019-09-11 21:57:57,300: INFO:     run 3: 22.45s
```

[hail] Implement memset with a while loop

---

batch/test/test_aioclient.py
batch/test/test_batch.py
batch/test/test_dag.py
ci/ci/ci.py
hail/python/hail/backend/backend.py
hail/python/hailtop/auth/__init__.py
hail/python/hailtop/auth/auth.py
hail/python/hailtop/auth/tokens.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py
hail/python/hailtop/config/deploy_config.py
hail/python/hailtop/hailctl/auth/auth_list.py
hail/python/hailtop/hailctl/auth/cli.py
hail/python/hailtop/hailctl/auth/login.py
hail/python/hailtop/hailctl/auth/logout.py
hail/python/hailtop/hailctl/batch/cli.py
hail/python/hailtop/hailctl/dev/config/cli.py
hail/python/hailtop/hailctl/dev/deploy/cli.py
hail/python/hailtop/pipeline/backend.py
hail/python/test/hailtop/gear/test_deploy_config.py

Stacked on: https://github.com/hail-is/hail/pull/7031
Changes:
- primary change was to add `Tokens.namespace_token_or_error` which prints a friendly error of the user doesn't have the necessary authentication
- added `hailctl auth list`, and made `hailctl dev config` with no options print out the current configuration
- implemented @danking's suggestion: change some natural entrypoints (BatchClient, get_userinfo, etc.) to take optional `deploy_config` argument and load the default config if not given

[hailctl] generate a friendly error message if not authenticated

---

notebook/images/isia/Dockerfile
notebook/notebook/notebook.py

A few things.
- app.secret_key was never used, it was an old hold over from the flask style of doing HTTP session cookies. When I translated notebook, I accidentally made it generate a new secret key every time it started up. This PR fixes it to use the secret key in the notebook secret.
set the default image to isia
- fix the URL redirect when you go to notebook.hail.is with a preexisting session. I screwed this up when I switched to aiohttp. You're not supposed to put query parameters in yourself, you're supposed to use with_query. What I did URL encoded the ? so it wasn't treated as a query parameter it was treated as a file with a literal ? in the name.
- the router (see router/router.nginx.conf.in) treats 502 and 504 as if the pod was dead which redirects to the login page and …

[notebook] fixes to notebook

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/test/scala/is/hail/expr/ir/LocusFunctionsSuite.scala

Fixes #7063.
I forgot to change the cached methods in Emit to account for return type when I changed it to allow a single function to specify multiple return types.

[hail][bugfix] account for return type when caching methods in Emit

---

hail/python/hailtop/hailctl/dev/benchmark/run/table_benchmarks.py
hail/src/main/scala/is/hail/expr/ir/Simplify.scala

At some point we started optimizing the MakeStruct to a SelectFields,
which is great, but not if it breaks important optimizations like the
avoid-a-shuffle rewrite rule!

[hail] Extend TableKeyByAndAggregate => TableAggregateByKey rewrite

---

hail/src/main/scala/is/hail/expr/ir/agg/GroupedAggregator.scala

i'm only partially sure this is correct but i believe it is. `+1` to `nStates` didn't really make sense, and this causes my collect agg to work

[hail] fix setNumParents bug in GroupedAggregator

---

docker/requirements.txt
hail/python/requirements.txt

Currently, the notebook scale tests are broken by this.
Aiohttp [has a bug in 3.5](https://github.com/aio-libs/aiohttp/issues/3700) that incorrectly handles cookies in 302 redirects. The master commit was cherry-picked into 3.6.0.

[hail][etc.] Update aiohttp version to avoid bug

---

hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/asm4s/joinpoint/JoinPoint.scala
hail/src/main/scala/is/hail/asm4s/joinpoint/ParameterPack.scala
hail/src/main/scala/is/hail/asm4s/joinpoint/package.scala
hail/src/test/scala/is/hail/asm4s/JoinPointSuite.scala

This PR implements a "join-point" abstraction for the JVM backend. Join-points are a primitive
control flow construct that allow sophisticated forms of branching to be implemented in a type safe
way, without having to directly manipulate labels and jumps at the JVM bytecode level. Importantly,
they will enable the kinds of branching needed by stream-deforestation techniques that
@patrick-schultz and I have been discussing, for which while loops and if's were not sufficient.
We've also discussed plans for implementing join points as a feature in the IR.
* Implementation of `whileLoop` (emits bytecode identical to current version):
```scala
def whileLoop(cond: Code[Boolean], body: Code[Unit]): Code[Unit] =
JoinPoint.CallCC[Unit] { (jb, break) =>
val continue = jb.joinPoint()
val loopBody = …
```

[hail] JoinPoints for JVM backend

---

hail/python/hailtop/batch_client/aioclient.py

cc: @tpoterba 
The main and cleanup containers run in parallel and thus should not be summed but max'ed (cleanup should always be longer, but this seems safer).
I'm not sure why we return None if a duration is present in the dictionary but set to None (as opposed to missing from the dictionary), but I preserved that behavior.

[batch] Accurate job durations

---

hail/python/hail/docs/getting_started.rst

I believe `conda create -n hail python==3.6` should only use `=`.

Fix typo installation docs

---

hail/python/hail/docs/getting_started.rst

When the conda env is created with `python>=3.6` there will not be a `pip3` alias created; as long as the env is activated, `pip` will work correctly.

Use pip, not pip3, to install hail

---

hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala

Master:
```
2019-09-18 10:57:21,316: INFO: [1/1] Running table_annotate_many_nested_dependence...
2019-09-18 10:58:18,144: INFO:     burn in: 56.82s
2019-09-18 10:59:09,182: INFO:     run 1: 51.03s
2019-09-18 10:59:59,688: INFO:     run 2: 50.50s
2019-09-18 11:00:52,745: INFO:     run 3: 53.05s
2019-09-18 11:01:46,129: INFO:     run 4: 53.38s
```
PR:
```
2019-09-18 11:02:42,403: INFO: [1/1] Running table_annotate_many_nested_dependence...
2019-09-18 11:02:44,261: INFO:     burn in: 1.85s
2019-09-18 11:02:45,562: INFO:     run 1: 1.30s
2019-09-18 11:02:46,734: INFO:     run 2: 1.17s
2019-09-18 11:02:47,898: INFO:     run 3: 1.16s
2019-09-18 11:02:49,048: INFO:     run 4: 1.14s
```

[hail] Improve simplification of nested struct insertions

---

hail/python/hailtop/hailctl/dev/benchmark/run/table_benchmarks.py
hail/src/main/scala/is/hail/expr/ir/Exists.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala

Following up on the last PR, that didn't actually solve the general problem. See the test at the bottom for an example of an IR that wasn't matching the rule.

[hail] Simplify nested struct inserts broken by lets

---

batch/batch/templates/batch.html
batch/batch/templates/batches.html
ci/ci/ci.py
ci/ci/templates/batch.html
ci/ci/templates/batches.html
ci/ci/templates/index.html
ci/ci/templates/job_log.html
ci/ci/templates/pr.html
docker/Makefile
notebook2/notebook/notebook.py
notebook2/notebook/styles/pages/notebook.scss
notebook2/notebook/styles/pages/user.scss
notebook2/notebook/templates/notebook.html
notebook2/notebook/templates/user.html
scorecard/scorecard/templates/index.html
scorecard/scorecard/templates/user.html
web_common/web_common/styles/main.scss
web_common/web_common/styles/variables.scss
web_common/web_common/styles/variables/colors.scss
web_common/web_common/styles/variables/margins.scss
web_common/web_common/templates/header.html
web_common/web_common/templates/layout.html

Pushing pixels around.  Summary of changes:
- make links blue, with underline :hover, :active
- added data-table class for striped, hover-highlighting tables, dark background headers, use all over
- put open_in_new on links that open new tabs
- made the search bars a bit wider (40%)
- make Github links all be <title> #<number>, where number is a lighter gray
- format attributes of repos and batches in CI tighter
- added batch labels on PR page
- made artifacts link clickable (long overdue)
@tpoterba I think this will fix most of your complaints from earlier today.
I deployed just CI by hand to verify it works, looks good.
I'm going to leave off styling for a bit after this and work on workshops in notebook2 and support many jobs in batch (paging, search, etc.)

UI tweaking

---

hail/python/hail/expr/functions.py
hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/expr/types/physical/PNDArray.scala

This PR adds support for ndarrays where one of the shape fields is 0. `list_shape` was previously written to ask for first element of each list, which did not work when lists were empty. Also had to fix the way strides were calculated, as the expression: 
`hl._ndarray([[], []])` should have stride (8, 8), and the previous code would have returned (8, 0), due to the shape being 0 on the last dimension.

Support empty ndarray

---

hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/io/bgen/BgenRDD.scala
hail/src/main/scala/is/hail/io/bgen/BgenRDDPartitions.scala

This doesn't actually hugely improve performance:
Master:
```
2019-09-12 16:25:06,282: INFO: [1/1] Running import_bgen_force_count_all...
2019-09-12 16:26:26,427: INFO:     burn in: 80.14s
2019-09-12 16:27:46,816: INFO:     run 1: 80.39s
2019-09-12 16:29:10,637: INFO:     run 2: 83.82s
2019-09-12 16:30:33,742: INFO:     run 3: 83.11s
2019-09-12 16:31:53,968: INFO:     run 4: 80.22s
2019-09-12 16:33:18,855: INFO:     run 5: 84.89s
```
PR:
```
2019-09-12 16:46:20,424: INFO: [1/1] Running import_bgen_force_count_all...
2019-09-12 16:47:39,550: INFO:     burn in: 79.12s
2019-09-12 16:48:57,259: INFO:     run 1: 77.71s
2019-09-12 16:50:15,457: INFO:     run 2: 78.20s
2019-09-12 16:51:32,472: INFO:     run 3: 77.01s
2019-09-12 16:52:49,160: INFO:     run 4: 76.68s
2019-09-12 16:54:05,504: INFO: …
```

[hail] Reorganize `import_bgen` staged code; use lookup table to parse

---

hail/src/main/scala/is/hail/annotations/Region.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala
hail/src/main/scala/is/hail/expr/ir/agg/ArrayElementLengthCheckAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/CollectAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/GroupedAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/PrevNonNullAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/TakeAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/TakeByAggregator.scala
hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
hail/src/test/scala/is/hail/expr/ir/TakeByAggregatorSuite.scala

The main goal here was to flatten out the aggregator states in the tuple of aggregator states, so that we could e.g. inline the value of a prevnonnull aggregator instead of storing a pointer to the state. The big change that I made was in creating a `TupleAggregatorState` that knows its own offset so that when we initialize a state, we can initialize the value offset directly from the value of the container. (The previous StateContainer got renamed `StateTuple` and was slimmed down accordingly.) I think I eventually want `TupleAggregatorState` to implement the `AggregatorState` interface; I haven't pushed it there yet because I haven't needed to, but I think it would fit a lot better.

[hail] cleaning up the new aggregator interface a little bit

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala

Lowest-effort possible lift for now, so that we can just have it running through the new path.
If the aggregators can't be converted, we fall back to the old system the same way as TableAggregate and TableMapRows do.

[hail] implement ArrayAgg and ArrayAggScan in new aggregator path

---

hail/python/test/hail/matrixtable/test_matrix_table.py
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala

[hail][bugfix] fix type requirements for MatrixUnionRows

---

hail/python/hail/methods/statgen.py
hail/python/test/hail/methods/test_statgen.py

Makes it possible to proceed past the duplicate-multiallelic-loci error.

[hail] Add `permit_shuffle` option to `split_multi`

---

hail/python/hail/docs/getting_started_developing.rst

The `install-wheel` Make target was renamed to `install` in hail-is/hail@346fb67aa5f943c42981025823876272ee222183 but the documentation for building Hail still refers to the old name.

Update docs for building Hail

---

hail/python/hailtop/hailctl/dataproc/connect.py

Turns out we didn't support `--dry-run` on `dataproc connect`. I'm not totally satisfied with this, as the command that gets printed out isn't runnable, because it will lack quotes around the `--ssh-flag=-D 1000` part. I tried adding the quotes into the command, thinking it would work but just be redundant, but I couldn't get it to work. I suppose I could have the printing logic go through the list and replace that bit with a quoted version. Let me know what you think.

hailctl dataproc connect needs dry-run

---

hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/types/encoded/EArray.scala
hail/src/main/scala/is/hail/expr/types/encoded/EBaseStruct.scala
hail/src/main/scala/is/hail/expr/types/encoded/EBinary.scala
hail/src/main/scala/is/hail/expr/types/encoded/EBoolean.scala
hail/src/main/scala/is/hail/expr/types/encoded/EFloat32.scala
hail/src/main/scala/is/hail/expr/types/encoded/EFloat64.scala
hail/src/main/scala/is/hail/expr/types/encoded/EInt32.scala
hail/src/main/scala/is/hail/expr/types/encoded/EInt64.scala
hail/src/main/scala/is/hail/expr/types/encoded/EType.scala
hail/src/main/scala/is/hail/expr/types/physical/PArray.scala
hail/src/main/scala/is/hail/expr/types/physical/PBaseStruct.scala
hail/src/main/scala/is/hail/expr/types/physical/PBinary.scala
hail/src/main/scala/is/hail/expr/types/physical/PBoolean.scala
hail/src/main/scala/is/hail/expr/types/physical/PCall.scala
hail/src/main/scala/is/hail/expr/types/physical/PDict.scala
hail/src/main/scala/is/hail/expr/types/physical/PFloat32.scala
hail/src/main/scala/is/hail/expr/types/physical/PFloat64.scala
hail/src/main/scala/is/hail/expr/types/physical/PInt32.scala
hail/src/main/scala/is/hail/expr/types/physical/PInt64.scala
hail/src/main/scala/is/hail/expr/types/physical/PInterval.scala
hail/src/main/scala/is/hail/expr/types/physical/PLocus.scala
hail/src/main/scala/is/hail/expr/types/physical/PNDArray.scala
hail/src/main/scala/is/hail/expr/types/physical/PSet.scala
hail/src/main/scala/is/hail/expr/types/physical/PStream.scala
hail/src/main/scala/is/hail/expr/types/physical/PString.scala
hail/src/main/scala/is/hail/expr/types/physical/PType.scala
hail/src/main/scala/is/hail/expr/types/physical/PVoid.scala

No detectable difference in performance:
```
$ hail-bench compare /tmp/before.json /tmp/after2.json
matrix_table_decode_and_count     101.5%     4.216     4.278
Geometric mean: 101.5%
Simple mean: 101.5%
Median:  101.5%
```

[hail] Only generate etype methods once per etype/ptype combination

---

hail/src/main/scala/is/hail/linalg/BlockMatrix.scala
hail/src/main/scala/is/hail/linalg/GridPartitioner.scala
hail/src/test/scala/is/hail/linalg/BlockMatrixSuite.scala

`BlockMatrix.filterCols` and `BlockMatrix.filterRows` has a bug where the smaller blocks located on the edge of the matrix are not always correctly handled when they're of a smaller size than the rest of the blocks. The source of this problem was the fact that `BlockMatrix.scala` line 1515 below, which was calling `blockDims(split.index)`. This was a problem because `split.index` is a partition index, not a block index. The fix was to convert it to a block index and then call `blockDims`. The rest of this PR is some white space fixes, a spelling error, and an additional test case for BlockMatrix filtering that would fail in current master because of this bug.

Block Matrix filter rows/cols edge issues

---

notebook/notebook/notebook.py
notebook/notebook/styles/pages/notebook.scss
notebook/notebook/templates/notebook-state.html

- change notebook states to Scheduling, Initializing, Ready (Running was too suggestion of being ready)
- remove "a_notebook" notebook name, replace with "Creating Notebook..." or "Open Notebook[open_in_new]" link
- change nb-state-container styling, blue/underline link on top, but the whole container still acts as a link
- made material icons bold.  I'm not sure if I like this, it is bordering on cartoonish.
- make checkmark green to match other success/ok coloring using green (e.g. messages)
- un-bold pod name, which is really only interested for us (maybe we should remove?)
It is deployed in my namespace if you want to play with it.

[notebook] Disable notebook link until ready

---

hail/python/hail/docs/functions/collections.rst
hail/python/hail/docs/functions/constructors.rst
hail/python/hail/docs/functions/index.rst

Unlike `empty_array` and `empty_set`, `empty_dict` does not currently appear in the documentation.

Add empty_dict function to documentation

---

hail/src/main/scala/is/hail/expr/ir/Exists.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala

Better IR for:
```
ht = mt.cols()
ht.aggregate(...)
```
Instead of a `TableAgg(TableKeyBy(TableParallelize(x)))`, we get an `ArrayAgg(x)`.

[hail] Add TableAggregate simplify rules

---

hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala

I want to use this in optimization.

[hail] Add lazily computed `rowCountUpperBound` to MatrixIR/TableIR

---

notebook/notebook/notebook.py
notebook/notebook/templates/notebook-form.html
notebook/notebook/templates/notebook-state.html
notebook/notebook/templates/workshop-admin.html
notebook/notebook/templates/workshop/index.html
notebook/test-playbook.txt
router/router.nginx.conf.in
web_common/web_common/styles/main.scss
web_common/web_common/web_common.py

Mostly small, straightforward stuff.  /auth must only return 2xx, 401 or 403, or nginx returns 500.  Redirect auth failures connecting to instance to /error, too.  Changed "Create/Open Notebook" to "Launch/Open Jupyter" and associated language throughout.
I'll run through the whole test playbook again after these go in.
Note to self, some improvements to consider:
- Validate image, memory, cpu values in workshop-admin.  Right now, if you enter invalid values, you get a 500 on launch Jupyter with invalid pod spec.
- Could change notebook.hail.is/notebook URL to notebook.hail.is/jupyter now.
- A background loop to kill any notebook workers associated to inactive workshops.  Then if you just inactivate the workshop at the end, everything gets cleaned up.

[notebook] fixes for playbook

---

hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py

This causes issues when starting interactive sessions on clusters.
Before, I get lots of output like this:
SPARKMONITOR_LISTENER: Started SparkListener for Jupyter Notebook
SPARKMONITOR_LISTENER: Port obtained from environment: ERRORNOTFOUND
SPARKMONITOR_LISTENER: Exception creating socket:java.lang.NumberFormatException: For input string: "ERRORNOTFOUND"
SPARKMONITOR_LISTENER: Application Started: application_1569946119076_0001 ...Start Time: 1569946336092
SPARKMONITOR_LISTENER: Exception sending socket message:java.lang.NullPointerException
After:
<nothing>
I also tested to make sure the monitor still worked in a notebook.

Do not start hail spark monitor outside of jupyter

---

hail/src/main/scala/is/hail/linalg/GridPartitioner.scala
hail/src/test/scala/is/hail/linalg/BlockMatrixSuite.scala

`BlockMatrix.transpose` was not implemented correctly, failed on sparse, rectangular matrices. 
Specifically, the `transposeBI` function in the old implementation was a function from new block indices to old block indices. However, in mapping over maybeBlocks, it was used as though it was a function from old block indices to new block indices. To fix this, I now have `transposeBI` and `inverseTransposeBI`

Transpose bug

---

benchmark/python/benchmark_hail/run/table_benchmarks.py
hail/src/main/scala/is/hail/sparkextras/RepartitionedOrderedRDD2.scala

the 1b_1k benchmark goes from 100s to 0.12s

[hail] Go back to interruptible iterators in RepartitionedOrderedRDD2

---

hail/python/hail/table.py
hail/python/test/hail/matrixtable/test_matrix_table.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

Also require that TableCollect has an unkeyed table. order_by in
Python to enforce key ordering.

[hail] Add simplify rule to invert order_by and collect

---

hail/python/hail/expr/aggregators/aggregators.py
hail/python/hail/ir/base_ir.py
hail/python/test/hail/expr/test_expr.py

we were looking at the IR to check whether an expression was an aggregation, but 1. we already track that and 2. we were ignoring that TableAggregates existed.

[hail] fix aggregation checking in aggregator transformations

---

hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
hail/src/test/resources/flag_at_end.vcf

When reading flag fields, we attempt to check if `line(pos) == '='`.
When a flag occurs at end of line, pos will be equal to line.length,
and thus caused an out of bounds read on the string.
Added the bounds check to prevent this.

[hail][bugfix]: fix out of bounds read in LoadVCF

---

web_common/web_common/styles/main.scss
web_common/web_common/templates/header.html

Another attempt at dropdown menus.  I like this better, too, for the reasons you described.
Changes:
- change dropdowns to "caret" style, with a triangle on the top of the dropdown that points to the header item it dropped down from
- move monitoring links into their own dropdown
To issues I'm not totally happy with:
- Monitoring can't be clicked on, so it is grayed out, but styling matches hover styling for active header items
- To center the triangle under the header item, I had to measure the width of the header items in the browser first.  It would be nice to do this from within CSS, but I don't know how to do that: the caret and the header item are in different parts of the DOM, and I don't know how to communicate the width of the header item to the left property of the caret.
It is …

[notebook] restyle dropdowns

---

hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/backend/Backend.scala
hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/test/scala/is/hail/TestUtils.scala

Most of the functionality was already available in EmitFunctionBuilder, but Compile() didn't make it available. This PR creates a `PrintWriter` during assertEvalsTo if you set the `jvm_bytecode_dump` flag to a file path you want the bytecode to be written to.
Example:
```scala
HailContext.setFlag("jvm_bytecode_dump", "arr_filter_bytecode.java")
assertEvalsTo(ArrayFilter(a, "x",
ApplyComparisonOp(LT(TInt32()), Ref("x", TInt32()), I32(6))), FastIndexedSeq(3))
HailContext.setFlag("jvm_bytecode_dump", null)
```

[hail] print out JVM bytecode in tests if HailContext feature flag is set

---

hail/python/hail/methods/qc.py

I don't think RST handles newlines in lists well.

[hail] fix docs in variant_qc

---

batch2/batch/__main__.py
batch2/batch/batch.py

Stacked on: https://github.com/hail-is/hail/pull/7208
Make app, db and v1 not global variables in batch.py.   I'm doing this because I want to break Batch, Job into separate files and use them in both the scheduler and the front end.  To do that, they need to be parameterized by the app (or the services that are carried on the app).

[batch2] fewer globals

---

hail/python/hailtop/batch_client/aioclient.py

Retry ALL requests with temporary failures.  We might want to add more exceptions/status codes, but these seem like a good first cut.
Also, don't cancel a batch that failed to submit.  It shouldn't be cancellable unless it was closed (in case the submit block in question would have succeeded).  At some point we should have something that cleans up unclosed batches after a while (e.g. 24hrs).

[hailtop] batch client: only retry temporary failures

---

hail/src/main/scala/is/hail/expr/ir/Exists.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/test/scala/is/hail/expr/ir/ForwardLetsSuite.scala
hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala

Fixed inlining of ArrayAgg nodes without aggs in the body. Also added
simplify rule to rewrite these nodes to just the body.

[hail] Fix ForwardLets inlining ArrayAggs

---

benchmark/python/benchmark_hail/run/table_benchmarks.py
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/utils/BufferedAggregatorIterator.scala
hail/src/test/scala/is/hail/utils/BufferedAggregatorIteratorSuite.scala

This pretty closely mimics the existing execution pattern.
I made a change to allow BufferedArrayIterator to store its internal buffer values in non-serializable form---I wanted to store the intermediate aggregator states as region values for as long as possible, and only serialize them when we have to return something for the iterator we're passing to Spark's aggregateByKey function.
I'm also allocating one aggRegion per key---that way, when we send an aggregator state into the Spark aggregation, we can clean up the region that we were using for aggregation. I'm managing this region manually, though--not sure how else to do it.

[hail] new aggregator path for TableKeyByAndAggregate

---

hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala
hail/src/main/scala/is/hail/expr/ir/agg/ArrayElementLengthCheckAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/GroupedAggregator.scala
hail/src/test/scala/is/hail/expr/ir/FunctionSuite.scala

Permits the big aggregate benchmarks to run...slowly:
```
2019-10-05 10:58:08,110: INFO: [1/2] Running table_big_aggregate_compilation...
2019-10-05 10:58:24,685: INFO:     burn in: 16.57s
2019-10-05 10:58:28,664: INFO:     run 1: 3.98s
2019-10-05 10:58:32,558: INFO:     run 2: 3.89s
2019-10-05 10:58:36,332: INFO:     run 3: 3.77s
2019-10-05 10:58:36,335: INFO: [2/2] Running table_big_aggregate_compile_and_execute...
2019-10-05 10:58:42,972: INFO:     burn in: 6.64s
2019-10-05 10:58:48,677: INFO:     run 1: 5.71s
2019-10-05 10:58:54,358: INFO:     run 2: 5.68s
2019-10-05 10:59:00,091: INFO:     run 3: 5.73s
```

[hail] Method-wrap aggregator functionality

---

hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/asm4s/joinpoint/JoinPoint.scala
hail/src/test/scala/is/hail/asm4s/ASM4SSuite.scala

`switch` can either be used with `Code[T]`s or `JoinPoint[Unit]`s. The former resemble's Java's `switch` by executing the code in the matched case. The latter in some cases generates less bytecode; it simply jumps to the join point for the matched case.
```scala
Code.switch[T](target: Code[Int], dflt: Code[T], cases: Seq[Code[T]]): Code[T]
JoinPoint.switch(target: Code[Int], dflt: JoinPoint[Unit], cases: Seq[JoinPoint[Unit]]): Code[Ctrl]
```

[hail] [jvm] implement switch for JVM codegen

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/expr/functions.py
hail/python/hail/expr/types.py
hail/python/hail/utils/misc.py
hail/python/test/hail/expr/test_ndarrays.py
hail/src/main/scala/is/hail/annotations/RegionValueBuilder.scala
hail/src/main/scala/is/hail/expr/AnnotationImpex.scala
hail/src/main/scala/is/hail/expr/ir/FoldConstants.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
hail/src/main/scala/is/hail/expr/types/encoded/EBaseStruct.scala

This PR adds the ability to use `hl.literal` on numpy arrays. It also changes the behavior of `hl._ndarray` when called on a numpy ndarray so it just goes through literal to avoid creating an IR node for each element of tensor.

Numpy literals

---

batch2/batch/utils.py
ci/ci/github.py
ci/ci/utils.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/process.py

I thought I was eliminating some duplicated code, but it turned out it wasn't used in batch2 anymore.  Anyway, it probably belongs in the common utils.

[ci, batch2, hailtop] move shared async subprocess code to hailtop.utils

---

hail/python/hail/docs/_static/rtd_modifications.css

There may be a more elegant way of doing this. I would like to remake doc styles at some point, post ASHG. (fyi @cseed). I think needed for workshop. Docs should work.
Before:
After:

[docs] fixes scrollto section

---

hail/src/main/scala/is/hail/expr/types/physical/PLocus.scala

New algorithm:
Check the bytes of the contig string
If equal, compare the positions
Otherwise, use the contig ordering

[hail] compare bytes before strings in locus ordering

---

hail/src/main/scala/is/hail/expr/types/encoded/EType.scala
hail/src/main/scala/is/hail/io/Decoder.scala
hail/src/main/scala/is/hail/io/Encoder.scala

The boxing saved like 20% of the runtime of the shuffler when codecs are just converting ints from bytes to JVM ints. The compilation made a bigger difference but I didn't measure it precisely.

[hail] no boxing in generated codecs, also compile once

---

hail/src/main/scala/is/hail/utils/HTTPClient.scala
hail/src/main/scala/is/hail/utils/package.scala

Take a wild guess what this is for.
The Java HTTP libraries are oddly complicated. This makes each verb I need in the shuffler a static method.

[hail] add HTTPClient which abstracts over Apache HTTP client

---

hail/src/main/scala/is/hail/annotations/RegionValue.scala
hail/src/main/scala/is/hail/io/CodecSpec.scala
hail/src/main/scala/is/hail/rvd/RVD.scala

Cosmetic. Seemed simpler overall to not take an RV to mutate. No one used this in a smart way anyway.

[hail] simplify region value fromBytes code

---

hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala

I use the compiler in the shuffler to check if an interval contains a key. I didn't see any way to do this without running the compiler on this IR:
```
ApplySpecial(
"contains",
Seq(
Ref("interval", intervalType.virtualType),
Ref("key", wireKeyType.virtualType)),
TBoolean(true))
```
And I don't want to start Spark (to create a HailContext) in the shuffler.

[hail] do not require a hail context if there are no literals

---

hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/TableValue.scala
hail/src/main/scala/is/hail/io/BufferSpecs.scala
hail/src/main/scala/is/hail/io/Spec.scala
hail/src/main/scala/is/hail/io/index/IndexWriter.scala
hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala

Cosmetic. I was working on buffer specs and noticed this duplicative code. Also we should never do `implicit val = x....z` if `z` is marked `implicit`. It is equivalent to `import x....z`.

[hail] Simplify buffer spec parsing code

---

hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/compatibility/LegacyRVDSpecs.scala
hail/src/main/scala/is/hail/expr/ir/ExecuteContext.scala
hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/TableValue.scala
hail/src/main/scala/is/hail/io/bgen/IndexBgen.scala
hail/src/main/scala/is/hail/io/gen/LoadGen.scala
hail/src/main/scala/is/hail/io/plink/ExportPlink.scala
hail/src/main/scala/is/hail/io/plink/LoadPlink.scala
hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
hail/src/main/scala/is/hail/methods/PCA.scala
hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala
hail/src/main/scala/is/hail/rvd/KeyedRVD.scala
hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/main/scala/is/hail/table/Table.scala
hail/src/main/scala/is/hail/variant/MatrixTable.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/annotations/AnnotationsSuite.scala
hail/src/test/scala/is/hail/expr/ir/MatrixIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/RandomFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
hail/src/test/scala/is/hail/io/ExportVCFSuite.scala
hail/src/test/scala/is/hail/io/ImportVCFSuite.scala
hail/src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala
hail/src/test/scala/is/hail/variant/vsm/VSMSuite.scala

This PR just clutters the RVD code with `ExecuteContext`. A later PR will leverage this to manage shuffle lifetimes.
I also added `addOnExit` to `ExecuteContext` which I'll use to make HTTP requests to the shuffle service to delete shuffle data.

[hail] thread execute context through RVD

---

batch2/Dockerfile.test
batch2/test/test_aioclient.py
batch2/test/test_batch.py
batch2/test/test_dag.py
batch2/test/test_scale.py
hail/python/hailtop/auth/auth.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

retry in get_userinfo
retry on ClientOSError (client connection error) on timeout
log errno to diagnose future failures
Some of the current errors are ClientOSErrors (ClientConnectionErrors, actually) with strerror "Connect call failed" but that doesn't correspond to a standard errno message returned by perror/os.strerror as far as I can tell.  So I'm retrying on timeout (good) and logging the errno so we can diagnose future transient failures.

[hailtop, batch2] improve retry

---

hail/python/hail/docs/_static/rtd_modifications.css

This should fully address the scroll-to artifact on docs, which had the item that was scrolled to (specified by a #id after the url) was hidden by the navbar.
Browsers interpret a hash after a url as being an element selector (id) to move the top of the page to. The browser will set the top of the browser to the top of the element, which is determined by its height, padding, and box-sizing rule (which determines whether padding and borders are taken into account when calculating the element's height and width). *The margin on the element is not taken into account*
This is incompatible with fixed navbars, because now the the top of the element should also take into account the height of the nabber.
2 solutions, one for the case where the element has a transparent background, and one for …

[www/docs] simplify section rule, enable scrollto functions

---

notebook/notebook/notebook.py

This might give us a bit more insight into the 500.  However, this assert shouldn't fail because we're querying on the primary key which is necessarily unique.

[notebook] extra info on assert

---

gear/gear/auth.py
hail/python/hailtop/auth/auth.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

So I'm of two minds here, and I don't quite know which to choose.  Imagine we make an internal (service to service) request.  It fails with a transient error like a timeout.  What do we do?
Option 1.  Retry.
Option 2.  Return a transient error 503 service unavailable to our client, and let them to decide what to do.
I've implemented both options here: request_{retry, raise}_transient_errors.  Which should I use in, for example, the auth decorators which hit the auth/userinfo endpoint?
I've chosen option 1 after bouncing back and forth a few times.  I feel like retrying will give a better experience in the common case (a real transient error) and both will recover eventually in the case of a real outage.
It appears that browsers don't retry 503 even with Retry-After header set.  I'd want …

[gear, hailtop] improve retry 2

---

batch2/batch/driver/k8s.py
batch2/batch/driver/main.py
hail/python/hailtop/utils/utils.py

- clean up unused code
- switch to async kubernetes client (I think now the only legacy use of the non-async library is in batch1)
- remove BATCH_USE_KUBE_CONFIG check since this can't run outside the cluster (for a long time now)
I really want async Google libraries so we can get read of the thread pool.

[batch2] clean up K8s client

---

hail/python/hail/expr/functions.py
hail/python/test/hail/expr/test_ndarrays.py

This PR introduces the ability to create an `NDArrayNumericExpression` from an `ArrayNumericExpression` or a `NumericExpression`. Along with #7304, this will allow hail users to make ndarrays from scratch by doing things like 
`hl._ndarray(hl.range(6)).reshape((3, 2))`

NDArray from Hail Array

---

batch2/MANIFEST.in

The jinja2 templates got moved from batch2/templates to batch2/front_end/templates but the manifest file to copy the template files wasn't updated.

[batch2] fix manifest path

---

Makefile
batch/Dockerfile.test
batch/batch/batch.py
batch/batch/schemas.py
batch2/batch/batch.py
batch2/batch/front_end/front_end.py
batch2/batch/front_end/schemas.py
ci/ci/build.py
hail/python/Makefile
hail/python/hailtop/batch_client/__init__.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py
hail/python/hailtop/batch_client/validate.py
hail/python/hailtop/pipeline/backend.py
pipeline/Dockerfile.test

Changes:
- create a custom job spec schema for what a job means to us
- hand-rolled validator
- use in bath_client, /jobs/create endpoints in batch, batch2
- slightly changed create_job interface around volumes, docker socket and secrets, update usage
- wrote route to convert this to a k8s pod spec, use when actually creating jobs
The secret has a namespace, but it is ignored by the servers.  Eventually, batch should be able to pull secrets from wherever, but needs to enforce permissions on who can use what secrets.  This was a long-standing issue that I think now has a clearer path.
We can get rid of the mount docker socket option by making the worker support a build (rather than run) task.
The validator should really go in the server code, but it needs to be shared between batch and …

[batchs] add custom job schema in batch client

---

hail/python/hail/experimental/vcf_combiner.py
hail/python/test/hail/methods/test_impex.py

The GVCF AS Fields were described to me as follows:
- `AS_QUALapprox`: string, pipe-delimited R-length int list
- `AS_SB_TABLE`: string, pipe-delimited R-length list of
comma-delimited length 2 lists of ints
- `AS_VarDP`: string, pipe-delimited R-length list of ints
- `AS_RAW_MQ`: string, pipe-delimited R-length list of doubles (sum
of squared MQs for each read)
- `AS_RAW_MQRankSum`: string, pipe-delimited R-length list of
histograms where histogram is a comma-delimited set of double bin
values followed by int counts-- may have empty entries or dots; e.g.
`AS_RAW_MQRankSum=||1.0,1||-2.1,1|`
- `AS_RAW_ReadPosRankSum`: string, pipe-delimited R-length list of
histograms where histogram is a comma-delimited set of double bin
values followed by int counts-- may have empty entries or dots

[combiner] Add canonical allele specific GATK annotation parsing

---

hail/python/test/hail/expr/test_ndarrays.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala

Resolves #6957 
Basically none of the NDArray stuff currently supports missingess, so this is the beginning of adding that support. The IR nodes that rely on the `NDArrayEmitter` are more complicated, but here's two easy ones to start. This fixes MakeNDArray and NDArrayShape's handling of missingness, with a test for each. It also adds some test for NDArrayRef with missingess, which was already handled but not tested.

MakeNDArray Missingess Semantics

---

batch/batch/batch.py
batch/test/test_batch.py
batch/test/test_dag.py
batch2/batch/batch.py
batch2/deployment.yaml
batch2/test/test_batch.py
batch2/test/test_dag.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py
hail/python/hailtop/pipeline/pipeline.py
hail/python/hailtop/pipeline/resource.py

Changes:
- Remove the per-job callback.  Nobody is relying on this.
- The batch callback should send batch metadata, not job metadata.  This is already what the CI is expecting (I think the only callback user).
- Switch to aiohttp for the callback, not threading/requests.
@tpoterba this will speed up merges in the CI by a few minutes.  Now the callback is ignored and its the periodic poll loop that notices the finished tests.

[batches] remove job callbacks, batch callback with batch info

---

hail/python/hailtop/hailctl/dataproc/modify.py

* Correct spelling of "decommissioning" in help for `--graceful-decommission-timeout`.
* Add space between "match" and "the" in help for `--update-hail-version`.
* Add punctuation to help for `--update-hail-version` for consistency with other arguments.

Fix spelling in hailctl dataproc modify help

---

batch/test/test_batch.py
batch2/test/test_batch.py

This job was adding an extra 30 seconds that was unnecessary.

[batches] fix slow tests by adding a cancel

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_ndarrays.py
hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/types/physical/PNDArray.scala
hail/src/main/scala/is/hail/utils/richUtils/Implicits.scala
hail/src/main/scala/is/hail/utils/richUtils/RichCodeArray.scala

This PR adds the ability to call reshape on hail NDArrayExpressions. It should behave just like: https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html
except that it doesn't take an order argument since we are currently not exposing user control over in memory layout of their ndarrays. If you haven't used numpy much, the potentially surprising detail is that you're allowed to specify a `-1` as one of the dimension sizes in the new shape, which will result in numpy inferring the correct size for that dimension by dividing the total number of elements by the product of the dimension sizes you did specify.

Support NDArray Reshape

---

hail/python/hailtop/utils/utils.py

I'm not sure why my exception didn't get picked up by the aiohttp.ClientOSError block. I added a plain OSError just in case. Feel free to push back on that. It's possible I didn't have updated is_transient_error code when I got the original error.

[hailtop.utils] add OSError to is_transient_error

---

hail/python/hail/docs/aggregators.rst
hail/python/hail/expr/aggregators/__init__.py
hail/python/hail/expr/aggregators/aggregators.py
hail/python/test/hail/expr/test_expr.py

Just an alias for `approx_quantiles(.5)` but easier to find when searching for median and probably a very common operation.

[hail] Adding approx median

---

hail/python/hail/docs/_static/goto.js

Enables id="Let's-Do-a-GWAS!" which previously wouldn't scroll to element because of the apostrophe, which is a reserved character, and which JS receives as an encoded HTMLEntity.
As an aside, it would be nice to not have reserved characters in IDs.

[www/docs] support HTMLEntities in id

---

hail/src/main/scala/is/hail/expr/ir/AggOp.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala

* don't use inefficient unapply
* Cache the returnType of AggSignatures so they persist through copies
```
table_big_aggregate_compilation      85.6%     4.113     3.519
Geometric mean: 85.6%
Simple mean: 85.6%
Median:  85.6%
```

[hail] Improve performance of IR copying

---

batch/Dockerfile
batch/batch/batch.py
batch2/batch/worker.py

This is why copying is so slow:
```
==> NOTE: You are uploading one or more large file(s), which would run
significantly faster if you enable parallel composite uploads. This
feature can be enabled by editing the
"parallel_composite_upload_threshold" value in your .boto
configuration file. However, note that if you do this large files will
be uploaded as `composite objects
<https://cloud.google.com/storage/docs/composite-objects>`_,which
means that any user who downloads such objects will need to have a
compiled crcmod installed (see "gsutil help crcmod"). This is because
without a compiled crcmod, computing checksums on composite objects is
so slow that gsutil disables downloads of composite objects.
/ [1/1 files][  4.1 GiB/  4.1 GiB] 100% Done  45.8 MiB/s ETA 00:00:00
Operation …
```

[batch] use composite upload when copying out dependencies

---

hail/.gitignore
hail/Makefile
hail/python/hail/__init__.py
hail/python/hail/context.py
hail/python/hail/docs/_static/annotationdb/annotationdb.js
hail/python/hail/docs/_templates/layout.html
hail/python/hail/docs/annotation_database_ui.rst
hail/python/hail/experimental/annotation_db.json
hail/python/hail/experimental/db.py
hail/python/hail/experimental/lens.py
hail/python/hail/expr/expressions/typed_expressions.py
hail/python/hail/expr/types.py
hail/python/hail/table.py
hail/python/setup.py
hail/python/test/hail/experimental/test_annotation_db.py
hail/python/test/hail/expr/test_expr.py
hail/python/test/hail/table/test_table.py

This change simplifies aspects of the annotation db's implementation as well as adding new features such as annotating a Table or using a custom JSON configuration file.
The Annotation DB will remain experimental until we iron out the JSON configuration file's structure and we're confident in the deploy process.
- Allow custom URL or JSON for configuration (enabling testing and local development).
- Support Tables.
- Restructure the annotation db JSON to reduce duplication. It now maps from dataset name to dataset metadata and dataset versions.
- Simplify JS logic based on new JSON structure.
- Check-in and implement versioned deployment of the annotation db configuration JSON.
- Add a JS file to the website that defines `hail_version` and `hail_pip_version`.
- Add `key_properties` which …

[hail][annotationdb] refactor annotation db

---

hail/python/test/hail/expr/test_ndarrays.py
hail/src/main/scala/is/hail/annotations/Annotation.scala

We needed a case in Annotation copy for `TNDArray`. I also don't want someone to have this issue again, so I replaced the wildcard catch a list of all the types.

NDArray Segfault

---

hail/Makefile

On debian and derivatives, /bin/sh is dash, so bashisms won't work in
makefiles.
This blocks me from releasing on my laptop.

[hail][bugfix] Some posix fixes for makefile

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_ndarrays.py

Currently, `reshape` only takes a python tuple. This will allow it to take a hail tuple as well.

[hail] Support passing ndarray reshape a hail tuple

---

hail/python/hail/docs/_static/goto.js

The actual necessary fix is `history.pushState("", document.title, loc.pathname + loc.search);` instead of `history.pushState("", document.title, loc.pathname);`
Given the nervousness around JS and its use in docs (many imperative scripts interacting), I've decided to take a simpler approach that guarantees that Firefox will have behavior inconsistent with Chrome/Safari. In practice it isn't so bad (initially scrolls too far instead of starting at top of page). There may also be a chance that the browser's built-in scroll will act after the JS command, but there simply isn't a better way (besides setting a longer timeout), or the version that alters the url.

[www/docs] don't modify url on load

---

hail/python/hail/methods/impex.py

Also note that `sep` is a deprecated name.

[hail] add delimiter argument to import_matrix_table

---

hail/python/hail/experimental/import_gtf.py

Currently, there is no way to directly import a GTF file with a ".gz" extension. The options are either rename it to ".bgz" if it is block compressed or decompress it outside of Hail if it is not. It would be nice if `import_gtf` supported the same `force_bgz` and `force` arguments as `import_table`.

Add force_bgz and force arguments to import_gtf

---

hail/python/hail/__init__.py

we can force users to refer to the `_`-prefixed version (`hail._nd`) by `del`eting the original module in `__init__.py`
python's module system is very strange

[hail] prevent users from referencing "hail.nd"

---

hail/src/main/scala/is/hail/annotations/CodeOrdering.scala
hail/src/main/scala/is/hail/expr/ir/BinarySearch.scala
hail/src/main/scala/is/hail/expr/ir/ComparisonOp.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/CollectAsSetAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/GroupedAggregator.scala
hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala
hail/src/main/scala/is/hail/expr/types/physical/PBaseStruct.scala
hail/src/main/scala/is/hail/expr/types/physical/PBinary.scala
hail/src/main/scala/is/hail/expr/types/physical/PBoolean.scala
hail/src/main/scala/is/hail/expr/types/physical/PInt32.scala
hail/src/main/scala/is/hail/expr/types/physical/PInt64.scala
hail/src/main/scala/is/hail/expr/types/physical/PLocus.scala
hail/src/main/scala/is/hail/expr/types/physical/PStruct.scala
hail/src/main/scala/is/hail/expr/types/physical/PTuple.scala
hail/src/main/scala/is/hail/expr/types/physical/PType.scala
hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala
hail/src/test/scala/is/hail/expr/ir/StagedBTreeSuite.scala

`order_by` supports sort fields. Eventually `order_by` will use the shuffler. To support this `CodeOrdering` needs to support sort fields.
I didn't actually add any tests. The Shuffler will eventually land and use this to do non-standard orderings.
There's a lot of noise due to threading SortField's everywhere, but the implementation of `CodeOrdering.reverse` and `PType.codeOrdering` are actually quite simple.
I also cleaned the code that I touched by abstracting over lt, lteq, gt, gteq.

[hail] Code Ordering Sort Fields

---

ci/ci/build.py

This is necessary for the user account to execute (call) stored procedures.
We'll have to update batch2/deployed users by hand.

add execute permission to user

---

ci/ci/ci.py

Fixes this error message in logs:
```
File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 418, in start
resp = await task
File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py", line 458, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/local/lib/python3.6/dist-packages/aiohttp_session/__init__.py", line 152, in factory
response = await handler(request)
File "/usr/local/lib/python3.6/dist-packages/ci/ci.py", line 302, in batch_callback
await asyncio.shield(batch_callback_handler(request))
File "/usr/local/lib/python3.6/dist-packages/ci/ci.py", line 276, in batch_callback_handler
await …
```

[ci] fix batch_callback_handler

---

blog/deployment.yaml
build.yaml
ci/ci/build.py
gateway/gateway.nginx.conf
router/deployment.yaml
router/router.nginx.conf.in

this deploys a standard ghost installation to the default namespace and routes to it from blog.hail.is; can be customized once deployed.
This won't pass tests until #7413 is in.

[blog] add ghost blogging infrastructure to blog.hail.is

---

auth/deployment.yaml
batch/batch/batch.py
batch2/deployment.yaml
gateway/deployment.yaml
internal-gateway/deployment.yaml
monitoring/monitoring.yaml
monitoring/router.yaml
router-resolver/deployment.yaml
router/deployment.yaml
site/deployment.yaml

Also, make batch pods eviction-safe.
This should allow the cluster autoscaler to scale the cluster down, according to: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node

[all] add disruption budget for replicated services (min 2)

---

batch2/batch/front_end/front_end.py
batch2/batch/worker.py
batch2/test/test_batch.py

fix /batches endpoint for unconstrained query, added test: there was a trailing AND
make worker create pod endpoint idempotent

[batch2] batch2 fixes

---

batch2/batch/driver/instance_pool.py
batch2/batch/front_end/front_end.py
batch2/batch/worker.py
batch2/create-batch-tables.sql
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

Changes:
- When looking up log in gs, return None if we get 404/NotFound.
-  Make sure the number of created jobs matches expected.  This handles the case where job creation fails but /close still gets called.
- make bounded gather take awaitables, raise exceptions by default

[batch2] more batch2 fixes

---

batch2/batch/driver/main.py
batch2/batch/front_end/templates/batches.html
hail/python/hailtop/pipeline/task.py

If there are live instances, batch2 won't startup.  Instances get the instance pool via the app, so it needs to be set before calling InstancePool.async_init.
Also, convert cores and memory to strings in pipeline.  The batch2 API requires a string for cpu.

[batch2] fix startup failure

---

batch2/batch/batch.py
batch2/batch/driver/instance.py
batch2/batch/driver/instance_pool.py
batch2/batch/driver/main.py
batch2/batch/driver/scheduler.py
batch2/create-batch-tables.sql
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

One more if/when you want to take a look.
Changes:
- Keep track of failed requests to workers, failed_request_count.  Reset on a successful communication in Instance.mark_healthy.
- Don't retry the /job/create request.  The scheduler loop will just retry.
- Don't schedule on nodes with failed count > 1.  This basically ignores 1-off hiccups.
- The /jobs/delete (unscheduled) call is an interested situation.  I decided to retry with back off and stop if the instance gets deactivated.  Retry abstractions seem hard, I'm not quite sure how to share this code with request_retry_transient_error, for example, given different exit conditions.  Sometime to think about as we see more examples.
- Ignore errors for each schedule attempt, so if there is a failure, count the request as failed and keep …

[batch2] track instance health

---

batch2/batch/driver/instance_pool.py
batch2/batch/front_end/front_end.py
batch2/create-batch-tables.sql

A little chaos testing revealed a database integrity issue.  If jobs.state = Running, instance_id must be non-null.  I incorrectly had `ON DELETE SET NULL`.  Instead, make sure that the instance has been deactivated (which reschedules all jobs, setting state = Ready) before deleting the instance entry.
Also, feedback on cancellation.

[batch2] fix instance_id integrity

---

batch2/Makefile
batch2/batch/worker.py
batch2/build-batch2-worker-image-startup.sh
batch2/create-batch-tables.sql
batch2/delete-batch-tables.sql

First, I'm seeing transient (but common, maybe 10% of the time?!  Have you seen this before, Jackie?) gsutil errors in the setup/cleanup containers that look like: [Errno 2] No such file or directory.  I ran with -DD, the file is there in gs://, something is going wrong in the container.  It happens with and without -m.
I tried to upgrade google/cloud-sdk, but ran into a problem: after updating the instance base image, the worker container can no longer get credentials from the metadata server and therefore gets permission denied when trying to copy out the logs.  Upon reflection, in our setup, containers being able to access the metadata server seems very insecure!  So we should (1) make sure containers we run can't access the metadata service, (2) run the instance as no service account, …

retry in setup/cleanup

---

batch2/batch/batch.py
batch2/batch/driver/instance.py
batch2/batch/driver/instance_pool.py
batch2/batch/driver/main.py
batch2/batch/driver/scheduler.py
batch2/batch/front_end/front_end.py
batch2/batch/utils.py
batch2/batch/worker.py
batch2/create-batch-tables.sql
batch2/delete-batch-tables.sql

This secures the batch2 driver endpoints.  The driver is called by workers on activate, deactivate and when a job is complete.  It is also called by the front end to notify it when a batch is closed, cancelled or deleted.
Workers have a random token stored in the database that is sent along with requests.  The front end and driver share another random, internal token which is also placed in the authorization header.
The driver has to decorators to protect request handlers: batch_only and instances_only.

[batch2] secure driver endpoints

---

hail/python/test/hail/matrixtable/test_matrix_table.py
hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/types/virtual/TDict.scala
hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala

Unblocks linear regression aggregator.

[hail][bugfix] Resolve handling of bindings in Matrix lowering of aggs

---

batch2/batch/driver/instance.py
batch2/batch/driver/instance_pool.py
batch2/batch/driver/main.py
batch2/batch/driver/scheduler.py
batch2/batch/front_end/front_end.py
batch2/batch/google_storage.py
batch2/batch/log_store.py
batch2/batch/worker.py
batch2/build-batch2-worker-image-startup.sh
batch2/create-batch-tables.sql

Stacked on: https://github.com/hail-is/hail/pull/7440
Changes:
- start the instance with a 1-time use activation token in the metadata
- on activation, clear the activation token, send the worker the normal token and batch-gsa-key
- upgrade the worker image to -6 which has the latest cloud-sdk (v269)
As far as I can tell, the metadata server is still available from within the worker container after the upgrade, so I'm not 100% sure why this change was necessary.  However, it will make things easier to lock down later.  I think the picture we want is:
- store the worker and batch logs in different buckets,
- the worker instance service account only has instance.delete* and object.insert on the worker log bucket,
- the service account used by the worker only has object.insert on the batch …

[batch2] send batch-gsa-key on activation, upgrade worker image

---

hail/python/hail/expr/functions.py
hail/python/hail/methods/family_methods.py
hail/python/hail/methods/misc.py
hail/python/hail/methods/qc.py
hail/python/hail/methods/statgen.py

Assorted fixes to the docs I found while reviewing the math formatting under KaTeX.
Besides a couple actually broken spots, mostly consists of LaTeX tweaks and fixing argument references using \`\`arg\`\` to \`arg\` (which is the style we use in most of the docs).

docs fixes

---

hail/python/hail/ir/matrix_ir.py
hail/python/hail/matrixtable.py
hail/python/test/hail/matrixtable/test_matrix_table.py
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

~~stacked on #7386~~
* implements `.tail` method on `MatrixTable`
```python
def tail(self, n: Optional[int], n_cols: Optional[int] = None) -> 'MatrixTable':
"""Subset matrix to last `n` rows.
....
Parameters
----------
n : :obj:`int`
Number of rows to include (all rows included if ``None``).
n_cols : :obj:`int`, optional
Number of cols to include (all cols included if ``None``).
Returns
-------
:class:`.MatrixTable`
Matrix including the last `n` rows and last `n_cols` cols.
"""
```
question: should the interface have the same backwards compatibility naming issue as `.head`, to preserve consistency? or should the keyword arguments be `n_cols` and `n_rows`?

[hail] matrix table tail

---

hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
hail/src/main/scala/is/hail/utils/richUtils/RichString.scala

while i was working on #7408, i realized that our parsing of nan and infinity deviated from python's in a strange way. specifically, it would behave like java's `parseFloat`, handling `[+-]NaN` and `[+-]Infinity` (case sensitive, permitting a sign). it would also accept `nan` and `inf` (like python), but would not support the other variations allowed by python (`[+-]nan`, `[+-]infinity`, and total case insensitivity).
with this change it should behave identically to python's `float(<str>)`, at least wrt. nan and infinity.

[hail] make float parsing correspond more precisely to python semantics

---

batch2/batch/batch.py
batch2/batch/driver/scheduler.py
batch2/batch/worker.py
batch2/test-batch-pod.yaml
batch2/test/test_batch.py
build.yaml

Images are stored in a global cache, so we have to be careful that a private image pulled by one user isn't executed by another user.  Therefore, pull each time for private images.  We could speed this up by having a per-user private image cache.

[batch2] add auth for gcr pull using user gsa-key

---

batch2/MANIFEST.in
batch2/batch/driver/instance.py
batch2/batch/driver/main.py
batch2/batch/driver/templates/index.html
web_common/web_common/styles/main.scss
web_common/web_common/templates/header.html
web_common/web_common/web_common.py

This adds a bare-bones status page for the batch2-driver.  It includes:
- a Driver dropdown from the Batch2 header item,
- the instance ID and ready cores,
- list of instances with their name, state, free cores, created and last updated time.

[batch2] driver status page

---

batch2/create-batch-tables.sql

Fixes this warning message I got when activating the instance:
```
/usr/local/lib/python3.6/dist-packages/aiomysql/cursors.py:192: Warning: Column 'activation_token' cannot be null
await self._do_get_result()
```

[batch2] fix instances schema for activation token

---

hail/python/hail/expr/functions.py
hail/python/hail/nd/__init__.py
hail/python/hail/nd/nd.py
hail/python/test/hail/expr/test_ndarrays.py

Adding the numpy style function `arange` to the `nd` module, as a shortcut for `hl._nd.array(hl.range(start, stop, step))`. I was mostly just tired of typing it, plus numpy consistency seems good.

ndarray arange

---

batch2/batch/batch.py
batch2/batch/batch_configuration.py
batch2/batch/driver/instance_pool.py
batch2/batch/driver/main.py
batch2/batch/front_end/front_end.py
batch2/deployment.yaml
batch2/service-account-batch-pods.yaml
build.yaml
ci/ci-agent-default.yaml
ci/ci-agent-sa.yaml
ci/ci-agent.yaml
ci/ci/build.py
ci/ci/environment.py
ci/deployment.yaml

First of 3 changes, I think:
- batch2 secret field now requires namespace and it is used for lookup (it was required before in validation, but ignored)
- CI now sets namespace consistently.  Since batch1 pods can only mount secrets from batch-pods, it only sets this to batch-pods.  The one exception is when the secretes come from a runImage step.  Then the namespace is taken from the runImage step if it is present, and otherwise defaults to batch-pods.
Two more PRs:
1. Set the namespace in all runImage step secrets
2. Make the namespace required in runImage steps
Then, when we switch CI from batch1 => batch2, we can create runImage steps that use secrets from namespaces other than batch-pods.

[ci, batch2] fix batch2 secrets part 1

---

ci/ci/build.py

Require namespace field of runImage step secrets.

[ci] fix batch2 secrets part 3

---

hail/python/cluster-tests/cluster-read-vcfs-check.py
hail/python/hail/docs/methods/impex.rst
hail/python/hail/docs/methods/index.rst
hail/python/hail/experimental/vcf_combiner.py
hail/python/hail/methods/__init__.py
hail/python/hail/methods/impex.py
hail/python/scripts/drive_combiner.py
hail/python/test/hail/methods/test_impex.py

* Make old functions the passthroughs, not the newer functions
* Don't `@typecheck` the passthrough functions.

[combiner][hail] reorganize/rename functions

---

hail/python/hail/ir/matrix_ir.py
hail/python/hail/matrixtable.py
hail/python/test/hail/matrixtable/test_matrix_table.py
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala

[Hail][feature] add `outer` option to `union_cols`

---

hail/src/main/scala/is/hail/expr/types/physical/PNDArray.scala

The previous version was incorrect, could not be parsed by `IRParser.parsePType`, and so prevented me from calling `.show()` on a table containing an NDArray. Now I can call `show`, but the output is terrible, will fix that in a subsequent PR. 
Additionally, I was surprised that the `_toPretty` method on `PInt32` didn't handle the requiredness plus sign on its own, but didn't want to change it in case there was a reason it didn't.

[hail][ndarray] Better PNDArray._toPretty

---

hail/build.gradle
hail/src/main/scala/is/hail/io/tabix/TabixReader.scala

This includes a fix that allows parsing of VCFs with header
lines that include more than four tags, in particular, the
optional Source and Version tags.

[hail] update htsjdk version

---

hail/src/main/scala/is/hail/expr/ir/agg/AppendOnlyBTree.scala
hail/src/main/scala/is/hail/expr/ir/agg/GroupedAggregator.scala

- each node in the BTree holds 6 elements
- the agg containers are stored inline in each tree element instead of by reference
- unrolled the recursive calls to `get` into a while loop (I'm not actually super sure why this helps, but it seems to have sped up the benchmark.)
Current master vs this PR:
```
table_aggregate_counter      86.6%     9.107     7.887
```

[hail] various cleanups to the GroupBy aggregator

---

hail/python/test/hail/expr/test_ndarrays.py
hail/src/main/scala/is/hail/expr/types/virtual/TNDArray.scala

I wasn't sure what this should look like. For now it does this, would be open to suggestions on how it should look. Currently the tests just test that it doesn't crash, if you're good with how this output looks I'll figure out how to test the output.
Some examples:
Boring case with 0 dimensional ndarrays
```
t = hl.utils.range_table(6)
t = t.annotate(a = hl._nd.array(t.idx))
t.show()
+-------+---------------------------+
|   idx | a                         |
+-------+---------------------------+
| int32 | ndarray<int32, 0>         |
+-------+---------------------------+
|     0 | ndarray{shape=(), data=0} |
|     1 | ndarray{shape=(), data=1} |
|     2 | ndarray{shape=(), data=2} |
|     3 | ndarray{shape=(), data=3} |
|     4 | ndarray{shape=(), data=4} |
|     5 | ndarray{shape=(), …
```

Showing ndarrays is no longer useless

---

hail/src/main/scala/is/hail/backend/Backend.scala
hail/src/main/scala/is/hail/backend/LowerTableIR.scala
hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
hail/src/main/scala/is/hail/backend/local/LowerTableIR.scala
hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/CompileAndEvaluate.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Optimize.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPass.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPipeline.scala
hail/src/main/scala/is/hail/utils/ArrayStack.scala
hail/src/main/scala/is/hail/utils/ExecutionTimer.scala

stacked on #7446
This is the first step toward broad integration of the timer throughout the compiler.
This gives us output like:
```
2019-11-06 18:44:11 root: INFO: Timer: all timings:
2019-11-06 18:44:11 root: INFO: Time taken for CompileAndEvaluate -- Optimize -- FoldConstants : 5.811ms, total 29.474ms, tagged coverage 0.0
2019-11-06 18:44:11 root: INFO: Time taken for CompileAndEvaluate -- Optimize -- ExtractIntervalFilters : 21.579ms, total 51.305ms, tagged coverage 0.0
2019-11-06 18:44:11 root: INFO: Time taken for CompileAndEvaluate -- Optimize -- Simplify : 38.711ms, total 90.246ms, tagged coverage 0.0
2019-11-06 18:44:11 root: INFO: Time taken for CompileAndEvaluate -- Optimize -- ForwardLets : 58.138ms, total 148.873ms, tagged coverage 0.0
2019-11-06 18:44:11 root: INFO: Time …
```

[hail] Improve execution timer.

---

batch2/batch/batch.py

The other option to fix this was to make `job_record_to_dict` have an extra layer of getopt everywhere, so I thought this was simpler.

[batch2] fix status if error occurred when getting the job config

---

hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala

This is invalid because our system currently doesn't know how to handle intervals of structs that are shorter than the full type.

[hail] Disable currently-invalid simplify rule

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_ndarrays.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/types/physical/PTuple.scala

This adds slicing support to NDArrays. I've implemented most of what numpy offers here under "Basic Indexing": https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html
Edge cases to note, assuming I have a 3 dimensional ndarray `arr`:
- `arr[:, ::, ::1]` returns the whole array (: is shorthand for "give me the full extent of this particular dimension", 2 colons does the same thing since it's like making a slice with all default values, and 2 colons followed by a 1 is specifying a slice with step size 1, which is the default step size. ). 
- `arr[2:3, 4:8:1, 5:10]` passing in 1 as a step argument has no effect, as 1 is assumed to be the default step. 
- `arr[:, :, -5:-2]` means that in the last dimension we should start selecting at the 5th to last element and stop at the second to …

NDArrays Support Slicing

---

batch2/batch/batch.py

This is causing CI to have 500 errors.

[batch2] a config error won't have a timing field

---

build.yaml

Fixes this problem:
```
+ xargs -r gcloud -q compute instances delete --zone
ERROR: (gcloud.compute.instances.list) The required property [project] is not currently set.
You may set it for your current workspace by running:
$ gcloud config set project VALUE
or it can be set temporarily by the environment variable [CLOUDSDK_CORE_PROJECT]
```

[batch2] fix delete_instances build step

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/types/physical/PNDArray.scala

Fixes #7532. Previously, could not write a table containing an NDArray because `StaticallyKnownField` is not serializable. There's no reason to serialize that thing though, so I made it transient lazy.

[hail][ndarray] Make NDArrays serializable

---

batch2/batch/batch.py
batch2/batch/front_end/front_end.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py

First of a few PRs cleaning up the batch2 API.  Goal is to remove the legacy job spec (now that batch1 is gone) and all endpoints that return multiple items (/batches, /jobs) need to support pagination and search.

[batch2] remove /batch endpoint include_jobs param

---

hail/python/hail/table.py
hail/python/test/hail/table/test_table.py

Fixes #7545. I opted to just make it print a degenerate table that looks like:
```
++
||
++
||
++
||
||
||
||
||
++
```
Admittedly I just sort of added special cases for empty list where necessary as opposed to trying to reword it to more naturally handle empty lists.

Table show works with no row fields

---

hail/python/hail/conftest.py
hail/python/hail/expr/__init__.py
hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_ndarrays.py

I plan on removing `_ndarray` entirely. I want everything going through the `nd` module. This PR just removes all calls to `_ndarray` and replaces them with calls to `hl._nd.array` (mostly just a find and replace PR). It also removes `_ndarray` from init.py so it cannot be called

Use _nd module everywhere

---

hail/python/hail/matrixtable.py

Noticed this while poking around the code for other reasons.
This could cause ordering problems.

[hail] MT.show() shouldn't use key_by

---

hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/Binds.scala
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPass.scala
hail/src/main/scala/is/hail/linalg/BlockMatrix.scala
hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala

The main goal of this PR was to remove some of the vector/scalar logic from the BlockMatrixMap2 node, and to support the scalar operations on BlockMatrixMap. I basically accomplished this by taking the cases that are matched on in BlockMatrixMap2 and lifting them into the Simplify rules.
The only endpoint that I believe I needed to cover was the BlockMatrix.pyExecute() one; all the others will go through the usual CompileAndEvaluate.
There's another part of the PR that fixes the variable bindings, which are currently hard-coded and unchecked. I needed this to construct the right expressions for the IR expressions, so I changed it to handle variable bindings with the rest of our IR.

[hail] clean up BlockMatrixMap IRs, delegate optimization of broadcasting for scalars to Simplify pass

---

hail/python/hail/docs/cheatsheets.rst
hail/python/hail/docs/index.rst

I added a cheatsheets page to the docs. It has a link to the single current cheat sheet. I just used the fact that it's already on github to create a download link, if that's bad practice I'm happy to do something else.

Cheatsheets page with a link to the download

---

hail/src/main/scala/is/hail/expr/ir/AbstractMatrixTableSpec.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/TableValue.scala
hail/src/main/scala/is/hail/expr/ir/functions/RelationalFunctions.scala
hail/src/main/scala/is/hail/variant/ReferenceGenome.scala

[hail] Rename `MatrixTable.scala` and move to `is.hail.expr.ir`

---

hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/io/TextMatrixReader.scala

This will fail until #7376 lands and allows the test to create an empty matrix table.
- document `sep`
- add two tests for importing empty matrix tables, one with a header and one without
- include the offending lines in error messages when files have different numbers of columns
- consistently use `String.split(separator, 0)` instead of using two different approaches which yield inconsistent results.
- simplify `parseHeader` and generalize to empty files
- improve error message when a row field found in the file does not match one of the row fields specified by `row_fields` (a dictionary from row field name to type).
NB: A no-header empty file implies no columns in the MT. We print a warning to this effect when we discover an empty file.
Resolves #7242

[hail] fix docs, fix bug, add empty file parsing to import_matrix_table

---

hail/src/main/scala/is/hail/annotations/Region.scala
hail/src/main/scala/is/hail/annotations/RegionValue.scala
hail/src/main/scala/is/hail/annotations/UnsafeRow.scala
hail/src/main/scala/is/hail/expr/types/physical/PBaseStruct.scala
hail/src/main/scala/is/hail/expr/types/physical/PContainer.scala

(since doesn't use any constructor arguments or other instance state). Should cost a bit less memory per region instance.
Part of upcoming larger refactor that removes region instances where possible

[hail/region] pretty printer does not need to live on region instance

---

gateway/gateway.nginx.conf
hail/python/hailtop/batch_client/aioclient.py
router/router.nginx.conf.in

Also, consistently make max client size 8m.
@konradjk this should permanently solve the 413 entity too large issue

[batch2] submit jobs in groups of at most 1MB

---

hail/python/hailtop/batch_client/aioclient.py

I think the database insert didn't perform as well with > 1000 jobs per insert in the front_end create_jobs, but I can't figure out where I got that. Feel free to reject this change.

[aioclient] limit group to 1000 jobs max

---

batch2/batch/batch_configuration.py
batch2/batch/driver/instance_pool.py
batch2/batch/front_end/front_end.py
batch2/batch/utils.py
batch2/batch/worker.py
batch2/deployment.yaml
batch2/test/test_batch.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py
hail/python/hailtop/batch_client/validate.py

This is an enhancement of #7498.
We adjust the number of cores in a user's request to make sure they have enough memory based on the memory per core rather than giving them the exact resources they asked for.

[batch2] add memory request to docker container config

---

hail/python/hail/experimental/write_multiple.py
hail/python/hail/ir/blockmatrix_writer.py
hail/python/test/hail/experimental/test_experimental.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixWriter.scala
hail/src/main/scala/is/hail/linalg/BlockMatrix.scala

Just numbering the matrices in order is creating a lot of post processing work for Jacob and Masahiro. This allows users to specify the filenames they want.

[hail][experimental] Pass Custom names to `export_block_matrices`

---

hail/python/hail/context.py
hail/python/hail/docs/api.rst

`hl.version` didn't have any generated documentation.

Document hail.version

---

hail/python/hail/docs/getting_started.rst

Conda added python 3.8, so our current docs result in someone getting python 3.8 as their hail environment. We are not compatible with python 3.8 because of pyspark problems.

Prevent conda from autoinstalling 3.8

---

hail/python/hail/docs/getting_started.rst

It seems not right to pin to a specific patch version of python 3.7. This is unnecessarily more generous, but seems fine.

[hail] 3.6 or 3.7

---

hail/src/main/scala/is/hail/expr/types/physical/PContainer.scala

Makes elementsOffsetTable private, it's only used internally and by defensively making class members private we can reduce the cognitive complexity of our codebase.
More importantly, avoid unnecessarily initializing the elementsOffsetTable array.

[hail/ptypes] private elementsOffsetTable

---

build.yaml

This is covered by readiness probes, which blog already has. Moreover, these parameters are unused due to PR #7564 "wait for stateful set" which fixes waiting on StatefulSets to work with headless ones.

[ci] remove irrelevant wait parameters

---

batch2/batch/batch.py
batch2/batch/driver/instance.py
batch2/batch/driver/instance_pool.py
batch2/batch/front_end/front_end.py
batch2/batch/utils.py
batch2/batch/worker.py
batch2/create-batch-tables.sql
batch2/test/test_batch.py
batch2/test/test_dag.py
ci/ci/ci.py
ci/ci/github.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/time.py

Three changes:
1. I noticed the costs were all 0.  I think this is due to `cores_mcpu INTO cores_mcpu` scoping issues in the attempt triggers, where the local variable was always zero.  At least changing the local variable name immediately fixed the problem.
2. I wrote a test to verify the costs were non-zero and consistent with the reported timing for the succeeding job.  It is hard to do on the cost string, so I included msec_mcpu in the batch/job status response to verify it.  In trying to verify it, I noticed that timestamps in the attempts table were slightly truncated compared to start/end times in the status (JSON).  This lead to rounding errors and slight disagreement.
3. Rather descend into the floating point rabbit hole of madness, I changed times everywhere to be stored as …

[batch2] fix costs

---

batch2/batch/driver/scheduler.py

The query in the scheduler was running incredibly slowly.  So slowly, I didn't have the patience to let it finish.  
```
mysql> EXPLAIN
-> SELECT job_id, batch_id, spec, cores_mcpu,
->   ((jobs.cancelled OR batches.cancelled) AND NOT always_run) AS cancel,
->   userdata, user
-> FROM jobs
-> INNER JOIN batches ON batches.id = jobs.batch_id
-> WHERE jobs.state = 'Ready' AND batches.closed
-> LIMIT 50;
+----+-------------+---------+------+--------------------+---------+---------+-------------------+------+-------------+
| id | select_type | table   | type | possible_keys      | key     | key_len | ref               | rows | Extra       |
+----+-------------+---------+------+--------------------+---------+---------+-------------------+------+-------------+
|  1 | SIMPLE      | batches | ALL …
```

[batch2] optimize scheduler query

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/types/physical/PContainer.scala
hail/src/test/scala/is/hail/expr/types/physical/PContainerTest.scala

Ready to look at. Assigning John because this code was related to NDArray.
Purpose of this was to clean up the function a bit (some unnecessary assignments, code clarity), reduce the number of loops needed to detect a missing value. We don't need to check every bit O(N) to determine whether a value is missing. Instead, it is sufficient to check groups of at least 1 byte, and in the case that there are more than 64 values, groups of 8 bytes, or 1 byte. We could further improve this by removing the condition in the loop in favor of 2 loops (one over floor(nMissingBytes / 8), one over the remainder), but I think this gets us most of the benefit. We could also check for groups of 4 bytes (int) when groups of 8 bytes (long) are exhausted, but that doesn't really bring us much, since the major …

[hail/ptypes] vectorized checkedConvert, clarified offset use

---

batch2/batch/front_end/front_end.py
batch2/batch/front_end/templates/batch.html

Batch page shows max 50 jobs paginated, with next page button.
Search box supports search with a simple language of terms:
- k=v - match jobs with attribute key k and value v
- has:k - match jobs with attribute k, any value
- state - match jobs with the corresponding states.  Search state terms are lower case (unlike actual job states, which I plan to change) and the recognized state terms are:
```
state_query_values = {
'pending': ['Pending'],
'ready': ['Ready'],
'running': ['Running'],
'live': ['Ready', 'Running'],
'cancelled': ['Cancelled'],
'error': ['Error'],
'failed': ['Failed'],
'bad': ['Error', 'Failed'],
'success': ['success'],
'done': ['Cancelled', 'Error', 'Failed', 'Success']
}
```
as you can see, some state search terms, like done, match multiple job states. 
- !term - match …

[batch2] scalable job search/batch page

---

hail/src/main/scala/is/hail/io/TextMatrixReader.scala

`.toSeq` is insufficient because a lazy stream is a `Seq`. `.toArray` forces the data to be realized in memory before the file is closed. We convert back to Seq for nice matching syntax. Dunno why the tests didn't catch this, I guess somehow the stream is valid long enough after the file being closed to work for the tests.

[hail] fix read after file close

---

hail/python/test/hail/expr/test_ndarrays.py

We don't even run this test currently, but we were generating a warning everytime we ran pytest about the fact that it would always be true if we did run it.

[tests] Remove parens from test so it isn't always true

---

hail/python/hail/methods/impex.py

Fixes #7584. We already require this in Scala, but since we don't require it in python the error message is bad.

Require column key is a string to export vcfs

---

build.yaml

Fixes this error:
```
+ gcloud -q compute instances list --filter 'tags.items=batch2-agent AND labels.namespace=pr-7660-default-ne0pow1za1v4' '--format=value(name)'
+ xargs -r gcloud -q compute instances delete --zone us-central1-a --project hail-vdc
ERROR: (gcloud.compute.instances.list) The required property [project] is not currently set.
```

[build.yaml] fix delete batch2 instances

---

hail/src/main/scala/is/hail/asm4s/joinpoint/ParameterPack.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/Streamify.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala

Stacked on #7228 ~~(transitively, #7207)~~
Implements the following pull based streams:
- `ArrayFlatMap`
- `ArrayLeftJoinDistinct`
- `ArrayScan`
- `ArrayAggScan`

[hail] [streams] more complicated streams

---

hail/python/hailtop/pipeline/backend.py
hail/python/hailtop/pipeline/pipeline.py
pipeline/test/test_pipeline.py

Submitting a pipeline now looks like:
```
$ hail pipeline.py
Submitted batch 120, see https://batch2.hail.is/batches/120
Waiting for batch 120...
Batch 120 complete: failure
```
FYI @konradjk Pipeline.run now passes through kwargs to the backend.  BatchBackend supports two new args: wait (default True) to wait for the pipeline to finish, and open (default False) to open the batch URL in the browser.
It no longer attempts to print the failed jobs.

[pipeline] wait, open options

---

hail/python/hail/methods/statgen.py

I guess people should read the whole docs before using something, but in practice they don't.

[hail] Move the split_multi warning up top

---

hail/src/main/scala/is/hail/annotations/RegionValueBuilder.scala
hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/ArrayElementLengthCheckAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/StagedBlockLinkedList.scala
hail/src/main/scala/is/hail/expr/types/physical/PContainer.scala

1) Removes region.allocate called on PContainer instances, in favor of Container's allocate instance method.
2) Introduces a copyeFrom
Goal was to remove contentsByteSize, because as used represents an allocation/copy implementation detail that does not need to live on a public interface.
Part of upcoming introduction of PContainer trait and complimentary PCanonicalArray.

[ptype/pcontainer] remove dependence on contentsByteSize

---

build.yaml
ci/ci-agent-default.yaml
ci/ci-agent.yaml
ci/ci/build.py

The assumption is that the default_ns namespace has a database-server-config that has credentials for the database instance which can be used to create various databases.
This is present in default.  We will require this is also present for dev namespaces, database-server-config will be the user's private database.  devs shouldn't have access to the root database credentials.
When we create a test default_ns when running the tests, we also create a "test_instance" database that will be used as the database instance inside the tests.  database-server-config is only used by CI.
Also, there's no reason to use the credentials from batch-pods anymore, so I use the one from default.
This will need to go in before I can finish https://github.com/hail-is/hail/pull/7674

[ci] use dev database server config in dev deploy

---

hail/python/hail/docs/data/matrix1_comment.tsv
hail/python/hail/ir/matrix_reader.py
hail/python/hail/ir/table_reader.py
hail/python/hail/methods/impex.py
hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/io/TextMatrixReader.scala
hail/src/main/scala/is/hail/utils/TextTableReader.scala

[hail][feature] Add "comment" potion to `import_matrix_table`

---

hail/python/hail/expr/expressions/typed_expressions.py

`Call.one_hot_alleles` takes an integer parameter with the total number of alleles. `CallExpression.one_hot_alleles` takes a list of strings but completely ignores its content and just takes the length. This PR allows `CallExpression.one_hot_alleles` to take an integer as well, and deprecates the old functionality. Would appreciate someone double checking my docstring changes to make sure I didn't say anything incorrect. 
Fixes #6855

Change CallExpression.one_hot_alleles to take total number of alleles

---

ci/ci/build.py
ci/create_database.py

Create step needs to generate names that are needed in both the create and cleanup steps (database name, user and admin usernames).

[ci] fix database cleanup

---

batch/batch/batch.py
batch/batch/driver/instance_pool.py
batch/batch/driver/main.py
batch/batch/driver/scheduler.py
batch/batch/front_end/front_end.py
batch/batch/google_compute.py
gear/gear/database.py
hail/python/hailtop/utils/utils.py

You can now say:
```
async with db.start() as tx:
await tx.just_execute(sql)
row = await tx.execute_fetchone(sql, args)
...
```
Transactions support all the database utility functions.  If the transaction context manager exists with an exception, the transaction is rolled back, otherwise it is committed.  You also can explicitly rollback or commit the transaction, although it can't be used again after that.  I also added an execute_many function.
I use this in the front end instead of dropping down to aiomysql to create explicit transactions.
Note on internal changes: I no longer use autocommit now that transaction boundaries are explicit.  You can start a read only transaction, and I do that by default for execute_and_fetch{one, all}, although maybe those should be renamed …

[gear] add transactions to database interface

---

hail/python/hail/ir/ir.py
hail/src/main/scala/is/hail/expr/ir/Optimize.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala

This creates redundant bindings that interfere with our ability to apply certain simplification rules.

[hail] don't bind Refs when deduplicating in InsertFields

---

hail/src/main/scala/is/hail/expr/ir/Optimize.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala

Looking at the IR generated by table.flatten, this snippet:
```
>>> import hail as hl
>>> t = hl.utils.range_table(10)
>>> t2 = t.annotate(**{f'f{i}': i for i in range(5)})
>>> t2.flatten().collect()
```
generates the following IR:
```
(GetField rows
(TableCollect
(TableMapRows
(TableOrderBy (Aidx)
(TableMapRows
(TableRange 10 8)
(InsertFields
(SelectFields (idx)
(Ref row))
None
(f0
(I32 0))
(f1
(I32 1))
(f2
(I32 2))
(f3
(I32 3))
(f4
(I32 4)))))
(Let __uid_3
(Ref row)
(InsertFields
(SelectFields ()
(SelectFields (idx f0 f1 f2 f3 f4)
(Ref row)))
None
(idx
(GetField idx
(Ref __uid_3)))
(f0
(GetField f0
(Ref __uid_3)))
(f1
(GetField f1
(Ref __uid_3)))
(f2
(GetField f2
(Ref __uid_3)))
(f3
(GetField f3
(Ref __uid_3)))
(f4
(GetField f4
(Ref __uid_3))))))))
```
If we look at the last …

[hail] optimize flatten

---

batch/batch/worker.py

Adds retry for specific 500 errors:
```
aiodocker.exceptions.DockerError: DockerError(500, 'error creating overlay mount to /var/lib/docker/overlay2/545a1337742e0292d9ed197b06fe900146c85ab06e468843cd0461c3f34df50d/merged: device or resource busy'
```
```
aiodocker.exceptions.DockerError: DockerError(500, 'Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

[batch] add docker retry for specific 500 errors

---

hail/src/main/scala/is/hail/annotations/RegionValue.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/main/scala/is/hail/utils/richUtils/Implicits.scala
hail/src/main/scala/is/hail/utils/richUtils/RichCodeIterator.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala

part of the work for getting TableMapPartitions working
you can use `Ref` or `In` nodes that have type `TStream` as emittable streams. the variable/argument must be bound to a `Iterator[RegionValue]`, which will be iterated over and emitted as part of the stream. this stream can then be composed like other streams.
there's no fancy region management going on in this PR since i'm going to handle that by deep copying in TableMapPartitions

[hail] [streams] IR to use region value iterator as stream

---

hail/python/hail/__init__.py
hail/python/hail/nd/nd.py
hail/python/test/hail/expr/test_ndarrays.py

I'm not removing ability to use `_nd` yet, because there's a couple of other PRs in motion right now that `_nd`. Once this goes in, I'll do a proper cleanup of all uses of `_nd` and make it so only `nd` is left.

Allow use of nd without underscore, change all known references of _nd

---

hail/src/main/scala/is/hail/expr/ir/Simplify.scala

When the number of fields in `x` is really huge, this optimization creates huge chains of `Let` bindings which cause stack size issues in downstream IR analysis passes.
(we can remove this cap once our passes will no longer run into stack size issues on very deep IRs.)

[hail] cap size of struct for passing refs through InsertFields

---

ci/ci/github.py

4 concurrent builds for 10 engineers with a couple branches each just isn't tenable.

[ci] 8 concurrent builds

---

apiserver/jupyter_notebook_config.py.in
auth/Dockerfile
auth/MANIFEST.in
auth/Makefile
auth/auth/auth.py
auth/auth/driver/__main__.py
auth/auth/driver/driver.py
auth/auth/templates/users.html
auth/cluster-role.yaml
auth/create-auth-tables-pod.yaml
auth/create-auth-tables.sql
auth/delete-auth-tables.sql
auth/deployment.yaml
batch/batch/batch_configuration.py
batch/batch/driver/main.py
batch/batch/front_end/front_end.py
batch/batch/worker.py
batch/deployment.yaml
build.yaml
gear/gear/auth.py
gear/gear/auth_utils.py
gear/gear/database.py
hail/python/hail/fs/google_fs.py
hail/python/hailtop/pipeline/backend.py
notebook/MANIFEST.in
notebook/notebook/notebook.py
router-resolver/router_resolver/router_resolver.py
web_common/web_common/styles/main.scss
web_common/web_common/templates/header.html

Building off your previous user creation logic PR.  Summary of changes:
- Add auth/users admin page with list of users and automated add, delete user.
- Bit of database reorg, user_id is gone, users table is now auth.users.
- Added state to users table, `active` for active users.  Adding (deleting) users just sets state to `adding` (`deleting`)
- Added a new service (doesn't serve requests) auth-driver that watches the database and processes adding, deleting users.  Only one replica, runs every ~60s
- Don't actually delete users, just mark them deleted.  This is so we don't lose billing information for users we're deleting.  This will need more thought once we understand what the financial record keeping constraints are.  Maybe we purge users after 90 days?  Maybe keep them forever?
- …

[auth] user admin page with automated create, delete

---

benchmark/python/benchmark_hail/run/linalg_benchmarks.py

Added benchmarks for NDArray addition and multiplication. There are 2 for multiplication because when I add something to use BLAS instead of just naive multiply it will improve the one that is using float64s.

Benchmark NDArray Addition and Multiplication

---

hail/python/hail/methods/misc.py
hail/python/test/hail/methods/test_misc.py
hail/src/main/scala/is/hail/utils/BinaryHeap.scala
hail/src/main/scala/is/hail/utils/Graph.scala
hail/src/test/scala/is/hail/utils/GraphSuite.scala

Maximal independent set has had a bug/misfeature since https://github.com/hail-is/hail/pull/2975. That PR added an `hl.int64(...)` coercion around the tie_breaker function. This allowed users to pass tie_breakers that returned floating point numbers, but it *changed the meaning*. The sign of values with magnitude greater than or equal to one was preserved. All values in (-1, 1) were converted to 0, thus treating them as indistinguishable for the purposes of the MIS.
This PR fixes this long standing bug and adds a simple test for that case. Supporting arbitrary numeric types is actually quite simple! The conversion from any Hail numeric type to float64 is sign-preserving (AFAIK), which is the only property we need to preserve the user's intended ordering.
This change also introduces two …

[hail] fix maximal_independent_set

---

apiserver/test-apiserver-pod.yaml
auth/create-auth-tables-pod.yaml
auth/deployment.yaml
batch/create-batch-tables-pod.yaml
batch/delete-batch-tables-pod.yaml
batch/deployment.yaml
batch/test-batch-pod.yaml
blog/deployment.yaml
ci/create-ci-tables-pod.yaml
ci/deployment.yaml
gateway/deployment.yaml
internal-gateway/.gitignore
internal-gateway/deployment.yaml
letsencrypt/letsencrypt-pod.yaml.in
monitoring/.gitignore
monitoring/router.yaml
notebook/create-notebook-tables-pod.yaml
notebook/deployment.yaml
notebook/notebook/notebook.py
router-resolver/deployment.yaml
router/deployment.yaml
scorecard/deployment.yaml
site/deployment.yaml
ukbb-rg/deployment.yaml

And separate preemptible and non-preemptible workloads to run in their own pools.  This should fix the problem where the non-preemptible pool fills up with preemptible things but k8s can't evict.
When this is ready to go in, I will remove the preemptible pool toleration and redeploy the infrastructure components by hand.

use node selector instead of tolerations/node affinity

---

hail/python/hail/methods/statgen.py
hail/python/test/hail/methods/test_statgen.py

Assigned Jackie because I want to make sure this is correct.

[hail] Fix crash in ld_prune because we weren't imputing missing GTs

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/expr/functions.py
hail/python/test/hail/expr/test_expr.py

Fixes #3699. Makes it so Hail can take in a numpy type anywhere it can take a python number or expression.

[hail] Support Numpy Scalar Types

---

hail/python/hailtop/hailctl/dataproc/start.py
hail/src/main/scala/is/hail/HailContext.scala

This means people who don't use hailctl get these configurations.

[hail] Move kryo and result size capacity increases to HailContext

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala

This helps with method size if we're doing a lot of 
```
Let("foo", <value>,
Let("bar", <value2>,
… ))
```
where the size of the code generated by the values are potentially quite large. (I think doing this will unblock one of @konradjk's pipelines for now.)

[hail] method-wrap value of Let if it's potentially large

---

hail/python/hail/experimental/__init__.py
hail/python/hail/experimental/loop.py
hail/python/hail/ir/ir.py
hail/python/test/hail/experimental/test_experimental.py
hail/python/test/hail/helpers.py
hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/expr/ir/Binds.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InTailPosition.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/add-ir-checklist.txt
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

I don't think I'm quite satisfied with this implementation, although I think that it will do the things we need it to do, for the most part. It mostly adheres to the structure that @chrisvittal was implementing in #5228, although I had some questions/notes about implementation/interface and would love some input:
* I'd like to implement (in python) some sort of while loop construct, but I'm not sure what it looks like. I think I'd like to think of that as our primary loop construct since the general recursive loop function can be confusing to start with in terms of what's allowed (what is tail-recursive? what is non-tail-recursive?) if you're just trying to implement some convergence criteria. Some initial thoughts on interface:
```
1:
loop = hl.WhileBuilder(i=0, x=0)
loop.cond(loop.i < …
```

[hail] tail-recursive loops

---

hail/src/main/scala/is/hail/io/vcf/ExportVCF.scala

Fixes #6963.
%e vs %g:
```scala
scala> val big = 12345678910112d
big: Double = 1.2345678910112E13
scala> val small = 0.0000000000123123
small: Double = 1.23123E-11
scala> val medium = 1.12345
medium: Double = 1.12345
scala> Array(big, small, medium).foreach { x => println(x.formatted("%.5e")) }
1.23457e+13
1.23123e-11
1.12345e+00
scala> Array(big, small, medium).foreach { x => println(x.formatted("%.6g")) }
1.23457e+13
1.23123e-11
1.12345
```

[hail] Export VCF floats using %g formatter

---

hail/python/hailtop/utils/utils.py

For some reason, all output was suppressed so I wasn't even seeing my debugging output. 502 is labelled "transient" but it's not always. I still don't know what's wrong, but something like this would have prevented me from running in circles trying to figure out what the hell changed (this works in a PR, it's only broken in dev deploy, don't know why yet).

[hailtop] log every tenth error message

---

hail/python/hail/experimental/sparse_split_multi.py

Note how and why sparse_split_multi differs from split_multi with how it
treats the `*` allele.

[hail][docs] Expand sparse_split_multi docs.

---

hail/src/main/scala/is/hail/sparkextras/ContextRDD.scala

before:
```
2019-12-19 13:46:39,469: INFO: [1/1] Running matrix_table_take_entry...
2019-12-19 13:46:48,414: INFO: burn in: 8.94s
2019-12-19 13:46:51,170: INFO: run 1: 2.75s
2019-12-19 13:46:53,789: INFO: run 2: 2.62s
2019-12-19 13:46:56,590: INFO: run 3: 2.80s
```
after:
```
2019-12-19 13:51:38,688: INFO: [1/1] Running matrix_table_take_entry...
2019-12-19 13:51:43,457: INFO: burn in: 4.77s
2019-12-19 13:51:43,871: INFO: run 1: 0.41s
2019-12-19 13:51:44,295: INFO: run 2: 0.42s
2019-12-19 13:51:44,742: INFO: run 3: 0.44s
```

[hail] Fix `mt.entry.take` performance regression

---

hail/src/main/scala/is/hail/expr/types/physical/PBinary.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalBinary.scala
hail/src/main/scala/is/hail/expr/types/physical/PType.scala

Closes out the first reorg work.
There are a bunch of utility methods on PBinary, but these are non-trivial to remove. There are places where it isn't clear to me that we have a PBinary instance for instance.
For example,
```scala
srvb.addString("hello"),
```
Would need a PString (and the fundamentalType of that)

[hail/ptypes] PBinary restructure

---

hail/python/hail/expr/functions.py
hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/expr/ir/FoldConstants.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/MathFunctionsSuite.scala

I haven't ripped out the Scala uniroot stuff in this PR; I'll do that if/when this goes in.
It's based on the same thing that the Scala version is, here:
https://github.com/wch/r-source/blob/e5b21d0397c607883ff25cca379687b86933d730/src/library/stats/src/zeroin.c

[hail] rewrite uniroot in python

---

hail/src/main/scala/is/hail/expr/ir/NestingDepth.scala
hail/src/test/scala/is/hail/expr/ir/ForwardLetsSuite.scala

Otherwise we would be calculating the (unchanged) value of the binding for each iteration through the loop.

[hail] increment nesting depth for body of loop to prevent let forwarding into loop

---

batch/batch/front_end/templates/batch.html
batch/batch/front_end/templates/batches.html
web_common/web_common/styles/main.scss

Add an expandable element just below the search box.
Screen shots, unexpanded:
And expanded:
@akotlar A CSS thing I couldn't figure out, if you have any ideas: I wanted the width of the expanded help to be 75% the width of the table below it, but `max-width: 75%` doesn't work.  For now, I just set the max-width: 450px, which is 75% of the min-width of the table (now 600px).

[batch] search help for batches, batch jobs

---

ci/ci/build.py

The error this fixes is in the line: 
`if not step.run_if_requested or step.name in requested_step_names`
when `requested_step_names is None`, you cannot check if a value is `in` it. I chose not to make the default value of `requested_step_names = []`, since it's dangerous to do that in python (that single mutable list will be shared across invocations of the constructor)

[ci] Need to use empty list for requested step names

---

hail/python/test/hail/expr/test_ndarrays.py
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala

Added a new test to make sure type promotion worked correctly (multiplying int matrix by float matrix), found a requiredness issue instead.

[hail] NDArrayMatMul Requiredness Fix

---

internal-gateway/internal-gateway.nginx.conf

This is sufficiently large to permit the transmission of the Hail JAR
which is about 38 MB. I will use this to test and eventually normally
use the Gradle build cache server.

[internal-gateway] increase client max body size to 50m

---

apiserver/test-apiserver-pod.yaml
auth/create-auth-tables-pod.yaml
auth/deployment.yaml
batch/create-batch-tables-pod.yaml
batch/delete-batch-tables-pod.yaml
batch/deployment.yaml
batch/test-batch-pod.yaml
blog/deployment.yaml
ci/create-ci-tables-pod.yaml
ci/deployment.yaml
dbuf/deployment.yaml
gateway/deployment.yaml
internal-gateway/deployment.yaml
monitoring/monitoring.yaml
notebook/create-notebook-tables-pod.yaml
notebook/deployment.yaml
router-resolver/deployment.yaml
router/deployment.yaml
scheduler/deployment.yaml
scorecard/deployment.yaml
site/deployment.yaml
ukbb-rg/deployment.yaml

We need at least one pool without taints to schedule the kube-system services (e.g. dns).  Therefore, I propose:
- make the non-preemptible pool untainted,
- keep taint on preemptibles so kube-system pods are not scheduled there,
- and keep tolerations for preemptible pods,
- use nodeSelector to force preemptible pods to be scheduled on the preemptible pool.  In fact, I put nodeSelectos on all pods, although it isn't strictly necessary for non-preemptible pods.
Sound good?

use nodeSelector, tolerate preemptibles

---

hail/python/hail/expr/types.py
hail/python/test/hail/expr/test_ndarrays.py

It's wrong to use the strides as given from numpy in the current implementation. When we do `x.reshape(x.size).tolist()`, we are flattening the ndarray into a single contiguous list that can be thought of as being stored in row major. So I always want to generate the strides that the row major version of the numpy array would have had. The `if shape_element > 0` bit is because if you have an empty numpy array of a certain type, you still don't want it to have 0 stride.

Fix strides from numpy

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_expr.py

Shouldn't lint anyhow -- CollectionExpression does not define __getitem__

[hail] Remove dead code in ArrayExpression.__getitem__

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/hail/ir/ir.py
hail/python/hail/ir/register_functions.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala
hail/src/test/scala/is/hail/expr/ir/ArrayFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

Fixes #2921
Example:
```
In [3]: mt = mt.annotate_entries(PL=[0])
In [4]: hl.split_multi_hts(mt)._force_count_rows()
... hundreds of lines of java trace ...
Hail version: 0.2.30-bae67f384161
Error summary: HailException: array index out of bounds: index=1, length=1
----------
Python traceback:
File "<ipython-input-4-ba11ec1cd68e>", line 1, in <module>
hl.split_multi_hts(mt)._force_count_rows()
File "/Users/tpoterba/hail/hail/python/hail/methods/statgen.py", line 2246, in split_multi_hts
(hl.range(0, 3).map(lambda i:
File "/Users/tpoterba/hail/hail/python/hail/methods/statgen.py", line 2250, in <lambda>
).map(lambda j: split.PL[j]))))))
File "/Users/tpoterba/hail/hail/python/hail/methods/statgen.py", line 2250, in <lambda>
).map(lambda j: split.PL[j]))))))
```

[hail] include Python stack trace in ArrayRef out-of-bounds error

---

build.yaml

Does this look right?  We aren't including the test repo on deploy, so we shouldn't create it/can't test against it.

[ci, build] don't test ci in deploy

---

batch/test/test_batch.py

Sorry, attempt #2.  Batch currently keeps the cpu/memory ratio constant, and the default memory is 3.75G (= 1 core), so in spite of setting the cpu=100m, it was still getting 1 core.

[batch] fix batch tests in deployment

---

admin-pod/.gitignore
admin-pod/Makefile
admin-pod/admin-pod.yaml
build.yaml

This is a pod running in default that mounts deploy-config and database-server-config.  `mysql` will connect to the database as root.  Useful for troubleshooting.  I often have it running, but figure it should be official.
Doesn't run in test since it doesn't have a database-server-config.

[admin-pod] add admin pod

---

hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala
hail/src/main/scala/is/hail/expr/types/encoded/EArray.scala
hail/src/main/scala/is/hail/expr/types/encoded/EBaseStruct.scala
hail/src/main/scala/is/hail/expr/types/encoded/EType.scala

This makes the api for inplace decoders identical to regular decoders.

[hail] add buildInplaceDecoderMethod

---

hail/src/main/scala/is/hail/annotations/RegionValueBuilder.scala
hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/AppendOnlyBTree.scala
hail/src/main/scala/is/hail/expr/ir/agg/CollectAsSetAggregator.scala
hail/src/main/scala/is/hail/expr/types/physical/PBaseStruct.scala
hail/src/test/scala/is/hail/expr/ir/StagedBTreeSuite.scala

Replaces setAllMissing (1, staged-only function), clearMissingBits (3 functions with both staged and unstated implementations) with staged/non-staged initialization functions, mirroring the PContainer API.
Semantically this is more correct (for instance clearMissingBits was used mostly behind the condition like `if (init)`), and represents 2 fewer functions to maintain (3 if you count that we may have eventually wanted a setAllMissing in the non-staged world)

[hail/ptypes] add initialize and stagedInitialize methods to PBaseStruct

---

batch/batch/semaphore.py

This fixes a bug in the fifo sem.  If we release a large job, we would only start at most 1, not as many as we could.  This could actually lead to worker deadlock.

[batch] satisfy as many items as possible in fifo sem

---

batch/batch/batch.py
batch/batch/driver/scheduler.py

Overschedule batch workers by 2 cores.  Changes:
- `free_cores_mcpu` in `compute_fair_share` includes the overschedule cores, which will get allocated to users, and
- when scheduling, schedule if the job fits on the node with the overschedule cores, or the node is not yet overscheduled.  This allows us to overschedule jobs that need >2 cores.
This shouldn't go in until after @jigold's parallel scheduler PR.
FYI @danking

[batch] overschedule batch workers 2 cores

---

ci/create_database.py

The database name `test-instance` is causing trouble in: https://github.com/hail-is/hail/pull/7856

[ci] consistently quote migration table names in create tables

---

benchmark/python/benchmark_hail/run/matrix_table_benchmarks.py
hail/src/main/scala/is/hail/expr/ir/Simplify.scala

Fixes O(N) performance of mt.entries().show()

[hail] Don't let TableOrderBy blow away already-sorted TableKeyBy nodes

---

hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/main/scala/is/hail/sparkextras/ContextRDD.scala

[hail] move head/tail from crdd to rvd; fix linear memory usage

---

benchmark/python/benchmark_hail/run/matrix_table_benchmarks.py
hail/python/hail/expr/functions.py
hail/python/hail/ir/ir.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/asm4s/joinpoint/ParameterPack.scala
hail/src/main/scala/is/hail/expr/ir/Binds.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/Env.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/NestingDepth.scala
hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/Streamify.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala
hail/src/test/scala/is/hail/expr/ir/ArrayFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

Needs a bit more infrastructure before this can help deforest several
more lowered IRs.
timings:
```
$ hail-bench compare /tmp/pre.json /tmp/post.json
matrix_table_array_arithmetic      81.2%     9.967     8.095
matrix_table_nested_annotate_rows_annotate_entries      23.6%    31.287     7.369
```

[hail] Add ArrayZip IR node.

---

hail/src/main/scala/is/hail/compatibility/LegacyBufferSpecs.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/io/BufferSpecs.scala
hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

also used it to read the column values in MatrixNativeReader directly instead of doing a TableCollect on a TableRead.

[hail] implement ReadPartitions IR node

---

ci/ci/build.py

Now that createDatabase is gone, rename createDatabase2Step => createDatabase2, and accept createDatabase in build.yaml for creating database.  In follow up PRs, I will:
- rename createDatabase2 => createDatabase in build.yaml,
- don't support createDatabase2, completing the change.
I can't do this in one change because this PR is tested/deployed by the _previous_ CI, not the one in this PR, so it has to be done in stages.  Such is the microservices life.

[ci] rename createDatabase2 #1

---

hail/python/hail/expr/functions.py
hail/python/test/hail/expr/test_ndarrays.py

This PR adds support for `hl.nd.array` to take an arbitrarily nested `ArrayExpression` as an argument.

[hail] Support nested ArrayExpression in arguments to hl.nd.array

---

batch/batch/batch.py

This is an improvement, but I think we should reconsider the batch state.
Thinking out loud: The batch and CI UIs have slightly different displays.  If you're running, have had a failed job, but also been cancelled, what should your state be?  I think we either need columns in the batch display for open/closed, cancelled, complete and the simple state (open, running, cancelled, failure, success ... where the latter 3 mean complete), or display compound states like "running failure cancelled".

[batch] cancelled batches should have cancelled state

---

hail/src/main/scala/is/hail/expr/types/physical/PType.scala
hail/src/main/scala/is/hail/rvd/RVDType.scala

[hail] Rewrite PType.subsetTo to avoid using `canonical`, which is wrong

---

build.yaml

fixes
```
+ gcloud -q auth activate-service-account --key-file=/test-gsa-key/key.json
Activated service account credentials for: [test-665@hail-vdc.iam.gserviceaccount.com]
+ set +e
+ gcloud -q compute instances list --filter 'tags.items=batch2-agent AND labels.namespace=pr-7890-default-b9qytu01zuim' '--format=value(name)' --project hail-vdc
+ xargs -r gcloud -q compute instances delete --zone us-central1-a --project hail-vdc
Deleted [https://www.googleapis.com/compute/v1/projects/hail-vdc/zones/us-central1-a/instances/batch-worker-pr-7890-default-b9qytu01zuim-15e3g].
ERROR: (gcloud.compute.instances.delete) Could not fetch resource:
- The resource 'projects/hail-vdc/zones/us-central1-a/instances/batch-worker-pr-7890-default-b9qytu01zuim-hr6b9' was not found
```

[build] fix delete_batch_instances if instance not found

---

docker/requirements.txt
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py
hail/python/hailtop/pipeline/backend.py
hail/python/hailtop/pipeline/pipeline.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/tqdm.py

Progress bars for batch submit (which work even if individual bunches fail).
Stacked on #7875
Now also works in Jupyter Notebook (you get a GUI bar).
I added `hailtop.utils.tqdm` and `hailtop.utils.TQDM_DEFAULT_DISABLE` because the "correct" default argument for disable is different between Jupyter Notebook and the console tqdm. In particular, console tqdm treats `None` as "if I'm connected to a TTY, display, otherwise hide". Jupyter tqdm treats `None` as "do not display" (which is clearly the wrong default, but 🤷‍♀ ).

[batch] insertion progress bars

---

benchmark/python/benchmark_hail/run/matrix_table_benchmarks.py
hail/src/main/scala/is/hail/expr/types/encoded/EArray.scala
hail/src/main/scala/is/hail/expr/types/encoded/EBaseStruct.scala
hail/src/main/scala/is/hail/expr/types/encoded/EType.scala

Benchmark:
```
$ hail-bench compare /tmp/before.json /tmp/after.json
write_profile_mt     100.4%    31.130    31.249
Geometric mean: 100.4%
Simple mean: 100.4%
Median:  100.4%
```

[hail] Clear trailing missing bits on encoded arrays as well

---

hail/src/test/scala/is/hail/expr/ir/MatrixIRSuite.scala

I use text search for "fail" in the CI logs, and this always pops up.

[tests] rename test that has "fail" in its name

---

hail/python/hail/docs/getting_started_developing.rst

In a new environment,
```
cd hail
make install
make pytest
```
fails with
```
...
ERROR: usage: setup.py [options] [file_or_dir] [file_or_dir] [...]
setup.py: error: unrecognized arguments: --instafail --self-contained-html --html=../build/reports/pytest.html
inifile: None
rootdir: /path/to/hail/hail/python
```
because the pytest plugins in hail/python/dev-requirements.txt are not installed.
This documents the need to install them before running tests.

Document installing dependencies for pytest

---

hail/src/main/scala/is/hail/io/InputBuffers.scala

I followed the rabbit hole form https://github.com/hail-is/hail/pull/7922 and was a bit concerned that we weren't verifying the stream met our expectations. I don't think we need to handle errors more gracefully (these assertions should only fail on malformed files).

[hail] assert non-empty stream in InputBuffers.scala

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_expr.py

Since #5913, `__getattr__` for ArrayStructExpressions and SetStructExpressions calls `__getitem__` so that collection expressions behave more like tables. However, this means that when the requested attribute is not a field of the collection's elements, `__getattr__` throws a KeyError when it [should throw an AttributeError](https://docs.python.org/3/reference/datamodel.html#object.__getattr__).
This breaks `hasattr`, since it [checks whether `getattr` raises an AttributeError](https://docs.python.org/3/library/functions.html#hasattr). 
```python
hasattr(hl.struct(foo="bar"), "someattribute")
hasattr(hl.literal([hl.struct(foo="bar")]), "someattribute")
```
This changes `__getattr__` to catch the KeyError thrown by `__getitem__` and throw an AttributeError instead.
---
I found this because …

Change exception type for __getattr__ on struct collection expressions

---

batch/batch/batch.py
batch/batch/driver/main.py
batch/batch/driver/scheduler.py
batch/batch/front_end/front_end.py
batch/sql/delete-batch-tables.sql
batch/sql/estimated-current.txt
batch/sql/improve-cancel.sql
batch/utils/stress.py
build.yaml
hail/python/hailtop/pipeline/backend.py
hail/python/hailtop/pipeline/task.py

I finally figured out the "right" way to do cancellation.
I introduce the following notions:
- a job is cancellable if it is ready or running, it hasn't been cancelled, but if the batch is cancelled, it will be cancelled (not always_run),
- a job is runnable if it is ready but has not been cancelled.
Now we aim to incremental maintain the following information:
Globally:
- runnable jobs and cores
Per user:
- runnable and running jobs and cores,
- running cancelled jobs, and
- ready cancelled jobs.
The global runnable cores are needed by the instance pool controller.
The per-user stats are needed by the three threads of the scheduler:
- for the fair share allocator and the scheduler,
- to cancel running jobs on workers that have been cancelled (because the batch was cancelled),
- to cancel …

[batch] improve cancel

---

batch/batch/driver/scheduler.py
batch/batch/front_end/front_end.py
batch/batch/utils.py
gear/gear/database.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

Changes:
- move LoggingTimer to hailtop.utils
- add timer_description option to fetchall functions in gear.database
- add descriptions for all scheduler queries
We have to call the timer inside fetchall because it is an async generator.  The other database functions can be timed by the client code with LoggingTimer directly.

[batch] log scheduler queries timing

---

batch/batch/driver/scheduler.py

If there is no work to do, the scheduler threads should wait.
This is likely causing the database load.  run_if_changed isn't waiting if there is no work to do, so all three threads are spinning as fast as possible.

[batch] fix return value for run_if_changed

---

hail/python/hail/methods/statgen.py

128 MiB partitions are a much more reasonable default than 1MB. This will result
in better file read/write performance.

[hail] fix default partition calculation for BN model

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/ir/TableIR.scala

This PR introduces a new test case that was failing. It fixes two problems:
1. needed to bind `n` to `blockSize` so that it didn't serialize the whole IR. 
2. needed to add references to the regions from producer to `targetRegion` to ensure that the filter test passes. 
Question: Does this keep too much garbage in memory? Ideally, I'd release the references to the regions of my producer once I finished constructing the new `RegionValue`.

Fix group within partitions region management and serialization

---

batch/batch/driver/main.py
batch/batch/driver/scheduler.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

Changes:
- Add WaitableSharedPool that allows you to submit a collection of jobs (which start running as soon as they are submitted) against a shared AsyncWorkerPool and then `wait()` at the end for all submitted jobs to complete.
- Use in scheduler threads.
I also unscientifically tweaked a few of the settings:
- Use queue_size=100 in shared async worker pool in scheduler.  This is 1x the parallelism, which seems like plenty.  (Queue size is how much pending work to queue up before blocking.)
- Drop work per iteration from 1000 to 300.
- Increase the number of database connections to 50.  This is 1/2 the parallelism in the scheduler, the argument being half the work goes into servicing web requests (e.g. talking to workers) and the other half talking to the database.
FYI @danking

[batch] use waitable pool in scheduler

---

benchmark/python/benchmark_hail/run/methods_benchmarks.py
hail/python/hail/matrixtable.py
hail/python/hail/methods/statgen.py
hail/src/main/scala/is/hail/expr/types/physical/PArray.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalArray.scala
hail/src/main/scala/is/hail/linalg/BlockMatrix.scala
hail/src/main/scala/is/hail/methods/PCRelate.scala

I changed the Spark `persist`s to `writeRead` which writes and then reads. I tried to maintain this invariant: a block matrix partition always reads a linear number of partitions in the number of referenced block matrices. In particular, the result of *any* matmul must `writeRead`.
I removed the boxing of Doubles to check for NaN.
I avoided a bunch of allocation when performing matmul by using a fused multiply and add operation (`dgemm`).
I sped up conversation to BlockMatrix somewhat by introducing an iterator that caches the firstelementoffset.
I substantially improved `BlockMatrix.checkpoint` by using the fast lz4 codec.
*new*: I also added some tasteful cache'ing to PCRelate which substantially reduced the time spent reading data from disk.
cc: @johnc1231 @konradjk

[hail] PC Relate improvements

---

batch/test/test_batch.py
hail/python/hailtop/batch_client/aioclient.py

It is impossible to submit large batches without this.  What happens?  The timeout per request is 60s.  We have 50 x 8MB = 400MB worth of requests in flight.  That means the client needs a reliable sustained MINIMUM bandwidth of ~7MB/s to not time out.  This doesn't seem reasonable.
Without this change, Konrad wasn't able to submit a large batch (although it probably would have gone through eventually with enough retry/backoff).  With this, 136K jobs took 2-3m to submit.
FYI @konradjk

[batch] adjust client parameters

---

batch/batch/worker.py

After watching batch a bit, it is clear 5m is way too long.

[batch] shorten worker timeout

---

benchmark/python/benchmark_hail/run/methods_benchmarks.py

This larger benchmark shows clearer separation between the old pc-relate approach and the current one.
this branch (which include's master's improvements)
```
2020-01-27 13:16:20,975: INFO: [1/1] Running pc_relate_big...
2020-01-27 13:18:12,886: INFO: burn in: 111.90s
2020-01-27 13:19:56,255: INFO: run 1: 103.35s
2020-01-27 13:21:46,801: INFO: run 2: 110.54s
2020-01-27 13:23:39,147: INFO: run 3: 112.37s
{"config": {"cores": 1, "version": "0.2.31-68d448411ab5", "timestamp": "2020-01-27 13:23:39.157122", "system": "darwin"}, "benchmarks": [{"name": "pc_relate_big", "failed": false, "timed_out": false, "times": [103.35172498200001, 110.53654034999997, 112.369625832]}]}
```
before improvements `becbbc6d2` (run against this branch's new benchmark)
```
2020-01-27 13:25:15,789: INFO: [1/1] …
```

[hail] add pc_relate_big benchmark

---

hail/python/hailtop/hailctl/dataproc/start.py

These changes enable hailctl clusters to work correctly in an Broad GCP Security Best Practices configured project, with minor hail-specific set-up. See further details in team chat.

[hailctl/dataproc] Support Broad's GCP Security Best Practices Document

---

batch/batch/driver/scheduler.py

- long running jobs are causing too much latency for interactive stuff (e.g. CI)
- overscheduling core calculation wasn't behaving how we wanted

[batch] remove overscheduling

---

hail/python/test/hail/expr/test_ndarrays.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala

I accidentally got the dimensions wrong in one of the `matmulShape` cases, causing this issue: #7982. This didn't come out in testing because in my 2 dimensional by 1 dimensional ndarray test, I used a square 2 dimensional array, so the shape was the same on either side. This PR adds another test and makes the fix.

2d by 1d matmul fix

---

batch/batch/front_end/templates/batch.html
batch/batch/front_end/templates/batches.html
web_common/web_common/styles/main.scss

Creates a responsive table whose dimensions are defined on the parent (allowing child elements to be set as a percentage of that table), by setting width of the parent based on viewport. If the table exceeds that width, it will scroll, such that the elements above the table are still fixed to the flex-end position. See https://github.com/hail-is/hail/pull/7777
Narrow view (very slightly wider, because 75% of 653 is > 75% of 600, and table is in fact 653px at minimum, even when you set 600px min width):
Wide view:
Table that is too wide is scrollable (wider than 1024px):
after scrolling right:
Tested manually in browser in Firefox and Chrome.

[batch] improve alignment

---

ci/ci/ci.py

I think this is right. I think `j` is an async Job rather than a sync one even though we collect_agen.

[ci] fix ui in batch page -- attributes interface change

---

batch/batch/front_end/templates/batch.html
batch/batch/front_end/templates/batches.html

Mac didn't show these, missed it. I need to create a better testing system for UI. 
overflow: scroll can force the browser to show scrollbars even when they are not necessary.

[batch] Fix table scrollbars

---

batch/batch/batch.py
batch/batch/batch_format_version.py
batch/batch/front_end/front_end.py
batch/test/test_batch.py
batch/test/test_dag.py
batch/test/test_scale.py
batch/test/utils.py
ci/ci/ci.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py

This fixes a few of problems:
- Batch.jobs() was discarding the job json objects and returning an Job objects.  This is not OK because we need the metadata from the json objects for efficiency (e.g. in CI PR/batch pages).
- We confused Job.status(), which is the job json object, with the status field of that object.  In particular, we got that wrong in BatchFormatVersion.get_status_exit_code_duration in the call to Job.{exit_code, total_duration_msecs}.  Add a test to check we got this right.
- Return the duration in msecs, not a string, because as an API, the string is useless.  humanize it before sending it to the API.
I think the batch client is (1) has a lot of legacy baggage that can be cleaned up, and (2) is massive overkill and can probably be cleaned up.  It should probably have …

[batch] fix issues with exit code, duration

---

batch/batch/batch.py

Scenario: we mark a ready job cancelled, and it doesn't change the free core counts.  It may cause another job to cancellable or runnable (if it was always_run).
This is another timing issue that was causing the batch tests to take longer than necessary.

[batch] kick scheduler after job completes

---

hail/python/hail/nd/__init__.py
hail/python/hail/nd/nd.py
hail/python/test/hail/expr/test_ndarrays.py

This just adds a convenience function to get the diagonal of a 2d ndarray. The numpy version offers more functionality when you have something greater than 2 dimensions, but I haven't needed that yet so starting with this. It won't be a breaking interface change to add more arguments to this function to support what numpy does.

Diagonal function for 2d ndarrays

---

batch/batch/front_end/front_end.py

We saw this error in production:
```
pymysql.err.IntegrityError: (1062, "Duplicate entry '7433-432443' for key 'PRIMARY'")
```
hand deploy in progress already.

[batch] Fix catch duplicate key

---

batch/batch/driver/instance.py
batch/batch/driver/instance_pool.py

1. If we receive an error other than 404 from Google when asking about an instance, we should raise. This is unexpected. (The later lines will fail anyway because spec is `None`)
2. (the main issue) if the instance is not active, do not bother contacting it and, crucially, continue `check_on_instance` eventually learning the instance does not exist.
3. Drop timeout to 5s to talk to a batch agent
Fixes the zombie instance issue.

[batch] fix up instance polling

---

benchmark/python/benchmark_hail/run/methods_benchmarks.py
hail/python/hail/ir/ir.py
hail/python/hail/matrixtable.py
hail/python/hail/table.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/Binds.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Compilable.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

We were reading the column values per row. This was bad.
Introduce the LiftMeOut node that is evaluated in the
`InterpretNonCompilable` lowering pass.
The benchmarked pipelines are still exponential in the number of
iterations of QC, which I will fix in a forthcoming PR.
Before:
```
2020-01-29 12:36:38,135: INFO: [1/1] Running variant_and_sample_qc_nested_with_filters...
2020-01-29 12:38:31,070: INFO: burn in: 112.93s
2020-01-29 12:40:17,863: INFO: run 1: 106.79s
2020-01-29 12:42:01,471: INFO: run 2: 103.61s
2020-01-29 12:43:47,330: INFO: run 3: 105.86s
```
After:
```
2020-01-29 12:30:18,619: INFO: [1/1] Running variant_and_sample_qc_nested_with_filters...
2020-01-29 12:31:24,969: INFO: burn in: 66.34s
2020-01-29 12:32:24,797: INFO: run 1: 59.82s
2020-01-29 12:33:22,849: INFO: run 2: …
```

[hail][bugfix] Resolve performance bug in variant_qc

---

hail/python/hail/ir/blockmatrix_ir.py
hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala

For block matrices, we apparently have a notion of "tensor shape" vs "matrix shape". I am so far not a huge fan of this, as I don't think `BlockMatrix` was really designed to be anything other than a matrix. Anyway, the bug here is that the types contain the "tensor shape", and the block matrix filtering code was acting under the assumption that the types contained the "matrix shape". I've tried to be explicit when naming them below. 
I also added some python tests to catch this. We have Scala filtering tests as well, so just added enough python tests to convince myself this bug was fixed.

Block Matrix Shape Bug

---

hail/python/hail/experimental/__init__.py
hail/python/hail/experimental/sparse_mt_utils.py
hail/python/hail/experimental/vcf_combiner.py

Saw this warning: /usr/lib/python3.7/runpy.py:125: RuntimeWarning: 'hail.experimental.vcf_combiner' found in sys.modules after import of package 'hail.experimental', but prior to execution of 'hail.experimental.vcf_combiner'; this may result in unpredictable behaviour
when running:
python -m hail.experimental.vcf_combiner -h
This restructure fixes it while not changing the export point of
`lgt_to_gt`.

Fix warning when running combiner script

---

hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/RefEquality.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

The `assert(_ptype2 == null)` check in InferPType is breaking here on
certain complex pipelines in a way I don't want to debug.
There's no IR sharing within the IR (see utility I added), but there
must be subtrees that are inferred multiple times in different Compile
calls.
This is a safe stop-gap.

[hail/ptypes] Copy IRs before inferring

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/ir/TableIR.scala

[hail][bugfix] always truncate partitioner keys in TableMultiWayZipJoin

---

hail/python/hail/ir/matrix_ir.py
hail/python/hail/methods/qc.py
hail/src/main/scala/is/hail/expr/ir/Binds.scala
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala

This change lets the call_rate calculation in variant_qc and sample_qc use the same IR without forking (which led to an exponential duplication of the IR, when these appeared iteratively).
We do this by introducing a new binding in MatrixMapCols and MatrixMapRows which refers to the row/col count. These metrics can be computed at essentially no marginal cost.
```
$ hail-bench compare ~/misc/debug/qc_before.json ~/misc/debug/qc_after.json
sample_qc     102.3%    13.173    13.470
variant_qc      91.4%     5.259     4.809
variant_and_sample_qc_nested_with_filters_2      29.9%    55.963    16.749
variant_and_sample_qc_nested_with_filters_4       3.2%   1183.905    38.048
```

[hail] Improve IR generated by VQC/SQC to avoid exponential blowup

---

hail/src/main/scala/is/hail/expr/types/physical/PBaseStruct.scala
hail/src/main/scala/is/hail/expr/types/physical/PType.scala

pytest and jvm-test pass, so it seems the looser assertion can be tightened to make this safer.

[hail/ptypes] unsafeOrdering: require equality of ptypes

---

hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala

Mostly a dead code thing at this point; there's nothing that uses nSpecialArgs != 1 and we've moved away from using that as a way of tracking objects.

[hail] remove nSpecialArgs argument to Emit

---

gateway/service.yaml

cc: the "services team" @cseed, @johnc1231
This fixes gateway to log the user's IP. Forthcoming PRs will fix all downstream
services.
---
There are two important pieces of which to be aware:
- The gateway pod are exposed via the gateway Service, which is the only
object modified in this PR.
- K8s fulfills our request for the gateway Service by creating a [Google TCP
LoadBalancer](https://console.cloud.google.com/net-services/loadbalancing/loadBalancers/list). Moreover,
we specify `loadBalancerIP` which is a manually (outside of k8s) allocated IP
which we expose on the public internet.
When you `curl https://hail.is` this is what happens:
- Your packet travels across the internet until it reaches the Google TCP
LoadBalancer
- The Google TCP LoadBalancer selects one of the kubernetes nodes …

[gateway] log external user's IP in gateway

---

hail/src/main/scala/is/hail/expr/ir/Compile.scala

Source of instability in the short term; will add back after release

[hail] Remove InferPTypes from Compile

---

hail/python/hail/docs/experimental/index.rst

The current link leads to a 404 page.

Fix link to example NumPy style docstrings

---

hail/python/hail/docs/index.rst

In the Sphinx theme which the Hail docs use, the search page does not show anything unless a query has been provided and a search performed.
https://github.com/readthedocs/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/search.html
Thus, the Search link on the [home page of the Hail 0.2 docs](https://hail.is/docs/0.2/index.html) leads to a [blank page](https://hail.is/docs/0.2/search.html).
To avoid confusion, this change removes the link to the search page from the home page.

Remove search link from docs home page

---

hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/hail/methods/statgen.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Defines two new BlockMatrixIR nodes, BlockMatrixSparsify and BlockMatrixDensify, to represent the corresponding operations in BlockMatrix. Execution is unchanged.

[hail] nominally move sparsify operations to IR

---

benchmark/python/benchmark_hail/run/combiner_benchmarks.py
benchmark/python/benchmark_hail/run/matrix_table_benchmarks.py

* Add an empty multi write benchmark
* Add python only combiner benchmarks (4ms / iteration of `transform_gvcf`!)
* Make the merge and write nothing benchmark actually finish on a laptop and reduce the time it spends in python.

[benchmarks] Additional multi-write / combiner benchmarks

---

hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/FoldConstants.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/expr/types/physical/PNDArray.scala
hail/src/main/scala/is/hail/expr/types/physical/PType.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

The primary use case I have in mind for this right now is to lower a BlockMatrixCollect node; I don't *think* this can be easily implemented in terms of other nodes.
Currently I've only implemented this in Scala but I can expose it in python if necessary.

[hail] implement (Scala) NDArrayConcat

---

auth/auth/auth.py

It seems that sessions sometimes become inaccessible to auth. Using some
logging, I realized that `/login` will set some session parameters that do not
reappear in `/oauth2callback`. While trying to debug this, I deleted my cookie
and everything started working again. Luckily, my phone was still borked. The
fix is to use `new_session` which I discovered with a big red warning in
aiohttp-session's docs: [Always use new_session() instead of get_session() in
your login views to guard against Session Fixation
attacks!](https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.new_session).
If nothing else, we are now safe from session fixation attacks. I do not
understand why this is necessary for correctness.

[auth] maybe fix auth flow & close security hole

---

hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Compilable.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/lowering/Rule.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Defines, but does not implement, a BlockMatrixCollect value IR node.
This is kind of an awkward node currently. We cannot compile nodes with BlockMatrixIRs. We cannot interpret nodes with NDArrayIRs. So we can't compile this or interpret this, unless we define an interpreted version of NDArray (or a compilable version of BlockMatrix).
I think this node might eventually be useful for Hail BlockMatrix -> Hail NDArray -> Python ndarray conversions, but for now the intention is to use this as a quick way to start testing BlockMatrix lowering.

[hail] define BlockMatrixCollect node

---

batch/batch/driver/scheduler.py

Timing:
```
mysql> SELECT job_id, spec, cores_mcpu FROM jobs WHERE batch_id = 10 AND state = 'Ready' AND always_run = 0 AND `cancelled` = 0 LIMIT 1;
+---------+------------------------------------------------------------------+------------+
| job_id  | spec                                                             | cores_mcpu |
+---------+------------------------------------------------------------------+------------+
| 1606431 | [[["batch-pods", "konradk-gsa-key", "/gsa-key", 1]], null, 1, 1] |       1000 |
+---------+------------------------------------------------------------------+------------+
1 row in set (1.22 sec)
mysql> SELECT job_id, spec, cores_mcpu FROM jobs FORCE INDEX(jobs_batch_id_state_always_run_cancelled) WHERE batch_id = 10 AND state = 'Ready' AND always_run = 0 AND …
```

[batch] use force index to speed up queries

---

batch/batch/google_storage.py
batch/batch/worker.py
hail/python/hailtop/utils/utils.py

This fixes two bugs:
1. The container logs weren't being cached. This made the logs "disappear" for previous tasks while the job was still running. FYI @konradjk 
2. My job got stuck in "running" even though the job was deleted from the worker because writing the status to GCS timed out and we didn't actually mark the job complete. I'm not sure if we should always try to retry writing the status rather than failing on non-transient errors.
```
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
six.raise_from(e, None)
File "<string>", line 2, in raise_from
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
httplib_response = conn.getresponse()
File …
```

[batch] fix bugs in worker

---

hail/python/hailtop/batch_client/aioclient.py

Fixes #8083 
The format of the status is 
```
```

[batch] fix exit code when error occurred

---

batch/deployment.yaml

A field value that can be interpreted as a number in YAML is parsed as an int64 and k8s does not approve of this.

[batch] fix deploy

---

hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/Binds.scala
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala

this will let us lift the implicit densification that happens in operations like BlockMatrixMap's sum, etc. into an explicit BlockMatrixDensify node on the python side.
necessary for moving sparsity into BlockMatrixType.

[hail] add sparsity tracking flags to BlockMatrixMap and Map2

---

hail/python/requirements.txt

Nik ran into humanize not being imported to use Pipeline. I added it to the requirements.txt that I believe is the correct requirements.txt. I think the other ones in the docker folder are just for creating docker images.

[hailtop] add humanize to requirements.txt

---

batch/batch/worker.py
ci/ci/constants.py
ci/ci/github.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

This got a bit complicated to ensure idempotence.
This should make issues related to GitHub hiccups during clones and fetches even
rarer than they are now (retry three times, as we do for uploading).
I added a function called `clone` which:
- creates a temporary,
- clones into the temporary directory, and
- copies every file in the directory (including hidden files) into the current
directory
I added retries to clones and fetches (which are already idempotent).
I removed duplication of cloning and fetching scripts. I also moved the shell retry function to `hailtop.utils`.

[ci] Retry clones and fetches

---

hail/python/hail/ir/blockmatrix_ir.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/types/BlockMatrixType.scala
hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

adds a notion of sparsity to BlockMatrixType; I've lifted all of the necessary logic except for Map/Map2, which needs #8072 to implement in a sensical way.
I had originally implemented this as a dense boolean matrix, which makes a lot of transformations simpler, but for really large (and very sparse) block matrices, you end up needing ~GB of space just to store the sparsity matrix, which is pretty untenable. This version basically preserves the structure of the version on GridPartitioner, except that we're storing the unlinearized form of the block index.

[hail] add sparsity to BlockMatrixType

---

hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/types/BlockMatrixType.scala

Map2 needs to compute its sparsity based on the provided merge strategy.
Also apparently i forgot to include densify in the other PR, so I'm including it here.

[hail] fix sparsity for Map/Map2/Densify nodes

---

hail/src/main/scala/is/hail/expr/ir/Compilable.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/lowering/IRState.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPass.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPipeline.scala
hail/src/main/scala/is/hail/expr/ir/lowering/Rule.scala

We're currently emitting the explicit node (without optimization!).
This design is incrementally better, and lets us do ptyping more easily.
The right solution is to do generate a method as the node suggests, but
there are some issues to sort out here, like how to return a missing
value. We may need to return a (possibly null) pointer to an allocated
value, which could be inefficient. Pushing ptypes/requiredness fully
through the system would let us avoid this in many cases.
cc @catoverdrive

[hail] Inline ApplyIR in compile lowering pass.

---

hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py

jgscm doesn't seem to be maintained, relies on super old google libraries. Let's use our hail fork of jgscm instead, as that fork has been modified both to use the new google libraries and to not crash in the presence of requester pays buckets. We may consider just publishing something called `hail-jgscm` to pypi instead of this weird github based method.

Use Hail version of jgscm

---

hail/python/hail/ir/ir.py
hail/python/hail/matrixtable.py
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Stacked on #8032
Compared to parent:
```
$ hail-bench compare ~/misc/debug/qc_after.json ~/misc/debug/qc_after_2.json
variant_qc      95.0%     4.809     4.568
sample_qc      94.1%    13.470    12.671
variant_and_sample_qc_nested_with_filters_2      79.1%    16.749    13.246
variant_and_sample_qc_nested_with_filters_4      65.2%    38.048    24.797
```

[hail] Add MatrixCount IR node

---

router/router.nginx.conf.in

@danking the changes in the router configuration for the blog are causing an infinite redirect loop when you try to go to https://blog.hail.is. I'd like to change them back to how they were before (I added the X-Real-IP line that was not in the original configuration, which I think is the change you were introducing in that PR, although I have no idea how that works.)

[blog][bugfix] revert router headers for blog

---

auth/Dockerfile

Root cause: https://github.com/googleapis/google-auth-library-python/issues/443
`google-auth-oauthlib` does not pin any version of `google-auth` (I [created a PR](https://github.com/googleapis/google-auth-library-python-oauthlib/pull/71) to start pinning major & minor version). However, that wouldn't have saved us, the change (it increasingly appears to have been a bug, not an accidental breaking change) was introduced in the patch version 1.11.1. This pins *us* to 1.11.0. I am subscribed to the bug and will remove the patch-version pin once a fix is released.

[auth] resolve auth bug by pinning google-auth version

---

router/proxy.conf
router/router.nginx.conf.in

The proxy should propagate an existing forwarded protocol and
host if either exists. See the definition of `$updated_...` in
`nginx.conf`.
Revert blog to standard proxy rules now that proxy rules are correct.

[router][blog] fix proxy rules

---

hail/python/test/hail/experimental/test_experimental.py
hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala

Right now, IR function registration fails in the following case.
- Multiple Python HailContexts are running on the same cluster
- User on HailContext A calls a function (eg. create histogram) that triggers `hl.experimental.define_function`
* An anonymous function is used to create a new `Set` in `IRFunctionRegistry.irRegistry`
- User on HailContext B calls the same function
* The anonymous function is added to create a `Set` of size `2` in `IRFunctionRegistry.irRegistry`, as anonymous functions are never considered equivalent
* This triggers a fatal error `Multiple functions found that satisfy ...`
By changing the definition of `IRFunctionRegistry.irRegistry` from a `MultiMap(functionName -> Set[argumentTypes, returnType, alwaysInline, anonymousFunction])` to a `Map(functionName -> …

Make IR function registration idempotent

---

hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

ReadValue reads a value from a file. It behaves equivalently to ReadPartitions, except that it reads non-stream objects while ReadPartition reads stream objects.
WriteValue writes a value to a file. It takes a filly qualified path prefix and returns the fully qualified file path. (This is so we can eventually implement the thing we do on writes now, where we could potentially try to write a partition multiple times, appending a unique suffix each time, and will only collect the path names of the ones that completed successfully.)
Eventually, we might want to merge ReadValue/ReadPartition and WriteValue/WritePartition, but it might also be nice to know based on the type of node whether it handles a stream.
This just contains all of the definitions associated with the IR node; I'll …

[hail] define (unimplemented) ReadValue and WriteValue IR nodes

---

hail/python/hail/linalg/blockmatrix.py
hail/python/hail/methods/statgen.py

Intended as a replacement for
```
bm = BlockMatrix._from_java(bm._jbm.filterRowIntervalsIR(Env.backend()._to_java_ir(starts_and_stops._ir), False))
```
which I hope to remove support for in the near future. The new invocation would be:
```
bm = bm._sparsify_row_intervals_expr(starts_and_stops, blocks_only = False)
```

[hail] write undocumented function for passing expr to sparsify_row_intervals

---

hail/python/hail/docs/experimental/vcf_combiner.rst
hail/python/hail/experimental/vcf_combiner.py
hail/python/scripts/drive_combiner.py

Official [GATK documenation] uses GVCF.
[GATK documenation]: https://gatk.broadinstitute.org/hc/en-us/articles/360035531812-GVCF-Genomic-Variant-Call-Format

[combiner] s/gVCF/GVCF/g

---

hail/python/hail/ir/base_ir.py
hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/ir/blockmatrix_reader.py
hail/python/hail/ir/blockmatrix_writer.py
hail/python/hail/ir/ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/backend/Backend.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/backend/spark/SparkValueCache.scala
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/BlockMatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Compilable.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/types/BlockMatrixType.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

This lets us get rid of python-side BlockMatrix (_jbm) and BlockMatrixLiteral (JavaBlockMatrix) notions, so that every BlockMatrix manipulation either generates/transforms a (python-level) BlockMatrix IR or executes one.
I don't *super* like that there's an IR node for unpersist, but it did help move things cleanly into the "everything is BlockMatrixIR or .execute()" world.
This should also let us get rid of `BlockMatrixLiteral` (which I'll do in a separate PR) and lifts over the last piece that was constructing a BlockMatrix directly from python without going through BlockMatrixIR.
Eventually, I'd like to move Table/MatrixTable caching over to something like this as well, since I think it's going to be easier to tie in to the lowering.
cc @tpoterba

[hail] introduce caching to BlockMatrixIR

---

hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/io/TextMatrixReader.scala

As far as I can tell, the scan we were doing here was just incorrect.

Fix text matrix reader partition count

---

hail/src/main/scala/is/hail/methods/Nirvana.scala
hail/src/main/scala/is/hail/methods/VEP.scala
hail/src/main/scala/is/hail/utils/richUtils/RichIterator.scala

This is untested, but probably can't make things worse.
fixes #8146

[bugfix][hail] Capture error rather than printing it

---

hail/src/main/scala/is/hail/variant/HardCallView.scala

Scala pattern match is too weak and terrible for this seemingly obvious use-case. (nb: `null` cannot be used with pattern matching).

[hail] fix import_bgen

---

hail/src/main/scala/is/hail/asm4s/joinpoint/ParameterPack.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

~~Stacked on #8129~~
This PR adds support for the new streams in the emit code for `ArrayMap`, and for all stream consumers in `Emit` except `CollectDistributedArray` (ArraySort, ToSet, ToDict, ToArray, GroupByKey, and ArrayFold2). Once `CollectDistributedArray` is ported, we can get rid of `EmitArrayTriplet` and `ArrayIteratorTriplet`.
While I was wrangling with `ArrayFold2`, I made some tweaks and additions to the EmitTriplet ParameterPack to help make the emitter code more readable and easier to work on. I think the changes are likely to be in a similar direction as Cotton's PValue proposal, so I don't anticipate this making migration away from ParameterPack any harder (hopefully easier).

[Hail/streams] port more stream consumers

---

batch/batch/driver/instance_pool.py
batch/batch/driver/scheduler.py
batch/batch/worker.py
docker/Makefile
gear/gear/database.py
hail/python/hailtop/utils/utils.py
internal-gateway/deployment.yaml
internal-gateway/internal-gateway.nginx.conf
letsencrypt/letsencrypt-pod.yaml.in
router/Makefile

- At the end of schedule, log total time and number of jobs scheduled.
- Only log database timing if total query took >20ms.
- Make sure context_manager is cleaned up in gear.Transaction.
- Limit workers to max 250 requests/s incoming to batch driver.  I used an nginx limit to do this, but it is per pod, so I turned off autoscaling and increased CPU to roughly what I saw when 100K cores was hammering against a dead driver.
- Increase the worker exponential backoff from 30s to 2m.
The main thing I was trying to address was the driver getting overloaded when trying to restart with a large standing cluster.  It isn't totally clear why the cluster failed in the first place.  I made a few other changes to mitigate the issue before adding the nginx limit, so I'm not 100% …

[batch] batch tweaks

---

batch/batch/worker.py

This PR makes docker calls idempotent and adds a timeout for docker calls in the retry function.
I got the error codes to ignore from the older docker documentation at the bottom of each API call: https://docs.docker.com/engine/api/v1.30/#operation/ContainerDelete
FYI: @cseed since you had opinions on the timeout times

[batch] make docker calls idempotent with a timeout

---

batch/batch/worker.py

Docker also reports transient DNS resolution failure as 500.

[batch] add transient error

---

ci/ci/github.py

I want the function to exit in error if any step fails. I achieve this by
starting a sub-shell and setting -e inside that sub shell. That causes the
sub-shell to exit if any individual command fails.
Previously, the `git clone` could fail but `clone` would still return exit code
zero.

[batch] fix retry of clone

---

hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala
hail/src/main/scala/is/hail/asm4s/StagedBitSet.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/SpecializedArrayBuilders.scala
hail/src/main/scala/is/hail/io/TextMatrixReader.scala
hail/src/test/scala/is/hail/asm4s/ASM4SSuite.scala

This the beginning of some Code infrastructure changes and cleanup.  The plan is to clean up the tangle of builder classes.  I'm still working on the plan for dependent functions, but the skeleton of the rest looks like:
```
class ClassBuilder[C]
def newMethod(suffix: String, argsInfo: Array[TypeInfo[_]], returnInfo: TypeInfo[_]): MethodBuilder
def newField[T]: ...
def result(): () => C
class MethodBuilder:
def newLocal[T]: LocalRef[T]
def emit(c: Code): Unit
class FunctionBuilder[C]:
val classBuilder: ClassBuilder[C]
def applyMethod: MethodBuilder
def result(): () => C = classBuilder.result()
class EmitMethodBuilder
val mb: MethodBuilder // contain don't extend
```

[query] Add class builder

---

build.yaml
hail/Dockerfile.hail-repl
hail/Makefile
hail/hail_repl.yaml

This is runIfRequested deployment that simply has hail
and ipython installed. It facilitates developmnent of
services that interact with Hail Query (i.e. the Shuffler).
I do this silly thing with a tar file because:
- I do not know the hail version (which is included in the wheel filename), so
- I am unable to copy it out with a variable name, and
- python refuses to install a wheel that does not have the version in the filename
I added `make update-hail-repl` to `hail/Makefile` which updates the hail wheel on the hail-repo without changing the pod or rebuilding the image. If the pod is restarted you lose your version, but the risk is worth the immense benefit of 5s deploys.

[hail-repl] add a hail-repl definition

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/expr/types/physical/PNDArray.scala

John, to gain some familiarity with your codebase, a proposed change. Makes the interface 1 method smaller, and reduces a bit of complexity in element value loading. Also fixes a potential source of errors long term: element loading should depend on the representation (as this controls memory layout), and not the elementType passed to the PNDArray constructor.
This came up as I was writing down the invariants for PNDArray for the PTypes design doc. Feel free to push back on this if you have plans for getElementAddress (although if that's the case we should get rid of loadElementToIRIntermediate)

[hail/ptypes/PNDArray] remove elementAddress

---

hail/python/hail/expr/functions.py
hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/annotations/UnsafeRow.scala

Instead of `hl.struct(x=3, foo="hi")` looking like `[3, hi]` it will look like `{x: 3, foo: hi}` which is a mild improvement.

[hail] improve unsafe row printed form

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_ndarrays.py

We were missing `__rmatmul__`.
The treasures you find when cleaning up my shuffler PR 🤷‍♂ .

[hail.nd] interoperate with numpy

---

hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/FoldConstants.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

This node filters an NDArray to a smaller NDArray that has only the specified rows/cols/etc. along a specific axis, in the specified order. It will be used for lowering BlockMatrixFilter.
If the array of indices along a given axis is missing, then we preserve the original indexing along that axis. If an element in the array of indices is missing, we throw a runtime error.
The filter/don't filter decision for a given axis could also be lifted to a compile-time decision, rather than a runtime decision (say by having the type of the filter along that axis being `ttuple[]` instead of `tarray<tint64>`).
Unlike NDArraySlice, it does not give the option of reducing the number of dimensions of the NDArray, although I can change that if we have a use for it.

[hail] implement NDArrayFilter node

---

hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala
hail/src/main/scala/is/hail/asm4s/package.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala

Stacked on: https://github.com/hail-is/hail/pull/8179
This adds ModuleBuilder.  A module is a collection of classes whose bytecode should be loaded together (like a function and some associated dependent functions).  Dependent functions now add themselves to the module.

[query] Add module builder

---

batch/batch/driver/instance.py
batch/batch/worker.py

We must have had an instance that was still active in batch, but it's IP address had already been assigned to another instance.
I couldn't find anything about get caching responses without using a separate package to do that.

[batch] fix instance check when ip address is reused

---

hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/asm4s/joinpoint/ParameterPack.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/agg/AppendOnlyBTree.scala
hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala
hail/src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/main/scala/is/hail/expr/types/encoded/EArray.scala
hail/src/main/scala/is/hail/expr/types/encoded/EBaseStruct.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalNDArray.scala

[query] remove Code._empty type parameter

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/PValue.scala

- add PIndexableValue.  This represents canonical array, set and dict values.
- use in ArrayRef
- newP{Local, FIeld} now has a `PV <: PValue` type parameter to eliminate some casting
Where I'm going:
There will be a abstract PValue with the interface for each virtual type (container/indexable, base struct, etc.)  Each concrete PType will have a corresponding PValue implementation (in this case, PCanonicalArray is implemented by PCanonicalIndexableValue.)  I think this will allow us to get rid of PArrayBackedContainer.  Only primitive PValues will have a code method (since other types might be compound).
The code generator should then dispatch through downcasts of PValues get access to the relevant methods.

[query] add PIndexableValue

---

hail/src/main/scala/is/hail/asm4s/joinpoint/ParameterPack.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala

~~Stacked on #8140~~
This PR adds support for the new streams in the emitter for ArrayFilter, ArrayZip, ArrayFlatMap, If, and Let.
It also changes the semantics of `Stream` slightly: Before, a producer had to close itself before calling EOS on its consumer. Now, the consumer is responsible for closing the producer after the producer calls EOS. This makes flatMap slightly more complicated, but it allows a significant simplification to zip.
To implement the different modes of `ArrayZip`, I added `extendNA` and `take`. `extendNA` turns a stream into an infinite stream, where values after the end are missing, to allow the consumer to decide what to do when the stream ends. `take` is then needed to end infinite streams. Both use `COption` to encode whether the child stream has ended / whether …

[query/streams] port more stream nodes

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
hail/src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala

In this PR:
- removed unused region arg for `fb.addLiteral`
- add non-type-serialization path for PLocus in wrapArgs
- port isAutosomal, … to not rely on RG serialization (does the implementation look reasonable?)

[query] elide more RG serializing

---

hail/src/main/scala/is/hail/annotations/Region.scala
hail/src/main/scala/is/hail/expr/ir/PValue.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalArray.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalDict.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalSet.scala
hail/src/main/scala/is/hail/expr/types/physical/PType.scala

OK, this one is slightly subtle.  A physical value at runtime actually has two forms:
1. It is a bunch a bunch of bytes in memory at a particular address (e.g. a struct field, an array element, or a freestanding value in memory).
2. It is a value made up of JVM primitive values (or, more abstractly, Code[T]'s) that can be operated on immediately.
Note, one option for (2) is just the address (1).  This is what we do for structs (but note, not for arrays).
Therefore, one thing we need is an operation that constructs a PValue from a physical type and an address to go from (1) => (2).  I call this `PType.load`.  It will be used in, for example, loadElement or loadField.  See the use in loadElement below in PCanonicalIndexableValue.
We also need something that goes from (2) => (1).  There are …

Add PValue load/store.

---

hail/src/main/scala/is/hail/backend/HailTaskContext.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/io/CodecSpec.scala
hail/src/main/scala/is/hail/utils/package.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

I wanted `WriteValue` to be able to essentially generate filenames exactly like we currently do in crdd.writePartitions, so I added a `HailTaskContext` concept to be able to mimic that behavior. It'll currently generate files named `prefix` if run on the master, and files named `prefix-stage-partition-…` if run in a distributed setting.
We may eventually want to parameterize the behavior of `WriteValue` to have it do different things with the filename, but I think this will be enough to start moving over some of the writers.

[hail] implement ReadValue/WriteValue in Emit

---

hail/src/main/scala/is/hail/HailContext.scala

Should be useful for benchmarking and other circumstances where
HailContexts are being started and stopped more often.

Configure feature flags with environment variables

---

hail/python/hailtop/hailctl/dataproc/start.py

Adds two new `hailctl dataproc start` flags to allow reading from requester pays buckets.
```
hailctl dataproc start my-cluster --requester-pays-allow-all
```
allows you to read from any requester pays bucket.
```
hailctl dataproc start  my-cluster --requester-pays-allow-buckets bucket1,bucket2
```
allows you to read from `gs://bucket1` and `gs://bucket2`, regardless of whether they're requester pays.

Support Requester Pays

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/SpecializedArrayBuilders.scala
hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala

~~Stacked on #8172~~
Implement emitters for StreamScan, RunAggScan, and StreamLeftJoinDistinct. These complete the handling in the new emitter for non-root stream nodes (i.e. those which take stream children). Thus it is now safe to delete non-root nodes from the previous EmitStream.
This also implements length tracking in the new EmitStream, and adds back the optimizations that take advantage of knowing the length, plus some we weren't doing before, like in ArraySort and CollectDistributedArray.

[query/streams] remaining non-root stream nodes, add back length tracking

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala

I thought just removing the `asInstanceOf`s altogether would be fine, but it seems the explicit casts to `any` are necessary for this to go through.

Don't make it seem like NDArray elements have to be doubles

---

dev-docs/hail-query/linalg/block-matrix-lowering.md
hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/backend/Backend.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/IRState.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPass.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPipeline.scala
hail/src/main/scala/is/hail/expr/ir/lowering/Rule.scala
hail/src/main/scala/is/hail/expr/types/BlockMatrixType.scala
hail/src/main/scala/is/hail/expr/types/physical/PType.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/lowering/BlockMatrixStageSuite.scala

This PR describes a lowering framework for BlockMatrixIR -> CollectDistributedArray.
As part of this, I split out a `LowerIR` function from the `LowerTableIR` value rules so that we can apply lowering more modularly, if desired. It delegates to `LowerTableIR` and `LowerBlockMatrixIR` for the relevant nodes but lets us use both the table lowerer and/or the block matrix lowerer together as desired.
(this PR turned into quite a large change, since I ended up implementing enough to start testing the lowering, but I'm happy to break it up, too.)
cc @cseed @tpoterba @danking @patrick-schultz @johnc1231

[hail] LowerBlockMatrixIR skeleton

---

hail/src/main/java/is/hail/utils/IntPacker.java
hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/expr/ir/AbstractMatrixTableSpec.scala
hail/src/main/scala/is/hail/expr/ir/agg/StagedBlockLinkedList.scala
hail/src/main/scala/is/hail/expr/types/encoded/EPackedIntArray.scala
hail/src/main/scala/is/hail/expr/types/encoded/EType.scala
hail/src/main/scala/is/hail/io/InputBuffers.scala
hail/src/main/scala/is/hail/io/MemoryBuffer.scala
hail/src/main/scala/is/hail/io/OutputBuffers.scala
hail/src/main/scala/is/hail/utils/richUtils/Implicits.scala
hail/src/main/scala/is/hail/utils/richUtils/RichCodeInputBuffer.scala
hail/src/main/scala/is/hail/utils/richUtils/RichCodeIntPacker.scala
hail/src/main/scala/is/hail/utils/richUtils/RichCodeOutputBuffer.scala

We use Lemire et al.'s Stream VByte algorithm, as described in 
https://arxiv.org/abs/1709.08990
```
Encoded Format:
int (length)
missing bits (if necessary)
int (length of control bytes)
int (length of data bytes)
control bytes
data bytes
```
This was split off from continuted development on top of #7803, ideally they should be merged together.

[hail] Add packed integer EType

---

hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/agg/ArrayElementLengthCheckAggregator.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalArray.scala
hail/src/main/scala/is/hail/io/TypedCodecSpec.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

Changes:
- Defer allocation of locals until MethodBuilder.emit is being called.  This means LocalRefs can be created without a MethodBuilder.
- LocalRef now tracks the method builder it is (1) being constructed from and/or (2) being emitted into (which can be null if we don't know yet).  If there is ever disagreement, die.
- Leave in commented out code to print stack trace from newLocal call for the offending local.  This makes debugging a snap.  FYI @johnc1231 
- Remove mb argument to NDArrayEmitter, add it to the various code generation functions.  I think putting a method builder in a data structure is an anti-pattern.  
- Fix a variety of local issues in narray and aggregator code.
- Emit now takes a FunctionBuilder instead of a MethodBuilder.  Emit.emit takes a MethodBuilder.
- Add …

[query] add Code.memoize and check locals

---

hail/src/main/scala/is/hail/annotations/ExtendedOrdering.scala
hail/src/main/scala/is/hail/utils/Interval.scala
hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala

Interval struct comparisons were inconsistent/wrong.

query] Fix and reenable flaky ordering tests

---

hail/src/main/scala/is/hail/io/gen/ExportBGEN.scala

`boundary` is safe because after `it.next()` is called, the previous
value is no longer needed.
Fixes #8163

[query] Fix `hl.export_bgen` memory leak

---

hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala

`copyFrom` method was simply wrong. Also needed to fix memory management
in `result` function.
Fixes #8240

[query] Fix `hl.agg.downsample` inside array_agg or group_by

---

hail/python/hail/matrixtable.py
hail/python/test/hail/matrixtable/test_matrix_table.py

[query] Fix bad error message from `mt.make_table()` with missing keys

---

hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/expr/ir/agg/ApproxCDFAggregator.scala

Caveat: The ApproxCDFStateManager object is not freed, but is leaked
to the region. This behavior is similar to other aggregators.
Fixes #7824

[query] Fix `hl.agg.approx_cdf` inside group_cols_by

---

hail/python/hailtop/hailctl/dataproc/start.py

Now there are `hail-uk-vep` and `hail-eu-vep` buckets. Both are requester pays. This PR adds mappings from regions in those areas to the corresponding VEP data replicates. Once this goes in, we can do a release, after which we can change the permissions on the current hail vep folder to be not public (eventually we will delete, but maybe there's something in there I haven't noticed yet that people need / want).

[hailctl] Add EU and UK VEP

---

benchmark/Makefile

More replicates and fewer iterations seems to reduce variance, and
finishes faster as well.

[benchmark] Tweak benchmark pipeline parameters

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/main/scala/is/hail/sparkextras/ContextRDD.scala

Both coalesce and naiveCoalese couldn't handle empty keys because the
partition bounds we generate for unkeyed partitions fail isValid with
allowedOverlap of -1. Even if that was ok (make it so that empty keyed
partition bound sets are automatically valid), we end up duplicating all
the data per partion since RepartitionedOrderedRDD2 uses range bound
queries to determine what data goes into each partition. In the empty
case that duplicates the data once for every partition.
The solution here is to take both coalesce and naiveCoalese away from
using repartition in the shuffle=false case and to using RDD.coalesce.
We need to be sure to use a custom PartitionCoalescer in order to create
identical selection to the previous naiveCoalese that is partitioned
with a key.
fixes #8138

[query] Use RDD.coalesce and custom coalescer for non-shuffle repartitioning

---

hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

The main point here was to implement an `assertBMEvalsTo` function that works a lot like `assertEvalsTo` for IR---currently only testing existing tests through interpret and BlockMatrix, but as we move lowering things over we can also add eval strategies for existing tests to test them through the lowerer as well.
I also removed a lot of the explicit BlockMatrix construction and conversions since we can handle them through the IR.
(also removed the lowering test in favor of adding the lowered execStrategy to the BlockMatrixDot test as it's essentially a duplicate of that)

[query] tidy up BlockMatrixIRSuite

---

hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/TableValue.scala
hail/src/main/scala/is/hail/io/bgen/BgenRDD.scala
hail/src/main/scala/is/hail/rvd/RVDContext.scala

~Stacked on #8283~
We were creating fresh regions to pass as the `partitionRegion` to compiled functions deep within `ContextRDD` pipelines. Doing it that way, there's no clear owner responsible for freeing those regions. We're currently relying on Spark to clean them up.
This PR adds a `partitionRegion` field to `RVDContext`. This way, the root consumer is responsible for creating the partition region before running the iterator, and for freeing it after.
This is a step towards clarifying the structure of region ownership.

[query] add partitionRegion to RVDContext

---

batch/batch/worker.py
batch/test/test_batch.py

Also fixed getting the logs for a job.
- I didn't realize the context manager for asyncio_timeout was throwing an asyncio.TimeoutError. Now, I handle the TimeoutError exception and then throw our own exception after we've uploaded the logs and cleaned up the container. This way it still shows up as an error.
- I noticed the logs were being cached when a user gets the logs while the job is running and we don't update the cache until the job is complete. Therefore, I think from the code, if the user asks for the logs part-way through the job running, they wouldn't see any updates until the job is completed. I'm not sure why no-one has complained about this yet, so might be good to double check that this is indeed a bug.

[batch] upload logs after timeout occurs in worker

---

batch/batch/front_end/front_end.py
batch/batch/worker.py

@danking I remember you wanted raise web.Response() here for a reason, so I'll let you decide if this is correct or not.
```
{"levelname": "ERROR", "asctime": "2020-03-13 15:53:52,139", "filename": "web_protocol.py", "funcNameAndLine": "log_exception:355", "message": "Error handling request", "exc_info": "Traceback (most recent call last):
File \"/usr/local/lib/python3.6/dist-packages/batch/front_end/front_end.py\", line 635, in insert
jobs_args)
File \"/usr/local/lib/python3.6/dist-packages/gear/database.py\", line 172, in execute_many
return await cursor.executemany(sql, args_array)
File \"/usr/local/lib/python3.6/dist-packages/aiomysql/cursors.py\", line 283, in executemany
self._get_db().encoding))
File \"/usr/local/lib/python3.6/dist-packages/aiomysql/cursors.py\", line 318, in …
```

[batch] fix duplicate key insert error

---

docker/Dockerfile.base
hail/install-gcs-connector.sh

Fixes #8343. The Google Storage Hadoop connector introduced
a backwards incompatible change in 2.1.0 which relies on
a new method in Hadoop 2.8.3 that is not present in Hadoop
2.7.3. There are no Spark releases that include Hadoop 2.8.3
yet, so we choose to downgrade to the last compatible
connector library version.
Randomly picked a hail query person.

[hail] fix hadoop connector in hail base image

---

hail/build.sbt
hail/project/Dependencies.scala
hail/project/build.properties
hail/project/plugins.sbt

It's obvious that I'm the only one using SBT 😉 .
I removed this spark helper thing that data bricks has abandoned. It's not hard to specify the right spark dependencies manually. In fact, we do that in `build.gradle` already.
I don't know what the deal with hadoopClient, but it didn't seem necessary for my tests to pass. We don't use SBT for deployment, so I'm not worried.
I'm not sure how all the http4s and json4s stuff got pulled in. They're not present in grade, so I removed them.
I also bumped the SBT version for no particular reason. 🤷‍♀ . It works.

[hail] SBT fixes

---

hail/src/main/scala/is/hail/expr/ir/PCode.scala

I missed this when I added PLocusCode in #8351

[query] Add PLocus to PCode constructor match

---

hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/expr/types/encoded/ETransposedArrayOfStructs.scala
hail/src/main/scala/is/hail/expr/types/encoded/EType.scala
hail/src/main/scala/is/hail/io/RichContextRDDRegionValue.scala
hail/src/main/scala/is/hail/io/index/IndexWriter.scala
hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala
hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/test/scala/is/hail/io/IndexSuite.scala

High level changes are as follows:
+ Add one new EType, ETransposedArrayOfStructs.
The layout of ETransposedArrayOfStructs is as follows:
```
START:
encoded length (int)
array's missing bits (sequenceof byte) [if struct not required]
FOREACH field in struct:
field's missing bits (sequenceof byte, length is NOTE) [if field not required]
field elements (sequence of encoded field)
NOTE:
The length of a field's missing bits is equal to the number of present array elements.
If the array is of length 100, but only has 10 present elements, then each field's
missing bits will have 10 bits (2 bytes).
```

[query] Encoder for encoding arrays of structs as 'structs of arrays'

---

hail/python/hailtop/utils/utils.py

This is thrown by the connector which always uses it to wrap an OSError

[hailtop] retry transient ClientConnectorError

---

vdc/Makefile
vdc/README.md

I verified this manually. The deploy account didn't exist when I started this PR, but it still had a role grant in the project's IAM policy. Now the account still does not exist *and* the role grant is gone.
The `login` forces you to switch to your account since we're deleting the service account (as which you're probably authenticated).

[vdc] update playbook for using deploy account

---

ci/ci/ci.py
ci/test/test_ci.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py

CI gets the logs for every failing job in the batch and sends it with the deploy_status response. This performs O(n_jobs) work for a single request, but this API is developers only and used only by the deploy test which has a small batch. We can revisit if this becomes a problem.

[batch][ci] better error message when the deploy test fails

---

hail/src/main/scala/is/hail/annotations/RegionMemory.scala
hail/src/main/scala/is/hail/annotations/RegionPool.scala
hail/src/main/scala/is/hail/sparkextras/ContextRDD.scala

ContextRDD registered a TaskCompletionListener with Spark to close its context no matter why the task ends. But if the region in the context points to RegionMemory that is shared (has refcount > 1), this won't actually free the memory. Plus, this doesn't free any regions not created by an RVDContext.
This PR removes the TaskCompletionListener from ContextRDD, and instead adds a single one to each thread-local RegionPool. This clearly ensures all off-heap memory is freed at the end of the task.

[query] Move spark region finalization from ContextRDD to RegionPool

---

hail/src/main/scala/is/hail/expr/ir/Binds.scala
hail/src/main/scala/is/hail/expr/ir/FreeVariables.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Fixes #8338 
The problem was that in `FreeVariables.scala`, we call `ChildEnvWithoutBindings` to create a new env. It's important that the new env we get has the same type of aggregation environments as the `baseEnv`.

Fix LiftMeOut bindingEnv in ChildEnvWithoutBindings

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/test/hail/matrixtable/test_matrix_table.py
hail/src/main/scala/is/hail/expr/ir/Env.scala
hail/src/main/scala/is/hail/expr/ir/Exists.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
hail/src/main/scala/is/hail/lir/X.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

Fixes #8325
Got rid of dummy_table logic, which is unnecessary with `parallelize`.
Agg/Scan envs were being mishandled in Extract/liftScan.

[query] Fix bugs related to Duncan's permutation pipeline

---

benchmark/python/benchmark_hail/run/combiner_benchmarks.py
benchmark/python/benchmark_hail/run/resources.py
hail/src/main/java/is/hail/io/compress/BGzipInputStream.java

Improves performance of GVCF import significantly:
```
Benchmark Name      Ratio     Time 1     Time 2
--------------      -----     ------     ------
import_gvcf_force_count      81.2%     68.737     55.833
import_and_transform_gvcf      79.9%     75.692     60.464
Harmonic mean: 80.5%
Geometric mean: 80.6%
Arithmetic mean: 80.6%
Median:  80.6%
```
Stacked on #8382

[query] Improve BGzipInputStream.read

---

hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/asm4s/CodeBuilder.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala

This is a just a cleanup move.  It removes the ambiguity in the code of what m, v should be for (can a Void type be missing?  If it is present, should v be executed?)  It eliminates a potential issue I ran into earlier with a Code[Unit] had state changes in its missing field.   In particular, I had (at the time, incorrectly) assumed EmitCode(setup, m, v) was the same as EmitCode(Code._empty, Code(setup, m), v).  Now that should be correct.
In order to (slowly) push CodeBuilder forward, I wrote emitVoid with it.

[query] move void IR codegen to Emit.emitVoid

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

This step is probably the easiest. Remove the `PType` from `(PType, EmitCode)` pairs. It should always agree with the `PType` on the corresponding `EmitCode`

[query] Begin converting function registry from Code to PCode

---

hail/python/hail/experimental/vcf_combiner.py
hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala

Made some logging improvements to the combiner in the process of
understanding the various components. Benchmarks, docs, perf.
improvements are next.
Simple example of merging three GVCFs:
```
2020-03-27 15:17:58 Hail: INFO: GVCF combiner plan:
Branch factor: 2
Batch size: 2
Combining 3 input files in 2 phases with 2 total jobs.
Phase 1: 1 job corresponding to 2 intermediate output files.
Phase 2: 1 job corresponding to 1 final output file.
2020-03-27 15:17:58 Hail: INFO: Starting phase 1/2, merging 3 input GVCFs in 1 job.
2020-03-27 15:17:58 Hail: INFO: Starting job 1/1 to create 2 merged files, corresponding to ~50.0% of total I/O.
2020-03-27 15:21:20 Hail: INFO: Finished job 1/1, 50.0% of total I/O finished.
2020-03-27 15:21:20 Hail: INFO: Finished phase 1/2.
2020-03-27 15:21:20 Hail: …
```

[vcf-combiner] Usability improvements to vcf combiner

---

ci/ci/github.py

I never tested that PR that got merged (whoops!) and CI tests are insufficient
to catch this case (we should beef those up, asana task added).
The issue was that I thought the method to issue an HTTP get request was `get`,
but it was `getitem`. This PR fixes that. This error occured during `update` and
thus prevented all forward progress of CI.

[ci] fix "GitHubAPI object has no attribute 'get'" error

---

hail/python/hailtop/hailctl/__main__.py
hail/python/hailtop/hailctl/curl.py

This makes it easy to send authenticated HTTP requests to our
infrastructure. When developing a new service, you might not have an
existing (or working) client yet and want to explore the HTTP endpoints with
cURL.

[hailctl] authenticated curl

---

hail/src/main/scala/is/hail/rvd/RVDContext.scala

The biggest headaches always seem to have the smallest code changes to fix.

RVDContext must own partitionRegion or it won't be cleaned up

---

ci/ci/ci.py
ci/ci/github.py

- Fix statuses for dev deploys.
- Fix zulip notify for dev deploys (not currently used).
- Fix HTTPFound for dev deploys and PRs.
We need to prefix the redirect with the base path
for this current CI instance. In my dev deploy case,
this prepends: `dking/ci` from which the web browser can
correctly redirect to: `https://internal.hail.is/dking/ci/`.

[ci] Fix external URLs in CI

---

build.yaml
hail/.gitignore
hail/Makefile
hail/python/hail/backend/backend.py
hail/python/hail/context.py
hail/python/setup.py

Move installed location of hail-all-spark.jar to from hail/ to
hail/backend/
We were not finding the jar properly with pkg_resources, and so were not
setting the paths appropriately for pip installs, causing 'JavaPackage
not callable' errors.

[query] fix finding hail jar in pip package

---

hail/python/hail/backend/backend.py
hail/python/hail/methods/impex.py
hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/backend/Backend.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/backend/spark/SparkBlockMatrixCache.scala
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/BlockMatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/ExecuteContext.scala
hail/src/main/scala/is/hail/expr/ir/FoldConstants.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/io/bgen/BgenRDD.scala
hail/src/main/scala/is/hail/io/bgen/BgenRDDPartitions.scala
hail/src/main/scala/is/hail/io/bgen/IndexBgen.scala
hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala
hail/src/main/scala/is/hail/io/fs/FS.scala
hail/src/main/scala/is/hail/io/plink/ExportPlink.scala
hail/src/main/scala/is/hail/linalg/BlockMatrix.scala
hail/src/main/scala/is/hail/stats/LinearMixedModel.scala
hail/src/main/scala/is/hail/utils/Graph.scala
hail/src/main/scala/is/hail/utils/Py4jUtils.scala
hail/src/test/scala/is/hail/HailSuite.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/RandomFunctionsSuite.scala
hail/src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala

- Added index_bgen to Python Backend
- Move most Backend functions to SparkBackend.  Everything about the current code assumes a single user, but the ServiceBackend will have a different, mutli-user interface.
- Added Backend and FS to ExecuteContext.
- renamed Backend clear => stop

[query] more Backend cleanup

---

batch/test/serverthread.py
batch/test/test_batch.py
hail/python/hail/backend/backend.py
hail/python/hail/experimental/db.py
hail/python/hail/utils/tutorial.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

It was previously hard to retry transient errors from synchronous libraries like
requests because `hailtop` lacked a synchronous retry wrapper. This PR
implements such a function and uses it in every place that hail imports
`requests`. I also finally addressed the 1kg download issues.

[batch][hail] pervasively retry transient errors in synchronous code

---

ci/ci/build.py

Databases that are not created fail currently without this change
because they try to connect to a database called None. This
is only visible in PR builds and dev deploys. PR builds do
not test this behavior, so I do not think anyone else
has observed it.

[ci] no clean up for non-created databases

---

hail/python/hail/ir/ir.py
hail/python/test/hail/matrixtable/test_matrix_table.py

Fixes #8316 
I honestly don't know really know how this env/agg_env stuff works, I just know that this makes the tests pass. It's possible that this is an improvement but not a fully correct substitution rule, would appreciate if you could check it / tell me how you figured out what it's supposed to be.

Fix aggregate rows key error

---

hail/python/hail/expr/functions.py
hail/python/test/hail/expr/test_functions.py
hail/src/main/scala/is/hail/stats/package.scala
hail/src/test/scala/is/hail/stats/StatsSuite.scala

Changes:
- correct the interpretation of less and greater.
- improve the formatting and verbiage of the docs,
- expand upon the statistical definition alluded to previously in only the less
case,
- add python tests which would have caught this error,
- add python tests which test against `scipy`,
- deprecate the use of `'two.sided'`, an R-ism, document the preferred use of
`'two-sided'`, a Python-ism, and
- fix an error message in Scala that used yet another naming of the two sided test.

[hail] fix binom_test, improve docs, improve testing

---

ci/ci/github.py

We can have no batch if a batch hasn't been created yet. This state is considered "pending". It is not distinguished from the other "pending" case: having an in-progress batch.

[ci] fix target_url

---

ci/ci/github.py

A merge failure creates a funny batch that doesn't have an id. This handles that properly.

[ci] fix ci bug when a PR hits a merge failure

---

build.yaml

Soon, I will add certificates and keys to the secrets and I want
to add configuration parameters that specify the paths to those
certificates and keys. Therefore, the mount locations of the
secrets must be the same everywhere so the paths are valid.

[build.yaml] standardize on one location for sql-config.cnf

---

hail/python/hail/docs/experimental/index.rst
hail/python/hail/docs/experimental/vcf_combiner.rst
hail/python/hail/experimental/__init__.py
hail/python/hail/experimental/vcf_combiner/__init__.py
hail/python/hail/experimental/vcf_combiner/__main__.py
hail/python/hail/experimental/vcf_combiner/densify.py
hail/python/hail/experimental/vcf_combiner/sparse_mt_utils.py
hail/python/hail/experimental/vcf_combiner/sparse_split_multi.py
hail/python/hail/experimental/vcf_combiner/vcf_combiner.py
hail/python/test/hail/experimental/test_vcf_combiner.py
hail/python/test/hail/methods/test_impex.py

* Made vcf_combiner a module in experimental. Will probably
move this out of experimental in the future.
* Fleshed out docs, and moved associated functions into
the same file.
* Changed run_combiner to require sample_names only if
the header argument is defined. Will change the command-line
script to accept a file with one column of paths, too.
~Stacked on #8396~

[vcf-combiner] Docs update and restructuring.
