src/main/scala/org/broadinstitute/hail/expr/AST.scala

When the user fails to provide a lambda to an aggregation
they now receive a suggestion to use a lambda rather than
a Scala match error.
@tpoterba this should hold us over until we have something nicer like that `projectT` function.
resolves #786

add useful error messages

---

src/main/scala/org/broadinstitute/hail/driver/AnnotateSamplesTable.scala
src/main/scala/org/broadinstitute/hail/driver/ImputeSex.scala
src/main/scala/org/broadinstitute/hail/driver/SampleQC.scala
src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala

resolves #791 
This should cause type errors much sooner if a signature disagrees with the actual types.
Much of the sample annotating code uses multiple inserters and therefore cannot be rewritten to use `annotateSamples`.

add eager annotation type checking

---

src/main/scala/org/apache/spark/sql/SparkExport.scala
src/main/scala/org/broadinstitute/hail/driver/AnnotateGlobalTable.scala
src/main/scala/org/broadinstitute/hail/driver/AnnotateSamplesTable.scala
src/main/scala/org/broadinstitute/hail/driver/AnnotateVariantsLoci.scala
src/main/scala/org/broadinstitute/hail/driver/AnnotateVariantsTable.scala
src/main/scala/org/broadinstitute/hail/driver/ImportAnnotations.scala
src/main/scala/org/broadinstitute/hail/driver/Main.scala
src/main/scala/org/broadinstitute/hail/driver/SplitMulti.scala
src/main/scala/org/broadinstitute/hail/io/vcf/LoadVCF.scala
src/main/scala/org/broadinstitute/hail/sparkextras/OrderedPartitioner.scala
src/main/scala/org/broadinstitute/hail/sparkextras/OrderedRDD.scala
src/main/scala/org/broadinstitute/hail/utils/TextTableReader.scala
src/main/scala/org/broadinstitute/hail/utils/richUtils/RichPairRDD.scala
src/main/scala/org/broadinstitute/hail/utils/richUtils/RichSparkContext.scala
src/test/scala/org/broadinstitute/hail/utils/TextTableSuite.scala

TextTableReader.read takes (optional) nPartitions.
importannotations: new option -n/--npartitions.
Added hintPartition to OrderedRDD coerce and friends.
When loading variant annotations, load with as many partitions as the RDD we're going to join with, and hint with its partitioner.

Optimize import annotations.

---

src/main/scala/org/broadinstitute/hail/driver/ExportVariantsSolr.scala
src/main/scala/org/broadinstitute/hail/driver/SeqrServer.scala
src/main/scala/org/broadinstitute/hail/utils/StringEscapeUtils.scala
src/test/scala/org/broadinstitute/hail/methods/ExprSuite.scala

By default, don't use Solr Trie types.
Escape field names, sample subfields separated by __ after escaping.
Unescape in seqrserver.
seqrserver: added sample_filters.
seqrserver: decode json fields, --json-fields argument.

Improvements to Solr export and seqrserver

---

src/main/scala/org/broadinstitute/hail/driver/ExportGenotypes.scala
src/main/scala/org/broadinstitute/hail/driver/FilterGenotypes.scala

Fixes issue #844 global not accessible from filtergenotypes and exportgenotypes.

Added global context to filtergenotypes and exportgenotypes commands.

---

src/main/scala/org/broadinstitute/hail/expr/AST.scala
src/main/scala/org/broadinstitute/hail/expr/Fun.scala
src/main/scala/org/broadinstitute/hail/expr/FunctionRegistry.scala
src/main/scala/org/broadinstitute/hail/expr/HailRep.scala
src/main/scala/org/broadinstitute/hail/expr/TypeTag.scala
src/test/scala/org/broadinstitute/hail/methods/ExprSuite.scala

Resolves issue #763.
The Function Registry distinguishes between fields and functions because they were distinguished in the existing `AST.scala`. Moreover, for unary functions, there are registration methods for both pure functions and computations in the `Option` monad.
Registration requires only a name and an implementation. Unfortunately, the Scala compiler fails to infer the type parameters from an expression like `_.isHomRef`. 
```scala
registerOptionField("dosage", { (x: Genotype) => x.dosage.map(a => a: IndexedSeq[Double]) })
registerField("isHomRef", { (x: Genotype) => x.isHomRef })
```
```scala
register("Variant", { (x: String) =>
val Array(chr, pos, ref, alts) = x.split(":")
Variant(chr, pos.toInt, ref, alts.split(","))
})
register("Variant", { (x: String, y: Int, z: String, a: …
```

Initial Implementation of a Function Registry

---

docs/HailExpressionLanguage.md

It was not in the documentation that the separator is a regex.

update str.split doc

---

src/main/scala/org/broadinstitute/hail/methods/LinearRegression.scala
src/test/scala/org/broadinstitute/hail/methods/LinearRegressionSuite.scala

in the interest of modularity, the nMissing annotation need not be attached separately by linreg.  I had updated this before in #645 but strangely only the documentation update when through. here are the corresponding code changes.

removed nMissing from linreg output

---

src/main/scala/org/broadinstitute/hail/driver/ImportBGEN.scala
src/main/scala/org/broadinstitute/hail/io/IndexedBinaryBlockReader.scala
src/main/scala/org/broadinstitute/hail/io/IndexedBinaryInputFormat.scala
src/main/scala/org/broadinstitute/hail/io/bgen/BgenBlockReader.scala
src/main/scala/org/broadinstitute/hail/io/bgen/BgenInputFormat.scala
src/main/scala/org/broadinstitute/hail/io/bgen/BgenLoader.scala
src/main/scala/org/broadinstitute/hail/io/plink/PlinkBlockReader.scala
src/main/scala/org/broadinstitute/hail/io/plink/PlinkInputFormat.scala
src/main/scala/org/broadinstitute/hail/io/plink/PlinkLoader.scala

Refactored VariantRecord to RecordDecoder, made genotype decoding
lazy.  This allows us to get out fastKeys and the genotypes with the
same abstraction.
Refactored multiple BGEN file handling to BgenLoader, where it should be.
Added assertions that we silently relied on.

Added fastKeys option to BGEN and PLINK import.

---

docs/GettingStarted.md

I'm not sure whether it's better to splitmulti on import. People will wonder why it's necessary, how it affects count, etc. But at least this will run now!

added splitmulti to getting started command

---

docs/commands/ibd.md
src/main/scala/org/broadinstitute/hail/driver/IBDCommand.scala
src/main/scala/org/broadinstitute/hail/expr/AnnotationImpex.scala
src/main/scala/org/broadinstitute/hail/methods/IBD.scala
src/main/scala/org/broadinstitute/hail/utils/package.scala
src/main/scala/org/broadinstitute/hail/variant/Variant.scala
src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala
src/test/scala/org/broadinstitute/hail/methods/IBDSuite.scala

This PR depends on PR #738. Merge that first.
This adds `--min` and `--max` flags to the `ibd` command. The resulting TSV will only contain sample pairs with `pi_hat` above the minimum and below the maximum, inclusively of both.

Add a threshold flag for IBD output filtering

---

src/main/scala/org/broadinstitute/hail/driver/AnnotateVariantsLoci.scala
src/main/scala/org/broadinstitute/hail/driver/AnnotateVariantsTable.scala
src/main/scala/org/broadinstitute/hail/driver/AnnotateVariantsVCF.scala
src/main/scala/org/broadinstitute/hail/driver/AnnotateVariantsVDS.scala
src/main/scala/org/broadinstitute/hail/driver/Coalesce.scala
src/main/scala/org/broadinstitute/hail/driver/ExportPlink.scala
src/main/scala/org/broadinstitute/hail/driver/SplitMulti.scala
src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala

Only call before perist or (real) shuffle: just in coalesce.
Unpersist plinkRDD in exportplink.

Clean up withGenotypeStream.

---

src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala

Don't construct intermediate string.
Print full exception on metadata load failure.

Metadata loading fix.

---

docs/HailExpressionLanguage.md

pandoc adds id attributes to headers that are equal to the header name

Fix hyperlinks for Info Score

---

src/main/scala/org/broadinstitute/hail/driver/Cache.scala
src/main/scala/org/broadinstitute/hail/driver/Coalesce.scala
src/main/scala/org/broadinstitute/hail/driver/FilterAlleles.scala
src/main/scala/org/broadinstitute/hail/driver/Persist.scala
src/main/scala/org/broadinstitute/hail/sparkextras/OrderedRDD.scala
src/main/scala/org/broadinstitute/hail/utils/package.scala

Don't presist in repartition/coalesce.
Fixed Int overflow bug in OrderedRDD.coalesce.
Convert to GenotypeStream in cache, persist.
Fixed filteralleles annotation bug.

repartition/coalesce improvements + filteralleles bug fix

---

src/main/scala/org/broadinstitute/hail/expr/AST.scala

Provide a hint to the user when a field or
method is not found.

resolves issue #933

---

src/main/scala/org/broadinstitute/hail/driver/ExportGEN.scala
src/main/scala/org/broadinstitute/hail/sparkextras/OrderedRDD.scala
src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala
src/test/scala/org/broadinstitute/hail/variant/vsm/VSMSuite.scala

Fixed bug that cause --no-shuffle mode to do nothing, no matter what.
Fixed bug that caused shuffle mode to shuffle lazily mapped iterators

Fix coalesce/repartition

---

src/main/scala/org/broadinstitute/hail/check/Gen.scala
src/main/scala/org/broadinstitute/hail/sparkextras/ToIndexedRowMatrixFromBlockMatrix.scala
src/test/scala/org/broadinstitute/hail/utils/UtilsSuite.scala

- based on Spark 2.0
- converts directly without passing through CoordinateMatrix
- added test to UtilsSuite

added ToIndexedRowMatrixFromBlockMatrix to sparkextras

---

build.gradle
src/main/scala/org/broadinstitute/hail/asm4s/Code.scala
src/main/scala/org/broadinstitute/hail/asm4s/FunctionBuilder.scala
src/main/scala/org/broadinstitute/hail/asm4s/package.scala
src/test/scala/org/broadinstitute/hail/asm4s/A.java
src/test/scala/org/broadinstitute/hail/asm4s/ASM4SSuite.scala

@danking, I started playing with your ASM experiment and wrote a library for lightweight bytecode generation.
The primary abstractions are `FunctionBuilder` and `Code[T]`.  The latter is an object that can generate bytecode to produce a value of type `T` on the top of the stack.
I'm reasonably happy with the interface, see this example for factorial:
https://github.com/cseed/hail/commit/93d95982bccd16ffa531f67fa47163f3fc8cbdde#diff-e434fa9004c38142a8f6f64ffa73b48eR109
No ClassBuilder yet.  Apart from that, all the major features are there.  There are a bunch of missing operations (type conversions, for example) and I only have wrapper classes for `Int` and `Double`.  Once we fill it out I think it will make an excellent stand-alone library.
While I optimized conditional generation to be …

Added asm4s lightweight bytecode generation

---

docs/faq/Annotations.md
docs/javascript/buildDocs.js
docs/javascript/compileDocsNode.js
www/style.css

@danking: I can't figure out why all of the edit links are clickable except for the Annotations and Exporting Data ones. They're auto-generated with the same code.

resolves #836 -- add edit links to FAQ

---

src/main/scala/org/broadinstitute/hail/driver/SampleQC.scala
src/main/scala/org/broadinstitute/hail/variant/Genotype.scala
src/test/scala/org/broadinstitute/hail/methods/FilterSuite.scala

Note that there are a few additional changes in the way counts are computed:
- Each allele counts towards its respective count, so a homozygous transition counts as 2 transitions
- Singletons are restricted to a single individual carrying a single allele (so a homVar genotype in a single sample is not considered a singleton any more).

Added support for multi-allelic sites to sampleqc

---

src/main/scala/org/broadinstitute/hail/stats/BaldingNicholsModel.scala

Don't create math3 objects (relocated) that are passed to breeze
(non-relocated).  Just use Scala Random.

Fix method not found error due to relocation.

---

build.gradle

Rely on versions of math3 and lang3 pulled in by other dependencies,
e.g., Spark.

Don't relocate math3.

---

src/main/scala/org/broadinstitute/hail/variant/Locus.scala

This allows Spark 2 Hail to load partitioning information from VDSes
written by the Spark 1 version, but loading partitioning from previous
Spark 2 versions will now fail.  Since there are far more VDSes in
uses written with Spark 1 in use, this seems like a good trade-off.
There are now to serial version UIDs in the wild for Locus.  I don't
see how to write code to load both of them (except maybe
loading/unloading different versions of the Locus class which seems
painful.)  I would prefer a tool that converts the partitioning to
JSON instead (once support for JSON is ready).
The partitioning information should be stored as JSON instead of Java
serialization, which is not a good long-term storage format.

Set Locus serial version UID.

---

src/main/scala/org/broadinstitute/hail/driver/package.scala
src/main/scala/org/broadinstitute/hail/sparkextras/OrderedPartitioner.scala
src/main/scala/org/broadinstitute/hail/utils/JSON.scala
src/main/scala/org/broadinstitute/hail/utils/package.scala
src/main/scala/org/broadinstitute/hail/utils/richUtils/Implicits.scala
src/main/scala/org/broadinstitute/hail/utils/richUtils/JSONWritable.scala
src/main/scala/org/broadinstitute/hail/utils/richUtils/RichJValue.scala
src/main/scala/org/broadinstitute/hail/variant/Locus.scala
src/main/scala/org/broadinstitute/hail/variant/Variant.scala
src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala
src/test/scala/org/broadinstitute/hail/utils/OrderedRDDSuite.scala

Allow -b 0.
Added typeclasses for converting to/from JSON.
Implemented for OrderedPartitioner and Locus.
Use in VSM.{read, write}.
Remove OrderedPartitioner.ascending.  It wasn't properly implemented.
Still try to load serialized .vds/partitioner if partitioner.json.gz
isn't there.

End the serialiation madness.

---

src/main/scala/org/broadinstitute/hail/expr/AST.scala
src/main/scala/org/broadinstitute/hail/expr/FunctionRegistry.scala

They don't work.  TT.t gets overwritten when matching other functions.

Back json and str out of FunctionRegistry.

---

python/pyhail/docs/_static/custom.css
python/pyhail/docs/conf.py
python/pyhail/docs/index.rst
www/style.css

- Fixed blockquote formatting
- Fixed code blocks filling page
- Added highlighting of class and method names. To fix colors, change css here: `python/pyhail/docs/_static/custom.css`

Sphinx CSS fixes

---

python/pyhail/dataset.py
python/pyhail/keytable.py
python/pyhail/tests.py
src/main/scala/org/broadinstitute/hail/annotations/Annotation.scala
src/main/scala/org/broadinstitute/hail/driver/package.scala
src/main/scala/org/broadinstitute/hail/expr/AnnotationImpex.scala
src/main/scala/org/broadinstitute/hail/keytable/KeyTable.scala
src/main/scala/org/broadinstitute/hail/variant/Genotype.scala
src/main/scala/org/broadinstitute/hail/variant/Locus.scala
src/main/scala/org/broadinstitute/hail/variant/Variant.scala
src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala
src/test/scala/org/broadinstitute/hail/methods/KeyTableSuite.scala

Replaced VariantDataset ..._to_pandas with ..._keytable.
Added expand_types and flatten to KeyTable.  These probably need to be more configurable but are a start.
Added KeyTable.toDF.  This allows KeyTables to be easily written to Parquet.

KeyTable improvements.

---

src/main/scala/org/broadinstitute/hail/driver/ExportVariantsCass.scala

This is so it matches the column name computed from the -v expression.

escape 'dataset_id' column name

---

src/main/scala/org/broadinstitute/hail/variant/VariantSampleMatrix.scala

This avoids serializing to a String before writing, which
likely doubles the memory requirements.

write directly to the file

---

docs/reference/HailExpressionLanguage.md
src/main/scala/org/broadinstitute/hail/expr/FunctionRegistry.scala
src/test/scala/org/broadinstitute/hail/methods/AggregatorSuite.scala

Expressions such as
```
samples.flatMap(g => [1,2]).sum()
```
are now valid Hail expressions.
Should merge cleanly after #1220

Add `flatMap` for aggregables

---

src/main/scala/org/broadinstitute/hail/methods/Aggregators.scala

Convert three foreach calls to while loops.
I see about a 15% reduction in variant aggregation time. I executed
```
hail read profile225.vds \
annotatevariants expr -c 'va.foo = gs.map(g => 1).sum()' \
exportvariants -c 'va.foo' -o 'foo.tsv'
```
Here are the comparisons between this PR, master, and some part-solutions that I tried. We always compare to this PR. In each case, the first row of numbers is the same row of timings for this PR. The second row of numbers is the timings for the alternative. Note that converting the outer loop and the last loop, but not the inner loop, seems to be slower than master. I suspect these measurements are fairly noisy, but perhaps there's something else going on in that case. Regardless, this PR is the clear winner and we know why: `while` loops are …

improve aggregator performance

---

python/pyhail/docs/getting_started.rst

The ~'s in file paths in the getting started section of the tutorial were not being expanded, creating an unwanted ~ folder in the working directory as a result of line 52. With this change the sample.vds file and and all other files being created just get created in working directory.

Removed ~/ from several paths

---

python/pyhail/docs/getting_started.rst
src/main/c/Makefile

Use curl instead of wget.  wget is not installed by default on OSX.

Added native dependencies to getting started.

---

build.gradle
src/main/scala/org/broadinstitute/hail/utils/package.scala
src/main/scala/org/broadinstitute/hail/utils/richUtils/RichSQLContext.scala

In Spark 2.1, write.parquet writes part-NNNNN instead of part-r-NNNN
files.

Get working with Spark 2.1.

---

src/main/scala/is/hail/expr/AnnotationImpex.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala

Fix empty struct write error.

---

docs/reference/HailExpressionLanguage.md
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/test/scala/is/hail/methods/ExprSuite.scala

fixed numeric aggregations behavior on empty arrays and sets
- modified min, max, mean, and median functions in FunctionRegistry
- added regression tests for empty sets and empty arrays to ExprSuite
- updated and refactored ExpressionLanguage docs to reflect changes

Fixed min, max, mean, median on empty sets and arrays

---

src/main/scala/is/hail/variant/Genotype.scala

This was identified as a cost center during my compiler investigations. The effect is not measurable on the standard benchmark [1]. More investigation is needed. As we improve the performance of the expression language, I suspect this will constitute a more significant fraction of execution time.
[1]:
```
filtergenotypes -c ' g.dp > 400 ||
(g.isHomRef && (g.ad[0] / g.dp < 0.9 || g.gq < 20)) ||
(g.isHomVar && (g.ad[1] / g.dp < 0.9 || g.pl[0] < 20)) ||
(g.isHet && ( (g.ad[0] + g.ad[1]) / g.dp < 0.9 || g.ad[1] / g.dp < 0.20 || g.pl[0] < 20 ))' --keep
```

speed up genotype parsing

---

python/hail/dataset.py

This prevents an error in _run_command where we attempt to put an int into an array of `java.lang.String`s

Send correct types to Java in vep

---

src/main/scala/is/hail/variant/package.scala

Our convention has been to reserve it for iterators, so I've changed `git` and `it` in #1325 (of type Iterable[Genotype]) to `ig`.

improve variable names in VariantPackage object

---

src/main/c/test.cpp

`inttypes.h` is definitely needed for standards compliant usage of
printf format strings. The latter is safe, but should not be necessary
on recent C++ compilers with recent stdlibs.
Compiling with a C++ compiler and a somewhat old version of glibc will
not provide PRIu64 and friends unless this macro is defined before
including `inttypes.h`. For more details see [1] with associated comments
and the related bug fix [2] which landed in glibc 2.18.
[1] http://stackoverflow.com/questions/8132399/how-to-printf-uint64-t
[2] https://sourceware.org/bugzilla/show_bug.cgi?id=15366

fix: include inttypes.h and __STDC_FORMAT_MACROS

---

python/hail/docs/getting_started.rst

Based on https://clang.llvm.org/cxx_status.html and https://gcc.gnu.org/gcc-4.7/cxx0x_status.html Clang 3.3 and GCC 4.7 should be sufficient to prevent compile errors arising from not supporting C++11 features.
FYI @cseed @tpoterba

specify desired C++ compatibility

---

python/hail/dataset.py

I added an annotations table for sample_qc, added two missing entries from the variant_qc table, and fixed various formatting issues and warnings that building docs was emitting.

Documentation additions (sample_qc, plus miscellaneous)

---

python/hail/dataset.py

I removed a reference to print_schema from the docs in the vep function, and I also fixed the table I inadvertently broke in last commit in lmmreg function (sorry about that)

Fixed print_schema references, fixed tables I broke

---

src/main/scala/is/hail/stats/BaldingNicholsModel.scala

Had to cast toLong to avoid overflow on multiplication, cast back to Int because number of partitions must be an integer.

Added a cast toLong before doing multiplication to avoid overflow

---

src/main/scala/is/hail/utils/TempDir.scala
src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala

If you follow the call path of a `org.apache.hadoop.fs.LocalFileSystem.mkdirs`,
you'll find that it's actually implemented on
`org.apache.hadoop.fs.FilterFileSystem` which implements it in terms of some
internal `fs` variable, which in `LocalFileSystem`'s case is
`org.apache.hadoop.fs.RawLocalFileSystem`. This class has `mkOneDirWithMode`,
which delegates to `java.io.File`. Now we're at ground truth. This is a well
documented Java API. It returns true if the directory was created, false
otherwise. No `IOException`s. Going back up through the callstack, we find that
`IOException`s are thrown for a variety of unusual circumstances (like if
you're creating `/foo/bar/baz` and `/foo/bar` is a file that isn't a
directory), but, ultimately, if the directory *already exists* `mkdirs`
returns …

Fix PipelineSuite file io race

---

src/main/scala/is/hail/driver/AnnotateSamplesTable.scala

This was an issue for Sali. I think the computational cost is small enough that it is worth warning; but I could be convinced otherwise.
cc @cseed @tpoterba

warn about sample mismatch in annotate_samples_table

---

src/main/scala/is/hail/utils/TempDir.scala

I was wrong about the return value of `RichHadoopConfiguration.mkdir`. This is better than nothing, but still susceptible to races :(

assert directory does not exist

---

src/main/scala/is/hail/utils/TempDir.scala

I hope this is the last one.
Instead of assert (since the catch doesn't catch assertion errors), I just use an `if`.

AssertionErrors are not caught

---

python/hail/dataset.py
src/main/scala/is/hail/methods/LogisticRegression.scala
src/main/scala/is/hail/stats/LogisticRegressionModel.scala
src/main/scala/is/hail/stats/eigSymD.scala
src/test/resources/regressionLogistic.R
src/test/scala/is/hail/methods/LogisticRegressionSuite.scala
src/test/scala/is/hail/stats/LogisticRegressionModelSuite.scala
src/test/scala/is/hail/stats/eigSymDSuite.scala

- removed nullFit function entirely, simplifying code
- null model variables are first rather than last, simplifying code
- logreg fit now only computes margins of score and firth on first iteration
- score and fisher are Options in LogisticRegressionFit (not computed by Firth)
- added Firth test to logreg
- added R test of Firth test
- added Firth to EPACTS test
- added Firth to logreg documentation
- added TriSolve for solving triangular systems (LAPACK dtrtrs), used in fitFirth
- added TriSolve test

Improved logreg code, added Firth

---

python/hail/dataset.py

Just converted concordance markdown to restructuredText. Didn't spend much time on examples, since Tim seems to be in process of changing this function a bit anyway.

Adding Concordance Docs to Python

---

src/test/scala/is/hail/methods/LinearMixedRegressionSuite.scala

`delta` is a randomly chosen double, we shouldn't assert its equivalence with a specific value.

remove numeric tests in favor of expected equivalence

---

python/hail/keytable.py
src/main/scala/is/hail/keytable/KeyTable.scala
src/main/scala/is/hail/methods/IBD.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/methods/KeyTableSuite.scala
src/test/scala/is/hail/variant/vsm/VSMSuite.scala
src/test/scala/is/hail/vds/AggregateByKeySuite.scala

- Switched rdd from `RDD[(Annotation, Annotation)]` to rdd `RDD[Annotation]` with a `signature` and `keyNames: Array[String]` rather than `keySignature` and `valueSignature`.
- Changed join behavior to not join based on key name, but join on the order and number of the types matching.

Change KeyTable internals

---

python/hail/keytable.py

It's unclear to me what the right way to link to expression language page is, and the examples of that I found in the actual docs were just links to actual Hail website as it is here.

Fixed two links to old docs. 

---

build.gradle
python/hail/context.py
python/hail/dataset.py
python/hail/keytable.py
python/hail/tests.py
src/main/scala/is/hail/keytable/KeyTable.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/methods/RenameSamplesSuite.scala

Added KeyTable.collect()
Default key_names to [].

rename_samples now takes a dict instead of a file.

---

python/hail/context.py
python/hail/tests.py
src/main/scala/is/hail/HailContext.scala

Example:
```
In[9]: hc.eval_expr_typed('[1, 2, 3].map(x => x * 2)')
Out[9]: ([2, 4, 6], Array[Int])
```

Add HailContext.eval_expr{_typed}.

---

src/main/scala/is/hail/stats/RegressionUtils.scala

Now the command:
```
pca_vds.logreg('wald', 'sa.isCase', ['sa.scores.PC1, sa.scores.PC2']).count()
```
gives the right error
```
FatalError                                Traceback (most recent call last)
<ipython-input-28-2fb5c41b2314> in <module>()
----> 1 pca_vds.logreg('wald', 'sa.isCase', ['sa.scores.PC1, sa.scores.PC2']).count()
<decorator-gen-218> in logreg(self, test, y, covariates, root)
/Users/jbloom/hail/python/hail/java.pyc in handle_py4j(func, *args, **kwargs)
105     except Py4JJavaError as e:
106         msg = env.jutils.getMinimalMessage(e.java_exception)
--> 107         raise FatalError(msg)
108     except Py4JError as e:
109         env.jutils.log().error('hail: caught python exception: ' + str(e))
FatalError: `|' expected but `,' found
<input>:1:sa.scores.PC1, …
```

better parsing of covariate list

---

src/main/scala/is/hail/expr/Type.scala
src/main/scala/is/hail/io/vcf/ExportVCF.scala
src/main/scala/is/hail/io/vcf/HtsjdkRecordReader.scala
src/main/scala/is/hail/io/vcf/LoadVCF.scala
src/test/scala/is/hail/annotations/AnnotationsSuite.scala
src/test/scala/is/hail/methods/FilterSuite.scala
src/test/scala/is/hail/methods/ProgrammaticAnnotationsSuite.scala

- Values of types other than `Array` and `Boolean` get output in VCF format (e.g. `.` instead of `NA` for missing values)
- `NaN` values are converted to missing (`.`) when exporting VCF since VCF doesn't handle `NaN`
- Changes to handling of filters:
- `.` <=> `NA:Set[String]`
- `PASS` <=> `{}:Set[String]`
- `other` <=> `{"other"}:Set[String]"`
- Removed `va.pass` entirely (redundant with `va.filters` and needs constant synchronization)

Improvements to VCF impex

---

src/main/c/ibs.cpp

On my macbook pro, with -march=native, this emits the popcnt
intrinsic, so I do not expect any slowdown on architectures that
support the popcnt flag.
resolves #1520

use stdlib popcnt instead of intrinsic

---

src/main/scala/is/hail/utils/IntervalTree.scala

Resolves error where exportVariants exported an Interval as `Interval(14:968765858,22:1565768082)` and import parser expects `14:968765858-22:1565768082`

fixed interval type export to match import parser

---

python/hail/tests.py
src/main/scala/is/hail/methods/LinearMixedRegression.scala
src/main/scala/is/hail/utils/richUtils/RichIterable.scala
src/test/scala/is/hail/methods/LinearMixedRegressionSuite.scala

Now the lmmreg python test is deterministic. And I found another bug in lmmreg by implementing the same test in LinearMixedRegressionSuite, which I then fixed, namely, kinshipVds should have been filtKinshipVds. Upon rebasing, that test failed again due to interaction of IntIterator and lazyFilterWith, which I've also fixed.  I've added a regression test to LinearMixedRegressionSuite, paralleling the Python test, that catches both bugs.

made lmm python test deterministic, fixed bug in lmmreg and lazyFilterWith

---

src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala

It's safe here since we're within bounds and don't use negative indexing.
```
def unsafeValueAt(row: Int, col: Int): V = data(linearIndex(row, col))
```

switched to unsafeValueAt in RichDenseMatrixDouble

---

src/main/scala/is/hail/methods/IBD.scala
src/main/scala/is/hail/variant/VariantDataset.scala

I realized that not all the optional IBDPrune parameters were getting passed along, so some were being ignored. This is no longer the case with this change.

Fixed IBDPrune so optional parameters actually get used

---

python/hail/dataset.py

Fixed code-block in annotate-globals-list

---

python/hail/dataset.py
python/hail/type.py
src/main/scala/is/hail/expr/Type.scala
src/main/scala/is/hail/methods/VEP.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/annotations/AnnotationsSuite.scala

The functions expose Field attributes (useful for VCF header)
- Annotations generated using annotate_alleles_expr now have 'Number=A'
- VEP now parses the Description when using csq=True option (required to know the fields stored in the  |-delimited field)

Added get_va_attributse, set_va_attributes and delete_va_attribute

---

python/hail/docs/scripts/setupTutorial.sh

I think this preserves the old semantics, except that now it works when `curl` exists too and it errs when neither exists.

add curl as an alternative to wget

---

build.gradle
python/hail/docs/getting_started.rst

This change fixes a bug in the Python code for HailContext that I found when trying to get Hail to run in interactive mode on a CDH cluster. (Inspired by https://docs.databricks.com/spark/latest/training/1000-genomes.html.)
I also added a build task to generate a zipfile of the Python code.

Fix interactive python shell and document running on CDH cluster

---

src/main/scala/is/hail/utils/richUtils/RichIndexedRowMatrix.scala

Accidentally set things up so that there would only be one block per partition. That should not be the case.

Fixed use of grid partitioner

---

src/main/scala/is/hail/utils/FunctionDocumentation.scala

- Example of fix is for `index` in doc page for functions
- Issue caused by changing the `.toString` behavior for Structs to print "Empty" if the Struct is empty.

Fixed Empty return type for Struct in docs

---

src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/expr/Type.scala
src/test/scala/is/hail/methods/ExprSuite.scala

Assigning Dan because it involves a somewhat weird expr motif -- putting in a special comparison for typecheck, but using the function registry for the eval/compile

Fixed == to require same-type arguments

---

python/hail/dataset.py
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/methods/FilterAlleles.scala
src/main/scala/is/hail/methods/SplitMulti.scala
src/main/scala/is/hail/variant/Variant.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/io/SplitSuite.scala
src/test/scala/is/hail/vds/FilterAllelesSuite.scala
src/test/scala/is/hail/vds/MinRepSuite.scala

* CamelCased minRep (was inconsistent globally and more importantly camelcased in python interface!)
* Added `isStar` to `AltAllele` and made sure that `*` alleles aren't counted as `SNP`s anymore
* Modified minRep to ignore `*` alleles and correctly minrep in their presence
* FilterAlleles now filters sites where only a `*` allele is left by default (keepStar option allows overriding this behavior)

MinRep fix and better Star allele support

---

src/main/scala/is/hail/methods/KinshipMatrix.scala
src/test/scala/is/hail/methods/KinshipMatrixSuite.scala

To be clear, the bug was that if the rdd of IndexedRows backing the IndexedRowMatrix omitted some rows (as a way of indicating that they contained only 0's), that omitted row would not get written to TSV file. This has been corrected, and a test was created for it by making the test data in the Suite more interesting and adding an assertion.

Fixed bug where rows not explcitily in RDD would not be included

---

python/hail/dataset.py
python/hail/kinshipMatrix.py
python/hail/tests.py
src/main/scala/is/hail/methods/GRM.scala
src/main/scala/is/hail/methods/KinshipMatrix.scala
src/main/scala/is/hail/stats/ComputeRRM.scala
src/main/scala/is/hail/utils/richUtils/Implicits.scala
src/main/scala/is/hail/utils/richUtils/RichIndexedRowMatrix.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/test/scala/is/hail/methods/KinshipMatrixSuite.scala
src/test/scala/is/hail/utils/RichIndexedRowMatrixSuite.scala
src/test/scala/is/hail/vds/BiallelicMethodsSuite.scala
src/test/scala/is/hail/vds/GRMSuite.scala

-Changed the "grm()" method to return instances of KinshipMatrix. 
-Added various export to file methods that were supported by GRM to the KinshipMatrix.
-Modified GRM tests appropriately. 
-Add RichIndexedRowMatrix implicit to the hail utils implicit file.

Grm to kinship matrix

---

python/hail/dataset.py
src/main/scala/is/hail/methods/VEP.scala

Also, added hail.vep.extra_plugins for specifying additional plugins beyond the default ones (such as LoF_splice.pm for predicting variants' probability of splice junction disruption or creation)

hail.vep.assembly setting to allow assemblies other than GRCh37

---

src/main/scala/is/hail/annotations/Annotation.scala
src/main/scala/is/hail/expr/AnnotationImpex.scala
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/expr/HailRep.scala
src/main/scala/is/hail/expr/Parser.scala
src/main/scala/is/hail/expr/Type.scala
src/main/scala/is/hail/io/CassandraConnector.scala
src/main/scala/is/hail/io/vcf/ExportVCF.scala
src/main/scala/is/hail/io/vcf/HtsjdkRecordReader.scala
src/main/scala/is/hail/io/vcf/LoadVCF.scala
src/test/scala/is/hail/vds/FilterAllelesSuite.scala

Data formats that use Characters (including old VDSes) will now be loaded as `TString`s.
Resolves #1710

remove TChar

---

build.gradle
src/main/scala/is/hail/methods/Aggregators.scala
src/test/scala/is/hail/methods/AggregatorSuite.scala

- In the `combOp`, the `TakeByAggregator` was calling the `seqOp` which recomputes the sort-key. Since the evaluation context was not set correctly for the keys, the expression that evaluates the sort-key obviously produced the wrong value for the given key.
- `TakeByAggregator.result` used `PriorityQueue.toArray`, which is not guaranteed to produce the elements in sorted order, according to [the PriorityQueue docs](http://www.scala-lang.org/api/current/scala/collection/mutable/PriorityQueue.html). Instead, we must `clone` the `PriorityQueue` and then `dequeueAll` the elements. I'm not certain the `clone` is necessary. @cseed, does the Aggregator interface permit multiple calls to `result`?
> Only the dequeue and dequeueAll methods will return elements in priority order (while removing …

Fix: TakeBy Merge Bug, TakeBy Result Not Ordered

---

src/main/scala/is/hail/variant/VariantDataset.scala

ld_prune in Python has signature
`ld_prune(self, r2=0.2, window=1000000, memory_per_core=256, num_cores=1)`
Add same defaults to Scala ldPrune method.

Add defaults to ldPrune to match Python API

---

python/hail/dataset.py
src/main/scala/is/hail/variant/VariantDataset.scala

I hadn't noticed that the memory_per_core argument in Python uses different units.

Fix memoryPerCore arg in ldPrune

---

src/test/scala/is/hail/methods/LinearMixedRegressionSuite.scala

These values are computed whenever an object of this class is allocated. This happens even when `gradle test --tests 'FOO'` filters out the class. I would prefer filtered tests to not run anything so that the desired tests run as quickly as possible.

Prevent LinearMixedRegressionSuite From Computing On Creation

---

python/hail/dataset.py
python/hail/tests.py
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/methods/AnnotateGlobalSuite.scala
src/test/scala/is/hail/methods/AnnotateSuite.scala
src/test/scala/is/hail/variant/IntervalSuite.scala
src/test/scala/is/hail/vds/AnnotateSamplesSuite.scala

- aggregate intervals (easy to implement with key tables)
- annotate samples list (easy to implement with annotate_samples_table)
- annotate global list and annotate global table (easy to implement with key table and annotate_global (renamed from annotate_global_py)
Also cleaned up VSM interface (removed annotateSamplesList)

Removed unnecessary methods (last VDS methods that take files)

---

python/hail/context.py
src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/expr/Parser.scala
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/io/bgen/BgenLoader.scala
src/main/scala/is/hail/io/plink/PlinkLoader.scala
src/main/scala/is/hail/io/vcf/LoadVCF.scala
src/main/scala/is/hail/methods/Aggregators.scala
src/main/scala/is/hail/stats/BaldingNicholsModel.scala
src/main/scala/is/hail/stats/package.scala
src/main/scala/is/hail/variant/GenericDataset.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/main/scala/is/hail/variant/VariantMetadata.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/PipelineSuite.scala
src/test/scala/is/hail/annotations/AnnotationsSuite.scala
src/test/scala/is/hail/methods/FilterSuite.scala
src/test/scala/is/hail/utils/TestRDDBuilder.scala
src/test/scala/is/hail/variant/GenericDatasetSuite.scala
src/test/scala/is/hail/variant/IntervalSuite.scala
src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala
src/test/scala/is/hail/variant/vsm/VSMSuite.scala
src/test/scala/is/hail/vds/FilterAllelesSuite.scala
src/test/scala/is/hail/vds/JoinSuite.scala

Mostly infrastructure.
Added NewAST base class for Matrix and KeyTable ASTs with a primitive term rewriting engine.  This should eventually be a base for AST, too (because we'll want to rewrite value expressions, too).
I broke VariantMetadata into two parts: VSMMetadata (static types/metdata for VSM) and VSMLocalValue (part of MatrixValue that is computed/stored on master and broadcast).
Added MatrixRead, FilterSamples and FilterVariants matrix AST nodes.  Simple optimizer that pushes filters into read and some minor optimizations of filters.

infrastructure for query optimizer

---

src/main/scala/is/hail/sparkextras/OrderedRDD.scala

Just because an RDD is OrderedPartitioner partitioned doesn't mean it
is an OrderedRDD (might not be sorted within partitions).  Users who
want this behavior should call OrderedRDD.apply to assert it is an
OrderedRDD.

Fix potential bug in OrderedRDD.

---

python/hail/representation/variant.py
src/main/scala/is/hail/expr/FunctionRegistry.scala

Hi hail team, what do you think about supporting `alt_allele_type` through the python API?
This came about because I'd like to be able to export the alt allele type per variant using [export_variants](https://hail.is/hail/hail.VariantDataset.html#hail.VariantDataset.export_variants)

add a method to return the type of alt allele

---

python/hail/docs/_ext/hail_doctest.py

This produces a python script `_build/doctest/test_hail_docs.py` with all of the code tested by the Sphinx doctest module.

Emit python code run in doctests as script

---

src/main/scala/is/hail/sparkextras/OrderedRDD.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala

asOrderedRDD preserves the the same partitioner.  In this case,
joinedRDD is Locus-partitioned, but we want the result to be
Variant-partitioned.
@tpoterba Is it possible this will fix @konradjk's cast exception?

Fix incorrect partitioner.

---

python/hail/dataset.py
src/main/scala/is/hail/methods/LinearMixedRegression.scala
src/main/scala/is/hail/methods/LinearRegression.scala
src/main/scala/is/hail/methods/LinearRegressionBurden.scala
src/main/scala/is/hail/methods/LinearRegressionMultiPheno.scala
src/main/scala/is/hail/methods/LogisticRegression.scala
src/main/scala/is/hail/methods/LogisticRegressionBurden.scala
src/main/scala/is/hail/stats/ComputeRRM.scala
src/main/scala/is/hail/stats/LinearRegressionModel.scala
src/main/scala/is/hail/stats/RegressionUtils.scala
src/test/scala/is/hail/methods/LDPruneSuite.scala
src/test/scala/is/hail/methods/LinearRegressionBurdenSuite.scala
src/test/scala/is/hail/methods/LinearRegressionMultiPhenoSuite.scala
src/test/scala/is/hail/methods/LinearRegressionSuite.scala
src/test/scala/is/hail/stats/ComputeRRMSuite.scala

- removed repeated imports in dataset
- fixed typos and clarified docs
- collapsed RegUtils to provide one ingest function each for hardCalls, dosages, and keyedRows. These optionally impute missing and produce sparse, dense, and dense vectors respectively. The first two also optionally take a mask. hardCalls no longer checks for constant vectors.
- killed the two RegUtils mutate matrix functions entirely
- simplified code in regression methods taking Vector[Double] input
- temp added constantHardCalls to RegUtils and in regressions to retrofit changes to preserve 0.1 behavior of missing for constant vectors. In 0.2 constant vectors will be treated the same as others, resulting in lack of convergence, Double.NaN, etc.
- temp added hardCallsAndAC to RegUtils and in linreg to retrofit …

Simplifed RegUtils and retrofit to 0.1

---

src/main/scala/is/hail/asm4s/package.scala

This also makes the `defineClass` exception the one that is thrown up.

simplify error handling logic

---

python/hail/docs/tutorial.ipynb

Markdown supports links to be formatted as literals, but Restructured Text does not. https://stackoverflow.com/questions/4743845/format-text-in-a-link-in-restructuredtext

fix tutorial formatting for website

---

python/hail/kinshipMatrix.py
python/hail/ldMatrix.py

Moved pyspark imports to be local to methods, removing numpy dependency

Moved pyspark imports to be local to matrices

---

src/main/scala/is/hail/io/bgen/BgenLoader.scala
src/main/scala/is/hail/methods/Aggregators.scala

Added while loop and replaced a vector to speed up queryGenotypes call rate by about 3x running off a BGEN

Made BGEN query_genotypes 3x faster

---

python/hail/dataset.py

The docstring for `VariantDataset.vep` was stale. [The code ](https://github.com/hail-is/hail/blob/master/src/main/scala/is/hail/methods/VEP.scala#L267) actually allows more flexibility in choosing the assembly (i.e., GRCh38) for vep annotation, but it wasn't being reflected in the API docs.

Update docstring for VariantDataset.vep

---

src/main/scala/is/hail/asm4s/Code.scala
src/main/scala/is/hail/asm4s/package.scala
src/main/scala/is/hail/check/Arbitrary.scala
src/main/scala/is/hail/check/Gen.scala
src/test/scala/is/hail/asm4s/ASM4SSuite.scala
src/test/scala/is/hail/methods/ExprSuite.scala

Addresses #1943 
[JVM Spec, Chapter 6](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-6.html) states, regarding, DCMPG and DCMPL:
> NaN is unordered, so any double comparison fails if either or both of its operands are NaN. With both dcmpg and dcmpl available, any double comparison may be compiled to push the same result onto the operand stack whether the comparison fails on non-NaN values or fails because it encountered a NaN. For more information, see [§3.5](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-3.html#jvms-3.5).
The `G` and `L` suffices refer to whether the presence of one or more `NaN`s should be indicated by returning "greater than" or "less than". Ergo, when we're checking `x > y` we use `DCMPL` so the NaN case produces `-1` with which the downstream …

NaN always compares false in ASM4S

---

python/hail/dataset.py

Minor doc fix. There were two "examples" sections in the make_table docs.

Fixed make_table docs. 

---

src/main/scala/is/hail/utils/richUtils/RichIndexedRowMatrix.scala

toBlockMatrixDense method did not specify size of matrix in constructor, meaning that querying its size later performed an RDD action.

Specify Size in toBlockMatrixDense (1 line fix)

---

src/main/scala/is/hail/methods/GRM.scala
src/main/scala/is/hail/stats/ComputeRRM.scala

Replacing multiplies in master after having done so in 0.1
(cherry picked from commit 4238176833ab35f11f454f87f960d270d737d3b8)

Replaced Spark multiply with Dan multiply in GRM and RRM [master]

---

src/main/scala/is/hail/methods/LDMatrix.scala

I don't know what I was doing when I first wrote this. I guess I thought I had to use the `toNormalizedIndexedRowMatrix` method and worked to accommodate that? Anyway, this had too many calls to `collect()` in it and was more complicated than it needed to be. 
I also replaced the default Spark multiply operation with Dan's matrix multiply, which is a massive improvement. 
Addresses #2009

Clean up / increase efficiency of LD Matrix method

---

src/main/scala/is/hail/expr/Type.scala

This PR extends #1902, merge that one first.
Now, 50% of the time a type is a Scalar type rather than a recursive one. Additionally, this PR adds a generator for pairs of types and values of that type.
Here's a few samples:
```scala
t Struct{
W: Call,
GL: Genotype,
nsfJ: Long,
tiX0pLA: Int,
B7vWAW: Call,
a6_mm: Boolean,
AGS1Eh: Interval,
tqbHQbDv: Dict[AltAllele, Long],
HUh: Set[Double],
Xgb26Wlws: Double,
qe_XlLJt7_X: Dict[Double, Int],
U: Array[Call],
j: Double
}
v [ 1
, 5/6:.:.:.:GP=0.0,0.0,6.103515625E-4,0.0,0.0,0.0,0.0,0.00286865234375,0.0,0.058441162109375,0.0,0.0,0.0,0.00567626953125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.004730224609375,0.153839111328125,0.0,0.0,0.0,0.704742431640625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.018402099609375,0.050689697265625,0.0,0.0,0.0,0.0,0.0,0.0,37690292 …
```

Improve Random Generation: Avoid Excessive Collection Nesting

---

src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala

The [constructor of `ObjectInputStream`](https://docs.oracle.com/javase/8/docs/api/java/io/ObjectInputStream.html#ObjectInputStream-java.io.InputStream-) can, sadly, throw an exception and we must therefore have two finally blocks. One in the case of an exception during reading, and one in the case that the constructor itself throws an exception. Luckily `InputStream`'s `close` method is an implementation of `Closeable.close`, ergo it may be called twice with no effect.

fix latent bug in readObjectFile

---

python/hail/context.py
python/hail/java.py
src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/sparkextras/OrderedRDD.scala
src/main/scala/is/hail/utils/ErrorHandling.scala
src/main/scala/is/hail/utils/LoggerOutputStream.scala
src/main/scala/is/hail/utils/Logging.scala
src/main/scala/is/hail/utils/Py4jUtils.scala
src/main/scala/is/hail/utils/StringSocketAppender.scala
src/main/scala/is/hail/utils/package.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/SparkSuite.scala

- Removed SLF4J, everything goes directly through log4j now.
- Removed the explicitly System.err.write calls inside info / warn.
- Separated console logging and log file logging
- Stripped the huge stack traces out of python errors; they are logged
to the screen / cell through log4j.

Reworked logging to route log output through Python stderr

---

python/hail/context.py
python/hail/java.py
src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/sparkextras/OrderedRDD.scala
src/main/scala/is/hail/utils/ErrorHandling.scala
src/main/scala/is/hail/utils/LoggerOutputStream.scala
src/main/scala/is/hail/utils/Logging.scala
src/main/scala/is/hail/utils/Py4jUtils.scala
src/main/scala/is/hail/utils/StringSocketAppender.scala
src/main/scala/is/hail/utils/package.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/SparkSuite.scala

* Reworked logging to route log output through Python stderr.
- Removed SLF4J, everything goes directly through log4j now.
- Removed the explicitly System.err.write calls inside info / warn.
- Separated console logging and log file logging
- Stripped the huge stack traces out of python errors; they are logged
to the screen / cell through log4j.
* Fix info for truncatables
* Address comments

[0.1] Reworked logging to route log output through Python stderr (#2063)

---

src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/annotations/Memory.scala
src/main/scala/is/hail/annotations/MemoryBlock.scala
src/main/scala/is/hail/annotations/ReadRowsRDD.scala
src/main/scala/is/hail/annotations/UnsafeRow.scala
src/main/scala/is/hail/annotations/UnsafeUtils.scala
src/main/scala/is/hail/expr/Type.scala
src/main/scala/is/hail/utils/BytePacker.scala
src/main/scala/is/hail/variant/HTSGenotypeView.scala
src/test/scala/is/hail/annotations/UnsafeSuite.scala

Use off-heap storage.
Replaced Platform => is.hail.annotations.Memory.
Offsets are now Long, including stored offests to binary and arrays.

Preparation for OrderedRDD2.

---

src/main/scala/is/hail/keytable/KeyTable.scala
src/test/scala/is/hail/methods/KeyTableSuite.scala

If a KeyTable has no keys, then the KeyedRDD should have an empty row as the key rather than throwing a fatal error. This was causing problems when using `same` for KeyTables with no keys.

Fixed KeyTable same method

---

python/hail/context.py
python/hail/dataset.py
python/hail/expr.py
python/hail/history.py
python/hail/keytable.py
python/hail/kinshipMatrix.py
python/hail/ldMatrix.py
python/hail/representation/annotations.py
python/hail/representation/genotype.py
python/hail/representation/interval.py
python/hail/representation/pedigree.py
python/hail/representation/variant.py
python/hail/stats.py
python/hail/tests/tests.py
src/main/scala/is/hail/utils/Py4jUtils.scala

- Resolves #1105, #196
- For VDS and KT writes, writes history to `<output_path>/history.txt`
- For all other file types, writes history to `<output>.history.txt`
- Requires new Python dependency: `pip install autopep8`

Write history to file for all export/write commands

---

python/hail/docs/getting_started.rst
src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/kryo/HailKryoRegistrator.scala

`sc.broadcast` uses Kryo for serialization. If Kryo sees an unknown class, it uses the `FieldSerializer` which ignores `@transient` fields and does not call any `java.io.Serializable`. As a result, Kryo always deserializes `SerializableHadoopConfiguration` with a `null` `value` field. The code in `HailKryoRegistrator` instructs Kryo to use Java Serialization instead.

add HailKryoRegistrator and fix cloud tests

---

build.gradle

For Cloudera builds we must compile against Cloudera's Spark package. Without this maven repository, we cannot find the spark package and the build fails.

Fix Cloudera Build

---

python/hail/expr.py
src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/annotations/Annotation.scala
src/main/scala/is/hail/annotations/MemoryBlock.scala
src/main/scala/is/hail/annotations/UnsafeRow.scala
src/main/scala/is/hail/expr/AnnotationImpex.scala
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/expr/HailRep.scala
src/main/scala/is/hail/expr/Parser.scala
src/main/scala/is/hail/expr/Type.scala
src/main/scala/is/hail/io/CassandraConnector.scala
src/main/scala/is/hail/io/annotators/BedAnnotator.scala
src/main/scala/is/hail/io/annotators/IntervalList.scala
src/main/scala/is/hail/io/bgen/BgenLoader.scala
src/main/scala/is/hail/io/plink/PlinkLoader.scala
src/main/scala/is/hail/io/vcf/LoadGDB.scala
src/main/scala/is/hail/io/vcf/LoadVCF.scala
src/main/scala/is/hail/methods/CalculateConcordance.scala
src/main/scala/is/hail/methods/FilterAlleles.scala
src/main/scala/is/hail/methods/IBD.scala
src/main/scala/is/hail/methods/MendelErrors.scala
src/main/scala/is/hail/stats/BaldingNicholsModel.scala
src/main/scala/is/hail/utils/TextTableReader.scala
src/main/scala/is/hail/variant/GenomeReference.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/main/scala/is/hail/variant/VariantMetadata.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/methods/AggregatorSuite.scala
src/test/scala/is/hail/utils/TextTableSuite.scala

- Added genome reference to TVariant, TInterval, TLocus

Reference Genome #3

---

python/hail/docs/getting_started.rst

The script link is dead as the wiki is gone. @danking I'm removing as you suggested, but I recall this had half-dozen lines that included apt-get of java and natives (a bit tricky), which may be helpful info for developers in devel.

Removed “use this script” for fresh Ubuntu install

---

python/hail/docs/conf.py

Default Mathjax CDN is no longer active. https://www.mathjax.org/cdn-shutting-down/

Change mathjax cdn

---

src/test/scala/is/hail/methods/LinearMixedRegressionSuite.scala
src/test/scala/is/hail/methods/LogisticRegressionSuite.scala

@danking the lmm change can be considered a bug fix since delta should never be negative. The log change should make the tests more robust to which JVM. Let me know if this fixes the failures and I'll PR against 0.1 as well.

fixes to help cloud tests pass on lmm and log

---

src/test/scala/is/hail/methods/LinearMixedRegressionSuite.scala

In old code, there's 50% change of generative a negative delta.

fix to make delta > 0 in LMM suite

---

src/main/scala/is/hail/methods/ImputeSexPlink.scala
src/main/scala/is/hail/methods/LinearMixedRegression.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/annotations/AnnotationsSuite.scala
src/test/scala/is/hail/io/ExportVcfSuite.scala
src/test/scala/is/hail/methods/FilterSuite.scala

The previous idiom was mapAnnotations(...).copy(vaSignature =
newVASignature), but this results (temporarily) in a VDS with an
incorrect va type that which causes problems for downstream changes
and assertions like typecheck.

mapAnnotations takes new va type.

---

python/hail/keytable.py
src/main/scala/is/hail/expr/Type.scala
src/main/scala/is/hail/keytable/KeyTable.scala
src/test/scala/is/hail/methods/AnnotateSuite.scala
src/test/scala/is/hail/methods/ExprSuite.scala
src/test/scala/is/hail/methods/KeyTableSuite.scala
src/test/scala/is/hail/methods/LogisticRegressionBurdenSuite.scala
src/test/scala/is/hail/variant/IntervalSuite.scala

Verify Field index is the index within the TStruct.
field => column in keytable.  This was an old rename but looks like
some things got missed.
Simplify KT.select interface in Scala (and mathc Python).

Some keytable cleanup.

---

python/hail/keytable.py
python/hail/tests/tests.py
src/main/scala/is/hail/keytable/KeyTable.scala

This method functions very similarly to to_dataframe().show(), with
some important distinctions.
- Don't call flatten / expandTypes. Instead, expand only structs and call
Type.str on non-struct types.
- Right-align numeric columns, left-align everything else
- Customizable truncation
- Column types are printed optionally (default true)

Added KeyTable.show

---

python/hail/keytable.py
python/hail/tests/tests.py
src/main/scala/is/hail/keytable/KeyTable.scala

* Added KeyTable.show
This method functions very similarly to to_dataframe().show(), with
some important distinctions.
- Don't call flatten / expandTypes. Instead, expand only structs and call
Type.str on non-struct types.
- Right-align numeric columns, left-align everything else
- Customizable truncation
- Column types are printed optionally (default true)
* Address comments and expand docs

[0.1] Added KeyTable.show (#2191)

---

python/hail/docs/getting_started.rst

This should also go against `master` once we're happy with the verbiage.

Make Cloudera Build from Source documentation very explicit

---

src/main/scala/is/hail/methods/Skat.scala
src/test/scala/is/hail/methods/SkatSuite.scala

Added typecheck to SkatSuite as regression test.
keysType was being passed instead of keyType, which resulted for example in Array[String] instead of String as the type of key when the variantKeys was an Array[String] annotation and singleKey was False.

Fixed bug on Skat key type

---

build.gradle

@cseed @tpoterba Thoughts? this is necessary to compile against hortonworks Spark. We already include cloudera stuff. Should we include both? Only cloudera? Neither?

add repositories necessary for compiling against hortonworks Spark

---

src/main/scala/is/hail/utils/UnionFind.scala
src/test/scala/is/hail/utils/UnionFindSuite.scala

This has no current practical use, but we may find a UnionFind structure useful in the future. I implemented this for fun a couple weekends ago.

add UnionFind data structure with tests

---

python/hail/dataset.py

`record_method` works for `annotate_variants_db` with no additional modifications based on how History is structured. I confirmed that any additional method calls in the function are not showing up in the `history.txt` file.

Add annotate_variants_db decorators

---

src/test/scala/is/hail/methods/DeNovoSuite.scala
src/test/scala/is/hail/methods/LDMatrixSuite.scala
src/test/scala/is/hail/methods/SkatSuite.scala

Every suite is allocated by the gradle test framework, and then only those matching the requested filters are executed. Ergo, non-lazy fields on a suite will be executed (and may trigger errors) even though the suite wasn't requested by the gradle user.

Avoid computation in suite allocation

---

python/hail/docs/getting_started_developing.rst
src/main/c/Makefile

`libsimdpp` only requires CMake for creating a distribution that can be installed on a given system. We only need the header files at compile time, so there's no need to install it. This removes our dependency on CMake and prevents recompilation of the C code on each call to `gradle test` (as well as `compileScala` and `compileTestScala`).

Speed up gradle test by 3s

---

python/hail/dataset.py
python/hail/typecheck/__init__.py
python/hail/typecheck/check.py
src/main/scala/is/hail/methods/PCRelate.scala
src/main/scala/is/hail/variant/VariantDataset.scala

Builds on PC Relate Unified Filtering #2238.
I think this practically much more valuable to our users than filtering.
This avoids computation of unneeded statistics (they appear as NA in the output).
I'm happy to rebase without unified filtering, but it's some work to do that, so I'd rather decide one way or the other on filtering first.

PC Relate: Add a desired output flag [PCRI-2]

---

src/main/scala/is/hail/methods/LDMatrix.scala
src/test/scala/is/hail/methods/LDMatrixSuite.scala

Removes two unnecessary stages and persists to prevent recomputing stages. These changes are orthogonal to improvement from HailBlockMatrix and should go in master as well once this is in.

improvements to LDMatrix

---

src/test/scala/is/hail/stats/BaldingNicholsModelSuite.scala

Unnecessarily specific (and crashes on UnsafeRow).

Use Row instead of GenericRow.

---

src/main/scala/is/hail/utils/HashMethods.scala

Implements the two "multiply-shift" hash functions, as described in [High Speed Hashing for Integers and Strings](http://arxiv.org/abs/1504.06804v3), sections 2.3 and 3.3. They have the weakest still useful distributional properties, but are often sufficient, and very very fast.

Add simplest hash functions

---

python/hail/keytable.py

@patrick-schultz you can look at the docs by opening the docs test result link below, then navigating to artifacts then navigating to the index.html page in that folder structure.

fix link syntax in KeyTable.maximal_independent_set docs

---

src/main/scala/is/hail/utils/HashMethods.scala

Implements a more involved tabulation based hash function which achieves 5-independence (which will be needed in one of the basic primitives for randomized linear algebra). This method is described in [Tabulation-Based 5-Independent Hashing with Applications to Linear Probing and Second Moment Estimation](http://www.cs.utexas.edu/~yzhang/papers/5-indep-sicomp12.pdf), which provides C code in section A.7.

Implement 5-independent tabulation hash

---

src/main/scala/is/hail/utils/HashMethods.scala

Implements simple tabulation and twisted tabulation hash methods. See [Fast and Powerful Hashing using Tabulation](http://arxiv.org/abs/1505.01523v5): simple tabulation is described in Section 2, twisted tabulation is described in Section 3, and Figure 1 on p.9 has C code for both.

Add simple- and twisted-tabulation hashes

---

src/main/scala/is/hail/io/bgen/BgenLoader.scala

Bug discovered when reviewing #2228. Should not be an issue in 0.2 after #2228 is done. If this fix makes UK Biobank import too slow, then I can change the `BgenBlockReaderV12` code to not accept multi-allelic variants.

Fix wasSplit for BGEN loader [0.1]

---

src/main/scala/is/hail/asm4s/Code.scala
src/main/scala/is/hail/asm4s/package.scala

fixes and additions to asm4s.Code
- added invokeStatic with 4 args, fixed invokeStatic with 3 args
- for CodeBoolean, changed && -> & and || -> | for bitwise operations; implemented new && and || as short-circuit boolean operations
- defined some new ops for CodeInt and CodeLong
- fixed TypeInfo for Byte to use BALOAD and BASTORE
- implicit conversions for Byte->Code[Byte], Code[Byte]->CodeInt, Code[Byte]->Code[Int]

asm4s.Code additions

---

python/hail/keytable.py

Somehow, this didn't trigger an error in master but did in 0.1. Nonetheless, removing unnecessary data seems good.

In MIS example, throw away conflicting columns before joining

---

src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/sparkextras/OrderedRDD2.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/io/LoadBgenSuite.scala

mapValuesWithAll should go away eventually (as should all routines representing runtime values as Annotation).
This makes filterGenotypes semi-native in particular.
Removed unused filterGenotypes on VariantDataset.
Removed unused mapPartitionsWithAll.

Semi-native mapValueWithAll (it can only be semi-native)

---

python/hail/context.py
python/hail/utils.py

> TMPDIR
>     This variable shall represent a pathname of a directory made
>     available for programs that need a place to create temporary
>     files.
http://pubs.opengroup.org/onlinepubs/9699919799/
Requested by the discuss user rca:
http://discuss.hail.is/t/hailcontext-tmp-dir/323

read POSIX TMPDIR for hail temporary directory

---

src/main/scala/is/hail/annotations/MemoryBlock.scala
src/main/scala/is/hail/annotations/UnsafeUtils.scala
src/main/scala/is/hail/expr/Type.scala
src/main/scala/is/hail/utils/richUtils/RichCodeMemoryBuffer.scala
src/main/scala/is/hail/variant/HTSGenotypeView.scala

- `TContainer.loadLength` is now on the object so creating byte code to
read the length does not require knowledge of the element type
- in `elementsOffset`, use the non-Code pattern of delegating to
`roundUpAlignment`
- add staged `TContainer.elementOffset`, `TContainer.loadElement`,
`TStruct.fieldOffset`, `UnsafeUtils.roundUpAlignment`
- fix bug: loadElement reads addresses using `loadAddress` instead of
`loadInt`
- add several `loadX` methods to `RichCodeMemoryBuffer`.

improve staged Type methods

---

python/hail/context.py
src/main/scala/is/hail/HailContext.scala
src/test/scala/is/hail/variant/vsm/VSMSuite.scala

Simplify the read logic by no longer reading multiple files at once. This functionality is preserved in the newly-added union function.

Simplify read logic

---

src/main/scala/is/hail/check/Gen.scala
src/test/scala/is/hail/distributedmatrix/BlockMatrixSuite.scala

The native libraries sometimes play tricks to squeeze out better
precision if the memory layout is amenable to it. This causes some
of our tests to fail, particularly those related to transposition.
We avoid extreme values which should keep us from encountering
situations where naive arithmetic produces Infinity.

use nonExtremeDouble to avoid test failures

---

src/main/scala/is/hail/expr/Fun.scala
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/methods/Aggregators.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala

Need to copy in certain aggregators since the input can now point to underlying regions which will be reset.

use region value in aggregators

---

python/hail/dataset.py
python/hail/representation/genotype.py
python/hail2/expr/column.py
src/main/scala/is/hail/annotations/Annotation.scala
src/main/scala/is/hail/annotations/MemoryBlock.scala
src/main/scala/is/hail/annotations/UnsafeRow.scala
src/main/scala/is/hail/expr/AnnotationImpex.scala
src/main/scala/is/hail/expr/Fun.scala
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/expr/Type.scala
src/main/scala/is/hail/methods/Aggregators.scala
src/main/scala/is/hail/methods/SplitMulti.scala
src/main/scala/is/hail/variant/Genotype.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/main/scala/is/hail/variant/VariantKeyDatasetFunctions.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/io/HardCallsSuite.scala
src/test/scala/is/hail/io/SplitSuite.scala
src/test/scala/is/hail/methods/DeNovoSuite.scala
src/test/scala/is/hail/variant/GenotypeSuite.scala

Generic: computation of split values is done in expression language.
Support HTS-like split of generic schema.
Removed fakeRef, which I don't think anyone ever used.  If anyone wants it, can be added through expression language once that is exposed.
@tpoterba FYI I removed fakeRef.

 Use region values in SplitMulti.

---

src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/annotations/ReadRowsRDD.scala
src/main/scala/is/hail/annotations/UnsafeRow.scala
src/main/scala/is/hail/distributedmatrix/BlockMatrix.scala
src/main/scala/is/hail/distributedmatrix/GridPartitioner.scala
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/io/RowStore.scala
src/main/scala/is/hail/keytable/KeyTable.scala
src/main/scala/is/hail/utils/richUtils/Implicits.scala
src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala
src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala
src/main/scala/is/hail/utils/richUtils/RichIndexedRowMatrix.scala
src/main/scala/is/hail/utils/richUtils/RichRDD.scala
src/test/scala/is/hail/annotations/UnsafeSuite.scala
src/test/scala/is/hail/distributedmatrix/BlockMatrixSuite.scala
src/test/scala/is/hail/distributedmatrix/GridPartitionerSuite.scala
src/test/scala/is/hail/variant/vsm/VSMSuite.scala

@cseed I've implemented `readPartitions` on `HailContext` and `writePartitions` on `RichRDD`, re-implemented read/write of blocks on `BlockMatrix` to preserve partitioning using these, and moved MatrixValue and KeyTable row read/write to use these.
readPartitions and writePartitions use `unsafeReadPartition` and `writePartition` in RichHadoopConfig.  `readRow` includes `close()`, and I've added `close()` to `readBlock` as well. At first I used `using` (see `readPartition` which is remarked out), but this closes the resource before the iterator iterated in the readRows case. Yet somehow, `testWriteRead` in VSMSuite passes even with `readPartition`. This test just creates a random VDS, writes, reads, compares.  I added `testWriteRead2` which imports `sample.vcf`, writes, reads, compares. …

Abstracted partitioned read/write and used in BlockMatrix

---

src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
src/main/scala/is/hail/asm4s/AsmFunction.scala
src/main/scala/is/hail/asm4s/Code.scala
src/main/scala/is/hail/asm4s/FunctionBuilder.scala
src/main/scala/is/hail/asm4s/GenericTypeInfo.scala
src/main/scala/is/hail/asm4s/StagedBitSet.scala
src/main/scala/is/hail/asm4s/package.scala
src/main/scala/is/hail/expr/Type.scala
src/main/scala/is/hail/expr/ir/BinaryOp.scala
src/main/scala/is/hail/expr/ir/Casts.scala
src/main/scala/is/hail/expr/ir/Children.scala
src/main/scala/is/hail/expr/ir/Compile.scala
src/main/scala/is/hail/expr/ir/Copy.scala
src/main/scala/is/hail/expr/ir/Env.scala
src/main/scala/is/hail/expr/ir/IR.scala
src/main/scala/is/hail/expr/ir/Infer.scala
src/main/scala/is/hail/expr/ir/UnaryOp.scala
src/main/scala/is/hail/expr/ir/package.scala
src/main/scala/is/hail/utils/richUtils/RichCodeMemoryBuffer.scala
src/test/scala/is/hail/annotations/StagedRegionValueSuite.scala
src/test/scala/is/hail/asm4s/ASM4SSuite.scala
src/test/scala/is/hail/asm4s/StagedBitSetSuite.scala
src/test/scala/is/hail/expr/ir/CompileSuite.scala

To achieve this we need TypeInfo[T] to require ClassTag[T], to keep
the requirements to one type class, we switch from implicits to
type class constraints and an implicit extracting method, `typeInfo`.

allow creation of arrayInfo from element TypeInfo

---

src/main/scala/is/hail/annotations/MemoryBlock.scala
src/main/scala/is/hail/io/vcf/HtsjdkRecordReader.scala
src/main/scala/is/hail/io/vcf/LoadVCF.scala
src/main/scala/is/hail/utils/ArrayStack.scala

I would appreciate a review from anyone who has time.  First of two (probably) for fast VCF parser.  Main functionality still goes through HTSJDK.  Next one will handle the genotypes.
Signature for parseLines is a bit nuts but it definitely reduces the code size.  @danking calling `hasNext` on my iterator invalidates it.  I think this is inevitable and we should embrace it.  Seems to work fine.
Warn when filtering alleles due to invalid REF or symbolic alts.  Much better than dropping data silently.
Added `clear` to `ArrayStack` and `RegionValueBuilder`.

Custom parser for variant (key) in LoadVCF.

---

python/hail/dataset.py
src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/annotations/MemoryBlock.scala
src/main/scala/is/hail/io/RowStore.scala
src/main/scala/is/hail/io/vcf/LoadVCF.scala
src/main/scala/is/hail/methods/SampleQC.scala
src/main/scala/is/hail/methods/VariantQC.scala
src/main/scala/is/hail/utils/Context.scala
src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala
src/main/scala/is/hail/utils/richUtils/RichSparkContext.scala
src/main/scala/is/hail/variant/Genotype.scala
src/main/scala/is/hail/variant/HTSGenotypeView.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/io/ImportVCFSuite.scala
src/test/scala/is/hail/utils/TextTableSuite.scala

Parse format field directly, don't use HTSJDK.
I also lowered the compression block size to balance size and speed.
Sizes:
```
original:
214M profile.vcf.bgz
1.2G gnomad.genomes.r2.0.2.sites.chr21.vcf.bgz
631M exac_table.tsv.bgz
fastvcf:
248M profile.vds
1.4G gnomad.sites.vds
688M exac.kt
is/master
224M profile.vds
1.2G gnomad.sites.vds
610M exac.kt
is/master
207M profile.vds
1.1G gnomad.sites.vds
550M exac.kt
```
So the sizes for fastvcf are slightly worse than master and 0.1, about 10-15% larger than the originals.
Speed:
```
fastvcf:
import_vcf/count 7.8s
import_vcf/write 15.3s
import_gnomad_sites/write 51.4s
read/count 2.1s
import_table/write 99.4s
read_table/count 7s
is/master:
import_vcf/count 14s
import_vcf/write 25.5s
import_gnomad_sites/write 57.8s
read/count 2.1s …
```

format field parser

---

python/hail/tests/tests.py
python/hail/typ.py
src/main/scala/is/hail/io/vcf/LoadGDB.scala
src/main/scala/is/hail/io/vcf/LoadVCF.scala

Intern types rather than recording singletons.
Remove canonical field stuff from LoadVCF (unused), move to LoadGDB.

Fixed single type problem in Python.

---

src/main/scala/is/hail/expr/Parser.scala
src/main/scala/is/hail/expr/Type.scala
src/main/scala/is/hail/io/bgen/BgenLoader.scala
src/main/scala/is/hail/io/plink/PlinkLoader.scala
src/main/scala/is/hail/io/vcf/LoadGDB.scala
src/main/scala/is/hail/io/vcf/LoadVCF.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/main/scala/is/hail/variant/VariantMetadata.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/annotations/AnnotationsSuite.scala
src/test/scala/is/hail/methods/DeNovoSuite.scala
src/test/scala/is/hail/vds/FilterAllelesSuite.scala

Insertable types are those that can have .insert called.
In particular, we cannot insert into an optional struct
containing required fields because there is no sensible
defaults for those required fields.
I also did some clean up of the Type generators while
implementing this

implement genInsertable

---

src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/utils/Context.scala
src/main/scala/is/hail/utils/ErrorHandling.scala

I thought we fixed this already? Maybe it was never back ported to 0.1. This should preserve the stack traces for exceptions encountered inside a `WithContext.map`

propagate root-cause exceptions

---

python/hail/dataset.py
src/main/scala/is/hail/io/vcf/ExportVCF.scala
src/test/scala/is/hail/io/ExportVCFSuite.scala

- added reference and contig names/lengths to header in export_vcf
- added line in docs
- added a test
- renamed ExportVcfSuite to ExportVCFSuite to match classname and ImportVCFSuite
@jigold is going to update GenomeReference to capture MD5, at which point I'll make a PR to export other metadata.

include contigs in export vcf header

---

python/hail/dataset.py
src/main/scala/is/hail/sparkextras/OrderedRDD.scala
src/main/scala/is/hail/sparkextras/OrderedRDD2.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala

Well, OrderedRDD2-ify.
@jbloom22 This needed by Robert to export the cohorts.  Timely review appreciate.

RV-ify naive coalesce.

---

src/main/scala/is/hail/utils/FunctionDocumentation.scala

got rid of all the "!" cluttering up type documentation; also fixed up the "()" parsing so that functions with Variant/Locus/AltAllele as args or return types will display e.g. "f: Genotype => Variant(GR)". instead of "f: Genotype => VariantGR". (I think TFunction is the only other type that uses 
"()" in the string representation and needs it removed for the docs; if not I'll need to fix that.)

 clean up type parsing for FunctionDocumentation.scala

---

src/main/scala/is/hail/utils/HashMethods.scala
src/test/scala/is/hail/utils/HashMethodsSuite.scala

* Implement arithemetic in the finite field of order 2^32, as
polynomials over F_2 modulo the irreducible polynomial
x^32 + x^7 + x^3 + x^2 + 1.
* Define class `PolyHash`, implementing polynomials over above field,
using Horner's rule for polynomial evaluation.
* Use random polynomials to fill tables in tabulation hashes, for
guaranteed 32-independent randomness.

Polynomial-based hashes

---

python/hail/ldMatrix.py
src/main/scala/is/hail/methods/ExportableMatrix.scala
src/main/scala/is/hail/methods/KinshipMatrix.scala
src/main/scala/is/hail/methods/LDMatrix.scala
src/test/scala/is/hail/methods/LDMatrixSuite.scala

rudimentary matrix export as text facilities (#2450)

---

python/hail/dataset.py
python/hail/docs/conf.py
python/hail2/dataset.py
python/hail2/tests.py
src/main/scala/is/hail/methods/SplitMulti.scala
src/main/scala/is/hail/variant/Genotype.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/test/scala/is/hail/methods/AnnotateAllelesSuite.scala

Which exposes the generic split_multi interface.
When we nuke Genotype, I will rename split_multi_generic => split_multi and split_multi => split_multi_hts.
Updated the interface slightly.  The rule I'm using is: v, va, g, etc. all denote the old annotations and newV denotes the new, split variant.

Added split_multi_generic.

---

python/hail/representation/genotype.py
python/hail/tests/tests.py
python/hail/typ.py

There was a bug converting Call to/from Java, in this line:
if annotation:
A call is represented by a 0 integer which is False in Python.  I
changed all of these to `if annotation is not None`.
Also, there was a bit of confusion in the call interface inherited
from genotype.  A not call is just a missing Call value (in python)
and a null Call = java.lang.Integer (in Java).

Fix python Call handle bug (and probably another annotations)

---

python/hail/representation/genotype.py
python/hail/tests/tests.py
python/hail/typ.py
src/main/scala/is/hail/annotations/MemoryBlock.scala
src/main/scala/is/hail/expr/Type.scala

When instantiating structs inserting into missing structs, make sure
to set all fields (except the one we're inserting into) to missing.

Fix bug inserting into missing structs.

---

python/hail/representation/genotype.py
python/hail/tests/tests.py
python/hail/typ.py
src/main/scala/is/hail/annotations/MemoryBlock.scala
src/main/scala/is/hail/expr/Type.scala
src/main/scala/is/hail/methods/Aggregators.scala

Aggregators can close over a, so the tree aggregation step in the
aggregators can cause any values left over in a to be serialized.
Since we're putting annotations backed by region values into a, that
can go bad.

Fix potential crash.

---

src/main/scala/is/hail/methods/VEP.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala

RV-ify the easy case.
Preserve partitioning where possible in VSM legacy constructors.

Some improvements for VEP.

---

python/hail/dataset.py
src/main/scala/is/hail/methods/SplitMulti.scala
src/main/scala/is/hail/methods/VEP.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/vds/FilterAllelesSuite.scala

Also nuked filter_altered_genotypes which I don't think anyone was using, couldn't possibly have been the intended implementation, and can now be done generically.
I copied the existing annotate_alleles interface but, in light of generics, I don't like it anymore. I will propose an alternative on the dev forum.

Added generic filter_alleles, annotate_alleles.

---

python/hail/dataset.py
src/main/scala/is/hail/annotations/Annotation.scala
src/main/scala/is/hail/annotations/Memory.java
src/main/scala/is/hail/annotations/MemoryBlock.scala
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/io/RowStore.scala
src/main/scala/is/hail/methods/SplitMulti.scala
src/main/scala/is/hail/methods/VEP.scala
src/main/scala/is/hail/utils/ArrayBuilder.scala
src/main/scala/is/hail/utils/TruncatedArrayIndexedSeq.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/methods/ExprSuite.scala
src/test/scala/is/hail/vds/FilterAllelesSuite.scala

Allocating memory off-heap but relying on the GC to deallocate will
never work.  Since regions are allocated for iterators, it is
difficult to know when we can free the memory.  When hasNext returns
false, but ending iteration early will lead to a memory leak.  We
could define something like a CloseableIterator which closes itself at
the end of iteration and clients have to close if they exit early, but
this won't play nicely with Spark (or Scala iterators, for that
matter).
This doesn't matter in the current setup but will make it somewhat
more difficult to push things into C/C++.

Use array instead of off-heap memory in RegionValue.

---

python/hail/context.py
python/hail/dataset.py
python/hail/tests/tests.py
python/hail/typ.py
src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/expr/Parser.scala
src/main/scala/is/hail/expr/Type.scala
src/main/scala/is/hail/io/package.scala
src/main/scala/is/hail/io/vcf/ExportVCF.scala
src/main/scala/is/hail/io/vcf/LoadGDB.scala
src/main/scala/is/hail/io/vcf/LoadVCF.scala
src/main/scala/is/hail/keytable/KeyTable.scala
src/main/scala/is/hail/methods/LDMatrix.scala
src/main/scala/is/hail/methods/VEP.scala
src/main/scala/is/hail/stats/CallStatsCombiner.scala
src/main/scala/is/hail/stats/HWECombiner.scala
src/main/scala/is/hail/stats/HistogramCombiner.scala
src/main/scala/is/hail/stats/InbreedingCombiner.scala
src/main/scala/is/hail/stats/InfoScoreCombiner.scala
src/main/scala/is/hail/utils/FunctionDocumentation.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/annotations/AnnotationsSuite.scala
src/test/scala/is/hail/io/ExportVCFSuite.scala
src/test/scala/is/hail/methods/ExprSuite.scala

I'm getting this warning:
```
/Users/jigold/hail/src/main/scala/is/hail/io/vcf/ExportVCF.scala:199: non-variable type argument String in type pattern scala.collection.immutable.Map[String,Any] (the underlying of Map[String,Any]) is unchecked since it is eliminated by erasure
case Some(x: Map[String, Any]) => getAttributes(path.tail, Some(x))
```
If you have suggestions on how to improve the `getAttributes` function, I'd appreciate it!

Remove attributes from Type

---

src/main/scala/is/hail/expr/ir/Recur.scala

If we view IR as the least fixpoint of an algebra wherein recursive
references are replaced with a type parameter, a la:
IR[T] ::= I32() ...
|  Cast(T, Type)
|  ...
|  Let(T, String, T, Type)
|  ...
Then IR is a functor and has a natural map operation.
Recur is inspired by this intuition, but in the restricted situation of
Scala's built-in type recursion.

implement a map-like operation on IR

---

src/main/scala/is/hail/expr/Fun.scala
src/main/scala/is/hail/expr/FunctionRegistry.scala

This is needed for future genome reference pull requests to be able to access the ordering from the GenomeReference after the variable GR has been substituted for.

Added dependent functions to registry

---

src/main/scala/is/hail/distributedmatrix/BlockMatrix.scala
src/main/scala/is/hail/distributedmatrix/GridPartitioner.scala
src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala
src/main/scala/is/hail/utils/richUtils/RichIndexedRowMatrix.scala
src/main/scala/is/hail/utils/richUtils/RichRDD.scala
src/test/scala/is/hail/TestUtils.scala
src/test/scala/is/hail/distributedmatrix/BlockMatrixSuite.scala
src/test/scala/is/hail/distributedmatrix/GridPartitionerSuite.scala
src/test/scala/is/hail/utils/RichIndexedRowMatrixSuite.scala

@cseed after comments in #2482, I reworked this so that for each block row, each overlapping parent partition is iterated through once, writing out the full row into files corresponding to block columns.
Based on the WriteBlocksRDDPartition comment and looking at BlockedRDD, now rather than computing the indices of all non-empty overlapping parent partitions, I switched to just computing the first and last overlapping parent partitions, and the number of rows to skip in the first partition, and put this in WriteBlocksRDDPartition. I'd appreciate feedback on this approach, and whether I've put the "right" data in WriteBlocksRDDPartition. In particular, I'm unsure why `computeBlockRowDependencies` would have been called multiple times given that it's a private val in the class. Is the class …

Block export on IRM v2

---

python/hail/representation/genomeref.py
src/main/scala/is/hail/expr/AnnotationImpex.scala
src/main/scala/is/hail/variant/GenomeReference.scala
src/test/scala/is/hail/variant/GenomeReferenceSuite.scala

- Intervals cannot be in GenomeReference constructor because intervals
are parameterized by reference with Ordering[Locus]

Modified GenomeReference constructor

---

src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/variant/vsm/ExplodeSuite.scala

explodeVariants and explodeSamples are failing on Set keys because of cast to IndexedSeq. And on key=[1, 2], explodeSamples is annotating each sample with [1,2] rather than with 1 and then 2. Here are fixes and regression tests.

fixed explode to handle sets and annotate samples with key elements

---

src/main/scala/is/hail/annotations/MemoryBlock.scala
src/main/scala/is/hail/expr/package.scala
src/main/scala/is/hail/utils/richUtils/RichCodeMemoryBuffer.scala
src/test/scala/is/hail/annotations/ScalaToRegionValue.scala
src/test/scala/is/hail/annotations/StagedRegionValueSuite.scala
src/test/scala/is/hail/expr/ir/CompileSuite.scala

I think I also fixed a couple bugs in the tests where we set `rv`
instead of `rv2`.

Add ScalaToRegionValue convenience functions

---

python/hail/java.py

Output for a requirement failed exception now looks like:
```
File "hail_extract_cohorts.py", line 37, in <module>
vds = vds.annotate_global('global.samples_to_exclude', set(samples_to_exclude_list), hail.TSet(hail.TString()))
File "<decorator-gen-390>", line 2, in annotate_global
File "/home/cotton/hail/python/hail/java.py", line 167, in handle_py4j
'Error summary: %s' % (e.desc, e.stackTrace, Env.hc().version, e.desc))
hail.java.FatalError: requirement failed
Java stack trace:
scala.Predef$.require(Predef.scala:212)
at is.hail.variant.VariantSampleMatrix.annotateGlobal(VariantSampleMatrix.scala:564)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at …
```

Stacktrace

---

src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/io/RowStore.scala
src/main/scala/is/hail/keytable/KeyTable.scala
src/main/scala/is/hail/rvd/RVD.scala
src/main/scala/is/hail/stats/ComputeRRM.scala
src/main/scala/is/hail/utils/richUtils/RichRDD.scala
src/main/scala/is/hail/variant/VariantMetadata.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala

Use partitionCounts in VSM.count, VSM.toIndexedRowMatrix and ToNormalizedIndexedRowMatrix.

Include partition counts in VSM/KT metadata.

---

src/main/scala/is/hail/variant/VariantDataset.scala

The prior form raises a warning about existential types that cannot be expressed using wildcards.
Here we use the rule that
(exists t. t) => u
is equivalent to
(forall t. t => u)
which is basically how quantifiers switch when moving through implication arrows.

scala handles universals better than existentials

---

src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
src/main/scala/is/hail/expr/ir/Compile.scala
src/test/scala/is/hail/annotations/StagedRegionValueSuite.scala

An IR Intermediate is:
- a value of a primitive type capable of being stored in a JVM stack
slot (or two, as the case may be), or
- a pointer to a value of a non-primitive type (e.g. Array, Struct)
Pointers are of type `Long` and are implicitly in the working region of
the this IR fragment.

addPrimitive becomes addIRIntermediate

---

src/main/scala/is/hail/asm4s/Code.scala
src/main/scala/is/hail/expr/ir/BinaryOp.scala
src/main/scala/is/hail/expr/ir/UnaryOp.scala

@patrick-schultz I believe you noted this earlier, so I'm assigning to you.

eliminate match warnings in UnaryOp and BinaryOp

---

src/main/scala/is/hail/methods/PCA.scala
src/main/scala/is/hail/methods/PCRelate.scala
src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/methods/PCASuite.scala
src/test/scala/is/hail/methods/PCRelateReferenceImplementation.scala
src/test/scala/is/hail/methods/PCRelateSuite.scala

-pulled PCA and PCRelate from Spark to Breeze DenseMatrix
-improved PCA math to not realize diagonal matrix when rescaling scores
-deleted unused horzcat on RichDenseMatrix
-improved formatting/readability

moved PCA / PCRelate from spark to breeze dense matrices, other improvements

---

src/main/scala/is/hail/check/Gen.scala
src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/expr/Type.scala
src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/sparkextras/OrderedRDD.scala
src/main/scala/is/hail/utils/IntervalTree.scala
src/main/scala/is/hail/utils/package.scala
src/main/scala/is/hail/variant/GenomeReference.scala
src/main/scala/is/hail/variant/Genotype.scala
src/main/scala/is/hail/variant/Variant.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/annotations/UnsafeSuite.scala
src/test/scala/is/hail/distributedmatrix/BlockMatrixSuite.scala
src/test/scala/is/hail/io/ExportVCFSuite.scala
src/test/scala/is/hail/io/LoadBgenSuite.scala
src/test/scala/is/hail/io/SplitSuite.scala
src/test/scala/is/hail/io/compress/BGzipCodecSuite.scala
src/test/scala/is/hail/methods/ConcordanceSuite.scala
src/test/scala/is/hail/methods/LDPruneSuite.scala
src/test/scala/is/hail/utils/BitVectorSuite.scala
src/test/scala/is/hail/utils/OrderedRDDSuite.scala
src/test/scala/is/hail/utils/UtilsSuite.scala
src/test/scala/is/hail/variant/IntervalSuite.scala

The core issue is that we want Scala to infer the T parameter
but not the C[_] parameter. Unfortunately, Scala does not provide
a facility to partially specify type parameters of a method
the changes herein achieve this with no run-time allocation
one cast, and one level of indirection.

Improve inference of anyFailAllFail

---

src/main/scala/is/hail/annotations/Region.scala
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/expr/ir/Compile.scala
src/main/scala/is/hail/expr/ir/Emit.scala
src/main/scala/is/hail/expr/ir/Env.scala
src/main/scala/is/hail/expr/ir/Subst.scala
src/main/scala/is/hail/expr/ir/TypeToIRIntermediateClassTag.scala
src/main/scala/is/hail/expr/ir/TypeToPrimitiveClassTag.scala
src/main/scala/is/hail/expr/ir/package.scala

Use in filterSamples.
I might stop here for the moment.  This seems about as good for the interface as one could hope modulo and easier way to write the IR.
I'll come back to `InsertStruct` once physical types are in.
@catoverdrive FYI this might be a useful idiom when adding the IR to key tables, etc.

Add one-stop-shopping Compile interface to ir.

---

build.gradle
python/hail/api1/tests.py
python/hail/expr/tests.py
python/hail/genetics/tests.py
python/hail/utils/tests.py

This will make it easier to rip out hail1 when the time comes.

Reorganize tests by splitting them out into appropriate modules.

---

python/hail/api1/dataset.py
python/hail/methods/qc.py
src/main/scala/is/hail/methods/SampleQC.scala
src/main/scala/is/hail/methods/VariantQC.scala
src/main/scala/is/hail/variant/VariantSampleMatrix.scala
src/test/scala/is/hail/annotations/SplatSuite.scala
src/test/scala/is/hail/expr/KeyTableIRSuite.scala
src/test/scala/is/hail/io/ImportPlinkSuite.scala
src/test/scala/is/hail/methods/AggregatorSuite.scala
src/test/scala/is/hail/methods/AnnotateGlobalSuite.scala
src/test/scala/is/hail/methods/ExportSuite.scala
src/test/scala/is/hail/methods/FilterSuite.scala
src/test/scala/is/hail/methods/ImputeSexSuite.scala
src/test/scala/is/hail/methods/ProgrammaticAnnotationsSuite.scala
src/test/scala/is/hail/methods/gqDpStatsSuite.scala
src/test/scala/is/hail/stats/HWESuite.scala
src/test/scala/is/hail/stats/InbreedingCoefficientSuite.scala
src/test/scala/is/hail/vds/BiallelicMethodsSuite.scala

Moved sample and variant QC methods from VDS to their own objects, and call the object apply methods from elsewhere (tests and python).
If we're happy with this model (following the hail2 api) I'll change everything else.
Long chains of `vds.f().g().h()` will need to get broken up as
```
var vdss = ...
vds = f(vds)
vds = g(vds)
vds =  h(vds)
```
to avoid unnecessary nesting (and clarity).

Moved variant, sample QC to method objects.

---

src/test/scala/is/hail/expr/TableIRSuite.scala

No need to import a sub-package. Sub-packages are implicitly imported.

fix warning in table ir suite

---

src/main/scala/is/hail/expr/ir/IR.scala

Without the final modifier, these case classes may be subclassed by arbitrary classes.

finalize IR case classes

---

src/main/scala/is/hail/annotations/aggregators/RegionValueSumAggregator.scala
src/main/scala/is/hail/asm4s/Code.scala
src/main/scala/is/hail/asm4s/package.scala

The AnyRef bound is necessary for the ability to reflectively
invoke methods. The Null bound is necessary for operations that
return null as a value of that type.
Unfortunately AnyRef does not imply a Null lower bound. This
PR resolves this issue by formally divorcing the two notions.
Most types will staisfy both bounds enabling the use of
either implicit. I actually am not aware of what types do not
satisfy both bounds.

Split CodeNullable from CodeObject

---

python/hail/api1/dataset.py
python/hail/api1/keytable.py
python/hail/api2/matrixtable.py
python/hail/api2/table.py
python/hail/expr/aggregators.py
python/hail/expr/ast.py
python/hail/expr/expression.py
python/hail/expr/functions.py
python/hail/typecheck/__init__.py
python/hail/typecheck/check.py
python/hail/typecheck/tests.py

This involves a rework of the varargs/kwargs typecheck semantics:
old:
```
@typecheck(args=tupleof(int), kwargs=dictof(str, int))
def f(*args, **kwargs):
```
new:
```
@typecheck(args=int, kwargs=int)
def f(*args, **kwargs):
```

Support expressions in typecheck more naturally

---

python/hail/linalg/matrix.py
src/main/scala/is/hail/distributedmatrix/BlockMatrix.scala
src/main/scala/is/hail/utils/richUtils/RichIterable.scala
src/test/scala/is/hail/distributedmatrix/BlockMatrixSuite.scala

This adds filter, filterCols, and filterRows to BlockMatrix, en route to moving kinship and LD matrix to from IRM to BlockMatrix. For example, filtering out rows/columns from a kinship matrix (e.g. to remove samples with missing covariate data); or filtering an LD matrix (e.g. to perform Leave-One-Chromosome-Out LMM analysis).
Since the number of tasks equals the number of resulting partitions (blocks), these functions are suited to filtering out a small to medium subset (say, throwing out a few rows and columns, or half of the rows and columns) and may fail when filtering all but a small number of rows and columns due to all the blocks being sent to one executor. In the latter case, one can do better by writing the result of filterCols, then reading and applying filterRows.
Testing …

filter on BlockMatrix

---

src/main/scala/is/hail/io/bgen/BgenRecord.scala

It should be in case the BGEN is shuffled.

[0.1] Make Bgen12GenotypeIterator serializable.

---

python/hail/docs/getting_started.rst

Don't even give the impression that we might support 2.1.0.

strike references to 2.1.0

---

python/hail/api2/matrixtable.py

@tpoterba I'm not entirely sure this is the correct thing to do (rather than make it return nothing) because it does still mutate the original dataset. I don't really think anyone will get tripped up by this, but it feels a little silly. What do you think?

make MatrixTable.unpersist return itself

---

python/hail/docs/methods/index.rst
python/hail/methods/__init__.py
python/hail/methods/statgen.py

I couldn't find any tests of `sample_variants` in either the Python or Scala suites, nor could I think of any good tests. But it's such a direct interface to `RDD.sample`, that seems okay to me. I can add tests if anyone has suggestions.

move `sample_variants` to api2 as `sample_rows`

---

src/main/scala/is/hail/distributedmatrix/BlockMatrix.scala
src/main/scala/is/hail/distributedmatrix/RowMatrix.scala
src/main/scala/is/hail/distributedmatrix/RowPartitioner.scala
src/main/scala/is/hail/rvd/OrderedRVPartitioner.scala
src/main/scala/is/hail/sparkextras/OrderedRDD2.scala
src/main/scala/is/hail/utils/BinarySearch.scala
src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala
src/test/scala/is/hail/distributedmatrix/BlockMatrixSuite.scala
src/test/scala/is/hail/distributedmatrix/RowMatrixSuite.scala
src/test/scala/is/hail/distributedmatrix/RowPartitionerSuite.scala
src/test/scala/is/hail/utils/UtilsSuite.scala

Depends on (and includes changes in) #2661
This PR adds:
RowPartitioner and RowPartitionerSuite
RowMatrix.readBlockMatrix and tests in RowMatrixSuite
forceRowMajor parameter to BlockMatrix.write, included in tests
forceRowMajor to richDenseMatrixDouble
Currently I use skipBytes (which reads and throws away) to advance the DataInputStream. @cseed do you have advice on how to use seek instead?

RowMatrix.readBlockMatrix with RowPartitioner

---

python/hail/genetics/interval.py
src/main/scala/is/hail/annotations/Annotation.scala
src/main/scala/is/hail/annotations/RegionValueBuilder.scala
src/main/scala/is/hail/annotations/UnsafeRow.scala
src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/expr/AnnotationImpex.scala
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/expr/HailRep.scala
src/main/scala/is/hail/expr/Parser.scala
src/main/scala/is/hail/expr/types/TInterval.scala
src/main/scala/is/hail/expr/types/TLocus.scala
src/main/scala/is/hail/expr/types/TVariant.scala
src/main/scala/is/hail/io/annotators/BedAnnotator.scala
src/main/scala/is/hail/io/annotators/IntervalList.scala
src/main/scala/is/hail/kryo/HailKryoRegistrator.scala
src/main/scala/is/hail/methods/FilterIntervals.scala
src/main/scala/is/hail/methods/ImputeSexPlink.scala
src/main/scala/is/hail/sparkextras/OrderedRDD.scala
src/main/scala/is/hail/utils/IntervalTree.scala
src/main/scala/is/hail/utils/Py4jUtils.scala
src/main/scala/is/hail/variant/GenomeReference.scala
src/main/scala/is/hail/variant/Locus.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/methods/ExprSuite.scala
src/test/scala/is/hail/methods/LDPruneSuite.scala
src/test/scala/is/hail/variant/GenomeReferenceSuite.scala
src/test/scala/is/hail/variant/IntervalSuite.scala

Previous patches made the interval _type_ generic (e.g. Interval[T] instead of just Interval which implied interval of locus).  This patch makes the intervals themselves generic.  The interval doesn't carry the type (it's just a container for the start, end) so various interval operations need the ordering on the type that the interval is over to be passed in.  Then everything else is follows from this.
The next PR makes the intervals generic on the Python side.
Along the way, I allows intervals to be improper, e.g., [7, 5), which are effectively empty.  Note, intervals compare for equality if the endpoints are equal, so [7, 5) != [8, 5) even though they are both empty.

made interval generic on the JVM side

---

python/hail/api1/dataset.py
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/methods/AnnotateSuite.scala
src/test/scala/is/hail/vds/JoinSuite.scala

renamed fromKeyTable => fromTable.
made generic (single key until we have compound keys in MT)
The two FIXMEs will use infrastructure from other, pending PRs.  To avoid stacking, I'll rebase one side or the other depending on which goes in first.

rv-ified fromTable.

---

src/main/scala/is/hail/methods/PCRelate.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/io/ImportGDBSuite.scala
src/test/scala/is/hail/methods/LDPruneSuite.scala
src/test/scala/is/hail/methods/TableSuite.scala
src/test/scala/is/hail/stats/StatsSuite.scala
src/test/scala/is/hail/utils/RichMatrixTable.scala
src/test/scala/is/hail/variant/vsm/ExplodeSuite.scala
src/test/scala/is/hail/variant/vsm/GroupBySuite.scala
src/test/scala/is/hail/vds/FilterVariantsSuite.scala

Instead of building variant map (which is actually broken because variants are not necessarily unique!)
Move MT.variants to test code.  This eliminates another use of MT.rdd.

Use partitionStarts in PCRelate.

---

src/main/scala/is/hail/utils/richUtils/RichRDD.scala

The type of this RDD is rather complicated because we prepend a String to
an RDD of a universally quantified variable.
`writeTextTable` works with any subtypes of AnyRef because it only requires
that the object defines `toString`. Ergo, we don't actually need to know
anything about the type parameter of the RDD. The explicit annotation
that I've added prevents Scala from inferring a complex type that cannot
be expressed without `forSome`. Such types trigger a warning from the
Scala compiler.

force a broader type, appeasing Scala's type system

---

src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/methods/LinearMixedRegressionSuite.scala
src/test/scala/is/hail/methods/LinearRegressionSuite.scala
src/test/scala/is/hail/methods/LogisticRegressionSuite.scala
src/test/scala/is/hail/stats/BaldingNicholsModelSuite.scala
src/test/scala/is/hail/stats/FisherExactTestSuite.scala
src/test/scala/is/hail/stats/HWESuite.scala
src/test/scala/is/hail/utils/RichMatrixTable.scala
src/test/scala/is/hail/variant/IntervalSuite.scala
src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala

along the way, move rdd-based variantsAndAnnotations to tests code

rv-ify queryVariants

---

src/main/scala/is/hail/methods/LogisticRegression.scala
src/test/scala/is/hail/methods/LogisticRegressionSuite.scala
src/test/scala/is/hail/stats/LogisticRegressionModelSuite.scala

This addresses a user issue whereby adding an indicator covariate that only varied in controls caused Firth to fail. Currently the standard logistic MLE is computed even for Firth regression so this beta can be used to initialize the Firth per-variant models. But if the data has a (quasi-)separated coordinate, the standard MLE may not converge, throwing an error before the Firth models are fit. With the changes in this PR, if the MLE does not converge, Firth falls back to initializing with the intercept-only estimate.

Allow Firth to bypass non-converged MLE

---

python/hail/api1/dataset.py
python/hail/docs/methods/index.rst
python/hail/methods/__init__.py
python/hail/methods/family_methods.py
python/hail/methods/io.py
python/hail/methods/misc.py
python/hail/methods/qc.py
python/hail/methods/statgen.py
python/hail/methods/tests.py
python/hail/utils/testutils.py
src/main/scala/is/hail/methods/IBD.scala
src/main/scala/is/hail/variant/MatrixTable.scala

I think IBD could/should maybe be rewritten to return a MatrixTable instead of a Table (the old format could be extracted pretty easily with `ibd.to_entries_table()`) but I haven't done that here yet.
Tim also suggested that methods where we're extracting a call could conceivably take a `CallExpression` instead of the dataset as the initial argument so we'd have e.g. `ibd(dataset['GT'])`.

port ibd to api2

---

python/hail/dataset.py
src/main/scala/is/hail/io/hadoop/BytesOnlyWritable.scala
src/main/scala/is/hail/utils/ExportType.scala
src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala
src/main/scala/is/hail/utils/richUtils/RichRDD.scala
src/main/scala/is/hail/utils/richUtils/RichRDDByteArray.scala
src/main/scala/is/hail/variant/VariantDataset.scala
src/test/scala/is/hail/io/ExportPlinkSuite.scala
src/test/scala/is/hail/utils/RichRDDSuite.scala

- I ported over the parallel write changes from 0.2 to 0.1. However, I left the interface of parallel being a Boolean where False = concatenate and True = parallel with a header per shard.
- This is a combination of previous PRs: #2265, #2263, #2354, #2587, #2630 
- Addresses #2245 for @maryhaas

Parallel option for export PLINK

---

src/main/scala/is/hail/methods/Nirvana.scala
src/main/scala/is/hail/methods/VEP.scala
src/main/scala/is/hail/variant/MatrixTable.scala

Builds on: https://github.com/hail-is/hail/pull/2711 (genericintervals7)
You probably want to wait until that goes in to review.
@konradjk Unfortunately, we don't have automated tests for VEP yet.  I'm bump the priority on that to make changing VEP safer, but in the mean time, can I ask you to run this on a small example to make sure we didn't break anything?  Thanks!
@jbloom22 Can you do the same for Nirvana?

rv-ified VEP and Nirvana

---

python/hail/api1/dataset.py
python/hail/methods/qc.py
src/main/scala/is/hail/methods/CalculateConcordance.scala
src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/sparkextras/OrderedRDD2.scala
src/test/scala/is/hail/SparkSuite.scala
src/test/scala/is/hail/methods/ConcordanceSuite.scala

I changed the semantics slightly.  Instead of using outerJoinDistinct,
since it really seems like the left and right sides should be treated
symmetrically, I used an "OrderedZipJoin".  This is like a sort and then
zip, except (1) only the same rows with the same key are zipped
together, and (2) if there are different number of rows with a given
key on the left and right, the side with the fewer rows is padding
with null rows.

rv-ified concordance

---

src/main/scala/is/hail/expr/Parser.scala
src/main/scala/is/hail/expr/types/EncodedType.scala
src/main/scala/is/hail/expr/types/PhysicalType.scala

towards next file format
just placeholders, currently unused
In the new file format, (matrix) table should store the encoded type of its rows.
Eventually, an RVD should carry a physical type, not (just) a virtual type.  Operations manipulating region values should go throw PhysicalType, not Type.

added physical, encoded types

---

src/main/scala/is/hail/distributedmatrix/BlockMatrix.scala
src/main/scala/is/hail/distributedmatrix/KeyedBlockMatrix.scala
src/main/scala/is/hail/distributedmatrix/Keys.scala
src/test/scala/is/hail/distributedmatrix/BlockMatrixSuite.scala
src/test/scala/is/hail/distributedmatrix/KeyedBlockMatrixSuite.scala
src/test/scala/is/hail/distributedmatrix/KeysSuite.scala

KeyedBlockMatrix is a BlockMatrix with optional row and column Keys. I chose to make them optional when considering the need to constantly check key agreement. Here if both operands have row keys in a binary operation like add, then the keys are checked for agreement. The result has rowKeys iff at least one operand has rowKeys (and they agree). Similar rules apply to column keys and other operations where sensible. When promoting a BlockMatrix to a KeyedBlockMatrix, the keys are set to None. A BlockMatrix can be promoted to a KeyedBlockMatrix even if it's dimensions exceed Int.MaxValue; the simple rule is that you can't set keys on a dimension that is too large. This is convenient if you have a matrix where one dimension is huge but you still want keys on the other dimension.
Checking …

Add Keys and KeyedBlockMatrix

---

python/hail/api2/matrixtable.py
python/hail/api2/table.py
python/hail/api2/tests.py

Select and transmute can remove uid fields after an implicit join, but cleanup was trying to remove all uids.

fix implicit joins inside select/transmute

---

python/hail/api1/dataset.py
python/hail/api1/tests.py
python/hail/api2/matrixtable.py
python/hail/api2/table.py
python/hail/api2/tests.py
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/variant/vsm/VSMSuite.scala

Fixes https://github.com/hail-is/hail/issues/2802
fixed a bug where a matrix with duplicated row keys would join incorrectly witha table via a computed key (vds_key)
added test for this case
moved the vds_key logic and tests to python in api2
removed vds_key from api1

fixed matrix computed key join bug

---

python/hail/utils/java.py

otherwise some operations (e.g.  creating types) fail

create hc if necesary when requesting jvm or gateway

---

.gitignore

this folder is generated by sbt, so we should ignore it now that we have a `build.sbt`

ignore sbt build folder

---

python/hail/linalg/matrix.py
src/main/scala/is/hail/distributedmatrix/BlockMatrix.scala
src/test/scala/is/hail/distributedmatrix/BlockMatrixSuite.scala

it may be possible to avoid creating a new generator per block, but given that each block samples 16M entries for the default blockSize (which I've changed to 4096 in another PR), I don't think it's a big deal.

seeded random BlockMatrix, uniform / guassian

---

src/main/scala/is/hail/distributedmatrix/BlockMatrix.scala
src/main/scala/is/hail/utils/package.scala
src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala
src/main/scala/is/hail/utils/richUtils/RichRDD.scala
src/test/scala/is/hail/distributedmatrix/BlockMatrixSuite.scala

I've changed BlockMatrix.from(lm: BDM[Double]) so that each executor is transmitted only the blocks it needs (~num_blocks/num_executors) rather than all of them: "[TorrentBroadcast](https://jaceklaskowski.gitbooks.io/mastering-apache-spark/spark-TorrentBroadcast.html) uses a BitTorrent-like protocol for block distribution (that only happens when tasks access broadcast variables on executors)."
In another branch, I've verified on GCP that distributing and then localizing a 10k x 10k matrix is twice as fast (about 15s vs 30s). Distributing and then writing a 25k by 25k matrix (5GB) with 10+2 standard 8-core workers takes about 30s with the new method but fails for every partition with the old method (months ago I believe I sometimes got the old method to work at this scale using high mem. …

improved BlockMatrix.from(lm), added lm.writeBlockMatrix, defaultBlockSize=4096

---

python/hail/linalg/matrix.py
python/hail/methods/tests.py
src/main/scala/is/hail/distributedmatrix/BlockMatrix.scala
src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala
src/test/scala/is/hail/distributedmatrix/BlockMatrixSuite.scala

Added methods to melt a BlockMatrix into a Table with the format: [row index, column index, entry]. Added method to make a Block Matrix from a numpy matrix in python, for testing the melt() method.

Block matrix explode

---

src/main/scala/is/hail/distributedmatrix/LocalMatrix.scala
src/test/scala/is/hail/distributedmatrix/LocalMatrixSuite.scala

Depends on #2848 and #2861, I'll rebase once those are in. LocalMatrix has pointwise +,-,*,% ops with broadcasting, matrix ops, etc. It's meant to mirror NumPy restricted to always having 2 axes (we may eventually want to introduce np.array into the expression language). Vectors are identified with a single column rather than having a separate class.
Once this is in, I'll rename the distributedmatrix package to linalg. Next step is to build Python interface starting with those ops I need to pull over much of LMM pipeline, with testing on the Python side against Numpy.

Numpy-like LocalMatrix

---

python/hail/methods/statgen.py
src/main/scala/is/hail/variant/MatrixTable.scala

Still not the ideal (M as transpose is confusing and we should probably automatically mean-center), but at least the docs are now correct.

Fixed PCA docs and caching

---

python/hail/matrixtable.py
python/hail/table.py
python/hail/tests.py
src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/annotations/UnsafeRow.scala
src/main/scala/is/hail/io/RowStore.scala
src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/rvd/RVD.scala
src/main/scala/is/hail/rvd/UnpartitionedRVD.scala
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/annotations/AnnotationsSuite.scala
src/test/scala/is/hail/annotations/UnsafeSuite.scala
src/test/scala/is/hail/variant/vsm/VSMSuite.scala

- made decoder stuff modular/composable
- CodecSpec, stored in RVDSpec (and hence in metadata) describes the en/decoding process
- exposed to Python (private parameter in MT and Table.write)

parameterize en/decoder

---

python/hail/docs/methods/index.rst
python/hail/docs/methods/misc.rst
python/hail/methods/__init__.py
python/hail/methods/statgen.py

@tpoterba any reason not to remove this?
We already have sample_rows on MatrixTable and sample of Table.

remove sample_rows from methods/misc

---

python/hail/expr/functions.py
python/hail/expr/tests.py

Will remove x.min(y) in a followup PR.

Extend min/max functions.

---

python/hail/methods/tests.py

I think the syntax change is needed because numpy versions older than 1.12 don't let you filter a numpy array on a boolean mask in this way.

fix rrm test

---

src/main/scala/is/hail/io/RowStore.scala
src/main/scala/is/hail/linalg/BlockMatrix.scala
src/main/scala/is/hail/linalg/LocalMatrix.scala
src/main/scala/is/hail/linalg/RowMatrix.scala
src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala
src/test/scala/is/hail/linalg/BlockMatrixSuite.scala

I also added skipBytes for use with RowMatrix.readBlockMatrix
@cseed I still need to experiment on compression w.r.t. banded LD project, which should inform the choice of BDM BufferSpec further, but using the general infrastructure is clearly better than the one-off BDM buffers I'd written before. Is it reasonable to merge this to master (post review)?

DenseMatrix I/O moved to blocking buffer

---

python/hail/environment.yml

NB: we cannot use python 3.6 because ipython-notebook hasn't been updated yet.

update conda env for python 3

---

python/hail/docs/tutorials/hail-overview.ipynb
python/hail/expr/expression.py
python/hail/table.py
src/main/scala/is/hail/methods/PCRelate.scala
src/main/scala/is/hail/table/Table.scala
src/test/scala/is/hail/methods/AggregatorSuite.scala
src/test/scala/is/hail/methods/AnnotateGlobalSuite.scala
src/test/scala/is/hail/variant/vsm/VSMSuite.scala

Use Table.aggregate in Expression.collect since it is much faster
(doesn't convert row and unneeded keys to python)

use new Expression.show, collect, etc. in tutorial

---

python/hail/docs/expr/types.rst
python/hail/environment.yml
python/hail/expr/__init__.py
python/hail/expr/expression.py
python/hail/expr/functions.py
python/hail/expr/tests.py
python/hail/expr/type_parsing.py
python/hail/expr/types.py
python/hail/matrixtable.py
python/hail/table.py
python/hail/tests.py
python/hail/typecheck/check.py
python/hail/utils/java.py
src/main/scala/is/hail/expr/types/TArray.scala
src/main/scala/is/hail/expr/types/TBoolean.scala
src/main/scala/is/hail/expr/types/TCall.scala
src/main/scala/is/hail/expr/types/TDict.scala
src/main/scala/is/hail/expr/types/TFloat32.scala
src/main/scala/is/hail/expr/types/TFloat64.scala
src/main/scala/is/hail/expr/types/TInt32.scala
src/main/scala/is/hail/expr/types/TInt64.scala
src/main/scala/is/hail/expr/types/TInterval.scala
src/main/scala/is/hail/expr/types/TLocus.scala
src/main/scala/is/hail/expr/types/TSet.scala
src/main/scala/is/hail/expr/types/TString.scala
src/main/scala/is/hail/expr/types/TStruct.scala
src/main/scala/is/hail/expr/types/TTuple.scala
src/main/scala/is/hail/expr/types/Type.scala
src/main/scala/is/hail/table/Table.scala

to the Type._from_java hotspot and the typecheck inspect hotspot.

Add Python type parser. Speed up Python API by ~3x with optimizations

---

python/hail/context.py
python/hail/expr/functions.py
python/hail/expr/types.py
python/hail/genetics/genomeref.py
python/hail/genetics/interval.py
python/hail/genetics/locus.py
python/hail/methods/impex.py
python/hail/methods/statgen.py
python/hail/methods/tests.py
python/hail/typecheck/check.py
src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/expr/types/TLocus.scala
src/main/scala/is/hail/io/annotators/BedAnnotator.scala
src/main/scala/is/hail/io/annotators/IntervalList.scala
src/main/scala/is/hail/io/bgen/BgenBlockReader.scala
src/main/scala/is/hail/io/bgen/BgenRecord.scala
src/main/scala/is/hail/io/bgen/LoadBgen.scala
src/main/scala/is/hail/io/gen/LoadGen.scala
src/main/scala/is/hail/io/plink/LoadPlink.scala
src/main/scala/is/hail/io/vcf/LoadGDB.scala
src/main/scala/is/hail/io/vcf/LoadVCF.scala
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/utils/TextTableReader.scala
src/main/scala/is/hail/variant/GenomeReference.scala
src/main/scala/is/hail/variant/Locus.scala
src/test/scala/is/hail/io/ExportVCFSuite.scala
src/test/scala/is/hail/io/ImportPlinkSuite.scala
src/test/scala/is/hail/io/ImportVCFSuite.scala
src/test/scala/is/hail/methods/LinearMixedRegressionSuite.scala

Previous behavior:
- `None` = default reference
Now:
- `default` = default reference
For import methods, `None` means don't convert to Locus(reference) and instead return a Struct with ["contig": String, "position": Int]. `None` is not valid for constructors, TLocus, and balding nichols.

fix import docs and change how reference is handled

---

python/hail/methods/misc.py
python/hail/methods/tests.py
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/utils/BinaryHeap.scala
src/main/scala/is/hail/utils/Graph.scala
src/test/scala/is/hail/methods/TableSuite.scala
src/test/scala/is/hail/utils/GraphSuite.scala

to accept a table of vertices and return a filtered table.
* changed BinaryHeap's tiebreaker function to return
a Long, which matches data type of indices returned by
Table.index()
* added selectGlobal method to Table which takes String*

* changed signature of maximal_independent_set method

---

python/hail/docs/conf.py
python/hail/docs/doctest_setup.py
python/hail/docs/methods/genetics.rst
python/hail/docs/methods/index.rst
python/hail/environment.yml
python/hail/matrixtable.py
python/hail/methods/impex.py
python/hail/methods/misc.py
python/hail/methods/statgen.py
python/hail/utils/misc.py

I also reordered FilterAlleles and SplitMulti because in emacs `sort-lines` sorts using ASCII character index, so `A` comes after `_`. I think this will be an easier ordering to maintain, because it's the default ASCII ordering the most tools will use.

add missing docs for ld_prune and impute_sex

---

src/main/scala/is/hail/utils/IntervalTree.scala

No need to compare upper bound if position is below lower bound. And `compareStart == 0` is more likely to short circuit `includeStart` than the other way around.

proposed improvement to Interval.contains 

---

python/hail/methods/impex.py
python/hail/methods/qc.py
src/main/scala/is/hail/methods/VEP.scala

Other methods are already checked with require_biallelic which calls require_variant.

Require variant for export vcf, nirvana, vep

---

python/hail/matrixtable.py
python/hail/tests.py
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/variant/vsm/GroupBySuite.scala

the other way was clearly backwards

MT.count returns (n_rows, n_cols)

---

python/hail/matrixtable.py
python/hail/methods/tests.py
python/hail/table.py
python/hail/tests.py

so we don't confuse column of table and column of matrixtable.

rename column => field everywhere in Table

---

src/main/scala/is/hail/linalg/LocalMatrix.scala
src/test/scala/is/hail/linalg/LocalMatrixSuite.scala

I made these updates to Scala LocalMatrix as I was building the Python interface, to more closely mirror NumPy functions and name the symbolic operators. I no longer intend to expose LocalMatrix in Python in its current form, but rather to localize BlockMatrix "directly" to NumPy and vice versa. Still, LocalMatrix in Scala is a useful local model for how I'll update BlockMatrix to be more NumPy like (e.g. broadcasting), and a step toward building a region-value based ndarray. I think these are good changes, isolated to LocalMatrix, so my preference is to merge them in now.

updates to LocalMatrix

---

build.gradle
python/hail/tests/test_typecheck2.py
python/hail/typecheck2/__init__.py
python/hail/typecheck2/check.py

(This wasn't a random assignment, so feel free to remove yourself and I'll assign someone else)
I've implemented a type checker that uses type annotations and a minor amount of frame hacking to check type signatures.
The register_conversion mechanic can be used to do the following:
```
register_conversion(Int32Expression, Int64Expression)
```
and so on. I'm leaning towards that rather than fully documenting an Int64ExpressionType which is `Union[Int32ExpressionType, Int64Expression]` where `Int32ExpressionType = Union[int, Int32Expression]`.
Happy to do either, though!

Typecheck2 : The Types Strike Back

---

python/hail/expr/expressions/base_expression.py
python/hail/tests/test_api.py

of the entire MatrixTable if the field is a row key.

Resolves a performance problem with _to_table that caused a re-scan

---

src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/utils/ArrayBuilder.scala

rounding could cause last partition to be mis-sized
also, normalize values before shuffle

fixed calculate ranges

---

python/hail/methods/impex.py
src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/rvd/OrderedRVDPartitioner.scala
src/main/scala/is/hail/utils/ArrayBuilder.scala

This builds on: https://github.com/hail-is/hail/pull/3107
We were getting absolutely murdered by serializing the partitioner on every task.  I made OrderedRVDPartitioner not inherit from Spark Partitioner, non-serializable, and modified it to be broadcasted where needed.
There is a good chance this will speed up OrderedRVD shuffles as well, but I haven't timed.
Timing:
```
mt = hl.read_matrix_table('gnomad.exomes.vds', _drop_cols=True)
mt = mt._filter_partitions(list(range(1000)))
mt._force_count_rows()
```
master: 1m15s
no_ser_ord_part: 9s
That's about 8x improvement.  This includes startup time so it's actually much better.

Make OrderedRVDPartitioner non-serializable

---

src/main/scala/is/hail/linalg/GridPartitioner.scala
src/test/scala/is/hail/linalg/GridPartitionerSuite.scala

I'm keeping my LD extension branch separate until we add a proper sparse block matrix implementation, but I pulled out these functions on GridPartitioner since (i) they're some of the logic we'll need to make sparse block matrix useful and (ii) Meredith just built a step to compute variant windows in LDPrune, which can then be combined with this logic as part of her optimization strategy to not compute unneeded blocks.

GridPartitioner functions for overlapping blocks

---

src/main/scala/is/hail/linalg/BlockMatrix.scala
src/main/scala/is/hail/methods/PCRelate.scala
src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala
src/test/scala/is/hail/linalg/BlockMatrixSuite.scala

Also changed `assertCompatibleLocalMatrix` to used `isCompact`, which is the intended condition. The current one doesn't rule out extra trailing values in data.

changed blockMap2 from join to zipPartitions

---

python/hail/expr/aggregators.py
python/hail/expr/expressions/base_expression.py
python/hail/expr/expressions/expression_typecheck.py
python/hail/expr/expressions/typed_expressions.py
python/hail/expr/functions.py
python/hail/expr/types.py
python/hail/tests/test_api.py
src/main/scala/is/hail/expr/Fun.scala
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/expr/Parser.scala
src/test/scala/is/hail/expr/AstToIrSuite.scala
src/test/scala/is/hail/io/ExportVCFSuite.scala
src/test/scala/is/hail/methods/AggregatorSuite.scala
src/test/scala/is/hail/methods/AnnotateGlobalSuite.scala
src/test/scala/is/hail/methods/ExprSuite.scala
src/test/scala/is/hail/methods/FilterSuite.scala
src/test/scala/is/hail/methods/LinearMixedRegressionSuite.scala
src/test/scala/is/hail/methods/LinearRegressionSuite.scala
src/test/scala/is/hail/methods/PCASuite.scala
src/test/scala/is/hail/methods/SkatSuite.scala
src/test/scala/is/hail/methods/TableSuite.scala
src/test/scala/is/hail/stats/FisherExactTestSuite.scala
src/test/scala/is/hail/stats/InbreedingCoefficientSuite.scala
src/test/scala/is/hail/variant/vsm/GroupBySuite.scala
src/test/scala/is/hail/variant/vsm/VSMSuite.scala

Remove conversions from the function registry.  They are now inserted by Python and explicit in the expression language.
This should simplify lots of stuff on the back end.

moved numeric conversions to python

---

python/hail/methods/statgen.py
src/main/scala/is/hail/expr/ir/Emit.scala
src/main/scala/is/hail/expr/ir/SpecializedArrayBuilders.scala

GQ as expr means adding it on after the splitmulti calculation as an annotate_entries which still goes through the AST.
```
profile.vcf.bgz
non-deforested, gq inline: ~50s
non-deforested, gq as expr: ~45s
deforested, gq as expr: ~36s
deforested, gq inline: ~26s
```

deforest filter, map, range, arrayfold

---

src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/expr/ir/BinaryOp.scala

Wasn't short circuiting properly as written. Caused this test to fail:
`self.assertEqual(hl.cond(hl.null(hl.tbool), 1, 2, missing_false=True).value, 2)`

Removed DoubleAmpersand and DoublePipe IRs

---

src/main/scala/is/hail/linalg/BlockMatrix.scala
src/test/scala/is/hail/linalg/BlockMatrixSuite.scala

Breeze diag only works on square matrices, whereas BlockMatrix diagonal was written for arbitrary matrices, consistent with NumPy. Update avoids Breeze diag, tests non-square matrix with multiple blocks, and deletes shortened operator `diag` as unnecessary.

Fix BlockMatrix diagonal bug on non-square matrices

---

src/main/scala/is/hail/io/RowStore.scala
src/main/scala/is/hail/rvd/RVD.scala

DirectEncoder is not currently used and will not work
with the forthcoming off-heap Region PR.

remove direct encoder

---

python/hail/expr/expressions/base_expression.py
python/hail/expr/expressions/indices.py
python/hail/expr/expressions/typed_expressions.py
python/hail/expr/functions.py
python/hail/matrixtable.py
python/hail/table.py
python/hail/tests/test_api.py
python/hail/tests/test_expr.py
src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/expr/Parser.scala
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/expr/types/TStruct.scala
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/expr/TableIRSuite.scala
src/test/scala/is/hail/expr/ir/CompileSuite.scala
src/test/scala/is/hail/io/ImportPlinkSuite.scala
src/test/scala/is/hail/methods/ExportSuite.scala
src/test/scala/is/hail/methods/SelectSuite.scala
src/test/scala/is/hail/methods/TableSuite.scala
src/test/scala/is/hail/testUtils/RichTable.scala
src/test/scala/is/hail/variant/vsm/GroupBySuite.scala
src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala
src/test/scala/is/hail/variant/vsm/VSMSuite.scala

- TableMapRows IR (takes a Struct IR as an argument)
- Removed TableAnnotate
- select can output an IR
- Rewrote annotate and rename in Python to utilize select
- Removed annotate, rename, and drop from the Scala Table interface
- Moved annotate and rename to RichTable for Scala tests
- added some additional python tests

Table select/annotate/rename/drop changes

---

python/hail/tests/utils.py
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/expr/ir/Compile.scala
src/main/scala/is/hail/expr/ir/Infer.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/io/ExportVCFSuite.scala

I'm going to merge select/drop/annotate on the scala side in a separate PR. For now annotateEntriesExpr uses the IR path if possible for testing.

MapEntries IR; use in annotate.

---

src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/expr/ir/Children.scala
src/main/scala/is/hail/expr/ir/Copy.scala
src/main/scala/is/hail/expr/ir/Emit.scala
src/main/scala/is/hail/expr/ir/IR.scala
src/main/scala/is/hail/expr/ir/Infer.scala
src/main/scala/is/hail/expr/ir/Recur.scala
src/main/scala/is/hail/expr/ir/functions/Functions.scala
src/test/scala/is/hail/expr/ir/CompileSuite.scala
src/test/scala/is/hail/expr/ir/FunctionSuite.scala

cc @cseed @danking 
I changed the `ApplyFunction` IR to store the function name instead of the IRFunction implementation. (The implementation gets looked up during Infer if it doesn't already exist, but we're always pre-populating it in IRFunctionRegistry.lookupConversion).
As part of this, I separated the way that `IRFunctionRegistry` stores IR => IR from the IRFunction lookup, since the lookup in Infer wants to grab the IRFunction and not necessarily the entire `Apply` IR that we currently store. Maybe the IR => IR aspect (handled by `IRFunction.lookupConversion`) could go away once we no longer need the AST to IR conversion and start constructing the IR directly in python.

IRFunctionRegistry changes

---

python/hail/methods/statgen.py
src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/stats/BaldingNicholsModel.scala
src/test/scala/is/hail/stats/BaldingNicholsModelSuite.scala

A simple but powerful extension requested by @alexb-3 and Christina to allow for synthetic genotypes with very general and realistic-looking PCA plots with [redacted]. Alex pointed out that BaldingNichols is special case of PritchardStephensDonnelly in a degenerate sense, just as one-hot encoded `Categorical(p_1,...,p_k)` is the distributional limit of `Dirichlet(a * p_1,..., a * p_k)` as `a` goes to 0. So the substantive changes took about 10 lines.
It's turned on by the `mixture` parameter which defaults to False and is marked as experimental. `True` means treat `pop_dist` as the parameters of Dirichlet rather than Categorical. @alexb-3 , it'd be great if you and Christina could experiment with it and extend the documentation accordingly. Once we have that, I'll add tests and remove …

generalize BaldingNichols to PritchardStephensDonnally

---

src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala

this moves the struct-level annotate that's in the AST (which calls `tstruct1.annotate(tstruct2)`) This will allow the python struct-level annotate operation to pass through the IR when able.

move annotate(struct1, struct2) to IR

---

src/main/scala/is/hail/linalg/BlockMatrix.scala

@konradjk is getting bogged down by the single-core implementation of BlockMatrix diagonal. This implementation pulls out the diagonal of each diagonal block in parallel, and then collects and flattens the result.

parallelize BlockMatrix diagonal

---

src/main/scala/is/hail/linalg/BlockMatrix.scala
src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/sparkextras/RepartitionedOrderedRDD.scala
src/main/scala/is/hail/sparkextras/RepartitionedOrderedRDD2.scala
src/main/scala/is/hail/variant/MatrixTable.scala

Basically just exploded the RepartitionedOrderedRDD2 interface so that the individual (serializable) parts could be passed in separately. 
The next step is to make the partitioner unserializable, so I'll change this again when I do that to broadcast the partitioner where needed.

remove Serializable from OrderedRVD

---

src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/io/LoadMatrix.scala
src/main/scala/is/hail/io/bgen/LoadBgen.scala
src/main/scala/is/hail/io/plink/LoadPlink.scala
src/main/scala/is/hail/io/vcf/LoadGDB.scala
src/main/scala/is/hail/io/vcf/LoadVCF.scala
src/main/scala/is/hail/methods/FilterAlleles.scala
src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/rvd/OrderedRVDType.scala
src/main/scala/is/hail/rvd/RVD.scala
src/main/scala/is/hail/stats/BaldingNicholsModel.scala
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/variant/MatrixTable.scala

This change anticipates the ContextRDD change wherein `RVD.rdd` will not
be an RDD. Moreover, enforcing an abstraction barrier at the level of
`RVD` will ease changes to the implementation of `RVD`.
There are two remaining types of calls that I cannot eliminate:
- uses in BlockMatrix and OrderedRDD2: these two classes are building
new RDDs based on the RVD's rdd, these classes should be considered
within the implementation of the RVD abstraction. Because these two
classes are outside of `is.hail.rvd`, I cannot enforce an access
modifier on `RVD.rdd`.
- uses by methods:
- LDPrune: it seems we need a "GeneralRVD"
- Skat: it seems like some of this could be moved to python actually;
but there is some matrix math that cannot be moved until the expr
lang has efficient small-matrix ops
- …

Eliminate some but not all uses of RVD.rdd

---

src/main/scala/is/hail/expr/ir/Children.scala
src/main/scala/is/hail/expr/ir/Copy.scala
src/main/scala/is/hail/expr/ir/Emit.scala
src/main/scala/is/hail/expr/ir/ExtractAggregators.scala
src/main/scala/is/hail/expr/ir/IR.scala
src/main/scala/is/hail/expr/ir/Infer.scala
src/main/scala/is/hail/expr/ir/Recur.scala
src/main/scala/is/hail/expr/ir/functions/Functions.scala
src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala
src/main/scala/is/hail/table/Table.scala
src/test/scala/is/hail/expr/ir/CompileSuite.scala

This allows us to write functions for the IR that handle missingness specially, in cases where we don't necessarily want the behavior where any missing argument implies that the entire function result is considered missing. I implemented `&&` and `||` using this in order to test.
I also refactored the return from Emit.emit to a case class `EmitTriplet` to make it easier to talk about them in other contexts.
cc @cseed @danking

add ApplySpecial to handle IRFunctions with missingness treatment

---

src/main/scala/is/hail/io/RowStore.scala
src/main/scala/is/hail/linalg/BlockMatrix.scala
src/main/scala/is/hail/linalg/RowMatrix.scala
src/main/scala/is/hail/utils/package.scala
src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala
src/main/scala/is/hail/utils/richUtils/RichRDD.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/linalg/BlockMatrixSuite.scala

I think it is possible for two partitions, either through speculation or a network partition between the master and a worker, to try to write the same file.  This leads to Bad Problems(tm).  In this change, each write task attempt creates a unique part file path name (part-NNN-taskID-partitionID-attemptNumber-UUID) and writes that.  These path files (collected from the successful tasks) are collected and stored in the relevant metadata.
Note, this is a breaking change for the matrix file format which should be OK since it is marked as experimental.

Unique part files

---

python/hail/matrixtable.py
python/hail/methods/qc.py
python/hail/table.py
src/main/scala/is/hail/methods/Nirvana.scala
src/main/scala/is/hail/methods/VEP.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/io/ExportVCFSuite.scala
src/test/scala/is/hail/io/ImportBgenSuite.scala
src/test/scala/is/hail/io/ImportMatrixSuite.scala
src/test/scala/is/hail/methods/AggregatorSuite.scala
src/test/scala/is/hail/methods/AnnotateSuite.scala
src/test/scala/is/hail/methods/ConcordanceSuite.scala
src/test/scala/is/hail/methods/LinearRegressionSuite.scala
src/test/scala/is/hail/methods/PCASuite.scala
src/test/scala/is/hail/methods/SelectSuite.scala
src/test/scala/is/hail/methods/SkatSuite.scala
src/test/scala/is/hail/stats/FisherExactTestSuite.scala
src/test/scala/is/hail/stats/HWESuite.scala
src/test/scala/is/hail/stats/InfoScoreSuite.scala
src/test/scala/is/hail/utils/RichMatrixTable.scala
src/test/scala/is/hail/variant/LocusIntervalSuite.scala
src/test/scala/is/hail/variant/ReferenceGenomeSuite.scala
src/test/scala/is/hail/variant/vsm/ExplodeSuite.scala
src/test/scala/is/hail/variant/vsm/GroupBySuite.scala
src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala
src/test/scala/is/hail/variant/vsm/VSMSuite.scala

- annotateRowsExpr and dropRows(**exprs) have been removed from the Scala interface (annotateRowsExpr has been moved to testUtils)
- annotate_rows and drop_rows are rewritten in terms of select_rows in Python (following Table.select and MatrixTable.select_entries).

rewrite annotate_rows in terms of select_rows

---

src/main/scala/is/hail/expr/ir/functions/Functions.scala

use MultiMap instead of `Map[String, Seq[]]` and pull out duplicate code between `lookupFunction` and `lookupConversion`.

clean up IR function registry code

---

python/hail/tests/test_api.py
src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/rvd/OrderedRVDPartitioner.scala
src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala

Where None denotes a partitioner for an empty RVD.
Fixes #3244.
cc @patrick-schultz do you think this is ok?

ORVDPartitioner.range -> Option[Interval]

---

src/main/scala/is/hail/expr/types/TBaseStruct.scala
src/main/scala/is/hail/expr/types/TContainer.scala
src/main/scala/is/hail/expr/types/Type.scala
src/main/scala/is/hail/rvd/OrderedRVDType.scala

@maccum ran into a problem where a join was failing because the two tables had different requiredness in their key fields. This should resolve the problem, by adding an overload `Type.unsafeOrdering` which takes a `rightType: Type`, requiring that `this isOfType rightType`, but allowing them to have different requiredness.

Fix unsafe ordering

---

src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/rvd/RVD.scala
src/main/scala/is/hail/rvd/RVDContext.scala
src/main/scala/is/hail/rvd/UnpartitionedRVD.scala
src/main/scala/is/hail/rvd/package.scala
src/main/scala/is/hail/sparkextras/ContextRDD.scala
src/main/scala/is/hail/sparkextras/RepartitionedOrderedRDD.scala
src/main/scala/is/hail/utils/Pointed.scala
src/main/scala/is/hail/utils/package.scala

cc: @cseed, @patrick-schultz, @catoverdrive 
A `ContextRDD[C, T]` is an `RDD[C => Iterator[T]]` and captures the idea that a computation needs a context. I did not inherit from RDD so that `map` and friends can be implemented as if this was an `RDD[T]`. To access the context, one uses `cmap` and friends.
The lifetime of a context corresponds roughly to the dynamic extent of an `RDD` computation happening on a single worker node. In particular, a context always ends before a `shuffle` or other network communication happens. One may explicitly end a `ContextRDD`'s context lifetime by calling `ContextRDD.run` which produces an `RDD[T]`.
Generally the partitions of a `ContextRDD[C, T]` need only contain one element, but (I believe) I have written `ContextRDD[C, T]` to also handle many `C => …

ContextRDD and its Basic Usage in RVD

---

python/hail/methods/impex.py

"Import a UCSC .bed file as a key table" is currently cut off at .:
https://hail.is/docs/devel/methods/impex.html
And BED is more consistent anyway.

UCSC bed doc fix2

---

python/hail/docs/functions/genetics.rst
python/hail/docs/functions/index.rst
python/hail/expr/__init__.py
python/hail/expr/expressions/typed_expressions.py
python/hail/expr/functions.py
python/hail/tests/test_expr.py
python/hail/tests/test_genetics.py
src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/expr/Parser.scala
src/main/scala/is/hail/variant/ReferenceGenome.scala

I thought these functions would be generally useful and I need them for a future PR reimplementing `import_bed` and `import_locus_intervals` in Python.

Add expr functions testing contigs/loci/intervals are valid for a RG

---

python/hail/matrixtable.py
python/hail/table.py

We mention interop with Spark SQL/ML on the homepage, which is pretty cool but obscure in the docs, so I've added a sentence at the top of Table doc.

Small doc update, mention spark ml in Table.

---

python/hail/docs/tutorials/01-genome-wide-association-study.ipynb
python/hail/methods/statgen.py
python/hail/tests/test_methods.py
src/main/scala/is/hail/methods/LinearRegression.scala
src/main/scala/is/hail/variant/MatrixTable.scala

- changed behavior of `linear_regression` to parallel that of the other stats method when an expression is passed for `y`. When `y` is a list of expressions (even a list of one expression), the the five phenotype-dependent annotations are still array of float64.
- expanded `test_linreg` to test that all the interfaces work as expected
- changed `n_complete_samples` to just `n` since we may introduce an option to subset rather than impute per variant (which would cause n to change per variant) and I don't want to overload the notion of complete_sample to depend on the mode. I also think `n` is clear in linear regression context as the number of data points used, and in any case it's documented as the number of columns used.
- fixed a bug whereby `sum_x` was still `AC` on the Scala side.

linear_regression ys => y, return scalar annotations when y is not list

---

src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/rvd/UnpartitionedRVD.scala
src/main/scala/is/hail/sparkextras/ContextPairRDDFunctions.scala
src/main/scala/is/hail/sparkextras/ContextRDD.scala
src/main/scala/is/hail/utils/richUtils/Implicits.scala

cc: @cseed
Adds coalesce and shuffle. They're not particularly interesting. I just implemented them in terms of the underlying RDD. They use `run` which demarcates the end of a memory-lifetime. The end of a memory-lifetime means, if regions were off-heap, I could free the region. When RegionValues become non-serializable, I'll have to come back here and add serialize/deserialize steps. I'll probably do that at the RVD level (since that's where serialization and deserialization are meaningful concepts).

Context rdd coalesce and shuffle

---

python/hail/table.py
src/main/scala/is/hail/annotations/Annotation.scala
src/main/scala/is/hail/annotations/UnsafeRow.scala
src/main/scala/is/hail/expr/AnnotationImpex.scala
src/main/scala/is/hail/rvd/RVD.scala
src/main/scala/is/hail/table/Table.scala
src/test/scala/is/hail/methods/ExprSuite.scala
src/test/scala/is/hail/methods/TableSuite.scala

removed AnnotationImpex
removed some dead code from SparkAnnotationImpex
Table.toDF now requires expandTypes to have been run (will fail with match error in SparkAnnotationImpex.exportType)
Handle tuple in Spark conversion (convert to struct)

use rvd in expandTypes

---

src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
src/main/scala/is/hail/asm4s/Code.scala
src/main/scala/is/hail/asm4s/FunctionBuilder.scala
src/main/scala/is/hail/asm4s/StagedBitSet.scala
src/main/scala/is/hail/expr/ir/Emit.scala
src/main/scala/is/hail/expr/ir/IR.scala
src/main/scala/is/hail/expr/ir/SpecializedArrayBuilders.scala
src/main/scala/is/hail/expr/ir/package.scala
src/test/scala/is/hail/asm4s/ASM4SSuite.scala
src/test/scala/is/hail/asm4s/StagedBitSetSuite.scala
src/test/scala/is/hail/expr/ir/CompileSuite.scala

fyi @cseed 
All of the auxilliary methods have the same arguments as the original emitted function, to preserve the behavior of In and aggregator stuff without change.
Any IR that binds a new environment variable (`Let`, `Map`, etc.) now stores those values on a class field so that other methods don't have to worry about whether or not there exist such values in scope.
That's basically the only change I made to the structure of Emit; `MakeArray`, `MakeStruct`, and `MakeTuple` now check how big their fields/elements are. I'm a little worried we'll start hitting the class size limit; turning up one of the tests really far already hits it.

wrap more things in their own methods to get around function size limits

---

src/main/scala/is/hail/annotations/Region.scala
src/main/scala/is/hail/rvd/RVDContext.scala
src/main/scala/is/hail/sparkextras/ResettableContext.scala

also add rvb to rvdcontext and give it children
Eventually `close` on `Region` will free off heap memory. For now, it does nothing.

ResettableContext

---

python/hail/expr/types.py
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/expr/ir/Compile.scala
src/main/scala/is/hail/expr/ir/Interpret.scala
src/main/scala/is/hail/expr/ir/Optimize.scala
src/main/scala/is/hail/expr/ir/RewriteBottomUp.scala
src/main/scala/is/hail/expr/ir/RewriteTopDown.scala
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/variant/MatrixTable.scala

Mostly code reorg.  Also:
moved rewriters to ir objects
call Optimize before intepreting
removed Filter{Rows, Cols} rules (non-IR), those should get folded back into the MT methods like other AST-based rules
re-enabled Fitler{Rows, Cols}IR fusion rules since logical and/or is back

Added ir.Optimize

---

python/hail/tests/test_methods.py
src/main/scala/is/hail/annotations/aggregators/RegionValueAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueCountAggregator.scala
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/expr/ir/AggOp.scala
src/main/scala/is/hail/expr/ir/Emit.scala
src/main/scala/is/hail/expr/ir/functions/Functions.scala
src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala
src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
src/main/scala/is/hail/expr/ir/package.scala
src/main/scala/is/hail/methods/LinearMixedRegression.scala
src/main/scala/is/hail/stats/LogisticRegressionModel.scala
src/main/scala/is/hail/stats/package.scala
src/test/scala/is/hail/methods/LinearMixedRegressionSuite.scala
src/test/scala/is/hail/stats/StatsSuite.scala

swapped the (inverse) chi squared tail paramters to match the order in the function registry
added ir.genUID to generate unique IDs.  There are other places it should probably be used.  In the long term, we should just use Longs instead of strings, but keep strings for informational purposes.

added some more stuff to the function registry

---

src/main/scala/is/hail/annotations/Annotation.scala
src/main/scala/is/hail/annotations/UnsafeRow.scala

RegionValue and Region are going off-heap, so where we use `Annotation` we will need to start using something not based on `Region`s.
This PR is just for the implementation. A follow up PR will spread it throughout the code-base wherever we need GC'd `Annotation`. My hope is that this is quite limited. For over-the-network communication, we should use the `is.hail.io` `RowStore.scala` stuff. If the memory-lifetime of the object is known, we can use a region that is explicitly `close`d.
cc: @cseed

Safe, On-Heap Annotations

---

src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/io/RowStore.scala
src/main/scala/is/hail/methods/LDPrune.scala
src/main/scala/is/hail/methods/SampleQC.scala
src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/rvd/RVD.scala
src/main/scala/is/hail/rvd/UnpartitionedRVD.scala
src/main/scala/is/hail/sparkextras/ContextRDD.scala
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/utils/richUtils/Implicits.scala
src/main/scala/is/hail/utils/richUtils/RichContextRDD.scala
src/main/scala/is/hail/utils/richUtils/RichRDD.scala
src/main/scala/is/hail/variant/MatrixTable.scala

An unfortunately large set of changes to enable `writeRows` on a `ContextRDD`.
I took the chance to do a wee bit of refactoring between the write methods of `UnpartitionedRVD` and `OrderedRVD`.

ContextRDD Write Rows

---

src/main/scala/is/hail/annotations/Region.scala

Long term goal is for all allocations of `Region` to come through either `RVDContext` or `Region.scoped`. Forthcoming PRs will start making this conversion.

Add Region.scoped

---

src/main/scala/is/hail/rvd/RVDContext.scala

This isn't used and doesn't work right now. Perhaps we will bring it back in the future when we find a need for it.

Remove ContextRDD.partitionRegion

---

python/hail/matrixtable.py
python/hail/table.py
python/hail/tests/test_methods.py
src/main/scala/is/hail/expr/types/TBaseStruct.scala
src/main/scala/is/hail/expr/types/TDict.scala
src/main/scala/is/hail/expr/types/TFloat32.scala
src/main/scala/is/hail/expr/types/TFloat64.scala
src/main/scala/is/hail/expr/types/TIterable.scala
src/main/scala/is/hail/expr/types/Type.scala
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/io/ImportBgenSuite.scala

Current behavior is it's testing both D_== and abs(d1 -d2) <= tolerance. Now `absolute=True` specifies use `abs(d1-d2)`. Behavior used to be D_== for everything until I changed it for the BGEN test. So `absolute=True` should only be in the BGEN tests.

Improve valuesSimilar for _same

---

src/main/scala/is/hail/sparkextras/ContextPairRDDFunctions.scala
src/main/scala/is/hail/sparkextras/ContextRDD.scala

Added:
- `textFilesLines` to go directly form array of file names to ContextRDD of strings
- `parallelize` with an `Option[Int]` (in addition to an overloaded version with an int parameter having a default value)
- moved `run` to the top since it's super important
- eliminated two useless methods
- colocated `zipPartitions` with other zip-like methods
- added some `*AndContext*` methods that let the API user decide what context to give to the producer of values
The AndContext methods are useful for these two situations:
- One input value becomes multiple output values. We want to clear the input region separately from clearing the output region.
- A zipPartitions / join where there are two inputs, we might want to use the same region for both inputs, but use a new region for the output. …

ContextRDD Changes for forthcoming things

---

src/main/scala/is/hail/rvd/RVD.scala

I also included a little change to use `Region.scoped` for writing a local `IndexedSeq[Annotation]`. In general, we cannot move Region off-heap until all the allocations of Regions are matched with `Region.close()`.
We don't use the context's region yet in the persist. I'll introduce that in a later pull request. This just avoids serializing regions and region values, which will soon become off-heap, non-serializable values.

Use Encoder/Decoder in RVD.persist

---

src/test/scala/is/hail/methods/LDPruneSuite.scala

With 1 core on my local computer, it went from 49.832s to 10.254s with this change. I removed the random test (count=10) of pruning `sample.vcf` with random partition numbers, window size, and r2 threshold. This is replaced with one test with default parameters (R^2 = 0.2, window size = 1MB). I also moved the vcf import as a class value so it wasn't being reimported for each test.

Improve LDPruneSuite timing

---

src/main/scala/is/hail/expr/Relational.scala

When regions are off-heap, we can allow the globals to live in a separate, longer-lived Region that is not cleared until the whole partition is finished. For now, we pay the memory cost.
cc: @cseed

Remove direct Region allocation from FilterColsIR

---

src/main/scala/is/hail/io/RowStore.scala

Only fast-path required arrays (e.g. in AD, PL).  Gives minor (7%) decode speedup on a shard of gnomad (51.5s => 47.5s):
```
mt = hl.read_matrix_table('gnomad.mt')
mt = mt.drop_cols()
mt.write('freq.mt', overwrite=True)
```

minor decode optimization

---

python/hail/tests/test_api.py
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/utils/MultiArray2.scala
src/main/scala/is/hail/variant/MatrixTable.scala

`RegionValueBuilder` isn't serializable. Therefore, I had to initialize it for each seqop in `treeAggregate`. Is there a way to avoid this? @danking

SelectCols in IR

---

src/main/scala/is/hail/expr/ir/Binds.scala
src/main/scala/is/hail/expr/ir/FoldConstants.scala
src/main/scala/is/hail/expr/ir/Mentions.scala
src/main/scala/is/hail/expr/ir/Pretty.scala
src/main/scala/is/hail/expr/ir/Simplify.scala

remove unused let
push aggfilter into aggmap (if possible)
fuse aggmaps
Added ir.Binds (list of variables bound by an IR)
Added ir.Mentions (whether a variable is free in an IR)
propagate NA where strict
fuse ArrayMaps
Also improved ir.Pretty (more headers, was missing some closing parens).
This cleans up most of the small IR opportunities I've seen in @konradjk's scripts, although probably won't make a huge difference (except maybe pushing AggFilter into AggMap).

Improve simplify

---

src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
src/main/scala/is/hail/asm4s/FunctionBuilder.scala
src/main/scala/is/hail/expr/types/TBinary.scala
src/main/scala/is/hail/io/RowStore.scala
src/main/scala/is/hail/rvd/RVD.scala
src/main/scala/is/hail/utils/richUtils/Implicits.scala
src/main/scala/is/hail/utils/richUtils/RichCodeInputBuffer.scala
src/test/scala/is/hail/annotations/AnnotationsSuite.scala
src/test/scala/is/hail/annotations/UnsafeSuite.scala

13.7% improvement (47.3 => 40.8) over and above https://github.com/hail-is/hail/pull/3415.  Tested on a shard of gnomAD with:
```
mt = hl.read_matrix_table('gnomad.mt')
mt._force_count_rows()
```

I brought back the staged decoder

---

python/hail/methods/impex.py
python/hail/tests/test_methods.py
src/main/scala/is/hail/io/bgen/LoadBgen.scala

Expands the interface to permit importing with no entry fields (previously was error)

fast-path import_bgen with no entry fields

---

src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala

@tpoterba I think you originally added `val problem = hc.readVDS(out)`. Do you recall why?

minor speed ups in partitioningsuite.testWriteRead

---

src/main/scala/is/hail/methods/LDPrune.scala
src/main/scala/is/hail/sparkextras/GeneralRDD.scala

I made a couple formatting changes, so if you want functional changes only narrow the diff to the first commit.
The key change is that the `GeneralRDD` now contains a singleton iterator containing the array of parent iterators. Anywhere we previously had
```
new GeneralRDD(..., Array((..., f))
```
we transform it to
```
new GeneralRDD(..., Array((...)))
.flatMap(f)
```
We didn't previously take advantage of having distinct functions for different partitions. If that functionality became necessary we could `mapPartitionsWithIndex` and lookup the relevant function in an array.
I want to use this change in the spicy meatball (cc: @cseed) so that I can convert to a `ContextRDD` before calling `flatMap`.

Simplify GeneralRDD

---

src/main/scala/is/hail/methods/LDPrune.scala
src/test/scala/is/hail/methods/LDPruneSuite.scala

Previously it always assumed the variant struct started at offset zero, which is not true.

fix BitPackedVectorView

---

src/main/scala/is/hail/annotations/aggregators/RegionValueCollectAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueFractionAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueHistogramAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueMaxIntAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueStatisticsAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueSumAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueTakeAggregator.scala
src/main/scala/is/hail/asm4s/AsmFunction.scala
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/expr/ir/AggOp.scala
src/main/scala/is/hail/expr/ir/Children.scala
src/main/scala/is/hail/expr/ir/Compile.scala
src/main/scala/is/hail/expr/ir/Copy.scala
src/main/scala/is/hail/expr/ir/Emit.scala
src/main/scala/is/hail/expr/ir/ExtractAggregators.scala
src/main/scala/is/hail/expr/ir/IR.scala
src/main/scala/is/hail/expr/ir/Interpret.scala
src/main/scala/is/hail/expr/ir/Pretty.scala
src/main/scala/is/hail/expr/ir/Recur.scala
src/main/scala/is/hail/expr/ir/Subst.scala
src/main/scala/is/hail/expr/ir/TypeCheck.scala
src/main/scala/is/hail/expr/ir/TypeToIRIntermediateClassTag.scala
src/main/scala/is/hail/expr/ir/package.scala
src/test/scala/is/hail/expr/ir/ExtractAggregatorsSuite.scala
src/test/scala/is/hail/methods/AggregatorSuite.scala

Previously, MatrixMapRows was calling into an IR-generated function for each element.  Now we aggregate the entire row from within Python.  On a 6-aggregator benchmark on a shard of gnomAD, this improved things about 50% (1m59 => 1m02).
Some notable changes:
- I added a Begin for sequencing void-type IR,
- I added ArrayFor for looping over arrays (@danking)
- I added a SeqOp that represents calling the RegionValueAggregator in seqOp in the IR after extracting aggregators, it holds the index of the aggregator to call seqsOp on, since there might be multiple,
- added Void literal (which I didn't end up using, but I left it in for now),
- TAggreable symbol table is no longer used in compiling the extracted aggregators.  The arguments need to specified explicitly and otherwise it is just …

do full per-row aggregation inside the IR

---

python/hail/docs/_templates/req_unphased_diploid_gt.rst
python/hail/methods/impex.py
python/hail/methods/qc.py
python/hail/methods/statgen.py
src/main/scala/is/hail/methods/CalculateConcordance.scala

I purposefully left off the warning for `call_stats` because the requirement will be removed with #3496.

Concordance, SplitMulti, diploid/unphased warnings

---

python/hail/expr/expressions/base_expression.py
python/hail/typecheck/check.py

The stack trace looks like this now:
```
Error
File "/Users/jigold/hail/python/hail/expr/expressions/expression_typecheck.py", line 73, in check
return self.coerce(to_expr(x))
File "/Users/jigold/hail/python/hail/expr/expressions/base_expression.py", line 101, in to_expr
dtype = impute_type(e)
File "/Users/jigold/hail/python/hail/expr/expressions/base_expression.py", line 59, in impute_type
raise ExpressionException("Cannot impute type of empty list. Use 'hl.empty_array' to create an empty array.")
hail.expr.expressions.base_expression.ExpressionException: Cannot impute type of empty list. Use 'hl.empty_array' to create an empty array.
The above exception was the direct cause of the following exception:
File …
```

Fix #3475: Expression error gets output in stacktrace

---

src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/rvd/UnpartitionedRVD.scala

Definitely need a boundary on filters because filtering out half a partition would generate a bunch of garbage.

boundary on filters

---

src/main/scala/is/hail/annotations/aggregators/RegionValueAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueCollectAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueCountAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueFractionAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueHistogramAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueMaxIntAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueStatisticsAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueSumAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueTakeAggregator.scala
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/stats/HistogramCombiner.scala
src/main/scala/is/hail/utils/MissingBooleanArrayBuilder.scala
src/main/scala/is/hail/utils/MissingDoubleArrayBuilder.scala
src/main/scala/is/hail/utils/MissingFloatArrayBuilder.scala
src/main/scala/is/hail/utils/MissingIntArrayBuilder.scala
src/main/scala/is/hail/utils/MissingLongArrayBuilder.scala

Use in MatrixMapRows to avoid region value allocations.

Added RegionValueAggregator.clear.

---

src/main/scala/is/hail/asm4s/Code.scala
src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
src/main/scala/is/hail/expr/ir/functions/Functions.scala
src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala

This is to make it easier to port things to the FunctionRegistry.
This involves serializing the type, so it's not going to be especially efficient on most arbitrary objects, so i pulled strings out separately. It also doesn't deal with returning things that are arrays or structs or anything yet. (mostly just strings).
The type serializing is also included in this PR.
I moved the StringFunctions to use this so it should be moderately tested by the string function tests in python.
cc @tpoterba

`wrapArg` and `unwrapReturn` to pull annotations from RV representation

---

src/main/scala/is/hail/io/bgen/BgenRecord.scala
src/main/scala/is/hail/io/bgen/LoadBgen.scala

adding requiredness seemed to speed up import with GP by about 5%.  The GT stuff was smaller, maybe in the noise.

minor import_bgen optimizations

---

python/hail/methods/impex.py

Correct import_bgen docs based on the optimization I made last week (empty `entry_fields` takes a fast path that doesn't parse the genotypes)

Correct import_bgen docs

---

src/main/scala/is/hail/expr/ir/BinarySearch.scala
src/main/scala/is/hail/expr/ir/Children.scala
src/main/scala/is/hail/expr/ir/Copy.scala
src/main/scala/is/hail/expr/ir/Emit.scala
src/main/scala/is/hail/expr/ir/IR.scala
src/main/scala/is/hail/expr/ir/Infer.scala
src/main/scala/is/hail/expr/ir/Interpret.scala
src/main/scala/is/hail/expr/ir/TypeCheck.scala
src/test/scala/is/hail/expr/ir/OrderingSuite.scala

Uses binary search on sorted array representation of sets and dicts. The binary search algorithm is just pulled from the old `is.hail.utils.BinarySearch` which was here:
https://github.com/hail-is/hail/pull/2895/files#diff-c4570442b21e7226350aeeae4e958dc9

add IR nodes for SetContains, DictContains, DictGet

---

src/main/scala/is/hail/expr/ir/Children.scala
src/main/scala/is/hail/expr/ir/Compile.scala
src/main/scala/is/hail/expr/ir/Copy.scala
src/main/scala/is/hail/expr/ir/Emit.scala
src/main/scala/is/hail/expr/ir/ExtractAggregators.scala
src/main/scala/is/hail/expr/ir/IR.scala
src/main/scala/is/hail/expr/ir/Interpret.scala
src/main/scala/is/hail/expr/ir/Pretty.scala
src/main/scala/is/hail/expr/ir/TypeCheck.scala
src/main/scala/is/hail/expr/ir/functions/Functions.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/expr/AstToIrSuite.scala
src/test/scala/is/hail/expr/ir/FunctionSuite.scala

@cseed @tpoterba 
this was my solution to wrapping the `registerIR` calls to the function registry as one unit. The `fn` tag at the beginning is more or less just a tag on what the function name was.
If this looks ok, maybe we can just expose the ability to create and register these from python (maybe with uids as function names for distinctness) to wrap things like `alt_allele` and other things where the IR gets big and explody.

add ApplyIR to wrap ir => ir conversions in function registry

---

python/hail/methods/statgen.py
python/hail/tests/test_methods.py
src/main/scala/is/hail/methods/LocalLDPrune.scala
src/test/scala/is/hail/methods/LocalLDPruneSuite.scala

edit ld_prune to take a CallExpression instead of a matrix table, as well as some doc edits
will post to this [dev thread](http://discuss.hail.is/t/log-of-breaking-changes-in-0-2-beta/454/3) when it goes through

edit ld_prune to take CallExpression

---

src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/expr/ToIRErr.scala
src/main/scala/is/hail/methods/SplitMulti.scala
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/utils/Graph.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/expr/AstToIrSuite.scala
src/test/scala/is/hail/expr/ir/FunctionSuite.scala

Example:
```
2018-05-09 17:30:41 root: WARN: [is.hail.variant.MatrixTable.selectRows(MatrixTable.scala:1176) found no AST to IR conversion for:
Apply[annotate](
SymRef[va]
StructConstructor(
Select[toFloat64](
Select[position](
Select[locus](
SymRef[va]
)
)
)
)
)
due to the following errors:
locus<GRCh37> should be a subtype of TStruct, Select[locus](SymRef[va] ), is.hail.expr.Select$$anonfun$toIR$1.apply(AST.scala:371)
in
is.hail.variant.MatrixTable.selectRows(MatrixTable.scala:1176)
is.hail.testUtils.RichMatrixTable.annotateRowsExpr(RichMatrixTable.scala:57)
is.hail.variant.vsm.GroupBySuite.testLinregBurden(GroupBySuite.scala:107)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
With multiple …

More Information when toIR fails

---

src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
src/main/scala/is/hail/asm4s/Code.scala
src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/expr/ir/functions/Functions.scala
src/main/scala/is/hail/expr/ir/functions/ReferenceGenomeFunctions.scala
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/variant/ReferenceGenome.scala

cc @jigold I'm pretty sure this works, but I'd appreciate a look just in case. 
There's a set of tests in ReferenceGenomeSuite.testConstructors to test the functions, including one with a fake reference. I didn't add any more tests because those are now running through IR (I checked). But I can move the tests to python if desired.

ReferenceGenome-dependent constructors in the function registry

---

python/hail/expr/aggregators.py
python/hail/tests/test_api.py
python/hail/tests/test_expr.py
src/main/scala/is/hail/annotations/aggregators/RegionValueCallStatsAggregator.scala
src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/expr/ir/AggOp.scala
src/main/scala/is/hail/expr/ir/Children.scala
src/main/scala/is/hail/expr/ir/CodeAggregator.scala
src/main/scala/is/hail/expr/ir/Compile.scala
src/main/scala/is/hail/expr/ir/Copy.scala
src/main/scala/is/hail/expr/ir/Emit.scala
src/main/scala/is/hail/expr/ir/ExtractAggregators.scala
src/main/scala/is/hail/expr/ir/IR.scala
src/main/scala/is/hail/expr/ir/Infer.scala
src/main/scala/is/hail/expr/ir/Interpret.scala
src/main/scala/is/hail/expr/ir/Pretty.scala
src/main/scala/is/hail/expr/ir/Subst.scala
src/main/scala/is/hail/expr/ir/TypeCheck.scala
src/main/scala/is/hail/expr/ir/functions/CallFunctions.scala
src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
src/main/scala/is/hail/methods/Aggregators.scala
src/main/scala/is/hail/stats/CallStatsCombiner.scala
src/test/scala/is/hail/expr/AstToIrSuite.scala
src/test/scala/is/hail/expr/ir/ExtractAggregatorsSuite.scala
src/test/scala/is/hail/expr/ir/InterpretSuite.scala
src/test/scala/is/hail/methods/AggregatorSuite.scala
src/test/scala/is/hail/methods/SkatSuite.scala

For aggregation, there is now an `InitOp` which is a companion to a `SeqOp`. The `InitOp` IR will emit an `initOp` function on the `RegionValueAggregator` if it exists (not `None` as defined by the `ApplyAggOp`). The `initOp` function must have the region as the first argument followed by pairs of offsets and missing values. The `InitOpIR` gets compiled with `args` rather than `aggArgs` (scope is different from `SeqOp`) as it doesn't execute in the scope of the aggregable.

Added InitOp IR, RegionValueCallStatsAggregator

---

python/hail/tests/test_expr.py
src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/expr/ir/Emit.scala
src/main/scala/is/hail/expr/ir/IR.scala
src/main/scala/is/hail/expr/ir/functions/Functions.scala
src/main/scala/is/hail/expr/ir/functions/SetFunctions.scala
src/main/scala/is/hail/expr/ir/package.scala
src/main/scala/is/hail/utils/FastSeq.scala
src/test/scala/is/hail/TestUtils.scala
src/test/scala/is/hail/expr/ir/FunctionSuite.scala
src/test/scala/is/hail/expr/ir/IRSuite.scala
src/test/scala/is/hail/expr/ir/SetFunctionsSuite.scala
src/test/scala/is/hail/variant/vsm/VSMSuite.scala

Added the straightforward implementations to get them in the IRFunctionRegistry.  They are not optimal from the computational complexity perspective (e.g. union is n log m instead of n + m).  I will improve them in a separate PR.

add set functions

---

python/hail/methods/statgen.py
python/hail/tests/test_methods.py
src/main/scala/is/hail/methods/LocalLDPrune.scala

Proposed change for `ld_prune` motivated by user difficulty importing and pruning 1kg. As we don't have near-term plans for a version that exploits phasing, I think it's best to make this runnable regardless of phasing, while documenting that the algorithm ignores phasing. I've added this description, fixed a doc bug (unit is bases, not kilobases) and changed the parameter `window` to `bp_window_size`, which is consistent with `window_by_locus` and I think clearer. (I'll note it on our breaking changes dev post).
If we add a method that incorporates phasing in 0.2 lifetime, it can be a separate method or we can add a parameter `use_phasing` with default value `False`. (actually, it should be a separate method since r^2 correlation won't be the right measure for that).

relax ld_prune to run on phased GT

---

src/main/scala/is/hail/package.scala

with the version of deployed jars / zips / distros

Make the version length coming from error messages consistent

---

src/main/scala/is/hail/io/vcf/LoadVCF.scala

fixes Christina's bug
With enough partitions, it's somewhat likely that the `fastKeys` will end up with different partition ordering from the full rows, I guess.
cc: @tpoterba

reuse same RDD

---

src/main/scala/is/hail/io/DoubleInputBuffer.scala

`off + (n << 3)` was overflowing when writing a 16k x 16k matrix of doubles to binary, corresponding to n << 3 = MaxInt. With this change, I've verified that exporting a 16k x 16k as well as 32k x 32k (8GB) block matrix `tofile` no longer kills the JVM. Also fixed readDoubles.
Aside: `off` is a pointer into a java array, not raw memory, so remains an int (in particular, `out.write` requires that `off` is an int.)

fix overflow bug in writeDoubles and readDoubles

---

src/main/scala/is/hail/annotations/Region.scala
src/main/scala/is/hail/annotations/RegionValue.scala
src/main/scala/is/hail/methods/LocalLDPrune.scala
src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/rvd/OrderedRVPartitionInfo.scala
src/main/scala/is/hail/rvd/RVDContext.scala
src/main/scala/is/hail/table/Table.scala

Will merge cleanly when https://github.com/hail-is/hail/pull/3560 lands.
I needed to remove `RegionValue.copy` and `Region.copy` because they necessarily create regions that aren't managed by an `RVDContext`.
`RegionValue.copy` is only used in three places. 
- `Table.toMatrixTable`: Here, I took the somewhat inefficient choice of creating `SafeRow`s. If `toMatrixTable` is a performance bottleneck, we might want to reconsider this. It's not totally obvious how to do this. I think I'd need to explicitly serialize/deserialize these values and modify `reduceByKey` to explicitly provide the `RVDContext`. Anyway, this works and I don't think it's _that_ slow. (I guess I should check that)
- `OrderedRVD.localKeySort` & `LocalLDPrune.pruneLocal`: in both cases we need keep a handful of region …

Off Heap Region Prep

---

src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/variant/MatrixTable.scala

It seems that as long as we are copying the rows and the
entries into a combined RVD--rather than placing pointers
to the two, previously read, data structures--we need to
separate the regions used for each source and for the
combined data structure.
cc: @konradjk @catoverdrive

fix using rows table of matrix table

---

python/hail/matrixtable.py
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/expr/ir/Compile.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/variant/vsm/GroupBySuite.scala

Created a Relational IR for `mt.group_by_rows(...).aggregate(...)`.
I've never done this before so I just copied and massaged `MatrixMapRows`. It seems a lot longer than I anticipated. Two of the `GroupBySuite` tests exercise this path. The other two use non-IR features. When more things are put into the expr IR, they'll start exercising this path too.

group_by_rows(...).aggregate(...) in the IR

---

src/main/scala/is/hail/expr/ir/Simplify.scala

A small PR for you, @cseed. 😀
If we are immediately looking at the rows or cols table of
a MatrixTable, then we need not load the entries in either case.

Load less data in simple cases

---

src/main/scala/is/hail/methods/SplitMulti.scala
src/test/scala/is/hail/io/SplitSuite.scala

This prevents importing from Annotation multiple times.
I also did some minor clean up of the structure of the class
while I made this change.
I saw about a 10 second improvement (out of 2.5 minutes) on
```
In [1]: import hail as hl
In [2]: hl.init()
In [3]: %%time 
...: hl.split_multi_hts(hl.read_matrix_table('/Users/dking/projects/hail-data/profile.mt').select_entries('GT', 'AD', 'DP', 'GQ', 'PL'))._force_count_rows()
```

SplitMulti globals region

---

src/main/scala/is/hail/annotations/aggregators/RegionValueArraySumAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueCallStatsAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueCollectAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueCountAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueFractionAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueHistogramAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueMaxAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueMinAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueProductAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueStatisticsAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueSumAggregator.scala
src/main/scala/is/hail/annotations/aggregators/RegionValueTakeAggregator.scala
src/main/scala/is/hail/expr/ir/AggOp.scala
src/main/scala/is/hail/expr/ir/CodeAggregator.scala
src/main/scala/is/hail/expr/ir/Emit.scala
src/main/scala/is/hail/expr/ir/Interpret.scala
src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala

This teaches the IR how to compile `hl.agg.array_sum`, which it
previously could not compile. This is the first aggregator whose
input is a non-primitive value. I decided to generalize the seqOp
so that it accepts a Region argument and so that the element is
an IR "intermediate". An IR "intermediate" is a primitive value
or a `Long` offset for values of fundamental type Array or Binary.
cc: @armartin

Teach IR to ArraySum

---

python/hail/expr/expressions/base_expression.py
python/hail/table.py
python/hail/tests/test_api.py
src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/expr/ir/Simplify.scala
src/main/scala/is/hail/methods/PCRelate.scala
src/main/scala/is/hail/rvd/OrderedRVPartitionInfo.scala
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/utils/TextTableReader.scala
src/test/scala/is/hail/linalg/BlockMatrixSuite.scala
src/test/scala/is/hail/testUtils/RichTable.scala
src/test/scala/is/hail/utils/TextTableSuite.scala

This PR changes the semantics of TableMapRows in the IR and Table.select. They are now required to preserve the key ordering. In other words, applying TableMapRows to an ordered table can produce an ordered table without shuffling. I put an assert to verify that the produced OrderedRVD is really ordered, but that might be too expensive an assertion.
Before, `newKey = None` meant "keep the old key", but that left no room to ask for the result to be unkeyed. Now `newKey` is just the key of the resulting table.
If any partition key fields are modified, then even if the ordering is preserved, the result will need to be scanned to update the partition bounds. To avoid this scan when unnecessary, I added the `preservedKeyFields` parameter, which is the length of the prefix of key fields which …

Make TableMapRows/select preserve key order

---

src/main/scala/is/hail/expr/ir/functions/Functions.scala

Now that all the warnings are happening in toIR, and Apply.toIR checks all three possible conversions to make sure that only one of them converts properly, these warnings are both extraneous and misleading.

remove function registry warning for failed conversion

---

python/hail/matrixtable.py

I was going to remove `group_by_row` and `group_by_col` from the GroupedBlockMatrix docs, but they can technically be called on an "ungrouped" GroupedMatrixTable (e.g. created with `dataset.group_rows_by()`).

clarify GroupedMatrixTable doc

---

python/hail/linalg/blockmatrix.py
python/hail/tests/test_linalg.py
src/main/scala/is/hail/linalg/BlockMatrix.scala
src/main/scala/is/hail/linalg/GridPartitioner.scala
src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala
src/main/scala/is/hail/variant/MatrixTable.scala

Added to Python BlockMatrix:
- `fill` w/ test
- `sum` w/ test (useful for LD scores among other things)
Added to Scala BlockMatrix:
- `fill`
- `apply` to factor out common motif in `fromBreezeMatrix`, `random`, `fill`
- `sum`, `rowSum`, `colSum` via `reduce`, `rowReduce`, `colReduce`
Added `maybeBlockRows` and `maybeBlockCols` to GridPartitioner, and changed `maybeSparse` to the more descriptive `maybeBlocks` to match.
Regarding the implementations of `sum`, `rowSum`, `colSum`: I tested Breeze op `sum(a(::, *))` against Breeze matrix multiplication by a vector of ones at the block level, and found the latter to be four times faster on laptop (17s vs 4.5s for 1000 iterations).
```
@Test  
def sum() {
val a = BDM.rand[Double](4096, 4096)
printTime {
var i = 0
while (i < 1000) {
//val c = …
```

BlockMatrix fill, sum over axis

---

python/hail/methods/statgen.py

@maccum without checks on the requirements, it could be that `mt` is not partitioned by locus in which case LocalLDPrune wouldn't do much and this would be a bug because the `correlation_matrix` and `locally_pruned_rows` would not align:
```
block_matrix = BlockMatrix.from_entry_expr(normalized_mean_imputed_genotype_expr, block_size=1024)
correlation_matrix = (block_matrix @ block_matrix.T)
locally_pruned_rows = locally_pruned_ds.rows()
locally_pruned_rows = locally_pruned_rows.key_by(contig=locally_pruned_rows.locus.contig)
locally_pruned_rows = locally_pruned_rows.select(pos=locally_pruned_rows.locus.position)
entries = correlation_matrix._filtered_entries_table(locally_pruned_rows, bp_window_size, False)
```
I'm still worried about the following. By changing the key (and partition_key) …

LD prune optimization & question

---

python/hail/conftest.py
python/hail/docs/doctest.sh
python/hail/docs/getting_started.rst
python/hail/docs/getting_started_developing.rst
python/hail/docs/overview.rst

I forgot to add the restructured text files to the new doctest framework, so right now they aren't being tested. This fix will test the python commands in all of the `.rst` files in `python/hail`.
Also, I removed the obsolete doctest directive strings `.. doctest::` and `.. testsetup::`.

Test *.rst files

---

src/main/scala/is/hail/expr/ir/functions/Functions.scala
src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala
src/main/scala/is/hail/expr/types/TLocus.scala
src/test/scala/is/hail/expr/ir/LocusFunctionsSuite.scala

move these to IR function registry: 
isAutosomalOrPseudoAutosomal(locus<RGVariable>):bool
isAutosomal(locus<RGVariable>):bool
inYNonPar(locus<RGVariable>):bool
inXPar(locus<RGVariable>):bool
isMitochondrial(locus<RGVariable>):bool
inXNonPar(locus<RGVariable>):bool
contig(locus<RGVariable>):str
position(locus<RGVariable>):int32
inYPar(locus<RGVariable>):bool
I have a couple more to do that aren't locus ones, which I'll PR separately.

Port locus functions to ir registry

---

python/hail/expr/functions.py
python/hail/linalg/blockmatrix.py
python/hail/methods/misc.py
python/hail/methods/statgen.py
python/hail/tests/test_methods.py
src/main/scala/is/hail/linalg/BlockMatrix.scala
src/main/scala/is/hail/methods/LocalLDPrune.scala
src/main/scala/is/hail/methods/UpperIndexBounds.scala
src/main/scala/is/hail/table/Table.scala
src/test/scala/is/hail/methods/LocalLDPruneSuite.scala
src/test/scala/is/hail/methods/UpperIndexBoundsSuite.scala

- added `keep_higher_maf` option (`true` by default) to `ld_prune` to prefer to keep higher MAF variants in the global (MIS) stage.
- improved the `ld_prune` flow to reduce duplicated work
- set BlockMatrix.entries to set `i` and `j` as key fields and improved its doc
- corrected references to standard deviation that are actually n times standard deviation, i.e. centered length
- switched `computeCoverByUpperTriangularBlocks` to use the newer`rowIntervalsBlocks` rather than `rectanglesBlocks` directly
I've tested `keep_higher_maf` in notebooks, will add a test of MAF soon and then assign.
@danking rather than:
```
def tie_breaker(l, r):
return hl.cond(l.twice_maf > r.twice_maf,
-1,
hl.cond(l.twice_maf < r.twice_maf,
1,
0))
```
I'd prefer:
```
def tie_breaker(l, r):
return …
```

ld_prune: add MAF preference in MIS, other improvements

---

python/hail/table.py

The `self` here is the left-hand side of a join. This expression is checking if the right-hand side of the join needs to be re-keyed. Obviously the left-hand side's keys will never be reference equal to the right-hand side's keys.

Remove Unnecessary KeyBy's

---

src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
src/main/scala/is/hail/expr/ir/Emit.scala
src/main/scala/is/hail/io/RowStore.scala

I need to use in decoder builder which doesn't currently chunk struct construction, will use there after https://github.com/hail-is/hail/pull/3667 goes in to avoid conflicts.
This introduces 1 change in behavior: code with estimated size > 100 will be put out in its own method, even it fits in one block.  If I read it correctly, the old code would put any amount of code inline up to the method limit target, so several medium-sized structs would potentially blow out the method bytecode limit.
Also fixed a bug in getChunkBounds where items on the boundary weren't counted in the size.

generalize wrapToMethod

---

python/hail/table.py
python/hail/tests/test_api.py

Indexing a table by a non-unique matrixtable field was broken (only joined with one row per distinct value). For example, in the test I added, `m4.filter_cols(hl.is_defined(m4.idx)).count_cols()` previously returned 1, now returns 9.

join bugfix

---

src/main/scala/is/hail/expr/ir/functions/SetFunctions.scala
src/test/scala/is/hail/expr/ir/SetFunctionsSuite.scala

`median` for Sets doesn't work. I'm deleting for now and reimplementing in a separate PR.

rm broken set median IR function

---

src/test/scala/is/hail/methods/ExportSuite.scala
src/test/scala/is/hail/methods/SelectSuite.scala
src/test/scala/is/hail/methods/TableSuite.scala
src/test/scala/is/hail/testUtils/RichTable.scala
src/test/scala/is/hail/variant/vsm/GroupBySuite.scala
src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala
src/test/scala/is/hail/variant/vsm/VSMSuite.scala

They use the deprecated AST interface.   Rewrite in terms of Table interface.

remove RichTable.{select, selectGlobal}

---

src/main/scala/is/hail/annotations/Region.scala

I found this logging helpful but not noisy. The blockSize change
is inspired by @rcownie. It means that things that take half or more of the block will get a custom block, rather than possibly having a block half-occupied with something big and not have a lot of room for new stuff. (At least, that's my understanding of the rational)

Some logging and an alloc improvement to Region

---

src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/expr/ir/functions/DictFunctions.scala
src/test/scala/is/hail/expr/ir/DictFunctionsSuite.scala
src/test/scala/is/hail/methods/ExprSuite.scala

I removed `toDict` (well, renamed it to `dict`) since it doesn't appear to be used anywhere (the function is in the current function registry as `dict`).

add some dict functions to IR

---

src/main/scala/is/hail/io/bgen/BgenBlockReader.scala
src/main/scala/is/hail/io/bgen/BgenRecord.scala

from https://github.com/hail-is/hail/pull/3727
`assert`s don't protect the allocation of their strings. `If`'s do.

Convert BGEN asserts to ifs for performance

---

src/main/scala/is/hail/annotations/RegionValueBuilder.scala

This provides necessary performance improvements when creating
an array of empty structs, which should have o(1) cost, not
O(n) cost.

Add RVB.unsafeAdvance

---

python/hail/context.py
src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/variant/MatrixTable.scala

I believe useIR is no longer necessary.  It was meant to handle copying large globals/col values (just fixed by https://github.com/hail-is/hail/pull/3660) and blowing out the JVM bytecode limit (long since fixed).  @tpoterba @catoverdrive am I missing anything else?

remove useIR

---

src/main/scala/is/hail/io/bgen/BgenBlockReader.scala
src/main/scala/is/hail/io/bgen/BgenRecord.scala
src/main/scala/is/hail/io/bgen/LoadBgen.scala

@tpoterba you were in here recently for performance so your eyes are appreciated.
I simplified things a bit and localized almost all the parsing logic to `BgenRecord`. The contract for `advance` is that it is always called when `bfis` is pointing at the start of a record _or_ at or past the `end`. Advance will return the position to the start of a record or at or past the `end`. It returns true if there was a new record found. False otherwise.
I avoided a couple allocating patterns.
The rest of the diffs are copy pastes and some indentation changes.

avoid copying data when not reading genotypes

---

src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/rvd/RVD.scala
src/main/scala/is/hail/rvd/UnpartitionedRVD.scala
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/variant/MatrixTable.scala

The old `Table.index` used the `RDD` route which forced a shuffle because all partitioning information was lost. I exposed `zipWithIndex` on `RVD` and used it in both MatrixTable and Table.

Table.index no shuffle

---

src/main/scala/is/hail/expr/AST.scala

I ran into an error on another branch where ArrayFor doesn't work if the object being aggregated is a Set. I'm assuming here the ToArray is free for all container objects.

Fix Aggregable IR FlatMap

---

src/main/scala/is/hail/expr/ir/Interpret.scala
src/test/scala/is/hail/expr/ir/MathFunctionsSuite.scala

I forget why I added this, but I came across something in
Uniroot that either was not or made me think that Uniroot
was not strict in max and min, so I added a test.

Uniroot is strict in min and max test

---

python/hail/methods/impex.py
python/hail/tests/test_io.py
src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/io/AbstractBinaryReader.scala
src/main/scala/is/hail/io/bgen/BgenBlockReader.scala
src/main/scala/is/hail/io/bgen/BgenRecord.scala
src/main/scala/is/hail/io/bgen/LoadBgen.scala

This option controls parsing and loading of the `rsid` and `varid`
BGEN row fields. When (in a future PR) the reader does not decompress
the genotypes (nor decode them), these row field imports become
a substantial portion of the time necessary to load just the row
keys.
broken out from: https://github.com/hail-is/hail/pull/3727

Add row_fields import_bgen parameter

---

src/main/scala/is/hail/io/IndexBTree.scala
src/test/scala/is/hail/io/IndexBTreeSuite.scala

I knew I was missing tests of greater than two layers. Sure enough there were more bugs lurking. I think >3 layers won't find any new bugs given that there are basically three kinds of b-trees:
- 1 layer: all leaf nodes, <=1024 elements
- 2 layers: one internal/key layer, one leaf layer [1025, 1024^2] elements
- n layers: n-1 internal/key layers, one leaf layer [1024^(n-1)+1, 1024^n] elements
The last case is the first case where we have to do two levels of internal layers. This traversal is defined inductively, so I suspect succeeding on 3 layers tests all the functionality of >3 layers.

More index btree array position tests

---

src/main/scala/is/hail/asm4s/FunctionBuilder.scala
src/main/scala/is/hail/expr/ir/AggOp.scala

forgot to add it to this, so it wasn't actually being parsed here and was still going through AST. I double checked that the python tests that call this are now going through IR.

actually add collectAsSet to IR conversion

---

python/hail/methods/impex.py
python/hail/tests/test_io.py
src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/io/bgen/BgenBlockReader.scala
src/main/scala/is/hail/io/bgen/BgenRecord.scala
src/main/scala/is/hail/io/bgen/LoadBgen.scala

This builds on top of #3779 and will merge clean once that it's in. Please review after #3779 merges.
This adds a row field that is the index of the variant _in the original file_. This might not be the same as the locus ordered position. In particular, our 8bit test file has variants ordered by RSID, which is not the same ordering as the file ordering.
The next file will add a filter on file row indices. Then, finally, we can use all this in combination to generate a list of file row indices to keep and dramatically increase filtering speed.
```python
In [1]: import hail as hl
...: 
...: mt = hl.import_bgen('/Users/dking/projects/hail/src/test/resources/example.8bits.bgen',
...:                     entry_fields=['dosage'],
...:                     contig_recoding={'01': '1'},
...: …
```

Add BGEN File Row Index Row Field

---

python/hail/matrixtable.py
python/hail/table.py
python/hail/tests/test_api.py

Joins were not being tested and fail with source mismatch if joins are present in both key and agg expressions. This fix is analogous to that on Table.group_by.aggregate in #3730, processing all joins at once, and not reprocessing later. I don't address here a deeper bug that throws a source error when processing more than one entry-indexed. I've made an issue #3763

make MatrixTable.group_by.aggregate_rows/cols work with implicit joins

---

src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/expr/ir/Pretty.scala
src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
src/main/scala/is/hail/expr/ir/Simplify.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/expr/ir/PruneSuite.scala

I needed to make the read function in MatrixRead into a class so I can print/parse as part of the work to replace AST with IR in the Python interface.
Also, push down required type into MT decoder.  I also use the compiler to build the function to add the entries to the row values (no RegionValueBuilder).

Make MatrixRead.f into a class

---

python/hail/expr/expressions/base_expression.py

Prints a nice message if the user forgets default/or_missing
Fixes #3696

Nicer error for case/switch statements

---

python/hail/tests/test_expr.py
src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/expr/ir/Children.scala
src/main/scala/is/hail/expr/ir/Copy.scala
src/main/scala/is/hail/expr/ir/Emit.scala
src/main/scala/is/hail/expr/ir/IR.scala
src/main/scala/is/hail/expr/ir/Infer.scala
src/main/scala/is/hail/expr/ir/Interpret.scala
src/main/scala/is/hail/expr/ir/TypeCheck.scala
src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala
src/main/scala/is/hail/variant/MatrixTable.scala

I'm still not really sure how to test this properly since it's not in the IR function registry, but I checked that the tests in is.hail.methods.AggregatorSuite that rely on this are going through IR.

add sortBy to IR conversion

---

python/hail/tests/test_api.py
python/hail/tests/test_expr.py
src/main/scala/is/hail/asm4s/Code.scala
src/main/scala/is/hail/expr/FunctionRegistry.scala
src/main/scala/is/hail/expr/ir/functions/Functions.scala
src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala
src/main/scala/is/hail/methods/VariantQC.scala
src/main/scala/is/hail/stats/HWECombiner.scala
src/main/scala/is/hail/stats/package.scala
src/main/scala/is/hail/utils/package.scala
src/test/scala/is/hail/expr/ir/MathFunctionsSuite.scala
src/test/scala/is/hail/stats/FisherExactTestSuite.scala

- ir for chisq, fet, ctt, hwe
- using nan instead of missing
- direct implementation of chisq
This is first half of closed #3825, leaving all python docs and interface as is.
To cross-check, I used R and https://www.cog-genomics.org/software/stats

IR for chisq, fet, ctt, hwe with simpler chisq implementation

---

src/main/scala/is/hail/expr/ir/functions/DictFunctions.scala
src/test/scala/is/hail/expr/ir/DictFunctionsSuite.scala
src/test/scala/is/hail/expr/ir/IRSuite.scala
src/test/scala/is/hail/expr/ir/OrderingSuite.scala

(actually, I put `dict.get(key)` back in since it's used in python join stuff also.)

add dict[key], remove dict.get without default from Scala

---

build.gradle
python/hail/methods/impex.py
python/hail/tests/test_io.py
src/main/scala/is/hail/HailContext.scala
src/main/scala/is/hail/io/IndexBTree.scala
src/main/scala/is/hail/io/IndexedBinaryBlockReader.scala
src/main/scala/is/hail/io/bgen/BgenBlockReader.scala
src/main/scala/is/hail/io/bgen/BgenInputFormat.scala
src/main/scala/is/hail/io/bgen/BgenRecord.scala
src/main/scala/is/hail/io/bgen/LoadBgen.scala
src/main/scala/is/hail/utils/package.scala
src/test/scala/is/hail/io/IndexBTreeSuite.scala
src/test/scala/is/hail/utils/UtilsSuite.scala

Finally add BGEN filtering at the level of bytes. We add a non-public, non-documented `_variants_per_file` argument that lists the variants to keep by their on-disk indices. It's a pretty groady interface, but it works with the current infrastructure and provides a _massive_ improvement. We go from decoding all the variants in the BGEN to decoding only those relevant to the computation at hand. In the case of Caitlin's PRS scoring method, that's about 1% or less of the original variant set.
It's a bit janky. The file paths need to be the fully qualified ones that are seen by the hadoop reader. So `file:/full/path/to/file.bgen` or `gs://full/path/to/bgen.file`, which is annoying. I don't have any better way to generically uniquely identify files though.
---
I also had to fix a bug in the …

BGEN File-Read-Level Filtering

---

src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala
src/test/scala/is/hail/expr/ir/IntervalSuite.scala

@cseed this fixes the bug that was caught by testConstructor in your branch, but it was distinct enough that I broke it out as a separate PR, if that's ok.

fix interval.start, interval.end

---

python/hail/matrixtable.py
src/main/scala/is/hail/expr/Relational.scala
src/main/scala/is/hail/variant/MatrixTable.scala

@cseed @tpoterba I couldn't think of a great way to figure out how to handle aggregations more generally in python, so I currently just have it setting a boolean field for the filter. This seemed more straightforward than adding aggregations to the FilterCols IR node, but maybe it's wrong/bad in a way that I hadn't thought of?

make filter_cols aggregations happen in python

---

python/hail/tests/test_genetics.py
src/main/scala/is/hail/expr/ir/functions/ReferenceGenomeFunctions.scala

before, a npe was being thrown because `liftoverLocus` would return a null Locus if it couldn't be lifted over.

fix liftover functions to handle missing return

---

src/main/scala/is/hail/expr/Parser.scala
src/main/scala/is/hail/expr/ir/MatrixIR.scala
src/main/scala/is/hail/expr/ir/Pretty.scala
src/main/scala/is/hail/expr/ir/TableIR.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/expr/ir/IRSuite.scala

Builds on https://github.com/hail-is/hail/pull/3852 to avoid a conflict nightmare.  You probably don't want to reivew until that goes in.
This adds TableIR parser.  TableImport is missing because handling the import options requires a bit more work.  Tested by pretty printing/parsing example TableIR and verifying the result is the same.  Also added (most of the) MatrixIR parser, but it is untested, that will come in part (3).
Had to change some Array => IndexedSeq in various places to get proper equality.
Rewrote Parser.quotedLiteral to avoid JVM stack depth limits when parsing non-small string literals.

added IR parser (2)

---

src/main/scala/is/hail/expr/ir/TableIR.scala

just realized that this one doesn't keep partitionCounts() information, either

have MatrixRowsTable preserve partitionCounts() information from MatrixIR

---

src/main/scala/is/hail/expr/ir/Emit.scala

Beryl was having an issue where we included the debug string in the IR, but it was greater than the maximum IR string length.

limit debug string size

---

src/main/scala/is/hail/annotations/aggregators/RegionValueCountAggregator.scala
src/main/scala/is/hail/expr/AST.scala
src/main/scala/is/hail/expr/Parser.scala
src/main/scala/is/hail/expr/ir/AggOp.scala
src/main/scala/is/hail/expr/ir/CodeAggregator.scala
src/main/scala/is/hail/expr/ir/ExtractAggregators.scala
src/main/scala/is/hail/expr/ir/IR.scala
src/main/scala/is/hail/expr/ir/Interpret.scala
src/main/scala/is/hail/expr/ir/Pretty.scala
src/main/scala/is/hail/expr/ir/TypeCheck.scala
src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala
src/test/scala/is/hail/expr/ir/FunctionSuite.scala
src/test/scala/is/hail/expr/ir/IRSuite.scala
src/test/scala/is/hail/expr/ir/InterpretSuite.scala

The goal of this PR is to move the inputType of the AggSignature into the seqOpArgs to make it more general. For now, the first seqOpArgument is always the aggregable. However, when I add Keyed AggOps, the first argument will be the key and the second argument will be the aggregable.

Refactor AggSignature

---

python/hail/methods/statgen.py

Hail should not signal an error if the PAR is empty. This change provides an explicit type to the PAR before handing it to filter_intervals. 
@tpoterba assigning you because I want to make sure I'm doing this right.

Fix Type Error When PAR is Empty

---

python/hail/table.py

need space to render examples properly

fix example formatting in docs for Table.index

---

src/main/scala/is/hail/io/AbstractBinaryReader.scala
src/test/scala/is/hail/io/ByteArrayReaderSuite.scala

I discovered this while working on BGEN things.

Fix AbstractBinaryReader.readLong and add test for it

---

src/main/scala/is/hail/expr/ir/MatrixIR.scala
src/main/scala/is/hail/expr/ir/TableIR.scala
src/main/scala/is/hail/rvd/RVD.scala

Fixes #3920
I'm a bit dubious on `collectPerPartitions` because it can only be safely used if there's a `ctx.region.clear` in the right spot. This should avoid some issues that caitlin was experiencing.
The root issue is that `clearingRun` clears once per item, but, after the `cmapPartitions` there is only one item per partition. That item was produced by iterating through every element (with `it.foreach`) and accumulating some state. When `it.foreach` is finished, the entire partition will be in memory. On sufficiently large datasets, YARN will kill the executors for exceeding memory limits. We previously observed these errors coming from Java, but now that the regions are in native code, there are no JVM limits, the memory usage is instead noticed by YARN at the container-level.
The fix …

Safer scans

---

.gitignore
src/main/c/Makefile

Adds ignore for the header sentinel file, linux (and technically other OSes) built shared object. Also replaces `basename` with `dir` to not create an extra empty directory during compilation.

Small c++ build system tweaks

---

python/hail/methods/linear_mixed_model.py
python/test/test_hail/methods/test_statgen.py

- removed dependencies of lmm tests on linear_mixed_regression
- added test against fast_lmm
- added h_sq_standard_error feature from linear_mixed_regression
Toward goal of deleting linear_mixed_regression and its Scala / suites ASAP, as well as the KinshipMatrix class

lmm2 test improvements and h_sq_standard_error

---

python/hail/linalg/blockmatrix.py
python/hail/matrixtable.py
python/hail/table.py
python/test/test_hail/linalg/test_linalg.py
python/test/test_hail/matrixtable/test_matrix_table.py
python/test/test_hail/table/test_table.py
src/main/scala/is/hail/expr/ir/Children.scala
src/main/scala/is/hail/expr/ir/Copy.scala
src/main/scala/is/hail/expr/ir/IR.scala
src/main/scala/is/hail/expr/ir/Interpret.scala
src/main/scala/is/hail/expr/ir/MatrixValue.scala
src/main/scala/is/hail/expr/ir/Pretty.scala
src/main/scala/is/hail/expr/ir/TableValue.scala
src/main/scala/is/hail/expr/ir/TypeCheck.scala
src/main/scala/is/hail/io/RowStore.scala
src/main/scala/is/hail/linalg/BlockMatrix.scala
src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/rvd/RVD.scala
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/utils/richUtils/RichContextRDD.scala
src/main/scala/is/hail/utils/richUtils/RichRDD.scala
src/main/scala/is/hail/variant/MatrixTable.scala

If the option is set, then writeRowsSplit for MatrixTable and writePartitions for Table
first write much of their output to tempfiles before copying it to the final destination.

Add option to stage Table/MatrixTable writes locally before copying to final storage location

---

python/hail/methods/linear_mixed_model.py
python/test/test_hail/methods/test_statgen.py

`h_sq_normalized_lkhd` is the final feature of LinearMixedRegression that should be exposed directly on LinearMixedModel. I also fixed a bug in the relationship of `h2 = s2 / (s2 + t2)` and `gamma = s2/t2` in `_estimate_h_sq_standard_error`, which didn't noticeably change the answer because of the symmetry of the left and right points about the max (curvature of fit parabola doesn't change when reflected over a vertical axis).

lmm2: added h_sq_normalized_lkhd

---

python/hail/docs/methods/index.rst
python/hail/docs/methods/stats.rst
python/hail/linalg/blockmatrix.py
python/hail/methods/__init__.py
python/hail/methods/statgen.py
python/test/test_hail/linalg/test_linalg.py
python/test/test_hail/methods/test_statgen.py

I next plan to add an `ld_matrix` function under methods/genetics that incorporates parameters for optional windowing and is implemented in a few lines using `locus_windows`, `correlation`, and `sparsify_row_intervals`. I may then add a more generic example here and put the ld_matrix examples there.

correlation between rows of matrix table

---

src/main/scala/is/hail/expr/ir/Binds.scala
src/main/scala/is/hail/expr/ir/Compile.scala
src/main/scala/is/hail/expr/ir/Emit.scala
src/main/scala/is/hail/expr/ir/Interpret.scala
src/main/scala/is/hail/expr/ir/Mentions.scala
src/main/scala/is/hail/expr/ir/Optimize.scala
src/main/scala/is/hail/expr/ir/Simplify.scala
src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/expr/ir/IRSuite.scala

Improved the optimizer so the IR generated for:
```
mt = hl.import_vcf('sample.vcf')
mt.info.CCC.show()
```
is reasonable.
Run optimizer in compile, so we optimize (transformed) agg and seq ops.
Simplify runs:
- propagate Begins up if possible
- inline single-use Lets
- (Apply annotate ...) => InsertFields if possible
- Turn MakeStruct of a bunch of FieldRefs into InsertFields
The optimizer now turns this:
```
(TableMapGlobals Struct{} "{}"
(MatrixRowsTable
(MatrixMapRows None None
(MatrixRead None False False ...)
(Let __uid_1
(MakeStruct
(<expr>
(GetField CCC
(GetField info
(Ref ... va)))))
(ApplyIR annotate
(MakeStruct
(locus
(GetField locus
(Ref ... va)))
(alleles
(GetField alleles
(Ref ... va))))
(MakeStruct
(<expr>
(GetField `<expr>`
(Ref Struct{`<expr>`:Int32} __uid_1)))))))) …
```

fix optimizer to clean up mt.field.show()

---

python/hail/expr/builders.py
python/test/test_hail/expr/test_expr.py

it felt a little weird to directly define a hail function that's like "throw an error of the specified type", so I added it as an option to `hl.case()`, but I could break it out explicitly if that would be better.

add 'or_error' case to CaseBuilder

---

src/main/scala/is/hail/asm4s/Code.scala
src/main/scala/is/hail/expr/ir/Emit.scala
src/test/scala/is/hail/expr/ir/IRSuite.scala

Fixes https://github.com/hail-is/hail/issues/3969
This was quite a subtle one.  I was able to replicate:
before:
```
>>> ht = hl.utils.range_table(1000)
>>> ht = ht.annotate(tp = True)
>>> ht = ht.annotate(x = hl.cond(~ht.tp, ht.tp, ht.tp & hl.rand_bool(0.5)))
>>> ht.aggregate(hl.agg.counter(ht.x))
{False: 755, True: 245}
>>> ht = hl.utils.range_table(1000)
>>> ht = ht.annotate(tp = True)
>>> ht = ht.annotate(x = ht.tp & hl.rand_bool(0.5))
>>> ht.aggregate(hl.agg.counter(ht.x))
{False: 490, True: 510}
```
after
```
>>> ht = ht.annotate(tp = True)
>>> ht = ht.annotate(x = hl.cond(~ht.tp, ht.tp, ht.tp & hl.rand_bool(0.5)))
>>> ht.aggregate(hl.agg.counter(ht.x))
{False: 498, True: 502}
>>> ht = hl.utils.range_table(1000)
>>> ht = ht.annotate(tp = True)
>>> ht = ht.annotate(x = ht.tp & …
```

fix condition bug in emit

---

src/main/scala/is/hail/io/RowStore.scala

Table write was completely fucked.  It was flushing the encoder after every record (putting each row in its own compression block).
before:
```
In [2]: %%time
...: t1 = hl.utils.range_table(10 * 1000 * 1000)
...: t2 = t1.annotate(x = hl.rand_unif(0, 1))
...: t2.write('t2.ht', overwrite=True)
...: 
2018-07-29 14:16:23 Hail: INFO: wrote 10000000 items in 8 partitions
CPU times: user 14.6 ms, sys: 775 µs, total: 15.3 ms
Wall time: 27.9 s
In [3]: %%time
...: t3 = hl.read_table('t2.ht')
...: t3._force_count()
...: 
CPU times: user 4.09 ms, sys: 8 µs, total: 4.1 ms
Wall time: 1.48 s
```
after:
```
In [3]: %%time
...: t1 = hl.utils.range_table(10 * 1000 * 1000)
...: t2 = t1.annotate(x = hl.rand_unif(0, 1))
...: t2.write('t2.ht', overwrite=True)
...: 
2018-07-29 14:20:34 Hail: INFO: wrote …
```

remove per-row flush in table write

---

python/hail/methods/misc.py
python/test/hail/methods/test_misc.py
src/main/scala/is/hail/methods/FilterIntervals.scala
src/main/scala/is/hail/rvd/OrderedRVD.scala
src/test/scala/is/hail/variant/LocusIntervalSuite.scala

Along the way, I slightly generalized filter_intervals to support filtering on intervals that are a prefix of the partition key.
FYI @konradjk

filter_intervals now works on tables

---

src/main/scala/is/hail/expr/ir/TableValue.scala
src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/rvd/RVD.scala
src/main/scala/is/hail/rvd/UnpartitionedRVD.scala

1. Convert globals once per partition instead of once per row.
2. Add filterWithContext method so filter doesn't strip partitioning

speed up TableFilter.

---

python/hail/methods/impex.py

Tested export_vcf and confirmed that an `rsid` row field gets put into ID, but this is not documented.

Adding RSID into export_vcf docs

---

python/hail/linalg/blockmatrix.py
python/test/hail/linalg/test_linalg.py
src/main/scala/is/hail/linalg/BlockMatrix.scala
src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/linalg/RowMatrixSuite.scala

Currently writing a new block matrix to the same path leaves the old blocks in the folder, making them hard to delete. Adding an overwrite parameter fixes the issue and is safer.

add overwrite parameter to BlockMatrix.write and write_from_entry_expr

---

python/hail/expr/expressions/base_expression.py
python/hail/matrixtable.py
python/hail/table.py
python/test/hail/table/test_table.py

for better IR generation. This change the (`key_struct`, `value_struct`) arguments to a more general (`row`, `new_keys`) which allows individual methods more flexibility in how the row is constructed.
@tpoterba this fixes the specific case in #4001, but I'm not sure if you wanted to keep that open as a general issue or just open issues with other cases as we test them? With this change I'm getting:
```
2018-07-30 18:11:23 root: INFO: optimize: before:
(TableMapRows (idx) 1
(TableRange 5 2)
(InsertFields
(Ref Struct{idx:Int32} row)
(x
(I32 5))))
2018-07-30 18:11:23 root: INFO: optimize: after:
(TableMapRows (idx) 1
(TableRange 5 2)
(InsertFields
(Ref Struct{idx:Int32} row)
(x
(I32 5))))
```

Refactor _select methods in python

---

src/main/scala/is/hail/annotations/OrderedRVIterator.scala
src/main/scala/is/hail/expr/ir/MatrixIR.scala
src/main/scala/is/hail/expr/ir/Simplify.scala
src/main/scala/is/hail/rvd/KeyedOrderedRVD.scala
src/main/scala/is/hail/rvd/OrderedRVD.scala
src/main/scala/is/hail/rvd/OrderedRVDPartitioner.scala
src/main/scala/is/hail/utils/FlipbookIterator.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/expr/ir/MatrixIRSuite.scala

basically, it now looks at the partitioner for the MatrixValues of its children when it executes, and only shuffles if rvds are non-disjoint. It removes empty rvds and separates children into non-disjoint piles, shuffles those independently, and then concatenates them together in sorted order.
(I'm not sure how this behaves relative to the old behavior (coerce everything together) when we have multiple shuffles that need to happen, but at least filtering out empty RVDs helps a lot in e.g. the split-multi case where none of the variants need to be moved.)
I think the (a?) better optimization would be to add smarter partitioning so that we're adjusting partition bounds and not really shuffling under most circumstances, but I thought I'd PR this first since at least there's a warning in …

add more logic to MatrixUnionRows

---

src/main/scala/is/hail/rvd/OrderedRVD.scala

I broke this assertion when I fixed the bug that was caught by it.

Fix OrderedRVD assertion

---

Dockerfile.pr-builder
Makefile
build.gradle
hail-ci-build-image
hail-ci-build.sh
python/hail/docs/makeDocs.sh

This is the plan for the new Hail CI (tentatively: Hephaestus aka h8s [but Hodor is also in the running, see CI software name in Zulip for the real big questions of our time]).
Every repository to be tested has at least two files: `hail-ci-build-image` and `hail-ci-build.sh`. The former contains a docker image in a publicly accessible repository. The latter is a shell script that exits with 0 if this branch passes the tests, otherwise it exists with a non-zero code. The logs of this shell script will be shared publicly via the GH PR Status. This script will be executed in the image referenced by `hail-ci-build-image`.
I carefully wrote a docker file to cache as much gradle crap as possible.
I pushed `gitHash`'s definition into the `doLast` blocks of the gradle steps that actually need it. …

Prep for Hail CI changes

---

.gitignore

Running the tests on a clean checkout should keep the tree clean

Add files created by test run to .gitignore

---

python/hail/ir/table_ir.py
python/hail/matrixtable.py
python/test/hail/table/test_table.py
python/test/hail/test_ir.py
src/main/scala/is/hail/expr/Parser.scala
src/main/scala/is/hail/expr/ir/Pretty.scala
src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
src/main/scala/is/hail/expr/ir/TableIR.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/expr/ir/IRSuite.scala

This is part of my work on UnlocalizeEntries (this function's 'inverse'). Separated out into it's own change.
Just moves `MatrixTable.localizeEntries` to the TableIR `LocalizeEntries` class.

Move localizeEntries from function to IR

---

python/hail/docs/tutorials/01-genome-wide-association-study.ipynb
python/hail/docs/tutorials/plotting.ipynb
python/hail/expr/aggregators/aggregators.py
python/hail/methods/statgen.py
python/test/hail/methods/test_statgen.py
src/main/scala/is/hail/methods/LinearRegression.scala
src/main/scala/is/hail/methods/LogisticRegression.scala
src/main/scala/is/hail/methods/Skat.scala
src/main/scala/is/hail/stats/LogisticRegressionModel.scala
src/main/scala/is/hail/stats/RegressionUtils.scala
src/test/scala/is/hail/methods/SkatSuite.scala
src/test/scala/is/hail/testUtils/RichMatrixTable.scala

This PR incorporates @cseed 's changes from #3477, brings everything up to date with master, and adds/fixes the following:
- added a test for linreg with no covariates against R, and deleted old `test_linear_regression_with_no_cov` since that still had intercept.
- extended Skat to work without covariates and added test that it runs, but it’s hard to test result against R given that the latter fails with no covariates: `Error in solve.default(t(X1) %*% X1) : 'a' is 0-diml`. The result look "reasonable" to me.
- added req of at least one covariate for logreg in doc and code. It's going to be painful to get logistic to take no covariates, we can always come back to it if priority goes up. Related fun breeze behavior: `a(::, *) *:* b` with `a` an `(n, 0)` matrix and `b` an `n`-vector has …

Optional intercept in regressions and skat

---

src/main/scala/is/hail/expr/ir/MatrixIR.scala

FYI @lfrancioli @konradjk 
TableMapRows doesn't have this problem.

fixed memory leak in MatrixMapRows.

---

python/hail/ir/matrix_ir.py
python/hail/table.py
python/test/hail/test_ir.py
src/main/scala/is/hail/expr/Parser.scala
src/main/scala/is/hail/expr/ir/MatrixIR.scala
src/main/scala/is/hail/expr/ir/Pretty.scala
src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
src/main/scala/is/hail/table/Table.scala
src/test/scala/is/hail/expr/ir/IRSuite.scala
src/test/scala/is/hail/expr/ir/MatrixIRSuite.scala

This represents the 'inverse' of LocalizeEntries. It combines two
tables, one representing the 'table view' of a MatrixTable's rows and
entries (with the entries as an array of structs), and the second
representing the column data of the MatrixTable.
UnlocalizeEntries is constructed from two TableIRs (rowsEntries and
cols) and a String (entriesFieldName). entriesFieldName must refer
to an array of structs. All elements of the entriesFieldName field
must be present and have the same length as the number of rows in
cols.

Add UnlocalizeEntries IR Node

---

Dockerfile.pr-builder
Makefile
hail-ci-build-image
python/hail/dev-environment.yml
python/hail/environment.yml
python/hail/expr/aggregators/aggregators.py
python/hail/expr/expressions/base_expression.py
python/hail/expr/functions.py
python/hail/ir/ir.py
python/hail/matrixtable.py
python/hail/plot/plots.py
python/hail/table.py
python/hail/typecheck/__init__.py
python/hail/typecheck/check.py
python/test/hail/table/test_table.py

Had to refactor some things to deal with subtle importing graphs.
I also left the hl.scan stuff using functools, because I'm not sure that
we can fix that as easily.
fixes #4112

Revert functools to decorator

---

python/hail/expr/aggregators/aggregators.py
python/test/hail/expr/test_expr.py

@konradjk asked for weighted OLS, which is just a transformation of `x` and `y` by `sqrt(w)`. Currently `sqrt` is done `1 + len(x)` per record rather than once because you can't bind inside an aggregate. If that's a bottleneck, I could rework the aggregator to pass the w through to scala and avoid taking sqrt altogether. But for now this simple change at the Python level seems reasonable.

added weights to linreg

---

python/hail/docs/index.rst

accidentally duplicated this link when I was rebasing #4097.

remove duplicate api link from sidebar

---

python/hail/expr/expressions/expression_utils.py

Fix usage of _hail_package so that eval_expr doesn't crash if
used without `hl.init` first.

Fix usage of _hail_package in eval_expr

---

python/test/hail/expr/test_expr.py
src/main/scala/is/hail/annotations/aggregators/KeyedRegionValueAggregator.scala

Dictionaries in regions need to be stored in sorted order.
Fixes #4170.

fix KeyedRegionValueAggregator.result()

---

python/hail/stats/linear_mixed_model.py
python/test/hail/stats/test_linear_mixed_model.py

The point of setting the following values at the end of fit() is so they won't be mutated by further calls to `compute_neg_log_lkhd`:
```
self._residual_sq = self.sigma_sq * self._dof
self._d_alt = self._d
self._ydy_alt = self._ydy
self._xdy_alt[1:] = self._xdy
self._xdx_alt[1:, 1:] = self._xdx
```
But when I added `h_sq_standard_error` above them, it introduced a very subtle bug by calling `compute_neg_log_lkhd` at a value `1e-4` to the right of the fit `log_gamma`. This caused both the scala and python routes to use the value of `self._residual_sq` at `log_gamma` but the value of `self._d_alt` and the rest at `log_gamma + 1e-4`. So these two routes remained consistent, but sometimes the alternate residual was coming up greater than the null residual, resulting in negative chi_sq stat. …

fix LinearMixedModel bug

---

python/hail/expr/aggregators/aggregators.py

this prevents the intercept warning from triggering whenever there are weights

fix intercept warning

---

build.gradle

This PR adds `--master local` to `PYSPARK_SUBMIT_ARGS` for the Gradle `makeDocs` target, so that the Sphinx notebook tests do not try to spawn distributed Spark jobs when running by coincidence on a Spark master. Now `makeDocs` locally under macOS and locally on an AWS EMR Spark cluster master.
This PR also removes `PYSPARK_SUBMIT_ARGS` from the `makeDocsNoTest` target, since Sphinx does not run notebook tests for that target.

Added "--master local" so makeDocs will run locally even on a Spark cluster master

---

src/main/scala/is/hail/expr/AnnotationImpex.scala
src/main/scala/is/hail/rvd/RVD.scala

Add flag to importAnnotation. Allows most callers to use the pre- #4094 behavior.

importAnnotation bugfix

---

src/main/scala/is/hail/io/index/IndexWriter.scala

`_toPretty` should have been `parsableString()`

fix type in index metadata

---

python/hail/methods/qc.py
src/main/scala/is/hail/methods/VEP.scala

@konradjk once this builds i'll see what header is produced and run that by you for reasonable-ness. Should we be testing vep with `csq=true` as well? I could produce a second copy of the gold standard with that option and add it to the script, which would also test that this string is created correctly

add VEP csq header definition to globals when csq=true

---

src/main/scala/is/hail/expr/Parser.scala
src/main/scala/is/hail/table/Table.scala
src/main/scala/is/hail/utils/Graph.scala
src/main/scala/is/hail/variant/MatrixTable.scala
src/test/scala/is/hail/expr/ir/IRSuite.scala

This is one of the first steps in building out relational IR generation
from Python. We need the ability to store IR nodes in a JVM map because
of things like MatrixLiteral and TableLiteral.

Make the parser faster; add support for cached IR nodes

---

Dockerfile.pr-builder
hail-ci-build-image

This consolidates all the apt-get dependencies into one line and brings them into line with [Dockerfile best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run).
It also sets the default user to a non-root user, thus limiting what can go wrong if we have security holes in the PR builder.

Update the PR image

---

Dockerfile.pr-builder
hail-ci-build-image

gcloud isn't in the path so no builds are copying the artifacts. I also need to fix the `hail-ci-build.sh` to fail if the gcloud commands fail, but this is quick fix before I go to bed.

Fix the build image

---

build.gradle
hail-ci-deploy.sh

A forthcoming change to the hail ci system will introduce deployment. This change adds `hail-ci-deploy.sh` which replicates the ["Deploy Website"](https://ci.hail.is/admin/editRunType.html?id=buildType:HailSourceCode_HailMainline_DeployWebsite&runnerId=RUNNER_29) and ["Deploy Google Cloud"](https://ci.hail.is/admin/editRunType.html?id=buildType:HailSourceCode_HailMainline_DeployDocsAndGoogleCloudSpark220&runnerId=RUNNER_10) TeamCity jobs.
My general thinking for deploy jobs from the CI is that, for the time being, we'll hardcode a mapping from GitHub repository to [Kubernetes Secret](https://kubernetes.io/docs/concepts/configuration/secret/). That's where this `/secret/ci.hail.is-web-updater-rsa-key` will come from. Moreover, the CI will always authorize a gcloud account (again with a …

Add hail-ci-deploy.sh for master

---

python/test/hail/expr/test_expr.py
src/main/scala/is/hail/expr/ir/Emit.scala

Fixes #3729.
The problem with the If in the array emitting logic was that the lengths were being stored in two different local variables, which were only being evaluated/stored depending on which branch was taken. Because we store that information in another local variable, `xvcond`, and check it again when we're actually consuming the array, the analyzer was checking both branches again for that step, and being unhappy that the local variable where the length is stored could have been unpopulated. I have fixed this by only having one branch and doing both the length calculation and the rest of the stuff there.

fix deforested If in Emit

---

src/main/scala/is/hail/methods/Nirvana.scala
src/main/scala/is/hail/methods/VEP.scala

This causes bad behavior when preemptible nodes are involved.

Don't count in VEP or Nirvana.

---

python/hail/dataset.py

We fixed this a while ago in 0.2, but apparently we forgot to back port to 0.1.

Fix IBD Prune Docs in 0.1

---

hail-ci-deploy.sh

I'm generalizing the CI's deploy system. https://github.com/hail-is/ci/pull/77
In particular, I no longer assume you need to authorize from to a gcloud account. Instead, I just mount you a volume. Each repo will have some secrets that it can authorize with.
This is safe to merge now because before the CI changes go in, this just re-authorizes. When the CI changes merge, we'll go back to authorizing once, except that the command is in `hail-ci-deploy.sh` instead of baked into the CI system.

Ci changes

---

python/hail/methods/statgen.py
python/test/hail/methods/test_statgen.py
src/main/scala/is/hail/methods/Skat.scala

This removes the name conflict with the `key` attribute of a table. I also changed the test `count` to `_force_count` to be sure they aren't ever optimized.

change field 'key' to 'id' in skat

---

cluster-sanity-check.py
hail-ci-build.sh

I think this will, in practice, catch a lot of the issues we've created in the recent past with blowing memory or dataproc incompatibilities.

cluster sanity check

---

src/main/scala/is/hail/expr/ir/Compile.scala
src/main/scala/is/hail/expr/ir/Infer.scala
src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
src/main/scala/is/hail/expr/ir/Simplify.scala
src/main/scala/is/hail/expr/ir/TypeCheck.scala
src/main/scala/is/hail/expr/types/Type.scala
src/test/scala/is/hail/expr/ir/IRSuite.scala

The fix is somewhat subtle and relies on PruneDeadFields, which is called (a) by the optimizer and (b) by the compiler, so this is safe. The important piece is that the process of upcasting strips requiredness.
This isn't a great design, but I'm comfortable with it for now since I hope physical types will solve this in The Right Way™ before 0.2 release anyway.
fixes #4134

Fix the If unification problem

---

python/hail/table.py
python/test/hail/matrixtable/test_matrix_table.py

so that keys = None if the expressions are a prefix of the matrix table keys.
@konradjk

relax table-matrix-table join check on keys

---

src/main/scala/is/hail/expr/ir/Simplify.scala

If cols() sorts on the column key, then this optimization doesn't work for expressions with scans since they'd scan in a different order.
(I also pulled out the `ContainsAgg` check for the next one, since MatrixFilterCols can't handle aggregations anyways.)

don't swap ColsTable and MapCols if MapCols contains a scan

---

hail/src/main/c/Makefile

User reported that hail wouldn't build on an EMR instance.  It turns out that g++-4.8.x doesn't
support "-march=sandybridge", but has the same architecture called "-march=corei7_avx". 
With this PR the Makefile tests a trivial compilation to pick a -march which works for the
particular $(CXX).

use -march=corei7_avx with g++-4.8.x

---

hail/src/main/scala/is/hail/expr/ir/add-ir-checklist.txt

The method you need to add when adding IR is not called `render`, `__str__` is implemented in `BaseIR` and calls out to `render`.
See #4236 for more details

Fix docs for adding pretty printing in python

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/test/hail/matrixtable/test_matrix_table.py

I believe this is the change discussed in today's meeting.
mt.s should not sort the column but mt.cols().s should. Same for entry fields. Row fields are unchanged.

Change behavior of _to_table for column and entry fields

---

hail/python/hail/ir/ir.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/FoldConstants.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/IsConstant.scala
hail/src/main/scala/is/hail/expr/ir/IsScalarConstant.scala
hail/src/main/scala/is/hail/expr/ir/LiftLiterals.scala
hail/src/main/scala/is/hail/expr/ir/Optimize.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/RewriteBottomUp.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/table/Table.scala
hail/src/main/scala/is/hail/variant/MatrixTable.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/expr/ir/FoldConstantsSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/IntervalSuite.scala
hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/TestUtils.scala
hail/src/test/scala/is/hail/expr/ir/UtilFunctionsSuite.scala
hail/src/test/scala/is/hail/methods/TableSuite.scala

This is a big win for moving code from
executed-many-times-on-workers to
executed-one-on-driver.
Along the way, I realized that having a name parameter
on the Literal node was unnecessary, and removed it. I
can split this up if requested.

Improve constant folder to generate literals.

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/expr/functions.py
hail/python/hail/ir/ir.py
hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/expr/Parser.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

The core of the change is the MakeArray.unify method, and Python only passing the type when constructing an empty array. I added strong assertions about types. to that and the node constructor.

Fix MakeArray

---

hail/Makefile

cc: @cseed @tpoterba
docker does not pull an image specified in --cache-from, so we need to
explicitly pull it before trying to use it as a cache

fix docker image cacheing

---

hail/src/main/scala/is/hail/expr/types/TArray.scala
hail/src/main/scala/is/hail/expr/types/TBaseStruct.scala
hail/src/main/scala/is/hail/expr/types/TDict.scala
hail/src/main/scala/is/hail/expr/types/TFloat32.scala
hail/src/main/scala/is/hail/expr/types/TFloat64.scala
hail/src/main/scala/is/hail/expr/types/TSet.scala
hail/src/main/scala/is/hail/expr/types/TString.scala
hail/src/main/scala/is/hail/expr/types/Type.scala
hail/src/main/scala/is/hail/table/Table.scala
hail/src/main/scala/is/hail/utils/ShowStrConfig.scala

Important differences:
- quotes around strings, always. this fixes problems
like newlines which we weren't handling correctly
- don't default to json, use python-repr-like syntax
- print structs and tuples the same (like tuples). This
might be contentious, but it'll only happen inside
nested objects where the inline field names is going
to blow out character limits anyway.
It should still be totally parsable (won't generate
patterns that are ambiguous), though we'd need to
write a separate parser for it.

Add new string representation of values for Table.show

---

hail/python/hail/matrixtable.py
hail/python/hail/table.py

Remove the following syntaxes:
- mt[:, col key]
- mt[row key, :]
- mt[:, :]
- ht[:]
fixes #2694
fixes #4027

Clean up relational slice syntax 1

---

hail/hail-ci-deploy.sh

I changed ci.hail.is to point to kubernetes, so this won't work any more.  The new web site is ready to go (live at test.hail.is) and I will switch it over hail.is over late tonight.  It needs to go down for a short while to get new Let's Encrypt credentials.

Remove doc deploy to ci.hail.is

---

Dockerfile.pr-builder
hail-ci-build-image
hail/hail-ci-deploy.sh
needs-redeploy.py

Next step is to fold in the other subprojects (batch, ci, scorecard, the web site, etc.), and we don't want to redeploy hail if batch changes (and vice versa).

Conditional deploy

---

hail/python/hail/methods/impex.py

The code block is being rendered as prose because there's no blank line between the prose and the code-block syntax.

Fix minor doc formatting issue in import_bgen

---

hail/src/main/scala/is/hail/io/RowStore.scala
hail/src/main/scala/is/hail/rvd/OrderedRVD.scala
hail/src/main/scala/is/hail/sparkextras/ContextRDD.scala

Factor out some reusable pieces of the `shuffle` implementation, and fold it into `repartition`.

Refactoring RVD interface, pt. 4

---

hail/python/hail/methods/statgen.py

I feel pretty good about pc_relate at this point. It's stood up to interrogation on a few real world datasets. We have automated testing of it. I think it's still a tricky method to use if you don't understand the underlying assumptions (which are listed here, specifically the limitations of PC Relate's estimator for "individual-specific allele frequency").
@cseed @tpoterba @jbloom22

pc_relate is not experimental any more

---

site/site.sh

[This is what the nginx docker image does](https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile#L136-L137).
The polls will finish first so we'll still see those logs.

Include NGINX logs in pod logs

---

hail/python/hail/__init__.py
hail/python/hail/context.py
hail/python/hail/docs/utils/index.rst
hail/python/hail/utils/__init__.py
hail/python/hail/utils/hadoop_utils.py
hail/python/hail/utils/misc.py

1. The default log path includes the version and a
timestamp. This will help people avoid overwriting
log files, which will help us.
2. Echo the full path to the log after the hail logo
3. Add a function `hl.copy_log` which can be used to
copy the session log to a hadoop-api-compliant
location.

Implement a set of logging improvements

---

site/hail.nginx.conf

This doesn't really matter, but seems best to keep the regex as limited as possible.

Capital letters are not allowed in k8s pod names

---

batch/get-deployed-sha.sh
batch/hail-ci-deploy.sh
hail-ci-build.sh
hail-ci-deploy.sh
hail/get-deployed-sha.sh
hail/hail-ci-deploy.sh
scorecard/Makefile
scorecard/deployment.yaml.in
scorecard/get-deployed-sha.sh
scorecard/hail-ci-deploy.sh
site/.gitignore
site/Makefile
site/get-deployed-sha.sh
site/hail-ci-deploy.sh
site/run-letsencrypt.sh
site/site-deployment.yaml.in

make appropriate targets phony
include sha in site deployment (like batch)
moved run-letsencrypt target body to shell script (no changes, but easier to work with)
This won't work until this CI PR goes in and is deployed: https://github.com/hail-is/ci/pull/102 (it won't hurt particularly, either.  make push-site will fail and site won't be deployed/up to date)

set up deployment for site

---

ci/deployment.yaml

This generates the CI image using the newest version of batch which includes [a fix](https://github.com/hail-is/hail/commit/c28a3f9863a030dd94ba1a1e350b939bd73adb6d) for using docker in batch jobs.
resolves  #4443

Fix Batch Deployment by updating CI version of batch

---

hail-ci-deploy.sh

cc: @cseed 
I missed this in review. Note that if we have a way to check deployed sha (i.e. get-deployed-sha.sh exists), and the deployed SHA is the same as the current SHA, then the state of the service is unchanged.

Do not redeploy batch and CI constantly

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/methods/misc.py
hail/python/hail/methods/statgen.py
hail/python/hail/table.py
hail/python/hail/utils/java.py
hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/table/Table.scala

`Table._select` got way too complicated (mostly my fault) when key changing moved from `TableMapRows` to `TableKeyBy`. Making `_select` a simple wrapper around `TableMapRows`, and moving the key logic to `key_by`, made both way simpler. I then realized the `key_by` code could be even simpler by adding some rules to the optimizer to clean up the case where all new keys are existing fields.
I actually think some things had gotten broken in the old `_select` (performance wise). In particular, in `split_multi`, in the `split_rows` function with `rekey=false`, I think it's supposed to extend the key from `['locus']` to `['locus', 'alleles']`, but that wasn't happening.
I changed `key_by` to no longer accept `key_by(None)` or `key_by([])`, both of which should now be `key_by()`, which is more …

move _select logic to key_by

---

hail/python/hail/docs/guides/genetics.rst

Fixes #4251
@jbloom22 Is there anything else I should add? Maybe something about the relative performance of each approach? I also thought about using two separate linreg aggregator annotations, but that didn't seem better than the group_by approach.

linreg stratified docs

---

hail/src/main/scala/is/hail/expr/ir/BinarySearch.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/functions/DictFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/SetFunctions.scala
hail/src/test/scala/is/hail/expr/ir/DictFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/SetFunctionsSuite.scala

- For #4014
- Changed behavior of LowerBoundOnOrderedCollection to return `n` if all elements are less than the search value (no lower bound)
- Fixed the interpreter for LowerBoundOnOrderedCollection

IRSuite tests for ToDict and LowerBoundOrderedCollection

---

hail/src/main/scala/is/hail/expr/ir/Simplify.scala

There are two problems with this:
- it is a massive de-optimization if we forward an expensive computation into a loop (e.g. arraymap)
- in the above case, it is an error in if the body of the let is non-deterministic
To do this right we need to build a control flow graph.

remove unconditional let forwarding to single ref

---

hail/install-gcs-connector.sh

Looks like this:
```
(py37) dking@wmb16-359 # ./install-gcs-connector.sh              
To set the active account, run:
$ gcloud config set account `ACCOUNT`
created key [bd10c2da666d327144166cc71ba13075dbd7ea26] of type [json] as [/Users/dking/.hail/gcs-keys/gcs-connector-key.json] for [842871226259-compute@developer.gserviceaccount.com]
mkdir: /Users/dking/anaconda2/envs/py37/lib/python3.7/site-packages/pyspark/conf: File exists
success
```
I tested it by running `python -c 'import hail as hl; hl.read_table("gs://danking/gnomad-test.mt").describe()'`

add gcs connector installer

---

hail/src/main/scala/is/hail/annotations/OrderedRVIterator.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/main/scala/is/hail/rvd/RVDType.scala
hail/src/main/scala/is/hail/table/Table.scala
hail/src/main/scala/is/hail/utils/FlipbookIterator.scala
hail/src/test/scala/is/hail/utils/FlipbookIteratorSuite.scala

This is the precursor to a follow-up PR which removes `IntervalTree`. `IntervalTree` was doing two jobs: handling queries against the range bounds of a partitioner, which have (essentially) no overlap, and in these interval join methods, where they may overlap arbitrarily. It ended up being suboptimal for both use cases. This PR rewrites the interval join methods, which should now be faster, and no longer depends on `IntervalTree`.
The existing interval join methods only supported distinct joins (`product = false`). The implementation I wrote won't work for the `product = true` case, but I have a plan for that, which will fit into the structure I started here.

rewrite interval joins

---

hail/python/hail/matrixtable.py
hail/python/test/hail/methods/test_impex.py

Addresses #4508. Can you double check I can turn off the warning if the col key is an empty struct and not None?

Improve robustness of export_plink and export_gen tests

---

hail/src/main/scala/is/hail/asm4s/package.scala
hail/src/main/scala/is/hail/io/RowStore.scala
hail/src/main/scala/is/hail/nativecode/NativeCode.java
hail/src/main/scala/is/hail/nativecode/NativeModule.scala
hail/src/main/scala/is/hail/utils/package.scala
hail/src/test/scala/is/hail/nativecode/NativeCodeSuite.scala

I was seeing crashes on workers in a local install because the Hail jar was loaded by a Spark class loader rather than the system class loader, so the toString in:
> String name = ClassLoader.getSystemResource("include").toString();
was failing with a null pointer exception.  Fixed this two ways: don't unpack includes on the worker (compilation should only happen on the master) and use the same class loader that loaded the NativeCode object.
Also some reformatting and style changes.

only extract includes on master

---

hail/python/hail/docs/tutorials/01-genome-wide-association-study.ipynb
hail/python/hail/docs/tutorials/03-expressions.ipynb
hail/python/hail/docs/tutorials/05-tables.ipynb
hail/python/hail/docs/tutorials/06-aggregation.ipynb
hail/python/hail/docs/tutorials/07-filter-annotate.ipynb
hail/python/hail/docs/tutorials/08-joins.ipynb
hail/python/hail/docs/tutorials/09-matrixtable.ipynb
site/poll-devel.sh

This also fixes a broken link in site from the devel => 0.2 rename.  See poll-devel.sh.  This is urgent!  I patched it by hand for the moment, but if it redeploys, it will be broken again.

Update tutorial links

---

hail/hail-ci-deploy.sh

This will fix the upload location for 0.2 artifacts, and therefore the broken distribution download link.

deploy artifacts as 0.2, not devel

---

hail/src/main/scala/is/hail/expr/ir/BaseIR.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
hail/src/test/scala/is/hail/expr/ir/RandomFunctionsSuite.scala

Adding a new compiler pass (lowering MatrixIR to TableIR) exposed a problem in Simplify. The logic for preventing some simplifications from triggering if they would introduce non-determinism was broken, and fixing it required a pretty complete overhaul. Fortunately, I think it's now a lot simpler.
Besides the rewrite of the high level Simplify architecture, I also:
* Changed `testRepartitioningSimplifyRules` to something that failed in the old version.
* Changed the `copy` signature on the IR hierarchy to be more precise (to avoid unnecessary coercions).
* Grouped the Simplify rules into IR, MatrixIR, and TableIR. After the reorganization, a couple of rule redundancies became evident.
* A couple of vals in PruneSuite required running the compiler. When I had a bug in Simplify, this was …

Simplify fix

---

hail/hail-ci-build.sh

cc: @tpoterba 
Previously stderr ended up in the build log while stdout ended up in the per-task log. This change ensures all output (err or out) goes to the log. The only information in the build log is about the orchestration script. This should make debugging CI build failures much easier because stderr and stdout are in one place.

also send stderr to log file

---

hail/python/hail/ir/matrix_ir.py
hail/python/hail/ir/table_ir.py
hail/python/hail/matrixtable.py
hail/python/test/hail/table/test_table.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/Parser.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/types/TStruct.scala
hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/main/scala/is/hail/rvd/RVDType.scala
hail/src/main/scala/is/hail/table/Table.scala
hail/src/main/scala/is/hail/utils/ErrorHandling.scala
hail/src/main/scala/is/hail/variant/MatrixTable.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/MatrixIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
hail/src/test/scala/is/hail/methods/LocalLDPruneSuite.scala

Preparation for compiler pass lowering MatrixIR to TableIR. Make LocalizeEntries and UnlocalizeEntries preserve column values, so they are completely information preserving and inverse to each other.

IR conversion between Table and MatrixTable

---

scorecard/.gitignore

There is an assumption that the secrets file for scorecard will be in a folder called secrets in the scorecard directory. This makes sure that it is harder to commit github API tokens.

Add secrets to scorecard gitignore

---

hail/python/hail/context.py
hail/python/hail/expr/expressions/expression_utils.py
hail/python/hail/ir/base_ir.py
hail/python/hail/ir/ir.py
hail/python/hail/ir/matrix_ir.py
hail/python/hail/ir/renderer.py
hail/python/hail/ir/table_ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/hail/matrixtable.py
hail/python/hail/methods/impex.py
hail/python/hail/methods/misc.py
hail/python/hail/methods/qc.py
hail/python/hail/methods/statgen.py
hail/python/hail/stats/linear_mixed_model.py
hail/python/hail/table.py
hail/python/hail/utils/backend.py
hail/python/hail/utils/misc.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

@cseed - Here's the minimal changes needed as a proof of concept. I converted `_select` to use `TableMapRows`, `_select_globals` to use `TableMapGlobals`, `count` to use `TableCount`, and `parallelize` to use `TableParallelize`.
Future to-do items:
- Add TVoid type to Python (interpret needs to know how to return the result -- i.e. TableExport)
- Add parser support and tests for TableExport, TableAggregate, and TableWrite.
- Fix pretty/parser/Python render for some IRs such as TableRange

First steps for Python Table to use IR

---

hail/src/main/scala/is/hail/io/bgen/BgenRDDPartitions.scala
hail/src/main/scala/is/hail/methods/LocalLDPrune.scala
hail/src/test/scala/is/hail/annotations/UnsafeSuite.scala

Can't get rid of it yet since Type alignment is still used pervasively.
**Stacked on PTypes 19**

PTypes 20: Convert references to Type.byteSize 

---

gateway/hail.nginx.conf.in
notebook/.gitignore
notebook/Makefile
notebook/deployment.yaml.in
notebook/hail-ci-deploy.sh
projects.txt

This adds the minimal resources to k8s to allow us to modify the gateway's configuration to include redirects for https://notebook.hail.is. Currently, that domain will timeout, but there should otherwise be no errors introduces to the k8s system.
cc: @cseed

[Notebook] Add server to Gateway

---

image-fetcher/.gitignore
image-fetcher/Dockerfile
image-fetcher/Makefile
image-fetcher/SECRETS.md
image-fetcher/deployment.yaml.in
image-fetcher/fetch-image.sh
image-fetcher/hail-ci-deploy.sh
projects.txt

A [daemonset](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) which, given a list of images, constantly tries to keep those images cached on the nodes docker container. Because the preemptible nodes that execute CI builds are tainted, this will only execute on the main nodes and the non-preemptibles, which is the functionality we desire for now because this tool will be used to ensure `notebook` worker images are always cached.
cc: @cseed

[Notebook] Image Fetcher

---

notebook/Makefile

fixes  #4656 
The deploy service account does not have privileges to create anything in `batch-pods` (as noted by the error message in #4656). The correct namespace in which to create the notebook service is `default`. That is rectified here with the `-n` or "namespace" argument.

Fix notebook deploy

---

hail/.gitignore
image-fetcher/.gitignore

- `hail/python/dist` is generated by `setup.py` when publishing to PYPI. It is strictly build artifacts and should never be checked in.
- `image-fetcher/deployment.yaml` is auto-generated by the `Makefile`

A couple more gitignores

---

ci/Makefile
ci/ci/ci.py
ci/ci/pr.py
ci/ci/prs.py
ci/test/test-ci.py

1. Makefile is a bit more resilient to changes in the `dk-test` instance that is used to route traffic from GitHub to a local laptop test. It now looks up the ip. The zone is still hardcoded and it's moved to zone `us-central1-a`. The name is also hardcoded to `dk-test`.
2. I renamed `is_running` to `is_building`
3. When a job refresh happens, it is now `PRS` responsibility to determine what to do. It starts the same as it always does, updating existing PRs with new job information. The difference is that it tracks which (believed to be) currently building jobs are not seen in the job list. All such jobs are re-built, under the assumption that the job must have failed.
cc: @cseed 
This should allow CI to recover from the loss of batch.
Fixes #4654.

[CI] Refresh From Batch

---

ci/ci/prs.py

`remove` throws a `KeyError` if the argument is not in the set, `discard` does nothing in that case.

[CI] Do not error if a job for an unknown PR is received

---

notebook/get-deployed-sha.sh

The default namespace of the CI job is batch-pods, so
it fails to find the notebook deployment

[notebook] fix get-deployed-sha.sh

---

ci/ci/pr.py

If CI notices a job is now missing we must be in the state `Building`, not `Buildable`.

[CI] fix assertion

---

ci/ci/ci.py
ci/ci/prs.py

#4659 teaches CI to recover from a build job gone missing, but
I neglected to teach CI how to recover from a deploy job gone
missing. This follows the same strategy but for deploy jobs.
If a deploy job is not found in the list of refreshed jobs
it is simply removed from the deploy_jobs map. The next heal
stage of CI will kick off a new batch job for whatever the
latest undeployed SHA is.

[ci] Recover from missing deploy jobs as well

---

ci/ci/ci.py
ci/ci/pr.py

At some point in the distant past I fixed `refresh_review_state` (full state refresh from GH) but failed to fix `github_pull_request_review` (where web hooks come in). As a result, CI is very confused about https://github.com/hail-is/hail/pull/4644, wherein a `COMMENTED` review came in after a `APPROVED` review. I eliminated the duplicate, incorrect implementation of review status and replaced references to it with references to the correct (and tested) review status function.

[CI] fix review status calculation

---

notebook/environment.yml

had the wrong name. Not used by deployment, just for developers.

Fix pip install dependency name

---

image-fetcher/Dockerfile
image-fetcher/Makefile
image-fetcher/fetch-image.sh
notebook/notebook/notebook.py

Now image fetcher asks the running notebook image what worker image its using and pulls that.
Also, add a five second sleep after the service's endpoints are configured. Hopefully that prevents these intermittent gateway errors.

Fix image fetcher and notebook

---

hail/src/main/scala/is/hail/nativecode/NativeCode.java

Throw a useful error message when the resource does not exist instead of  throwing an NPE.

[hail] Useful error message instead of NPE on missing resource

---

ci/Makefile
ci/hail-ci-deploy.sh

Previously everything was fine because the deploy script called
both the image creation and the deploy targets in make. However,
if we need to manually deploy, it is easy to forget this. I
modified the Makefile to make the dependency explicit.

[ci] make dependency of image and deploy explicit in Make

---

hail/python/hail/dev-environment-py3.7.yml
hail/python/hail/typecheck2/check.py

This adds preliminary support for python 3.7 including a conda env with relaxed dependencies compared to what we currently ship. I've tested this manually and found no problems aside from a lot of warnings about upcoming depreciation in new versions of dependencies.
The value of `__origin__` changed for many types from 3.6 to 3.7, which is why the check function map needed to be expanded.

Experimentally Support python 3.7

---

hail/python/hail/experimental/phase_by_transmission.py

Background for this is the following: I have data with quads (parents + 2 offspring). This is represented as two trios in the trio matrix format. When exploding the trio matrix, I'm left with duplicate columns for the parents but no way of backtracking which parent corresponds to which trio.
More generally the previous implementation did not allow to carry any trio-specific data over, which was somewhat restrictive.

Added options to keep col/entry trio data to explode_trio_matrix

---

hail/src/main/scala/is/hail/sparkextras/MultiWayZipPartitionsRDD.scala
hail/src/main/scala/is/hail/utils/FlipbookIterator.scala
hail/src/test/scala/is/hail/utils/FlipbookIteratorSuite.scala

Applies on top of #4713 
Compared to previous versions, this uses a priority queue rather than a linear search to create the list of returned items. We return tuples so that the caller can construct arrays as appropriate rather than constructing an array of values here.

Add multiZipJoin to FlipbookIterator

---

hail/python/hail/__init__.py
hail/python/hail/context.py
hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/io/RowStore.scala
hail/src/test/scala/is/hail/SparkSuite.scala

currently can be used to control whether the decoder/encoder uses c++ or jvm bytecode, although we're not yet bundling the lz4 dependency so I don't think this will work on a default cloudtools cluster yet.

add function for setting feature flags from python

---

hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
hail/src/test/scala/is/hail/expr/ir/StringFunctionsSuite.scala

the default Scala behavior is to strip trailing empty strings. I think it's pretty reasonable to expect Hail to mimic python behavior, but I'm not sure if this counts as a breaking change?
Fixes #4740.

make split behavior mimic python

---

hail/src/main/scala/is/hail/expr/ir/IRBuilder.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Optimize.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/RewriteBottomUp.scala
hail/src/main/scala/is/hail/expr/ir/RewriteTopDown.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/types/TStruct.scala
hail/src/main/scala/is/hail/io/bgen/BgenRDD.scala
hail/src/main/scala/is/hail/io/bgen/BgenRDDPartitions.scala
hail/src/main/scala/is/hail/io/bgen/IndexBgen.scala
hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala
hail/src/main/scala/is/hail/table/Table.scala
hail/src/main/scala/is/hail/utils/richUtils/RichMap.scala
hail/src/main/scala/is/hail/variant/MatrixTable.scala
hail/src/test/scala/is/hail/expr/ir/MatrixIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
hail/src/test/scala/is/hail/expr/ir/RandomFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
hail/src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala

* Add a lightweight DSL for writing IR in Scala, which made the lowerings much easier to write, and read. It is implemented in `IRBuilder`, and can be used by importing `IRBuilder._` into scope. It's not complete, and I want to make it eagerly typecheck eventually, but we can build on it.
* Make `execute` protected on `MatrixIR` and `TableIR`, making `Interpret` the official place to execute IR.
* Add a compiler pass lowering some `MatrixIR` to `TableIR`. The `Interpret` gateway to `execute` always lowers, so we can safely remove the execute methods of IR nodes which are rewritten by the lowering.
* Fix `LoadBgen` to not create entries arrays when `dropCols` is true.

lower MatrixIR to TableIR

---

hail/python/hail/ir/__init__.py
hail/python/hail/ir/utils.py
hail/python/hail/table.py
hail/src/main/scala/is/hail/table/Table.scala
hail/src/test/scala/is/hail/methods/TableSuite.scala

- still more methods to convert -- these were the easiest to do
- removed corresponding methods on Table in Scala where possible
Methods:
- GroupedTable.aggregate
- Table.key_by
- Table.filter
- Table.union
- Table.head
- Table.repartition
- Table.join
- Table.rename
- Table.order_by
- Table.explode
- Table.distinct

Python Table methods to IR

---

hail/src/main/resources/include/hail/Decoder.h
hail/src/main/resources/include/hail/Encoder.h
hail/src/main/scala/is/hail/cxx/Definition.scala
hail/src/main/scala/is/hail/cxx/PackDecoder.scala
hail/src/main/scala/is/hail/cxx/PackEncoder.scala
hail/src/main/scala/is/hail/io/RowStore.scala
hail/src/test/scala/is/hail/nativecode/NativeDecoderSuite.scala
hail/src/test/scala/is/hail/nativecode/NativeEncoderSuite.scala

This basically just pulls out the logic from the `NativeDecoder` and `NativeEncoder` stuff in RowStore.scala into their own objects, and dynamically generates a c++ class for the row type. (The only things that have changed between `NativeDecoder`/`cxx.PackDecoder` and the encoders are the `apply` functions; I'm generating an Encoder class that inherits NativeObj instead of relying on the wrapper classes in `Encoder.h` and `Decoder.h`.
This mostly felt like it made things easier to reason about when I started writing the full-stage code generation stuff, but I've pulled it out here as a separate PR.
cc @cseed

make Encoder/Decoder generate cpp classes

---

hail/python/hail/expr/expressions/base_expression.py

The check for col fields was always returning false, sending col
fields to aggregate_entries
fixes #4776

Fix aggregation_method() used in plotting

---

batch/Makefile
batch/test-locally.sh
batch/test/test_batch.py

Without this `make test-local` fails because there is no running server. This ensures that `make test-local` first starts a server to test against.
Recreated for stacked PRs from #4785
---
The `until curl ...` nonsense is because the server takes some time to start up, so we poll until we get a successful return value from `curl`. `-f` means return non-zero-exit-code on failure. `-L` means follow redirects (not really necessary here, but I think it's good practice to use `-L`).
`BATCH_USE_KUBE_CONFG=1` tells batch to use the latent kubernetes configuration, which means the developer must already have set up `kubectl`. This is a reasonable expectation for a developer of `batch`.
The `trap cleanup EXIT` ensures we run cleanup before the shell exits. `trap "exit 24" INT TERM` converts …

[batch][dag1] Teach batch to test itself locally

---

hail/python/hail/ir/base_ir.py
hail/python/hail/ir/ir.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/Parser.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/main/scala/is/hail/expr/types/MatrixType.scala
hail/src/main/scala/is/hail/expr/types/TableType.scala
hail/src/main/scala/is/hail/expr/types/virtual/TStruct.scala
hail/src/main/scala/is/hail/io/index/IndexReader.scala
hail/src/main/scala/is/hail/rvd/RVDType.scala
hail/src/main/scala/is/hail/table/Table.scala
hail/src/main/scala/is/hail/utils/Graph.scala
hail/src/main/scala/is/hail/variant/MatrixTable.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/methods/ExprSuite.scala

@cseed Can you look over this for structure before I assign it randomly? There's three things I am not happy about or want double checked:
1. I had to replicate the parsing code for `quoted_literal` etc. between the two parser classes. I couldn't figure out how to have the function in one place and be able to call it.
2. I debated back and forth what the `repsepUntil` and `repUntil` interface should look like. I decided to make it take the desired tokens instead of comparing to a string or any value because that seems more error proof and explicit. However, the users of the function have something like this now `repsepUntil(it, f, PunctuationToken(","), PunctuationToken("}"))`, which is quite verbose. I thought about making a second function that took string arguments and converted it to …

Reimplemented IR Parser

---

batch/Dockerfile
batch/Dockerfile.test
batch/setup.py

Now that we are using proper python packages and modules, we can use pip dependencies instead of explicitly writing out the dependencies in the `Dockerfile`.

[batch][dag3] Use pip dependencies

---

batch/Dockerfile
batch/Dockerfile.test
batch/batch/api.py
batch/batch/requests_helper.py
batch/batch/server/__init__.py
batch/batch/server/globals.py
batch/batch/server/server.py

1. Separating the `apk update` from the `apk add` means that if the apk package repository metadata changes (say, the URL of some repository changes) and we change our `apk add` line (say we add a new package), then the `apk add` will fail (e.g. because it has an out of date URL for the repository that should contain the new package). The `apk add --no-cache ...` invocation is essentially the same as `apk update && apk add ... && rm -rf /path/to/repo/cache`. When using docker, it is good practice remove unnecessary files so that they do not get included in the "image diff" for that line of the Dockerfile. `apk add --no-cache ...` succinctly performs exactly what we want.
2. Keeping each package on a separate line and sorting those lines makes diffs easy-to-read with one line per new …

[batch][dag5] Cleanup Dockerfiles

---

batch/Dockerfile
batch/Dockerfile.test

@jigold I screwed up the stacked PRs so I'll need reapprovals. Sorry :(
---
1. Separating the `apk update` from the `apk add` means that
if the apk package repository metadata changes (say, the
URL of some repository changes) and we change our `apk add`
line (say we add a new package), then the `apk add` will
fail (e.g. because it has an out of date URL for the
repository that should contain the new package). The
`apk add --no-cache ...` invocation is essentially the same
as `apk update && apk add ... && rm -rf /path/to/repo/cache`.
When using docker, it is good practice remove unnecessary
files so that they do not get included in the "image diff"
for that line of the Dockerfile. `apk add --no-cache ...`
succinctly performs exactly what we want.
2. Keeping each package on a separate line …

[batch][dag5] Cleanup Dockerfile's

---

hail/python/hail/ir/matrix_ir.py
hail/python/hail/matrixtable.py
hail/python/hail/methods/statgen.py
hail/src/main/scala/is/hail/expr/Parser.scala
hail/src/main/scala/is/hail/variant/MatrixTable.scala

- converted aggregateColsByKey, aggregateRowsByKey, keyRowsBy, keyColsBy, explodeRows, explodeCols, filterCols, filterRows, filterEntries, select_*, annotate_*,
- deleted unused Scala methods

Python MatrixTable to IR

---

notebook/notebook/notebook.py
vdc/gcp-config.yaml.in

@tpoterba @jbloom22 a few more things to fix for the workshop. I was using a too powerful kubernetes command to look up worker pods and services for the admin page. I now use a restricted form of it that is permitted by our security policy.
We also are missing the non-preemptible node pool (!), so this adds that to our gcp-config.
cc: @cseed

More workshop fixes

---

hail/python/hail/expr/builders.py
hail/python/hail/ir/ir.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/IsConstant.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Follow-up PRs will use this for better error messages in places like require_biallelic

Refactor Die to take a string IR child

---

notebook/notebook/notebook.py
notebook/notebook/templates/workers.html

- two network requests instead of four now that we know the name of both the service name and pod name
- use try-catch to avoid 500ing if a user hits `GET /new` and their service or pod is already gone (for whatever reason)

[notebook] Make notebook deletion reliable

---

hail/src/main/scala/is/hail/cxx/Compile.scala
hail/src/main/scala/is/hail/cxx/Definition.scala
hail/src/main/scala/is/hail/cxx/PackDecoder.scala
hail/src/main/scala/is/hail/cxx/PackEncoder.scala
hail/src/main/scala/is/hail/cxx/RVDEmitTriplet.scala
hail/src/main/scala/is/hail/cxx/RegionValueIterator.scala
hail/src/main/scala/is/hail/cxx/TableEmit.scala
hail/src/main/scala/is/hail/cxx/TranslationUnit.scala
hail/src/test/scala/is/hail/nativecode/NativeCodeSuite.scala
hail/src/test/scala/is/hail/nativecode/NativeDecoderSuite.scala
hail/src/test/scala/is/hail/nativecode/NativeEncoderSuite.scala
hail/src/test/scala/is/hail/nativecode/RegionValueIteratorSuite.scala

Builds on: https://github.com/hail-is/hail/pull/4851
Basically, various builders have parents so we can walk up to the translation unit to store the orderings that have been generated.

changes to C++ emit code for (coming) ordering

---

hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/linalg/GridPartitioner.scala

Summing a block-sparse matrix may result in a block-dense vector, in which case maybeBlocks should be None (otherwise the `bis.length < maxNBlocks` assert fails...when rebuilding BlockMatrix in Python/C++ I may change the invariants).
Also extended test cases to serve as regression test.

fix blockmatrix sparse sum bug

---

hail/src/main/scala/is/hail/annotations/CodeOrdering.scala
hail/src/main/scala/is/hail/annotations/ExtendedOrdering.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/utils/Interval.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/annotations/AnnotationsSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala

Builds on: https://github.com/hail-is/hail/pull/4869
ExtendedOrdering on rows and containers now matches CodeOrdering by using lt instead of compare in lt, etc.
FYI @tpoterba since this could potentially (e.g. comparing arrays with nans) cause a user-visible change in behavior.

make sure interpreted and compiled orderings agree

---

hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/methods/LocalLDPrune.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

I noticed that the `testIfWithDifferentRequiredness` and `testMakeArrayWithDifferentRequiredness` were failing after I added the assertion in `upcast` for #4585 
After discussing with @tpoterba , it seemed like it would be okay to allow a required type to be a subtype of an optional type. This PR also includes the assertion, which may cause other tests to fail, and so I have marked it as a WIP.

Allow required types to be subtypes of optional types in isSupertype

---

hail/python/test/hail/methods/test_statgen.py
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Closes #4527
Closes #4761
This is a workaround to prevent issues with MatrixUnionRows when the
entries arrays are in different places in the rvRowType in each of the
children.  Furthermore, it prevents issues if the entries array is
pruned and then re-added later in rebuild, where it will often be
inserted, likely by MatrixMapRows, at the end of the rvRowType. This
rearrangement caused the type equality assertion in Optimize to fail.

Move entries array to end of rvRowType for MatrixUnionRows

---

hail/python/hail/expr/functions.py
hail/python/test/hail/genetics/test_reference_genome.py
hail/src/main/scala/is/hail/expr/ir/functions/ReferenceGenomeFunctions.scala
hail/src/main/scala/is/hail/io/reference/LiftOver.scala
hail/src/main/scala/is/hail/variant/ReferenceGenome.scala
hail/src/test/scala/is/hail/variant/ReferenceGenomeSuite.scala

@konradjk @bw2 Can you double check the test examples in `test_liftover_negative_strand` and give feedback on the interface?

Negative strand option for liftover

---

hail/src/main/resources/include/hail/Ordering.h
hail/src/main/scala/is/hail/cxx/Compile.scala
hail/src/main/scala/is/hail/cxx/Definition.scala
hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/main/scala/is/hail/cxx/EmitTriplet.scala
hail/src/main/scala/is/hail/cxx/PackDecoder.scala
hail/src/main/scala/is/hail/cxx/PackEncoder.scala
hail/src/main/scala/is/hail/cxx/RVDEmitTriplet.scala
hail/src/main/scala/is/hail/cxx/RegionValueIterator.scala
hail/src/main/scala/is/hail/cxx/StagedBaseStructBuilder.scala
hail/src/main/scala/is/hail/cxx/StagedContainerBuilder.scala
hail/src/main/scala/is/hail/cxx/TableEmit.scala
hail/src/main/scala/is/hail/cxx/TranslationUnit.scala
hail/src/main/scala/is/hail/cxx/package.scala
hail/src/test/scala/is/hail/nativecode/RegionValueIteratorSuite.scala

Use in C++ emit of ApplyComparisonOp.
TranslationUnitBuilder keeps a list of orderings.

added C++ codegen support for orderings

---

site/hail.nginx.conf
site/poll-0.2.sh

These follow the same logic as the `/hail` to `/docs/0.1` to redirect,
except they are 307 TEMPORARY REDIRECT because devel and stable may
change to different versions in the future.

[site] make devel and stable 307 redirects

---

hail/python/hail/table.py
hail/python/test/hail/matrixtable/test_matrix_table.py

BUG: fixes #4920
FEATURE: Adds the ability to order by any row expression, not just
top-level fields.

Fix bad error message in Table.order_by, extend functionality

---

hail/python/hail/expr/expressions/expression_utils.py
hail/python/hail/ir/base_ir.py
hail/python/hail/ir/ir.py
hail/python/hail/matrixtable.py
hail/python/hail/table.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Compilable.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/Infer.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/LiftLiterals.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

With good optimization too:
```
hl.eval(hl.utils.range_table(10).annotate(x=[1,2,3]).explode('x').annotate(y=10).index_globals())
```
```
2018-12-05 18:33:33 root: INFO: optimize: before:
(TableGetGlobals
(TableMapRows
(TableExplode x
(TableMapRows
(TableRange 10 12)
(InsertFields
(Ref row)
(x
(Literal Array[Int32] "[1,2,3]")))))
(InsertFields
(Ref row)
(y
(I32 10)))))
2018-12-05 18:33:33 root: INFO: optimize: after:
(MakeStruct)
```

Table get globals

---

hail/src/main/scala/is/hail/io/plink/ExportPlink.scala
hail/src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala

`ExportPlink` was previously modified to resiliently handle failure of a
Spark task by including a per-task UUID. `copyMerge` was not modified to
correctly handle the directories generated by this modified
`ExportPlink`.
For example, if exactly one task out of N fails during `ExportPlink`, the
temporary output directory will contain N+1 partition files. One of
these partition files is corrupted and invalid. The other N are the
output of successful task completion. The invalid file should simply be
ignored by `copyMerge`.
This PR modifies `copyMerge` to take an optional list of files to
merge. If that argument is set to `None`, the original behavior
persists. The original behavior is used by `RichRDD.writeTable` and
`RichRDDByteArray.saveFromByteArrays`. These two methods use the default …

[hail] Correctly merge files in ExportPlink

---

notebook/Makefile
notebook/images/ccg-workshop/Dockerfile

I also added short names to build images for ease of development. You can now say `make hail` or `make ccg-workshop`.

[notebook] permit local R package installation by default

---

notebook/notebook/notebook.py

We want to pack four notebooks per 8-core machine with extra space
for k8s jobs and daemon sets that in practice do not utilize their
required CPU. To prevent a fifth notebook we should set CPU
requirement to x such that:
8 - 4x < x
ergo: x > 8/5 = 1.6, x = 1.6 + 0.001

reduce cpu and memory minimums

---

notebook/images/ccg-workshop/Dockerfile

TIL: R will explode if you haven't set a default CRAN mirror, but merely prints a warning if you provide an invalid package name.

[notebook] More ccg notebook changes

---

gateway/hail.nginx.conf.in
notebook/notebook/notebook.py

Assigning @tpoterba since he (and cotton) have the most context to review this.
A few preliminaries:
1. I noticed the proxy headers were not quite right when you're testing this without SSL or on some non-standard port. `$host` does not include the port, `$http_host` does. `$scheme` returns `http` or `https` depending on how the user connected to gateway
2. The admin privilege check was too restrictive, if `delete_worker_pod` is called by `/new` there's no need to check admin privs
3. I realized that the timeout logic wasn't quite right because a misconfigured gateway (I was testing with a broken gateway config) will return 5xx codes, but that doesn't mean the server is alive. We probably should error here, but I'm hesitant to add new error modes so close to a tutorial.
Ok, how does this …

[notebook] Banish 50x

---

gateway/hail.nginx.conf.in

Spaces were screwing things up because the `location` directive matches the decoded string (e.g. "%20" is converted back to " "). We don't need to reconstruct the URL explicitly with the regex pieces and the `$args` (which refers to HTTP query parameters), `$request_uri` is all that, but still encoded.
The notebook was receiving requests without encoded spaces which appear as a bunch of weird hex characters. Obviously the notebook errors when it sees such demonic lettering.

[notebook] Fix URLs containing encoded chars

---

ci/ci/prs.py

The deploy job we thought was running may have been deleted for a variety of reasons. It's not an error for that to happen, especially since we're about to accept a different deploy job that was running for the same desired target sha. This can happen if an old CI starts a deploy but is then killed and this CI creates another deploy job before it hears of the old CI's deploy job (and the old one finishes first).

[ci] do not fail if expected job is gone

---

hail/src/main/resources/include/hail/Decoder.h
hail/src/main/resources/include/hail/PartitionIterators.h
hail/src/main/scala/is/hail/cxx/Definition.scala
hail/src/main/scala/is/hail/cxx/PackDecoder.scala
hail/src/main/scala/is/hail/cxx/RegionValueIterator.scala
hail/src/test/scala/is/hail/nativecode/RegionValueIteratorSuite.scala

I didn't like how the scala wrapper was written, so I rewrote it? Should make it easier to use as an endpoint for code-generated stages.

rewrite cxx iterator

---

hail/src/main/resources/include/hail/Utils.h
hail/src/main/scala/is/hail/cxx/Compile.scala
hail/src/main/scala/is/hail/cxx/Definition.scala
hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/main/scala/is/hail/cxx/RVDEmitTriplet.scala
hail/src/main/scala/is/hail/cxx/StagedBaseStructBuilder.scala
hail/src/main/scala/is/hail/cxx/StagedContainerBuilder.scala
hail/src/main/scala/is/hail/cxx/TableEmit.scala
hail/src/main/scala/is/hail/cxx/TranslationUnit.scala

Basically what it says on the box. NativeStatus is now only used in the generated code in the wrapper function signature; internally, we just throw a HailFatalError object that's caught in the wrapper.

throw exceptions in generated code

---

hail/python/hail/expr/__init__.py
hail/python/hail/expr/matrix_type.py
hail/python/hail/expr/table_type.py
hail/python/hail/expr/types.py
hail/python/hail/matrixtable.py
hail/python/hail/table.py

Also fixed a bug, HailType.pretty was missing the initial indent.
A few design questions:
- Are ttable/tmatrix dtypes?  I'm treating dtype as value types, so no.
- Unlike HailType, __str__ return a dense but user-readable format, and __repr__ returns code-as-string to recreate the type.
- I went for the lower case tmatrix and table.  MatrixType and TableType would also be reasonable (and more analogous to HailType).
Also, why is HailType not just Type?  If you're in module hail, I don't see the need for the Hail prefix.
I'll add BaseType, etc. analogous to Scala in another PR.

Added tmatrix/ttable types, {Matrix}Table.schema.

---

hail/python/hail/backend/backend.py
hail/python/hail/expr/matrix_type.py
hail/python/hail/expr/table_type.py
hail/python/hail/ir/base_ir.py
hail/python/hail/ir/ir.py
hail/python/hail/ir/table_ir.py
hail/python/hail/matrixtable.py
hail/python/hail/table.py
hail/src/main/scala/is/hail/expr/AnnotationImpex.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/types/TableType.scala

Builds on: https://github.com/hail-is/hail/pull/4995
First of several (many) changes to rip out Java dependence from the mainline Python code.  Move _to_java_ir to the SparkBackend.  Eventually, only the Spark backend should call Java.  Matrix/Table now gets it types from BaseIR.typ (which will eventually implement the (virtual) typing rules in Python).  Matrix/Table explicitly call into the Spark backend to create _jmt/_jt, but those can be removed once the methods are all using IR.
@tpoterba giving this to you since you got the last one.  Let me know if you would prefer me to spin the wheel.

Backend read

---

scorecard/environment.yml
scorecard/scorecard/scorecard.py
scorecard/scorecard/templates/index.html

Simply enables CORS from all domains. This would be insecure, but our endpoints are read-only operations on public GitHub resources, against a fixed list of users, there is no database to inject, and there are no cookies or local storage entries to steal. I think it's safe enough for the time being, but open to suggestions.
Also expose /json endpoint to return all index.html data without rendering a page.

Scorecard: 1) CORS, 2) /json endpoint 3) properly close <h2> on Urgent

---

hail/python/hail/backend/backend.py
hail/python/hail/table.py
hail/python/hail/utils/java.py

This is part of a larger set of changes to separate the Python front end from Java and Spark to support connecting to a REST API Hail backend.

move from_spark, etc. to SparkBackend

---

hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/linalg/BlockMatrix.scala

@danking I rebased in the process of addressing your requested changes, so git won't allow me to re-open the closed branch #4842. I think this is now safe with regard to closing resources. Do you see a way to not include the branch on binary twice? I'd prefer to consider changing the types of streams/buffers as another PR.

Add binary option to export rectangles

---

ci/Makefile
ci/ci/batch_helper.py
ci/ci/build_state.py
ci/ci/ci.py
ci/ci/constants.py
ci/ci/pr.py
ci/ci/prs.py
ci/ci/templates/index.html

Major Changes:
- never delete CI jobs, only cancel them
- Mergeable (success) and Failure build states include the job that triggered the build state
- if a PR's build state has a job, link to that job
Minor Changes:
- fix location of dk-test instance
- test that proxy processes are still alive (if proxy creation fails, the process usually exits)
- provide `HAIL_CI_GCS_PATH` for developers to set an alternative deploy bucket and path-within-bucket (now that `gs://hail-ci-0-1` is protected)

[ci] link to logs for all PRs in CI UI

---

hail/src/main/scala/is/hail/stats/LogisticRegressionModel.scala
hail/src/main/scala/is/hail/stats/PoissonRegressionModel.scala

This is a performance improvement (and also returns explosion after the right number of iterations which is more logical). It is only necessary to check the first element because I'm confident NaN appears nowhere or everywhere in deltaB (and certainly if it appears somewhere in one iteration, it spreads to everywhere in the next).

Stop iterating logistic/poisson fit once NaN appears

---

hail/src/main/scala/is/hail/expr/ir/ExtractAggregators.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala

In last year's PTypes season finale (#4900) I changed Infer to infer the
physical type, and used that to determine the virtual type. This was a
mistake, since there will be plenty of cases where we know the type but
not the physical type (e.g. we have a Ref node). There are also some
nodes where physical types don't even make sense: Literal, TableCollect,
and anything else that fails `CanEmit`.
This PTypes episode changes Infer to InferPType, brings back the old
Infer as InferType, and makes some housekeeping changes to the IR file.

PTypes 53: Bring back InferType alongside InferPType. All IRs inferred.

---

hail/src/main/scala/is/hail/expr/ir/Sym.scala
hail/src/main/scala/is/hail/expr/ir/package.scala

the entries! [hash] must die
will use Sym instead of String throughout IR, types, etc.
Identifiers from the user program are as before, colon is used for internal symbols like `:foo` and generated symbols like `:jlen-5`.

added ir.Sym

---

hail/python/hail/ir/table_ir.py
hail/python/hail/table.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/table/Table.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

This makes it possible to explode nested fields in TableExplode,
but I don't want to solve the interface problem in this PR.

Lower MatrixExplodeRows

---

hail/python/hail/methods/statgen.py
hail/python/test/hail/methods/test_statgen.py
hail/src/main/scala/is/hail/methods/LogisticRegression.scala
hail/src/test/resources/regressionLogisticMultiPheno.cov
hail/src/test/resources/regressionLogisticMultiPheno.pheno
hail/src/test/scala/is/hail/methods/LogisticRegressionTest.scala

First crack at supporting multi phenotype logistic regression.  No matrix optimizations, as is implemented in multi phenotype linear regression, but I attempt to follow a similar approach as far as far as API and single call of mapPartitions.

Multi-phenotype logistic regression

---

hail/python/hail/table.py
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/DictFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
hail/src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/ReferenceGenomeFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/SetFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
hail/src/main/scala/is/hail/expr/types/virtual/TVariable.scala
hail/src/test/scala/is/hail/expr/ir/FunctionSuite.scala

Some infrastructure changes to support type checking in Python:
- include return types on registerIR,
- make the TVariable condition representable so it can be dumped to Python
- add a dump function that dumps the register IR function signatures as Pyhton

pave the way for computing types in Python

---

hail/python/hail/experimental/__init__.py
hail/python/hail/experimental/write_multiple.py
hail/python/hail/ir/ir.py
hail/python/hail/ir/matrix_writer.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/io/RowStore.scala
hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/main/scala/is/hail/sparkextras/OriginUnionRDD.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/MatrixIRSuite.scala

Some notes
- Currently, all matrix tables must have the same type.
- The `path` argument is treated as a prefix, to which zero-padded `0.mt` to `n.mt` is appended.
- The partfile file names are sequential across all writes.

Add ability to unify many matrix table writes into one RDD and therefore, one spark stage.

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/hail/ir/ir.py
hail/python/hail/matrixtable.py
hail/python/hail/table.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala

This allows us to insert fields elsewhere in the struct, and
is necessary for a forthcoming Python IR generation change, which will fix the BGEN allocation performance problem.

InsertFields takes the final field order

---

hail/python/hail/expr/aggregators/aggregators.py
hail/python/test/hail/expr/test_expr.py

Now raises an error instead of asserting. resolves #4770 by clarifying problem with old syntax introduced by [breaking change](https://discuss.hail.is/t/breaking-change-redesign-of-aggregator-interface/701)

Raise expression error for misuse of filter/explode without aggregation

---

batch/batch/server/server.py

Batch currently only supports a single container with the name default. This change encodes this requirement in the create_job endpoint. A better solution is to change the API to not accept multiple containers or name parameters, but this is a simpler fix.
resolves #4773

[batch] reject invalid pod specs

---

hail/python/hail/ir/ir.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/Binds.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/SpecializedArrayBuilders.scala
hail/src/main/scala/is/hail/expr/ir/Subst.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/add-ir-checklist.txt
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

(basically, the same behavior as the rows of TableLeftJoinRightDistinct, but for arrays)
This isn't used anywhere yet. The hope is that eventually we can generate an IR to represent the per-partition work for each stage of computation, at which point this will be used in the per-partition piece for the corresponding TableIR node.
During array deforestation, the left side is completely deforested. The right side is just computed directly and stuck into a RegionValue for now, although when this is pushed into C++ the right side should also be deforested as far as possible (see #4997, #4998 for what I kind of hope to do there).

implement ArrayLeftJoinDistinct IR node

---

hail/python/hail/utils/java.py
hail/python/test/hail/matrixtable/test_matrix_table.py
hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/utils/package.scala

Fix escaping of some edge identifiers like '$'

---

hail/python/benchmark/table_benchmarks.py
hail/python/hail/ir/matrix_ir.py
hail/python/hail/matrixtable.py
hail/python/hail/table.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
hail/src/test/scala/is/hail/variant/vsm/PartitioningSuite.scala

Some context:
We have 3 kinds of IRs currently: 
- Value IRs (MakeStruct, I32, ApplyComparisonOp, etc)
- TableIRs (TableRange, TableFilter, etc)
- MatrixIRs (MatrixMapRows, MatrixExplodeCols, etc)
One of the passes of the optimizer is to reformulate MatrixIRs in terms of TableIRs, and we're in the middle of this push to write lowerers for each MatrixIR node (which means writing an algorithm in LowerMatrixTable.scala, and removing the node's 'execute' method).
Here I implement lowering MatrixAnnotateRowsTable as either TableIntervalJoin or TableLeftJoinRightDistinct (a future PR should split MatrixAnnotateRowsTable into 2 nodes like Table has, probably).
The one bit of extra complexity in Python comes from implementing foreign-key joins explicitly (this was previously handled by the IR …

Lower MatrixAnnotateRowsTable

---

hail/python/hail/expr/expressions/base_expression.py

Otherwise to_expr generates code (rather than a literal) for literal data containing a missing value which can blow up on large examples.

fix to_expr bug

---

hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
hail/src/main/scala/is/hail/expr/ir/Compilable.scala
hail/src/main/scala/is/hail/expr/ir/EvaluateNonCompilable.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/LiftNonCompilable.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala

Required for adequate performance in forthcoming lowered MatrixIRs involving the cols.
There are a few changes here.
1) LiftLiterals is renamed to LiftNonCompilable. This pass functions to lift non-compilable IRs into MapGlobals nodes.
2) Introduced EvaluateNonCompilable pass. This evaluates all non-compilable nodes, and replaces them either with primitives (I32, Str, NA), or with references to a struct of compound values.
3) TableMapGlobals uses EvaluateNonCompilable and the compiler.

Lift non-compilable nodes and use compiler in TableMapGlobals

---

hail/python/hail/experimental/vcf_combiner.py

This ensures that variants that are identical across combiner inputs
are properly deduplicated during merge, and then we get the appropriate
representation of all alleles after merging.

gVCF combiner: Do proper minrep before and after merging

---

hail/python/hail/expr/expressions/expression_utils.py
hail/python/hail/ir/ir.py
hail/python/test/hail/expr/test_types.py

This caught a bug in the type inference in `GroupByKey`, which is also fixed in the PR.
@konradjk I'm pretty sure that this makes #5147 work, but I haven't confirmed directly so if you could confirm that it does and then close (or re-ping) once this goes in, that would be great.

add check that IR type and expression type are the same

---

hail/src/main/scala/is/hail/io/RowStore.scala

Don't check feature flags for encoding/decoding if the HailContext doesn't exist.
This should fix the immediate problem in that issue, although longer term, we probably shouldn't be building the encoder (or anything else, either!) on worker nodes.

Fix issue with building encoder on worker nodes (fixes #5144)

---

batch/test/test_dag.py

cc: @cseed 
---
Root issue is that `alpine` does not have `/bin/bash`, so we use `/bin/sh` instead. The syntax for the loops is POSIX compliant.
---
Interesting, these pods were failing due to:
```
State:      Terminated
Reason:   ContainerCannotRun
Message:  oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory"
Exit Code:    127
Started:      Fri, 18 Jan 2019 16:15:45 -0500
Finished:     Fri, 18 Jan 2019 16:15:45 -0500
Ready:          False
```
But this didn't fail the tests. I suppose because we cancel it faster than k8s realizes the container cannot run and notifies batch?

let container start

---

hail/python/hail/expr/expressions/indices.py
hail/python/hail/expr/expressions/typed_expressions.py
hail/python/hail/matrixtable.py
hail/python/hail/methods/statgen.py
hail/python/hail/table.py
hail/python/hail/utils/misc.py
hail/python/test/hail/matrixtable/test_matrix_table.py
hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala

Stacked on #5103 
Fixes #5100 
This PR changes the Python select and key_by operators to generate
the IR we'd expect them to be generating (e.g. `ht.select('x')` emits
a `SelectFields` instead of a `MakeStruct`).
In the process, I found and fixed a bug in group expressions for 
`GroupedMatrixTable`. This is tested for both tables and matrix tables
in the new tests in `test_table` and `test_matrix_table`.
Some timings:
>>> mt = hl.read_matrix_table('/Users/tpoterba/data/profile.mt')
>>> %timeit mt.select_entries('GT')._force_count_rows()
master: 
1.64 s ± 106 ms per loop
PR: 
967 ms ± 61.1 ms per loop

Fix Python generating Terrible, Horrible, No Good, Very Bad IR

---

hail/python/hail/table.py
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala

Fix deoptimization in Simplify.

Fix show problem by changing TableOrderBy to accept keyed tables.

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/expr/expressions/expression_utils.py
hail/python/hail/expr/types.py
hail/python/hail/genetics/locus.py
hail/python/hail/genetics/reference_genome.py
hail/python/hail/utils/interval.py

remove _convert_to_j, no longer used (pending some other PRs)
note, this is a breaking change, I'm removing overlaps and contains from the Interval interface.  I doubt anyone is using them.  Users should use hl.eval and the corresponding functions on IntervalExpression.  FYI @tpoterba for release notes (or pushback)

remove jrep from Interval

---

ci/ci/templates/index.html

Turn out [the default method is GET](https://www.w3.org/TR/html401/interact/forms.html#h-17.3).

[ci] restest form needs to POST the endpoint

---

notebook/Makefile

This was preventing use of cache when building the notebook leader image. The `$*` variable is for use with [Pattern Rules](https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html#Automatic-Variables).
Still note sure why the build is failing.

[notebook] remove use of $*

---

ci/ci/build_state.py

`to_json` was broken on `Failure` objects

fix ci bug

---

ci/test/test-ci.py

Sleeping used to work when we had a small number of PRs and other jobs. Now, test-CI deploy jobs need to wait a long time to start running. We should have always been polling for CI to be finished deploying, I was just lazy. Fixed now. Also should free up @jigold 's PR.

[ci] Fix CI test flakiness

---

batch/batch/api.py
batch/batch/client.py
batch/batch/pylintrc
batch/batch/server/server.py
batch/test/test_batch.py

When a batch is closed the DAG is complete and we do not permit any new jobs to be added. This permits us to safely clean up any job garbage when a job's children are finished. (We don't do any of that right now, but this is necessary for that).

[batch] Batches can be closed

---

batch/Makefile

This is only relevant to the local testing case. `pylint` is really slow (even if you run it on one file, which was my first attempt to mitigate slowness).

add PY_CHECK=false to disable flake8 and pylint in batch

---

batch/batch/server/server.py
batch/test/test_dag.py

Jobs are now only allowed to have parents in the same batch. This is necessary for a long term goal: inter-job dependencies. We plan to temporarily store the output of a job. We need to know when a job can no longer have children (ergo it is safe to delete the job's output). We will add a `batch.close` which prevents a batch from receiving new children. If batch jobs may only depend on other jobs in the batch, then a `close` means that we can delete any output from a job whose children have already read its output.

[batch] no parents allowed in other batch

---

gateway/Dockerfile.in
gateway/gzip.conf
gateway/hail.nginx.conf.in
letsencrypt/domains.txt

Just adds app.hail.is and notebook-api.hail.is server blocks for the two corresponding features, and modifies letsencrypt domain def to allow us to listen on 443/use https.
This has already been pushed to the cluster, works. The auth_request for notebook redirect will be reenabled when I modify it to properly handle not only the initial redirect, but the subsequent ~30 requests issued by the Jupyter web app (various css / js files, and some Ajax requests).

Gateway + Letsencrypt changes for app , notebook-api 

---

hail/python/hail/backend/backend.py

Danfeng was seeing this error trying to unpersist a matrix table:
```
>>> mt = hl.utils.range_matrix_table(10, 10)
>>> mt = mt.persist()
>>> mt = mt.unpersist()
File "<stdin>", line 1, in <module>
File "/Users/wang/code/hail/hail/python/hail/matrixtable.py", line 2896, in unpersist
return Env.backend().unpersist_matrix_table(self)
TypeError: unpersist_matrix_table() missing 1 required positional argument: 'storage_level'
```

fix signature of Backend.unpersist_matrix_table

---

gateway/hail.nginx.conf.in

This is the last change needed to enable authorized notebooks. Completely handles all N requests after redirect to Jupyter server, including all requests in subsequent within-Jupyter operations such as notebook creation (which still pass through our proxy)

Gateway: use cookies instead of query string to pass access token

---

hail/build.gradle
hail/python/hail/methods/statgen.py
hail/python/test/hail/methods/test_statgen.py

resolves https://github.com/hail-is/hail/issues/5263

[hail] Fix pc_relate bug with non-default call_expr

---

hail/build.gradle
hail/hail-ci-build.sh

Fixes #5106.
(I realized halfway through that cseed fixed the problem with the artifacts not getting copied in a PR a few weeks ago, but I think the codegen tests should probably be writing to their own directory and not overwriting other tests.)

write codegen tests to their own directory

---

hail/python/hail/ir/ir.py
hail/python/hail/table.py
hail/python/test/hail/table/test_table.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/TableValue.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/table/Table.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Add delimiter option to TableExport

---

hail/python/hail/docs/tutorials/01-genome-wide-association-study.ipynb
hail/python/hail/plot/__init__.py
hail/python/hail/plot/plots.py

I'm not sure if this is worth it, but gives the plotting library a slightly more self-contained feel.

Plot utils

---

hail/python/hail/genetics/pedigree.py
hail/python/test/hail/methods/test_family_methods.py

Fixes #5293
@tpoterba I decided not to throw an error if the key is null and instead just let the `flatMap` in `restrictTo` take care of it. Let me know if you think we should error out.

fix trio matrix filter_to typecheck error

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/rvd/RVD.scala

Fix bug in TableLeftJoinRightDistinct related to RVD physical key

---

batch/batch/server/globals.py
batch/batch/server/server.py
batch/batch/templates/recent.html

informational page for last 100 job created (with command line) and job finished (with log) events
This is for @jigold's demo on Monday so she can give some sense of progress of jobs when running a pipeline demo.
Note, batch isn't exposed publicly so you'll have to `kubectl` port forward to access it.
Not the most beautiful, but should be functional.  Here's a screenshot:

add batch/recent endpoint

---

hail/python/hail/matrixtable.py
hail/python/test/hail/matrixtable/test_matrix_table.py

@tpoterba @cseed I think this should be public, it's been useful more than once, and it's reasonable to do on certain datasets (currently all datasets, but maybe not when we have 10 million columns).

[hail] Promote localize_entries to public & tested

---

hail/python/hail/matrixtable.py
hail/python/hail/table.py

Was confused when reading https://hail.is/docs/0.2/hail.Table.html#hail.Table.filter, so did something about it.

tables README logic typo fix

---

hail/python/hail/experimental/__init__.py
hail/python/hail/experimental/densify.py
hail/python/hail/expr/aggregators/__init__.py
hail/python/hail/expr/aggregators/aggregators.py
hail/python/hail/ir/register_aggregators.py
hail/src/main/scala/is/hail/Uploader.scala
hail/src/main/scala/is/hail/annotations/aggregators/RegionValuePrevNonnullAnnotationAggregator.scala
hail/src/main/scala/is/hail/expr/ir/AggOp.scala
hail/src/main/scala/is/hail/expr/ir/ExtractAggregators.scala

I made `_prev_nonnull` private since it's pretty specific to this use case, but I can imagine we'll want to generalize it to something like `take` which aggregates the last `n` values instead of the first `n` values.
Here is an example pipeline against `test-chr22.mt`:
```
mt = hl.read_matrix_table('test-chr22.mt')
mt = mt._filter_partitions(range(8)) # make small
mt = mt.filter_cols((mt.s == 'V33335') | (mt.s == 'NWD157935'))
mt = mt.annotate_rows(__n = hl.agg.count_where(hl.is_defined(mt.GT)))
mt = mt.filter_rows(mt.__n > 0)
print(
mt.count())
def show_mt(mt):
entry_fields = ['GT']
if 'END' in mt.entry:
entry_fields.append('END')
(mt.select_rows()
.select_entries(*entry_fields)
._localize_entries('__entries', '__cols')
.show())
show_mt(mt)
mt = …
```

added experimental aggregator _prev_nonnull and densify

---

hail/src/main/scala/is/hail/expr/ir/IRBuilder.scala
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala

The `distinct` is safe to remove since `ToDict` will do its own distinct. The only occasion when we'd want the distinct there is if we have tons of highly duplicated keys in `table`, which is very rare. Otherwise, removing the distinct and inserting an unkey will generate better IRs with fewer shuffles.

Lower MatrixAnnotateColsTable better by unkeying before collecting

---

hail/python/hail/ir/matrix_reader.py
hail/python/hail/ir/table_reader.py
hail/python/hail/ir/utils.py
hail/python/hail/methods/impex.py
hail/python/test/hail/methods/test_impex.py
hail/python/test/hail/table/test_table.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
hail/src/main/scala/is/hail/sparkextras/ContextRDD.scala
hail/src/main/scala/is/hail/utils/TextInputFilterAndReplace.scala
hail/src/main/scala/is/hail/utils/TextTableReader.scala
hail/src/main/scala/is/hail/utils/richUtils/RichHadoopConfiguration.scala
hail/src/test/resources/filter_replace.txt
hail/src/test/scala/is/hail/TestUtils.scala

Add the `filter` and `find_replace` arguments to `import_table` and `import_vcf`.
These are regex filter and substitution arguments, which will make it possible to tolerate some invalid inputs.

[hail][new feature] Add regex filter/substitution to import_table and import_vcf

---

hail/python/test/hail/genetics/test_reference_genome.py
hail/src/main/scala/is/hail/variant/ReferenceGenome.scala

@patrick-schultz I fixed this for the case of locus intervals, but wasn't sure if there was a reason we don't add the `isValid` check to the Interval constructors.

Fix #5174 - LocusInterval length == 0

---

site/hail.nginx.conf

Fixes #5095 and tips Google that we don't want it to index /devel /stable (also 301 redirects are cached, should be faster).

Hailpedia 404 fix, 301 redirect

---

batch/README.md

1) More completely document pointing kubectl to a google cloud cluster.
2) at least in Google Cloud SDK 228.0.0, one of --zone or --region are required.
3) eval $(minikube docker-env) seemed out of place, but I may not have understood

Update batch README.md

---

hail/python/hail/ir/ir.py

Change naming of Python MakeArray IR node since it is actually used as the type for the MakeArray, not the element-type.

Change MakeArray._element_type to MakeArray._type

---

hail/src/main/scala/is/hail/methods/VEP.scala

@cseed I have no idea if this will work.

Add error output to VEP exceptions

---

hail/python/hail/matrixtable.py
hail/python/hail/table.py
hail/python/test/hail/table/test_table.py

We throw an error if field is nested and the name argument is passed.

[feature] Table.explode supports nested fields

---

hail/.gitignore
hail/src/main/c/Makefile
hail/src/main/c/ibs.h

- automatically download catch.hpp from GitHub if it's missing
- remove builtin rules and suffix based rules to improve performance and ease debugging
- change Makefile variable definitions to match our standard `FOO OP VAL` (note: two spaces)
- rely on `clang -MM` (see: [Clang command line reference](https://clang.llvm.org/docs/ClangCommandLineReference.html) and below explanation) to generate precise dependencies for object files (including source and header files)
- explicitly specify which files depend on `NUMBER_OF_GENOTYPES_PER_ROW` to be set (namely the dependency file and the object file associated with `ibs.cpp`)
- break `TEST_OBJECTS` into two steps so that we can have `_test.cpp` files which do not have corresponding `.cpp` files (consider, for example, a header-only file, …

[hail] improve makefile in anticipation of approximate quantiles

---

hail/python/hail/experimental/vcf_combiner.py

It is unnecessary to store it during merging as it is computed from
a dense MT in summarize.

Drop info.DP in combiner pre-transform

---

batch/Dockerfile
batch/MANIFEST.in
batch/batch/server/server.py
batch/setup.py

The template files weren't getting installed so the /recent endpoint was breaking.  I followed the Flask instructions for installing non-Python files: http://flask.pocoo.org/docs/0.12/patterns/distribute/.

Fix batch deploy

---

hail/python/hail/expr/blockmatrix_type.py
hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/types/BlockMatrixType.scala
hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala

Using index expressions to represent abstract transformations on tensors. E.g. broadcasts from scalars and vectors to matrices would be represented by
```
O(i, j) <- A()
O(i, j) <- A(i)
O(i, j) <- A(j)
```
where A is the input tensor and O is the output tensor. Similarly, transpose and identity look like
```
O(i, j) <- A(j, i)
O(i, j) <- A(i, j)
```
Since the `O(i,j)` is the same in all of these, we only need to look at the "in" index expressions for broadcasts to distinguish what operation needs to be performed. There's also a Simplify rule to cut out identity broadcasts.
This method of index expressions treats scalars and vectors as 0-dimensional and 1-dimensional tensors, respectively. As such, their shapes in the IR are 0 and 1-dimensional. However, BlockMatrix (Py API and Scala …

Use index expressions for broadcasting and transpose

---

hail/src/main/scala/is/hail/HailContext.scala

cc: @tpoterba 
Not sure why this wasn't printed before. I found it a bit surprising we weren't actually using the `tmpDir` that I specified in `hl.init`. At least this way, I can figure out which temp dir is for my current session.

[hail] Print the temporary directory on context start-up

---

hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/UnaryOp.scala
hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala

- Add a `BlockMatrixMap` IR node that handles operations like: `neg`, `log`, `sqrt`, `abs`
- Change the function on Map2 to be an `IR`, not just `ApplyBinaryPrimOp`. This allows Map2 to support `pow` and other registered functions as well as arbitrary functions on tensors.

Add BlockMatrixMap to IR

---

hail/python/hail/experimental/vcf_combiner.py

The numbers used in local alleles now correspond to global allele
indexes rather than global alt-allele indexes
Example, obtaining the allele for `LGT[i]`:
```
Old:
allele = alleles[LA[LGT[i] - 1] + 1]
New:
allele = alleles[LA[LGT[i] - 1]]
```

Change local allele numbering

---

hail/src/main/scala/is/hail/expr/ir/Binds.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Compilable.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/Subst.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

This adds (but does not implement) a node called CollectDistributedArray, which takes an array of contexts (an array of values that defines the start of a partition of work) and some global values to broadcast and applies `body` to each element of `context`, collecting the result.
Implementation to follow.
cc @cseed

add CollectDistributedArray IR node

---

hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/linalg/test_linalg.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

- Add an IR node to represent matrix multiplication between two `BlockMatrixIR`.
- Cleaned up the workaround introduced in #5338 for differentiating between a matrix shape (2-D shape that the `BlockMatrix` front-end is aware of) and a tensor shape (n-D shape of the IR type).

Add BlockMatrixDot to IR

---

hail/python/hail/experimental/densify.py

Discovered that in one of the gnomAD gvcfs, there is a ref block that overlaps a variant. We need to be able to handle this case. For now, just don't allow overwriting an entry.

Do not overwrite present entries in densify

---

hail/python/hail/experimental/vcf_combiner.py

SB is a reserved INFO field in VCFs, and so downstream tools may
overwrite the header. SB_TABLE is more what we want and the header will
be correct for the datatype (array of 4 ints)

Rename info.SB to info.SB_TABLE

---

hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/linalg/test_linalg.py

The front-end accepted a boolean flag to make the a random BlockMatrix with a uniform distribution and would default to gaussian, whereas the backend method it's calling accepts a `gaussian` flag. Updated the front-end API to match the backend and added a test to check that matrices made explicitly uniform have no negative values and are (very likely) not gaussian.

change BlockMatrix.random parameter from uniform to gaussian

---

hail/python/hail/methods/qc.py
hail/python/hail/methods/statgen.py
hail/src/main/scala/is/hail/methods/LogisticRegression.scala
hail/src/main/scala/is/hail/methods/Nirvana.scala
hail/src/main/scala/is/hail/methods/PoissonRegression.scala
hail/src/main/scala/is/hail/methods/VEP.scala

None of these methods were appropriately persisting, since the call was
in Scala. Since the Python IR was evaluated each time, the a new RVD
would be created and persisted on each call to backend.execute, and
the previous persisted RVDs would only be used once.
We need to be on the lookout for this pattern as we convert more
operations to MatrixToTableFunctions and friends

[bugfix] Fix persisting of vep, logistic regression, poisson regression

---

apiserver/Makefile
apiserver/apiserver/apiserver.py
hail-ci-build-image
hail/Makefile
hail/hail-ci-build.sh
hail/python/hail/backend/backend.py
hail/python/hail/dev-environment.yml
hail/python/hail/ir/table_ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/experimental/test_experimental.py
hail/python/test/hail/helpers.py
hail/python/test/hail/linalg/test_linalg.py
hail/python/test/hail/methods/test_impex.py
hail/python/test/hail/methods/test_misc.py
hail/python/test/hail/methods/test_qc.py
hail/python/test/hail/methods/test_statgen.py
hail/python/test/hail/stats/test_linear_mixed_model.py
hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/HailContext.scala
hail/test-apiserver.sh
projects.txt

Stacked on: https://github.com/hail-is/hail/pull/5384
Right now just running one test, since the Python tests are quite long (~10m).  When they get parallelized (ongoing batch changes), we enable the full tests.  The full tests are currently passing when run as:
HAIL_TEST_SERVICE_BACKEND_URL=http://localhost:5000 gw testPython

add apiserver to tests

---

hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/io/RowStore.scala
hail/src/main/scala/is/hail/io/bgen/BgenRDDPartitions.scala
hail/src/main/scala/is/hail/io/bgen/IndexBgen.scala
hail/src/main/scala/is/hail/io/reference/FASTAReader.scala
hail/src/main/scala/is/hail/io/reference/LiftOver.scala
hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
hail/src/main/scala/is/hail/linalg/BlockMatrix.scala
hail/src/main/scala/is/hail/linalg/RowMatrix.scala
hail/src/main/scala/is/hail/methods/MatrixExportEntriesByCol.scala
hail/src/main/scala/is/hail/utils/richUtils/RichContextRDD.scala
hail/src/main/scala/is/hail/variant/ReferenceGenome.scala
hail/src/test/scala/is/hail/io/TabixSuite.scala

Only create serializable and broadcasted HadoopConf once in HailContext and use everywhere else.  I was seeing pipelines with MANY duplicate broadcasts the Hadoop configuration.

centralize serializable and broadcasted Hadoop configuration

---

hail/python/hail/expr/__init__.py
hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/annotations/aggregators/RegionValuePrevNonnullAnnotationAggregator.scala
hail/src/main/scala/is/hail/expr/ir/AggOp.scala
hail/src/main/scala/is/hail/io/RowStore.scala

I left in the previous one for testing purposes.  When we're confident the new one dominates, I will remove it.
This is the first of several PRs to speed up densify (and scans and aggregates in general).  The rough plan is:
- add CompiledPackEncoder so we aren't interpreting types in the prev_nonnull seqOp,
- make RegionValueAggregator.result staged so we don't use RegionValueBuilder to construct aggregator and scan results
I will  do some more benchmarking at that point.

_prev_nonnull aggregator mark 2

---

hail/src/main/scala/is/hail/annotations/aggregators/RegionValuePrevNonnullAnnotationAggregator.scala
hail/src/main/scala/is/hail/io/RowStore.scala
hail/src/main/scala/is/hail/io/bgen/IndexBgen.scala
hail/src/main/scala/is/hail/io/index/IndexWriter.scala
hail/src/main/scala/is/hail/utils/richUtils/Implicits.scala
hail/src/main/scala/is/hail/utils/richUtils/RichCodeOutputBuffer.scala
hail/src/test/scala/is/hail/io/IndexSuite.scala

Stacked on: https://github.com/hail-is/hail/pull/5414
UnsafeSuite.testCodec verifies this aggressively.  I also turned the up the test count massively in hand testing and everything looks good.
This should give a modest speed boost to writes, shuffles, anything that uses the encoder generally.
Next up is staging the result from RegionValueAggregators.

Compiled pack encoder

---

hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/main/scala/is/hail/sparkextras/ContextRDD.scala
hail/src/main/scala/is/hail/utils/package.scala
hail/src/test/scala/is/hail/utils/UtilsSuite.scala

... in the sense that they always aggregate in partition order.
This is achieved by a `AssociativeCombiner` which greedily combOp's aggregator state from adjacent partitions.  I think this is the best you can do.  Later we should have a `CommutativeCombiner` and choose between the two based on the whether the user-level aggregators are (duh) associative (like collect and prev_nonnull) or commutative (like collectAsSet or count).
This is slightly conservative as I converted, with slavish consistency, all aggregators and reducers, included one only used by concordance, which I think is commutative.  I'm OK with that mostly because this is safer and concordance really needs to get rewritten in Python (I think @tpoterba has a draft but it needed some performance work).
FYI @chrisvittal this …

Make all aggregators deterministic

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/main/scala/is/hail/rvd/RVDContext.scala

cc: @tpoterba @patrick-schultz @catoverdrive 
We are not allowed to clear a region we do not own.
Someone should test this doesn't blow memory on a severe filter in the cloud.
---
Prevent segfaults when joining two tables using `t1.join(t2)`. This syntax does a "product join", i.e., a normal join. The `t2[t1.key]` syntax takes only one matching element from `t2` for each element in `t1`. When performing a "product join", hail keeps a side-buffer of region values from the right-hand-side table. This side buffer *must not be cleared* by down stream operations (it is owned by the join node). Unfortunately, hail's filter method was incorrectly clearing regions it might not own. This bug only appeared as a segfault when `t1.join(t2)` was followed by a filter.

[hail] Prevent segfaults when joining two tables using `.join`

---

hail/python/hail/experimental/vcf_combiner.py
hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/main/scala/is/hail/rvd/RVDPartitioner.scala
hail/src/test/scala/is/hail/SparkSuite.scala

First, I changed import_vcfs to return a MatrixTable only keyed by locus, and removed the MatrixKeyRowsBy in combine_gvcfs.  To goal here is to avoid re-buidling an re-broadcasting the partitioner once for each gVCF.  We'll need to re-key at the very end.  I'm not so familiar with the end of the joint calling pipeline.  @chrisvittal can you take care of that?
Second, I don't repartition in TableMultiWayZipJoin if the partitioners all match (which they should in in the joint calling pipeline).  For that to work right, I need allowedOverlap == 0 (or to verify the partitions are in fact disjoint).  Turns out allowedOverlap wasn't being propagated in various places.  I fixed that.
@patrick-schultz can you look at the RVDPartitioner changes?  They just look like oversights to me, but maybe …

Combine locus keyed

---

hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/linalg/blockmatrix.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala

Add IR node for aggregations on a single BlockMatrix. This node assumes `sum` as the aggregator since it's currently the only supported monoid.

Blockmatrix agg

---

hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala

if the comparison returns missing for two non-missing values, we throw an error (and user-facing comparison functions are constructed to never hit this case). I accidentally did this in one of the test cases and the interpreter didn't have the same behavior so the tests were passing. I've fixed the Interpret behavior as well; this was caught in the tests for #5283.

fix _sort_by test, Interpret behavior with missing comparison

---

notebook2/Dockerfile

Dependency was only added to environment.yml, causing the container to fail to run. Would be nice if we could specify in one place.

Notebook2: add libsass to docker image

---

batch/Makefile
batch/batch/api.py
batch/batch/client.py
batch/batch/server/globals.py
batch/batch/server/server.py
batch/test/test_batch.py
batch/test/test_dag.py

I had a choice on how to implement this and I decided to add a JobTask class that takes care of a single pod and the Job changes to just be a manager of the pods. However, I could have done it all within the Job if you think that is clearer. Happy to refactor if needed.
Please look and see if I have enough tests. The tests are passing, but I'm getting this error message. Is this expected or a bug in my code? 
```
INFO	| 2019-02-22 11:48:48,126 	| _internal.py 	| _log:87 | 127.0.0.1 - - [22/Feb/2019 11:48:48] "POST /pod_changed HTTP/1.1" 204 -
INFO	| 2019-02-22 11:48:48,210 	| _internal.py 	| _log:87 | 127.0.0.1 - - [22/Feb/2019 11:48:48] "POST /pod_changed HTTP/1.1" 204 -
INFO	| 2019-02-22 11:48:48,833 	| server.py 	| mark_complete:190 | wrote log for job 61, main task to …
```

[batch] Added triple pod to Job

---

batch/batch/client.py

The status parameter was being set as the scratch parameter. https://github.com/hail-is/hail/pull/5418 introduced another constructor parameter before `_status`, changing the meaning of the fifth argument.
CI is currently broken as a result. I'm going to force merge this and manually re-deploy CI and batch.
I'll follow up with a commit that enforced inter-project dependencies.

[batch] explicitly use constructor parameters

---

hail/python/hail/linalg/blockmatrix.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala

Implementation of extracting a diagonal of a matrix in the IR. This can be represented by saying that given a matrix of indices `[i, j]`, I am going to take entries corresponding to an index expression of `[i, i]` (or in the code `[0, 0]`).
Also made the method return a `BlockMatrix` instead of numpy `ndarray` so we don't unnecessarily force the IR execution. @jbloom22 thoughts on the user-facing change?

Implement BlockMatrix.diagonal in the IR

---

batch/batch/server/server.py
batch/test/test_batch.py

If batch job fails we should still increment the _task_idx.
Otherwise, we ignore the log for the failing task.

[batch] fix batch logs

---

hail/python/hail/expr/expressions/base_expression.py

Fixes #5449
We don't have machinery for testing performance behavior of something
like show() right now, so I can't test it easily. But I did verify by
hand.

[bugfix] Fix Expression.show() with a key field that isn't the first key

---

hail/python/hail/ir/ir.py
hail/python/hail/linalg/blockmatrix.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Compilable.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/functions/GetElement.scala
hail/src/main/scala/is/hail/expr/ir/functions/RelationalFunctions.scala

- Added IR node to go from a BlockMatrix to a value
- Added BlockMatrixToValueFunction to get an element at a certain index and used it to access elements in BlockMatrix.__getitem__
- This raises an interesting question of whether accessing an element of a tensor should return a Python value or a Hail expr. Right now, it just builds a BlockMatrixToValue IR and immediately executes it to return a Python number (matches existing behavior), but we could just as easily return the IR node.

Add BlockMatrixToValue IR node

---

hail/python/hail/ir/__init__.py
hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/ir/blockmatrix_reader.py
hail/python/hail/ir/blockmatrix_writer.py
hail/python/hail/ir/ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/BlockMatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Previously, the BlockMatrix IR had nodes for reading and writing that only covered the BlockMatrix part file format. Implemented readers and writers for both native and binary file formats (compatible with numpy) refactored read/write nodes, and implemented `tofile` and `fromfile` BlockMatrix methods in terms of the IR. Also hardcoded the front end default block size so now tests running IO/basic algebra should be able to run on the service.

Add readers and writers to BlockMatrix IR

---

pipeline/pipeline/backend.py
pipeline/pipeline/pipeline.py
pipeline/pipeline/resource.py
pipeline/pipeline/task.py
pipeline/test-locally.sh
pipeline/test/test_pipeline.py

Plus better error checking!
- Some bioinformatic tools expect a secondary implied file to be present. For example, sample.vcf and it's index file sample.vcf.tbi. This PR adds file localization such that if any file in a resource group is used, the entire resource group will be copied and not just the mentioned file.
- Added a mentioned set that tracks whether a resource was defined in the command or declare resource group functions. Otherwise, you could do something like this which would throw an error upon execution:
```python
p = Pipeline()
t = p.new_task()
p.write_output(t.undefined_variable, 'gs://foo/foo')
p.run()
```

[pipeline] Added implicit copy of resource group

---

hail/python/hail/expr/blockmatrix_type.py
hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/types/BlockMatrixType.scala
hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala

Removes the specification of what dimensions are partitioned from the construction of IR nodes. In nodes where the dimensionality is subject to change, the resultant dimensions are assumed to all be distributed (this field in the type does not currently affect the behavior of BlockMatrix).

Remove dims partitioned from BlockMatrixIR constructors

---

notebook2/Dockerfile

notebook2 deploys are currently broken, which breaks all deploys

[notebook2] libsass depends on a c++ compiler

---

hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Compilable.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/io/RowStore.scala
hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala
hail/src/main/scala/is/hail/variant/MatrixTable.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

This defines (but doesn't yet implement) a ReadPartition value IR node. For an idea of how it would be implemented and used, see #5326 for a (non-working) example. I think I need to make the interface for c++ to call back into spark a little better before I implement this, but in the meantime I'm PRing the IR bits.

define parseable scala ReadPartition IR node

---

hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/io/vcf/ExportVCF.scala
hail/src/test/resources/gvcfs/HG0096_excerpt.g.vcf

Previously export_vcf would write nothing when there were no alternate
alleles, hail would then fail to import the exported vcf.

[hail] export ALT as '.' when there is only one allele

---

batch/Makefile
batch/hail-ci-deploy.sh
batch/kubectl-wait-for-delete
batch/test-namespace.yaml

Currently, garbage pods will sit around in the batch-pods and test namespaces forever.
In anticipation of adding expensive resources (storage), batch needs to learn to clean up after itself. Batch creates garbage whenever it is killed without warning. This happens in two circumstances:
- when batch is killed by a deploy
- CI job is running a test batch instance and is killed because master or the feature branch changed
To mitigate this issue we delete all PVCs (storage, ergo monetarily expensive resources) from the batch-pods namespace before we deploy batch. These PVCs are no longer needed because the batch instance that owns them is about to be re-deployed.
Since the test namespace (where CI jobs will spin up batch instances to test) might also contain PVCs, we delete the whole …

[batch] batch cleans up after itself when it is deployed

---

hail/python/hail/ir/blockmatrix_writer.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/linalg/BlockMatrix.scala

- Refactored `exportRectangles` on BlockMatrix from a static function with an input and output file to an instance function with an output file that writes the instance.
- Added `BlockMatrixRectanglesWriter` so exporting rectangles happens through the IR.
- Updated tests and deleted parts of tests that dealt with invalid inputs that aren't applicable when exporting from an already loaded BlockMatrix.

Blockmatrix export rects

---

hail/python/hail/experimental/vcf_combiner.py
hail/python/test/hail/methods/test_impex.py

To summarize:
- Filter out '<NON_REF>' allele in transform_one
- Create RGQ, as PL[GT index of 0/<NON_REF>]
- Set LPL to missing if alleles only contains the ref after filtering

[combiner] update combiner format in response to feedback

---

hail/src/main/scala/is/hail/cxx/PackDecoder.scala
hail/src/main/scala/is/hail/cxx/PackEncoder.scala
hail/src/main/scala/is/hail/expr/types/physical/PContainer.scala

Unnecessary currently, but I'll be using this functionality to be able to directly serialize the result of partition computations that return primitive values. (see #5450) Seemed easier than explicitly writing and calling different versions of a function for different primitive types.

[c++] PackEncoder/PackDecoder can serialize primitive values

---

hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/linalg/blockmatrix.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala

- Added a single `BlockMatrixFilter` IR node for filtering a subset of rows and columns.
- I don't really have a great way of talking about filtering on some dimensions and not others. Filter takes a list of list of indices (one list per dimension) and if the list is empty that dimension is not filtered on. While there's no other meaningful interpretation of an empty list it feels like you're saying you don't want to keep any of the indices. Could use optionals for each dimension but `None` seems just as confusing and would require some small refactoring of the parser. The more consistent thing to do is pass along something like `range(n_rows)` but that just seems wasteful.

Blockmatrix filter IR node

---

hail/src/main/scala/is/hail/io/tabix/TabixReader.scala
hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala

There was some real bad capture/broadcast issues in VCFsReader.  I made the following changes:
- import_vcfs requires the signature of all files to be the same,
- compute the type once from the first file,
- verify the types agree when parallelizing over files computing the partitions,
- always broadcast the header lines (which can be large)
This reduced the DAGScheduler RDD broadcast by about 4x (6MB => 1.4MB) on a simple 10-input pipeline of import_vcfs/transform_one/combine/write_multi.

tune ImportVCFs

---

hail/src/main/scala/is/hail/io/RowStore.scala
hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/main/scala/is/hail/sparkextras/OriginUnionRDD.scala
hail/src/test/scala/is/hail/expr/ir/MatrixIRSuite.scala

Stacked on: https://github.com/hail-is/hail/pull/5507
Drops one broadcast from my test dataset from 1.4MB => 300KB (5x).  I think that corresponds to the parallelize for writeSplitSpecs, which is now constant (won't scale according to the number of inputs).  The RDD actually doing the writing, the OriginUnionRDD, still scales linearly.  I think that's inevitable unless we do the LightweightContextRVDDistributedArray thing I mentioned on Zulip since we necessarily allocate at least one RDD per input.  It might still be possible to push the constants down.
The point of this change is to avoid capturing the OriginUnionRDD partitions inside the map step.  I did this essentially by turning OriginUnionRDD into a union with "mapPartitionsWithOriginIndex".
I think it might be wroth trying to …

Tune write rows split files

---

hail/python/hail/matrixtable.py
hail/python/test/hail/matrixtable/test_matrix_table.py

You came up on the dial, let me know if I should reassign

[feature] Add n_cols argument to MatrixTable.head

---

vdc/k8s-config.yaml

I've already applied this change to the cluster since k8s-config.yaml isn't actually auto-deployed yet.

[batch] fix batch deploy

---

hail/python/hail/experimental/function.py

This enables us to use ApplyIR directly as we now save the function's
name.

[experimental] Return an object in define_function

---

hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/linalg/test_linalg.py

- Added convenience method to export each block of a BlockMatrix into its own file using `export_rectangles`
- Added static method to load rectangle files into a NumPy NDArray

Blockmatrix export blocks

---

hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/linalg/test_linalg.py

Updated incorrect doc and added test to verify that if you try to export a sparse block it writes a file of zeros. resolves #5500

add test for exporting sparse matrix

---

hail/src/main/scala/is/hail/variant/ReferenceGenome.scala

@chrisvittal This will fix your define_function issue.  I was wrong, the types were the same.
@danking Something very strange is going on here.  I can verify only one GenomeReference is being constructed, so this and concrete must be the same object, but eq is returning false.  I don't see how this can be possible.
I some something similar last week which caused me to add ReferenceGenome.hashCode (we were defining one but not the other).  However, that shouldn't matter because there was only one reference genome object, but two different pointers captured at different times were returning different values of hashCode.
I don't see how that's possible but I don't see an alternate explanation.
This fixes the immediate bug.  I think ReferenceGenome shouldn't be a case class, and it should …

fix reference genome unify

---

apiserver/apiserver/apiserver.py
hail/python/hail/backend/backend.py
hail/python/hail/experimental/ld_score_regression.py
hail/python/hail/expr/__init__.py
hail/python/hail/expr/blockmatrix_type.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/linalg/test_linalg.py
hail/test-apiserver.sh

- Implemented support for blockmatrix types in the service backend
- All BlockMatrix tests except those for `sparsify` methods and `svd` (which uses `sparsify`) succeed locally on the service backend
- Removed test decorators for tests that succeeded locally
- Added a single test out of the `BlockMatrix` suite to `test-apiserver.sh`
- `Statgen` doesn't seem to have any `BlockMatrix`-based Java dependencies
- `linear-mixed-model` uses `svd` and `RowMatrix`

implement tblockmatrix service endpoint and test BlockMatrix methods

---

hail/python/hail/conftest.py
hail/python/hail/matrixtable.py
hail/python/hail/table.py
hail/python/test/hail/matrixtable/test_matrix_table.py
hail/python/test/hail/table/test_table.py

[feature] Add semi- and anti-joins.

---

hail/src/main/scala/is/hail/backend/spark/LowerTableIR.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

Lowers TableFilter to a SparkStage containing a value IR computation for each partition.

lower TableFilter in SparkBackend

---

hail/src/main/resources/include/hail/SparkUtils.h
hail/src/main/scala/is/hail/backend/spark/LowerTableIR.scala
hail/src/main/scala/is/hail/cxx/Compile.scala
hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/main/scala/is/hail/cxx/EmitTriplet.scala
hail/src/main/scala/is/hail/cxx/TranslationUnit.scala

Changes the first argument that Emit expects to be a SparkFunctionContext, which currently holds a region and a SparkEnv (currently a stub; will be fleshed out as we start writing code to call back into Spark.) This should let us be more flexible in our ability to pass other necessary (non-IR-value) inputs, such as a hadoop configuration, to the function without relying on function argument ordering and accounting.
builds on #5457.

 [c++] first argument to Emit is context, which wraps region

---

hail/python/test/hail/test_ir.py

All the matrix IR tests were in a method in `TableIRTests`. Moved them out into a separate class to stay consistent.

move matrix ir tests out of table ir test class

---

hail/python/hail/plot/plots.py

It crashes the browser when it gets a label that's None.

[bugfix] Fix bokeh scatter label

---

hail/python/hail/experimental/vcf_combiner.py

The VCF spec indicates that there should be 1 element in this array per
alternate allele (`Number=A`), not one per allele (`Number=R`).

[combiner] drop the first element in AC, AF in summarize

---

hail/python/hail/table.py

We weren't checking for a key even though the docs said the table needed to be keyed. This led to undefined behavior for `distinct`. Not sure what the error mode for `collect_by_key` was.

[bug-fix] Check keyed table for collect_by_key and distinct

---

batch/batch/client.py
batch/batch/server/server.py
batch/test/test_dag.py
vdc/k8s-config.yaml

Add volumes to `batch`, which are mounted by each pod, but are not written to or read from.
Key Changes
---
- Introduce a k8s [StorageClass](https://kubernetes.io/docs/concepts/storage/storage-classes/) and associated [ResourceQuota](https://kubernetes.io/docs/concepts/policy/resource-quotas/#storage-resource-quota) which creates and destroys disks for use by k8s pods whenever a PersistentVolumeClaim is created or delete, respectively. 1GB of disk [costs 0.04 USD per month](https://cloud.google.com/compute/pricing#disk), so I feel pretty fine with a 100GB limit for each, limiting our total possible monthly cost to 8 USD per month.
- If there is more than one task (ergo there is a need for a shared disk), then we create a PVC and mount it to `/volume`. We delete this PVC if 1) all tasks …

[batch] Volumes

---

image-fetcher/fetch-image.sh

Forthcoming changes to batch will use this image to copy data between batch jobs. Waiting 30 seconds for this image to pull is not tenable.

[image-fetcher] also fetch google/cloud-sdk docker image

---

vdc/list-gcp-sa-keys
vdc/make-k8s-gcp-sa-key
vdc/remove-k8s-gcp-sa-key

These scripts wrap `gcloud` and `kubectl` to provide one line commands to create and remove k8s secrets, with a standard name scheme, for GCP service accounts.

helpers to create and remove k8s secrets for gcp sa keys

---

hail/python/hail/expr/__init__.py
hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/expr/generic_summary.py
hail/python/hail/matrixtable.py
hail/python/hail/table.py
hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/annotations/aggregators/RegionValueStatisticsAggregator.scala
hail/src/main/scala/is/hail/methods/Aggregators.scala

Experimental. Assigning Patrick because we had discussed this together several months ago.

Add experimental summarize() functions

---

notebook2/notebook/notebook.py
notebook2/notebook/templates/notebook-form.html

This just removes the ibg2019 image from notebook2, resets the default (and only image) to the hail image that preceded it.

[notebook2]: remove ibg 2019

---

hail/src/main/scala/is/hail/cxx/Compile.scala
hail/src/test/scala/is/hail/TestUtils.scala

@cseed @tpoterba I accidentally undid the caching behavior in the tests by using the name of input variables from their name in the environment instead of just using a default set of variable names. Should be much faster now.

[c++] fix test times

---

hail/python/hail/experimental/vcf_combiner.py

There is currently only one valid input type to the merge function.

[combiner] use a single variable rather than a map for merge function

---

hail/src/main/resources/include/hail/ArrayBuilder.h
hail/src/main/resources/include/hail/Utils.h
hail/src/main/scala/is/hail/cxx/PackDecoder.scala
hail/src/main/scala/is/hail/cxx/StagedContainerBuilder.scala

Again, shouldn't change behavior but moves the implementation of StagedContainerBuilder from entirely Scala-generated to a templated C++ function so that we can construct arrays more easily from C++.

[c++] write templated array builder in C++; use in StagedContainerBuilder

---

hail/src/main/resources/include/hail/ArrayBuilder.h
hail/src/main/resources/include/hail/ArraySorter.h
hail/src/main/scala/is/hail/cxx/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/types/physical/PContainer.scala

Builds on #5463.
This currently just pulls values out into a vector and sorts the vector based on a defined sorting function; could possibly be improved in the future by defining an iterator that we can call e.g. `std::stable_sort` on.

[c++] Implements ArraySort/ToSet/ToDict in Emit.

---

hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

This should take the time it takes to run IRSuite back down to ~7 minutes. Still not great, but better than 12.

parameterize some IRSuite tests to avoid c++ recompilation

---

hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala
hail/src/test/scala/is/hail/expr/ir/ArrayDeforestationSuite.scala
hail/src/test/scala/is/hail/expr/ir/ArrayFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/CallFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/DictFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/GenotypeFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/IntervalSuite.scala
hail/src/test/scala/is/hail/expr/ir/LiftLiteralsSuite.scala
hail/src/test/scala/is/hail/expr/ir/LocusFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/MathFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala
hail/src/test/scala/is/hail/expr/ir/RandomFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/SetFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala
hail/src/test/scala/is/hail/expr/ir/StringFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/StringLengthSuite.scala
hail/src/test/scala/is/hail/expr/ir/StringSliceSuite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/UtilFunctionsSuite.scala

- Added an implicit parameter to `assertEvalsTo` to specify the execution strategies you want to ensure support the IR instead of silently failing
- For every test suite that uses `assertEvalsTo`, declared the set of execution strategies that work for a majority of the tests in that suite, overriding individual test methods when necessary
- This gives pretty easy visibility as to the progress of every test block
cc: @cseed

Specify which execution strategies should pass for assertEvalsTo

---

batch/batch/client.py

This slows the exponential growth in sleeps dramatically. Enough that the tests don't sometimes wait 30 seconds to learn that a batch is finished. On my laptop, the tests just finished in less than three minutes.

[batch] much slower exponential backoff for wait

---

hail/src/main/scala/is/hail/annotations/aggregators/RegionValuePrevNonnullAnnotationAggregator.scala
hail/src/main/scala/is/hail/io/RowStore.scala
hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/test/scala/is/hail/annotations/UnsafeSuite.scala

emitPackEncoder now supports requested type
I see a small (few percent) increase in performance in import_vcf/write on a gVCF file.  Still, getting rid of a RVB is always a good change.

don't use rvb in writeRowsSplit
