ci/ci/github.py

The latest changes to CI introduced a bug where an old build status
can be reported to GitHub because we do not always clear the
intended_github_status when we change the build_state. This PR
fixes that.

[ci] always update github_status when build state changes

---

build.yaml
hail/python/hail/backend/backend.py
hail/python/hail/context.py
hail/python/hail/experimental/codec.py
hail/python/hail/experimental/compile.py
hail/python/hail/fs/hadoop_fs.py
hail/python/hail/ir/base_ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/hail/methods/impex.py
hail/python/hail/stats/linear_mixed_model.py
hail/python/hail/utils/java.py
hail/python/hail/utils/misc.py
hail/python/hail/utils/tutorial.py
hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/backend/Backend.scala
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
query/Dockerfile
query/Makefile
query/query/query.py

This changes allow `hl.init()` to run against the query service without starting JVM/Spark on the client:
```
$ python3
Python 3.7.3 (default, Oct  7 2019, 12:56:13) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hail as hl
>>> hl.init(_backend=hl.backend.ServiceBackend())
Welcome to
__  __     <>__
/ /_/ /__  __/ /
/ __  / _ `/ / /
/_/ /_/\_,_/_/_/   version 0.2.34-0ef20f14e0c1
LOGGING: writing to /home/cotton/hail/hail-20200402-0120-0.2.34-0ef20f14e0c1.log
```
- Move initialization of Java HailContext from init to SparkBackend ctor.  There is no JVM or Java HailContext when using the service backend.
- Env no longer carries the gateway.  (Next: jvm)
- make Java HailContext.tmpDir construction lazy.  It requires …

[query] hl.init() against query backend without starting JVM/Spark

---

hail/src/test/scala/is/hail/fs/FSSuite.scala
hail/src/test/scala/is/hail/fs/gs/GoogleStorageFSSuite.scala
hail/testng.xml

There is a `testng-build.xml` that is used by build.yaml and tests the google storage fs.

[query] don't test GoogleStorageFS by default

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala

Emit was taking two MethodBuilder arguments, one directly and one embedded in an EmitRegion. This PR replaces the EmitRegion argument with a Value[Region]. It also makes a couple other simple refactorings that were personally helpful in understanding the structure of Emit.

[query] cleanup redundent MethodBuilders in Emit

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/expr/types/physical/PNDArray.scala
hail/src/main/scala/is/hail/expr/types/virtual/TNDArray.scala
hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
hail/src/test/scala/is/hail/expr/types/physical/PNDArraySuite.scala
hail/www/index.md

This PR gets rid of the vestigial `flags` and `offset` fields in `PNDArray` and `TNDArray`

[query] Pull unused fields out of NDArray

---

hail/python/hail/table.py

This fixes one mistake (right join does not set fields in the right table to missing), and makes the join table to be more precise. Keys are arrays of columns/fields of the table. They need to be present (they must be of same length and type for a join to be performed). The values are what are considered. The description also doesn't give a clear idea that left/right join is really about returning all rows from left/right table, and then joining the right/left table's fields depending on matches.

[query/docs] fix table join description.

---

hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/io/Decoder.scala
hail/src/main/scala/is/hail/io/Encoder.scala

Don't love allocating input/outputstreams per row, but still better than before.

[query] Don't create java objects in TableParallelize

---

build.yaml
hail/python/hail/backend/backend.py
hail/src/main/scala/is/hail/backend/Backend.scala
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/expr/ir/ExecuteContext.scala
hail/src/main/scala/is/hail/expr/ir/FoldConstants.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Optimize.scala
query/.gitignore
query/Makefile
query/deployment.yaml
query/query/query.py
query/service-account-batch-pods.yaml
query/service-account.yaml

It is able to execute a trivial pipeline without the JVM on the client.  The countdown down to a fully functional Hail Query service begins now.  I will start running the Python tests against the service to benchmark our progress.
The main blockers are:
- Table lowering @tpoterba @patrick-schultz @catoverdrive 
- The shuffle service @tpoterba @danking 
- Reading, writing and threading the (per-user, for the query service) filesystem through execution.  I'll be working on this.
- A Batch backend for distributed execution.  I will do this once there is enough functionality to execute something big/interesting.
It's happening!

[query] minimally functional query service

---

hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
hail/src/main/scala/is/hail/expr/types/physical/PBinary.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalBinary.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalString.scala
hail/src/main/scala/is/hail/expr/types/physical/PString.scala

Also make various PCode/PTypes improvements, notably removing `bytesAddress`
from `PString`, and adding a proper `PBinaryValue` class for byte indexing as a `PCode`.

[query/pcode] Convert `hamming` string function to registerPCode

---

hail/build.sbt

Couldn't build with sbt after googleFS changes. Couldn't download the proper LZ4 dependency.

Update build.sbt dependencies

---

hail/www/template.xslt

Removed id from anchor tags. Unneeded (all anchor tags should have same style, or determined by nesting level in menu, and now not used to make active links), less for Kumar to remember to do when adding pages.
Also removed cpage == "" check. By RFC2616, cannot have empty pathname; if none is provided "/" is defaulted to.
https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html
"The most common form of Request-URI is that used to identify a resource on an origin server or gateway. In this case the absolute path of the URI MUST be transmitted (see section 3.2.1, abs_path) as the Request-URI, and the network location of the URI (authority) MUST be transmitted in a Host header field."
and 
"The absoluteURI form is REQUIRED when the request is being made to a proxy. "
Also verified in …

[www] remove id from links, make location.pathname comply w/ RFC2616

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala

The current ptype inference doesn't account for the fact that we're serializing through en EType and could potentially generate a different PType when decoded. I pulled out a bunch of the type/codec stuff onto the IR node since we'll use it in InferPTypes and also in Emit.

[query] fix ptype inference for CollectDistributedArray

---

ci/ci/ci.py
ci/ci/github.py

CI was getting 422s from GitHub. Using a
`raise_for_status=True` ClientSession circumvented gidgethubs native
error handling logic smothering the HTTP response body where github
places critical debugging information. Aiohttp is aware that
`raise_for_status` provides no access to the response body. They addressed
this in https://github.com/aio-libs/aiohttp/pulls/3892, but that has not
been released because 4.0.0 has not yet been released.
Moreover, `gidgethub` incorrectly handles the too many statuses response. I'll PR a fix into their repo. For now, I've added a bit more information the logs and fixed the main issue, the missing `['status']`.
Another relevant issue: https://github.com/aio-libs/aiohttp/issues/4600.

[ci] better errors on bad github response and fix too many status updates

---

hail/python/hail/docs/index.rst
hail/python/hail/docs/libraries.rst

I added libraries to the sidebar, added a libraries page, and moved up "cheat sheets" and "how to guides" about "Datasets" and "Annotation Database". I figure documentation should be together, as opposed to split up by datasets
Looks like:

Add Libraries to Sidebar

---

auth/auth/auth.py

This means tokens obtained via `hailctl auth login` won't expire (but can be explicitly revoked by `hailctl auth logout`)

[auth] make api auth flow tokens non-expiring

---

hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala
hail/src/test/scala/is/hail/expr/ir/GenotypeFunctionsSuite.scala

This illustrates one of the footguns in using CodeBuilder. When using
functionality like ifx, we must be sure to actually put the resultant
code on the CodeBuilder in the block we pass to ifx. Otherwise we won't
add any code and the behavior may be surprising.
This is basically equivalent to storing some Code in a variable and then
never passing that variable into a returned Code, so it is never
executed.

[query] Fix dosage length check.

---

hail/python/hail/ir/table_reader.py
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/expr/ir/AbstractMatrixTableSpec.scala
hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/NativeReaderOptions.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
hail/src/main/scala/is/hail/utils/Graph.scala
hail/src/main/scala/is/hail/variant/ReferenceGenome.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

@danking @tpoterba I wasn't sure if this should go to compilers or services team.  I randomly picked Dan.  Who "owns" GoogleStorageFS?  ServiceBackend?  Let's discuss in staff meeting this week.
- ExecuteContext aded to IRParserEnvironment (maybe should be renamed IRParserContext now?)
- TableReader in general will need the filesystem for construct.  This breaks the json4s de/serializer model.  I started expanding the serializers and writing them by hand.  Just did the TableNativeReader for now.  We might reconsider the mix of custom and JSON in the printed format at some point in the future.
- A bunch of functions take a hc but only need an fs.  More of this to come.
```
hl.init(_backend=hl.backend.ServiceBackend())
t = …
```

[query service] example read_table works

---

internal-gateway/internal-gateway.nginx.conf
router-resolver/router_resolver/router_resolver.py

This change is temporary. I do not intend to keep the extra hop to `auth` on all internal-gateway requests.
Once all the TLS changes go in and everything in the cluster is TLS-secured, then I can switch the internal gateway to unconditionally use HTTPS and remove the router-resolver's extra endpoint.
I've already deployed this (I need it to get batch tests to pass in my namespace.

[internal-gateway][router-resolver] get optional TLS running

---

ci/ci/ci.py
ci/create_database.py
ci/deployment.yaml
gear/gear/database.py

This PR teaches gear/database.py to respect four more MySQL configuration parameters: `ssl-mode`, `ssl-ca`, `ssl-cert`, `ssl-key`. In particular, we can now turn TLS on or off and rotate keys by simply changing secrets and restarting the services. Since all sql-config secrets (except those in my namespace) currently have no certs, no keys, and no ssl parameters, after this PR merges all services will still use plaintext communications to the database.
After this PR merges, I will update the root secret as well as all the service secrets (e.g. sql-auth-user-config) to have a shared client cert/key and our sql database's cert. Moreover I will set `ssl-mode` to `VERIFY_CA` which means (in our world, at least) verify the server's certificate but not the hostname (we use IPs to connect to our …

[ci][batch][notebook][auth] TLS DB connections

---

ci/create_database.py

If you look in the body of create_database, you will see that I copy the
keys from an existing sql-config using `get`. This propagates the `None`s
rather than leaving the keys missing. This fix changes `write_user_config`
to filter out keys set to None. Such keys should not appear in normal
configs because we never use `null` in our configs.

[ci] fix create_database

---

gear/gear/database.py

I fixed sql-config.cnf in the last change, not sql-config.json.
I just changed everything to treat a key being `null` in JSON the
same as the key not existing.
The situation now:
- sql-config.cnf will not have the string None (seems right, cnf is for MySQL)
- sql-config.json might have `null` which is treated the same as a missing key

[ci] actually fix nullness in sql config

---

ci/ci/build.py

The error message you get is this:
```
Error from server (BadRequest): a container name must be specified for pod blog-0, choose one of: [nginx blog]
```
This option is described in `kubectl logs --help` as:
> --all-containers=false: Get all containers logs in the pod(s).

[ci] fix for waiting on a pod with multiple containers

---

hail/src/main/scala/is/hail/expr/ir/agg/CallStatsAggregator.scala

This is the same issue as #8487. Not actually generating the error
throwing code.

[query] Fix CallStats fatal assertion

---

build.yaml
site/deployment.yaml

This change brings the site deployment naming scheme in line with
our other k8s Deployments and also adds a `wait` to build.yaml so
that we check that the site has come up successfully.

[site] actually check that site is alive

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala

This change alters the signature of IEmitCode's apply method to take
a thunk returning a PCode, rather than a PCode. This was an issue
because the CodeBuilder is built up in strict append order. In an idiom
like:
EmitCode.fromI(mb) { cb =>
cb += setupIsMissing
val isMissing = missingExpr
cb += setupThePCode
val pc = pcodeExpr
IEmitCode(cb, isMissing, pc)
}
We were running all of the Code added to the CodeBuilder as a sort of
"setup" before computing the missingness expression. There was no way to
sequence this such that the Code needed to produce the PCode was not
also run in the setup, thus potentially leading to extra work, even when
the result would be missing, like in hamming.
By changing the signature of apply to take a thunk that produces
a PCode, we give callers the ability to …

[query] Fix subtle hamming performance regression/bug

---

ci/ci/ci.py
ci/ci/templates/pr.html

`wb.repo` is not a thing, the thing is `repo` which is `hail-is/hail`.

[ci] fix PR number link

---

ukbb-rg/Dockerfile.browser

AFAICT, CRAN speaks TLS. This command works in the r-base docker image.

[ukbb-rg] use tls to talk to CRAN

---

ci/ci/ci.py
ci/ci/github.py
ci/ci/templates/pr.html
ci/sql/estimated-current.txt
ci/sql/invalidated-batches.sql

cc: @tpoterba 
Since my mind was already thinking about CI to address other issues, I thought it prudent to implement this longstanding request.
The key idea is that each batch now has a target sha, source sha, and an attempt id. When we refresh state from batch, we look for the oldest batch with the newest attempt_id. We increment attempt_id whenever we `_start_build` on a batch. If the source sha changes, we set the attempt id to zero. It will be incremented to one the next time we build. In this manner, we prevent CI from refreshing from batch and blowing away a retried batch even though it has a higher batch id (and we always prefer lower ids).
Retry is implemented in the standard a PR is noted as needing a retry and the watched branch is informed that its state has changed. The heal …

[ci] add a retry button

---

hail/python/hail/expr/types.py
hail/python/hail/genetics/reference_genome.py
hail/python/hail/ir/__init__.py
hail/python/hail/ir/export_type.py
hail/python/hail/ir/matrix_writer.py
hail/python/hail/ir/table_writer.py
hail/python/hail/linalg/blockmatrix.py
hail/python/hail/methods/impex.py
hail/python/hail/table.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/TableValue.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
hail/src/main/scala/is/hail/io/gen/ExportBGEN.scala
hail/src/main/scala/is/hail/io/vcf/ExportVCF.scala
hail/src/main/scala/is/hail/linalg/RowMatrix.scala
hail/src/main/scala/is/hail/utils/ExportType.scala
hail/src/main/scala/is/hail/utils/richUtils/RichRDD.scala

[query] Don't call into JVM for parallel/export_type

---

router/deployment.yaml

The two entries are the same so we never noticed. I saw it when I was switching ports to 443.

[router] remove duplicate batch service

---

hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala

I had to modify the way stream lengths are tracked in the emitter to be able to handle StreamTake. The new way is also simpler, and moves in the direction of the new CodeBuilder style.
Now `SizedStream` is 
```
case class SizedStream(setup: Code[Unit], stream: Stream[EmitCode], length: Option[Code[Int]])
```
The `setup` must be emitted before either the `stream` or the `length` are used. This allows the length and stream to share setup code.

[query] refactor stream length tracking

---

ci/ci/ci.py

The users are always external, so they need to be external urls.

[ci] fix retry and authorize sha links

---

hail/python/hail/expr/types.py
hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala
hail/src/main/scala/is/hail/expr/types/physical/PBaseStruct.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalBaseStruct.scala

My intention is to start to replace my custom `CodePTuple` thing with the new standard `PBaseStructCode`. I've rewritten `MakeNDArray` to start doing this. 
This also fixes `IEmitCode.map`, which was broken in cases where the `CodeBuilder` ended in jumps.

Fix `IEmitCode.map`, Rewrite `MakeNDArray` in `CodeBuilder` style

---

hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/types/physical/PBaseStruct.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalStruct.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalTuple.scala
hail/src/main/scala/is/hail/expr/types/physical/PStruct.scala
hail/src/main/scala/is/hail/methods/IBD.scala

In looking at your PSelectFieldsStruct PR, I got a bit angry at the number of abstract methods on PStruct. This cleanup should make your PR smaller and simpler. We'll sort out the constructible methods at some point too.
All the methods I changed were ones that are always used to do type-level manipulation to return a new constructible type that is fed into an RVB. Returning a PCanonicalStruct to these usages is the correct thing.

[query] Refactor PStruct to avoid abstract methods

---

hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/asm4s/package.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
hail/src/main/scala/is/hail/lir/Emit.scala
hail/src/main/scala/is/hail/lir/X.scala
hail/src/main/scala/is/hail/lir/package.scala

Plus:
- Boolean ldc (load constant) instructions need an int, not a boolean.  JVM seems OK with it, but the asm bytecode verifier rejects it.
- In Apply codegen, the zip in function lookup was potentially truncating the arguments, selecting an incorrect function.  Fix, and simplify the definition of `methods`.
- Fix/simplify asm error reporting from asm in lir Emit.  The old code was crashing inside asm.  I used the new code to debug some bytecode issues, it works well.
- compute max locals/stack, needed by the asm verifier (CheckClass).
@konradjk This fixes your class not found issue.

[query] fix incorrect method lookup

---

build.yaml

The `wait` directive tells CI to wait for the service to come up before
continuing with deployment. If the service fails to come up (including
failing to respond to the readiness checks) then CI will fail the build.

[router] ensure the router comes up during deployment

---

ci/ci/github.py

Gidgethub does not properly handle this error response. The right answer is to fix gidgethub, but, alas, too much to do and too little time.

[ci] improve error message when we exceed the commit SHA status limit

---

site/hail.nginx.conf

The previous location directive redirected every URL matching that prefix to `/batch`, thus losing the suffix. I'm testing right now.

[site] fix matches

---

site/hail.nginx.conf

`try_files` does not automatically try appending a `/` the way
that other directives do, so you have to explicitly ask for that
which then triggers and `index.html` lookup

[site] fix again for directories

---

hail/python/hail/docs/_templates/layout.html

missed during testing: there is a brief interval where z-height of placeholder navbar is smaller than the sphinx side nav element, causing a flash from blue to white after load.

[www] fix navbar flash

---

hail/python/setup.py

Documentation for this field's use is availible at the end of the linked
section. We can maybe version the docs url in order to host the docs to
the released versions.
https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords

[infra/docs] Add setup.py project urls.

---

hail/python/test/hail/expr/test_ndarrays.py
hail/python/test/hail/matrixtable/test_matrix_table.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala

It was wrong for the `elemRef` values in the emit code `NDArrayMap` and `NDArrayMap2` to use `mb` as opposed to `elemMB`. They were being emitted in a different method builder than they were being used in. In order to fix this, I had to fix `NDArrayEmitter` to take an `EmitMethodBuilder[C]` instead of `EmitMethodBuilder[_]`, so I did that. I also had to pass the arguments along from the `mb` method builder to the `innerMethod` method builder in the `NDArrayEmitter` emit method. Factored out `mb.getParamsList()` to make that easier.
I also added a new test that is remedied by this change.

NDArray Map Method Builder Scoping

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala

This is a simple refactor, that moves `Stream[A]` to a top-level class. Some of my wip depends on this, so it will be helpful to get it merged. This should also simplify merging `Stream` with the PType infrastructure, where `Stream` should become a `PCode`.

[query] refactor Stream to top-level class

---

hail/www/index.md

We use Broad's corporate license now.

[www] Remove Yourkit homepage shoutout.

---

ci/ci/build.py

I missed a few places where CI tries to get the logs of a service.
All of these can fail if the pod has multiple containers. I added
`--all-containers` to ensure it never fails for multi-container Pods.

[ci] always handle multiple containers

---

hail/python/hail/expr/types.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/expr/types/physical/PNDArray.scala

This PR switches the `NDArrayEmitter` to emit column major data by default. However, it still allows things like the result of `MakeNDArray` to come back as row major. This simplifies code that calls BLAS considerably, since we no longer have to manually flip to column major and then flip back. 
There's still unnecessary copying going on, just less. `emitNDArrayStandardStrides` is not a very smart method, always copies the data even if it's already in the right format. At some point a smarter version of this should check if the ndarray exists in memory with the proper striding already.

NDArrays Default to Column Major

---

benchmark/.gitignore
benchmark/Dockerfile
benchmark/Makefile
hail/Makefile

* push image to unique tag based on docker digest
* prevent multiple overlaid benchmarks from using incorrect image
Thought this was already in, oops...

[benchmark] Fix docker usage

---

hail/src/main/scala/is/hail/asm4s/CodeBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala
hail/src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala

@johnc1231 I realized there's a really easy way to catch the kinds of dead-code-after-a-goto bugs we were running into, so I went ahead and did it.
The basic idea is: most operations on a CodeBuilder (which ultimately call `append`) assert that the current `code` doesn't end in a `ControlX`, such as a jump. `CodeBuilder.define` is the escape hatch, which works whether `code` ends in a jump, or doesn't, in which case the previous code falls through to the new label.

[query] add checks to CodeBuilder

---

hail/src/main/scala/is/hail/experimental/ExperimentalFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/CallFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/DictFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
hail/src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/NDArrayFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/RandomSeededFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/ReferenceGenomeFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/SetFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
hail/src/test/scala/is/hail/expr/ir/FunctionSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/RandomFunctionsSuite.scala

The overloading made development a huge headache. I think we should consider overloading more than ~2-way bad practice and try to avoid it.

[query] Refactor function registry to not use overloading

---

hail/build.gradle
hail/scripts/test-dataproc.sh

Our public interface is python. The public interface of Spark that we use, AFAICT, does not depend on any non-Spark-defined classes. Ergo, we should hide away all our dependencies.
I intended to shade every bundled package except for breeze-natives, because I think we want to take that from the cluster (and we're willing to lock into Spark's version). `RandBasis` (a breeze class) takes as argument a random generator from `math3`, so I keep the Apache Commons Math3 library unbundled and not shaded. Everything else should now be shaded.

[hail] Shade most of our bundled dependencies

---

hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/expr/ir/agg/LinearRegressionAggregator.scala
hail/src/main/scala/is/hail/expr/types/physical/PArrayBackedContainer.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalArray.scala
hail/src/main/scala/is/hail/expr/types/physical/PContainer.scala
hail/src/test/scala/is/hail/expr/types/physical/PContainerTest.scala

Fixes #8349.
The `anyMissing` implementation on `PArray` was wrong, and could return false if the only missing elements were in the last aligned 32 bits containing the end of the missing bits. This in turn let some rows be included in the regression even if some of the covariates were missing.

[query] fix linreg aggregator correctness bug

---

hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/expr/types/physical/PCode.scala
hail/src/main/scala/is/hail/expr/types/physical/PNDArray.scala

Simplified `NDArrayRef` considerably by switching to `CodeBuilder` interface, adding `EmitCode.mapN`, and adding `PNDArrayCode`. 
Thanks @patrick-schultz for contributing code for `EmitCode.mapN`.

[query] PNDArrayCode / NDArrayRef CodeBuilder

---

hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

This PR lowers `TableParallelize` and beefs up the tests for parallelize a bit. If you see a simpler formulation of the math to compute `start` and `length` let me know.

Lower TableParallelize

---

hail/src/main/scala/is/hail/asm4s/CodeBuilder.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala

Replace, the top level entry into `emit` with `emitI`. Move anything that had
already been converted, as well as constants/literals, into `emitI`. Added the
necessary fallbacks.

[query] Begin moving from EmitCode to IEmitCode in Emit

---

build.yaml
hail/Makefile
hail/scripts/deploy.sh

This pains me. As currently set up, there's no way to deploy the wheel that we tested because that wheel is tightly coupled with a bunch of "temporary" file paths. I'm not confident I can untangle all this into a clean promote-what-you-test deploy right now. This PR should get us back to correct deploys until I can take the time to get us to proper promote-what-you-test deploys.

[deploy] deploy rebuilds wheel from scratch and uploads artifacts

---

hail/build.gradle
hail/python/hail/backend/backend.py
hail/python/hail/context.py
hail/src/main/scala/is/hail/HailContext.scala
query/query/query.py

HailContext initialization overrides any existing log4j configuration, which can lead to the logs ending up in an unexpected location. This PR adds an option to HailContext initialization to skip this configuration step.
I also included two unrelated changes to this PR:
- Not bundling the transitive dependencies for `com.indeed:lsmtree-core:1.0.7`, which don't seem to be needed and can lead to classpath conflicts.
- Allowing the `quiet` option during initialization to silence the warning issued when initializing with pip-installed Hail.

Provide option to skip log4j configuration

---

hail/python/hailtop/hailctl/curl.py

Currently, `hailctl curl` uses `external_url` instead of `url`. As a result,
if `hailctl curl` is used inside a GCE VM or on a k8s pod, the url will always
be `....hail.is` to which GCE VMs and k8s pods likely lack credentials.
This was a mistake when I first wrote curl. At that time, I was only using it for
local testing. It will still work for local testing because our deploy configs are
all `external`.

[hailtop.curl] curl should use localized url

---

build.yaml
hail/python/hailtop/batch/backend.py
hail/python/hailtop/batch/docs/service.rst
hail/python/hailtop/config/__init__.py
hail/python/hailtop/config/user_config.py
hail/python/hailtop/hailctl/__main__.py
hail/python/hailtop/hailctl/config/cli.py
hail/python/test/hailtop/batch/test_batch.py

Currently, the test_batch fails for local users.
These changes enable test_batch to work for local users with minimal configuration. The only necessary step is for a user to execute:
```
hailctl config set batch/billing_project hail
```
All other steps are handled by the test suite, including uploading test data if it does not already exist. I believe this obsoletes `hail-services` bucket. Is that correct?
The main change necessary to support this was a Hail configuration system. There is now a file stored in an [XDG acceptable](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) location to which we can read and write sectioned key-value pairs. The `ServiceBackend` looks in this configuration file if the billing_project is unspecified. The file format is defined by …

[hailctl][batch] add hailctl config & make tests work locally

---

build.yaml
docker/Makefile
docker/genetics/Dockerfile
docker/hail/Dockerfile

This adds two new Dockerfiles. The first has gsutil and pip-wheel-installed
Hail. The second builds on the first adding a number of bioinformatics tools
that were included in the CCG Tutorial.
Deployment to dockerhub is not trivial because, unfortunately, I need to mount
the docker socket even to download and then upload an image (never starting a
container). I'll design and implement some extension to CI that lets me deploy
images to docker hub later. For now, I used dev deploy to build
these (https://ci.hail.is/batches/33294) and then manually pulled them and
uploaded them to PyPI as hailgenetics/hail:0.2.37 and
hailgenetics/genetics:0.2.37. I particularly appreciate criticism of the names.

[hail] automatically build two bioinformatics images 

---

build.yaml
hail/python/hailtop/config/deploy_config.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

In the words of Camille Fournier: "An Engineer II rarely makes the same mistake twice."
I will be damned if I ever forget to `export HAIL_DEPLOY_CONFIG_FILE=...` ever again.

[deploy-config] add service deploy-config location to defaults

---

hail/src/main/scala/is/hail/expr/ir/TableIR.scala

My change https://github.com/hail-is/hail/pull/8581 introduced a bug, count of native reads with pushed down intervals could give the wrong answer.

[query] fix bug in TableNativeReader.partitionCounts.

---

hail/src/main/scala/is/hail/asm4s/package.scala
hail/src/main/scala/is/hail/lir/X.scala

The constant pool may only hold references to JVM things (e.g. a class),
Strings, Floats, Doubles, Ints, and Longs. https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-5.html

[hail] fix constant pool issue

---

hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalLocus.scala

PCLocus wasn't honoring requested requiredness
prev nonnull aggregator requiredness was wrong

[query] fix two requiredness issues

---

hail/python/hail/context.py
hail/python/test/hail/test_context.py

- generate appropriate error message
- don't test

[query] fix hl.spark_context for query backend

---

hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

~~Stacked on #8564~~
Adds a `StreamGrouped` node, which groups a stream into equal size substreams.
Finishes adding support for nested streams in `EmitStream`:
* the element types in `StreamMap` and `StreamFlatMap` may be streams
* for `StreamMap` the resulting element type may also be a stream (`StreamFlapMap` handles that case automatically)
* `Let` may bind streams, whether the body type is stream, value, or void.

[query] Add StreamGrouped node

---

hail/src/main/scala/is/hail/expr/ir/FoldConstants.scala
hail/src/main/scala/is/hail/expr/ir/ForwardLets.scala
hail/src/main/scala/is/hail/expr/ir/Optimize.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/test/scala/is/hail/expr/ir/FoldConstantsSuite.scala
hail/src/test/scala/is/hail/expr/ir/ForwardLetsSuite.scala
hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala

ExecuteContext.scoped() depends on the Spark backend, and all uses of it need to get removed.  A separate PR removes it from the IRParser.  The remaining uses are in BlockMatrix and the Graph/maximal independent set stuff.

[query] remove call to ExecuteContext.scoped from FoldConstants

---

hail/python/hail/backend/backend.py
hail/python/hail/experimental/codec.py
hail/python/hail/experimental/function.py
hail/python/hail/ir/base_ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/hail/methods/misc.py
hail/python/test/hail/experimental/test_codec.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

- SparkBackend has the right context
- skip the parser tests unless on Spark backend

[query] move Python parser entrypoints to SparkBackend

---

hail/src/main/scala/is/hail/expr/ir/TableIR.scala

[query] Loosen TableAggregateByKey assertion

---

hail/python/hail/linalg/blockmatrix.py
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala

When BM gets de-Sparked, this will go away an the structure will be analogous to Table and MatrixTable.
Also, this removes a use of ExecuteContext.scoped(), which is deprecated.

[query] move BlockMatrixIR.pyExecute to SparkBackend

---

hail/python/test/hailtop/batch/test_batch.py

When I last tried to fix this up, I somehow missed the GCS client dependency. This
uses the in cluster location if it is available otherwise it lets Google try to find
the key.

[batch] make hailtop/batch/test_batch work locally

---

hail/python/hailtop/batch/backend.py

The default behavior, is, apparently, to error, not to return `None`. This change makes the missing value case return `None` which triggers the ValueError on the next line.

[batch] give a reasonable error message when no batch billing project is set

---

hail/python/hail/expr/types.py
hail/python/test/hail/expr/test_ndarrays.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala

This PR:
- Fixes it so that we can pass numpy ndarray literals with no elements.
- Makes sure we don't call BLAS when shape contains a 0. 
- Allows reshapes that contain a 0.

Add Support for NDArrays with Zero elements

---

hail/python/hail/expr/types.py
hail/src/main/scala/is/hail/expr/ir/ExtractIntervalFilters.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/types/virtual/TNDArray.scala
hail/src/test/scala/is/hail/expr/ir/ExtractIntervalFiltersSuite.scala

Fix bugs that show up when we typecheck the literal value on construction.  The assert is commented out for now because it is expensive.  Later, I'll add a flag to control expensive checks like this and checkRVDKeys and the tests should be run with expensive checks turned on.

typecheck literal

---

hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

Addressing what we discussed in lowering meeting yesterday. I've refactored TableStage to accumulate a bunch of let bindings that can be wrapped around the IR you want to generate with `TableStage.wrapInBindings`. See `TableCollect` for an example of this.
This definitely generates the IR we wanted, but I'd be very open to suggestions about how to make this more ergonomic to use (had to generate a lot of UIDs and Refs manually for `TableParallelize`). 
cc @cseed @tpoterba

[lowering] TableStage Refactor / TableParallelize Lowering Improvement

---

hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/expr/ir/package.scala

Some light refactoring of TableStage to change how context/body is defined; this is pretty similar to how BlockMatrixStage currently handles contexts.
I prefer this way of defining the body of a partition because I think it will make writing table joins more natural and lead to less boilerplate ref generation; I think BlockMatrixDot provides a pretty good illustration of what a join body will look like, in general. (The context handling is different, and I don't think we want to do what BlockMatrixStage does w.r.t contexts right now.) This is slightly different from the code in master; I've rewritten `blockBody` to make use of `bindIR` and (currently non-existent) `foldIR` instead of manually generating refs to better illustrate flow.
```
case x@BlockMatrixDot(leftIR, rightIR) =>
val left …
```

[query] refactor TableStage.context for ease of use and better scoping

---

hail/python/hail/docs/getting_started.rst

It's clear we are failing to explain the necessity of a compatible BLAS library. I hope this will stem the flow of bug tickets and support questions related to a misconfigured, missing, or incompatible BLAS library.

[hail] A compatible BLAS library is an install requirement

---

hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala

There was no way to get the class printout from resultWithIndex.
Must have been droped at some point

[query/debug] add print parameter back to classesBytes

---

ci/ci/github.py

As currently written, if `git clone` returns a non-zero exit code, the script
should exit immediately. I am not sure why this GnuTLS recv error (pasted below)
does not trigger a non-zero exit code from git clone. This change both
explicitly echoes the exit code so we can be sure of our sanity and adds a check
that I'm confident will fail if no git repository was cloned (`git status`).
```
+ date
Wed Apr 29 21:15:15 UTC 2020
+ rm -rf repo
+ mkdir repo
+ cd repo
+ '[' '!' -d .git ']'
+ retry clone
+ clone
+ set -e
++ mktemp -d
+ dir=/tmp/tmp.5R5aJAlgEm
+ git clone https://github.com/hail-is/hail.git /tmp/tmp.5R5aJAlgEm
Cloning into '/tmp/tmp.5R5aJAlgEm'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early …
```

[ci] Make git clone resilient to failure 

---

hail/python/hail/linalg/blockmatrix.py
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala

@cseed following up on my comment from #8642.
There's no need to keep java block matrices as a python concept anymore, since there's no operation that isn't encoded in the IR.
I checked with Konrad and Jacob before removing, although it turns out that I'd at some point previously already removed the Scala function that they were calling through `_jbm`, so the `._jbm.filterRowIntervalsIR` call hasn't worked for a while now, anyways.

[query] remove BlockMatrix._jbm from python

---

hail/build.gradle

The logic trying to infer the version of various Spark dependencies
was total garbage and almost certainly except for a few specific
cases.  I was feeling aggressive.  I nuked it.  If we want to support
building with other versions of Spark reliably (whcih we don't test)`,
we should find another way.

Bump versions to Spark 2.4.5 and Scala 2.11.12.

---

build.yaml
hail/Makefile
hail/build.gradle
hail/python/hail/docs/getting_started.rst
hail/python/hail/docs/getting_started_developing.rst
hail/python/hailtop/hailctl/dataproc/start.py

Changes:
- removed unused py4jVersion from build.gradle
- pin breeze native version to version required by spark.  This was not easy!  I do it by creating a configuration that just depends on Spark, and then a resolution rule for all configurations that says only accept the breeze natives version corresponding to the version requested by spark.
- determine sparkMajorVersion from sparkVersion (strip patch version)
- in docs, everywhere we use SPARK_VERSION, also specify SCALA_VERSION.  I verified 2.4.0.cloudera is built against Scala 2.11.
- added SCALA_VERSION to hail/Makefile
- make Makefile versions match build.gradle defaults (somewhat annoying they are duplicated)

fix Spark and Scala versioning

---

hail/build.sbt
hail/project/plugins.sbt

The date time changes added `-target:jvm-1.8` to build.gradle which quietly
broke SBT. It wasn't a problem for me because I wasn't hacking on Hail until
recently.
Moreover, [Ensime](https://ensime.github.io) is dead, so I'm switching over to
bloop. This plugin is necessary for SBT to generate bloop configuration files.

[hail] fix sbt, support bloop

---

hail/src/main/scala/is/hail/expr/ir/agg/ApproxCDFAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/ArrayElementLengthCheckAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/CallStatsAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/CollectAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/CollectAsSetAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/CountAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/GroupedAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/LinearRegressionAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/MonoidAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/PrevNonNullAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/StagedAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/TakeAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/TakeByAggregator.scala

Also protect and rename the internal agg methods.

[query/agg] Remove unused `dummy` parameters

---

.dockerignore
docker/Makefile
docker/stat-permissions.sh
gateway/deployment.yaml
gateway/gateway.nginx.conf
internal-gateway/service.yaml
router-resolver/deployment.yaml

- `stat -c` doesn't work on Mac
- I have a bloop directory now (related to metals which is a Scala Emacs IDE)
- I had a rogue x in the definition of gateway's deployment
- I had missing semicolons in gateway's deployment
- the router resolver *is* TLS enabled
- the internal-gateway is *not* TLS enabled

[many] Fixes needed to get TLS working for CI, Batch, & Auth

---

hail/src/main/scala/is/hail/expr/ir/GenericLines.scala
hail/src/main/scala/is/hail/io/fs/package.scala
hail/src/main/scala/is/hail/utils/package.scala
hail/src/test/scala/is/hail/io/compress/BGzipCodecSuite.scala

Write loading lines from text files in a way that can be used by Spark or table lowering.  This will be to lower the VCF and text file importers.
This handles three cases:
- an (splittable) uncompressed file,
- a (splittable) bgzip compressed file, and
- an non-splittable compressed file compressed by some other codec.  In this case, it will be loaded as a single partition.
I test each of the three cases.  I also ported the prexisting partition test that generates random splittings and tests that in the bgzip case.  I tested with the number of tests turned up to 10,000.
Two ideas here:
Each line has a fixed offset depending on the case (file offset, virtual offset, or decompressed offset).  The split defines a partition of the offset spaces. For a partition (start, end), and line with …

[query] add GenericLines

---

hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

This PR lowers `TableGroupWithinPartitions` and adds a test for it.

Lower TableGroupWithinPartitions

---

router/router.nginx.conf.in
tls/config.yaml

So I both screwed up by including the TLS proxy settings in the location as
well as setting the router to port 80, which the gateway does not respect.
The gateway tries to speak to the router on 443. All the router services
should speak TLS on 443, even if they proxy to a service speaking plain
HTTP on 80.

[ukbb-rg][admin-pod][router] fix ukbb-rg connectivity

---

ci/deployment.yaml
query/deployment.yaml
scorecard/deployment.yaml

to be a little more in line with need, and to make the non-preemptible pods more packable.
The ukbb-rg pods are pretty slow, so I didn't reduce them.

[ci, query, scorecard] reduce k8s requests

---

hail/build.gradle

In our use case, the shaded Hail jar runs into dependency conflicts due to `org.apache.commons.io`, which is pulled in by `com.indeed:lsmtree-core`. This PR shades `org.apache.commons.io`; unfortunately, shading all of `org.apache.commons` was problematic.

Shade org.apache.commons.io

---

hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/GenericTableValue.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala

- Teach `unfold` to accept close and close0.
- Teach `unfold` to use the language of `Stream`, i.e. `setup0` and `setup`.
- Teach `unfold` to not require `setup` and `setup0`.

[hail][ir] improve Stream.unfold signature

---

hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala

When you screw up an `Apply` IR, you previously received no information as
to why. This change teaches the function registry to display all signatures
that match the function name but not the types, assisting a developer in
diagnosing whether they got the name wrong or the types wrong.

[hail][ir] teach function registry to raise helpful errors

---

hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala

The argTypes were duplicated. That is just wrong. Moreover, the typeParams are
printed as if they are the types of parameters, not formal parameters themselves.
This uses the well-understood, Scala-style square-bracket notation.

[hail][ir] fix & improve IRFunction.toString

---

hail/src/main/scala/is/hail/expr/ir/AggOp.scala
hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/ComputeUsesAndDefs.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/ForwardLets.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/main/scala/is/hail/expr/types/TypeWithRequiredness.scala
hail/src/main/scala/is/hail/expr/types/virtual/TNDArray.scala
hail/src/main/scala/is/hail/stats/package.scala
hail/src/test/scala/is/hail/expr/ir/RequirednessSuite.scala

This PR is already getting kind of massive, so I think I'm going to plan on implementing (extracted) aggregator support separately.
I may also pull out the TableIR stuff into a separate PR and leave this as just implementations of pure value IR nodes, since I ended up needing to add a bunch of stuff to be able to pull minimal PTypes out of reads.
I've written tests for most of the values nodes, but not all of them.

[query] lift requiredness inference into separate pass

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/CallStatsAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/StagedArrayBuilder.scala
hail/src/main/scala/is/hail/io/TypedCodecSpec.scala

A TypedCodecSpec has a reasonable VType on hand: `_vType`. In the Shuffler, I have
found myself repeating myself too often. This seems generally useful.

[hail][io] Teach TypedCodecSpec to create decoders without a VType

---

hail/src/main/scala/is/hail/io/OutputBuffers.scala

Anything with an `OutputStream` must be able to `flush`
said `OutputStream`.

[hail][io] OutputBlockBuffer *must* also flush

---

hail/src/main/scala/is/hail/io/MemoryBuffer.scala

The Shuffler uses MemoryBuffer to apply Hail encoders and decoders on byte arrays. For
example, I need to serialize the ETypes into generated bytecode so I can send it to the
Shuffler at run-time. I serialize the EType object to bytes using an encoder and MemoryBuffer
Then, I base64 encode it and store it as a JVM constant pool String. When I need to start
a Shuffle I base64 decode the string, stuff the bytes in a MemoryBuffer and decode it.

[hail] teach MemoryBuffer to act like ByteArray(In|Out)putStream

---

hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/annotations/RegionMemory.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala

It was wrong for me to check `hasNext` before checking `childIterationCount != blockSize`. If you look at https://github.com/hail-is/hail/blob/master/hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala#L1306, you can see that `LoadVCF`'s `hasNext` loads values into memory. By calling `hasNext` and then not actually processing that value, I was loading a value into memory and then invalidating the pointer before it processed in the next group of rows. 
Thanks to @tpoterba  for helping me figure this out.

TableGroupWithinPartitions Memory Fix

---

hail/src/main/scala/is/hail/io/InputBuffers.scala
hail/src/main/scala/is/hail/utils/TracingInputStream.scala
hail/src/main/scala/is/hail/utils/TracingOutputStream.scala

These are unused, and should mostly remain that way, but it is convenient to
have them on-hand when you need to figure out why an Encoder or Decoder is
misbehaving. A `TracingOutputBuffer` is missing because I did not need it
and have not spent the time to write it.

[hail][io] tracing buffers and streams for debugging

---

hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/io/TextMatrixReader.scala
hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala
hail/src/main/scala/is/hail/io/gen/LoadGen.scala
hail/src/main/scala/is/hail/io/plink/LoadPlink.scala
hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala
hail/src/main/scala/is/hail/utils/TextTableReader.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

This adds the function to TableReader:
```
rowAndGlobalPTypes(ctx: ExecuteContext, requrestedType: Type): (PStruct, PStruct)
```
(The context is necessary for native readers to be able to get the filesystem in order to read the metadata.)
I'm not sure if this is the best way to implement this, but it feels like TableReaders ought to be able to tell you what PType they expect to be decoding into at compile time, since we can use this information to make decisions about requiredness, etc. on IRs that contain TableReads.
I rely on this to extend the requiredness analysis to TableIR nodes; I think it's probably reasonable to have one function that goes from requestedType => PType instead of separate functions for requiredness and other analyses we might want to do un the future, since I don't …

[query] TableRead readers statically know ptypes for a requested ptype

---

hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

This PR lowers `TableTail`. It's very similar to `TableHead`'s lowering, and `TableHead` is less confusing, so may be helpful to look at that one first (this one does a lot of subtracting lengths from total lengths to figure out how many to drop).

[query] Lower TableTail

---

gear/gear/database.py

Got this error in a migration step when dev deploying.
```
File "/usr/local/lib/python3.7/dist-packages/aiomysql/connection.py", line 598, in _read_bytes
data = await self._reader.readexactly(num_bytes)
File "/usr/lib/python3.7/asyncio/streams.py", line 679, in readexactly
await self._wait_for_data('readexactly')
File "/usr/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
await self._waiter
File "/usr/lib/python3.7/asyncio/selector_events.py", line 804, in _read_ready__data_received
data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
The above exception was the direct cause of the following exception:
File "create_database.py", line 263, in <module> …
```

[gear] add new retry for database

---

hail/src/main/scala/is/hail/io/TypedCodecSpec.scala

Just as `buildEmitDecoderF` need not accept a virtual type, we might want to know
the PType that the natural decoder would produce. This PR implements that.

[hail][internal] Teach TypedCodecSpec to supply decodedPType

---

hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

Also build infrastructure for repartitioning table stages without shuffle.
Test does not pass with `allRelational` due to method splitting issues, but did pass when I fixed a few locals=>fields and disabled EstimableEmitter splitting logic.

[query] Lower TableAggregateByKey

---

router/router.nginx.conf.in

Missed one.  Hand deployed, verified it works end-to-end with this.

[query] fix router rule for query service

---

hail/python/hail/genetics/reference_genome.py

ReferenceGenome's `lengths` property is currently documented as returning a list of strings. However, it actually returns a dict of strings to ints.

Correct documented type for ReferenceGenome.lengths

---

hail/python/hail/docs/cloud/google_cloud.rst

Elsewhere, CLI arguments are formatted with double backticks.

Format VEP CLI arguments in GCP docs

---

hail/www/references.md

"Landscape of multi-nucleotide variants in 125,748 human exomes and 15,708 genomes" is currently listed twice on the Hail-Powered Science page.

Remove duplicate entry from Hail-Powered Science list

---

hail/python/hail/genetics/reference_genome.py

ReferenceGenome's `remove_sequence` method is currently documented as returning a bool. However, it doesn't actually return anything.

Correct documented return type for ReferenceGenome.remove_sequence

---

hail/python/hailtop/aiogoogle/auth/__init__.py
hail/python/hailtop/aiogoogle/auth/access_token.py
hail/python/hailtop/aiogoogle/auth/credentials.py
hail/python/hailtop/aiogoogle/auth/session.py
hail/python/hailtop/aiogoogle/container/__init__.py
hail/python/hailtop/aiogoogle/container/client.py
hail/python/hailtop/cleanup_gcr/__main__.py

Added asyncio native client library hailtop.aiogoogle for auth and containers.  Used in cleanup_gcr.  The auth library works with service account keys or application default credentials.  By default, it looks for application default credentials in the standard place created by gcloud.
After we add compute and storage, we can drop the standard client libraries.
cleanup_gcr can be run with `python3 -m hailtop.cleanup_gcr`.
I added a new kind of worker pool thingie, AsyncIOExecutor.  I wanted the cleanup to have maximal parallelism, except limit the number of active requests to something reasonable (in this case, 8).  I couldn't figure out how to do that with the existing stuff.  We might consider moving this to utils to augment/replace the existing mechanisms.

Added hailtop.cleanup_gcr runnable module to clean up gcr images.

---

hail/src/main/scala/is/hail/expr/types/encoded/EType.scala

This mirrors the functionality available on `TypedCodecSpec`. In some cases (the shuffler),
you might be handed a buffer that is already configured, but you still want to create a
decoder whose PType is known to be a subtype of PStruct.

[hail][internal] teach EType to preserve XStruct

---

hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala

In particular, include both the IR context (a series of IR names) and the
environment context (names to iruids). This enables me, as a developer, to
rapidly identify the problematic node.

[hail][internal] Improve error messages when normalize names fails

---

build.yaml

This addresses issues where the gradle download may fail. We retry a command
that is cheap (`--version`) but which requries downloading the gradle binary.

[hail] retry gradle download

---

hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

I added a `StreamLen` IR node. The justification for this were optimization issues in `Simplify` situations like
```
case ArrayLen(ToArray(StreamMap(s, _, _))) => ArrayLen(ToArray(s))
```
The above is not a valid optimization in all cases because if the elements of `s` are not realizable, the optimization will have created an invalid IR that will fail at emit time since elements of an array must be realizable.

StreamLen node

---

hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/types/TypeWithRequiredness.scala
hail/src/test/scala/is/hail/expr/ir/RequirednessSuite.scala

Requiredness stuff was assuming that tuples were well-ordered and contiguously indexed, which is wrong because the pruner can prune tuple elements.
See https://discuss.hail.is/t/arrayindexoutofboundsexception-error-in-hail-0-2-40/1413/5

[query][bugfix] fix handling of subsetted tuples in Requiredness

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/expr/types/physical/PCode.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

I'm PRing this because it's done / short / adds a good test, but it may be possible to eliminate `TableDistinct` in the future in favor of just `TableAggregateByKey`

TableDistinct Lowering + Tests

---

hail/python/hail/docs/cloud/other_cloud_providers.rst

Currently, the [Other Cloud Providers](https://hail.is/docs/0.2/cloud/other_cloud_providers.html#others) documentation says "There are no known open-source resources for working with Hail on cloud providers other than Google and AWS." right after a section on working with Hail on Azure.

Reword docs for other cloud providers

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/types/physical/PCanonicalBaseStruct.scala
hail/src/test/scala/is/hail/expr/ir/DictFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/SetFunctionsSuite.scala

This should fix Julia's bug here: https://discuss.hail.is/t/arrayindexoutofboundsexception-error-in-hail-0-2-40/1413/11
I will make a follow up PR tomorrow splitting things up and making a `PCanonicalTupleCode`. I just wanted to get rid of this blatantly wrong thing.

[query] Fix bad tuple indexing on PCanonicalBaseStructSettable

---

hail/python/hailtop/hailctl/dataproc/connect.py
hail/python/hailtop/hailctl/dataproc/modify.py

`hailctl dataproc connect` and `hailctl dataproc modify` hard-code a default compute zone of us-central1-b. This changes those two commands to use the `compute/zone` value from the user's gcloud configuration if a zone argument is not provided.
@johnc1231 [mentioned this in Zulip](https://hail.zulipchat.com/#narrow/stream/128581-Cloud-support/topic/Unable.20to.20launch.20notebook) the other day.

Use configured compute zone as default for hailctl dataproc

---

hail/python/hailtop/hailctl/dataproc/start.py

Currently, attempting to start a Dataproc cluster without either a region argument or a configured `dataproc/region` results in a long error message `subprocess.CalledProcessError: Command '['gcloud', 'dataproc', 'clusters', 'create', ... ]' returned non-zero exit status 1` with the actual cause obscured above the traceback. That cause is:
```
Failed to find attribute [region]. The attribute can be set in the following ways:
- provide the argument [--region] on the command line
- set the property [dataproc/region]
```
There is some logic to show a nicer error message if no region is provided. However, that is only shown if `gcloud config get-value dataproc/region` fails. When `dataproc/region` is not set, that command succeeds and outputs an empty string. This change handles that case and …

Improve error message for starting a cluster without a region

---

hail/project/plugins.sbt

Fix is to upgrade to Bloop 1.4.1. https://github.com/scalacenter/bloop/issues/1276

[hail][sbt] bloop 1.4.0 has a bug that breaks Java 8 compatibility

---

hail/python/hailtop/hailctl/dataproc/modify.py

`hailctl dataproc modify` has a `--dry-run` argument. That argument is checked before resizing the cluster but not before modifying the wheel.

Respect dry run arg when modifying wheel on Dataproc cluster

---

batch/test/test_batch.py
hail/python/hailtop/batch_client/aioclient.py

There are two errors in the status returned by the worker: one is caught when executing the job and the other is when executing the container (such as uploading log to google storage or timeout error). We were only handling job-level errors correctly.

[batch] fix exit code if error is in container execution

---

hail/python/hailtop/utils/utils.py
hail/src/main/scala/is/hail/services/batch_client/BatchClient.scala
hail/src/main/scala/is/hail/services/package.scala

Add retry infrastructure mirroring Python.
This will hopefully fix the deploy issue.  I think we'll have to grow another set of transient errors to retry related to lower-level networking issues.

[services/Java] retry retryable http client errors

---

batch/batch/front_end/templates/batch.html
batch/batch/front_end/templates/batches.html
ci/ci/templates/index.html
web_common/web_common/static/focus_on_keyup.js

FYI @konradjk 
I tested this with dev deploy for the batch pages. I assume the ci page is the same. This changes the behavior of CI focus to require to enter slash first. I think it's better to be consistent.

[batch] focus search box

---

hail/python/hail/docs/annotation_database_ui.rst
hail/python/hail/docs/cloud/google_cloud.rst
hail/python/hail/experimental/annotation_db.json
hail/python/hail/experimental/db.py
hail/python/hailtop/hailctl/dataproc/start.py

I've copied the Annotation DB data into a requester pays bucket and added a new `hailctl` argument to enable reading from that bucket.
Please also ensure that this new bucket is globally visible and marked as requester pays as part of the review process.

Annotation DB Requester Pays

---

web_common/web_common/static/search_bar.js
web_common/web_common/styles/main.scss

The main issue is that `nth-child-of` still sees the hidden elements. We can instead
use `nth-of-type` and wrap hidden `tr`s in a `div`. Because the `div` is not a `tr`,
it does not appear as part of the `nth-of-type` calculation. The content is still
present on the page, so we can restore it by removing the `display: none` div.

[ci] fix table row highlighting when using on-page filter

---

batch/batch/utils.py
batch/test/test_utils.py
hail/python/hailtop/batch/docs/change_log.rst
hail/python/hailtop/batch/docs/index.rst
hail/python/hailtop/batch/job.py

Fixes #8793 
This is a breaking change as numeric values for storage and memory are in bytes rather than GiB.
CHANGELOG: Fixed the documentation for job memory and storage requests to have default units in bytes.

[batch] fix memory, storage requests

---

hail/python/hail/docs/change_log.md

The change log only supports (#NNNN) for PRs and issues, not a comma separated
list of #NNNNs inside parentheses. See: https://hail.is/docs/0.2/change_log.html#bug-fixes
for the issue currently. A sed rule in the makefile implements this syntax.

[hail][change_log] fix change log syntax

---

ci/ci/ci.py

I avoid printing the full exception into the body in most cases. Seems prudent to not expose too much about our internals.
CI already uses a broad except and prints the full message when building PRs so I adopted that for building the branch (`unwatched_branch.deploy`) in dev deploy.

[ci] teach CI to issue 400s on bad dev deploys

---

ci/ci/ci.py

There are `await`s between checking that `pr.batch` is not `None` and using
it. During the awaits someone else could remove the batch.

[batch] no 500s if batch changes mid-request

---

hail/src/main/scala/is/hail/expr/package.scala

Removed TypedAggregator

---

hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala
hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/main/scala/is/hail/types/TypeWithRequiredness.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Fixing the InferPType pass with requiredness to correctly handle nested non-canonical PTypes, as discussed.
I ended up merging the new pass and the old pass, since the new pass *should* now be able to handle aggregator nodes using the existing agg inference stuff.

[query][ptypes] fix InferPType to work with requiredness pass

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_ndarrays.py

CHANGELOG: Fixed issue where accessing an element of an ndarray in a call to Table.transmute would fail.
Because `_indices` was not being set, transmute would fail when it tried to see which row fields to delete.

[query] Fix NDArrayExpression._getitem_ to remember its source

---

hail/python/hail/ir/ir.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/Binds.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/NestingDepth.scala
hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

This replaces StreamLeftJoinDistinct, and supports a `joinType` flag like `TableJoin`. The plan is to lower `TableJoin` using this, by first doing a `StreamGroupByKey` on the right table to end up in the "right distinct" case, and then exploding after the join.
For now this only adds an implementation for the "outer" case to the existing "left".

[query] Add StreamJoinRightDistinct node

---

hail/src/main/scala/is/hail/expr/ir/TableIR.scala

If `tv.rvd.typ.key` is longer than `tv.typ.key`, then this would create a partitioner with `allowedOverlap` > the length of the partitioner key.

[query] bugfix in TableFilterIntervals.execute

---

hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/GenericTableValue.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

In several places constructing a stream from in iterator or buffer, the side effect of advancing the input was packaged with the value passed to the stream consumer. If that value was never used, the input wasn't advanced properly.
I fixed this pattern every place I could think of: the two `PartitionReader`s, and the `In` node allowing a java iterator to be passed as a stream argument to a compiled function.

[query] fix converting iterator/buffer to stream

---

hail/src/main/scala/is/hail/expr/ir/ComputeUsesAndDefs.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/test/scala/is/hail/expr/ir/RequirednessSuite.scala

Although we generally want unshared IRs for downstream passes, there are many instances where we construct IRs with shared nodes (common case: using the same Ref for the table row in TableMapRows expressions). 
Requiredness correctness should not be affected by node-sharing, and deduplicating every time we want to run the requiredness analysis is potentially very expensive since the goal is to be able to run it at arbitrary points in the lowering stack, so I'm going to allow Requiredness to handle shared nodes.
This could potentially mess up if there are instances where a ref is created and used to represent two separate values for whatever reason, but I think we should consider that to be a bug---e.g.
```
val r = Ref("foo", TInt32)
If(…, 
Let("foo", NA(TInt32), r + 3)
Let("foo", I32(5), …
```

[query][ptypes] allow requiredness to handle shared nodes

---

hail/python/hail/backend/local_backend.py
hail/python/hail/backend/py4j_backend.py
hail/python/hail/context.py
hail/python/hail/fs/local_fs.py
hail/python/hail/utils/java.py
hail/python/test/hail/helpers.py
hail/src/main/scala/is/hail/backend/local/LocalBackend.scala

Bascially grabbed the relevant bits from SparkBackend and ServiceBackend.  Enabled by setting HAIL_QUERY_BACKEND=local.  Needs HAIL_HOME and SPARK_HOME set to find jars, and hardcodes the py4j jar version that comes with Spark 2.4.x.  Will have to work on ripping out Spark dependency. Currently uses HadoopFS for the file system in Java.  GoogleFS in Python works with gs:// or local files, I just copied it and ripped out the Google stuff.  Some some rough ideas from some of your old work, @johnc1231 (py4jbackend).  Current results on the Python tests:
> == 470 failed, 245 passed, 87 skipped, 15 warnings, 1 error in 270.61 seconds ==

[query] Local backend

---

hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

Added a `Consume` IR that just emits its body and then returns a 1. I think I did the `IEmitCode` bit right such that it should emit all of the inner code, then ignore it and return 1, but I'd appreciate a second set of eyes. The lowering rule is trivial given that `Consume` exists. 
In the future, may be better to delete `ForceCountTable` entirely, and just use `Consume` from Python. 
cc @tpoterba

Lower Force Count

---

hail/python/hail/ir/__init__.py
hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/functions/MatrixWriteBlockMatrix.scala
hail/src/main/scala/is/hail/linalg/BlockMatrix.scala
hail/src/main/scala/is/hail/linalg/GridPartitioner.scala
hail/src/main/scala/is/hail/types/BlockMatrixType.scala
hail/src/main/scala/is/hail/utils/richUtils/RichDenseMatrixDouble.scala
hail/src/test/scala/is/hail/linalg/BlockMatrixSuite.scala

CHANGELOG: Fix a major correctness bug ocurring when calling  `BlockMatrix.transpose` on sparse BlockMatrices. Symmetric matrices are not affected.
It seems like `BlockMatrix.transpose` has been broken for a while when the matrix is sparse. 
I added `PerBlockMatrixSparsifier` as a way to sparsify particular blocks of a `BlockMatrix` from python. This is just so we can write tests / diagnose user errors based on sparsity patterns. I also wrote a helper function to sparsify numpy matrices for testing purposes. 
The crucial fix here is to `GridPartitioner.transpose`. That function is supposed to return a pair of the form `(GridPartitioner, Int => Int)`, where the first of the pair is the new `GridPartitioner` for the transposed thing, and the second of the pair is a function that takes in a …

BlockMatrix Transpose Sparsity Fix

---

hail/python/test/hailtop/batch/test_batch.py

Only one of the files existed. I'm guessing the deletion policy isn't strict and one file didn't get deleted.

[batch] Fix missing files in test_hailtop_batch

---

hail/src/main/scala/is/hail/expr/ir/agg/AppendOnlyBTree.scala
hail/src/main/scala/is/hail/expr/ir/agg/CollectAsSetAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/GroupedAggregator.scala

Allocate a fixed stack, as it was the simplest thing I could do.  128 stack
slots should be more than enough for this implementation as it requires one
stack slot per level of the tree.
There are many improvements that can be made here, but hopefully this should
unblock some amount of the method splitting work.

[query] Replace recursive BTree foreach with iterative version

---

hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Allow the inner stream in a `StreamGrouped` or `StreamGroupByKey` to be unused, by recognizing when the `apply` method on the inner stream is never called, and calling it ourselves with a dummy consumer which just asserts the contained code paths are unreachable.

[query] fix unconsumed inner streams

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
hail/src/main/scala/is/hail/expr/ir/functions/ReferenceGenomeFunctions.scala
hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/test/scala/is/hail/expr/ir/FunctionSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/RandomFunctionsSuite.scala

Use `emitI` to emit `ApplySeeded` nodes and port the seeded function implementations to rely on IEmitCode instead of EmitCode
The changes in IRSuite are arguably to a test that's no longer relevant---it was a regression test for a bug where we were occasionally double-emitting some part of the EmitTriplet in some cases.
On the other hand, it feels kind of useful to keep as an illustration of how to thread IEmitCode through the function registry in a way that allows us to have weird interactions between the setup code of various IEmitCode args and the function itself. It was certainly instructive for me to work through how to translate the test functions in a way that made sense.
I've removed one of the functions since we no longer have a single notion for "this code should be run after …

[query] run seeded functions through IEmitCode

---

hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/FoldConstants.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

I'd like to introduce a function to generate UUIDs in our code. The use case I have in mind is currently to append unique identifiers to partition file names for write to mimic our current behavior, but the ability to generate uuids in our IR seems pretty nice, in general.
I added it as an IR node, but there's several problems arising from the fact that UUID is non-deterministic, and we can't effectively seed it. 
The fact that UUID4 is non-idempotent is actually the feature I'm looking for here---running the exact same IR twice should get me two different results, because if my WritePartition fails with a certain UUID I want to retry the execution, generating a new UUID. 
We can put a "seed" in the node to effectively treat each UUID4() node as non-equal to avoid any theoretical CSEing …

[query] add UUID4 IR node

---

batch/batch/front_end/front_end.py
batch/test/test_batch.py

If a batch contains a job who lists the same parent twice, Batch will encounter
[integrity errors from
MySQL](https://hail.zulipchat.com/#narrow/stream/127527-team/topic/ci.20broken/near/195236580). For
example, this error was raised when I duplicated a parent in build.yaml:
pymysql.err.IntegrityError: (1062, "Duplicate entry '35921-13-1' for key 'PRIMARY'")"}
This change catches the integrity error and raises a more useful 400 bad request
error message.

[batch] Issue a 400 for batches with jobs with duplicated parents

---

hail/python/hailtop/batch/backend.py

CHANGELOG: Add support for a user-specified, at-most-once HTTP POST callback when a Batch completes.

[batch/client] add a callback parameter to ServiceBackend._run

---

hail/python/hail/context.py
hail/python/hail/docs/getting_started_developing.rst

A couple of small fixes for docs:
* Correct spelling of "requirements" in getting started developing
* Fix reST syntax for type of `local_tmpdir` parameter to `hl.init`

Documentation fixups

---

hail/python/hail/methods/impex.py
hail/python/test/hail/methods/test_impex.py

When you have a sites only dataset (like gnomad), you shouldn't have to convert to a `MatrixTable` just to make a VCF. This fixes that problem by internally converting tables to MatrixTables for export.

[query] Extend `hl.export_vcf` to work on Table

---

hail/src/main/scala/is/hail/annotations/ExtendedOrdering.scala
hail/src/main/scala/is/hail/rvd/PartitionBoundOrdering.scala
hail/src/main/scala/is/hail/types/virtual/TArray.scala
hail/src/main/scala/is/hail/types/virtual/TBaseStruct.scala
hail/src/main/scala/is/hail/types/virtual/TBinary.scala
hail/src/main/scala/is/hail/types/virtual/TBoolean.scala
hail/src/main/scala/is/hail/types/virtual/TCall.scala
hail/src/main/scala/is/hail/types/virtual/TDict.scala
hail/src/main/scala/is/hail/types/virtual/TFloat32.scala
hail/src/main/scala/is/hail/types/virtual/TFloat64.scala
hail/src/main/scala/is/hail/types/virtual/TInt32.scala
hail/src/main/scala/is/hail/types/virtual/TInt64.scala
hail/src/main/scala/is/hail/types/virtual/TInterval.scala
hail/src/main/scala/is/hail/types/virtual/TLocus.scala
hail/src/main/scala/is/hail/types/virtual/TNDArray.scala
hail/src/main/scala/is/hail/types/virtual/TSet.scala
hail/src/main/scala/is/hail/types/virtual/TStream.scala
hail/src/main/scala/is/hail/types/virtual/TString.scala
hail/src/main/scala/is/hail/types/virtual/TStruct.scala
hail/src/main/scala/is/hail/types/virtual/TTuple.scala
hail/src/main/scala/is/hail/types/virtual/TUnion.scala
hail/src/main/scala/is/hail/types/virtual/TVariable.scala
hail/src/main/scala/is/hail/types/virtual/TVoid.scala
hail/src/main/scala/is/hail/types/virtual/Type.scala
hail/src/main/scala/is/hail/utils/Interval.scala
hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala

This is needed to implement stream joins and groupByKey in Interpret.

[query] CodeOrdering support for missing-nonequal comparisons

---

hail/python/hailtop/hailctl/dataproc/connect.py

`spark-ui1` and `spark-ui2` were removed some time ago (#6760), but they are still listed as options in the usage/help text.

Remove unused service options for hailctl dataproc connect

---

hail/python/hailtop/hailctl/dataproc/modify.py

`hailctl dataproc modify`'s `--update-hail-version` and `--wheel` arguments cannot be used together. Using argparse's [mutually exclusive group](https://docs.python.org/3/library/argparse.html#mutual-exclusion) to enforce that makes the usage/help text clearer.
```
usage: hailctl dataproc modify [-h] [--num-workers NUM_WORKERS]
[--num-preemptible-workers NUM_PREEMPTIBLE_WORKERS]
[--graceful-decommission-timeout GRACEFUL_DECOMMISSION_TIMEOUT]
[--max-idle MAX_IDLE] [--dry-run] [--zone ZONE]
[--update-hail-version | --wheel WHEEL]
name
```

Clarify usage of hailctl dataproc modify

---

hail/python/hail/docs/_templates/layout.html
site/site.sh

1. When dev deploying or PR deploying, the root URL is not the usual one. We fix `layout.html` to produce the correct url when prefixed.
2. The NGINX rule which fixes paths in dev deploys or PR deploys incorrectly assumed only double quotes were permissible around HTML attributes. Single quotoes are also permissible.
The layout changes will not take effect until we next deploy the Hail docs. Until then, dev deploy's will not have a nav bar on the docs.

[site] fixes for dev deploys

---

hail/src/main/scala/is/hail/annotations/CodeOrdering.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/types/physical/PBaseStruct.scala
hail/src/main/scala/is/hail/types/physical/PStruct.scala
hail/src/main/scala/is/hail/types/physical/PTuple.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

[query] Fix handling of missing keys in stream joins and GroupByKey

---

hail/src/main/scala/is/hail/types/encoded/EBlockMatrixNDArray.scala
hail/src/main/scala/is/hail/types/encoded/ENDArray.scala
hail/src/main/scala/is/hail/types/encoded/EType.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala
hail/src/test/scala/is/hail/expr/ir/ETypeSuite.scala

This PR introduces and tests a new `EType`, `ENDArray`. It is not used anywhere yet except for tests, as there are some issues with `fundamentalType` and backcompatibility to be worked out, but in the interest of smaller PRs I figured I'd get the type implementation in first and do a follow up where we start using it.

Add ENDArray

---

hail/src/main/scala/is/hail/io/RichContextRDDRegionValue.scala
hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala
hail/src/main/scala/is/hail/rvd/RVD.scala

the lowered TableWrite should be able to represent the pre-write RVDSpec in a concise way.

[query] refactor MakeRVDSpec to have intermediate with no partFiles

---

hail/src/main/scala/is/hail/expr/ir/Binds.scala

We don't broadcast the env when generating code, so the body of a CDA can see exactly two bindings: its context and broadcast values.

[query] CDA body shouldn't see bindings in env

---

hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/TableValue.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala
hail/src/main/scala/is/hail/types/physical/PType.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Defines (but doesn't implement) WritePartition and WriteMetadata nodes as well as stub classes for the writers needed for native TableWrite lowering.
WriteMetadata uses IEmitCode; WritePartition is implemented with EmitCode because it consumes a stream.

[query] WritePartition and WriteMetadata IR node definitions

---

hail/python/hail/methods/qc.py
hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh37.sh
hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh38.sh
hail/python/hailtop/hailctl/dataproc/start.py

VEP will now automatically look for a config file in environment variable `VEP_CONFIG_URI` if one isn't specified. This environment variable is prepopulated on dataproc clusters started with `hailctl dataproc`

[query] Make VEP on Dataproc not require a config

---

hail/python/hail/matrixtable.py
hail/python/hail/table.py

Not sure why the extra line is required here... riddles of Sphinx.
https://hail.is/docs/0.2/hail.Table.html#hail.Table.checkpoint
https://hail.is/docs/0.2/hail.MatrixTable.html#hail.MatrixTable.checkpoint
Before
After

Fix warning in Table/MatrixTable checkpoint docs

---

ukbb-rg/Dockerfile.browser

I do not know where `static` came from. The shiny docs indicate that static files
should be placed inside a `www` directory which is a sibling to the `app.R` file.
Already deployed.

[ukbb-rg] fix rainbowvis.js

---

hail/python/hailtop/hailctl/dataproc/describe.py

With this table
```
ds = hl.utils.range_table(10)
ds = ds.annotate(t=hl.tuple([1, "Foo", True]))
ds.write("test.ht")
```
`hailctl dataproc describe test.ht` currently outputs the following for "Row fields":
```
----------------------------------------
Row fields:
'idx': int32
't': tuple<>
----------------------------------------
```
With this change, it outputs:
```
----------------------------------------
Row fields:
'idx': int32
't': tuple<int32, str, bool>
----------------------------------------
```

Support tuples in hailctl dataproc describe

---

build.yaml
hail/python/hail/backend/service_backend.py
hail/python/hail/context.py
hail/python/hailtop/batch/backend.py
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
query/deployment.yaml
query/query/query.py

The problem was query was writing the job configuration to the query bucket, but workers only get the user gsa, so they were unable to read the configuration.  This worked in the tests because the query and user account are both the test service account.
I can remove the query-gsa-key and the hail-query bucket after this goes in.

[query] store job configuration in user bucket

---

hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/io/plink/LoadPlink.scala

CHANGELOG: Fixed `hl.import_plink` with multiple data partitions.

[query] Fix `import_plink` with n_partitions > 1

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/main/scala/is/hail/io/index/IndexWriter.scala
hail/src/main/scala/is/hail/io/index/LeafNodeBuilder.scala
hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala
hail/src/main/scala/is/hail/types/encoded/EType.scala
hail/src/main/scala/is/hail/types/physical/PType.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

This implementation lowers TableWrite with a TableNativeReader.
Punting on the `stageLocally` path for now (it'll throw a lowering error) since our current implementation adds a task listener to the spark task to clean up files, and I'm not sure how we want to handle that in the general case.

[query][lowering] lower TableWrite with native reader

---

site/site.sh
site/www/index.xslt

Not sure why crossorigin is necessary to make authenticated imports work, but it works. No information at MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script.
https://internal.hail.is/dking/site/ demonstrates this working.

[site] when dev deploying also update js module imports

---

hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerDistributedSort.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala

~Stacked on #8874, not by necessity, but because the following PR lowering TableJoin depends on both this and that.~
* Before, `TableStage` defined it's per-partition behavior in an abstract method `def partition(ctxRef: Ref): IR`. This makes defining a new `TableStage` a bit heavy syntactically, and means we can't inspect the type of the partition IR without apply the function to something.
This PR replaces the abstract method with two fields `ctxRefName: String` and `partitionIR: IR`. It defines a method `def partition(ctx: IR): IR` using these, which is more ergonomic to use because the context isn't forced to be a `Ref`.
* With the type of the partition result accessible, this PR requires that type to be a `TStream<TStruct>`. Without this requirement, there is no clear connection …

[query] Some refactoring of TableStage

---

hail/python/hail/docs/change_log.md
hail/python/hail/docs/tutorials/01-genome-wide-association-study.ipynb
hail/python/hail/docs/tutorials/06-joins.ipynb

Algolia crawls anchor tags, and treats query strings as distinct urls (since apriori there is no way to know that that doesn't represent a unique page, since query strings can be used for routing).
We don't use ?highlight consistently anyway, and it frankly doesn't add anything useful (it highlights what the page already scrolls to).

[docs] remove ?highlight

---

hail/python/hail/expr/functions.py

hail/python/hail/expr/functions.py defines functions `str`, `int`, etc. There are a few uses of `str` or `int` in functions.py that refer to `hail.expr.functions.str` and `hail.expr.functions.int` where they are intended to refer to `builtins.str` or `builtins.int`.
Empty collection constructors are currently documented as accepting either a Hail type object or a `hail.expr.functions.str` instead of a `builtins.str` for the type name.
https://hail.is/docs/0.2/functions/constructors.html#hail.expr.functions.empty_array
In the case of `shuffle`, the type check as well as the type annotation is incorrect. Currently, attempting to call `hl.shuffle` with a `seed` argument throws an exception `TypeError: int() missing 1 required positional argument: 'x'`.
---
There is also a more widespread but …

Fix type annotations and checks in functions.py

---

hail/src/main/scala/is/hail/io/plink/LoadPlink.scala

Can't really test this easily, unfortunately.
CHANGELOG: Fix integer overflow error when reading files >2G with `hl.import_plink`

[query] Fix import_plink overflow

---

internal-gateway/service.yaml

Currently, this is set inside GCP, but if anyone were to apply this service.yaml file,
it would reset the global access to `false`. This change ensures that the service.yaml
for internal-gateway reflects the actual desired state.
This annotation was added in GKE 1.16 which we now have.

[internal-gateway] add allow global access to the yaml

---

hail/src/main/scala/is/hail/expr/ir/TableWriter.scala

Working on the safe memory allocator that checks if we are accessing invalid memory, it's catching this 0 pointer. 
There are already tests that hit `TableWriter`, and this should result in no functionality change.

Don't use a 0 pointer in TableWriter

---

hail/python/test/hail/expr/test_ndarrays.py

This just removes a bunch of unnecessary `skip_unless_spark_backend`s.

Remove annotations limiting most ndarray tests to spark backend

---

hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/GenericLines.scala
hail/src/main/scala/is/hail/expr/ir/GenericTableValue.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/io/TextMatrixReader.scala
hail/src/main/scala/is/hail/rvd/RVDPartitioner.scala

Summary:
- remove debug statement (?)  in PartitionIteratorLongReader
- LowerTableIR needs to truncate the partitioner when truncating the keys.  Otherwise, the partitioner will refer to rows that can be modified elsewhere.
- Added a missing ToStream in TableExplode lowering
Unfortunately, the local backend tests are now segfaulting.  How's the debugging allocator fix coming @tpoterba @johnc1231?

[query] various minor fixes

---

batch/batch/driver/instance_pool.py
docker/requirements.txt

I'm seeing this in the driver logs:
```
ERROR 2020-06-16 23:37:18,446 in event loop Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/batch/driver/instance_pool.py", line 500, in event_loop
await self.handle_event(event)
File "/usr/local/lib/python3.7/dist-packages/batch/driver/instance_pool.py", line 430, in handle_event
timestamp = event.timestamp.timestamp() * 1000
AttributeError: 'dict' object has no attribute 'timestamp'
```
`event['timestamp']` is in RFC3339 Zulu format with nanosecond precision, for example: 2020-06-08T16:49:53.374657381Z, see: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry
There is no native RFC3339 Python parser.  RFC3339 is nearly identicaly to ISO 8601, except maybe some timezone differences which aren't …

[batch] fix another logging error

---

hail/src/main/scala/is/hail/asm4s/ClassBuilder.scala
hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/lir/Emit.scala
hail/src/main/scala/is/hail/lir/InitializeLocals.scala
hail/src/main/scala/is/hail/lir/Pretty.scala
hail/src/main/scala/is/hail/lir/SimplifyControl.scala
hail/src/main/scala/is/hail/lir/SplitMethod.scala
hail/src/main/scala/is/hail/lir/X.scala
hail/src/main/scala/is/hail/lir/package.scala

Due to bytecode verification rules, an allocated but uninitalized object cannot be stored into a field, so the NEW and INVOKESPECIAL constructor call bytecodes cannot be split across methods.  Therefore, I modified newInstance to fuse those operations together.
I broke out control simplification and made it a stronger.
Added method splitting.  Currently, method splitting splits out basic blocks into their own, straight-line methods and all the control flow remains in the original method.  All locals are spilled to fields which is terrible, but what we're doing now.  I expect two changes in the future: recover the structured control flow (there are standard algorithms for this) so we can split out control flow, and use the dataflow analysis from InitializeLocals to only spill locals split …

[lir] add code splitter, currently unused

---

site/www/search.xslt

Occurred because I moved the  #hits .aa-suggestion-title-separator:before to an inline style, and the xml parser converted the utf-8 character to ISO-8859-15.
current:
after:

[site] fix utf-8 encoding

---

site/www/style.css

Points shouldn't show through central section, too noisy, triggers trichophobia. This fixes a regression (previously there was enough padding to make the space between the title and panel to block point/line visibility), and improves on that previous state (by making the entire central section uniformly opaque, gives more visual consistency and will mean future padding changes don't break opaqueness). 
After:

[site] prevent background from encroaching all-hero-content on wide views

---

site/www/index.xslt

On views narrower than the height of the graph image + 100px, the slide box will overflow the adjacent install section.
Fixed using inline style to avoid css caching issues until the build process is fixed.

[site] don't overflow install section

---

README.md
site/www/references.md

A few links to references.md were broken when website files were moved in #8923.
This changes the "Hail-powered science" link in README.md to point to the references page on the website instead of the references.md file in GitHub and fixes the "editing this page directly" link on https://hail.is/references.html.

Fix links to references.md

---

hail/python/hail/docs/tutorials/07-matrixtable.ipynb
hail/src/main/scala/is/hail/annotations/ExtendedOrdering.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/rvd/KeyedRVD.scala
hail/src/main/scala/is/hail/types/TypeWithRequiredness.scala
hail/src/main/scala/is/hail/types/virtual/TStruct.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/expr/ir/RequirednessSuite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

~Stacked on #8917~
Adds `zipPartitions`, `extendKeyPreservesPartitioning`, `orderedJoin`, and `alignAndZipPartitions` methods to `TableStage`, trying to mirror the `RVD` implementation, especially concerning the partitioning logic.
Adds lowering case for `TableJoin`.

[query] Lower TableJoin

---

hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

From a conversation we had a while ago---
It turns out PhysicalAggSig *does* need to know nested aggOps, since they're used in constructing the correct resultOp for a nested aggregator, but we don't need to carry *all* the operations that are happening on a given agg state, only the AggOps that are going to be used in the CombOp/ResultOp. This lets us get rid of the weird `Seq[Seq[PhysicalAggSig]]` that was confusing by only tracking the "main" aggOp on a given state.
I'm still not entirely happy with how this looks, but I think that not carrying around an array of possible ops is much nicer.
Shouldn't cause conflicts with the aggregator lowering stuff, but I'm assigning you just in case.

[query][qggs] refactor PhysicalAggSig

---

hail/src/main/scala/is/hail/io/gen/ExportBGEN.scala

CHANGELOG: Fix memory leak in ExportBgen
If you look a dozen or so lines under the `boundary` I added, you'll see a :
```
it.foreach { ptr =>
val (b, d) = bpw.emitVariant(ptr)
out.write(b)
dropped += d
}
```
So that thing is stepping through the iterator without freeing. The `boundary` is to do a `clear` after each read from the `it`.

Fix Memory Leak in ExportBgen

---

hail/src/main/scala/is/hail/annotations/UnsafeRow.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/rvd/RVDPartitioner.scala

The new generic lines coerce code could produce a partitioner with unsafe values.  Those unsafe values ended up in the Compile cache, which become invalid when owning region was cleared.
This fixes the memory errors I was seeing when running with the local backend.  It is possible it will fix (some?) of the errors you were investigating, @johnc1231.

[query] Fix partitioner memory error

---

hail/src/main/scala/is/hail/lir/SimplifyControl.scala
hail/src/main/scala/is/hail/lir/SplitMethod.scala
hail/src/main/scala/is/hail/lir/X.scala
hail/src/main/scala/is/hail/lir/package.scala

I need this for upcoming improvements to SplitMethod.
Summary:
- add Block.replace
- have Block track uses
- makes SimplifyControl simpler
- Method.findBlocks prunes dead uses

[query/lir] add Block.replace

---

batch/sql/estimated-current.txt
batch/sql/fix-mark-job-complete-on-error.sql
build.yaml

Fixes the problem where if there is a bad secret / job config fails, we didn't update the attempt id in the jobs table in the database.

[batch] fix getting status when job config fails

---

hail/python/hailtop/batch/backend.py
hail/python/hailtop/batch/batch.py
hail/python/hailtop/batch/docs/tutorial.rst
hail/python/hailtop/batch/job.py
hail/python/hailtop/batch/resource.py
hail/python/test/hailtop/batch/test_batch.py

There might be additional PRs, but for now this PR does the following:
- Names folders for jobs based on the job_id computed after ordering the jobs
- Gets rid of double slashes in path names
- Names JobResourceFiles based on the name of the attribute.
Example: j.ofile => /batch/1/ofile
- Names resource groups from jobs as follows:
Example: j.declare_resource_group(ofile={'bed': '{root}.bed'})
/batch/1/ofile.bed
- Names input resource files based on the file name
/batch/inputs/{uid}/my_vcf.bgz
- Names input resource groups two-ways
input = batch.declare_resource_group(vcf=...)
/batch/inputs/{uid}/my_vcf.bgz
/batch/inputs/{uid}.vcf
I tested this locally and on the service to make sure it's doing what I want.

[batch] change how files are named in the user interface

---

hail/src/main/scala/is/hail/expr/ir/AggOp.scala
hail/src/main/scala/is/hail/expr/ir/Exists.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
hail/src/main/scala/is/hail/expr/ir/agg/TakeByAggregator.scala
hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

`LoweredTableReader.makeCoercer` was using the same aggregator to find both the min and max keys in a partition, hence creating degenerate partitioners. This manifested in incorrect results in joins. This PR fixes it by adding a `SortOrder` option to the `TakeBy` aggregator, and using a descending `TakeBy` to compute the max key.

[query] fix bug in LoweredTableReader

---

hail/python/test/hail/matrixtable/test_matrix_table.py
hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala

Fixes #8953
CHANGELOG: Fixed aggregation behavior of `MatrixTable.{group_rows_by, group_cols_by}` to skip filtered entries.

[query] Fix aggregation semantics in MT group_rows_by/group_cols_by

---

ci/ci/ci.py

A KeyError's __str__ is just the key that failed. This prints the traceback and the full
error message. It is far more useful.

[ci] better dev deploy messages

---

ci/ci/github.py

I do not understand how `set -e` works in bash functions, but I know what
currently exists does not retry properly. I have verified this works as intended.
It deletes *all* files in the current folder, then tries to clone into this folder.
If the clone fails, becasue it is the last command in the function, the function
will return the same exit code. The retry function will then retry `clone`. Because
`clone` removes all files in the directory before attempting a clone, it is idempotent.
Users of the checkout script all use it by creating an empty directory and cd'ing into it.

[ci] fix clone to actually retry

---

hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

if we're zipping two streams and neither of them is referenced in the zip body, the pruner removes both streams in the AssumeSameLength case.

[query][bugfix] don't prune all streams in zip if none of them are used

---

hail/python/hail/docs/index.rst

Currently, the link to Hail 0.1 docs at the bottom of https://hail.is/docs/0.2/index.html links to https://hail.is/docs/0.2/docs/0.1/index.html. This changes it to https://hail.is/docs/0.1/index.html.

Fix link to Hail 0.1 docs

---

hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala

The previous implementation, while seeming to be well-abstracted at
first, actually had a rather devious property of creating agg states
for multiple classes multiple times. I'm still working on figuring out
*exactly* the place where our assumptions broke down, but this change
definitely fixes the problem, and simplifies the implementation by
directly using IR, instead of other compiled functions.
This problem was a symptom of a larger issue, which is that the
ownership semantics of the current aggregator system is way too complex
to be coding against regularly. This all will go away when lowering is
complete, in favor of the *much* simpler set of IR nodes that are used
in lowering. We may need to address this problem sooner, though.
CHANGELOG: Fixed memory leak affecting `Table.annotate` …

[query] Fix memory leak in combOpFSerialized (and therefore densify)

---

hail/python/test/hail/expr/test_expr.py
hail/src/main/scala/is/hail/expr/ir/agg/LinearRegressionAggregator.scala

CHANGELOG: Fix crash when using `hl.agg.linreg` with no aggregated data.

[query] Fix bug in linreg aggregator when n == 0

---

hail/src/main/scala/is/hail/types/physical/PCanonicalInterval.scala

Struct's loadField has been changed to load the address directly in the
case of the field being a collection type. PCanonicalIntervalValue was
using loadStart and loadEnd rather than startOffset and endOffset which
caused addresses to be loaded twice in the case of intervals of
collections, leading to segfaults.
This code is currently unused, but will be used in EmitCodeOrdering #8725

[query] Fix PCanonicalIntervalValue loadStart and loadEnd

---

hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/CompileAndEvaluate.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPass.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPipeline.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
hail/src/test/scala/is/hail/expr/ir/LoweringPipelineSuite.scala

I need this for TableAggregate work, but think this is a good change regardless.

[query] Refactor LoweringPipeline so that optimization is a pass

---

hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Split out the TableNativeWriter metadata writers into three separate writers. I use this to make the MatrixWriter lowering cleaner.
(see #8967)

[query] split out metadata writers

---

hail/src/main/scala/is/hail/experimental/package.scala

CHANGELOG: fixes bug where ci parameter is not passed through experimental.filtering_allele_frequency
fixes #8945

[query] pass ci argument to faf, fixes #8945

---

hail/python/hail/backend/local_backend.py
hail/src/main/scala/is/hail/backend/local/LocalBackend.scala

LocalBackend uses LocalFS. LocalFS doesn't have a Java analog or a _jfs field.

[query] fix LocalBackend.load_references_from_dataset

---

hail/src/main/scala/is/hail/utils/package.scala

If an exception occurs in a finally cause, the original exception is completely
lost. For example:
```
Exception in thread "main" java.lang.RuntimeException: second
at Foo.main(Foo.java:6)
class Foo {
public static void main(String[] args) {
try {
throw new RuntimeException("first");
} finally {
throw new RuntimeException("second");
}
}
}
```
This seems so unwieldly as to be unreasonable, but this seems to be the correct
answer:
```
Exception in thread "main" java.lang.RuntimeException: Exception during closing!!!
at Foo.close(Foo.java:3)
at Foo.main(Foo.java:12)
Suppressed: java.lang.RuntimeException: first
at Foo.main(Foo.java:8)
Caused by: java.lang.RuntimeException: cause of exception during close
... 2 more
class Foo {
public static void close() {
throw new …
```

[hail] properly report suppressed exceptions in `using`

---

hail/src/main/scala/is/hail/types/physical/PTuple.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

Here's the minimal case for replicating #9016:
```
t = hl.array([hl.struct(a=hl.tuple([0, 1]))])
t2 = hl.Table.parallelize(t)
t2 = t2.annotate(b=t2.a[0], c=t2.a[1])
t2.drop('a', 'b').collect()
```
The issue was that the PTuple `fields` argument is carrying the wrong field index, which is what EType.defaultFromPType uses to construct the EType (since it operates on the fundamental type).

[query][bugfix] fix #9016 (wrong subset tuple field names on PTuple)

---

hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

This PR adds stream nodes `StreamMultiMerge` and `StreamZipJoin`, which will be used to implement `TableUnion` and `TableMultiWayZipJoin`. The two nodes were so similar, both in implementation and in interface, that I thought bundling them into one PR would actually make it *easier* to review, but I can split them up if you disagree.
The implementations of both nodes use tournament trees, a very simple data structure ideal for this problem. Think of it as a priority queue specialized to holding exactly `k` elements, so when you pop the top element, you must immediately replace it with a new value.
A tournament tree is just what it sounds like. It is a complete binary tree with `k` leaves. Conceptually, the leaves hold the current `k` elements (the heads of each of the `k` input streams), …

[query] add StreamMultiMerge and StreamZipJoin nodes

---

hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala

CHANGELOG: Fixed memory leak affecting `Table.aggregate`, `MatrixTable.annotate_cols` aggregations, and `hl.sample_qc`.

[query] Fix memory leak in combine operation

---

hail/src/main/scala/is/hail/asm4s/ClassBuilder.scala
hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/lir/Emit.scala
hail/src/main/scala/is/hail/lir/X.scala
hail/src/main/scala/is/hail/lir/package.scala

The interfaces are `newStaticField` and `newStaticMethod` on (Emit)ClassBuilder. The first
usage of this feature is to move the `FS` off of the class itself and onto a container class.

[query] Per Pipeline Static Filesystem

---

benchmark/python/benchmark_hail/run/linalg_benchmarks.py
hail/python/hail/__init__.py
hail/python/hail/conftest.py
hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/table/test_table.py

Pycharm thought `hl.nd` didn't exist, and I'm pretty sure we could
have had issues on certain python installations without this change.

[query] Expose _nd as nd

---

hail/python/hailtop/hailctl/dataproc/gcloud.py
hail/python/hailtop/hailctl/dataproc/start.py
hail/python/test/hailtop/hailctl/dataproc/conftest.py
hail/python/test/hailtop/hailctl/dataproc/test_start.py

This proposes a way to test `hailctl dataproc`, starting with `hailctl dataproc start`.
1. Move `subprocess` calls to run gcloud commands and get gcloud configuration to a separate `gcloud` module. This module serves as a convenient place to insert mocks in tests.
2. Automatically (with pytests's `autouse`) mock calls to the `gcloud` module's methods in tests. This prevents actually running `gcloud` in tests. This also provides a pytest fixture to set the mocked `gcloud` configuration values.
3. Add some tests for `hailctl dataproc start`. These tests pass arguments to `cli.main` and make assertions about the resulting `gcloud` command(s).

Add some tests for hailctl dataproc start

---

hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

TableIRSuite extensively uses the function
```
def collect(tir: TableIR): TableCollect = TableCollect(TableKeyBy(tir, FastIndexedSeq()))
```
to compare the result of a `TableIR` with the expected collection. But `TableCollect` makes no promises what order the results will be in, and in particular the optimizer is allowed to remove that `TableKeyBy`.
This PR redefines that function to use the collect aggregator, which does promise the order rows are collected.
It also fixes a small type error in the `TableJoin` lowering case that was uncovered.

[query] fix TableIRSuite

---

hail/python/hailtop/batch/backend.py

Run local commands using check_call instead of check_output so that command stdout goes to the terminal.

Run local commands using check_call instead of check_output

---

hail/python/hailtop/hailctl/dataproc/modify.py
hail/python/test/hailtop/hailctl/dataproc/conftest.py
hail/python/test/hailtop/hailctl/dataproc/test_modify.py

Follow on to #9066.
Still todo: tests for `--update-hail-version`. Those will require a mock for deploy metadata.

[hailctl dataproc] Add some tests for hailctl dataproc modify

---

hail/python/hail/experimental/dnd/array.py
hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/experimental/test_dnd_array.py

Implement an arbitrary inner product operation. This is the critical piece of
infrastructure that underlies all relatedness inference algorithms. The typical
inner product on real number matrices is defined as:
```
L_ij : matrix of shape a by b
M_kl : matrix of shape b by c
N_il : matrix of shape a by c, the inner product of L and M.
N_il = Sum_k (L_ik * M_kl)
```
This PR allows the user to define what `*` means and what `Sum` means. For
example, the KING paper defines an estimator for relatedness of homogeneous
populations called KING-homo. KING-homo's numerator is given by
`score_difference` below.
```python3
mt = hl.balding_nichols_model(2, 5, 5)
mt = mt.select_entries(genotype_score=hl.float(mt.GT.n_alt_alleles()))
da = hl.experimental.dnd.array(mt, 'genotype_score', block_size=3) …
```

[dnd] add DNDArray.inner_product

---

hail/python/hail/docs/install/macosx.rst

For reasons completely unclear to me, on Mac OS X, you have to install a JDK to
get the `java` command line tool. https://stackoverflow.com/questions/34074039/java-command-line-requires-jdk-on-mac

[hail] fix installation instructions

---

hail/python/hailtop/hailctl/dataproc/start.py
hail/python/test/hailtop/hailctl/dataproc/test_start.py

Currently, project and zone arguments to `hailctl dataproc start` are not included in the `gcloud compute instances add-tags` command used to add tags to the master node. Thus, adding tags may fail if the cluster is created in a non-default project/zone or if a default project/zone is not set.

[hailctl dataproc] Respect project and zone args when adding tags to cluster

---

hail/python/hail/ir/__init__.py
hail/python/hail/ir/ir.py
hail/python/hail/nd/__init__.py
hail/python/hail/nd/nd.py
hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/linalg/LAPACK.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

to flesh out our linear algebra, and in service of regenie. eventually, this, qr, and other linalg functions should be moved to hl.linalg I think, to match scipy, numpy, dask, etc
we should also decide whether to break out LU factorization. Numpy, scipy, dask do this, so that's my preference for a followup pr, because people who are looking for a fleshed out linalg experience may want this.
also, we should have less than double precision support, but this matches QR.

[query] ndarray inverse using LAPACK

---

hail/src/main/scala/is/hail/backend/Backend.scala
hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/expr/ir/LiftRelationalValues.scala
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerDistributedSort.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerToCDA.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPass.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPipeline.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/lowering/BlockMatrixStageSuite.scala

* Add new LiftRelationalValues pass, run before LowerToCDA.
* RelationalLets are converted to Lets during lowering, and broadcast.
* RelationalRefs are converted to normal Refs.
Stacked on #9041

[query] Solve recursive LowerToCDA issue

---

hail/python/dev-requirements.txt

Based on [discussion](https://github.com/hail-is/hail/pull/9092#discussion_r456509655) in #9092.
Pylint and Flake8 are necessary to run `check-hail` and `check` tasks in [hail/python/Makefile](https://github.com/hail-is/hail/blob/88aa36ce94ffd3501602784887fd40ece917834a/hail/python/Makefile#L4-L14). However, they are not currently included in [hail/python/dev-requirements.txt](https://github.com/hail-is/hail/blob/88aa36ce94ffd3501602784887fd40ece917834a/hail/python/dev-requirements.txt).

List Pylint and Flake8 in dev requirements

---

hail/python/hail/nd/__init__.py
hail/python/hail/nd/nd.py
hail/python/test/hail/linalg/test_linalg.py

Identity matrix, needed for ridge regression in Hail. This is obviously suboptimal, it should be a special instance of a sparse ndarray that specifies 'k', but this matches the Numpy implementation and represents a good start.

[hail] NDArray eye

---

build.yaml

This needs to be done at least once. The root SSL/TLS key is used to sign all
other keys used in the namespace. We do not recreate it when we deploy into
default or into dev namesapces.

[ci] make create_ssl_config_root idempotent and use it in dev deploy

---

hail/python/hail/experimental/__init__.py
hail/python/hail/experimental/write_multiple.py
hail/python/hail/ir/__init__.py
hail/python/hail/ir/blockmatrix_writer.py
hail/python/hail/ir/ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/linalg/BlockMatrix.scala
hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/main/scala/is/hail/utils/package.scala
hail/src/main/scala/is/hail/utils/richUtils/RichContextRDD.scala

This PR introduces `tree_matmul`, a method on `BlockMatrix` that allows for greater parallelism when multiplying two large matrices that result in a small matrix (i.e. the inner dimension is much larger than the outer dimensions). 
In order to do this, this PR takes a `split_on_inner` parameter. This parameter defines how many subdivisions to break the two matrices into. Corresponding subdivisions are multiplied, written to disk, then read back in and summed. 
For example, if you are multiplying a 4k by 500k matrix by its transpose, your answer will be a 4k by 4k block. With normal matrix multiply, you'd get no parallelism at all, since the result is only a single partition. If you instead use `tree_matmul` with `split_on_inner = 5`, hail will do the following:
1. Break up 4k by 500k …

[query] Add tree_matmul, matrix multiply in case of large inner dimension 

---

batch/batch/front_end/validate.py
batch/batch/worker.py
batch/test/test_batch.py
hail/python/hailtop/batch/backend.py
hail/python/hailtop/batch/batch.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py
hail/python/test/hailtop/batch/test_batch.py

I debated whether to have this option on a batch which would require a database migration to add a new field to the batches table or just have it in the job spec for all jobs (same for all jobs). What I did is the easiest thing. It assumes all requester pay accesses are billed to the same project.

[batch] Add requester pays option

---

auth/auth/driver/driver.py
ci/create_database.py
hail/python/hailtop/auth/__init__.py
hail/python/hailtop/auth/sql_config.py

The auth driver currently uses the old secret format. The new secret format
includes SSL information. This change defines the secret format once in hailtop
and uses it everywhere. I also simplified the auth secret format: everyone uses
SSL/TLS to talk to databases now, so assume all necessary files are present.

[hail] Unify sql-config secret creation

---

hail/src/main/scala/is/hail/annotations/Memory.java
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala

In response to @cseed's comments here: https://github.com/hail-is/hail/pull/8970
Assigning Arcturus since they reviewed 8970.

Revert 8970 and Prevent Unsafe.copyMemory from being called with length 0

---

auth/auth/auth.py
batch/batch/batch.py
batch/batch/driver/main.py
batch/batch/front_end/front_end.py
batch/batch/worker.py
batch/test/failure_injecting_client_session.py
ci/ci/ci.py
ci/test/test_ci.py
gear/gear/auth.py
hail/python/hailtop/auth/auth.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/hailctl/auth/login.py
hail/python/hailtop/hailctl/auth/logout.py
hail/python/hailtop/hailctl/dev/deploy/cli.py
hail/python/hailtop/tls.py
notebook/notebook/notebook.py
notebook/scale-test.py
query/query/query.py
router-resolver/router_resolver/router_resolver.py
scorecard/scorecard/scorecard.py

The fix for Notebook is on line 242. Copying from my Zulip post:
> I made a mistake when I implemented TLS.
>
> In the following code snippet we use ssl_client_session which should probably be
> called in_cluster_ssl_client_session. It's supposed to be used to communicate
> with other services in the cluster. That needs to be changed back to
> aiohttp.ClientSession which loads the normal system certificates (including the
> VeriSign root certs that signed the public certs that gateway uses, different
> from the internal certs that our services use).
>
> In particular, note that the error says "unable to get local issuer
> certificate." That means that the local trust store lacks a certificate that
> trusts the remote server's certificate. In Dania's case, the default python on
> OS X …

[notebook] fix notebook, improve tls naming, add typing to tls.py

---

hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/BlockMatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala
hail/src/main/scala/is/hail/expr/ir/agg/CallStatsAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/StagedArrayBuilder.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala
hail/src/main/scala/is/hail/io/CodecSpec.scala
hail/src/main/scala/is/hail/io/TypedCodecSpec.scala
hail/src/main/scala/is/hail/types/BlockMatrixType.scala
hail/src/main/scala/is/hail/types/encoded/EBlockMatrixNDArray.scala
hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/lowering/BlockMatrixStageSuite.scala

Also, tidies up some of the emit encoder/decoder function signatures.

[query] lower native BlockMatrixRead/BlockMatrixWrite

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_ndarrays.py

This PR supersedes #9146, sets ndarray slicing behavior to follow ndarray/python semantics when out of bounds: upper_bound = len_dim if step > 0 else len_dim - 1, lower_bound = 0 if step > 0 else -1 (since our -1 has the effect of a slice bound that is None)
The other PR doesn't clamp dimensions properly (min and max out of bounds for start and stop are identical), and missed a 2nd issue, which is that python changes clamping behavior when step is negative. I bet this polymorphism is the reason we don't allow non-1 steps for ArrayExpressions.
- @johnc1231 could you still follow up on the byte code generation issue?
I've verified this works in the boundary cases.

[query] ndarray slice bounds fixed

---

hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
hail/src/main/scala/is/hail/variant/ReferenceGenome.scala

make LocalBroadcastValue serializable.
make writeReference public.
Gets the local tests to 419 passing:
> ====== 344 failed, 419 passed, 75 skipped, 16 warnings in 362.06 seconds =======

Two LocalBackend fixes

---

hail/python/hail/ir/ir.py
hail/python/hail/nd/nd.py
hail/python/test/hail/expr/test_ndarrays.py

CHANGELOG: Fix bug that prevented concatenating ndarrays that are fields of a table
Two bugs:
1. We can't call `.typ` on `concat_ir`, since that kicks off the type inference process before this IR gets wrapped in a `TableIR` that provides the necessary context to infer the type.
2. We need to `_compute_type` on `self.nds` as a whole, not just each of its `args`.

CHANGELOG: Fix bug that prevented concatenating ndarrays that are fields of a table

---

batch/Dockerfile.worker
docker/Dockerfile.base

Old versions of pip could only download some packages in source form which
requires compiling them. New version of pip can download these packages in
binary form which requires no compilation. This *substantially* improves docker
build times when you have to run `pip` in any layer.

[docker] make pip fast

---

batch/test/test_batch.py

The test deployment sets the default storage to 1GiB instead of the normal 10GiB. As a result, the PR tests passed. The deployment tests fail because the 10GiB default storage request forces a minimum core count of 0.5 CPU. This change explicitly requests less storage, thus preventing the rounding up of core count from 0.25 CPU to 0.5 CPU. The rounding up doubled the mcpu_msec time for the test, thus failing the test.
Fixes this:
```
-------------------------------- live log call ---------------------------------
2020-07-28T15:42:34 INFO batch_client.aioclient aioclient.py:497:submit created batch 70818
2020-07-28T15:42:34 INFO batch_client.aioclient aioclient.py:533:submit closed batch 70818
FAILED
_____________________________ Test.test_msec_mcpu ______________________________
self = …
```

[batch] fix resource requests in test

---

hail/python/hail/nd/nd.py
hail/python/test/hail/expr/test_ndarrays.py

CHANGELOG: make hl.nd.concatenate, hl.nd.vstack, and hl.nd.hstack accept ArrayExpression of NDArrayExpression, in addition to Python collections of NDArrayExpression

[query] make concatenate operations work with array expressions

---

batch/test/test_batch.py

Same issue where I didn't specify the storage to be 1Gi, so it got more memory than intended. I changed all the explicit resource requests to be 1Gi.
```
2020-07-28T18:18:12 INFO batch_client.aioclient aioclient.py:497:submit created batch 71161
2020-07-28T18:18:12 INFO batch_client.aioclient aioclient.py:533:submit closed batch 71161
FAILED
___________________________ Test.test_out_of_memory ____________________________
self = <test.test_batch.Test testMethod=test_out_of_memory>
def test_out_of_memory(self):
builder = self.client.create_batch()
resources = {'cpu': '0.1', 'memory': '10M'}
j = builder.create_job('python:3.6-slim-stretch',
['python', '-c', 'x = "a" * 1000**3'],
resources=resources)
builder.submit()
status = j.wait()
>       assert j._get_out_of_memory(status, 'main')
E …
```

[batch] Add storage resource to the tests

---

gear/gear/auth.py

Numerous times, I have sent REST credentials to a web endpoint. It is supremely annoying
to run around in circles wondering how your credentials got out of date. I think
this message is safe because the user really is a credentialed user, they just
used the wrong endpoint.

[auth] give a reason when wrong auth is used

---

hail/python/hailtop/auth/tokens.py

This just removes one level of second-guessing when debugging things.

[hailtop][auth] log file when successfully loading tokens

---

hail/python/cluster-tests/cluster_tree_aggregate.py
hail/src/main/scala/is/hail/expr/ir/Interpret.scala

Fixes #8944
CHANGELOG: Fixed crash (error 134 or SIGSEGV) in `MatrixTable.annotate_cols`, `hl.sample_qc`, and more.

[query] Fix invalid memory reference in Table.aggregate

---

hail/python/requirements.txt

CHANGELOG: fix missing google-cloud-storage python dependency, required by batch.
This makes the tutorial work: https://hail.is/docs/batch/getting_started.html
Version chosen based on our dataproc dependency declaration in init_notebook.py. Note that 1.25.* will install a new version of google-auth. On that note, it is possible that we can upgrade /auth to use a newer google-auth (@danking), as the issue listed in the /auth docker file (https://github.com/googleapis/google-auth-library-python/issues/443) is obviated by the 1.11.2 release: https://github.com/googleapis/google-auth-library-python/pull/446.

[batch] add google-cloud-storage dep

---

auth/Dockerfile

CHANGELOG: auth: upgrade google-auth-oauthlib to 0.4.1 an google-auth to 1.20.0
Note that google-auth-oauthlib 0.4.1 fixes to bug 0.4.0 introduced that prevented us from using that version: https://github.com/googleapis/google-auth-library-python-oauthlib/pull/48/files
1.20.0 is the (latest <2.0-dev) version installed with google-cloud-storage, use by hailctl dataproc, and now hail batch.

[auth] upgrade deps

---

hail/python/hailtop/batch/backend.py

Without this abstract* decorators have no effect, class isn't abstract.

[batch] fix Backend missing ABC

---

ci/deployment.yaml
dev-docs/development_process.md
hail/python/hail/context.py
hail/python/hail/docs/change_log.md
hail/python/hail/docs/cloud/general_advice.rst
hail/python/hail/docs/getting_started_developing.rst
hail/python/hail/linalg/blockmatrix.py
hail/python/hail/stats/linear_mixed_model.py
hail/python/hailtop/hailctl/dataproc/connect.py
hail/python/hailtop/hailctl/dataproc/start.py
hail/scripts/deploy.sh
site/www/references.md

I mixed the required changes with some cosmetic changes to, e.g. docs and comments.
I also added a missing </div> in references.md.
AFAICT, there's no way to change the default branch yet, so I didn't change the PR test CI's test repo's branch yet.
This change will change the references page on the site as soon as its merged, so we should be prepared to switch over when we merge it.

Rename the master branch to main

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/test/hail/matrixtable/test_matrix_table.py

Whitespace-only bugfix. Yay Python!
Fixes #9163

[query] Fix expression source mismatch exceptions

---

hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPass.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPipeline.scala
hail/src/test/scala/is/hail/expr/ir/RandomFunctionsSuite.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
hail/src/test/scala/is/hail/expr/ir/TestUtils.scala

* Fix error in TableKeyByAndAggregate caused by field name clobbering
* Fix error in TableLeftJoinRightDistinct with non-strict left tables
* Fix erroneous key preservation in TableStage.mapPartition
* Add Consume to TypeCheck
* Fix error where globals were not exposed in TableAggregate
* Fix error where globals were not exposed in TableAggregate
New local backend success rate:
```
271 failed, 496 passed, 75 skipped, 15 warnings in 368.17 seconds
```

[query] Fix errors in LowerToCDA.

---

hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala
hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala

This basically implements the collect-and-broadcast strategy that we use for the current BlockMatrix.execute. I think it might be good to eventually be able to lift scalar broadcasts out as a relational let in a simplify pass instead of in the lowering, but in the meantime I've implemented it in the lowerer also.

[query] lower BlockMatrixBroadcast

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/types/physical/PCode.scala
hail/src/main/scala/is/hail/types/physical/PType.scala
hail/src/main/scala/is/hail/types/physical/PUnrealizable.scala
hail/src/main/scala/is/hail/types/physical/PVoid.scala

This is the first in a series of changes that will push PCode through more of
the PType construction interfaces. The intent is to reduce code duplication,
and have as few interfaces as possible where `Code[_]` or `Code[Long]`
represents a hail type.

[query] Remove PType.copyFromPValue, replace with PCode.castTo

---

hail/python/hailtop/config/deploy_config.py
hail/python/hailtop/utils/utils.py

This PR changes the `addresses` function on `DeployConfig` to retry all transient errors. In particular, if the address service is temporarily down (maybe its getting redeployed), this change allows the client to repeatedly retry until the address service comes back to life.
I also added some type annotations to `retry_transient_errors`. It takes a function that returns something we can `await` and then applies that function in a loop until it does not raise an error.

[address] retry address

---

hail/python/hail/experimental/vcf_combiner/__main__.py
hail/python/hail/experimental/vcf_combiner/vcf_combiner.py
hail/python/test/hail/experimental/test_vcf_combiner.py

[query/combiner] Add options to better partition imported GVCFs
Teach the VCF combiner three new options:
* --genomes/-G to indicate that it is operating on genomes
* --exomes/-E to indicate that it is operating on exomes
* --import-interval-size to more finely control the partitioning of
the reference genome on GVCF import.
These are specified as a required mutually exclusive group, exactly one
of them must be present.
This goes along with removing `default_exome_intervals` and adding
`calculate_even_genome_partitioning`. The new function takes a reference
genome and a target interval size and computes a partitioning of the
reference into intervals of length at most the target size. It does so
by looping over the 'regular' contigs of the reference (as such it only
supports GRCh37 and …

[query/combiner] Add options to better partition imported GVCFs

---

hail/Makefile

A commit from a few months ago removed the ability to specify a single file for testing.

[query] Makefile: allow folder to be overriden

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_ndarrays.py

CHANGELOG: Fixed issue where ndarrays being sliced and indexed into in one expression didn't have sufficient bounds checks
Fixes #9144 by checking if indices provided in a slicing expression that mixes slices and single indices are out of bounds. 
Alex, please tell me if you're able to get anymore errors from #9144 with this change. I wasn't able to, but that issue was not super well defined at first so it's unclear to me if this covers all of your problems. I retitled the issue to reflect my understanding of the problems. 
More detail:
In numpy, it is ok for the upper bound of a slice to go past the end of an array, but it is not ok for an indexing operation to do the same. For example:
```
n = np.array([[1,2,3,4], [1,2,3,4]])
n[0:1000, 0:1000]
```
is allowed, the bounds just get …

[query] NDArray Slice with Indices Needs Bounds Checks

---

hail/python/hailtop/batch/docs/cookbook/clumping.rst
hail/python/hailtop/batch/docs/docker_resources.rst
hail/python/hailtop/batch/docs/service.rst

In #9176 Dan and I settled on Docker Hub as the preferred name for that service. This PR makes that consistent across batch docs. I left `docker_resources.rst` alone to avoid conflicting with #9176.

[batch] consistently name Docker Hub

---

benchmark/Makefile

To run benchmarks, you'll need to grant your batch service account permissions:
1. grab service account name from https://auth.hail.is/user
Then:
```
export BATCH_SERVICE_ACCOUNT="..."
gsutil iam ch serviceAccount:${BATCH_SERVICE_ACCOUNT}:objectAdmin gs://hail-benchmarks-2
gsutil iam ch serviceAccount:${BATCH_SERVICE_ACCOUNT}:objectViewer gs://artifacts.broad-ctsa.appspot.com
```

[query] Benchmark in broad-ctsa

---

batch/Makefile
batch/batch/driver/instance_pool.py
batch/build-batch-worker-image-startup.sh

This should wait for #9184 
This PR adds fluentd support for streaming the logs to Logs Viewer.
Things to Note:
-  I didn't have to setup the authorization at all, so I believe it's using the service account on the worker which would be the batch2 service account. I had to give that service account Logs Writer permissions. This is the same service account regardless of the namespace.
- All namespaces have output written.
- I added some labels of the instance id and namespace to help with searching. Let me know if you think we need something else.
- I used a filter to parse the JSON in the worker log to get the right timestamp of the record rather than the publication of the log message in the Logs Viewer
Example Stackdriver Queries:
```
resource.type="gce_instance" …
```

[batch] Add fluentd support to worker

---

dev-docs/tls-cookbook.md
dev-docs/tls.md

This is an adaptation of my comment on the TLS PR.
I moved the old `tls.md` to `tls-cookbook.md`. Git doesn't realize that.
Dania & @catoverdrive, y'all are probably the two folks most likely to benefit from tls.md, so I'd appreciate your comments on the readability of this document.

[dev-docs] Describe TLS

---

hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

~~Stacked on #9106.~~
Adds an enumeration to control the allocation strategy in emitted code. There are currently three options, `Default`, `OneRegion`, and `ManyRegions`. `OneRegion` replicates the current behavior, and is the default for now. `ManyRegions` always allocates new regions when given the choice. This PR makes Java tests use the `ManyRegions` strategy to catch more lifetime errors. `Default` is somewhere in the middle, and will become the default. It will use one region (at least a constant number of regions) per row of a table. `Default` currently behaves the same as `ManyRegions`. Future work will implement the per-row behavior.

[query][smm 2] Use stream region management in tests

---

hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
hail/src/main/scala/is/hail/io/TextMatrixReader.scala
hail/src/main/scala/is/hail/types/encoded/EType.scala
hail/src/test/scala/is/hail/annotations/StagedRegionValueSuite.scala
hail/src/test/scala/is/hail/types/physical/PSubsetStructSuite.scala

Stacked on #9220
The region parameter to emit ostensibly means "construct the value in this region". But in many places `StagedRegionValueBuilder`s are constructed with the default region, which is the argument to the method being emitted into.
This PR fixes all the uses in the emitter to build values in the right region. Most of the remaining users of the constructor with the default region are in tests, so I thought it safest to remove those constructors, and require explicitly passing the region to build into. Otherwise it's too easy to create memory leaks.

[query][smm 3] force region to be passed to StagedRegionValueBuilder constructor

---

hail/src/main/scala/is/hail/expr/ir/CompileAndEvaluate.scala

Maybe this is an artifact of when we didn't do lowering inside Compile.

[query] optimize in CompileAndEvalutate consistently

---

hail/src/main/scala/is/hail/annotations/CodeOrdering.scala
hail/src/main/scala/is/hail/expr/ir/ComparisonOp.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

I need this to write the local keyby/orderby lowering entirely in IR, which is necessary to fix the currently-broken design.

[query] Add CompareStructs comparison node

---

image-fetcher/fetch-image.sh

The contents of ssl-config are not named after the service in question. See create_certs.py

[image-fetcher] fix path to curlrc

---

site/www/references.md

pandoc treats 4-space indentation as a literal text block and wasn't parsing the innermost h1 and div tags.

[www] remove hero indentation so pandoc can parse the html correctly

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/StagedRegion.scala
hail/src/main/scala/is/hail/types/physical/PCode.scala

~~Stacked on #9177~~
These are tricky because of the overlapping lifetimes of the accumulator values. The solution implemented here is to keep two regions. When running the fold body, one region is empty, and the other holds just the previous accumulator. Then we deep copy the new accumulator to the empty region, clear the other one, then swap the two regions before moving to the next iteration.
This required expanding the StagedRegion API a bit. First, it now strictly tracks the parent StagedRegion, even in the non-allocating case where the parent wraps the same run-time region. Second, in addition to copying a value to the parent, we can now copy a value to a sibling. It enforces at compile time that the two regions have the same parent. It follows that either both are actually separate …

[query][smm 5] Memory management for StreamFold and StreamFold2

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala

~~Stacked on #9178~~
This adds memory management to ShuffleWrite, CollectDistributedArray, and WritePartition, all of which are straightforward. With #9178 this finishes all stream consumers, except TableMapPartitions, which will need to pass in the consumer's region.

[query][smm 6] Memory management for other stream consumers

---

batch/test/test_dag.py

Now that we have the old workers, we allow wildcards in the file paths.

[batch] revert test for wildcards in input paths

---

batch/Makefile

Context: `batch/Makefile` is for manually building and deploying batch from your local machine.  This is rare, and is done when we are bootstrapping a new cluster, or something goes wrong and we need to manually intervene.    The service Makefiles have three main targets: `build`, `push` and `deploy`.  `build` builds docker images for the service locally.  `push` pushes them to the Google Container Repository.  `deploy` deploys the new image to Kubernetes.
The `build` target builds a new image, and BATCH_IMAGE uses docker to get the current image.  `:=` means evaluate once.  This means the JINJA_ENVIRONMENT had the image when `make` was invoked.  So if a new image was built, deploy would deploy the wrong image.
@danking @jigold I wonder if this might explain surprising behavior when you …

batch `make deploy` could push stale image

---

batch/batch/driver/instance_pool.py

use preemptible and local ssd quotas
Inspired by some slow spin up issues I saw on the other instance.  Also, there was a bug: the zones for us-east1 were wrong (it is b,c,d not a,b,c).  Also added new region us-west4.
We might want to scrape the quotas at startup.  We probably want to subtract the instances by region to compute the weights.  This is a step in the right direction.

[batch] improve region balancing

---

hail/python/hailtop/hailctl/dataproc/cli.py
hail/python/hailtop/hailctl/dataproc/gcloud.py
hail/python/hailtop/hailctl/dataproc/modify.py
hail/python/hailtop/hailctl/dataproc/start.py
hail/python/test/hailtop/hailctl/dataproc/conftest.py
hail/python/test/hailtop/hailctl/dataproc/test_cli.py
hail/python/test/hailtop/hailctl/dataproc/test_modify.py
hail/python/test/hailtop/hailctl/dataproc/test_start.py

[gcloud 284.0.0](https://cloud.google.com/sdk/docs/release-notes#28400_2020-03-10) deprecated the `--num-preemptible-workers` and `--preemptible-worker-boot-disk-size` arguments to `gcloud dataproc clusters create`.
[gcloud 285.0.0](https://cloud.google.com/sdk/docs/release-notes#28500_2020-03-17) deprecated the `--num-preemptible-workers` argument to `gcloud dataproc clusters update`.
This replaces `--num-preemptible-workers` with `--num-secondary-workers` and `--preemptible-worker-boot-disk-size` with `--secondary-worker-boot-disk-size` in calls to `gcloud` from `hailctl dataproc start` and `hailctl dataproc modify`.
Since the new arguments were added in gcloud version 285.0.0 (released in March 2020), this also adds a requirement that gcloud be at least version 285.0.0. Alternatively, …

[hailctl dataproc] Replace deprecated gcloud arguments in hailctl dataproc start and modify

---

hail/python/hail/experimental/vcf_combiner/vcf_combiner.py
hail/python/test/hail/experimental/test_vcf_combiner.py

`import_gvcfs` makes no assumptions about the number of samples in
a file, and so external sample names must be a list of lists.

[combiner] fix import_gvcfs call in run_combiner

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/agg/NDArraySumAggregator.scala
hail/src/main/scala/is/hail/types/physical/PBaseStruct.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalBaseStruct.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/types/physical/PNDArray.scala
hail/src/main/scala/is/hail/types/physical/PSubsetStruct.scala

It's wildly unsafe. It's better to scope the unsafety in
`IEmitCode.handle` for `loadField`.
Also add `PNDArrayValue.shapes` to handle the previous use case of
`PBaseStructValue.apply`.

[query] Remove PBaseStructValue.apply

---

hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/StagedRegion.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala

~~Stacked on #9232.~~
This adds memory management to StreamGrouped and StreamGroupByKey. As always, the case where the inner stream is never consumed causes complications. Because the child stream gets its per-element region from the consumer of the inner stream, if the inner stream is unconsumed we have to pass some other region.
The solution implemented here uses the outer stream's eltRegion. If the outer stream's consumer allows creating new regions, the grouping node creates an owned region to construct child stream elements in, and clears it every element (because it is never passed to a consumer). Otherwise, all child elements get created in the outer stream's eltRegion.

[query][smm 10] Memory management for grouped streams

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/types/encoded/EBlockMatrixNDArray.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/types/physical/PNDArray.scala

Almost every call to these methods was just casting the values to codes anyway, and using a list of values makes more sense. In the future, we are almost definitely going to want to change this so the method just directly takes in a `PTupleValue` so that we aren't making variables per dimension of the ndarray all the time.

Change PNDArray builder methods to take in Values instead of Codes

---

hail/python/hail/expr/functions.py

I did not like that all of the `hl.zip` examples returned a length one array. We were only showing how the edge case with different array lengths worked. Now I show an example of the common case, where you have two arrays of the same length and you want to combine them into one array of tuples.

Added better example for the common case of hl.zip

---

hail/python/hail/docs/nd/index.rst
hail/python/hail/ir/__init__.py
hail/python/hail/ir/ir.py
hail/python/hail/nd/__init__.py
hail/python/hail/nd/nd.py
hail/python/test/hail/expr/test_ndarrays.py
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/linalg/LAPACK.scala
hail/src/main/scala/is/hail/types/physical/PNDArray.scala

This adds an `svd` method to `hl.nd`, allowing us to take singular value decomposition of local ndarrays. This is a generally useful operation, but my primary reason for adding it is to avoid the need to call numpy's SVD as a substep of Annamira's new randomized PCA method. The interface is designed to match numpy exactly. 
Note that this method uses the LAPACK method `dgesdd`, which is newer, faster version of `dgesvd`. As far as I can tell, there's never a reason to use `dgesvd`.

[query] Add `hl.nd.svd` for doing local Singular Value Decompositions

---

hail/python/hailtop/hailctl/dataproc/modify.py
hail/python/hailtop/hailctl/dataproc/start.py

CHANGELOG: Teach `hailctl dataproc start` about `--expiration-time`. Teach `hailctl dataproc modify` about `--no-max-idle`, `no-max-age`, `--max-age`, and `--expiration-time`.
These flags were always available as pass-throughs. This change adds them to the
help documentation and improves error messages in the case that an incompatible
set of arguments are provided together.

[hailctl] improve accessibility of max age and expiration time

---

batch/batch/driver/instance_pool.py
hail/python/hailtop/aiogoogle/client/compute_client.py

Instead of using a fixed weighting, query the GCP /regions endpoint which includes the quota limit and usage.  Use this to weight zones for new instance requests.  Added a ComputeClient.list endpoint that should work with any GCE list endpoint that is paged.
I'm working on improving this logic further by tracking how often instance create requests fail and then weighting zones by `capacity * p(create instance will succeed)`.

[batch] weight zones by quota capacity

---

.dockerignore
.gitignore
hail/Makefile

These things get huge! There is one for each folder and most of the hail ones
are bigger than 10MB

[git][docker][hail] pervasively ignore the mypy_cache folders

---

internal-gateway/internal-gateway.nginx.conf

It seems that 83 is potentially too high now.  I saw batch-driver get overwhelmed with the current setting.  However, there was also a bug related leaking database connections which also contributed to the observed behavior.  Batch was able to make forward progress with 45, so at least this is safe and can be adjusted again next time we're running at scale.

[internal-gateway] lower per-instance request rate to 45

---

hail/src/main/scala/is/hail/io/BufferSpecs.scala
hail/src/main/scala/is/hail/io/InputBuffers.scala
hail/src/main/scala/is/hail/io/OutputBuffers.scala

I'm having a lot of of trouble demonstrating that this is faster using the benchmark system. I can see a marked improvement in shuffle benchmarks using my laptop:
```
$ hb compare /tmp/lz4-before.json /tmp/lz4-after.json
Benchmark Name      Ratio     Time 1     Time 2
--------------      -----     ------     ------
shuffle_order_by_10m_int      70.4%     47.193     33.245
```
I also don't see any slowdown for the larger shuffles (which do get slower if we use one of the uncompressed codecs).
Running benchmarks on batch have produced results where the median varies from 1% slower to 6% faster.

[query] Use size-based LZ4 compression codec for wireCodec (shuffles)

---

benchmark/Makefile

Make evaluates the entire recipe before executing it. Consider this:
```
(base) # cat Makefile; rm -rf file; make foo
foo:
echo hello > file
echo $(shell cat file)
cat: file: No such file or directory
echo hello > file
echo 
```
The file does not exist because Make runs cat before the recipe is executed.

[benchmark] use latest SHA

---

hail/Makefile

Docs build fails if build/batch does not exist.

[batch] fix batch docs build

---

hail/src/main/scala/is/hail/expr/ir/lowering/LowerDistributedSort.scala

[query] Fix local shuffle implementation with no rows

---

benchmark/python/benchmark_hail/run/linalg_benchmarks.py
hail/src/main/scala/is/hail/io/InputBuffers.scala
hail/src/main/scala/is/hail/linalg/BlockMatrix.scala

CHANGELOG: Eliminate quadratic behavior in `BlockMatrix.to_matrix_table_row_major`. Users should expect significant reduction in run-time.
There are two significant changes in this PR:
- Teach `LZ4InputBlockBuffer` how to skip bytes without decompressing every block, and
- Teach BlockMatrix to use a small cache of rows when converting from a BlockMatrix to a row-wise RDD.
We compress in blocks of 16 KiB. The blocks begin with an 32-bit integer indicating the decompressed length. When we're skipping large numbers of bytes we can request an `LZ4InputBlockBuffer` to skip decompression if the entire block will be skipped.
Currently, for every row in every block, BM opens a file, skips to the appropriate location, reads that one row, writes it into an RVB, and then closes the file. This has …

[hail] Eliminate quadratic behavior in BlockMatrix.to_matrix_table_row_major

---

hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala

We end up with tens of thousands of miniscule broadcasts across
thousands of executors, the management of which seems to take signifigant
time.

[query] Don't broadcast the contigRecoding if there are no contigs

---

hail/.gitignore
hail/Makefile
hail/python/hail/docs/Makefile
hail/python/hailtop/batch/docs/Makefile

It takes one minute to build the docs *even if nothing has changed since the
last build*. There are a few things that lengthen the feedback cycle:
- We defeat Sphinx's input cache by deleting and re-copying over all the source
files.
- We defeat Sphinx's output cache by `mv`ing the output to a new location.
- We check that Hail is installed (at a cost of two seconds) *every* time we
build the docs. This isn't necessary, Sphinx prints a reasonable message
("cannot import ...") if Hail is not installed.
- We create a wheel file every time we build the docs at a cost of several
seconds.
- We recreate the tutorials tar even if it has not changed.
Instead, I propose this PR:
- Do not copy the source files.
- Copy the output to the new location.
- Do not check hail is installed.
- Do not even …

[hail][docs] overhaul docs build Makefile

---

hail/python/hailtop/hailctl/dataproc/connect.py
hail/python/test/hailtop/hailctl/dataproc/test_connect.py

Unlike many other `hailctl dataproc` commands, there is currently no way to specify a project for `hailctl dataproc connect`.

[hailctl dataproc] Allow specifying project for hailctl dataproc connect

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/expr/expressions/typed_expressions.py

Let me know if you think the error message is clear.

[query] Better error message when using `in` incorrectly

---

hail/python/hail/docs/functions/collections.rst
hail/python/hail/docs/functions/index.rst
hail/python/hail/experimental/full_outer_join_mt.py
hail/python/hail/experimental/phase_by_transmission.py
hail/python/hail/expr/__init__.py
hail/python/hail/expr/functions.py
hail/python/hail/matrixtable.py
hail/python/hail/methods/statgen.py

`zip_with_index` seems based on Scala's `zipWithIndex`. Here I deprecate that in favor of using the more pythonic `enumerate`. To match the signature of the python function, I add a `start` argument and make our custom `index_first` argument keyword only.

[query] Add enumerate, deprecate zip_with_index

---

batch/batch/driver/main.py
batch/sql/add-aggregated-batch-resources-tokens.sql
batch/sql/estimated-current.txt
build.yaml

I tested this by adding the check_aggregated_resources loop which didn't throw any errors. I tested the cost by looking at the UI and submitting one job that cost $0.0004 and then two of that same job in a batch and it cost $0.0008. The database looked like this:
mysql> select * FROM aggregated_batch_resources where batch_id > 46;
+----------+--------------------------+-------------+-------+
| batch_id | resource                 | usage       | token |
+----------+--------------------------+-------------+-------+
|       47 | compute/n1-preemptible/1 |    25867000 |    11 |
|       47 | compute/n1-preemptible/1 |           0 |   115 |
|       47 | compute/n1-preemptible/1 |           0 |   132 |
|       47 | disk/local-ssd/1         |  9932928000 |    11 |
|       47 | disk/local-ssd/1 …

[batch] add tokens to aggregated_batch_resources

---

hail/src/main/scala/is/hail/linalg/BlockMatrix.scala

Do this by:
- Marking fields as transient when possible
- Broadcasting the child partitions array and blockParentsMap

Decrease BlockMatrixFilterCols Memory Usage

---

hail/src/main/scala/is/hail/services/DeployConfig.scala

It is possible for socket connect to fail if the shuffle service is down (e.g. https://ci.hail.is/batches/91027/jobs/105).
This change ensure we retry forever, periodically logging that we are retrying

[shuffler] retry socket connect

---

hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala
hail/src/main/scala/is/hail/expr/ir/RewriteBottomUp.scala
hail/src/main/scala/is/hail/utils/StackSafe.scala

This PR adds `utils/StackSafe.scala`, which contains generic tools for writing stack safe code. To illustrate its use, I've converted `NormalizeNames` and `RewriteBottomUp` to be stack safe.
This approach optimizes for the minimal possible change to existing code to make it stack safe. I originally expected this to have mediocre performance, and designed this to have optimization opportunities--requiring more substantial rewrites--where we found it was necessary.
In a follow up PR, I converted the IR parser to be stack safe. In benchmarking that, I'm not able to see any performance penalty (if anything, the stack safe version looks slightly faster, which is probably just noise). So it's possible this will perform well enough as is, but we can keep an eye on it as we convert more passes. …

[query] Framework for making compiler passes stack safe

---

batch/batch/driver/instance_pool.py
batch/test/test_batch.py

We're supposed to use DOCKER-USER https://docs.docker.com/network/iptables/.
I also added a test.

[batch] block containers from using the metadata server

---

hail/python/hail/experimental/dnd/array.py
hail/python/test/hail/experimental/test_dnd_array.py

In `main`, dnd array is just very broken if the columns are not ordered by their
column key.
I also added the missing `n_partitions` kwarg to `array`.

[hail] implement sort_columns for dndarray

---

hail/src/main/scala/is/hail/linalg/BlockMatrix.scala

The current `filter_rows` is implemented as a transpose. Nik and Konrad are running into driver memory issues when doing `tree_matmul`, and one theory of mine is that making lots of `BlockMatrixTransposeRDD`'s is contributing to this.  I'd like to make this change to avoid that in the future.

Add BlockMatrixFilterRowsRDD to decrease transposing

---

monitoring/test/test_monitoring.py

Fixes:
```
async def test_billing_monitoring():
deploy_config = get_deploy_config()
monitoring_deploy_config_url = deploy_config.url('monitoring', '/api/v1alpha/billing')
headers = service_auth_headers(deploy_config, 'monitoring')
async with in_cluster_ssl_client_session(
raise_for_status=True,
timeout=aiohttp.ClientTimeout(total=60)) as session:
async def wait_forever():
data = None
while data is None:
resp = await utils.request_retry_transient_errors(
session, 'GET', f'{monitoring_deploy_config_url}', headers=headers)
data = await resp.json()
await asyncio.sleep(5)
return data
data = await asyncio.wait_for(wait_forever(), timeout=30 * 60)
>           assert data['cost_by_service'], str(data)
E           AssertionError: {'cost_by_service': [], 'compute_cost_breakdown': [], …
```

[monitoring] fix test to allow no data returned by big query

---

hail/python/hailtop/batch/genetics/regenie/regenie.py

I do not understand how this passed the PR tests, but this fix makes regenie not
use the metadata server to authenticate itself.

[batch] avoid use of metadata server in regenie tests

---

hail/src/main/scala/is/hail/asm4s/ClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/StagedBlockLinkedList.scala
hail/src/main/scala/is/hail/types/encoded/EArray.scala
hail/src/main/scala/is/hail/types/encoded/EBaseStruct.scala
hail/src/main/scala/is/hail/types/encoded/EBinary.scala
hail/src/main/scala/is/hail/types/encoded/EBlockMatrixNDArray.scala
hail/src/main/scala/is/hail/types/encoded/EBoolean.scala
hail/src/main/scala/is/hail/types/encoded/EFloat32.scala
hail/src/main/scala/is/hail/types/encoded/EFloat64.scala
hail/src/main/scala/is/hail/types/encoded/EInt32.scala
hail/src/main/scala/is/hail/types/encoded/EInt64.scala
hail/src/main/scala/is/hail/types/encoded/ENDArrayColumnMajor.scala
hail/src/main/scala/is/hail/types/encoded/EPackedIntArray.scala
hail/src/main/scala/is/hail/types/encoded/ETransposedArrayOfStructs.scala
hail/src/main/scala/is/hail/types/encoded/EType.scala
hail/src/main/scala/is/hail/types/physical/PBaseStruct.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalArray.scala
hail/src/main/scala/is/hail/types/physical/PContainer.scala

This streamlines the logic significantly. No attempt has been made to have the encoder methods take
PCode/EmitCode directly, but that is the future direction here.

[query] Switch _buildEncoder methods to use CodeBuilder infrastructure

---

ci/ci/ci.py

Previously this triggered a 500 because a `MergeFailureBatch` has no `jobs`.

[ci] report merge failure exception in deploy_status

---

hail/python/hail/ir/ir.py
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/ExtractIntervalFilters.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalStream.scala
hail/src/main/scala/is/hail/types/physical/PStream.scala
hail/src/main/scala/is/hail/types/physical/PType.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/RequirednessSuite.scala

This PR makes the following changes:
* Add a `separateRegions` flag to `PStream`.
* Add a `separateRegions` flag to the stream producer nodes `MakeStream`, `StreamRange`, and `ToStream`.
* Propogate `separateRegions` through all stream nodes in `InferPType`.
The intended semantics is that if a stream's type has the `separateRegions` flag set, its consumer must pass it a region which gets cleared every element. If the flag is not set, there is no requirement; depending on context, the consumer may put every element in the same region, but is also allowed to use separate regions for each element. For example, in a zip, the elements of the zipped stream are put in separate regions iff at least one child stream requires separate regions; in that case, all children will get emitted with …

[query] encode allocation behavior in stream PTypes

---

internal-gateway/Dockerfile
internal-gateway/internal-gateway.nginx.conf
internal-gateway/nginx.conf
internal-gateway/service.yaml

The plan for TLS workers is:
- internal-gateway supports HTTP and HTTPS
- workers speak server-auth-only TLS
- internal-gateway supports only HTTPS
- workers proffer client auth
- internal-gateway requires client auth
This is step 1.

[internal-gateway] permit TLS connections to internal gateway

---

auth/auth/driver/driver.py
ci/create_database.py
gear/gear/database.py
hail/python/hailtop/auth/sql_config.py

In https://github.com/hail-is/hail/pull/9113, I forced the auth driver to use
the modern, TLS-required, SQL config format. I incorrectly forgot to specify the
TLS file paths. Luckily, when I tried to create a user account for Patrick
Cummings, instead of creating a broken secret, the auth driver
error'ed. Moreover, the clean up code was broken. As a result, Patrick's account
was stuck in `creating`.
This PR fixes both the clean up code issue (I set `self.namespace` in
`K8sSecretResource`) and specifies the TLS file paths (see driver.py near
line 217).
In addition, this PR attempts to avoid future problems with the sql
configuration by codifying the required components as a NamedTuple, `SQLConfig`. I also
co-located all the parsing and transformation logic between JSON, dicts, and CNF
in …

[auth] teach auth to specify SSL for SQL secrets

---

auth/auth/driver/driver.py

SQLConfig requires an `ssl_mode`, this prevents auth from creating Developer accounts.
I already deployed this.

[auth] missing ssl_mode

---

hail/build.gradle

I don't think it is used anymore.  Builds are failing because it is returning 500.
> Unable to load Maven meta-data from https://repo.hortonworks.com/content/repositories/releases/org/scalanlp/breeze-natives_2.11/maven-metadata.xml.
> Could not get resource 'https://repo.hortonworks.com/content/repositories/releases/org/scalanlp/breeze-natives_2.11/maven-metadata.xml'.
> Could not GET 'https://repo.hortonworks.com/content/repositories/releases/org/scalanlp/breeze-natives_2.11/maven-metadata.xml'. Received status code 500 from server: Server Error

[hail/build.gradle] remove Hortonworks repo from build.gradle.

---

hail/python/hailtop/hailctl/dataproc/start.py

Currently the only debug feature is the heap dump flag, but probably best to control debug features we might add in the future as a unit.

[hailctl] Add `--debug-mode` flag to `hailctl dataproc start`

---

hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/ExecuteContext.scala

CHANGELOG: Drastically reduce memory usage by `tree_matmul`
`tree_matmul` reads from the same RDD many times. The RDDs created by `BlockMatrixRead` can actually be big when reading in a very large matrix, since they contain all the BlockMatrix metadata, which means a very long list of string file names. I don't want to create many different copies of this RDD when it would be better to share one copy.

Don't create multiple copies of same RDD during `BlockMatrixRead`. 

---

hail/python/hail/backend/spark_backend.py
hail/python/hail/expr/builders.py
hail/python/hail/ir/base_ir.py
hail/python/hail/ir/ir.py
hail/python/hail/utils/__init__.py
hail/python/hail/utils/java.py
hail/python/test/hail/expr/test_expr.py
hail/python/test/hail/expr/test_ndarrays.py
hail/python/test/hail/linalg/test_linalg.py
hail/python/test/hail/methods/test_misc.py
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/IRBuilder.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/functions/DictFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/utils/ErrorHandling.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

This PR is based on discussion here: https://dev.hail.is/t/better-python-error-messages-idea/201/9 The intention is to create a system to give better error messages from python in a generic way. Tim's work in #7792 does a good job introducing behavior like this this specifically for `ArrayRef` nodes, but I want to add three things on top of that:
1. I don't want to have to do as much custom per IR node work
2. I don't want to send the entire python stack trace over py4j to scala for every node
3. I don't want the user to see a Java stack trace in this scenarios.
This first PR is a proof of concept that adds this behavior for the `Die` node, which will catch any errors generated by uses of `CaseBuilder.or_error`. Follow up PRs should change `ArrayRef` to work this way, as well as catch …

Better Python Errors

---

build.yaml

Increase memory and cpu for test_hail_services_java to match java query tests. This contains tests of the shuffler IR, which runs the hail compiler, so it seems it should have the same resource limits as the other java query tests. #9401 is getting an out of memory error in `testShuffleIR`.

[ci] raise resources for java services tests

---

hail/src/main/scala/is/hail/linalg/BlockMatrix.scala

It should complain if `uri` already exists, not `prefix`.

Fix `writeBlockMatrices` file already exists check

---

build.yaml
hail/python/Makefile
hail/python/hailtop/aiogoogle/__init__.py
hail/python/hailtop/aiogoogle/auth/__init__.py
hail/python/hailtop/aiogoogle/auth/session.py
hail/python/hailtop/aiogoogle/client/__init__.py
hail/python/hailtop/aiogoogle/client/base_client.py
hail/python/hailtop/aiogoogle/client/compute_client.py
hail/python/hailtop/aiogoogle/client/storage_client.py
hail/python/hailtop/aiotools/__init__.py
hail/python/hailtop/aiotools/fs.py
hail/python/hailtop/aiotools/stream.py
hail/python/hailtop/aiotools/utils.py
hail/python/hailtop/batch/batch_pool_executor.py
hail/python/hailtop/batch/genetics/regenie/regenie.py
hail/python/hailtop/batch/resource.py
hail/python/hailtop/batch/utils.py
hail/python/hailtop/hail_logging.py
hail/python/hailtop/tls.py
hail/python/test/hailtop/test_aiogoogle.py

- Added a (low level) aiogoogle.StorageClient for Google Storage.
- Added an abstract AsyncFS interface.  There are currently 3 implementations: GoogleStorageAsyncFS, LocalAsyncFS, and RouterAsyncFS, which can route (based on the scheme) to other file systems.  I tried to copy the standard Python os file system interface (open, remove, mkdir, isfile, etc.)  I'm skeptical about pushing hard on this perspective, and I think we're better off finding a natural interface that that unifies local, gs, (hadoop) and s3.  Maybe a read-only HttpFS.  I think I want to split open() into open (for reading) and create (for writing).  LocalFS operations are run in a thread pool which controls the level of IO parallelism.
- AsyncFS.open returns an AsyncStream.  This is an async …

[hailtop/aiogoogle] added StorageClient

---

hail/python/hail/methods/pca.py

Tried this locally on a `hl.balding_nichols_model(20, 6000, 50000)` dataset, overall time for 10 pcs with 2 iterations went from ~50 seconds to ~40 seconds. Surprised it made that much of a difference.

Avoid calling a tail -> collect in blanczos pca

---

hail/python/hail/methods/pca.py

#9425 fixes the bug that caused us to need to checkpoint twice. This PR removes the second checkpoint.
For the `hl.balding_nichols_model(20, 6000, 50000)`, 2 iterations test I've been doing, this gets us down to more like 35 seconds, as opposed to ~40. Current hail PCA takes more like 16 seconds, so we are getting closer (though again, it's not clear that 2 is going to be the right number of iterations in the end).

Remove extra checkpoint from blanczos_pca

---

hail/src/main/scala/is/hail/io/reference/FASTAReader.scala

In readBlock, membership was checked in a LinkedHashMap, then if it was
found, the value was retrieved from the cache. This lead to a data race
where a value could be evicted between the check and retrival. The
solution is to grab the block value out of the map, and if it is not
null, return it, otherwise, grab the block string, put it in the map,
and return it.
Co-authored-by: Tim Poterba <tpoterba@broadinstitute.org>

[query] Fix data race in FASTA reader

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/types/physical/PNDArray.scala

Moving two IR nodes to `emitI`, plus cleaning them up to be a bit more idiomatic.

emitI: NDArrayShape and NDArrayReindex 

---

batch/batch/front_end/front_end.py
batch/batch/front_end/validate.py
batch/test/test_batch.py
build.yaml
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py

I'd like to give the user the ability to authenticate to our services from within a batch job. The specific use case I need it for is for the query service to be able to cache things with the memory service, but it seems like it could be more broadly applicable. I'm unsure whether this is the correct way to do it.
This is currently not exposed in the python user interface (only in BatchClient), but I can pipe the option through in this PR if we want to.

[batch] add option for mounting user token inside batch job

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/package.scala

Nothing in `IEmitCode` depends on the value being a `PCode`. This PR makes `IEmitCode` a type alias, `IEmitCode = IEmitCodeGen[PCode]`, where `IEmitCodeGen` is a generic version. This supports any pattern where we generate missing and present branches, and the value can be anything to be used while generating the present branch, e.g. `Code`, `PCode`, `Array[PCode]`, `Stream`, or even another optional value (an `EmitCode` or `CodeBuilder => IEmitCode`.

[query] Make IEmitCode generic

---

batch/batch/front_end/front_end.py
batch/batch/front_end/templates/billing_projects.html
batch/test/test_batch.py
hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py
hail/python/hailtop/hailctl/batch/billing/__init__.py
hail/python/hailtop/hailctl/batch/billing/cli.py
hail/python/hailtop/hailctl/batch/billing/get.py
hail/python/hailtop/hailctl/batch/billing/list_billing_projects.py
hail/python/hailtop/hailctl/batch/cli.py

- I use a right join in the query so that if there are no users, the record['users'] ends up being None rather than [None].
- I decided that an arbitrary user should be able to see all the other users for billing projects they are on.
- I decided that a developer can see all billing projects.
This is infrastructure that I figured was nice to have but also will make #9354 better so I can add proper tests.

[batch] add rest api for billing_projects

---

hail/python/hail/backend/backend.py
hail/python/hail/backend/spark_backend.py
hail/python/hail/ir/__init__.py
hail/python/hail/ir/base_ir.py
hail/python/hail/ir/blockmatrix_ir.py
hail/python/hail/ir/blockmatrix_reader.py
hail/python/hail/ir/ir.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/backend/Backend.scala
hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/backend/spark/SparkBlockMatrixCache.scala
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/BlockMatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Compilable.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpret.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Simplify.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

I need to use the backend context while persisting in order to support this with user separation on the service. I also moved the methods onto the general backend in preparation for implementing this on the service backend.

[query] refactor block matrix persistence to take backend context

---

hail/src/main/scala/is/hail/expr/ir/BlockMatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
hail/src/main/scala/is/hail/expr/ir/agg/NDArraySumAggregator.scala
hail/src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala
hail/src/main/scala/is/hail/io/index/InternalNodeBuilder.scala

`IEmitCode.consume`, with signature `consume[T](cb: EmitCodeBuilder, ifMissing: => Unit, ifPresent: (A) => T): T`, is wrong: it exports a value that is only defined in the present branch to be used after the two branches have joined.
The only use of this manually guarded the exported value by a bit remembering which branch was taken, but this is better handled by memoizing the `IEmitCode` in an `EmitValue`. Almost every other use of `consume` could be more simply expressed using `handle`, and moreover almost every use of `handle` could be more simply expressed using a method `get` which simply throws an exception if the missing branch is taken.
For those few cases where one really does want to consume an `IEmitCode` to a `Code` or `PCode`, with definitions given for each branch, I added …

[query] fix IEmitCode.consume

---

hail/src/main/scala/is/hail/io/reference/FASTAReader.scala
hail/src/main/scala/is/hail/variant/ReferenceGenome.scala
hail/src/test/scala/is/hail/variant/ReferenceGenomeSuite.scala

Introduce FASTAReaderConfig to act as a kind of factory for FASTAReader,
while all FASTAReaders themselves are confined to ThreadLocals (except
in tests).
Furthermore, add a lock around the fasta file map to prevent more than
one fasta from being copied per jvm. The can be lock contention on the
map, but if there is large amounts of waiting for said lock, then it
usually means that a fasta is downloading and we definitely should be
waiting.

[query] Work around concurrency issues in FASTAReader

---

hail/src/main/scala/is/hail/services/package.scala

This can happen if the server is restarted during an SSL handshake.

[services] retry after an unexpected EOF

---

hail/src/main/scala/is/hail/io/reference/FASTAReader.scala
hail/src/test/scala/is/hail/variant/ReferenceGenomeSuite.scala

On certain occasions, the file inside the FASTA reader can be closed. It
is not yet understood why. Tests indicate that simply reopening the file
seems to resolve the issue when we run the appropriate exception.
This also removes the need for SerializableReferenceSequenceFile, and so
deletes it.

[query] Add retry to FASTAReader.getSequence

---

batch/sql/change_test_worker_pool_size.py
build.yaml

The tests relying on Batch are getting slower because it takes a long time to download and build Docker images and we're putting more load on Batch. This will increase parallelism and reduce test failures due to timeouts.

[batch] Change number test worker pool size

---

hail/python/hail/docs/getting_started_developing.rst

Make targets for building docs were renamed in #8086 and #9348.
`make install-dev-deps` does not cover all build dependencies for docs (it does not install pandoc), so added a note about what is required.

Update documentation for building Hail documentation

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala

After this and #9450 go in, all NDArray IR nodes will be moved to `emitI`, making it easier for me to update `NDArrayEmitter` to use `EmitCodeBuilder` and `PCode`. I cleaned up `NDArrayQR` a little bit in this PR, but all the low level LAPACK stuff means it's still kind of a mess.

emitI NDArrayQR

---

hail/python/hail/experimental/vcf_combiner/sparse_mt_utils.py

[query/sparse_mt] preserve phasing in lgt_to_gt

---

batch/batch/driver/scheduler.py
ci/ci/build.py

Add a few helpful log statements and use default CPU/mem rather than explicitly specifying it in CI. This reduces cpu from 1 to 0.1. I have to parse the cgroup requirements to ensure that the host docker daemon does not exceed the limits of the build job.

[batch] reduce test flakiness

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_expr.py

Requested in #9188.
This is similar to [hl.delimit](https://github.com/hail-is/hail/blob/6b5d7a5cde246c5caf53b97c5b17d7e7c6440fec/hail/python/hail/expr/functions.py#L4293-L4326). However, unlike hl.delimit, this throws a TypeError if a collection with a non-string element type is provided. This matches the behavior of Python's [str.join](https://docs.python.org/3/library/stdtypes.html#str.join).

Add join method to StringExpression

---

hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/StagedRegion.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

Stacked on #9400 
This PR modifies stream consumers' emit cases to look up `separateRegions` on the child stream's type, using that to construct the appropriate `StagedRegion`, then passing that region into `emitStream`. It also removes `EmitAllocationStrategy`, as this is now encoded in the IR. We may at some point want something similar to choose what allocation behavior to generate during lowering, but that is left for future work.
Getting this to work well required some changes to the `StagedRegion` design.
First, when a stream node needs to create a fresh region which it owns, the new region is now created as a child of the `outerRegion`, not the consumer's `eltRegion` as was done before. This simplifies the semantics of the parent/child relationship: now the lifetime of a child …

[query] enable memory managenment in lowered IR

---

hail/python/hailtop/batch/batch_pool_executor.py

The `BatchPoolExecutor` assumes, incorrectly, that the default number of CPUs for
a batch job is 1. This is not true in test and development environment.
I avoid explicitly setting the value if it is `None`. This choice preserves the
default value in this environment. I set the thread limit to 1 if the CPU is `None`.

[batch] do not explicitly set cpu in BPE, which improves test time

---

batch/batch/driver/instance_pool.py
batch/batch/driver/scheduler.py
batch/batch/utils.py

I noticed that jobs in test deployments were deadlocking because we weren't spinning up extra instances (compared to the production version of Batch). Although each job could fit on an open instance, its allocated share is still less than the core request for that job. This PR aims to increase the probability in which we ignore an exceed shares error the more we have these errors such that at a certain point the rate will be 100% and we'll be able to continue scheduling.

[batch] Fix deadlock with exceeded shares

---

hail/python/hail/expr/functions.py
hail/python/requirements.txt

Now we can add a decorator to give a warning when a user uses a deprecated thing. It will print a message out when it is used. 
There's a way to get this to automatically print in Sphinx as well, but I'll set that up later. For now, I have manually mentioned in the docstring when a method is deprecated, and now this decorator will give a warning when it's used.

[query] Deprecation Decorator

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_expr.py

Add `first` method to ArrayExpression to replace `head`. Add `last` method as the counterpart to `first`.

Add first and last methods to ArrayExpression

---

batch/test/serverthread.py
batch/test/test_batch.py
hail/python/hail/backend/service_backend.py
hail/python/hail/experimental/db.py
hail/python/hail/utils/java.py
hail/python/hailtop/tls.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

- Add a flush after writing the first log statement. This log statement is
displayed before any network requests, the flush ensures we always see it.
- Set the retries for in-cluster synchronous requests to 1.
- Change all external (ones that go through the gateway) HTTP(S) requests to use
a centrally defined session. This session improves the situation in two ways:
1. It prevents urllib from retrying requests, which ensures Hail's retry
infrastructure is the only retry infrastructure.
2. It sets a timeout, ensuring that all requests will timeout. Previously,
requests could hang forever.
3. It permits setting headers that are used for all requests.

[query] add timeouts and more logging

---

hail/python/hail/methods/statgen.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala

In this PR, I rewrite `linear_regression_rows_nd` to use `_map_partitions` instead of `_group_within_partitions`. By doing this, I've eliminated the need to do a `key_by` at the end of `linear_regression_rows_nd`. I also think this makes the code clearer. 
This PR also makes a few seemingly random changes that are actually bug fixes:
1. When emitting `Apply` nodes, we were grabbing the `Code[Region]` from the first argument to the `MethodBuilder`. However, the assumption that the first argument will always be a `Region` seems to no longer be true. As such, we just construct a `CodeParam` from the `StagedRegion` we have available. 
2. In the NDArrayEmitter, I want to make sure I call the local `emit` method that passes off to `emitWithRegion`, for the same reason as 1: (Can't trust first …

linear_regression_rows_nd using TableMapPartitions

---

hail/src/main/scala/is/hail/lir/SimplifyControl.scala

This was a good one :)
I haven’t measured the performance difference, but clearly the bug defeated the purpose of using a union-find data structure in the first place, which was to reduce the complexity of `unify` from quadratic to linear.
While I was here, I made a separate simplification. Now that the sets are being unioned as intended, each set contains exactly one block that doesn’t start with a `GotoX`, and that block is the final target of all blocks in the set. That observation allows a simplification when computing the `rootFinalTarget` map.

[query] fix performance bug in lir.SimplifyControl

---

docker/python-dill/Dockerfile
docker/python-dill/Makefile
docker/python-dill/README.md
docker/python-dill/push.sh
hail/python/hailtop/batch/batch_pool_executor.py

The old BPE images (which still exist) are based on the full python image. The
slim image reduces the size by about 750MB. This should substantially improve
image pull on the n1-standards. I have seen image pull for this image take 136
seconds before in a test job.

[batch] use a slim image for BPE

---

hail/python/hailtop/config/user_config.py

It was previously called config.yaml, when it was actually a python
configparser config file, which is a subset of [ini syntax].
[ini syntax]: https://docs.python.org/3/library/configparser.html
Check to see if the .yaml file exists and the .ini file does not exist.
If so, silently rename the config file to the new name.

[hailctl] Fix config file name

---

hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala

I have yet to successfully create a VCF that doesn't hit another error before hitting this one. But user hit this here: https://discuss.hail.is/t/assertionerror-exception/1700

[query] Throw better error in VCFLine.nextField if separator is not a tab

---

hail/python/hail/methods/statgen.py
hail/python/test/hail/methods/test_statgen.py

SparkBackend is the only one that can actually use the Scala/Breeze version of `linear_regression_rows`, right? Otherwise, we need to use the new ndarray version.

Use NDArray Version of linear_regression_rows when not on SparkBackend

---

hail/src/main/scala/is/hail/lir/SimplifyControl.scala
hail/src/main/scala/is/hail/lir/X.scala

~~Stacked on #9490~~
With the stronger invariants enforced by the previous PRs, some of the work done in `asBytes` is redundant.

[query/lir] simplify Classx.asBytes

---

hail/python/hail/ir/table_reader.py
hail/python/hail/linalg/blockmatrix.py
hail/python/test/hail/linalg/test_linalg.py
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/linalg/BlockMatrix.scala

CHANGELOG: Remove memory leak in `BlockMatrix.to_matrix_table_row_major` and `BlockMatrix.to_table_row_major`. Also, make the cache size used in both methods configurable.
The `ref` variable was holding entire blocks in memory for no reason. It was a
vestiage of debugging. Moreover, the configurable cache permits users to fine tune
memory usage.

[hail] Fix memory leak in BM and make cache size configurable

---

hail/src/main/scala/is/hail/asm4s/ClassBuilder.scala
hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/lir/Emit.scala
hail/src/main/scala/is/hail/lir/SplitMethod.scala
hail/src/main/scala/is/hail/lir/X.scala
hail/src/main/scala/is/hail/lir/package.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala

This PR is a first step towards full debug information in generated bytecode. It lays the foundation in lir, and uses it to add line numbers to generated exceptions, which then show up in the stack trace. The line numbers are computed by taking the stack trace in `Code._fatal`, and finding the most recent line in `Emit.scala`, if any. Sometimes this will be less useful, e.g. exceptions thrown in aggregators, but it's a step.
The design of the source location tracking in lir is very simple: every instruction has an associated line number, and `lir.Emit` watches for when the line numbers of the current and previous instruction are different, and emits the start of a new line number interval. This design might be slightly wasteful of memory, if we expect groups of several consecutive …

[query] bytecode debug info for exceptions

---

hail/python/hail/methods/impex.py

CHANGELOG: Fix hl.import_plink docs to properly report the type of `is_case` and `quant_pheno`.
I verified the correct types by checking `LoadPlink.scala`.

[hail] fix hl.import_plink docs

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala

I broke up #9450. This PR moves just `NDArrayMatMul` to `emitI`, and does so by introducing a new, simpler `NDArrayEmitter` called `NDArrayEmitter2`. In a subsequent PR, I'll delete the old `NDArrayEmitter` entirely and move everything over to new version.

NDArrayMatMul EmitI

---

batch/batch/driver/main.py

I have added an item to services design meeting to further discuss the meaning of
`start_time` and `end_time` of an attempt. For the time being, this eliminates the
flakiness that is preventing PRs from merging.

[batch] fix flaky batch invariants test

---

docker/requirements.txt

Related issues in upstream projects:
- YARL issue: aio-libs/yarl#509
- aiohttp issue: aio-libs/aiohttp#4972

[batch] require YARL <1.6.0 which avoids bug

---

hail/python/hailtop/hailctl/curl.py

Subprocess machinery is unnecessary here, we exit right after returning, so use `exec` instead.

[hailctl] use execvp for hailctl curl

---

hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala

The exception message will now have the metadata path to more easily
assist in diagnosing issues.

[hail] Wrap AbstractRVDSpec.read failure to log the path

---

hail/python/hailtop/hailctl/dataproc/describe.py

Currently, there is no way to use `hailctl dataproc describe` on a table in a [requester pays](https://cloud.google.com/storage/docs/requester-pays) bucket. Accessing files in requester pays buckets requires adding a `-u` flag to `gsutil` with the project to bill for operation, network, and data retrieval charges.
https://cloud.google.com/storage/docs/using-requester-pays#using

[hailctl dataproc] Add support for requester pays buckets to hailctl dataproc describe

---

hail/python/hail/expr/types.py
hail/python/test/hail/expr/test_ndarrays.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/types/physical/PArrayBackedContainer.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalArray.scala
hail/src/main/scala/is/hail/types/physical/PContainer.scala
hail/src/test/scala/is/hail/types/physical/PContainerTest.scala

CHANGELOG: Fixed bug where making NDArrays of non-numeric types would fail. Non-numeric ndarrays still cannot be collected to python though. 
NDArrays of non numeric types are broken, have been for a while. No one seems to use them for that currently, so it hasn't been an issue, but I suspect with `dndarray` or BlockedMatrixTable experiments it's going to be desirable. 
This PR starts to address that problem by doing the following:
1. `checkedConvertFrom`, which only supported primitive arrays, is replaced with the more flexible `copyFromType`. As this was the only use of `checkedConvertFrom`, I removed it altogether. 
2. Add tests that show that it's now possible to make an ndarray of non-numeric types, so long as the only things that get returned in python are numbers.
The remaining …

[query] Fix NDArrays of Non-numerics: Part 1

---

hail/src/main/scala/is/hail/lir/Emit.scala

This is a simple refactoring of `lir.Emit` to directly use the core visitor based interface of ASM, rather than the higher level `tree` interface. This should have a small performance benefit, as we aren't building the in-memory tree representation only to immediately walk it with a visitor. But I also find this version of `Emit` slightly cleaner.
For reference, you can find the documentation for ASM 5.1 [here](https://javadoc.io/doc/org.ow2.asm/asm/5.1/index.html).

[query/lir] Don’t use asm.tree in lir.Emit

---

batch/batch/driver/instance_pool.py

I got an email saying the activity logs are no longer supported after September 30th. Here's the [migration instructions](https://cloud.google.com/compute/docs/logging/migrating-from-activity-logs-to-audit-logs#log_entry_field_mappings).
I figured out how to map the fields mostly by trial and error looking at the JSON for an event. The only thing that didn't map at all was the operationType. I hardcoded that as 'insert'.
There are different event_subtype names such as 'v1.compute.instances.insert' or 'beta.compute.instances.insert'. So I did what they suggested and looked for a partial match such as 'compute.instances.insert'.
I can send you the full JSON for the events if you want to double check anything.
I also double checked that the activity logs aren't used anywhere else in the …

[batch] convert activity logs to audit logs

---

hail/python/hail/ir/matrix_writer.py
hail/python/hail/methods/impex.py
hail/python/test/hail/methods/test_impex.py
hail/python/test/hail/test_ir.py
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/io/compress/BGZipLineReader.scala
hail/src/main/scala/is/hail/io/compress/BGzipLineReader.scala
hail/src/main/scala/is/hail/io/tabix/TabixReader.scala
hail/src/main/scala/is/hail/io/vcf/ExportVCF.scala
hail/src/test/scala/is/hail/io/TabixSuite.scala

Adds the long requested feature for tabix creation support to export_vcf.
This represents an 80% solution due to the requirement that the file already exist in order to write the index. Leans entirely on htsjdk for index creation.
There is a limitation where index writing is only supported for the export type of `CONCATENATED`, but this should be easy to add to.
CHANGELOG : Teach tabix writing to `export_vcf`, experimental.

[query] Quick and dirty tabix creation/writing for export_vcf

---

.gitignore

We generate these a lot as intermediates when we manually build service images. I think it should be pretty safe to ignore all of these, since I don't know of anything we need to check in with that extension.

[git][services, mostly] add *.out files to gitignore

---

hail/python/hailtop/hailctl/dev/deploy/cli.py

Allow --steps/-s to be supplied multiple times and with multiple
arguments. It still handles comma separated lists to preserve the old
behavior.

[hailctl dev] Teach dev deploy better handling of steps argument

---

batch/sql/create-billing-projects.sql
batch/test/test_batch.py
build.yaml
hail/python/hailtop/hailctl/dev/cli.py
hail/python/hailtop/hailctl/dev/query/__init__.py
hail/python/hailtop/hailctl/dev/query/cli.py
hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
query/query/query.py
query/test/test_query.py

I wanted a quick way to set global feature flags on the service backend. Also took the opportunity to move query tests into their own file.

[query] add hailctl function to set global flags

---

hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/types/physical/PCode.scala
hail/src/test/scala/is/hail/expr/ir/EncodedLiteralSuite.scala

Introduces `EncodedLiteral`, a literal that is stored as an `EType` encoded array of bytes. 
I did this with the intention of making PCA faster, but so far this seems to take roughly the same amount of time. Currently this is only used by `_blanczos_pca`, since that's the only code using `IR._persist`

[query] Add EncodedLiteral node to avoid java serialization

---

hail/Makefile
hail/python/hail/__init__.py
hail/python/hail/backend/spark_backend.py

Spark 3 resolved the issues with library changes python 3.8, so we can
now use python 3.8 as long as pyspark is version 3 or greater.
I also took this opertunity to make every link in or welcome doc message
a canonical https link that will be recognized as such by many parsers
such as sufficiently advanced terminal emulators.

[query] Expand Python version compatibility with spark 3

---

hail/src/main/scala/is/hail/types/encoded/EArray.scala
hail/src/main/scala/is/hail/types/encoded/EBaseStruct.scala
hail/src/main/scala/is/hail/types/encoded/EBinary.scala
hail/src/main/scala/is/hail/types/encoded/EBlockMatrixNDArray.scala
hail/src/main/scala/is/hail/types/encoded/EBoolean.scala
hail/src/main/scala/is/hail/types/encoded/EFloat32.scala
hail/src/main/scala/is/hail/types/encoded/EFloat64.scala
hail/src/main/scala/is/hail/types/encoded/EInt32.scala
hail/src/main/scala/is/hail/types/encoded/EInt64.scala
hail/src/main/scala/is/hail/types/encoded/ENDArrayColumnMajor.scala
hail/src/main/scala/is/hail/types/encoded/EPackedIntArray.scala
hail/src/main/scala/is/hail/types/encoded/ETransposedArrayOfStructs.scala
hail/src/main/scala/is/hail/types/encoded/EType.scala

One exception is ETransposedArrayOfStructs, where I take the copout of `val mb = cb.ecb` at the top of the function.

[query] Port etype decoders to CodeBuilder

---

ci/ci/build.py
ci/create_database.py

Save it to a variable and pass it to standard input using a heredoc
instead of a gnarly command line argument.  This still outputs the
config to the logs/job output since the variable assignment expression
will be printed with `set -x`.

[ci] Pretty print create_database.py json config

---

hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
hail/src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala

This function used `defaultValue`, which is going away as it requires `typeToTypeInfo` (which is also going away)

[query] port firstMatchIn to IEmitCode

---

hail/python/hailtop/batch/batch_pool_executor.py
hail/python/test/hailtop/batch/test_batch_pool_executor.py

CHANGELOG: BatchPoolExecutor now raises an informative error message for a variety of "system" errors, such as missing container images.
If the main container fails for reasons beyond BatchPoolExecutor's control, such
as a missing container image, we previously did not report these errors. In
fact, we encountered errors when trying to load the output file that cannot
exist if the main container errors.
Smaller included changes:
- directly use the asynchronous, low-level client instead of the synchronous,
low-level client
- introduce an `async_cancel` now that we have access to the async client.

[batch] Teach BatchPoolExecutor how to handle container errors

---

build.yaml

We want to eventually run all of our tests with the checked memory allocator, plus a few representative tests with the regular allocator. This PR switches the Java tests to the checked memory allocator, while the python tests remain on the normal allocator. I'll follow up to deal with the Python tests, but wanted to get a start in here to at least make sure some CI tests are exercising each allocator.

Run hail Java tests with checked memory allocator

---

build.yaml
hail/python/dev-requirements.txt

See discussion in Zulip: https://hail.zulipchat.com/#narrow/stream/127527-team/topic/ci/near/212305447
The nbconvert package changed how template extensions work. It is possible
this broke nbsphinx.

[hail] maybe fix nbsphinx/nbconvert issues

---

hail/build.gradle

- Remove all the deprecated tasks
- Re-add -Xlint:-unused, but only for scala 2.12

[query] Clean up build.gradle

---

hail/python/hailtop/hailctl/batch/list_batches.py

Summary: hailctl batch list --help
```
usage: hailctl batch list [-h] [--query QUERY] [--limit LIMIT] [--all] [--before BEFORE] [--full] [--no-header] [-o O]
List batches
optional arguments:
-h, --help            show this help message and exit
--query QUERY, -q QUERY
see docs at https://batch.hail.is/batches
--limit LIMIT, -l LIMIT
number of batches to return (default 50)
--all, -a             list all batches (overrides --limit)
--before BEFORE       start listing before supplied id
--full                when output is tabular, print more information
--no-header           do not print a table header
-o O                  specify output format (json, yaml, csv, tsv, or any tabulate format)
```
Details:
* Default listing to a limit of 50 records, once batch statuses are
cached from …

[hailctl batch] Teach batch list verbosity, limits, and formatting

---

build.yaml
hail/Makefile

The semantics of setting a variable in make are kinda weird, example:
```make
FOO := foo
BAR ?= bar
.PHONY: echo
echo:
echo $(FOO) $(BAR)
```
```sh
$ FOO=baz make
echo foo bar
foo bar
$ make FOO=baz
echo baz bar
baz bar
$ BAR=baz make
echo foo baz
foo baz
```
This will fix an issue where ci wasn't actually building with spark 3.

Use ?= in make variables for spark and scala versions

---

hail/python/hail/methods/family_methods.py
hail/python/test/hail/methods/test_statgen.py

Also take the opportunity to implement the check on pop_frequency_prior
in accordance with our years-old comment.

[query] Add `ignore_in_sample_allele_frequency` flag to `hl.de_novo`

---

build.yaml

The --export flag on `kubectl get` is deprecated. I've removed the flag and added the filter manually in the jq step to pull out only the necessary info to create the secret wherever we use it in build.yaml.

[build] rewrite kubectl secret copying to avoid deprecated --export flag

---

hail/python/hailtop/batch_client/aioclient.py
hail/python/hailtop/batch_client/client.py

This will avoid extra requests especially since most batches statuses
will not change (most batches are finished).
The new function last_known_status() will make an HTTP request if and
only if the saved status is None.

 [hailctl batch client] Add ability to cache batch status.

---

hail/Makefile

#9500 didn't update the `hail/hail` makefile

[benchmark] fix missed HAIL_VERSION rename in makefile

---

hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala

Summing ndarrays should use tree aggregation strategy, as they can be big. They will be big in things like blanczos PCA.

NDArraySum should TreeAggregate

---

hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/lir/Pretty.scala
hail/src/main/scala/is/hail/lir/X.scala

This PR is a step towards a general picture for generating debugging information in bytecode. The general picture is to write a sequence of files, each corresponding to a certain point in the compile pipeline, where each line in each file includes a line number pointing to the line in the previous file from which this line was derived. (We may eventually want richer source information than just a single line number, like a range or list of ranges.) The top of each file has the file name of the previous printout, which is the target of all line numbers in the file. We could in the future also print a list of transformations that were applied to get from the previous printed state to this one.
The idea to implement this picture is simple. Each IR node stores a line number in a mutable …

[query/lir] Print emitted lir, embed line refs in bytecode

---

batch/batch/worker/worker.py

This PR fixes the double copying of input and output files. This was due to missing parentheses in the shell command for copying.

[batch] Get rid of double copying in io

---

hail/python/hail/docs/_static/annotationdb/annotationdb.js
hail/python/hail/docs/annotation_database_ui.rst
hail/python/hail/experimental/datasets.json
hail/python/hail/experimental/db.py
hail/python/test/hail/experimental/test_annotation_db.py
hail/scripts/deploy.sh

Changes to make sure that only the annotation datasets are visible on the docs page, now that the `datasets.json` config file contains all available datasets.
Overview:
- In `datasets.json`, moved "key_properties" inside an "annotation_db" field, like `"annotation_db":  {"key_properties":  []}`, so that only the datasets with the "annotation_db" key are shown in the annotation DB docs page. Removed "key_properties" from non-annotation datasets.
- Minor reformatting changes to docs page, added a reference genome column to the HTML table.
- Updated deploy script to reflect the filename change from `annotation_db.json` to `datasets.json`.
- Modified checks for keys in dicts from `assert key in doc, doc` to `assert key in doc` in `DatasetVersion.from_json()` and …

[annotationdb] update annotation db docs page for deploy

---

hail/python/hail/backend/service_backend.py
hail/python/hailtop/utils/utils.py
query/test/test_query.py

If query has to pull its image fresh each job takes ~2 minutes. I also fixed some
whitespace issues in the tests and a little bug in `retry_response_returning_functions`.

[query] use a 10 minute timeout

---

build.yaml
hail/python/test/hail/experimental/test_experimental.py
hail/python/test/hail/methods/test_king.py
hail/python/test/hail/methods/test_statgen.py

This PR:
- Switches all python tests to run in debug mode on the checked allocator.
- Adds a pytest mark, `unchecked_allocator`. Anything with this mark will be rerun with the unchecked allocator as a way of testing the unchecked allocator

[query] Hail Python Tests Should Use Checked Memory Allocator

---

benchmark/python/benchmark_hail/run/cli.py
benchmark/python/benchmark_hail/run/utils.py

Add async-profiler support to hail-bench.
Add options:
* `--profile` (`-p`). Can be `-p cpu` or `-p alloc`; `-p` alone defaults to `cpu`.
* `--prof-fmt` (`-f`). Can be `-f html`, `-f flame`, or `-f jfr`. If not specified, defaults to `html`. `html` writes a collapsible tree as you would see in a profiler gui. `flame` writes an svg format flame graph. `jfr` writes a Java Flight Recorder format file which can be read by Java Mission Control or the integrated IntelliJ profiler.
Uses [async-profiler](https://github.com/jvm-profiling-tools/async-profiler), which must be installed at the path `$ASYNC_PROFILER_HOME`. It attaches to the spark JVM using the JVMTI argument interface. The JVMTI async-profiler arguments are described [here](https://github.com/jvm-profiling-tools/async-profiler/blob/v1 …

[benchmark] add profiler options to hail-bench

---

batch/test/conftest.py
build.yaml

This is for @catoverdrive and I to be able to manipulate billing projects and their limits in tests. But we don't want to litter the default namespace with a bunch of bogus projects. We also need to reset the accrued costs to 0 in order for the billing limit tests to work.
@danking -- FYI

[batch] Add infrastructure for not running batch tests in production

---

hail/python/test/hail/matrixtable/test_matrix_table.py
hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/asm4s/Code.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/io/index/MaybeIndexedReadZippedIterator.scala
hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala

11 new tests passing.
Can briefly walk you through the change in 1:1.

[query] Add lowered execution path for `hl.read_matrix_table`

---

auth/Makefile
batch/Makefile
build.yaml
check-sql.sh
ci/Makefile
monitoring/Makefile
notebook/Makefile

SQL migrations are not permitted to be modified. Unfortunately, our tests
previously did not verify this at all. Indeed, a PR merged which modified a SQL
file. This PR caused main to fail a deploy.
This change verifies that no SQL migration is mutated in the source SHA relative
to the target SHA. One can also use it locally by running `make
check-services` from the root. Unfortunately, it does not work properly when run
on the main branch because there is no obvious point of comparison.
I considered comparing against the previous commit, but that might cause
failures if we have to manually fix something in batch. As such, I prefer a
non-deploy only test.

[batch][auth][ci][monitoring][notebook] check for sql mutation

---

hail/python/hail/backend/local_backend.py
hail/python/hail/backend/py4j_backend.py
hail/python/hail/backend/spark_backend.py
hail/python/test/hail/expr/test_expr.py
hail/python/test/hail/expr/test_ndarrays.py
hail/python/test/hail/linalg/test_linalg.py

This PR updates the LocalBackend to match the behavior of the SparkBackend w.r.t. error handling. 
- `handle_java_exception` and `execute` are lifted into the parent file, `Py4JBackend`. 
- Tests in `test_ndarrays` that were marked as failing local tests are now passing, since the only failure was inconsistent handling of errors. 
The error handling changes in question here were introduced in #9398

LocalBackend Better Errors

---

hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/Param.scala
hail/src/main/scala/is/hail/expr/ir/agg/TakeByAggregator.scala
hail/src/main/scala/is/hail/expr/ir/package.scala
hail/src/main/scala/is/hail/types/physical/PType.scala

Remove implicit conversion from ptype to EmitParamType, adding asParam
and asEmitParam to PType for explicit conversion.
Currently PCodeParams are implemented pretty poorly as we should really
be creating the proper PValue from the parameters. This will require
either expanding nCodes for PCode or automatically memoizing the value
when getPCodeParam is called.
This is left for a future PR.

[query] Add PCodeParam and PCodeParamType

---

hail/python/hail/__init__.py
hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala

- Expose init_local.
- Fix formatting of some error messages (stray }).
- Fix index paths, they don't have a "parts" component, have ".idx" suffix.  This showed up as an issue interopreating between Spark and local modes.
FYI @tpoterba rather than just testing them independently, it might be worthwhile to have write/read interop tests between the various backends.  Spark to local is partially tested by the pre-existing (matrix)tables tests, but not the other way.

[hail] minor fixes

---

hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

`isSupertype` on a `TTuple` and a `TStruct` should behave identically.

Fix isSupertype for Tuples

---

hail/python/test/hail/helpers.py
hail/python/test/hail/table/test_table.py
hail/src/main/scala/is/hail/HailContext.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/RVDToTableStage.scala
hail/src/main/scala/is/hail/io/CodecSpec.scala
hail/src/main/scala/is/hail/io/TypedCodecSpec.scala
hail/src/main/scala/is/hail/rvd/RVD.scala
hail/src/main/scala/is/hail/types/physical/PCode.scala
hail/src/main/scala/is/hail/types/physical/PPrimitive.scala

Currently tested with TableLiteral on the Spark backend.

[query] RVD to table stage infrastructure

---

hail/python/hailtop/auth/auth.py
hail/python/hailtop/auth/tokens.py
hail/python/hailtop/batch_client/aioclient.py

I need to be able to load tokens for multiple users for #9553 and would like to pipe it through the auth utilities in a reasonable way so I can use them. Let me know if this looks ok or if there's a better way to do it?

[hailtop-auth] allow tokens to be loaded from user-specified file

---

hail/python/hail/docs/_static/annotationdb/annotationdb.js
hail/python/hail/experimental/datasets.json
hail/python/hail/experimental/datasets.py
hail/python/hail/experimental/db.py
hail/python/test/hail/experimental/test_annotation_db.py

This allows the user to specify the cloud platform ('gcp' or 'aws') they are using when accessing datasets via the datasets API and annotation DB. A user running hail on AWS would read from the s3 bucket, and a user running on GCP would read from the gs bucket (can also still read locally from gs bucket with cloud storage connector installed). Not intended for cross-platform use like running a dataproc cluster and trying to access the s3 bucket, or trying to access the gs bucket on an EMR cluster. Will assume user on AWS has their configuration set with their credentials. 
Did not have permissions to set up a cluster or EC2 instance on AWS to test, but was able to access all the datasets without issue on a dataproc cluster when using s3a:// prefixes and providing my AWS credentials in the …

[datasets][annotationdb] specify cloud storage platform (gcp or aws)

---

hail/python/hailtop/hailctl/dataproc/modify.py

Currently, the `hailctl dataproc modify` does not print the first (after the cluster name) argument to `gcloud dataproc clusters update`. This bug was introduced in [#9078](https://github.com/hail-is/hail/pull/9078/files#diff-498f7c9ef8feab597e2213c7cbf2ca3d7f11c2f2427eea44850156ffc4c44fb0L54-R51).
For example:
```
$ hailctl dataproc modify some-cluster --num-workers 2 --dry-run
gcloud dataproc clusters update some-cluster \
```
With this change, the `--num-workers` argument is printed.
```
$ hailctl dataproc modify some-cluster --num-workers 2 --dry-run
gcloud dataproc clusters update some-cluster \
--num-workers=2
```

[hailctl dataproc] Print all gcloud args in hailctl dataproc modify

---

hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala

Use eltRegion instead of partitionRegion.

[query] Fix memory management for partition readers

---

hail/python/test/hail/methods/test_misc.py
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala

The `Consume` was getting optimized away in (StreamLen(StreamMap ...))

[query] Fix `TableForceCount` lowering.

---

hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
hail/src/main/scala/is/hail/expr/ir/ExecuteContext.scala
hail/src/main/scala/is/hail/services/shuffler/ShuffleClient.scala
hail/src/main/scala/is/hail/services/shuffler/server/ShuffleServer.scala
hail/src/main/scala/is/hail/utils/ExecutionTimer.scala
hail/src/test/scala/is/hail/HailSuite.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

FYI @tpoterba 
Rework `ExecutionTimer` with two goals in mind:
Report total time, children time, self time (total - children) and % in children for each timed section.  I think this improves clarity of reporting vs the old format.  The timing log lines now look like:
```
2020-10-20 12:10:38 root: INFO: timing SparkBackend.executeJSON total 43.597ms self 0.941ms children 42.655ms %children 97.84%
```
Decouple the timer from the execution context so we can time more than just the execution.  In particular, I want timings starting from entering the JVM from Python (and in fact, I plan to write an ExecutionTimer in Python so we can time e.g. a call to Backend.execute and include timings from the JVM, but also printing the IR, unserializing the response, etc.)

[hail] update execution timer

---

.dockerignore

Without the ** it seems to not ignore any mypy_cache. This results in extraordinarily slow local builds.

[docker] ignore mypy_cache everywhere

---

hail/src/main/scala/is/hail/expr/ir/Pretty.scala

The IRParser expects its join type to be printed.

MatrixUnionCols needs to include its join type in Pretty printing

---

address/address/address.py
auth/auth/driver/driver.py
batch/batch/driver/instance_pool.py
batch/batch/driver/main.py
batch/batch/driver/scheduler.py
batch/batch/front_end/front_end.py
batch/batch/worker/worker.py
benchmark-service/benchmark/benchmark.py
ci/ci/ci.py
hail/python/hailtop/aiotools/__init__.py
hail/python/hailtop/aiotools/tasks.py
hail/python/hailtop/cleanup_gcr/__main__.py
hail/python/hailtop/utils/utils.py
memory/memory/memory.py
monitoring/monitoring/monitoring.py
scorecard/scorecard/scorecard.py
web_common/Makefile

`asyncio.ensure_future` creates background tasks. When a service is shutdown by
kubernetes, these background tasks keep the service up for the full 30 second
grace-period. This impedes development and deployment velocity.
This change eliminates all uses of `asyncio.ensure_future` which ignore the
returned future. Instead, all these futures are managed by a
`aiotools.BackgroundTaskManager`. This is a new class which holds a (weak)
reference to all of its created tasks and provides `shutdown` to cancel all the
tasks. Canceling the tasks ensures a speedy shutdown.
The use of a weak reference is critical to enable the garbage collector to clean
up tasks that have completed successfully. In particular, the batch worker
creates short-lived, background tasks.
cc: @catoverdrive @Dania-Abuhijleh

[services] pervasively gracefully shutdown

---

hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

`SelectFields(child, fields)` needs to make sure that even if `fields` doesn't match the order present in `child.typ`, it still requests the fields in the order from `child.typ`. Otherwise, we break the invariant that `requestedType` is always a super type of the full IR type.

[query] SelectFields Memoization Fix

---

gear/gear/database.py
pylintrc
setup.cfg

The old code in `Transaction` to exit the transaction and release the connection back to the pool looked like this:
```
async def _aexit(self, exc_type, exc_val, exc_tb):
try:
if self.conn is not None:
try:
if exc_type:
await self.conn.rollback()
else:
await self.conn.commit()
finally:
self.conn = None
finally:
if self.conn_context_manager is not None:
try:
await aexit(self.conn_context_manager, exc_type, exc_val, exc_tb)
finally:
self.conn_context_manager = None
```
The problem was if the current coroutine was cancelled in the call to `aexit(self.conn_context_manager, ...)`, which ultimately calls aiomysql `Pool.release`, the release never happens.  This was happening when database calls in `@only_active_instances` were getting cancelled when the client timed out and terminated the …

[gear] fix db connection leak in transaction due to cancellation

---

check-sql.sh

This sends a literal tab character to grep, taking advantage of Bash ANSI-C style quoting (see https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_03.html)

[check-sql] fix check-sql

---

hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

`MatrixUnionCols` didn't have a rebuild rule, which was wrong because we need it to ensure that the left and right column and entry types continue to match. It also didn't have a `TypeCheck` rule, so I made one based on the rules outlined in the hail docs for `union_cols`.

[query] MatrixUnionCols Rebuild Rule and TypeCheck

---

hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

I added a test to demonstrate the problem. The `InsertFields` is overwriting the type of a field that is not part of the requested type. Previously we would just not insert anything and leave the rebuilt child alone. But when the child is a `Ref` or a `Literal` or something that doesn't actually get rebuilt differently, the old way would lead to a situation where the rebuilt IR is not a supertype of the original IR. By inserting a `SelectFields` to subset away the fields that would have been overwritten, we avoid this problem. 
Happy to further elaborate if the above isn't clear.

[query] Fix InsertFields rebuild rule when overwriting field with same name but different type

---

batch/batch/exceptions.py
batch/batch/front_end/front_end.py
batch/test/test_accounts.py
batch/test/test_batch.py
build.yaml
hail/python/hailtop/auth/tokens.py
hail/python/hailtop/batch_client/aioclient.py

add endpoints for creating/deleting billing projects and adding/removing users from billing projects to let us add batch users with billing projects for tests without having to trigger a migration. This will make testing user isolation easier.
I create a new file to test account-related things; all the deletions from test_batch were moved over to that test file.
Stacked on #9579, #9585.

[batch] add api for managing billing projects

---

hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala

This assertion was getting triggered by the ref `inner` in a perfectly correct IR of the form `StreamMap(inner, StreamGrouped(...), ...)`. There's no way to avoid the unrealizable ref when mapping over a nested stream, and I don't see why `extract` depends on this assertion.

[query] allow unrealizable ref in extract

---

hail/python/hailtop/hailctl/dataproc/describe.py

`hailctl dataproc describe` does not currently display point types for interval fields.
For example, with this table:
```
ds = hl.utils.range_table(10)
ds = ds.annotate(interval=hl.parse_locus_interval(hl.str(ds.idx + 1) + ":1-100"))
ds.write("test.ht")
```
```
$ hailctl dataproc describe test.ht
...
----------------------------------------
Row fields:
'idx': int32
'interval': interval<>
----------------------------------------
...
```
With this change,
```
$ hailctl dataproc describe test.ht
...
----------------------------------------
Row fields:
'idx': int32
'interval': interval<locus<grch37>>
----------------------------------------
...
```

[hailctl dataproc] Support interval fields in hailctl dataproc describe

---

hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/types/virtual/TStruct.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

When you have `TableAggregateByKey(child, expr)`, you cannot assume that the keys of the result are present in `expr`, so the memoization rule has to be changed to request only the subset of fields in the requested type that are present in `expr`. 
One of the bugs found during #9578

[query] TableAggregateByKey Memoization Fix

---

hail/python/hail/expr/types.py
hail/src/main/scala/is/hail/annotations/RegionValueBuilder.scala
hail/src/main/scala/is/hail/annotations/UnsafeRow.scala
hail/src/main/scala/is/hail/types/TypeWithRequiredness.scala
hail/src/main/scala/is/hail/types/virtual/TNDArray.scala
hail/src/test/scala/is/hail/expr/ir/ETypeSuite.scala
hail/src/test/scala/is/hail/types/physical/PNDArraySuite.scala

Fixes #9640
CHANGELOG: Fixed bug where show output for ndarrays was not correct
`TNDArray` shouldn't store strides on it. It only existed because of the old world where `PTypes` weren't fully fleshed out. Especially since `strides` is a series of offsets in bytes, and at the virtual type level we have no idea what elements of the ndarray will actually be. 
The way I've fixed this for now is by making all incoming ndarray literals row major and all Java `Row` representation style things use `UnsafeIndexedSeqRowMajorView` to make them indexable in arow major way. I mostly just did this since row by row is the way you'd want to display data for `show`. My eventual plan is reorganize the ndarray emitter so we know that all ndarrays are being emitted column major all the time, and then we …

[query] TNDArray shouldn't store `strides`, fix `show`

---

hail/python/hail/methods/statgen.py
hail/python/test/hail/methods/test_statgen.py

Replacing #9578 
_linear_regression_rows_nd now supports chained linear regression correctly. Also added support for pass through arguments. This should now support everything that regular linear regression supports, but all written in Python. This allows a few more tests to run on local backend.
I'd be particularly interested in whether you think there's a way to write this that would generate more efficient IR. It seems hacky to have to map over the range of rows and index into it, but I didn't see a better way.

Python Chained Linear Regression, Attempt 2

---

hail/src/main/scala/is/hail/types/physical/PType.scala

No one was using it, it just adds a potential footgun when making new ptypes
Assigning Tim on the off chance it conflicts with his STypes PR, it's a tiny change though so hopefully fine.

PType shouldn't have default bytesize

---

benchmark/python/benchmark_hail/run/cli.py

Without this change, it just sticks `"None"` in the url it generates, then says it couldn't find the `.so` it's looking for.

Throw a good error message if ASYNC_PROFILER_HOME isn't set

---

auth/auth/auth.py
auth/auth/driver/driver.py
auth/auth/templates/users.html
hail/python/hailtop/utils/utils.py

I can generate the new auth-driver service account by hand, but this will be much better. Am I missing anything or is it this easy?

[auth] Add ability to easily create new service accounts

---

hail/python/hailtop/batch/__init__.py
hail/python/hailtop/batch/backend.py

I'm not sure why we had the default be ubuntu:latest but I think 18.04 is better.

[batch] Add warnings for non-gcr images

---

hail/src/main/scala/is/hail/io/InputBuffers.scala
hail/src/main/scala/is/hail/utils/richUtils/RichInputStream.scala

The documentation for [`InputStream.read(byte[], int, int)`](https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#read-byte:A-int-int-) explicitly notes:
> Reads up to len bytes of data from the input stream into an array of
> bytes. An attempt is made to read as many as len bytes, but a smaller
> number may be read.
Therefore, our `InputBuffer` methods must not assume `read` returns the requested number of bytes. Moreover, `readFully` should not assume that a read of zero bytes indicates end of stream. End of stream is only indicated by a `-1`.

[hail] fix bugs in InputBuffers and RichInputStream

---

hail/python/hail/methods/statgen.py

I have no idea why we were skipping this test, but it was not a good idea to skip it, as the example was incorrect. We can't use `**split_ds.info` because that will contain `AC`, and so we will be trying to make a struct with two fields called `AC`. 
I also replaced `vds` with `mt`, which we should do pervasively everywhere at some point.

split_multi_hts doctest fix

---

batch/Dockerfile.worker
blog/Dockerfile.nginx
build.yaml
ci/Dockerfile.ci-utils
docker/Dockerfile.base
docker/Dockerfile.service-base
docker/Makefile
docker/genetics/Dockerfile
docker/hail-ubuntu/Dockerfile
docker/hail-ubuntu/hail-apt-get-install
docker/hail/Dockerfile
echo/Dockerfile
gateway/Dockerfile
hail/Dockerfile.hail-build
hail/Dockerfile.hail-pip-installed-python36
hail/Dockerfile.hail-pip-installed-python37
hail/Dockerfile.hail-repl
hail/Dockerfile.hail-run
internal-gateway/Dockerfile
letsencrypt/Dockerfile
router/Dockerfile
site/Dockerfile
site/Makefile
tls/Dockerfile

This PR is stacked on #9593. The key files to look at are in `docker/hail-ubuntu`. I introduced `hail-apt-get-install` which packages up the `apt-get update` and the removal of temporary files. I also set the number of package-download retries to 5.

[docker] Teach Hail Ubuntu Image how to resiliently install apt packages

---

hail/python/hail/experimental/import_gtf.py

GENCODE GTF files have contigs "chr1", "chr2", ... , "chrX", "chrY", "chrM". Currently, when `reference_genome` is set to GRCh37, `import_gtf` removes the "chr" prefix. This works for chromosomes 1-22, X, and Y.
However, for the mitochondrial contig, Hail expects "MT" instead of "M" and attempting to do anything with the imported table results in an error: `HailException: Invalid interval '[...]' found. Contig 'M' is not in the reference genome 'GRCh37'.`
With this change, `import_gtf` recodes "M" and "chrM" as "MT" so that the intervals are valid for GRCh37.

Support GRCh37 MT contig in import_gtf

---

benchmark/python/benchmark_hail/run/methods_benchmarks.py
hail/python/hail/expr/functions.py
hail/python/hail/methods/statgen.py
hail/python/hail/nd/nd.py

#9634 Introduced a large performance regression in the `linear_regression_rows_nd` benchmark (making it about 4x slower). This PR fixes that by doing two things:
1. Move all the global into one single `annotate_globals` expression, so that CSE can work properly. This required fixing a bug in some ndarray expressions that were not correctly tracking their source tables. To make sure I was only referencing the global versions of this computed things, rather accidentally recomputing, I wrapped the global setup in a function to scope the variables. This improvement was minor, didn't hit the real root of the problem.
2. Much more significantly, and not 100% clear why: `process_y_group` is now a function that returns a python dictionary, instead of a hail struct. I can guess that the allocation …

Linear Regression ND Performance Fix

---

Makefile
atgu/Dockerfile
atgu/MANIFEST.in
atgu/Makefile
atgu/atgu/__main__.py
atgu/atgu/atgu.py
atgu/atgu/templates/create_resource.html
atgu/atgu/templates/edit_resource.html
atgu/atgu/templates/layout.html
atgu/atgu/templates/resource.html
atgu/atgu/templates/resources.html
atgu/deployment.yaml
atgu/setup.py
atgu/sql/delete-atgu-tables.sql
atgu/sql/estimated-current.sql
atgu/sql/initial.sql
build.yaml
letsencrypt/domains.txt
router/deployment.yaml
router/router.nginx.conf.in
tls/config.yaml

This is the initial version of the ATGU intranet service. Currently, it has a curated list of resources which can be created, viewed, edited and deleted.  Resources can have attachments, which I store on Google storage.  I used the async Google Storage client and it worked very nicely with aiohttp.
Right now this developers only.  I may give access to the admins to start curating resources.  I'll follow up with roles and add roles for atgu-viewer and atgu-editor that I'll use in the service.
I think the code is mostly straightforward, but a few remarks:
This is built on Bootstrap.  It doesn't share the the styling with web common (which I probably want to convert).
On the resources page, for client side search I use fuse.js: https://fusejs.io/ (so fast)
For a rich text box (the resource …

[atgu] add initial version of ATGU intranet service

---

atgu/atgu/templates/create_resource.html
atgu/atgu/templates/edit_resource.html
atgu/atgu/templates/resource.html
atgu/atgu/templates/resources.html

base_path is empty in production.  href="" refers to the current page,
not the root page.  So always include a trailing slash when using
base_path in the HTML templates.
Also, note, / and /resources are currently the same, but won't be once there are other components besides resources.

[atgu] fix breadcrumb href targets

---

batch/test/test_accounts.py
gear/gear/auth_utils.py
hail/python/hailtop/auth/__init__.py
hail/python/hailtop/auth/tokens.py

We now have two functions which convert back and forth between the two
representations of session ids: `bytearray` and `str`.

[auth][gear] functions to work with session ids

---

hail/python/hail/docs/datasets/schemas/gnomad_hgdp_1kg_callset.rst
hail/python/hail/experimental/datasets.json

Updated the paths in `datasets.json` for `gnomad_exome_sites` and `gnomad_genome_sites` to use the `gs://gcp-public-data--gnomad` bucket. 
Added the Hail Table for version 3.1 of genome sites to `datasets.json`, as well as the gnomad HGDP + 1KG callset MatrixTable.

[datasets] add gnomad public datasets

---

hail/src/main/scala/is/hail/types/physical/stypes/SNDArray.scala

I detect no performance difference on blanczos running the benchmark
locally. This pattern appears a lot in the NDArrayEmitter, though,
so we should fix it everywhere and see what happens!

[query Start undoing value misuse related to ndarrays

---

gateway/Dockerfile
gateway/gateway.nginx.conf
gateway/nginx.conf

Previously, we used the default nginx.conf included by Ubuntu. This
changes us to use the same explicit settings that are used by the
internal-gateway vis-a-vis TLS.
This change also allows me to add (in a future PR) a TCP forwarding
block needed by the forthcoming Hail TCP Proxy.

[gateway] codify gateway nginx.conf

---

hail/python/hailtop/utils/utils.py

Without the stack trace we do not know who called retry_transient_errors,
which makes it hard to know exactly where we are stuck in an infinite
loop!

[utils] include stack trace in retry-transient-errors log

---

ci/ci/build.py

Since the first build.py we have had two bugs. Dev deploys would regularly
re-deploy the router service in the default namespace. The more recent bug
is that the router port ought to be 443, not 80. Any time we dev deploy,
I suppose we have broken the mainline, but this must have been resolved by
deploys that came shortly thereafter.

[ci] fix two longstanding bugs

---

ci/Makefile

This might explain long build times redeploying CI by hand.

[ci] ci-utils depends on service-base, not base

---

batch/test/test_batch.py
gear/gear/auth.py
hail/python/hailtop/auth/auth.py
hail/python/hailtop/hailctl/auth/user.py
router-resolver/router_resolver/router_resolver.py

I updated every call site to match the new parameters. This refactoring removes some code duplication, changes a stack trace in `hailctl auth user` to a nice print message, and adds a parameter (`client_session`) which I will use in my forthcoming TCP Proxy PR.

[auth] Simplify and unify use of userinfo

---

ci/ci/github.py

We cancel in two cases:
1. A (dev|) deploy failed.
2. A batch was found open but unknown to us.
In the former case, we should delete the batch. The batch contains no extra information
everything we need to know is in the failure message.
In the latter case, an open batch does not cost us anything and
cannot be cancelled anyway, so we choose to ignore them. Such a batch
should only come into existence when CI dies in the middle of submission
which should be quite rare.

[ci] delete open batches rather than cancelling them

---

docker/hail-ubuntu/hail-apt-get-install

Apt-get update does not use the retries parameter used by
apt-get install. In fact, I could not find any retry configuration
for apt-get update. This is a cheap hack that retries 5 times with
exponential back-off.

[hail-ubuntu] retry apt-get update

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/SpecializedArrayBuilders.scala
hail/src/main/scala/is/hail/expr/ir/package.scala

This is in anticipation of a new `EmitVale.get` that returns a `PValue`.

Rename EmitValue.get to EmitValue.load

---

hail/python/test/hail/expr/test_ndarrays.py

If hail and numpy use two different lapack implementations, might not get the same sign on the singular vectors. This PR switches our vector comparison tests to check the absolute values of the matrices, plus make sure they multiply back together properly.

SVD tests should be robust to sign ambiguity

---

hail/python/hail/expr/builders.py
hail/python/test/hail/expr/test_expr.py

CaseBuilder has an `or_error` method to throw an error if no `when` conditions are true. Currently, SwitchBuilder does not have an equivalent method: it only supports returning a default value or missing. The option to throw an error on an unhandled value can be useful for making sure that all possible values for an enum expression have been accounted for in switch cases.

[query] Add or_error method to SwitchBuilder

---

lsm/Makefile

This ensures the object files stick around for debugging purposes

[lsm] fix Makefile

---

hail/src/main/scala/is/hail/linalg/LinalgCodeUtils.scala

There were two bugs when checking if an ndarray is column major, causing it to always return false. This method is used to decide whether we need to copy the ndarray into a column major form. By fixing this bug, we now don't have to copy both arrays before every matrix multiply.
Benchmark: linear_regression_rows_nd
Before fix timings:
[50.794169104999995, 51.562208821, 60.402329871999996]
After fix timings: 
[38.504665161, 39.919831891, 37.882298633999994]

[query] Fix column major test to avoid extra copying

---

hail/python/hail/expr/expressions/base_expression.py
hail/python/test/hail/expr/test_expr.py

Fixes #9750 
The problem was that `bool(hl.struct())` is `False`.

[query] Fix bug with constructing an array of empty structs

---

hail/python/hail/matrixtable.py
hail/python/hail/table.py

Clarified that matrix table distinct methods keep one value per key after a user asked if it deleted all rows that had a key duplicated somewhere or all but one of them.

[query] Clarify matrix table distinct methods

---

batch/batch/driver/instance_pool.py
batch/batch/driver/main.py
batch/batch/driver/zone_monitor.py

This PR is the first towards the goal of supporting arbitrary machine types.
I tested both code paths where we create zones from a static list versus if there's over 4000 cores, creating it with east and west regions as well.
I thought about putting the regions and init_zones in the database, but figured that could be a follow up PR. I wasn't sure what the best way to do that was.

[batch] Refactor zone quotas code into a zone monitor

---

batch/batch/front_end/front_end.py
batch/batch/front_end/templates/job.html
hail/python/hailtop/dictfix.py
hail/python/test/hailtop/test_dictfix.py
web_common/web_common/styles/main.scss

1. Add `dictfix`, a little tool for wrangling json-like data into a sensible,
standardized format.
2. Modify job.html to include a simple table of important parts of the job
specification such as the command and the requests of cpu, memory, and
storage.
3. Modify job.html to include a simple table summarizing the status and runtime
of each step of the job.
My apologies for reformatting the whole file to have no excess spaces. Use the no whitespace diff option in GitHub for a better diff.

[batch] better status information for jobs

---

batch/batch/front_end/front_end.py
batch/test/test_accounts.py
batch/test/test_batch.py
build.yaml
hail/python/hailtop/auth/auth.py

gcloud uses this variable to find the tokens file. We should set it so
that users do not need to configure anything. I also fixed some
missing arguments in the non-async get_userinfo.

[batch] automatically set GOOGLE_APPLICATION_CREDENTIALS

---

ci/ci/build.py

Motivation for this change: I want to keep the global configuration information in one place, and that's going to be the K8s default/global-config secret.  In particular, I want to get rid of config.mk and just pull the relevant information from K8s.  The secret currently like this:
```
$ k get -o json secret global-config | jq '.data | map_values(@base64d)'
{
"default_namespace": "...",
"docker_root_image": "...",
"domain": "...",
"gcp_project": "...",
"gcp_region": "...",
"gcp_zone": "...",
"gsuite_organization": "...",
"internal_ip": "...",
"ip": "...",
"kubernetes_server_url": "..."
}
```
default_namespace will always be the name of the namespace the secret is in.
This adds gsuite_organization which will be used by auth to restrict logins to a fixed GSuite organization, e.g. …

[ci] create global-config in "default" namespaces created by CI

---

batch/batch/batch.py
batch/batch/front_end/front_end.py
batch/batch/front_end/templates/job.html
hail/python/hailtop/dictfix.py

- I am now enforcing that container statuses are None if there is no information
- The duration can be missing even if the timing struct is not (for example, in progress jobs).

[batch] a few fixups of front end jobs page

---

batch/test/test_batch.py

stderr and stdout non-deterministically interleave, breaking the string match in `test_can_use_google_credentials`

[batch] eliminate non-determinism in test

---

hail/python/hail/methods/impex.py
hail/python/test/hail/methods/test_impex.py

gnomAD v3.1 VCFs have many fields containing "-" ("AC-non_neuro-nfe-XX", etc). Someone pointed out that those are invalid in [VCF v4.3](https://samtools.github.io/hts-specs/VCFv4.3.pdf). Item 8 of section 1.6.1 of the specification says:
> INFO keys must match the regular expression ^([A-Za-z ][0-9A-Za-z .]*|1000G)$, please note that “1000G”
is allowed as a special legacy value. 
VCFs created by `hl.export_vcf` are marked as v4.2. However, it may still be useful to warn about these fields as it seems some tools expect the v4.3 pattern (samtools/bcftools#1335).

[query] Warn in export_vcf if info field names are invalid in VCF v4.3

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/types/physical/PNDArray.scala

`strides` shouldn't be a public field on `PNDArray` interface, just an internal detail of `PCanonicalNDArray`. 
`dimensionLength` was just loading the shape, should never have been its own method.
There's a lot more interface clean up to do, these two were just easy

[query] Remove strides and dimensionLength from PNDArray

---

hail/python/hail/expr/expressions/typed_expressions.py
hail/python/test/hail/expr/test_ndarrays.py

I have to do some manual type checking inside the method because I don't know of a way to express full constraints in decorator. If there's a better way I'd love to know it. 
cc @danking

[query] Let NDArrayExpression.reshape take varargs

---

batch/batch/front_end/front_end.py
batch/batch/worker/worker.py
batch/test/test_batch.py

At this point, every job that needs the private network specifies
it (https://github.com/hail-is/hail/pull/9380). This change moves jobs with
unspecified `network` to the private network.
I removed the gce-deploy-config because jobs should not, by default, assume they
are on the private network. The GCE Deploy Config instructs you to enter GKE
using the internal-gateway, which is on our private network.

[batch] change worker to default to the private network

---

hail/python/hailtop/auth/auth.py
hail/python/hailtop/config/deploy_config.py
hail/python/hailtop/hailctl/auth/login.py
hail/python/hailtop/hailctl/curl.py
hail/python/hailtop/hailctl/dev/cli.py
hail/python/hailtop/hailctl/dev/config/cli.py
hail/python/hailtop/hailctl/dev/config/set_property.py
hail/python/hailtop/hailctl/dev/config/show.py
hail/python/test/hailtop/config/test_deploy_config.py
hail/src/main/scala/is/hail/services/DeployConfig.scala

Modify hailctl dev config to let you set the domain.  Note, this is an
interface change since I changed `hailctl dev config` to act like
gcloud/kubectl `... set property value`.
The hardest part of this was getting a doubly-nested subcommand to work in argprase.  The existing code is wack, but I will change everything to work like hailctl dev/dev config does below.

Add domain to the deploy config.

---

hail/python/hail/docs/getting_started_developing.rst

Add a note that commits with user facing changes should include "CHANGELOG" in the commit message (see https://github.com/hail-is/hail/pull/9749#pullrequestreview-541110277).
Also adds a link to the development forum as in the readme (https://github.com/hail-is/hail#contribute).

Update contributing guidelines

---

benchmark/python/benchmark_hail/run/linalg_benchmarks.py

There was a typo in the term `mean_impute`. I assume this benchmark has never actually worked, so it's troubling we haven't ever noticed it was broken for such a silly reason.

Fix blockmatrix_write_from_entry_expr_range_mt_standardize benchmark

---

hail/python/hailtop/config/deploy_config.py
letsencrypt/domains.txt
router/router.nginx.conf.in
web_common/web_common/templates/header.html
web_common/web_common/web_common.py

The slight subtly was that the internal URL (internal.hail.is/namespace/service) requires a service, so you can't link to "hail.is".  I used www instead.

[web_common] fix hardcoded Batch docs URL

---

hail/python/dev-requirements.txt
hail/python/hailtop/aiogoogle/client/storage_client.py
hail/python/hailtop/aiotools/fs.py
hail/python/test/hailtop/test_aiogoogle.py

Existence of directories is filesystem dependent, and they exist on Google if there is an object with that directory name a prefix.
This required a little refactoring that changed fs.listfiles to return a coroutine that gives an iterator, rather than returning an iterator directly.  This is because, if you use the `async def foo ... yield ...` syntax, it is not possible to write any code that will run between calling the async genreator function `foo` and the first call to `__anext__`.

[aiotools, aiogoogle] AsyncFS.listfiles raises FileNotFoundError if the directory doesn't exist

---

hail/python/hail/expr/builders.py
hail/python/hail/expr/functions.py

Also fixed examples in `cond` doc to call `cond` instead of `if_else`.

Removed an internal use of cond to avoid deprecation warnings

---

hail/python/hail/methods/relatedness/pc_relate.py
hail/python/test/hail/methods/relatedness/test_pc_relate.py
hail/src/main/scala/is/hail/methods/PCRelate.scala

CHANGELOG: `hl.pc_relate` now includes values on the diagonal of kinship, IBD-0, IBD-1, and IBD-2

[hail] include the diagonal in PCRelate

---

hail/python/hail/utils/placement_tree.py
hail/python/test/hail/utils/test_placement_tree.py

Proposed fix for https://github.com/hail-is/hail/issues/9833
Summary: fix run time error when a matrix table row has an empty struct.
Example: `info` field below is an empty struct
```
----------------------------------------
Global fields:
None
----------------------------------------
Row fields:
'locus': locus<GRCh38> 
'alleles': array<str> 
'rsid': str 
'qual': float64 
'filters': set<str> 
'info': struct {} 
----------------------------------------
Key: ['locus', 'alleles']
----------------------------------------
```
The function `max` will throw this error
```
ValueError: max() arg is an empty sequence
```

[utils] provide default for max in from_named_type()

---

benchmark-service/benchmark/benchmark.py

- Batch returns results in descending order of batch id. I think we want the latest one.
- Let's bump the checking of results to every 10 mins for now.

[benchmark] minor fixups

---

hail/python/hail/expr/functions.py
hail/python/hail/typecheck/__init__.py
hail/python/hail/typecheck/check.py
hail/python/test/hail/expr/test_expr.py

CHANGELOG: `hl.any` and `hl.all` now also support a single collection argument and a varargs of Boolean expressions
Any and all currently take two arguments: a function and a collection. This
differs from the Python `any` and `all` which take only a collection and check
for truthy values.
We rectify this situation by supporting three forms:
1. ``hl.all(boolean, ...)``, are all arguments ``True``?
2. ``hl.all(collection)``, are all elements of the collection ``True``?
3. ``hl.all(function, collection)``, does ``function`` return ``True`` for
all values in this collection?

[hail] Add two new forms to any all

---

pylintrc

These ignores prevent my Emacs from running pylint. I mistakenly added these
here long ago.

[pylintrc] remove some ignores

---

hail/python/hailtop/hail_logging.py

Google considers any message written to stderr as an error.

[services] stop treating all logs as error logs

---

hail/src/main/scala/is/hail/expr/ir/agg/AppendOnlyBTree.scala

This is a series of small refactorings in AppendOnlyBTree that removes
the folds in code generation, replacing a pattern that I find difficult
to follow with a more imperative CodeBuilder style that is necessary for
future changes to proceed as the folding style does not work well with
functions that need code builders.

[query] Remove code generating folds from AppendOnlyBTree

---

hail/python/hail/expr/functions.py
hail/python/test/hail/expr/test_expr.py

Currently, attempting to bit shift by zero bits throws an error.
```
$ hl.eval(hl.bit_rshift(4, 0))
HailUserError: Error summary: HailException: cannot shift by a negative value: 4 >> 0
```

[query] Allow bit shifts by zero bits

---

hail/src/main/scala/is/hail/annotations/Annotation.scala
hail/src/main/scala/is/hail/annotations/RegionValueBuilder.scala
hail/src/main/scala/is/hail/annotations/UnsafeRow.scala
hail/src/main/scala/is/hail/expr/AnnotationImpex.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/types/TypeWithRequiredness.scala
hail/src/main/scala/is/hail/types/encoded/EBaseStruct.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/types/physical/PNDArray.scala
hail/src/main/scala/is/hail/types/virtual/TNDArray.scala
hail/src/test/scala/is/hail/expr/ir/ETypeSuite.scala
hail/src/test/scala/is/hail/types/physical/PNDArraySuite.scala

Part of a refactoring effort. I need to break the model that a `TNDArray` is represented by an underlying `TStruct` and `TArray`. This adds an `UnsafeNDArray` Java representation, rather than the old model which was just to use`UnsafeRow` like it was a struct. 
cc @tpoterba

[query] NDArray Java Representation

---

hail/src/main/scala/is/hail/expr/ir/Simplify.scala

I think there are a lot of situations like this, like `hl.nd.zeros(shape)`, which is implemented as:
`hl.nd.array(hl.range(total_num_elements)).map(lambda x: 0).reshape(shape)`. No reason to actually generate code for reshaping in these situations.

[query] NDArray Reshape Simplification

---

hail/src/main/scala/is/hail/expr/ir/Simplify.scala

Reverts hail-is/hail#9874
This is invalid, doesn't handle the fact that negative ones can be present in the shape. Unless we handle that in python/IR, we can't do this optimization.

Revert "[query] NDArray Reshape Simplification"

---

hail/python/dev-requirements.txt

Jupyter now requires tornado>=6. We added the tornado<6 requirement to prevent previous issues in
which the notebook package did not correctly specify its dependency on tornado<6.

[hail] remove dev requirement due to jupyter changes

---

batch/batch/worker/worker.py
hail/python/hailtop/batch/backend.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

The Artifact Registry is useful to avoid network egress costs for regions like Australia, where GCR doesn't provide local hosting.
Partially addresses #9872.

[batch] pass credentials for both GCR and Artifact Registry images

---

hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SStruct.scala

The subset method is used to construct SSubsetStructCode

[query] Add subset method to SBaseStructCode

---

batch/batch/front_end/front_end.py

Found the problem where EXISTS in a correlated subquery should be rewritten as IN
https://dev.mysql.com/doc/refman/5.7/en/optimizing-subqueries.html
```
-> FROM jobs
-> INNER JOIN batches ON jobs.batch_id = batches.id
-> LEFT JOIN aggregated_job_resources
->   ON jobs.batch_id = aggregated_job_resources.batch_id AND
->      jobs.job_id = aggregated_job_resources.job_id
-> LEFT JOIN resources
->   ON aggregated_job_resources.resource = resources.resource
-> INNER JOIN job_attributes
->   ON jobs.batch_id = job_attributes.batch_id AND
->      jobs.job_id = job_attributes.job_id AND
->      job_attributes.`key` = 'name'
-> WHERE (jobs.batch_id = 14327) AND
-> (jobs.batch_id, jobs.job_id) IN (SELECT batch_id, job_id FROM job_attributes WHERE `key` = 'pheno' AND `value` = '50')
-> GROUP BY …
```

[batch] Fix search queries with attributes

---

gear/setup.py
hail/python/setup-hailtop.py
web_common/setup.py

Without this empty file, mypy ignores the type annotations present in these modules. Adding
this file enables downstream modules (like CI and batch) to check the type annotations
provided by hailtop, gear, and web_common.
See more information here: https://mypy.readthedocs.io/en/stable/installed_packages.html#making-pep-561-compatible-packages

[gear][hailtop][web_common] enable mypy for shared modules

---

batch/batch/front_end/validate.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/validate/__init__.py
hail/python/hailtop/utils/validate/validate.py

I thought about porting some of the typechecker stuff from hail, but they don't serve quite the same purpose, and the functions themselves are pretty simple. This does move the schema definitions to the bottom of the file rather than at the top, but this way we have a schema description that includes requiredness and is guaranteed to be the thing we're actually validating on.

[batch] rewrite schema validation so that schema description is working validation function

---

batch/batch/worker/worker.py
hail/python/hailtop/batch_client/parse.py

I screwed this up in the Shuffler PR. I need to remove the "image tag suffix" (the stuff after the final colon) before comparing
to a string like "gcr.io/hail-vdc/query".
I used the terminology from the Docker image specs:
- https://github.com/moby/moby/blob/master/image/spec/v1.md
- https://github.com/moby/moby/blob/master/image/spec/v1.2.md
But this terminology is kind of confusing. In "gcr.io/hail-vdc/query" the "repository" is "gcr.io/hail-vdc/query" and the tag is
not present.

[query-service] enable public use of query image

---

hail/python/hailtop/httpx.py

This change replaces uses of `requests.Session` with uses of
`BlockingClientSession`. The latter is a class introduced by this
PR. BlockingClientSession is a shim around
[`aiohttp.ClientSession`](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L167). I
also needed these new classes:
- `BlockingClientResponse`, representing a response to an HTTP request. Wraps `aiohttp.ClientResponse`.
- `BlockingClientWebSocketResponse`, representing a web socket session. Wraps
`aiohttp.ClientWebSocketResponse`
- `BlockingClientresponseContextManager` and
`BlockingClientWebSocketResponseContextManager` which wrap the context manager
returned by `aiohttp_client_session.post(...)` or
`....ws_connect(...)`. They wrap the `__aenter__` and `__aexit__` calls and
also wrap the value returned by …

[tls2] implement blocking client session in terms of aiohttp

---

batch/batch/driver/create_instance.py

We lost this in a rebase. Query jobs need to talk to the internal network because the shuffler
is on the internal network.

[batch] restore internal network

---

batch/batch/driver/create_instance.py
batch/batch/public_gcr_images.py
batch/batch/worker/worker.py

I thought that pulling with no auth would use the credential helper to use the machine's
credentials. AFAICT, the Docker HTTP API has no way to use the credential helper. You *must* provide
authentication in the HTTP request which means the HTTP client must obtain the credentials
themselves. The Docker docs note ["Authentication for registries is handled client side. The client
has to send authentication details to various endpoints that need to communicate with
registries"](https://docs.docker.com/engine/api/v1.41/#section/Authentication)
I request a short-lived oauth2 access token from the Google metadata endpoint. The google
[documentation obliquely notes that the username should be
`oauth2accesstoken`](https://cloud.google.com/container-registry/docs/advanced-authentication). I
use …

[batch] Fix broken batch worker image pulling

---

build.yaml

Building the JAR only takes 5 minutes. Query and Shuffler don't need the other stuff, so it's better for services team if we can skip all that. I don't really care much about the added 5 compute minutes. It's worth the increase in developer velocity.

[hail] add jar-only hail build job

---

ci/ci/build.py
hail/python/hailtop/hail_logging.py

GCP Logging attempts to infer the severity of a log entry and defaults to labelling everything written to `stdout` as `INFO` and everything written to `stderr` as `ERROR`. There are some [LogEntry fields](https://cloud.google.com/logging/docs/structured-logging) that can be overwritten by fields in our JSON output, including `severity`. Until now we had been logging the severity level as `levelname`, which is the expectation of `jsonlogger`, but this means GCP's levels and ours do not necessarily match.  This adds another `severity` field to the logs so GCP can pick up the level.
This should get rid of a swath of non-error log messages written to `stderr` (only JSON though) and lets other levels like `WARNING` get marked as such.
GCP does quite literally extract the severity field though, …

[logging] Add severity field to jsonlogger

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala

A simplistic port that still uses an EmitCode for the element IR to keep
BinarySearch mostly happy

port LowerBoundOnOrderedCollection to emitI

---

hail/python/hail/backend/local_backend.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py
query/query/query.py

If SPARK_HOME is not set, we might still be able to call find_spark_home.py and get the spark
home directory from that. We already do this in query.py. We now do this in local backend too.

[hail] intelligently discover the spark home directory

---

auth/auth/auth.py
batch/batch/driver/main.py
gear/gear/__init__.py
gear/gear/auth.py
router-resolver/router_resolver/router_resolver.py

The router resolver incorrectly assumed the contents of the `Authorization` header was a session
id. In fact, the structure of that header and X-Hail-Internal-Authorization is:
```
Bearer SESSION_ID
```
where `SESSION_ID` is a 44 base64 characters representing a 32 byte secret session id.
I also took this opportunity to centralize the parsing of bearer headers as
`gear.maybe_parse_bearer_header`.
---
This caused a failure because router-resolver, when checking that a user is properly authenticated,
would send:
```
Bearer Bearer SESSION_ID
```
which failed the 44-byte length check in auth/front_end.py.

[router-resolver][auth] fix latent bug in router-resolver

---

hail/python/test/hail/matrixtable/test_matrix_table.py
hail/src/main/scala/is/hail/expr/ir/TableIR.scala

`filterSet` requires the argument be a subset of the fields of the given struct. That is not
how `splitRequestedTypes` works. Instead, we explicitly compute the fields needed from each side
and pass those to `filterSet`.

[hail] make TableNativeZippedReader work

---

hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala

This just adds a utility debugging method, instead of having to do `cb.append(Code._println(...))`. I find it helpful.

[query] Add println to codebuilder

---

hail/src/main/scala/is/hail/annotations/UnsafeRow.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/linalg/LinalgCodeUtils.scala
hail/src/main/scala/is/hail/types/encoded/EBlockMatrixNDArray.scala
hail/src/main/scala/is/hail/types/encoded/ENDArrayColumnMajor.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/types/physical/PNDArray.scala
hail/src/main/scala/is/hail/types/physical/PTuple.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SNDArrayPointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SNDArray.scala

This PR:
- Pushes code builders through PNDArray interface instead of method builders
- Starts switching away from `PNDArray.data.load` to using methods like `dataPArrayPointer` and `dataFirstElementPointer`. All `dataPArrayPointer` calls will go away when ndarrays are no longer backed by `PArray`. 
- Speeds up repeated calls to `loadElement` on `SNDArrayPointerSettable`, which speeds up linear regression nd benchmark ~12%. Now we are approximately 60% slower than breeze linear regression.'
- Removes `CodePTuple`, since all instances of its use are removed now and it predated the current `PCode` system

[query] Clean up PNDArray / Improve loadElement performance

---

hail/python/hail/backend/service_backend.py
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
hail/src/test/scala/is/hail/fs/FSSuite.scala
query/query/query.py

This fixes a bug faced by Konrad preventing him from reading any tables. There were two issues here:
1. `load_references_from_dataset` was unimplemented
2. `GoogleStorageFS.listStatus` included the directory itself in the listing which caused
unexpected, wrong behavior in `ReferenceGenome.readReferences`. I fixed this by filtering out the
directory itself from `listStatus`.

[query-service] implement load_references_from_dataset

---

hail/python/hailtop/aiogoogle/client/storage_client.py
hail/python/hailtop/aiotools/__init__.py
hail/python/hailtop/aiotools/fs.py
hail/python/test/hailtop/test_aiogoogle.py

implement in LocalAsyncFS with test.
AsynFS needs to support multi-part writes in order to parallelize transfers of large files.  Next PR will implement this for gs:// efficiently using a temporary file and the compose operation.

[fs] add AsyncFS.multi_part_create interface

---

hail/python/hailtop/aiotools/fs.py
hail/python/hailtop/utils/utils.py

This includes two changes:
First, add parallelism (async, single-core) to copy by parallelizing
over transfers, sources and files in directory sources.  This doesn't
get multi-core or intra-file parallelism yet.
copy() returns a CopyReport now.  It summarizes each transfer, source
and records counts of files copied, exceptions, etc.  To preserve the
old behavior, there is a flag that causes the first exception in the
report to be raised (if there is one) (this is the default).
I will remark, this makes copy() very parallel and it will immediately
and do in parallel all the transfers, files and discovered files.
Separate PRs will add process parallelism and intra-file parallelism which on multi-part upload support: https://github.com/hail-is/hail/pull/9918

[fs] add some parallelism to copy

---

image-fetcher/Makefile
image-fetcher/fetch-image.sh

- Using `-x` prints every line of the script to an error log entry. The main thing we're concerned about here is if it can fetch from notebook, so capture that output in `image-fetch-output.log` and cat that out to `stderr` only if it failed so it shows up as errors in the logs.
- Removed old templating from before the `jinja2` times
cc @cseed

[image-fetcher] only redirect errors to stderr and remove old Make rules

---

hail/python/hail/expr/functions.py

Unlike a normal python array, there's no reason for us to traverse a numpy array to type check its entries. We know it is of uniform type.

[query] Do not traverse entries to check type of a numpy array

---

blog/nginx.conf
gateway/nginx.conf
internal-gateway/nginx.conf
router/nginx.conf
site/nginx.conf

- Basic JSON format for NGINX access logs
- `message`, `remote_address`, `request_duration`, `response_status` and `x_real_ip` should match the Python Access logger so we should be able to query these fields all at once
- Unfortunately the NGINX `error_log` does not allow the same custom formatter, but we can create multiple, [custom access logs](https://www.nginx.com/blog/diagnostic-logging-nginx-javascript-module/#proxy_next_upstream) based on arbitrary failure criteria if there's a particular class of error logs we want to get in the future.

[router,gateway,site,blog,internal-gateway] Change nginx logs to JSON

---

hail/python/hail/conftest.py
hail/python/hail/docs/functions/core.rst
hail/python/hail/docs/overview/expressions.rst
hail/python/hail/docs/tutorials/05-filter-annotate.ipynb
hail/python/hail/experimental/full_outer_join_mt.py
hail/python/hail/experimental/loop.py
hail/python/hail/experimental/phase_by_transmission.py
hail/python/hail/experimental/vcf_combiner/sparse_split_multi.py
hail/python/hail/experimental/vcf_combiner/vcf_combiner.py
hail/python/hail/expr/__init__.py
hail/python/hail/expr/aggregators/aggregators.py
hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/expr/expressions/typed_expressions.py
hail/python/hail/expr/functions.py
hail/python/hail/matrixtable.py
hail/python/hail/methods/family_methods.py
hail/python/hail/methods/qc.py
hail/python/hail/methods/statgen.py
hail/python/hail/table.py
hail/python/test/hail/expr/test_expr.py

CHANGELOG: Deprecated `hl.null` in favor of `hl.missing`.
Dan suggested that `hl.null` and `hl.is_missing` didn't match well. Now it's `hl.missing` and `hl.is_missing`, which makes more sense.

[query] Deprecate `hl.null` in favor of `hl.missing`

---

batch/batch/worker/worker.py

Those image paths start with e.g. australia-southeast1-docker.pkg.dev/.

[batch] remove assertion that breaks the usage of Artifact Registry images

---

hail/python/hailtop/batch/backend.py

This is necessary for submitting a "nested batch" from the user's job.

[batch] mount Hail tokens in user job containers

---

.pre-commit-config.yaml
ci/Makefile
ci/ci/__main__.py
ci/ci/build.py
ci/ci/ci.py
ci/ci/constants.py
ci/ci/github.py
ci/create_database.py
ci/jinja2_render.py
ci/setup.py
ci/test/resources/sql/insert.py
ci/test/test_ci.py
ci/wait-for.py
docker/requirements.txt
hail/python/dev-requirements.txt
setup.cfg

@danking Here's what it looks like running black on `ci.py` and `address.py` with only customizations being a line length of 120 (I personally prefer shorter but that's what we have currently) and no single quote -> double quote changes (`--skip-string-normalization`).
It is _super_ opinionated, so you have to like the defaults or be willing to roll with it on some calls. It took a lot of [discourse](https://github.com/psf/black/issues/118) just to allow single-quoting strings, but a commit hook to auto-format service code seems useful.

[format] black formatting

---

router/start-nginx.sh

`-x` logs each line of `start-nginx.sh` that runs and I don't expect anything in here to fail / the code itself to provide useful context in a failure

[router] dont log lines of startup script

---

address/address/address.py
build.yaml

This ended up being a great lesson in `asyncio`!
`kubernetes_asyncio` has a deeply hidden `asyncio.ClientSession` that doesn't get properly closed when we restart services with `SIGINT`. Turns out the `__del__` method on the `RESTClient` deep inside the library that holds this client session sets up a future with asyncio to close the session, but I suspect that this object is getting deleted _after_ the event loop closes. As a result we get a bunch of garbage in the logs that
- the event loop is already closed when something is trying to happen
- a `ClientSession.close` was never properly awaited
I initially tried to explicitly close the client session but still dealt with the problem that the `k8s_client` was trying to interact with the even loop after it closed. Explicitly deleting the …

[address] Close all existing connections on cleanup

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/GenericTableValue.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/types/physical/stypes/SCode.scala

Refactor `_emitStream` to a `EmitCodeBuilder -> IEmitCode` signature.

[query] CodeBuilder-ify part of EmitStream

---

hail/src/main/scala/is/hail/lir/SplitMethod.scala
hail/src/test/scala/is/hail/lir/LIRSplitSuite.scala

The match on method identity caused mismatches between the variable
stored in loaded across splits.

[query] Fix LIR splitting of parameters with mutation

---

auth/auth/driver/driver.py

Think this should resolve this [error](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.container_name%3D%22auth-driver%22%0Aseverity%3DERROR;timeRange=PT3H?authuser=2&project=hail-vdc) where `auth-driver` is crashing on start

[auth-driver] Don't await BatchClient init

---

hail/python/hail/methods/impex.py

Add information from https://discuss.hail.is/t/export-elasticsearch-function-documentation-for-updating-behavior/1899 to `export_elasticsearch` docs. This happens fairly often with preemptible Dataproc workers and has caused us some confusion in the past with the gnomAD browser. Without some understanding of how Hail works, it's not immediately clear why this happens.

Add note about avoiding duplicate data to export_elasticsearch docs

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/AppendOnlyBTree.scala

This replaces the EmitCode implementation by a start label together with an IEmitCode. I propose that EmitCode will still be needed occasionally in a CodeBuilder world, and that this is a form it could take.
For compatibility with existing EmitCode users, this defines `setup` and `m`, but those should be removed after the transition to CodeBuilder/IEmitCode is complete.

[query] Change EmitCode implementation

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/StagedRegion.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalArray.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala

Also added a PCanonicalArray constructor that takes a stream of elements.

[query] remove uses of SRVB in EmitStream

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala

The existing implementation only worked when evaluating `value` did
not append any code to the code builder.

[query] Fix IEmitCode.present

---

dev-docs/creating-a-developer-account.md

As far as I can tell, there is no way to completely automate the creation of
a developer namespace. I document why and how to manually do so here.
cc: @jigold

[dev-docs] information about creating a developer account

---

hail/python/hailtop/utils/utils.py

Ben W. experienced this while trying to submit a large batch. I eliminated ClientOSError because
it is a subtype of OSError.

[batch] retry EPIPE

---

atgu/atgu/atgu.py
batch/batch/driver/main.py
memory/memory/memory.py
notebook/notebook/notebook.py
query/query/query.py
router-resolver/router_resolver/router_resolver.py
scorecard/scorecard/scorecard.py

A follow-up on #9944 to make sure that client sessions used by the k8s client are closed on cleanup across all services that use it, along with a couple other client connections that need to get closed on shutdown.

[k8s] Close k8s client on cleanup

---

address/test/test_address.py

The IP address we got from `address` might be the IP of a pod that has been removed. When this happens
we get connection failed errors, which we treat as "transient". This change modifies the test to also
get a new IP address each time a transient error occurs. Not ideal, but more correct than previously.
There are forthcoming changes that I hope will more pervasively address this problem.

[address] retry with new IP as well

---

dev-docs/development_process.md

Nested another section layer under `Implementation` so now there is `Environment / Tooling` and `Testing / Debugging` with space in both to outline shared steps and then compiler & services-specific steps

[dev-docs] Add pre-commit notes and kube/gcloud setup

---

hail/python/cluster-tests/cluster-vep-check-GRCh37.py
hail/python/cluster-tests/cluster-vep-check-GRCh38.py
hail/python/hail/methods/qc.py
hail/src/main/scala/is/hail/methods/VEP.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

1. Don't ignore parse errors by default. These shouldn't be happening
with modern VEP versions anyway (they were caused by genes named NaN
or something in older versions)
2. Don't silently drop variants that don't have a match in VEP. All keys
coming in will have a row coming out with a VEP annotation (maybe NA)
and a partition/block index.

[vep] Rework VEP with more visibility

---

hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
hail/src/main/scala/is/hail/types/physical/stypes/SType.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SBaseStructPointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SBinaryPointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SCanonicalCall.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SCanonicalLocusPointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SCanonicalShufflePointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SIndexablePointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SIntervalPointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SNDArrayPointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SStringPointer.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SSubsetStruct.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SStream.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SString.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SVoid.scala
hail/src/main/scala/is/hail/types/physical/stypes/interfaces/package.scala
hail/src/main/scala/is/hail/types/physical/stypes/primitives/SBoolean.scala
hail/src/main/scala/is/hail/types/physical/stypes/primitives/SFloat32.scala
hail/src/main/scala/is/hail/types/physical/stypes/primitives/SFloat64.scala
hail/src/main/scala/is/hail/types/physical/stypes/primitives/SInt32.scala
hail/src/main/scala/is/hail/types/physical/stypes/primitives/SInt64.scala

 [query] Fix up some string functions using old-style registerCode 

---

hail/src/main/scala/is/hail/expr/ir/agg/DensifyAggregator.scala
hail/src/main/scala/is/hail/types/physical/PArrayBackedContainer.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalArray.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalBaseStruct.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalBinary.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalCall.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalInterval.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalLocus.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalShuffle.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalStream.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalString.scala
hail/src/main/scala/is/hail/types/physical/PPrimitive.scala
hail/src/main/scala/is/hail/types/physical/PSubsetStruct.scala
hail/src/main/scala/is/hail/types/physical/PType.scala
hail/src/main/scala/is/hail/types/physical/PVoid.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SIndexablePointer.scala

This replaces any instances I know about where we were using `match` to decide whether we had to dereference a pointer. This makes it easier for me to add reference counted ndarrays, and it makes it easier for us to nix fundamental type altogether. 
I had to add `unstagedLoadFromNested` as well

[query] Use `loadFromNested` rather than matching on fundamental type

---

hail/src/main/scala/is/hail/io/bgen/BgenRDD.scala
hail/src/main/scala/is/hail/io/bgen/BgenRDDPartitions.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalArray.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalLocus.scala

BGEN benchmarks before/after:
```
$ hb compare  0.2.61-ffa3169a657f-bgen-cb-before.json 0.2.61-126a8c8d5147-bgen-cb.json
Benchmark Name      Ratio     Time 1     Time 2
--------------      -----     ------     ------
import_bgen_force_count_all      98.0%    144.232    141.289
import_bgen_filter_count      97.9%    142.950    139.965
import_bgen_force_count_just_gp      96.1%    146.766    141.000
import_bgen_info_score      95.0%    197.271    187.353
Harmonic mean: 96.7%
Geometric mean: 96.7%
Arithmetic mean: 96.7%
Median:  97.0%
```
I think this is within noise of no change.

[query] Translate BGEN import to codebuilder and new constructors

---

hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala

Stream separate regions inference is coming next (and going into EmitContext)

[query] Replace ExecuteContext with EmitContext in emitter

---

gateway/gateway.nginx.conf

Previously, unauthenticated developers would get a 401 nginx page when hitting an internal url. This now sends them through the auth flow.
In the spirit of deploying before merge, you can try this out!

[gateway] redirect to auth on 401 in internal

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/agg/CollectAsSetAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/StagedBlockLinkedList.scala
hail/src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala
hail/src/main/scala/is/hail/io/bgen/BgenRDDPartitions.scala
hail/src/main/scala/is/hail/linalg/LinalgCodeUtils.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalArray.scala

[query] Rework PCArray.constructFromFunctions to track index internally

---

hail/python/test/hail/utils/test_utils.py
hail/src/main/scala/is/hail/io/fs/HadoopFS.scala

As described in #9600, `hl.hadoop_ls` currently raises a NullPointerException when called with a path that does not exist. The error originates in `is.hail.io.fs.HadoopFS.listStatus`.
The [hadoop.fs.FileSystem docs](https://hadoop.apache.org/docs/current/api/org/apache/hadoop/fs/FileSystem.html#globStatus-org.apache.hadoop.fs.Path-) list two forms of `globStatus`:
* public FileStatus[] globStatus(Path pathPattern)
* public FileStatus[] globStatus(Path pathPattern, PathFilter filter)
The first makes no mention of returning null. The second however, says:
> Returns: null if pathPattern has no glob and the path does not exist an empty array if pathPattern has a glob and no path matches it else an array of FileStatus objects matching the pattern
This matches the behavior seen with …

[query] Improve error message from hadoop_ls when file does not exist

---

batch/batch/worker/worker.py

If there is a true issue, we raise the exception which is caught and printed by
docker_call_retry, or, if that re-raises, it is stored as an error and serialized
back to the driver in Container.run

[batch] eliminate expected exceptional log statement

---

image-fetcher/fetch-image.sh
site/site.sh

the gcloud command write to `stderr` which gets interpreted as errors in the logs and causes [a lot of noise](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aseverity%3DERROR%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.container_name%3D%22image-fetcher%22;timeRange=PT3H?project=hail-vdc&folder=true&organizationId=548622027621&query=%0A). 
Added `gcr.io` because without it `configure-docker` would configure all the registries it can find, which is unnecessary. Also removed `-x` from the site script since each line of that goes to error logs and none of it is helpful. If errors occur they will show up in some other form.

[image-fetcher,site] clean up normal bash output from error logs

---

auth/Dockerfile

There is a new version of google-cloud-core which is incompatible with google-auth 1.12.1. Rather than
pin to an old version of google-cloud-core, I bump us to the latest of both auth libraries.

[auth] bump PyPI versions of google auth libs

---

docker/requirements.txt

Matches up the `gcsfs` version between services and hail query. Right now services developers have to pip install the `docker/requirements.txt` to run stuff like `sync.py` or resolve imports in editor. Might not be ideal but this at least allows you to pip install all the different requirements together for now.

[pip] fix conflicting pip requirements between query and services

---

hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
hail/src/main/scala/is/hail/expr/ir/agg/CallStatsAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/StagedArrayBuilder.scala
hail/src/test/scala/is/hail/annotations/StagedRegionValueSuite.scala

Replace with PType constructors.

[query] Delete a bunch of static SRVB methods

---

hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/GenericTableValue.scala
hail/src/main/scala/is/hail/expr/ir/TableIR.scala
hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala
hail/src/main/scala/is/hail/expr/ir/agg/TakeByAggregator.scala
hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
hail/src/main/scala/is/hail/io/bgen/BgenRDDPartitions.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalLocus.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalStream.scala
hail/src/main/scala/is/hail/types/physical/PType.scala
hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala
hail/src/test/scala/is/hail/expr/ir/agg/DownsampleSuite.scala

This is the first step toward top-level requiredness being an attribute
of IEmitCode rather than PType.
* Take cb/mb when necessary.
* Remove unnecessary constructors

[query] Begin simplifying EmitCode constructors.

---

hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
hail/src/test/scala/is/hail/expr/ir/StringFunctionsSuite.scala

The whitespace changes are an autoformat.

[query] Remove SRVB from StringFunctions

---

hail/python/hailtop/aiogoogle/auth/session.py
hail/python/hailtop/aiogoogle/client/storage_client.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py

This should fix the test_copy failures.
The problem was, we were sending a mutable byte iterator for data when inserting a new object.  If that insert read some of the data, failed, and was retried, the data that was read was lost and the retry started where the failed insert left off.
To retry writes, you need to keep around the data you've sent to resend in case of failure.  So you don't have to keep around an unbounded amount of data, Google Storage supports resumable uploads: https://cloud.google.com/storage/docs/resumable-uploads.  This allows us to send data in chunks, and release the data after Google reports back that the data has been committed.  `StorageClient.insert_object`, when the upload type is resumable (the default), takes an additional argument `bufsize`.  This is the …

[aiogoogle] use resumable uploads to make writes resilient

---

hail/python/hail/expr/expressions/typed_expressions.py

Noticed that ArrayExpression.head was not documented as deprecated when it was deprecated in #9482.
This also fixes a rendering error with one of its examples.
https://hail.is/docs/0.2/hail.expr.ArrayExpression.html#hail.expr.ArrayExpression.head

[query] Document deprecation of ArrayExpression.head

---

hail/python/hailtop/aiogoogle/client/storage_client.py

If we find out the write is complete during a status check, we would assert the buffer is empty before advancing the the offset to the end.  This exit point now matches the exit point when we complete after a normal chunk write.
Also assert _closed in _wait_closed.  _write_chunk can only complete when we've closed and therefore know the final size, so make sure _closed so we don't accidentally get into an infinite loop waiting for _done.

[copy] fix overly strong assertion

---

hail/python/hail/expr/aggregators/aggregators.py
hail/python/test/hail/expr/test_expr.py

CHANGELOG: Fix mishandling of NaN values in `hl.agg.hist`, where they were unintentionally included in the first bin.

[query] Fix bug where NaN values fell into first bin in `hl.agg.hist`

---

.pre-commit-config.yaml
build.yaml
grafana/Makefile
grafana/deployment.yaml
router/deployment.yaml
router/router.nginx.conf.in
tls/config.yaml

Deploying grafana in our GKE cluster gives us instant and easy access to the stackdriver backend with the same querying capabilities of our current front-end, but without the clutter and insanely slow load times. See [here](https://internal.hail.is/dgoldste/grafana/d/TVkleyLMk/detailed-service-resource-utilization?orgId=1) for some example dashboards I set up to look at resources across our services (credentials are the default admin/admin).
This alleviates the immediate pain of using the console (for metrics only, not logging), but my longer aim is that getting more regular use out of our metrics can reveal deeper pain points of our monitoring stack and if/where we need to eat up more responsibility from google monitoring.
This is a StatefulSet, so configuration through the UI will …

[grafana] Add grafana service for metrics monitoring

---

hail/src/main/scala/is/hail/annotations/UnsafeRow.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalCall.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalString.scala
hail/src/main/scala/is/hail/types/physical/PString.scala
hail/src/main/scala/is/hail/types/physical/package.scala
hail/src/main/scala/is/hail/types/physical/stypes/concrete/SStringPointer.scala
hail/src/test/scala/is/hail/types/physical/PhysicalTestUtils.scala

Stop using fundamental type on PString where possible. We just will have a special  `binaryRepresentation` or whatever on strings to get the underlying binary representation as long as it exists. Also, pull out some other fundamentals I suspect are not needed

[query] Removing fundamental types on strings

---

.pre-commit-config.yaml
ci/ci/templates/batch.html
ci/ci/templates/index.html
ci/ci/templates/job.html
ci/ci/templates/pr.html

Adds a `pre-commit` linting rule to run on our html files that is jinja-aware.
The ~ resilience ~ of html continues to astound me.

[ci] add curlylint and fix some improper html

---

hail/src/main/scala/is/hail/expr/ir/Pretty.scala

We also need to fix the renderer to properly bail out on large inputs.
This caused a string buffer overflow with a large literal.

[query] Change Pretty.short to elide literals by default

---

dev-docs/development_process.md
devbin/functions.sh

I use these functions to monitor the k8s cluster. These are useful in the interim while we
move towards more robust monitoring solutions. To make these accessible modify your ~/.bashrc
or ~/.zshrc to have this line:
source /path/to/hail-repository/devbin/functions.sh
cc: services-team: @jigold @CDiaz96 @catoverdrive @cseed

[devbin] add devbin/functions.sh

---

site/pages/robots.txt
site/www/favicon.ico

We're upsetting the robots of the world by not having a `robots.txt` to instruct how they should crawl the website. As retribution, they crawl everything, so this robots.txt doesn't change any indexing behavior but if there's anything we don't want indexed I can add here. Requests for `/robots.txt` and `/favicon.ico` make up a non-trivial amount of site's error logs now, so I also added a symlink to the image we use as our favicon. Hopefully this helps to further quiet the logs.

[site] Add robots.txt and favicon.ico symlink

---

benchmark/python/benchmark_hail/combine/combine.py

`scipy.stats.f_oneway` now throws if only one arg is passed:
```
TypeError: at least two inputs are required; got 1.
```

[benchmarks] Fix benchmark combine after scipy update

---

batch/test/test_accounts.py
build.yaml

These billing projects tests did not correctly handle multiple attempts. Instead,
we use one billing project prefix for the entire batch (based on the token) and
each attempt gets a unique prefix. After all batch tests are complete, a job runs
which deletes all billing projects for the current batch.

[batch] fix billing projects tests

---

batch/batch/driver/job.py
batch/sql/estimated-current.sql
batch/sql/fix-schedule-job.sql
build.yaml

We had a bug yesterday where the return value for `delta_cores_mcpu` when scheduling a job was None instead of an integer. This messed up the instance collection data structures for that instance so we couldn't remove the instance and we couldn't handle the deactivate or delete events. Also, the instance was stuck with -1 free cores.
I think until we figure out why this happened, this is a perfectly good solution. If the job was actually scheduled correctly, then MJS will happen and the free cores will be correct.

[batch] Fix bug in schedule_job

---

hail/python/hailtop/hailctl/dev/deploy/cli.py

Hi, just proposing a possible fix (at least it fixes things for me).
After `raise_for_status=True` [was set](https://github.com/hail-is/hail/pull/9864/files) to default to True for `ClientSession` objects, [these lines](https://github.com/hail-is/hail/blob/9303a3aeccc3c374130b845bdaa5b22a84a64ea5/hail/python/hailtop/hailctl/dev/deploy/cli.py#L48-L53) that handle the response and redirect the remote traceback locally, are no longer reachable.
This PR sets `raise_for_status=False` for dev deploy, similar to how it [was handled for dev query](https://github.com/hail-is/hail/pull/9864/files#diff-3d7267e81281c8027cba60607e398a7d5fbfcc16481cddf45017948889b15715).
Thanks @lgruen for helping to locate the issue!

[hailctl dev] deploy cli: fix printing remote traceback

---

hail/src/main/scala/is/hail/types/physical/PCanonicalArray.scala

Want to use memcpy when possible.

[query] Array Copy Fast Path

---

hail/src/main/scala/is/hail/expr/ir/TableIR.scala

The left and right sources may provide more fields than are necessary. This is OK, but
previously this caused an error because `filterSet` expects the argument to be a subset
of the `self` argument.

[hail] fix bug in PartitionZippedNativeReader

---

hail/python/test/hail/expr/test_expr.py

Its definition is literally first so I do not think we need this test

[hail] stop testing head, avoiding deprecation warning

---

hail/src/main/scala/is/hail/annotations/Region.scala
hail/src/main/scala/is/hail/types/physical/PArrayBackedContainer.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalArray.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalBaseStruct.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalCall.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalInterval.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalLocus.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalShuffle.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalStream.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalString.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalStruct.scala
hail/src/main/scala/is/hail/types/physical/PCanonicalTuple.scala
hail/src/main/scala/is/hail/types/physical/PDict.scala
hail/src/main/scala/is/hail/types/physical/PSet.scala
hail/src/main/scala/is/hail/types/physical/PString.scala
hail/src/main/scala/is/hail/types/physical/PStruct.scala
hail/src/main/scala/is/hail/types/physical/PSubsetStruct.scala
hail/src/main/scala/is/hail/types/physical/PTuple.scala
hail/src/main/scala/is/hail/types/physical/PType.scala
hail/src/main/scala/is/hail/utils/richUtils/RichCodeInputBuffer.scala
hail/src/main/scala/is/hail/utils/richUtils/RichCodeOutputBuffer.scala
hail/src/main/scala/is/hail/variant/RegionValueVariant.scala

Fundamental types seem like a good idea, but using them in code generation at any stage but point manipulation of values can constrain our ability to use other representations for a given type.

[query] Remove PType.fundamentalType

---

ci/ci/github.py

I've only ever seen this for merge conflicts, which doesn't seem "exceptional" for a CI system.

[ci] dont say a merge conflict is an exception

---

hail/src/main/scala/is/hail/io/fs/HadoopFS.scala

[query] Fix flushing on HadoopFS.toPositionedOutputStream

---

hail/python/hail/ir/ir.py
hail/python/test/hail/expr/test_ndarrays.py
hail/src/main/scala/is/hail/expr/ir/Children.scala
hail/src/main/scala/is/hail/expr/ir/Copy.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferType.scala
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/expr/ir/Pretty.scala
hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala

Add errorId tracking to MakeNDArray, allowing user to get a good python error highlighting where an error is thrown from.

[query] MakeNDArray uses Better Python Error system

---

hail/src/main/scala/is/hail/expr/ir/Compile.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
hail/src/main/scala/is/hail/expr/ir/InferPType.scala
hail/src/main/scala/is/hail/expr/ir/InferStreamMemoryManagement.scala
hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala

Currently, this is done in parallel with the existing memory management
tracking (in ptypes), and we assert that the two produce the same
result. This can give us confidence that removing InferPType will not
change semantics.

[query] Add independent inference pass for stream memory management

---

batch/batch/driver/canceller.py
batch/batch/driver/job_private.py

This solves a problem we saw where an attempt was scheduled on the instance, but when entering the schedule event into the database it failed. In the meantime, the job is cancelled before the database call can be retried. Now the job is presumed cancelled even though there are still attempts running. I added a loop to find attempts that are orphaned and unschedule them.
Please double check the SQL query here that I got all the conditions correct!

[batch] Cancel orphaned attempts

---

hail/python/hailtop/aiogoogle/client/storage_client.py
hail/python/hailtop/aiotools/fs.py
hail/python/hailtop/utils/__init__.py
hail/python/hailtop/utils/utils.py
hail/python/test/hailtop/aiotools/generate_copy_test_specs.py
hail/python/test/hailtop/aiotools/test_copy.py
hail/python/test/hailtop/test_aiogoogle.py

This PR introduces async parallelism for copy.  Summary of changes:
- add compose to aiogoogle StorageClient and use it to implement (hierarchical) multi-part write for the google AsyncFS
- add AsyncFS.open_from, to open a file starting at a given offset,
- PART_SIZE is the size of parts to transfer and the combine with a multi-part write when copying large files.  PART_SIZE is currently 128MB.
- BUFFER_SIZE is the size we request when reading in the copy.  Change this to 256KB (from 8KB).
- Copy files in parts and use multi-part writes when copying large files.
- Parallelize rmtree (it now takes a semaphore for controlling parallelism)
- Add new primitives for parallelization, bounded_gather2 and OnlineBoundedGather2.
bounded_gather2 was an interesting design problem.  I would describe …

[copy] parallelize over chunks

---

docker/requirements.txt
hail/python/dev-requirements.txt
hail/python/hailtop/httpx.py
hail/python/requirements.txt

Bump aiohttp version and fix some discrepancies between requirements files.
Cleaned out my virtual env and made sure I could `make -C hail install-deps` and `pip install -r docker/requirements.txt`

[aiohttp] bump aiohttp version and sync some other dependencies

---

hail/python/hail/docs/utils/index.rst
hail/python/hail/expr/aggregators/aggregators.py
hail/python/hail/expr/expressions/base_expression.py
hail/python/hail/expr/expressions/typed_expressions.py
hail/python/hail/expr/functions.py
hail/python/hail/expr/types.py
hail/python/hail/utils/__init__.py
hail/python/hail/utils/frozendict.py
hail/python/test/hail/expr/test_expr.py
hail/python/test/hail/utils/test_utils.py

CHANGELOG: Evaluating hail expressions in python will now return `frozendict`, an immutable dictionary type. Sets will return python's `frozenset`.
This is necessary because hail supports hashable dicts, but python does not. Same with sets.

[query] frozendict

---

hail/python/hail/expr/aggregators/aggregators.py

The previous formula, `(1/n) (sumsq - (2 * mean * sum) + (n * mean^2))` was weirdly redundant, since `mean * sum == n * mean^2`. This was added by #6728, which ported stats from Scala, but the weird formula did not come from the Scala implementation. I have no clue where this came from. The only reason for doing something like this might be for improved numerical stability, but that doesn't seem to be the case here.
In fact, this current method of computing the variance (pre or post this pr) is known to be unstable when the mean is much larger than the stdev (as is easy to see: you're subtracting two nearly equal positive numbers). The Scala implementation used the spark `StatCounter`, which uses the more stable [Welford's algorithm](https://en.wikipedia.org/wiki/Algorithms_for_calculating …

[query] simplify strange stdev formula

---

address/deployment.yaml
amundsen/deployment.yaml
atgu/deployment.yaml
auth/deployment.yaml
batch/deployment.yaml
benchmark-service/deployment.yaml
blog/deployment.yaml
bootstrap-gateway/deployment.yaml
ci/deployment.yaml
ci/test/resources/deployment.yaml
ci/test/resources/statefulset.yaml
echo/deployment.yaml
gateway/deployment.yaml
grafana/deployment.yaml
image-fetcher/deployment.yaml
internal-gateway/deployment.yaml
memory/deployment.yaml
monitoring/deployment.yaml
query/deployment.yaml
router-resolver/deployment.yaml
router/deployment.yaml
shuffler/deployment.yaml
site/deployment.yaml
ukbb-rg/deployment.yaml

Our GKE nodes come with 2 CPU and 7.5 GB each, but not all of that is allocatable to our pods. In reality, somewhere between 5.7-5.9GB ([GCP Docs](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture) say 5.7, GKE console says 5.9) of memory and 1.9CPU are available for us to use. Some of our Big services request 1 CPU and 3.75GB, but then we can never fit two big pods on one node. This is an attempt to standardize our requests so their easier to reason about while hopefully getting better packing.  
| resource | Big | Medium | Small |
| --- | --- | --- | --- |
| CPU        | 600m   | 100m | 20m |
| Memory  | 2G | 200M | 20M |
The intentions here are:
- always be able to comfortably get 2 Big pods on a node
- medium pods shouldn't have to force new nodes to spin …

[k8s] set consistent resource requests for better node packing

---

hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala

PRing to test, hopefully will fix Akhil's bug. 
Akhil's stack trace top:
```
Java stack trace:
java.lang.RuntimeException: invoke __m684btree_insert: arg 2: type mismatch:
got +PBoolean
expected PBoolean
at is.hail.expr.ir.EmitCodeBuilder$$anonfun$1.apply(EmitCodeBuilder.scala:132)
at is.hail.expr.ir.EmitCodeBuilder$$anonfun$1.apply(EmitCodeBuilder.scala:114)
at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
at scala.collection.immutable.Range.foreach(Range.scala:160)
at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
at …
```

[query] Fix EmitParams with incorrect requiredness

---

hail/python/hail/methods/statgen.py
hail/python/test/hail/methods/test_statgen.py

This change simplifies the logic to create the various globals when computing linear regression, cuts the size of the IR in half, and makes the code faster in the process
Benchmark times for linear_regression_rows_nd on my laptop:
Before this PR: [37.80013062, 37.84073734200001, 38.025162351999995]
After this PR: [31.85279850500001, 33.12659071399999, 31.33206254000001]
So about 15% faster, but still not fast enough. Regular linear regression is 22 seconds on my laptop.

[query] Reorganize linreg globals computation

---

ci/ci/templates/dev-deploy-table.html
ci/ci/templates/job-table.html
ci/ci/templates/pr-table.html
ci/ci/templates/user.html

The divs for the two columns now span the whole screen, so there is room to breathe between the dev deploy and PR tables. Fixed a spacing bug in the PR tables by aligning them to the start of the flexbox column and standardized on header / searchbox / table per card. This should take up more of the screen, but is not explicitly "centered", basically the tables start at 0% and 50%. Unfortunately it's a painful process to fiddle with the test repo to get anything good to look at on a development CI. I'll start thinking automatically writing out test data to better test UI changes, but for now I just want to see this in main.

[ci] fix flexbox alignment and clean up css

---

batch/batch/worker/worker.py

Timing is supposed to be a dict that maps a named step to timing information. JVMProcess
currently only has one step: "running".

[batch] fix JVMProcess timing dict

---

hail/python/hail/methods/relatedness/king.py
hail/python/test/hail/methods/test_king.py

CHANGELOG: Teach `hl.king` to treat filtered entries as missing values.

[query] teach king to treat filtered entries as missing

---

ci/ci/templates/index.html
ci/ci/templates/pr-table.html
ci/ci/templates/user.html

I added an `id` input to the jinja macro for PR tables. The index page wasn't passing in the second input and the class attribute got smashed into the `id` attribute for the div (`id="class="data-table""`), so the table lost all styling.

[ci] fix missing id css bug

---

hail/python/hailtop/aiogoogle/client/storage_client.py

Multi-part uploads put their scratch data in `<dest-dir>/_/<token>`, however, they deleted `<dest-dir>/_`.  Therefore, if two multi-part uploads were happening to the same destination directory, they would potentially delete the other's uploads causing a 404.  I will hand merge this because it will fail the build.

[copy] fix overly agressive cleanup

---

batch/batch/worker/worker.py

When a bunch of longer running jobs got deleted at once, we instantly deleted the app. We should update the last_updated time when a delete operation comes in.

[batch] Fix last updated on worker when deleting jobs

---

auth/auth/auth.py
build.yaml
grafana/Dockerfile.nginx
grafana/Makefile
grafana/deployment.yaml
grafana/nginx.conf
router/deployment.yaml
router/router.nginx.conf.in
tls/config.yaml
web_common/web_common/templates/header.html
web_common/web_common/web_common.py

Right now the Grafana is exposed as a k8s service speaking http with only the grafana auth. This puts an nginx sidecar in front of Grafana to bring TLS all the way through the the Grafana pod and perform dev authentication. This required adding an api endpoint to auth that can verify a connection based on the session and not an Authorization header. Other services like `router-resolver` have gotten away with not having this since they construct the Authorization header in python before hitting the `userinfo` endpoint, but this seems like a straightforward addition that will make it easier for internal authentication such as this case.
This does another deviant thing which is using a `runImage` step to template the nginx config instead of templating inside the container at container start …

[grafana][auth] add nginx sidecar in front of grafana for tls and auth

---

batch/batch/driver/instance_collection.py
batch/sql/estimated-current.sql
batch/sql/fix-provisioning-bug.sql
build.yaml

The issue is we start billing for instances as soon as they're created with the API. However, if an instance is stuck in provisioning and never activates, we never update the start billing time to account for the lack of resource. This PR uses the `lastStartTimestamp` in the [Google REST API](https://cloud.google.com/compute/docs/reference/rest/v1/instances/get). This value is in RFC3339 format. I think this is the same format the timestamp in the activity logs, so I copied how we parse that value. If we delete the instance due to activation timeout, then we set the attempt start time to NULL so it's not billed.
I couldn't find good documentation on this, but it seems like the `lastStartTimestamp` approximates what we care about for the purposes of checking for stuck workers. I checked it …

[batch] Fix provisioning bugs

---

hail/python/hail/ir/__init__.py
hail/python/hail/ir/table_ir.py
hail/python/hail/ir/table_reader.py
hail/python/hail/methods/impex.py
hail/python/test/hail/methods/test_impex.py
hail/src/main/scala/is/hail/expr/ir/Parser.scala
hail/src/main/scala/is/hail/utils/TextTableReader.scala

CHANGELOG: Add `source_file_field` parameter to `hl.import_table` to allow lines to be associated with their original source file.

[query] Add `source_file_field` to `import_table`

---

ci/ci/ci.py
ci/ci/github.py
ci/ci/templates/batch.html
ci/ci/templates/dev-deploy-table.html
ci/ci/templates/job-table.html
ci/ci/templates/pr.html
ci/ci/templates/user.html

This kind of does a lot of small things:
- Adds a table at the top of the page that is all the PRs that require the user's attention, meaning: a personally authored PR where the build has failed or there are changes requested, or a PR for review that the user has not yet reviewed.
- Under PRs that require a review, a user now sees those where they are listed under `Assignees` *as well as* under `Reviewers`. We have been using assignees to assign reviews, but outside collaborators are unable to do so or dismiss reviews. This is because we don't really align with GitHub's semantics for these labels. Per GitHub, Assignees are organization members responsible for the supervision of a PR, whether the author or the final merge sign-off. Meanwhile, reviewers are what they suggest. If an outside …

[ci] add authorize sha and action items table to user page

---

batch/batch/worker/worker.py

I think there is some unresolved issue with asyncgen shutdown that is keeping
workers alive. This is not an issue in worker because worker calls sys.exit
which forcibly stops execution. cc: @daniel-goldstein @jigold.

[batch] add more logs and do not wait for asyncgens

---

hail/python/test/hail/conftest.py
hail/python/test/hail/helpers.py

The event loop is supposed to be initialized in the main thread. Sometimes
our tests get placed in the non-main thread (always a thread named Dummy-1).
Hopefully the session-scoped fixture is run in the main thread.

[query-service] maybe fix event loop not initialized

---

batch/batch/front_end/front_end.py
build.yaml
ci/ci/ci.py
ci/deployment.yaml
gear/gear/__init__.py
gear/gear/metrics.py
hail/python/hailtop/config/deploy_config.py
letsencrypt/domains.txt
prometheus/Dockerfile.nginx
prometheus/Makefile
prometheus/nginx.conf
prometheus/prometheus.yaml
router/deployment.yaml
router/router.nginx.conf.in
tls/config.yaml

This adds a prometheus statefulset to track metrics like API request latency and uptime. It scrapes pods on a 15s interval and collects prometheus metrics from any container in a pod with `grafanak8sapp` label that exposes an https endpoint `/metrics`.
The batch front end was already exposing prometheus metrics, but I changed it up slightly. For any http endpoint there should be a single metric, `http_request_latency`. Prometheus adds app and namespace metrics so seeing latencies for batch in particular is just a filter applied to this single metric. You can track latency of an endpoint by adding the `@monitor_endpoint` decorator defined in `metrics.py`, which tracks latency as well as number of requests and status code per request, available in the `http_request_count` metric. I also …

[prometheus] add prometheus to track SLIs

---

hail/python/hail/experimental/loop.py
hail/python/test/hail/experimental/test_experimental.py

CHANGELOG: Fixed incorrect error message when incorrect type specifid with hl.loop
I added a test that gave a bad error message, then rearranged code in `hl.loop` to improve the error message. Prior to this change, the error a user would get here is that they wrote a loop that isn't tail recursive, because hail would insert an implicit cast when trying to unify types, and the casting would wrap the recursive loop call. Now, we check to make sure the loop's return type is correct before analyzing whether it's tail recursive, which I believe removes the possibility of getting a tail recursion error when you should be getting a type error.

[query] Check loop return type matches before checking tail recursiveness

---

build.yaml
website/Makefile
website/website/website.py

I build old versions of the docs and use them in new websites. This does not
work for versions of the docs before I introduced the new system. In particular
versions 0.2.63 and before generate old-style docs.

[website] fix website

---

ci/ci/github.py

Due to most of these failures being due to service tests. Feel free to revert when you see fit

[ci] change mention for deploy failure

---

hail/src/main/scala/is/hail/rvd/RVD.scala

EDIT from John for future readers: The issue here is that in general we only expect consumers to free memory after they're done processing a row. So when doing any sort of filtering operation, we want to make our own region that we clear after each row is filtered out, otherwise the garbage rows will continue to accumulate until we finally find a row to keep. `filterWithContext` demonstrates the correct way to do this, and so switching to use that method fixes the problem.

[query] Fix filter intervals (keep=False) memory leak

---

build.yaml

grafana and prometheus jobs for rendering their nginx configs were producing same name outputs so one would overwrite the other.

[nginx] ensure nginx configs dont overwrite each other in build.yaml

---

hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala

Hail-on-Spark uses HadoopFS which emulates directories by creating size-zero files with
the name `gs://bucket/dirname/`. Note: the object name literally ends in a slash. Such files
should not be included in `listStatus` (they should always be empty anyway). Unfortunately,
my fix in https://github.com/hail-is/hail/pull/9914 was wrong because `GoogleStorageFileStatus` removes
the trailing slash. This prevented the path from matching `path`, which always ends in a `/`.
Sorry @jigold, you're now on the reviewers list for the Query Service with Arcturus's departure.

[query-service] teach query service to read MTs and Ts created by Spark

---

website/website/website.py

the batch tutorial contained some `{{` that made for an invalid jinja template, which caused a 500. The batch docs in general don't seem to need any additional rendering at runtime so this treats all the batch docs as static files.

[website] dont jinja render any of the batch docs when serving

---

hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala

If a file exists with the *same name as the directory we are listing*,
then it must be a directory marker. It does not matter if that file is
a directory or not.

[googlestoragefs] ignore the directory check entirely

---

ci/ci/templates/pr.html

Forgot to update this usage of the `pr_table` macro when fixing search bars.

[ci] fix focus on slash and search job page for PRs

---

hail/python/hail/backend/service_backend.py
hail/python/hail/context.py

The idea is to allow the execution on both `SparkBackend` and `ServiceBackend` without code changes, simply switching to the Query service by setting the environment variables `HAIL_QUERY_BACKEND`, `HAIL_BILLING_PROJECT`, and `HAIL_BUCKET`.

[query] call init_service from init based on HAIL_QUERY_BACKEND value

---

website/website/website.py

We track valid docs paths in `docs_pages` relative to the docs directory, so e.g. `0.2/objects.inv` is a valid path, making `/docs/0.2/objects.inv` a valid route, but `0.2/objects.inv` is not a valid path on the host. To actually find and serve the file we have to use `f'{DOCS_PATH}/0.2/objects.inv`. We initialize jinja to know to look at the `docs` directory for templates but `web.FileResponse` takes a path to the specified file (all I could get from the documentation). Verified I receive `objects.inv` and get a 200 in my namespace.

[website] fix resource path for non-html files in the docs

---

hail/python/hail/linalg/blockmatrix.py
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala

This adds an arbitrary mapping operation to `BlockMatrix`. We already had the IR for this and supported it in the lowerer. We don't support this in the unlowered `execute` infrastructure, so I had to add a check to prevent that from happening.
I'm not sure how to document the fact that this operation is unavailable in Spark. I don't think we've had to do that yet. 
I'm also curious if you think `map_dense` and `map_sparse` are good names, or if you think we ought to just have one `map` with a boolean. I do worry what `sparse` is a funny name for this, since when I think of a sparse matrix I think of something closer to Spark's `CoordinateMatrix` (very few, random entries with no structure), as opposed to the block sparsity we have.
This PR also changes the implementation of …

[query] BlockMatrix map

---

build.yaml
ci/test/resources/build.yaml
ci/test/resources/config.yaml
ci/test/resources/deployment.yaml
ci/test/resources/hello.py
ci/test/resources/statefulset.yaml
router/deployment.yaml
router/router.nginx.conf.in

This is one piece of a multi-part saga to use tls for any and all communication between pods. This basically just required adding the `create_certs` step to the ci test `build.yaml` so we can create a ssl config for `hello`.

[ci] make test hello speak https

---

hail/python/hail/experimental/table_ndarray_utils.py
hail/python/hail/methods/pca.py

This should make computing the loadings better, since it uses a checkpointed variants table instead of accidentally recomputing the incoming MatrixTable. Also made a change to avoid accidentally clobbering a field name if someone had a field named `idx`.

[query] blanczos_pca dont do extra loading work

---

auth/auth/auth.py

This is a preparatory PR for getting rid of router-resolver. Currently, the major role of router-resolver is:
- Find the user session in a request
- Make a call to default auth to verify the session and retrieve userdata
- If the user is a developer, return the router IP in the given namespace (given as input to router-resolver)
The code for this is [here](https://github.com/hail-is/hail/blob/466f3c32c7fed972dc9bf45834669fdff038224c/router-resolver/router_resolver/router_resolver.py#L24-L66).
This whole process can just be replaced by an auth endpoint that returns whether or not a request is coming in from a valid developer (we can rely on kubernetes services to find IP addresses on any of our deployments). This moves over the finding of the user session in router-resolver to make an auth …

[auth] add more options for obtaining session id for dev credentials

---

batch/Dockerfile.worker
build.yaml
docker/Dockerfile.base
docker/Dockerfile.service-java-run-base
hail/Makefile
hail/build.gradle
hail/python/hail/backend/local_backend.py
hail/python/hail/docs/install/linux.rst
hail/python/hail/docs/install/macosx.rst
hail/python/hail/docs/install/other-cluster.rst
hail/python/hailtop/hailctl/dataproc/start.py
hail/python/requirements.txt
hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
hail/src/main/scala/is/hail/expr/ir/AbstractMatrixTableSpec.scala
hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
hail/src/main/scala/is/hail/expr/ir/BlockMatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/IR.scala
hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
hail/src/main/scala/is/hail/expr/ir/functions/RelationalFunctions.scala
hail/src/main/scala/is/hail/io/BufferSpecs.scala
hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala
hail/src/main/scala/is/hail/types/BlockMatrixType.scala

This PR:
- Changes default hail Spark version to Spark 3
- Changes default hail Scala version to 2.12
- ~Changes the `build_hail_spark3` rule to `build_hail_spark2`. I don't know how long we will care if we still build under Spark 2.~ Scratch that, I deleted this. We don't support spark 2 anymore.  
- Changes the dataproc image used in `hailctl dataproc start` to one that uses Spark 3.1.1.

[query] Default to Spark 3

---

gateway/gateway.nginx.conf

This PR only impacts `internal.hail.is`.
The current internal flow is:
1. gateway receives request for `internal.hail.is/$namespace/$service`
2. `auth_request` to router-resolver for auth & router ip, and in router-resolver
a. request to auth that the user is a signed in developer
b. retrieve router ip from k8s
3. `proxy_pass` to router IP returned from router-resolver in $namespace which proxies to $service in $namespace
This changes the flow to:
1. gateway receives request for `internal.hail.is/$namespace/$service`
2. request to auth that the user is a signed in developer
3. `proxy_pass` to $service in $namespace
This does impose the restriction that there is an equivalence between subdomains and k8s Services. For the most part we enforce this just by convention, with the exception of …

[gateway] Cut out router and router-resolver from gateway internal routing

---

hail/python/hail/docs/datasets/schemas/panukb_ld_scores_AFR.rst
hail/python/hail/docs/datasets/schemas/panukb_ld_scores_AMR.rst
hail/python/hail/docs/datasets/schemas/panukb_ld_scores_CSA.rst
hail/python/hail/docs/datasets/schemas/panukb_ld_scores_EAS.rst
hail/python/hail/docs/datasets/schemas/panukb_ld_scores_EUR.rst
hail/python/hail/docs/datasets/schemas/panukb_ld_scores_MID.rst
hail/python/hail/docs/datasets/schemas/panukb_ld_variant_indices_AFR.rst
hail/python/hail/docs/datasets/schemas/panukb_ld_variant_indices_AMR.rst
hail/python/hail/docs/datasets/schemas/panukb_ld_variant_indices_CSA.rst
hail/python/hail/docs/datasets/schemas/panukb_ld_variant_indices_EAS.rst
hail/python/hail/docs/datasets/schemas/panukb_ld_variant_indices_EUR.rst
hail/python/hail/docs/datasets/schemas/panukb_ld_variant_indices_MID.rst
hail/python/hail/experimental/datasets.json

Make available [pan-ukb datasets](https://pan.ukbb.broadinstitute.org/docs/hail-format) via datasets API.
Includes:
- Summary statistics MatrixTable, meta-analysis MatrixTable (both on GCS and S3)
- LD score Table, variant index table, and LD BlockMatrix for each population (AFR, AMR, CSA, EAS, EUR, MID) (S3 only)

[datasets] add pan-ukb datasets

---

hail/src/main/scala/is/hail/expr/AnnotationImpex.scala
hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala

We don't test the logs, but I did test this manually, it works as
expected.

[query] Add json warn context to `parse_json`

---

libhail/CMakeLists.txt
libhail/src/hail/allocators.cpp
libhail/src/hail/allocators.hpp
libhail/src/hail/format.cpp
libhail/src/hail/format.hpp
libhail/src/hail/hash.hpp
libhail/src/hail/main.cpp
libhail/src/hail/query/backend/compile.cpp
libhail/src/hail/query/backend/compile.hpp
libhail/src/hail/query/backend/jit.cpp
libhail/src/hail/query/backend/jit.hpp
libhail/src/hail/query/backend/stype.cpp
libhail/src/hail/query/backend/stype.hpp
libhail/src/hail/query/backend/svalue.cpp
libhail/src/hail/query/backend/svalue.hpp
libhail/src/hail/query/ir.cpp
libhail/src/hail/query/ir.hpp
libhail/src/hail/query/ir_type.cpp
libhail/src/hail/query/ir_type.hpp
libhail/src/hail/runtime/runtime.cpp
libhail/src/hail/runtime/runtime.hpp
libhail/src/hail/tunion.hpp
libhail/src/hail/type.cpp
libhail/src/hail/type.hpp
libhail/src/hail/value.hpp
libhail/src/hail/vtype.hpp

And lots of other things along the way.  Summary of changes:
- Add RawArenaAllocator
- Add runtime to call arena allocate from generated code
- Support MakeTuple, GetTupleElement
- Intern STypes, add STypeContext
- Add EmitValue.cast_to, SType.{load_from_address, construct_from_value, construct_at_address_from_value}
- Add SType.get_memory_size, only works for types for which is_heap_stype<T>() is true
- Use phi nodes to implement EmitValue.as_data()
- isa now calls T::is_instance_tag rather than checking tag directly

[cpp] add support for tuple

---

libhail/CMakeLists.txt
libhail/src/hail/format.cpp
libhail/src/hail/format.hpp
libhail/src/hail/main.cpp
libhail/src/hail/test.cpp
libhail/src/hail/test.hpp
libhail/src/hail/test_value.cpp
libhail/src/hail/value.hpp

Very preliminary.  Builds test instead of main by default, output looks like this:
```
~/hail/libhail/build$ ./test
RUN test_int64_value
RUN test_int64_value OK
RUN test_int32_value
RUN test_int32_value OK
RUN test_bool_value
RUN test_bool_value OK
...
```
Added `std::string render(...)` to format module.  Added some format tests.  Added `CHECK_EQ` macro that prints the details on failure:
```
../src/hail/test.hpp:42: assert failed:
CHECK_EQ(render(FormatAddress(nullptr)), "0x0000000000000000")
with values:
CHECK_EQ(0000000000000000, 0x0000000000000000)
```

[libhail] Add simple testing infrastructure

---

notebook/deployment.yaml

This must have been skipped or lost in a rebase but keeping the resources at minimum is keeping the notebook deployment at max replicas after the workshop. Giving a bit higher request (what I set as the baseline in #10117) should encourage k8s to downscale back to 3 replicas.

[notebook] fix resource requests so deployment can downscale

---

build.yaml
dev-docs/tls.md
notebook/Dockerfile.nginx
notebook/Makefile
notebook/deployment.yaml
notebook/nginx.conf
notebook/notebook/notebook.py
notebook/proxy.conf
router/deployment.yaml
router/router.nginx.conf.in
tls/config.yaml

This moves the nginx proxy configuration out of router and into a sidecar in the notebook/workshop pod. This extends TLS termination from router to the notebook pod and consolidates the notebook routing logic. I didn't run a scale test but this doesn't change any functionality, and I tested in dev that I could log in to a workshop, start and open a notebook.

[notebook] Move notebook and workshop nginx to sidecar

---

hail/python/test/hail/expr/test_ndarrays.py
hail/src/main/scala/is/hail/expr/ir/Emit.scala

I'm not sure this is the right fix.  The segfault was coming from dgeqrf itself, and it was happening only when `N` is 0 (`M` being 0 was fine). The real issue is that when `N` is 0, LAPACK computes `LWORK` to be 0, meaning we don't actually allocate any memory for the `WORK` array and we segfault. To contrast, if I do a workspace size query for shape `(0, 10)`, I get `320` for `LWORK`. This also seems wrong though, as you shouldn't really need any work space for an empty matrix? 
Anyway, the segfault preventing fix was just to make sure LWORK was at least 1. I was hoping you (Patrick) could use Julia interface to play with the LAPACK functions and see what behavior you notice, and if it's consistent with the above.

[query] Fixed bug where hl.nd.qr didn't support 0 elements

---

hail/python/hail/methods/pca.py

We use Q twice if someone wants to compute the loadings, so we want to save it to avoid redoing full QR.

[query] NDArray based PCA Performance Fix. Discard R, persist Q

---

build.yaml
ci/test/resources/config.yaml
tls/config.yaml
tls/create_certs.py
website/deployment.yaml
website/website/website.py

website is the only service that doesn't follow the subdomain == base_path convention, nor does the subdomain match the k8s service, which is website. This enforces that by adding a `www` k8s service and changes the base_path in `website.py`.

[website] make www the website service and base path

---

batch/batch/front_end/templates/billing_projects.html

We were able to realign the users back to a vertical stack and increased the rowspan for each billing project to compensate for the `tr` of the billing project name.
HTML tables are reorganized somewhere along the way to the browser to not have nested rows. The template previously had 1 `tr` per billing project, which contained 3 `td`s, and then the user `td` had nested `tr`s. Inspecting on the dev console showed that each `tr` was pulled to the top level of the corresponding `tbody`, meaning that in total the number of `tr`s per billing project is
- 1 for the name and close button +
- `billing_project.size` user rows +
- 1 for the add button
So we changed the organization of the `tbody`s to not have nested `tr`s and adjusted the `rowspan` accordingly.
@CDiaz96

[batch] fix table row templating

---

hail/python/hailtop/hailctl/dev/config/show.py

`hailctl dev config show` is currently inconsistent with the verbiage used
to change those variables. This change ensures `hailctl dev config set k v`
is displayed as `k: v`.

[hailctl] use consistent names for variables

---

hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala

`IOUtils.toString(InputStream, Charset)` was only introduced in a later version of `commons-io` than we're stuck with because of Indeed's lsmtree. This workaround uses a method that we do have access to.

[query] use other IOUtils.toString method

---

website/website/styles/style.scss

When I unified the CSS for the docs and the website, every block quote in
the docs (including all bulleted lists) received a border. `style.css` originally
came from the main Hail website (https://hail.is, https://hail.is/references.html, etc.).
I cannot find any place where we needed a border around a blockquote, so I
have removed the blockquote border rules and consolidated the pre rules into
one block.
@CDiaz96, can you check out this branch, run the website locally and poke around and make sure everything looks OK to you? The main page, the references.html page, etc. should all look these same as https://hail.is. The docs for PC Relate (currently deployed: https://hail.is/docs/0.2/methods/relatedness.html#hail.methods.pc_relate; URL for your laptop …

[docs][website] remove border around blockquote

---

hail/Makefile
hail/build.gradle

Naturally, every possible Spark version uses a different elasticsearch library. 
This also uses curl instead of gsutil to download the jar, so we don't require people to have gsutil to make.

Different elasticsearches per Spark version

---

hail/python/hail/methods/pca.py

From testing in Julia, I think this is critical for accuracy.

[query] pca: orthogonalize on every iteration

---

docker/Makefile

I screwed this up when i added service-java-run-base. I meant to put hail_version
at the root of the Docker context (in this case, the root of the hail repo).

[docker] fix Makefile

---

notebook/nginx.conf
notebook/notebook/notebook.py

Realized that the notebook python app should in fact speak https because it is exposed on the pod even though it does not have a service in front of it. For example, prometheus scrapes all visible ports on a pod and it anticipates https. This was triggering the deluge of errors from notebook and deploying this into default seems to have stopped them.

[notebook] make notebook python https and fix metrics endpoint

---

dev-docs/development_process.md

re: conversation over Zulip. ci.hail.is/me now includes PRs where you've been requested as a reviewer, not just assigned.

[dev-docs] update PR process

---

hail/build.gradle

Spark imports json4s but excludes its dependency, com.fasterxml.jackson.core:jackson-databind. We should do the same when shadowing json4s.

Fix handling of jackson-databind

---

query/query/query.py

asyncio.wait takes an [iterable of Tasks](https://docs.python.org/3/library/asyncio-task.html#waiting-primitives)

[query] fix asyncio.wait call in shutdown

---

hail/build.gradle

The changelog for [6.0.0](https://github.com/johnrengelman/shadow/releases/tag/6.0.0) claims performance improvements. In practice,
I save maybe a few second on the `shadowJar` step.

[gradle] update shadow plugin

---

hail/python/hail/methods/pca.py
hail/python/test/hail/methods/test_pca.py

This flips the pca algorithm, so that we're locally collecting a Krylov space basis on the column side (presumably the smaller side). This leads to a few simplifications, and allows for an optimization in the `compute_loadings=False` case. Once we have a complete TSQR implementation, we can optimize the `compute_loadings=True` case as well. With that, there should be no memory limitation to the number of rows (no local value is O(rows)).

[query] pca simplification/optimization

---

prometheus/prometheus.yaml

I think prometheus got forcibly shutdown and its volume got corrupted, which caused it to fail on startup. I had to wipe the volume. Starting with a new volume introduced permissions issues, I think because that volume claim might still have been there from the original time we were running prometheus.. Either way I was able to get this up and running in default. I had wanted to extend the retention time so we can see a full month of metrics instead of just two weeks, so I'm being extra nice with the volume and moving prometheus off of preemptibles in default.

[prometheus] fix prometheus permissions and make non-preemptible in prod

---

build.yaml
ci/create_database.py
dev-docs/tls-cookbook.md
devbin/functions.sh
tls/create_certs.py

For some reason we delete secrets when re-creating them. This creates a race condition which Batch
appears to encounter whenever it is under heavy load during a deploy.
@cseed, do you recall why you chose to delete and then use apply in ci/create_database.py?
I am using the command sequence suggested here: https://stackoverflow.com/questions/45879498/how-can-i-update-a-secret-on-kubernetes-when-it-is-generated-from-a-file.

[k8s] never delete a secret

---

batch/batch/worker/worker.py

I broke this in a previous PR. It causes mark_job_started to fail because
there is no `self.proc` yet.

[batch] fix exit_code computation in worker

---

ci/ci/ci.py
ci/ci/constants.py
ci/ci/github.py

Outside collaborators have virtually no powers on the right-hand side of the PR page w.r.t. reviewers/assignees/labels, so this is my best shot at letting them get someone assigned on their PRs. If a PR does not have any assignees or reviewers, but has #assign services or #assign compiler in the PR body, CI will randomly select a collaborator from those teams and assign them (including both will assign one person from each). Outside collaborators can re-request reviews, so I think this solves the PR review problem.

[ci] auto-assign member from team using #assign comment in PR body

---

hail/python/test/hail/experimental/test_experimental.py
hail/src/main/scala/is/hail/annotations/RegionPool.scala
hail/src/main/scala/is/hail/annotations/UnsafeRow.scala
hail/src/main/scala/is/hail/expr/ir/Emit.scala
hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala
hail/src/main/scala/is/hail/lir/X.scala
hail/src/test/scala/is/hail/TestUtils.scala
hail/src/test/scala/is/hail/expr/ir/IRSuite.scala

This PR changes the way loop memory management works.  
Previously, memory used while in the loop was allocated in one region, with no cleanup happening between loops. A long running loop that did a lot of allocation could therefore easily cause hail to run out of memory. This PR fixes that by creating two regions for each loop. Every iteration, we emit everything in region 1, copy the state that is necessary to region 2, then clear region 1. Then we swap the regions and repeat this until the loop terminates.

[query] Loop memory management
