hail/src/main/scala/is/hail/annotations/RegionMemory.scala, hail/src/main/scala/is/hail/annotations/RegionPool.scala, hail/src/main/scala/is/hail/sparkextras/ContextRDD.scala
=> Revert "[query] Move spark region finalization from ContextRDD to RegionPool"

benchmark/scripts/benchmark_in_pipeline.py
WIP while I wait for benchmarks to succeed with this change
=> [benchmark] Combine files hierarchically

hail/Makefile, hail/python/hail/docs/change_log.md
=> [release] Update changelog for 0.2.36

hail/src/main/scala/is/hail/expr/ir/functions/ArrayFunctions.scala, hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala, hail/src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala, hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala, hail/src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala, hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala, hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
Rename only
git grep -l 'registerCodeWithMissingness' | xargs sed -i 's/registerCodeWithMissingness/registerEmitCode/g'
=> [query/pcode] Rename registerCodeWithMissingness to registerEmitCode

gateway/gateway.nginx.conf, router-resolver/router_resolver/router_resolver.py
I've already deployed these changes.
Without these changes, I've locked myself out of my dev namespace because my dev namespace refuses to speak HTTP now (😄).
=> [router][gateway] Support https routers

ci/ci/ci.py
This is developer only and helpful primarily in dev deploy.
I think its safe as long as we trust hail devs not to
accidentally hit this endpoint.
=> [ci] add manual developer triggered update

hail/python/hail/docs/_templates/layout.html, hail/www/template.xslt
Forgot that we were importing navbar.css. We could go back to a separate navbar.css, but I think that is less optimal because I don't think you can include the html directly in xslt, and importing it using jquery can cause the navbar to flash immediately after page load.
=> [www] fix docs navbar

batch/test/serverthread.py, batch/test/test_batch.py, hail/python/hail/backend/backend.py, hail/python/hail/experimental/db.py, hail/python/hailtop/utils/__init__.py, hail/python/hailtop/utils/utils.py
We were not handling non-success HTTP resposnes. This fixes that
=> [batch][hail][ci] fix retrying logic

hail/src/main/scala/is/hail/expr/ir/AbstractMatrixTableSpec.scala, hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala, hail/src/main/scala/is/hail/expr/ir/Parser.scala, hail/src/main/scala/is/hail/expr/ir/Simplify.scala, hail/src/main/scala/is/hail/expr/ir/TableIR.scala, hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala, hail/src/main/scala/is/hail/rvd/RVDPartitioner.scala, hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
Exact same thing I just did for read_table.
=> [query service] read_matrix_table example works

ci/wait-for.py
This is unused. Not sure what it was for. It adds some complication to
TLS-everywhere due to the schemes in the `internal_base_url`.
=> [ci] remove wait-for.py .. service

hail/src/main/scala/is/hail/asm4s/CodeBuilder.scala, hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/agg/CallStatsAggregator.scala, hail/src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala, hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala, hail/src/main/scala/is/hail/expr/types/physical/PCanonicalArray.scala, hail/src/main/scala/is/hail/expr/types/physical/PCanonicalCall.scala, hail/src/main/scala/is/hail/expr/types/physical/PCode.scala
It's not really 'memoization' when it takes arbitrary initialization
code.
=> [query] Rename CodeBuilder.memoize

hail/build.gradle
Protectes from (unlikely) man in the middle attacks on our infrastructure.
=> [hail] use TLS to speak to maven repos

datasets/extract/extract.CADD_v1.4_GRCh37.sh, datasets/extract/extract.CADD_v1.4_GRCh38.sh
This server speaks TLS 1.2 (verified with cURL).
=> [datasets api] switch to https for downloading CADD

ci/create_database.py
I find this structure a bit easier to understand. If we write or copy a file
we add the file to the list of files first.
=> [ci] cleanup create_database.py

router/router.nginx.conf.in
It's already gone, this just removes it from the router.
=> [router] remove dbuf

hail/src/main/scala/is/hail/expr/ir/Children.scala, hail/src/main/scala/is/hail/expr/ir/Copy.scala, hail/src/main/scala/is/hail/expr/ir/EmitStream.scala, hail/src/main/scala/is/hail/expr/ir/IR.scala, hail/src/main/scala/is/hail/expr/ir/InferPType.scala, hail/src/main/scala/is/hail/expr/ir/InferType.scala, hail/src/main/scala/is/hail/expr/ir/Interpret.scala, hail/src/main/scala/is/hail/expr/ir/Parser.scala, hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala, hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala, hail/src/main/scala/is/hail/expr/ir/add-ir-checklist.txt, hail/src/test/scala/is/hail/expr/ir/IRSuite.scala, hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
=> [query] add StreamTake node

ci/ci/ci.py
Every other BatchClient user does this.
=> [ci] let BatchClient construct the aiohttp session

benchmark/python/benchmark_hail/compare/cli.py, benchmark/python/benchmark_hail/compare/compare.py
=> [benchmark] Use 'median' for benchmark default metric

hail/src/main/scala/is/hail/expr/ir/Children.scala, hail/src/main/scala/is/hail/expr/ir/Copy.scala, hail/src/main/scala/is/hail/expr/ir/EmitStream.scala, hail/src/main/scala/is/hail/expr/ir/IR.scala, hail/src/main/scala/is/hail/expr/ir/InferPType.scala, hail/src/main/scala/is/hail/expr/ir/InferType.scala, hail/src/main/scala/is/hail/expr/ir/Interpret.scala, hail/src/main/scala/is/hail/expr/ir/Parser.scala, hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala, hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala, hail/src/test/scala/is/hail/expr/ir/IRSuite.scala, hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
=> [query] add StreamDrop node

hail/python/test/hail/expr/test_expr.py, hail/src/main/scala/is/hail/variant/VariantMethods.scala
=> [query] Fix min_rep with nulls

hail/src/main/scala/is/hail/expr/ir/EmitStream.scala, hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
This adds an implementation for grouping a stream into nested streams of equal size. I've called it `grouped`, following Scala. Note this is just the codegen implementation, it doesn't add an IR node. For `EmitStream` to return a nested stream will require adding a stream PCode.
=> [query] implement Stream.grouped

hail/src/main/scala/is/hail/asm4s/CodeBuilder.scala, hail/src/main/scala/is/hail/asm4s/FunctionBuilder.scala, hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala, hail/src/main/scala/is/hail/expr/types/physical/PCanonicalArray.scala, hail/src/main/scala/is/hail/expr/types/physical/PCanonicalBaseStruct.scala, hail/src/main/scala/is/hail/expr/types/physical/PCanonicalBinary.scala, hail/src/main/scala/is/hail/expr/types/physical/PCanonicalCall.scala, hail/src/main/scala/is/hail/expr/types/physical/PCanonicalInterval.scala, hail/src/main/scala/is/hail/expr/types/physical/PCanonicalLocus.scala, hail/src/main/scala/is/hail/expr/types/physical/PCode.scala, hail/src/main/scala/is/hail/expr/types/physical/package.scala
WIP. Need to figure out addLiteral for DependentEmitFunction.
=> [query/pcode] addLiteral returns PValue, literalMap stores PSettable

router-resolver/router_resolver/router_resolver.py
Currently, the router-resolver returns 500 if the session id is invalid. Instead,
it should return 401. This collapses two states: not authorized due to not being
a developer and not authorized due to not being logged in. This is unfortunate, but
we should avoid leaking information as to *why* this endpoint is unauthorized to
an attacker. Developers, presumably, are knowledgable enough to figure out why
they cannot log in on their own.
=> [router-resolver] unauthorized also means not developer

hail/src/main/scala/is/hail/expr/ir/IR.scala, hail/src/main/scala/is/hail/expr/ir/InferPType.scala, hail/src/main/scala/is/hail/expr/ir/InferType.scala, hail/src/main/scala/is/hail/expr/types/encoded/EBaseStruct.scala, hail/src/main/scala/is/hail/expr/types/virtual/TStruct.scala
Based on https://dev.hail.is/t/proposal-shuffler-ir/187/4
=> [hail] Shuffler IR

hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
Fixes #8587
Fixes #8586
See issues and related github.com/hail-is/jgscm changes
=> [jgscm][notebook][dataproc] new jgscm to address severe slowness

hail/src/main/scala/is/hail/expr/types/TypeWithRequiredness.scala, hail/src/main/scala/is/hail/expr/types/package.scala, hail/src/main/scala/is/hail/expr/types/virtual/TypeWithRequiredness.scala
Introduces a TypeWithRequiredness class to carry requiredness information for analysis.
=> [query] introduce TypeWithRequiredness

build.yaml
The wheel container prevents this image from ever being cached.
=> [images] only build images on deploy or dev

build.yaml, docker/hail/Dockerfile
This ensures we get hail from pip.
=> [hail_public_image] directly depend on hail_pip_version

hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
=> [query] Uncomment PruneSuite

hail/src/main/scala/is/hail/expr/ir/Children.scala, hail/src/main/scala/is/hail/expr/ir/Copy.scala, hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/EmitStream.scala, hail/src/main/scala/is/hail/expr/ir/IR.scala, hail/src/main/scala/is/hail/expr/ir/InferPType.scala, hail/src/main/scala/is/hail/expr/ir/InferType.scala, hail/src/main/scala/is/hail/expr/ir/Interpret.scala, hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala, hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala, hail/src/main/scala/is/hail/expr/types/physical/PType.scala, hail/src/test/scala/is/hail/expr/ir/IRSuite.scala, hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
=> [query] StreamGroupByKey node

docker/Makefile, hail/python/hail/backend/backend.py, hail/python/hail/fs/google_fs.py, hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala, hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala, query/query/query.py
HailException and LowererUnsupportedOperation get returned as 400 with the error message,
other exceptions as 500 with stack trace.
Also, some docker fixes.  @jigold, I think this might explain why deploying from your computer is so slow.  Docker includes the file permissions in the metadata when checking the image cache.  The CI uses umask 022 (group not writable).  I changed up my computer, and noticed everything was being rebuilt from scratch (requiring me to push massive images).  I added some checks in docker/Makefile that the expectations for the image.  I couldn't find a way to fix this globally.  If the checks trigger, I think the solution is to set your umask to 022 going forward and chmod -R g-w your Hail source tree.
=> [query service] propagate exceptions

hail/src/main/scala/is/hail/asm4s/CodeBuilder.scala, hail/src/main/scala/is/hail/expr/ir/Emit.scala
Also move mapN to an IEmitCode method.
=> [query] Move NDArrayRef to emitI

hail/python/hail/docs/cloud/other_cloud_providers.rst
Add link to documentation for setting up a hail-capable cluster on Microsoft Azure HDInsight
=> Add Microsoft Azure Link

hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala, hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
This will allow us to begin porting to IEmitCode in the function
registry.
=> [query/pcode] Add registerIEmitCode

auth/auth/auth.py, auth/auth/templates/copy-paste-token.html, auth/sql/copy-paste-tokens.sql, auth/sql/delete-auth-tables.sql, auth/sql/estimated-current.txt, batch/batch/driver/instance_pool.py, batch/batch/driver/main.py, batch/batch/driver/scheduler.py, batch/batch/spec_writer.py, build.yaml, gear/gear/__init__.py, gear/gear/auth_utils.py, hail/python/hailtop/auth/__init__.py, hail/python/hailtop/auth/auth.py, hail/python/hailtop/hailctl/auth/cli.py, hail/python/hailtop/hailctl/auth/copy_paste_login.py, hail/python/hailtop/hailctl/curl.py, hail/python/hailtop/utils/__init__.py, hail/python/hailtop/utils/utils.py, hail/python/setup-hailtop.py, hail/python/setup.py, notebook/notebook/templates/user.html
```
Logged into namespace dking as dking.
```
It is safe to reprint this token because it is not only expired but already used. Tokens live for 5 minutes and can be used only once. You can try logging in with that token (to dking's auth) to see for yourself.
The user page now includes a button to retrieve a fresh copy-paste token:
This sends you to a rather ugly page that includes a base32 encoded (dashes create word breaks which makes highlighting annoying, so I preferred base32 over base64) token. That token is good for 5 minutes. You copy that token and log in as above.
=> Copy paste login

hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala, hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
Wasn't worth trying to salvage/rebase #8605 after several changes were made to `LowerTableIR`, just redid it.
=> [query][lowering] `TableRename` Lowering, Redo

batch/batch/front_end/front_end.py, batch/batch/utils.py, batch/batch/worker.py, batch/test/test_batch.py, batch/test/test_utils.py, build.yaml, hail/python/hailtop/batch/docs/service.rst
=> [batch] round up cores request to nearest power of two

hail/src/main/scala/is/hail/expr/types/encoded/EArray.scala, hail/src/main/scala/is/hail/expr/types/encoded/EBaseStruct.scala, hail/src/main/scala/is/hail/io/MemoryBuffer.scala, hail/src/test/scala/is/hail/expr/ir/ETypeSuite.scala
High prio because this fixes bugs Dan is hitting in shuffler work.
=> [query] Fix bugs in encoding/decoding when requiredness doesn't match

hail/python/hail/experimental/vcf_combiner/__main__.py, hail/python/hail/experimental/vcf_combiner/vcf_combiner.py, hail/python/test/hail/experimental/test_vcf_combiner.py
Ruchi and Sam need this functionality to avoid an unnecessary scan.
=> [vcf-combiner] Add option to key by both locus and alleles

hail/src/main/scala/is/hail/io/InputBuffers.scala, hail/src/main/scala/is/hail/io/OutputBuffers.scala, hail/src/main/scala/is/hail/io/package.scala
=> [hail][io] implement read/write UTF

hail/src/main/scala/is/hail/expr/types/encoded/EType.scala, hail/src/main/scala/is/hail/io/TypedCodecSpec.scala
This will be used by the Shuffler.
=> [hail][etype] teach EType how to make OutputBuffer => Encoder

hail/python/Makefile, hail/python/hail/table.py
except for a message around spacing in parameters with type hints and
default values that I'm not quite sure how to resolve.
I couldn't help myself.
=> [hail] table.py now passes flake8

hail/python/hail/docs/cloud/google_cloud.rst
=> Added GCS Connector instructions and information

hail/python/hail/matrixtable.py
=> [query] fix lint errors in matrixtable.py

hail/python/hail/docs/getting_started.rst
Somehow duplicated the apt-get here
=> [hail][docs] fix getting started apt-get

hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
With this added context it was completely obvious what I had done wrong. Without
this context, I just knew that somewhere I had some ints and structs that did not
unify.
=> [hail][ir] improve error message when unify fails in PruneDeadFields

hail/src/main/scala/is/hail/expr/types/TypeWithRequiredness.scala
I also converted a no-message assertion into an if with an AssertionError
because I found it difficult to debug without the added information.
This removes the duplication of the list of supported types for RPrimitive.
=> [hail] refactor RPrimitive.typeSupported

hail/python/hailtop/utils/__init__.py, hail/python/hailtop/utils/rates.py
Unfortunately, I can't dev deploy the rest of the resources branch until this is merged. I need these functions in the services-base image as that's what CreateDatabase uses to run the migration scripts.
=> [hailtop] Add rate conversions to hailtop.utils

batch/batch/front_end/templates/batch.html, batch/batch/front_end/templates/batches.html, batch/batch/front_end/templates/billing.html, batch/batch/front_end/templates/billing_projects.html, batch/batch/front_end/templates/job.html, web_common/web_common/templates/layout.html
The CSS makes some strong statements about how the web browser should display it. I
removed all these statements which lets the web browser choose if it should wrap some
in-cell text, truncate the table, or expand the table.
I fixed some bad formatting and removed tabs (😱) from some pages.
Check my dev deploy: https://internal.hail.is/dking/batch
=> [batch][ui] let the web browser choose the table size and make / focus search

batch/batch/front_end/front_end.py, ci/ci/ci.py, ci/ci/templates/job.html, hail/python/hailtop/batch_client/aioclient.py, hail/python/hailtop/batch_client/client.py
I'm sorry the diff ended up more complicated than necessary for this.
=> [batch,ci] expose attempts to clients and ci

auth/auth/driver/driver.py, auth/deployment.yaml, batch/batch/driver/main.py, hail/python/hailtop/aiogoogle/__init__.py, hail/python/hailtop/aiogoogle/auth/session.py, hail/python/hailtop/aiogoogle/client/__init__.py, hail/python/hailtop/aiogoogle/client/iam_client.py
The remaining clients are storage and auth (for the auth flow in auth/hailctl).  I don't know if I'll redo the auth flow.
=> [aiogoogle, auth] add IAmClient, use in auth-driver

batch/batch/driver/instance_pool.py
This is fully resolved by https://github.com/hail-is/hail/pull/8777, but we need this fix
to unbreak the driver until that PR gets in.
=> [batch][hotfix] address driver looping failure

batch/batch/worker.py
This moves `self.activate` into a `wait_for` with a timeout. We use a tight try-except
around the activation code to provide a precise error message if activation fails.
If activation succeeds, we enter the else branch which operates as before. If activation
times out we do not deactivate. This is OK, we probably did not activate. If we did activate,
batch will eventually find out.
=> [batch] timeout for worker activation

hail/python/hail/__init__.py, hail/python/hail/docs/conf.py, hail/python/hail/experimental/datasets.py, hail/python/hail/experimental/full_outer_join_mt.py, hail/python/hail/experimental/interact.py, hail/python/hail/experimental/ld_score_regression.py, hail/python/hail/experimental/ldscore.py, hail/python/hail/experimental/ldscsim.py, hail/python/hail/experimental/loop.py, hail/python/hail/expr/__init__.py, hail/python/hail/expr/blockmatrix_type.py, hail/python/hail/expr/functions.py, hail/python/hail/expr/matrix_type.py, hail/python/hail/expr/table_type.py, hail/python/hail/expr/types.py, hail/python/hail/genetics/locus.py, hail/python/hail/genetics/pedigree.py, hail/python/hail/methods/family_methods.py, hail/python/hail/methods/impex.py, hail/python/hail/methods/misc.py, hail/python/hail/methods/qc.py, hail/python/hail/methods/statgen.py, hail/python/hail/typecheck/check.py, hail/python/hail/utils/linkedlist.py, hail/python/hail/utils/misc.py, hail/python/hail/utils/tutorial.py
I'm down to about 350 issues.  The next one will probably be the last one.
=> [query] delint 8

web_common/web_common/styles/main.scss
=> Fix nth of type

hail/python/hail/expr/functions.py, hail/python/test/hail/expr/test_functions.py, hail/src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala, hail/src/main/scala/is/hail/stats/package.scala
=> [query] Noncentral Chi-Square option in pchisqtail

ci/create_database.py
Five things may already exist:
- creating the database
- creating the admin or user user
- creating the admin or user secret
Creating the database is now idempotent with `IF NOT EXISTS`.
Creating a user is idempotent because we create a user with a random name. If
we're racing with someone else, the database might have extra users
created.
Finally, we race to create the secrets. Whoever runs last wins the race and
their secret create is the one downstream tasks see. Secret creation was made
idempotent by using `create --dry-run` piped to `apply`. Apply does not fail if
the secret already exists, it merely updates it. In a sense, apply is an atomic
create-or-update.
=> [ci][build] do not fail if database already exists

ci/create_database.py
SQL Syntax was wrong. https://dev.mysql.com/doc/refman/5.7/en/create-database.html
=> [ci] fix create database fixing ci

ci/create_database.py
=> [ci] revert db idempotency

ci/ci/build.py
Otherwise, we might leave namespaces up
=> [ci] retry ci cleanup forever

batch/batch/front_end/templates/job.html, ci/ci/templates/job.html
I was seeing Reason: None.
This is probably overkill but it seems safest.  We should probably do it consistently.
=> [ci] fix formatting of attempts table in jobs page

hail/src/main/scala/is/hail/asm4s/CodeBuilder.scala
Add a whileLoop overload that takes a label, pass the start label to it.
=> [query] Teach CodeBuilder.whileLoop how to continue

hail/python/hailtop/hailctl/dev/deploy/cli.py
Previously we get a stack trace without the http response body. I tested this
locally on a branch that does not exist:
HTTP Response code was 400
error finding {"repo": {"owner": "danking", "name": "hail"}, "name": "shuffler-deploymefdsafdsa"} at GitHub
=> [hailctl][devdeploy] improve error messages

hail/python/hail/backend/backend.py, hail/python/hail/backend/service_backend.py, hail/python/hail/backend/spark_backend.py, hail/python/hail/context.py, hail/python/hail/experimental/import_gtf.py, hail/python/hail/experimental/plots.py, hail/python/hail/expr/expressions/expression_utils.py, hail/python/hail/expr/expressions/typed_expressions.py, hail/python/hail/expr/functions.py, hail/python/hail/genetics/pedigree.py, hail/python/hail/hail_logging.py, hail/python/hail/matrixtable.py, hail/python/hail/methods/impex.py, hail/python/hail/methods/statgen.py, hail/python/hail/plot/plots.py, hail/python/hail/table.py, hail/python/hail/utils/__init__.py, hail/python/hail/utils/java.py
This fixes `balding_nichols_model` in the service.
I also fixed warn => warning. Warn is deprecated in Python's logging library.
=> [hail] logger comes from Backend

hail/www/index.xslt
CHANGELOG: remove learn more, which should not have gone in until the learn more content was finalized.
=> remove learn more

hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala, hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
Also add more typechecking throughout. Might need to disable that.
=> [query] Fix MakeNDArray prune rules

batch/Makefile, batch/batch/driver/instance_pool.py, batch/build-batch-worker-image-startup.sh
- changed worker image from batch-worker-7 to batch-worker-8
- upgraded version of ubuntu from ubuntu-minimal-1804-bionic-v20191024 to ubuntu-minimal-1804-bionic-v20200520
- upgraded docker 
- added debug = true mode to docker daemon
=> [batch] upgrade disk image and add dockerd debug mode

hail/src/main/scala/is/hail/expr/ir/GenericLines.scala, hail/src/main/scala/is/hail/utils/TextTableReader.scala
Haven't tested at all yet, expect there will be things to fix.
=> [hail] switch import table impute to go through generic lines

hail/python/hail/docs/cloud/google_cloud.rst, hail/python/hail/methods/qc.py
Crosslink to dataproc docs that explain how to start a VEP cluster, mention that the config info is not necessary if you're using dataproc
=> Improve VEP Docs

hail/src/main/scala/is/hail/HailContext.scala, hail/src/main/scala/is/hail/expr/ir/GenericLines.scala, hail/src/main/scala/is/hail/io/fs/FS.scala, hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala, hail/src/main/scala/is/hail/io/fs/HadoopFS.scala, hail/src/main/scala/is/hail/io/tabix/TabixReader.scala, hail/src/main/scala/is/hail/utils/TextTableReader.scala, hail/src/test/scala/is/hail/fs/FSSuite.scala, hail/src/test/scala/is/hail/utils/UtilsSuite.scala
The build will fail until TextMatrixReader is fixed.
=> [hail] remove maybeGZipAsBGZip

hail/python/hail/experimental/import_gtf.py
CHANGELOG: Substantially improve the performance of `import_gtf`.
=> [hail] improve import_gtf performance

hail/python/hail/docs/functions/index.rst, hail/python/hail/docs/functions/random.rst, hail/python/hail/expr/__init__.py, hail/python/hail/expr/functions.py, hail/python/test/hail/expr/test_functions.py
CHANGELOG: added shuffle function
=> [hail] add hl.shuffle

hail/python/hailtop/batch/docs/service.rst
Need objectAdmin to be able to delete files.
=> [batch] fix service account directions to set objectAdmin

hail/python/test/hail/table/test_table.py, hail/src/main/scala/is/hail/expr/ir/TableIR.scala
In a TableValue, the RVD key may be longer than the TableType key, so it's wrong for the row type of the result of a TableIR execute to depend on the RVD key. I tried to find all cases of this error in TableIR execute methods, and only found these two.
=> [query] fix incorrect uses of RVD key in TabeIR

batch/batch/batch.py, batch/batch/front_end/front_end.py
I think I got all of the fixes. I tested the UI with dev deploy.
=> [batch] fix queries for listing jobs and batches

hail/src/main/scala/is/hail/expr/ir/FoldConstants.scala, hail/src/test/scala/is/hail/expr/ir/FoldConstantsSuite.scala
should fix your error from friday, Dan.
=> [query] Don't fold agg lets

hail/python/hail/experimental/vcf_combiner/vcf_combiner.py
CHANGELOG: Refactored VCF combiner to support other GVCF schemas.
=> [vcf-combiner] Refactor VCF combiner to support other GVCF schemas.

ci/ci/build.py, ci/create_database.py
Database idempotency is easy, use `IF NOT EXISTS`. User cleanup is hard because
the job isn't deterministic. Each attempt will produce a different password. You
cannot retrieve a password of an extant user.
The bulk of the changes are in service of creating a job whose attempts will
race to create the password. Only one attempt will win that race and pass its
password on to the `create_database_job`. Those jobs will race to create
databases and users and secrets, but all those operations are now
idempotent (`CREATE USER` uses `IF NOT EXISTS`; the secret is always the same).
=> [ci] make ci idempotent, try two

hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala, hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala, hail/src/main/scala/is/hail/expr/ir/lowering/LowerToCDA.scala, hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPass.scala
Also rename "LowerIR" to "LowerToCDA"
This is necessary for TableAggregate.
=> [query] Add requiredness analysis to LowerToCDA

batch/batch/driver/instance_pool.py
=> [batch] Fix choosing zone based on cpu rather than mcpu

hail/python/hail/docs/conf.py
Addresses https://github.com/hail-is/hail/issues/8940
=> [docs] fix make-docs

hail/python/hail/docs/_static/rtd_modifications.css, hail/python/hail/docs/_templates/layout.html, hail/python/hail/docs/conf.py, site/www/index.xslt, site/www/navbar.css, site/www/search.xslt, site/www/style.css, site/www/template.xslt
cc @mkveerapen @tpoterba 
1) Adds natural language documentation search bar with autocompletion
2) Adds paginated search page to browse all search results
3) Makes navbar scripts async, to allow inclusion of navbar scripts at top of file without impacting performance (since we include the navbar.html content in other templates we cannot easily locate those scripts at bottom of the includers' pages)
4) Increases hero content width on mobile.
5) Hides sphinx search bar
http://34.207.246.132/
=> [site] add documentation search bar, search page

auth/auth/auth.py, auth/auth/driver/driver.py, auth/auth/templates/user.html, auth/sql/drop-bucket.sql, auth/sql/estimated-current.txt, build.yaml, hail/python/hailtop/batch/backend.py, hail/python/hailtop/batch/docs/service.rst, hail/python/test/hailtop/batch/test_batch.py, notebook/notebook/notebook.py, web_common/web_common/templates/header.html
CHANGELOG: Batch ServiceBackend now requires a bucket for intermediate files, either explicitly or through the batch/bucket config setting
Other changes:
- moved notebook/user to auth/user (more appropriate there)
- auth no longer creates bucket during user creation
=> [various] bring your own bucket (BYOB)

hail/src/main/scala/is/hail/expr/ir/functions/MatrixWriteBlockMatrix.scala, hail/src/main/scala/is/hail/linalg/BlockMatrix.scala
Should solve an issue Masa is running into.
=> [query] Stage files locally in WriteBlocksRDD

site/www/navbar.css
=> [site] remove small caps

ci/ci/constants.py
Added @annamiraotoole to constants.py
=> Add Annamira to constants.py

site/www/gethelp.xslt, site/www/index.xslt, site/www/references.md, site/www/style.css, site/www/tutorial.xslt
Last todo to round out the first phase of web work.
1) Styles references page by adding header and making sure content is centered on wide views
2) Makes get help .about content consistent with tutorial page and home page (using .content)
3) Sets max width to 1521px on non-home pages
stacked on #9005
I will look at any comments on July 1
=> [site] reference styling, more consistent styling elsewhere

hail/python/test/hail/test_memory_usage.py, hail/src/main/scala/is/hail/annotations/Region.scala
1024 seems pretty generous, but I didn't rigorously search for a value.
I do know that when setting 400 million bytes, memset is way faster.
=> [query] test we do not blow memory

hail/python/hail/docs/getting_started.rst
It is not obvious you need to be in the Hail sub-directory.
=> [query] improve getting started

site/www/index.xslt, site/www/style.css, site/www/tutorial.xslt
1) Learn More button shouldn't have target blank; it's a link to a page in the same domain, better to allow forward/back nav and no new window
2) Reference page text would overflow because default word-break is none.
3) Height of blue background to title was constrained to a certain height, and while that helped consistency, it cost inner margin (padding) consistency; tradeoff not worth it
4) Fix code block alignments
=> [site] various fixes

hail/src/main/scala/is/hail/lir/Blocks.scala, hail/src/main/scala/is/hail/lir/CFG.scala, hail/src/main/scala/is/hail/lir/InitializeLocals.scala, hail/src/main/scala/is/hail/lir/Liveness.scala, hail/src/main/scala/is/hail/lir/Locals.scala, hail/src/main/scala/is/hail/lir/SimplifyControl.scala, hail/src/main/scala/is/hail/lir/SplitMethod.scala, hail/src/main/scala/is/hail/lir/X.scala
I also added `Blocks` and `Locals` to package up the blocks and locals.
I need liveness separately in `SplitMethod`.
=>  [query/lir] abstract Liveness from InitializeLocals

build.yaml, hail/python/hailtop/batch/backend.py, hail/python/hailtop/batch/job.py, hail/python/test/hailtop/batch/test_batch.py
CHANGELOG: Added gcsfuse option for the Service Backend.
The only thing I wasn't sure about was whether the default for the read_only should be True or False.
=> [batch] expose gcsfuse to user

hail/src/main/scala/is/hail/backend/local/LocalBackend.scala, hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala, hail/src/main/scala/is/hail/types/TypeWithRequiredness.scala, hail/src/main/scala/is/hail/types/encoded/EType.scala
Also:
- support executing void IR in LocalBackend
- added BaseTypeWithRequiredness.check to verify if a Type and TypeWithR are compatible (uncalled, useful for debugging)
=> [hail] Fix EType.fromTypeAndAnalysis

hail/python/hail/experimental/import_gtf.py
`hl.experimental.import_gtf` is documented as accepting either a string or a `ReferenceGenome` object for its `reference_genome` argument.
However, it actually only works correctly with a string because it compares the `reference_genome` argument to the string "GRCh37" and calls `hl.get_reference` with the `reference_genome` argument.
https://github.com/hail-is/hail/blob/c9b2ddfa92d619d0e4e22a169157853dc391f29a/hail/python/hail/experimental/import_gtf.py#L162-L173
This changes `import_gtf` to accept a string or `ReferenceGenome` by using `typecheck` to cast the argument into a `ReferenceGenome`.
This also corrects the docstring for `_load_gencode_gtf`, which only works with a `ReferenceGenome` because it accesses the `name` property of its `reference_genome` argument. …
=> Accept ReferenceGenome object in import_gtf

hail/python/hail/backend/backend.py, hail/python/hail/backend/local_backend.py, hail/python/hail/backend/service_backend.py, hail/python/hail/backend/spark_backend.py, hail/python/hail/methods/impex.py, hail/src/main/scala/is/hail/backend/local/LocalBackend.scala, hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala, hail/src/main/scala/is/hail/io/plink/LoadPlink.scala, hail/src/main/scala/is/hail/utils/Py4jUtils.scala
import-fam endpoint still mising from query service
I also removed incorrect persist methods on LocalBackend.  The default (do nothing) is the best thing for now.
=> [hail] fix import_fam for local backend

hail/src/main/scala/is/hail/expr/ir/Binds.scala, hail/src/main/scala/is/hail/expr/ir/ComputeUsesAndDefs.scala, hail/src/main/scala/is/hail/expr/ir/Env.scala, hail/src/main/scala/is/hail/expr/ir/FreeVariables.scala
=> [query] Extend BindingEnv to include relational bindings

hail/src/main/scala/is/hail/asm4s/CodeBuilder.scala
currently unused, may be useful in the future.
=> [query] Add forLoop to CodeBuilder

hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
One class per genome is generated per module.
=> [query] Move reference genomes onto static classes

hail/python/hailtop/hailctl/dataproc/list_clusters.py, hail/python/hailtop/hailctl/dataproc/stop.py, hail/python/test/hailtop/hailctl/dataproc/test_list_clusters.py, hail/python/test/hailtop/hailctl/dataproc/test_stop.py
=> [hailctl dataproc] Add some tests for hailctl dataproc list and stop

hail/python/hail/table.py, hail/python/test/hail/table/test_grouped_table.py, hail/src/main/scala/is/hail/expr/ir/TableIR.scala, hail/src/main/scala/is/hail/types/physical/PCanonicalBaseStruct.scala
=> [query] Reimplement Table._same as outer join on row idx

hail/python/hail/expr/aggregators/__init__.py, hail/python/hail/expr/aggregators/aggregators.py, hail/python/hail/ir/register_aggregators.py, hail/src/main/scala/is/hail/expr/ir/AggOp.scala, hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala, hail/src/main/scala/is/hail/expr/ir/agg/ImputeTypeAggregator.scala, hail/src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala
Will use this to implement type imputation for TextTableReader in python.
=> [query] Add ImputeType aggregator

hail/python/hailtop/hailctl/dataproc/submit.py, hail/python/test/hailtop/hailctl/dataproc/conftest.py, hail/python/test/hailtop/hailctl/dataproc/test_submit.py
=> [hailctl dataproc] Add some tests for hailctl dataproc submit

hail/python/hail/docs/nd/index.rst, hail/python/hail/ir/__init__.py, hail/python/hail/ir/base_ir.py, hail/python/hail/ir/ir.py, hail/python/hail/nd/__init__.py, hail/python/hail/nd/nd.py, hail/python/test/hail/linalg/test_linalg.py
Used in the regenie implementation I'm referring to, and a useful/common ndarray function to expose.
=> [query] NDArray concatenate

hail/src/main/scala/is/hail/asm4s/AsmFunction.scala, hail/src/main/scala/is/hail/asm4s/Code.scala, hail/src/main/scala/is/hail/expr/ir/Binds.scala, hail/src/main/scala/is/hail/expr/ir/Compile.scala, hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala, hail/src/main/scala/is/hail/expr/ir/EmitStream.scala, hail/src/main/scala/is/hail/expr/ir/Interpretable.scala, hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala, hail/src/main/scala/is/hail/expr/ir/Requiredness.scala, hail/src/main/scala/is/hail/expr/ir/TableIR.scala, hail/src/main/scala/is/hail/lir/Emit.scala, hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala, hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
To come next:
* Expose in Python, add more tests of Python functionality
=> [query] Add TableMapPartitions node

hail/python/hail/experimental/full_outer_join_mt.py
I took this example directly from an interaction with Akhil on Zulip.
=> [hail] Add an example for full_outer_join_mt

batch/Makefile
This is only a problem when hand deploying batch.
=> [batch] teach make deploy to also deploy service accounts

hail/python/hail/ir/__init__.py, hail/python/hail/ir/table_ir.py, hail/python/hail/table.py, hail/python/test/hail/table/test_table.py, hail/python/test/hail/test_ir.py, hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
=>  [query] Expose Table._map_partitions in Python

hail/python/hailtop/batch/batch_pool_executor.py, hail/python/hailtop/batch/docs/api.rst
Do I have to do anything else to get BatchPoolExecutor exposed in the Batch docs?
=> [hailtop.batch] expose batch pool executor docs

benchmark-service/benchmark/benchmark.py
[benchmark] fix crash loop backoff from init_app
=> [benchmark] fix crash loop backoff from init_app

batch/batch/semaphore.py, batch/batch/worker/worker.py
I wasn't sure if we should print at least one Docker config or not. I'm worried about the test for out_of_memory where that prints out a bunch of the letter 'a' in the script.
=> [batch] cleanup content in worker.log

hail/python/hailtop/batch_client/parse.py
re.Pattern was introduced in Python 3.6.
=> [hailtop] Change to be compatible with Python 3.6 and Python 3.7

build.yaml, hail/Dockerfile.hail-pip-installed-python36, hail/Dockerfile.hail-pip-installed-python37, hail/python/hail/__init__.py, hail/python/hail/methods/family_methods.py, hail/python/hail/table.py, hail/python/hailtop/batch/job.py, hail/python/hailtop/batch/resource.py, hail/python/hailtop/cleanup_gcr/__main__.py
CC: @tpoterba I've fixed up CI to check hail and hailtop under both python 3.6 and 3.7. There were a few minor fixes to hail.
=> [hail] check hail using 3.6 and 3.7

hail/python/hail/matrixtable.py, hail/python/hail/table.py, hail/python/hail/utils/misc.py, hail/python/test/hail/matrixtable/test_matrix_table.py
=> [query] Add expression source checking to annotate methods

hail/Makefile, hail/build.gradle
Furthermore, update build.gradle to (finally) not print all the
Unsafe warnings.
=> [query] Add JAVA_HOME configuration to Makefile

hail/python/hailtop/hailctl/auth/cli.py, hail/python/hailtop/hailctl/auth/user.py
@tpoterba I think this should be fine. It returns a formatted json string that you can use jq to parse.
=> [hailctl] Add hailctl auth user

hail/src/main/scala/is/hail/annotations/CodeOrdering.scala, hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala, hail/src/main/scala/is/hail/expr/ir/ArraySorter.scala, hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala, hail/src/main/scala/is/hail/expr/ir/SpecializedArrayBuilders.scala, hail/src/main/scala/is/hail/expr/ir/agg/CallStatsAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/CollectAsSetAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/GroupedAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/MonoidAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/PrevNonNullAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/TakeByAggregator.scala, hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala, hail/src/main/scala/is/hail/expr/ir/package.scala, hail/src/main/scala/is/hail/io/CodecSpec.scala, hail/src/main/scala/is/hail/types/encoded/EType.scala, hail/src/main/scala/is/hail/types/physical/PPrimitive.scala, hail/src/main/scala/is/hail/types/physical/PType.scala, hail/src/main/scala/is/hail/types/physical/package.scala
Felt wrong for the ptypes to typeinfo and default values being in the ir package.
=> [query] Move typeToTypeInfo and defaultValue to ptypes package

web_common/web_common/templates/header.html, web_common/web_common/web_common.py
I think this is all that needs to be added to get benchmark in the header. There's no caret after so we don't need to format that at all.
=> [web_common] Add benchmark to header

ci/ci/build.py
I don't know how to test this works unless I can dev deploy to my own copy of CI that's running with the new changes.
The issue I was seeing is the database step runs fine, but the new tables weren't actually created.
=> [ci] fix create_passwords for dev deploy

hail/src/main/scala/is/hail/asm4s/CodeBuilder.scala, hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala, hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala, hail/src/main/scala/is/hail/expr/ir/EmitStream.scala, hail/src/test/scala/is/hail/expr/ir/UtilFunctionsSuite.scala
=> [query][smm 4] rewrite StreamFold and StreamFold2 to prepare for memory management

batch/batch/front_end/front_end.py
I checked this works with dev deploy
=> [batch] sort attempts by start time

batch/batch/worker/worker.py
This should speed up the tests and fully revert everything
=> [batch] use google-sdk image for copying

hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
~~Stacked on #9182~~
This enables per-element regions in MakeStream. This finishes all stream producers, other than `In`.
=> [query][smm 7] Memory management for stream producers

hail/src/main/scala/is/hail/annotations/Region.scala, hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/EmitStream.scala, hail/src/main/scala/is/hail/expr/ir/StagedRegion.scala
=> [query][smm 8] Memory management for StreamMap and StreamFilter

batch/batch/driver/instance_pool.py, batch/batch/driver/main.py, batch/batch/driver/templates/index.html, batch/sql/add-worker-pd-ssd-data-disk.sql, batch/sql/estimated-current.txt, build.yaml
Expose in front end
Currently unused
=> [batch] add worker local SSD and PD SSD options to globals

hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
=> [query][smm 9] Memory management for StreamFlatMap

batch/batch/driver/instance_pool.py, batch/batch/front_end/front_end.py, batch/batch/utils.py, batch/batch/worker/worker.py, batch/batch/worker_config.py
=> [batch] Configurable worker disk type

hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
=> [query][smm 11] Memory management for StreamMerge and StreamZip

hail/python/hail/expr/expressions/typed_expressions.py, hail/python/hail/ir/__init__.py, hail/python/hail/ir/ir.py, hail/python/test/hail/expr/test_expr.py, hail/src/main/scala/is/hail/expr/ir/Parser.scala
This PR exposes `StreamGrouped` IR node in python as a `grouped(group_size)` method on `ArrayExpression`.
=> [query] Add ArrayExpression.grouped

web_common/web_common/styles/main.scss, web_common/web_common/templates/header.html
=> [Benchmark] Add header dropdown

hail/src/main/scala/is/hail/expr/ir/agg/NDArraySumAggregator.scala
Mostly doing this for visibility as we are profiling randomized PCA and dndarray stuff. 
The diff makes this seem like more than it is, basically just wrapped the already existing code in method calls.
=> NDArrayAggregator Method Wrap Add Values

hail/src/main/scala/is/hail/expr/ir/Compile.scala, hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala, hail/src/main/scala/is/hail/expr/ir/EmitStream.scala, hail/src/main/scala/is/hail/expr/ir/StagedRegion.scala, hail/src/main/scala/is/hail/expr/ir/TableIR.scala, hail/src/main/scala/is/hail/types/physical/package.scala, hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
=> [query][smm 14] Memory management for TableMapPartitions

dev-docs/batch-operation.md
=> [batch, dev-docs] add note on operating batch at scale

dev-docs/hail-overview.md
Rendered markdown here: https://github.com/cseed/hail/blob/9ff708738fe8f447a6cf8d7361502ef4ad270028/dev-docs/hail-overview.md
Dan, what else do you want to see here?  @tpoterba?  I'm happy to do more of this/these.
=> [dev-docs] added Hail overview

hail/src/main/scala/is/hail/expr/ir/TableIR.scala
=> [query] Fix lowered coercer sortedness logic

hail/python/hailtop/batch/genetics/regenie/example/step1.txt, hail/python/hailtop/batch/genetics/regenie/example/step2-nosplit.txt, hail/python/hailtop/batch/genetics/regenie/example/step2-phenoCol.txt, hail/python/hailtop/batch/genetics/regenie/example/step2-phenoColList.txt, hail/python/hailtop/batch/genetics/regenie/example/step2.txt, hail/python/hailtop/batch/genetics/regenie/regenie.py, hail/python/test/hailtop/batch/test_regenie.py
CHANGELOG: Enable batch.genetics.regenie to use the ServiceBackend.
Thought I would contribute this in case it would be useful and out of a sense of responsibility; may be easier for me to create the service backend implementation as I'm closest to the project. Feel free to close if not beneficial.
cc @tpoterba in case you were interested
=> [batch/genetics] regenie service backend 

benchmark/scripts/benchmark_in_batch.py
This ensures that we fail a benchmark early if we cannot copy into the output directory.
=> [benchmark] check permissions before all resource jobs

hail/src/main/scala/is/hail/expr/ir/TableIR.scala, hail/src/main/scala/is/hail/expr/ir/package.scala
=> Fix pk-sorted and unsorted LoweredTableCoercers

build.yaml, hail/python/hailtop/batch/genetics/regenie/regenie.py
I am not really sure why $? is not set to 1 if these parentheses are absent. Nonetheless,
this fixes CI to actually complain about mypy failures.
=> [batch] actually check the mypy exit status

hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
I tried summing a list of `BlockMatrix` and found I was spending all of my time recomputing the type.
=> [query] Turn BlockMatrixIR typs into lazy vals to avoid recomputing

batch/batch/driver/main.py
Can't use this anymore after we added local SSDs
=> [batch] remove check_cost loop

hail/python/hail/experimental/dnd/array.py
When I first dndarray, I did not know you could use rename for keys. This
change takes advantage of rename instead of using the `r_field` and `c_field`
indirection.
=> [hail] use rename in dndarray

hail/python/hail/experimental/dnd/array.py, hail/python/test/hail/experimental/test_dnd_array.py
I also realized that we shouldn't need to reshape the `collect` of a dndarray. DNDArray collects to a properly shaped numpy array.
=> [hail][dndarray] add many pairwise operations

build.yaml, hail/python/hailtop/aiogoogle/__init__.py, hail/python/hailtop/aiogoogle/client/__init__.py, hail/python/hailtop/aiogoogle/client/bigquery_client.py, hail/python/hailtop/utils/__init__.py, hail/python/hailtop/utils/utils.py, monitoring/Dockerfile, monitoring/Dockerfile.test, monitoring/MANIFEST.in, monitoring/Makefile, monitoring/deployment.yaml, monitoring/monitoring/__main__.py, monitoring/monitoring/configuration.py, monitoring/monitoring/monitoring.py, monitoring/monitoring/templates/billing.html, monitoring/setup.py, monitoring/sql/delete-monitoring-tables.sql, monitoring/sql/estimated-current.sql, monitoring/sql/initial.sql, monitoring/test/test_monitoring.py, router/deployment.yaml, router/router.nginx.conf.in, tls/config.yaml, web_common/web_common/templates/header.html, web_common/web_common/web_common.py
Sorry, this is the same PR as #9241. I had to rebase on master to dev deploy efficiently. I added a test to the existing PR and fixed why my tables weren't being created with dev deploy. I also reduced the query size in the test scope by only querying 2 days. It only changed it from 10 MB scanned instead of 20+ MB scanned, but I figured that was better than nothing.
The last commit from 35cf654 are the new changes.
FYI: @danking
=> [monitoring] Added the monitoring service with billing infrastructure

hail/python/hail/experimental/dnd/array.py
Unfortunately, these calculations get inlined into the map.
=> [hail][dndarray] evaluate row and col once

build.yaml, hail/python/hail/expr/expressions/typed_expressions.py, hail/python/hailtop/batch/__init__.py, hail/python/hailtop/batch/batch_pool_executor.py, hail/python/hailtop/batch/genetics/regenie/regenie.py, hail/python/hailtop/batch/job.py, hail/python/hailtop/batch/resource.py
I misunderstood the issue originally. The exit status was set *in the sub-shell*, so
it did not affect the parent shell's environment. Instead, I run the command in
a sub-shell and update the variable in the parent shell.
I also had to fix the issues that arose while the check wasn't honored.
=> [batch] finally fix check_hail_python37

ukbb-rg/deployment.yaml
=> [ukbb-rg] reduce requests to 800mCPU to improve packing

Makefile, auth/Makefile, batch/Makefile, benchmark-service/Makefile, benchmark/python/Makefile, build.yaml, ci/Makefile, gear/Makefile, hail/python/Makefile, notebook/Makefile, query/Makefile, router-resolver/Makefile, scorecard/Makefile, web_common/Makefile
In particular, check hailtop, which appears to have been missing.
=> [build.yaml] consolidate check build steps

hail/python/hail/docs/_templates/_autosummary/class.rst, hail/python/hail/docs/_templates/_autosummary/class2.rst
We need to include the :members: directive in newer Sphinx versions. I also elided
hidden and inherited members for now, though we can add those back if we like.
=> [hail] fix Hail docs

hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
I apparently missed this during my first pass of conversions. The PR to follow this one refines the `StagedRegion` class hierarchy to better work with allocation behaviors encoded in `PStream`. I caught this while making that change, because the tighter API makes it much harder to "cheat" like stream joins were doing.
=> [query] memory management for StreamJoinRightDistinct

benchmark/python/benchmark_hail/run/methods_benchmarks.py
I wanted to add some benchmarks to start tracking this. They take roughly 25 and 45 seconds respectively on my laptop currently
=> Blanczos PCA Benchmarks

hail/src/main/scala/is/hail/services/package.scala, hail/src/test/scala/is/hail/services/shuffler/ShuffleSuite.scala, router/router.nginx.conf.in
I also added SocketException and SSLException as transient errors
=> [shuffler] retry transient errors

build.yaml, hail/build.gradle, hail/python/Makefile, hail/python/hailtop/batch/__init__.py, hail/python/hailtop/batch/backend.py, hail/python/hailtop/batch/batch.py, hail/python/hailtop/batch/batch_pool_executor.py, hail/python/hailtop/batch/conftest.py, hail/python/hailtop/batch/genetics/regenie/regenie.py, hail/python/hailtop/google_storage.py, hail/python/hailtop/tls.py, hail/python/hailtop/utils/rate_limiter.py, setup.cfg
One fix.  Also, prefer global `--ignore-missing-imports` to local hints.
=> [hailtop/utils] check with mypy

hail/python/test/hail/table/test_table.py, hail/src/main/scala/is/hail/sparkextras/RepartitionedOrderedRDD2.scala
Fixes TableMapPartitions(indexed read)
=> [query] Remove invalid boundary on RepartitionedOrderedRDD2

hail/python/hail/ir/ir.py, hail/python/test/hail/expr/test_ndarrays.py, hail/src/main/scala/is/hail/asm4s/Code.scala, hail/src/main/scala/is/hail/expr/ir/Children.scala, hail/src/main/scala/is/hail/expr/ir/Copy.scala, hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/IR.scala, hail/src/main/scala/is/hail/expr/ir/InferPType.scala, hail/src/main/scala/is/hail/expr/ir/InferType.scala, hail/src/main/scala/is/hail/expr/ir/Parser.scala, hail/src/main/scala/is/hail/expr/ir/Pretty.scala, hail/src/main/scala/is/hail/expr/ir/Requiredness.scala, hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala, hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala, hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala, hail/src/main/scala/is/hail/types/physical/PNDArray.scala, hail/src/test/scala/is/hail/TestUtils.scala, hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
Extending the idea of better error messages from #9398  to include `NDArrayRef`.
=> NDArrayRef Better Error Message

hail/src/main/scala/is/hail/expr/ir/Parser.scala
~~Stacked on #9320~~
Use the framework introduced in #9320 to make the IR parser stack safe. This touches a lot of lines, but it is a completely mechanical refactoring.
I did some preliminary benchmarking by timing the parse of the IR in `test_ld_prune`. (I chose that test fairly arbitrarily, and we can probably find better test cases, or generate synthetic large IRs.) Running a loop parsing the same IR repeatedly, with 10 burn-in rounds, and 60 timed rounds, I got the following results:
* On main
```
quartiles = [4.55816, 5.209579, 5.647135]
avg = 5.332496950000001, std = 1.13761574944604
```
* Using `StackSafe`, without the optimization in `repUntil`
```
quantiles = [4.610798, 5.09793, 7.159075]
avg = 5.7519015000000016, std = 1.612397075594852
```
* Using `StackSafe, with the …
=> [query] Stack safe parser

batch/test/test_batch.py, hail/python/test/hailtop/batch/test_regenie.py
Regenie defaults to requesting 1 core. I also fixed some syntax errors in test_batch.py
=> [batch] reduce resource requirements of test_regenie

batch/batch/driver/scheduler.py
=> [batch] Add scheduler bump if shares exceeded

hail/python/hail/expr/expressions/typed_expressions.py
=> Deprecate ArrayExpression's head method

hail/python/hail/experimental/vcf_combiner/vcf_combiner.py, hail/src/main/scala/is/hail/expr/ir/MatrixValue.scala, hail/src/main/scala/is/hail/expr/ir/TableWriter.scala, hail/src/main/scala/is/hail/io/FileWriteMetadata.scala, hail/src/main/scala/is/hail/io/RichContextRDDRegionValue.scala, hail/src/main/scala/is/hail/io/bgen/IndexBgen.scala, hail/src/main/scala/is/hail/io/index/IndexWriter.scala, hail/src/main/scala/is/hail/linalg/BlockMatrix.scala, hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala, hail/src/main/scala/is/hail/rvd/RVD.scala, hail/src/main/scala/is/hail/utils/package.scala, hail/src/main/scala/is/hail/utils/richUtils/RichContextRDD.scala, hail/src/main/scala/is/hail/utils/richUtils/RichRDD.scala, hail/src/test/scala/is/hail/io/IndexSuite.scala
Next, I want to put file sizes into the metadata.json
=> [query] Print file size on Table/MT write

Makefile, build.yaml, docker/requirements.txt, hail/python/hailtop/google_storage.py, hail/python/hailtop/utils/utils.py, memory/Dockerfile, memory/Makefile, memory/deployment.yaml, memory/memory/__main__.py, memory/memory/client.py, memory/memory/memory.py, memory/redis.conf, memory/run.sh, memory/service-account-batch-pods.yaml, memory/service-account.yaml, memory/setup.py, memory/test/test_memory.py, router/deployment.yaml, router/router.nginx.conf.in, tls/config.yaml
I think I still have to fix the pylint stuff (and add typechecking?) but otherwise should be complete.
I'll add the dev doc in a separate PR.
=> [memory] add simple read-only cache

hail/src/main/scala/is/hail/lir/SimplifyControl.scala
… and make it true.
Randomly assigned. John, I know you haven't looked at lir much; happy to answer any questions.
=> [query/lir] assert postcondition of SimplifyControl

benchmark/Makefile
=> [Benchmark] rename HAIL_VERSION to HAIL_PIP_VERSION

hail/python/hailtop/hailctl/dataproc/modify.py, hail/python/test/hailtop/hailctl/dataproc/test_modify.py
CHANGELOG: Fix hailctl dataproc modify to install dependencies of the wheel file.
=> [hailctl] update dependencies on modify

memory/memory/memory.py
=> [memory] better logging

hail/python/hail/methods/pca.py
It's nice to get a print out of how far along it is.
=> [query] Extra blanczos_pca info

batch/batch/driver/main.py, docker/requirements.txt, hail/python/hailtop/utils/__init__.py, hail/python/hailtop/utils/serialization.py
1. Correctly serialize Exceptions.
2. Include a dictionary diff in the assertion message.
=> [batch] improve error messages on checks

hail/python/hailtop/batch_client/aioclient.py, hail/python/hailtop/batch_client/client.py
Set the default limit for number of values returned to 2^64 to keep current default behavior.
=> [hailctl batch] Give/Teach list_batches limits

batch/batch/worker/flock.py
flock(2) does not prevent other processes from doing anything to the
locked file unless they also gate usages on an flock call. Update Flock
to open only one descriptor, the directory that is the parent of `path`,
creating said directory if it doesn't exist.
The semantics have changed slightly. Previously if path was an already
extant directory, it would be opened and that descriptor would be
flocked. Now, the parent is always locked.
=> [batch] Update flock strategy

build.yaml
=> [benchmark] Add benchmark user account

batch/Makefile
We started using the scope in the deployment.yaml. This addes it to the JINJA_ENVIRONMENT
in the Makefile.
=> [batch] fix hand deploy

batch/batch/worker/worker.py, hail/python/hailtop/batch/batch.py, hail/python/test/hailtop/batch/test_batch.py
This is intended to fix Matt's copying bug with copying a Hail table with Batch.
=> [batch] Fix copying with a directory

hail/src/main/scala/is/hail/expr/ir/Emit.scala
This ports `NDArrayInv` to `EmitI`. 
With this, all NDArray emit rules are ported to `EmitI`, though the `NDArrayEmitter` still uses `EmitCode` internally. Will address that in a future PR.
=> NDArrayInv ported to EmitI

Makefile, address/Makefile, admin-pod/Makefile, auth/Makefile, batch/Makefile, benchmark-service/Makefile, ci/Makefile, docker/Makefile, hail/Makefile, hail/python/hail/docs/Makefile, memory/Makefile, monitoring/Makefile, query/Makefile, router-resolver/Makefile, shuffler/Makefile, site/Makefile
As stated in the GNU make manual, "Recursive make commands should always
use the variable MAKE, not the explicit command name ‘make’".
https://www.gnu.org/software/make/manual/make.html#MAKE-Variable
=> Update all make in makefiles to use $(MAKE)

build.yaml, scorecard/deployment.yaml, scorecard/scorecard/scorecard.py, scorecard/scorecard/templates/index.html, scorecard/scorecard/templates/user.html
- Use the scorecard tag or design-docs tag to have Asana tasks show up in scorecard
- Easy to add different tags to track
- Currently using my personal access token. Not sure if that's ideal, but seemed fine for now.
=> [scorecard] Added Asana integration

batch/batch/worker/worker.py
This is regardless of whether there are inputs or outputs.
=> [batch] add /io mount path to the main container

ci/ci/ci.py, hail/python/hailtop/hailctl/batch/get.py, hail/python/hailtop/hailctl/batch/list_batches.py
This should reduce the number of requests clients are making.
=> [hailctl batch][ci] use last_known_status in ci and hailctl

batch/sql/estimated-current.sql
This was missing in #9532 / #9506
=> [batch] add missing insert into to billing_project_users

hail/python/hailtop/batch/__init__.py
CHANGELOG: The Resource class is now also available at hailtop.batch.Resource.
I screwed up my branches. This is just #9515.
=> [batch] expose ABC Resource to users (previously #9515)

batch/Makefile, batch/batch/driver/instance_pool.py, batch/batch/worker/worker.py, batch/build-batch-worker-image-startup.sh, hail/python/hailtop/batch/backend.py, image-fetcher/fetch-image.sh
Also update all uses of cloud sdk to same version.
Seems good to do anyway. I hope the newer version of gcloud includes a faster gsutil. I also hope that using gcr will improve the pull time a bit.
=> [batch] use the gcr repo for the cloud sdk

batch/test/test_batch.py
I did this because I think we want to add more flexibility and use more pytest features like how you wrote the two different clients and I want to add pyest marks.
=> [batch] refactor test_batch.py to use pytest instead of unittest

batch/test/conftest.py, build.yaml
=> Revert "[batch] Add infrastructure for not running batch tests in production"

hail/src/test/scala/is/hail/services/shuffler/ShuffleSuite.scala
I do not know why these 143 so often with 7.5 GB of RAM. Maybe too many strings?
=> [shuffler] maybe less memory use in tests?

build.yaml
=> [shuffler] actually use 7.5GB in test_hail_services_java

batch/Makefile, batch/batch/driver/instance_pool.py, batch/build-batch-worker-image-startup.sh
This restores things to the way the were. The changes to docker daemon.json were
not moved back to instance_pool.py.
=> [batch] restore fluentd functionality

hail/python/hailtop/aiogoogle/client/storage_client.py, hail/python/hailtop/aiotools/__init__.py, hail/python/hailtop/aiotools/fs.py, hail/python/test/hailtop/test_aiogoogle.py
Current plan going forward for this:
- I'm getting pretty happy with the interface (but maybe want to rename some things).  I think I will document what I have next.
- Get rid of legacy hailtop.GCS.  This means we can get rid of all the client libraries except the oauth2 flows in auth.
- The add a glob operation.
- Add a copy/sync operation.
I might also add an S3AsyncFS.  I could have used that recently.
=> [aiogoogle, aiotools] added statfile, listfiles

benchmark/scripts/benchmark_in_batch.py
=> [benchmark] fix lowered benchmarks

hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
`TableMapPartitions` needs to insert a TableKeyBy if any element of its child's key is not in the rebuilt body. This is the same thing TableMapRows does.
I can figure out a PruneSuite test for this if you want, but the incoming chained linear regression PR will test this behavior as well, I'm just trying to break things up.
=> [query] TableMapPartitions Rebuild Fix

batch/batch/batch.py, batch/batch/driver/main.py, batch/batch/exceptions.py, batch/batch/front_end/front_end.py, batch/batch/front_end/templates/billing_limits.html, batch/sql/add-aggregated-billing-project-resources.sql, batch/sql/delete-batch-tables.sql, batch/sql/estimated-current.sql, batch/test/test_accounts.py, batch/test/test_batch.py, build.yaml, hail/python/hailtop/batch_client/aioclient.py, hail/python/hailtop/batch_client/client.py, web_common/web_common/templates/header.html
Stacked on #9346 
Changes:
- infrastructure needed for kill switch
- UI page
- Default value for the limit is None
Testing:
- In the database migration, there's two updates that populate the initial state of the aggregated_billing_resources_table. I tested this by hand using a database that hadn't been migrated previously, but this might be good to double check.
- I ran the `check_resource_aggregation` loop while running `test_batch` and made sure there were no errors.
- I tested the UI page editing the limits with negative values and gibberish by hand to make sure those failed. I also refreshed the page to make sure the values were in the database and the update worked.
So here's a PR where I convinced myself it was correct a couple of days ago, but the longer this sits, the less …
=> [batch] Aggregated billing project resources infrastructure

batch/batch/batch.py, batch/batch/driver/main.py, batch/batch/exceptions.py, batch/batch/front_end/front_end.py, batch/batch/utils.py, batch/test/test_accounts.py, batch/test/test_batch.py
Stacked on #9354
I'm happy with the tests here.
=> [batch] spending limit kill switch for a billing project

hail/python/hailtop/batch/docs/cookbook/clumping.rst, hail/python/hailtop/batch/docs/cookbook/files/batch_clumping.py
=> [batch] fix clumping tutorial with add_extension

hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala, hail/src/main/scala/is/hail/types/physical/PInterval.scala
It was basically a proto PIntervalValue
=> [query/pcode] Remove IRInterval from IntervalFunctions

batch/deployment.yaml
I think this is how to make it nonpreemptible in production only.
=> [batch] Make driver nonpreemptible in production

auth/auth/auth.py, auth/auth/templates/roles.html, auth/sql/add-roles.sql, auth/sql/estimated-current.sql, build.yaml, web_common/web_common/templates/header.html
This adds roles to the auth service.  They are not used yet, but they are stored in the database and I created a simple UI for adding them.  I tested with this dev deploy.
FYI @danking @jigold
=> [auth] add roles

benchmark-service/benchmark/benchmark.py, benchmark-service/benchmark/config.py, benchmark-service/benchmark/utils.py, benchmark-service/deployment.yaml
fix file path in file_exists function
=> [Benchmark] fix file path

build.yaml, echo/Dockerfile, echo/deployment.yaml
I will test this with a forthcoming PR which adds a TCP gateway.
=> [echo] implement a TCP echo server

build.yaml
@Dania-Abuhijleh This is infrastructure for your benchmark project. Once this goes in, you can change your Batch Client billing project to be benchmark instead of test.
=> [build] Add billing projects in a new build step

hail/python/hail/experimental/__init__.py, hail/python/hail/experimental/table_ndarray_utils.py, hail/python/hail/methods/pca.py
Dan wanted this for Gonzalo and Ahmed's QR work.
=> Split out new experimental method mt_to_table_of_ndarray

admin-pod/Makefile, auth/Makefile, batch/Makefile, benchmark-service/Makefile, ci/Makefile, config.mk, image-fetcher/Makefile, memory/Makefile, monitoring/Makefile, query/Makefile, router/Makefile, shuffler/Makefile, site/Makefile
There were a few places where things that had `NAMESPACE` didn't use it in certain places. I also fixed that. I also standardized the error verbiage.
=> [services] ensure all make deploy require & use NAMESPACE

hail/testng-services.xml
I accidentally disabled this in https://github.com/hail-is/hail/pull/9109.
=> [batch] restore java batch testing

amundsen/Makefile, amundsen/deployment.yaml, build.yaml, config.mk, docker/third-party/images.txt, letsencrypt/domains.txt, router/Makefile, router/deployment.yaml, router/router.nginx.conf.in
This works in the sense that I didn't get a 404 or 502 contacting the server in my namespace. I think we need to redeploy lets encrypt -- can't remember.
=> [amundsen] Add front end service

hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/linalg/LinalgCodeUtils.scala, hail/src/main/scala/is/hail/types/encoded/EBlockMatrixNDArray.scala, hail/src/main/scala/is/hail/types/encoded/ENDArrayColumnMajor.scala, hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala, hail/src/main/scala/is/hail/types/physical/PNDArray.scala
More constructor redesigns to come.
=> [query] Refactor PNDArray.construct to return a PCode

batch/batch/front_end/front_end.py
=> [batch] CI needs access to the admin service account

.dir-locals.el, lsm/Makefile, lsm/main.cpp, lsm/test.sh
We'll talk more about this during our meeting. This provides a skeleton for an LSM tree. Your first job will be to implement the interface using just C++'s `std::map`, an ordered key-value mapping.
I implemented a simple command line interface that accepts a key-value language:
- `p k v`, put the value `v` at the key `k` (overwriting any value that currently exists)
- `g k`, print the value associated with key `k`; if there is no value print an empty line
- `r l r`, print, on one line, all the key-value pairs between `l` (inclusive) and `r` (exclusive)
- `d k`, remove any value associated with the key `k`
=> [lsm] outline

hail/python/hail/docs/experimental/index.rst, hail/python/hail/experimental/loop.py
Fixed some small latex issues to allow this.
=> Add loop to autogenerated docs

.dockerignore
=> [docker] ignore pycache directories

auth/auth/auth.py
Empty text boxes are (always?) transmitted to the server as an empty string.
This change teaches auth to interpret both the empty string or a missing email attribute
equivalently. Moreover, service accounts with the empty string email are converted to
NULL emails.
=> [auth] fix handling of empty email for service accounts

hail/python/hail/methods/statgen.py, hail/python/test/hail/methods/test_statgen.py
I just added a slightly more informative error message. Do you want something more than this?
=> [query] Slightly better Error Message from realized_relationship_matrix

batch/Dockerfile, batch/Makefile, build.yaml
We never used any other directory anyway.
=> [batch] limit docker context for faster builds

ci/ci/build.py
=> [ci] set namespace

ci/ci-agent.yaml, ci/ci/build.py, ci/test/resources/build.yaml, ci/test/resources/statefulset.yaml
Both Cotton and I have PRs failing due to pod failures that are impossible to debug without this.
=> [ci] better ci information on deploy failure

build.yaml, docker/python-dill/Makefile, docker/python-dill/push.sh, docker/third-party/images.txt, hail/python/test/hailtop/batch/test_batch.py, hail/python/test/hailtop/batch/test_batch_pool_executor.py, hail/python/test/hailtop/batch/utils.py
I didn't test the getting the logs code.
=> [hailtop/batch] Add logs messages to tests

build.yaml, lsm/Makefile, lsm/main.cpp
=> [lsm] part 1

hail/src/main/scala/is/hail/expr/ir/Optimize.scala, hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala
=> [query] Remove optimize overload

hail/python/requirements.txt
Let's see if we can update to newest pandas.
=> [query] Update pandas to 1.1.4

ci/ci/constants.py
```
+ Carolin
- Annamira, Alex K
```
=> [ci] authorized users house keeping

batch/batch/driver/zone_monitor.py, hail/python/hailtop/utils/__init__.py, hail/python/hailtop/utils/utils.py, hail/python/test/hailtop/utils/test_utils.py
This is part of the copy tool changes.
=> [utils] added url_basename and url_join

batch/batch/driver/instance_pool.py
These are always delete operations that have failed due to the worker not
existing.
=> [batch] handle events with no operation

hail/python/hail/linalg/blockmatrix.py, hail/python/hail/utils/__init__.py, hail/python/hail/utils/misc.py, hail/python/test/hail/utils/test_utils.py
CHANGELOG: Eagerly delete temporary files produced by some BlockMatrix operations.
=> [hail] use with_local_temp_file to eagerly delete files

hail/python/hail/plot/plots.py, hail/python/requirements.txt
Updated bokeh to a better documented version, last 1.x release. This required some changes to use of `legend` mentioned here: `https://docs.bokeh.org/en/latest/docs/releases.html#release-1-4-0-migration`.
=> [query] Update bokeh version, fix legend issues.

devbin/sync.py
- Use the fully qualified name rather than relying on the PATH for krsync.sh.
- Remove dead pods from the pods list.
=> [sync.py] fix PATH and handle dead pods

batch/batch/front_end/validate.py, hail/python/hailtop/batch_client/aioclient.py, hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala, hail/src/test/scala/is/hail/services/batch_client/BatchClientSuite.scala
=> [batch][bugfix] forgot to actually run validate_process

batch/batch/front_end/front_end.py
We updated the job spec but forgot to update the display of jobs.
=> [batch] fix job page

devbin/sync.py
If a pod is unreachable for any reason, we previously retried forever. However,
a pods are ephemeral; we cannot assume they will return. Instead, if we fail to
contact a pod, we remove it from the pods list and log the error. If the pod
really does exist, the monitor_pods loop will attempt to initialize it again.
=> [sync.py] avoid infinite retry loop

devbin/sync.py
=> [sync.py] use add not append for sets

hail/python/hailtop/utils/utils.py
The internet suggests this is due to a network connectivity problem such as not having an ethernet cable
plugged in. This seems transient to me; who is intentionally disconnected from the Internet?
=> [hailtop] retry ENETUNREACH

router-resolver/router_resolver/router_resolver.py
Use our `AccessLogger` in `router-resolver` too.
=> [router-resolver] add access logger to router resolver

ci/ci/build.py
@daniel-goldstein , this is a relatively tiny change to CI, but I think it's a chance to take a peek at one part of it. Send me your questions!
=> [ci] time most commands in the image build step

ci/ci/ci.py
Eliminates the two log entries for unclosed connections/sessions on shutdown
=> [ci] close all aiohttp client connections on shutdown

hail/python/test/hail/linalg/test_linalg.py, hail/src/main/scala/is/hail/asm4s/CodeBuilder.scala, hail/src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala, hail/src/main/scala/is/hail/types/physical/PCanonicalArray.scala, hail/src/main/scala/is/hail/types/physical/PCanonicalBaseStruct.scala
Use these to convert a few locus functions from Code => PCode
=> [query] Add new constructors for PBaseStruct/PCanonicalArray

batch/batch/exceptions.py, batch/batch/front_end/front_end.py, batch/test/test_accounts.py
FYI @danking 
I wasn't sure if removing a previously deleted user should be an error. I think it should be, but I left it as idempotent for now.
=> [batch] Make billing project operations idempotent

hail/python/hailtop/hailctl/dev/deploy/cli.py
dev deploy isn't quite there yet with the 5 second rule and is timing out a lot.
=> [hailctl] change dev deploy timeout to 60s

libhail/docs/tagged-union.txt, libhail/src/hail/tunion.hpp
Add utilities for working with tagged unions.
I'm going to build up some basic C++ infrastructure with a series of PRs like this documenting the designs and rationale.
@tpoterba, no hurry in reviewing this.  FYI @danking
=> [libhail] initial cpp commit.

batch/test/test_accounts.py, batch/test/test_aioclient.py, benchmark-service/benchmark/benchmark.py, build.yaml, ci/ci/ci.py, hail/python/hailtop/batch/backend.py, hail/python/hailtop/batch_client/aioclient.py, hail/python/hailtop/batch_client/client.py, hail/python/hailtop/config/deploy_config.py, hail/python/test/hailtop/batch/test_batch.py, hail/python/test/hailtop/batch/utils.py
I'm seeing a PR failure that I can't debug further without the status information.
=> [batch] maximal debugging information when a job fails

hail/src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala, hail/src/main/scala/is/hail/types/physical/PCanonicalBaseStruct.scala
This makes the interaction with other infrastructure a bit simpler.
=> [query] Refactor struct code constructor to take codes, not values

hail/src/main/scala/is/hail/types/virtual/TDict.scala
=> [query] Fix show for dict expressions

hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/EmitStream.scala, hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala, hail/src/main/scala/is/hail/expr/ir/functions/GenotypeFunctions.scala, hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala, hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala, hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala, hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
() => IEmitCode is now a worse version of EmitCode!
=> [query] Refactor registerIEmitCode to use EmitCode instead of thunks

notebook/notebook/notebook.py
I previously add an `on_cleanup` but only added it to the `workshop_app` and forgot the `notebook_app`, so I consolidated their setup too.
=> [notebook] cleanup notebook_app too and refactor app config

hail/python/requirements.txt
Qi said a Terra person asked for this.
=> [query] Update scipy version range, which I think we just use for tests

batch/batch/worker/worker.py
The delay was at the wrong indent level.
=> [batch] Fix delay in worker

batch/batch/driver/create_instance.py
Without this change, we race against dockerd. If the chain does not exist
before we add the rules, then containers will be able to access the metadata server
other containers, etc.
=> [batch] wait for iptables chain before initializing

ci/ci/ci.py, ci/ci/github.py
Now shows the source branch in the batch and PR pages along with the other attributes.
=> [ci] add source branch to PR batch attributes

.pre-commit-config.yaml, address/deployment.yaml, atgu/deployment.yaml, auth/deployment.yaml, batch/deployment.yaml, benchmark-service/deployment.yaml, ci/deployment.yaml, monitoring/deployment.yaml, notebook/deployment.yaml, router-resolver/deployment.yaml, router/deployment.yaml, scorecard/deployment.yaml, site/deployment.yaml
This is still quite generous, based on activity from the past week in Grafana, but the goal is to get the utilization to rise to "interesting" levels. Since this doesn't touch limits, I'm tempted to just set requests to the minimum and correct if necessary, but am open to opinions. I also didn't touch `memory` or `query` since those requests seemed more intentional.
=> [k8s] Reduce resource requests

hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
=> [query] Convert some EmitCode.apply to EmitCode.present

batch/Dockerfile.worker, batch/Makefile, batch/batch/front_end/front_end.py, batch/batch/front_end/validate.py, batch/batch/worker/worker.py, batch/download-gcs-connector.py, build.yaml, hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
Currently, this just spins up a new JVM instance; I need to integrate this with a different branch with a standing JVM server that listens on a TCP socket for incoming jobs.
=>  [query-service] add JVM jobs to worker

hail/python/hailtop/aiogoogle/client/storage_client.py
=> [aiogoogle] fix incorrect logic in resumable upload status check

batch/batch/driver/create_instance.py
https://docs.docker.com/storage/storagedriver/overlayfs-driver/
=> [batch] Fix XFS settings for overlayfs in docker

hail/python/hailtop/aiogoogle/client/storage_client.py
=> [aiogoogle] fix typo

hail/python/hailtop/aiogoogle/client/storage_client.py
I think this is the last one.  The tests passed 30 times without a failure.
=> [aiogoogle] another fix to the write logic

scorecard/scorecard/scorecard.py
Apparently scorecard automatically creates a page for you: https://scorecard.hail.is/users/CDiaz96, but this will add you to the random reviewer picker at the bottom of https://scorecard.hail.is/.
=> [scorecard] add Carolin to scorecard

batch/batch/batch.py, batch/batch/driver/main.py, batch/batch/front_end/front_end.py, batch/batch/front_end/templates/batches.html, batch/test/test_accounts.py, batch/test/utils.py, benchmark-service/benchmark/benchmark.py, ci/Makefile, ci/ci/ci.py, ci/ci/github.py, hail/python/hailtop/batch_client/aioclient.py, hail/python/hailtop/batch_client/client.py
There might be an opportunity to also push NOT DELETED into the decorator as well. I chose the decorator route because it's cleaner and I expect a more complicated query for checking permissions in the future.
=> [batch] Give users in billing project access to batches, jobs

auth/deployment.yaml, batch/deployment.yaml, ci/deployment.yaml, grafana/deployment.yaml, scorecard/deployment.yaml, site/deployment.yaml
A more accurate representation of resource needs.
=> [k8s] update resource requests

batch/deployment.yaml, monitoring/deployment.yaml
=> [batch][monitoring] either use deploy or scope, not both

batch/batch/inst_coll_config.py
Stupid bug! I'm not sure why no one ran into this yet.
=> [batch] Fix issue when computing compatible resources

query/test/test_query.py
This is all changing with my new PR, let's just get it out so it stops bothering us.
=> [query-service] remove flaky test code

batch/batch/front_end/front_end.py
Stupid bug. Had close instead of create.
=> [batch] Fix create billing projects in UI

hail/build.gradle
I was asked to agree to some license after clearing my gradle cache. I do not think anyone needs this.
=> [query] remove build scan

batch/batch/front_end/front_end.py
-When there were exactly 50 batches it would show a next page button 
that displayed an empty page.
=> [batch] Fixed next page button

build.yaml
@danking Is 20 min appropriate? It's currently an hour.
=> [batch] Add timeout to test_hail_services_java

build.yaml
Secrets needed to dev deploy site.
=> [k8s] add dataproc secret to createNamespace

dev-docs/hail-for-new-engineers.md
This doc introduces the entire Hail project to new software engineers. This is a response to
Carolin's and Daniel's critiques of our on-boarding documentation.
I think there's a lot more to say, but I think it's time for some feedback before I continue.
The other things I want to document:
- How we use git? Including practical examples.
- What does genetic data look like?
- What is a GWAS?
- What is PCA as applied to genetics?
- A Tour of Hail Query (in the spirit of Soustroup's a Tour of C++).
- A Bibliography of Hail Team's recommended books.
=> [dev-docs] Hail For New Engineers

ci/ci/ci.py, ci/ci/constants.py, ci/ci/github.py, ci/ci/templates/team-table.html, ci/ci/templates/user.html
CI user page now contains assigned PRs and random team member selection. These seem to me like the only features of scorecard people use and potentially eliminates the need for scorecard altogether. The CSS is a little crude but I'm hoping it's temporary, also happy to take suggestions.
=> [ci] bring over useful scorecard features to ci user page

hail/src/main/scala/is/hail/types/physical/PCanonicalNDArray.scala
```
linear_regression_rows_nd      35.8%    274.506     98.311
```
=> [query] Method-wrap NDArray constructor code

hail/python/hailtop/utils/__init__.py, hail/python/hailtop/utils/process.py, tls/config.yaml, tls/create_certs.py
We should just always use async everywhere.
=> [tls] async create_certs

hail/python/hailtop/utils/__init__.py, hail/python/hailtop/utils/process.py, tls/config.yaml, tls/create_certs.py
Reverts hail-is/hail#9738. Concurrently creating certs doesn't work when OpenSSL assigns consecutive serial numbers.
=> Revert "[tls] async create_certs"

hail/src/main/scala/is/hail/rvd/RVDPartitioner.scala
Looks like this got added in some dndarray work
=> [query] Remove verbose print

query/query/query.py
Only one coro waits on receive now. We still error if a message is sent before
we make our first response.
=> [query-service] fix receive logic

website/website/website.py
Response doesn't take positional args so this endpoint is failing.
=> [website] pass response body as kwarg

hail/python/hail/expr/expressions/typed_expressions.py, hail/python/hail/methods/statgen.py, hail/python/test/hail/expr/test_ndarrays.py, hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/NumericPrimitives.scala, hail/src/main/scala/is/hail/types/physical/stypes/SCode.scala, libhail/src/hail/query/backend/compile.hpp
Finally correcting this glaring omission, this PR adds ability to sum ndarray along an axis. This is generally useful, but is also necessary for lowering BlockMatrix.sum.
=> [query] NDArray Sum

batch/batch/batch.py, batch/batch/front_end/front_end.py, batch/batch/front_end/templates/batch.html, batch/batch/front_end/templates/batches.html, batch/batch/front_end/templates/job.html, batch/test/test_dag.py, hail/python/hailtop/batch_client/aioclient.py, hail/python/hailtop/batch_client/client.py
@danking Feel free to reassign to Carolin if you're happy with the overall concept. We were trying to check off a task for February on the ToDo list.
cc: @CDiaz96
=> [batch] Add more info to UI pages

benchmark-service/Dockerfile.test, benchmark-service/test/test_update_commits.py, ci/Dockerfile.test, ci/test/test_ci.py, docker/requirements.txt, hail/python/dev-requirements.txt, hail/python/test/hail/expr/test_ndarrays.py, hail/python/test/hail/linalg/test_linalg.py, monitoring/Dockerfile.test, monitoring/test/test_monitoring.py
Issues like this https://ci.hail.is/batches/221291/jobs/112 do not appear locally for me,
I suspect this is due to my using a much newer pytest.
=> [docker][hail] update to latest pytest

address/deployment.yaml, atgu/atgu/atgu.py, auth/auth/auth.py, auth/deployment.yaml, memory/deployment.yaml, memory/memory/memory.py, notebook/deployment.yaml, notebook/notebook/notebook.py, query/deployment.yaml, query/query/query.py, website/deployment.yaml, website/website/website.py
Added endpoint monitoring to auth, query, memory, atgu, workshop and website, as well as removed an unused label on address.
=> [metrics] add metrics collection to API endpoints across services

batch/batch/driver/main.py
Tracks latency and status code metrics on endpoints so we can see those too in the batch grafana dashboard.
=> [batch-driver] track endpoint metrics for batch-driver too

hail/python/test/hailtop/test_aiogoogle.py
This test fails often ([for example](https://ci.hail.is/batches/234836/jobs/73)). I do not believe the test itself is being cancelled
by pytest-asyncio. Instead, I believe the aiotools code inadvertantly allows a
`CancelledError` to bubble to the top-level. Unfortunately, `asyncio` appears
to treat that as if the *task itself was cancelled*. Because it treats the
task as cancelled, we lose the stack trace (which would tell us where
we were just before the cancellation occurred).
You can see for yourself this unfortunate behavior here:
```
In [1]: import asyncio 
...:  
...: async def foo(): 
...:     raise asyncio.CancelledError() 
...:  
...: loop = asyncio.get_event_loop() 
...: future = asyncio.ensure_future(foo()) 
...: # allow the loop to run long enough that foo gets scheduled 
...: …
```
=> [aiotools] add better debugging information for flaky test

batch/batch/worker/worker.py
This is a simplified implementation of `Process.communicate`. We feed lines into the log one-by-one
until we reach the end of both stdout and stderr. When both stdout and stderr have been closed by
the child process, we wait for the process to exit. At any point in time, the most recent log is
available to us.
=> [batch] make JVM logs real-time

build.yaml, query/Dockerfile, query/Makefile
We only need files in the query folder.
=> [query-service] reduce unnecessarily broad docker context

hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala, hail/src/main/scala/is/hail/backend/service/Worker.scala
@daniel-goldstein, you and I are both modifying this class. I want to relocate it for
ease of editing/discovery. I hope we can merge this before either of our PRs lands, so
the rebase is easier.
=> [query-service] move Worker to Worker.scala

hail/python/hailtop/aiogoogle/client/storage_client.py
This is a temporary fix for the sporadic copy failures.  The problem is that this code cancels a task managed by the online bounded pool, and the pool treats that cancellation as an exception that it propagates up.
I need to think through the details of the bounded gather with respect to cancellation, and that's going to take a few days.  We could put this back when that's done, but honestly, it doesn't seem like an important optimization (given how rarely this failure comes up), so I'll probably just leave it out.
=> [batch/copy] fix for sporadic copy failures (1/2)

hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
Created by PR here: https://github.com/hail-is/sparkmonitor/pull/5
=> [dataproc] Update sparkmonitor to version that supports spark 3

hail/python/cluster-tests/cluster-start-stop.py, hail/src/main/scala/is/hail/HailContext.scala, hail/src/main/scala/is/hail/backend/Backend.scala, hail/src/main/scala/is/hail/backend/BackendUtils.scala, hail/src/main/scala/is/hail/backend/HailTaskContext.scala, hail/src/main/scala/is/hail/backend/local/LocalBackend.scala, hail/src/main/scala/is/hail/backend/service/Worker.scala, hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala, hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala, hail/src/main/scala/is/hail/expr/ir/ExecuteContext.scala, hail/src/main/scala/is/hail/expr/ir/TableIR.scala, hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala, hail/src/main/scala/is/hail/io/bgen/BgenRDD.scala, hail/src/main/scala/is/hail/io/bgen/IndexBgen.scala, hail/src/main/scala/is/hail/linalg/BlockMatrix.scala, hail/src/main/scala/is/hail/sparkextras/ContextRDD.scala, hail/src/main/scala/is/hail/stats/LinearMixedModel.scala, hail/src/test/scala/is/hail/TestUtils.scala, hail/src/test/scala/is/hail/methods/LocalLDPruneSuite.scala
Part 1 of exposing FS correctly in service backend.
=> [query] Simplify HailTaskContext logic

batch/batch/worker/worker.py
I thought this went in under #10252 but turns out it was just for `DockerJob` and needed to do the same for a `JVMJob`.
=> [batch] dont clean up on cancelled JVM job

hail/python/hailtop/utils/utils.py
Importantly, I want to see the stack trace in either case.
=> [hailtop] use the exact same error message for sync and async

dev-docs/tls-cookbook.md
#assign services (@daniel-goldstein Thanks for implementing this, it's awesome!)
=> [infra] add hail_version in TLS cookbook

internal-gateway/internal-gateway.nginx.conf
=> [internal-gateway] only limit requests to batch-driver instances

hail/src/main/scala/is/hail/expr/ir/Emit.scala
Generates a lot of bytecode and called in performance-sensitive places. Helps with profiling a bit.
=> [query] Method-wrap ArrayRef bounds check

hail/python/hailtop/aiotools/fs.py
=> [copy] Fix assertion error on exceptions

build.yaml, ci/test/resources/build.yaml
I ran our build.yaml through yq and am committing the results.
=> [build.yaml] use consistent formatting

batch/batch/worker/worker.py, docker/Makefile, docker/genetics/Dockerfile, docker/publish-public-images.sh, hail/python/hailtop/batch/hail_genetics_images.py
Now these images live at gcr.io/hail-vdc/hailgenetics/hail and gcr.io/hail-vdc/hailgenetics/genetics.
=> [hailgenetics] update the hailgenetics images, fix Makefile

infra/README.md
@cseed, I want to add a new bucket for Hail Query to use for its own purposes. I tried to add it to
Terraform. I ran into some issues which I've fixed here.
Additionally, when I run `terraform plan -var-file="$HOME/.hail/global.tfvars`, it claims I need to
create all 82 resources. Do you know what is wrong? I thought terraform would recognize our, for
example, our MySQL database.
=> [terraform] fixes

docker/hail/Dockerfile
This allows this to be used with PythonJob.
=> [hailgenetics/hail] add dill to the image

hail/python/hail/ir/__init__.py, hail/python/hail/ir/matrix_writer.py, hail/python/hail/matrixtable.py, hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala, hail/src/main/scala/is/hail/expr/ir/Parser.scala, hail/src/main/scala/is/hail/expr/ir/functions/MatrixWriteBlockMatrix.scala, hail/src/main/scala/is/hail/expr/ir/functions/RelationalFunctions.scala, hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
Previously we had a weird void typed `MatrixToValueFunction`. Makes more sense to just have a writer.
=> [query] MatrixWriteBlockMatrixWriter

devbin/sync.py
stacked on https://github.com/hail-is/hail/pull/10341
=> [sync.py] more improvements to avoid unnecessary extra reloadings

atgu/Makefile, auth/Makefile, batch/Dockerfile.worker, batch/Makefile, build.yaml, ci/Makefile, ci/ci/build.py, ci/test/resources/build.yaml, monitoring/Makefile, notebook/Makefile
stacked on https://github.com/hail-is/hail/pull/10354, will fail until that PR merges
=> [ci] checkout repository once

ci/Makefile
I changed this late in the PR and forgot to update the Makefile.
=> [ci] fix Kaniko make target

hail/python/test/hail/table/test_table.py, hail/src/main/scala/is/hail/annotations/Region.scala, hail/src/main/scala/is/hail/annotations/RegionMemory.scala, hail/src/main/scala/is/hail/annotations/RegionPool.scala, hail/src/main/scala/is/hail/expr/ir/package.scala, hail/src/main/scala/is/hail/expr/ir/streams/EmitStream.scala, hail/src/main/scala/is/hail/utils/richUtils/RichCodeRegion.scala, hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
- add 1st round of tests for stream memory usage
- clarify streamfilter implementation (no bug here though)
=> [query] Fix memory management in new stream emitter

batch/batch/worker/disk.py
Also, make sure we always delete the disk despite any failures
=> [batch] Add logs to disk operations

hail/src/main/scala/is/hail/annotations/RegionPool.scala
It was unused / never updated.
=> [query] Remove maxNumJavaObjects

hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
Optimize lowered TableHead to not scan a partition past the requested number of rows.
Currently TableHead performs a loop, calculating the lengths of the first 4 partitions, then the first 16, etc. If we fix it to not count a partition multiple times, instead starting each loop at the first uncounted partition, we can further optimize to stop scanning a partition after the number of rows still needed (requested number minus sum of partitions counted so far).
Note that there is no similar optimization to TableTail. We must compute the full length of each partition, to compute how many rows to drop.
=> [query] Let lowered TableHead short-circuit

batch/test/test_batch.py
I couldn't find any usages of this anywhere.
=> [batch] remove unused test utility

batch/batch/driver/instance_collection.py
after 5+ failed requests and 5+ minutes since last successful request
=> [batch] kill workers that are not responding

datasets/extract/extract_CADD.py, datasets/notebooks/CADD_datasets.ipynb, hail/python/hail/docs/datasets/schemas/CADD.rst, hail/python/hail/experimental/datasets.json
Adds [CADD](https://cadd.gs.washington.edu/download) v1.6 Hail Tables to datasets API/annotation DB.
=> [datasets] [annotationdb] add CADD v1.6 tables

hail/python/hailtop/aiogoogle/auth/credentials.py, hail/python/hailtop/aiogoogle/client/storage_client.py, hail/python/hailtop/aiotools/fs.py, hail/python/test/hailtop/aiotools/test_copy.py, hail/python/test/hailtop/test_aiogoogle.py
- Also handle case with GCS files ending in a slash
=> [copy] Fix copying file with name ending in slash

hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala, hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala, hail/src/main/scala/is/hail/expr/ir/streams/EmitStream.scala, hail/src/main/scala/is/hail/types/physical/stypes/SType.scala, hail/src/main/scala/is/hail/types/physical/stypes/concrete/SBaseStructPointer.scala, hail/src/main/scala/is/hail/types/physical/stypes/concrete/SSubsetStruct.scala, hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SBaseStruct.scala
Needed to add a bit more tooling to emitcode/emitsettable/emittype for stack struct purposes.
=> [compiler] Some groundwork for SStackStruct

hail/python/hailtop/aiogoogle/client/storage_client.py, hail/python/hailtop/aiotools/fs.py, hail/python/test/hailtop/aiotools/test_copy.py, hail/python/test/hailtop/test_aiogoogle.py
=> [fs] Add higher level fs operations

hail/python/hailtop/batch/backend.py
CHANGELOG: Fixed the error 'Argument list too long: '/bin/sh'' when using the LocalBackend
=> [batch] Fix local backend too many args error

hail/python/hailtop/batch/docs/change_log.rst
=> [docs] fix list formatting

hail/python/hail/backend/spark_backend.py, hail/python/hail/experimental/vcf_combiner/vcf_combiner.py, hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
=> [combiner] Redesign combiner matrix reads to avoid interval duplication

hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala, hail/src/main/scala/is/hail/expr/ir/NativeReaderOptions.scala, hail/src/main/scala/is/hail/expr/ir/Pretty.scala, hail/src/main/scala/is/hail/expr/ir/TableIR.scala, hail/src/main/scala/is/hail/io/TextMatrixReader.scala, hail/src/main/scala/is/hail/io/bgen/LoadBgen.scala, hail/src/main/scala/is/hail/io/gen/LoadGen.scala, hail/src/main/scala/is/hail/io/plink/LoadPlink.scala, hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala, hail/src/main/scala/is/hail/utils/TextTableReader.scala, hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala, hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
This lets us avoid crashes/ooms from rendering 90K intervals thousands of times.
Stacked on #10517
=> [combiner] Override JSON rendering for reader

hail/python/hail/expr/expressions/typed_expressions.py, hail/python/test/hail/expr/test_ndarrays.py
Adding support to nd arrays to include less than max dimension indexing and the use of ellipses to echo numpy behavior.
=> Add ellipses and less than max dimension indexing to nd arrays

hail/python/hailtop/aiogoogle/auth/session.py, hail/python/hailtop/httpx.py
Addresses conversation in #10432
=> [httpx] Add response body when raising for status

hail/python/hail/experimental/datasets.py
To allow users on GCP to access datasets that are only available on AWS (e.g. pan-ukb LD block matrices and tables). 
If trying to read dataset from `s3` path throws `FatalError: UnsupportedFileSystemException: No FileSystem for scheme "s3"`, then will read with the `s3a` prefix instead.
=> [datasets] modify `load_dataset` to handle s3/s3a

hail/python/hail/experimental/vcf_combiner/__main__.py, hail/python/hail/experimental/vcf_combiner/vcf_combiner.py
=> [combiner] Use batch size of 1 for phases after 1.

hail/python/hailtop/utils/utils.py
The assumption of the bounded gather operations is that threads of
control hold the bounding semaphore.  That means, when the bounded
gather operations should be called from a thread of control which
holds the semaphore and when those operations need to block internally
(by calling wait or gather, say) it should release the semaphore.  I
added a "WithoutSemaphore" semaphore release manager to implement this
pattern and use it in the bounded gather operations.
=> [hailtop] Replace Subsemaphore with a semaphore release manager.

benchmark/python/benchmark_hail/compare/compare.py, benchmark/python/benchmark_hail/run/__init__.py, benchmark/python/benchmark_hail/run/sentinel_benchmarks.py
Use pure Python to do some IO and CPU work. This will help
identify fraught comparisons between benchmark runs.
=> [benchmark] Add sentinel benchmarks

hail/python/hailtop/aiotools/stream.py
The original problem we were seeing was this error message:
```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe17e8c4bd0>
File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.7/site-packages/batch/copy/__main__.py", line 34, in <module>
asyncio.run(main())
File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
return loop.run_until_complete(main)
File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
return future.result()
concurrent.futures._base.CancelledError
sys:1: RuntimeWarning: coroutine …
```
=> [aiotools] Fix out of memory bug when using writable streams

hail/python/hail/expr/expressions/typed_expressions.py, hail/python/hail/nd/__init__.py, hail/python/test/hail/expr/test_ndarrays.py, hail/src/main/scala/is/hail/expr/ir/Emit.scala
NDArrayExpression now supports np.newaxis when slicing.
=> CHANGELOG: Added support for np.newaxis to NDArrayExpression.__getitem__

grafana/deployment.yaml
There's some nice QoL updates and new chart types
=> [grafana] update to Grafana v8

dev-docs/batch-operation.md
=> [devdocs] batch operation: quotas

batch/batch/worker/worker.py
Pending confirmation from Ben W. that this is indeed a user error...
=> [batch] Add user error for bad gcsfuse creds

hail/python/test/hail/methods/test_impex.py, hail/src/main/scala/is/hail/io/plink/LoadPlink.scala
CHANGELOG: Fixed partitioning logic in `hl.import_plink`
=> [query] Fix import_plink partitioning logic

benchmark/python/benchmark_hail/run/matrix_table_benchmarks.py
Also rename so that these don't pop up as spurious performance changes
=> [benchmark] Fix scan benchmarks

batch/batch/front_end/front_end.py, batch/batch/front_end/templates/billing.html, web_common/web_common/templates/header.html
New PR for #10656 -- forgot I rebased and pushed before I reopened the PR. I tried a bunch of complicated table formats and decided just showing the one table for non-dev users with billing_project x user should be straightforward.
=> [batch] Expose billing page to non-dev users

hail/python/hail/experimental/vcf_combiner/__init__.py, hail/python/hail/ir/register_functions.py, hail/python/hail/vds/__init__.py, hail/python/hail/vds/functions.py, hail/python/test/hail/vds/test_vds_functions.py, hail/src/main/scala/is/hail/expr/ir/functions/CallFunctions.scala, hail/src/main/scala/is/hail/methods/IBD.scala, hail/src/main/scala/is/hail/types/physical/stypes/concrete/SCanonicalCall.scala, hail/src/main/scala/is/hail/types/physical/stypes/concrete/SUnreachable.scala, hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SCall.scala, hail/src/main/scala/is/hail/variant/Call.scala, hail/src/main/scala/is/hail/variant/Genotype.scala
Now supports 0-ploid and haploid as well as diploid.
=> Fix LGT_TO_GT to be a registered function

batch/batch/driver/create_instance.py, batch/batch/driver/gce.py, batch/batch/driver/instance.py, batch/batch/driver/job_private.py, batch/batch/driver/main.py, batch/batch/driver/pool.py, batch/batch/worker_config.py, batch/sql/add-instance-config.sql, batch/sql/estimated-current.sql, build.yaml
cc: @daniel-goldstein Can you double check the database changes?
=> [batch] Add prometheus stats for user resources and instances

hail/python/hailtop/aiotools/s3asyncfs.py
boto is synchronous.  The AsyncFS create interface returns a writable file-like object, which means the S3 request has to be run in a thread in the background.  Originally, I was using the thread pool for that. However, if we fill the thread pool with create requests, then there are no threads for other operations, so client code can deadlock.  Instead, run the create requests in a new thread.
=> [asyncfs] fix deadlock in S3 backend

hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
*DDS = distributed distribution sort.
=> [query-service] Use local sort for ServiceBackend until DDS* is live.

batch/batch/copy/__main__.py, batch/batch/driver/create_instance.py, batch/batch/driver/job.py, batch/batch/driver/main.py, batch/batch/front_end/front_end.py, batch/batch/log_store.py, batch/batch/spec_writer.py, batch/batch/worker/worker.py, benchmark-service/benchmark/benchmark.py, benchmark-service/benchmark/utils.py, benchmark-service/test/test_update_commits.py, build.yaml, hail/python/hailtop/aiogoogle/auth/credentials.py, hail/python/hailtop/aiotools/fs.py, hail/python/hailtop/batch/batch_pool_executor.py, hail/python/hailtop/google_storage.py, memory/memory/client.py, memory/memory/memory.py, memory/test/test_memory.py
=> Revert "[batch] replace GCS with GoogleStorageAsyncFS in LogStore"

hail/src/main/scala/is/hail/expr/ir/FoldConstants.scala, hail/src/main/scala/is/hail/types/physical/stypes/SCode.scala, hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SBaseStruct.scala, hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SBinary.scala, hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SCall.scala, hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SContainer.scala, hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SLocus.scala, hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SString.scala, hail/src/main/scala/is/hail/types/physical/stypes/primitives/SBoolean.scala, hail/src/main/scala/is/hail/types/physical/stypes/primitives/SFloat32.scala, hail/src/main/scala/is/hail/types/physical/stypes/primitives/SFloat64.scala, hail/src/main/scala/is/hail/types/physical/stypes/primitives/SInt32.scala, hail/src/main/scala/is/hail/types/physical/stypes/primitives/SInt64.scala, hail/src/test/scala/is/hail/asm4s/CodeSuite.scala
Draft of hashcodes for SValues
=> [query] Hash codes

hail/python/hail/expr/functions.py
=> [query] fix error in hardy_weinberg_test docs

batch/batch/copy/__main__.py, ci/bootstrap.py, ci/bootstrap.yaml, ci/create_initial_account.py, infra/README.md, infra/main.tf
A little pieced together but these are my notes from getting batch set up in a new GCP project. Most is copied from @cseed's recent branch with a few additional fixes.
One not-great thing is that gateway fails to start if it can't resolve its upstream hosts, so I had to effectively remove the server blocks for anything not batch/batch-driver/auth by editing `letsencrypt/subdomains.txt` and then redeploying the gateway. Weird thing is that I deleted the batch deployment and new gateway pods started up fine, so perhaps it's something to do with kube-dns? Planning to look into this as a follow-up.
=> [infra] Refresh infra setup instructions

hail/src/main/scala/is/hail/expr/ir/Children.scala, hail/src/main/scala/is/hail/expr/ir/Copy.scala, hail/src/main/scala/is/hail/expr/ir/IR.scala, hail/src/main/scala/is/hail/expr/ir/IRBuilder.scala, hail/src/main/scala/is/hail/expr/ir/InferType.scala, hail/src/main/scala/is/hail/expr/ir/Requiredness.scala, hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala, hail/src/main/scala/is/hail/expr/ir/streams/EmitStream.scala, hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
This PR adds `SeqSample(totalRange, numToSample)`, a stream IR that generates a stream of `numToSample` unique random integers in the range `totalRange`.
=> [query] SeqSample

hail/src/main/scala/is/hail/asm4s/Code.scala, hail/src/main/scala/is/hail/expr/ir/Simplify.scala, hail/src/test/scala/is/hail/expr/ir/SimplifySuite.scala
Added rules to simplify ArraySlice IR
=> [query] ArraySlice simplify

hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/types/physical/stypes/concrete/SNDArrayPointer.scala, hail/src/main/scala/is/hail/types/physical/stypes/concrete/SNDArraySlice.scala, hail/src/main/scala/is/hail/types/physical/stypes/concrete/SUnreachable.scala, hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SNDArray.scala
I pulled this out of my local whitening branch. It's being tested there, but I'm not sure the best way to write unit tests. Do we have any similar tests for STypes?
=> [query] add SNDArraySlice

hail/src/main/scala/is/hail/asm4s/Code.scala, hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SNDArray.scala
=> [query] add wrappers for gemm, geqrf, orgqr

hail/python/hailtop/batch/backend.py
@danking Assigning to you since Daniel's out today.
=> [batch] Fix Backend.close to be idempotent

build.yaml
I've deleted the secret already in kubernetes.
=> [asana] Remove reference to unused token

hail/src/main/scala/is/hail/expr/ir/Binds.scala, hail/src/main/scala/is/hail/expr/ir/Children.scala, hail/src/main/scala/is/hail/expr/ir/Copy.scala, hail/src/main/scala/is/hail/expr/ir/IR.scala, hail/src/main/scala/is/hail/expr/ir/InferType.scala, hail/src/main/scala/is/hail/expr/ir/Interpret.scala, hail/src/main/scala/is/hail/expr/ir/NestingDepth.scala, hail/src/main/scala/is/hail/expr/ir/NormalizeNames.scala, hail/src/main/scala/is/hail/expr/ir/Parser.scala, hail/src/main/scala/is/hail/expr/ir/Pretty.scala, hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala, hail/src/main/scala/is/hail/expr/ir/Requiredness.scala, hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala, hail/src/main/scala/is/hail/expr/ir/package.scala, hail/src/main/scala/is/hail/expr/ir/streams/EmitStream.scala, hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala, hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
Also add specialized code generators for range/zipWithIndex
=> [compiler] Rewrite StreamTake and StreamDrop to TakeWhile and DropWhile

hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala, hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
=> [compiler] Rewrite lowered partition alignment with takeWhile/dropWhile 

hail/src/main/scala/is/hail/expr/ir/Interpret.scala, hail/src/main/scala/is/hail/expr/ir/TableIR.scala, hail/src/test/scala/is/hail/expr/ir/LiftLiteralsSuite.scala, hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala, hail/src/test/scala/is/hail/expr/ir/TableIRSuite.scala
=> [compiler] Thread requiredness through TableIR.execute

hail/src/main/scala/is/hail/io/compress/BGzipLineReader.scala, hail/src/main/scala/is/hail/io/tabix/TabixReader.scala, hail/src/main/scala/is/hail/io/vcf/ExportVCF.scala, hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala, hail/src/test/scala/is/hail/io/TabixSuite.scala
Also fix some cleanup warnings that intellij mentioned while touching
these files.
=> [compiler] Use FS over broadcasting in tabix support

infra/azure/.gitignore, infra/azure/README.md, infra/azure/main.tf, infra/azure/variables.tf
This is the initial terraform setup to spinning up resources in azure, from downloading the `az` cli to getting a kubernetes cluster, database and network running. This contains instructions on initializing terraform using a remote backend in an azure container so multiple people should be able to apply terraform changes and have the same view of the system. Next step is setting up the gateway and internal gateways so that we can communicate between k8s services and VMs in the batch worker subnet.
=> [infra] Setup instructions from zero to kubernetes cluster in Azure

hail/build.gradle
These upgrades are simple and do not represent major version upgrades.
=> [query/compiler] Update simple dependencies

grafana/deployment.yaml
I tested the config comes through correctly in my namespace.
=> [grafana] Fix datasources.yaml to include additional settings

batch/batch/front_end/front_end.py, batch/batch/inst_coll_config.py, batch/test/test_batch.py
This fixes the bug where someone submitted a bad storage request and we did not catch it on job submission.
=> [batch] Catch bad storage requests on job submission

build.yaml, docker/requirements.txt, hail/python/hailtop/aiogoogle/client/storage_client.py, hail/python/hailtop/aiotools/__init__.py, hail/python/hailtop/aiotools/azurefs.py, hail/python/hailtop/aiotools/fs.py, hail/python/hailtop/aiotools/utils.py, hail/python/requirements.txt, hail/python/test/hailtop/aiotools/test_copy.py, hail/python/test/hailtop/test_fs.py
This PR adds the Azure AsyncFS. I added a new secret with the Azure credentials for a new service account, adopted the container `hail-test-****` as the test container, and made the container have a 1 day retention policy (we'll want to check and make sure this actually works).
The performance seemed decent. We'll probably want to benchmark this formally at some point, but I think it's good enough for now to have something that works.
=> [aiotools] Azure AsyncFS

batch/Dockerfile.worker, batch/Makefile, batch/batch/driver/create_instance.py, batch/batch/worker/worker.py, batch/build-batch-worker-image-startup.sh, docker/requirements.txt
Reverts hail-is/hail#10693 while we inspect errors pulling large numbers of images at once.
=> Revert "[batch] Replace docker on the worker with podman"

hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala, hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala, hail/src/main/scala/is/hail/expr/ir/agg/AppendOnlyBTree.scala, hail/src/main/scala/is/hail/expr/ir/agg/ArrayElementLengthCheckAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/CollectAsSetAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/GroupedAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/TakeByAggregator.scala, hail/src/main/scala/is/hail/types/encoded/EBaseStruct.scala, hail/src/main/scala/is/hail/types/physical/PBaseStruct.scala, hail/src/main/scala/is/hail/types/physical/PCanonicalBaseStruct.scala, hail/src/main/scala/is/hail/types/physical/PCanonicalInterval.scala, hail/src/main/scala/is/hail/types/physical/PCanonicalStruct.scala, hail/src/main/scala/is/hail/types/physical/PInterval.scala, hail/src/main/scala/is/hail/types/physical/PStruct.scala, hail/src/main/scala/is/hail/types/physical/PSubsetStruct.scala, hail/src/main/scala/is/hail/types/physical/stypes/concrete/SBaseStructPointer.scala, hail/src/main/scala/is/hail/types/physical/stypes/concrete/SInsertFieldsStruct.scala, hail/src/main/scala/is/hail/types/physical/stypes/concrete/SIntervalPointer.scala, hail/src/main/scala/is/hail/types/physical/stypes/concrete/SStackStruct.scala, hail/src/main/scala/is/hail/types/physical/stypes/concrete/SSubsetStruct.scala, hail/src/main/scala/is/hail/types/physical/stypes/concrete/SUnreachable.scala, hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SBaseStruct.scala, hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SInterval.scala, hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala, hail/src/test/scala/is/hail/expr/ir/StagedBTreeSuite.scala
Refactor SBaseStruct.isFieldMissing and dependent methods to `CodeBuilder => Value` style.
=> [compiler] SBaseStruct.isFieldMissing returns value

hail/src/main/scala/is/hail/types/physical/stypes/concrete/SJavaArray.scala
fixed reuse code bug in loadElement in SJavaArray
=> fixed reuse code bug in SJavaArray

batch/batch/front_end/front_end.py
The `GoogleStorageAsyncFS` raises `FileNotFoundError` when a file is not found.
=> [batch] use correct not found error

hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala, hail/src/main/scala/is/hail/expr/ir/agg/ApproxCDFAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/ArrayElementLengthCheckAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/CallStatsAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/CollectAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/CollectAsSetAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/DensifyAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/GroupedAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/TakeAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/TakeByAggregator.scala
=> [compiler] (S)Code->(S)Value in AggregatorState interface

hail/python/hailtop/utils/utils.py
- Botocore (AWS) produces its own ConnectionClosedError (:sad:).
- TIMEDOUT is yet another transient socket issue
- I have seen EAI_NONAME as a transient error, even though I would hope to receive EAI_AGAIN.
=> [utils] more transient errors

hail/python/hail/vds/combiner/variant_dataset_combiner.py
* spelling
* metadata
* argument type hinting
=> [vds/combiner] Minor VDS combiner fixes

hail/python/test/hail/expr/test_expr.py
The ServiceBackend is not yet fast enough to serially execute huge numbers of tests.
=> [query] test a whole bunch of expressions at once

hail/python/hail/experimental/db.py
Currently there are multiple compatible versions of the `CADD` (1.4 and 1.6) and `gnomad_genome_sites` (2.1.1 and 3.1) annotation datasets, which leads to an error in `index_compatible_version`. This PR addresses that by annotating with the highest version number if there are multiple compatible versions of the same dataset. Will likely add fix in future to allow user to specify the version they would like to use, this was just a fairly quick and easy fix in the meantime.
=> [annotationdb] use highest version of annotation dataset if multiple compatible versions exist

docker/hail/Dockerfile
=> [hailgenetics/hail] install pv

atgu/atgu/atgu.py, batch/batch/front_end/front_end.py
Gotta close things that are closable.
=> [batch][atgu] close db

ci/ci/ci.py, ci/ci/templates/pr-table.html
I find this useful for identifying which local branches I can safely delete.
=> [ci] Show source branch name in PR table

dev-docs/key-rotation.md, devbin/rotate_keys.py
Some additional asserts and quality of life messages that I found necessary for confidently rotating keys.
=> [iam] Add rotation status and colors to key rotation info

batch/batch/worker/worker.py
I'm not 100% sure I know the implications of this change with regards to race conditions. I think it's okay? Also, why do we not include the timings if the job is deleted in `__exit__`? This is the current code:
```python3
class ContainerStepManager:
def __init__(self, timing: Dict[str, float], is_deleted: Callable[[], bool], ignore_job_deletion: bool = False):
self.timing: Dict[str, float] = timing
self.is_deleted = is_deleted
self.ignore_job_deletion = ignore_job_deletion
def __enter__(self):
if self.is_deleted() and not self.ignore_job_deletion:
raise JobDeletedError()
self.timing['start_time'] = time_msecs()
def __exit__(self, exc_type, exc, tb):
if self.is_deleted() and not self.ignore_job_deletion:
return
finish_time = time_msecs()
self.timing['finish_time'] = finish_time …
```
=> [batch] Ignore job deletion when uploading the logs

hail/python/hailtop/hailctl/dataproc/submit.py
=> There was no --region flag in submit preventing submission to clusters

hail/python/hailtop/aiotools/aio_contextlib.py, hail/python/hailtop/hailctl/dataproc/cli.py, hail/python/hailtop/hailctl/dataproc/connect.py, hail/python/hailtop/hailctl/dataproc/describe.py, hail/python/hailtop/hailctl/dataproc/diagnose.py, hail/python/hailtop/hailctl/dataproc/list_clusters.py, hail/python/hailtop/hailctl/dataproc/modify.py, hail/python/hailtop/hailctl/dataproc/start.py, hail/python/hailtop/hailctl/dataproc/stop.py, hail/python/hailtop/hailctl/dataproc/submit.py, hail/python/test/hailtop/hailctl/dataproc/test_cli.py
Tested this locally after uploading a tiny dataset to all three clouds.
=> [hailctl] allow describe on s3, hail-az, gs, and local

hail/python/hailtop/utils/utils.py
A little surprised there's no prior mention of 429's in here which made me think I might have put this in the wrong place but afaict this is the way we would retry when being rate limited.
=> [utils] Retry when rate limited

build.yaml
See details here: https://testng.org/doc/documentation-main.html#testng-exit-codes
=> [jvm-services] allow skipped tests in FS tests

batch/batch/driver/main.py, batch/batch/front_end/front_end.py
I'm pretty sure this is why the session messages were gone when trying to configure the pools pages.
=> [batch] Fix validate_int function to not reraise

build.yaml
[Here](https://ci.daniel-azure.hail.is/batches/1253/jobs/129)'s an example of the failing test. I think the `--service-principal` should fix
=> [build.yaml] Fix delete_azure_batch_instances

build.yaml
Fixes az delete VMs hopefully.
=> [build.yaml] export azure resource group to xargs and, transitively, sh

batch/batch/cloud/azure/driver/resource_manager.py
AFAIK, we do not need a distinct name anyway
=> [batch] fix job private jobs

batch/batch/worker/worker.py, hail/python/hailtop/batch/backend.py, hail/python/hailtop/utils/__init__.py, hail/python/hailtop/utils/utils.py
and only use user credentials to pull from same cloud
=> [batch] Clarify DockerHub error message

hail/python/hailtop/batch/docs/service.rst, website/website/pages/gethelp.html, website/website/pages/index.html, website/website/styles/style.scss, website/website/templates/nav-top.html
I promise the style changes are correct, I verified locally by running `make -C website run` and looking at the page. The styles are generally a mess. I made the fewest changes I could to ensure the batch section looks OK.
=> [website] put Hail Batch on the main page

auth/auth/auth.py, auth/auth/driver/driver.py, auth/auth/flow.py, auth/auth/templates/account-error.html, auth/auth/templates/user.html, auth/auth/templates/users.html, auth/deployment.yaml, auth/sql/estimated-current.sql, auth/sql/support-azure-oauth.sql, build.yaml, ci/bootstrap_create_accounts.py, ci/create_initial_account.py, config.mk, hail/python/hailtop/hailctl/auth/login.py, hail/python/hailtop/hailctl/auth/user.py, infra/azure/README.md, infra/azure/bootstrap.sh, infra/azure/main.tf, infra/azure/outputs.tf, infra/azure/service_principal/outputs.tf, infra/azure/variables.tf, infra/bootstrap_utils.sh, infra/gcp/README.md, infra/gcp/main.tf, infra/gcp/outputs.tf, infra/k8s/main.tf, infra/k8s/variables.tf
I think it's going to be too hard to test this PR in dgoldste. I think we should combine getting this PR to work with standing up the Azure production cluster. Until then, I need your help to finish this draft:
@danking -- Can you look over the oauth flow?
@daniel-goldstein -- Next week, can you help out with the necessary Terraform changes?
=> [auth] Add support for Azure Active Directory oauth flows

batch/batch/cloud/azure/driver/resource_manager.py
=> Revert "[batch] use one global deployment"

build.yaml, hail/scripts/deploy.sh
Skopeo needs to know that we are speaking the docker protocol.
=> [deploy] add protocol for skopeo

batch/batch/cloud/azure/driver/create_instance.py
Adding this change first so I can check the tags are added to the deployments before adding the full garbage collection PR. I'm putting the WIP tag on so we don't merge until it's passing on Azure.
=> [batch] Add tags to Azure deployments

ci/buildkit/Dockerfile, docker/third-party/images.txt
I'll copy the images now into Azure and GCP.
=> [ci] remove dependency on docker hub

hail/python/hail/expr/functions.py, hail/python/test/hail/expr/test_ndarrays.py
Used a decorator to make select one argument hail functions work for both numeric expressions and nd arrays filled with numeric expressions.
=> Ndarray broadcasting

batch/batch/worker/worker.py
Not 100% sure this will solve the issue if it's actually more nuanced, but this code should at least be an improvement. For reference, original discussion is here: https://hail.zulipchat.com/#narrow/stream/300487-Hail-Batch.20Dev/topic/Bugs/near/258563670
=> [batch] Fix exec not found bug on the worker

build.yaml, grafana/Makefile, grafana/deployment.yaml, grafana/nginx.conf
This issue didn't manifest until I needed to re-authenticate in azure, at which point grafana tried to bring me to gcp auth and got hella confused.
=> [grafana] Use templated domain instead of hail.is

hail/python/hailtop/aiocloud/aiogoogle/credentials.py
and give the user a warning that they might want to log in. Anonymous credentials will allow us to access public buckets without authenticating, which was not possible until now. I contemplated whether we should only suggest the login if they've received a 401 but I assume most everyone using this will want to be authenticated and we already log a warning as it is.
This is reasonably testable, but I couldn't find where it should go. Does `test_fs` test credential-loading at all?
=> [aiogoogle] Use anonymous credentials when not in GCE

hail/src/main/scala/is/hail/HailContext.scala, hail/src/main/scala/is/hail/backend/local/LocalBackend.scala, hail/src/main/scala/is/hail/expr/ir/EmitStreamDistribute.scala, hail/src/main/scala/is/hail/expr/ir/IR.scala, hail/src/main/scala/is/hail/expr/ir/Optimize.scala, hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala, hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala, hail/src/main/scala/is/hail/expr/ir/functions/RandomSeededFunctions.scala, hail/src/main/scala/is/hail/expr/ir/lowering/LowerDistributedSort.scala, hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala, hail/src/main/scala/is/hail/expr/ir/package.scala, hail/src/main/scala/is/hail/expr/ir/streams/EmitStream.scala, hail/src/test/scala/is/hail/expr/ir/lowering/LowerDistributedSortSuite.scala
PRing for test suite, but it's mostly working. 
Todo:
=> [query] New Shuffler

hail/python/hail/vds/methods.py, hail/python/test/hail/vds/test_vds.py
Bins now use `>=` comparisons instead of `>`
=> [vds] Change definitions of coverage in interval_coverage and sample_qc

hail/python/hail/vds/methods.py, hail/python/test/hail/vds/test_vds.py
Match interval_coverage, and annotate a global field with the bins used.
Stacked on #11243
=> [vds] Introduce DP calculations to vds.sample_qc, change field names

hail/python/hail/docs/ggplot/index.rst, hail/python/hail/ggplot/__init__.py, hail/python/hail/ggplot/geoms.py, hail/python/hail/ggplot/stats.py, hail/python/test/hail/ggplot/test_ggplot.py
Adds `geom_col`, which is like `geom_bar` except it expects you to specify the `y` aesthetic to determine bar height rather than doing a count aggregation.
Also took opportunity to lift stats into their own file.
=> [ggplot] Add geom_col

batch/sql/estimated-current.sql, batch/sql/fix-n-cancelled-creating-jobs.sql, build.yaml
I ran the select ... from (select ...) part of the UPDATE which fixes
this issue. It completed in ~72 seconds, so I think this change is actually
plenty fast to run.
=> [batch] fix n cancelled creating jobs

hail/python/hailtop/aiocloud/aioazure/fs.py
I can't figure things out without a url.
=> [hailtop] better errors in Azure FS

batch/batch/driver/main.py
Without this change, no error is raised and we never record
that there was a check incremental failure.
=> [batch] raise error in check incremental

infra/azure/variables.tf
=> [infra] use Premium ACR

ci/ci/build.py, ci/ci/github.py, ci/deployment.yaml, ci/test/resources/build.yaml, infra/azure/README.md
=> [ci] Make zulip-config optional

hail/python/hail/linalg/utils/misc.py
Trying to get to the bottom of https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query.200.2E2.20support/topic/locus_windows.20Error/near/270984913
=> [query] Better error message on locus_windows

docker/requirements.txt, hail/python/dev-requirements.txt
=> [chore] Update pytest

infra/azure/main.tf, infra/azure/modules/auth/main.tf, infra/azure/modules/auth/variables.tf, infra/azure/variables.tf
I tested this and it indeed has no conflicts if I include Daniel, Jackie, and I in the oauth2 callbacks list.
=> [infra] allow configuration of oauth2 callback list

hail/src/main/scala/is/hail/expr/ir/Emit.scala, hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala, hail/src/main/scala/is/hail/expr/ir/IR.scala, hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala, hail/src/main/scala/is/hail/expr/ir/functions/IntervalFunctions.scala, hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala, hail/src/main/scala/is/hail/expr/ir/streams/EmitStream.scala, hail/src/main/scala/is/hail/types/physical/stypes/concrete/SIntervalPointer.scala, hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
This will be used to lower TableIntervalJoin.
=> [compiler] StreamJoinRightDistinct handles intervals on right

hail/python/hail/backend/service_backend.py
orjson is substantially faster.
I promise it looks nice with whitespace changes hidden.
=> [query/service] use orjson and track timings

infra/azure/modules/batch/outputs.tf
=> [infra] Fix query bucket output in Azure

hail/scripts/deploy.sh
I used the relevant portion of deploy.sh to create this PR: https://github.com/DataBiosphere/terra-docker/pull/303
=> [deploy.sh] DataBiosphere PRs must come from non-fork branches

query/Makefile
I forgot to include this in my previous PR. I have it set like this
in my .zshrc, so I did not notice.
=> [query] set HAIL_QUERY_BACKEND in query/Makefile

batch/batch/cloud/azure/driver/resource_manager.py
The [API](https://docs.microsoft.com/en-us/azure/virtual-machines/states-billing) optionally postfixes an error code/modifier so it seems more robust to look at the prefixes here. This currently manifested with a `ProvisioningState/failed/AllocationFailed` state leaving an instance forever pending.
=> [batch] Use code prefixes to detect vm states

batch/batch/driver/instance_collection/base.py
Currently, an instance that is `inactive` in batch and `Terminated` per the cloud will enter the second branch and we will call `deactivate`, which since the instance is already inactive will be a no-op. We really want the third branch to be executed in which we call delete on the instance, so that the inactive instances don't hang around forever.
Vedant and I paired on this and did some case analysis to restructure the conditions here a little bit. The order of the conditions now doesn't matter and is hopefully more explicit. We also decided that an unspoken case (deleted but not terminated) should be an error scenario, let me know if you think that is an appropriate exception to log here.
=> [batch] Fix monitor instances loop to delete inactive instances

hail/python/hail/ggplot/ggplot.py
- Better defaults for professional looking plots
- Adjusted title size defaults
The old defaults were somewhat arbitrary, the new defaults are requested by Alicia's group. It's likely defaults will continue to move around a bit until we arrive at something stable and have good options in place to tweak plot aesthetics.
=> Change default styles for hail ggplot

hail/src/main/scala/is/hail/services/package.scala
Closes hail-is/hail-production-issues#12.
Details [here](https://github.com/hail-is/hail-production-issues/issues/12).
=> [services-java] new transient error observed

build.yaml
These tests run for ~35 minutes right now.
=> [fs] parallelize cloud file system tests

batch/batch/front_end/front_end.py, batch/batch/worker/worker.py
I hope I finally squashed this issue for good where cancelled jobs wouldn't have data to show in the UI. I apologize that the diff is not great for this change. I tested all 5 possible cases in the UI by hand.
=> [batch] Show logs and status for running cancelled jobs

hail/build.gradle
- Keep ES transitive = false
- Explicitly exclude spark from import
=> Always Exclude Spark from Build

batch/test/test_accounts.py
These are failing a bunch of PRs which is impairing our ability
to get features merged. Hopefully these delays give the DB enough
time to process the add_attempt_resources.
We can properly fix this in Q2.
=> [batch] mitigate some of the cost test failures

batch/test/test_accounts.py
Mitigation for hail-is/hail-production-issues#3
=> [batch] Mitigate accrued_costs test failure

batch/batch/worker/worker.py
cc: @daniel-goldstein 
I am not sure what change uncovered this latent bug; however, I am
pretty certain I understand the bug.  I have seen this happen in GCP
and in Azure. Take a look at an interval of driver logs:
```
INFO	2022-03-02 19:06:30,198	main.py	get_credentials_1:226	returning azure credentials to activating instance instance batch-worker-pr-11438-default-g6cibyji6520-standard-9xy2q
INFO	2022-03-02 19:06:30,199	hail_logging.py	log:40	https GET /pr-11438-default-g6cibyji6520/batch-driver/api/v1alpha/instances/credentials done in 0.005999999999858119s: 200
INFO	2022-03-02 19:06:30,226	main.py	activate_instance_1:237	activating instance batch-worker-pr-11438-default-g6cibyji6520-standard-9xy2q
INFO	2022-03-02 19:06:30,991	base.py	check:335	checking on instance …
```
=> [batch] activate only when we are ready to accept jobs

hail/python/hailtop/batch/backend.py
This is useful for launching batches on behalf of other users.
=> Support passing an authorization token to the ServiceBackend.

hail/python/hail/vds/methods.py, hail/python/test/hail/vds/test_vds.py
=> [vds] Fix and test `hl.vds.filter_intervals`

ci/ci/github.py
Given we have only gone a hair over 50% lately, 3 should be safe.
cc: @daniel-goldstein
=> [ci] increase max concurrent PRs to 3

.git-blame-ignore-revs, batch/batch/driver/main.py, batch/batch/worker/worker.py, ci/create_database.py, hail/python/hail/backend/service_backend.py, hail/python/hail/vds/variant_dataset.py, hail/python/hailtop/utils/__init__.py, hail/python/hailtop/utils/utils.py, hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
I merged these already approved, likely passing, branches together for CI efficiency.
- [daniel-goldstein/drop-user-if-exists](/daniel-goldstein/hail/tree/drop-user-if-exists)
- [daniel-goldstein/mysql-flexible](/daniel-goldstein/hail/tree/mysql-flexible)
- [daniel-goldstein/blame-ignore-isort-pr](/daniel-goldstein/hail/tree/blame-ignore-isort-pr)
- [jigold/timings](/jigold/hail/tree/timings)
- [CDiaz96/find_spark_home_type](/CDiaz96/hail/tree/find_spark_home_type)
- [daniel-goldstein/close-db-pool-last-batch-driver](/daniel-goldstein/hail/tree/close-db-pool-last-batch-driver)
- [chrisvittal/lowering/fix-export-table-separate-header](/chrisvittal/hail/tree/lowering/fix-export-table-separate-header)
- [chrisvittal/vds/n_partitions](/chrisvittal/hail/tree/vds/n_partitions)
FYI @chrisvittal …
=> [omnibus] grouping a bunch of approved likely passing changes together

web_common/web_common/static/search_bar.js
Inserting a div causes the tr's to not appear within the `rows` attribute of a TableBody. Our rows don't have funky `display` values anyway, so there's no need to jump through hoops to not modify the display value.
=> [ci] fix search

batch/batch/worker/worker.py
Seen in Azure:
```
aiodocker.exceptions.DockerError: DockerError(500, 'Get \"https://mcr.microsoft.com/v2/azure-cli/manifests/sha256:068eaecb7abab2d5195a05a6c144c71e9ba1c532efc2912b3ea290d98fbeadb2\": dial tcp 131.253.33.219:443: i/o timeout')
```
=> [batch] new transient docker error

docker/requirements.txt, hail/python/requirements.txt, hail/python/test/hailtop/hailctl/dataproc/conftest.py
See https://hail.zulipchat.com/#narrow/stream/123000-general/topic/Release.200.2E2.2E90/near/274617637
=> [pip] Update tabulate to support python 3.10

hail/python/hailtop/hailctl/dataproc/start.py
The way that the off-heap-memory-fraction argument currently works
limits total memory usage in hail value heavy (like lowered) pipelines
immensely. The default settings both reserve AND and limit hail off heap
allocations to 60% of executor's memory. This behavior is almost never
what a user wants as it will reduce total memory that they can use. We
can retain some of the characteristics that these limits give us by
reserving off-heap-memory-fraction as overhead, and setting the
worker_off_heap_memory_per_core to be the total available memory per
core. This should still give good error messaging on attempts to
allocate too much memory for hail values while allowing us to use all
the memory we have available.
A flag, --off-heap-memory-hard-limit, has been added to preserve the
previous …
=> [hailctl dataproc] Rework off-heap-memory-fraction

hail/python/test/hail/methods/test_impex.py, hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
=> [query] Push dropRows of TableRead into ImportVCF

auth/auth/auth.py, auth/auth/templates/index.html
Closes https://github.com/hail-is/hail-tasks/issues/7
I tested this in my namespace.
=> [auth] Remove redirects to notebook

ci/ci/github.py
Just until I redeploy the azure stack and it is working again.
=> [ci] Ignore follower (azure) ci statuses

query/Makefile
Now you should be able to do:
```
make -C query test NAMESPACE=default PYTEST_ARGS='-k test_foo'
```
=> [query/service] proposal to ease testing in default

hail/python/hail/fs/router_fs.py, hail/python/test/hail/matrixtable/test_file_formats.py, hail/python/test/hail/utils/test_google_fs_utils.py
I also added some tests that would have caught this infinite recursion.
=> [hail.fs] fix RouterFS.remove

hail/python/hail/fs/router_fs.py, hail/python/hailtop/utils/utils.py
This was breaking RouterFS.ls
Tested in the export_vcf lowering branch
=> [hailtop/utils] Allow OnlineBoundedGather2.call to return values

auth/deployment.yaml, batch/deployment.yaml, bootstrap-gateway/deployment.yaml, gateway/deployment.yaml
I calculated this:
targetAverageUtilization = limits.cpu / requests.cpu / 2
=> [k8s] set HPA target to 2500%

hail/python/hail/fs/router_fs.py
I do not think this ever worked, my bad!
=> [hail/fs] fix use of Semaphore in router fs

hail/src/main/scala/is/hail/types/physical/stypes/concrete/SRNGState.scala
With the new rng splitting design, each ApplySeeded node directly gets a unique fixed-length ID (similar to the seed currently), which gets combined into the RNGState immediately before generating random numbers. That allows us to simplify the SRNGState type. Abstractly, each `rand` result is the hash of a bitstring with one block corresponding to the static ID---which gets encrypted using the `staticTweak` tweak---and any number of blocks corresponding to the accumulated dynamic splits---which get encrypted using the block counter as tweak (except for the last block in normal PMAC fashion).
=> [compiler] Simplify SRNGState

batch/batch/front_end/front_end.py, batch/batch/front_end/templates/job.html, batch/batch/worker/worker.py, hail/python/test/hail/table/test_table.py
Closes https://github.com/hail-is/hail-tasks/issues/3
Stacked on #11396. I haven't tested this code at all.
=> [batch] Containerize the JVM

letsencrypt/subdomains.txt
I'm not sure if we need to redeploy anything by hand as well.
cc: @daniel-goldstein
=> [query] Fix memory not being resolved in default

batch/batch/front_end/front_end.py, batch/batch/worker/worker.py, hail/python/hail/backend/service_backend.py, hail/python/test/hail/backend/test_service_backend.py, hail/python/test/hail/helpers.py
=> [batch,query] Enable 8 core drivers with standard or highmem workers

batch/batch/file_store.py, batch/batch/front_end/front_end.py, batch/batch/front_end/templates/job.html, batch/batch/resource_usage.py, batch/batch/worker/worker.py, hail/python/hailtop/utils/__init__.py, hail/python/hailtop/utils/time.py
Closes https://github.com/hail-is/hail-tasks/issues/6
Stacked on #11353. This PR does everything necessary to give the user the CPU and memory statistics except expose them on the jobs UI page.
=> [batch] Save job memory and CPU statistics

build.yaml, hail/python/hail/__init__.py, hail/python/hail/backend/service_backend.py, hail/python/hail/context.py, hail/python/hail/docs/cloud/query_on_batch.rst, hail/python/hail/docs/hail_on_the_cloud.rst, hail/python/hail/utils/java.py, hail/python/test/hail/helpers.py, hail/python/test/hail/methods/test_statgen.py, query/Makefile
Writing the ATGU presentation made clear that we need consistent branding. I am
going with "Hail Query-on-Batch" and the "Batch backend".
=> [query/service] add docs, use consistent branding

batch/batch/front_end/front_end.py, batch/batch/front_end/templates/job.html
There's some issues that need to be fixed when @CDiaz96 comes back from vacation... The units on the plot are wrong and we're not handling missing data well.
Reverts hail-is/hail#11652
=> Revert "[batch]memory cpu plot"

batch/batch/worker/worker.py
=> [batch] Retry docker pulls when 503 is reported as a 500

hail/python/hail/backend/service_backend.py, hail/python/hail/context.py
Similar to https://github.com/hail-is/hail/pull/11435, adding `token` parameter for `init_batch` as well.
=> Pass authorisation token to Query Batch backend

batch/batch/worker/worker.py, hail/python/test/hailtop/batch/test_batch.py
https://hail.zulipchat.com/#narrow/stream/223457-Hail-Batch-support/topic/how.20to.20use.20sample.20list.20file.20as.20an.20argument.20in.20Hail.20batch/near/278603415
=> [batch] Use stdin for copy container specs

hail/python/hail/docs/tutorials-landing.rst, hail/python/hail/docs/tutorials/09-ggplot.ipynb, hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
This doesn't get into the full feature set of hail's ggplot module, but figured it was worth adding a starting point.
=> [query] Added an initial version of the hail ggplot tutorial

dev-docs/letsencrypt.md, gateway/gateway.nginx.conf, letsencrypt/Dockerfile, letsencrypt/Makefile, letsencrypt/letsencrypt.nginx.conf, letsencrypt/letsencrypt.sh, letsencrypt/revoke-certs-pod.yaml, letsencrypt/revoke-certs.sh, letsencrypt/run-letsencrypt.sh
See the dev docs for more explanation.
=> [letsencrypt] enable revocation

docker/requirements.txt, hail/python/dev/requirements.txt, hail/python/hailtop/aiocloud/aioazure/fs.py, hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py, hail/python/hailtop/aiotools/fs/stream.py, setup.cfg
Compilation of the typed-ast version range that mypy 780 used was broken
in python 3.10.
=> [deps] update mypy to 900 series

batch/batch/front_end/templates/batch.html
Add a cancel button to the /batch/batches/{batch_id} page for convenience
Manually tested  cancelling behavior
=> [batch] Add Cancel button to Batch page

ci/ci/build.py, ci/test/resources/build.yaml
I haven't tested this yet because I wanted to see if you liked the idea. Not as flexible as a python loop, but possibly the easiest way to get rid of *a lot* of yaml.
=> [build.yaml] Allow numSplits in RunImageStep

ci/ci/constants.py
=> Remove John from reviewer rotation

hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
This change avoids computing the context twice (or, if head and tail are interleaved, an exponential number of times).
=> [query] use the just-computed contexts instead of recomputing

batch/create_key.py
Couldn't find any occurences of this file in the codebase so I think it's no longer used.
=> [batch] Delete unused create_key file

docker/requirements.txt, hail/python/dev/requirements.txt, hail/python/hailtop/batch/batch.py
I'm not sure if this is the right fix here or if we can get rid of the deprecated FS but this is the lint error that's breaking main.
=> [style] Pin mypy

batch/batch/worker/worker.py
Currently, when a job-deletion event arrives on a worker, it removes the job from its running list of jobs and enqueues a future to run that job's deletion/cleanup. If a deletion removes all running jobs from a worker, and the worker does not receive new work, it could potentially idle out and shutdown before the job has finished cleanup in another task. One specific example of where this could go wrong is that worker shutdown can delete the compute client that the job's cleanup step needs to detach/delete a disk.
The worker should never shut down while operations are still in progress, so we should only ever remove a job once its deletion has completed.
=> [batch] Only remove a job from the worker's dictionary after delete 

benchmark/python/benchmark_hail/run/resources.py
The `download` function does this already.
=> [benchmark] Don't double-log about downloading

hail/python/hail/docs/ggplot/index.rst, hail/python/hail/ggplot/__init__.py, hail/python/hail/ggplot/geoms.py, hail/python/hail/ggplot/stats.py
=> [ggplot] add approx_cdf based geom_density

benchmark/Dockerfile, benchmark/Makefile
This lets us run benchmarks on M1s
=> [benchmark] Fix makefile so we can create images again

batch/batch/front_end/front_end.py, batch/batch/front_end/templates/job.html, web_common/web_common/styles/main.scss, web_common/web_common/templates/layout.html
=> [batch] Add download logs button

hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
Add an extra (currently unused) flag on PartitionNativeWriter and an
extra field on its return type. When the flag is true, we compute the
sum of the byte sizes of every row and return it as the extra field
`partitionByteSize`.
We will use this to compute branch factors in LowerDistributedSort and
depending on computational cost, possible turn this on by default to
allow more optimization around deserializing/processing more than one
row at a time.
=> [query] Allow tracking of the full deserialized byte size of a partition

hail/Makefile
Sufficient to run local backend.
=> [make] Add target for $PYTHON_JAR and version-info

hail/python/hailtop/batch/job.py
=> [batch] Fix typo in docs

batch/batch/driver/main.py, batch/batch/front_end/front_end.py
=> [batch] Tone down access log messages that are not helpful

auth/deployment.yaml, batch/deployment.yaml, ci/deployment.yaml
=> [k8s] Steps towards optimizing k8s

batch/batch/cloud/gcp/worker/disk.py, hail/python/hailtop/aiocloud/aiogoogle/client/compute_client.py
I'm not sure why the disk formatting failed. So I've added more logging to see if we can understand why this is happening.
=> [batch] Add more logging for disk formatting errors

batch/sql/set-test-and-dev-pools-to-8-core-max-2.py, build.yaml
=> [batch] aggressively reduce cpus per PR

hail/python/test/hail/linalg/test_linalg.py, hail/python/test/hail/matrixtable/test_matrix_table.py, hail/src/main/scala/is/hail/backend/local/LocalBackend.scala, hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
No more replicability diversions between local/service!
=> [local] Local backend always uses new shuffle

notebook/deployment.yaml, prometheus/prometheus.yaml, website/deployment.yaml
Prometheus was using quite a lot of resources in the test namespaces so this should fix that.
=> [k8s] Reduce the number of replicas for other services

hail/python/test/hail/matrixtable/test_file_formats.py
Stacked on #11905 
Before this change, we had one long running test which verified all
the old files still parsed properly. In the service backend in particular,
one test split job was substantially longer than the rest. This is bad
for PR merge time.
This change has one significant downside, "collecting" the tests in pytest
requires evaluating two glob patterns which takes several seconds against
GCS. It is relatively fast against the local filesystem.
=> [query] use one test per old file in file format test

hail/scripts/deploy.sh, hail/scripts/update-terra-image.py
I tested this a bit manually. I'm pretty confident its right but I'm sure we'll hit some snag on the next deploy.
=> [deploy] also update AoU image

hail/src/main/scala/is/hail/services/package.scala
https://ci.hail.is/batches/3190579/jobs/118
I have no explanation for why the google service account suddenly was not found except
a bug in Google.
=> [jvm-services] add retry once errors to JVM too

check_pip_requirements.sh
Makes it easier for those of us not developing on linux.
=> [build.yaml] on difference, dump up-to-date pinned requirements

memory/memory/memory.py
Memory is a major source of logs which we never look at.
=> [memory] less logging

auth/auth/auth.py, batch/batch/driver/main.py, batch/batch/front_end/front_end.py
Not helpful for debugging, we still get logs on errors
=> [auth] remove userinfo logs

batch/batch/cloud/azure/driver/create_instance.py, batch/batch/cloud/gcp/driver/create_instance.py
cc: @jigold @daniel-goldstein
These are the bulk of the worker logs and I have never found them useful, just confusing.
=> [batch] disable syslogs

hail/python/test/hail/experimental/test_experimental.py, hail/python/test/hail/methods/test_impex.py, hail/python/test/hail/methods/test_king.py
`hl.import_plink` issues O(N_variants) seeks which triggers O(N_variants) HTTP requests
=> [QoB] disable import_plink using tests

hail/scripts/deploy.sh
I am not quite sure how this works, but dirname $0 resolves to repo/hail, not repo/hail/scripts.
=> [deploy] fix releases

docker-build.sh, gateway/Makefile, internal-gateway/Makefile
Follow up for #11999
cc @danking
=> [docker] Use updated cache tags in Makefiles

infra/gcp/main.tf
Related to https://github.com/hail-is/hail/pull/11985.
Also update the MySQL version while we're at it.
=> [batch] Fix autoscaling policy in GCP Terraform config

hail/python/hail/methods/relatedness/identity_by_descent.py, hail/python/hail/methods/relatedness/pc_relate.py
=> [docs] Math formatting fixes for IBD / PC-Relate

hail/python/hailtop/aiocloud/aioazure/client/pricing_client.py
Azure fixed their cert problems.
=> Revert "[batch] Dont use tls for Azure pricing API"

hail/src/main/scala/is/hail/expr/ir/AbstractMatrixTableSpec.scala
cc @danking @daniel-goldstein 
I bet this is a QoB hotspot for small tables.
=> [query] cache RVD specs to avoid lots of file reads

build.yaml
I'm not sure if adding the `--force-delete` option will help delete the VMs that are not getting cleaned up, but it's worth a shot.
https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-delete
=> [build.yaml] Force delete Azure VMs in cleanup step

batch/sql/estimated-current.sql, batch/sql/rename-timestamp-to-date.sql, build.yaml
I put the WIP tag on, but that's just a precaution.
=> [batch] Rename billing_timestamp to billing_date in agg billing

hail/python/hail/docs/change_log.md
=> [docs] Fix version in changelog: 0.2.99 --> 0.2.98

auth/auth/auth.py, auth/deployment.yaml, batch/batch/driver/main.py, batch/batch/front_end/front_end.py, benchmark-service/benchmark/benchmark.py, ci/ci/ci.py, gear/gear/__init__.py, gear/gear/auth.py, memory/memory/memory.py, monitoring/monitoring/monitoring.py, notebook/notebook/notebook.py, website/website/website.py
Reverts hail-is/hail#12122 Since this broke in prod.
=> Revert "[auth] Cache user sessions in memory"

batch/batch/cloud/azure/driver/pricing.py
See https://hail.zulipchat.com/#narrow/stream/127527-team/topic/ci.20down/near/297868370 for details. I'll file a ticket with Azure to see if this is a breaking change that they're fine making and if so if there is a more robust way for us to filter to disk costs.
=> [batch] Filter for disks or disk on azure pricing api

auth/auth/auth.py, auth/deployment.yaml, batch/batch/driver/main.py, batch/batch/front_end/front_end.py, benchmark-service/benchmark/benchmark.py, ci/ci/ci.py, gear/gear/__init__.py, gear/gear/auth.py, memory/memory/memory.py, monitoring/monitoring/monitoring.py, notebook/notebook/notebook.py, website/website/website.py
A revival of #12122, which was reverted because the web-based code path had an error. The last commit here fixes that bug and I tested that the web path works through a dev deploy.
=> [auth] Cache user sessions in memory

batch/batch/front_end/front_end.py, batch/batch/front_end/templates/billing.html
=> [batch] Include total spent on the UI /billing page

batch/sql/add-jobs-update-id-index.sql, batch/sql/estimated-current.sql, build.yaml
Took 3 minutes on the test database and no locking occurred...
=> [batch] Add index on jobs for update id

hail/python/hail/vds/combiner/variant_dataset_combiner.py
CHANGELOG: The `batch_size` parameter of `vds.new_combiner` is deprecated in favor of `gvcf_batch_size`.
This avoids a confusing error message: https://dev.hail.is/t/vds-new-combiner/269/4?u=dking.
@tpoterba do you think this is better?
=> [query] deprecate the batch_size parameter for gvcf_batch_size

batch/batch/driver/instance_collection/pool.py, batch/batch/driver/main.py, batch/batch/front_end/front_end.py, batch/batch/front_end/templates/batch.html, batch/batch/front_end/templates/batches.html, batch/batch/front_end/validate.py, batch/batch/globals.py, batch/sql/add-commit-updates.sql, batch/sql/delete-batch-tables.sql, batch/sql/estimated-current.sql, batch/test/test_accounts.py, batch/test/test_batch.py, build.yaml, hail/python/hailtop/batch_client/aioclient.py, hail/python/hailtop/batch_client/client.py
Based off of #12154. Stacked on #12193.
=> [batch] Open Batches!

batch/batch/driver/instance.py, batch/batch/driver/instance_collection/base.py, batch/batch/driver/main.py
This concept appears multiple times, best to give it a name.
=> [batch] introduce Instance.free_cores_mcpu_nonnegative

hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
Example transient error:
```
E                       hail.utils.java.FatalError: batch id was 2301842
E                       IllegalStateException: Timeout on blocking read for 30000000000 NANOSECONDS
E                       java.lang.IllegalStateException: Timeout on blocking read for 30000000000 NANOSECONDS
E                           at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123)
E                           at reactor.core.publisher.Mono.block(Mono.java:1727)
E                           at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:130)
E                           at com.azure.storage.blob.specialized.BlobClientBase.downloadStreamWithResponse(BlobClientBase.java:731)
E …
```
=> [query] Retry downloadStreamWithResponse in AzureStorageFS

benchmark-service/benchmark/submit.py, hail/scripts/deploy.sh
This should fix the deploy step.
=> [deploy] Switch deploy to use artifact registry

docker/linux-pinned-requirements.txt, docker/requirements.txt, hail/python/dev/pinned-requirements.txt, hail/python/pinned-requirements.txt, hail/python/requirements.txt
See https://nvd.nist.gov/vuln/detail/CVE-2022-1941.
=> [security] mitigate CVE-2022-1941

.github/workflows/codeql-analysis.yml, batch/batch/front_end/front_end.py, ci/ci/templates/batch.html, ci/ci/templates/batches.html, ci/ci/templates/dev-deploy-table.html, ci/ci/templates/index.html, ci/ci/templates/job-table.html, ci/ci/templates/pr-table.html, ci/ci/templates/pr.html, notebook/notebook/templates/notebook-state.html, website/website/pages/index.html, website/website/pages/search.html, website/website/templates/base-foot.html, website/website/templates/nav-bottom.html
I mostly want to see what kinds of things this reports. We can shut it off it is annoying.
=> [security] enable CodeQL for main and PRs to main

batch/batch/utils.py
I'm pretty sure this is still correct.
=> [batch] Cleanup regions bit shift loop

build.yaml, query/CMakeLists.txt, query/Dockerfile.query-build, query/README.md
~~Need to get sccache working for building LLVM~~
Install llvm/mlir from apt.llvm.org. Need to get llvm-lit working for the tests.
=> [native query] Build LLVM and native query in ci

ci/test/resources/deployment.yaml, ci/test/resources/statefulset.yaml, gear/gear/session.py, grafana/deployment.yaml, monitoring/deployment.yaml, notebook/notebook/notebook.py, website/deployment.yaml
My frustration boiled over and I went to go fix this. This change will cause everyone to become logged out because they will lack the right cookie. That seems fine.
=> [auth] fix this cloud cookie nonsense

hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala, hail/src/main/scala/is/hail/backend/service/Worker.scala, hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala, hail/src/main/scala/is/hail/io/fs/FS.scala, hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala, hail/src/main/scala/is/hail/io/fs/HadoopFS.scala, hail/src/test/scala/is/hail/fs/FSSuite.scala
Hopefully this gives more clues as to what went wrong.
=> [fs] debugging information for AzureStorageFS in FSSuite

batch/batch/file_store.py, batch/batch/front_end/front_end.py, batch/batch/front_end/templates/job.html, batch/batch/resource_usage.py, batch/batch/worker/worker.py, hail/python/hailtop/utils/__init__.py, hail/python/hailtop/utils/time.py
Continuation of #11750 and #11968 
The last commit should be what I've added since it originally went in last June, but I did have to do a rebase.
=> [batch] Reattempt Part 3 of Adding Resource Usage Plots

hail/python/hailtop/aiocloud/aiogoogle/client/compute_client.py, hail/python/hailtop/aiocloud/aiogoogle/client/logging_client.py
#12447 Added some assertions to appease mypy checking use of optional types, and these two were too aggressive but aren't necessary to pass the test suite, just noticed the additional error log entries.
=> [batch] Fix overeager assertions in GC loops

batch/batch/worker/worker.py
This should quiet the logging situation when the driver goes offline.
=> [batch] Quiet down MJC and MJS logging exceptions

hail/python/hail/backend/backend.py, hail/python/hail/backend/py4j_backend.py, hail/python/hail/backend/service_backend.py, hail/python/hail/backend/spark_backend.py, hail/python/hail/matrixtable.py, hail/python/hail/table.py, hail/python/test/hail/methods/test_statgen.py, hail/python/test/hail/table/test_table.py, hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala
=> [query] persist=checkpoint in all backends

hail/python/hailtop/batch/batch.py
CHANGELOG: Added hailctl config setting 'batch/backend' to specify the default backend to use in batch scripts when not specified in code.
This is more consistent now with `HAIL_QUERY_BACKEND` and makes it less boilerplate-y to use the service.
cc: @danking
=> [batch] Add hailctl config batch/backend

batch/batch/front_end/front_end.py, batch/batch/utils.py, batch/sql/case-sensitive-billing-project.sql, batch/sql/estimated-current.sql, batch/test/test_accounts.py, build.yaml, hail/python/hailtop/batch_client/aioclient.py, hail/python/hailtop/batch_client/client.py
=> [batch] Mitigation for case insensitive billing projects and usernames

hail/src/main/scala/is/hail/services/package.scala
For example: https://ci.hail.is/batches/6800777/jobs/108
=> [query] address another rare Google error

hail/Makefile
=> [query] fix Makefile: check-pip-lockfile is singular

batch/batch/worker/worker.py
Since `jvm.kill` is async, using `callback` didn't do anything. This meant every worker that deactivated would spew a bunch of dangling tasks, wait for ten minutes, then exit. We probably don't notice this because the driver kills inactive workers pretty frequently, but I ran into this while doing terra work before I was having the driver delete workers.
=> [batch] Fix JVM kill exit stack on worker shutdown

batch/batch/front_end/front_end.py, batch/batch/resource_usage.py, batch/batch/worker/worker.py
=> [batch] Storage & Network Usage Monitoring

hail/src/main/scala/is/hail/HailFeatureFlags.scala, hail/src/main/scala/is/hail/expr/ir/Emit.scala
=> [qob] Add feature flags to print IR and inputs on workers

batch/batch/resource_usage.py
This PR mitigates the 500 error Ben was getting on the UI page when a resource usage file was corrupt. It also implements a more graceful handling of an out of space error on the worker.
=> [batch] More graceful resource usage error handling

batch/batch/cloud/gcp/driver/disks.py
I left the exception log statements in because it's not like these are driving up our logging costs, but let me know whether you want to keep them or not.
Can make a Grafana alert after this goes in based on this metric.
=> [batch] Add prometheus metric for deletion of orphaned disks

hail/python/hailtop/aiotools/fs/stream.py
I'm not 100% sure this will fix Ben's out of memory error when copying input files. It's possible there's a memory leak somewhere else. My guess on why this change could solve the issue is that because we open the files in "r+b" mode when writing to a local file in parallel, the kernel was caching the data as much as possible based on the available amount of memory to the container because it was anticipating sequential reads. I'd think the kernel is smart enough to evict data when needed, but maybe when using an attached disk with a network drive, the contention is high if the disk starts to lag and it couldn't write all of the data in the write buffer quickly enough and evict unneeded data to meet demand??? At the very least, hopefully this change will allow us to see if there is a true …
=> [fs] Reduce the memory footprint of the LocalAsyncFS

batch/batch/front_end/front_end.py
Based on @bw2 suggestions to make it clear where the limits are and more interpretable storage plots:
=> [batch] Usability fixes to resource usage plots in the UI

hail/python/hailtop/aiotools/fs/stream.py
I messed up that the third argument is length and not end position. I think the "+1" is needed, but not 100% sure.
=> [fs] fix fadvise args

hail/python/hail/methods/impex.py
This is export_bgen, not export_gen.
=> [query] one character doc fix

hail/python/hailtop/config/deploy_config.py
The address service doesn't exist anymore so these methods are unused.
=> [hailtop] Delete dead code in deploy_config

hail/src/main/scala/is/hail/expr/ir/agg/CallStatsAggregator.scala
Saw this while working on random other things.
=> [query] improve hl.agg.call_stats error messages

hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
Fix an unprotected recursive call
=> [compiler] fix stack safety bug in TypeCheck

batch/batch/driver/billing_manager.py
Unfortunately, we'll only get the debug info once every 12 hours when a price change occurs, but let's at least put it in.
=> [batch] Fix adding new resources with same rates

batch/batch/driver/billing_manager.py
Found this bug in my dev environment with randomly changing the version names. The error is a catastrophic failure trying to insert duplicate rows, so there shouldn't be any issues with the current database data.
=> [batch] Fix bug in resource billing updates

hail/python/hailtop/batch/job.py, hail/python/test/hailtop/batch/test_batch.py
I feel like `ofile` semantics should apply the same to bash and python jobs. I don't believe this is a breaking change since `j.ofile` didn't really mean anything usable until now for python jobs IIUC.
=> [batch] Allow python jobs to have file resources too

hail/python/hailtop/utils/utils.py
Fix is based on this commit in nest_asyncio referenced in https://github.com/erdewit/nest_asyncio/issues/58.
https://github.com/erdewit/nest_asyncio/commit/39561034da04bb3744732ac4f6d9a21eddf86948
=> [hailtop.utils] Fix async_to_blocking to support interactive keyboard interrupt

batch/sql/cleanup-old-billing-tables.sql, batch/sql/estimated-current.sql, build.yaml
This is part 1 in mitigating the extra rows in the billing tables with redundant resources with the same prices.
I'm not sure how long it takes to drop a table of this size. Would prefer to merge in the morning in case there are any issues.
=> [batch] Cleanup old billing tables

batch/Dockerfile.worker
https://github.com/GoogleCloudPlatform/gcsfuse/issues/982.
=> [batch] downgrade gcsfuse to avoid gcsfuse bug

batch/sql/create_resource_dedup_mapping.py, build.yaml
This PR populates / deduplicates the previous resources where `deduped_resource_id IS NULL`. Thus we are only collapsing resources before the mitigation went in and before 12723. The algorithm is to go within order of resource id (guaranteed to be chronologically ordered) and collapse sequential entries with the same price to create the map. 
Stacked on #12723
After 12723 will have merged but before this PR:
```
| memory/n1-nonpreemptible/us-east4/1677168676719         |     0.00000000021015025079948776 |          33 |                NULL |
| memory/n1-nonpreemptible/us-east4/1677168680230         |   0.0000000000012942165798611112 |          82 |                NULL |
| memory/n1-nonpreemptible/us-east4/1677168984638         |   0.0000000000012942165798611112 |         131 | …
```
=> [batch] Create resource id dedup map

hail/python/hail/backend/backend.py, hail/python/hail/backend/local_backend.py, hail/python/hail/backend/service_backend.py, hail/python/hail/backend/spark_backend.py, hail/python/hail/linalg/blockmatrix.py, hail/python/hail/matrixtable.py, hail/python/hail/methods/impex.py, hail/python/hail/table.py
I'm not sure this is the "query-way" of doing these checks, but having this feature would have saved Cal from running an expensive pipeline and the output file "disappearing" at the end.
=> [query] Fail fast when writing local output files with QoB

dev-docs/tls.md, devbin/rotate_keys.py
A bunch of stuff:
1. grab disabled status, ignore them in most places, show disabledness when printing
2. Handle the case where a service account has no active key
3. Remove loop confirmation (I can just ctrl-c)
Future work:
We probably do need a bulk update thing but this remove enough annoyance for me for now.
=> [devbin] updates to rotate_keys.py

hail/python/hail/ggplot/utils.py, hail/python/hail/nd/nd.py, hail/python/test/hail/expr/test_ndarrays.py
This caused assertion errors in Scala in `MakeArray.unify`.
=> [query] better hl.nd.concatenate error message

hail/python/test/hail/experimental/test_experimental.py, hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
The most trivial loop is the loop which does not recur. I added a simple test and fixed Requiredness to handle this case.
=> [query] fix hl.experimental.loop

hail/python/hail/methods/statgen.py, hail/python/test/hail/methods/test_statgen.py, hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala
Incidentally, this is the last thing needed for ld prune in local/service backends.
=> [lowering] fix comparison in SparseContexts.apply

hail/Makefile, hail/scripts/upload_qob_jar.sh
Requires network requests -- I had to comment this out to build during a power outage :)
Totally open to better ways to do this than converting it to a shell script -- this is not my expertise.
=> [build] stop evaluating upload-qob-jar variables on makefile parsing

hail/python/hailtop/batch/docs/service.rst
1. Consistent use of `<..>`
2. Remove unused verbiage about `<PROJECT>`
3. Fix indentation.
=> [batch] minor docs fixes

.dockerignore, batch/test/test_accounts.py, batch/test/test_dag.py, build.yaml, hail/Makefile, hail/python/hail/expr/type_parsing.py, hail/python/hailtop/batch/Makefile, hail/python/hailtop/batch/__init__.py, hail/python/hailtop/batch/backend.py, hail/python/hailtop/httpx.py, hail/python/test/hail/conftest.py, hail/python/test/hail/matrixtable/test_file_formats.py, pylintrc
My brain was a little slow today so I decided to fix some easy low hanging fruit.
=> [query][batch] fix warnings and add -Werror for pytest

hail/python/hailtop/batch/job.py, hail/python/test/hailtop/batch/test_batch.py
CHANGELOG: Support nested resource files in PythonJobs.
=> [hailtop.batch] Support nested resource files in PythonJobs

hail/python/hailtop/batch/backend.py, hail/python/test/hailtop/batch/test_batch.py
=> [batch] Fix combinatorial explosion in cancellation calculation in LocalBackend

batch/batch/front_end/front_end.py
This is a mitigation for turning off cloudfuse until we understand why the unmount is not working properly.
=> [batch] Turn off support for cloudfuse

batch/test/test_batch.py
See https://github.com/hail-is/hail/issues/12958.
=> [batch] xfail highcpu cheapest test

hail/python/hailtop/batch/backend.py, hail/python/test/hailtop/batch/test_batch.py
=> [hailtop.batch] Fix 12924 -- waiting on a batch with zero unsubmitted jobs

hail/python/test/hailtop/batch/test_batch.py
This PR just adds a test to make sure submounts don't cause deletion.
=> [batch] Ensure submount in /io doesn't cause deletion

hail/python/test/hail/utils/test_struct_repr_pprint.py
I forgot to check in the tests for #12901. I found them on my filesystem today while cleaning up untracked files.
=> [query] struct pprint tests

hail/python/hailtop/batch_client/parse.py
=> [batch] Allow optional byte suffix for memory and storage requests

Makefile, admin-pod/Makefile, admin-pod/admin-pod.yaml
These were busted after my image-building changes. Also made some cosmetic changes to `admin-pod.yaml`
=> [admin-pod] Fix admin-pod Makefile and deployment.yaml

batch/batch/front_end/front_end.py, batch/batch/worker/worker.py, batch/test/test_batch.py, build.yaml, ci/bootstrap.py, ci/ci/ci.py, ci/ci/github.py, hail/python/hailtop/aiocloud/aiogoogle/client/bigquery_client.py, hail/python/hailtop/batch/job.py, hail/python/hailtop/hailctl/batch/list_batches.py, pyproject.toml
what do you think of it?
---
We should at least keep the fix to list_batches.py. I am unsure why I discovered blatant type errors in ci.
=> [ruff] maybe eliminate PLW2901

hail/python/test/hail/matrixtable/test_matrix_table.py
This test takes up to fifteen minutes on QoB and can be a long tail for CI pipelines so I broke it up into smaller tests.
=> [query] Split up matrix randomness test

hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
Fixes https://github.com/hail-is/hail/issues/13059
=> [hailctl] fix init_notebook.py requirements to be compatible with Hail

batch/sql/dedup_billing_project_users.py, build.yaml
=> [batch] Populate aggregated billing project users table

batch/batch/driver/main.py, batch/batch/worker/worker.py
Workers in terra batch need to use an actual azure bearer token in the authorization header to get through terra auth. I figured it's easiest to just not overload that header.
=> [batch] Dont use the authorization header for worker tokens to the driver

hail/src/main/scala/is/hail/services/package.scala
I also cleaned up our match statement and ensured we recur through every kind of exception just like Python.
=> [transient-errors] will it ever end?

hail/src/main/scala/is/hail/services/package.scala
https://ci.hail.is/batches/7450431/jobs/109
Fixes #13074.
=> [qob] novel transient error

hail/scripts/test-dataproc.sh
see: https://github.com/hail-is/hail/pull/13020
=> [test-dataproc] add subnet

batch/sql/estimated-current.sql, batch/sql/fix-billing-triggers-deduped-resource-id.sql, build.yaml
=> [batch] Fix attempt resources after update trigger to use deduped resource id

hail/python/hailtop/hailctl/__main__.py
`pip search` has been [disabled since 2020](https://discuss.python.org/t/pip-search-is-still-broken/18680), so I don't see how this can work anymore. Happy to replace if you know of an alternative way to do this.
=> [hailctl] Remove check_for_update since pip search no longer works

hail/python/test/hail/matrixtable/test_matrix_table.py, hail/python/test/hail/vds/test_vds.py, hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala, hail/src/main/scala/is/hail/expr/ir/TableWriter.scala, hail/src/main/scala/is/hail/expr/ir/lowering/CanLowerEfficiently.scala, hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
collaboration with @ehigham 
Woohoo!
=> [query] Lower MatrixMultiWrite

hail/src/main/scala/is/hail/backend/BackendUtils.scala
=> [qob] Add retry to one partition fast path

build.yaml, ci/ci/github.py, ci/sql/delete-ci-tables.sql, ci/sql/estimated-current.sql, ci/sql/record-failure-notifications.sql
I did not test these changes at all. Let me know if you have suggestions for doing so.
=> [ci] Only alert on failed deploys once

build.yaml, hail/python/test/hail/methods/test_impex.py, hail/python/test/hail/methods/test_pca.py
https://ci.hail.is/batches/7502486/jobs/80
=> [query] spectra_and_moments_1 also takes a long time in spark??

batch/batch/worker/worker.py, batch/test/test_batch.py, build.yaml, ci/ci/github.py, ci/test/resources/build.yaml, ci/test/resources/deployment.yaml, ci/test/resources/statefulset.yaml, hail/python/test/hailtop/batch/test_batch.py, hail/python/test/hailtop/batch/test_batch_pool_executor.py
Maybe some Google API cannot handle 3 batch-drivers under full load?
Also, this docker inspect thing is just pervasive and extraordinarily annoying.
=> [ci][batch] mitigate some instability

hail/python/hail/matrixtable.py, hail/python/hail/utils/deduplicate.py, hail/python/test/hail/matrixtable/test_matrix_table.py
Soyeon hit an ugly message from Scala.
=> [query] better error message in union_cols

hail/python/hailtop/aiotools/local_fs.py, hail/python/test/hail/utils/test_hl_hadoop_and_hail_fs.py, hail/python/test/hailtop/inter_cloud/test_fs.py
This will at least give us more information about which directories are taking forever to delete.
=> [fs] rmtree empty dir, rmtree empty subdir, rmtree link, raise contents exc

ci/create_database.py
I need this functionality for compacting the billing tables. I'm not sure how we get this privilege to `batch`, `batch-admin` etc., but this should be fine for me to at least measure any performance gains.
=> [ci] Grant create temporary tables privilege to test dbs

ci/ci/constants.py
It will be way better for us to be able to ensure Tim's outstanding PRs continue to be tested. Also, welcome to the rotation @ehigham.
=> [ci] You can't get away that easily Tim

batch/sql/dedup_billing_project_users_by_date.py, build.yaml
=> [batch] Populate billing project users by date deduped table

hail/src/main/scala/is/hail/expr/ir/Simplify.scala
Now that we have fully deterministic randomness, there is no need to prevent simplify from changing the partitioning.
=> [query] always allow simplify to repartition

batch/batch/front_end/front_end.py, batch/batch/front_end/query/__init__.py, batch/batch/front_end/query/query.py, batch/batch/front_end/query/query_v1.py, batch/batch/front_end/query/query_v2.py, batch/sql/add-list-batches-index.sql, batch/sql/estimated-current.sql, batch/test/test_batch.py, build.yaml, hail/python/hailtop/batch_client/aioclient.py, hail/python/hailtop/batch_client/client.py
=> [batch] Add new list_batches query interface to REST calls

hail/src/main/scala/is/hail/services/package.scala
https://ci.hail.is/batches/7525669/jobs/178
=> [transient-error] new transient error from GCS

hail/src/main/scala/is/hail/backend/Backend.scala, hail/src/main/scala/is/hail/backend/local/LocalBackend.scala, hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala, hail/src/main/scala/is/hail/backend/spark/SparkBackend.scala, hail/src/main/scala/is/hail/expr/ir/lowering/LowerAndExecuteShuffles.scala
Bug reported by https://discuss.hail.is/t/no-change-with-partition-hint/3497/2
=> [query] use nPartitions arg of KeyByAndAgg in lowered impl

hail/python/hailtop/batch/docs/advanced_search_help.rst, hail/python/hailtop/batch/docs/index.rst, hail/python/hailtop/batch/docs/service.rst
This PR should go in after #13199.
=> [hailtop.batch] UI Advanced Search Help Documentation

hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh38.sh
=> [qob] restart docker after vep initialization

hail/python/hail/vds/combiner/combine.py
It returns a VariantDataset not a Table
=> [query/vds] fix transform_gvcf docs

hail/python/test/hail/experimental/test_dsp_necessary_functions_have_not_moved.py
https://hail.zulipchat.com/#narrow/stream/379853-Hail.2FVariants/topic/handing.20off.20import_gvs/near/381266567
=> [query] ensure functions need by DSP are not moved

hail/python/hail/vds/combiner/variant_dataset_combiner.py, hail/python/hail/vds/variant_dataset.py
Use it in the combiner as it's very noisy otherwise.
=> [query/vds] Teach read_vds to supress the 'no ref block max length warning'

build.yaml
cc: @jigold @iris-garden @sjparsa , since you all use dev namespaces.
=> [build.yaml] scale dev namespaces to zero 9p-9a weekdays and weekends

hail/python/hailtop/batch_client/aioclient.py, hail/python/hailtop/batch_client/client.py, hail/python/hailtop/utils/__init__.py, hail/python/hailtop/utils/utils.py
I ran into missing type information while I was writing the tests in https://github.com/hail-is/hail/pull/13400
=> [batch] add missing types and deduplicate code

batch/batch/driver/main.py, batch/batch/front_end/front_end.py, batch/batch/utils.py
Let's use the new compacted billing tables!
=> [batch] Use new v3 billing tables on the driver and front end

hail/python/hail/methods/qc.py
Hi all, I have made some quick edits in the docstring of the `hl.methods.qc.charr()` function. Please let me know if anything else is needed to clarify. Thanks!
=> [query] changes in charr docstring

batch/batch/driver/main.py
The "free" cores as written is less useful because it includes pending instances.
=> [batch] monitor in prometheus/grafana the *schedulable* free cores

hail/python/hailtop/batch_client/aioclient.py
This should be just a simple refactoring in anticipation of having bunches for job groups as well.
=> [aioclient] Refactor BatchBuilder submit for ease of job groups changes

hail/Makefile
These have not worked in a long time.
=> [query] fix services-jvm-test and fs-jvm-test Make targets

batch/sql/turn_on_billing_compaction.py, build.yaml
We weren't actually testing the compaction in test and dev, which is probably why we had those initial errors in production.
=> [batch] Turn on compaction in test and dev

batch/test/test_batch.py, batch/test/test_dag.py, hail/python/hailtop/batch/batch_pool_executor.py, hail/python/hailtop/batch_client/__init__.py, hail/python/hailtop/batch_client/aioclient.py, hail/python/hailtop/batch_client/client.py
Follow up to #13458 for making adding job groups simpler.
=> [hailtop.batch_client] Merge Unsubmitted/Submitted Job into Job

hail/python/hail/experimental/ldscsim.py
I was running `pyright` on Hail for other reasons and it pointed out we should not use `type` in this way.
=> [query] eliminate use of type in ldscsim

batch/batch/front_end/query/__init__.py, batch/batch/front_end/templates/batch.html, batch/batch/front_end/templates/batches.html, batch/batch/front_end/templates/table_search.html
The updated template renders the following in Firefox on my machine:
=> [batch/ui] adds advanced search box and help link

batch/test/conftest.py, batch/test/test_batch.py, batch/test/test_dag.py, hail/python/test/hailtop/batch/test_batch.py, hail/python/test/hailtop/batch/test_batch_pool_executor.py
Just some cleanup, all in test files.
=> [batch] Favor configuration_of and get_remote_tmpdir over get_user_config

build.yaml
Sorry, I forgot to add #13510  to build.yaml.
=> [batch] Actually do the cleanup unused functions migration

batch/Dockerfile.worker, batch/az-create-worker-image.sh, batch/batch/cloud/azure/driver/create_instance.py, batch/batch/cloud/azure/worker/worker_api.py, batch/batch/cloud/gcp/driver/create_instance.py, batch/gcp-create-worker-image.sh, batch/test/test_batch.py, batch/test/utils.py, benchmark/Makefile, build.yaml, docker/hail-ubuntu/Dockerfile, docker/third-party/images.txt, hail/python/hailtop/batch/backend.py, hail/python/hailtop/batch/docs/cookbook/clumping.rst, hail/python/hailtop/batch/docs/cookbook/files/batch_clumping.py, hail/python/hailtop/batch/docs/docker_resources.rst, hail/python/hailtop/batch/job.py, hail/python/test/hailtop/batch/test_batch.py, hail/src/test/scala/is/hail/services/batch_client/BatchClientSuite.scala, infra/azure/modules/batch/main.tf, infra/azure/modules/vdc/main.tf, infra/gcp-broad/main.tf, infra/gcp/README.md, infra/gcp/main.tf, infra/k8s/global_config/main.tf, ukbb-rg/Dockerfile.browser, ukbb-rg/Dockerfile.static
Upgrade to Ubuntu 22.04 everywhere including for the Batch Worker VMs in Azure and Google.
=> [batch] update ubuntu image version to latest

ci/ci/github.py
I added this feature because I am tired of every time I want to dev deploy and try out new changes, it triggers a new build in CI. I'd prefer to put a new label on the PR rather than close it each time or make a copy of the branch and test the copy.
=> [ci] Don't test PRs with do-not-test label

build.yaml, hail/scripts/deploy.sh, infra/gcp-broad/gcp-ar-cleanup-policy.txt
=> [vep] Restore GRCh38 VEP image

ci/ci/github.py
There's more cleaning to be done, but this at least fixes the merge ordering.
=> [ci] fix merge priority ordering

hail/Makefile
1. Include the Azure code in a comment for the sake of other devs.
2. Fix the envvar checks.
3. Depend only on the uploaded files in upload-qob-test-resources.
4. fs-jvm-test needs upload-qob-test-resources.
=> [query] fix make fs-jvm-test

hail/.gitignore, hail/python/hail/backend/backend.py, hail/python/hail/backend/local_backend.py, hail/python/hail/backend/service_backend.py, hail/python/hail/backend/spark_backend.py, hail/python/hail/context.py, hail/python/hail/docs/configuration_reference.rst, hail/python/hail/docs/index.rst, hail/python/hail/linalg/blockmatrix.py, hail/python/hail/matrixtable.py, hail/python/hail/methods/impex.py, hail/python/hail/table.py, hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py, hail/python/hailtop/aiotools/router_fs.py, hail/python/hailtop/aiotools/validators.py, hail/python/hailtop/batch/backend.py, hail/python/hailtop/batch/batch.py, hail/python/hailtop/batch/docs/_templates/_autosummary/class.rst, hail/python/hailtop/batch/docs/conf.py, hail/python/hailtop/batch/docs/configuration_reference.rst, hail/python/hailtop/batch/docs/index.rst, hail/python/hailtop/config/variables.py, hail/python/hailtop/hailctl/config/config_variables.py, hail/python/test/hail/fs/test_worker_driver_fs.py, hail/python/test/hailtop/batch/test_batch.py
Closes https://github.com/hail-is/hail/issues/13003.
=> [batch] restricts operations to GCS buckets using hot storage

batch/batch/resource_usage.py
At some point (highly likely that it was the Ubuntu 20.04 -> 22.04 upgrade) Batch went from using cgroups v1 to cgroups v2 for setting containers' CPU and memory limits. We mostly don't touch cgroups, the container runtime handles that for us, but we poll the `cgroupfs` for recoding memory usage and CPU utilization. The accounting mechanism changed between v1 and v2 so batch was silently failing to collect these metrics. Deploying these changes into my namespace got me back the following plots (compiling hail):
The reason why we fail silently when the file doesn't exist is because we are letting the container runtime manage the cgroup, and there is a race condition between the container exiting + the cgroup getting destroyed and our polling of this file. We could probably do a better job …
=> [batch] Fix job cpu and memory recording

build.yaml, hail/python/test/hail/backend/test_service_backend.py, hail/python/test/hail/experimental/test_experimental.py, hail/python/test/hail/expr/test_expr.py, hail/python/test/hail/genetics/test_reference_genome.py, hail/python/test/hail/helpers.py, hail/python/test/hail/matrixtable/test_file_formats.py, hail/python/test/hail/matrixtable/test_grouped_matrix_table.py, hail/python/test/hail/matrixtable/test_matrix_table.py, hail/python/test/hail/methods/relatedness/test_identity_by_descent.py, hail/python/test/hail/methods/relatedness/test_pc_relate.py, hail/python/test/hail/methods/test_family_methods.py, hail/python/test/hail/methods/test_impex.py, hail/python/test/hail/methods/test_qc.py, hail/python/test/hail/methods/test_skat.py, hail/python/test/hail/methods/test_statgen.py, hail/python/test/hail/table/test_grouped_table.py, hail/python/test/hail/table/test_table.py, hail/python/test/hail/test_context.py, hail/python/test/hail/test_randomness.py, hail/python/test/hail/utils/test_hl_hadoop_and_hail_fs.py, hail/python/test/hail/utils/test_utils.py, hail/python/test/hail/vds/test_combiner.py, hail/python/test/hail/vds/test_vds.py, hail/python/test/pytest.ini
Based heavily on #13238, this reduces QoB tests to a minimal number of integration tests + tests known to specifically flex Batch backend functionality.
=> [qob] test the core functionality rather than everything

Makefile, admin-pod/Dockerfile, auth/Dockerfile, batch/Dockerfile, batch/Dockerfile.worker, blog/Dockerfile.nginx, bootstrap-gateway/Dockerfile, build.yaml, ci/Dockerfile, ci/Dockerfile.ci-utils, ci/buildkit/Dockerfile, ci/ci/build.py, ci/test/resources/Dockerfile, ci/test/resources/build.yaml, docker-build.sh, docker/Dockerfile.base, docker/Dockerfile.hail-dev, docker/hail-ubuntu/Dockerfile, docker/hailgenetics/vep/grch37/85/Dockerfile, docker/hailgenetics/vep/grch38/95/Dockerfile, hail/Dockerfile.hail-run, infra/gcp-broad/gcp-ar-cleanup-policy.txt, monitoring/Dockerfile, query/Dockerfile.query-build, tls/Dockerfile, ukbb-rg/Dockerfile.browser, ukbb-rg/Dockerfile.static, website/Dockerfile
Curious for your thoughts on this. I think this will make it easier to build `hailgenetics/hail` images for different python versions without duplicating Dockerfiles with the nice side-effect of not needing to jinja our Dockerfiles.
=> [ci] Support docker build args in buildImage steps

hail/src/test/scala/is/hail/stats/GeneralizedChiSquaredDistributionSuite.scala
I added this and I do not know why. This broke some Scala linter I was looking at.
=> [query] eliminate weird syntax in test suite

auth/auth/auth.py
The comment in the code has most of the context. For auth checks, Envoy uses the same HTTP method as the original request, which confuses our aiohttp middleware which checks CSRF tokens on every `POST`. This broke Grafana because the grafana front-end POSTs queries to the backend, and those end up failing the auth check. We just don't need to check for CSRF in auth checks. This should be the only occurrence in our codebase where a safe endpoint can be reached with an unsafe HTTP method.
=> [auth] Opt out of CSRF check for Envoy auth endpoints

batch/jvm-entryway/src/main/scala/is/hail/QoBAppender.scala
see also https://github.com/hail-is/hail/issues/13242
=> [batch] synchronize all access to QoBOutputStreamManager map

build.yaml
Not great that CI hasn't been erroring because of this.
=> [memory] Remove dangling reference to long gone step

batch/batch/worker/worker.py
Creating network namespaces can often take hundreds of milliseconds (and sometimes seconds with `iptables` contention), so Batch takes this off the job hot path by pre-allocating namespaces. All job namespaces are configured identically and there is a fixed number of "slots" on any batch worker (`CORES * 4`), so pre-allocation and asynchronous recycling of namespaces is fairly straight-forward so long as we never attempt to run more containers on a worker than the number of slots (which the scheduling system should prohibit).
However, since we started running long-lived JVM containers (#11397), the number of containers running on a given worker can easily be *greater* than `N_SLOTS`. On a 16-core machine, we create 30 JVMs that sit idle waiting for JVMJobs all the while occupying a …
=> [batch] Account for JVM containers when allocating network namespaces

batch/batch/worker/worker.py
https://hail.zulipchat.com/#narrow/stream/300487-Hail-Batch-Dev/topic/resource.20plots.20starting.20too.20early.3F/near/393520689
=> [batch] Use job-only resource usage for running JVM jobs

Makefile, website/Makefile, website/website/website.py
So you don't need to rebuild the docs if you only touched code in `website`.
=> [website] Make better use of make when building docs locally for the website

hail/python/hail/backend/service_backend.py
This would have been useful when I was rapidly iterating on different versions. It saves me from clicking into a job to figure out which JAR was used and then working backward from git SHA to Hail version.
I also noticed we had this deadcode which was supposed to set the name. I moved that into the constructor so that it has the intended effect.
=> [qob] include version in batch attributes

ci/ci/ci.py, ci/ci/environment.py, ci/ci/templates/pr.html, ci/ci/utils.py
Fixes #13556. I haven't tested these changes -- would like to get initial feedback first.
=> [ci] Generate PR specific logging queries

hail/python/hailtop/aiotools/delete.py, hail/python/hailtop/utils/utils.py
Some quality-of-life stuff for `hailtop.aiotools.delete`.
Without deleting in batches, I found it impossible to delete very large lists of files because we create too many asyncio tasks.
=> [fs] delete in batches, accept stdin

docker/Dockerfile.hail-dev
=> [ci] Force the installation of node and npm pyright in the linting image

hail/python/hailtop/aiocloud/aiogoogle/client/storage_client.py
Similar to https://github.com/hail-is/hail/pull/13818. We *must* retrieve exceptions from any task that is `done` otherwise we'll get a warning when the task is freed.
=> [fs] raise exceptions from failed tasks

hail/python/hailtop/aiocloud/common/session.py
:facepalm:
I grepped for other hasattr that do not check `self`
=> [aiogoogle] finally squash an open http session

gear/gear/database.py
We should never have been using `await`. (aiomysql should probably not implement `__await__`). `create_pool` returns `aiomysql.utils._PoolContextManager` which inherits from `aiomysql.utils._ContextManager` which implements `__await__`, `__aenter__`, and `__aexit__` thusly:
```python3
def __await__(self):
return self._coro.__await__()
async def __aenter__(self):
self._obj = await self._coro
return self._obj
async def __aexit__(self, exc_type, exc, tb):
await self._obj.close()
self._obj = None
```
`__await__` is a footgun! You should never do that! You should close the return value of the coroutine!
=> [gear] properly close the aiomysql pools

batch/batch/driver/main.py
We already do this in httpx.ClientSession. I just copied from there.
=> [batch] wait long enough for aiohttp to clean itself up

batch/batch/resource_usage.py
Fixes #13861. CPU monitor races with container deletion just like RAM monitor. I also switched to catching FileNotFoundError instead of exists since technically the file could disappear between us checking `exists` and us `open`ing it.
=> [batch] make cpu and mem resource readers similar and avoid race

batch/sql/dedup_job_resources.py, build.yaml
=> [batch] Dedup aggregated job resources table

Makefile, auth/Makefile, batch/Makefile, ci/Makefile, infra/bootstrap_utils.sh, monitoring/Makefile, website/Makefile
Didn't verify but this seems closer to right.
=> [makefile] use the pushed-private image name not the local image name

batch/batch/worker/worker.py
If a container is deleted before it ever runs, the log files won't exist.
Fixes #13906
Fixes #13907
=> [batch] Only update log files if they exist

hail/python/hailtop/batch/backend.py
=> [batch] Use 0.25 cpu for remove_tmpdir job

batch/batch/front_end/templates/billing_projects.html
=> [batch] Turn off autocomplete on billing projects page

batch/batch/exceptions.py, batch/batch/front_end/front_end.py, batch/test/test_accounts.py, gear/gear/auth.py, hail/python/hailtop/auth/auth.py
=> [batch] Check whether user exists before adding to billing project

batch/batch/front_end/templates/job.html
=> [batch] Show attributes on the jobs UI page

batch/batch/worker/worker.py
Very small change, something I noticed while working on something else entirely. Given how this is currently used I don't think it needs to be boxed anymore.
=> [batch] Dont box data_disk_space_remaining

batch/batch/cloud/gcp/driver/create_instance.py, batch/build-batch-worker-image-startup-gcp.sh, batch/gcp-create-worker-image.sh
=> [batch] Install the Ops Agent in GCP on instance startup

build.yaml, hail/python/test/hailtop/batch/test_batch.py
Another small step in going key-less.
=> [batch] Remove explicit settings in hailtop tests

hail/python/hail/docs/cloud/azure.rst
=> Minor doc typo

hail/python/test/hail/test_hail_in_notebook.ipynb
=> [query] Make test_hail_in_notebook idempotent

build.yaml, dev-docs/services/services-development-faq.md, devbin/functions.sh
Resolves #14020.
I'll manually delete the scale up cron jobs from the dev namespaces once this goes in.
=> [k8s] Make devbin function for manually scaling dev namespaces

batch/batch/worker/worker.py
No need to accept anything addressed to a public IP
=> [batch] Batch workers listen on the internal IP address

hail/Makefile, hail/python/test/hail/matrixtable/test_file_formats.py
Just explicitly start a loop and use our cloud-friendly FSes. Also, we need to recursively copy the resources.
=> [qob] fix pytest-qob

hail/python/hailtop/hailctl/dataproc/connect.py
Oh Chrome,
How do I call thee? Let me count the ways.
=> [hailctl] fix hailctl for YHJ

config.mk, grafana/Makefile, grafana/deployment.yaml
I've already deployed to the cluster to test. Unless master deploys, you can see it here: https://grafana.azure.hail.is/datasources/edit/kgzY5Io7k
I also fixed the grafana Makefile.
=> [grafana] encode azure monitor in grafana yaml

hail/.scalafix.conf, hail/.scalafmt.conf, hail/build.gradle, hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala, hail/src/main/scala/is/hail/expr/ir/agg/CollectAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/ReservoirSampleAggregator.scala, hail/src/main/scala/is/hail/expr/ir/agg/TakeAggregator.scala, hail/src/test/scala/is/hail/utils/BinaryHeapSuite.scala
Split from https://github.com/hail-is/hail/pull/14103
Co-Authored by @patrick-schultz 
This change includes some edits to prevent build failures caused by using the scala formatter
=> [compiler] Add `scalafix` and `scalafmt` configs

Makefile, build.yaml
split from https://github.com/hail-is/hail/pull/14103
co-authored by @patrick-schultz
=> [compiler] enforce scala formatting in ci

Makefile
`--diff` will show you what is wrong.
=> [ruff] use --diff instead of --check

batch/batch/driver/billing_manager.py, batch/batch/driver/main.py, batch/batch/front_end/front_end.py, batch/batch/inst_coll_config.py, batch/batch/resource_usage.py, batch/batch/worker/worker.py, ci/ci/ci.py, ci/ci/github.py, ci/ci/utils.py, ci/create_database.py, devbin/rotate_keys.py, hail/python/dev/pinned-requirements.txt, hail/python/dev/requirements.txt, hail/python/hail/experimental/ld_score_regression.py, hail/python/hail/experimental/ldscore.py, hail/python/hail/expr/type_parsing.py, hail/python/hail/methods/impex.py, hail/python/hail/table.py, hail/python/hailtop/aiotools/validators.py, hail/python/hailtop/batch/batch_pool_executor.py, hail/python/hailtop/batch/docker.py, hail/python/hailtop/batch/docs/cookbook/files/batch_clumping.py, hail/python/hailtop/hailctl/hdinsight/start.py, hail/python/hailtop/utils/utils.py, hail/python/test/hail/utils/test_placement_tree.py, hail/python/test/hailtop/hailctl/batch/test_submit.py, hail/python/test/hailtop/hailctl/config/test_cli.py, hail/scripts/update-terra-image.py
The changes other than requirements and pinned-requirements.txt are just format changes.
=> [ruff] update to ruff 0.1.13

hail/scripts/test-gcp.sh
AFAIK, we do not use this file, but it is a nice historical note of how to run the Hail tests on a Dataproc cluster, if we ever wanted to do that. These days we only run a limited set of tests via test-dataproc.sh
I am also open to deleting this file since it certainly does not work now.
=> update test-gcp.sh to be closer to modern use

benchmark/Makefile
https://github.com/hail-is/hail/pull/14147 exposes `HAIL_RELEASE_MODE` to build with opimisation. Let's use that.
=> [benchmark] build hail in release mode

gear/pinned-requirements.txt, gear/requirements.txt, hail/python/hailtop/batch/job.py, hail/python/hailtop/pinned-requirements.txt, hail/python/hailtop/requirements.txt, hail/python/hailtop/utils/utils.py, hail/python/pinned-requirements.txt
Fixes Wenhan's bug: https://hail.zulipchat.com/#narrow/stream/223457-Hail-Batch-support/topic/AttributeError.3A.20'InputResourceFile'.20object.20has.20no.20attribute
=> [batch] fix handle_arg and fix unused TypeVar

hail/python/hailtop/utils/utils.py
The T is free so its tantamount to Any.
=> [hailtop] eliminate pyright warning

hail/python/hailtop/aiotools/delete.py, hail/python/test/hailtop/inter_cloud/conftest.py, hail/python/test/hailtop/inter_cloud/test_copy.py, hail/python/test/hailtop/inter_cloud/test_delete.py, hail/python/test/hailtop/inter_cloud/test_diff.py, hail/python/test/hailtop/inter_cloud/utils.py
I rearranged some fixtures as well.
=> [hailtop] ensure delete also deletes single files

batch/batch/front_end/front_end.py
Horrible diff but it's mainly just a de-indentation of the `insert_jobs_into_db` function and lifting the try/except block to the callsite of the transaction. By handling that error externally to the transaction we don't stifle errors that would be caught by the `@transaction` retry logic.
=> [batch] Make insert_jobs_into_db retryable

hail/src/main/scala/is/hail/io/InputBuffers.scala, hail/src/main/scala/is/hail/io/OutputBuffers.scala, hail/src/main/scala/is/hail/utils/richUtils/RichCodeInputBuffer.scala
=> [query] Remove read/writeUTF from Input/OutputBuffer

ci/ci/build.py
Facilitates writing data to cloud storage as `ci`
=> [ci] Expose `HAIL_CI_STORAGE_URI` as `ci_storage_uri` in CI Steps

.git-blame-ignore-revs
See https://github.com/hail-is/hail/pull/14150.
=> [lint] ignores import linting for blame

batch/batch/batch.py, batch/batch/front_end/front_end.py, batch/batch/front_end/templates/batch.html, batch/batch/front_end/templates/job.html, hail/python/hailtop/batch_client/types.py
Closes https://github.com/hail-is/hail/issues/14210.
Shows whether a Job is "Always Run" on the Batch page:
and on the Job page:
=> [batch/ui] adds "always run" to job and batch UIs

dev-docs/services/batch/operation.md
Incorporates grafana which we did not have at the time of previous revision and removes the nginx config that is no longer used. We now use Envoy as our load balancer. I'll make a separate dev doc explaining the gateways.
=> [dev-docs] Update batch operation docs

hail/python/hail/__init__.py, hail/python/hail/backend/backend.py, hail/python/hail/context.py, hail/python/hail/experimental/datasets.py, hail/python/hail/experimental/datasets_metadata.py, hail/python/hail/experimental/db.py, hail/python/hailtop/__init__.py, hail/python/hailtop/hailctl/dataproc/deploy_metadata.py, hail/python/hailtop/hailctl/dataproc/start.py, hail/python/test/hail/backend/test_spark_backend.py
=> [python] Use `importlib.resources` instead of `pkg_resources`

batch/pinned-requirements.txt, ci/pinned-requirements.txt, gear/pinned-requirements.txt, hail/python/dev/pinned-requirements.txt, hail/python/hailtop/pinned-requirements.txt, hail/python/pinned-requirements.txt, web_common/pinned-requirements.txt
Fixes https://github.com/hail-is/hail/security/dependabot/168
=> [pip] Update jinja to avoid 3.1.3 vulnerability

hail/python/hail/expr/expressions/typed_expressions.py, hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
=> [query] add `StringExpression.find`

hail/python/hail/context.py, hail/python/test/hail/helpers.py
=> [query] Fix backend arg typecheck in init

hail/python/benchmark/hail/benchmark_matrix_table.py, hail/scripts/benchmark_in_batch.py
Specify which benchmark to run by nodeid instead of by expression
=> [benchmark] fix benchmark duplication in batch

hail/python/test/hail/linalg/test_linalg.py
Adds tests for sparse block matrices in python, which are currently failing in backends with bm lowering.
=> [query] add sparse bm agg tests

batch/batch/front_end/front_end.py
`'/api/v1alpha/batches/create-fast'` is a Batch API endpoint that allows you to create a batch, submit jobs, and start them running all in one HTTP request. It makes a few transactions within the endpoint and must be idempotent. One of the failure modes it must watch for is when a Batch Update to add some new jobs and/or job groups to a batch has already successfully been committed, but the request is retried for X reason. In that scenario, we want to just return a 200 to the client. We do this already, but there was an oversight when creating job groups where those branches did not include the full response payload, which results in intermittent errors on the client when it can't retrieve `resp['last_job_group_id']`. This fixes that so we always return the same JSON.
=> [batch] Fix incomplete API responses in idempotency-handling branches

dev-docs/services/auth/identity-management.md
Most of the technical details of how our authentication/authorization works is in the linked RFCs, but I thought there should be a brief overview of just how to think about identity across the system and a place that links to the deeper details.
=> [dev-docs] Create overview of identity management

batch/batch/worker/worker.py
=> [batch] Remove blob storage read inside Worker job creation endpoint

batch/batch/front_end/templates/batch.html, devbin/dev_proxy.py
In analogy to the "Next Page" button, I often find myself wanting to navigate backwards too.
=> [UI] Batch UI: Previous page button

dev-docs/services/batch/design.rst
Quick write up on how preemption works in the design RST
=> [Docs] Document how preemption works

build.yaml
Fixes `bash: line 10: yum: command not found` failures in `delete_azure_batch_instances`
=> [ci] mcr.microsoft.com/azure-cli no longer provides yum

docker/hailgenetics/vep/grch37/85/Dockerfile
This is the vep85/grch37 analogue to #14713
Rebuilds a docker image could introduce new vulnerabilities, but in all likelihood, fixes more/more critical vulnerabilities than it would introduce.
=> [vep/grch37] Use system package manager to install perl libraries

batch/gcp-create-worker-image.sh, bootstrap-gateway/Makefile, ci/bootstrap.py, infra/bootstrap_utils.sh, infra/gcp/README.md, infra/gcp/main.tf, infra/gcp/outputs.tf, infra/install_bootstrap_dependencies.sh
Corrections and updates to the gcp deploy instructions following a fresh deployment in a brand new project.
No impact because this does not impact the production system.
=> [Docs] Fix GCP deploy steps, instructions

.github/pull_request_template.md
Make the PR template a little easier to work with.
No impact because this is not code being deployed to production
=> [Github] Update pull_request_template.md

.github/ISSUE_TEMPLATE/new-developer.yml, dev-docs/services/creating-a-developer-account.md
A convenience template for creating "add new developer" issues and documenting the steps required
No impact, only a new github issue creation form
=> [Github] Issue template for creating "new developer" requests

dev-docs/services/letsencrypt.md
=> [dev-docs] Update letsencrypt cert rotation instructions

ci/ci/constants.py
Issue: #14718
Adding permissions for grohli.
Covered in issue
=> Adding grohli to AUTHORIZED_USERS in constants.py

infra/gcp/hail-is/appsec/auth_oauth2_client_secret.enc.json, infra/gcp/hail-is/appsec/global.tfvars, infra/gcp/hail-is/appsec/hailctl_client_secret.enc.json, infra/gcp/hail-is/appsec/terraform_sa_key.enc.json
Config and records relating to the appsec deployment instance. Necessary for future maintenance and management of the appsec instance.
No impact because this relates only to the parallel appsec instance, not the main production instance.
=> [Config] Appsec sandbox config and files

.github/ISSUE_TEMPLATE/new-developer.yml
Updates new developer template to include the need for a Google project role
None, documentation change only
=> GCP roles in new developer template

batch/batch/driver/billing_manager.py
Right now, our `latest_product_version` table has a partially filled sku column. This is because we added sku and didn't back calculate the old skus, and we haven't assigned skus to 'our' products (ip fees, service fee). I'd like to fix that, so that most of our 'resources' can be tracked by sku rather than some of the more fragile name/version strings that has lead to conflicts with duplicates in GCP.
- This change has low security impact
Update to a mostly unused database field.
=> [batch] During resource rate refresh, update SKU if it is NULL

auth/auth/auth.py, batch/batch/front_end/front_end.py, monitoring/monitoring/monitoring.py, web_common/web_common/__init__.py, web_common/web_common/web_common.py
- Adds more content security policy sources to unblock functionality in the web UI
- Adds more pages using "unsafe_eval" content security policy, to unblock functionality in the web UI
- Updates the decorator order to avoid changing returned types
- Adds decorators to the monitoring service endpoints
Sets some more flexible content security policies
=> [web/api] Fix plotting and billing project functionality (CSP edit)

dev-docs/services/letsencrypt.md
=> [docs] Mention container registry login to certificate cycling instructions

hail/python/hail/vds/variant_dataset.py
=> [vds/docs] Clarify that VDS write can take MatrixTable write parameters

hail/hail/src/is/hail/types/virtual/Type.scala
=> [query] remove unused json impex on `Type`

batch/deployment.yaml, batch/terra-chart/values.yaml.tmpl, dev-docs/services/connecting_docker_to_container_registry_creds.md, dev-docs/services/letsencrypt.md, dev-docs/services/setting_the_kubectl_context.md, dev-docs/services/updating-third-party-images.md, docker/third-party/images.txt, gateway/deployment.yaml, grafana/deployment.yaml, guide/deployment.yaml, internal-gateway/deployment.yaml, prometheus/prometheus.yaml, ukbb-rg/deployment.yaml
Bumps the deployed envoy version to 1.33.0
New version of our gateway, but should be a positive security impact
=> [gateway] bump envoy version

hail/python/hailtop/hailctl/auth/cli.py
CLI now requires user to agree to Terms of Service when logging in. Login flow now includes a ToS agreement step, used as a modification for cli/login() before calling async_login().
Brief description and justification of what this PR is doing.
Modifies command line login process to include a ToS agreement step, but does not change anything about how login occurs if user agrees. Additionally, terminates login process if user does not agree. User is not able to proceed with login unless they agree.
=> [batch/auth] ToS agreement/modification for command line login.

auth/auth/auth.py, auth/auth/auth_utils.py, auth/test/pytest.ini, auth/test/test_auth_utils.py, batch/test/test_batch.py, build.yaml
Adds unit tests for auth secret name validation
Test addition only
=> [auth] Secret credentials name validation tests

hail/python/hail/expr/functions.py, hail/python/test/hail/table/test_table.py
Low level non-security code changes only. Functionality is identical, only the error messages and tests have changed.
=> [query] query_table: Refactor parameter validation and parametrize tests

auth/auth/auth.py, auth/auth/templates/users.html, dev-docs/services/services-development-faq.md, gear/gear/auth.py
Adds a web endpoint to invalidate all user (non-robot) sessions. UI element too:
- This change has a high security impact
- New endpoint added. 
- Could cause DOS or lockout if accessible inappropriately. 
- Mitigated by:
- Making this a developer-only functionality
- Using the same standard developer-only access pattern as we use throughout the web service
=> [auth] Invalidate sessions hook

auth/auth/auth.py, auth/auth/templates/openapi.yaml, batch/batch/front_end/templates/openapi.yaml, ci/ci/ci.py, ci/ci/templates/openapi.yaml, monitoring/monitoring/monitoring.py, monitoring/monitoring/templates/openapi.yaml
Updates batch service openapi documentation to fix tabulation bugs and add request and response object definitions. Adds openapi and swagger documentation for the ci, auth and monitoring services.
New endpoints added to auth, ci and monitoring, but in analogy to the existing batch swagger and monitoring endpoints. They take no parameters, are intentionally public, and serve only minimally templated content from system setup variables for version and base path.
=> [batch, auth, monitoring, ci] API documentation additions and fixes

batch/pinned-requirements.txt, check_pip_requirements.sh, ci/pinned-requirements.txt, gear/pinned-requirements.txt, hail/python/dev/pinned-requirements.txt, hail/python/hail/expr/types.py, hail/python/hailtop/pinned-requirements.txt, hail/python/pinned-requirements.txt, hail/python/requirements.txt, hail/python/test/hail/expr/test_functions.py, web_common/pinned-requirements.txt
Also regenerate _all_ pinned-requirements.
Fixes #14852 
- This change has medium security impact
Dependency upgrades. Probably _better_ from a security standpoint.
=> [deps] Upgrade to Numpy 2.x series

.github/workflows/create-release-pr.yml
I pushed up the wrong branch to address @cjllanwarne's feedback in #14858 then that PR merged. I has the dumb.
=> [github] fIx WoRkFlOw I pUsHeD uP wRoNg

dev-docs/services/letsencrypt.md
Adds some documentation about what happens when we refresh certificates
=> [docs] Document how certificate refreshing actually works

hail/hail/test/src/is/hail/expr/ir/OrderingSuite.scala
See #14994.
Note that all the special casing of whether the dict contains the key is unnecessary. We know the dict is sorted (we're using a binary search after all), so if `dict(i).getKey < key` and `key <= dict(i).getKey`, then if the dict contains the key, then `key == dict(i).getKey`.
=> [compiler] fix testBinarySearchOnDict

hail/hail/src/is/hail/backend/driver/Py4JQueryDriver.scala
PR #14698 refactored the startup of the py4j http server so that calling `pyHttpServer` created and started the sever. In the process, it deleted the daemon thread that the server was started from originally. This caused the `httpServer.start` method to spawn a non-daemon thread as it was being called from the main thread py4j was using to do its work. Simply calling `setExecutor(null)` is not sufficent for this purpose.
Manually stopping the server, like with `hl.stop()` would solve the issue since the JVM would exit and spark would note that the job was complete after the python process exited as well.
We once again create a thread that itself starts the http server, and then start that thread in `pyHttpServer`.
This should solve the hanging in dataproc that bisection showed was …
=> [query] Daemonize Py4JQueryDriver http server

batch/batch/cloud/gcp/driver/create_instance.py
Fixes https://github.com/hail-is/hail-security/issues/50
Enables shielded boot when creating worker VMs
=> [batch] Shielded boot for worker vms

hail/hail/src/is/hail/HailContext.scala, hail/hail/src/is/hail/linalg/BlockMatrix.scala
Moves `BlockMatrix` read functionality from `HailContext` into `BlockMatrix.scala`. 
=> [query] move block matrix read out of `HailContext`

hail/hail/src/is/hail/services/BatchClient.scala, hail/hail/test/src/is/hail/services/BatchClientSuite.scala
=> [query] fix job group state polling

hail/Makefile, hail/python/hailtop/hailctl/dataproc/start.py
=> [query] Use list for pip_dependencies in deploy.yaml
